### ISSUE TITLE
Flow types for React Router

### ISSUE THREAD

**Issue by TheSisb** [ReactTraining/react-router#3193]
I've been using and loving Flow in my current work project.  I'm trying to incorporate it into all the things.  

A new 'flow-typed' repo opened up (https://github.com/flowtype/flow-typed) similar to Typescript's DefinitelyTyped repo.  Was wondering if anyone wanted to make or already had a definition file for react-router to contribute before I'm forced to build my own.

As the main routing library in react, it would be nice to have this.

**Comment by taion** [comment]
I feel like we'd be better off having our Flow definitions in this repo, if applicable, and actually using Flow.

I recall that Redux used Flow at one point, but I see that it got stripped out. @reactjs/redux: what were the issues there?

**Comment by timdorr** [comment]
Would this cause any issues with Typescript users? I know they have a similar central repo of type mappings for various libraries, but I'm not a user, so I don't know how these things interact.

**Comment by taion** [comment]
I don't think so. Flow bindings go under `src/`, but they're stripped out of the transpiled code. Can you find commit/discussion where Flow types were stripped from Redux though?

**Comment by timdorr** [comment]
https://github.com/reactjs/redux/pull/299

**Comment by timdorr** [comment]
Given the similarities between Flow and TypeScript, does anyone know if there's a way to generate support for both via one set of annotations?

**Comment by taion** [comment]
You should bring that question up on the Flow types repo.

It looks like the concerns there are about not wanting to offer a public API with respect to Flow types. Given that the whole idea of adding type annotations would be to offer a public API, I don't think those concerns are relevant here.

cc @gaearon

**Comment by iktakahiro** [comment]
I didn't know Flow types. However, I think [typings](https://github.com/typings/typings) is the most major tool as a type-definition manager.

[TSD](https://github.com/DefinitelyTyped/tsd/blob/master/README.md#tsd) was de-fact until recently, but no longer active.

We had better manage type-definition using typings.

**Comment by chrisrittelmeyer** [comment]
+1 for submitting flow definitions to the flow-typed repo.

**Comment by MoOx** [comment]
Meanwhile you can use `iflow-react-router` https://stackoverflow.com/questions/37513785/flow-react-router-required-module-not-found/37622770#37622770

**Comment by timdorr** [comment]
Looks like there's a PR for this at flowtype/flow-typed#284

**Comment by 0xcaff** [comment]
It looks like the [react-router-dom](https://github.com/flowtype/flow-typed/tree/master/definitions/npm/react-router-dom_v4.x.x), [react-router-native](https://github.com/flowtype/flow-typed/tree/master/definitions/npm/react-router-native_v4.x.x) and [react-router](https://github.com/flowtype/flow-typed/tree/master/definitions/npm/react-router_v4.x.x) all have flow typings now.
