### ISSUE TITLE
Provide hooks for injecting additional data into onEnter hooks

### ISSUE THREAD

**Issue by taion** [ReactTraining/react-router#3404]
I don't have a proposal for an API here. Just thinking out loud – it might be nice if in addition to the current render middleware hook, we had a way to inject additional properties into `nextState` used on `onEnter` hooks.

This lets people move stuff like injecting Redux state or a Relay environment into the library level. Users can accomplish this right now by closing over those values in creating routes, but I think the API would be cleaner if there were a hook to add those values onto the `nextState` argument to the `onEnter` hook.

**Comment by deser** [comment]
Let me jump in with question concerning  `router.setRouteLeaveHook(route, this.routerWillLeave)`. I believe that for consistency (with reacttouer 0.13.x) reasons function `this.routerWillLeave` should have ability to be asynchronous. And this would be nice feature to have in my opinion. For example I want to send asynchronous request to server and wait until response before leaving current route.

**Comment by taion** [comment]
That's disallowed by design for compatibility with "before unload" listeners.

Separately, this issue is talking about `onEnter` hooks, which unlike route leave hooks do not have natural access to React context.

**Comment by maspwr** [comment]
> That's disallowed by design for compatibility with "before unload" listeners.

@taion I've recently been searching through the docs and issues trying to understand why the callback parameter wasn't exposed by `setRouteLeaveHook`. The library could [pass the callback to the hook](https://github.com/reactjs/react-router/blob/8707d05b00273590e4d054771b8ae7ae9ad312e3/modules/createTransitionManager.js#L148) if the hook expected it, and the [`beforeUnloadHook`](https://github.com/reactjs/react-router/blob/8707d05b00273590e4d054771b8ae7ae9ad312e3/modules/createTransitionManager.js#L166) could stay as it is. The user's hook function could then behave differently based on whether `(nextLocation, callback)` is supplied (the `listenBefore` case) or not (the `listenBeforeUnload` case). But your comment above sounds like this would have some kind of unwanted side-effect. Can you please explain?

Apologies for continuing an unrelated discussion on this issue, but I wanted to respond to your comment.

**Comment by taion** [comment]
If you want to talk about async route leave hooks, please use https://github.com/reactjs/react-router/issues/3406. This issue is about providing extra state for `onEnter` hooks.

**Comment by deser** [comment]
So please reopen #3406

**Comment by perrin4869** [comment]
`onEnter` gets a `nextState` of the router as an argument, but is there a way to access the current state? It seems `onEnter` doesn't have access to the `router` object...

**Comment by timdorr** [comment]
You probably want `onChange`. It doesn't make sense to pass the "current" state into `onEnter` because at that point we've already left the previous route and have committed to loading the next one.

**Comment by taion** [comment]
To be clear, this isn't talking about _router_ state. This is talking about injecting stuff like the Redux store or the Relay environment, to make it easier to interact with those, rather than e.g. having to close over those in your route definition.

**Comment by taion** [comment]
That's one of the big reasons why Router 1.x uses an `onEnter` hook on the route rather than a static hook on the route component – to allow closing over the store... but that doesn't work super great with things like async loaded route configs... so let's try to do better.

**Comment by BerkeleyTrue** [comment]
How about something similar to react-redux's provider, a top level component that you pass in props which will be made available to onEnter/onLeave?

**Comment by baronswindle** [comment]
@BerkeleyTrue That's kind of what I have in mind, but I reckon we wouldn't need to create a new component. Instead, we could just use the `<Router>` component. Any non-standard props passed to the `<Router>` component would then be passed into the hooks.

```
<Router
  routes={routes}
  history={browserHistory}
  /* props below are arbitrary and will be passed into enter/leave/change hooks */
  store={store}
  dispatch={store.dispatch}
/>

const routes = (
  <Route component={App} path="/">
    <Route path="groups" component={Groups} />
    <Route path="users" component={Users} onEnter={checkAuth} />
  </Route>
);

function checkAuth({ nextState, replace, store, dispatch }, executeTransition) {
  return dispatch(someAuthAction()).then(executeTransition);
}
```

Of course, this would be a breaking change. That said, because the behavior around enter/leave/change hooks depends on the arity of the hooks, I reckon it'd be tough to make this change without breaking changes. I suppose we could make this opt-in on a route-by-route basis and deprecate the old approach. This way, you'll only use the new hook signature if you specify a prop on the route component (e.g., `<Route path="users" component={Users} onEnter={checkAuth} newHooks={true} />`). We could then deprecate enter/leave/change hooks with an invalid number of arguments. I think this is a really messy approach though.

Any thoughts, @taion?

**Comment by klarezz** [comment]
Could you please explain why this issue has been closed? has it been implemented in v4? could you please provide a link? Thanks!

**Comment by klarezz** [comment]
I think I have found the answer: [link](https://github.com/ReactTraining/react-router/tree/v4#what-about-route-transition-hooks-example-needed)

**Comment by BigPrimeNumbers** [comment]
I don't quite follow @klarezz; did that doc specify how to do this? To inject some information I get from a Store by adding it to the nextState.params object in onEnter, but this feels a bit hacky.
