### ISSUE TITLE
Async onEnter hook can lead to inconsistent state

### ISSUE THREAD

**Issue by hoschi** [ReactTraining/react-router#3476]
## Version
2.4.0

## Test Case
http://codepen.io/hoschi/pen/wGbZWo?editors=0010

## Steps to reproduce

* click on "Users" link, shows still "Home"
* click on "Widgets" link, shows Widgets component
* wait

## Expected Behavior
* Widgets component stays visible
* url is still "/widgets"

## Actual Behavior
* Users component shows up
* url is *still* "/widgets", which doesn't match the component on the screen

## Description

The example has an `onEnter` hook which calls the `callback` after two seconds. When you move away from the "Users" route to "Widgets" all works fine. After the delay finishes you get an inconsistent state, as described above.

I think the problem lies in async management of hooks, where waiting callbacks should be dismissed on a location change.

**Comment by alisd23** [comment]
Should be fixed in #4063
