### ISSUE TITLE
Make it easy for people to run the website

### ISSUE THREAD

**Issue by mjackson** [ReactTraining/react-router#3817]
Not even our good friend @jlongster [could figure it out](https://github.com/ReactTraining/react-router/pull/3814)! 😆 

The way I see it, there are a few options:

1. add everything inside `website/package.json` to `devDependencies` in the root (probably easiest)
1. do a `cd website && npm install` as part of `npm start` (not ideal, would take extra time to boot the server)
1. put everything in a separate repo and deploy the site separately (not ideal, code and site would need to be versioned separately)

**Comment by timdorr** [comment]
Maybe use Create React App? 😄

**Comment by ryanflorence** [comment]
I busted the website right before release 🙄 will fix soon, but Tim is right, use create react app and then copy/paste any example into App.js.

**Comment by jlongster** [comment]
fwiw, I did try to get it working! I did `npm install` from the website directory and `npm start` but `http://localhost:9000` just showed me a blank page.

**Comment by ryanflorence** [comment]
Yeah I busted it right before release and then just went ahead and released.

**Comment by jlongster** [comment]
No worries at all! Thanks for continuing to work on this project.

**Comment by mjackson** [comment]
OK the site works for now. I'd like to build the site statically inside of our `docs` directory and just serve it via GH pages. Working on that now.

**Comment by threepointone** [comment]
related - started work on my fork on a CONTRIBUTING.md file https://github.com/threepointone/react-router/blob/v4/CONTRIBUTING.md

**Comment by threepointone** [comment]
whoops, looks like there's a previous one? I'll edit this to be closer to the original one soon.

**Comment by timdorr** [comment]
Fixed in 640ddf35e.
