### ISSUE TITLE
[v4] npmcdn link for v4 doesn't work

### ISSUE THREAD

**Issue by modernserf** [ReactTraining/react-router#3835]
`<script src="https://npmcdn.com/react-router/4.0.0"></script>` is a lie! This is making reporting a _different_ bug difficult 😉

**Comment by threepointone** [comment]
try `<script src="https://npmcdn.com/react-router@next"></script>`

**Comment by threepointone** [comment]
rather `<script src="https://unpkg.com/react-router@next"></script>`

**Comment by modernserf** [comment]
This is a commonjs build

**Comment by threepointone** [comment]
right you are, my bad! try this? - `https://unpkg.com/react-router@4.0.0-2/umd/react-router.js`

**Comment by threepointone** [comment]
looks like the readme now points to the correct location. closing this, thanks for reporting!
