### ISSUE TITLE
[v4] Match group can't be direct child of router

### ISSUE THREAD

**Issue by modernserf** [ReactTraining/react-router#3836]
## Version
4.0.0-2

## Test Case

This works:

```
<HashRouter>
      <div>
          <Match pattern="/foo" component={() => <div>FOO</div>} />
          <Miss component={() => <div>BAR</div>} />
      </div>
</HashRouter>
```

This doesn't:

```
<HashRouter>
      <Match pattern="/foo" component={() => <div>FOO</div>} />
      <Miss component={() => <div>BAR</div>} />
</HashRouter>
```

## Expected Behavior
route matches

## Actual Behavior
`Uncaught Invariant Violation: MatchProvider.render(): A valid React element (or null) must be returned. You may have returned undefined, an array or some other invalid object.`

**Comment by modernserf** [comment]
same as #3837.

**Comment by threepointone** [comment]
The Router needs to have a single child, so you could wrap the children with a div like so 
```jsx
<Router>
    <div>
      <Match pattern="/foo" component={() => <div>FOO</div>} />
      <Miss component={() => <div>BAR</div>} />
    </div>
  </Router>
```

we should probably have better dx/warning for the above.

**Comment by SimonPuckey** [comment]
Couldn't this be enforced within the BrowserRouter component?

**Comment by steida** [comment]
It's already fixed.

**Comment by SimonPuckey** [comment]
Yeah just saw on the duplicate issue. Thanks
