### ISSUE TITLE
[v4] MatchProvider.render() fails to return valid react element

### ISSUE THREAD

**Issue by kennetpostigo** [ReactTraining/react-router#3837]
Taking v4.0.0-2 for a spin after checking out the website. But I keep running into this error:
<img width="660" alt="screen shot 2016-09-14 at 2 11 55 am" src="https://cloud.githubusercontent.com/assets/8888991/18501760/ba6134c8-7a20-11e6-85d3-c9025fc3a330.png">

I thought that perhaps one of my components were what was causing the issue but I went through all of them and could not find any reason in my components but still same error. So then I removed `<Navbar />` component and all `<Match />` components  except for the first one that uses the pattern `'/'` and it worked. But As soon as I add one more to the mix it fails. So I thought okay what If I add another <Match /> that renders the same `HomeContainer` component. Again it still failed to render.

Heres the code that __fails__:
```js
import React from 'react';
import Router from 'react-router/BrowserRouter'
import Match from 'react-router/Match'
import Miss from 'react-router/Miss'
// other components...

render(
  (
    <Provider store={store}>
      <Router>
        <Navbar isAuthenticated={true}/>

        <Match exactly pattern='/' component={HomeContainer}/>
        <Match pattern='/:username' component={ProfileContainer} />
        <Match pattern='/:username/:repo' component={RepoContainer} />
        <Match pattern='studio' component={StudioContainer} />
        <Miss component={NotFound} />
      </Router>
    </Provider>
  ), document.getElementById('app')
);
```

This code below __works__:
```js
import React from 'react';
import Router from 'react-router/BrowserRouter'
import Match from 'react-router/Match'
import Miss from 'react-router/Miss'
// other components...

render(
  (
    <Provider store={store}>
      <Router>
        <Match exactly pattern='/' component={HomeContainer}/>
      </Router>
    </Provider>
  ), document.getElementById('app')
);
```

This code also __fails__:
```js
import React from 'react';
import Router from 'react-router/BrowserRouter'
import Match from 'react-router/Match'
import Miss from 'react-router/Miss'
// other components...

render(
  (
    <Provider store={store}>
      <Router>
        <Match exactly pattern='/' component={HomeContainer}/>
        <Match pattern='/lol' component={HomeContainer} />
      </Router>
    </Provider>
  ), document.getElementById('app')
);
```

I've tried to follow along with the website but can't seem to find a fix.

**Comment by threepointone** [comment]
The router needs to have just one child. Try wrapping the children with a `div` like so  -
```jsx
  <Router>
    <div>
      <Match exactly pattern='/' component={HomeContainer}/>
      <Match pattern='/lol' component={HomeContainer} />
    </div>
  </Router>
```

**Comment by kennetpostigo** [comment]
@threepointone thank you!

**Comment by WishCow** [comment]
I just run into this, the docs seem to suggest (incorrectly) that multiple children can be there:

https://react-router-website-xvufzcovng.now.sh/quick-start

(also, there is an overflow: hidden on one of the top wrapper elements, so the docs are not scrollable)

**Comment by timdorr** [comment]
This is fixed in #3849. Whenever Ryan can update the site, it'll have a `<div>` wrapper.

**Comment by aaugustin** [comment]
Indeed, this isn't obvious at all, especially given the claim that "if you know React you can use React Router". Regular React components don't have this restriction. Any chance it could be lifted, perhaps just by adding the <div> automatically if it isn't there?

**Comment by aaugustin** [comment]
Another related pitfall: if you have a container component whose render method is merely:

```javascript
render = () => (this.props.children)
```

**Comment by mjackson** [comment]
@aaugustin It's definitely a deviation from React's DOM components, which all (I think?) accept multiple children. But it's actually not uncommon for compound components. In fact, there even exists a special method, [`React.Children.only`](https://facebook.github.io/react/docs/top-level-api.html#react.children.only), specifically for the case of compound components that only accept a single child. I'm going to amend the code to use it here so people aren't surprised.

**Comment by steida** [comment]
@mjackson https://github.com/yahoo/react-intl/blob/master/src/components/provider.js#L173

**Comment by SamuelMaxwell** [comment]
@aaugustin How can you do the props.chidren method you mentioned in v4?

**Comment by aaugustin** [comment]
For example:

```
class GATracking extends React.Component {

    static propTypes = {
        children: PropTypes.node.isRequired,
    }

    static contextTypes = {
        location: locationPropType.isRequired,
    }

    componentDidUpdate(prevProps, prevState, prevContext) {
        const {location} = this.context
        if (location !== prevContext.location) {
            // Set the tracker to the current page so it is set for other events
            // See: https://developers.google.com/analytics/devguides/collection/analyticsjs/single-page-applications
            typeof window.ga === 'function' && window.ga('set', 'page', location.pathname + location.search)
            // Signal page view
            typeof window.ga === 'function' && window.ga('send', 'pageview')
        }
    }

    render() {
        return this.props.children
    }
}
```
