### ISSUE TITLE
Basename is not used in createHref

### ISSUE THREAD

**Issue by jochenberger** [ReactTraining/react-router#3839]
I use a `basename` in my router setup. In one of my components I have a `Link to="/"`. The `href` attribute points to `http://${hostname}/` instead of `http://${hostname}/${contextPath}`. The click handler works fine though.

**Comment by timdorr** [comment]
Pass it in as a prop to BrowserRouter or HashRouter.

**Comment by jochenberger** [comment]
I'm doing that, but it seems to be ignored for the `href`.

**Comment by timdorr** [comment]
I'll double-check when I'm at a computer, but it's got tests at least: github.com/ReactTraining/react-history/commit/b61ae2c362a34fe6545b24f5f06c77d23ab050b7

**Comment by jochenberger** [comment]
I do about this:
```jsx
<Router basename='/foo'}>
  <Match exactly pattern="/" render={()=><Link to="/">Index</Link>} />
</Router>
```
The link renders as `<a href="/">` but I expect it to render as as `<a href="/foo">`.

**Comment by chentsulin** [comment]
My comments in #3843: https://github.com/ReactTraining/react-router/pull/3843#issuecomment-247028856

**Comment by timdorr** [comment]
@chentsulin
> It seems that history is no longer responsible for creating hrefs. See mjackson/history#365 (comment)
>
> And Link component just use router.createHref to create hrefs, so miss the basename: https://github.com/ReactTraining/react-router/blob/v4/modules/Link.js#L91

 Ah, shazbot. Well, that's a little confusing as to who should be responsible then? Let me see what the thought process is on that and we can either re-open that PR or integrate the ideas in a more clear API. I feel like history should be aware of it, but we'll see if that stops at react-history or not. 

Either way, thanks for this issue!

**Comment by mjackson** [comment]
Just to clarify where responsibilities are: history has no knowledge of queries, so router is responsible for creating hrefs. It *does* know about basenames, but all `location`s you get in the `history.listen` callback already have properly-truncated `pathname`s.

**Comment by timdorr** [comment]
Started a fix over in #3858. Need to do the latter part of what @mjackson said.

**Comment by jochenberger** [comment]
Now I'm confused. Consider the following:
```jsx
<Router basename='/foo'>
  ...
  <Link to={"bar"} /> // renders `href='/foo/bar'` but transitions to "/foobar"
  <Link to={"/bar"} /> // renders `href='/bar'` but transitions to "/foo/bar"
  ...
</Router>
```

**Comment by timdorr** [comment]
@jochenberger That is not how it should end up behaving. This area of the code should be considered "in progress".

**Comment by jochenberger** [comment]
Yes, I thought so, that's why I let you know. ;-)

**Comment by mjackson** [comment]
I'm looking into this today.

**Comment by indeyets** [comment]
I see similar issue on react-router@2. should I open separate issue?

**Comment by nibblesnbits** [comment]
Is there any progress on this?  I've noticed that the behavior for this in the `4.0.0-alpha.4` package is incorrect.  The docs reflect this as well.

```
basename

The base URL for all locations. If your app is served from a sub-directory on your server, you’ll want to set this to the sub-directory.

<HashRouter basename="/calendar" />

// now links like this:
<Link to="/today"/>
// will generate links with an href to "#/calendar/today"
```
That last comment is the issue.  If my application exists at `http://example.com/calendar/`, then what should be generated is a link to `/calendar/#/today`, not `#/calendar/today`.  As it stands now, the actual behavior is as documented.

**Comment by pshrmn** [comment]
@nibblesnbits If your app exists at `http://example.com/calendar/`, then a link within your app to `#/today` _is_ a link to `http://example.com/calendar/#/today`, no basename is necessary.

Basenames are used to change the root url (location of `/`). Everything before the root doesn't matter to RR. For the `<HashRouter>`, `#/` is the root url, so `http://example.com/calendar/` doesn't matter.

**Comment by patotoma** [comment]
Hey @pshrmn, basename is required for that /calendar thing because it is a subdirectory and not the actual root of the webserver.

**Comment by ryanflorence** [comment]
07725d7ef566a9a4bcfcf91b1f0816dd1f546393 fixes this? let me know if it doesn't and we'll reopen.

**Comment by patotoma** [comment]
Hello @ryanflorence, sorry for a stupid question but how can I try this thing out? Is it already merged and published on npm? I found that this was merged a month ago but I experienced these issues a few days ago so in that case this commit wasnt helpful. Thanks in advance.

**Comment by nibblesnbits** [comment]
@patotoma, the easiest way I know of is to `npm link` from the repo.

1. Download the repo, and `npm install` its dependencies.
2. `npm link` the package so that you can use it from other projects on that machine.
2. `npm install` the version of `react-router` that you `link`ed in you project and test as needed.
