### ISSUE TITLE
[website] the content is not fully visible in Firefox

### ISSUE THREAD

**Issue by stof** [ReactTraining/react-router#3840]
The website has an ``overflow: auto`` on the ``<pre>`` tag to allow scrolling to the end of the code-block.
However, in Firefox, the overflow happens on a parent element (the one with styles ``flex: 1 1 0%; flex-direction: row; display: flex;``), meaning it is impossible to scroll to see the end of the code

**Comment by stof** [comment]
note that adding ``overflow: auto`` on this parent element seems to achieved the right behavior (the scroll happens on the ``<pre>`` only)

**Comment by stof** [comment]
adding ``min-height: 0`` on this div also fixes the issue

**Comment by timdorr** [comment]
Already fixed in #3814. It just needs to be republished, which Ryan needs to do.
