### ISSUE TITLE
Component Not re rendering Based on the Param change

### ISSUE THREAD

**Issue by sajumani** [ReactTraining/react-router#3844]
Hi,

Am facing one big problem,

<Route path="user/:userId" />

when i visiting route with http://localhost:8080/#/user/22 , it working for first time with any user id

after changes param, component not getting rendering .. it seem same

**Comment by sajumani** [comment]
i used, 'react-router-redux' to update params in the state.
then ,
componentWillReceiveProps(nextProps) {
		
		if(nextProps.userId != this.props.userId )
			this.props.getLists(5);
}

It works for me but Is this correct ???

**Comment by timdorr** [comment]
Correct. You need to use cWRP because the component itself will not change, just the props it receives.

**Comment by li2274221** [comment]
thx for your solution.
And I write this as a Decorator function:
```
const routeStateChnageToReload = (...states) => {
	return target => {
		const oldDidMount = target.prototype.componentDidMount;
		const oldWillReceiveProps = target.prototype.componentWillReceiveProps;

		target.prototype.componentWillReceiveProps = function(nextProps) {
			const changed = Boolean(states.find(state => {
				return this.props.routeParams[state] !== nextProps.routeParams[state];
			}));
			if (changed) {
				oldDidMount && oldDidMount.call(this);
			}
			oldWillReceiveProps && oldWillReceiveProps.call(this, nextProps);
		};
	};
};
```
then I can use it at any components I need:
```
@routeStateChnageToReload('stateName') 
export default class OrderList extends React.Component {
    componentDidMount() {
        this.props.getLists(5);
    }
}
```

**Comment by ryanflorence** [comment]
eh ... alternatively you can put a "key" on the component

```js
// in your parent component where you have
{this.props.children}

// switch it to
{React.cloneElement(this.props.children, { key: location.pathname }}
```

And you'll get an unmount/remount w/o messing w/ class prototypes 🙈
