### ISSUE TITLE
Add support of Promises for getComponent(s), getChildRoutes, getIndexRoute

### ISSUE THREAD

**Issue by kirill-konshin** [ReactTraining/react-router#3850]
It would be very useful if async methods like `getComponent(s)`, `getChildRoutes`, `getIndexRoute` will be able to support promises, for example with https://github.com/gaearon/promise-loader route definitions could be very small and elegant:

```js
{
    getChildRoutes: require('promise?global!./path/to/route') // when called returns a promise
}
```

Currently it does not look so good:

```js
{
    getChildRoutes: (partial, cb) => {
        require('promise?global,route-feed!./routes/feed')().then(cb.bind(null, null)); // this is needed for cb(null, file);
    }
}
```

**Comment by timdorr** [comment]
Already added in #3719. It's not published on the 3.0 alphas yet, but it's coming.

**Comment by kirill-konshin** [comment]
Any chance to get this in 2.x too?

**Comment by timdorr** [comment]
Nope, it'll be in 3.0, which is just the current version with deprecation warnings removed.
