### ISSUE TITLE
Link isn't active when partial match

### ISSUE THREAD

**Issue by kennetpostigo** [ReactTraining/react-router#3853]
Working with `<Link />` on a nested views that is 3 levels deep. We have tabs that are are styled differently based on whether they are active and we are using `activeClassName` to do this. However say im on `/user/steven` the active link is the "index" and its tab is styled as it should be. However if I hit the comments tab that transitions to `/user/steven/comments` the comments tab activeClass is turned on but the default "index" tab remains on. Prior to v4 I mitigated this using `<IndexLink />`. Im on the v4 site and the API section says there `<Link />` has only `to, activeClassName, activeStyle ` as props. How should I handle preventing the "index" from being active when its nested routes are also on in v4 of react-router?

**Comment by timdorr** [comment]
So, [we have this code to handle partial or exact matches](https://github.com/ReactTraining/react-router/blob/v4/modules/Link.js#L30-L39) (new feature!) and [there is a test for this](https://github.com/ReactTraining/react-router/blob/v4/modules/__tests__/Link-test.js#L208-L236). Is there a difference in how your code is set up from that example? It should work.

**Comment by kennetpostigo** [comment]
@timdorr Thanks for the link! Wasn't aware or this :)
