### ISSUE TITLE
[v4] onEnter and onChange hooks

### ISSUE THREAD

**Issue by olegafx** [ReactTraining/react-router#3854]
How could we replace `onEnter` and `onChange` route hooks?

I found only 1 solution: additional `<Match/>` with a custom component.
This component could use something like `componentWillReceiveProps` to emulate `onChange`.
But what about `onEnter`? We have no lifecycle hooks that receive props on initial render.

Nice work, btw.

**Comment by mjackson** [comment]
Thanks :)

> We have no lifecycle hooks that receive props on initial render.

We no longer have a "route lifecycle". Instead, since `<Match>` components are *real* components (not pseudo-components like `<Route>`s were) they get to participate in React's lifecycle, which means they can just use `componentWillMount`.

**Comment by corydeppen** [comment]
As someone who is very new to React, I'm trying to understand if the recommended approach is to have the component being rendered with `Match` (e.g. `/items`) implement `componentWillMount` and possibly set data on `state` instead of getting data passed via props. Or how might a table row containing a link to the item details be rendered with `Match` (e.g. `/items/:id`) - seems that wouldn't be able to have the item passed to it via props if I understand how the router works.

I appreciate any guidance.

**Comment by mbrevda** [comment]
Here is an example: https://react-router.now.sh/auth-workflow

**Comment by dtipson** [comment]
Been looking over that example, but I think I'm not understanding how that works when it's asynchronous. If, say, `/items/:id` requires a network call to retrieve, how would the navigation transition get blocked until the response comes back and there's something new to display?  I'd prefer not to have every page display have to have a componentWillMount empty state, if that makes sense.

It looks like there was an example that sort of went in documenting this kind of direction where the Router becomes slave to Redux, and navigations are all handled in there, but it's not part of the playground yet: https://github.com/ReactTraining/react-router/blob/7f6706dab4827afc1c26a58418f8ef8c8ab40125/website/examples/Redux.js

Is there a non-redux pattern?

**Comment by MathieuLorber** [comment]
Hello. I still don't understand how I'm supposed to replace onEnter with router v4. componentWill/DidMount seem "technical" hooks linked to dom lifecycle. With a route /view/:id, if I switch from /view/1 to /view/2, the same ViewComponent will be used, and componentDidMount() will not be called between the two different routes. If I'm fetching data using the :id, how I am suppose to do without an onEnter ?
(besides this problem, I'm very seduced by the rest of the API ftm =). I _particularly_ appreciate the login redirect solution, often wanted smthg like this with old single page apps)

**Comment by MathieuLorber** [comment]
Hello. I still don't understand how I'm supposed to replace onEnter with router v4. componentWill/DidMount seem "technical" hooks linked to dom lifecycle. With a route /view/:id, if I switch from /view/1 to /view/2, the same ViewComponent will be used, and componentDidMount() will not be called between the two different routes. If I'm fetching data using the :id, how I am suppose to do without an onEnter ?
(besides this problem, I'm very seduced by the rest of the API ftm =). I particularly appreciate the login redirect solution, often wanted smthg like this with old single page apps)

**Comment by MathieuLorber** [comment]
I was thinking of using Route.render(), but I'm not sure to really understand when it can be called. It could result in useless fetching calls =/

**Comment by pshrmn** [comment]
@MathieuLorber `componentWillReceiveProps`

**Comment by MathieuLorber** [comment]
Sure, but the whole lifecycle of the component can be called for several reasons (any change in the app state). With componentWillReceiveProps, I have to check that the changed prop is the one which interests me for fetching. Or maybe by creating a dedicated wrapper component with no other props. Still, doesn't it sound a bit verbose ?

**Comment by pshrmn** [comment]
v4 is all about routes just being components. That means taking advantage of lifecycle methods.

```js
componentWillMount() { // or componentDidMount
  fetch(this.props.match.params.id)
}

componentWillReceiveProps(nextProps) { // or componentDidUpdate
  if (nextProps.match.params.id !== this.props.match.params.id) {
    fetch(nextProps.match.params.id)
  }
}
```

**Comment by MathieuLorber** [comment]
Hmm I still must be missing something. Your proposition works in a component inside the Route, not in a component extending Route (componentWillReceiveProps is never called).

So I still need a dedicated wrapper component. And this solution is a lot more verbose + a lot more bug prone.

For the moment, using Route.render() is my best candidate. Code is there : https://gist.github.com/MathieuLorber/61ee584e375c41cd60038a11a9bf437b

**Comment by pshrmn** [comment]
What is the purpose of your `<MyRoute>` component?

**Comment by MathieuLorber** [comment]
Well, I wanted to take advantage of lifecycle methods =]

**Comment by pshrmn** [comment]
The lifecycle methods should be on the component that is rendered by the `<Route>`. A `<Route>` is just there to match its `path` against the current `location.pathname`.

**Comment by MathieuLorber** [comment]
Ok.

And using Route.render() for that purpose sounds like a good idea or not ?

**Comment by pshrmn** [comment]
I'm afraid I don't understand the question. Can you ask over on Reactiflux? This has turned into a bit of a conversation which would be more appropriate to have on an actual chat app :smile:.

**Comment by mandalatv** [comment]
I have a similar need to what @MathieuLorber had (thanks for posting your code, BTW). In React Router v3, I had a function that updated a store with location data on onChange() and onEnter() hooks. This saved me the trouble of writing redundant code in each Route Component's respective componentWillMount().

The best v4 equivalents I've found so far are to either make a separate component that only exists to listen to changes and update a store (envisioning something like the [withRouter example] (https://reacttraining.com/react-router/web/api/withRouter)
) or to do what @MathieuLorber has done.

**Comment by oallouch** [comment]
I put my onEnter functions next to my actions factories. This way, all data fetching is at the same place.
So, for me, it's better to stick with v3.

**Comment by bmanturner** [comment]
Is this really something you wouldn't be willing to add to BrowserRouter? I think it's the only thing keeping us back.

**Comment by FredericHeem** [comment]
Unfortunately, `onEnter` is one of the reasons why my project is stuck with v3.

**Comment by gvidon** [comment]
I have a tree of deeply nested routes. Before the transition to one of them I need to fetch the data, and behave just like Github does — change url while keeping current render state, show non-blocking progress bar line in the top and then when data fetched do the actual transition.

It was pretty simple with `[onEnter]`, because being passed with callback it blocks transition, which freeze current render state.

But now I can't find the way to prevent transition in order to wait for some job to be done. `component*` life cycle methods don't work for me as routes are deeply nested and calling life cycle methods will mean previous render state was dropped and new render started even before some background job is done.

What am I doing wrong? Thanks!

**Comment by gvidon** [comment]
By the way, I'm using react-router with redux and the only way I can see so far is writing redux middleware for every app module which has components performing data fetching. Obviously I don't like it.

**Comment by wzuo** [comment]
I am using v4, and I need to redirect to index page when user is logged in, so I decided to create temporary (hopefully..) fix to it.

Snippet:
https://gist.github.com/wzuo/e9c18132c94b5494a3156b2a2e6e57f6

`onEnter` function have to return redirect path if browser need to be redirected, otherwise have to return `null`. Also, feel free to modify it - I am getting expression based on `state`

**Comment by gvidon** [comment]
@wzuo from what I see it would work for me if I had just single `Switch`. But in my situation it is like:
```
Route
  Switch
    Switch

Route

Route
  Switch
```

**Comment by gvidon** [comment]
I misunderstood how react-router-redux works, injecting middleware will not help. Clicking `Link` or `NavLink` will cause changing history and triggering routes. I still can't freeze rendered state.

**Comment by gsantiago** [comment]
React doesn't offer any lifecycle hook that is triggered once, right before the initial render.

How can I emulate the `onEnter` behavior with the lifecycle methods?

The solutions I have in my mind are too verbose, repetitious and ugly. I still can't see the advantage of removing `onEnter` and `onChange` hooks. They were so simple...

**Comment by MathieuLorber** [comment]
@gsantiago 
> React doesn't offer any lifecycle hook that is triggered once, right before the initial render.

It does actually, it's componentWillMount. But it's still not what you want. componentWillMount + componentWillReceiveProps will do the trick, but you indeed have to check the changes of matches.

**Comment by jamiehutber** [comment]
So @MathieuLorber so as everything in react-router is now a component it means that we'll need to make the calls to our auth logic inside of each routes components?

**Comment by oallouch** [comment]
@jamiehutber ...or stick with v3 :)

**Comment by jamiehutber** [comment]
Na, gotta move with the times :D I prefer it being on a component level. :p

**Comment by MathieuLorber** [comment]
@jamiehutber I'm not sure to understand, your auth logic works "the same". Yes, it has to be done in component lifecycle. But you still just need one component. Here is an example : https://gist.github.com/MathieuLorber/b9b257d306ef72bbd930cd609c7daa3f
(I'm not a react-router contributor, it's just my suggestion)

**Comment by DORRITO** [comment]
onEnter is beyond simple, any chance this change gets reverted?

**Comment by craftzdog** [comment]
I created a decorator that lets component check if authenticated on `componentWillMount` like:

```javascript
// check-authenticated.js
// @flow
import React from 'react'
import PropTypes from 'prop-types'
import type { State } from '../states'

export default function checkAuthenticated (Component: Object) {
  class AuthenticatedRoute extends React.Component {
    static contextTypes = {
      store: PropTypes.object,
      router: PropTypes.object
    }
    componentWillMount () {
      const { store, router: { history, route } } = this.context
      const { session }: State = store.getState()
      if (session.userId === null) {
        const { location: { pathname } } = route
        history.replace(`/?redirect=${pathname}`)
      }
    }

    render () {
      return React.createElement(
        Component,
        { ...this.props }
      )
    }

  }

  return AuthenticatedRoute
}
```

You can add the decorator to auth-required pages:

```javascript
// page.js
// @flow
import React, { Component } from 'react'
import checkAuthenticated from './check-authenticated'

@checkAuthenticated
export default class Page1 extends Component {
  render () {
    return (
      <h1>Hello</h1>
    )
  }
}
```

**Comment by santaclauze** [comment]
There is a neat example of an HoC to deal with the authorization avoiding the mutiplication of ComponentWillMount and ComponentWillReceiveProps:

https://medium.com/@francoisz/react-router-v4-unofficial-migration-guide-5a370b8905a

**Comment by brandonaaskov** [comment]
Well, now that I've been going through this migration for half of the day, I have to say: this is really fucking aggravating.

Lifecycle hooks like `componentWillMount` aren't blocking, so if you call an async method there, `render` will run before the response comes back. Not all apps are built with this in mind, and you're forcing anyone that wants to use v4 to make a  potentially _massive_ change to a codebase.

I don't understand why those hooks were dropped altogether. Plus, now the `Route`s are all over the place in the code, and I can't look at my entrypoint and understand the routing across the entire app.

The example that @mbrevda posted above (that's been thumbed down extensively) doesn't even leverage a single lifecycle hook: not a great example to say the least.

There are a handful of not-so-great solutions presented by others above, all wrapping `Route` or `Switch` in a way that should never have to be done.

There's mention in a few places of using the `render` prop on a `Route` component, but that still doesn't solve for the async scenario: if you don't return something immediately, it will throw an error.

If anyone, especially @mjackson or @mbrevda, can provide an example where a route makes an async request, and then redirects away from that component without rendering it, I'm sure we'd all be much happier for it. From what I can see thus far, it's not doable out-of-the-box.

![boo this man](https://user-images.githubusercontent.com/445778/27202504-ecbd8672-51ef-11e7-9113-674877e5eb73.gif)

**Comment by detj** [comment]
With v4, it seems I don't have much alternative to `onEnter`, either using the `render` method which must return a `null`. Again, I am not able to justify why one would put a data loading or some other _before_ side effect inside the `render` method. The other alternative is to use component lifecycle methods, but what if my components are stateless functional components and I do not intend to change them and introduce component lifecycle methods in them.
I like the way v4 has embraced components in routing parlance, this has made React Router a whole lot more easier to get onboarded with IMO, but there it feels there could be a better way?

Maybe I'm missing some point, please correct me If I'm wrong.

**Comment by detj** [comment]
@santaclauze The HOC approach is neat indeed. I guess, will have to stick to this going forward.

**Comment by oallouch** [comment]
I'm not worried. V3 works like a charm and @ryanflorence knows there are issues with async needs.

**Comment by detj** [comment]
@oallouch Okay. Good to know that. 👍

**Comment by moraleslos** [comment]
Been converting to v4 and this is the last issue I've encountered which I can't figure out a good fix for.  I had one route with an onEnter implementation that essentially would check the url to see if there was a particular hash and key in it.  If so that meant to redirect to another page since it was coming from an ad link.  OnEnter was perfect for checking conditions like this before rendering a component.  

The other suggestions about using componentWillMount and such is not good in our particular case since everything was built with stateless functional components.  Hopefully something like onEnter will be put back in v4-- apparently it's useful in many different cases just going off of this thread.

**Comment by dr3w** [comment]
I ended up writing this HOC. Works fine for my particular needs

```javascript
const withRouteOnEnter = callback => BaseComponent => {
  const routeOnEnterCallback = (props) => {
    if (callback && typeof callback === 'function') {
      callback(props)
    }
  }

  class routeOnEnterComponent extends React.Component {
    componentWillMount() {
      routeOnEnterCallback(this.props)
    }

    componentWillReceiveProps(nextProps) {
      // not 100% sure about using `locatoin.key` to distinguish between routes
      if (nextProps.location.key !== this.props.location.key) {
        routeOnEnterCallback(nextProps)
      }
    }

    render() {
      return <BaseComponent {...this.props} />
    }
  }

  return routeOnEnterComponent
}

...

const loadData = props => {
  fetchStuff(props.someId)
}

<Route path="/articles/:id" component={withRouteOnEnter(loadData)(ArticleViewContainer)} />

```

**Comment by MathieuLorber** [comment]
@dr3w this is very similar to what I'm doing. Suggesting a more generalist pattern in react-router documentation would probably be the best solution
(I wanted to work on a PR in this direction since several weeks but could take the time for the moment =s)

**Comment by kevr** [comment]
Let me get this straight. You would rather force a user to manually check, as opposed to using the deduction logic that onEnter provides? It doesn't make much sense to me. If something is asynchronous, now, instead of being able to rely on the data being available, we are forced to use a ternary render, and also checking for the data properly every step of the way?

It sounds like more runtime work, and it sounds like we just went back in time. Moving with the "times" is not necessarily relevant, when this is not a widely accepted standard at this point. Leaving this feature out, for almost no reason, is pretty disturbing for back-compatibility and flexibility.

**Comment by oallouch** [comment]
@kevr it's really only a matter of async Route preparation. Unfortunately, it's ALWAYS async :)

**Comment by stiff** [comment]
One possible workaround for this is to use redux connect:

```javascript
const mapDispatchToProps = (dispatch) => {

  /* this code executed once before rendering component */
  doSomePreparation().then((preparedData) => {
    dispatch(dataForComponentLoaded(preparedData));
  });

  return (dispatch) => ({});
}

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(SomeComponent);
```

**Comment by mjackson** [comment]
Sorry everyone, I had to lock the conversation on this issue because it's going nowhere. The short story is your routes are just components now. Use them like any other component. The router is not a framework.
