### ISSUE TITLE
4.0 Example Projects

### ISSUE THREAD

**Issue by peter-mouland** [ReactTraining/react-router#3856]
I know it's not released yet, but with v4 on the horizon I thought you might think about including links to repos that might help people upgrade.

The [react-lego](https://github.com/peter-mouland/react-lego) repo is a universal example app built for the sole purpose of showing people how to upgrade/add tech into react apps.

I've had positive feedback about the repo being helpful to see the code differences between versions and I have a section for [react-router v4](https://github.com/peter-mouland/react-lego/compare/react-router-4) (which also includes tests).

Is this something that interests you or are you keep to keep documents in-house?

**Comment by timdorr** [comment]
I think eventually having something similar to [Redux's ecosystem page](https://github.com/reactjs/redux/blob/master/docs/introduction/Ecosystem.md) would be good to have.

**Comment by mjackson** [comment]
We've historically published an upgrade guide with every major release of the router. If you're interested in helping out, I'd love to get started on one here in this repo. It should probably follow the style of [our existing upgrade guides](https://github.com/ReactTraining/react-router/tree/master/upgrade-guides).
