### ISSUE TITLE
Some pages in the docs website are not scrollable

### ISSUE THREAD

**Issue by jochenberger** [ReactTraining/react-router#3859]
See for example https://react-router-website-xvufzcovng.now.sh/Link. The inner `div` has `overflow: hidden` set, so the page content cannot be scrolled.

**Comment by timdorr** [comment]
Busted via #3814 😢

**Comment by timdorr** [comment]
BTW, while a bit out of date, the old version scrolls just fine: https://react-router-website-uxmsaeusnn.now.sh

**Comment by timdorr** [comment]
Fixed in e12f60765. Just need @ryanflorence to push a new website version at some point.

**Comment by abuisman** [comment]
Still not working.

**Comment by bravedick** [comment]
come on, i believe in you.

**Comment by timdorr** [comment]
This is fixed on the latest version. Use the latest link: https://react-router.now.sh/
