### ISSUE TITLE
useQueries.js:60 Uncaught TypeError: Cannot read property 'substring' of undefined

### ISSUE THREAD

**Issue by gilesbradshaw** [ReactTraining/react-router#3861]
## Version
2.8.1

## Test Case
sorry none
## Steps to reproduce
with the router provided by withRouter do router.push("your route")
once on the new route click the back button

## Expected Behavior
no error

## Actual Behavior
error in title is raised

nb this does not occur if I use an object as a parameter ie

````
  router.push({pathname,query})
````

**Comment by gilesbradshaw** [comment]
actually I lied it seems to be happening with the object form too

**Comment by timdorr** [comment]
What version of history are you using? What exact pathname are you attempting to `push`?

**Comment by timdorr** [comment]
Closing due to lack of a repro. Sounds like something might be messed up with your node_modules or an incorrectly installed version.
