### ISSUE TITLE
Coerce all <Link query> values to strings

### ISSUE THREAD

**Issue by jochenberger** [ReactTraining/react-router#3863]
On one of my pages, where I have a paging table, I store the page number as a query parameter. I use a number in the Link target, e.g. `<Link to={{query:{page:2}}}>Page 2</Link>`.
When the component re-renders after I click on the `Link`, `props.location.query.page` is a `number`. However, if I reload the page so that `window.location.search` is parsed again, `props.location.query.page` is a `string`.
In Router v2, query parameter values were always coerced to `string` btw.

**Comment by timdorr** [comment]
Well, href building/handling has been moved out of history back up to the router (where it really *should* live). It's a serialization problem, where URLs are insufficient to represent types. I'm not sure if we should get into the messiness of query string parsing. We're using query-string, but you can swap out for another library (qs is popular) with the `stringifyQuery` and `parseQuery` props.

**Comment by jochenberger** [comment]
That wouldn't help. The discrepancy is caused by the fact that router keeps the data type intact internally but does no coercion of the values that come out of the query parser. IMO, either it should be possible to specify data types for path/query params or, for thr sake of consistency, everything should be converted to strings internally.

**Comment by mjackson** [comment]
Since we consistently give you strings when we parse the query string, we should make sure that when you give us numbers in `<Link query>` we coerce them to strings.

**Comment by pshrmn** [comment]
From my understanding, this should also apply to `boolean` and `undefined` values.

`?x=true` will be parsed as `{x: 'true'}` and `?y` (where no value is defined) will be parsed as `{y: null}` as defined by [w3](https://www.w3.org/TR/2012/WD-url-20120524/#collect-url-parameters).

**Comment by jochenberger** [comment]
I wouldn't coerce `undefined` (see also #4064) but the other examples look fine to me.

**Comment by pshrmn** [comment]
@jochenberger I don't think that #4064 applies here because `path-to-regexp` doesn't do query parameters (see [note](https://github.com/pillarjs/path-to-regexp#usage)).

It does seem odd to coerce `undefined` to `null`, but I believe that it technically should be correct. That said, it seems that different query string parsing libraries handle keys with no value differently ([qs](https://github.com/ljharb/qs) treats keys with no value as empty strings unless you specify `strictNullHandling`), so not coercing isn't unreasonable.

**Comment by jochenberger** [comment]
#4064 is related because it is also about (not) coercing `undefined` to a string. The handling should be the same for query and for path params.

**Comment by ryanflorence** [comment]
where does this ever show up as a problem? Every time you read it from Router you're going to get strings, when would you define it as a number, and then try to access it and get a number instead of a string again?

**Comment by jochenberger** [comment]
The point is that I *don't* get strings. I'll try to write a test to make it clear.

**Comment by jochenberger** [comment]
See #4099

**Comment by pshrmn** [comment]
I've been going back and forth on this issue. I understand that as is, the values will be different, but I don't see what the harm is. If there is a number in the search string, you'll want to parse it to an int/float yourself in the match component, right? In that situation, it doesn't matter if the query object contains a number or a string.

There are also a number of edge cases where different query string parsing libraries handle things differently, so manual coercion may introduce bugs. If anything, I would say that the (ugly) solution of stringifying then parsing the query object using the `stringifyQueryString` and `parseQueryString` functions passed to `createRouterLocation` would be the "best" coercion strategy.

**Comment by jochenberger** [comment]
The "harm" is that things are not predictable the way they are.
About your different coercion strategy proposal: Yes, it's ugly, but it's probably *safe* and it's probably a better idea than what #4099 does. I can submit another PR and hopefully one of them can be merged.

**Comment by jochenberger** [comment]
Created #4106.
However, another "solution" occurred to me: It might be best to just throw (or at least warn in DEV) if a value in the query object is not null or a `string` and have the user deal with the type coercions in both directions.

**Comment by pshrmn** [comment]
That's probably best. I think that my reluctance to coercing is just because there are a number of edge cases, but if we want the `query` to replicate what it would be parsed as, using the provided functions should correctly replicate parsing from `window.location`.

**Comment by jochenberger** [comment]
> That's probably best.

What do you mean? #4106 or not accepting non-strings?

**Comment by pshrmn** [comment]
#4106. Makes it easier for users while also keeping `query` consistent.
