### ISSUE TITLE
React Router routing with express router routing

### ISSUE THREAD

**Issue by itphixl** [ReactTraining/react-router#3865]
Hi ! 

I'm currently working on an application who needs a server routing and a client routing for a specific route of the server router. 
In fact my server router severs a lots of different routes where one of them is a front end React application who has his own inner routing.

For example : 
  - (server route )  '/' : serves a single html page
  - (server route) '/app' : serves my React application
  - (client route) '/app/profile' : serves the page profile of my React application

This is my problem (I think it's more my lack of comprehension ) : 
When I use on my client routing hashHistory I've no problems it works well but I've (ugly) URLs with query keys and for the user this isn't friendly at all. 
And when I use on my client routing browserHistory (to have clean URLs) this don't work, react-router tells me "[react-router] Location "/app" did not match any routes". 

I think I missed something but I don't really know what :/

Is there a way to avoid using hashHistory ? 

Thanks a lot for your time and your help !

**Comment by timdorr** [comment]
You need to configure your express server correctly: https://github.com/ReactTraining/react-router/blob/master/docs/guides/Histories.md#configuring-your-server

**Comment by itphixl** [comment]
Oh I see ! Thanks a lot ! 

But in my routes definition of my client routing I must define : 
`var routes = {
  path: '/app',
  component: Root,
  childRoutes: [
    {path: 'user', component: User}
  ]
};`

for it works well right ? 

Thanks for your time ! :)
