### ISSUE TITLE
Missing BaseNameSuppport documentation

### ISSUE THREAD

**Issue by blazzy** [ReactTraining/react-router#3867]
There are two links to a [BasenameSupport.md](https://github.com/ReactTraining/history/blob/master/docs/BasenameSupport.md) document that doesn't exist. One from [API.md](https://github.com/ReactTraining/react-router/blob/master/docs/API.md) and another from [Histories.md](https://github.com/ReactTraining/react-router/blob/master/docs/guides/Histories.md).

**Comment by timdorr** [comment]
A PR is more helpful here. The v2.x branch has the doc: https://github.com/mjackson/history/blob/v2.x/docs/BasenameSupport.md
