### ISSUE TITLE
React router website, quick start page can't scroll

### ISSUE THREAD

**Issue by heldrida** [ReactTraining/react-router#3873]
React router website, quick start page can't scroll

https://react-router-website-xvufzcovng.now.sh/quick-start

**Comment by femesq** [comment]
Confirmed here (Chrome v53 on MacOS).

In `Inspector`, removing `height: 100%;` from `<div id="app">` solved the problem... 

Tested on Firefox and Safari, and both are working...

**Comment by katpas** [comment]
Looks like none of the pages scroll if you're using Chrome or Firefox. It's fine on Safari. I opened up the browser console and unticked the body height property which is set to 100%. Brought back the scroll bar.

**Comment by timdorr** [comment]
Dupe of #3859. Fixed in e12f607.
