### ISSUE TITLE
v4 - Is `history` and/or `react-history` necessary/recommended to install using the new `react-router` or not?

### ISSUE THREAD

**Issue by jferrettiboke** [ReactTraining/react-router#3876]
While the current [v4 README](https://github.com/ReactTraining/react-router/tree/v4) says `$ npm install --save react-router@next`, the current external [v4 docs](https://react-router-website-xvufzcovng.now.sh/quick-start) says `npm install react-router history`.

In addition, I saw in the `package.json`, you have installed `history` and `react-history`.

```
"dependencies": {
    "history": "^4.0.0",
    "path-to-regexp": "^1.5.3",
    "query-string": "4.2.3",
    "react-history": "^0.13.0"
  },
```

Is `history` and/or `react-history` necessary/recommended to install using the new `react-router` or not?

**Comment by timdorr** [comment]
You don't need to install history yourself. That doc can be updated. A PR would be great!
