### ISSUE TITLE
<Miss> and Server Side Rendering results in invalid checksum

### ISSUE THREAD

**Issue by jumoel** [ReactTraining/react-router#3877]
## Version
4.0.0-2 (e12f607)

## Test Case
https://github.com/jumoel/react-router-v4-ssr-miss-checksum-fail

## Steps to reproduce
Implement Server Side Rendering with a `<Miss>` component

## Expected Behavior
No checksum errors

## Actual Behavior
Checksum errors

![](https://i.imgur.com/S5B3M42.png)

---

I'd like to help out with the bug (if possible), but I haven't been able to figure out where to start.

**Comment by timdorr** [comment]
Does your server generate any errors during rendering?

**Comment by steida** [comment]
I confirm that, and no my server does not generate any errors during rendering.

**Comment by ryanflorence** [comment]
are you doing a two pass render with serverRenderContext?

**Comment by ryanflorence** [comment]
oh shoot I get it, I'll post some thoughts later, out and about right now

**Comment by steida** [comment]
Yes, I do.

**Comment by steida** [comment]
https://gist.github.com/steida/0627c405246f997dcc007a8cf17bc0f3

**Comment by alisd23** [comment]
So it seems like this a fundamental with the current `Miss` API, both client and server need to do **2** render passes to render a `Miss` component, so at the moment this warning is unavoidable as the client does not render the `Miss` on the first render.

It's still in alpha so I assume more discussion on the API design will happen, to address things like this. In my opinion there needs to be another way of rendering misses in **one pass**, otherwise server-rendered apps might have to avoid using v4 at all.

**Comment by ryanflorence** [comment]
I'd suggest not sending the JS at all on a 404 or not worry about the
repaint for now: it's an exceptional case, seems like an okay trade off
until we + React can't figure it out.

"our 404s repaint when JS loads, therefore we can't use this" seems a bit
of an extreme position 🙂

**Comment by alisd23** [comment]
Haha true, let's call it *non-optimal*

**Comment by ryanflorence** [comment]
"non-optimal in the exceptional case" 😜

Leaving this open until i write some docs about it

**Comment by michalwerner** [comment]
I've encountered the same warning in my case, which is:

- few <Match /> components for predefined routes,
- catch-all at the end, which does server request and check for route definition on the server.

That catch-all uses <Miss />. I think in this case I could use <Match pattern="/" />, but is there some way to avoid rendering it, when some of previously defined routes matches?

**Comment by ryanflorence** [comment]
got some docs on my machine, just cleaning house right now.

**Comment by alexFaunt** [comment]
I've just hit this issue, is it possible to pass the server rendered context result down to the client and use that for the client side render?
