### ISSUE TITLE
Link always displays active class on <Link to "/" />

### ISSUE THREAD

**Issue by Connorelsea** [ReactTraining/react-router#3890]
## Version
4.0.0-2

## Test Case
Can't get the window.ReactRouter import to work with v4, but you can see the basic layout of the code here. http://jsbin.com/zucepupoxe/edit?html,js,console,output

How do I show an active style on a link whenever they are only on "/"

## Steps to reproduce
Create three matches, one pointing to the home page route, and two pointing to other pages.

    <Match exactly pattern="/" component={Dashboard} />
    <Match exactly pattern="/about" component={About} />
    <Match exactly pattern="/links" component={Links} />

Anywhere else, create three Links, all with classNames and activeClassNames

    <Link to="/" className="name" activeClassName="active">App</Link>
    <Link to="/about" className="name" activeClassName="active">About</Link>
    <Link to="/links" className="name" activeClassName="active">Links</Link>

## Behavior

Whenever I am on "/", the "/" Link should have the full class name "name active" and the other two Links should have just "name". Whenever I am on one of the other two it should have "name active" on that one and NOT dashboard. But interestingly, it is rendering "name active" on the "/" Link and whichever of the other two links you clicked. (If the url is `/about` for example)

**Comment by Connorelsea** [comment]
Resolved: You must use activeOnlyWhenExact. But AFAIK, unless I missed something, this is un-documented. I found out by reading the code.

**Comment by mattiamanzati** [comment]
It is actually documented, you may be hitting the #3868 bug! ;)

For now, reference the markdown docs!
https://github.com/ReactTraining/react-router/blob/v4/website/api/Link.md#activeonlywhenexact-bool
