### ISSUE TITLE
[v4] Is v4 ready for production?

### ISSUE THREAD

**Issue by vinpac** [ReactTraining/react-router#3892]
First, I want to thank you for react-router, it's awesome. Secondly, I loved v4 and I want to use it on production, do you think it's production ready already or not?
Thanks

**Comment by ryanflorence** [comment]
It's a pre-release right now. Your tolerance for solving problems in
prerelease software should determine your answer :)

**Comment by gabrielalan** [comment]
@ryanflorence I have a huge production environment, can I use v4? I could use v2.8, but its getting old because you guys are working no the new version, so I don't want to rewrite my application.

**Comment by ryanflorence** [comment]
If you're willing to own bugs that block you, go for it.

Until we release a final version, you'll need to take ownership of problems
you run into :)

**Comment by gabrielalan** [comment]
@ryanflorence thanks for the anwser. Do you know if will there great changes on the API in the final v4?
