### ISSUE TITLE
Memory leak with basic usage.

### ISSUE THREAD

**Issue by pauldotknopf** [ReactTraining/react-router#3900]
Using the example "sidebar", I added this code to test the memory leak.

```js
var current = false;

var flop = function() {
  if(current) {
    browserHistory.push('/sidebar/category/Burgers/Buffalo%20Bleu');
  } else{
    browserHistory.push('/sidebar/category/Burgers/Mushroom%20and%20Swiss')
  }

  current = !current;

  setTimeout(flop, 100);
}

setTimeout(flop, 100);
```

After about 3 minutes of running, my heap size has grown 1MB.

I have ran a very similar test using ```router5-react``` and the heap size stayed stable.

**Comment by timdorr** [comment]
That points to the underlying history library, not something within the router. I would open an issue there and test against the latest version to be sure.
