### ISSUE TITLE
CSS and JavaScript breaking with onEnter with react-router

### ISSUE THREAD

**Issue by oshalygin** [ReactTraining/react-router#3904]
## Version
"react-router": "2.4.0"

## Test Case
github repo: 
https://github.com/oshalygin/MerchantDashboard
## Steps to reproduce
So I was bringing in Material Design Lite and trying to add some components to the page.  For some reason all of the component css was getting overriden by the `user agent stylesheet `.  I think I spent about an hour trying to figure out why...

Finally after hacking the code apart I narrowed it down to this:

Before entering any route, I'm checking if the user is authorized with the following:

    function isAuthorized(nextState, replace, callback) {
        if (nextState.location.pathname === "/login") {
            callback();
            return;
        }
        const state = store.getState();
        if (state.user && state.user.loggedIn === true) {
            callback();
            return;
        }
    
        retrieveUser((store.dispatch), (error) => {
            if (!!error) {
                replace("/login");
            }
            callback();
        });
    }

My routing looks like this:

    render(
        <Provider store={store}>
            <Router history={browserHistory}>
                <Route path="/" component={Application} onEnter={(nextState, replace, callback) => isAuthorized(nextState, replace, callback)}>
                    <IndexRoute component={DashboardPage} />
                    <Route path="login" component={LoginPage} />
                    <Route path="dashboard" component={DashboardPage} />
                    <Route path="items" component={ItemPage} />
                    <Route path="item-categories" component={DashboardPage} />
                    <Route path="modifiers" component={DashboardPage} />
                    <Route path="taxes" component={DashboardPage} />
                    <Route path="discounts" component={DashboardPage} />
                    <Route path="orders" component={DashboardPage} />
                    <Route path="users" component={DashboardPage} />
                    <Redirect to="dashboard" from="*" />
                </Route>
            </Router>
        </Provider>,
        document.getElementById("application")
    );

Now if I remove the `onEnter` property, eg: 

`<Route path="/" component={Application} onEnter={(nextState, replace, callback) => isAuthorized(nextState, replace, callback)}>`

to

`<Route path="/" component={Application}>`

I'm all good.  But I need my authorization!

Anyone know whats going on?

BAD: 
[![enter image description here][1]][1]

GOOD:
[![enter image description here][2]][2]

  [1]: http://i.stack.imgur.com/bfpvP.png
  [2]: http://i.stack.imgur.com/VwuNu.png
## Expected Behavior
The styling should work and user agent stylesheet shouldn't override anything
## Actual Behavior

Guessing this is causing issues:

***If callback is listed as a 3rd argument, this hook will run asynchronously, and the transition will block until callback is called.***

Alright updated to:
`<Route path="/" component={Application} onEnter={(nextState, replace) => isAuthorized(nextState, replace)}>`

With that in place, the styling/js stuff I need is working but obviously we route to the path without checking that the user is authorized since the callback isn't part of the loop....

**Comment by oshalygin** [comment]
Actually after some more testing, it appears anytime I change routes thats where the problem occurs.  
After removing onEnter and continuing developing I notice that whenever I switch routes, the `user agent stylesheet` becomes king on the new route.

**Comment by timdorr** [comment]
Unless your components are manipulating the CSS links and style tags on the page, there is nothing that would be causing that within React Router. It looks like you're using Windows, so you might be running into IE's infamous style and link tag limits. While you can cause this via Router hooks, I think the culprit is elsewhere. Try upgrading your dependencies too.

Also, since you're not doing anything async in the onEnter hook, I would remove the 3rd argument (for `callback`) and just return where needed. That will run the code synchronously and might fix things too. Worth a shot.
