### ISSUE TITLE
MatchNot

### ISSUE THREAD

**Issue by steida** [ReactTraining/react-router#3906]
The opposite of the
```jsx
<Match />
```

**Comment by ryanflorence** [comment]
I've thought about this ... got some use cases?

**Comment by ryanflorence** [comment]
(also note the children prop of match, you can implement this as a one
liner)

**Comment by steida** [comment]
Since RR4 inlined the routing, the use case is simple. I want to be able to render something exceptional aka don't render <Header /> for the page of the specific path (https://github.com/ReactTraining/react-router/issues/3907).

**Comment by timdorr** [comment]
Could just be a prop: `<Match whenNot pattern="/foo/bar" />`.

**Comment by ryanflorence** [comment]
```js
const MatchNot = ({ pattern, render, ...props }) => (
  <Match pattern={pattern} children={({ matched, ...matchProps }) => (
    matched ? null : render(matchProps)
  )} {...props}/>
)
```

We don't need this in the core lib, at least not yet.

**Comment by ryanflorence** [comment]
(what we really need is a `<MatchRenderer/>` that does the `component:Component, render, children` branching for components that wrap match and want to keep the same render flexibility)

**Comment by ryanflorence** [comment]
This is easy enough to wrap `Match` to implement `MatchNot` so I'm going to close. Maybe worth an example, maybe under the Match `children` prop API doc.

**Comment by jedwards1211** [comment]
I've about concluded that I'm going to use something like this instead of `<Miss>`.
