### ISSUE TITLE
Rename pattern to path

### ISSUE THREAD

**Issue by steida** [ReactTraining/react-router#3907]
The path is the pattern.
Pattern smells like regex.
Regex is an implementation detail.

The path should be a string or a regex or an ad hoc function.

**Comment by ryanflorence** [comment]
pattern is the thing you match, path is the actual path from a URL

**Comment by steida** [comment]
No, the `pathname` is.

**Comment by steida** [comment]
The thing we match is the `path`. Not pathname nor regex.

**Comment by ryanflorence** [comment]
I'd like to reserve "path" for pathname + search + hash.

**Comment by steida** [comment]
That's what `path` should be. Flavoured with regex or ad hoc function.

**Comment by timdorr** [comment]
It's the "pattern" that you use to "match". It makes perfect sense as-is. We're not bringing things back from previous versions for the sake of familiarity, as that leads to incorrect interpretations of the API.
