### ISSUE TITLE
props.location.query is null if there are no query params

### ISSUE THREAD

**Issue by jochenberger** [ReactTraining/react-router#3909]
In v4, `props.location.query` is null if there are no query parameters. This makes components' code more complicated.
See also https://github.com/ReactTraining/react-router/commit/2d4f4b8721b72b53be4f14ab4d0970e657297cd9.

**Comment by ryanflorence** [comment]
dupe

**Comment by jochenberger** [comment]
of what?

**Comment by chentsulin** [comment]
https://github.com/ReactTraining/react-router/issues/3899
