### ISSUE TITLE
Server rendering and getComponent

### ISSUE THREAD

**Issue by Mosho1** [ReactTraining/react-router#3911]
We have server side rendering set up, and recently started utilizing getComponent to lazy load our routes. We encounter a problem where the initial render (before the route's getComponent) gets called renders a blank page, and only then after getComponent resolves we get actual page. This results in having the page html sent from the server turn into a blank page momentarily before the local render occurs. What can be done about this?

**Comment by timdorr** [comment]
Follow the server rendering guide: https://github.com/ReactTraining/react-router/blob/master/docs/guides/ServerRendering.md

You need to use `match` to resolve any async behaviors or routes before rendering.

**Comment by Mosho1** [comment]
Perhaps I wasn't clear, this isn't on the server. It's the client. The first render, on the client, before `getComponent` is called, turns the div empty, and there's a delay until it is populated with the rendered content from the lazy loaded route.
