### ISSUE TITLE
when refresh page : localhost:8080/docs/angular~2.0_typescript cant match route 

### ISSUE THREAD

**Issue by wangfaxi1985** [ReactTraining/react-router#3913]
## when refresh page : localhost:8080/docs/angular~2.0_typescript cant match route 
when i use `history.push({pathname:'/docs/angular~2.0_typescript/'}) ` can go corrent  page 
but when i refresh whole page with : http://localhost:8080/docs/angular~2.0_typescript/   

chrome page display: 'Cannot GET /docs/angular~2.0_typescript/'

any idea?

my route config is:
```
const routeConfig = (
  <Route path="/" component={App}>
    <IndexRoute component={Home} />
    <Route path="about" component={About} />
    <Route path="counter" component={Counter} />
    <Route path="stars" component={Stars} />
    <Route path="/*" component={DocPage} />
  </Route>
)
```

**Comment by timdorr** [comment]
Something is set up incorrectly with your server. Look into setting it up to handle the browser history in the docs.

**Comment by wangfaxi1985** [comment]
webpack-dev-server --config config/webpack/index.js --content-base ./build --history-api-fallback --no-info --open
i use this start my server

you mean is thisconfig err?
