### ISSUE TITLE
Passing function to Link doesn't work

### ISSUE THREAD

**Issue by BrandonDickson** [ReactTraining/react-router#3915]
I like the ability to pass a function to a Link in v4, but it's not working. In looking at the compiled source pulled from npm, it seems the wrong source code file is used for Link.js, it has no check for the function, but the code on Github does.

**Comment by mntbkr** [comment]
I just hit this...make sure you have "react-router": "4.0.0-alpha.3" installed and not "react-router": "4.0.0-2"  the docs also have this wrong and need updating

**Comment by timdorr** [comment]
This was added in #3881 and we're probably going to iterate on this a little further (most likely by creating a `<Navigation>` component that `<Link>` uses). So, I wouldn't build on this just yet. `<Link>`'s API is pretty stable, but this part is rocky right now. Maintain a holding pattern for a little bit, please 😄
