### ISSUE TITLE
How to execute function/callback, after router.go() has finished?

### ISSUE THREAD

**Issue by tomazahlin** [ReactTraining/react-router#3919]
I would like to ask how to execute function/callback, after router.go() has finished. Lets say I would like to do something like this:

this.context.router.go(-5).then(() => { console.log('done'); }); // Of course this doesn't work, because .go() doesn't return a Promise.

I need this because some components will be unmounted during going back in history and I want to execute something after they are unmounted.

**Comment by timdorr** [comment]
Use the routerWillLeave hook.

**Comment by tomazahlin** [comment]
Hi Tim, thanks for suggestion, but I don't get it how I can use this hook, and after searching the docs, I didn't find much or anything that would be relevant to my case. Can you give me a short generic example?
