### ISSUE TITLE
params prop does not reflect a change when redirecting to url with same route pattern but different url params

### ISSUE THREAD

**Issue by PGuimarais** [ReactTraining/react-router#3922]
## Version
4.0.0

## Steps to reproduce
When visiting a different Link that possesses the same url pattern as the current url, it appears that the url parameters do not change on the params prop as expected.

Two Links to Visit:
Link to="/home/3" 
Link to="/home/4"

Route Match:
Match pattern="/home/:userid" component={Home}

According to the docs, the param value is available on the this.props.params object. When I initially view the params object in the Home component with the first <Link>, it is correct. However, when navigating to the second Link (with the same url pattern), the URL changes in the browser, but the this.props.params object does not reflect a change for this.props.params.userid. 

## Expected Behavior
From my understanding, when navigating to a new route with the same pattern and rendering the same component, the url parameters should be updated on the params prop to reflect the url change. 

## Actual Behavior
When navigating with a Link with different URL parameters but the same route pattern, and rendering the same component, it appears that the params object available to the rendered component does not reflect the updated parameters.

**Comment by timdorr** [comment]
This would show up in the recursive paths example: https://react-router.now.sh/recursive-paths

Can you give a more complete reproducible test case ("repro")?

**Comment by PGuimarais** [comment]
It appears to have been my fault. I was mistakenly attempting to access the set of updated props on componentWillReceiveProps instead of componentWillUpdate.
