### ISSUE TITLE
`undefined is not a function `

### ISSUE THREAD

**Issue by garyfungwelab** [ReactTraining/react-router#3924]
## Version
^2.0.1

## Steps to reproduce
Randomly got `undefined is not a function` error in 
https://github.com/ReactTraining/react-router/blob/master/modules/RouterContext.js#L59

## Environment
OS: Android 5 
Browser: Chrome 34.*

**Comment by timdorr** [comment]
We need a more in depth example. Can you provide a repro? Without one, we can't determine if this is a valid bug.
