### ISSUE TITLE
Old props after click back arrow in browser

### ISSUE THREAD

**Issue by tomasztomys** [ReactTraining/react-router#3925]
## Version
2.4.1

## Expected Behavior
I want to see new props in this.props.location.query after click back arrow.

## Actual Behavior
I have old props after click back arrow in browser. New props will be load and visible by router after a few miliseconds after first render of component.

**Comment by timdorr** [comment]
I'm not sure I understand. The props you're given should revert when you go back because youte going back to the URL that provided then. 

In any case, we need a repro to really act on this. I'll reopen if you can provide one and it confirms an issue.
