### ISSUE TITLE
RR V4 Programmatically Change Routes

### ISSUE THREAD

**Issue by michaelryancaputo** [ReactTraining/react-router#3926]
## Version
4.0.0

## Test Case
Can't access router history to push state.

## Steps to reproduce
Attempt to access programmatically the ability to change routing.

## Expected Behavior
`history.push (path)` is what I would expect to push to a new route
alternatively `history.replaceState (path)` etc.

## Actual Behavior
`history` is not available, confused as to if I need to import a library for this.

**Comment by michaelryancaputo** [comment]
I should note, previous versions of RR contained these docs: https://github.com/ReactTraining/react-router/blob/master/docs/guides/NavigatingOutsideOfComponents.md

**Comment by michaelryancaputo** [comment]
It appears I can access the router methods I need through context, however I was under the impression that using context was an anti pattern and would be deprecated?

**Comment by timdorr** [comment]
We can't prevent its use, only discourage it. You might be interested in react-history for a declarative means to issue history actions. It's pretty neat.

**Comment by valerybugakov** [comment]
@timdorr so what's the correct way to redirect in V4 from redux-saga for example?

**Comment by joshwcomeau** [comment]
Any news on this? I need to be able to send the user to a specific URL after they submit a form, so I can't use `<Link>`.

I checked `react-history` but it's not really what I need. Are there plans to include `withRouter` in v4?

**Comment by daqo** [comment]
Any update on this?

**Comment by michaelryancaputo** [comment]
I think you want to use `react-history` and do something like `history.push ('/route');`

**Comment by kwelch** [comment]
As best as possible I try to use either the `Link` or `Redirect` component. Accessing `react-history` works, but could reduce the reusability of the action.

**Comment by dranzboi** [comment]
i have a same problem iI cant redirect user after sending form, how can i solve it?

**Comment by sbussard** [comment]
this issue needs to be reopened. 
the experience is terrible for those using redux-saga

**Comment by aaronsmulktis** [comment]
I'm also unsuccessful using <Redirect /> or this.props.history.push("/") after a form submission... I've imported everything correctly, wrapped my component using HOC withRouter(), and even setup passed in the component scope using `let self = this;` within the callback of the form.. still nada

any ideas?
