### ISSUE TITLE
How do you create a Master Detail page? (v4)

### ISSUE THREAD

**Issue by acpower7** [ReactTraining/react-router#3928]
I went through the docs multiple times but I'm still not sure how to create a layout that can share some common components.

How do you create a layout that always has a header and footer, and only body changes? And how do you create more routes within that body? (bonus)

thanks

**Comment by ryanflorence** [comment]
the basic example does this, doesn't it?

**Comment by LukeAskew** [comment]
Not exactly. 

I want to do something like:

```
<Router>
  <div className={'app-container'}>
    <Switch>
      <DefaultLayout>
        <Route exact path={'/'} component={Dashboard} />
      </DefaultLayout>

      <EmptyLayout>
        <Route component={NotFound} />
      </EmptyLayout>
    </Switch>
  </div>
</Router>
```

Where the app uses a different container component based on which route matches.

**Comment by kachkaev** [comment]
@LukeAskew Have you found a better solution so far? I've got the same issue here. The page layout is expected to contain a header and a sidebar in all cases except when it's 404. The trick with routes.map would work, but it would also generate multiple instances of the header and the sidebar, so when a user is switching between routes, the layout DOM gets a deep refresh :–(

**Comment by kachkaev** [comment]
@ryanflorence how would you solve this?

**Comment by ryanflorence** [comment]
```jsx
const routes = [
  { path: '/one',
    component: One
  },
  { path: '/two',
    component: Two
  },
  { path: '/three',
    component: Three
  }
]

<Router>
  <div>
    <Switch>
      {routes.map(route => (
        <Route path={route.path} component={Header}/>
      ))}
    </Switch>
    <Switch>
      {routes.map(route => (
        <Route path={route.path} component={Sidebar}/>
      ))}
    </Switch>

    <Switch>
      {routes.map(route => (
        <Route path={route.path} component={route.component}/>
      ))}
      <Route component={NoMatch}/>
    </Switch>
  </div>
</Router>
```

There's a bug right now #4578 that will avoid the remounting of `Header` and `Sidebar` as the routes change, but does this do what you want?

**Comment by ryanflorence** [comment]
@LukeAskew 

```jsx
const routes = [
  { path: '/one',
    Component: One,
    Layout: Layout1
  },
  { path: '/two',
    Component: Two,
    Layout: Layout2
  },
  { path: '/three',
    Component: Three,
    Layout: Layout2
  }
]

<Router>
  <div>
    <Switch>
      {routes.map({ path, Layout, Component } => (
        <Route path={route.path} render={(props) => (
          <Layout {...props}>
            <Component {...props}/>
          </Layout>
        )}/>
      ))}
    </Switch>
  </div>
</Router>
```

**Comment by kachkaev** [comment]
Thanks for your reply @ryanflorence – this is close to what I was looking for, assuming that the componets are reused. What would be good as well is to be able to control that top-level `<div>`, because someone might want to end up with something like this:

```jsx
// /
<LayoutForPageWithContent>
  <Header />
  <Sidebar />
  <Home />
</LayoutForPageWithContent>

// /about
<LayoutForPageWithContent>
  <Header />
  <Sidebar />
  <About />
</LayoutForPageWithContent>

// /cart
<LayoutForPageWithContent>
  <Header />
  <Sidebar />
  <Cart />
</LayoutForPageWithContent>

// ...

// /404
<LayoutForPageWithError>
  <Error404 />
</LayoutForPageWithError>
```

**Comment by ryanflorence** [comment]
@kachkaev 

```jsx
const routes = [
  { path: '/',
    exact: true,
    Component: Home
  },
  { path: '/about',
    Component: About,
  },
  { path: '/cart',
    Component: Three,
  }
]

<Router>
  <div>
    <Switch>
      {routes.map({ path, exact, Component } => (
        <Route path={route.path} exact={exact} render={(props) => (
          <LayoutWithSidebarAndHeader {...props}>
            <Component {...props}/>
          </LayoutWithSidebarAndHeader>
        )}/>
      ))}
      <Route component={Error404}/>
    </Switch>
  </div>
</Router>
```

**Comment by kachkaev** [comment]
@ryanflorence this solution wont reuse `LayoutWithSidebarAndHeader` as far as I understand, so their states and fetched will be lost each time the url changes.

**Comment by ryanflorence** [comment]
there's a bug in switch #4578

**Comment by ryanflorence** [comment]
fixed by

b556060d7f17d008877f4b976e0ff092b833d81d
32a5bbb5871f5024d9c4e62cddfaa020fd5f7857
7a02cc3545ea27b039d0bc6ebb652dd9e06928ed

**Comment by kachkaev** [comment]
I'm not sure that that bug is related. Reusing `component={Sidebar}` is one thing, because it's just a reference to a component type. But reusing `render={(props) => (...)}` inside `map` is probably a completely different story, because here we have subtrees of component instances, not just references to their names.

I don't see any solution in the current API, but I may be wrong. Looks like the only place the wrapper like that can be declared is in `<Switch />`:

```js
<Switch wrapper={({match}) => (match ? LayoutWithSidebarAndHeader : LayoutForPageWithError)}>
  <Route exactly path="/" component={Home} />
  <Route exactly path="/about" component={About} />
  <Route exactly path="/cart" component={Cart} />
  <Route component={PageWithError404} />
</Switch>
```

It's ugly, but at least it gives a chance to reuse the Layout in the situation above. Once again, I can be totally wrong here.

**Comment by ryanflorence** [comment]
It's not a different story. It's fixed on the v4 branch.

**Comment by kachkaev** [comment]
Just updated to v4.0.0-beta.7 and can confirm that shared layout wrappers are reused perfectly now! Checked this by rendering a random `instanceId` in the layout, which is came from here: `componentDidMount() { this.isntanceId = `instance ${Math.random()}`; }

Two caveats to share:

* When running `yarn add react-router@v4.0.0-beta.7`, it is important not to forget `yarn add react-router-dom@v4.0.0-beta.7`, because otherwise some weird context-errors will show up.

* When looping through routes using `map`, do not add assign key to them as this is done elsewhere, because otherwise the layout will not be reused:

```js
{routes.map(({ path, exact, content: ContentComponent }) => (
  <Route
    // NO key={path} etc. here!
    path={path}
    exact={exact}
    render={(props) => (
      <Layout {...props}>
        <ContentComponent {...props} />
      </Layout>
  )}
  />
))}
```

Thanks for your previous responses @ryanflorence! I like V4 API more and more!

**Comment by ryanflorence** [comment]
@kachkaev you shouldn't be installing `react-router` yourself at all. `react-router-dom` re-exports everything from `react-router` that you need.

**Comment by ankibalyan** [comment]
How the approach, is their any backlog issue if I'll try like this.
I want a couple of different layouts for Anonymous users, Logged in users, then Admin users, Addtional layout like Page Layouts.

```
      <Switch>
        <Route exact path="/login" render= { ({ ...rest }) => (
          <Login { ...rest } onLogin={ (props) => { // do something on login } } />
        ) } />

        <Route exact path="/register" component={Register} />

        <Route path="/admin" render={ ({ ...rest }) => (
          <AuthLayout { ...rest }>
            <Switch>
              <Route exact path="/admin" render={ (props) => (
                <Dashboard />
              ) } />
            </Switch>
          </AuthLayout>
        ) } />

        <Route path="/">
          <MainLayout>
            <Switch>
              <Route exact path="/" >
                <Home />
              </Route>
              <Route exact path="/about" >
                <About />
              </Route>
              <Route exact path="/faqs" >
                <Faqs />
              </Route>
              <Route exact path="/terms-of-service" >
                <TermsOfService />
              </Route>
            </Switch>
          </MainLayout>
        </Route>
      </Switch>
```

or how can I achieve this in a better way.

**Comment by ankibalyan** [comment]
while this was pretty easy in previous versions

```
<Router history={browserHistory}>
  <Route path="/" component={MainLayout}>
    <IndexRoute component={Home} />
    <Route path="/about" component={About} />
    <Route path="/terms-of-service" component={TermsOfService} />
    <Route path="/faqs" component={Faqs} />
  </Route>
  <Route path="/" component={AdminLayout}>
    <IndexRoute component={Dashboard} />
    <Route path="/users" component={Users} />
  </Route>
</Router>
```

**Comment by Anima-t3d** [comment]
@ankibalyan Have you tried [this](http://stackoverflow.com/a/43388506/3163075):

> Define one Route pointing to a component that will decide what to wrap the route in
> 
> ```
> <Router>
>   <Route component={AppWrap} />
> </Router>
> ```
> 
> In AppWrap do something like the following
> 
> ```
>  var isPrivateLayout;
>  for (var path of listOfPrivateLayoutPaths) {
>    if (this.props.location.pathname == path) {
>      isPrivateLayout= true;
>    }
>  }
>  if (isPrivateLayout) {
>    return <PrivateLayout>
>         (routes)
>       </PrivatelyLayout>
>  } else {
>    return <PublicLayout>
>         (routes)
>       </PublicLayout>;
>  }
> ```

@timdorr it does not seem that this issue should be closed. Based on the basic example one would need to create `GuestLayout`, `AdminLayout` and in each of those layouts define the routes? Whereas in the older version you could just define everything in 1 file. In v4 it seems you can only go 1 level deep each time when defining a route/template?

**Comment by eashish93** [comment]
I tried with this approach:
```jsx
const DefaultLayout = ({children}) => (
  <div>
     <Header/>
     {children}
 </div>
);
<Router>
<Switch>
                <Route path="/checkout" exact component={Checkout}/>
                <DefaultLayout>
                    <Switch>
                        <Route path="/" exact component={Home}/>
                        <Route path="/products" component={Products}/>
                        <Route path="/product/:item" component={ProductSingle}/>
                        <Route path="/cart" component={Cart}/>
                        <Route path="/login"  component={Login}/>
                        <Route path="/register" component={Register}/>
                        <Route path="/forgetpass" component={ForgetPass}/>
                    </Switch>
                </DefaultLayout>
            </Switch>
</Router>
```

**Comment by viiiprock** [comment]
Hi @kachkaev ,
Do you have the any better solution for `key` ?
I used `key={path}` to defeat my confusing of key number `0` to all child components array, because of this line in React docs 
"Keys help React identify which items have changed, are added, or are removed. "
But I really don't know is it the right way, the path should be unique as my think.

**Comment by viiiprock** [comment]
I used this approach 

```js
  <Provider store={store}>
    <ConnectedRouter history={history}> // this is from connected-react-router for my sagas 
      <Switch>
        {routes.map(({ path, exact, component: Component }) => (
          <Route
            key={path}
            path={path}
            exact={exact}
            render={props => (
              <App {...props}>
                <Component {...props} />
              </App>
            )}
          />
        ))}
      </Switch>
    </ConnectedRouter>
  </Provider>
```
Anyone has idea to work with Sidebar like https://reacttraining.com/react-router/web/example/sidebar
with this approach?

**Comment by noinkling** [comment]
@eashish93 Unfortunately there doesn't seem to be a way to make that approach work with a layoutless fallthrough (e.g. 404). But it works great if your fallthrough does use the layout.

**Comment by EricFries** [comment]
@kachkaev Thanks for the tip about not using keys.  I was using keys and components were getting remounted on every route change.  What's the best practice for `.map()` to generate `<Route>` components in terms of assigning keys?

**Comment by steelx** [comment]
// when
```
<Switch>
        {routes.map(({ path, exact, component: Component }) => (
          <Route
            key={path}
            path={path}
            exact={exact}
            render={props => (
              <App {...props}>
                <Component {...props} />
              </App>
            )}
          />
        ))}
      </Switch>
```

**exact match doesn't work**

BUT, I inserted Layout directly as per @eashish93  commented on 27 Apr 2017, it works fine
