### ISSUE TITLE
Params and Query passed as null

### ISSUE THREAD

**Issue by kwelch** [ReactTraining/react-router#3929]
## Version
4.0.0

## Steps to reproduce
```diff
const Component = ({location: { query = {} }, params ={} }) => {
// Since params is null, defaulting the params fails
- const id = params.id;
// Workaround
+ const id = (params || {}).id;

// Same case on query
- const firstName = query.firstName;
+ const firstName = (query || {}).firstName;
};
```
## Expected Behavior
Props to allow for defaulting.

## Actual Behavior
Null was returned causing defaulting to be skipped. 

I found this as part of my conversion from v2 to v4.

**Comment by timdorr** [comment]
What does your `<Match>` usage look like?

**Comment by timdorr** [comment]
See this tweet from @knowbody: https://twitter.com/matzatorski/status/778868456569630720

That's just how defaults work in ES2015. `null` has a value, so it only uses the default on `undefined`. While annoying, this isn't really up to us to solve. It's how the language works.
