### ISSUE TITLE
Router params is not update "push" was execute

### ISSUE THREAD

**Issue by iroy2000** [ReactTraining/react-router#3931]
We are using React Router, React Redux Router and hashHistory

Routes
```
  <Route path='/(:bookmark)' component={DemoApp}>
      <IndexRoute component={DefaultRouteHandler} />
      <Route path="*" component={DefaultRouteHandler} />
  </Route>
```

Somewhere in our code, user click an action and we  do the following

```
import { push } from 'react-router-redux'

export const setHash = (hash) => {
  const hashString = encodeURI(JSON.stringify(hash))
  return push(`/#/${hashString}`)
}
```

But somehow in our view, we didn't get the "params" after `push` above was execute. 

```
this.props.params.bookmark
```

Did I do something wrong here ?

Thsnks

**Comment by timdorr** [comment]
This is a react-router-redux issue. But it looks like you're not dispatching that action to the store.
