### ISSUE TITLE
Feature Request: Mechanism for "guarding" routes

### ISSUE THREAD

**Issue by nibblesnbits** [ReactTraining/react-router#3932]
I have an application which needs to prevent access to certain routes (e.g., a Profile page).  I have found that the `onEnter` method does allow me to kick a user back to another route if necessary, but my main problem with it is that the method is static, and also provides no insight into the application state.  I *could* simply check my cookie/localStorage/etc from this static method, but that hardly feels ideal.  Would it be possible to provide access to the store or possibly the component's `props` within the onEnter handler?  Obviously this may require moving the onEnter handler to be an instance method, but I feel like that would provide a lot of power that currently isn't possible.

**Comment by timdorr** [comment]
You can do the same check in `componentWillMount` on your route component, which has access to your component state and should have access to other state containers.
