### ISSUE TITLE
<Match exactly> doesn't take parent into account

### ISSUE THREAD

**Issue by ForbesLindesay** [ReactTraining/react-router#3938]
version: 4.0.0-alpha.3

When you use `<Match exactly={true} path="foo" />`, it doesn't take into account the parent context.  This kind of makes sense, exactly means match the entire path.

The default behaviour, allows `<Match path="foo" />` to match paths that end `foo/bar/baz`.  This is fine if there child matchers that match (or miss) the `bar/baz` part, but I need a good way to indicate when something is a leaf.

In the example:

```js
const App = () => {
  return <Router><Match path="settings" component={Settings} /></Router>;
};

const Settings = () => {
  return (
    <div>
      <Match path="profile" component={Profile} />
      <Miss component={PageNotFound} />
    </div>
  );
};

const Profile = () => {
  return <div>Profile does not have any child matchers</div>;
};

const PageNotFound = () => {
  return <div>Page not found</div>;
};
```

How can I ensure that `/settings/profile` renders the profile component, but also ensure that `/settings/profile/foobar` renders my `PageNotFound` component?

**Comment by alisd23** [comment]
@mjackson this can close :+1:
