### ISSUE TITLE
'useBeforeUnload' enhancer dosent exists.

### ISSUE THREAD

**Issue by shaibam** [ReactTraining/react-router#3941]
using the explenation at the end of - https://github.com/ReactTraining/react-router/blob/master/docs/guides/Histories.md
I am trying to listen to route changes in the react-app, but the 'useBeforeUnload' enhancer dosent exists.
any help please?

**Comment by timdorr** [comment]
Make sure you're installing a 2.x version of `history`. The docs are here: https://github.com/mjackson/history/blob/v2.x/docs/ConfirmingNavigation.md
