### ISSUE TITLE
Ignore omitted components in deeply nested routes 

### ISSUE THREAD

**Issue by twheys** [ReactTraining/react-router#3949]
Hi, I would like to nest routes reflecting my URL structure with route levels in between but I don't need a component at every level. Would it be possible to ignore missing components when deeply nesting them in order to make a structure like the following?

```
<Router history={browserHistory}>
    <Route path="/" component={Container}>
        <Route path="/feature">
            <IndexRoute component={ListPage}/>
            <Route path="/create" component={EditPage}/>
            <Route path="/:pk">
                <IndexRoute component={DetailsPage}/>
                <Route path="/edit" component={EditPage}/>
            </Route>
        </Route>
    </Route>
</Router>
```

Here we expose a couple URLs:

1. /feature <- a list of feature entities
2. /feature/create <- Create page for a new entity
3. /feature/23  <- Details page for entity
4. /feature/23/edit <- Edit page for existing entity

However, it's not necessary to add a component to the view for every level here, so by omitting a component, it should be ignored.

**Comment by timdorr** [comment]
Yes, both `path` and `component` are optional props on `<Route>`

**Comment by twheys** [comment]
Ok, it was not working for me this way, but I think for a different reason.

**Comment by twheys** [comment]
Can you please reopen this and investigate it?  True that both of those fields are optional, however it does not exert the expected behavior.  In the above routes example I gave, if you navigate  to the url `/feature/1/create` for example, it will not find a matching route.  I would expect it to render the `EditPage` component nested in `Container`

**Comment by timdorr** [comment]
Your config doesn't have any route that matches that URL. You also have nested absolute routes, so remove the leading slashes from all of your paths.
