### ISSUE TITLE
Correct way of using v4.0.0 api without rendering components.

### ISSUE THREAD

**Issue by Aourin** [ReactTraining/react-router#3951]
There seems to be a bit of confusion on how to best approach how to handle redirects/transitioning to other states.

From what I understand, withRouter is no longer available.
Also, this.context.router seems to not be something that "should" be used.

If that is the case, can it be inferred that the only real way to navigating to new states is by using component rendering?

This is a new issues to discuss based on https://github.com/ReactTraining/react-router/issues/3903 and https://github.com/ReactTraining/react-router/issues/3847

**Comment by mjackson** [comment]
This is essentially a dup of #3847. We should probably just reopen it.

**Comment by mjackson** [comment]
I re-opened #3847. Let's continue discussion there. Thanks :)
