### ISSUE TITLE
Add Component Lifecycle doc to V4 docs

### ISSUE THREAD

**Issue by theirishpenguin** [ReactTraining/react-router#3954]
I'm new to React Router, so I don't have any pre-V4 knowledge. I found the V4 guide at https://react-router.now.sh excellent. However, **one crucial missing thing** from it for a fully fledged app is how to load data when the component is _updating_, eg. navigating from /invoices/3 to /invoices/4.

This pre-V4 guide is the missing link...

https://github.com/ReactTraining/react-router/blob/master/docs/guides/ComponentLifecycle.md

Is there a plan to spruce it up for V4 and add it to the above V4 guide in the short term? Is it possible to contribute to the new V4 docs (ie. where is the source?)

If this issue is just adding noise feel free to just close it

**Comment by timdorr** [comment]
There is no separate router component lifecycle in 4.0. You simple use the built-in React lifecycle methods: https://facebook.github.io/react/docs/component-specs.html

**Comment by theirishpenguin** [comment]
I agree @timdorr. However, nowhere else gives a good simple example of how to fetch data on a component update. So the React lifecycle docs say...

```

componentDidUpdate (prevProps) {
    // respond to parameter change in scenario 3
    let oldId = prevProps.params.invoiceId
    let newId = this.props.params.invoiceId
    if (newId !== oldId)
      this.fetchInvoice()
  },

**Comment by timdorr** [comment]
Data fetching hasn't yet been decided on by the community. We have a number of things like this we need to figure out. We don't want to prescribe a solution too early so that we don't proliferate a bad pattern.

**Comment by theirishpenguin** [comment]
Oops. I hit return too soon accidentally. Just updated the above comment.

Feel free to leave this issue closed. Just my 2 cents. Without the above info a developer will not know a reasonable way to approach this problem.

Thanks for the quick replies.

**Comment by giorgi-m** [comment]
I am looking for a version of this document: https://github.com/ReactTraining/react-router/blob/v3/docs/guides/ComponentLifecycle.md, however for router 4, is there such? maybe @timdorr ?
