### ISSUE TITLE
"What's it look like?" example in the README should show App rendering `this.props.children` explicitly

### ISSUE THREAD

**Issue by zodiac** [ReactTraining/react-router#3958]
This is the example I'm talking about: https://github.com/ReactTraining/react-router#whats-it-look-like

The contents of the `App` component are elided, and I wrote my `App` component's render function without displaying `{this.props.children}`, hence the `About` and `User` components were never rendered.

**Comment by timdorr** [comment]
I think this is covered by the docs elsewhere. You shouldn't rely on that one example and start building things right away.

But if you have a specific suggestion, a PR is more appropriate here.
