### ISSUE TITLE
Remove history dep

### ISSUE THREAD

**Issue by mjackson** [ReactTraining/react-router#3960]
Ideally [react-history](https://npmjs.com/package/react-history) will be our only history-related dep in the router. If it doesn't export something we need, it should.

I think right now the only thing it's missing are the location/path creation utilities.

**Comment by timdorr** [comment]
Can it export those from history and just pass things through?

**Comment by mjackson** [comment]
Yep. Working on it now.

**Comment by mjackson** [comment]
Please excuse me while I use GitHub issues as a TODO list :)
