### ISSUE TITLE
How to implement onEnter function for auth check with dynamic routing.

### ISSUE THREAD

**Issue by jasan-s** [ReactTraining/react-router#3963]
This is a question rather than a issue. I am currently using react router onEnter with my routes however I want to lazy load components with require ensure but I can't find how to implement the onEnter check.

**Comment by dmason30** [comment]
@silasb @timdorr +1

**Comment by timdorr** [comment]
Do the auth check within your `getComponent` or `getChildRoutes` handler. They can return a NotFound/AccessDenied component or wildcard route to display.

**Comment by dmason30** [comment]
Thanks @timdorr, This is what I was currently doing but just wondered if there was a different way.

**Comment by jasan-s** [comment]
@timdorr would the following could be acceptable?  
```
                    <Route path="auth"  getComponent={(nextState, replace, callback) => {
                        require.ensure([], function(require) {
                            const isAuthed = checkAuth()
                             if (isAuthed) {
                               replace('/feed')
                              } else { 
                                callback(null, require('./auth.js').default);
                                }
                        })
                    }}/>
```

**Comment by timdorr** [comment]
`getComponent` doesn't provide `replace` as an argument. You should be able to do that in an `onEnter` hook on that same route.

**Comment by jasan-s** [comment]
I'm sorry its unclear, I preassumed that If I'm using require.ensure I can't use onEnter hook and have to use auth check in the getcomponent function. If possible is there a gist or link to a sample.

**Comment by timdorr** [comment]
You can still do the code splitting for separating out a chunk for auth.js. But there is no chunk being separated if you move the checkAuth() and replace to the onEnter hook. Just `if (checkAuth()) replace('/feed')` is all you need in that hook, and the require.ensure and callback code in the getComponent.

**Comment by jasan-s** [comment]
Thank you for replies, Tim . Just to confirm, the following code would work and code split for auth route but the onEnter function checkAuth() would remain in the main Chunk.  Does this mean the when User visits auth path the code splitting i did for auth,js wouldn't really benefit in load time since the main chunk is always required for OnEnter chekAuth() check? 

```
                    <Route path="auth" onEnter = {checkAuth} getComponent={(nextState,callback) => {
                        require.ensure([], function(require) {
                                callback(null, require('./auth.js').default);
                        })
                    }}/>
```

**Comment by timdorr** [comment]
Since you're not requiring the code for checkAuth() within the require.ensure, it wouldn't be splitting that out anyways. require.ensure only creates new chunks on require() calls.

**Comment by jasan-s** [comment]
This may be a webpack issue but using the code does not generate a separate chunk file. I still just one large app.js only.

**Comment by dmason30** [comment]
@jasan-s Have you specified a chunkFileName in the output section of your webpack config?

**Comment by jasan-s** [comment]
@dmason30  this is how i'm defining the output: ```  output: {
    path: PATHS.build,
    filename: '/[name].[chunkhash].js',
    chunkFilename: '/[chunkhash].js'
  }```    I also tried: 

```  output: {
    path: PATHS.build,
    filename: '/[name].[chunkhash].js',
    chunkFilename: '/[id].[chunkhash].js'
  }```

**Comment by jasan-s** [comment]
I 'm able to successfully build a vendor.js but that is because i have a defined entry point for it.

**Comment by dmason30** [comment]
I have similar and it works fine: 

    output: {
        path: BUILD_DIR
        , publicPath: '/'
        , filename: '[hash].js'
        , chunkFilename: '[id].[hash].chunk.js'
    },

**Comment by jasan-s** [comment]
@dmason30  could it be my [routes file](https://gist.github.com/jasan-s/8c17d5bd7bdf63de1c82f21221827a08)?

**Comment by ksngits** [comment]
so any updates on this? Unfortunately I am stuck with it.
