### ISSUE TITLE
params in location descriptor object?

### ISSUE THREAD

**Issue by voidale** [ReactTraining/react-router#3965]
That will be nice, is there a way to do something like that right now? (notice the optional return param) if there are no optional params we could use template literal syntax but how about optional params?
````
<Route path="flights/:from/:to/:depart(/:return)" component={} />
const params = {
  from: 'x',
  to: 'x',
  depart: 'x'
}
this.props.router.push({
  pathname: '/flights',
  params,
  query,
})
````

**Comment by timdorr** [comment]
Location is a concern of `history`. Params are layered on top by React Router, so they are unrelated things. This has come up a few times before, and we want to keep a separation of concerns here to avoid APIs crossing over each other (which can produce a lot of subtle bugs).
