### ISSUE TITLE
"Scary" text in Redirect/Authentication Documentation Example

### ISSUE THREAD

**Issue by machineghost** [ReactTraining/react-router#3969]
This is a documentation issue, so it doesn't really fall in to any of the three provided categories.  The issue is simple: the example for Redirect/Authentication contains the following:

    cb()
    setTimeout(cb, 100) // weird bug if async?

First off, "weird bug if async?" in an example looks very unprofessional.  But more importantly, calling a logout function, then calling it again 100ms later, with no explanation of why anyone would do such an odd thing, makes it look like the library authors don't understand how their own library works.

Please understand, I'm not saying you don't know how your library works (I'm sure you do); I'm simply reporting that this documentation makes it appear as if you don't, and that you might want to improve it if you don't want to scare users away from the new React Router.

**Comment by mjackson** [comment]
That comment is there because there is indeed a bug if the code is run asynchronously. So you're wrong. We don't actually understand how our own library works in this case. That's why v4 is currently a preview release, and not stable. Please feel free to dig in and figure it out if you'd like.

**Comment by machineghost** [comment]
Even if there is a bug, is highlighting it to new users trying to learn the library really the best course of action?  And even if it is, couldn't you at least provide a meaningful comment?  For instance:

    // The following line illustrates a bug in the current alpha version of Redux Router:
    //  If you call the signout callback after it is initially passed in it will do ________
    setTimeout(cb, 100);

**Comment by mjackson** [comment]
Sure. I'd be happy to accept a PR if you want to fix the comment.

**Comment by ryanflorence** [comment]
I think that bug is gone after history v4 and our restructure with
StaticRoute/React History.
