### ISSUE TITLE
Updated documentation for basename?

### ISSUE THREAD

**Issue by chrylis** [ReactTraining/react-router#3971]
I am trying to configure my app with a `basename`, but it looks like the documentation has vanished. Multiple places link to `BasenameSupport.md` (e.g., `API.md`), but it's 404.

**Comment by pshrmn** [comment]
@chrylis Assuming you are using RR v2/v3, try https://github.com/mjackson/history/blob/v2.x/docs/BasenameSupport.md. For v4 basenames are set in the Router components.

There are a few other links that seem to be affected by this. Fixing should just be a matter of updating links that point to `/history/blob/master/` to `/history/blob/v2.x/`.

**Comment by nareshbhatia** [comment]
In the link provided above, it says:

> In HTML documents, you can use the <base> element's href attribute to specify a basename for the page. This way, you don't have to manually pass the basename property to your createHistory function.

Does this mean that it is ok to use the <base> tag now? RR v2 gives a warning if I do that but RR v3 does not.
