### ISSUE TITLE
[v4] <Match> and context subscription ?

### ISSUE THREAD

**Issue by lvauvillier** [ReactTraining/react-router#3974]
Hi,

First of all, thanks for this new API. I really like the new declarative syntax :)

`<Match>` and `<MatchProvider>` seems to work together with a notification mechanism to render matched component even if a parent implements sCU.

But I do not understand why `<Match>` register itself (`context.match.addMatch()`) but do not call the `context.match.subscribe()` function do be notified when the location changes... (I only found  a `subscribe()` call in the `<Miss>` component)

How to properly subscribe to changes ? My components doesn't rerender when location change because i have parent component connected with redux.

**Comment by lvauvillier** [comment]
Ok, this is on road.
(just see the new repo https://github.com/ReactTraining/react-context-emission)

**Comment by timdorr** [comment]
We actually switched to react-broadcast, which takes a more composable approach to it. See ce59676 for more details.
