### ISSUE TITLE
Active class always active for root route

### ISSUE THREAD

**Issue by nirajmchauhan** [ReactTraining/react-router#3975]
# Version
2.8.1

By default always I am getting active class on the first `li`, this issue might have been fixed in previous version, but currently I am facing it again.
```
ReactDOM.render((
	<Router history={browserHistory}>
		<Route path="/" component={Wrapper}>
			<IndexRoute path="/" component={Login}></IndexRoute>
			<Route path="/registration" name="registration" component={Registration}></Route>
		</Route>
	</Router>
	),
document.getElementById('app'));
```

My menu:
```
<li className="ui-component__primary-navigation-item">
  <Link to='/' activeClassName="active">Login</Link>
</li>
<li className="ui-component__primary-navigation-item">
  <Link to='/registration' activeClassName="active">Register</Link>
</li>
```

I have created this [codepen](http://codepen.io/nirajmchauhan/pen/RGkaxN?editors=0111) of the issue.

**Comment by razh** [comment]
This can be handled by using the [`onlyActiveOnIndex`](https://github.com/ReactTraining/react-router/blob/v2.8.1/docs/API.md#onlyactiveonindex) prop:

```html
<Link to="/" onlyActiveOnIndex activeClassName="active">Login</Link>
```

Or by using the [IndexLink](https://github.com/ReactTraining/react-router/blob/v2.8.1/docs/API.md#indexlink) component:

```html
<IndexLink to="/" activeClassName="active">Login</IndexLink>
```

**Comment by timdorr** [comment]
Correct, this isn't a bug. It's intended behavior.

**Comment by danawoodman** [comment]
Note to future people, `onlyActiveOnIndex` no longer exists.
