### ISSUE TITLE
How to  exclude some special routes?

### ISSUE THREAD

**Issue by yezongyang** [ReactTraining/react-router#3982]
My project both use React and Framework7, but they have same route rule. So i want to know how to exclude some Framework7 routes?, is there filter or hook to prevent some special routes from routing?

**http://localhost/#/about  (React router)**

**htttp://localhost/#!/about.html (Framework7 Router)**

**Comment by timdorr** [comment]
You would need to use a memory router/history for this. React Router (or history, more specifically) would attempt to process the hash changes.

**Comment by yezongyang** [comment]
@timdorr is possible to use a memory router for SPA project
