### ISSUE TITLE
Isomorphic rendering: data-reactid and data-react-checksum not being cleared in v4.

### ISSUE THREAD

**Issue by phyllisstein** [ReactTraining/react-router#3984]
## Version
4.0.0-alpha.4

## Test Case
https://github.com/phyllisstein/react-router-v4-isomorphic-glitch

## Steps to reproduce
1. Create a simple app using React Router v4.
2. Render the app on the server.
3. Run the app in the browser and wait for React to mount.

## Expected Behavior
When React mounts, the `data-react-checksum` and `data-reactid` attributes should be cleared from the server-rendered components.

## Actual Behavior
React appears to mount successfully, as clicking on a `Link` component does not send an additional request to the server, but the server-rendered attributes are not removed.

**Comment by timdorr** [comment]
This would be a React issue. But those attributes are sent over in the server-rendered HTML, as they're needed to confirm the correct component tree when the client boots up on top of it.

**Comment by phyllisstein** [comment]
I'm happy to kick it to the React folks, but it seemed curious that it happened with RR4 and not with previous versions.

**Comment by foobahh** [comment]
@timdorr is it possible this could have something to do with the Miss component specifically?

**What I am seeing with SSR:**
On a match, the checksum attribute is included
On a miss, the checksum disappears, even if included with the pre-rendered html from the server.  

This specific discrepancy seems to be causing the React warning:
```warning.js:36 Warning: React attempted to reuse markup in a container but the checksum was invalid.```

**Comment by ryanflorence** [comment]
Miss doesn't work yet for picking up a server rendered page in the client.
Needs docs and the (probably not worth it) workaround.

**Comment by phyllisstein** [comment]
#3877 addresses issues with `<Miss>` and isomorphic rendering, but the issue I've observed can be reliably reproduced even without that component. The repro repo posted above just has a few simple `<Match>`es, and React still can't clear the checksum and IDs on mount.

**Comment by ryanflorence** [comment]
For now I recommend server rendering them, then dumping a `window.__IS_404__` or something and not loading JavaScript at all in the client.

**Comment by foobahh** [comment]
good idea, thanks @ryanflorence
