### ISSUE TITLE
Optimize <Link>s when active-apathetic

### ISSUE THREAD

**Issue by pshrmn** [ReactTraining/react-router#3985]
Now that the `context.location` has been removed in favor of `<LocationSubscriber>` I believe that it would be useful to know when _not_ to subscribe and optimize for those situations. The only `<Link>` components that need to know location information are ones that care about whether or not they are active.

```javascript
// care when:
// activeStyle is provided
<Link activeStyle={{color: 'blue'}} to='/foo'>Foo</Link>
// activeClassName is provided
<Link activeClassName='active' } to='/bar'>Bar</Link>
// children is a function
<Link to='/seuss'>
  {
    ({isActive, ...rest}) => (
      <a {...rest} className={isActive ? 'one fish' : 'two fish'}>
        { isActive ? 'red fish' : 'blue fish' }
      </a>
    )
  }
</Link>

// doesn't care
<Link to='/quux'>Quux</Link>
```

I believe that those are the only cases where location information is necessary. When none of those three cases are true, the `<Link>` should be able to return an `<a>` that is not wrapped with a `<LocationSubscriber>`.

**Comment by timdorr** [comment]
This is coming out of this conversation: https://github.com/ReactTraining/react-router/issues/3961#issuecomment-250237350

I also agree on this. A PR would probably be best for this kind of thing.

**Comment by ryanflorence** [comment]
let's continue discussion on the PR
