### ISSUE TITLE
PropTypes Warning

### ISSUE THREAD

**Issue by apperside** [ReactTraining/react-router#3988]
## Version
2.8.1

## Test Case
http://jsbin.com/sacerobuxi/edit?html,js,output

## Steps to reproduce
npm installing your library an using it with this simple code

```
var React = require('react');
var ReactDOM = require('react-dom');
var Router = require('react-router').Router
var Route = require('react-router').Route
var browserHistory = require('react-router').browserHistory
var Maine = require('./components/main');


ReactDOM.render(
    <Router history={browserHistory}>
        <Route path="/" component={Maine}>

        </Route>
    </Router>
    ,
    document.getElementById('app')
)


```

give me the following errors on browser's console

warning.js:36Warning: You are manually calling a React.PropTypes validation function for the `path` prop on `Route`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.

warning.js:36Warning: You are manually calling a React.PropTypes validation function for the `component` prop on `Route`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.

warning.js:36Warning: You are manually calling a React.PropTypes validation function for the `components` prop on `Route`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.

warning.js:36Warning: You are manually calling a React.PropTypes validation function for the `getComponent` prop on `Route`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.

warning.js:36Warning: You are manually calling a React.PropTypes validation function for the `getComponents` prop on `Route`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.

**Comment by timdorr** [comment]
You must not be using the right version of React Router. This was specifically fixed in 2.5.2. See #3695 and 92824f60

**Comment by zhenyulin** [comment]
I'm getting the warning currently on `react-router: next`

> 	printWarning	@	warning.js:36
warning	@	warning.js:60
get	@	React.js:95
../node_modules/react-router/es/Router.js	@	Router.js:93

**Comment by timdorr** [comment]
Don't use the `next` tag. I've removed them from npm.
