### ISSUE TITLE
[v4] How could we handle multiple path with <Match />

### ISSUE THREAD

**Issue by jackypan1989** [ReactTraining/react-router#3992]
## Version
4.0.0+

## Question

When I migrate from 2 to 4
```
2.x
<Route path='user/create' component={UserCreate}/>
<Route path='user/:userId' component={UserIndex}/> 

The route component only show the first match

---

4.0.0
<Match exactly path='user/create' component={UserCreate}/>
<Match path='user/:userId' component={UserIndex}/>

when url = user/create
both matched and will show both
so I have to change to other totally different path
```

I know ```<Match/>``` is just like other React Components
So how could I do REST-style path config likes 2.0

any tricks?

**Comment by timdorr** [comment]
You can use the child function form to bail on rendering anything if the `userId` param is 'create'.

**Comment by jackypan1989** [comment]
Thanks!

**Comment by knivets** [comment]
You need to use <a href="https://reacttraining.com/react-router/web/api/Switch">Switch</a> component.

**Comment by paulintrognon** [comment]
Is this the recommended approach of dealing with this problem?
