### ISSUE TITLE
Create a new repo for examples

### ISSUE THREAD

**Issue by prometheansacrifice** [ReactTraining/react-router#3993]
A separate repo for example would go a long way in easily trying them out as opposed to cloning the complete repo. Advantages as I see it, please let me know if they are just my opinion or if I'm missing something, are as below:

1. **Lack of instructions to build the examples**
Having separate build config files (webpack if everyone is okay) would really help. On the contrary, I couldn't find instructions to build the example on the README.md. Found it [here](https://github.com/ReactTraining/react-router/tree/master/examples) instead.

2. **Faster onboarding**
Separate repo clones/downloads faster.

Also, cleaner version history of the mainline repo?

**Comment by timdorr** [comment]
We have the examples integrated into Redux as well. This is intentional. Having multiple places to go to makes it appear as though the other repos may not be canonical. Also, we can ensure the examples work properly with the latest code changes.
