### ISSUE TITLE
Parent Route Doesn't work properly 

### ISSUE THREAD

**Issue by WUJJU** [ReactTraining/react-router#3995]
When I put /video/3 into url, the {Main} component doesn't work properly. (However, /video works good.) It doesn't load Css and the png files.  Is it because the Parent Route is not Active? I don't use any  Link.  

   `render(` 
     `<Router  history={browserHistory}>`
              `<Route path="/" component={Main}>`
              `<IndexRoute component={Home} />`
        		` <Route path="/video" >`
          			 `  <Route path=":id" component={Video} />`
          		`</Route>`
      `</Route>`
    `</Router>,`
   ` document.getElementById("main")`
	`);`

Where is the problem? Anyone gives me a hand.

**Comment by timdorr** [comment]
You need to use the Link component. You likely have relative URLs for your CSS and other assets, so they are requesting from the wrong location.

**Comment by WUJJU** [comment]
Thanks for quick response! Yes, I use relative URLs, which I haven't pay attention before.
