### ISSUE TITLE
Need to access URL Parameters object in v4

### ISSUE THREAD

**Issue by elfenheart** [ReactTraining/react-router#3997]
It would be nice to have access to the URL Parameters object from anywhere, not just the direct component from <Match>

### Use Case:
Let's say that I need to make an AJAX request with the information provided in URL Parameters, but I need to make this AJAX request from a component that is not a descendant of a component being rendered by <Match>. Currently I will have to parse these information from the location path.  Context does not work either, because it will only go downstream.

**Comment by alisd23** [comment]
This seems more of a design issue to me. If you want to access the url params from a `match` **higher up** the component tree than the match component itself - well that doesn't really conform with React's 'top-down' approach as you said.

You'd probably need some external store to do what you want to do. Something like **Redux** or **MobX**. There you could store the url params in that `store` when the match happens, then the state can be accessed from anywhere, including your components higher up in the tree.
