### ISSUE TITLE
Documentation for this.context.router methods

### ISSUE THREAD

**Issue by jtulk** [ReactTraining/react-router#3998]
Sorry if I'm asking this in the wrong place, but I'm looking for direction as to where I can find documentation for the `router` object made available in `this.context.router` within a React component. 

<img width="722" alt="screen shot 2016-10-05 at 1 24 17 pm" src="https://cloud.githubusercontent.com/assets/2204260/19135450/4ec86812-8b00-11e6-9caa-4e8c587d1c15.png">

I can't seem to find it in the docs (although I can find sporadic documentation describing some of these methods scattered around). Just by playing around I'm discovering that a good chunk of these methods are deprecated, but I can't find any guidelines on what to use instead, or how they should have been used to begin with.

**Comment by pshrmn** [comment]
https://github.com/ReactTraining/react-router/blob/master/docs/API.md#contextrouter
