### ISSUE TITLE
How to access request headers after route has matched. 

### ISSUE THREAD

**Issue by TiagoCardoso1983** [ReactTraining/react-router#4012]
I'm having a hard time deciding whether this is a bug, missing feature, or just undocumented. 

I'm rendering on the server-side using react-router and authentication. As most people, I have a `onEnter=requireAuth` set up, which will look for a token in the `localStorage`, which is not defined on the server. So far I got it. The problem is that, everywhere I look for, I get suggestions on using react context, `typeof document == undefined` and the like. 

The way I see it, a request has been made to the server. The request passed from express (in my case) to the routing layer. The request contains (or not) an `Authorization` header which might contain (or not) the necessary JWT. I would like to access the request header, look for the jwt and use it to build my authenticated homepage when `typeof document == undefined`. 

How can I do it? Because so far, I didn't manage to achieve visibility on the routing layer to the request and its headers.

**Comment by timdorr** [comment]
You need to pass the request object into React somehow. There are a number of potential ways to do that, but this doesn't have to do with React Router.

**Comment by TiagoCardoso1983** [comment]
And where is the documentation on how to do that? I only have the routes object, which matches routes in my express app. How can I pass the the request while matching? I guess it'll have to come to that.
