### ISSUE TITLE
Router methods API?

### ISSUE THREAD

**Issue by wzup** [ReactTraining/react-router#4014]
Can't find `router` methods API. Do you have one? Could you pls provide a link.

Specifically, I'd like to know what `transitionTo` method does. How it is different from other transition methods, like `go`, `replace` and `push`.  Detailed API for those methods would also be nice.

The use case is as follows.

I use `withRouter` HoC with a component: `withRouter(MyComponent)`. 
It adds `router` as a prop, `this.props.router`:

![react router - google chrome 2016-10-08 14 00 37](https://cloud.githubusercontent.com/assets/3880497/19210823/4899b43e-8d60-11e6-9d1b-5bc9c78868ee.png)

So what is the difference between those methods: `go`, `replace`, `push`, `transitionTo`? Also where may I find detailed info about all the other methods listed?

**Comment by pshrmn** [comment]
Those are all methods of the `history` object [0]. `transitionTo` was removed in v2.8.0 and `replace` should be used instead [1].

[0] https://github.com/mjackson/history/blob/v2.x/docs/GettingStarted.md#navigation
[1] https://github.com/ReactTraining/react-router/blob/master/CHANGES.md#v280
