### ISSUE TITLE
Miss inside Miss does not work

### ISSUE THREAD

**Issue by Ciantic** [ReactTraining/react-router#4016]
Consider I have two apps, one in /OtherApp, but then main app which takes rest of the urls:

```javascript
import * as React from "react";
import { render } from "react-dom";
import { HashRouter, Match, Miss, Link } from "react-router";

const OtherAbout = () => (
    <div>
        <h3>Other About</h3>
    </div>
)
const OtherNoMatch = ({ location }) => (
    <div>
        <h3>Other app 404</h3>
        <p>Sorry but didn’t match any pages</p>
    </div>
)
const OtherApp = ({ pathname }) => {
    return <div>
        <h2>OtherApp</h2>
        <Match exactly pattern={`${pathname}/About`} component={OtherAbout} />
        <Miss component={OtherNoMatch} />
    </div>;
}


const MainAbout = () => (
    <div>
        <h3>Main About</h3>
    </div>
)
const MainNoMatch = ({ location }) => (
    <div>
        <h3>Main app 404</h3>
        <p>Sorry but didn’t match any pages</p>
    </div>
)
const MainApp = () => (
    <div>
        <h2>Main App</h2>
        <Match exactly pattern="/About" component={MainAbout} />
        <Miss component={MainNoMatch} />
    </div>
)

class App extends React.Component<any, any> {
    render() {
        return <HashRouter>
            <div>
                <Match pattern="/OtherApp" component={OtherApp} />
                <Miss component={MainApp} />
            </div>
        </HashRouter>;
    }
}
render(<App />, document.querySelector('#root'));
document.body.style.display = "block";
```

/OtherApp/About -> OK (Other App's about page as expected)
/OtherApp/notfound -> OK (Other app's 404 as expected)
/About -> OK (Main apps about page as expected)
/notfound -> ERROR Does not work as main apps 404. Instead it shows me empty page.

Is this a bug? The MainApp should have it's own Miss IMO to cleanly separate the concerns.

**Comment by pshrmn** [comment]
`<Miss component={MainApp} />` should be `<Match pattern='/' component={MainApp} />`. This will create a new `<MatchProvider>` for the `<MainApp>`.

Putting a `<Match>` inside of a `<Miss>` messes with the miss/match system because they share the same `<MatchProvider>`. If a `<Match>` inside of a `<Miss>` matches, then the `<Miss>` will no longer render its component. This in turn means that the `<Match>` will also not render.

For example, while you can navigate directly to the `/About` page with your provided code, you cannot navigate from the root (`/`) to `/About`. This only works when navigating directly because the `<MatchProvider>` does not get updated after the `<Match component={MainAbout} />` component is rendered.

```javascript
// go to localhost:3000/#/, then click the "About" link
const MainApp = () => (
  <div>
    <h2>Main App</h2>
    <Link to='/About'>About</Link>

    <Match exactly pattern="/About" component={MainAbout} />
    <Miss component={MainNoMatch} />
  </div>
)
```

**Comment by pshrmn** [comment]
To directly answer your question about a `<Miss>` inside of a `<Miss>`, the reason that that doesn't work is that `notifySubscribers` is never called after the first `<Miss>` has rendered, so the nested `<Miss>`'s subscriber function is never called and it never re-renders.

One case where it _should_ render would be when navigating from one miss to another (`/` to `/notfound`). However, this does not work with the current release because of an optimization where subscribers aren't notified if there were no matches and there still are no matches.

Commit #3980 dropped that optimization, so that type of transition will work with the next release of v4. That said, I just wouldn't recommend using `<Miss>` as a catch all. I know that the "Ambiguous Matches" example does something like that, but even that would run into issues with nested matches (unless you wrap the `<Miss>`'s child component in a `<MatchProvider>`, but since it isn't a default export, I'm guessing that wouldn't be encouraged).

**Comment by Ciantic** [comment]
@pshrmn I think I tried this `<Match pattern='/' component={MainApp} />` but the problem is then both OtherApp and MainApp matches. We need #3994 to deal with this then.

**Comment by pshrmn** [comment]
Ah, yes, I overlooked the double render. I guess that it is mostly a weird situation because it is bending what I think of as a miss (no matches) to being "try these other `<Match> components when no other `<Match>`es matched" (the exclusive issue).

**Comment by ryanflorence** [comment]
Yeah, I can't even think about what should happen if you put `Match` inside of a `Miss`. I'd put `MainApp` at `/`, not in `Miss`, it's not intended to be used as a "default case", its an "exceptional case". The "default case" is `<Match pattern="/" exactly/>`

**Comment by ryanflorence** [comment]
@kwelch can you move your comment (https://github.com/ReactTraining/react-router/issues/3994#issuecomment-252946797) over here and delete it from there?

**Comment by kwelch** [comment]
I have this same problem but I took a slightly different approach due to the #4016 issue. For the record, I am not proud of this solution so I would love a better approach. Using the Example above here is how I fixed this problem at at deeper a level. 
```
class OtherApp extends React.Component {
  render() {
    const matchA = matchPattern('a', this.props.location, false, this.context.match.pattern);
    const matchB = matchPattern('b', this.props.location, false, this.context.match.pattern);
    const matchC = matchPattern('c', this.props.location, false, this.context.match.pattern);
    const displayDefault = !matchA && !matchB && !matchC;
   return (<div>
      <h1>Other App header</h1>
      {matchA && <ComponentA />}
      {matchB && <ComponentB />}
      {matchC && <ComponentC />}
      {displayDefault && <DefaultView hasNesting='true' />}
    </div>);
  }
}

**Comment by ryanflorence** [comment]
Can you show me the urls and the components you want to render (along with their nesting)? For whatever reason I can't think of what you're trying to do from a product perspective.

**Comment by kwelch** [comment]
Here is a high-level of what I have now focused mainly on the `Events` tree, but similar pattern could be used for `Users`.

`/` ->
```
<Title />
<Header />
<Match '/events'><EventLayout /></Match>
<Match '/users'><UsersLayout /></Match>
<Miss><NotFoundPage/></Miss>
<Footer />
```
`/events` ->
```
<Match '/:id'><EventDetail /></Match>
<Match exactly '/'><EventList /></Match>
```

`/events/:id` -> 
```
!this.props.event -> <NotEventFound />
<Match 'confirmation'><EventConfirmation /></Match>
<Miss? ><DetailView />
```

DetailsView -> 
```
<Match 'register'>
  <RegistrationForm>
    <DynamicForm />
    <Match 'payment'><PaymentForm/></Match>
  </RegistrationForm>
</Match>
```

**Comment by ryanflorence** [comment]
Looks like maybe we need to work on the docs for `exactly` and how to couple nested UI to nested URLs. Unless I'm mistaken, this is what you're after.

```jsx
const App = () => (
  <Router>
    <div>
      <Title />
      <Header />
      <Match pattern="/events" component={EventLayout}/>
      <Match pattern="/users" component={UsersLayout} />
      <Miss component={NotFoundPage}/>
      <Footer />
    </div>
  </Router>
)

const EventLayout = ({ pattern }) => (
  <div>
    <Match pattern="/:id" component={EventDetail}/>
    <Match exactly pattern={pattern} component={EventList} />
  </div>
)

const EventDetail = ({ pattern }) => (
  <div>
    <Match pattern={`${pattern}/confirmation`} component={EventConfirmation} />
    <Match exactly pattern={pattern} component={DetailView} />
  </div>
)

const DetailsView = ({ pattern }) => (
  <div>
    <Match pattern={`${pattern}/register`} component={Register}/>
  </div>
)

const Register = ({ pattern }) => (
  <div>
    <RegistrationForm>
      <DynamicForm />
      <Match pattern={`${pattern}/payment`} component={PaymentForm}/>
    </RegistrationForm>
  </div>
)
```

**Comment by kwelch** [comment]
I will try that again, the DetailView had issues rendering when pathname was `/events/:id/register`

I will let you know. Thanks!

**Comment by pshrmn** [comment]
@ryanflorence The issue with @Ciantic's case was that they don't want an exact match on `/`. They wanted all routes that weren't matched by the other apps to share some common "main app" UI, which is why they were placed in a separate component.

```javascript
const OtherApp = ({pathname}) => (
  <OtherUI>
      <Match pattern={`${pathname}/about`} component={OtherAbout} />
      <Miss component={OtherMiss} />
  </OtherUI>
)

const MainApp = ({pathname}) => (
  <MainUI>
    <Match pattern={`${pathname}/about`} component={MainAbout} />
    <Miss component={MainMiss} />
  </MainUI>
)

const App = () => (
  <Router>
    <Match pattern='/other' component={OtherApp} />
    <Miss component={MainApp} />
  </Router>
)
```
Then, any view for a URL that doesn't begin with `/other` would have the UI provided by `<MainUI>`. The solution is probably just that each route that wants the main UI should wrap its component in it. I'm not sure if there is some more complex case that makes this undesirable

```javascript
const MainMiss = () => (
  <MainUI>
    404
  </MainUI>
)

const MainAbout = () => (
  <MainUI>
    About
  </MainUI>
)

const App = () => (
  <Router>
    <Match pattern='/other' component={OtherApp} />
    <Match pattern='/about' component={MainAbout} />
    <Miss component={MainMiss} />
  </Router>
)

**Comment by Ciantic** [comment]
@pshrmn exactly, and you've changed the MainApp to be the preciesly reason I want to do it.

The "apps" can be then plugged in to any URL path, regardless if they are in there or not. Even in the root path.

**Comment by ryanflorence** [comment]
Can you do a table of URL -> components you want to render, I'm not getting this.

**Comment by Ciantic** [comment]
I think there is no simpler code than the one above.

One develops apps like this: 

```
const MainApp = ({pathname}) => (
  <MainUI>
    <Match pattern={`${pathname}/about`} component={MainAbout} />
    <Miss component={MainMiss} />
  </MainUI>
)
```

and they can live in all subdirs now, except in the root if others share it.

**Comment by Ciantic** [comment]
Okay once more, I'll try to explain:

Let's not think about MainApp, it's confusing name cause any of the apps could be main app.

```
const OtherApp = ({pathname}) => (
  <OtherUI>
      <Match pattern={`${pathname}/about`} component={OtherAbout} />
      <Miss component={OtherMiss} />
  </OtherUI>
)

const FancyApp = ({pathname}) => (
  <FancyUI>
    <Match pattern={`${pathname}/about`} component={FancyAbout} />
    <Miss component={FancyMiss} />
  </FancyUI>
)

const ThirdApp = ({pathname}) => (
  <ThirdUI>
    <Match pattern={`${pathname}/about`} component={ThirdAbout} />
    <Miss component={FancyMiss} />
  </ThirdUI>
)

const App = () => (
  <Router>
    <Match pattern='/other' component={OtherApp} />
    <Match pattern='/fancy' component={FancyApp} />
    <Match pattern='/third' component={ThirdApp} />
  </Router>
)
```

How can I one day decide I want to plug ThirdApp (maybe even in some other package) to the "/" root? We need exclusive for that

**Comment by Ciantic** [comment]
I hope I'm being clear here, I think @pshrmn got it.

**Comment by ryanflorence** [comment]
okay I think I get it now. I'm working on a `<MatchGroup/>` that will only match one `<Match/>` which is the same as "exclusive" for the group.

**Comment by Ciantic** [comment]
Oh great! Sounds like just the feature. I don't see a need for exclusive attribute if immediate Matches in MatchGroup match only the first one in order.

**Comment by kwelch** [comment]
@ryanflorence I attempted your suggestion in the [comment above](https://github.com/ReactTraining/react-router/issues/4016#issuecomment-252959974), but having the `exactly` on the `EventDetail` is not allowing it nested components to be rendered. 

Any ideas? I may have to go the `MatchGroup` route.

**Comment by Ciantic** [comment]
@kwelch that is what exactly means, it matches only that url and not nested ones. There is no feature to do this yet, MatchGroup is the way when it's available.
