### ISSUE TITLE
Miss location is undefined

### ISSUE THREAD

**Issue by carnevalle** [ReactTraining/react-router#4018]
## Version
4.0.0-alpha.4

## Steps to reproduce
I just installed a brand new version of create-react-app (0.6.1)

Installed react-router (^4.0.0-alpha.4) and history (^4.3.0)

Replaced the contents of the index.js with the code below.

Ran `npm start`

```
import React from 'react'
import { render } from 'react-dom'
import { BrowserRouter, Miss } from 'react-router'

const NoMatch = ({ location }) => (
  <div>
    <h2>Whoops</h2>
    <p>Sorry but {location.pathname} didn’t match any pages</p>
  </div>
)

const App = () => (
  <BrowserRouter>
    <div>
      <Miss component={NoMatch}/>
    </div>
  </BrowserRouter>
)

render(<App/>, document.querySelector('#root'))
```

## Expected Behavior

I expected it to render the pathname that didn't match any pages.

## Actual Behavior

Instead I got: `Uncaught TypeError: Cannot read property 'pathname' of undefined`

I tried to recreate the problem here:
http://codepen.io/troelsjohnsen/pen/WGzXaw

But the code works fine in the codepen.

**Comment by carnevalle** [comment]
If I add a Match-component, it receives the location object just fine. I have been trying to debug through the code, but I don't have enough knowledge to understand where the chain jumps off.

```
const Home = ({location}) => {
  console.log(location);
  return (
    <div>
      <h2>Home</h2>
    </div>
  )
}

const App = () => (
  <BrowserRouter>
    <div>
      <Match exactly pattern="/" component={Home} />
      <Miss component={NoMatch}/>
    </div>
  </BrowserRouter>
)
```

**Comment by ryanflorence** [comment]
Why would you ever render a Miss without any Matches? Just render whatever you want to render.

I guess we maybe warn a miss was rendered without any matches, not sure how much code that would take and if it's even worth it.

**Comment by carnevalle** [comment]
I am not trying to render a Miss without a Match. I just wanted to provide the minimum example to reproduce the error. Sorry for the confusion :-) 

I got the error when trying the example from the quick start guide.

**Comment by ryanore** [comment]
@carnevalle I saw the same thing working with 4.0.0-alpha.4 yesterday.
Removing  {location}  from the arguments actually made it work for me.  The Match component is  not behaving  this way, just the Miss

`const NoMatch = () => (
  <div>
    <h2>Whoops</h2>
    <p>Sorry but {location.pathname} didn’t match any pages</p>
  </div>
)`

**Comment by carnevalle** [comment]
@ryanore 

Confirmed. 

Removing {location} from the arguments from the Miss component makes the code function without errors. Match component works well with or without {location} in the arguments.

**Comment by ryanflorence** [comment]
Ah, `<Miss/>` needs to use `LocationSubscriber`

**Comment by alisd23** [comment]
Yep this also causes an issue with things like Redux connect, which implements `shouldComponentUpdate`

`Miss` never renders in the following example:

```js
const App = () => (
  <div>
    <h1>Home</h1>
    <Match pattern='/' exactly component={Home} />
    <Miss component={NotFound} />
  </div>
)

class Blocker extends React.Component {
  shouldComponentUpdate() {
    return false; // For whatever reason i.e. connect seeing store has not changed 
  }
  render() {
    return <App />  
  }
}

ReactDOM.render(
  <BrowserRouter>
    <Blocker />
  </BrowserRouter>,
  document.getElementById('container')
);
```

I can look into this today.

**Comment by alisd23** [comment]
Maybe it's not the problem I think it is... Opened an issue for the problem above - #4035

**Comment by ryanflorence** [comment]
follow #4035
