### ISSUE TITLE
Expose history

### ISSUE THREAD

**Issue by alisd23** [ReactTraining/react-router#4021]
If the idea of `v4` is to have a smaller API but accompanied by small addon libraries, wouldn't it be better if the `history` object is more readily available, for example on `context`. The only thing exposed at the moment is a `router` object with a few methods.

I think this would make it easier for addon libraries (e.g. react-router-redux #3879) to implement their functionality (e.g. listening for route changes).

It seems to me that the only way to get at the history at the moment is by wrapping the `StaticRouter` and making a new router component, whereas I think exposing history on context would be a simpler approach.

*Thoughts on this?*

**Comment by philholden** [comment]
Also struggling to see how to updates route onClick. I need this for tabs and don't want to Links in tab headings.

**Comment by alisd23** [comment]
Yeah I agree, I think there's a valid case for wanting access to history methods *(push, go, etc...)* as you say. 

For people who aren't using Redux (where history methods would be available from `react-router-redux`), or something similar, there is **no way** to access these methods easily, without creating a custom router component.

**Comment by ryanflorence** [comment]
redux story is coming, this is an alpha.

**Comment by timdorr** [comment]
This is already provided via react-history, which 4.0 uses: https://github.com/ReactTraining/react-history/blob/master/modules/History.js#L10-L18

**Comment by alisd23** [comment]
@timdorr Didn't spot that, cheers!
