### ISSUE TITLE
Link does not respect hashType when creating href

### ISSUE THREAD

**Issue by herrkris** [ReactTraining/react-router#4022]
Hey everyone!

I hope you don't mind bringing up this issue with you gals and guys but I'm a bit uncertain on how to correctly deal with the new hash router, perhaps it's a bug, perhaps I'm doing it wrong (which accounts for 90% of the times).

So, just a quick summary: 

## Version
4.0.0-alpha.4

## Test Case
http://jsbin.com/wusefegiva/edit?js,output

## Steps to reproduce
Create a `Link` inside a `HashRouter` component

## Expected Behavior
The anchor's href attribute should have a hash link respecting the defined hashType

## Actual Behavior
A "plain" link without any hash is rendered

When I click the link everything works as expected only the rendered `href` value is not as expected. I expect the output for `<Link to="/a">A</Link>` to be something like `<a href="#/a">A</a>` but unfortunately it currently looks like this: `<a href="/a">A</a>`.

While looking at the `StaticRouter` component I saw that `createHref` has a [default value](https://github.com/ReactTraining/react-router/blob/v4.0.0-alpha.4/modules/StaticRouter.js#L23) which just returns the path.

I expect that HashRouter provides it's own createHref method, but perhaps I'm mistaken and you folks have thought of another solution?

**Comment by alisd23** [comment]
Hey, good find.

It looks like there is no hash-specific `createHref` method. I assume the only reason for the links `href` currently is to give the link browser behaviour:
- link styles
- right-click ➔ open in new tab

however the *open in new tab* option won't work currently because of this issue.

We could simply provide this as the `createHref` for `HashRouter`:
```js
const createHref = path => `#${path}`
```

**Comment by timdorr** [comment]
Yeah, it looks like that needs to be added here: https://github.com/ReactTraining/react-router/blob/v4.0.0-alpha.4/modules/HashRouter.js#L15-L23

A PR would be appreciated!
