### ISSUE TITLE
`search` is empty while `query` is not for <Redirect/>

### ISSUE THREAD

**Issue by halt-hammerzeit** [ReactTraining/react-router#4023]
Version: `2.8.1` (latest as per filing this issue).
Behaviour: `search` is empty while `query` is not for `<Redirect/>`
Expected behaviour: `search` corresponding to the `query`.

On this line:
https://github.com/ReactTraining/react-router/blob/c3cd9675bd8a31368f87da74ac588981cbd6eae7/modules/createTransitionManager.js#L100

```js
redirectInfo { pathname: '/', query: { a: 'b' }, state: null }
```

No `search` parameter in `redirectInfo`

**Comment by ryanflorence** [comment]
I don't understand. What does your `<Redirect/>` look like?

**Comment by halt-hammerzeit** [comment]
The Redirect is a generic one

```js
<Redirect from="/foo" to="/bar"/>
```

It's not the point of whether the `<Redirect/>` is unusual.
The point is that `redirectInfo` contains `query` parameter with URL parameters yet it doesn't contain the corresponding `search` parameter. In this case it should have been:

```js
redirectInfo { pathname: '/', query: { a: 'b' }, search: '?a=b', state: null }
```

**Comment by ryanflorence** [comment]
is `search` included in other location objects across router v2?

**Comment by halt-hammerzeit** [comment]
I guess it is since

```js
{JSON.stringify(this.props.location)}
```

Gives me

```js
{"pathname":"/","search":"?a=b","hash":"","state":null,"action":"POP","key":"9govif","query":{"a":"b"},"$searchBase":{"search":"?a=b","searchBase":""}}
```

On a `react-router`ed page.

**Comment by ryanflorence** [comment]
Our limited time is being spent on 4.0, but if you need this fixed, we will happily merge a pull request.

**Comment by halt-hammerzeit** [comment]
Ok, I think I'll pass

**Comment by Lexicality** [comment]
@halt-hammerzeit I just ran into this and had an exciting time debugging how the history library works.
Make sure you import `createMemoryHistory` etc from `'react-router'` rather than directly from `'history'`

**Comment by halt-hammerzeit** [comment]
@Lexicality Oh wow, what do you know...
