### ISSUE TITLE
Missing "children" prop feature in <Miss>

### ISSUE THREAD

**Issue by stnwk** [ReactTraining/react-router#4026]
So, the `<Match>` Component takes a prop `children` which allows the following:

``` js
<Match children={({ matched, ...rest}) => (
  {/* Animate will always render, so you can use lifecycles
      to animate its children */}
  <Animate>
    {matched && (
      <Something {...rest}/>
    )}
  </Animate>
)}/>
```

As taken from the current v4 docs.

The function provided via this `children` prop will **always** be rendered, regardless whether it's a match or not - allowing to use lifecycle hooks in `<Animated>` to animate the content e.g. using `ReactCSSTransitionGroup`.

Unfortunately this prop is missing in the `<Miss>` component, making it unpossible to use lifecycles to animate it. Would be nice to add it.

**Comment by ryanflorence** [comment]
thanks, yeah the rendering code was once shared, i'm going to share it
again with a new component so match and miss composition is easier for
others too

**Comment by supasate** [comment]
Hi @ryanflorence. While the rendering code is not shared, I've made a fix to add the children prop for <Miss> at PR #4140. 

It's my first time here if there is anything wrong, please advise.

**Comment by supasate** [comment]
@ryanflorence I've made a PR to fix this issue (while the rendering code is not shared yet). I'm new here. Please advise if there's anything wrong.

**Comment by mjackson** [comment]
`<Miss>` is gone in the current v4 branch. Closing.
