### ISSUE TITLE
How to create a pinterest style modal in React Router v4

### ISSUE THREAD

**Issue by gabrielbull** [ReactTraining/react-router#4029]
I was trying to make a modal like the pinterest modal (https://github.com/ReactTraining/react-router/tree/master/examples/pinterest) but felt short of any clever ideas on how to make them using v4.

Any one has successfully implemented one yet?

**Comment by timdorr** [comment]
You would put the `modal` flag in your `location.state`. That isn't transmitted to the URL, so it'll switch to `undefined` (a falsey) value when you refresh the page.

**Comment by ryanflorence** [comment]
this is an example i've intended to have, just fyi

**Comment by dakt** [comment]
I would really love to see this example. So far I always end up with unnecessary re-rendering and data fetching by using children prop in <Route /> component.

**Comment by marekkobida** [comment]
@gabrielbull Can you please send me your final example? I will be very grateful.

**Comment by kdenz** [comment]
A demonstration will be nice!

**Comment by zhirzh** [comment]
The example is now [here](https://github.com/ReactTraining/react-router/tree/bd147e88c9a162f740fb7f9cd4a218343603e3ee/examples/pinterest)

Please use [canonical links](https://help.github.com/articles/getting-permanent-links-to-files/)
