### ISSUE TITLE
Nested <Match> need to be wrapped in another component in v4

### ISSUE THREAD

**Issue by gabrielbull** [ReactTraining/react-router#4030]
Take this example:

```jsx
<Match pattern="/users" children={() => (
  <div>
     <Match pattern="create" component={CreateUser}/>
     <Match pattern="delete" component={DeleteUser}/>
  </div>
)}/>
```

It would be nice to not have to wrap the children. It would also be nice to be able to provide the  children as React elements and not be forced to use a function. Like this:

```jsx
<Match pattern="/users">
  <Match pattern="create" component={CreateUser}/>
  <Match pattern="delete" component={DeleteUser}/>
</Match>
```

**Comment by ryanflorence** [comment]
If we did that then we'd have to make `react-dom` a dependency (because we'd have to make the div). This way we work on all platforms, web, native, vr (?).

**Comment by gabrielbull** [comment]
@ryanflorence would it work with an array?

```jsx
<Match pattern="/users" children={() => [
  <Match key="1" pattern="create" component={CreateUser}/>
  <Match key="2" pattern="delete" component={DeleteUser}/>
]}/>
```

**Comment by ryanflorence** [comment]
No, because match doesn't render anything, but you can make your own match w/ a div wrapping its children with a couple lines of code and use that. Compose!

**Comment by jedwards1211** [comment]
I wonder if React will some day allow returning an array of children from `render`?

**Comment by just-boris** [comment]
According to [this](https://github.com/acdlite/react-fiber-architecture#child-and-sibling), the new Fiber algorithm will support multiple children as a result of `render`.

But this is quite very long-term perspective, so you can't rely on it in current solutions, however you can hope that eventually it will become better.

**Comment by jedwards1211** [comment]
Cool!

**Comment by jonas-db** [comment]
Is there currently another way to nest routes with react router v4 then the one shown in the first post?
I find a lot of examples like this:

```
    <Route path="/" component={App}>
      <Route path="/repos" component={Repos}/>
      <Route path="/about" component={About}/>
    </Route>
```

However, v4 is not like this anymore because it uses `Match` instead, right?

**Comment by pshrmn** [comment]
@jonas-db You would include those child routes in the `<App>` component. 

**note:** I am writing this using relative paths which are not supported, but hopefully will be in the near future.

```js
const App = () => (
  <div>
    <Switch>
      <Route path="repos" component={Repos} />
      <Route path="about" component={About} />
    </Switch>
  </div>
)
```
