### ISSUE TITLE
Pass all props placed on Match

### ISSUE THREAD

**Issue by kennetpostigo** [ReactTraining/react-router#4031]
I'm currently using `alpha.4` of react-router and using the Match component and thought that I could place props on it and they would transfer to the component prop:

```js
<Match pattern={`${this.props.pathname}/:rad`}
       component={ViewComponent}
       open={this.state.open} 
       showSource={() => this.showSource()}/>
```

so given that I thought that match would pass the props `open` and `showSource` to the `ViewComponent`. It did not however. A good workaround I found was to do the following:
```js
<Match pattern={`${this.props.pathname}/:rad`}
        render={() => <ViewComponent open={this.state.open} showSource={() => this.showSource()}/>}/>
```

Basically use the `render` prop instead and place them on the component in that fashion.

Is there anyway that Match automatically place the props that we put on it as props to the component prop?

I may be over looking something completely 😅 .

**Comment by ryanflorence** [comment]
You arrived at the correct solution. We may want to add props to `Match`, if we proxy them to your component, we'll break things: therefore, `render` prop.

You can wrap Match and pass along all props if you want. It's all Just React™

https://github.com/ReactTraining/react-router/issues/3826#issuecomment-246892331

**Comment by nfarina** [comment]
I've just encountered this same desire - so far I have nine instances of `<Match>` and I have to use the `render` method on all of them because I need to pass props from the parent. It works fine, but `render` is a bit more complicated looking and verbose.

Perhaps something like `<Match component={WelcomePage} componentProps={pageProps}>`?

**Comment by ryanflorence** [comment]
again, use composition https://github.com/ReactTraining/react-router/issues/3826#issuecomment-246892331

**Comment by nfarina** [comment]
Thanks for the pointer - I appreciate the consideration but I generally stay away from "customizing" frameworks like this; I always end up regretting it, and the next dev will wonder why I didn't do it "the right way". I'll just continue using `render`.

**Comment by ryanflorence** [comment]
Rendering a match in one component or another is not customizing anything, it's composition. Match's API is designed for this kind of composition, it's completely intentional for you wrap Match, as many of the examples in the repo already do 😊

**Comment by jonathanphz** [comment]
I get and error when I try to use render for Match like this: 

`<Match  exactly pattern={`${pathname}`}  render={() => {
       <Intro buttonClick={this.buttonClick} />
 }}/>`


Error: MatchProvider.render(): A valid React element (or null) must be returned.

I'm probably doing something really dumb because I'm just starting out using React.

**Comment by pshrmn** [comment]
@jonathanphz Questions should be posted to StackOveflow, but yours does have a simple answer.

Your arrow function with curly brackets does not return anything. Either include a return statement or, for an implicit return, wrap your return value in parentheses (or nothing at all it your code fits on one line).

```js
<Match exactly pattern={${pathname}} render={() => <Intro buttonClick={this.buttonClick} /> }/>
```

**Comment by jonathanphz** [comment]
Thanks for the help.
