### ISSUE TITLE
How to not match a pattern v4

### ISSUE THREAD

**Issue by gabrielbull** [ReactTraining/react-router#4032]
Say I have two matches like this:

```jsx
<Match pattern="add" component={AddUser}/>
<Match pattern=":id" component={ViewUser}/>
```

the second pattern matches the first one. Is there a way in v4 for this to work?

**Comment by ryanflorence** [comment]
https://react-router.now.sh/ambiguous-matches

though a `<MatchGroup/>` component is coming and will make this less nutty.

**Comment by gabrielbull** [comment]
+1 for the MatchGroup, using the Miss component is indeed crazy.

**Comment by ryanflorence** [comment]
I'm sticking with nutty 🔩

**Comment by gabrielbull** [comment]
Fixed.
