### ISSUE TITLE
[V4] <Match> / <Miss> children

### ISSUE THREAD

**Issue by jampy** [ReactTraining/react-router#4033]
According to the docs, [`<Match>`](https://react-router.now.sh/Match) and [`<Miss>`](https://react-router.now.sh/Miss) can only be configured using props and don't seem to expect any children.

Is there a good reason not to support (also) something like this?

```jsx
<Match pattern="/foo">
  <SomeComponent>
    <div>
      Hello "foo"
    </div>
  </SomeComponent>
</Match>

<Match pattern="/bar">
  This is Bar!
</Match>

<Match pattern="/baz">
  <ComplexComponent
    what="ever"
    style={myStyle}
    coord={123}
    optimize={true}
    matrix={myMatrix}
  />
</Match>
```

I understand that this way the component does not receive props from Match/Miss, but for static routes (no `:param`) and for static content (for example, the `This is Bar!` text) this makes it much more readable, IMHO.

**Comment by jampy** [comment]
Additional use case:

```jsx
<Match pattern="/config">
  <ConfigFrame>
    <Match pattern="/config/foo" component={FooConfig} />
    <Match pattern="/config/bar" component={BarConfig} />
    <Match pattern="/config/baz/:id" component={BazConfig} />
  </ConfigFrame>
</Match>
```

**Comment by timdorr** [comment]
Match supports children. It's at the bottom of the page you linked. The reason we take a function is so the React Element doesn't have to be instantiated unless the Match matches. In your example, the child components are always instantiated, even if the pattern doesn't match.

**Comment by ryanflorence** [comment]
@jampy some more notes on why: https://gist.github.com/ryanflorence/a301dc184f75e929a263dc1e80399a28

**Comment by jampy** [comment]
Thanks @timdorr and @ryanflorence for the hint. Makes a lot of sense performance-wise! :-)

>Match supports children. It's at the bottom of the page you linked.

But `children` must be a function. Using simple React components like in my example above  (accepting the performance risks you mentioned) leads to low level errors.

**Comment by ryanflorence** [comment]
You should have gotten a propType warning: https://github.com/ReactTraining/react-router/blob/v4/modules/Match.js#L111

**Comment by jampy** [comment]
indeed

so, no components as childs
