### ISSUE TITLE
Unknown prop `params` on <a> tag. Remove this prop from the element

### ISSUE THREAD

**Issue by raulrene** [ReactTraining/react-router#4036]
So I want to pass some parameters on a `<Link>` and I've done the following:

` <Link params={{ id: item.id}} to={'/trip/3'}>Book trip</Link>`

It works, but I always get a warning in the console: 
**Warning: Unknown prop `params` on <a> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop**

Is there a way around this using react-router? Thanks

**Comment by pshrmn** [comment]
This is happening because the `params` prop is being added as a prop to the `<a>` that the `<Link>` makes. You can include additional information through the `state` property of the [location](https://github.com/ReactTraining/react-router/blob/master/docs/Glossary.md#locationdescriptor)

```javascript
<Link to={{ pathname: '/trip/3', state: { id: item.id } }}>
  Book trip
</Link>
```

**Comment by raulrene** [comment]
@pshrmn Thank you very much, the first solution worked. I didn't need to add parameters in the href, I just needed to pass some data
