### ISSUE TITLE
Show loading state onEnter async is not yet resolved

### ISSUE THREAD

**Issue by arthurvi** [ReactTraining/react-router#4043]
I do async authentication in the onEnter function.
```js
export default async function requireAuth(nextState, replace, callback) {
	const user = await getCurrentUser();

	if(!user) {
		replace({
			pathname: '/login',
			state: {
				nextPathname: nextState.location.pathname
			}
		})
	}

	callback();
}
```
```js
<Route path="/app" component={App} onEnter={requireAuth}>
```

But how can I show a loader or spinner or anything when the requireAuth function is not yet resolved?

**Comment by timdorr** [comment]
You have to do that within your route component then. Nothing renders until the onEnter hook resolves, so it's only useful if you don't intend to show a loading state. If you do, then you need to let the component mount and show a loading state itself.

**Comment by arthurvi** [comment]
@timdorr ok thanks!

**Comment by ddela-cr** [comment]
@arthurvi is this actually working for you? For some reasons, replace function doesnt redirect me to /login when no user is found. But if I put it before the async getCurrentUser(), I get redirected... any idea? thanks
