### ISSUE TITLE
yarn doesn't resolve to the beta releases 

### ISSUE THREAD

**Issue by volkanunsal** [ReactTraining/react-router#4048]
I'm using the `beta` release, version 3.0.0-beta.1. When I install this via npm, everything works as expected, but when I run `yarn`, it loads the uncompiled version of the library. I'm not sure what your release process entails, but I thought I'd report it here since it seems to be only happening with this repo, and for this particular release tag. 

This is the relevant bit in the `yarn.lock` file.

```
react-router@beta:
  version "3.0.0-beta.1"
  resolved "https://registry.yarnpkg.com/react-router/-/react-router-3.0.0-beta.1.tgz#eb3019587da65ac77c12cf6ab790d408247ad5af"
  dependencies:
    history "^3.0.0"
    hoist-non-react-statics "^1.2.0"
    invariant "^2.2.1"
    loose-envify "^1.2.0"
    warning "^3.0.0"

```

**Comment by timdorr** [comment]
You are likely using Webpack 2, which can use ES modules. We ship a version with only the import/export statements uncompiled. Everything else is compiled. This is expected.

**Comment by volkanunsal** [comment]
> You are likely using Webpack 2

No, I'm using 1.13.2 actually.

**Comment by volkanunsal** [comment]
This issue is still happening. It has nothing to do with Webpack, but probably with the way Yarn installs packages. It's a bit of a mystery to me right now, but I found this snippet about Yarn's architecture that explains it a little bit.

The [install process](https://code.facebook.com/posts/1840075619545360) is broken down into three steps:

> 
> Resolution: Yarn starts resolving dependencies by making requests to the registry and recursively looking up each dependency.
>
> Fetching: Next, Yarn looks in a global cache directory to see if the package needed has already been downloaded. If it hasn't, **Yarn fetches the tarball for the package and places it in the global cache so it can work offline and won't need to download dependencies more than once.** Dependencies can also be placed in source control as tarballs for full offline installs.
>
> Linking: Finally, Yarn links everything together by copying all the files needed from the global cache into the local node_modules directory.

So, my guess is that the tarball of the beta release is not compiled, and so when we run `yarn add react-router@beta`, it takes the beta branch –– which must be uncompiled –– and caches it locally as a tarball.

I'm currently solving this by re-installing `react-router` after every call to `yarn add`, but I figured it's something you might like to do something about.
