### ISSUE TITLE
Automatically setting basename using <base href> is deprecated and will be removed in the next major release. The semantics of <base href> are subtly different from basename. Please pass the basename explicitly in the options to createHistory

### ISSUE THREAD

**Issue by nitish24p** [ReactTraining/react-router#4055]
Ok i know this is a previous issue too, but when i tried solving the issue with the suggestion given in the earlier issue, i was unable to so can someone please help me out 
```javascript
import React, { Component } from 'react';
import ReactDOM from 'react-dom';
import { createStore, combineReducers, applyMiddleware } from 'redux'
import { Provider } from 'react-redux'
import { Router, Route, browserHistory } from 'react-router';
import { syncHistoryWithStore, routerReducer } from 'react-router-redux'
import ReduxPromise from 'redux-promise';

import App from './components/App';
import Foo from './components/Foo';

import rootReducer from './reducers';



const createStoreWithMiddleware = applyMiddleware(ReduxPromise)(createStore);

const store = createStoreWithMiddleware(rootReducer, window.devToolsExtension && window.devToolsExtension());


const history = syncHistoryWithStore(browserHistory, store)



ReactDOM.render(
    <Provider store={store}>
    { /* Tell the Router to use our enhanced history */ }
    <Router history={history}>
      <Route path="/consult/ama" component={App} />
      <Route path="/consult/ama/foo" component={Foo}/>
    </Router>
  </Provider>,
  document.getElementById('mount-node')
);
```

I get the following error
```
Automatically setting basename using <base href> is deprecated and will be removed in the next major release. The semantics of <base href> are subtly different from basename. Please pass the basename explicitly in the options to createHistory
```

I tried using createHistory explicitly and pass a basename but to no avail. Can anyone help here.

**Comment by alisd23** [comment]
Try passing the `history` into the `<Router />` instead of `browserHistory.

**Comment by nitish24p** [comment]
Sorry that was a typo.. updated the code.. i had passed history.. still getting the same

**Comment by alisd23** [comment]
Not sure, check versions and simplify until it starts working.

**Comment by nitish24p** [comment]
```
"react": "^15.3.2",
    "react-dom": "^15.3.2",
    "react-redux": "^4.4.5",
    "react-router": "^2.8.1",
    "react-router-redux": "^4.0.6",
    "redux": "^3.0.4"
```

**Comment by alisd23** [comment]
I don't think this is an issue with react-router. Try to get as close to the [react-router-redux example](https://github.com/reactjs/react-router-redux#tutorial) as possible. I can't see something obviously wrong from your code.

**Comment by alisd23** [comment]
Maybe try reinstalling dependencies as well

**Comment by nitish24p** [comment]
Ok so the react app is only on 1 route which is part of an entire symfony app. I use nginx as the server config. So my site doesnt have a "/" path the home path for my site is actually "/consult" which is redirected to another repository via nginx and then in "/consult/ama" i have the react app set up. Can this error be possibly because of this configuration?

**Comment by alisd23** [comment]
Possibly, that does seem like quite a unique setup... Have you got a `<base href="..." />` tag in your html? Sounds like your issue might be caused by a similar thing to (this issue)[https://github.com/ReactTraining/react-router/issues/3387#issue-151180128]

**Comment by nitish24p** [comment]
Ahh yes.. that seemed to be the issue.. was extending another parent file.. .. Closing.. Thanks @alisd23
