### ISSUE TITLE
how to reload current page

### ISSUE THREAD

**Issue by RifeWang** [ReactTraining/react-router#4056]
i want to reload the current  page after updating some data in form , so i write like this:
`browserHistory.push('current page url')`, but i find that it doesnt work .

**Comment by alisd23** [comment]
That will replace the current url, which will re-render your `Route` components. What do you mean by it 'doesn't work'?

**Comment by alisd23** [comment]
I don't think this is a react-router issue, as this `push` is very well tested. Closing for now until there's more info.

**Comment by RifeWang** [comment]
@alisd23 i mean that my data doesn't update when i  `browserHistory.push('current page url')`

**Comment by RifeWang** [comment]
@alisd23 it re-rendered my Route component, but the data that i updated show like before, i think it maybe cookie problem

**Comment by alisd23** [comment]
If the Route component re-rendered then it's doing its job properly :+1:
How you handle state in those route components is nothing to do with the router.

**Comment by RifeWang** [comment]
i use `window.location.reload()` , the data will update

**Comment by kenchengch** [comment]
Thanks @RifeWang window.location.reload() is work for me. But refresh whole page is not a good idea.....

**Comment by amol-c** [comment]
`window.location.href`

**Comment by gilesbradshaw** [comment]
window.location.reload - is reloading your entire page - ie refetching the page from the server and starting again from scratch

**Comment by m3talstorm** [comment]
I was looking for the same solution, being able to completely reload the page/browser as if the (physical) user was visiting it for the first time. I needed this because I wanted to clear down all memory/state/etc from the page when a user logged out so nothing is leaked.

**Comment by tkvw** [comment]
You can use a `refresh` route. 
```
const Refresh = ({ path = '/' }) => (
    <Route
        path={path}
        component={({ history, location, match }) => {
            history.replace({
                ...location,
                pathname:location.pathname.substring(match.path.length)
            });
            return null;
        }}
    />
);
```
Usage: 
```
<Refresh path="/refresh"/>
```
Now you can push to history with the url prefixed with `/refresh` and it will rerender the route (this happens because Refresh route uses a component which forces remount of component) .  

`history.push('/refresh/')` => Reloads `/`
`history.push('/refresh/posts?user=tkvw')` => Reloads `/posts?user=tkvw`

The `/refresh/` urls won't be visible in the history because they are replaced.

**Comment by Titiiii** [comment]
Hi guys, i have a problem when i refresh a current page, it return to a home page!!!
someone can help me please!
in advance thanks
