### ISSUE TITLE
[v4] <Miss /> and SSR res.status

### ISSUE THREAD

**Issue by lvauvillier** [ReactTraining/react-router#4060]
Is there a way to return a http 404 status if no route matches on server side ?

The new declarative API `<Match />` `<Miss />` is great but i do not see how to properly get the status of the final SSRendered page.

My workaround is to add a `<Status code={}>` component into `<Miss>` children and rewind it at the end to know the final status.

I there a more elegant solution ?

**Comment by alisd23** [comment]
Have you checked the [react-router 4 server rendering example](https://react-router.now.sh/ServerRouter)? It shows how to deal with no matches on the server.

**Comment by lvauvillier** [comment]
This is exactly what i needed... I don't believe i missed it...
Thanks @alisd23

**Comment by alisd23** [comment]
No problem :+1:
