### ISSUE TITLE
No reducer provided for key "routing"

### ISSUE THREAD

**Issue by dukedougal** [ReactTraining/react-router#4061]
I've updated all my packages for various reasons and now my app won't start.

Two errors are in the console:

```
No reducer provided for key "routing"
Uncaught TypeError: (0 , _reactRouterRedux.syncHistory) is not a function
```

The wording of these errors seems to suggest they have something to do with the router and redux.

I thought I was using react router without integration with redux, so I'm puzzlked as to what these errors are.

Can anyone suggest what I can do to get them resolved and get my app going again please?

thanks

**Comment by alisd23** [comment]
Please post the code of where you create the `Router`

**Comment by alisd23** [comment]
You're using `react-router-redux` by the looks of it, check that out first - https://github.com/reactjs/react-router-redux
