### ISSUE TITLE
Exports from V4

### ISSUE THREAD

**Issue by donnieflorence** [ReactTraining/react-router#4062]
Hello,

I recently started using React Router V4, Which is by far freaking awesome! I noticed how I could import modules in the following manners:
```js
import { Link } from 'react-router';

// OR

import Link from 'react-router/Link';

```

I know how to do the first when creating a library but I'm not sure at all how to distribute a module that allows imports the second way. Is there an article or guide that you can point me to that goes through how to distribute npm modules to support both types of import formats that are shown above?

**Comment by timdorr** [comment]
This is just referencing the file in the npm package. We [move everything out of the `modules` directory when compiling with babel](https://github.com/ReactTraining/react-router/blob/v4/package.json#L19). That's all there is to it.

**Comment by ryanflorence** [comment]
Donnie Florence? Are we cousins?

**Comment by donnieflorence** [comment]
@ryanflorence I don't think so but do you have roots in Australia?
