### ISSUE TITLE
[v4] basename for server-side rendering

### ISSUE THREAD

**Issue by frux** [ReactTraining/react-router#4068]
Hello! My application has a base url ``/console``. So I have the following routers
```jsx
<BrowserRouter basename="/console">
	<App appData={appData}/>
</BrowserRouter>
```
```jsx
<ServerRouter location={location} context={context}>
	<App appData={appData}/>
</ServerRouter>
```

When I want to create an index link to ``/console/`` I do
```jsx
<Link to="/">home</Link>
```

But it renders differently for server and for browser. So I got error:

![2016-10-19 20-45-49](https://cloud.githubusercontent.com/assets/4231003/19526476/fe7e409a-963d-11e6-8aaf-fd538794d92e.png)

Is there any way to do a basename on server-side?

**Comment by pshrmn** [comment]
Have you tried just adding a `basename` prop to your `<ServerRouter>`? Looking at the `ServerRouter.js` source , it appears that any additional props passed to the `<ServerRouter>` get appended to the `<StaticRouter>` (which uses the `basename` in its `createHref` function).
https://github.com/ReactTraining/react-router/blob/v4/modules/ServerRouter.js#L16

**Comment by frux** [comment]
I'm sorry. I lust saw propTypes and didn't found basename there. So I thought it doesn't support it.

**Comment by pshrmn** [comment]
@mjackson @ryanflorence any reason for `basename` not to be an explicitly defined prop of the `<ServerRouter>`?

**Comment by pshrmn** [comment]
Created a PR for this (#4070)
