### ISSUE TITLE
v4 - unit testing

### ISSUE THREAD

**Issue by tomitrescak** [ReactTraining/react-router#4078]
Hi, how can I approach unit testing of layouts containing Match components? I noticed in your tests that you explicity provide "location" into match component. Yet, I feel it is not possible to use this when using with normal app?

[EDIT] in your docs on `location` you mention `If you don’t want to match the location on context, you can pass a location as a prop instead.`. Yet, when I add location to my component context it is not there. How can I set the location for Match? Thanks.

**Comment by pshrmn** [comment]
In the integration tests, components are wrapped by a `<MemoryRouter>` which is provided the `location`.

https://github.com/ReactTraining/react-router/blob/v4/modules/__tests__/integration-test.js

Would that work for what you're trying to do?

**Comment by tomitrescak** [comment]
Yes it would, thanks for that!

**Comment by ryanflorence** [comment]
wrap the UI you're testing in a MemoryRouter
