### ISSUE TITLE
React Router v4 code split with server rendering

### ISSUE THREAD

**Issue by dlebedynskyi** [ReactTraining/react-router#4084]
## Intro 
First thank you for all work you guys do with react router 4. it does look better and cleaner a lot now. I have one feature request(discussion)  - Code Split with webpack without react warning

## TL;DR 
How to do code splitting with react router v4 for both client and server side without react warnings about hash mismatch?

## Feature request

[quick and dirty code split](https://gist.github.com/acdlite/a68433004f9d6b4cbc83b5cc3990c194)

 **Problem**
while server will render content correctly due to synchronous nature or webpack 2 System.import ( or require.ensure webpack 1) -  client will be rendering null element, that leads to react complaining that it can not reuse markup. 

### react-router 2 hacks 
sample https://github.com/ryanflorence/example-react-router-server-rendering-lazy-routes/blob/master/modules/client.js#L12
uses hack for side effect  of rr2
```
match({ routes, location }, () => {
render( )//...
}
```
it _kinda_ works sometimes. 

### RR4 
How to do something like this in react-router 4? 
How to trigger webpack loading code before actual rendering? 

## Suggestion 
Could we have some kind or fetching done within BrowserRouter  that could handle cases with render returning a promise? Similar to what serverContext is doing on server but for render having a promise? 
```
<Match pattern="/async" render={System.import('./async').then(m=>m.default)} />
```

It would be really nice to have this ability out of the box.

**Comment by pshrmn** [comment]
I would argue that the server rendering async content on the first pass is **not** correct behavior. The first pass should always render `null` for asynchronously loaded components. If the component should render on the first pass, then it should be loaded synchronously. Changing the `asyncComponent`'s `componentWillMount` to `componentDidMount` will cause both the client and server to render `null` on the first pass.

**Comment by vimniky** [comment]
@dlebedynskyi Can you have a look of this project ? [code-split-component](https://github.com/ctrlplusb/code-split-component)

**Comment by dlebedynskyi** [comment]
@vimniky thanks for the link. it is basically same as above https://github.com/ctrlplusb/code-split-component/blob/master/src/index.js#L48 - load and save to state. 
tbh only time we have a warning is when you navigate to page that comes from chunk but was rendered on server - basically once on initial load. This is why match before was happening before any render at all.

**Comment by dlebedynskyi** [comment]
@pshrmn simple example for SSR - list page and details(article, profile or what ever 2nd level) page. details page is rendered from chunk. You do want this page to be rendered by server for all SSR reasons. Rendering null - well you might as well do not render at all.

**Comment by yormi** [comment]
I did read the whole thing but have you looked into: https://github.com/gabrielbull/react-router-server ?

**Comment by dlebedynskyi** [comment]
@yormi  this looks like some I was looking for. Thanks will check it out

**Comment by yormi** [comment]
@dlebedynskyi I just set up the data loading for server rendering and it
works pretty good for me so far :)

**Comment by dlebedynskyi** [comment]
@yormi  data loading is easy)

**Comment by ryanflorence** [comment]
We'll have docs about code splitting + server rendering eventually.

**Comment by drejohnson** [comment]
Any update on this for v4 beta.5?

**Comment by dlebedynskyi** [comment]
@drejohnson  I ended up using https://github.com/ctrlplusb/react-async-component

**Comment by drejohnson** [comment]
@dlebedynskyi Thanks, I'll look into this! A sample would be appreciated.

**Comment by bondz** [comment]
@dlebedynskyi please do 😄

**Comment by dlebedynskyi** [comment]
@drejohnson @bondz something like this https://github.com/dlebedynskyi/react-playground
FYI ignore all script stuff

**Comment by wellyshen** [comment]
Hi Guys, I also upgrade my [repo](https://github.com/wellyshen/react-cool-starter) to support the code-splitting of routes and server-side rendering with React-Router v4, enjoy it :)

**Comment by terencechow** [comment]
Also came across this link if ppl are interested:
https://medium.com/@apostolos/server-side-rendering-code-splitting-and-hot-reloading-with-react-router-v4-87239cfc172c
