### ISSUE TITLE
What do numbers mean in ComponentLifecycle.md guide?

### ISSUE THREAD

**Issue by wzup** [ReactTraining/react-router#4086]
What do these numbers mean? Could you please update the guide in order to eliminate the need to ask?

![react-router_componentlifecycle md at master reacttraining_react-router - google chrome 2016-10-22 14 32 58](https://cloud.githubusercontent.com/assets/3880497/19617491/a7e43b62-9864-11e6-91c5-a98142659406.png)

**Comment by alisd23** [comment]
Numbers in brackets just mean the order of when they lifecycle methods are called.
