### ISSUE TITLE
ReactCssTransitionGroup doesn't work with react-router

### ISSUE THREAD

**Issue by owenliang** [ReactTraining/react-router#4089]
```
import React from "react";
import ReactCSSTransitionGroup from "react-addons-css-transition-group";

export default class Container extends React.Component {
    constructor(props, context) {
        super(props, context);
    }

    componentWillMount() {
        document.body.style.margin = "0px";
        // 这是防止页面被拖拽
        document.body.addEventListener('touchmove', (ev) => {
            ev.preventDefault();
        });
    }

    render() {
        console.log(this.props);
        return (
            <div id="reactContainer">
                <ReactCSSTransitionGroup
                    transitionName="RouterTransition"
                    transitionEnterTimeout={2000}
                    transitionLeaveTimeout={2000}
                >
                    {
                        React.cloneElement(this.props.children, {
                            key: this.props.location.pathname
                        })
                    }
                </ReactCSSTransitionGroup>
            </div>
        );
    }
}

```

this is my router container component,  the transition doesn't work, and the console has a warning like this when switching route: 

> bundle-main-3babb664.js:1371 Warning: setState(...): Cannot update during an existing state transition (such as within `render` or another component's constructor). Render methods should be a pure function of props and state; constructor side-effects are an anti-pattern, but can be moved to `componentWillMount`. 

help, thanks~

**Comment by alisd23** [comment]
Is `this.props.children` always a single React element?

**Comment by timdorr** [comment]
You're keying on the location pathname, which is changing during the transition. You need to key your element on something else more constant, as the element is likely changing because of that key change.

**Comment by owenliang** [comment]
thanks, i will try~
