### ISSUE TITLE
Document programmatic/imperative routing

### ISSUE THREAD

**Issue by calebthebrewer** [ReactTraining/react-router#4094]
## Version
4.0.0-alpha.3

## Test Case
[The docs](https://react-router.now.sh/)

## Steps to reproduce
I was interested in programmatically routing somewhere new, which is documented well in [`v3`](https://github.com/ReactTraining/react-router/blob/master/docs/API.md#routercontext), but has not yet been added to the `v4` docs.

## Expected Behavior
Couldn't find anything in the docs.

## Actual Behavior
I'm not sure if there is some dark magic going on in my local stack, but I can't access `context.router` unless I specify the `contextType` like so:
```js
class MyComponent extends Component {
  static contextTypes = {
    router: PropTypes.object.isRequired
  }

  handleSomeEvent = () => {
    this.context.router.transitionTo('/somewhere-else')
  }
  ...
}
```
Though this may be obvious to folks familiar with the library, it caused me a bit of friction while getting started.

**Comment by alisd23** [comment]
Hi,
This is just part of the `context` api, a component needs to specify exactly the context it needs via `contextTypes`.

https://facebook.github.io/react/docs/context.html
