### ISSUE TITLE
Bug with latest release:

### ISSUE THREAD

**Issue by Berky115** [ReactTraining/react-router#4097]
## Version
2.0.0

## Test Case
http://colddigitalheart.com/

## Steps to reproduce
Visit link above

## Expected Behavior
site displays react components

## Actual Behavior
Failure to load, error:
ReactRouter.min.js:1Uncaught TypeError: Cannot read property 'getCurrentLocation' of undefined

**Comment by timdorr** [comment]
Downgrade to 2.8.1: https://unpkg.com/react-router@2.8.1/umd/ReactRouter.min.js

**Comment by andrejunges** [comment]
@timdorr I noticed that it's only happening when we don't provide one of the histories option..   
Is it a bug from 3.0 (there should be a default one) or it's required to pass a history?

If its required, we may have to fix the example in this page https://github.com/ReactTraining/react-router/blob/master/docs/guides/RouteConfiguration.md.

**Comment by machinelearningdeveloper** [comment]
I am curious about this issue as well.

**Comment by darknoon** [comment]
I also ran into this, feels like the framework should either throw a more explicit exception if you don't provide a history or keep the default from before.
