### ISSUE TITLE
Miss will always render null before rendering its component in BrowserRouter

### ISSUE THREAD

**Issue by timmolendijk** [ReactTraining/react-router#4104]
## Version

4.0.0-alpha.5
## Test Case

http://jsbin.com/qinahok/edit?html,js,output
## Steps to reproduce
- Set up a `BrowserRouter` that contains just a single rule: a `Miss` with an arbitrary non-empty component attribute.
- Open the page on any path.
## Expected Behavior

This router will end up in "missed" state in every scenario, and therefore `Miss`'s containing component is expected to be rendered in every scenario.
## Actual Behavior

When we inspect the initial render value of our `Miss` "route", we will notice that it is briefly empty (`null`, represented as a `react-empty` comment node or a `noscript` tag in React<15) before its containing component is rendered.
## Context

Not only is this behavior unexpected, it is also problematic in the scenario of universal/isomorphic rendering. In a situation where the server successfully renders the `Miss` route's containing component (for instance as a result of waiting for some prefetched data to come in), the client's initial empty render will destroy this server render before recreating it client-side:

> Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server: …

**Comment by pshrmn** [comment]
I don't think that this is a bug, just a side effect of the two pass nature of `<Miss>` components.

**Comment by alisd23** [comment]
Yep currently `<Miss>` components require 2 render passes to render. We're looking for a solution to that at the moment so I think it's worth keeping this issue open until we find one.

**Comment by zombieJ** [comment]
When use redux I found it needs more than 2 pass render if component has dispatch which cause tree  needs multi times render.
currently I use for loop to compare the resultHTML but I guess there is a better way to resolve that.

**Comment by larrxu** [comment]
This breaks server side rendering of react-router v4 Miss component with the react markup error.

**Comment by mjackson** [comment]
`<Miss>` is gone in current v4. Everything is doable in 1 pass now.

**Comment by larrxu** [comment]
Should we use Switch / Last Route for missed route now?

**Comment by larrxu** [comment]
Looks like the docs are updated but the package is not updated? When can we get this in alpha7?
