### ISSUE TITLE
Optional patterns returns a String with "undefined" as value when this pattern isn't set

### ISSUE THREAD

**Issue by rodrigobacelli** [ReactTraining/react-router#4113]
This is a weird bug. When I npm install RR@4.0.0-alpha.5, an optional pattern is returned as an String instead of not returning param at all. I think that this is a bundle bug, because I've cloned and npm linked RR4, built the files and it works proper.

## Version
4.0.0-apha.5

## Test Case
http://jsbin.com/toroxe/1/edit?html,js,console,output

## Steps to reproduce
Create a Route with optional params. Ex.: `<Match pattern="/param1/:param2?" component={Catalog} />`, and access the `/param1` route
## Expected Behavior
Return just `param1` as route parameter
## Actual Behavior
`param2` value is a String with `undefined` as content

**Comment by timdorr** [comment]
This was fixed in #4064. However, that version isn't yet released on npm. You'll have to install and build locally until we can get that released.

**Comment by rodrigobacelli** [comment]
We did a workaround to ignore those routes. Thx for the response
