### ISSUE TITLE
v3 - onEnter callback don't passing error to match callback

### ISSUE THREAD

**Issue by arkist** [ReactTraining/react-router#4114]
## Version

3.0.0
## Test Case

💖 
## Steps to reproduce

``` javascript
<someRouter onEnter=(nextState, replace, callback) => {
  callback(new Error('error!');
}/>

match({router, location}, (error, redirect, renderProps) => {
  console.error(error); // null
});
```
## Expected Behavior

match callback should catch error if onEnter callback passing error.
## Actual Behavior

on match's callback, error is null

it seems https://github.com/ReactTraining/react-router/pull/4063 causing this. 🤔

**Comment by timdorr** [comment]
Thanks for reporting! Let's track this in #4123
