### ISSUE TITLE
app.get("*"... shows no effect

### ISSUE THREAD

**Issue by Java-Jonas** [ReactTraining/react-router#4116]
Hello.
Even though I have this line of code in my express file:
`app.get('*', function (req, res) {
  res.sendFile(publicPath, "index.html")
})`
the side responds on a refresh of the page with:
Cannot GET .../foo.
I don't understand it and had a professional already looking into it. He couldn't understand why this happens as well. So i'm assuming it's a bug??
Here a link to the repository:
https://github.com/Java-Jonas/problem-with-react-router
Help is very appreciated. Thanks :)

**Comment by timdorr** [comment]
Check that you're requesting from the right server.`.../foo` isn't a valid path, so that might be the issue too.

**Comment by Java-Jonas** [comment]
/foo was just an example, i tried to not confuse anyone. What do you mean "requesting from the right server"? can you give me more information on that? :/

**Comment by pshrmn** [comment]
This isn't a React Router issue. You aren't correctly concatenating the filename. http://expressjs.com/en/api.html#res.sendFile
