### ISSUE TITLE
TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by steida** [ReactTraining/react-router#4135]
"react-router": "4.0.0-alpha.5"

I believe the `else if (typeofA === 'object') {` is insufficient check.

I'm not sure how to reproduce it but that's what sentry.io reports me. 

![screen shot 2016-11-02 at 21 58 44](https://cloud.githubusercontent.com/assets/66249/19947303/bb0588f4-a147-11e6-8202-dd1e6bd201d9.png)

**Comment by timdorr** [comment]
This is a `history` issue. And it's been fixed: https://github.com/mjackson/history/pull/381

**Comment by steida** [comment]
Just for the record, the wrong dependency was caused by yarn. npm installed dependency correctly.
