### ISSUE TITLE
URL pattern with undefined optional parameter in <Match>

### ISSUE THREAD

**Issue by iamciroja** [ReactTraining/react-router#4138]
"version": "4.0.0-alpha.5"

---

Documentation says that for 'pattern' property in <Match> we can use '_any valid URL pattern that path-to-regexp understands_'. So in particular (according to path-to-regexp docs) we can define optional params, something like:

`<Match pattern='/foo/:bar?' component={MyComponent} />`

and then in MyComponent we can access this.props.params.bar 

In the case when this optional component in URI is not supplied at all (i.e. when path=/foo) I would expect params.bar to be undefined. But instead I get **string** 'undefined' - like in the case when path=/foo/undefined

It seems that it's because in this case: 
1) path-to-regexp exec method returns array with undefined as element
2) in matchPattern.js (line 37) we use decodeURIComponent() function that returns string even if it's argument is undefined. So maybe in this line it would be better to replace
`params[keys[index].name] = decodeURIComponent(value);`
with
`params[keys[index].name] = value && decodeURIComponent(value);`

Or it's meant to work this way - and there's no reason to make changes?

**Comment by pshrmn** [comment]
Fixed in #4064, just not released yet.
