### ISSUE TITLE
React router server side not working correctly

### ISSUE THREAD

**Issue by WebTerminator** [ReactTraining/react-router#4142]
![screen shot 2016-11-03 at 00 02 00](https://cloud.githubusercontent.com/assets/4947347/20003456/7476e63e-a27e-11e6-9a20-4f66549ae71c.png)
I have managed to implement server side rendering with express and it almost works.
I say almost because of the following issue:

if I hit url like this http://localhost:8080 or like this http://localhost:8080/projects and I refresh it works as expected. The moment I hit a url like this: http://localhost:8080/projects/margam and I refresh the page then I get this error: "Uncaught SyntaxError: Unexpected token < bundle.js" .

routes.jsx

    import React from 'react';
    import { Route, Router, browserHistory } from 'react-router';
    import ReactDOM from 'react-dom';
    import Wrapper       from './../components/wrapper.jsx';
    import Home          from './../components/home.jsx';
    import Projects      from './../components/projects.jsx';
    import SingleProject from './../components/projectContent/singleProject.jsx';
    import About         from './../components/aboutUs.jsx';

    if(typeof window !== 'undefined') {
	console.log('here baby');
	ReactDOM.render((
		<Router history={browserHistory} >
			<Route path="/" component={Wrapper} >
				<IndexRoute component={Home} />
				<Route path="projects" component={Projects} />
				<Route path="projects/:id" component={SingleProject} />
				<Route path="about" component={About} />
			</Route>
		</Router>
	), document.getElementById('app'));
    }

server.js

    import express from 'express';
    import path from 'path';
    import React from 'react';
    import { renderToString } from 'react-dom/server';
    import { match, RouterContext } from 'react-router';
    import routes from './src/client/app/config/routes.jsx';

    let port = process.env.PORT || 8080;
    let app = express();

    app.use(express.static('src/client/'));

    app.get('*', (req, res) => {
     match(
       { routes, location: req.url },
       (err, redirectLocation, renderProps) => {

      if (err) {
        return res.status(500).send(err.message);
      }

      if (redirectLocation) {
        return res.redirect(302, redirectLocation.pathname + redirectLocation.search);
      }

      let markup;
      if (renderProps) {
        markup = renderToString(<RouterContext {...renderProps}/>);
        console.log(markup);
       } 
        return res.sendFile('index.html', {root : __dirname + '/src/client/'});
      }
     );
   });
 
     app.listen(port); 
     console.log('server started');

singleProject.jsx

     import React from 'react';

    import Video       from  './../video.jsx';
    import Overview    from  './overview.jsx';
    import Photography from  './photography.jsx';
    import Details     from  './details.jsx';
    import Cast        from  './cast.jsx';
    import Nav         from  './second-nav.jsx';

    import porgectsCollection from './../../data/projectInfo.js';

    import { StickyContainer, Sticky } from 'react-sticky';

     class SingleProject extends React.Component {
       getProjectDataFromUrl() {
        return porgectsCollection.filter(el => el.title === this.props.params.id);
      }
      render () {
  	let data = this.getProjectDataFromUrl(),
        project = data[0];
    return (
    	<section className="project-page">
        <StickyContainer>
          <Video project={project} />
          <Nav project={project} />
          <Overview project={project} />
          <Photography project={project} />
          <Details project={project}  />
          <Cast project={project} />
        </StickyContainer>
    	</section>
        );
      }
     }

       export default SingleProject;

this app has been deployed to heroku and the issue can be viewed at: https://aldemar-productions.herokuapp.com/

**Comment by timdorr** [comment]
This isn't a React Router issue. You're referencing your bundle as `public/bundle.js`, which is a relative URL. So, it's looking for that file in the wrong place: `projects/public/bundle.js`. Just add a slash in front to make it an absolute URL.

**Comment by WebTerminator** [comment]
Thank you
