### ISSUE TITLE
MIss

### ISSUE THREAD

**Issue by ralphsmith80** [ReactTraining/react-router#4144]
## Version
4.0.0-alpha.5

## Test Case
https://react-router.now.sh/Miss

## Steps to reproduce
Navigate to the missed route.

## Expected Behavior
location is passed to the Miss component

## Actual Behavior
No params/location available
An error is thrown attempting to access location.pathname since location is undefined.
`index.js:259 Uncaught TypeError: Cannot read property 'pathname' of undefined(…)`

Here's the JS I was using

```index.js
import React from 'react'
import { render } from 'react-dom'
import Match from 'react-router/Match'
import Miss from 'react-router/Miss'
import Link from 'react-router/Link'
import Router from 'react-router/BrowserRouter'

const App = () => (
  <Router>
    <div>
      <ul>
        <li><Link to="/missed">Home</Link></li>
      </ul>
      <Match pattern="/foo"/>
      <Match pattern="/bar"/>
      <Miss render={({ location }) => (
        <div>Nothing matched {location.pathname}.</div>
      )}/>
    </div>
  </Router>
)

render(<App/>, document.querySelector('#root'))
```

```package.json
{
  "name": "react-router-v4",
  "version": "0.1.0",
  "private": true,
  "devDependencies": {
    "react-scripts": "0.7.0"
  },
  "dependencies": {
    "react": "^15.3.2",
    "react-dom": "^15.3.2",
    "react-router": "^4.0.0-alpha.5"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  }
}
```

I used create-react-app to get started but I've only been running through the examples and Miss was the only issue I bumped up against. I realize this is alpha code, but I expect this has been working since it's documented and the embedded example works in the docs.

**Comment by pshrmn** [comment]
Should work after 3423b1d, just hasn't been published yet.

**Comment by gpltaylor** [comment]
I had the same issue. Spent a lot of time on this, thinking I had done something wrong. Upgraded to alpha.6 and this is working.
