### ISSUE TITLE
missing libraries [history, invariant, warning, esolve-pathname]

### ISSUE THREAD

**Issue by kedoska** [ReactTraining/react-router#4162]
## Version
4.0.0-alpha.5

## Steps to reproduce
 1. `creare-react-app ohGodOnEnterIsGone && cd ohGodOnEnterIsGone`
 2. `npm install react-router@next`

## Expected Behavior
include the library and start working with `{ BrowserRouter as Router, Match, Link, Miss }`

## Actual Behavior
The following modules are missed:
 * history
 * invariant
 * warning
 * resolve-pathname

I then installed those using npm and everything is ok now.
I also removed node_modules and `npm clear cache && npm install`

**Comment by timdorr** [comment]
That's something with your npm install. Those modules are all either directly required by the module or by a sub-module.
