### ISSUE TITLE
transitionTo encoding the url

### ISSUE THREAD

**Issue by vvstej** [ReactTraining/react-router#4163]
Hello ,

When using react router's transitionTo with query params, I send the params as {runs:"1|2|3"}
"|" being my delimiter. The transitionTo method encodes the "|" character and the resultant url looks like 
subruns=1%7C%7C2%7C3
While functionally I have no issues , Is there any way to let the router not to encode the params so that the url is readable?

Thanks,

**Comment by timdorr** [comment]
Supply your own query string parsing: https://github.com/ReactTraining/react-router/blob/master/upgrade-guides/v2.0.0.md#custom-query-string-parsing
