### ISSUE TITLE
Hang occurs when getComponent(s) returns an erroneous Component.

### ISSUE THREAD

**Issue by gearboxdesign** [ReactTraining/react-router#4165]
Hi guys,

This may be an incorrect use of the functionality, and perhaps being that it occurs when passing in components with errors precludes this from being recognised as an issue, but I have encountered an issue when using the getComponent(s) property of any given route.

The issue essentially stems from returning a valid React Component which happens to have an error. 

Of course the idea is for it not to have an error, but in terms of trying to debug and track down the issue in question, no mechanism seems to exist to catch any errors and report this back to either the console or command line (when running on the server for instance).

In my case I am returning a promise which I see from the source is acceptable but from my limited knowledge of its inner workings, I would expect since the promise technically resolves then the opportunity to catch the error at this point has lost, it would only become apparent as react actually attempts to render the components.

I may be approaching this all wrong, but essentially the requirement stems from the need to query an external source to gather the information required to resolve the promise with a single component, which this functionality seems to provide. Since this is an isomorphic implementation, I would rather retrieve the components using this method rather than load the component post render so that it is available for the initial render.

Note this all works great if the components returned are free of errors, I'm looking for a nice way of tracking down the issue in lieu of any logs.

The only work-around so far I have found is to defer the execution of the callback directly using process.nextTick on the server side which isn't ideal, this crashes out the application and gives me the error, but I have no idea how to catch the error at this point and handle as appropriate.

Thanks for the Router though, other than this issue its been a dream to use :)

**Comment by timdorr** [comment]
[The first arg of the callback function is if any error occurred](https://github.com/ReactTraining/react-router/blob/master/docs/API.md#getcomponentnextstate-callback). So, use that.

**Comment by gearboxdesign** [comment]
Perhaps I haven't articulated the issue very well, I'm aware of this but the problem goes beyond that, if I supply a component which doesn't expose the issue until the component is rendered, by this point my opportunity to pass the error into the callback as the first argument has gone.

To be clear then the component itself only reveals its errors once it goes through the lifecycle and render is called, e.g

<Route ... getComponent={ (nextState, cb) => {
  return gatherComponentData().then(data) {
    return BreaksOnRenderComponent
  });
} } />

Bits omitted for brevity here and returning a promise rather than using a callback here but the point is I don't know that the component is broken until it is rendered, for example an error in the render method.

If for instance BreaksOnRenderComponent didn't exist or at this point an error was thrown, the error would be thrown and the error handler would execute, if I was using a callback i could maybe try catch and throw the error into the cb as the first argument and then it's fine, but the issue is let's say that component does exist and the component itself is error free until it is rendered and an erroneous render method is called, at this point there is no error so I cant get the error to throw back into the callback...

Make sense?

**Comment by gearboxdesign** [comment]
Great half he code got stripped out in the comment!
