### ISSUE TITLE
support lazy loading with RR v4

### ISSUE THREAD

**Issue by Hotell** [ReactTraining/react-router#4167]
Are there any plans to support lazy loading like in RRv3 via `getComponent` and friends?

Something like 
```js
<Match 
  pattern="/lazy/foo" 
  getComponent={ ()=>System.import('./lazy/foo').then(module)=>module.default }
/>
```
or
```js
<LazyMatch 
  pattern="/lazy/foo" 
  render={ () => System.import('./lazy/foo').then(module) =>{
    const props = {...myProps};
    return <module.default {...props}/>;
  }
}
/>
```

would be nice.

Or is this rather meant to be implemented within [addons](https://github.com/ReactTraining/react-router-addons-routes) repo ?

thanks!

## Version
4.0.0

**Comment by timdorr** [comment]
There are a number of implementations for this already. This isn't the router's job to handle. It shouldn't be an addon, because it's also useful in a number of non-router contexts.

Here's an example I googled just now: https://gist.github.com/simenbrekken/cca4cf2104508e40dc004b29692bfabf
