### ISSUE TITLE
Strip Proptypes in production

### ISSUE THREAD

**Issue by pvorona** [ReactTraining/react-router#4169]
Hello, i've found here is used such approach of stripping propTypes:
```
if (__DEV__) {
  Component.propTypes = {
      a: PropTypes.string
  }
}
```

But threre is babel transformation which does exactly same thing https://www.npmjs.com/package/babel-plugin-transform-react-remove-prop-types. Maybe it's worth rewriting existing declaration without `if (__DEV__)`? I can do this pr

**Comment by timdorr** [comment]
We use this plugin to strip them: https://github.com/ReactTraining/react-router/blob/v4/package.json#L43

That converts `__DEV__` to `process.env.NODE_ENV !== 'production'`, which you should be setting in your production builds so things like React are built with all the dev stuff stripped out.

**Comment by pvorona** [comment]
But with transformation i've suggested we don't need to use `if` in code at all. Don't you think it's good for clarity?

**Comment by timdorr** [comment]
That won't work unless your project uses that transform. We have to ship code on npm that includes the proptypes so you can use them during development, but still mark them as removable for production builds. The NODE_ENV check does that.

**Comment by taurose** [comment]
Well, the transform does have a `wrap` mode which would do exactly that.

**Comment by timdorr** [comment]
Sure, but I don't want to rely on magic code transformations. If it stops working for some reason, we don't have any feedback that things are broken.
