### ISSUE TITLE
Trailing slash + `exactly`

### ISSUE THREAD

**Issue by pdhoopr** [ReactTraining/react-router#4170]
Hi there,

Apologies up front if this is the wrong place for this - wasn't quite sure what category this issue falls into so I figured I'd start here. Also, sorry if I've missed something obvious in my search for a solution or to see if this had already been answered elsewhere.

Basically, I'm starting a new project with **version 4.0.0-alpha.5** and have just a few routes right now:

```jsx
<Match exactly pattern="/" component={Dashboard} />
<Match exactly pattern="/users/:id" component={User} />
<Match exactly pattern="/login" component={LoginForm} />
<Miss component={NotFoundError} />
```

I'm using `exactly` pretty liberally because I want to be able to navigate to `/users/lol` and get the user `lol`'s page, but I don't want to navigate to `/users/lol/cats` and get the user `lol`'s page (rather, a 404), which is the behavior without `exactly`. So, this works well for my current use case.

However, I _do_ want to be able to go to `/users/lol/` with the trailing slash and have it show me the user `lol`'s page. As it stands now, the only way I can get it to work is to add another `<Match>`:

```jsx
<Match exactly pattern="/" component={Dashboard} />
<Match exactly pattern="/users/:id" component={User} />
<Match exactly pattern="/users/:id/" component={User} />
<Match exactly pattern="/login" component={LoginForm} />
<Miss component={NotFoundError} />
```

It could be that I'm just missing an obvious way to make this work, whether that be with some regex pattern or otherwise, but this is the only way I could get the behavior I'm looking for.

I have also downloaded the `path-to-regexp` package separately and been able to reproduce the behavior I want with this code:

```js
const pathToRegexp = require('path-to-regexp');
const keys = []
const re = pathToRegexp('/users/:id', keys, { end: true, strict: false });
```

From what I can tell, the difference between this code and React Router v4 is the `strict` option being set to `false`.

Thanks in advance for any help or feedback!

**Comment by Skilgarriff** [comment]
Just want to chime in here quickly - I'm running into the same issue without including the 'exactly' directive. Further, the issue is compounded by the fact that if I go to /About -> it takes me my About component. If I go to /doesnotexist -> it takes me to the Miss component and my 404 page. BUT if I go to /About/ then it takes me to none of the above :/.

**Comment by rlovato** [comment]
I second that this seems to be caused by the strict flag being sent to path-to-regexp. I cloned the repo and was experimenting with it. Setting strict to false breaks two of the unit tests, but on cursory glance, it seems to fix the problem.

**Comment by dictions** [comment]
For those looking for a work around for now, I'm using this:

```js
const RemoveTrailingSlash = ({location}) => {
  const {pathname} = location;
	
  if (pathname.substr(-1) === '/') {
    return <Redirect to={pathname.substr(0, pathname.length - 1)} />;
  } else {
    return null;
  }
};

<Router>
  <Match pattern="/" render={RemoveTrailingSlash} />
  ...
</Router>
```

**Comment by shendepu** [comment]
I work around by creating the route object twice, and change one of them with pattern empty string, then add both them into routes 


```
# PositionListRoute
export default (store) => {
  return {
    exactly: true,
    pattern : '/',
    component: PositionListContainer
  }
}
```

This is returns the routes array
```
export const createRoutes = (store) => {
  const indexRoute = PositionListRoute(store)
  indexRoute.pattern = ''
  return {
    routes : [
      indexRoute,
      PositionListRoute(store)
    ]
  }
}
```

**Comment by mjackson** [comment]
@pdhoopr Can you use `<Match exactly pattern="/users/:id/?" component={User} />` (or, with the current v4 branch `<Route exact path="/users/:id/?" component={User} />`) to make the trailing slash optional?

I still need more practice with the `path-to-regexp` API, but seems like it could work.

**Comment by pdhoopr** [comment]
@mjackson Thanks for the suggestion, just tried the following real quick:

`<Match exactly pattern="/login/?" component={Login} />`

This actually made it so the login component was never rendered; both `/login` and `/login/` ended up hitting the `<Miss />` component instead.

**Comment by porfirioribeiro** [comment]
I had this problem also, it's a pity, but found a way to work arround it
* Match `_url_/season` and `_url_/season/`
```jsx
<Match pattern={`${pattern}/season(/)?`} exactly component={SeasonList} />
```
* Match `_url_/season/add`, `_url_/season/add/` and `_url_/season/add/32`
```jsx
<Match pattern={`${pattern}/season/add(/)?:seasonId(\\d+)*`} exactly component={SeasonAdd} />
```
* Match `_url_/season/32`
```jsx
<Match pattern={`${pattern}/season/:seasonId(\\d+)`} exactly component={SeasonContainer} />
```

**Comment by rafrex** [comment]
According to the `path-to-regex` docs, the way to match a trailing `/` is by setting the `strict` flag to false. So @mjackson I think the solution is in how you implement `path-to-regex` in `react-router`.

In the mean time, this works for me:
```javascript
<Switch>
  <Route exact path="/:userid" component={UserProfile} />
  <Route exact path="/:userid/:postid" component={Post} />
  <Route render={({ history }) => (
    (history.location.pathname.slice(-1) === '/') ?
      <Redirect to={history.location.pathname.slice(0, -1)} /> :
      <PageNotFound />
  )} />
</Switch>

**Comment by Phoenixmatrix** [comment]
Seconded the above. strict:false seems to be the way to go. Seems to be the normal Express-like behavior from using their [express route tester](http://forbeslindesay.github.io/express-route-tester/)

Maybe there's a good reason to deviate from it, but optional trailing slash seems to be a very very common requirement, and should at a minimum be configurable, but I think it should be the default.

**Comment by mjackson** [comment]
I'd be grateful if someone would make a PR that sets `strict: false` and see what breaks. I seem to recall having a specific reason for using `strict: true`, but can't put my finger on it right now... :/

In any case, seems like there's definitely something that needs to change here.

**Comment by pshrmn** [comment]
@mjackson It would probably make sense to add a `strict` prop to `<Route>` to let users control this.

```js
<Route path='/foo/' strict={false} component={Foo} />
```

**Comment by rafrex** [comment]
@mjackson I created a pull request that adds a `strict` boolean prop to `Route` (if the strict prop is omitted it defaults to `true`). See #4357 

```js
// this will match both /foo and /foo/
<Route exact path="/foo" strict={false} component={foo} />
```

**Comment by mjackson** [comment]
Thanks, @rafrex! Let's follow up in #4357

**Comment by leite08** [comment]
If you got here looking to remove the trailing slash at the end of all URLs in React Router 4, this comment might help you:
https://github.com/ReactTraining/react-router/issues/4841#issuecomment-349096723
