### ISSUE TITLE
Document `routes` injected prop

### ISSUE THREAD

**Issue by jethrogb** [ReactTraining/react-router#4172]
The `routes` prop is [injected](https://github.com/ReactTraining/react-router/blob/6eeb7ad358f987520f5b519e48bdd31f725cbade/modules/RouterContext.js#L64), but this is [not documented](https://github.com/ReactTraining/react-router/blob/master/docs/API.md#injected-props).

**Comment by timdorr** [comment]
Please create a PR to add those docs. Thanks!

**Comment by jethrogb** [comment]
Why has this been closed? It hasn't been fixed.
