### ISSUE TITLE
best way to call async method before transition

### ISSUE THREAD

**Issue by ruifortes** [ReactTraining/react-router#4173]
I know the preferred way is to do async work in the componentDidMount hook and render the target component in a waiting state.
When waiting times are low and the unavailable content is substantial there is a annoying flicker in the transition because of the rapid interpolation of the waiting UI.
I'm want to do all async data fetching before the transition (eventually rendering current component in a waiting state) and only do the transition when data returns.
Is there a preferred way to do this?

**Comment by timdorr** [comment]
You can run your async code and in whatever callback runs after it's complete, do your transition there.

```js
fetch(url).then(data => this.context.router.transitionTo('/somewhere'))
```

**Comment by ruifortes** [comment]
Sorry for the extreme delay.

I understand that I can do it that way but since react-router is managing the transitions it would be nice to have some static method in the component that could be called before transition (eventually setting setting some state in current component) in order to just use a simple link.
