### ISSUE TITLE
Parameter lost after navigating with React-router on Multilingual app

### ISSUE THREAD

**Issue by peshoicov** [ReactTraining/react-router#4176]
I have a routes setup, simplified version of which is this one:

```js
// define the routes for each language ..
const InnerRoutes = (
    <Route>
        <IndexRoute page="home" component={InnerPage}></IndexRoute>
        <Route path="(:page)" component={InnerPage}></Route>
    </Route>
);

// define the routes for all the languages, using InnerRoutes .. 
const AllRoutes = (
    <Router history={browserHistory}>
        <Route path='/' component={App} language="bg">
            {InnerRoutes}
            <Route path=":lang" language="en">
                {InnerRoutes}
            </Route>
        </Route>
    </Router>
);

// and render our app ..
ReactDOM.render(
    AllRoutes,
    document.getElementById('app')
);
```

So, when I open "/en/team" - I have in "InnerPage" component two props - "lang" and "page".
When after that I navigate to "/en/sport" - I have only the "page" property. The other one gets lost, although the same component is used.

**Comment by timdorr** [comment]
Don't make :page optional. It's matching the route before :lang can.

**Comment by peshoicov** [comment]
It's still not working. Changing `(:page)` to `:page` gives the same result: after navigation I get only the `page` property and the `language` one gets lost.
