### ISSUE TITLE
How do I use the imperative API instead of the Redirect component?

### ISSUE THREAD

**Issue by Industrial** [ReactTraining/react-router#4179]
Hi!

I'm not really in tune with the new way redirection works with `react-router`. I would much rather give my action creators control over when to dispatch a redirect action then having to keep specific store state upon which to decide to show one part of the application or the other.

I don't want a website where I'm hiding the public part of the site after you log in to `/admin`. I would much rather have a website where it just redirects me to `/admin` after logging in but nothing else.

The API used to be `dispatch(reactRouter.hashHistory.push(uri))`. How do I do this now? I am using `<HashRouter/>`.

**Comment by EdgarOrtegaRamirez** [comment]
@Industrial for a temp solution I use the [history](https://github.com/mjackson/history) module directly

```js
import { createHashHistory } from 'history'
const history = createHashHistory()
history.push('/new-path')
```

**Comment by timdorr** [comment]
You can compose things together. Create a component that lives under the Router and pulls it off context and puts it into a global that can be accessed anywhere. 

I'll have a pre-packaged solution for this in react-router-redux soon.

**Comment by Industrial** [comment]
@timdorr Hi!

Is there an update on this?

**Comment by Industrial** [comment]
@EdgarOrtegaRamirez This works.

**Comment by Huxpro** [comment]
From my practices, I found the easiest way is to use `withRouter` to let a component get reach to `history` object and invoke imperative APIs on it.

```js
// Where you render the Some
withRouter(Some)

// Some.jsx
Some = ({history}) => <div onClick={history.push(url)}/>
```
