### ISSUE TITLE
I just want 'window.location.href=window.location.href' ,what should I do?

### ISSUE THREAD

**Issue by eddyzhang1986** [ReactTraining/react-router#4181]
I just want 'window.location.href=window.location.href' ,what should I do?

when I use window.location.href=window.location.href ,the browser not refresh 

I just want refresh the page

**Comment by mbrevda** [comment]
what version are you on? `window.location.href=window.location.href` works just fine here

**Comment by timdorr** [comment]
Yes, use the location.reload() method.

**Comment by eddyzhang1986** [comment]
@mbrevda @timdorr 
thanks a lot , I use 'window.location.reload()' instead .
