### ISSUE TITLE
Nested Miss-component throws an error

### ISSUE THREAD

**Issue by carnevalle** [ReactTraining/react-router#4182]
So, I am playing around with React Router v4. 

I am trying to have some code run on every url-change and unaware of how to achieve this, I tried to follow the path of wrapping my App in a container, so I could grab the historyContext and listen for changes.

This is what I did:

```
class AppContainer extends Component {

  constructor(props) {
      super(props);
  }

  render(){
    return (
      <div>
        <Match pattern="/" exactly component={Home} />
        <Match pattern="/about" component={About} />
        <Match pattern="/topics" component={Topics} />
        <Miss component={NoMatch}/>  
      </div>
    )
  }
}

const App = () => (
  <BrowserRouter>
      <Match pattern="/" component={AppContainer} />
  </BrowserRouter>
)

const NoMatch = ({ location }) => (
  <div>
    <h2>Whoops</h2>
    <p>Sorry but {location.pathname} didn’t match any pages</p>
  </div>
)
```
(I have removed code not relevant for the example in the above)

The above codes runs fine in v4.0.0-2, but it throws an error in v4.0.0-alpha.5. The problem is with the Miss-component. It throws an `Uncaught TypeError: Cannot read property 'pathname' of undefined`.

## Version
4.0.0-alpha.5

## Test Case
I have created two codepens demonstrating the issue working

Working - 4.0.0-2
http://codepen.io/troelsjohnsen/pen/QGNedy

Not working - 4.0.0-alpha.5
http://codepen.io/troelsjohnsen/pen/ENKqav/

## Steps to reproduce
See Codepen.

**Comment by timdorr** [comment]
This is fixed already, just isn't released. Wait on another alpha or pull directly from GitHub for now.
