### ISSUE TITLE
react-router 3.0.0 push/replace state -> pop

### ISSUE THREAD

**Issue by medz** [ReactTraining/react-router#4183]
In the 3.0 version of react-router, either push or replace jump routing, will render twice the component. I use the push function to jump to url, then the target page will trigger a push, and then pop.
<img width="1231" alt="qq20161114-0 2x" src="https://cloud.githubusercontent.com/assets/5564821/20260787/23f36e60-aa96-11e6-8b55-ef6cf350b242.png">
<img width="1203" alt="qq20161114-1 2x" src="https://cloud.githubusercontent.com/assets/5564821/20260786/23f355e2-aa96-11e6-8621-19c05d5268c8.png">

**Comment by medz** [comment]
This problem does not exist in version 2.x.

**Comment by timdorr** [comment]
Do you have another history instance in use somewhere? Are you using a library like react-router-redux? This is something with history library underneath, so it's probably how you are using it.

**Comment by medz** [comment]
@timdorr 
 Thanks,
Yes, I use the re-redux component and have a <Provider store = {store}> <Route> ... </ Route> </ Provider> `on the top of the routes. -redux-router, component of the render function will be implemented twice, print the log `this.props.location.status` first try` PUSH` state, the second is the `POP` state, but I did not update the routing The upper store.

**Comment by fantua** [comment]
Got same problem
