### ISSUE TITLE
Feature Request: <Link>: add a way to imperatively trigger it

### ISSUE THREAD

**Issue by gre** [ReactTraining/react-router#4184]
I have an example app that have a NEXT and a PREV button. I've nicely used a Link for them.
Now, I want to add keyboard left/right binding to trigger the same `to={{ path, ... }}` target of my Link.
I want to re-use the same `to` of my Link, and not having to write it twice.

So, one way I've "fixed" this is by doing:

`<Link ref="next" />`

and then `findDOMNode(this.refs.next).click()` but I wish I could just do something like `this.refs.next.trigger()`.

---

What do you think of this idea?

**Comment by gre** [comment]
a bit answering myself now:

Maybe there is a way to think and solve this problem in a more descriptive way?
Like I could implement my own `<LinkAndHookKeyboard to={..}  keyboardBinding="meta shift left" />`

But still, I feel having a way to just trigger a Link by ref, is nice.

**Comment by pshrmn** [comment]
This isn't a `<Link>` issue.

If you want to navigate when a key is pressed, you should be adding an event listener that listens for key presses, checks the keycode, and pushes the next/prev location to the `router` (which is available through the context).

I'll include some code below that shows what I'm talking about. I think that it will work, but I haven't tested it.

```js
class KeyDown extends React.Component {

  componentDidMount() {
    document.addEventListener('keydown', this.props.event, false)
  }

  componentWillUnmount() {
    document.removeEventListener('keydown', this.props.event, false) 
  }

  render() {
    return null
  }
}

const View = ({ pathname }, { router }) => {
  // somehow determine the next/prev locations
  const nextLoc = '/next'
  const prevLoc = '/prev'
  return (
    <div>
      <KeyDown event={(event) => {
        const { keyCode } = event
        if (keyCode === 37) {
          router.transitionTo(prevLoc)
        } else if (keyCode === 39) {
          router.transitionTo(nextLoc)
        }
      }}/>
      <Link to={prevLoc}>Previous</Link>
      <Link to={nextLoc}>Next</Link>
    </div>
  )
}
```

**Comment by gre** [comment]
Interesting way :)
