### ISSUE TITLE
RouteConfiguration guide uses outdated syntax

### ISSUE THREAD

**Issue by danoc** [ReactTraining/react-router#4185]
## Version
3.0.0

## Steps to reproduce
Copy and paste example from the first guide:
https://github.com/ReactTraining/react-router/blob/master/docs/guides/RouteConfiguration.md#route-configuration

## Expected Behavior
Expected application to render.

## Actual Behavior
```
Uncaught TypeError: Cannot read property 'getCurrentLocation' of undefined(…)
```
<img width="1439" alt="screenshot 2016-11-14 14 11 29" src="https://cloud.githubusercontent.com/assets/916038/20284950/42da9d70-aa74-11e6-8dca-3028bb050c3b.png">

## Fix

Add `history={browserHistory}` to the outer `<Router>` in the first example:
https://github.com/ReactTraining/react-router/blob/master/docs/guides/RouteConfiguration.md#route-configuration

**Comment by timdorr** [comment]
It's not necessarily outdated, just simplified so we don't have to have tons of verbosity in there. Keeps things readable by reducing some cognitive load.
