### ISSUE TITLE
Initial history does not work if on iOS Chrome

### ISSUE THREAD

**Issue by 311chaos** [ReactTraining/react-router#4186]
## Versions
React Router - 4.0.0-alpha.5
iOS - 10.0.1 and 10.1.1
Chrome - 54.0.2840.91

## Test Case
No test case, but it is reproducible on the docs at https://react-route.now.sh

## Steps to reproduce
* on iOS Chrome, navigate to https://react-route.now.sh
* Click on any of the example links in the left hand nav (ie `URL Parameters`)
  * The page will load the content for the selected example
* Use browser back button (again, only seems to be an issue on Chrome on IOS). The page will not change content. 

## Expected Behavior
It should navigate back to the previous page

## Actual Behavior
* There is no navigation, the page flickers, but the old content remains.

## Other info
It seems like the initial history state for the browser does not get set on first load. In a top level component, in the `componentWillMount`, if I set:

```history.replaceState({}, 'Some page name', location.pathname)```

it will work normally.

**Comment by timdorr** [comment]
I believe this is being tracked on the `history` library here: mjackson/history#383

But I'm mistaken, please open up the appropriate issue over there since that's closer to the source of the problem.

**Comment by spicydonuts** [comment]
Is there any value in keeping this open until that PR is merged and `history` has been updated here in `react-router`?  It's hard to track otherwise.

**Comment by timdorr** [comment]
It's not a bug with Router, so no, we shouldn't keep this issue open.

**Comment by spicydonuts** [comment]
> It's not a bug with Router, so no, we shouldn't keep this issue open.

I just installed `react-router` and I have this bug. ¯\_(ツ)_/¯
I also, as an end user, will only see it fixed when there's a new `react-router` version.  How do I track if it's in the next version without digging through commits?  I get that the real issue is elsewhere, but this bug is present in projects using `react-router` until a change is made.  Seems like an issue is the right place to keep track of that change.
