### ISSUE TITLE
[react-router@^4.0.0-alpha.5], Link onClick={} causes a page reload rather than a simple history change

### ISSUE THREAD

**Issue by DimitarChristoff** [ReactTraining/react-router#4187]
Use case:

```js
const handleClick = () => {
  // do something
}

return <Link className='nav-item' to='/dashboard' activeClassName='is-active' onClick={handleClick}>Click me</Link>
```

the mere existence of the `onClick` handler with `activeClassName` seesm enough to bypass onclick handlers - the compiled module that comes via npm seems to have the apatheticToIsActive code and not rebuilt since 5b3f61945620682edfeb9c1b3b3f9fe36265ea60 

this is probably fine now but can't really confirm

**Comment by jaypea** [comment]
this is already fixed in https://github.com/ReactTraining/react-router/pull/4066 and will released with the next v4 release.

**Comment by benjamingeorge** [comment]
Is there any work around for this until the next release ?

**Comment by DimitarChristoff** [comment]
revert to beta4 worked for me.
