### ISSUE TITLE
How about give a name to the route?

### ISSUE THREAD

**Issue by farzer** [ReactTraining/react-router#4189]
for example:
```js
<Route path="/xxx/xxx" getComponent={Xxxxx} name="manage"/>
```

so that i can get the path from the props - `manage`

**Comment by timdorr** [comment]
We do not support named routes. Instead, you can create an object/module of strings and functions that contains your routes and use that as psuedo-named routes:

```js
export const index = '/'
export const about = '/about'
export const user = id => `/user/${id}`
```

Something sort of like that.
