### ISSUE TITLE
react-router 3.0.0 render bugs.

### ISSUE THREAD

**Issue by medz** [ReactTraining/react-router#4191]
更具 #4183 和 https://github.com/amazeui/amazeui-touch/issues/114 的反馈信息，我们做了测试，初步确定是react-router 3.0.0的bug.

**Comment by medz** [comment]
react-router 3.0.0 push/replace state -> pop

**Comment by medz** [comment]
https://github.com/mjackson/history/blob/v3.2.1/modules/HashProtocol.js#L66

**Comment by medz** [comment]
@timdorr why？

**Comment by timdorr** [comment]
There is no question here.

**Comment by lizhengqiang** [comment]
push and pop in one time?
