### ISSUE TITLE
The readme should have instructions on how to upgrade to version 3

### ISSUE THREAD

**Issue by jaredbeck** [ReactTraining/react-router#4192]
# BUG TEMPLATE

This is a bug in the documentation.

## Version
master

## Steps to reproduce

1. Visit https://github.com/ReactTraining/react-router
2. Look for instructions on how to upgrade to version 3
3. Find instructions for upgrading to 2, but none for 3

## Expected Behavior

I expected the readme to have instructions on how to upgrade to version 3

## Actual Behavior

I could not find said instructions in the readme.

## Notes

- While the changelog (https://github.com/ReactTraining/react-router/blob/master/CHANGES.md) seems to be through, I, not being an expert in this project, was unable to use it as a guide for upgrading.
- The docs directory (https://github.com/ReactTraining/react-router/tree/master/docs) also needs a link to the upgrade instructions.
- I searched StackOverflow for information that we could base a guide on (https://stackoverflow.com/search?q=%5Breact-router%5D+upgrade) but didn't find any.

**Comment by timdorr** [comment]
There isn't a need. 3.0 is basically just 2.x with the deprecation warnings removed. If your code is running without warnings in 2.x, then no change is needed to run 3.0.

**Comment by jaredbeck** [comment]
> There isn't a need. 3.0 is basically just 2.x with the deprecation warnings removed. If your code is running without warnings in 2.x, then no change is needed to run 3.0.

That's great news for me, in my upgrade, thanks!

Can we add your description to the readme? It would encourage more people like me to upgrade.
