### ISSUE TITLE
Relative links produce the wrong href when router has a basename

### ISSUE THREAD

**Issue by AsaAyers** [ReactTraining/react-router#4195]
## Version
4.0.0-alpha.5

I also tried locally using d2a5b28 (head of v4 right now) and got the same results. I ran `npm pack` and then `npm install` in my test project with the path to the `.tgz` file that was generated.

## Test Case
http://jsbin.com/fufosoheta/edit?js,output

## Steps to reproduce

1. Use a `basename="/some/path"` on your router
2. Create a `<Link` with a relative path

I tried adding a trailing slash to `basename`, but that just causes different problems. When navigating you end up on URLs like `/some/path//whatever`.

## Expected Behavior

Link's href should match the URL that it navigates to when you click it.

## Actual Behavior

Link's href points to an invalid URL. The link still works when you left click it because of [`handleClick`](https://github.com/ReactTraining/react-router/blob/v4.0.0-alpha.5/modules/Link.js#L31-L44), but you get the wrong URL if you open the link in a new tab.

**Comment by pshrmn** [comment]
Relative locations are not currently supported. They hopefully will be soon, but right now you should always use absolute locations.

For simple relative pathnames you can concatenate the current `pathname` (which is passed as a prop to the component that a `<Match>` renders) with the relative pathname that you want to link to. It isn't pretty, but it's the best current way.

**Comment by AsaAyers** [comment]
What does "not supported" mean? `Link` doesn't error or warn when I pass a relative link and I don't see a reference to it in the docs.

**Comment by AsaAyers** [comment]
Are relative `<Match` supported?

**Comment by pshrmn** [comment]
The `<Link>` does not resolve its `to` prop. AFAIK no version of React Router has supported relative locations. #4122 is my attempt at rectifying this issue and hopefully that or some other code gets added to allow relative locations soon.

`<Match>` does allow for relative patterns, but those are also simpler (`../../path` is a valid pathname but not a valid pattern)
