### ISSUE TITLE
component props get store of mobx 

### ISSUE THREAD

**Issue by RifeWang** [ReactTraining/react-router#4196]
```
<Router history={browserHistory}>
	<Route path='/' component={Welcome}/>
</Router>
```
if my component Welcome need a store of mobx , how to get it through props?
I write like this:
```
const store = new Store();
const Welcome_container= React.createClass({
   render(){
       return (
          <Welcome_container sStore={Store}/>
       )
   }
});
<Router history={browserHistory}>
        <Route path='/' component={Welcome_container}/>
 </Router>
```
it can solve the problem, but havn't anyone better solution?

**Comment by timdorr** [comment]
That is the correct way to do it. Create separate route components that simply join together the routing info with the rest of your app. Don't try to make components do a lot of work. Keep them simple.

**Comment by RifeWang** [comment]
@timdorr  In this way , if i have 100 components, so i have to create 100 component-container, i don't think it's a simple way.
