### ISSUE TITLE
Ignore match rule like pattern="/:route" if pattern="/dashboard" is defined

### ISSUE THREAD

**Issue by IljaDaderko** [ReactTraining/react-router#4197]
Router version `4.0.0-alpha.5`

I have index.js file set up in the following way:

```

    <BrowserRouter>
      <div id="router-root">
        <Match pattern="/" component={Base}  />
        <Match pattern="/dashboard" component={Dashboard} />
        <Miss component={NotFound} />
      </div>
    </BrowserRouter>
```

users got to `/dashboard` section after authenticating and are displayed different layout `Dashboard`, users who are not authenticated are displayed `Base` layout. Each of the layouts has subsequent match tags to check the route and render page contents.

Issue now is that going to `/dashboard` renders both base and dashboard layouts.

**Comment by bs1180** [comment]
You need to add the `exactly` prop on your Match component.

**Comment by IljaDaderko** [comment]
@bs1180 I ave cases like `/dashboard/home` that should initially go into dashboard layout and there are more match components there to handle `/home` bit, if I do exactly on `pattern="/"` it would show NotFound component for route like `/something`

**Comment by pshrmn** [comment]
Where is the `/:route` defined in your app? If I understand correctly, your `<Base>` component is a catch all for routes that don't begin with `/dashboard`, but you didn't include a `<Match pattern='/:route' />` in your example code.

Currently you could write a [`<MatchNot>`](https://github.com/ReactTraining/react-router/issues/3906#issuecomment-247899742) component to do this, but I'd recommend waiting for the next release instead. The next release will provide a better way to handle your problem, either through a `<MatchGroup>` or a `<Match>` that accepts an array of patterns.

**Comment by timdorr** [comment]
@pshrmn is correct here. You should either pull from master and check out `<MatchGroup>`, or compose your own component.
