### ISSUE TITLE
Route Matching

### ISSUE THREAD

**Issue by cristiandley** [ReactTraining/react-router#4198]
## Version

2.8.1

Im using react-router since a while... my app like the documentation has a 
```Javascript
<Route path="/" component={App}>
</Route>
```
Now i had to deploy my app... i found my company designated a subpath for my app (i thought, no problem!)... but when i get to `/myapp` everything loads except components.

So i starting trying matching my new path

```JavaScript
<Route path="/myapp" component={App}>
    <IndexRoute component={ComponenA}/>
    <Route path="A" component={ComponentA}/>
    <Route path="B" component={ComponentB}/>
    <Route path="C" component={ComponentC}/>
</Route>
```

(Now each link must use `/myapp/A`, `/myapp/B`) Cool!

Now, some times and by some reasons the path would change like `/test /v1 /v2` etc... so i thought, i would use matching for this issue

```JavaScript
<Route path="/**" component={App}>
    <IndexRoute component={ComponenA}/>
    <Route path="A" component={ComponentA}/>
    <Route path="B" component={ComponentB}/>
    <Route path="C" component={ComponentC}/>
</Route>
```

But now routes arent find :cry:  

Is there any practical solution to this ?

**Comment by timdorr** [comment]
Use one asterisk instead of two for wildcard matches.

**Comment by cristiandley** [comment]
@timdorr mmmm i already tried... i just checked it again just in case

``` JavaScript
<Route path="/*" component={App}>
    <IndexRoute component={ComponentA}/>
    <Route path="A" component={ComponentA}/>
    <Route path="B" component={ComponentB}/>
    <Route path="C" component={ComponentC}/>
</Route>
```

 `/test/B`  => `/*/B`  will bring `ComponentA`...
 `/test/C`  => `/*/C`  will bring `ComponentA`...

Also tried (working... but dont seem to be a good solution):

```JavaScript
<Route path="/" component={App}>
    <IndexRoute component={ComponentA}/>
    <Route path="/**/A" component={ComponentA}/>
    <Route path="/**/B" component={ComponentB}/>
    <Route path="/**/C" component={ComponentC}/>
</Route>

```

**Comment by timdorr** [comment]
Wait, you shouldn't be doing that anyways. Nested routes inherit from their parent. The wildcard won't ever match anything underneath because it's swallowing up the whole URL.

It sounds like you want <Route path="/:section"> at the top.

**Comment by cristiandley** [comment]
Yes, thats what i described on the main part,  `<Route path="/{{{something}}}" component={App}>` where 'something' is the base path like `dom.com/something/A`
