### ISSUE TITLE
Programatically redirecting when context is not avaliable?

### ISSUE THREAD

**Issue by IljaDaderko** [ReactTraining/react-router#4199]
v4, alpha 5

I am trying to redirect from my redux action, at the moment I need to pass it router context to call, is there a way to redirect without passing it?

**Comment by dlebedynskyi** [comment]
@IljaDaderko  have you tried https://github.com/reactjs/react-router-redux/tree/4.0.x ?

**Comment by timdorr** [comment]
You can put the `this.context.router` into a global variable or singleton module (or just attach it as a property of your `store` as a hack) via a component near the top of your component tree. Just do things The React Way™ :smile:
