### ISSUE TITLE
[Docs] Upgrading to v3.0.0

### ISSUE THREAD

**Issue by ncphillips** [ReactTraining/react-router#4205]
I just noticed that the docs are lacking an upgrade guide for v3.0.0. 

I'm looking forward to upgrading, but it would be great if this could be made available first.

**Comment by timdorr** [comment]
Dupe of #4174, #4192, and #4175. Please search before posting a new issue.

**Comment by ncphillips** [comment]
Sorry :( I tried searching, but apparently ineffectively
