### ISSUE TITLE
Why RR4 alpha 5 doesn't work with yarn

### ISSUE THREAD

**Issue by steida** [ReactTraining/react-router#4206]
https://github.com/yarnpkg/yarn/issues/1922#issuecomment-261805178

**Comment by timdorr** [comment]
Ah, that's what's causing all the problems. I'll see about getting a new version pushed.

**Comment by timdorr** [comment]
Published alpha 6 to fix that. @ryanflorence has some big changes coming in a day or two, so only install alpha 6 if you're having issues with installation: https://github.com/ReactTraining/react-router/releases/tag/v4.0.0-alpha.6
