### ISSUE TITLE
Inconsistent links generated for pathname: null

### ISSUE THREAD

**Issue by jochenberger** [ReactTraining/react-router#4208]
If i create a `<Link pathname={null} ...>`, the href points to `${baseUrl}`, but the transition leads the the currently active URL.
This behavior has started between 4.0.0-alpha.4 and 4.0.0-alpha.5.
I suspect it's caused by https://github.com/mjackson/history/commit/445ce3ef4c1d3745dfae6eb199ce47b5d9eafadc.

**Comment by timdorr** [comment]
Pathname is a required property of a location.

**Comment by jochenberger** [comment]
Then it should throw or warn at least.
