### ISSUE TITLE
parsing query params (e.g. booleans)

### ISSUE THREAD

**Issue by lironess** [ReactTraining/react-router#4211]
I'm using version 2.5.2.
I've wanted to ask (because I didn't find that at the documentation pages) If there is an options to parse the accepted query params to another type which is not string.
for example:
```
http://myapp.com/foo?bar=true
```

I want the this.props.location.query to be like:
```json
{
  "bar": true
}
```
(boolean type, not a string)

**Comment by timdorr** [comment]
You can do this with your own query string parser: https://github.com/ReactTraining/react-router/blob/master/upgrade-guides/v2.0.0.md#custom-query-string-parsing
