### ISSUE TITLE
Fix react-router's (v0.13.6) problem of calling PropTypes directly 

### ISSUE THREAD

**Issue by alex-sh-wu** [ReactTraining/react-router#4212]
## Version
0.13.6

## Steps to reproduce
Use react-router with react v5.4.0. If you open the console, you get the follow error mentioned here:
https://facebook.github.io/react/warnings/dont-call-proptypes.html

**Comment by timdorr** [comment]
We're not developing the 0.x branch any more. If you need this, feel free to create a fork.
