### ISSUE TITLE
V4 CHANGELOG.md ?

### ISSUE THREAD

**Issue by willemx** [ReactTraining/react-router#4215]
Thanks for this nice clean router package!
Though it's still in alpha, it is allready good enough for me.
I'm only missing a CHANGELOG.md

**Comment by k15a** [comment]
You can find some changes at the releases tab https://github.com/ReactTraining/react-router/releases.

**Comment by timdorr** [comment]
Correct, please check the releases tab. 4.0 is a rewrite, so there isn't really a set of changes to work with.
