### ISSUE TITLE
V4 Release

### ISSUE THREAD

**Issue by donnieflorence** [ReactTraining/react-router#4219]
v4 is awesome! However theres been a lot of mixed feelings about it. I constantly see @ryanflorence tweets about his experiments with the new router and its wicked awesome! However to quell peoples negative comments about v4 a good approach would be to keep up with these experiments add them to the docs, and the new router site to show how good v4 can be for react-native, redux, data-loading, etc. and grow the adding for v4 while at the same time leaning out v4's API. Really looking forward to v4 and keep up the experiments! Main point being take as much time as possible to make v4 a no brainer!

**Comment by timdorr** [comment]
They do make their way into the documentation, but once they are more than just simple experiments. We don't want to throw a bunch of half-baked ideas in there. It's best to let them simmer for a bit and see if they hold up to scrutiny before just blinding posting them as gospel :smile:
