### ISSUE TITLE
routeParams is not valued for nested routes

### ISSUE THREAD

**Issue by marcellomontemagno** [ReactTraining/react-router#4225]
Hi guys, the following routing 

	<Router>
	  <Route path="/" component={App}/>
	  <Route path="/aRoute" component={App}>
	    <Route path=":myParam" />
	  </Route>
	</Router>

doesn't value routeParams when navigating to "/aRoute/1"

routeParams is valued if I use optional parameters as follow 

	<Router>
	  <Route path="/" component={App}/>
	  <Route path="/aRoute(/:myParam)" component={App}/>
	</Router>

looks like a bug to me, is it an intended behaviour?

tested against version 3.0.0

below a runnable version of both scenarios

nested routes:  http://codepen.io/anon/pen/QGqWQW?editors=001
optional parameters:  http://codepen.io/anon/pen/eBGYyd?editors=001

**Comment by pshrmn** [comment]
From the [docs](https://github.com/ReactTraining/react-router/blob/6eeb7ad358f987520f5b519e48bdd31f725cbade/docs/API.md#routeparams):
> ### `routeParams`
> A subset of this.props.params that were directly specified in this component's route.

If your `<Route path=":myParam" />` had a component, that component would have access to `props.routeParams.myParam`.

**Comment by marcellomontemagno** [comment]
Thanks for the quick response,

I noticed this thing refactoring some route with optional parameters to nested routes.
I did it because of the following issue with the isActive API 

[3277](https://github.com/ReactTraining/react-router/issues/3277)

I was expecting nothing to break and no need to change the components implementation doing that change.

Maybe a little extra to that line in the doc would not be bad, that route is rendering that component 	after all :)
