### ISSUE TITLE
buggy scroll on page transition

### ISSUE THREAD

**Issue by artofspeed** [ReactTraining/react-router#4226]
Say u transit from page B to page A. What happens now is B will first be scrolled to A's position **before being unmounted**, then A is mounted. In other words, the whole scenario is the following
B scrolls to A's scroll position -> screen freezes for ~100ms -> B is hidden -> A is shown. 

This behaviour is even worse on mobile browser since it has slower CPU, and the "freeze" lasts longer, sometimes ~300ms when there're a lot of things to compute, creating a very disturbing user experience.

To recreate this:
- make page A and page B both very long and scrollable. 
- in page B's `componentWillUnmount`, add `alert('will unmount')`. This helps visualize the bug.
- open page A, scroll to bottom
- click something that transits to page B and do not scroll down page B
- you're now on top of page B, execute `window.history.back()` in console
- you will see that page B will first be scrolled down, then `alert` will be poped. This means page B is been scrolled before unmounted.

I've tested this on **Firefox**. Is there any fix to this bug, or at least **disable** react router's auto scroll?

**Comment by timdorr** [comment]
Scroll position is unmanaged by default. If you want some control over it, [use react-router-scroll](https://github.com/taion/react-router-scroll).
