### ISSUE TITLE
v4 Match need to support regexp, not only express-style path

### ISSUE THREAD

**Issue by sweetcharity** [ReactTraining/react-router#4228]
For example, it's not possible to match any string except one with express-style path.

**Comment by pshrmn** [comment]
Using `<MatchRoutes>` you can have a pattern for the string that you don't want to match and a wildcard for every other route.

```js
<MatchRoutes routes={[
  { pattern: '/foo', component: Foo },
  { pattern: '*', component: NotFoo }
]} />
```

**Comment by timdorr** [comment]
It does support regexp. It uses [path-to-regexp](https://github.com/pillarjs/path-to-regexp) under the hood. You can use [a custom match parameter](https://github.com/pillarjs/path-to-regexp#custom-match-parameters) to achieve that.
