### ISSUE TITLE
v4: Match render a special case of Match component

### ISSUE THREAD

**Issue by alexisvincent** [ReactTraining/react-router#4229]
# render a special case of component
In RR4, the Match component has a prop called render, with the following spec.

> render: func
Instead of having a component rendered for you, you can pass in a function to be called when the location matches. Your render function will be called with the same props that are passed to the component.
This allows for convenient inline match rendering and wrapping.

```javascript
// convenient inline rendering
<Match pattern="/home" render={() => <div>Home</div>}/>

// wrapping/composing
const MatchWithFade = ({ component:Component, ...rest }) => (
  <Match {...rest} render={(matchProps) => (
    <FadeIn>
      <Component {...matchProps}/>
    </FadeIn>
  )}/>
)

<MatchWithFade pattern="/cool" component={Something}/>
```

However, since, `({ component:Component, ...rest }) => (...)` (as in the example), is a valid react component, this prop is simply a special case of the component prop, and the example, copy and pasted with just `render` changed to `component` would be valid, as shown below:

```javascript
// convenient inline rendering
<Match pattern="/home" component={() => <div>Home</div>}/>

// wrapping/composing
const MatchWithFade = ({ component:Component, ...rest }) => (
  <Match {...rest} component={(matchProps) => (
    <FadeIn>
      <Component {...matchProps}/>
    </FadeIn>
  )}/>
)

<MatchWithFade pattern="/cool" component={Something}/>
```

IMO, having an extra prop, which is really just a special case of another one, is unnecessary API bloat, that will lead to confusion. 

What is the motivation for including `render`? And is there perhaps something I'm missing here?

**Comment by timdorr** [comment]
It's mainly for having a sane API surface. Yes, they are essentially equivalent, but the common case is to do `component={Foo}` instead of providing a function. It reads better and makes it easier to remember, without having to dig into the code to learn the subtleties.

**Comment by alexisvincent** [comment]
@timdorr Have you considered dropping `component` in favor of `render`. This solves the readability issue. Since `render={Foo}`, sounds good, also follows the functional convention of using verbs over nouns. This also makes the API surface area smaller and easier to understand.

**Comment by taurose** [comment]
There's a difference in that `component={(props) => ...}` will create a new component each `render`, since the function is recreated each time, causing the identity check to fail. The result is that the component and everything within would be re-mounted each time.

**Comment by ivan-kleshnin** [comment]
> https://reacttraining.com/react-router/web/api/Route/children-func
> Sometimes you need to render **whether the path matches the location or not**. In these cases, you can use the function children prop. It works exactly like render except that it gets called whether there is a match or not.

> https://reacttraining.com/react-router/web/api/Route/path-string
> Routes without a path always match.

So what's the difference between:

`<Route path="/any" children={...}/>`

and

`<Route render={...}/>`

???
