### ISSUE TITLE
Uncaught URIError: URI malformed

### ISSUE THREAD

**Issue by suprMax** [ReactTraining/react-router#4233]
## Version
3.0.0

## Test Case
In examples: http://localhost:8080/query-params/?%2

## Steps to reproduce
Add %2 anywhere in your querystring, 

## Expected Behavior
`error` passed to `match` callback as first argument: https://github.com/ReactTraining/react-router/blob/master/docs/guides/ServerRendering.md

## Actual Behavior
`Uncaught URIError: URI malformed`

Not sure if this is expected behavior, I saw that history doesn't touch this subject. It would be nice if react router handled this error, otherwise every router user will have to pass down customized history and keep track of versions compatibility. Currently server side rendering fails with 500.

**Comment by timdorr** [comment]
You need to do your own query string parsing: https://github.com/ReactTraining/react-router/blob/master/upgrade-guides/v2.0.0.md#custom-query-string-parsing

**Comment by iamakulov** [comment]
Up-to-date link: https://github.com/ReactTraining/react-router/blob/v3/upgrade-guides/v2.0.0.md#custom-query-string-parsing
