### ISSUE TITLE
Exactly or exact

### ISSUE THREAD

**Issue by pshrmn** [ReactTraining/react-router#4237]
`<Match>` uses the `exactly` prop while `<MatchRoutes>` routes have an `exact` property. This should be consistent. I prefer `exactly` if for no other reason than that `<Match>` came first.

**Comment by timdorr** [comment]
Marking this as a "bug" in the sense that it's a bug of the API surface.

**Comment by sikanhe** [comment]
+1 for exact, not many var names uses '*ly' in my experience

**Comment by mark0978** [comment]
However `<Match exactly pattern='whatever'...>` reads better than `<Match exact pattern='whatever'...>`
But only by a tiny bit.

**Comment by mjackson** [comment]
It's too early to nit-pick prop names in v4. We're just exploring some new possible API. Please rest assured we won't ship the final release with two props that are supposed to do the same thing but with different names :)
