### ISSUE TITLE
Get params from push

### ISSUE THREAD

**Issue by juanda99** [ReactTraining/react-router#4238]
Working with: 
    "react-router": "3.0.0",
    "react-router-redux": "4.0.6",

I have defined this route:
`/pictograms/search/:searchText`

When I type this url: 
`localhost:3000/pictograms/search/test`
I get the param through redux:
```
const mapStateToProps = (state, ownProps) => {
  const searchText = ownProps.params.searchText || ''
  return ({
    searchText,
  })
}
```
However if I launch the url through react-router push:

```
  handleSubmit = (nextValue) => {
     this.props.router.push(`/pictograms/search/test`)
    if (this.props.searchText !== nextValue) {
      // this.props.router.push(`/pictograms/search/${nextValue}`)
    }
  }
```

I got nothing in searchText variable (url changes and mapStateToProps is called but ownProps.params and ownProps.router.params seem empty through the debugger)

**Comment by timdorr** [comment]
You don't need to map the props in react-redux. Just change that line to read from this.props.params.searchText. You're just moving around data.
