### ISSUE TITLE
SSR, how change the route (or component to render) programmatically

### ISSUE THREAD

**Issue by acanimal** [ReactTraining/react-router#4239]
Hi, 
I have looking for some info and other issues but didn't found any solution.

We are working on a universal app. For SSR we have an node+express endpoint that uses the `match` function. When requests arrives to `/product/xxxxxxx`  we want to load data and render the component `Product`. The goal is to render a `NotFound` component if the product with given id is not found. The current workflow is as follow:

1. Request arrive to express request  and we execute the `match` function.
2. From `renderProps` retrieve the component to be rendered and call a static `fetchData` method which is responsible to load data from server.
3. Once data is loaded we `renderToString` like this:

```
const body = renderToString(
            <MuiThemeProvider muiTheme={muiTheme}>
              <Provider store={store}>
                <IntlProvider>
                  <RouterContext {...renderProps} />
                </IntlProvider>
              </Provider>
            </MuiThemeProvider>
          );
```

What we want is in step 2, if no data is returned update the `renderProps` so the component that were rendered be the `NotFound`.

Any ideas?
Thanks

**Comment by timdorr** [comment]
You can just renderToString() a different set of components, most likely just the NotFound component, if your fetchData methods come back with an error.

**Comment by acanimal** [comment]
I know that, the question is the path to the component is within the renderProps !!!

My question is related on how to modify the renderProps so that the previous code renders a different component that those selecting by the `match` function ???

**Comment by timdorr** [comment]
You shouldn't mess around with `renderProps`, as that will cause issues when the client boots up and React runs into a mismatch error. You're better off just rendering the NotFound server-side as static markup and not including your client code/script tag in that response.
