### ISSUE TITLE
BrowserRouter requires a child element to contain Match/Miss components

### ISSUE THREAD

**Issue by jaydenseric** [ReactTraining/react-router#4244]
Version: 4.0.0-alpha.6.

```jsx
import React from 'react'
import {render} from 'react-dom'
import {BrowserRouter, Match, Miss} from 'react-router'
import HomePage from 'components/home-page'
import ErrorPage from 'components/error-page'

render(
  <BrowserRouter>
    <Match pattern='/' exactly component={HomePage} />
    <Miss component={ErrorPage} />
  </BrowserRouter>,
  document.getElementById('root')
)
```

Results in `Uncaught Error: React.Children.only expected to receive a single React element child.`.

Containing everything under `BrowserRouter` in a `div` fixes the error:

```jsx
<BrowserRouter>
  <div>
    <Match pattern='/' exactly component={HomePage} />
    <Miss component={ErrorPage} />
  </div>
</BrowserRouter>
```

The requirement for a containing element is not intuitive. Although most of the examples have this wrapper it is not explained in the docs that it is required, and there is [example code that does not have one and would presumably fail](https://github.com/ReactTraining/react-router/blob/v4.0.0-alpha.6/website/api/Miss.md#miss).

**Comment by jaydenseric** [comment]
Brought up here: https://github.com/ReactTraining/react-router/issues/4221#issuecomment-264683725.

**Comment by pshrmn** [comment]
This has been discussed before (#4009, #4131, #3837). It exists because the underlying router component, `<StaticRouter>` is environment agnostic, so it doesn't wrap its `children` prop in a  `<div>` or a `<View>`.

**Comment by jaydenseric** [comment]
@pshrmn thanks, closing as #4131 is the right place for this. Cheers :)

**Comment by protoEvangelium** [comment]
Thanks @jaydenseric  wrapping the Match's in a div fixed the issue 👍
