### ISSUE TITLE
Mobile Navigation-like with router

### ISSUE THREAD

**Issue by mmahalwy** [ReactTraining/react-router#4246]
Hi there,

Not 100% where to post this, but I figured I'd try here. 

As mobile web becomes more popular, I'd like to mimic the navigation style of mobile apps (navigation bar with back buttons, titles of current model, action links/buttons, search bars only on some pages, etc.)

With RR v4, is there plans to have such flexibility? My best solution at the moment is using something like React-Helmet's ideas/code to manipulate the nav component. 

Thoughts?

**Comment by timdorr** [comment]
With 4.0's `<Match>` you can place that anywhere. So having a static navigation component is totally possible. 

RN integration was also discussed recently: https://github.com/ReactTraining/react-router/issues/4203

**Comment by mmahalwy** [comment]
Oh wow. This is really awesome. Going to spend my night moving to V4 now :) 

Thanks @timdorr
