### ISSUE TITLE
Do get request with content-type: text/html

### ISSUE THREAD

**Issue by kol9n93** [ReactTraining/react-router#4249]
Hello. I implemented react-router in my application. But also I wanna integrate passport-saml in my app.
I'm trying to do the following using express router:
```
router.get('/login',
  passport.authenticate(config.passport.strategy, {
    successRedirect: applicationUrl,
    failureRedirect: applicationUrl+ '/login'
  })
);
```
This route should redirect user to SAML login page. But that '/login' handler is dead code, because react router handles that request and says something like "route /login didn't match any routes".
Is there some workaround to allow to do GET request with content-type: text/html? I wanna do request to the server directly.

**Comment by timdorr** [comment]
Just move the `router.get()` handler above the React/router handler. It's not getting to that route because the router one is eating up the request first.

**Comment by kol9n93** [comment]
But react-router is on client side. Router.get is on server side

**Comment by timdorr** [comment]
The part of your server code where you serve up the HTML and client code is above that `router.get`.
