### ISSUE TITLE
Implement a back button using V4

### ISSUE THREAD

**Issue by joshirushabh** [ReactTraining/react-router#4258]
Hi,
I could not find this in the examples on the website. Basically I have a back button in the application which takes user to previous page ( route ).

Can someone please let me know how to implement that?  In previous versions since we had 'history' instance, I was just doing history.goBack()

Thanks,
Rushabh

**Comment by timdorr** [comment]
The fake browser from the example site can help: https://github.com/ReactTraining/react-router/blob/v4/website/components/FakeBrowser/index.js#L104-L113

Alternatively, you can just pull `router` off context and use the imperative API as an escape hatch.

**Comment by joshirushabh** [comment]
Thanks @timdorr. Can you please let me know which API call I can use to make this happen. I tried context.router.transitionTo(-1) but it is not working.
