### ISSUE TITLE
How to do animated route transitions in v4

### ISSUE THREAD

**Issue by jedwards1211** [ReactTraining/react-router#4259]
I don't think that `<Match>` as designed right now will work well with transition components, since all `<Match>`es are mounted, even if only one actually renders its `component`.

In v2 wrapping route components in a transition component is easy since it gets passed only the matched route as a child.  I've been using a `<Fader>` component that takes a single child, and when the child (key) changes, it fades out the first, then fades in the second.  So crossfading is as simple as:

```es6
const FaderRoute = ({route, children}) => (
  <Fader>
    <div key={getCachedKey(route)} children={children} />
  </Fader>
)

const routes = (
  <Route component={FaderRoute}>
    <Route path="/" component={Home} />
    <Route path="/about" component={About} />
  </Route>
)
```

It was also really easy to add transitions to existing route configuration with v2.

In v4, it would be possible to do the mounting/unmounting animation in each `<Match>` component individually, so it would be easy to crossfade. But having the new route fade in *after the old route is done fading out* would be much more difficult.  One could delay the fade in, but then the initial page mount would be delayed...

However, this approach would work with something like @acdlite's ideas in #3914 about a single `<Match>` that takes multiple `routes` and *calls a child function with the matched route*:

```es6
<Match 
  routes={[
    {pattern: "/", exactly: true, component: Home},
    {pattern: "/about", component: About},
  ]}
>
  {({pattern, component: Comp}) =>
    <Fader>
      <Comp key={pattern} />
    <Fader>
  }
</Match>
```

**Comment by spicydonuts** [comment]
`Match` supports `children` passed as a function, which it will call with a flag indicating whether it's a match.  There's an example regarding animation in the docs: https://react-router.now.sh/animated-transitions

**Comment by jedwards1211** [comment]
Cool, I didn't know it already supports a child function!

However, that example relies on the fact that it's just *one `<Match>` with variable `params`*...maybe the bleeding-edge `<MatchRoutes>` would work for multiple patterns though?

**Comment by timdorr** [comment]
Yes, [it does that](https://github.com/ReactTraining/react-router/blob/v4/modules/MatchRoutes.js#L51).

**Comment by jedwards1211** [comment]
@timdorr actually no, a per-route `render` is not what I'd need; a child function that gets passed the route object would be more convenient for a lot of animation cases.

**Comment by timdorr** [comment]
Unless I'm missing something:
```jsx
<MatchRoutes>
  <Match pattern="/pants" render={transitionAnimated(genKey(), Pants)} />
  <Match pattern="/shoes" render={transitionAnimated(genKey(), Shoes)} />
  <Match pattern="/shirts" render={transitionAnimated(genKey(), Shirts)} />
</MatchRoutes>
```
Keep your keys from `genKey()` in a top-level var in your module so you can reference the same element instance. 

I know @ryanflorence's working pretty hard on some RN transition animation stuff (check his Twitter feed, it's cool stuff!), but that would be applicable to ReactDOM as well. There is probably a best practice that will come about from all of this, but we're still in the middle of nailing down the internals and need time to build that solid foundation so we can establish what those practices are.

**Comment by jedwards1211** [comment]
@Lube really I haven't switched to v4 yet in production work.  I'm just bringing up my questions before I take that leap.
@timdorr that example makes sense.

**Comment by dlebedynskyi** [comment]
@timdorr  @ryanflorence  any news on this transition animation? Would be great to see some. We appreciate you guys being busy with this but would be really nice to see how current v4 works with react-motion on multiple Maches
