### ISSUE TITLE
V4 Getting two matches, one for :id and another not

### ISSUE THREAD

**Issue by mmahalwy** [ReactTraining/react-router#4261]
```
<Match pattern="/projects/new" exactly render={this.renderProtectedMatch(ProjectsNew)} />
<Match pattern="/projects/:id" exactly render={this.renderProtectedMatch(Project)} />
```

and url: `/projects/new` results in matching both.

**Comment by pshrmn** [comment]
This is expected. If only one should render, use a [`<MatchRoutes>`](https://github.com/ReactTraining/react-router/blob/v4/website/api/MatchRoutes.md). The documentation for it explains this exact situation.

**Comment by elmarburke** [comment]
I ran into the same problem. The solution is super, so the matching is simpler. Can you bump a more current version to npm since in v4 alpha6 there is no MatchRoutes and a git source is not working since a build step is required.

**Comment by mmahalwy** [comment]
+1
