### ISSUE TITLE
v4 should allow no params Match and expose router helpers in the callback

### ISSUE THREAD

**Issue by gartz** [ReactTraining/react-router#4262]
**Motivation:**
Link component can't solve all the use cases where a user can use to navigate, this will allow to create other kind of navigable custom components such as Selector Element that navigate on change event.

Also I don't think react-router should own all the possible components to navigate, there are so many edge cases that the library should not provide a built-in component however, the tools to allow to build them would be good.

**How to do:**
If no params are set in the Match, it should adopt the `/` by default, allowing anything in the pathname/query to be valid match. And in the callback expose a read-only copy of the state (please share the same object though all the equal match results, so we can use the state memory reference to memoize results), and the router helper functions.

**Benefit:**
Avoid developers exposing the router context to create such components. What also nowadays don't give direct access to the getState and don't ensure that if a state changes it will try to update the component depending on it.

Btw, this solution works even for the Link element, if you guys like it and want to re-implement...

When I say helper functions I'm talking about of `createHref` and `transitionTo` and others...

Example on how to create the Select component with the current react-router v4:
```jsx
import React, { PropTypes } from 'react';
import { Match } from 'react-router';

class Select extends React.Component {
  static contextTypes = {
    router: PropTypes.shape({
      transitionTo: PropTypes.func.isRequired,
      createHref: PropTypes.func.isRequired,
    }).isRequired,
  };

  static propTypes = {
    onChange: PropTypes.func,
    children: PropTypes.node,
  };

  onChange({ location } = {}, queryname, onChange = Function.prototype) {
    const { router } = this.context;

    return (event) => {
      onChange(event);
      if (event.defaultPrevented) {
        return;
      }

      const to = router.createHref({
        pathname: location.pathname,
        query: {
          ...location.query,
          [queryname]: event.target.value
        }
      });
      router.transitionTo(to);
    };
  }

  render() {
    const { onChange, queryname, children, ...props } = this.props;

    return (
      <Match pattern="/">
        { (matchedProps) => (
          <select onChange={ this.onChange(matchedProps, queryname, onChange) } { ...props }>
            { children }
          </select>
        ) }
      </Match>
    );
  }
}

export default Select;
```

Example with after changes:
```jsx
import React, { PropTypes } from 'react';
import { Match } from 'react-router';

function Select({ queryname, onChange = Function.prototype, children, ...props }) {
  function onChangeHandler({ location, createHref, transitionTo  }) {
    return (event) => {
      onChange(event);
      if (event.defaultPrevented) {
        return;
      }

      const to = createHref({
        pathname: location.pathname,
        query: {
          ...location.query,
          [queryname]: event.target.value
        }
      });
      transitionTo(to);
    };
  }
    return (
      <Match pattern="/">
        { (matchedProps) => (
          <select onChange={ onChangeHandler(matchedProps) } { ...props }>
            { children }
          </select>
        ) }
      </Match>
    );
  }
}

Select.propTypes = {
  onChange: PropTypes.func,
  children: PropTypes.node,
};
```

As you see, doing that small changes get the same results with a smaller code and pure function would be very welcoming.

**Comment by pshrmn** [comment]
From what I can tell, you are using `<Match>` as an HOC to inject `router` functions into your component. While it hasn't been merged, there is a PR for a `withRouter` HOC that injects the `router` as a prop. That lets people use the `router` without having to touch the `context`.

Your `<Select>` component would look something like:

```js
import React, { PropTypes } from 'react'

class Select extends React.Component {

  onChange(event) {
    const { queryname, onChange, router } = this.props
    if ( onChange ) {
      onChange(event)
    }
    if (event.defaultPrevented) {
      return
    }
    const { location } = router.getState()
    router.transitionTo({
      pathname: location.pathname,
      query: {
        ...location.query,
        [queryname]: event.target.value
      }
    })
  }

  render() {
    return (
      <select onChange={this.onChange.bind(this)) } { ...this.props }>
        { children }
      </select>
    );
  }
}

export default withRouter(Select)
```

Maybe I'm missing the point of what you're proposing, in which case it would be helpful if you included an example of where this is useful, but I think the above should accomplish what you're trying to do.

**Comment by gartz** [comment]
I'm in the phone, but yes you got the point, doing it using high order function is even better than my suggestion, so after you merge that pull request that will be the way you've said and it's beautiful. Thanks.

--
Gabriel Reitz Giannattasio
gabriel@loadin.com.br
+1 (240) 803-1986
