### ISSUE TITLE
Which version of react-router to use for production app?

### ISSUE THREAD

**Issue by r3verser** [ReactTraining/react-router#4263]
I have tested react-router v4 and it seems to be good, but for now it has some bugs, so i think it is not yet ready for commercial production projects. So which version should i use, v3? And if so, what are the diff's between previous router and v4, pros and cons maybe.
p.s. stackoverflow community are too friendly to my [question](http://stackoverflow.com/questions/41051318/which-version-of-react-router-to-use-for-production-app)

**Comment by timdorr** [comment]
4.0 is still in alpha. 3.0 is the only production-ready version at this time.
