### ISSUE TITLE
V4 Redirect/router.replaceWith() change fired before the Router is listening to the History 

### ISSUE THREAD

**Issue by texels** [ReactTraining/react-router#4264]
**V4**
I was trying to make sure a user was logged in and if not, I would capture the desired path and then return a <Redirect> the sent them to /login. When I did this, the url changed, but the page did not. I also tried replaceWith( '/login' ) with similar results.  

I ended up tracing this down and it appears the the Router is attaching listeners in componentDidMount(), which occurs after the render(), which is where the redirect was occuring. Changing Router.componentDidMount() to Router.componentWillMount() seemed to fix my issue.

**Comment by timdorr** [comment]
Yes, you should be using cWM for now.

**Comment by texels** [comment]
Hi Tim - Thanks for the quick response! I am confused though, is that change going to make it into the React Router source tree or do i have to work around it in mine? Thanks!
