### ISSUE TITLE
Support For Promises on setRouteLeaveHook

### ISSUE THREAD

**Issue by cyberhck** [ReactTraining/react-router#4265]
Currently when we try to confirm with user, it uses browser's confirm which is IMHO just plain laziness, it's ugly and no one wants to use.

But if we want to use a custom dialog components, there's no way to return true or false or any kind of information as soon as user is about to navigate away.

My proposal: Just before we change the route, instead of just doing a `confirm(message)`, we check if the returned data is `bool`, string, or a promise. I believe `bool` and `string` are already being handled.

For promise, we wait for promise to complete and then do the change if promise is resolved, and ignore if promise is rejected.

In this way we extend the way so that old functionality doesn't break, jimmy is happy and we have better functionality.

I'm aware that it's gonna be a little difficult than I have anticipated. If it's a browser back, or refresh we aren't doing anything anyway.

I'd be happy to send a PR if it's not that much of work or if someone explains how all these work. I went to find out what happens when we do a return there by setting breakpoints. Since I'm not a front-end person, I'm not sure if it's too complicated

**Comment by timdorr** [comment]
[You can't have async leave hooks](https://github.com/ReactTraining/react-router/issues/3406#issuecomment-216917744). That comment sums up the major reasons.

**Comment by cyberhck** [comment]
@timdorr , I didn't mean there. that's a browser thing. Before we unmount what we have on Route, we can wait for a promise.

**Comment by travisdahl** [comment]
+1 for async leave hooks with promises. Ran into the same issue. Need to do some checking on leave and then proceed based on the result of the check.

**Comment by cyberhck** [comment]
whoever is coming to this issue to have async leave hooks, please look into router5 it has great support and has async leave hooks, and it is library/framework agnostic router, meaning it can be used with react, angular and what not.
