### ISSUE TITLE
Npm run dev shows error  in windows 8.1

### ISSUE THREAD

**Issue by TriptiPant01** [ReactTraining/react-router#4270]
0 info it worked if it ends with ok
        1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
        1 verbose cli   'C:\\Users\\dell\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
        1 verbose cli   'run',
        1 verbose cli   'dev' ]
        2 info using npm@4.0.5
        3 info using node@v6.3.1
        4 verbose stack Error: missing script: dev
        4 verbose stack     at run (C:\Users\dell\AppData\Roaming\npm\node_modules\npm\lib\run-script.js:151:19)
        4 verbose stack     at C:\Users\dell\AppData\Roaming\npm\node_modules\npm\lib\run-script.js:61:5
        4 verbose stack     at C:\Users\dell\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:356:5
        4 verbose stack     at checkBinReferences_ (C:\Users\dell\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:320:45)
        4 verbose stack     at final (C:\Users\dell\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:354:3)
        4 verbose stack     at then (C:\Users\dell\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:124:5)
        4 verbose stack     at ReadFileContext.<anonymous> (C:\Users\dell\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:295:20)
        4 verbose stack     at ReadFileContext.callback (C:\Users\dell\AppData\Roaming\npm\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16)
        4 verbose stack     at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:365:13)
        5 verbose cwd C:\Users\dell\Desktop\testreact\app
        6 error Windows_NT 6.3.9600
        7 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\dell\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
        8 error node v6.3.1
        9 error npm  v4.0.5
        10 error missing script: dev
        11 error If you need help, you may report this error at:
        11 error     <https://github.com/npm/npm/issues>
        12 verbose exit [ 1, true ]

**Comment by BTMPL** [comment]
There is no "dev" script defined in react-router package.json, what exactly are you trying to run? Is this when running part of some other project?

**Comment by BTMPL** [comment]
It looks like you're trying to run "C:\Users\dell\Desktop\testreact\app" - if this your custom app / 3rd party app that includes ract-router as a dependency it's not rr fault. "C:\Users\dell\Desktop\testreact\app\package.json" has no "dev" script defined.
