### ISSUE TITLE
HashRouter in v4

### ISSUE THREAD

**Issue by HelloTiago** [ReactTraining/react-router#4275]
The following code, on a URL such as "http://127.0.0.1/en/config/#/" results in an empty page. The route doesn't seem to be matching.

Using v4.0.0-alpha.4

```
import React from 'react';
import { render } from 'react-dom';
import { HashRouter, Match, Link } from 'react-router';
import Config from './Customizer';

const App = () => (
  <HashRouter>
      <div>
        <Match pattern="/:lang/config" component={Config} />
      </div>
  </HashRouter>
)

render(<App/>, document.querySelector('#react'))
```

Not sure what could be causing this... Am I missing some configuration for the HashRouter?

**Comment by timdorr** [comment]
Make sure you're using the latest alpha version (alpha.6). But keep in mind this is all pre-release, so it might not work yet.

**Comment by HelloTiago** [comment]
Can confirm it's not working with the latest alpha version either.
