### ISSUE TITLE
[question] Route.getComponent() - is there a way to only get params for given route segment?

### ISSUE THREAD

**Issue by BTMPL** [ReactTraining/react-router#4279]
I'm sorry for using the issue tracker as a question board, but I've already tried SO and reddit to no avail :/

I'm trying to use Route's getComponent() ( https://github.com/ReactTraining/react-router/blob/master/docs/API.md#getcomponentnextstate-callback ) to add some asynchronous logic to the routing. I got it mostly working but got stuck on how to only receive params related to current node fragment of the path.

An example:

```
const getSampleComponent = (nextState, cb) => {
  console.log(nextState.params);
  cb(null, () => {    
    return <div><Link to="/test/1">/test/1</Link> <Link to="/test/1/test2/2">/test/1/test2/2</Link></div>
  });
}

function createRoutes() {
  return {
    path: '/',
    getComponent: getSampleComponent,
    childRoutes: [{
        path: "test/:id",
        getComponent: getSampleComponent,
        childRoutes: [{
          path: "test2/:id",
          getComponent: getSampleComponent
        }]
      }
    ]
  }
}


ReactDOM.render((
  <Router history={createMemoryHistory()} routes={createRoutes()} />
), document.getElementById('app'))
```

( running version: http://jsbin.com/dedazozije/edit?html,js,console,output )

using `console.log(nextState.params);` I can list all the params, but those will contain params for the whole matched path, not only the node. So in case I visit /test/1/test2/2 it will be

```
[object Object] {
  id: ["1", "2"]
}
```
Reepated 3 times. I would like to only see:

for / getComponent - an empty object
for test/:id getComponent - {id: 1}
for test2/:id getComponent - {id: 2}
Is that data provided somewhere or is parsing the path location and matching params to it the only way? This will get complicated when I use same :paramName on different route segments...

**Comment by timdorr** [comment]
You should use unique param names. We only extract them from the URL once, so we can't isolate them easily.

**Comment by BTMPL** [comment]
Ok, so there is no other way to get the path-element specific params than to parse the params object? Fair enough. Thank you for your time :)
