### ISSUE TITLE
v4 Match pattern params reuse

### ISSUE THREAD

**Issue by zombieJ** [ReactTraining/react-router#4280]
Hi, I found that if pattern of `<Match>` contains params it will return new object even if it's the same:
```javascript
<Match pattern="/:test" component={Test} />
```
For example: `http://localhost/`

When ui update and url no change, it will pass new object `{}` as params which cause `PureComponent` refresh.

I'm not sure if this should improve in RR or just self handle `componentShouldUpdate` without PureComponent.

Thanks

**Comment by timdorr** [comment]
You shouldn't use a PureComponent as your route component. Use those further down the tree.
