### ISSUE TITLE
v3 produces React warnings about unknown prop `state` on <a> tag

### ISSUE THREAD

**Issue by necolas** [ReactTraining/react-router#4281]
## Version
3.0.0

## Test Case
http://jsbin.com/lijeyojute/edit?html,js,console,output (this would probably surface the warning if ReactRouter's UMD build weren't throwing an error)

## Steps to reproduce

Add `state` prop to `Link`.

```js
<Link state={{}} />
```

## Expected Behavior

Either no warning, like React 2.8.1, or documentation about the change

## Actual Behavior

React warning:

```
Unknown prop `state` on <a> tag. Remove this prop from the element
```

**Comment by JaakkoL** [comment]
I'm facing the same issue.

**Comment by pshrmn** [comment]
There has been a warning from [2.0.0-rc1](https://github.com/ReactTraining/react-router/blob/v2.0.0-rc1/modules/Link.js#L107-L110) through to the current [2.8.1](https://github.com/ReactTraining/react-router/blob/v2.8.1/modules/Link.js#L106-L109).

v3 removed deprecated v1 code (starting with [this release](https://github.com/ReactTraining/react-router/releases/tag/v3.0.0-alpha.1)) Passing a `state` prop was one of these deprecated functionalities. You should include the `state` in the `to` location descriptor.

```js
<Link to={{ state: { ... } }} />
```
