### ISSUE TITLE
Expose action to <Match /> component in 4.0

### ISSUE THREAD

**Issue by jamesism** [ReactTraining/react-router#4283]
Hello!

I just switched over to v4 (loving it!), and am wondering if there is a reason you left `action` out of the props passed to `Match` components? 

It is available to be passed to the `router` context value from `StaticRouter`'s `getChildContext` function as it is passed to that component as a prop, but left out of the `getState` call, and subsequently the props generated to pass to `Match` components.

I have a use case where I'd like to have in/out differentiation for an animating `Match` component. As it stands it seems the only way I can access the last action is by passing a function as child to `Router`. Since I'd like to be able to have other `Match` components out deeper in the tree and not have to pass the action down through props, it'd be nice to have it passed to `Match`.

I apologize in advance if there is some other way to do this that I'm missing, or if there is a good reason it's not passed to Match in the first place. The change required is [minimal](https://github.com/ReactTraining/react-router/compare/v4...jamesism:v4) and seems to work fine in my local tests. Let me know what you think!

Thanks,
James

**Comment by timdorr** [comment]
A PR to add this would be great, and should be easy since you're part of the way there. Just make sure you include some tests.

**Comment by jamesism** [comment]
Cool! Will look at adding tests this weekend, thanks!

**Comment by jamesism** [comment]
Alright, I've added some tests to verify the value of `action` passed. I also found a typo in some of the existing `Match` tests as a result and fixed them up. The updated changes are [here](https://github.com/ReactTraining/react-router/compare/v4...jamesism:v4), please let me know if anything isn't sufficient as my test writing experience is limited.

Unfortunately I've come to some grim realizations about the value of `action` and its usefulness for my use case mentioned above. The `POP` value you'd expect to come from a back button press is actually present on back button and *also* on page load (in chrome) and on forward button, as detailed by @mjackson and others [here](https://github.com/ReactTraining/react-router/issues/1200) and [here](https://github.com/ReactTraining/react-router/issues/1498).

I'm afraid this may be the reason why it was left out of this version. However I can see how this information passed to `Match` props might still be useful, especially if combined with some other technique to differentiate between first load/forward and back.

**Comment by mjackson** [comment]
Thanks for bringing this up, @jamesism. `<Route>` components (previously called `<Match>`) now receive `{ match, history }` props in current v4, which have everything you need (i.e. use `history.action`).
