### ISSUE TITLE
Can you access router context from the component that renders it?

### ISSUE THREAD

**Issue by andynoelker** [ReactTraining/react-router#4290]
Thank you for version 4! So far I am really liking it!

Is there any way for the component that renders your `<Router />` to know anything about the current path? I'm asking because I want to style my navigation buttons based on the current page. I would assume that context is the best way of finding this, but if I try to access context in that component, the props are undefined. For example, if you take this slightly modified example from the docs:
```
class App extends Component {
  render() {
    console.log(this.context.router, this.context.history);
    return (
    <BrowserRouter>
    <div>
      <ul>
        <li><Link to="/">Home</Link></li>
        <li><Link to="/about">About</Link></li>
        <li><Link to="/topics">Topics</Link></li>
      </ul>
  
      <hr/>

      <Match exactly pattern="/" component={Home} />
      <Match pattern="/about" component={About} />
      <Match pattern="/topics" component={Topics} />
  
      <Miss component={NoMatch}/>
    </div>
  </BrowserRouter>
    )
  }
}

App.contextTypes = {
  router: React.PropTypes.object.isRequired,
  history: React.PropTypes.object.isRequired
}
```
That console log will return undefined for both of those. Of course, if I try the same thing in the child components that are accessed from the routes, I have that context along with the props that react-router passes in. Maybe this is the completely wrong approach? How would you go about adding custom styles or implementing logic to change those `<li>` components when they are in the same level as the `<Router />`? Add some type of example of this to the docs would be really awesome.

**Comment by pshrmn** [comment]
Any easy solution is to make the `<App>` a child of the router.

```js
render((
  <BrowserRouter>
    <App />
  </BrowserRouter>
), holder)
```

**Comment by andynoelker** [comment]
@pshrmn I uh...somehow didn't think of that. 😳 I feel a little silly now. I guess I am just so used to the static config that it didn't occur to me to separate my `<Match />` elements from the component where the router gets rendered. Thanks!
