### ISSUE TITLE
createServerRenderContext's `result.missed` should be true even without a `Miss` component

### ISSUE THREAD

**Issue by ryancole** [ReactTraining/react-router#4291]
In the current version 4 branch, `createServerRenderContext`'s `result.missed` will be `false` if there is no `Miss`, even if no `Match` was matched. Given a single `Match`, no `Miss`, and a URL that does not match the route provided in `Match`, the `result.missed` will be `false`. Adding in a `Miss` fixes this.

There's no way to handle a 404 scenario on the server, at the moment. They must be handled on the client, using `Miss`, which requires you to render something. In some cases you might just want to respond with a blank response, or something, on 404. This would mean you'd need to create an empty `NotFound` component just to use in the `Miss` component, even if `NotFound` is never going to be used.

If this is intended, then I propose making `ServerRouter` trigger a missed scenario even if no `Miss` exists and no routes are matched.

**Comment by timdorr** [comment]
Routes don't have to be top-level. So, not `<Match>`-ing doesn't necessarily mean a "miss" has occurred. You simply might be in the part of your app where there are no routes (perhaps an index page?). This is fundamental to how 4.0 is architected, so this is by design.
