### ISSUE TITLE
withRouter error, if used withOUT router 

### ISSUE THREAD

**Issue by dropfen** [ReactTraining/react-router#4292]
## Version
3.0.0

## Steps to reproduce

use `withRouter` without a Router ;) (Rendering stuff in styleguidist)
`this.props.router` is used only in action handlers 

## Expected Behavior

The component should at least render.

## Actual Behavior

Get an error message:

`TypeError: Cannot read property 'params' of undefined` 

Unfortunately, I am unable to debug in styleguidist quickly, but I think the error is coming from here: 
https://github.com/ReactTraining/react-router/blob/6eeb7ad358f987520f5b519e48bdd31f725cbade/modules/withRouter.js#L32

Maybe a quick and dirty fix on Line 31 would be enough:

`const router = this.props.router || this.context.router || {}`

**Comment by timdorr** [comment]
We should probably just return the wrapped component:
```js
if (!router) return <WrappedComponent {...this.props} /> 
```
A PR for this would be appreciated!
