### ISSUE TITLE
Cannot navigate outside components

### ISSUE THREAD

**Issue by sirlp2** [ReactTraining/react-router#4296]
## Version
3.0.0

## Test Case
```
browserHistory.push('/location/outside/defined/routes')
```

## Steps to reproduce
Within a defined react-router route, try to navigate outside of the defined routes using browserHistory.push('/location/outside')

### React Component
```
import { browserHistory } from 'react-router'

class RegistrationView extends React.Component {
  constructor(props) {
    super(props)
    this.state = props.registration
  }

  componentWillReceiveProps(nextProps) {
    this.setState(Object.assign({}, nextProps.registration))
    if (nextProps.registration.success) {
      browserHistory.push(this.props.redirectLoginTo)
    }
  }

  render() {
    return ( ... html form ... )
  }
}
```

```
class Wrapper extends React.Component {
  render () {
    return (
      <RegistrationView redirectLoginTo="/login" />
    )
  }
}

const route = {
  path: '/app',
  component: Wrapper
}

ReactDOM.render(
  <IntlProvider locale="en">
    <Provider store={store}>
      <Router history={browserHistory} routes={route}/>
    </Provider>
  </IntlProvider>
  , document.getElementById('container')
)
```
## Expected Behavior
According to the documentation [Navigating Outside Of Components](https://github.com/ReactTraining/react-router/blob/master/docs/guides/NavigatingOutsideOfComponents.md)

browserHistory.push('/...') should allow navigating outside of the react-router defined routes

## Actual Behavior
It logs a warning and the page does not load even though the server can handle the url.
```
Warning: [react-router] Location "/login" did not match any routes
```

**Comment by timdorr** [comment]
If you need to go to a URL that isn't in React Router, just use `location.href`. You can only `push` to locations that router knows about.

**Comment by sirlp2** [comment]
Is the reference document incorrect/outdated?

> While you can use this.props.router from withRouter to navigate around, **many apps want to be able to navigate outside of their components. They can do that with the history the app gives to Router.**

**Comment by timdorr** [comment]
That's when you want to do a navigation from outside of a component's code. For instance, in some utility function you have that doesn't live inside of a React component. That doesn't refer to when you want to navigate to an external route (i.e., making a new request to the server in your browser).
