### ISSUE TITLE
[v4] Type definitions

### ISSUE THREAD

**Issue by olee** [ReactTraining/react-router#4297]
Hi, are there any type definitions for react-router@next out yet?
I'd rather not have to write them myself, but if there are none yet, I might be able to provide them then.

**Comment by olee** [comment]
I wrote a type definition file based on the current documentation for now which seems to work perfectly:
https://gist.github.com/olee/1a9a89a619feb1cfedeb3ab01bc82b39

Not sure who maintains the [@types/react-router](https://www.npmjs.com/package/@types/react-router) package, but I guess it could be updated with those new typings maybe.

**Comment by timdorr** [comment]
The alpha's API is still in a state of flux, so typings shouldn't be written for it yet. Once the API gels, we can get some community support on it. Right now, everything is done externally.
