### ISSUE TITLE
accessing location.query via context in v4

### ISSUE THREAD

**Issue by zebapy** [ReactTraining/react-router#4301]
- 4.0.0-alpha.6
- SSR with ServerRouter
- `client.js` with BrowserRouter

I'm trying to retrieve `location.query` so I can `<Redirect />` the user to a `?next=` param when they log in, but it seems I can no longer access `location` via context somehow. I see there's `context.router` but there's no way to get `location` out of it. I'm aware the `Match` component adds location to its children but the component I need this on is deeply nested and in multiple `Match` components. 

V3 had a way to do this by setting 
```
getChildContext() {
  return {
    location: this.props.location
  }
}
```

on my `App.js` component which was root of my app. 

Am I not seeing the docs on this or is this missing currently? Sorry ahead of time if it's answered elsewhere. I couldn't find anything in issues or asking in reactiflux.

**Comment by timdorr** [comment]
You can just put it on context in your top-level matched component and then pull it out where you need it deeper in the tree. A decorator/HoC can make this easier.

**Comment by littlehome-eugene** [comment]
So `withRouter` doesn't give you `location` info right?

**Comment by mjackson** [comment]
@littlehome-eugene No, `withRouter` does give you access to the `location`.

**Comment by littlehome-eugene** [comment]
Oh how do I  get it ?

2017. 1. 28. 오후 1:01에 "MICHAEL JACKSON" <notifications@github.com>님이 작성:

**Comment by mjackson** [comment]
@littlehome-eugene 

```js
const MyComponent = withHistory(({ location }) => (
  // do whatever you want with the location here
))
```
