### ISSUE TITLE
Expose history.goBack and history.goForward on the router context object

### ISSUE THREAD

**Issue by jamesism** [ReactTraining/react-router#4302]
Hello,

Wondering if it's alright to expose the `goBack` and `goForward` methods from `history` through the `router` childContext object in order to enable programmatic `back` and `forward` functionality. The change is very small and I've already run in to a couple scenarios where this would be really useful. I've added the change and a couple tests [here](https://github.com/ReactTraining/react-router/compare/v4...jamesism:v4-back-forward?expand=1), but I'm not sure if the tests are a little too contrived. Really though it's just confirming the already tested functions from the `history` APIs. 

Please let me know what you think!

Thanks,
James

**Comment by timdorr** [comment]
The APIs for 4.0 are in flux. So, we don't yet know if this is a reasonable request. It probably is, as we want to provide good imperative escape hatches, but we won't know until Ryan and Michael nail down the API.
