### ISSUE TITLE
Bug in react-router when used in Chrome Extension

### ISSUE THREAD

**Issue by CandyOgre** [ReactTraining/react-router#4309]
In Chrome Extension application, when using nested routes, routing will not be working.
I solve this issue by using single routes.  That's what I say.
Not working:
```
  <Router history={browserHistory}>
    <Route path="/" component={App}>
      <Route path="/description-view" component={DescriptionView}/>
    </ Route>
    <Route path="/popup.html" component={App} />
    <Route path="/window.html" component={App} />
  </Router>
```

Working:
```
  <Router history={browserHistory}>
    <Route path="/" component={App}/>
    <Route path="/description-view" component={DescriptionView}/>
    <Route path="/popup.html" component={App} />
    <Route path="/window.html" component={App} />
  </Router>
```

Also, when developing Chrome Extension, we need to set up routes for basic Extension view. It was not obvious for me.

**Comment by timdorr** [comment]
For a Chrome Extension, you should be using a hash or memory history. You'll run into problems otherwise.

**Comment by CandyOgre** [comment]
@timdorr I tried to use hash and memory history. Result was the same

**Comment by CandyOgre** [comment]
@timdorr
