### ISSUE TITLE
withRouter removes the internal _owner value

### ISSUE THREAD

**Issue by john-osullivan** [ReactTraining/react-router#4314]
## Version
2.4.1

## Steps to reproduce
Given routes like:
```
export default {
    path: '/',
    component: MainApp,
    childRoutes: [
        { path: '404', component : withRouter(Page404)},
        { path: '*', component : Page404}
    ]
};
```
The Page404 component has no owner at the `/404` route, while it is owned by `MainApp` at a `/somethingelse` route.  Check the value via `this._reactInternalInstance._currentElement._owner`.

## Expected Behavior
The owner of the HOC would be MainApp, then Page404 would be owned by the HOC.

## Actual Behavior
Wrapped components lose the value which an unwrapped component would've had otherwise.  This ends up breaking refs further down the tree, because all child components have null `_owner`s from then on.

Am I confused about how the withRouter HOC should work, or is this actually a bug?  My goal is to get a very persistent `addComponentAsRefTo` bug out of the way, it seems to be stemming from losing an `_owner` value and that seems to stem from `withRouter`.

**Comment by timdorr** [comment]
You should pass [the `withRef` option](https://github.com/ReactTraining/react-router/blob/master/modules/withRouter.js#L12) to get a reference to the wrapped component. Fiddling with internal React APIs is probably going to lead to a bad time, since they aren't public and aren't guaranteed to change at any time.

**Comment by john-osullivan** [comment]
That doesn't really fix my issue, as my code isn't the one applying the refs. I'm using the draft-js-plugin-editor, and it depends on adding refs to the nodes it creates. The page component has a cold component which then loads that editor. However, if the page has no internal owner then the child had no internal owner, and that breaks the React invariant on all refs having an owner.

My goal isn't to fiddle with internal APIs, I'm debugging an issue with how refs are made. I tried adding that option and it didn't resolve the core issue of a null _owner. Is there some way to use a ref to the wrapped component in order to reestablish the _owner value?
