### ISSUE TITLE
Match and Miss children

### ISSUE THREAD

**Issue by davidcrouch** [ReactTraining/react-router#4323]
Currently, `Match`  and `Miss` are used like this:-

`<Match pattern="/:myProp" component={Child} />`

to display a child that could look like this:-

```
const Child = ({ params }) => {
  return (
    <div>
      <h3>PROP: {params.myProp}</h3>
    </div>
  )
}
```

If I'm not mistaken (my experience with v4 is limited), to pass regular properties to `Child` you would use the `render` property and assign a function. But this doesn't seem like the "React way". So why not do something more natural like this? :-

```
<Match pattern="/:id" >
    <Child  myProp="123"  />
</Match>
```

Now, should the `location`, `params` etc. properties be pushed down to `Child` by `Match` or should they be passed explicitly to the child component using a helper function like this:-

```
<Match pattern="/:myProp" >
    <Child  myProp={param(":myProp")}   />
</Match>
```

Lastly, in React Router v2 I passed properties to the component via the route to parameterize my components. But then I found that for components that were referenced by the route and also referenced directly outside of the route, I would need to insert statements like this in reusable components:-

`var myProp = this.props.myProp || this.props.route.myProp;`

Most of what I describe above is supported today in v4 using `render`, although I don't think it is very "React-like". But components still need to be "React Router aware" (not good OO) and understand the React Router properties passed in e.g. `params `structure. 

Thoughts?

**Comment by timdorr** [comment]
https://gist.github.com/ryanflorence/a301dc184f75e929a263dc1e80399a28
