### ISSUE TITLE
renderProps?? How do I know what they are? 

### ISSUE THREAD

**Issue by wzup** [ReactTraining/react-router#4324]
From you docs:

> renderProps: The props you should pass to the routing context if the route matched, undefined otherwise.

And

```
renderToString(<RouterContext {...renderProps} />)
```

And what render props do you mean? Where is list all all possible props of `renderProps`? Why do you think we should guess it?

**Comment by wzup** [comment]
@mjackson  hey, why do you close issues silently? you received a question, answer it

**Comment by qoalu** [comment]
I assume because your question comes from not understanding code.
As I understand `...renderProps` is an array that contains the props you want to pass to the Router Context. `...` is the spread operator that puts each element of the array as a separate prop.
