### ISSUE TITLE
Route nesting and page transitions

### ISSUE THREAD

**Issue by nerijusgood** [ReactTraining/react-router#4326]
Hi,

I want to use `PreactTransitionGroup` to add animation between route changes and I assume that I need to nest routes so I could animate main content change. However, I have issues nesting routes:

```
<Router>
        <App path="/">
          <Router>
            <Home path="/" />
            <Content path="/content" />
          </Router>
        </App>
</Router>

```
This is my "Global" component, where App has transition group element wrapped children. When I load app, App with Home compoenent, however when i try to go to `/content` I get empty page. Something somehow does not work. 

Am I nesting correct?

**Comment by timdorr** [comment]
You can't nest `<Router>`'s. You also should be using `<Route>` components to form the route tree, not your own components.
