### ISSUE TITLE
Mixing RRv3 and v4

### ISSUE THREAD

**Issue by liveresume** [ReactTraining/react-router#4328]
I have a large codebase which would take a while to update to v4.  

Is it possible to incrementally upgrade to v4 from v3? 
Can they be used in the same project simultaneously?

**Comment by timdorr** [comment]
No. The history instances would interfere with each other. 4.0 isn't out yet, so I would wait until an upgrade path is available.

**Comment by liveresume** [comment]
@timdorr Do you think an upgrade path would allow mixing?

**Comment by timdorr** [comment]
Nope. Trying to get two histories at once isn't going to work.

**Comment by liveresume** [comment]
@timdorr So what do you suppose an upgrade path would allow that isn't yet practical?
