### ISSUE TITLE
Allow non-client-side routes

### ISSUE THREAD

**Issue by turnerhayes** [ReactTraining/react-router#4338]
There are cases in which I'd like a request to go to the server; for instance, I have Passport.js handling social media login (e.g. Facebook) and logout. Prior to using React Router, I'd `GET /auth/fb` to kick off the login process (and `/logout` to log out).

For `/logout`, I could make an AJAX request, but I'm not sure that'll work so well for login. I'd like to be able to have specific requests go to the server rather than being handled client side. Maybe a separate prop on a route, e.g

```jsx
<Route path="/auth/fb" passToServer />
```

in which case the history listener will not intercept it.

**Comment by pshrmn** [comment]
You should just use an anchor to navigate to URLs outside of your application (even if they are on the same domain).

```js
<a href='/auth/fb'>Login with Facebook</a>
```

**Comment by turnerhayes** [comment]
That still throws a warning that `Warning: [react-router] Location "/auth/fb" did not match any routes`

**Comment by turnerhayes** [comment]
Ah, I apologize, my app was configured incorrectly; I had the authentication routes commented out. Adding them back in worked.
