### ISSUE TITLE
this.props.router.push does not create history entry

### ISSUE THREAD

**Issue by new-xd** [ReactTraining/react-router#4339]
## Version
3.0.1

## Test Case
I jump write a demo  
https://github.com/new-xd/reactrouterpushreplace

## Steps to reproduce
- npm install
- npm start
- load url http://localhost:3000/#/entry/3 in browser

## Expected Behavior
when I press back button, it will go back to http://localhost:3000/#/page/3.  
press back button twice, it will go back to http://localhost:3000/#/page/4.

## Actual Behavior
when I press back button, it will go back to blank url

## code
```js
    componentDidUpdate(prevProps, prevState) {
        if (this.props.routeParams.num != prevProps.routeParams.num) {
            if (jump.get() > 0) {
                    this.props.router.push('/page/' + (this.props.routeParams.num - 1))
                // setTimeout(() => {
                //     this.props.router.push('/page/' + (this.props.routeParams.num - 1))
                // }, 1000)
            }
        }
    }
```
if I change to use setTimeout, it works fine

**Comment by timdorr** [comment]
You're running multiple `push`es synchronously. For at least the hash history (didn't check the others), that will result in a loop of `listener`s and subsequent `push`es that will continue until your short circuit kicks in. Instead, you should hook this into the React lifecycle by storing this stuff in local component state.
