### ISSUE TITLE
can't not load script when using /.../...

### ISSUE THREAD

**Issue by EasonWang01** [ReactTraining/react-router#4341]
## Version
2.0.0

## Test Case

```
http://localhost:3000/personalInfo/edit?id=587e1c5af60dc5e0f10938d4

<Route path="/personalInfo/edit" component={PersonalInfo} />
```

will cause some lib load by <script src="..." > </script>  error for `unexpect token <`
 but below works good

```
http://localhost:3000/personalInfo?id=587e1c5af60dc5e0f10938d4

<Route path="/personalInfo" component={PersonalInfo} />
```

the problem I found is that path with more than one slash will cause `unexpect token <` 

what might cause this problem?

**Comment by pshrmn** [comment]
Your script tag is relative when it should be absolute. See this [StackOverflow question](http://stackoverflow.com/questions/29718481/unexpected-token-error-in-react-router-component)
