### ISSUE TITLE
Match.js missing in v4 branch

### ISSUE THREAD

**Issue by skolmer** [ReactTraining/react-router#4342]
It seems like the Match Component is missing in the v4 branch.
There is a [Test](https://github.com/ReactTraining/react-router/blob/v4/modules/__tests__/Match.test.js) that imports Match.js from /modules but the actual Component source is missing:
https://github.com/ReactTraining/react-router/tree/v4/modules/Match.js

**Comment by timdorr** [comment]
The API in 4.0 is changing from `Match` to `Route`. The tests still need to be updated. This is all in-progress code.
