### ISSUE TITLE
[v4] go back programatically via MemoryRouter?

### ISSUE THREAD

**Issue by IljaDaderko** [ReactTraining/react-router#4343]
It is very hard to understand from v4 docs how to go back / forward programatically.
At the moment I was only able to figure out usage of router from context via `router.transitionTo` and can't figure out how to do something similar in order to go back / forward using MemoryRouter in react native.

**Comment by pshrmn** [comment]
Starting with the beta, you will have direct access to the `history` object, which will allow you to use `history.go`, `history.goBack` and `history.goForward`. You can clone and link the current `v4` branch if you want to test this out.

**Comment by IljaDaderko** [comment]
@pshrmn should history object be accessed via context? i.e. `this.context.history` ?

**Comment by pshrmn** [comment]
The history object is now destructured onto `context.router`. I.e., `context.router.goBack(2)` and `context.router.location`.
