### ISSUE TITLE
code splitting example with webpack 2

### ISSUE THREAD

**Issue by kimown** [ReactTraining/react-router#4344]
Hi, webpack has released [2.2.0](https://github.com/webpack/webpack/commit/4be093d27942c25ec802a40268ed94e24d886b1d), so we can use [import](https://webpack.js.org/guides/migrating/#code-splitting-with-es2015) to load module dynamically, so I think an official example about react-router and webpack 2  is very necessary.

**Comment by justinmasse** [comment]
That would be fantastic, been trying to figure out this problem today myself.

**Comment by timdorr** [comment]
I added Promise support to the async functions in #3719. There are some examples in the tests: https://github.com/ReactTraining/react-router/pull/3719/files#diff-7f51f7b8bcc1ab598f60a81f4bc21724

This is probably better represented as a PR. If you want to put something together, we can definitely work on getting it added in.

**Comment by marcofugaro** [comment]
So will this work?
```js
<Route path='/page' render={() => import('./components/page')} />
```
Will webpack effectively split my code by creating a "page.js" file and requesting it only when I navigate to the url `/page`?
