### ISSUE TITLE
React Router v4 Match children attribute error

### ISSUE THREAD

**Issue by ckwong90** [ReactTraining/react-router#4346]
## Version
4.0.0

## Steps to reproduce
    <BrowerRouter>
        <Match children={()=><div>Test</div>} />
    </BrowerserRouter>

Error "TypeError: Cannot read property 'length' of undefined:"

    <BrowerRouter>
        <Match pattern="/" children={()=><div>Test</div}> />
    </BrowerserRouter>

Works!

In the documentation example, the children attribute is shown by itself. But I got an error

**Comment by timdorr** [comment]
The API is changing from the published version, so this is no longer a bug that exists (because the code doesn't exist!).

**Comment by avindra** [comment]
@timdorr Awesome that this will be supported in the new version.

Is there a timeline yet for the beta release?
