### ISSUE TITLE
"module" entry point missing in v3.0.1

### ISSUE THREAD

**Issue by insin** [ReactTraining/react-router#4347]
The `"module"` entry point [added in this PR](https://github.com/ReactTraining/react-router/pull/3672) isn't present in the [latest release's package.json](https://unpkg.com/react-router@3.0.1/package.json), so Webpack 2 won't be able to tree shake by default.

**Comment by pshrmn** [comment]
It looks like it was was lost in this commit: a3dccec. I don't see a reason for its removal.

On a similar note, this also does not exist in the v4 `package.json`.

**Comment by mjackson** [comment]
@timdorr Do you know why this was removed in v3?

As for v4, I haven't really looked into tree-shaking in webpack v2 yet. Looks like all we need to do is compile a version of our code that leaves all our `import` statements intact?

**Comment by timdorr** [comment]
Must have been a bad merge of `master` back into `next`. I'll add it back and push a 3.0.2 to get it out there.
