### ISSUE TITLE
Use Flow or TypeScript

### ISSUE THREAD

**Issue by kube** [ReactTraining/react-router#4349]
Are you planning to add static typing ?

I know this question has been already asked, but IMO a project like this one should use static typing, as a lot of people use it.

And it would make it easier to get definition files when working on a project if it came **bundled with the package**.

**Comment by mjackson** [comment]
I'd be happy to take a look at a PR that incorporates Flow into what we're doing, but it's not a tool that I've got time to consider myself right now.

**Comment by timdorr** [comment]
None of the core team are TS or Flow experts. It's best left to 3rd party typing repos, since those can operate relative to the tooling versioning, rather than this library's cadence.

**Comment by QuantumInformation** [comment]
If the core lib was written in ts, you can auto generate the d.ts stuff.

But thats not going to happen IMOP, even if I would like it too)
