### ISSUE TITLE
Passing params outside the Url 

### ISSUE THREAD

**Issue by faisalil** [ReactTraining/react-router#4350]
Hey,

We are using the react-router in our application and in some cases we are trying to pass non string params, like objects and functions between scenes. Is there a recommended way of doing this with react-router? is this something that you guys recommend in general?

**Comment by pshrmn** [comment]
You can attach state to the [`location` descriptor](https://github.com/ReactTraining/react-router/blob/v3.0.2/docs/Glossary.md#locationstate).

```js
<Link to={{ pathname: '/other-place', state={ /* pass extra data here */ }}>Other Place</Link>
```

You would then access that data through the `location` prop passed to the component rendered by a matched `<Route>`. One caveat is that a location that is navigated to directly will not have any `state` associated with it, so you will need to take that into account.

```js
<Route path='/other-place' component={OtherPlace} />

const OtherPlace = ({ location }) => (
  const { state } = location
  return null
)
```
