### ISSUE TITLE
warning.js:36 Warning: Failed prop type: Invalid prop `component` supplied to `Route`.     in Route

### ISSUE THREAD

**Issue by jadekler** [ReactTraining/react-router#4354]
The following code gives me an error:

```
warning.js:36 Warning: Failed prop type: Invalid prop `component` supplied to `Route`.
    in Route
```

```
import React from 'react'
import ReactDOM from 'react-dom'
import {Router, Route, browserHistory} from 'react-router'

ReactDOM.render(<Router history={browserHistory}>
  <Route path="/" component={<div>hi</div>}/>
</Router>, document.getElementById('root'))
```

**Comment by jadekler** [comment]
It appears you need to use `const whatever = React.createClass` or `class whatever extends React.Component`. A normal jsx component e.g. `const whatever = <div>hi</div>` will not work.

It is probably a solid idea to make the error message about this more explicit.

**Comment by pshrmn** [comment]
`<div>hi</div>` is an element, not a component. `() => <div>hi</div>` would work.

**Comment by flekschas** [comment]
@pshrmn I am running into the same issue when wrapping a component. In my case I am defining HOC like so:

```javascript
import React from "react";

const { Provider, Consumer } = React.createContext();

const withValue = Component =>
  React.forwardRef((props, ref) => (
    <Consumer>
      {value => <Component ref={ref} {...props} value={value} />}
    </Consumer>
  ));

export default withValue;

export { Provider, withValue };
```

And then later I am wrapping a class component using `withValue` as follows:

```javascript
class Comp extends React.Component { ... }
export default withValue(Comp);
```

This worked so far in every scenario except for the Router, which throws:

```
Invalid prop `component` of type `object` supplied to `Route`, expected `function`.
```

I am wondering if this is related to [`React.forwardRef`](https://reactjs.org/docs/forwarding-refs.html)?

The weird thing is that the component just renders fine.

**Comment by flekschas** [comment]
Okay apparently its an issue with `React.forwardRef()` and `Route`. I assume react-router doesn't know of `React.forwardRef` and throws a warning. I found out one can avoid this warning by passing the renderer directly to `Route` like so:

```javascript
// The following will throw a warning mentioned in my previous post
// <Route exact path="/an-outrageously-awesome-endpoint" render={Comp} />

// Passing the renderer directly to `Route` avoids this warning
<Route exact path="/an-outrageously-awesome-endpoint" render={Comp.render} />
```

**Comment by timdorr** [comment]
You need to use the 4.4 betas or wait for release.

**Comment by amcdnl** [comment]
@timdorr - Hate to ask but - any hints to when 4.4+ will be out?

**Comment by QuantechTP** [comment]
Same issue. Beta 4.4 fixed it. Thank you @timdorr . Hoping the release will come soon 👍

**Comment by luismartinezs** [comment]
@flekschas 

Try also this:

<Route exact path="/an-outrageously-awesome-endpoint" render={() => <Comp />} />

**Comment by amcdnl** [comment]
Hate to bug but any updates here?

**Comment by Hano1388** [comment]
I had the same issue, I updated react-router-dom and it fixed the issue...
`npm install react-router-dom@4.4.0-beta.6 --save`

**Comment by justinlazaro-ubidy** [comment]
having an issue to using `React.Suspense and lazy`, giving me a error
````
Failed prop type: Invalid prop `component` of type `object` supplied to `Route`, expected `function`.
```

```
{isLoggedIn &&
          privateRoutes.length > 0 &&
          privateRoutes.map(r => (
            <Route
              key={r.path}
              path={r.id}
              component={r.component}
              exact={r.exact}
            />
          ))}
```

**Comment by alan345** [comment]
or `npm install --save react-router-dom` or `yarn add react-router-dom`
==> v 5.0.0
