### ISSUE TITLE
Default location state in Route Definition 

### ISSUE THREAD

**Issue by faisalil** [ReactTraining/react-router#4356]
I was wondering if there is a way to set default route location state when defining the route? 

<Route path='somepath' />

when defining this, if I want to pass some state location params I have to do. 

history.push({ pathname: 'somepath', state: 'somestate' });

I want to be able to define different default state when defining the route. Is that possible?

**Comment by timdorr** [comment]
You can use an `onEnter` hook and replace the location with one containing your default state. You could also apply it on your route component's lifecycle methods. Or you can just handle it whenever you get the state from the location.
