### ISSUE TITLE
yarn add https://github.com/ReactTraining/react-router.git#v4 fails

### ISSUE THREAD

**Issue by babsonmatt** [ReactTraining/react-router#4358]
## Version
v4 branch latest

## Steps to reproduce
yarn add https://github.com/ReactTraining/react-router.git#v4

## Expected Behavior
install react-router successfully from v4 branch

## Actual Behavior

Package "undefined@undefined" doesn't have a "name".

**Comment by timdorr** [comment]
The latest 4.0 version is switching to a monorepo format (see 4349de35), so this install method won't work. Just check out the git repo locally and `yarn/npm link` it.

**Comment by mjackson** [comment]
Just FYI, even before we were a monorepo we didn't support installing from GitHub. We dropped it in #3164

**Comment by babsonmatt** [comment]
Thanks for the info guys
