### ISSUE TITLE
Partial app loading using webpack 2 example

### ISSUE THREAD

**Issue by notgiorgi** [ReactTraining/react-router#4360]
I made [partial app loading using webpack 2 example](https://github.com/notgiorgi/react-router-partial-app-loading), based on [huge-apps example](https://github.com/ReactTraining/react-router/tree/master/examples/huge-apps).

I think it'd be nice, if it was in the react-router/examples in stead of separate repo, I'd be glad to do a pull request, but how would that be done if this example requires different packages? I mean, how the directories should be structured.

**Comment by timdorr** [comment]
We're not looking to add any more examples to the main repo right now. I'd suggest posting about it on social media and blogs to bring attention to it. I'd be happy to retweet something for you to give it a tiny bit of boost.

**Comment by notgiorgi** [comment]
Thanks, I'd appreciate that! https://twitter.com/notgiorgi/status/825301282483224576

But I was not suggesting adding a new example, I was suggesting updating huge-apps example, like this one is doing now: #4369
