### ISSUE TITLE
Should we no longer use v4 (npm link and version removed from v4 branch)

### ISSUE THREAD

**Issue by IljaDaderko** [ReactTraining/react-router#4361]
I'm using v4 router in some personal react-native projects, noticed to day that example website moved to github readme's + link for react-router@next npm package was removed. Shall we no longer rely on it / why was this done?

**Comment by gpltaylor** [comment]
hi @IljaDaderko I am also using RR within some personal website and I don't think there are any issues using it (for non production sites). It works really well for an alpha release.

There is going to be some breaking changes in the next alpha release, but for me, that's expected to happen when you use the cutting edge branch. The code base just did a 360 but I think it's settling down now (I hope).

The docs have moved over to MD files, as the new website is designed to use them directly. Not sure when/where the new demo/tutorial site will be hosted, but it's easy to fire up the project. My guess would be **www.react-router.now.sh** as it's currently offline.

**Comment by timdorr** [comment]
4.0 is being split into several packages, much like React itself. Check them out here: https://github.com/ReactTraining/react-router/tree/v4/packages

**Comment by IljaDaderko** [comment]
@timdorr thank you for the reference, once the move is complete will you guys provide implementation examples via README?

**Comment by timdorr** [comment]
4.0 is still in a pre-release state, so everything can be considered in flux. That includes READMEs. But PRs to improve them (and other documentation) are always appreciated!

**Comment by simonvizzini** [comment]
Hi guys, I'm just getting started with react-router and so I thought I'd jump right into v4, even if it's still in alpha. 

What is the current state of v4? I installed the react-router@next package but the API is nothing like in the docs here in the v4 branch (I think the @next package is actually v3, is that possible? e.g. there is no "Route" component but "Match" instead with different props)

I'd love to learn and use v4 right now, but I'm not sure how 😃

**Comment by simonvizzini** [comment]
Nevermind, I just realized that the docs at https://react-router.now.sh are already referring to 4.0, but with a slightly different API than in the current v4 branch.
