### ISSUE TITLE
Does not work with require.js no Router ant Route in scope.

### ISSUE THREAD

**Issue by rumatoest** [ReactTraining/react-router#4364]
From example (with umd module):
import {BrowserRouter, Route, hashHistory} from 'react-router'

In real life via debugger I can see only next possible objects in scope.
BrowserRouter
HashRouter
Link
Match
MemoryRouter
Miss
NavigationPrompt
Redirect
ServerRouter
StaticRouter

**Comment by pshrmn** [comment]
You are using an old version of v4 which does not have either the `<Route>` or `<Router>` components. The new version has not been released yet, so you would need to clone the repo and build the umd modules yourself in order to test them out.

**Comment by rumatoest** [comment]
Hello.

Thanks for advice, but latest version available from NPM repository is v3.0.2 And our team works only with NPM packages.

**Comment by pshrmn** [comment]
The `Match` and `Miss` components that you have in the scope are from the v4 alpha. If you are seeing those from an NPM install, my guess is that someone installed `react-router@4.0.0-alpha.6` or `react-router@next`

**Comment by rumatoest** [comment]
But the curious thing that actually I'm building this project and my version of react-router is 3.0.2
I take react-router.js from umd directory and load this file in my app using requirejs.

**Comment by pshrmn** [comment]
I don't know how/why it would have happened, but based on the listed exports, you definitely have a v4 alpha installed. v3.0.2 has the exports listed in this file https://github.com/ReactTraining/react-router/blob/v3.0.2/modules/index.js.

I imagine if you un- and re-install React Router, making sure to specify `react-router@3.0.2` in the install, that that would fix your issue.

**Comment by rumatoest** [comment]
I'm speaking not about server based router, but about UI router part in UMD directory.

```
npm init
npm install react-router
grep Route node_modules/react-router/umd/react-router.js
```
You will not find there any exports for Route or Router

**Comment by timdorr** [comment]
Did I push a bad version? 😞  That may be what's going on here.

**Comment by timdorr** [comment]
Well, I sort of did. I didn't clean up afterwards. Hence, there's a `umd/react-router.js` in the package. You're looking for `umd/ReactRouter.js`: https://unpkg.com/react-router@3.0.2/umd/ReactRouter.js
