### ISSUE TITLE
history.back() doesn't work in ios Chrome (need to update history to > 4.4.1)

### ISSUE THREAD

**Issue by KaboomFox** [ReactTraining/react-router#4365]
## Version
2.0.0 3.0.0

## Test Case
http://jsbin.com/sacerobuxi/edit?html,js,output

## Steps to reproduce
Related to: https://github.com/ReactTraining/react-router/issues/2565
On ios Chrome window.history.back() does not work. This was fixed in the https://github.com/mjackson/history/pull/208/files  v4.4.1. If we update History. This will no longer be an issue.

## Expected Behavior
You are redirect to the previous page
## Actual Behavior
Nothing happens

**Comment by timdorr** [comment]
You linked to the wrong PR on history. It's actually at mjackson/history#383

This just needs to be backported to history 3.x and it will fix things here. You should open up an equivalent issue over there, as there's nothing to fix on this library.

**Comment by timdorr** [comment]
Also, this is the equivalent line in history to that PR (in case you want to submit a PR, which would be better!): https://github.com/mjackson/history/blob/v3.x/modules/BrowserProtocol.js#L46-L47

**Comment by KaboomFox** [comment]
@timdorr  thanks!
