### ISSUE TITLE
Update the npm @next tag

### ISSUE THREAD

**Issue by mesteche** [ReactTraining/react-router#4366]
The last version of the READMEs says that we need to install react-router@next and react-router-dom@next, but the first one will install the '4.0.0-alpha.6' and the other will just fail.

## Steps to reproduce
`npm install --save react-router@next`
`npm install --save react-router-dom@next`
## Expected Behavior
Last beta version (like from github) installed.
## Actual Behavior
alpha.6 version installed

Thanks

**Comment by pshrmn** [comment]
The beta has not been released, so the code has not been published on NPM. Once it is, the tags will be set up to work as expected.
