### ISSUE TITLE
Lerna is effectively a dependency now, not devDependency

### ISSUE THREAD

**Issue by andriytyurnikov** [ReactTraining/react-router#4368]
## Version
4.0.0

## Steps to reproduce
add `"react-router": "git+ssh://git@github.com/ReactTraining/react-router.git#v4",`
to `package.json`
## Expected Behavior
Successfull installation
## Actual Behavior
```
Exit code: 127
Command: sh
Arguments: -c lerna bootstrap
Directory: /Users/andriytyurnikov/Code/rubakas/playground/playground-react-edge/node_modules/react-router
Output:
sh: lerna: command not found
```

Invoking lerna in postinstall hook effectively makes it a dependency, not devDependency

**Comment by andriytyurnikov** [comment]
@mjackson may be interrested

**Comment by timdorr** [comment]
We don't support install from git for a variety of reasons, including this one.

FWIW, [Babel does the same thing](https://github.com/babel/babel/blob/master/package.json#L38).

**Comment by mjackson** [comment]
Thanks, @timdorr. I was just writing that up, but you beat me to it :)
