### ISSUE TITLE
3.0.1 -> 3.0.2 broken browserHistory.listen

### ISSUE THREAD

**Issue by DimitryDushkin** [ReactTraining/react-router#4370]
## Version
3.0.2

## Steps to reproduce
1. Configure webpack 2 (with tree-shaking). Not sure does it matter.
2. `browserHistory.listen(someCallbackFunc)`
2. Somewhere execute `browserHistory.push('/1')`

## Expected Behavior
3. Browser URL will change and`browserHistory.listen` will fire callback 

## Actual Behavior
3. Browser URL will change, but `browserHistory.listen` won't fire callback

**Comment by timdorr** [comment]
Check to make sure you have the right history version installed. The only change from 3.0.1 to 3.0.2 was adding the `module` entry to our package.json. No other changes were made.

**Comment by DimitryDushkin** [comment]
I've found source of problem!

In my Root component I'am importing browserHistory like this:
```js
// Root.jsx
import { browserHistory } from 'react-router/lib/browserHistory';

<Route history={ browserHistory }>...
``

but in child component I'am importing browserHistory another way:
```js
// SomeComponent
import { browserHistory } from 'react-router';

<button onClick={() => browserHistory.push('/some-route') }>...
```

and that was the problem — this is totally different browserHistory. On from `./node_modules/react-router/lib/browserHistory'` and other from `./node_modules/react-router/es/browserHistory.js`. So they had different sets of listeners.

I've changed every import of browserHistory to `import { browserHistory } from 'react-router';`
