### ISSUE TITLE
v4 - Is it possible to wrap private routes?

### ISSUE THREAD

**Issue by andreyluiz** [ReactTraining/react-router#4374]
Since the new v4 is very declarative, I am trying to declare some of my routes inside a `PrivateContent` wrapper. The code below show how I am doing that:

> I will hide the imports for brevity.

**PrivateContent.js**
```jsx
class PrivateContent extends React.Component {
  componentWillMount() {
    console.log('Private content!');
  }

  render() {
    return (
      <div>
        {this.props.children}
      </div>
    );
  }
}

export default PrivateContent;
```

**Routes.js**
```jsx
const Root = () => (
  <div className="container">
    <Match
      exactly
      pattern="/login"
      component={LoginPage}
    />

    <Match
      pattern="/forgot"
      component={ForgotPage}
    />

    <Match
      pattern="/password-reset"
      component={PasswordResetPage}
    />

    <PrivateContent>
      <Match
        exactly
        pattern="/"
        component={AppContainer}
      />
    </PrivateContent>
  </div>
);

export default Root;
```

My expectation was to access `/` and see in the console `Private content!` message. And when I access `/login` not to see the message.

However the message is shown even if I access the `/login` or `/forgot` routes.

How can I get this to work as expected? Does react-router v4 behavior this way? Am I doing something wrong?

**Comment by marbemac** [comment]
Looks like you need the new Switch component. It's in v4 but not yet part of an official release - check out https://github.com/ReactTraining/react-router/blob/v4/packages/react-router-website/api/Switch.md for some insights into how it will work.

**Comment by andreyluiz** [comment]
Hmm, interesting. I think inverting should work, since the PrivateContent will aways performe the same check for authenticated user. Thank you for the information. :)
