### ISSUE TITLE
[react-native] lerna not found

### ISSUE THREAD

**Issue by IljaDaderko** [ReactTraining/react-router#4376]
Tried to test current v4 branch in a react native project today, I understand that this is still pre-release, but I believe v4 branch should be good for testing? after doing `yarn add ReactTraining/react-router#v4` I got following error output

```
error /Users/ilja/Documents/repositories/skimitar/node_modules/react-router-packages: Command failed.
Exit code: 127
Command: sh
Arguments: -c lerna bootstrap
Directory: /Users/ilja/Documents/repositories/skimitar/node_modules/react-router-packages
Output:
sh: lerna: command not found
```

After googling up lerna it seems to be some sort of package manager, but not sure what the error is. Any chance to get some advice on this to set up the router?

**Comment by mjackson** [comment]
We don't currently support installing from GitHub, for various reasons explained elsewhere in the issue tracker. We use lerna to manage the monorepo in v4, so it's just a development tool. Nothing users need to know about.

We'll have a beta release shortly, which you can `npm install` and use :)

**Comment by IljaDaderko** [comment]
@mjackson I see, thank you for clarification. Eager to start using beta release, v4 api is honestly most logical routing solution for react so far in my opinion 👍 heard you guys will expose history via context as well?
