### ISSUE TITLE
Named components only inject props into their parents (not the entire ancestry)

### ISSUE THREAD

**Issue by nevir** [ReactTraining/react-router#4378]
I'm not sure if this is considered a bug, or a feature request (and wasn't able to find any other issues or SO questions on it):

---

react-router@3.0.1

Named components declared via `components` appear to only be passed to their parent route, rather than all the way up the hierarchy.  This makes it difficult/impossible if you want to have some base layout, and some conditional layouts based on path.  For example:

```jsx
<Route component={BaseLayout}> 
  <Route path='/foo' component={FooLayout}
    <Route path='/:id' components={{ children: FooDetails, nav: FooNav }} />
  </Route>
</Route>
```

`FooLayout` receives both `children` and `nav` as props, but `BaseLayout` receives neither of them.

In my real world usage, I want the inner layout component (`FooLayout` in this example) to provide some common styling and structure for the main content area, but not mess with navigation (which is handled by `BaseLayout`).

---

The behavior I expected was that _all_ components in the ancestry would receive the named components

**Comment by pshrmn** [comment]
A parent `<Route>` is responsible for rendering the elements returned by its child `<Route>`. You can read the code responsible for this [here](https://github.com/ReactTraining/react-router/blob/v3.0.2/modules/RouterContext.js#L52-L93).

If your `BaseLayout` component should be receiving a `nav` element, your `/foo` route needs to give it one.

```js
<Route component={BaseLayout}>
  <Route path='/foo' components={{ children: FooLayout, nav: FooNav }}>
    <Route path=':id' components={{ children: FooDetails, nav: FooDetailsNav }} />
  </Route>
</Route>
```

```js
const FooNav = ({ nav }) => nav ? React.Children.only(nav) : null
```
