### ISSUE TITLE
<Link> and <a> returns wrong url

### ISSUE THREAD

**Issue by zRaspina** [ReactTraining/react-router#4380]
Hi guys,
I have used the following component `ActionButon` in one of my page with this address `http://localhost:3000/dashboard/projects`:

```
<ActionButton editLink={`dashboard/projects/edit/${row._id}`} detailLink={`projects/${row._id}`}/>
```  

The following code is part of the `ActionButton` component code that render one part of it:

```
renderEdit() {
    return (
      <a href={this.props.editLink} className=" btn btn-info">
      <span className="glyphicon glyphicon-pencil " ></span></a>
    );
}
```
The following results rendered as link url, but it's wrong because it's return "**dashboard**" twice:

```
dashboard/dashboard/projects/edit/1ddfdf
```
I also trying to use `Link` rather than `a` but it's returned same result.

How we can fix it?

**/CC:** @benvinegar , @zwily , @jeffbski , @spicyj , @doctyper

**Comment by mjackson** [comment]
This is not a problem with our library. If I were you, I'd double check the value of the `editLink` prop to make sure you're getting what you'd expect.

**Comment by zRaspina** [comment]
Hi @mjackson I think it's a bug because when I've been in `http://localhost:3000/dashboard/projects` url and set `editLink` props to `dashboard/projects/edit/${row._id}` why it's refer to `dashboard/dashboard/projects/edit/1ddfdf`?
I don't understand this?

**Comment by zRaspina** [comment]
I reproduced this issue as a sample project. You can download and run it and first go to this url `http://localhost:3000/dashboard/test2` then click on the `go` button in the page and attention to page URL it's go to test3 correctly but URL is wrong like this: `http://localhost:3000/dashboard/dashboard/test2/test3`.
What's happened here guys. Is it a bug or my code is wrong?

This is my code:


[This is my code (I don't know why but I couldn't upload file in github)](http://s000.tinyupload.com/index.php?file_id=24918955356728125489)

**/CC:** @benvinegar , @zwily , @jeffbski , @spicyj , @doctyper , @mjackson

**Comment by spicyj** [comment]
Hi @zRaspina – Please don't CC people like this on issues. It's annoying, and the maintainers of this repository will see your comments regardless.

**Comment by cyclops24** [comment]
I also test this code and it seems it's a bug. :thinking: 
But why this issue closed? Is it fixed in any version?

**Comment by pshrmn** [comment]
This is closed because it is a usage question, not a bug.

1. The original question is using an `<a>`, not a `<Link>`, so React Router won't be involved in the actual navigation.
2. Even if it was a `<Link>`, the `pathname` that the user is attempting to navigate to is relative, which is not supported by React Router.
3. The relative `pathname` is improperly formed. If you are at `/dashboard/project` and click a relative link to `dashboard/project/1`, that is resolved relative to `/dashboard` and you will end up at `/dashboard/dashboard/project/1`. Make the `pathname` absolute and this will work.
