### ISSUE TITLE
<Miss /> won't worked properly on redirect

### ISSUE THREAD

**Issue by rico345100** [ReactTraining/react-router#4381]
Thank you for made this great module.

I'm using RR 4.0.0-alpha.6, having trouble with Miss. In my application, when user refresh the page, top component <App /> determines that user was logged in or not, read from the disk(by localstorage).

This is the code:

```javascript
if(!localJSONStorage.getJSON('auth')) {
	localJSONStorage.setJSON('auth', {
		loggedIn: false
	});
}

let loggedIn = localJSONStorage.getJSON('auth').loggedIn;

if(loggedIn ) {
	store.dispatch({
		type: SET_LOGGED_IN,
		data: loggedIn
	});
}

class App extends Component {
	componentDidMount() {
		const { loggedIn, dispatch } = this.props;

		if(!loggedIn) {
			dispatch({
				type: SET_LOGIN_FALLBACK_URL,
				data: location.href
			});
			
			redirect('/login');
		}
	}
	render() {
		return (
			<div>
				<Match pattern="/login" exactly children={({ macthed }) => 
					<Login />
				}/>
				<Miss render={() => {
					console.log('render');
					return (
						<div className="app">
							<Navigation />
							<Views />
						</div>
					);
				}}/>
			</div>
		);
	}
}

const ConnectedApp = connect((state) => {
	return {
		loggedIn: state.auth.loggedIn
	};
})(App);

export default ConnectedApp;
```

Please check render method, you can see that there is one Match and one Miss. When user connect from "/" or "/login" without logged in, it redirects to "/login" and Login component rendered.

But when user connect from "/dashboard" or something else without logged in, Login component was rendered but also Miss component rendered too! 

At the moment that user connected as "/dashboard", yes, Miss should be rendered because it isn't "/login", but after redirect, why Miss still rendered?

P.S. I'm using history.push() to redirect. Is this can be a problem? If so, is there a way to "proper" redirect?

**Comment by pshrmn** [comment]
The `<Miss>` component has been removed. This change will be reflected in the beta release.

**Comment by rico345100** [comment]
Oh well, that's sad. Okay, I'll gonna find another way to fix it. Thanks.
