### ISSUE TITLE
Server Side HTTP Status

### ISSUE THREAD

**Issue by pshrmn** [ReactTraining/react-router#4382]
Right now, there isn't a good way for someone that is using server side rendering to indicate that a "miss" route (i.e., the last `<Route>` in a `<Switch>`) should have a 404 status code. For redirects, I have seen suggestions for adding a status in the `state` property of a location descripto, but there isn't a good way to do the same with 404s.

```js
<Redirect to={{ pathname: '/other-page', state: { status: '301' }}} />
```

One possible solution for this would be to add a `setStatus` type method to the `history` object that the `<StaticRouter>` created.

```js
setStatus = (status) => {
  context.status = status
}
```

The function might have to be slightly more resilient than the one above if more than 404s are done using this and some status codes should take precedence over others.

This would also provide an opportunity to set a status code on a redirect instead of relying on `location.state`.

```js
<Redirect to='/other-page' permanent />
```

My first thought on where to specify misses would be to set the status as a prop of the `<Route>`. This could work, but I'm not sure if you want to tack on extra props to the `<Route>` component, especially because it would only be useful on the server.

```js
// :/
<Route component={CatchAll} miss />
```

Alternatively, a simple `<Status code='404' />` component could be rendered in the matched component. I'm unsure if there would be a reason to support any other status codes besides 404s here or if a `<NotFound />` component that only sets the 404 status code would be preferable.

```js
<Route render={() => (
  <div>
    <Status code='404' />
    <h1>Page Not Found :(</h1>
  </div>
)} />
```

```js
class Status extend React.Component {
  static contextTypes = {
    router: React.PropTypes.shape({
      isStatic: React.PropTypes.bool,
      setStatus: React.PropTypes.func
    }).isRequired
  }

  static propTypes = {
    status: React.PropTypes.string.isRequired
  }

  componentWillMount() {
    const { isStatic, setStatus } = this.context.router
    if (isStatic) {
      setStatus(this.props.status)
    }
  }

  render() {
    return null
  }
}
```

**Comment by mjackson** [comment]
Thanks for the thoughts here, @pshrmn. I like your `<Status>` component. In fact, I had discussed something similar with @ryanflorence just a few weeks ago.

I wonder if, instead of `router.setStatus`, it makes sense to have a general `setState`-like function for the `<StaticRouter>`'s `context` object. Sort of like "merge all this stuff onto the static context". It could be used by your `<Status>` component as well as others like this:

```js
this.context.router.setContext({ status: 404 })
```

What do you think?

**Comment by pshrmn** [comment]
Exposing the `context` object sounds like a good solution to me.

**Comment by mjackson** [comment]
Fixed in https://github.com/ReactTraining/react-router/commit/bb663793717ab14fb738d70d752ab0f424dcadce
