### ISSUE TITLE
New release of react router v4 coming in a day or two in november?

### ISSUE THREAD

**Issue by kasperpeulen** [ReactTraining/react-router#4384]
![image](https://cloud.githubusercontent.com/assets/1035299/22405000/d3c0938c-e63b-11e6-8b26-a9b3ff534c0b.png)

I was just wondering, in the latest alpha release of november there was a note that you should wait before upgrading because a new release would come in a day or two. What is the status of that? Should I just use alpha.6 if I want to try out the react router v4?

**Comment by mjackson** [comment]
It's hard work to get the abstraction right :) We've been [working very hard on v4](https://github.com/ReactTraining/react-router/commits/v4) and should have a beta release this week.

**Comment by kasperpeulen** [comment]
great thanks for the info
