### ISSUE TITLE
Update v4 doc links

### ISSUE THREAD

**Issue by larrxu** [ReactTraining/react-router#4390]
Please update the links on the front page:

- APIs: https://github.com/ReactTraining/react-router/tree/v4/packages/react-router-website/modules/api
- Examples: https://github.com/ReactTraining/react-router/tree/v4/packages/react-router-website/modules/examples

**Comment by larrxu** [comment]
Can you also update the doc with what npm package@version to install for v4?

**Comment by timdorr** [comment]
`react-router@next`. We've been through this before with 2.0 and 3.0, so it'll get done soon enough :)

**Comment by larrxu** [comment]
Sure. I just feel as a new user who wants to try v4 it's hard to figure out what version to install. Even the npm website doesn't show the v4 versions.

**Comment by garmjs** [comment]
you can find info here https://reacttraining.com/react-router/
