### ISSUE TITLE
[Sugestion] Make it clearer that NativeRouter inherits from MemoryRouter

### ISSUE THREAD

**Issue by IljaDaderko** [ReactTraining/react-router#4393]
I wen't through source of NativeRouter, seems it is a MemoryRouter with native storage and few methods added on top of it, so it should still be possible to use `initialEntries` for example. This is unclear from documentation, but is very useful feature (in my opinion) that could help few folks out. Unless I am misunderstanding this, wouldn't it be a good idea to indicate this in documentation?

**Comment by mjackson** [comment]
Thanks for the suggestion, @IljaDaderko :)

I wouldn't say that `<NativeRouter>` *inherits* from `<MemoryRouter>`. Rather, it *renders* a `<MemoryRouter>`. That's an important difference.

The fact that `<NativeRouter>` renders a `<MemoryRouter>` is an implementation detail and shouldn't need documentation. In fact, the props to `<MemoryRouter>` (i.e. `initialEntries`, `initialIndex`, etc.) aren't even exposed in `<NativeRouter>`'s interface. Instead, [`<NativeRouter>` uses those props to plug in values it reads from `AsyncStorage`](https://github.com/ReactTraining/react-router/blob/78808c0abba6dee37b900827fba280da57e11569/packages/react-router-native/NativeRouter.js#L69-L70).
