### ISSUE TITLE
Can't resolve ./StaticRouter

### ISSUE THREAD

**Issue by mdurling** [ReactTraining/react-router#4394]
Build error with latest version of react-router
## Version
4.0.0-beta.2

ERROR in ./~/react-router/index.js
Module not found: Error: Can't resolve './StaticRouter' in '/Users/mdurling/Repos/inmotionnow/proximus/node_modules/react-router'
 @ ./~/react-router/index.js 26:21-46

There is no StaticRouter.js file in the package

**Comment by IljaDaderko** [comment]
This was fixed via #4389 we just need to wait while it is pushed up to npm

**Comment by joeltello** [comment]
same here!!

**Comment by pshrmn** [comment]
Will be fixed in next release as @IljaDaderko said

**Comment by mdurling** [comment]
@IljaDaderko @pshrmn Any idea how soon that might be? I don't want to implement any temporary measures if this fix is coming quickly, but our deployment is currently broken.

**Comment by IljaDaderko** [comment]
@mdurling I don't think it will take to long as next release fixes this critical issue + one related to react-router-dom

**Comment by YasserKaddour** [comment]
If you are eager to use the beta; you can move the missing file from `node_modules/react-router` to `node_modules/react-router-dom`, and renaming `ServerRouter.js` to `StaticRouter.js`

**Comment by imWildCat** [comment]
There might be some issues about installation scripts:

```json
// package.json
"react-router": "git://github.com/ReactTraining/react-router.git#v4",
```

```bash
[4/4] 📃  Building fresh packages...
⠁
⠁
⠁
⠁
error /path/to/project/node_modules/react-router: Command failed.
Exit code: 127
Command: sh
Arguments: -c lerna bootstrap
Directory: /path/to/project/node_modules/react-router
Output:
sh: lerna: command not found
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by kwelch** [comment]
This has been pushed see PR #4388

**Comment by kwelch** [comment]
This repo is not setup to allow dependency directly to git. See #4358 

Additionally the fix has been pushed to npm.

**Comment by mjackson** [comment]
This is fixed in beta 3. Sorry about the inconvenience. Please update! `npm install react-router-dom@next`

@imWildCat We do not support installing directly from GitHub for a variety of reasons. Please install from npm instead :)
