### ISSUE TITLE
invariant dependency missing from react-router in v4

### ISSUE THREAD

**Issue by kesne** [ReactTraining/react-router#4399]
## Version
4.0.0-beta.3

## Test Case
```js
import { BrowserRouter } from 'react-router-dom';
```

## Steps to reproduce
On fresh install of latest beta, add the test case code, look at console.

## Expected Behavior
`invariant` is defined.

## Actual Behavior
```
Can't resolve 'invariant' in 'project/node_modules/react-router-dom/node_modules/react-router'
```

**Comment by kwelch** [comment]
Duplicate see PR #4388

**Comment by kesne** [comment]
@kwelch That was fixed in `4.0.0-beta.3`, whereas this issue persists in that version. This appears to be due to `invariant` missing from the `dependencies` in the `react-router` package.

**Comment by mjackson** [comment]
Thanks for the heads up, @kesne. I sometimes forget to `--save` when I `npm install` stuff.

**Comment by mjackson** [comment]
This will be fixed in beta.4. In the meantime, please `npm install invariant` manually.
