### ISSUE TITLE
Router.isActive never checks the query

### ISSUE THREAD

**Issue by aequasi** [ReactTraining/react-router#4400]
https://github.com/ReactTraining/react-router/blob/master/modules/isActive.js#L125

On this line, when using createBrowserHistory, query is never in the location. 

https://github.com/mjackson/history/blob/master/modules/LocationUtils.js#L5

**Comment by pshrmn** [comment]
You linked to v4 of `history`, which is not compatible with the current master branch of React Router (v3). In v4 of `history`, there is no `query` object on a location descriptor, only a `search` string.

**Comment by timdorr** [comment]
Correct, this is just a version mismatch.

**Comment by aequasi** [comment]
I linked the wrong version. Still an issue with this in v3 of history.js

https://github.com/mjackson/history/blob/v3.2.1/modules/LocationUtils.js#L9

**Comment by timdorr** [comment]
We [wrap our router](https://github.com/ReactTraining/react-router/blob/master/modules/useRouterHistory.js#L6) with [the `useQueries` enhancer](https://github.com/mjackson/history/blob/v3.2.1/modules/useQueries.js).
