### ISSUE TITLE
index.js file in react-router-dom is empty after installing

### ISSUE THREAD

**Issue by TomLingham** [ReactTraining/react-router#4401]
## Version
4.0.0-beta.3
react-router-dom@0.0.0

## Steps to reproduce
Install react-router-dom and try and import any of the expected modules (`BrowserRouter` for example) it.

## Expected Behavior
The module should be imported.

## Actual Behavior
I get the value `undefined` instead and upon further inspection the index.js file in the `react-router-dom` directory in node_modules is empty.

**Comment by TomLingham** [comment]
Use `npm i -S react-router-dom@next`.

**Comment by pr1ntr** [comment]
I get a
```
ERROR in ./~/react-router-dom/Prompt.js
[1] Module not found: Error: Can't resolve 'react-router/Prompt' in {path}
```

error from webpack for every export in this package...
