### ISSUE TITLE
Pinterest example for v4

### ISSUE THREAD

**Issue by Vincz** [ReactTraining/react-router#4404]
Hi! I'm thinking to update to v4 (because of the new matching features), but the last thing I need is the ability to have Pinterest like modals like in the previous version. I know it was a work in progress for this new version. Any update about this? 
Thank you very much

**Comment by timdorr** [comment]
It follows the same basic format as before: Use `location.state` on the link to the modal version and that state data is removed on a browser-initiated reload (giving you a non-modal view). It might be a little hard to show that in the website, given that the virtual browser there doesn't give you a "real" browser reload. 

Perhaps we should start a react-router-examples sub-package?
