### ISSUE TITLE
NavLink: Cannot read property 'location' of undefined

### ISSUE THREAD

**Issue by heikkilamarko** [ReactTraining/react-router#4406]
## Version
4.0.0-beta.3

## Steps to reproduce
Use `NavLink` component in your code.

## Expected Behavior
Works as expected, without any errors.

## Actual Behavior
I get the following error:
```
TypeError: Cannot read property 'location' of undefined
```
NavLink.js
```
<Route
  path={typeof to === 'object' ? to.pathname : to}
  children={({ history, match }) => {
    const isActive = !!(getIsActive ? getIsActive(match, history.location) : match)
```
To make NavLink work without errors, I had to change `history` to `location` and `history.location` to `location`:
```
<Route
  path={typeof to === 'object' ? to.pathname : to}
  children={({ location, match }) => {
    const isActive = !!(getIsActive ? getIsActive(match, location) : match)
```

**Comment by timdorr** [comment]
Good catch! It's because [we spread the `router`/`history` object into the route component](https://github.com/ReactTraining/react-router/blob/v4/packages/react-router/modules/Route.js#L107) instead of making it an individual prop.

**Comment by pshrmn** [comment]
@timdorr #4403 fixes this. The original implementation was actually what we want now, but at the time the `history` variable was being passed instead of destructuring it and passing its properties. The `<NavLink>` tests haven't been created yet, which is why this wasn't caught before.

**Comment by timdorr** [comment]
Yup, working my way down the big list of notifications 😄
