### ISSUE TITLE
Disable sorting QueryString Parameters (React Router)?

### ISSUE THREAD

**Issue by fullyfaltu** [ReactTraining/react-router#4409]
I am trying to set a Route path with a query string. But react-router **always sorts query params** and shows alphabatically sorted querystring in URL.

For example, I have a location filter page where I add filters to my location list. If I filter _"Pakistan"_: "Lahore", _"India"_: "Delhi", and then _"America"_: "Washington", the URL should look like:
`/Search?Pakistan=Lahore&India=Delhi&America=Washington`

But URL shows it as follows (alphabetically sorted):
`/Search?America=Washington&India=Delhi&Pakistan=Lahore`

How can I disable this sorting feature in react-router?

**Comment by mjackson** [comment]
AFAIK we don't *intentionally* sort the query params anywhere. v4 gets rid of query string handling entirely, so you should be able to do whatever you'd like.
