### ISSUE TITLE
Ability to set default initial route in NativeRouter?

### ISSUE THREAD

**Issue by IljaDaderko** [ReactTraining/react-router#4413]
Prior to v4 it was possible to `<MemoryRouter initialEntries={['/sign-in']}>` in order to set initial route to be sign-ip, I attempted to do so with NativeRouter as it is built atop of memory one

```
<NativeRouter initialEntries={['/sign-in']}>
```

however app routes to `/` initially. Is there a way to override this in v4 beta?

**Comment by IljaDaderko** [comment]
Is setting this up inside `componentDidMount` of `App.js` (App renders NativeRouter) through `AsyncStorage` correct?

**Comment by mjackson** [comment]
Ah, this is an excellent point. We should be able to expose `<NativeRouter initialEntries>` and `<NativeRouter initialIndex>` as props and just plug them in here: https://github.com/ReactTraining/react-router/blob/e3cc25ad1fef7620d5868054f0d5f9eb858533c9/packages/react-router-native/NativeRouter.js#L56-L57

Would love to see a PR (with some tests, please!) that do this. You up for it, @IljaDaderko?

**Comment by IljaDaderko** [comment]
@mjackson yeh sure thing, might need some help with tests, but will mention it in the pr 👍

**Comment by IljaDaderko** [comment]
Docs state that memory routers initial index is of type `array`, but implementation shows number, is this an issue? If so could fix this one as well

**Comment by mjackson** [comment]
Ya, `initialIndex` should be a number. `initialEntries` is an array. The [docs on `createMemoryHistory`](https://github.com/mjackson/history#usage) may be useful here.
