### ISSUE TITLE
Support for parsing location.search

### ISSUE THREAD

**Issue by kgoggin** [ReactTraining/react-router#4414]
First off - really loving v4 and the flexibility it provides! Thanks for your hard work!

In the alpha, you could access the parsed search string off of the location object, so that `/route?doTheThing=absolutely` could be accessed in a route via `location.query.doTheThing`. Do y'all ever plan to support that in v4, or should I be using some other lib to parse `location.search`? I've got it working with  [query-string](https://github.com/sindresorhus/query-string) for now (first parser I found) which works just fine, but it does seem nice to have access to that parsed string via the RR API instead of needing to pull in another dependency. Then again, given the more simplified API in general, I could also see an argument for leaving it up to consumers to choose how they want to handle that string themselves. Or maybe it'd go in as a part of the history API?

Mostly just trying to see if y'all have already made a decision one way or the other. If it's something you'd consider adding, I'd be up for taking a stab at it.

Thanks!

**Comment by mjackson** [comment]
Please see the discussion in https://github.com/ReactTraining/react-router/issues/4410

**Comment by jedwards1211** [comment]
@kgoggin you may be interested in `react-router-parsed`, a little library I made that wraps `<Route>` with parsing logic you specify and injects parsed params and query into the route component.
