### ISSUE TITLE
list  of Links performance optimization

### ISSUE THREAD

**Issue by mogadanez** [ReactTraining/react-router#4416]
## Version
3.0.2

## Steps to reproduce

have a component with list  of Links

```
import React, { Component, PropTypes } from 'react'
import { Link } from 'react-router';
import  Topic  from './Topic';


const renderItems = (items)=>{
    if( items )
        return items.map( item=>{
            return (
                <Link key={item.uid} activeClassName="selected" className="topic-container" to={`/${item["type"]}/${item["id"]}`} >
                    <Topic item={item}/>
                </Link>
            )
        } )
}

const TopicListing = ({ items }) => {
    return (
        <div className="topic-listing">
            {renderItems(items)}
        </div>
    )
}
TopicListing.propTypes = {
    entity: PropTypes.array
}

export default TopicListing
```

## Expected Behavior
On clicking through items only prev and new should be touched

## Actual Behavior
when I click links, url update fine and selected item updated as well,
but profiler show that all links are touched 
![image](https://cloud.githubusercontent.com/assets/790307/22476697/97047c20-e7e3-11e6-8e64-7b0a5a5bf655.png)

maybe Link should have some shouldComponentUpdate implementation?

**Comment by timdorr** [comment]
Having an activeClass means we have to check if it should be active after every URL change. No way around that.
