### ISSUE TITLE
Unclear how to use history

### ISSUE THREAD

**Issue by IljaDaderko** [ReactTraining/react-router#4417]
Going through the doc's it is a bit unclear how history should be used, is it through `withRouter` or context? connected my component to router props using `widthRouter` and it indeed exposes things like `push` that seem to be from history, but also some other default props not related to react-router. Also tried `import { history } from 'react-router-native'` but in this case history is undefined. What's recommended way to just get full history object?

**Comment by pshrmn** [comment]
The `history` object is destructured onto `context.router`. There are three ways (that I know of) to access its methods & properties.

```js
// 1
const ThroughContext = (props, context) => {
  // history methods & properties are available through context.router
}

ThroughContext.contextTypes = {
  router: PropTypes.object
}

// 2
const WithWithRouter = withRouter((props) => {
  // history methods & properties are available through props
})

// 3
const InRoute = () => (
  <Route render={(props) => {
    // history methods & properties are available through props
  }} />
)
```

**Comment by IljaDaderko** [comment]
I guess cleanest way for my case is via context, thank you :)
