### ISSUE TITLE
Update Redux example for v4 beta

### ISSUE THREAD

**Issue by pr1ntr** [ReactTraining/react-router#4418]
## Version
4.0.0-beta.3

I would like to see an approach for integrating with redux now that the onChange is no longer in the BrowserRouter. Thanks.

**Comment by robinvdvleuten** [comment]
I managed to get the action dispatched with the following HoC;

```js
import React, { PropTypes } from 'react'
import { Route } from 'react-router-dom'

const ReduxRoute = ({ component, render, locationChange, ...rest }) => {
  return <Route {...rest} render={props => locationChange(props.location) && (render ? render(props) : React.createElement(component, props))} />
}

ReduxRoute.propTypes = {
  ...Route.propTypes,
  locationChange: PropTypes.func.isRequired
}

export default ReduxRoute
```

And then use it in my application like this;

```js
import React, { Component, PropTypes } from 'react'
import { BrowserRouter as Router } from 'react-router-dom'
import ReduxRoute from './ReduxRoute'

class Application extends Component {
  render () {
    return (
      <Router>
        <div>
          <Redux path="/hours" component={HoursOverview} locationChange={(location) => this.props.dispatch({ type: 'LOCATION_CHANGE', location })} />
        </div>
      </Router>
    )
  }
}

export default Application
```

Hopefully this will help anybody while waiting for the "official" solution 😄

**Comment by dtipson** [comment]
I'd been using react-router-addons-controlled/ControlledBrowserRouter with the alpha without any problems (even though it's 0.0.1), but got history.listen undefined errors when I tried out the beta version.  Haven't been able to figure out what the exact issue is yet myself, but hopefully there will be another pass soon now that v4's api has firmed up.

**Comment by pr1ntr** [comment]
Ah thanks! That will be helpful.

**Comment by gilbarbara** [comment]
Hey,
For somebody else looking a simple react-router with redux, I'm using this:
https://gist.github.com/gilbarbara/ee0bdd22851bd897b864b0c57b4cb070
