### ISSUE TITLE
Consider adding "module" entry point to v4

### ISSUE THREAD

**Issue by billyjanitsch** [ReactTraining/react-router#4425]
Originally brought up in #4347 

v3 ships with a "module" entry in package.json pointing to an `es/` build (still transpiled, but with the `import`/`export` statements left in tact). This allows bundlers like webpack 2 and rollup to implement tree-shaking (not possible in the standard build since the transpiled `require` calls can't be statically analyzed).

This is a really useful feature as it cuts down on bundle size significantly -- have you considered adding it to v4 as well?

I realize that in v4, you can currently do:
```js
import Link from 'react-router/Link'
import Redirect from 'react-router/Redirect'
```

But it doesn't allow for further shaking within the lib code, and is quite a bit more verbose than:
```js
import {Link, Redirect} from 'react-router'
```

If you're interested, I'm happy to work on a PR.

**Comment by mjackson** [comment]
Ya, we should probably bring this back. Let's just copy over whatever we are doing in v3.

**Comment by billyjanitsch** [comment]
It'll be slightly more complicated than the single-package v3 solution; the [re-exports](https://github.com/ReactTraining/react-router/blob/v4/packages/react-router-dom/modules/Route.js) are currently cherry-picked but will need to export from top level APIs (i.e. `export {Route} from 'react-router'`) for the descendant packages to be tree-shaken as well.

If you want, I can add a step to the CJS builds which converts them back to cherry-picked imports ([this babel plugin](https://github.com/lodash/babel-plugin-lodash) would work) to keep the bundle size saving option for non-tree-shaking bundlers.

**Comment by mjackson** [comment]
Let's follow up in #4432
