### ISSUE TITLE
I think I missed something regarding v4

### ISSUE THREAD

**Issue by andreyluiz** [ReactTraining/react-router#4426]
Guys, it's very quick.

What happened with the `Match` component? I saw the docs and became surprised with a `react-router-dom` thing, with a `Route` component like before.

Does it comes with v4? Or is it an update in v3?

Thank you.

**Comment by mjackson** [comment]
`<Match>` was something we were playing with in the v4 alpha. But the alpha was just a spike. We renamed it to `<Route>` in the v4 beta to make backwards compat with v2/3 easy.

**Comment by andreyluiz** [comment]
Thank you. :)
