### ISSUE TITLE
Dispatching push('/route') from non component environment?

### ISSUE THREAD

**Issue by IljaDaderko** [ReactTraining/react-router#4431]
I'm trying to figure out a way how to dispatch routers `.push('/route')` if I am not inside a component i.e I am dispatching an async function from my `helpers/api.js` file that should transition to a certain page after success. Only way I can think of is to keep passing this push function to every api call that needs it, but a much better way would be to do something along the lines:

`import { push } from 'react-router'`

is something like this achievable?

**Comment by pshrmn** [comment]
`push` is a `history` method. If you don't want to pass it as an argument to the functions, you would need to create your own `history` instance and use `<Router>` instead of one of the convenience router components (`<BrowserRouter>`, etc.)

```js
// history.js
import { createBrowserHistory } from 'history'
export default createBrowserHistory({ /* set an options here */ })

// index.js
import { Router } from 'react-router-dom'
import history from './history'

render((
  <Router history={history}>
    <App />
  </Router>
), holder)
```
