### ISSUE TITLE
What happened to react-router-addons-controlled?

### ISSUE THREAD

**Issue by randallknutson** [ReactTraining/react-router#4434]
Up until recently there was a repo in ReactTraining for react-router-addons-controlled. This was really useful for combining react-router with redux. It appears that this has been removed. Was there any reason for that and thoughts on the future or redux integration?

**Comment by timdorr** [comment]
It was built for the early alpha versions, which are completely different than later alphas and the current beta. So, it's relevance has long since passed and having it out there as a official-looking thing wasn't doing anyone any favors.

**Comment by randallknutson** [comment]
Thats fine. The documentation for v4 still points to the repo though. Also, what is the new best practice for redux integration?

**Comment by timdorr** [comment]
Wait for answers :) It's only been a couple days. We'll have something together for it soon.

**Comment by shepmaster** [comment]
Pushing a README to the old repository URL stating what you said here ("Code was no longer useful, hold tight") might have saved me some time, so it might save some other folks as well.

**Comment by jtag05** [comment]
I'd also appreciate some direction on this as I'm currently utilizing this now dead repo which prevents me from upgrading to follow along with your progress.
