### ISSUE TITLE
Upgrade webpack to v2

### ISSUE THREAD

**Issue by billyjanitsch** [ReactTraining/react-router#4437]
Are you interested in bumping webpack to v2 now that it's been released as stable? If so, happy to take care of the PR.

**Comment by mjackson** [comment]
Not particularly, no. We only use webpack for our UMD build and for our tests. I'm actually keen to swap out webpack with rollup though, in case you're interested in taking that on. I think rollup will give us the smallest UMD bundle, but it's not really high priority. Most people using the router are just importing bits and pieces I think, and not even using the UMD build.

But thanks for the offer :)

**Comment by timdorr** [comment]
I'd be interested in webpack 2 once scope hoisting (aka, what Rollup does) gets added: https://webpack.js.org/vote/

**Comment by mjackson** [comment]
Why not just use Rollup, then?

**Comment by timdorr** [comment]
Webpack 2 is easier to upgrade the tooling to (just some renamed config keys really) and will net a similar or greater size benefit once that feature lands.
