### ISSUE TITLE
URL Parameters, Restrict Matching?

### ISSUE THREAD

**Issue by rubencodes** [ReactTraining/react-router#4438]
Is there anyway to restrict matching on dynamic routes?

e.g. in the [Ambiguous Matches example](https://reacttraining.com/react-router/examples/ambiguous-matches), if I only wanted to match for known users, could this be done? Or would the `User` component have to handle 404-ing?

**Comment by rubencodes** [comment]
*Update*: I think I found a decent enough way of doing this by using the `render` prop of `Route`, to render a `Redirect` if it doesn't find a match for the url params. If there's a better way I'd love to hear, else I will close 🙂

**Comment by kwelch** [comment]
I do this in a similar way, but I put the logic in the component and use component state/props. This way I can control the view during loading and can redirect or render on completion.
