### ISSUE TITLE
Strict Documentation

### ISSUE THREAD

**Issue by pshrmn** [ReactTraining/react-router#4441]
In `Route.md`, it states

> When true, enforces strict matching of trailing slashes on location.pathname.

Along with the following table

| path | location.pathname | strict | matches? |
| --- | --- | --- | --- |
| /one/two  | /one/two/  | false | yes |
| /one/two  | /one/two/  | true | no |
| /one/two/  | /one/two/  | false | yes |
| /one/two/  | /one/two/  | true | yes |

I don't think that this table is correct. The one non-match only happens when `exact=true`.

From my testing (using the route testing example from #4435), I get the following results:

| path | location.pathname | strict | exact | matches? | regex |
| --- | --- | --- | --- | --- | --- |
|/one/two | /one/two/ | false | false | :heavy_check_mark: | ^\/one\/two(?:\/(?=$))?(?=\/\|$) |
|/one/two | /one/two/ | false | true | :heavy_check_mark: | ^\/one\/two(?:\/(?=$))?$ |
|/one/two | /one/two/ | **true** | false | :heavy_check_mark: | ^\/one\/two(?=\/\|$) |
|/one/two | /one/two/ | **true** | true | :x: | ^\/one\/two$ |
|/one/two | /one/two | false | false | :heavy_check_mark: | |
|/one/two | /one/two | false | true | :heavy_check_mark: | |
|/one/two | /one/two | **true** | false | :heavy_check_mark: | |
|/one/two | /one/two | **true** | true | :heavy_check_mark: | |
|/one/two/ | /one/two/ | false | false | :heavy_check_mark: | ^\/one\/two(?:\/(?=$))?(?=\/\|$) |
|/one/two/ | /one/two/ | false | true | :heavy_check_mark: | ^\/one\/two(?:\/(?=$))?$ |
|/one/two/ | /one/two/ | **true** | false | :heavy_check_mark: | ^\/one\/two\/ |
|/one/two/ | /one/two/ | **true** | true | :heavy_check_mark: | ^\/one\/two\/$ |
|/one/two/ | /one/two | false | false | :heavy_check_mark: | |
|/one/two/ | /one/two | false | true | :heavy_check_mark: | |
|/one/two/ | /one/two | **true** | false | :x: | |
|/one/two/ | /one/two | **true**| true | :x: | |

Essentially, the only time that `strict` mode enforces a trailing slash policy is when it is also in `exact` mode.

**Comment by mjackson** [comment]
Ya, you're probably right. I wasn't thinking about exact + strict when I made that table. Please feel free to update it in a PR.

**Comment by pshrmn** [comment]
I realized that there was a caching error and so my chart might not be completely accurate (see #4448). I'll need to test these again.
