### ISSUE TITLE
Need to remove basename from location for StaticRouter

### ISSUE THREAD

**Issue by justin808** [ReactTraining/react-router#4443]
## Version
    "react-router": "4.0.0-beta.3",

## Test Case
Server Rendering with a nested Route

## Steps to reproduce
Use React on Rails and server rendering as shown in the below file for the app. This SPA with react-router is rendered under Rails routes that start with `/browse`. So that is the "basename". The problem is that the location has to strip the basename.

```js
import React from 'react';
import { renderToString } from 'react-dom/server';
import { StaticRouter } from 'react-router';

import BrowseRoutes from './components/BrowseRoutes';

const basename = '/browse';
const basenameRegexp = new RegExp(`^${basename}`);

const BrowseApp = (props, railsContext) => {
  const { location: loc } = railsContext;
  const context = {};

  let relativeLocation = loc.replace(basenameRegexp, '');
  if (relativeLocation.length === 0) {
    relativeLocation = '/';
  }

  const markup = renderToString(
    <StaticRouter
      location={relativeLocation}
      context={context}
      basename={basename}
    >
      <BrowseRoutes {...props} />
    </StaticRouter>,
  );

  // the result will tell you if it redirected, if so, we ignore
  // the markup and send a proper redirect.
  if (context.url) {
    return { redirectLocation: context.url };
  }
  return { renderedHtml: markup };
};

export default BrowseApp;
```

## Expected Behavior

You should not have to remove the basename from the location every time. In other words, the location should contain the basename.

## Actual Behavior

I have to remove the basename from the location every time.

**Comment by mjackson** [comment]
Fixed (with tests) in 85bb2b1539e8d0be207dd7ecaf6684fd615c85f4

**Comment by mjackson** [comment]
Thanks for the report, @justin808 :)

**Comment by justin808** [comment]
@mjackson Is this in `  '4.0.0-beta.4': '2017-02-02T02:18:16.325Z' },`

Are there tags for releases?
