### ISSUE TITLE
Provide a nicer error when Router is given multiple children

### ISSUE THREAD

**Issue by jackfranklin** [ReactTraining/react-router#4444]
Firstly, can I just say how much I appreciate all your hard work. V1-3 was great, V4 looks absolutely incredible and it's such a joy to work with.

I do have one suggestion that I would love to work on and make the PR, if you agree that it's worth doing. Currently, if you give `<Router>` more than one child, you get the error:

```
Uncaught Error: React.Children.only expected to receive a single React element child.
    at invariant (invariant.js:44)
```

I was wondering if it might be worth catching this case (at least in development) and wrapping it in a nicer error, something along the lines of "`<Router>` can only have one child. You need to ensure all elements are wrapped within one parent element, such as a `<div>`". I expect it might save some developers (especially those new to React) time, as the default error isn't hugely intuitive if you're not a bit familiar with React.

Please feel free to close if you disagree, but thought I'd suggest it. Thanks again! :)

**Comment by mjackson** [comment]
Sure, @jackfranklin. I think it's probably worth providing a better error message here.

This is similar to the concern that @btholt had in https://github.com/ReactTraining/react-router/issues/4131, which we "fixed" with documentation. But probably better to give people a warning too.

I'd be grateful for a PR :)

**Comment by mjackson** [comment]
Let's follow up in #4450
