### ISSUE TITLE
Usage with ReactCSSTransitionGroup renders error Unknown prop `computedMatch`

### ISSUE THREAD

**Issue by weisk** [ReactTraining/react-router#4451]
## Version
4.0.0-beta.4

## Test Case
Can't reproduce in JSBin as ReactCSSTransitionGroup is not provided as a dist/standalone version and JSBin doesn't allow require calls

## Error
![image](https://cloud.githubusercontent.com/assets/2716537/22592627/fb6679c8-ea1a-11e6-87d7-16864c1164b8.png)

**Comment by weisk** [comment]
My mistake, I was using ReactCSSTransitionGroup as first child of <Switch>.

**Comment by pshrmn** [comment]
There should be an animation example using `<Switch>` in the documentation at some point to make it clearer  how to do this.

**Comment by weisk** [comment]
Absolutely! @pshrmn I'm following your thread on this. I'm having the same issue as you, the new route that comes in is the same as the prev one... Let's hope they fix this soon! Thanks for sharing your experience.
