### ISSUE TITLE
Naming collision with react-native

### ISSUE THREAD

**Issue by IljaDaderko** [ReactTraining/react-router#4455]
`react-router-native@4.0.0-beta.4` has some sort of naming collision with `react-native@0.41.1` this is output I get when trying to run ios simulator

```
Failed to build DependencyGraph: @providesModule naming collision:
  Duplicate module name: jsc-heap-capture
  Paths: /Users/ilja/Documents/repositories/projectTest/node_modules/react-native/local-cli/server/middleware/heapCapture/package.json collides with /Users/ilja/Documents/repositories/projectTest/node_modules/react-router-native/node_modules/react-native/local-cli/server/middleware/heapCapture/package.json

This error is caused by a @providesModule declaration with the same name across two different files.
Error: @providesModule naming collision:
  Duplicate module name: jsc-heap-capture
  Paths: /Users/ilja/Documents/repositories/projectTest/node_modules/react-native/local-cli/server/middleware/heapCapture/package.json collides with /Users/ilja/Documents/repositories/projectTest/node_modules/react-router-native/node_modules/react-native/local-cli/server/middleware/heapCapture/package.json

This error is caused by a @providesModule declaration with the same name across two different files.
    at HasteMap._updateHasteMap (/Users/ilja/Documents/repositories/projectTest/node_modules/react-native/packager/react-packager/src/node-haste/DependencyGraph/HasteMap.js:158:13)
    at p.getName.then.name (/Users/ilja/Documents/repositories/projectTest/node_modules/react-native/packager/react-packager/src/node-haste/DependencyGraph/HasteMap.js:133:31)
```

Possible related issue: https://github.com/facebook/react-native/issues/12183 but it seems like this one was fixed, leading me to think that there is an issue with react-native version used in native router, will updating it to 0.41.1 fix the issue?

**Comment by abec** [comment]
@IljaDaderko I hit this same issue last night. The problem was several versions of react-native are being included due to different versions being depended on my your project and react-router-native. My solution was to:
- change the react-native dependency version to >=0.40.0 (as seen here: https://github.com/abec/react-router/commit/12b51624eea8ee997fdfad6734e878546d28e9ed).
- Clone this repository locally and rely on local path dependencies.

I'd love to see what the rest of the react-router community thinks in terms of version compatibility.

**Comment by IljaDaderko** [comment]
Interesting, I wonder if this will be an issue in the future i.e. react native version differences with this library, might not be due to fixes implemented in react native 0.41.1, I really want to see if there is less "hacky" solution to this, otherwise might need to revert back to standard MemoryRouter that doesn't use AsyncStorage, hence doesn't include another version of react-native.

**Comment by ippa** [comment]
Got the same issue, on RN 0.39.2

**Comment by mjackson** [comment]
I think we should probably use a `peerDependency` on `react` and `react-native` in `react-router-native` just like we do [in `react-router`](https://github.com/ReactTraining/react-router/blob/9fdf267fc3a9c8c6bbe5f5acb229d66c3759533b/packages/react-router/package.json#L36-L38) and [in `react-router-dom`](https://github.com/ReactTraining/react-router/blob/9fdf267fc3a9c8c6bbe5f5acb229d66c3759533b/packages/react-router-dom/package.json#L40-L42). We can keep the peer dep fairly loose (i.e. >=0.40) to provide max compatibility with different versions that people are using.

Would that work?

**Comment by abec** [comment]
Yeah it should. +1.

**Comment by mjackson** [comment]
Fixed in 	6561676

**Comment by IljaDaderko** [comment]
@mjackson any eta on when this could be pushed to npm?

**Comment by mjackson** [comment]
I'll ship another beta tonight on the plane to Melbourne ✈️
