### ISSUE TITLE
"exact" prop not recognized in 4.0.0-beta.3 NavLink

### ISSUE THREAD

**Issue by trevordmiller** [ReactTraining/react-router#4456]
## Version
4.0.0-beta.3

## Test Case
http://jsbin.com/robilam/1/edit?html,js,output
_I coudn't figure out how to link to the new react-router-dom v4 beta via umd but it would look like this_

## Steps to reproduce
![image](https://cloud.githubusercontent.com/assets/5497885/22611243/becf7eae-ea26-11e6-98ab-85b7f9230f57.png)
![image](https://cloud.githubusercontent.com/assets/5497885/22611249/c5f6bd00-ea26-11e6-8746-0e2d760e305a.png)

## Expected Behavior
`exact` makes NavLink `activeClassName` only apply when match is exact as listed in prop types: https://github.com/ReactTraining/react-router/blob/v4/packages/react-router-dom/modules/NavLink.js#L40

## Actual Behavior
`exact` is not recognized as a prop
![image](https://cloud.githubusercontent.com/assets/5497885/22611497/221578dc-ea28-11e6-813c-652d969f5096.png)

**Comment by pshrmn** [comment]
`exact` wasn't added until beta 4. It works in this fork of your code:

http://codepen.io/pshrmn/pen/jyxdxa
