### ISSUE TITLE
History api is spread in props when using render function of `Route`

### ISSUE THREAD

**Issue by shendepu** [ReactTraining/react-router#4469]
## Version
4.0.0-beta.4

When use `Route` with render function, the props it passes down is spread with history api, why not wrap them in a `router` object so that it won't pollute component props? 

```

    <Route {...rest} path={nestedPath} render={(props) => {
      console.log(props)
      return (
        <Component {...props} parentPath={parentPath} routes={routes} />
      )
    }} />
```
logged props:
![image](https://cloud.githubusercontent.com/assets/4743845/22625836/285b636a-ebda-11e6-9f87-a65b37603804.png)

**Comment by porfirioribeiro** [comment]
This was already disused here: #4424 
It was decided that it was better this way, still i agree with you
