### ISSUE TITLE
RRN <Link to> support for location object

### ISSUE THREAD

**Issue by CodogoFreddie** [ReactTraining/react-router#4476]
Version: 4.0.0-beta.4

Native links function fine using object style `to` props, could the `propTypes` be changed to reflect this, if this is allowable behaviour?

I'll make a PR if you're accepting them

**Comment by mjackson** [comment]
Yes, @CodogoFreddie, RRN's `<Link to>` should support location objects. If you'd like to add support, be my guest :)

**Comment by CodogoFreddie** [comment]
https://github.com/ReactTraining/react-router/pull/4483
