### ISSUE TITLE
v4-beta About location handle

### ISSUE THREAD

**Issue by zombieJ** [ReactTraining/react-router#4479]
Ref: https://github.com/ReactTraining/react-router/issues/4410

For server side render: https://github.com/ReactTraining/react-router/blob/v4/packages/react-router/modules/StaticRouter.js#L115

history always be replaced by inner history. So I guess it may provide some props with each Router to make it easier for location query self handle.

in addition, how do I handle `Redirect.to`, `Link.to` && `router.push` when I want to use query instead of connecting the search string?

**Comment by pshrmn** [comment]
You should be stringifying your query object in whatever component is rendering your `<Redirect>`/`<Link>`.

```js
import { stringify } from 'qs'

const MyComponent = () => (
  <div>
    <Link to={{ pathname: '/some-place', search: '?' + stringify({ a: 'b', c: true }) }}>Go Here</Link>
  </div>
)
```
