### ISSUE TITLE
Waring when using dynamic route with ssr

### ISSUE THREAD

**Issue by JounQin** [ReactTraining/react-router#4482]
```
Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client) <!-- react-empty: 1 -
 (server) <div data-reactroot="
```

reproduce: https://github.com/JounQin/react-ssr/tree/react-router

Step:

1. I'm using *npm.taobao.org* in china, so maybe you should delete the *yarn.lock* first
2. `yarn && yarn dev`

Then open `localhost:3000`, it will show the waring messages on console.

**Comment by JounQin** [comment]
Sorry, noticed [this link](https://github.com/ReactTraining/react-router/blob/master/docs/guides/ServerRendering.md#async-routes) just now.

**Comment by tiemei** [comment]
any solution? I use BrowserRouter in client.js, and use StaticRouter in server.js. not work.

**Comment by JounQin** [comment]
@tiemei Sorry but I'm using react-router v3.0 which support dynamic route with ssr better, and v4.0 seems to drop support of dynamic router inside.

https://github.com/JounQin/react-ssr/tree/master/src

Here is the example of v3.0 in *entry-client.js* and *entry-server.js*.
