### ISSUE TITLE
Any plans to update History dependency to 4.5.0 (latest)

### ISSUE THREAD

**Issue by L3V147H4N** [ReactTraining/react-router#4485]
I noticed that react-router is still using history ^3.0.0
this creates a problem in conjunction with Typescript and typings because the @types are ahead to the latests version of history and we had to resort to weird workarounds to stop getting compilation errors

**Comment by pshrmn** [comment]
`history` v4 is designed to work with `react-router` v4 and is incompatible with `react-router` v3.

**Comment by L3V147H4N** [comment]
👍
