### ISSUE TITLE
v4 README refers to missing (or non-public) repo react-router-addons-controlled? 

### ISSUE THREAD

**Issue by jeffbski** [ReactTraining/react-router#4486]
Missing (or non-public) repo react-router-addons-controlled?

Where is `ControlledRouter` component (and the react-router-addons-controlled) that is mentioned in the v4 README [here](https://github.com/ReactTraining/react-router/tree/v4#what-about-redux)?

The README links to to https://github.com/ReactTraining/react-router-addons-controlled which is a 404 (maybe it is a private repo that should be made public?)

Thanks!

## Version
4.0.0-beta.5

**Comment by teonik** [comment]
I dont think a ControlledRouter is needed anymore with the latest beta (v4-beta5).
React-router now exposes a generic [Router](https://reacttraining.com/react-router/#router) that accepts a user supplied history so you use can that to listen to navigation events.

Some input from the devs would be nice to clarify this issue...

**Comment by pshrmn** [comment]
I think that that little blurb can probably be removed from the README.

I am unsure exactly what `<ControlledRouter>` was intended to be, but if you are looking for a router which you provide a `history` instance to, @teonik is correct that the `<Router>` component will do the trick.

Just to be clear: you can use any of the other routers with Redux. I am assuming that the use case with this is for people who want to store locations in the store (a la `react-router-redux`). I know that there are reasons to do this, but generally speaking, you do not need to store locations in the redux store.

**Comment by atoiv** [comment]
Another use case where you need access to history would be, when you want to change route from outside a react component, e.g. from inside a redux-saga.

So there's definitely other use cases as well, for needing access to history, other than just storing route information to redux store.

**Comment by pshrmn** [comment]
@atoiv Yes. I was unclear with my wording, but I was speculating about the `<ControlledRouter>` being some way to automatically sync a history with redux. For just navigating outside of components, `<Router history={history}>` is definitely the way to go.

**Comment by jeffbski** [comment]
So if I understand, basically instead of using BrowserRouter I would simply create my own history and use Router instead so that I can listen to it and pass it where I need it. That seems fine for the case of BrowserRouter since it doesn't do much, though I hope that in the future it wouldn't grow in functionality and thus I'd be mirroring all of that in my custom code (everything that BrowserRouter does I'd be mirroring in my own code with the minor difference of using my own history). 

Another idea is to have BrowserRouter allow us to pass in an optional createHistory function? That way I could provide one that gives me access to the history object and I could continue to use BrowserRouter rather than going custom.

How would things work with NativeRouter? So the same use case, we need to be able to listen to history changes and dispatch them and one might need to use the history to navigate.

**Comment by jeffbski** [comment]
@pshrmn to clarify my intended use case, I want to have route changes dispatch a redux action that I can listen to and perform my fetching. I will listen for that action with redux-logic and fetch the data needed for that route. The fetching is cancellable and it works great with server-side rendering. This also allows one stay more functional using primarily stateless function components which is a huge win in my book.

**Comment by pshrmn** [comment]
`<BrowserRouter>` (and all of the other `___Router`s) are just thin wrappers around the `<Router>` component.  All that `<BrowserRouter>` does is create a `history` instance when it is constructed and then it passes that to the `<Router>` component in its `render` method ([source](https://github.com/ReactTraining/react-router/blob/v4/packages/react-router-dom/modules/BrowserRouter.js#L17)).

The only difference between that and creating your own `history` object is that with the latter you will be able to import the `history` object throughout your project.

For your use case, the only complexity should be in creating your `history` object that wraps a "real" [`history`](https://github.com/mjackson/history). On React Router's end, it really only cares that it has `push`, `replace`, and `listen` methods (I'm probably missing a couple others, but those are the big three that you might find yourself wrapping. The rest can probably just be direct references to the internal `history` instance.)

**Comment by jeffbski** [comment]
Yes, I agree that as the BrowserRouter is implemented today, it is trivial to skip using it and just create my own history and pass to Router. 

However one concern is that IF BrowserRouter ever grows in capabilities then I will be possibly needing to duplicate all of that work in my own custom code using Router.

NativeRouter [(source)](https://github.com/ReactTraining/react-router/blob/v4/packages/react-router-native/NativeRouter.js) isn't nearly as trivial though, so I don't see a good approach. I don't think we should be bypassing its code and doing all that manually since it takes into account storing in ios and android etc. So I'm not sure how is the best way to get access to the history when creating a NativeRouter.

**Comment by timdorr** [comment]
Removed that section (for now!).

I've been toying around with some new stuff for react-router-redux, but will probably land on the same sort of solution we did for 2.x and 3.x: Just sync the history with redux and let the router do its own thing. I potentially want to do a `<ControlledRouter>` to give access to `params`, but that would be the only real need for it.

**Comment by jeffbski** [comment]
@timdorr Will this react-router-redux solution work with the NativeRouter?

**Comment by timdorr** [comment]
No idea. I haven't written it yet 😄

**Comment by jeffbski** [comment]
Fair enough, but I think I will raise the question as a separate issue so it isn't lost. I can't envision a solution for getting external access to history when using the NativeRouter given the current RRv4 API.

**Comment by timdorr** [comment]
No, please don't open up another issue on this. It isn't within scope for this library to solve. And it's known on `react-router-redux`, so it would be a duplicate of issues I've been closing about it. For now, that library only targets the production versions of 3.x and 2.x.

**Comment by jeffbski** [comment]
I respectfully disagree that it isn't in the scope of this library to solve. Your react-router-redux project assumes a redux solution which is fine, but what if someone wanted to use something else besides redux?

**This library should provide a way to either access history or provide a way to hook into the creation of history so that other solutions like react-router-redux can use it. This should be true for both the browser and native approaches.** It should not be a black box that other things cannot build on. Working around BrowserRouter is fine since it is trivial, but NativeRouter is more complex.

If and when react-router-redux supports NativeRouter I can't envision how you would get access to the history, so that is the issue that should be discussed regarding the RRv4 API.

**Comment by timdorr** [comment]
I'm only saying it's outside of scope to provide bindings to Redux.

**Comment by jeffbski** [comment]
Yes, I agree. We can leave the binding of react-router and redux to react-router-redux.

**Comment by cescoferraro** [comment]
@teonik is this what you mean?

https://gist.github.com/dolfelt/304e4a99b6f413d609994732a33b5906

**Comment by teonik** [comment]
Yeap, although RRv4's api has changed since the gist was published, that is the general idea.
I haven't actually implemented it since i don't need the functionality yet but it looks like a good start.
