### ISSUE TITLE
Broken relative path in v3 // More docs/examples for relative paths in v4

### ISSUE THREAD

**Issue by jzaefferer** [ReactTraining/react-router#4488]
Through #2172 I ended up on https://reacttraining.com/react-router/examples/recursive-paths

I have two issues with that page: It doesn't explain anything (there's only the example), and it doesn't provide a solution for the kind of relative paths I'm looking for.

I'm currently using the latest stable release (3.0.2) and trying to link to routes using relative paths like this:
```
<Link to={`../configure/${product.key}`}>
```
The generated href is correct, but when clicking this link, the route doesn't match, and I end up on our 404 page. Whats really weird: Using the browsers back and forward button, I can go back to the same URL, and now the correct route matches.

Now I understand that v3 isn't being developed, and I have to migrate to v4 beta to get this working. Since v4 looks completely different, and the canonical example for relative paths doesn't use the type I need, I'm pretty lost.

If bugs are being fixed in v3, I can try to put together a reduced test case. Otherwise some pointers for v4 would be great. Are there official docs for migrating from v3? [this](https://gist.github.com/kennetpostigo/7eb7f30162253f995cd4371d85c1e196) and [this](http://rants.broonix.ca/upgrading-to-react-router-v4/) looks useful, but I can't tell if they're still correct/relevant.

**Comment by pshrmn** [comment]
v3 does not support relative URLs for navigation.

In v4, there is work being done to support relative paths, but it is not yet included. When it is, it will include supporting double dot notation paths.

There should be an official upgrade guide closer to the full release.
