### ISSUE TITLE
Auth protected routes Example in V4 Documentation

### ISSUE THREAD

**Issue by oliverasistemas** [ReactTraining/react-router#4489]
I've noticed that the auth example is gone in the V4 documentation, is there any intention to come up with an example/preferred way of dealing with auth protected routes.

## Version
2.0.0

## Test Case
http://jsbin.com/sacerobuxi/edit?html,js,output

**Comment by pshrmn** [comment]
This should do the trick

https://reacttraining.com/react-router/examples/auth-workflow

**Comment by hubgit** [comment]
The example is now at https://reacttraining.com/react-router/web/example/auth-workflow

**Comment by mnemanja** [comment]
I've mocked an authentication that uses Session and Local storages and handles authentication in a stateful component for Redux updates. The example also utilizes Switch component.

```
    return (
      <Aux>
        <Switch>
          <Route exact={true} path="/" component={Home}/>
          <Route path="/products" component={Products}/>

          <Route path="/register" component={Register}/>
          <Route path="/login" component={Login}/>
          <Route component={NoMatch}/>
        </Switch>

        {!sessionStorage.getItem('authenticated') && this.props.location.pathname !== '/login' && this.props.location.pathname !== '/register'
          ? <Redirect to={{
              pathname: '/login',
              state: {from: this.props.location}
            }} />
          : ''
        }
      </Aux>
    )
```
