### ISSUE TITLE
Clarify how <Switch> works in docs

### ISSUE THREAD

**Issue by pshrmn** [ReactTraining/react-router#4490]
I have been seeing a decent bit of confusion about how the `<Switch>` component works. I think that this is a mixture of the docs not being explicit about how `<Switch>` matches routes and people not having a complete understanding of the `children` prop (it's a _thing_ of elements?!)

There are two problems that seem to be common:

1. Wrapping a `<Route>` and not including all of the props to the route wrapper that will be necessary for it to match.
2. Placing non-`<Route>` components in the `<Switch>`, for example to nest layouts.

Generally I explain that the `<Route>` components will actually be React elements and should be thought of as a configuration array.

```js
<Switch>
  <Route exact path='/' component={Home} />
  <Route path='/faq' component={FAQ} />
  <Route component={NoMatch} />
</Switch>
// can be thought of as
<Switch routes={[
  { path: '/', exact: true, component: Home },
  { path: '/faq', component; FAQ },
  { component: NoMatch }
]} />
```

(A `routes` array is simpler than saying `React.Children.toArray(props.children)` and then specifying that you have to access the `props` property of each element.)

I'm not really sure what the best approach to explaining this is in the docs is, but I imagine until (and even after :roll_eyes:) this gets clarified, there will continue to confusion about it.

**Comment by mjackson** [comment]
I don't think we need to explain *how* a switch works (the implementation) beyond just saying "it works like a switch statement" or "it renders the first route that matches the URL". If people want to dig deeper and look through the source they're welcome to see how it does what it does.

**Comment by pshrmn** [comment]
Perhaps the "how" is asking too much, but I think that maybe the description of the `children` prop could be improved. It is described as

> The first \<Route\> in children to match the current location will be rendered.

I think that something along the lines of the following would be clearer.

>One or more \<Route\> elements (or elements with the same prop types as a \<Route\>). Only the first one to match the current location will be rendered.

Also, I wish that there was an equivalent of `PropTypes.shape` for elements. `node` is just so generic.

**Comment by mjackson** [comment]
We don't need to support elements with the same props as Route. I know it'll work, but it just complicates things. But ya, the description could be improved to something like what you suggest.

**Comment by pshrmn** [comment]
Alright, I'll close this and if I think of some wording that I prefer, I'll open a PR.

Not officially supporting non-`<Route>` route components makes sense, although I wonder if their usage should be discouraged then. For example, there is a `<PrivateRoute>` in the auth example that wraps `<Route>` to handle redirecting. That could easily be rewritten to use a regular `<Route>` and have the "private" component handle redirecting.

```js
const private = Component => props =>
  auth.loggedIn() ? (
    <Component {...props} />
  ) : (
    <Redirect to={{
        pathname: '/login',
        state: { from: props.location }
    }}/>
  )

<Route path='/protected' component={private(Protected)} /> 
```

**Comment by kvanderkamp** [comment]
@pshrmn `private` is a reserved word in strict mode, so it's better to give the "private" component a different name. (Not `protected` because that is also reserved)

**Comment by dan-turner** [comment]
@pshrmn thanks for that! I've been trying to work out how to do this properly for ages...

Could you please provide a similar example showing the proper way to then handle the redirect back to their requested page after successfully logging in?
