### ISSUE TITLE
withRouter polluting props

### ISSUE THREAD

**Issue by samparmenter** [ReactTraining/react-router#4497]
I don't know if this is just the current implementation and if it will change but when you wrap a component with the HoC `withRouter` the history object pollutes the component props. Is there a reason why this doesn't just add `history` to the components props?

Am I using this incorrectly or is this intended behaviour?

Its just not super obvious when you see things like `this.props.listen` or `this.props.push` what that is referring to.

**Comment by smashercosmo** [comment]
This has been discussed a lot
https://github.com/ReactTraining/react-router/issues/4469
https://github.com/ReactTraining/react-router/issues/4424

**Comment by samparmenter** [comment]
Cheers, hadn't seen those, is there a way to search for these related issues?
