### ISSUE TITLE
NativeRouter needs documention

### ISSUE THREAD

**Issue by BerndWessels** [ReactTraining/react-router#4502]
Hi
The NativeRouter needs better documentation.
Especially what is the intention and how can it be used in common mobile scenarios like
```
- Drawer
  - Stack
  - Stack
  - Tab
    - Stack
    - Stack
    - Stack
- Modal
- Modal
```
How does it support the transitions, pushes and pops, headers, ...

I'd like to contribute to this but can't quite figure out where to start with the NativeRouter.

**Comment by mtford90** [comment]
I was able to get things working following the example in the repo @ https://github.com/ReactTraining/react-router/blob/v4/packages/react-router-native/index.ios.js but as @BerndWessels mentions above I can't find any examples or anything in the code base that suggests the support of transitions e.g. the kind of behaviour obtained via `Navigator.SceneConfigs`

**Comment by meno1** [comment]
I'm new to react native and am really lost.  I began w/ react-router-native (v4) and can't figure out how to add behavior to swipe to go back.  I'd need scroll position to be preserved as well.

react-router 4 was super easy to get started with.  I just can't figure out how to do more with it.

**Comment by meno1** [comment]
I don't know how ready it is, but I found a project that combines react-router v4 with NavigationExperimental:  https://github.com/LeoLeBras/react-router-navigation

**Comment by ryanflorence** [comment]
Docs aren't done, working on it this week.

**Comment by ryanflorence** [comment]
will have better native docs with final release, already wrote some decent ones today.
