### ISSUE TITLE
Where did the location/locationShape PropType go in v4?

### ISSUE THREAD

**Issue by mark0978** [ReactTraining/react-router#4506]
This was present as recently as `alpha-6`, but in the current beta-5 appears to be gone.
```
node_modules/react-router/PropTypes.js:23:var location = exports.location = _react.PropTypes.shape({
```

I find evidence that maybe it should be there in: 
```
./modules/index.js:16:export { locationShape, routerShape } from './PropTypes'
./modules/PropTypes.js:15:export const locationShape = shape({
```

But it doesn't show up in the installed product.

I'd be happy to work on a PR to fix it unless this is by design.

**Comment by pshrmn** [comment]
This was intentional. See #4419.

**Comment by Wobbly-Wibbly** [comment]
@mark0978  Hello, I'm using strict eslint rules for prop-types, so we had to define all the shapes.
I have created a package just for props, so those shapes are not duplicated all over the projects.
Thought maybe it would be helpful for you also.
https://www.npmjs.com/package/react-router-props
