### ISSUE TITLE
IE9: SCRIPT5: Access is denied with browserHistory.

### ISSUE THREAD

**Issue by cly** [ReactTraining/react-router#4507]
## Version
2.7.0
react-router-redux@4.0.7

## Test Case
In IE9 console shows `SCRIPT5: Access is denied.`.

## Steps to reproduce
```
    const reactRouterMiddleware = routerMiddleware(browserHistory);
    const store = createStore(
        getRootReducer(),
        initialState,
        composeWithDevTools(
            applyMiddleware(thunk, reactRouterMiddleware)
        )
    );

    const history = syncHistoryWithStore(browserHistory, store);

    match({ history: browserHistory, routes }, (err, redirectLocation, renderProps) => {
        const mount = document.getElementById('foo');

        ReactDOM.render(
            <Provider store={store}>
                  <Router {...renderProps} history={history} />
            </Provider>,
            mount
        );
    });
```

## Expected Behavior
Not throw error but do full refreshes per route accessed. https://github.com/ReactTraining/react-router/blob/master/docs/guides/Histories.md#ie8-ie9-support

## Actual Behavior
Throws error but it appears the react code still runs etc.

**Comment by timdorr** [comment]
That is something to do with iframes and cross-domain stuff. We don't have control over that.
