### ISSUE TITLE
Parameter requirements

### ISSUE THREAD

**Issue by egig** [ReactTraining/react-router#4508]
Do react router supports parameter requirements ?. e.g:

`<Route path="/:locale" requirements={{
    locale: "en|fr"
  }} />`

will match only `/en` and `/fr`.

the case is I need todo the following:

`<Route path="/:locale/some-path" } />`
`<Route path="/:city/some-path" } />`

`locale` and `city` have limited values, but its dynamic and too many to be defined as route. but I want to arbitrary path like `foo/some-path` to be not allowed.

There will no route ever be matched to `/:city/some-path` if there is no requirements because it placed after `/:locale/some-path`.

**Comment by timdorr** [comment]
We support whatever [`path-to-regexp`](https://github.com/pillarjs/path-to-regexp) supports. You can do this with a matching regex: https://github.com/pillarjs/path-to-regexp#custom-match-parameters

**Comment by egig** [comment]
hi @timdorr is it supported on version 3 ?

**Comment by timdorr** [comment]
No, but you can validate the parameters in your route component's componentWillMount or an onEnter hook and redirect if needed.
