### ISSUE TITLE
Page reloads on first 'Link' click with SSR

### ISSUE THREAD

**Issue by nicksrandall** [ReactTraining/react-router#4512]
## Version
4.0.0

## Test Case
Hard to produce Test Case because deals with SSR.

## Steps to reproduce
I'm using `StaticRouter` to render on the server and `BrowserRouter` on the client and everything seems to be working great other than the fact that the first time that I click on a Link, my page is doing a full reload. After that first reload, everything works as expected and any subsequent link clicks do not cause a full page reload. It appears that when the server renders an `a` tag (from a Link component), the browser is treating it as a normal a tag and not a special one that doesn't cause a refresh.

## Expected Behavior
I would expect no page refresh.

## Actual Behavior
A page refresh on first click.

**Comment by nicksrandall** [comment]
Related: https://github.com/RickWong/react-isomorphic-starterkit/issues/115

**Comment by timdorr** [comment]
This sounds like something outside of the library. Do other React components behave as expected? It sounds like React isn't plugging into the HTML-provided DOM on boot. 

Any console errors? 

You can provide a test case by simply sharing your repo where you're working on this.

**Comment by nicksrandall** [comment]
All react components behave as expected and there is no errors in the console (even in dev mode). I am unable to share my repo because it is private but the related issue says it has a reproducible example.

**Comment by nicksrandall** [comment]
I will continue to investigate and see if I can come up with a small repo to show issue.

**Comment by nicksrandall** [comment]
@timdorr you suspicions were correct. It was an issue with how I was using async scripts and react wasn't being loaded as fast as I needed it to. Closing.

**Comment by anton-aleksandrov** [comment]
@nicksrandall have you solved [the issue with react-isomorphic-starterkit](https://github.com/RickWong/react-isomorphic-starterkit/issues/115) ? If so, could you, please, describe your solution?
