### ISSUE TITLE
Can't resolve 'history/createBrowserHistory' [v4]

### ISSUE THREAD

**Issue by ApolloTang** [ReactTraining/react-router#4518]
## Version
4.0.0-beta.5

## Steps to reproduce
goto: 
https://github.com/ApolloTang/react-router-v4-lab
follow instruction in README.md

router's code is in:
https://github.com/ApolloTang/react-router-v4-lab/blob/master/lab02-router-v4/src/modules/root/index.js

## Expected Behavior
I have tested out the same router's code in forked repo (link below), it works:

https://github.com/ApolloTang/react-router/blob/apollo-lab/packages/react-router-website/modules/examples/Fundamental.js

(checkout branch apollo-lab, cd to 'packages/react-router-website', npm install, npm start)

## Actual Behavior
Something is wrong with npm package, history is not resolve properly.

```
ERROR in ./~/react-router-dom/es/BrowserRouter.js
Module not found: Error: Can't resolve 'history/createBrowserHistory' in '/Users/apollotang/Desktop/g-react/react-router-v4-lab/lab02-router-v4/node_modules/react-router-dom/es'
 @ ./~/react-router-dom/es/BrowserRouter.js 8:0-57
 @ ./~/react-router-dom/es/index.js
 @ ./src/modules/root/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://0.0.0.0:9090 ./main.js

ERROR in ./~/react-router-dom/es/HashRouter.js
Module not found: Error: Can't resolve 'history/createHashHistory' in '/Users/apollotang/Desktop/g-react/react-router-v4-lab/lab02-router-v4/node_modules/react-router-dom/es'
 @ ./~/react-router-dom/es/HashRouter.js 8:0-54
 @ ./~/react-router-dom/es/index.js
 @ ./src/modules/root/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://0.0.0.0:9090 ./main.js
```

**Comment by pshrmn** [comment]
You are including `"react-router": "^3.0.2"` in your dependencies. This installs v3 of `history`, which is causing your error. Remove that from your dependencies and re-install `react-router-dom@next`. That will install `history` v4 and your code will work.

**Comment by ApolloTang** [comment]
works now, v3 and v4 can not exist side by side !
Thanks

**Comment by AbhishekCode** [comment]
I just had somewhat similar issue, Initially I thought I need to install history package so did that using yarn. its install latest version, which isn't compatible with current version of react router. 
I found this thread, and realized i don't need add history package in my package.json, react router will install appropriate version. 
So removed that but still same error, found out if yarn caches package so it kept installing latest version of history(tried deleting whole node_modules also), so i ran npm install and whoa it worked.

**Comment by nikkwong** [comment]
Seems to be broken again in ```^4.3.0-rc.3```, I had to downgrade to 4.0.0
