### ISSUE TITLE
Update react-router docs to exclude Location.query examples

### ISSUE THREAD

**Issue by Dante-101** [ReactTraining/react-router#4520]
[`history` docs](https://github.com/ReactTraining/history/blob/v3.x/docs/Location.md) don't mention [`Location.query`](https://github.com/ReactTraining/history/blob/v3.x/docs/Location.md). The documentation expects users to use [useQueries](https://github.com/ReactTraining/history/blob/v3.x/docs/QuerySupport.md). 

This is not in sync with what [react-router mentions.](https://github.com/ReactTraining/react-router/blob/master/docs/API.md#link). I believe the code should be updated for `useQueries`?

It affects all the TypeScript users. The current TypeScript definitions for `history` don't support `Location.query` which makes it impossible to compile the project with the code as it is from the documentation. Till few days ago, `react-router` definitions were using the old definitions of `history` (v2.x, current is v4.x) which made it possible to run.

**Comment by Dante-101** [comment]
Never mind. I did more research and figured that it is solely a TypeScript definition issue.

**Comment by LiBo-Bobb** [comment]
I accept it.
