### ISSUE TITLE
v4 Unsure about differences between 'render=' and 'component=' attributes for 'Routes'

### ISSUE THREAD

**Issue by achung89** [ReactTraining/react-router#4526]
Unsure about the differences between the attributes 'render=' and 'component='. Documentation states that 'render' accepts a function with a parameter 'props', which to me sounds like a component. 'render' function also needs rendered elements to be returned, just like a component would.

Used both attributes interchangeably, and both worked for my components and functions.  

## Version
4.0.0-beta.5

**Comment by mjackson** [comment]
I added some more detail that hopefully makes the distinction clearer. When you use `component` we actually create a new React element for you. When you use `render`, we don't. So your component tree is different depending on which one you use.

**Comment by benhannel** [comment]
I'm still a bit confused. When you use render, is the component unmounted and remounted still when you navigate away and back? Is its state preserved?

**Comment by ArpiJakab** [comment]
If you declare a component inside of render(), react will unmount the component when the path is changed, same behavior as with setting the component attribute.

I'm using render to set the display state of components and this does not cause unmounting. This may be complete misuse of this API, however it achieves my desired effect.

<div key='tests'>
	<div style={{display: test === 'test1' ? 'block' : 'none'}}>
		<Test key='test1' name='test1'/>
	</div>
	<div style={{display: test === 'test2' ? 'block' : 'none'}}>
		<Test key='test2' name='test2' />
	</div>
</div>
<Route
	exact path='/test1'
	render={(routeProps) => {
		console.log('test1 called');
		if (test !== 'test1') {
			this.setState({test: 'test1'})
		}
		return <div />;
	}
}/>
<Route
	exact path='/test2'
	render={(routeProps) => {
		console.log('test2 called');
		if (test !== 'test2') {
			this.setState({test: 'test2'})
		}
		return <div />;
	}
}/>

**Comment by franklixuefei** [comment]
@mjackson Probably this is just a React related question... but since this problem was brought up, I would like to understand it thoroughly. From the source code, if we choose to use `component=`, then we end up calling `React.CreateElement(component, props)`. However, I don't understand why using `component=` will trigger an unmount and mount? Wouldn't React compare the tree and only update what's necessary? If I use `render=`, React does the right thing and updates only what's necessary.

**Comment by binarybaba** [comment]
I think `component={}` unmounts and remounts the component whereas render doesn't remount the component. I tried making dummy ajax calls in the componentDidMount lifecycle method and the ajax requests were called when using component but was NOT called when using render. I guess it's safe to say that render doesn't unmount and remount the component.
