### ISSUE TITLE
Where exactly is the doc for react-router 4.0.0-alpha.6

### ISSUE THREAD

**Issue by CyrilWork** [ReactTraining/react-router#4530]
I didn't find it. The link https://react-router.now.sh/Match that I was using before returns Not found

**Comment by mjackson** [comment]
The docs are at reacttraining.com/react-router/

**Comment by CyrilWork** [comment]
sorry but in my code I use `import { Redirect, Match, Miss } from 'react-router';` with react router 4.0.0-alpha.6 The docs you gave me does not document the `<Match>` . Should I switch to version 3.0.2  ?

**Comment by pshrmn** [comment]
1. `<Match exactly pattern='/some-place'>` -> `<Route exact pattern='/some-place'>`
2. `<Miss>` no longer exists, use a `<Switch>`
3. Use `react-router-dom` (`npm install --save react-router-dom@next`) for browser based sites.

**Comment by CyrilWork** [comment]
Does this mean yes ?

**Comment by pshrmn** [comment]
That is how to upgrade from the alpha to the beta. The changes are very simple, just rename a few components/props.

**Comment by mjackson** [comment]
@CyrilWork It sounds like you're looking for a stable release. For that, yes, I'd recommend you use version 3.0.2 which is on the master branch.

**Comment by CyrilWork** [comment]
Thanks a lot
