### ISSUE TITLE
Support for serialized/deserialized query arguments (v4)

### ISSUE THREAD

**Issue by mayani** [ReactTraining/react-router#4532]
**Serializing/Deserializing Query Strings**

Currently, `Link` can be assigned query args only as strings using `search` param. It would be better to extend it to accept objects, which are serialized by the router.

For active Routes, the query args. are only accessible as strings. It would be better to make them accessible as object.

The above was supported in old version at [Query Param Example](https://github.com/ReactTraining/react-router/blob/master/examples/query-params/app.js).

**Use Case**

While using Google Analytics (GA) or any analytics engine, we do not want to record personally identifiable info. in GA, like /user/<username-or-email>. 
GA provides a way to pre-process URLs using regex, before being recorded. However, if only path params are used, configuring the filter regex becomes tedious, but it is much easier to simply filter out query args. In such cases one would prefer to use query args instead of path args to design there routes.

**Examples**

```js
<Link to={{
    pathname: "/user",
    search: {
        "username": "user@domain.com"
    },
}}>Test</link>
```

```js
const User = ({ match }) => {
  return <h1>Hello {match.query.username}!</h1>
}
```

**Comment by timdorr** [comment]
See #4410
