### ISSUE TITLE
Easily allow Route to match child routes

### ISSUE THREAD

**Issue by wmertens** [ReactTraining/react-router#4534]
## Version
4.0.0

## Feature request
If I understand correctly, if you have a component that introduces sub-routes, but doesn't know where it is mounted, you should use something like this:

```js
const {match} = this.props
return <Route path={`${match.path}/subRoute`} .../>
```

Apart from being more typing and harder to read, it also means that you have to make sure to only do this in direct Route children, or else you also need to wrap in `withRouter`.

## Proposal
Instead, how about an extra prop `relative`?

```js
return <Route path="subRoute" relative/>
```

or even make this automatic if the path is missing a `/` at the beginning and there is no `absolute` prop (for when you want to match anywhere in the URL).

**Comment by porfirioribeiro** [comment]
Good idea, maybe
`return <Route path="./subRoute" />`

**Comment by wmertens** [comment]
Perfect, unambiguous and matches the current API!

**Comment by wmertens** [comment]
I took a quick look at implementing it and I realized that `match.path` is the regex that matched, and not the part of the url that already matched.

So `matchPath(pathname, path, options)` would need to export that information too, and `Route` and `Switch` would need to pass the previous `match` in `options`.

**Comment by timdorr** [comment]
Proper support is coming via #4459, which lays the groundwork for both relative/nested `<Route>`'s and `<Link>`'s.
