### ISSUE TITLE
render twice after click Link component(only hashHistory)

### ISSUE THREAD

**Issue by Sylvenas** [ReactTraining/react-router#4537]
When i run the react-router animations example, i change two places,

the first one is modify the _browserHistory_ into _hashHistory_,

the second is to add the `console.log('Page1');  ` at **Page1** component,  

and than i click the A tag(link to Page1 component), i see 'Page1' was printed two times.

![1](https://cloud.githubusercontent.com/assets/10754058/23022932/4b5b58fe-f48e-11e6-80b7-57f5731e1efb.png)
![2](https://cloud.githubusercontent.com/assets/10754058/23023171/32853484-f48f-11e6-8c96-81a3e1a84679.png)

**Comment by mjackson** [comment]
It seems there's a bug in v3 with hash history calling listeners twice in certain situations. There is already [a bug filed here](https://github.com/ReactTraining/history/issues/427) that you can follow. FWIW, we haven't had any reports of this bug in history v4.

**Comment by iyobo** [comment]
This should be fairly straight-forward to resolve though right?

```
hashHistory.listen( ( evt ) = > {
	console.log('LISTENER:', evt)
});
```

This event handler gets called twice per route visit. But evt is different each time:

```
//log upon visiting /models/Testy

LISTENER: {"pathname":"/models/Testy","search":"","hash":"","action":"PUSH","key":"1myy9b","query":{}}

LISTENER: 
{"pathname":"/models/Testy","search":"","hash":"","action":"POP","key":null,"query":{}}
```

I wouldn't call this a 'bug' per say. It just means, when visiting a route, react-router should focus on routes with:
* evt.action=== 'PUSH' && evt.key

Would there be any other consideration?
