### ISSUE TITLE
With Preact, <Route>s in a <Switch> are rendered even when not matched

### ISSUE THREAD

**Issue by zaygraveyard** [ReactTraining/react-router#4538]
## Version
4.0.0-beta-6

## Test Case
http://jsbin.com/ximalatava/1/edit?console,output

Loads Preact and Preact-compat

## Steps to reproduce
1. Click on the "/view" link
2. Click on the "/" link
3. Click on the "/view" link

## Expected Behavior
The console contains:
```
"/view"
"/"
"/view"
```

## Actual Behavior
The console contains:
```
"/view"
"/view"
"/"
"/"
"/view"
```

**Comment by timdorr** [comment]
We're not targeting support for Preact with this library. This is something for preact-compat to solve. If there's a behavior difference, it should patch over it somehow. I would open up an issue on their repo. 

Thank you for the usable test case, btw!

**Comment by zaygraveyard** [comment]
Thank you for the fast reply.

I understand that you're not targeting support for Preact.
But in this particular case, while the symptoms of the problem are only visible with Preact, problem is present in both React and Preact.

The problem, AFAICS, is that in the history listener of the Route uses `computedMatch` ([here](https://github.com/ReactTraining/react-router/blob/v4/packages/react-router/modules/Route.js#L51)) while it's no longer valid (it was passed as a prop from the Switch for the previous `location`).

Possible solutions:
1. _The easy solution_: Replace the call to `computeMatch()` in the [Route's listener](https://github.com/ReactTraining/react-router/blob/v4/packages/react-router/modules/Route.js#L51) with a direct call to `matchPath()` (ignoring the `computedMatch`)
2. _The clean solution_: Remove the internal `computedMatch` prop completely, so that `matchPath()` is always used. And if needed memoize `matchPath()`.

BTW, thank you for the fantastic library especially v4, I found the older versions too complex and thus chose not to use them. But it's not the case for v4, v4 is very simple and very "Reacty". :+1:

**Comment by zaygraveyard** [comment]
I can submit a PR if needed :smile:
