### ISSUE TITLE
react-router-native needs a better way to be controlled

### ISSUE THREAD

**Issue by linonetwo** [ReactTraining/react-router#4540]
V4 react-router-native alpha 6

I used to use addon-controlled-route  ( whos github repo is now disappeared ) and memoryRouter. At that time I can pass in a ```history/createMemoryHistory``` instance. 

So I can jump from loading page to main page automatically, without clicking  a ```<Link />```.

Hopes react-router-native have a prop that receives a history instance.

**Comment by linonetwo** [comment]
For a workaround, I can use 

```javascript
// in a redux-saga generator that takes a JUMP action
AsyncStorage.setItem('history', JSON.stringify({ entries: ['/mainPage'], index: 0 }));
```

To perform a jump.

**Comment by timdorr** [comment]
NativeRouter is just a wrapper around MemoryRouter that saves stuff in AsyncStorage. You can use Router directly (since MemoryRouter sets up the history instance for you) to pass in your own history.

**Comment by meno1** [comment]
@linonetwo I believe @timdorr may be talking about doing something like this:  https://github.com/ReactTraining/react-router/issues/3972#issuecomment-264805667

@timdorr is that right?

**Comment by timdorr** [comment]
@meno1 Yes, that's the basic idea. 

One thing that could still be useful here is to export the StoreHistory component as a separate thing so you can put it back into the custom Router you would be creating.

**Comment by BenBenz** [comment]
@linonetwo Have you find a new to jump from loading page to main page automatically, without clicking a now ?
