### ISSUE TITLE
Prompt produce an error with StaticRouter

### ISSUE THREAD

**Issue by diondirza** [ReactTraining/react-router#4543]
## Version
4.0.0-beta.6

## Test Case
Use `Prompt` component with server side rendering (isomorphic app)

## Steps to reproduce
Use `Prompt` inside a `Route` component  with `StaticRouter`
```
<StaticRouter location={request.url} context={reactRouterContext}>
  <Switch>
    <Route exact path="/" component={Home} /> // Prompt inside Home component
  </Switch>
</StaticRouter>
```

## Expected Behavior
Component rendered normally

## Actual Behavior
It produce an error in server, page cannot load otherwise if I request  another route without prompt and navigate back to Home it works as expected. This is an error message from server.
```
Warning: Failed context type: The context `router.block` is marked as required in `Prompt`, but its value is `undefined`.
```

**Comment by timdorr** [comment]
Thanks for finding this. Merged in a fix just now.
