### ISSUE TITLE
Possible infinite loop when redirecting from indexroute

### ISSUE THREAD

**Issue by willdembinski** [ReactTraining/react-router#4545]
## Version
2.0.0

Will totally make a PR to patch this if given the go-ahead.

## Test Case
http://jsbin.com/tisurigeze/edit?html,js,output
## Steps to reproduce
If you "replace" your current route (in the IndexRoute) with an object that doesnt have "pathname" - lowercase - it will enter an infinite loop
## Expected Behavior
It would be awesome to have a warning or any error.
## Actual Behavior
Infinite loop because it currently defaults to "/" if it cant find "pathname" on the object -which is the route you're currently in - creating a loop.

**Comment by willdembinski** [comment]
Upon some investigation - it looks like this occurs in the history module.

**Comment by timdorr** [comment]
Could you open up an equivalent issue over there? Note that history 2.x isn't maintained, nor is react-router 2.x at this point. So, I would double-check that it still exists in 3.0 (don't worry, the upgrade is actually really, really easy) and submit an issue if it is.
