### ISSUE TITLE
extra componentWillReceiveProps() call in v3

### ISSUE THREAD

**Issue by nippur72** [ReactTraining/react-router#4552]
I migrated an `hashHistory` app from router v2 to v3, and noticed that, when there are URL parameters, there is an extra call to `componentWillReceiveProps()`.

Example route: "/user/:id"

in v3, route to: "/user"  triggers `componentDidMount()`, then `componentWillReceiveProps(null)`.
in v2, route to: "/user"  triggers `componentDidMount()` only

I haven't found this in the breaking changes, so I'm reporting it (not sure if it's a bug or a feature).

**Comment by timdorr** [comment]
Caused by ReactTraining/history#427, so keep an eye on that issue.
