### ISSUE TITLE
v4x Router and Route doesn't pass props to children like it used to

### ISSUE THREAD

**Issue by craigcosmo** [ReactTraining/react-router#4553]
I have here two nearly identical examples. One I use reactjs project and the other I use in react-native project.

The problem is in react project, all my routes automatically received props parent. But in react-native they don't. 

## Version
4.0

## Reproduce
**react js index.js**
```js
<Provider store={mainStore}>
	<Router history={history}>
		<Route path="/" component={MainContainer}>
			<IndexRoute component={Home} />
		</Route>
	</Router>
</Provider>
```

**react native index.js**
```js
<Provider store={mainStore}>
	<NativeRouter>
		<MainContainer>
			<Route exact path="/" component={Home} />		
		</MainContainer>
	</NativeRouter>
</Provider>
```
**MainContainer.js**
```js
class Page extends React.Component {
	render() {
		return (
			<div className="page">
				{React.cloneElement(this.props.children, {...this.props})}
			</div>
		)
	}
}
function mapDispatchToProps(dispatch){
	return bindActionCreators(mainAction,dispatch)
}
export default connect(mapStateToProps, mapDispatchToProps)(Page)
```

## Expected Behavior

In react-native project Component Home should have props passed from MainContainer like the screen shot below

<img width="758" alt="screen shot 2017-02-19 at 10 59 57 pm" src="https://cloud.githubusercontent.com/assets/538657/23103982/5c6ad97e-f6f7-11e6-8e9d-a530c74e3774.png">

## Actual Behavior
In react-native project Component Home does not have props passed from MainContainer, it has object like this instead

<img width="752" alt="screen shot 2017-02-19 at 10 52 40 pm" src="https://cloud.githubusercontent.com/assets/538657/23103924/2cb041ac-f6f6-11e6-9885-666d65d7de48.png">

**Comment by timdorr** [comment]
This is intentional. In 4.0, you would use the render prop to be able to pass things into your children. It operates the same as React does normally now.

**Comment by jklepatch** [comment]
I had the same problem with "react-router-dom": "^4.0.0".
This is my solution:

```
<Route 
  path="/posts" 
  render={(routeProps) => (<Posts {...routeProps} posts={this.state.posts} />)} />
```

It uses the `render` prop of the `<Route>` component, and also add the props of `<Route>` to the child component with `routeProps`.

More details below.

## app.jsx

```
import ReactDOM from 'react-dom';
import React from 'react';
import {BrowserRouter as Router, Route, Link} from 'react-router-dom'

import Posts from './components/posts/index.jsx';
import initialData from './data.jsx';

const root = document.getElementById('root');

class App extends React.Component {
  constructor(props) {
    super(props);
    this.state = initialData;
  }

  render() {
    return (
      <Router>
        <div>
          <ul>
	     <li><Link to="/posts">Posts</Link></li>
	   </ul>
	   <main>
	     <Route 
                 path="/posts" 
                 render={(routeProps) => (<Posts {...routeProps} posts={this.state.posts} />)} />
	   </main>
         </div>
       </Router>	
    );
  }
}
```

ReactDOM.render(<App />, root);

## posts.jsx

```
import React from 'react';

class PostsIndex extends React.Component {
  constructor(props) {
    super(props);
  }

  render() {
    return (
      <div>{/*posts available in this.props.posts/}</div>
    );
  }
}
```
