### ISSUE TITLE
Feature request: `render` prop on `Link`

### ISSUE THREAD

**Issue by marcgreenstock** [ReactTraining/react-router#4554]
I feel the `Link` and `NavLink` components in `react-router-dom` are lacking flexibility when it comes to custom links.

Take the following html example:

```html
<li className='active'>
  <a href='/'>Home</a>
</li>
```

The [v4 documentation](https://reacttraining.com/react-router/examples/custom-link) is clear on how to handle custom links, however it could be handled more easily with a `render` prop in the `Link` component and having `NavLink` forward `render` and `isActive`.

```jsx
<NavLink exact to='/' render={({isActive, href, onClick}) => (
   <li className={isActive ? 'active' : ''}>
     <a href={href} onClick={onClick}>Home</a>
  </li>
)} />
```

I am happy to submit a PR if you think this is a good idea.

**Comment by jaypea** [comment]
btw. something similar (children as function) was available in the alpha versions: https://github.com/ReactTraining/react-router/pull/3881
would love to get it back.

**Comment by timdorr** [comment]
You can do exactly that as long as you swap out some words for other words:
```js
<Route exact to path='/' children={({match, href, onClick}) => (
   <li className={match ? 'active' : ''}>
     <NavLink to={href} onClick={onClick}>Home</NavLink>
  </li>
)} />
```
It's all there already :smile:

**Comment by marcgreenstock** [comment]
@timdorr thanks. This makes sense but I see some issues with this.

As far as I can see, `onClick` is not a property that is received by the handler for the `children` prop on the `Route` component, nor is `href` for that matter (but that can be sourced elsewhere).

But the point of this issue is really to allow `Link` to work with third-party components such as `Button`, `MenuItem` and `NavItem` from [React Router Bootstrap](https://react-bootstrap.github.io/components.html) or [React MDL](https://react-mdl.github.io/react-mdl/components/menu/).

I appreciate that `Route` can take care of most of the work when it comes to active or not, and it is a really nice pattern. Everything in your comment above looks great, except that `onClick` is undefined.

The `handleClick` method on the `Link` component comes with some extra functionality, so instead of changing the render of `Link`, perhaps it may be an idea to move the `handleClick` method up into the `router` context?

**Comment by timdorr** [comment]
Oh yeah, sorry about that. But you can just move it up the chain and wrap all of that in a functional component that takes those props. 4.0 is all about composability!

**Comment by p0wl** [comment]
Can you make an example how that would look like with a NavLink from reactstrap or similar? I just cannot get my head around what you wrote. The Route render method does not provide an onClick method, so your example does not work.

With the alpha, it was quite easy to render a different component than the <Link>.
```
<Link to={'/admin'}>{({ href, onClick }) => <NavLink onClick={onClick} href={href}>Admin</NavLink>}</Link>
```
The result was just one <a> tag with a perfectly setup onClick handler.

Can you please tell us how that example would look like with 4.0.0?

**Comment by marcgreenstock** [comment]
@p0wl I created my own [LinkContainer](https://gist.github.com/marcgreenstock/fb47f0de50654f4c5d3e2f47cb106d74), I use it like so:

```js
<LinkContainer exact to='/about'>
   <NavLink>About</NavLink>
</LinkContainer>
```

Perhaps there's a better way, I don't know, but it works.

**Comment by breakds** [comment]
AS @marcgreenstock has mentioned, without such flexibility it is really painful to work with third party components that have already got a "<a>" in it, e.g. Grommet's [Anchor](https://grommet.github.io/docs/anchor). It does not make sense to have Link in Anchor, nor Anchor in Link, since either way we will have "<a>" inside a "<a>".

It would be better if we do not have to use <Link> to trigger a route change, but I could not find that API in the documentation.

**Comment by p0wl** [comment]
any thoughts @timdorr?

**Comment by breakds** [comment]
Update: I am currently using `withRouter` and `history` property to work it around, which seems a good enough solution. See [this link](http://stackoverflow.com/questions/42123261/programmatically-navigate-using-react-router-v4/42124328?noredirect=1#comment72931236_42124328) on StackOverflow.

**Comment by ekilah** [comment]
I too would prefer a render prop for this functionality. It seems silly for us to have to compute whether or not the link is active on our own when `NavLink` already knows this. 

Here's a simple example of the 'workaround' that I used, it's pretty unfortunate to need this:

```jsx

interface IProps extends RouteComponentProps<any> {
  pathToLink: string //the path to link to, i.e.: `/about/team`
  linkText: string
}

const WrappedNavLink = ({pathname, ...routeComponentProps}: IProps) => {
  const isActiveLink = routeComponentProps.location.pathname === pathToLink
  return (
    <div>
      <NavLink
        key={i}
        to={{pathname: pathToLink}}
      >
        <Text color={isActiveLink ? 'black' : 'grey'}>{linkText}</Text>
      </NavLink>
    </div>
  )
}

export default withRouter(WrappedNavLink)
```
