### ISSUE TITLE
there is no "createMemoryHistory" in v4,  how to make the router link to a url manually?

### ISSUE THREAD

**Issue by songdun** [ReactTraining/react-router#4558]
when I use the v3, I can use 
`const createMemoryHistory= require('react-router').createMemoryHistory;
createMemoryHistory.push(url)` to make the router link to a url manually,
but now I update react-router to the v4, there is no "createMemoryHistory",  so what can I do ? I also need to make the router link to a url manually， without `<link>`.

**Comment by pshrmn** [comment]
`createMemoryHistory` comes from the `history` library.

```js
import { createMemoryHistory } from 'history'
```
