### ISSUE TITLE
Question about Nested Routes 

### ISSUE THREAD

**Issue by CusProjects** [ReactTraining/react-router#4562]
"react": "15.3.2",
 "react-router": "4.0.0-alpha.4"

How can i create nested routes ?
i tried with
`<Match  
			 	  		routes={[
			 	  			{pattern: '/signin', component: Signin},
			 	  			{pattern: '/test', component: Test}
			 	  		]}
			 	  	/>`

but is still not working.

**Comment by achung89** [comment]
I believe the 'Match' API has been changed back to 'Route'. You can refer to the [docs](https://reacttraining.com/react-router/api) for more details.

**Comment by ryanflorence** [comment]
the basic example has nested routes: https://reacttraining.com/react-router/examples/basic. It's all Just Components™ so you nest routes by ... well ... nesting them. It's like asking how to nest divs :P

**Comment by stoplion** [comment]
I'm not seeing any examples or nested `<Route>` in that link.

**Comment by timdorr** [comment]
@stoplion Look at the Topics component

**Comment by ryanflorence** [comment]
Routes nest with the UI. It's hard to explain because there is nothing really to explain anymore :P

**Comment by EvNaverniouk** [comment]
@CusProjects @stoplion I too found the docs and the basic example confusing as it didn't really show the wrong way to do it. In hopes that others find this thread here is how I understand nested routes:

1. `<Route />` components should **not** be nested when defined. eg:

```
// This won't work.
<Route component={About} path="/about">
    <Route component={AboutMe} path="me" />
    <Route component={AboutYou} path="you" />
</Route>
```

2. `<Route />` must use absolute `path` values, eg:

```
// This will work
<Route component={About} path="/about" />
<Route component={AboutMe} path="/about/me" />
<Route component={AboutYou} path="/about/you" />
```

3. If you want to nest routes to share UI then you must nest the `<Route />` component inside the `component` class of the top-level `<Route />`, eg:

```
// First define the top-level route
<Route component={About} path="/about" />

// Then inside your `About` component you can return a new `<Route />`

class About extends Component {
   render () {
      // Note that the `path` must still be absolute
      return <Route component={AboutMe} path="/about/me" />
   }
}
```

**Comment by sckoh** [comment]
@EvHaus thanks, number 3 is working. The migration does not mention about the need of using full absolute path in nested routes
