### ISSUE TITLE
Question about existing path being matched by another route

### ISSUE THREAD

**Issue by andreyluiz** [ReactTraining/react-router#4563]
I have two routes:

```
/admin/users/:id
/admin/users/add
```

I am using React Router 4.0.0-alpha.6 and when I access the `/admin/users/add` route, the `/admin/users/:id` is also matched. And this is not wrong, because `add` is a valid parameter.

But I need to make those two routes behave separately. How can I achieve this without needing to rename my routes?

My matches:
```jsx
<Match
  exactly
  pattern="/admin/users/add"
  component={AdminUserAddPage}
/>

<Match
  exactly
  pattern="/admin/users/:id"
  component={AdminUserEditPage}
/>
```

**Comment by pshrmn** [comment]
First, you should upgrade to the beta. Changes are minor, mostly just changing `<Match>` to `<Route>` and some prop names. Then, use the [`<Switch>`](https://github.com/ReactTraining/react-router/blob/v4/packages/react-router/docs/Switch.md) component.

**Comment by andreyluiz** [comment]
Thank you @pshrmn.
