### ISSUE TITLE
Is there a way to update only a dynamic property?

### ISSUE THREAD

**Issue by ryan4888** [ReactTraining/react-router#4564]
I need to update only one, dynamic, part of my path. The rest of it needs to remain the same... It seems rather simple but I am having a hard time finding a good solution. 

![image](https://cloud.githubusercontent.com/assets/10523324/23139702/ba3ab78e-f77b-11e6-8221-4e3e824d4ab3.png)

Here are my routes. Basically, I am using dynamic tabs. When the user creates a new tab, I generate an ID. When they click the new tab, I want to navigate from `/1/test` to `/2/test`. So the only thing that really needs to change is the dynamic part. Is there a way to do this? 

My issue is that if I use `this.context.location.pathname` to generate a new path, I will need to do some string manipulation. I will have to know exactly where my dynamic part is, and where the persistent part is. It seems like I should be able to tell react router that I want to change my `tabId` and have it know what I mean. 

Am I going about this the wrong way?

**Comment by ryanflorence** [comment]
Yep, string manip is what you'll have to do. This is much nicer in v4 since it gives you the partially matched path.
