### ISSUE TITLE
Add a Route option to disable passing context.router props to component

### ISSUE THREAD

**Issue by VladShcherbin** [ReactTraining/react-router#4565]
### Have a feature request?
=======================

Currently, `context.router` props are always passed to component.

If there are some routes with the same component, it will re-render. We will have to use `shouldComponentUpdate` to control re-rendering, which can be tedious sometimes. We can make use of `PureComponent` to solve this problem, but we need a way to prevent passing props.

```jsx
// common element
class UsersIndex extends PureComponent {
  render() {
    return <p>common users part</p>
  }
}

// routes
const Routes = () => (
  <BrowserRouter>
    <div>
      <ul>
        <li><Link to="/users">users</Link></li>
        <li><Link to="/users/create">create</Link></li>
      </ul>
      <Switch>
        <Route path="/users" render={UsersIndex} />
        <Route path="/users/create" render={UsersIndex} />
      </Switch>
    </div>
  </BrowserRouter>
)

// current way to solve this: change component to render
<Switch>
  <Route path="/users" render={() => <UsersIndex />} />
  <Route path="/users/create" render={() => <UsersIndex />} />
</Switch>

// proposed way to solve this
<Switch>
  <Route path="/users" component={UsersIndex} pure />
  <Route path="/users/create" component={UsersIndex} pure />
</Switch>

**Comment by ryanflorence** [comment]
> // current way to solve this: change component to render

That is the answer.

Make your own route if you want your API:

```jsx
const RouteWithoutRouter = ({ component: Comp, path }) => (
  <Route path={path} render={() => <Comp/>}/>
)

// viola!
<RouteWithoutProps path="/so-pure" component={SoPure}/>
```

**Comment by ryanflorence** [comment]
Also, I'm pretty sure the props that come in will do what you'd expect in `shallowCompare`. We don't change the identity of `match` or `location` unless the route changes, the rest of the values are primitives which should likewise do what you want.

**Comment by VladShcherbin** [comment]
Unfortunately, in my use-case the route changes, so even `PureComponent` re-renders. I guess, I'll have to use `render` then.

Thanks.
