### ISSUE TITLE
Route listeners still firing even though parent Router instance no longer exists

### ISSUE THREAD

**Issue by ctrlplusb** [ReactTraining/react-router#4566]
## Version
4.0.0

Concerning the following lines: 
https://github.com/ReactTraining/react-router/blob/v4/packages/react-router/modules/Route.js#L50
https://github.com/ReactTraining/react-router/blob/v4/packages/react-router/modules/Route.js#L75

These are executed within the `componentWillMount` and `componentWillUnmount` lifecycle hooks of `Route`.

There are cases where `componentWillUnmount` will not fire - like a "pre-render" parse to prepare the application in some manner.  In this case I noticed that the listen event for a `Route` still fires for a location match even though the `parentRouter` that it was initially created against in the "pre-render" parse no longer exists.  I then get the following error message:

```
warning.js:36 Warning: forceUpdate(...): Can only update a mounted or mounting component. This usually means you called forceUpdate() on an unmounted component. This is a no-op. Please check the code for the Route component.
(anonymous) @ Route.js:54
listener @ createTransitionManager.js:54
(anonymous) @ createTransitionManager.js:73
notifyListeners @ createTransitionManager.js:72
setState @ createBrowserHistory.js:99
(anonymous) @ createBrowserHistory.js:125
confirmTransitionTo @ createTransitionManager.js:44
(anonymous) @ createBrowserHistory.js:123
handlePop @ createBrowserHistory.js:130
handlePopState @ createBrowserHistory.js:106
```

Is there any way to clean up all existing listeners or do some sort of general disposal / garbage collection? Is this a potential memory leak issue too?

**Comment by mjackson** [comment]
Please show us some code. Stack traces aren't terribly useful.

**Comment by ctrlplusb** [comment]
Apologies, I'll try create a minimal example to illustrate this.

**Comment by ctrlplusb** [comment]
Hmmm, this is really tricky to create a minimal example for.  Further digging shows that the listeners only continue to live whilst in a dev environment.  I am going to close this issue for now until I can come back with a more useful report. x
