### ISSUE TITLE
getComponent() fails silently for code splitting if promise is returned

### ISSUE THREAD

**Issue by matt-way** [ReactTraining/react-router#4567]
This is not quite a bug, but definitely an issue. Just spent hours trying to debug why code splitting my routes was failing silently. Eventually figured out it was because I was doing this:

```
getComponent: (nextState, cb) =>
    require.ensure([], require => cb(null, require('./home').default), 'home')
```
 and not this:

```
getComponent: (nextState, cb) => {
    require.ensure([], require => cb(null, require('./home').default), 'home')
}
```

Looking through the router code, it shows that if a promise is returned to `getComponent()` the callback is automatically handled by react-router. So if you do the first example above, the callback is called twice, ultimately with the component being null.

In my opinion this is bad design. A callback should be left entirely up to the user, and not handled by the library. Even if this is better documented, it is still bad.

**Comment by mjackson** [comment]
Glad you figured it out. `getComponent` is old API that is going away soon anyway, so I'm not going to fix it. Feel free to submit a PR if you'd like to change something.

**Comment by matt-way** [comment]
No worries. Figured v4 was preference, so put it here in case someone else has the issue.
