### ISSUE TITLE
Navigation confirmation example needs improving

### ISSUE THREAD

**Issue by Kitanotori** [ReactTraining/react-router#4570]
[The example](https://github.com/ReactTraining/react-router/blob/master/docs/guides/ConfirmingNavigation.md) shows how to add logic before transitioning away from a particular component. However, I want to add some logic and possibility to cancel transition before *every* transition. I don't want to add such logic to every component. I couldn't find example anywhere on how to achieve this.

**Comment by timdorr** [comment]
You need to attach that to your history instance, which is outside this library. Here's how you do it: https://github.com/ReactTraining/history/blob/v3.x/docs/ConfirmingNavigation.md
