### ISSUE TITLE
Does react-router v4 support Hot Module Replacement

### ISSUE THREAD

**Issue by helfi92** [ReactTraining/react-router#4572]
Does `react-router` v4 support Hot Module Replacement with `react-hot-loader` v3? I can't seem to find any documentation on that. If someone can help, I'd be willing to update the docs.

**Comment by mjackson** [comment]
It should, yes. Though I don't know anyone actually doing it yet. You can be the pioneer :)

The blocker before was that all of our configuration was specified up front in one spot. But now that our API is Just Components™ anything that you can do with other components you should be able to do with React Router. Please give it a shot and let us know how it goes.

**Comment by hampusohlsson** [comment]
@helfi92 @mjackson can confirm it is working, I'm using `react-router v4`  `webpack v2` and `react-hot-loader v3beta-6` 😄

**Comment by helfi92** [comment]
@hampusohlsson @mjackson That's right, it worked liked a charm :)

**Comment by rclai** [comment]
Does it work if you're using [lazy loaded routes](https://github.com/mhaagens/lazy-route)?

**Comment by helfi92** [comment]
@rclai It should work. The lazy loaded library seems to use `System.import`. You can do this:

```javascript
// App.js
// ...

const Foo = asyncComponent(() => System.import('./components/Foo').then(module => module.default));
const Bar = asyncComponent(() => System.import('./components/Bar').then(module => module.default));
const Home = asyncComponent(() => System.import('./components/Home').then(module => module.default));

const App = () => (
  <Router>
    <div className="App">
      <ul>
        <li><Link to="/">Home</Link></li>
        <li><Link to="/foo">Foo</Link></li>
        <li><Link to="/bar">Bar</Link></li>
      </ul>

      <Route exact path="/" component={Home} />
      <Route path="/foo" component={Foo} />
      <Route path="/bar" component={Bar} />
    </div>
  </Router>
);

// ...
```

```javascript
// asyncComponent.js
import React from 'react';

const asyncComponent = getComponent => class AsyncComponent extends React.Component {
  constructor(props) {
    super(props);

    this.Component = null;
    this.state = { Component: AsyncComponent.Component };
  }

  componentWillMount() {
    if (!this.state.Component) {
      getComponent().then(Component => {
        AsyncComponent.Component = Component;

        this.setState({ Component });
      });
    }
  }

  render() {
    const { Component } = this.state;

    if (Component) {
      return <Component {...this.props} />;
    }

    return null;
  }
};

export default asyncComponent;
```

**Comment by helfi92** [comment]
I created [react-router-starter](https://github.com/mozilla-neutrino/react-router-starter), a starter kit, that uses react-router v4 + router code splitting + hot module replacement. Feel free to use.
