### ISSUE TITLE
Using object spread or Object.assign to replace route causes duplicate query params

### ISSUE THREAD

**Issue by dtaub** [ReactTraining/react-router#4573]
## Version
2.7.0

## Steps to reproduce
Current URL: `/foo?a=1`
```js
this.props.router.replace({
  ...this.props.location,
  pathname: '/bar'
});
```
## Expected Behavior
`/bar?a=1`
## Actual Behavior
`/bar?a=1&a=1`

I don't know if this is a bug exactly or just undefined behavior but it is a bit of a gotcha at the least. This seems to happen because using object spread causes both `location.query` and `location.search` to be passed and it ends up using both.

**Comment by mjackson** [comment]
This is one of the main benefits to sticking with just `location.search` in v4 instead of having 2 potentially different versions of the same info in the `location` object.

I'd recommend you try and upgrade as soon as possible. Version 2 is old and is no longer supported.
