### ISSUE TITLE
Documentation - importing from "react-router" not "react-router-dom"

### ISSUE THREAD

**Issue by revelt** [ReactTraining/react-router#4577]
In documentation there are multiple examples showing code importing `from 'react-router'`. For example, in `Switch` chapter, we have `import { Switch, Route } from 'react-router'`.

Should all those occurrences use `from 'react-router-dom'` instead?

Thank you.

**Comment by timdorr** [comment]
Not necessarily. If you don't have a DOM (react-native or jest, for example), then you don't want to import them from react-router-dom.  A lot of these are just re-exports from react-router anyways: https://github.com/ReactTraining/react-router/blob/v4/packages/react-router-dom/modules/Route.js
