### ISSUE TITLE
Switch is re-mounting the same component on route change

### ISSUE THREAD

**Issue by random-stranger** [ReactTraining/react-router#4578]
## Version
4.0.0-beta.6

## Test Case
Same issue as described [here](https://github.com/ReactTraining/react-router/issues/4551#issuecomment-281454148), the test case is from it

bug exists
http://codepen.io/ReactJSTraining/pen/ZLggog

no bug, but uses non-supported array as Route path 
http://codepen.io/anon/pen/qReegR

## Steps to reproduce
`UsersIndex` component is the one, that is persistent across the routes. Change the route to reproduce the bug (this component is re-mounted).

## Expected Behavior
When route is changed, `UsersIndex` component is not re-mounted, only passed props are changing.

## Actual Behavior
When route is changed, `UsersIndex` component is re-mounted on every route change.

This could be solved with [Route path array support](https://github.com/ReactTraining/react-router/issues/4551) or current `Switch` component fix.

**Comment by pshrmn** [comment]
This might have to do with the usage of `React.cloneElement` in the `<Switch>` components render function. I tested this with my [`<ConfigSwitch>`](https://github.com/pshrmn/rrc/blob/master/docs/ConfigSwitch.md), which uses `React.createElement`, and it worked as expected ([codepen](http://codepen.io/pshrmn/pen/vxBZPN)).

**Comment by timdorr** [comment]
Sanity check: Is this actually a problem? Mounting : unmounting !:: construction : destruction. 

Switch's goal should be just to juggle which Route is mounted based on the current location. The component is actually instantiated into an element by the render function of the Switch's container. `cloneElement` is only used as a trick to inject some props into an already instantiated component. Otherwise, we'd just return the appropriate Route, mounting it onto the render tree.

**Comment by random-stranger** [comment]
@timdorr it's a common pattern to fetch data in `componentDidMount()`, it will also trigger on every route change. Same goes for `render()`, no way to prevent re-rendering.

**Comment by timdorr** [comment]
Sorry, still not getting it (I'm trying!). What's the problem with that? If I've got some user profile page up, navigate away, the user posts some new content, and navigate back to the profile page, I would want to see that new content. So a fresh fetch from the lifecycle method would be good, no?

**Comment by VladShcherbin** [comment]
@timdorr in my use-case the component needs to be persistent across several routes.

- When you navigate to `/users`, you can see `UsersIndex` with a list of users.
- When you navigate to `/users/create`, you can see the same `UsersIndex` list of users and `UsersCreate` form (modal window).

So, when you navigate across this routes, `UsersIndex` is always visible and has to be mounted and fetched only once. When the user is added, the users list is automatically updated, no need to re-fetch.

![users](https://cloud.githubusercontent.com/assets/6711845/23229464/7756bae4-f951-11e6-89de-03a7a8a9152b.jpg)

**Comment by timdorr** [comment]
Sort of. Why are you using a Switch for that? Just have a non-exact Route for the list:
```js
<Route path="/users" component={UserIndex} />
<Route path="/users/create" component={UserCreate} />
```
That would do the same thing.

**Comment by VladShcherbin** [comment]
@timdorr it will render `UserIndex` on all `/users` routes, even on `/users/not/found/route`.

I want to render `NotFound` route on all undefined routes.

**Comment by VladShcherbin** [comment]
As i mentioned above, Switch can be replaced with an array of paths, passed to Route, but currently it's not supported (but working).

```jsx
<Route exact path={['/users', `/users/create`]} component={UsersIndex} />
```

**Comment by ryanflorence** [comment]
@timdorr I consider this a bug.

@VladShcherbin Please let's not talk about array paths in here, that's a totally different conversation :)

**Comment by mjackson** [comment]
Hmm, maybe we don't use `cloneElement`? In any case, I'd love to see a failing test for this. Makes it a lot easier to fix.

**Comment by ryanflorence** [comment]
cloneElement shouldn't cause a remount, I was just looking at the code and I'm a bit stumped

**Comment by taurose** [comment]
It's [React.Children.toArray](https://github.com/ReactTraining/react-router/blob/v4/packages/react-router/modules/Switch.js#L56) that causes this by setting the keys of the `<Route>`s.

> Returns the children opaque data structure as a flat array **with keys assigned to each child**. Useful if you want to manipulate collections of children in your render methods, especially if you want to reorder or slice this.props.children before passing it down.

([docs](https://facebook.github.io/react/docs/react-api.html))

Not sure exactly why this was added. If it's needed for flattening or sth, overwriting the key in `cloneElement` seems to work as well.

Anyway, I think there are arguments for both behaviors, both in terms of how you'd initially expect it to work and in terms of what you want to do with it. Though it seems that with the suggested behavior, one could force the remount by themselves, which is not possible the other way around, e.g.: 

```js
<Route render={() => <Comp key="1" />} />
<Route render={() => <Comp key="2" />} />
```

**Comment by ryanflorence** [comment]
```
<Switch>
  <Route render={() => <Comp key="1" />} />
  <Route render={() => <Comp key="2" />} />
</Switch>
```

That feels more intuitive to me

**Comment by timdorr** [comment]
Here's a test case:
```js
  it('does not remount a route', () => {
    const node = document.createElement('div')
    const history = createMemoryHistory({ initialEntries: ['/'] })

    let mountCount = 0

    class App extends React.Component {
      componentWillMount() { mountCount++ }
      render() { return <div /> }
    }

    ReactDOM.render((
      <Router history={history}>
        <Switch>
          <Route exact path="/" component={App}/>
          <Route path="/foo" component={() => <div />}/>
        </Switch>
      </Router>
    ), node)

    expect(mountCount).toBe(1)
    history.push('/foo')
    expect(mountCount).toBe(1)
    history.push('/')
    expect(mountCount).toBe(2)
  })
```
But I must be doing something wrong, because it passes...

**Comment by random-stranger** [comment]
@timdorr I guess it is:

```jsx
ReactDOM.render((
  <Router history={history}>
    <Switch>
      <Route exact path="/" component={App} />
      <Route exact path="/foo" component={App} />
    </Switch>
    <Route path="/foo" component={() => <div />}/>
  </Router>
), node)
```

**Comment by timdorr** [comment]
Oh, I'm totally missing things. The App component should not be remounted at all when switching between two component'ed Routes. I thought it was remounting too much just in general (not when going between two unique Routes). My bad...

Let me work that into the test...

**Comment by timdorr** [comment]
OK, here's a failing test:

```js
  it('does not remount a route', () => {
    const node = document.createElement('div')
    const history = createMemoryHistory({ initialEntries: ['/foo'] })

    let mountCount = 0

    class App extends React.Component {
      componentWillMount() { mountCount++ }
      render() { return <div /> }
    }

    ReactDOM.render((
      <Router history={history}>
        <Switch>
          <Route path="/foo" component={App}/>
          <Route path="/bar" component={App}/>
        </Switch>
      </Router>
    ), node)

    expect(mountCount).toBe(1)
    history.push('/bar')
    expect(mountCount).toBe(1)
    history.push('/foo')
    expect(mountCount).toBe(1)
  })
```
And changing the top of Switch's `render` to this fixes it:
```js
    const { children:routes } = this.props
    const { location } = this.state
```

**Comment by mjackson** [comment]
> It's React.Children.toArray that causes this

Nailed it, @taurose. Thanks :)

**Comment by wmertens** [comment]
@mjackson Can we get a release for this one?

**Comment by mjackson** [comment]
@wmertens Just released this morning in beta 7

**Comment by wmertens** [comment]
I am now running beta7 but I'm still seeing my component being remounted. Any quick tips to find the responsible parent?

**Comment by VladShcherbin** [comment]
I can confirm there is no bug in beta 7.

@wmertens it's probably re-rendering due to props change on route change, not re-mounting.

Thank you, guys! 👍

**Comment by wmertens** [comment]
No, the constructor is getting called, and I have to figure out which
parent is responsible…

**Comment by wmertens** [comment]
Found it in code of my own (merge mishap). All I had to do was put a breakpoint in Reacts `mountComponent` and make it conditional on truthy `doConstruct`. The first component to hit the breakpoint has the culprit parent. Will remember that one, useful.

```js
  mountComponent: function (transaction, hostParent, hostContainerInfo, context) {
[...]
    // Initialize the public class
    var doConstruct = shouldConstruct(Component);
/*=> here*/    var inst = this._constructComponent(doConstruct, publicProps, publicContext, updateQueue);
```

**Comment by VaishaliJain0209** [comment]
I am a bit new to React & React-Router. I am creating a SPA where I do not want components to be unmounted when I switch b/w routes. I am using 4.1.2 version of React-Router but ComponentDidMount is being called every time when I return to a mounted component after switching the route. Could you please suggest the version I should use.

**Comment by wmertens** [comment]
Try looking at the unmount/remounts via the timeline as explained in
https://facebook.github.io/react/blog/2016/11/16/react-v15.4.0.html - see
which component stays mounted, that is the one responsible for remounting
the rest

**Comment by katiepeters** [comment]
This still seems to be a problem if `Switch` is given an array of `Route` components (because of the `key` prop?).

So this doesn't cause a re-mount:
```
<Switch>
	<Route
		component={App}
		exact
		path="/"
	/>
	<Route
		component={App}
		exact
		path="/other"
	/>
</Switch>
```
But this does:
```
<Switch>
	{[
		<Route
			component={App}
			exact
			key="1"
			path="/"
		/>,
		<Route
			component={App}
			exact
			key="2"
			path="/other"
		/>,
	]}
</Switch>
```

Is that intentional/am I missing something?

**Comment by wmertens** [comment]
What happens if you don't pass a key, or pass the same key twice?

And what are the circumstances of the remounting?

**Comment by pshrmn** [comment]
@katiepeters Yes, React's reconciler will always unmount the existing component and mount a new one when two element's `key`s are different.

**Comment by katiepeters** [comment]
Ya, I ended up passing them the same key to get it to work. Wasn't sure if that was ideal, but maybe it's ok since `Switch` only renders one `Route` at a time

**Comment by artywhite** [comment]
@wmertens , @pshrmn , @timdorr please take a look on this case with `react-router-config` here: https://github.com/ReactTraining/react-router/pull/5430

**Comment by KaroseLiu** [comment]
I'm not sure, this commit fixed the bug, I upgraded the latest version v4.2.0 as your release, and try it, the component also remount. 

Here is my layout:

```javascript
const Layout = ({children, location}) => {
  // url like /:personId/a, /:personId/b
  const personId = location.pathname.split('/')[2]
  // b or a path
  const activeKey = location.pathname.split('/')[3]
  // The problem is every time the path changed, the Profile always componentDidMount.
  return <div>
    <Profile personId={personId}/>
    <Tabs
      type="card"
      activeKey={location.pathname.split('/')[3]}
      onTabClick={(key) => {
        const paths = location.pathname.split('/')
        history.push(`/person/${personId}/${key}`)
      }}
    >
      {tabs.map(tab =>
        (<TabPane tab={tab.title} key={tab.key}>
          {children}
        </TabPane>),
      )}
    </Tabs>
  </div>
}
```
The below is the Router config:
```javascript
const routes = [
  {
    path: '/a',
    component: A,
  },
  {
    path: '/b',
    component: B,
  },
  {
    path: '/c',
    component: C,
  },
]
const Router = ({ match }) => (
  <Switch>
    {
      routes.map(({ path, exact, strict, component: Comp }) =>
        (<Route
          key={path}
          path={`${match.url}${path}`}
          exact={exact}
          strict={strict}
          render={
            props => (
              <Layout {...props}>
                <Comp {...props} />
              </Layout>
            )
          }
        />),
      )
    }
  </Switch>
)
```
Every time the path change, the <Profile /> component will didMount again, so maybe my usage is the incorrect way to reuse the layout?

**Comment by TimoRuetten** [comment]
I am causing the same problem. Any updates to this ?

**Comment by wmertens** [comment]
@TimoRuetten that is very weird, can you share your whole code? This one looks too simplified…

**Comment by TimoRuetten** [comment]
@wmertens Yeah - its a bit simplified - but at the end not that much. This is the current code of our <AppRouter /> which is the first rendered Main-Component after all Provider we are using:


```
export default () => (
  <div>
    <Switch>
      <Route
        path="/:langCode"
        component={App}
      />
      <Route
        path="/:langCode/p/:nodeSlug/:nodeId"
        component={App}
      />
      <Route
        path="/:langCode/l/:regions*"
        component={App}
      />
    </Switch>
  </div>
);
```

Then we have in our <App /> a simple log in componentWillMount which gets always fired when clicking on a <Link /> link.

**Comment by wmertens** [comment]
Are you sure it's the Switch and not something higher up? You can also put `?react_perf` in your url and then you can use a Performance recording to see unmounts in the user events

**Comment by TimoRuetten** [comment]
Hey @wmertens - You were right, I'm sorry. A HOC of my `<App />` produced this problem! Sorry for the confusion and thanks for the fast response & help!

**Comment by wmertens** [comment]
@KaroseLiu you should give your Routes all the same key…

**Comment by julienvincent** [comment]
I still seem to be getting this issue (`v4.2.2`). I have confirmed that I have no HOC's or anything else affecting my app

**Comment by taurose** [comment]
This snippet works as expected without any unnecessary remounts, so the problem must be somewhere else.

**Comment by theenoahmason** [comment]
for anyone searching here, I am not getting remounts on switch, UNLESS switch is wrapped with react transition group's TransitionGroup/CSSTransition components.

**Comment by theenoahmason** [comment]
correction, I believe my above comment is only an issue when passing a key to switch, which react transition group requires. 

Itb seems animating a switch with react transition group requires a location for the switch component, which intern is causing a remount on the routes called component.

**Comment by wmertens** [comment]
You can also forego the switch and make sure only one route matches at a
time…

**Comment by hainessss** [comment]
What if I want my route to unmount and also be in a switch...  Using react-router-dom 4.1.1, my routes inside the switch don't unmount.  I need them inside a switch to be able to use a catch all route.  Seems like it wouldn't be hard to add a prop to coerce an unmount?  Any advice for my use case?
