### ISSUE TITLE
react-router adds slashes to URLs, when no slashes are wanted

### ISSUE THREAD

**Issue by Regaddi** [ReactTraining/react-router#4580]
I've encountered a sweet little problem and hope to get some help here as soonish as possible...
Is there any possibility to completely disable all the slash magic in react-router?
I need complete control over how URLs are configured and set with the <Link> component. But even if I completely miss out any slashes in my routers configuration, the <Link> will always produce a leading slash. And secondly if I link to another non-nested route, it will append that segment to the existing URL and adds another slash just before the segment I linked...
I expected to have these segments being appended to my configured basename and no slashes whatsoever...
Some basic information on my setup:

basename: example.com/app

```
<Route path=".html" component={Results} />
<Route path=".detail.html/:id" component={ResultDetail} />
```
So my expected routes are:

example.com/app.html => entry point of my application
example.com/app.detail.html/1 => some detail page

What I get is:

example.com/app/.html
example.com/app/.html/.detail.html/1

**Comment by timdorr** [comment]
When you are using a relative path, we have to add the slashes between path parts to correctly match the URL being provided to us. Otherwise, parameters would behave just like wildcard matches.

You need to include the full path part to make this work.
