### ISSUE TITLE
Nested routes in 4.0

### ISSUE THREAD

**Issue by Alxandr** [ReactTraining/react-router#4582]
Note: this might not be a bug, but just my misunderstanding of how things should work, but according to the api documentation for 4.0:

> Just as components are nested, context.router objects are nested and create a hierarchy. Each time you render a new <Route>, it shadows context.router to be the point of reference for all its descendants. This lets us express nested routes by simply nesting components.

## Version
4.0.0-beta.6

## Test Case
http://codepen.io/Alxandr/pen/pezKGy

Click the "Go" button to navigate to the route `/foo/bar` to see the wrong route being rendered.

## Steps to reproduce
I haven't played too much around with trying to reduce this example down to a minimal one, but if you put a route in a switch in a route in a switch, the innermost route needs an absolute path (as far as I can find at least).

## Expected Behavior
I would expect the route "/bar" to render in the inner switch in the example. I've tried different variations (like `bar`, `./bar`, etc.) but none of them has worked.

## Actual Behavior
The route "/foo/bar" renders.

**Comment by timdorr** [comment]
We're working through this right now in #4539
