### ISSUE TITLE
V4 Modals

### ISSUE THREAD

**Issue by marekkobida** [ReactTraining/react-router#4584]
Are we able to create the modals like in previous version of React Router? If I understand, now we can't use `this.props.children`. So how we can show the previous content when modal appears?

pinterest example in previous version
```
componentWillReceiveProps (nextProps) {
    if ((
      /* Something */
    )) {
      this.previousChildren = this.props.children
    }
  }
```

My stackoverflow question: http://stackoverflow.com/questions/42409175/react-router-v4-modal

**Comment by pshrmn** [comment]
With #4589, you should easily be able to create modals. That PR includes a [modal example](https://github.com/ReactTraining/react-router/pull/4589/files#diff-b670ef94fe3f57d46d7194d36b9b2000).

**Comment by marekkobida** [comment]
@pshrmn In your example modal appears but behind him is again something else than **_previous_** page...

**Comment by pshrmn** [comment]
@marekkobida Did you clone that branch? It relies on the changes in there to work.

**Comment by marekkobida** [comment]
@pshrmn Oh, I've just noticed it. Sorry for that. Thanks a lot.

**Comment by marekkobida** [comment]
@pshrmn If modal appears and then I will press CMD+R, modal still remains on the screen. Why it don't restart the component state?

**Comment by pshrmn** [comment]
When refreshing, you are at the same location, so it still has the state: `{ modal: true }`.

**Comment by marekkobida** [comment]
@pshrmn Yes but how can we prevent this? If I reload the page, state remains `{ modal: true }` and when I click on **_Close_** button, Gallery apears (not Image page). This is completely different from what I wanted in this issue. When I click on Close button, behind modal page must appear... not Gallery (the previous page from which I came). Thank you in advance for answer and probably correct solution.

**Comment by pshrmn** [comment]
On refresh, the `<ModalSwitch>` would be mounting, so `this.previousLocation` would be the same as `this.props.location`. You could probably modify [this line](https://github.com/pshrmn/react-router/blob/b77dc354abde0a9faa8e35004f51d5af398e187d/packages/react-router-website/modules/examples/ModalGallery.js#L111) to only show the modal when those two objects are different.

```js
const isModal = !!(location.state && location.state.modal && location !== this.previousLocation)
```
