### ISSUE TITLE
Pushing to routes right after each other will still first render the first route instead of last one pushed

### ISSUE THREAD

**Issue by pke** [ReactTraining/react-router#4585]
## Version
2.8.1

## Steps to reproduce

Push 2 routes onto the stack:

```es6
router.push("/")
router.push("/account")
```

## Expected Behavior

See the account page.

## Actual Behavior

Briefly see the home route and then the account page.

Isn't there a way to push/replace without the first pushed/replaced page to be rendered?

**Comment by timdorr** [comment]
You can enqueue your pushes separately:
```js
let pushTo
if (thing) pushTo = '/'
if (otherThing) pushTo = '/account'
router.push(pushTo)
```

**Comment by pke** [comment]
That's not my use case. I want the back stack preserved.

**Comment by timdorr** [comment]
Unfortunately, there's no way of doing this. Perhaps you can get around it by creating your own custom history with a `pushMultiple` method or one that accepts arrays to `push`, but there isn't direct access to bypass the subscription system and directly insert entries before transitions occur.

**Comment by pke** [comment]
Hmm ok thanks. Even in v4 this is not possible?

**Comment by timdorr** [comment]
Nope, because that's just the base assumption. We don't have a system to basically to router "transactions".
