### ISSUE TITLE
too many history items, is there a way to reduce?

### ISSUE THREAD

**Issue by windsome** [ReactTraining/react-router#4590]
think about the following scene.   
the url pattern:  
```
/products
/products/fruits
/products/fruits/apple
/products/fruits/orange
/products/computes
/products/computes/....
```
after do a lot of click, the history items grow quickly, and some of the items are same url. is there a way to custom the history items?  

maybe do check in onChange / onEnter hook?

**Comment by timdorr** [comment]
The history doesn't drop previous locations. That's not what it's designed to do. If you want to go to a path without adding another entry, you can use `replace`.

**Comment by windsome** [comment]
Here is the code of handleClick  in Link.js, which give an option to do replace instead of push.
It solve part of my problem.
```
  handleClick = (event) => {
    if (this.props.onClick)
      this.props.onClick(event)

    if (
      !event.defaultPrevented && // onClick prevented default
      event.button === 0 && // ignore right clicks
      !this.props.target && // let browser handle "target=_blank" etc.
      !isModifiedEvent(event) // ignore clicks with modifier keys
    ) {
      event.preventDefault()

      const { router } = this.context
      const { replace, to } = this.props

      if (replace) {
        router.replace(to)
      } else {
        router.push(to)
      }
    }
  }
```
<https://github.com/ReactTraining/react-router/blob/v4/packages/react-router-dom/modules/Link.js#L41>
