### ISSUE TITLE
Issue with trailing forward slashes and server-side rendering

### ISSUE THREAD

**Issue by DavidLi-Minxiao** [ReactTraining/react-router#4593]
## Version
react-router-dom 4.0.0.beta.6

## Test Case
https://github.com/DavidLi-Minxiao/react-boilerplate
https://davidli-web.herokuapp.com/

Attempting to have a universal React app, with both client and server side rendering

Client Router:
`
<BrowserRouter>
  <App />
</BrowserRouter>`

Routes:
`<Switch>
        <Route path='/' exact strict={false} component={Home} />
        <Route path='/about' strict={false} component={About} />
        <Route path='/blog' strict={false} component={Blog} />
        <Route path='/contact' strict={false} component={Contact} />
        <Route component={NotFound} />
</Switch>`

Server Router:
`server.use((req, res) => {
  const context = {}
  let body = ReactDOMServer.renderToString(
    React.createElement(StaticRouter, {location: req.url, context: context},
      React.createElement(App)
    )
  )
  res.write(template({body: body}))
  res.end()
})`

## Steps to reproduce
When navigating directly (so using server-side rendering), add a trailing forward (back?) slash to the URL.

## Expected Behavior
Having strict={false} on the Routes will ignore the trailing forward slash.

## Actual Behavior
The entire site will crash and node.js will attempt to deliver the static html page as Javascript, leading to:
Unexpected token '<' at the doctype declaration.

**Comment by pshrmn** [comment]
Not a React Router issue. Your `index.html` uses a relative path. If you open the network tab in dev tools, you will see that when you try to load `/about/`, it makes a request for `/about/public/js/bundle.js`.

**Comment by DavidLi-Minxiao** [comment]
No comment. :'(
