### ISSUE TITLE
Consider passing route props to render prop

### ISSUE THREAD

**Issue by donaldpipowitch** [ReactTraining/react-router#4595]
Have a feature request?
=======================

I'd be nice, if `props` passed to a route could be passed to `render`, too. This would be useful to write generic custom routes.

E.g. I have a custom route like this:

```
export class FooRoute extends Route {
  static defaultProps = {
    render: (props) => { /* complex render logic */}
  };
}
```

I do it that way so I can use my `<Foo/>` inside `<Switch/>`.

I'd like to configure my render logic, but use a default render function:

```
<FooRoute
  path="/home"
  doCoolStuff
/>
```

As far as I can see it is not possible to _see_ `doCoolStuff` in `render`. (The `props` passed to render is a [`router`](https://github.com/ReactTraining/react-router/blob/v4/packages/react-router/modules/Route.js#L81).)

Maybe `this.props` and `this.router` could be passed as a merged `props` to the `render` or `this.props` could be passed as `routeProps` or something like that? Something like that:

```
    const props = { ...this.router, routeProps: { ...this.props } }
```

**Comment by pshrmn** [comment]
This was temporarily a thing before, but it was removed because it is unnecessary. With the `render` prop you can include any props that are in scope.

```js
const View = () => {
  const doCoolStuff = () => { alert('!') }
  return (
    <Route
      path='/yay'
      render={(props) => <Alerter {...props} doCoolStuff={doCoolStuff} /> }
   />
  )
}
```

**Comment by donaldpipowitch** [comment]
But this doesn't not work inside [`<Switch/>`](https://github.com/ReactTraining/react-router/issues/4576).

**Comment by pshrmn** [comment]
As I said there, custom `<Route>`s _can_ work, but they aren't supported. You can modify your custom route to work, but generally speaking you should just use a `<Route>`.
```js
const View = () => {
  const extraProp = 'extra'
  return (
    <Switch>
      <Route path='/yay' render={(props) => <ComplexThing {...props} extraProp={extraProp} />
    </Switch>
  )
}
```

**Comment by donaldpipowitch** [comment]
> but they aren't supported

I think that's why I looked for a supported way.
