### ISSUE TITLE
search and query are empty when action is "POP"

### ISSUE THREAD

**Issue by kybarg** [ReactTraining/react-router#4600]
## Version
3.0.0

## Test Case
http://jsbin.com/sacerobuxi/edit?html,js,output

**Comment by timdorr** [comment]
This doesn't give any workable info. If there's a problem with the history action, you should open up an issue over on that repo.

**Comment by kybarg** [comment]
@timdorr Hello! Sorry, updated description

**Comment by kybarg** [comment]
@timdorr sorry, was my config issue
