### ISSUE TITLE
Documentation error about Router

### ISSUE THREAD

**Issue by vincentaudebert** [ReactTraining/react-router#4601]
I just noticed a small error in the documentation about Router
https://reacttraining.com/react-router/#router

In the code example it imports `history/createBrowserHistory` as `createHistory` but then calls it as `createBrowserHistory()`

This raises an error.

**Comment by timdorr** [comment]
This was fixed in #4531, but the docs need to be republished. I know @ryanflorence is working on some website updates, so that fix should get wrapped up with that.
