### ISSUE TITLE
Async routes section of documentation is confusing, please clarify

### ISSUE THREAD

**Issue by dKab** [ReactTraining/react-router#4602]
Although this is a question by nature and not a bug report, still I don't think that this would be suitable for StackOverflow and that's why I'm asking here. I suspect that maybe it isn't just me and this section of docs could be improved to provide more thorough explanation because now it seems ambigious to me. Namely,  I don't understand the reasoning of using match function on the client side.

[Let's see what it says](https://github.com/ReactTraining/react-router/blob/master/docs/guides/ServerRendering.md#async-routes): 

>Server rendering works identically when using async routes. However, the client-side rendering needs to be a little different to make sure all of the async behavior has been resolved before the initial render, to avoid a mismatch between the server rendered and client rendered markup.
On the client, instead of rendering
   ` render(<Router history={history} routes={routes} />, mountNode)`
You need to do
```
match({ history, routes }, (error, redirectLocation, renderProps) => {
    render(<Router {...renderProps} />, mountNode)
})
```

In a nutshell, what this paragraph says is "if you have at leat one async route, your client code should
wrap call to render(<Router/>) in `match(... () => { render(<Router/>)`. That's how I read it. 
And here I'm failing to understand the **why** of it.  

First of all,  am I correct that by **async route** we mean the route that resolves to a component which needs to do some async action before it can render itself e.g. do ajax call for data. 
Is this correct?

I'm sorry but I don't see a difference between async route and synchronous route, apart from the way in which the server should handle these two types of routes.
What I mean is the output that server sends to the client is the same, because essentially it does the same thing:

```
match({ routes: routes, location: ctx.path }, (err, redirect, props) => {
       ...
        } else if (props) {
           // the only diffrence wil be here
           // we will asyncrhonously do what we need to do if it's an async route and then send our html
           // if its a sync route we will skip this step and send rendered html right away
            const store = createStore(recipiesReducer);
            const appHtml = renderToString( <Provider store={store}>
                                                <RouterContext {...props}/>
                                            </Provider>);
            const initialState = store.getState();
            ctx.body = renderPage(appHtml, initialState);
        })
```
(If, hovewer we are navigating to such route by `<Link>` on client side - we will use componentDidMount hook to do this asynchronous step that we would do if this route would be initial point (if the server would render it))

So from the client side perspective why does it matter if route is sync or async except for the fact that with async route it will have to wait a little bit for a server while it will be performing async actions and holding the connection open before spitting out prerendered component tree? 
As I see it it doesn't matter, but why then I should use this:
`render(<Router history={history} routes={routes} />, mountNode)`
 when my routes are sync 
and this:

```
match({ history, routes }, (error, redirectLocation, renderProps) => {
  render(<Router {...renderProps} />, mountNode)
})
```

when some of them are async?

**Comment by taurose** [comment]
> So from the client side perspective why does it matter if route is sync or async except for the fact that with async route it will have to wait a little bit for a server while it will be performing async actions and holding the connection open before spitting out prerendered component tree?

When you first call `ReactDOM.render` client-side with html already rendered by the server, React expects the result of  `render` to be exactly the same markup as the one created by the server. With async routes, however, it's impossible to replicate the markup **synchronously within one render call**. Instead, `<Router>` would first render `null` and then update later once everything has loaded. So without the use of `match` you'd run into this error:

> React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server: ...

**Comment by dKab** [comment]
@taurose I think we probably mean different things when saying "async". Are you referring to "code splitting" functionality or **dynamic routes**
https://github.com/ReactTraining/react-router/blob/master/docs/guides/DynamicRouting.md ?

**Comment by taurose** [comment]
Yes, but also async hooks provided by the router ie *onEnter*,

**Comment by dKab** [comment]
Ok, I think I understand now. And If I'm correct this stuff is going to be ditched in v4 (https://github.com/ReactTraining/react-router/issues/4407)? And if I wan smooth transition from v3 to v4 I'm better off with some other mechanism to preLoad data for route component? (Like loading data in componentDidMount lifecycle hook)?

**Comment by taurose** [comment]
Yeah, even though I'm not sure about the current state of v4, I think ditching async stuff is one of the main goals.

`componentDidMount` should work around all that, but then you wouldn't be able to render that data on the server in the first place.

I haven't looked into all the options for async data loading in v4 yet, but I think you could get a smooth transition by using [the routes addon](https://github.com/ReactTraining/react-router-addons-routes#matchroutestolocationroutes-location) to replicate v3 `onEnter` hooks, e.g. using redux with redux-promise

**Comment by dKab** [comment]
>componentDidMount should work around all that, but then you wouldn't be able to render that data on the server in the first place.

I've actually got it covered: I have static methods on component classes which I call before rendering component tree to string.
