### ISSUE TITLE
Can you please migrate to history v4

### ISSUE THREAD

**Issue by cordosvictor** [ReactTraining/react-router#4604]
In history 3.x, when using hashHistory, Router calls LOCATION_CHANGE twice. And as @mjackson said in [hashchange double-fires listeners #427](https://github.com/ReactTraining/history/issues/427), this bug was already fixed.

**Comment by pshrmn** [comment]
As stated in the other issue, someone will need to provide a PR that fixes the issue. It isn't as simple as just changing from v3 to v4 of `history` because they are not API compatible.

**Comment by iyobo** [comment]
And so for the PR:

```
hashHistory.listen( ( evt ) = > {
	console.log('LISTENER:', evt)
});
```
This event handler gets called twice per route visit. But evt is different each time:

```
//log upon visiting /models/Testy

LISTENER: 
{"pathname":"/models/Testy","search":"","hash":"","action":"PUSH","key":"1myy9b","query":{}}

LISTENER: 
{"pathname":"/models/Testy","search":"","hash":"","action":"POP","key":null,"query":{}}

```
It's basically as a result of that annoying evt.key url replacement thing they do in hashHistory.
It just means, when responding to Link clicks for the hashhistory alone(Not sure if browserHistory does that seemingly useless key stuff) , react-router should only act on events with:

`evt.action=== 'PUSH' && evt.key`

**Would there be any other consideration?**
