### ISSUE TITLE
Route doesn't pass props down anymore. Is it intentional?

### ISSUE THREAD

**Issue by ruifortes** [ReactTraining/react-router#4606]
From [v4.0.0-beta.5](https://github.com/ReactTraining/react-router/blob/v4.0.0-beta.5/packages/react-router/modules/Route.js#L110) to [v4.0.0-beta.6](https://github.com/ReactTraining/react-router/blob/v4.0.0-beta.6/packages/react-router/modules/Route.js#L70) router stopped passing down all props. Now just router and match props are passed.
Why so?
And why not pack all route props and methods in a single object instead of spreading them all over the component props?

**Comment by pshrmn** [comment]
Yes. See 45649fd

**Comment by ruifortes** [comment]
I kind of liked the fact that the route was just a kind of "conditional switch" to the child components.
I thing passing props down is very idiomatic react. All state was in the route component
