### ISSUE TITLE
Warning: [react-router] Location "/D:/original/22-02-2017/job2.html" did not match any routes

### ISSUE THREAD

**Issue by hrc7505** [ReactTraining/react-router#4607]
I am working with typescript-with-react. And i m using webpack as a compiler . And my directory structure is as follows:
d:/original/22-02-2017/
      - 
![image](https://cloud.githubusercontent.com/assets/17545364/23393298/e8a6f81c-fda7-11e6-84d7-8bc7853ffbdb.png)

**and my entry point in web.config.js is ./src/index.tsx file.**
**my components placed inside src/components/demo.tsx** 
![image](https://cloud.githubusercontent.com/assets/17545364/23393587/dd16be54-fda9-11e6-950d-f9a82311435e.png)
![image](https://cloud.githubusercontent.com/assets/17545364/23393616/115a131e-fdaa-11e6-99f9-a053e34e8e84.png)

---------------------

and my index.tsx file is as follows

![image](https://cloud.githubusercontent.com/assets/17545364/23393642/3ce61a00-fdaa-11e6-9d1c-251b7d601fd3.png)

------------------
and inside /job2.html i have following links
![image](https://cloud.githubusercontent.com/assets/17545364/23393659/6eb91672-fdaa-11e6-81d5-1849a5d6ff0d.png)

but when i am trying to run program it gives me following error
Warning: [react-router] Location "/D:/original/22-02-2017/job2.html" did not match any routes

and i am not using server port i am just running my app at
file:///D:/original/22-02-2017/job2.html

i have tried many  but not get succeed. please help me what is wrong with my code?

**Comment by pshrmn** [comment]
1. This is an issue tracker, not a support system. Please ask questions at StackOverflow.
2. When you include code in comments on GitHub, it should start and end with lines containing three backticks. When you include unformatted code, most people will just ignore your post.
If you include this text:
\`\`\`
const x = () => { console.log('called x') }
\`\`\`
it will be formatted as:
```
const x = () => { console.log('called x') }
```
3. The actual answer is that `browserHistory` does not work with static sites. You need to use `hashHistory` for that.

**Comment by hrc7505** [comment]
@pshrmn thank you for reply and how i can use it?
