### ISSUE TITLE
Comments in <Switch> are treated as children routes. 4.0.0-beta.3

### ISSUE THREAD

**Issue by shadowfool** [ReactTraining/react-router#4608]
## Version
4.0.0-beta.3 react-router-dom

## Steps to reproduce
```
 <Switch>
    <Route path='/foo' render={ () => <Foo /> } />
    <Route path='/bar' render={ ()=> <Bar/> } />{ /*comment*/}
    <Route path='/baz render={ () => <Baz/> } />
</Switch> 
```
## Expected Behavior
Comment is ignored.
## Actual Behavior
Foo is accessable because it occurs before the error, bar becomes unreachable because of the comment being treated as a route in the switch.
`
Uncaught (in promise) TypeError: Cannot read property 'path' of undefined
    at Switch.render (Switch.js:73)
`

**Comment by mjackson** [comment]
Thanks for the bug report @shadowfool, but it looks like this has been fixed since beta 3. Added a test in https://github.com/ReactTraining/react-router/commit/1612eab638c201dae76d2bb6fffb0171e3d73915 to be sure.
