### ISSUE TITLE
Routes didn't works with parents

### ISSUE THREAD

**Issue by umair-khanzada** [ReactTraining/react-router#4609]
Hi, 
**Routes didn't work with parent route**
I am using  `"react-router": "^3.0.2"`

Didn't work

             <Router history={ browserHistory }>
			<Route path="/" component={ App }>
				<IndexRoute component={ Grid } />
				<Route path="/view/:id" component={ Detail } />
			</Route>
		</Router>

Working Example

             <Router history={ browserHistory }>
			<Route path="/" component={ App } />
			<Route component={ Grid } />
			<Route path="/view/:id" component={ Detail } />
		</Router>

How can i define nested routes ?

**Comment by brianespinosa** [comment]
@umair-khanzada It looks like it has to do with your leading `\` inside path for nested routes. Take a look at the documentation here: https://github.com/ReactTraining/react-router/blob/master/docs/guides/IndexRoutes.md

**Comment by timdorr** [comment]
Correct. The leading slash tells the Route not to nest.

**Comment by umair-khanzada** [comment]
@brianespinosa , @timdorr I am expecting same pattern as `ui-router` because I am from angular background.

Thanks
