### ISSUE TITLE
Unexpected re-rendering when back button is pressed with nested <Switch> components

### ISSUE THREAD

**Issue by marcgreenstock** [ReactTraining/react-router#4611]
## Version
4.0.0-beta.6

## Test Case
I've put up a example repo to demonstrate this bug.

https://github.com/marcgreenstock/react-router-nested-switch-bug-example

## Steps to reproduce
Nest a `<Switch>` as a child route component and press back.
See https://github.com/marcgreenstock/react-router-nested-switch-bug-example/blob/master/src/entry.js for a full example

## Expected Behavior
The history -1 route should be the only component rendered.

## Actual Behavior
When the back button is pressed, the parent route component and current route component is re-rendered twice.

**Comment by pshrmn** [comment]
Have you tested this with the current v4 branch? There was a re-rendering issue discussed in #4578 that was fixed in #4592. I'm not positive, but this sounds like it might be the same issue.

**Comment by marcgreenstock** [comment]
@pshrmn Ahh that looks like the problem, but I am having trouble testing against the v4 branch. Is there an easy way to package the branch into my project?

Extract from `package.json`:

```JSON
{
  "dependencies": {
    "react-router": "git://github.com/ReactTraining/react-router.git#v4"
  }
}
```

**Comment by pshrmn** [comment]
Git install isn't supported (not sure of the exact reason, just parroting what I've read). The only way that I have done that in the past is is with `npm link`.
```
npm clone git://github.com/ReactTraining/react-router.git
npm install
cd packages/react-router
npm link
cd ../react-router-dom
npm link
```
And then in your project:
```
npm link react-router
npm link react-router-dom
```

If you test that and it is still broken, please re-open this issue, but for the time being I'm going to close this.

**Comment by marcgreenstock** [comment]
Great thanks. Confirmed duplicate of #4578

**Comment by skystebnicki** [comment]
Any chance we could get this into an alpha or beta release on npm? We have run into this problem and it would be great to be able to install it with npm.
