### ISSUE TITLE
Make readme link to v2 docs

### ISSUE THREAD

**Issue by morenoh149** [ReactTraining/react-router#4613]
Current readme links to 0.13 and 1.0 docs. RR current version being v3, should link to the v2 docs in the `Older Versions` section of the readme.

**Comment by timdorr** [comment]
2.x is just 3.x with deprecation warnings (which were removed in 3.0). There are no API changes, so linking to that version isn't that helpful.

**Comment by morenoh149** [comment]
not interest in noting that for folks that do not know that? major version changes presume breaking api changes so it's not obvious v2 and v3 api's are the same.

**Comment by timdorr** [comment]
Sure, that could be useful. Submit a PR so I can merge that in.
