### ISSUE TITLE
v4 beta docs site broken in production

### ISSUE THREAD

**Issue by elliottkember** [ReactTraining/react-router#4614]
Hey guys,

I found a bug on the site. I'm having trouble figuring it out myself, but the error appears to be that `canGo` is not a function in `FakeBrowser.render`. In fact all the props but `location` are `undefined`. 

https://github.com/ReactTraining/react-router/blob/v4/packages/react-router-website/modules/components/FakeBrowser/index.js#L64

So possibly Route.js needs `const { canGo, goBack, go, goForward } = history` and those added to the props variable. I tried editing it locally but it wouldn't recompile or reload my code so I can't test it. 

## Version
4

## Test Case
https://reacttraining.com/react-router/

## Steps to reproduce
Site shows "." for the fake browser code tester and this error:
```
index.js:81 Uncaught TypeError: canGo is not a function
    at render (index.js:81)
    at Route.render (Route.js:91)
```

**Comment by tylermcginnis** [comment]
Fixed! Sorry about that. I broke it earlier when I rebuilt our home site without realizing it would break the router site.

**Comment by ryross** [comment]
@tylermcginnis The docs are down again for me. I see a loading screen forever and a JS error:

```
Uncaught TypeError: Cannot set property '_key' of null
    at r (main.js:4)
    at main.js:31
```

**Comment by timdorr** [comment]
@ryross Do a hard refresh (hold shift) and you'll see a coming soon page. It looks like the last build is stuck in cache.
