### ISSUE TITLE
React router v4 Dynamic Routing

### ISSUE THREAD

**Issue by awpsawps12** [ReactTraining/react-router#4616]
In the documentation of v3 version, there are 3 methods `getChildRoutes`,  `getIndexRoute`, and `getComponents` to achieve dynamic routing, but i saw that in the v4 version, it hasn't mention the three methods above. I wonder if there are any method in v4 version to achieve dynamic routing.

thanks.

**Comment by timdorr** [comment]
Check out #4407 that is related to this. We don't solve these issues for you anymore. You can do all of that in vanilla React.
