### ISSUE TITLE
Webjar at web format

### ISSUE THREAD

**Issue by OrbX** [ReactTraining/react-router#4618]
Hello, 
I'm looking for the last version of react-router as a webjar in "web format" with the minimum of dependencies.
Could you help me ?

Best regards

**Comment by timdorr** [comment]
We have never package the library in that format. If anyone did that, it would be a 3rd party effort we don't know about. Sorry!

**Comment by ghostd** [comment]
I confirm, the packging is done by a 3rd party.

@OrbX you can use the official site to make search: http://www.webjars.org/
The maven artedfactId seems to be : "org.webjars.npm" % "react-router" % "4.0.0-2"
