### ISSUE TITLE
[v4] Redirect always rendered, even if `from` prop provided.

### ISSUE THREAD

**Issue by Andreyco** [ReactTraining/react-router#4619]
## Version
4.0.0-beta.6

## Steps to reproduce
**1.** Minimal required setup
```js
function Place() {
  return <div>Place</div>
}

function AppRouter() {
  return (
    <Switch>
      <Redirect from='/old-path' to='/new-path'/>
      <Route path='/new-path' component={Place}/>
    </Switch>
  )
}
```

**2.** Navigate to `/old-path`

## Expected Behavior
Redirect from `/old-path` to `/new-path`, get `Place` component rendered.

## Actual Behavior
Redirected from `/old-path` to `/new-path`, nothing gets rendered (or `Redirect` gets rendered instead)

**Comment by pshrmn** [comment]
@Andreyco `<Redirect from>` was added after the beta 6 release.

**Comment by Andreyco** [comment]
Feel free to close, or I will when there is new released published. TY for info ✌️
