### ISSUE TITLE
Cannot pass props from <Route> to rendered `component`

### ISSUE THREAD

**Issue by Noitidart** [ReactTraining/react-router#4627]
## Version
4.0.0-beta.7

## Test Case
----

## Steps to reproduce
Render `<Route path="/" component={PageContent} pass_to_page_content="hi" exact/>`

## Expected Behavior
I expect that in `this.props` in `PageContent` I should have `pass_to_page_content`, however it is not there. In <= 4.0.0-beta.6 this worked.

## Actual Behavior
The `this.props` of `PageContent` only has `location` and `history`. It does not get `pass_to_page_content`.

Was I using `<Route>` wrong?

**Comment by pshrmn** [comment]
This was intentional. See the [comments where this change was made](https://github.com/ReactTraining/react-router/commit/45649fd3cc6fbe4c5b89c3d0506f8f076c3fa6ed#commitcomment-20902957).

If you need to pass props, use `render`.

```js
<Route exact path='/' render={(props) => (
  <PageContent {...props} pass_to_page_content='hi' />
)}/>
```

**Comment by omedale** [comment]
God bless you @pshrmn  for that snippet

**Comment by anthonydelgado** [comment]
` <Route exact path="/profile" render={(props) => (
                    <Profile user={this.props.user}/>
                )} />
`

Here is what I ended up using

**Comment by DavidNorena** [comment]
<Route exact path='/auth/login' render={(props) => <Login {...this.props} /> } />

Is there a way to pass automagically parent props to my route component ?

**Comment by anthonydelgado** [comment]
@DavidNorena i would look into using Redux .... that is the direction I am going in now with my project to accomplish "Global Props" if you will. He is the course I am taking from @StephenGrider 
https://www.udemy.com/react-redux/learn/v4/overview

**Comment by iyk-azorji** [comment]
You could make use of Higher Order Components to wrap the component to be rendered and pass the props as an argument. This would make your code cleaner and more re-usable.

For example

`const AddPropsToRoute = (WrappedComponent, passedProps)=>{
    return (
        class Route extends Component{
            render(){
                let props = Object.assign({}, this.props, passedProps)
                return  <WrappedComponent {...props} />
            }
        }
    )
}

export default AddPropsToRoute`

Then you pass the component as so

`<Route path={`${match.path}/:id`} component={AddPropsToRoute(EditUsers, passingProps)} />`

**Comment by iyk-azorji** [comment]
You could make use of Higher Order Components to wrap the component to be passed, and pass the props as an argument. This would make the code alot cleaner and more reusable. 

For example

```JSX

const AddPropsToRoute = (WrappedComponent, passedProps)=>{
    return (
        class Route extends Component{
            render(){
                let props = Object.assign({}, this.props, passedProps)
                return  <WrappedComponent {...props} />
            }
        }
    )
}

export default AddPropsToRoute

```
Then you can just use it as so:

```JSX

let passingProps = {
        userName: 'uche'
    }

<Route path={`${match.path}/:id`} component={AddPropsToRoute(Users, passingProps)} />
```
Where `Users` is the component being passed.

**Comment by GonzaloCBenlloch** [comment]
I made a really simple mom package for that! You can check it here: https://www.npmjs.com/package/react-router-with-props

I hope it helps

**Comment by pieplu** [comment]
Nice package @GonzaloCBenlloch ! light and useful!

**Comment by ifeanyidavid** [comment]
@pshrmn Thanks soo much. Spent hours trying to fix this.

@iyk-azorji Really clean and reusable. Nice.
