### ISSUE TITLE
React Router 4.beta.7 Route content not changing inside HOC'd component

### ISSUE THREAD

**Issue by rclai** [ReactTraining/react-router#4634]
I've tried this with Redux and MobX's HOC functions `connect` and `observable`.

Here's a `create-react-app` [repro](https://github.com/rclai/react-router-4-issue).

If you remove the `connect` from the `App` component, the route content will start changing when you click the links.

Does it have something to do with [this](https://github.com/ReactTraining/react-router/blob/b7357d19d545b4e3896ab2d817b0e1673f85c850/packages/react-router/modules/Route.js#L54)?

**Comment by pshrmn** [comment]
`connect` uses `shouldComponentUpdate` to block updates when its props have not changed. Obviously, you want your component to update, so you will need to have `shouldComponentUpdate` return `true`. There are two ways that you can do this:

1. Pass the `location` as a prop to connected components
2. Make `connect` non-pure (the fourth argument of `connect` is an options object where you can set `{ pure: false }`).

```js
const MyConnectedComponent = connect(mapStateToProps)(MyComponent)
<MyConnectedComponent location={location} />

// or

const MyImpureComponent = connect(
  mapStateToProps,
  mapDispatchToProps,
  mergeProps,
  { pure: false }
)(MyComponent)
```

**Comment by wmertens** [comment]
See also #4629

**Comment by rclai** [comment]
@pshrmn thanks, that takes care of Redux but what about MobX?

**Comment by pshrmn** [comment]
`observer` does a [shallow check](https://github.com/mobxjs/mobx-react/blob/master/src/observer.js#L239) of the next props, so passing the `location` should work there. If you have a project that you could verify that in, I would appreciate it.

**Comment by rclai** [comment]
@pshrmn instead of passing `location`, I simply just used `@withRouter` and that worked. I think it's cleaner.

**Comment by wmertens** [comment]
@rclai that is odd, `@withRouter` only injects the router context, it does not subscribe to history events, so I am surprised that works?

**Comment by rclai** [comment]
That's [v3's `withRouter`](https://github.com/ReactTraining/react-router/blob/c865bc6b331eabd853641dcc7e0224a7dce76f3b/modules/withRouter.js), I think [v4's `withRouter`](https://github.com/ReactTraining/react-router/blob/b7357d19d545b4e3896ab2d817b0e1673f85c850/packages/react-router/modules/withRouter.js) operates with props.

**Comment by rclai** [comment]
I also noticed that `withRouter` has to be the outer function, otherwise it won't work, for example

```
@withRouter
@connect
class MyComponent extends React.Component {}
```

not

```
@connect
@withRouter
class MyComponent extends React.Component {}
```

**Comment by pshrmn** [comment]
In the former, `withRouter` is passing the new `location` to the connected component, so `sCU` sees that the props are different and updates. In the latter, `withRouter` will not render (and pass the new `location`) unless `sCU` returns `true`.

**Comment by rclai** [comment]
@pshrmn, can I get your blessing on whether to use `withRouter` to circumvent this issue?

**Comment by pshrmn** [comment]
Any approach that passes new props to the connected component upon navigation should work. If you don't already have access to the `location` prop in whichever component renders the connected component, then I think that `withRouter` is a convenient mechanism for doing that.

That said, there is an issue with `withRouter` right now where the `match` prop it provides to the wrapped component is probably not what you want, so if you rely on that, I would not use it.
