### ISSUE TITLE
some questions about "<link />"

### ISSUE THREAD

**Issue by sayyllg** [ReactTraining/react-router#4636]
when i use "/</link />/" for changing the router, function "compontentDidUpdate" will be called every time; But i know function "compontentDidUpdate" can not be triggered for the first time.
Is this a problem?

**Comment by pshrmn** [comment]
I'm not really sure what you're asking. `componentDidMount` has an equivalent lifecycle method `componentDidMount` that you can call when the component is initially rendered.
