### ISSUE TITLE
[RR4] StaticRouter Example on website not working

### ISSUE THREAD

**Issue by OllieJennings** [ReactTraining/react-router#4637]
[Link](https://reacttraining.com/react-router/#staticrouter)

In the StaticRouter documentation you have the following line:

`import { StaticRouter } from 'react-router'`

This does not work, instead the line should be:

`import { StaticRouter } from 'react-router-dom'`

I can submit a pull request if you would like for this

**Comment by pshrmn** [comment]
`<StaticRouter>` is [exported by `react-router`](https://github.com/ReactTraining/react-router/blob/v4/packages/react-router/modules/index.js#L6). Can you get into any more detail about why this does not work for you?

**Comment by OllieJennings** [comment]
Sure, so when l use the exported one by React-Router l get the error:

```
Warning: React.createElement: type is invalid -- expected a string or class/function but got undefined
Invariant Violation: Element type is invalid etc
```

**Comment by pshrmn** [comment]
I just tried with the UMD builds of both `react-router` and `react-router-dom` and both appeared to work for me. [codepen](http://codepen.io/pshrmn/pen/LWZoOJ)

**Comment by OllieJennings** [comment]
Interesting, this is the exact error code am getting when using just:

`import { StaticRouter } from 'react-router'`

```
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component f
rom the file it's defined in.
Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from
 the file it's defined in.
    at invariant (/Users/olliejennings/Code/xyz/apollo-cli-test/node_modules/fbjs/lib/invariant.js:44:15)
    at instantiateReactComponent (/Users/olliejennings/Code/xyz/apollo-cli-test/node_modules/react-dom/lib/instantiateReactComponent.js:77:56)
    at /Users/olliejennings/Code/xyz/apollo-cli-test/node_modules/react-dom/lib/ReactServerRendering.js:44:31
    at ReactServerRenderingTransaction.perform (/Users/olliejennings/Code/xyz/apollo-cli-test/node_modules/react-dom/lib/Transaction.js:140:20)
    at renderToStringImpl (/Users/olliejennings/Code/xyz/apollo-cli-test/node_modules/react-dom/lib/ReactServerRendering.js:43:24)
    at renderToString (/Users/olliejennings/Code/xyz/apollo-cli-test/node_modules/react-dom/lib/ReactServerRendering.js:73:10)
    at /Users/olliejennings/Code/xyz/apollo-cli-test/rr4-src/server.js:23:15
    at Layer.handle [as handle_request] (/Users/olliejennings/Code/xyz/apollo-cli-test/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/olliejennings/Code/xyz/apollo-cli-test/node_modules/express/lib/router/index.js:317:13)
    at /Users/olliejennings/Code/xyz/apollo-cli-test/node_modules/express/lib/router/index.js:284:7
```

**Comment by pshrmn** [comment]
Can you do a fresh install just to verify that there is nothing out of sync with any of the `react-router` files? It really doesn't make sense that `react-router` would not work when `react-router-dom` does because `react-router-dom` just imports `<StaticRouter>` from 'react-router`.

One possible situation is that if you also have an earlier version (2/3) of `react-router` accidentally installed.

**Comment by OllieJennings** [comment]
Will do

**Comment by OllieJennings** [comment]
@pshrmn Same issue again with a fresh install, my package details are:

```
"react-router": "^3.0.2",
"react-router-dom": "^4.0.0-beta.6"
```

Error is:

```
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in.
```

**Comment by pshrmn** [comment]
`react-router": "^3.0.2"` This should be v4
