### ISSUE TITLE
importing browserHistory differently than declaring it in <Router history={browserHistory /> doesn't work properly

### ISSUE THREAD

**Issue by brotzky** [ReactTraining/react-router#4640]
## Version
3.0.2

## Steps to reproduce
If you're importing `browserHistory` differently than how you declare it in your `Router history={browserHistory}` it will not work properly. I'm not sure if this is intended, but it caused me a few headaches. I've created some examples to help demonstrate. The URL pathname gets updated but the components don't.

Examples
```JavaScript
// App.js

import React from 'react';
import { Provider } from 'react-redux';
import { Router, browserHistory } from 'react-router'; // notice I'm importing from 'react-router'
import routes from '../../../routes';

export default function App(props) {
  return (
    <Provider store={props.store}>
        <Router history={browserHistory} routes={routes} />
    </Provider>
  );
}
```

Working case:
```JavaScript
// Button.js

import React from 'react';
import { browserHistory } from 'react-router'; // importing from 'react-router'

function handelClick() {
  // this works. path updates and renders new component
  browserHistory.push('/my/path/name');
}

const Button = () => <button onClick={handleClick}>Update Route</button>;
```

Broken case:
```JavaScript
// Button.js

import React from 'react';
import browserHistory from 'react-router/lib/browserHistory'; // <-- NOT from 'react-router' like in App.js Router

function handelClick() {
  // this DOES NOT work, only URL pathname is updated correctly.
  browserHistory.push('/my/path/name');
}

const Button = () => <button onClick={handleClick}>Update Route</button>;
```

---
✅
```JavaScript
import { Router, browserHistory } from 'react-router';
+
import { browserHistory } from 'react-router';
```
---
✅
```JavaScript
import { Router } from 'react-router';
import browserHistory from 'react-router/lib/browserHistory';
+
import browserHistory from 'react-router/lib/browserHistory';
```
---
🙅
```JavaScript
import { Router } from 'react-router';
import browserHistory from 'react-router/lib/browserHistory';
+
import { browserHistory } from 'react-router';
```
---
🙅
```JavaScript
import { Router, browserHistory  } from 'react-router';
+
import browserHistory from 'react-router/lib/browserHistory';
```

## Expected Behavior
It doesn't matter how I'm importing browserHistory. I assumed both methods would work

## Actual Behavior
You have to import browserHistory in the same fashion as you declare it in the history

**Comment by timdorr** [comment]
The package import is just [re-exporting that module](https://github.com/ReactTraining/react-router/blob/master/modules/index.js#L23). If you're using a module-aware bundler (such as webpack 2) that could be causing some sort of problem, but that's a webpack issue and you might need to either import from `react-router/es/browserHistory` (the un-transformed version) or configure your transpiler differently.

**Comment by brotzky** [comment]
thanks for the clarification, @timdorr.
