### ISSUE TITLE
The context router undefined

### ISSUE THREAD

**Issue by expdevelop** [ReactTraining/react-router#4645]
Hey guys, I need your help!

Everything was good until the moment when I decided to remove `node_modules` folder and redownload it by `npm install`.

So, now I got the error in every component where I used context `router`, for example `CatalogFilterContainer` ->:

```
Warning: Failed context type: The context `router` is marked as required in `CatalogFilterContainer`, but its value is `undefined`.
    in CatalogFilterContainer (created by Connect(CatalogFilterContainer))
    in Connect(CatalogFilterContainer) (created by CatalogPage)
    in div (created by Container)
    in Container (created by CatalogPage)
    in CatalogPage (created by Connect(CatalogPage))
    in Connect(CatalogPage) (created by Route)
    in Route (created by render)
    in Switch (created by render)
    in render (created by Route)
    in Route (created by RouteNotify)
    in RouteNotify (created by Connect(RouteNotify))
    in Connect(RouteNotify) (created by App)
    in Switch (created by PagesTransitions)
    in div (created by PagesTransitions)
    in PagesTransitions (created by Connect(PagesTransitions))
    in Connect(PagesTransitions) (created by App)
    in div (created by App)
    in Router (created by BrowserRouter)
    in BrowserRouter (created by App)
    in App (created by Connect(App))
    in Connect(App)
    in Provider
    in AppContainer
```

In `CatalogFilterContainer` ->
```js
export default class CatalogFilterContainer extends Component {
  static contextTypes = {
    router: PropTypes.object.isRequired
  };
```

Project is here - https://github.com/expdevelop/ultrastore
First of all install dependencies by `npm install` and run `npm run dev`. Then go to (for example) `localhost:5000/catalog/phones`.

Router version ->
```js
"react-router-dom": "^4.0.0-beta.7"
```

**Comment by expdevelop** [comment]
Are you just changed `context.router` to `context.history`?

**Comment by expdevelop** [comment]
Was trying to downgrade to `4.0.0-beta.6` and got this ->
```
Warning: Failed context type: The context `router` is marked as required in `Link`, but its value is `undefined`.
    in Link (created by Route)
    in Route (created by NavLink)
    in NavLink (created by Text)
    in Text (created by Link)
    in Link (created by NavLinks)
    in div (created by FlexGrid)
    in FlexGrid (created by NavLinks)
    in NavLinks (created by NavDesktop)
    in div (created by FlexGrid)
    in FlexGrid (created by NavDesktop)
    in div (created by Container)
    in Container (created by NavDesktop)
    in nav (created by NavDesktop)
    in NavDesktop (created by NavContainer)
    in NavContainer (created by Connect(NavContainer))
    in Connect(NavContainer) (created by Route)
    in Route (created by App)
    in div (created by App)
    in Router (created by BrowserRouter)
    in BrowserRouter (created by App)
    in App (created by Connect(App))
    in Connect(App)
    in Provider
    in AppContainer
```

**Comment by seanchas** [comment]
@expdevelop That's because `react-router` still at `4.0.0-beta.7`, after you downgrade.
Having same errors, and since `v4` branch is private cannot look into it.

**Comment by expdevelop** [comment]
Solved!

package.json ->
```json
"react-router": "4.0.0-beta.6",
"react-router-dom": "4.0.0-beta.6",
```

**Comment by florimm** [comment]
I have same issue when i run test and use enzyme (mount) also with =>
```
"react-router": "4.0.0-beta.6",
"react-router-dom": "4.0.0-beta.6",
```

**Comment by natashache** [comment]
Tried the steps of @vyushenko. Still get the same error "Failed context type: The context `router` is marked as required in `Link`, but its value is `undefined`" :(

**Comment by JimiHFord** [comment]
@natashache see @mjackson's comment in #4759

**Comment by ha404** [comment]
I get this error when trying to map `Link`, is this related?

```js
map(([key, idea]) => (
  <Link
    key={key}
    to={`/idea/${key}`}
  >
    <Idea
      votes={idea.votes}
      title={idea.title}
    />
  </Link>
))
```

**Comment by ali-master** [comment]
Your class also needs @expdevelop 

```javascript
  contextTypes: {
    router: PropTypes.object
  },
```

Before use it, you should be install prop-types package for use this in React v15.5.x,

**Comment by scifutures** [comment]
This can happen if you do not wrap <Link /> with a <BrowserRouter> at a parent level.

**Comment by bkou** [comment]
Spent all day trying to figure this out for project 1 of Udacity's React nanodegree. BrowserRouter, which iirc was never mentioned in the course, was the answer. It needed to be included in index.js. Thanks @scifutures 

Phrases for searchability:
TypeError: _ref2 is undefined
function computeMatch(_ref, _ref2)
var route = _ref2.route
TypeError: this.context.router is undefined
_this.context.router
Warning: Failed context type: The context `router` is marked as required in `Link`, but its value is `undefined`
MyReads: A Book Tracking App
React Fundamentals
