### ISSUE TITLE
what's the diff between `react-router-dom` & `react-router`?

### ISSUE THREAD

**Issue by xgqfrms-GitHub** [ReactTraining/react-router#4648]
https://github.com/ReactTraining/react-router
```sh
$ npm install --save react-router

// using an ES6 transpiler, like babel
import { Router, Route, Link } from 'react-router'
``` 
https://reacttraining.com/react-router/

```
npm install react-router-dom@next
# or
yarn add react-router-dom@next

import {
  BrowserRouter as Router,
  StaticRouter, // for server rendering
  Route,
  Link
  // etc.
} from 'react-router-dom'

```

**Comment by pshrmn** [comment]
Your first link is to the master branch, which at this time is v3.

In v4, `react-router` exports the core components and functions. `react-router-dom` exports DOM-aware components, like `<Link>` (which renders an `<a>`) and `<BrowserRouter>` (which interacts with the browser's `window.history` ).

`react-router-dom` re-exports all of `react-router`'s exports, so you only need to import from `react-router-dom` in your project.

**Comment by xgqfrms-GitHub** [comment]
Thanks a lot! 😄

**Comment by mech** [comment]
So in the future, which is now where RR4 is released, which one shall we use for Web development only? Do we just do "yarn add react-router" will do?

**Comment by timdorr** [comment]
You'll use the bindings for your environment. You will probably want to use react-router-dom for 99.9% of web dev.

**Comment by MarcoMatta** [comment]
@pshrmn, thanks !

**Comment by apeg1515** [comment]
Thanks Guys!!!  @timdorr

**Comment by ClarenceC** [comment]
thank u ! @timdorr  I have confused before.

**Comment by Mcebrera** [comment]
This helped alot, thanks!

**Comment by AndrewRayCode** [comment]
@pshrmn repurposed your answer into documentation ^^^ I think this issue should be re-opened until the documentation is addressed, obviously lots of people have hit this.

**Comment by japrogramer** [comment]
hello im new to to react and js, Im building a front end for an API I have built and want to create one codebase for web and native. 

currently im using react-native-web and react-router-dom .. It is my understanding that they have native versions with different entry points. How than do this components get switch for the native components in other files? I guess what I really want is a guide on how to build for mobile and web with this technologies from one codebase, It is my understanding that this is what this libraries are for but i have yet too find such a tutorial or guide.

**Comment by arunrajnov3** [comment]
If I refresh in react-router-dom v4.x. It shows error like 'Cannot GET /address' .Can someone tell me how to solve that?
