### ISSUE TITLE
match params not being passed down to component wrapped by `withRouter`.

### ISSUE THREAD

**Issue by indiesquidge** [ReactTraining/react-router#4649]
_This is an official bug report that was originally part of the discussion on #4630. That issue was not opened to discuss re-rendering issues with `withRouter`, whereas this is to discuss issues with the `match` object not being passed down properly._

## Version
react-router-dom@4.0.0-beta.7
react-router@4.0.0-beta.7

## Test Case
http://codepen.io/indiesquidge/pen/KWgoNX

## Steps to reproduce
(See codepen link above)

## Expected Behavior

`match` params should be passed down to components wrapped by `withRouter`

## Actual Behavior

`match` params not being passed down to components wrapped by `withRouter`

It seems like [this change](https://github.com/ReactTraining/react-router/commit/1f0107986f98b38e175819fb0eca77c42c18b6bb#diff-524339bd092db50934a0c59a2df5d83dR3) was explicitly stating that only the closest `<Route>`'s `match` would be available when using `withRouter`, but it doesn't state that a pathless `<Route>` will (or should) inherit `match` from its parent in order to get access to, say, `match.params`. Should it say that?

**Comment by pshrmn** [comment]
Fixed by 394eb09

**Comment by DavidSvetlik** [comment]
I am running v 4.2.2, have some parent component wrapped in withRouter and while "this.props.location" tells me that pathname is "/users/8", "this.props.match.params" is an empty object. There should be "userId" with value 8.

Am I doing something wrong or...?
