### ISSUE TITLE
context.route conflicts with Relay's context.route

### ISSUE THREAD

**Issue by seanchas** [ReactTraining/react-router#4650]
Since `4.0.0-beta.7` there is `route` context variable which is overrided by `react-relay` context variable with same name.

**Comment by timdorr** [comment]
Oh fun 😞 

Maybe we should just put everything under `context.router` again?

**Comment by seanchas** [comment]
@timdorr I've just patched `context.route` into `context.react_router_route` in my `node_modules`.
This can be a solution :)

**Comment by spicydonuts** [comment]
Library-specific namespaces like `context.react_router` seems like a good idea, since they're generally only accessed by components and functions in that same library.

**Comment by ryanflorence** [comment]
yeah, I'd say lets do:

```
router: shape({
  history: object,
  route: object
})
```

**Comment by ryanflorence** [comment]
just talked to @mjackson and we're on the same page, anybody want to do the footwork there to put everything back on one namespace `router` as shown 👆

**Comment by JulienPradet** [comment]
I'd be glad to give a hand at grouping the context.

I'll send a PR this evening (European time).

**Comment by donaldpipowitch** [comment]
I wonder if we could use a Symbol here 🤔 

```
const routerSymbol = Symbol('react-router');

// ...

[routerSymbol]: shape({
  history: object,
  route: object
})

// ...

context[routerSymbol]
```

**Comment by mjackson** [comment]
@seanchas Now you have to go and open an issue on relay saying "hey, you guys should put everything on `context.relay`" :P 

@donaldpipowitch That's not a bad idea. At least then nobody could conflict with us. I wonder how babel shims `Symbol` for older runtimes...

**Comment by pshrmn** [comment]
@mjackson I don't think that will work because `for ... in` (what React uses to iterate over the `contextTypes`) doesn't work for symbols.

**Comment by pshrmn** [comment]
Actually, that is just for warnings. The actual merging just uses `Object.assign`.

**Comment by mjackson** [comment]
OK, after #4659 everything is grouped back under `context.router`, so we can close this.

For future reference, I think it's a good idea for everyone using `context` to either:

- Group everything under your npm package name (w/out the `react-` prefix, like we're doing) or
- Use a `Symbol` as @donaldpipowitch suggests

The latter seems like a more bullet-proof suggestion, but also requires us to provide something like `withRouter` so everyone can get access to our stuff.
