### ISSUE TITLE
Undefined function matchPath, question or bug

### ISSUE THREAD

**Issue by mymtwcom** [ReactTraining/react-router#4651]
## Version
^3.0.2

## Test Case
https://gist.github.com/kandros/ad9ff7b59282de02d6df4bdb8db39458#file-data-js-L64

## Steps to reproduce
I'm trying to reproduce next example as in this gist:
https://gist.github.com/kandros/ad9ff7b59282de02d6df4bdb8db39458#file-data-js-L64

## Expected Behavior
I expected that this function will return string with url of my component or `false`
## Actual Behavior
TypeError: (0 , _reactRouter.matchPath) is not a function
    at pathtomyproject/here/server.js:90:5
    at Array.reduce (native)

Also type of this function is undefined

**Comment by timdorr** [comment]
That gist is for 4.0. You're using 3.0, which has a totally different API.

**Comment by mymtwcom** [comment]
@timdorr are there exists any decision for 3.0? I want to implement the same rendering, but don't know how
