### ISSUE TITLE
non-strict dependencies between packages

### ISSUE THREAD

**Issue by frux** [ReactTraining/react-router#4656]
I think it's a bad idea to set [non-strict dependencies](https://github.com/ReactTraining/react-router/blob/v4/packages/react-router-dom/package.json#L45) between your packages. I used ``react-router-dom: "4.0.0-beta.4"`` since you've broken ``react-router@4.0.0-alpha.4``. And now my ``react-router-dom: "4.0.0-beta.4"`` installed ``react-router: "4.0.0-beta.6"`` so I've got an error.

**Comment by timdorr** [comment]
Yep, we should be doing this. A PR for this would be great (and really easy)!

Is this perhaps something Lerna can manage for us? I'll open up an issue over there to discuss.

**Comment by timdorr** [comment]
Ah wait, I think Lerna does do this. Maybe.

@mjackson Did you do 83f3459 with just `lerna publish` or was that by hand?

**Comment by mjackson** [comment]
`lerna` automatically manages the dependency versions for us and uses the `^`. I'm going to revert 59513c9caeb31779d0d335560b254c18488771f9

**Comment by timdorr** [comment]
But you see why that's a problem, right?

**Comment by mjackson** [comment]
Yes, there's just not much we can do about it w/out altering lerna (unless there's some lerna flag I'm missing...). In the next release, the `^` is going to be back anyway.

**Comment by YasserKaddour** [comment]
@mjackson  I think the flag you're looking for is `--exact`

From the lerna doc
>  `$ lerna publish --exact`
> When run with this flag, publish will specify updated dependencies in updated packages exactly (with no punctuation), instead of as semver compatible (with a ^).

**Comment by timdorr** [comment]
Oh thank you! That's exactly what I was looking for.

**Comment by YasserKaddour** [comment]
Be aware that flag was introduced in `v2.0.0-beta.33`, I would have made a PR to upgrade lerna, but I saw that @mjackson reverted to `v2.0.0-beta.32` for some reason.
