### ISSUE TITLE
Doc enhancement for

### ISSUE THREAD

**Issue by donaldpipowitch** [ReactTraining/react-router#4658]
Taken from [here](https://github.com/ReactTraining/react-router/blob/v4/packages/react-router/docs/api/Route.md#component-func).

> When you use component (instead of render, below) the router uses React.createElement to create a new React element from the given component. That means if you provide an inline function you will get a lot of **undesired** remounting. For inline rendering, use the render prop (below).

Could you explain _why_ this is probably undesired? Just one or two additional sentences - not more. When we switched from beta.6 to beta.7 several of our components behaved unexpected. It looks like we _needed_ remounting so it looks like we need to rewrite our `render` to `component`.

E.g. we use a lazy loading component for code splitting like [this](https://gist.github.com/donaldpipowitch/9fce086e7201477751fd00cf1766037e#file-index-tsx-L14) which fetches a module inside [`componentDidMount`](https://gist.github.com/donaldpipowitch/9fce086e7201477751fd00cf1766037e#file-lazy-tsx-L54).

**Comment by timdorr** [comment]
You're creating a new anonymous function on every render of that `<Route>`. Therefore React is going to recreate and mount the new instance of that function every time it needs to render the route. 

As for your components not working correctly, it's likely because of shouldComponentUpdate usage (in your case, via mobx). This guide was written to describe the problem and help fix it: https://github.com/ReactTraining/react-router/blob/v4/packages/react-router/docs/guides/blocked-updates.md

**Comment by donaldpipowitch** [comment]
Thanks for the feedback. I know MobX and `shouldComponentUpdate` is the "problem" here, but I didn't know that there is already a recommended solution with [`blocked-updates.md`](https://github.com/ReactTraining/react-router/blob/v4/packages/react-router/docs/guides/blocked-updates.md).

Anyway my original question was more about _why_ should I use `<Route component>`? The docs explain really good _what_ happens when you use `<Route component>`,  `<Route render>` and `<Route children>`, but for `<Route component>` there is only the description that it has undesired remounting - there is no explanation _when_ `<Route component>` should be used. (I guess there must be a use case or it wouldn't be included at all. 😃 ) (E.g. `<Route children>` has a small use case explanation that it could be useful for animations.)

**Comment by pshrmn** [comment]
You cannot do this:
```js
class MyComponent extends React.Component {
  render() {
    <div>This is my component</div>
  }
}

<Route render={MyComponent} />
```

**Comment by donaldpipowitch** [comment]
> Anyway my original question was more about why should I use <Route component>?

Given https://github.com/ReactTraining/react-router/issues/4661 is the use case _if you need side-effects in mount-related lifecycle hooks_?
