### ISSUE TITLE
Possible bug with <Switch/> in beta.7?

### ISSUE THREAD

**Issue by donaldpipowitch** [ReactTraining/react-router#4661]
## Version

4.0.0-beta.7

## Test Case

I use webpack and react-router for code splitting and lazy loading parts of my page. My component to lazy load looks [like this](https://gist.github.com/donaldpipowitch/9fce086e7201477751fd00cf1766037e#file-lazy-tsx).

And I use it like this:

```
// this is our single page application
import React from 'react';
import { render } from 'react-dom';
import { Router, Route, Switch} from 'react-router-dom';
import { Lazy } from 'react-lazy';  // package defined above
import { createHashHistory } from 'history';
//import { App } from './App'; // our app component - now loaded lazily!

const hashHistory = createHashHistory();

render(
  <Router history={hashHistory}>
    <Switch>
      <Route exact path="/" render={() => <Lazy fetch={() => _import('./App')} />} />
      {/* other routes */}
    </Switch>
  </Router>,
  document.getElementById('app')
);
```

This worked in beta.6 and it works in beta.7 without `<Switch/>` around my `<Route/>`'s. I thought it was a problem with [`blocked-updates.md`](https://github.com/ReactTraining/react-router/blob/v4/packages/react-router/docs/guides/blocked-updates.md), because only the _first_ route which lazy loads a component is displayed correctly. Navigation through my app doesn't update correctly. But the `render` method of my `<Lazy/>` component is always called correctly and no matter how I _force_ updating with passing `location` through props, it doesn't work (because `render` is called anyway...). It looks more like `<Switch/>` doesn't display the the newly rendered part.

Strange enough... it works when I use `<Lazy/>` just _once_:

```
      <Switch>
        <Route
          path="/foo"
          render={() => <Lazy fetch={() => _import('./foo')} />}
        />
        <Route
          path="/bar"
          render={() => <p>Bar</p>}
        />
      </Switch>
``` 

And it of course it works without it:

```
      <Switch>
        <Route
          path="/foo"
          render={() => <p>Foo</p>}
        />
        <Route
          path="/bar"
          render={() => <p>Bar</p>}
        />
      </Switch>
``` 

But this fails:

```
      <Switch>
        <Route
          path="/foo"
          render={() => <Lazy fetch={() => _import('./foo')} />}
        />
        <Route
          path="/bar"
          render={() => <Lazy fetch={() => _import('./bar')} />}
        />
      </Switch>
``` 

As well as this:

```
      <Switch>
        <Route
          path="/foo"
          render={({ location }) => <Lazy location={location} fetch={() => _import('./foo')} />}
        />
        <Route
          path="/bar"
          render={({ location }) => <Lazy location={location} fetch={() => _import('./bar')} />}
        />
      </Switch>
``` 

Or even this nightmare 😄:

```
      <Route render={({ location }) => <Switch>
        <Route
          path="/foo"
          render={({ location }) => <Lazy location={location} fetch={() => _import('./foo')} />}
        />
        <Route
          path="/bar"
          render={({ location }) => <Lazy location={location} fetch={() => _import('./bar')} />}
        />
      </Switch> } />
```

**Comment by donaldpipowitch** [comment]
It looks like [`componentWillMount`](https://gist.github.com/donaldpipowitch/9fce086e7201477751fd00cf1766037e#file-lazy-tsx-L54) is just called _once_. Is this because of [`cloneElement` in `<Switch/>`](https://github.com/ReactTraining/react-router/blob/v4/packages/react-router/modules/Switch.js#L46)?

**Comment by donaldpipowitch** [comment]
It looks like I _do_ need `<Route component>` here (see https://github.com/ReactTraining/react-router/issues/4658, too). This works:

```
      <Switch>
        <Route
          path="/foo"
          component={() => <Lazy fetch={() => _import('./foo')} />}
        />
        <Route
          path="/bar"
          component={() => <Lazy fetch={() => _import('./bar')} />}
        />
      </Switch>
```

If this is the canonical way to solve my problem, feel free to close this issue.

However I'm surprised that writing my example this way results in `<Lazy/>` being re-used instead of having two different examples.

```
      <Switch>
        <Route
          path="/foo"
          render={() => <Lazy fetch={() => _import('./foo')} />}
        />
        <Route
          path="/bar"
          render={() => <Lazy fetch={() => _import('./bar')} />}
        />
      </Switch>
```

**Comment by pshrmn** [comment]
If your `<Lazy>` component had a `cDU` lifecycle method, you would see that it is called on subsequent renders. Add a `key` prop to your `<Lazy>` components and it should work as expected.

```js
<Route path='/quux' render={() => <Lazy key='quux' fetch={...}/> }/>
```

**Comment by mjackson** [comment]
Thanks for the response @pshrmn

**Comment by donaldpipowitch** [comment]
@pshrmn Thanks. This works. But it works a little bit unexpected for me.

I don't want to sound bad - you all do a **great** job - but this seems somewhat tedious to me. Inside `<Switch/>` I always just want to render _one_ route. This only make sense if the `path` (and maybe in combination with `exact`) is always unique. If I would have a supported way to define custom `<Route/>`s inside `<Switch/>` (coming back to https://github.com/ReactTraining/react-router/issues/4576). I could create a `<LazyRoute/>` or something like that which would generate a unique `key` based on `path` and `exact` automatically.

But anyway, thank you.

**Comment by pshrmn** [comment]
`<Switch>` is a very simple component that iterates over its children elements. If you need to support custom routes, then the best solution would probably be to implement your own `<Switch>`-like component.

For example, I created a [`<ConfigSwitch>`](https://github.com/pshrmn/rrc/blob/master/src/ConfigSwitch.js) component. It has the same effect as `<Switch>`, but I prefer to explicitly define the array of route objects.

**Comment by donaldpipowitch** [comment]
Cool, thank you for the link and your support! ❤
