### ISSUE TITLE
[v4] Possible problem rendering components inside <Switch/>

### ISSUE THREAD

**Issue by sergonius** [ReactTraining/react-router#4662]
Not sure where the problem is, but using slightly modified examples from the site, I run into problems with rendering layouts.

The goal is being able to pass a layout for a route to be rendered in. The problem is that when using `<Switch/>`, the layout doesn't get rendered unless I hardcoded it around the switch.

Routes:
```
const routes = [
  {
    path: '/list',
    exact: true,
    component: List,
    layout: CoreLayout,
  },
  {
    path: '/settings',
    exact: true,
    component: Settings,
    layout: HelpLayout,
  },
];
```

This works:
```
<Router>
  <div>
    <CoreLayout>
      <Switch>
        {routes.map((route, i) => (
          <RouteWithSubRoutes key={i} {...route} />
        ))}
        <Route component={NoMatch} />
      </Switch>
    </CoreLayout>
  </div>
</Router>

export const RouteWithSubRoutes = route => (
  <Route
    {...route}
    render={props => <route.component {...props} routes={route.routes} />}
  />
);
```

While I would like this to work:
```
<Router>
  <div>
    <Switch>
      {routes.map((route, i) => (
        <RouteWithSubRoutes key={i} {...route} />
      ))}
      <Route component={NoMatch} />
    </Switch>
  </div>
</Router>

export const RouteWithSubRoutes = route => (
  <Route
    {...route}
    render={(props) => {
      if (!route.layout) return <route.component {...props} routes={route.routes} />;

      return (
        <route.layout>
          <route.component {...props} routes={route.routes} />
        </route.layout>
      );
    }}
  />
);
```

Obviously I cannot have route based layouts this way.

The `route.layout` bit seems to be ignored completely while the component  gets rendered. A similar solution worked in alpha with `Match` and `Miss`.

**Comment by pshrmn** [comment]
Your problem is the `component`property of the route objects. You should be seeing a warning in your console that you cannot use both `component` and `render`. When you do prop spreading you are effectively setting `<Route component>`. Change the name and your code should work.

**Comment by sergonius** [comment]
Weirdly enough I didn't get anything in the console. Renaming fixed the issue, though. Thanks a lot!

**Comment by pshrmn** [comment]
Oh, it looks like the warning was lost at some point in time. I'll look into when that happened and maybe it can be re-added.
