### ISSUE TITLE
Beta.7 Changes how basename works

### ISSUE THREAD

**Issue by jktravis** [ReactTraining/react-router#4663]
Just wanted to post this here in case others run into it, but it looks like the `basename` prop has changed from taking the full URL (proto://server/subdir) to just taking the subdirectory (/subdir).

**Comment by pshrmn** [comment]
There were no `basename` changes in beta 7.

However, there were changes in the `history` module to improve `basename` support by making sure that they are correctly formatted. Anyways, `basename` has always been intended to be a subdirectory. I can think of no reason why you would want to include the protocol and resource parts.
