### ISSUE TITLE
Navigating Outside of Components in V4

### ISSUE THREAD

**Issue by stunaz** [ReactTraining/react-router#4665]
Hi,
How to achieve this [https://github.com/ReactTraining/react-router/blob/master/docs/guides/NavigatingOutsideOfComponents.md](https://github.com/ReactTraining/react-router/blob/master/docs/guides/NavigatingOutsideOfComponents.md), in v4 ?

**Comment by pshrmn** [comment]
Answered on SO

**Comment by stunaz** [comment]
thanks :+1:

**Comment by hilde2** [comment]
Answered where ?

**Comment by stunaz** [comment]
here http://stackoverflow.com/questions/42672842/how-to-get-history-on-react-router-v4
