### ISSUE TITLE
documentation issue: broken links in Histories

### ISSUE THREAD

**Issue by weisjohn** [ReactTraining/react-router#4669]
https://github.com/ReactTraining/react-router/blob/4f2746155ce1cb6bd194864f9feb1599b2e46c51/docs/guides/Histories.md#customize-your-history-further references  `useQueries` and `useBasename` pointing to https://github.com/ReactTraining/history/blob/v2.x/docs/QuerySupport.md and https://github.com/ReactTraining/history/blob/v2.x/docs/BasenameSupport.md 

Is there anyone who knows where these documents went? I'd be happy to update, but I can't find them.

**Comment by pshrmn** [comment]
I believe that the branch was renamed to `v2`.

**Comment by timdorr** [comment]
Fixed that up now.
