### ISSUE TITLE
Documentation needed: client side only + nginx + server returning 404 responses

### ISSUE THREAD

**Issue by revelt** [ReactTraining/react-router#4672]
We need to supplement existing v4 documentation to add a quite elementary and common case: client-side (normal) rendering via v4 react-router, returning 404 server error, on custom styled error pages, on nginx.

I trawled many issues (like #3210) and it looks like everybody are rendering server-side or issues get closed too soon to allow meaningful discussion to reach the client-side rendering 404 error codes, or examples are outdated.

**What about routing and responding with 404 server errors on client-side rendering web apps on Nginx?**

It looks like I the only one on the Internet wanting to make Google-friendly web apps with custom, styled and meaningful 404 error pages **returning correct error codes**, and do it with minimal effort (client-side rendering using `react-router` (no fluxible, reduxible or whatnot), on `create-react-app`) 😀

**Comment by timdorr** [comment]
That's really outside the scope of this project to provide web server configuration advice.

**Comment by revelt** [comment]
I understand, but there have to be certain setup on `react-router` side too, doesn't it?

My situation is not unique, and without correct server error messages all web apps, driven by `react-router` are not production-ready. That's a big deal in my humble opinion.

**Comment by timdorr** [comment]
And there's documentation for that: https://github.com/ReactTraining/react-router/blob/v4/packages/react-router/docs/api/StaticRouter.md

**Comment by timdorr** [comment]
BTW, if the documentation isn't doing it for you, the best way to effect change is a PR.

**Comment by revelt** [comment]
That's the thing, link you mentioned is talking about server-side. There's a documentation knowledge gap regarding client-side only :)

Currently I'm thinking of somehow generating a static 404 page using react/webpack plugins, then placing it strategically in root as a standalone-capable HTML (no React, just static, but uses assets from React part, so I don't have to update nav and so on when I update nav on React side, static will update and will look seamless). Then somehow to direct router to hardcoded URL on the server (extracted static 404 page). Then to edit Nginx so it serves that static page as 404 — that should have correct server error code, and custom-styled 404 page .

---

Tim, I appreciate that you take time to manage all this. There must be full day worth of stuff to do here. I'll do my best to contribute findings once I get to the bottom of this. 👍

**Comment by willin** [comment]
404 not found 
https://github.com/ReactTraining/react-router/blob/v4/packages/react-router/docs/api/StaticRouter.md

**Comment by pshrmn** [comment]
@willin GitHub's 404 pages are pretty awful for when branches change. The above link is on the master branch now, but I'll include a link to a specific tag so that it should be more permanent.

https://github.com/ReactTraining/react-router/blob/v4.1.1/packages/react-router/docs/api/StaticRouter.md

**Comment by kerimdzhanov** [comment]
Here is a good example: https://gkedge.gitbooks.io/react-router-in-the-real/content/nginx.html

**Comment by AbhiOnlyOne** [comment]
In case someone is still looking for a configuration in Nginx:

```
location / {
  try_files $uri /index.html;
}
```
