### ISSUE TITLE
v4 example links broken

### ISSUE THREAD

**Issue by lgandecki** [ReactTraining/react-router#4675]
The v4 Readme points to a "coming soon" link
https://reacttraining.com/react-router/examples

There is quite a bit of references around the web that point to some specific things around that address like https://react-router.now.sh/animated-transitions that point to https://reacttraining.com/react-router/ again which is broken. :-(

Is there a chance to see those examples, or are they are completely not working at this point?
If that's so, it might be great to mention this in the v4 docs, and don't point to a broken link.

Thanks!
(PS. Very excited about the v4 :) )

**Comment by datoml** [comment]
@lgandecki I think its related to the release of beta 8 yesterday.
Docu will be up shortly i think :).

**Comment by timdorr** [comment]
Yep, the website will be back up soon.

**Comment by kkamperschroer** [comment]
@timdorr - Any idea when the examples will be back up? Should this issue remain open until they are? Sorry if I'm sounding impatient, just attempting to experiment with RR4 and it's a little more difficult/slow to do when spelunking through the repo and looking at source code is necessary. 😄

Thanks!

**Comment by tylermcginnis** [comment]
@kkamperschroer Should be up by end of day today.
