### ISSUE TITLE
[Discussion] About Lifecycle

### ISSUE THREAD

**Issue by Bastorx** [ReactTraining/react-router#4681]
In react@3.0.2

`export 'Lifecycle' was not found in 'react-router'`

Lifecycle has been deprecated ?

**Comment by pshrmn** [comment]
I'm not particularly familiar with early RR features, but I assume that you are referring to this mixin, which was removed in v2. https://github.com/ReactTraining/react-router/blob/c3cd9675bd8a31368f87da74ac588981cbd6eae7/upgrade-guides/v2.0.0.md#lifecycle-mixin

**Comment by Bastorx** [comment]
Thanks a lot
