### ISSUE TITLE
Route props not updated

### ISSUE THREAD

**Issue by DavidSvetlik** [ReactTraining/react-router#4682]
## Version
3.0.2

## Steps to reproduce

Hi, okay, so I have route where I am pushing props to:

```
let rnd = Math.random();
...
<Route path='/' component={App} rnd={rnd} />
```

## Expected Behavior

In App component, I expect "this.props.route.rnd" to be last generated random number.

## Actual Behavior

Despite expectations, "this.props.route.rnd" is actually keeping its initial value.

**Comment by timdorr** [comment]
I'm not sure what else to say. `<Route>` doesn't work like this. Please read the documentation.

**Comment by DavidSvetlik** [comment]
@timdorr  Well, if <Route> does allow to pass properties more or less like standard React component, it's quite logical you would expect the same behaviour.

Is there some specific documentation/workaround for my case?

**Comment by timdorr** [comment]
This example might be of help: https://github.com/ReactTraining/react-router/blob/master/examples/passing-props-to-children/app.js

**Comment by DavidSvetlik** [comment]
@timdorr Thank you!
