### ISSUE TITLE
Unknown prop `staticContext`

### ISSUE THREAD

**Issue by matthewrobb** [ReactTraining/react-router#4683]
It looks like the recent change to add staticContext to the prop types has the unintended consequence of passing undefined outside of StaticRouter. 
```js
const MyCmp = withRouter(function({ match, location, history, children, ...props }) {
  return <div {...props}></div>;
});
```
I'm not 100% of my diagnosis but it seems close, any ideas?

**Comment by mjackson** [comment]
It's not unintended. You only get a `staticContext` when you render inside a `<StaticRouter>`. To guard against it, always

```js
withRouter(({ match, location, history, staticContext }) => {
  if (staticContext) {
    // we're in a <StaticRouter>
  }

  return <div/>
})
```

**Comment by matthewrobb** [comment]
Is there no way to omit the prop from being passed when not in a static router? It seems like an edge detail that most users will have to guard against without having any idea why. If it's only on the passed in context/props when present the end result for the guards stays the same and destructured `{staticContext}` will remain undefined. The only difference is that object rest will not pick it up. Maybe the problem lies there. I almost feel like Object Rest shouldn't bring over undefined properties at all.

**Comment by pshrmn** [comment]
It would be a simple change, but at the same time you're already destructuring other props that you probably aren't using, so I don't think that it is a big deal. Either way, the `withRouter` and `<Route>` docs should be updated to include the `staticContext` prop.

```js
// Changes to Route.render:
const props = { match, location, history }
if (staticContext)
  props.staticContext = staticContext
```

@mjackson As an aside, the one thing I dislike about `staticContext` is its name. I kind of wish that it was named `log` or `staticLog` since its purpose as I understand it is to log information about the render. Its purely a semantic complaint, but this reminded me of it.

**Comment by mjackson** [comment]
@matthewrobb I don't understand why you're concerned. The only people who will need to use `staticContext` are using a `<StaticRouter>`. Everyone else will ignore it and never use it.

@pshrmn The name is derived from the prop name `<StaticRouter context>`. I'm open to bikeshedding better names but I'd like to keep them in sync.

**Comment by pshrmn** [comment]
I don't care enough about the name to _really_ want to push for a change. My only real argument for changing is that it sounds weird to pass a "context" as a prop that will be added to the context (maybe that even makes sense in a roundabout way).

If I really wanted to bikeshed, it would be about the fact that `<NavLink>` doesn't make any sense as a name. What is "nav" about it? :jerry_seinfeld_face:

**Comment by ryanflorence** [comment]
> (maybe that even makes sense in a roundabout way)

nailed it :P

**Comment by ryanflorence** [comment]
@matthewrobb I can't think of a scenario where this would lead to bugs or unexpected behavior. If you can, let us know and we'll reopen, but to keep our anxiety levels lower we gotta keep a clean issues page! Thanks for bringing this up.

**Comment by matthewrobb** [comment]
It may be that people will need to adjust to filter out staticContext but it introduced a bug for me where my assumption was that the only props is be getting from withRouter were match location and history. So that assumption falls over when I want to pass every other prop on to a regular Dom element. I'm now inadvertantly passing an undefined staticContext prop.

Yes I can and now am filtering it out but its existence was unexpected since I'm not using a static router.

**Comment by jacknevitt** [comment]
I am getting a React warning with my BackButton component. 
`Warning: React does not recognize the 'staticContext' prop on a DOM element.`
I am importing Button from semantic-ui-react, maybe this is an issue on their end? I need to pass `args` down so the button can be styled differently around the app although that is not essential.
```js
const BackButton = ({ history, children, ...args }) => (
  <Button onClick={() => history.goBack()} {...args}>
    {children}
  </Button>
);
```

**Comment by bcbrian** [comment]
@jacknevitt I hope you already solved this but just add `staticContext` to your destructure so that it is not part of `args`.

```javascript
const BackButton = ({ history, children, staticContext, ...args }) => (
  <Button onClick={() => history.goBack()} {...args}>
    {children}
  </Button>
);
```

**Comment by ralphsmith80** [comment]
Pulling `staticContext` out via destructuring works but having to change this

```
export default () => (
  <Switch>
    <Route path="/:month/envelopes" component={EnvelopeIcon} />
    <Route path="/:month/transactions" component={TransactionsIcon} />
    <Route path="/budgets/(add-budget|edit-budget)?" component={BudgetIcon} />
    <Route path="/settings" component={SettingsIcon} />
    <Route path="/:month" component={HomeIcon} />
  </Switch>
)
```

to this 

```
export default () => (
  <Switch>
    <Route
      path="/:month/envelopes"
      render={({ staticContext, ...props }) => <EnvelopeIcon {...props} />}
    />
    <Route
      path="/:month/transactions"
      render={({ staticContext, ...props }) => <TransactionsIcon {...props} />}
    />
    <Route
      path="/budgets/(add-budget|edit-budget)?"
      render={({ staticContext, ...props }) => <BudgetIcon {...props} />}
    />
    <Route
      path="/settings"
      render={({ staticContext, ...props }) => <SettingsIcon {...props} />}
    />
    <Route
      path="/:month"
      render={({ staticContext, ...props }) => <HomeIcon {...props} />}
    />
  </Switch>
)
```

Sucks!

FYI those icons are from `'@material-ui/icons`. I don't have a suggestion for a better way but it seems you going to loose the ability to use the `component` syntax in a lot of cases.
