### ISSUE TITLE
Release react-router-dom@4.0.0-beta.8

### ISSUE THREAD

**Issue by bancek** [ReactTraining/react-router#4690]
The latest `react-router-dom` release is `4.0.0-beta.6` and it is not compatible with `react-router@4.0.0-beta.8`. There are problems with `Link`s. `Link` comes from `react-router-dom` and `Router` comes from `react-router` and contexts are not compatible.

**Comment by ryanflorence** [comment]
```sh
npm info react-router-dom@next

...

  version: '4.0.0-beta.8',
```

time to `rm -rf node_modules` :)

**Comment by bancek** [comment]
In the documentation it says `npm install react-router-dom` or `yarn add react-router-dom` (77ca4b42d). And last non @next version is `4.0.0-beta.6` (`npm info react-router-dom`). So maybe it would be better to put `@next` back into the docs or release `4.0.0-beta.8` as `latest`.

**Comment by ryanflorence** [comment]
you're just catching us at a bad time. We meant to release a couple hours ago, had problems publishing the website, and then michael had to get back to a workshop he's running. Ignore the docs for another couple of hours, and then it'll all be taken care of :P

**Comment by bancek** [comment]
No problem.

**Comment by benlakey** [comment]
I'm also stuck on this, but even if I go to `4.0.0-beta.8` stuff is broken for me:

```
Failed context type:
The context 'router' is marked as required in 'Link', but its value is 'undefined'.
```

Related question: Why is a beta marked as `latest` ?
