### ISSUE TITLE
fix the build

### ISSUE THREAD

**Issue by ryanflorence** [ReactTraining/react-router#4693]
Not sure what's up, but travis keeps failing on stuff as simple as doc fixes: https://travis-ci.org/ReactTraining/react-router/builds/209984763

Hangs up on react-router-redux tests?

**Comment by timdorr** [comment]
It was working on the PR I had for it. Was it because those dependencies were moved to the root? Lerna can do that for you (though, I never got it to work...).

**Comment by pshrmn** [comment]
I have no idea what it's effect on de-duping dependencies would be, but Lerna's beta 38 added yarn support. I'd be interested in seeing what effects switching to yarn would have on install time.

**Comment by timdorr** [comment]
It was really significant on Redux:

> Switched redux to @yarnpkg. Dropped test suite from 14m to 6m, then to 3.5m after caching. That is a 75% reduction! https://travis-ci.org/reactjs/redux/builds

https://twitter.com/timdorr/status/837760279614275586

**Comment by timdorr** [comment]
Trying it out in #4703

**Comment by timdorr** [comment]
That fixed it. Should be a moderate speed up for the first run and then another boost for the 2nd once the cache has warmed up.
