### ISSUE TITLE
ConnectedRouter is undefined

### ISSUE THREAD

**Issue by on3iro** [ReactTraining/react-router#4694]
## Version
react-router-redux 4.0.8

## Test Case
-

## Steps to reproduce
Follow the react-router-redux example: https://github.com/reacttraining/react-router/tree/master/packages/react-router-redux

## Expected Behavior
A Router component which is connected to the store

## Actual Behavior
`ConnectedRouter` is always  `undefined`

### index.js
```javascript
import React from 'react';
import ReactDom from 'react-dom';
import { Provider } from 'react-redux';
import {
  // BrowserRouter as Router,
  Route,
} from 'react-router-dom';
import createHistory from 'history/createBrowserHistory';
import { ConnectedRouter } from 'react-router-redux';

// Styles
import 'sanitize.css/sanitize.css';
import './global-styles';

import configureStore from './store';
import rootSaga from './rootSaga';
import App from 'containers/App';


const rootElement = document.getElementById('root');
const initialState = {};
const history = createHistory();
const store = configureStore(initialState, history);

// Run rootSaga
store.runSaga(rootSaga);

ReactDom.render(
  <Provider store={store}>
    <ConnectedRouter history={history}>
      <Route path="/" component={App} />
    </ConnectedRouter>
  </Provider>,
  rootElement
);
```

### store.js
```javascript
import { createStore, combineReducers, applyMiddleware, compose } from 'redux';
import createSagaMiddleWare from 'redux-saga';
import promise from 'redux-promise';
import { routerMiddleware } from 'react-router-redux';

import rootReducer from './rootReducer';


export default function configureStore(initialState, history) {
  const sagaMiddleWare = createSagaMiddleWare();
  const routerMW = routerMiddleware(history);
  const middleWares = [
    routerMW,
    promise,
    sagaMiddleWare,
  ];

  const enhancers = [
    applyMiddleware(...middleWares)
  ];

  const composeEnhancers =
    process.env.NODE_ENV !== 'production' &&
    typeof window === 'object' &&
    window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__ ?
      window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__ : compose;

  const store = createStore(
    rootReducer,
    initialState,
    composeEnhancers(...enhancers),
  );

  store.runSaga = sagaMiddleWare.run;

  return store;
}
```

**Comment by timdorr** [comment]
It's not in 4.0.8. That's a 5.0 feature, which is in alpha.

**Comment by valstu** [comment]
5.0.0 alpha contains just package.json and README.md?

**Comment by timdorr** [comment]
Huh, that's weird. Perhaps a bad push? I'll get that fixed up.

**Comment by timdorr** [comment]
5.0.0-alpha.2 is up on the `next` tag: `npm install react-router-redux@next` Sorry about that!

**Comment by oxyno-zeta** [comment]
Yes it's working !! Thanks !!

**Comment by valstu** [comment]
Weird, i'm still getting following error:

```js
Error in ./~/react-router-redux/index.js
Module not found: ./actions in /Users/username/project_folder/node_modules/react-router-redux
```

**Comment by valstu** [comment]
Started completely new app with `create-react-app` and the problem above still occurs. Seems like those files `./middleware.js & ./actions.js` are missing from the npm package root folder if I compare it to this package https://github.com/ReactTraining/react-router/tree/master/packages/react-router-redux

**Comment by valstu** [comment]
Seems like the react-router-redux package.json is missing `middleware.js` and `actions.js` from the files array and won't be published to NPM?

https://github.com/ReactTraining/react-router/blob/master/packages/react-router-redux/package.json#L10-L17

**Comment by iwyg** [comment]
@valstu have you tried importing them from `react-router-redux/es`?

**Comment by valstu** [comment]
@iwyg Yeah, then I get `Uncaught SyntaxError: Unexpected token import`

**Comment by ekalinichev** [comment]
+1 here, fresh create-react-app application, if I import 'react-router-redux' it can't find anything, and if I import 'react-router-redux/es' browser says "Unexpected token import", because imported ES6 doesn't get transpiled.

**Comment by iwyg** [comment]
@valstu @ekalinichev that's interesting bc that's the only way I got it to work.

**Comment by ekalinichev** [comment]
Maybe you have extra babel settings in addition to what create-react-app provides?

**Comment by iwyg** [comment]
@ekalinichev Maybe. I m using a custom setup with webpack 2, so no create-react-app settings.

**Comment by Grmiade** [comment]
It works for me after `node_modules` reset. With no custom `create-react-app` settings. Just remove and reinstall `node_modules`. You must use the `next` branch of `react-router-redux`.

```
rm -rf node_modules
rm yarn.lock
yarn
```

But there is another issue, https://github.com/ReactTraining/react-router/pull/4709 ... so it's not usable for the moment :/

**Comment by srosset81** [comment]
I get the same error messages as @valstu and @ekalinichev

**Comment by timdorr** [comment]
Those files are also missing from the package. Sorry about that. An alpha 3 is coming soon.

**Comment by ekalinichev** [comment]
@valstu @srosset81 I just installed version `5.0.0-alpha.3` and it worked for me, with just  
```
import { ConnectedRouter } from 'react-router-redux';
```

**Comment by chris0715** [comment]
`**** Klk ***`

**Comment by igorbuts** [comment]
Same thing just happened for newly installed "^5.0.0-alpha.8", i got undefined.
This helped:
```
import ConnectedRouter from 'react-router-redux/ConnectedRouter'
```

**Comment by remy** [comment]
Okay, no idea what's going on. I installed `@next` looked like it didn't work, I installed `@latest` - still didn't work (all `undefined`) reinstalled `@next` and the same code is working. 🤪 Well, ignore me then :)

**Comment by yurikilian** [comment]
@remy same here. It worked when I used @next. Maybe you forgot to do: watchman watch-del-all && npm start --reset-cache
