### ISSUE TITLE
Where Did the Docs Go?

### ISSUE THREAD

**Issue by rizedr** [ReactTraining/react-router#4696]
## Version
4.0.0-beta.8

## Expected Behavior
Access https://github.com/ReactTraining/react-router/tree/latest/docs and read the docs.

## Actual Behavior
Access https://github.com/ReactTraining/react-router/tree/latest/docs & you get a 404.

**Comment by rizedr** [comment]
Weird place to place them under `packages`, but here they are: https://github.com/ReactTraining/react-router/tree/master/packages/react-router

**Comment by pshrmn** [comment]
Each package has its own docs.
