### ISSUE TITLE
OnEnter Docs

### ISSUE THREAD

**Issue by rizedr** [ReactTraining/react-router#4697]
Previously, the `onEnter` docs where [here](https://github.com/ReactTraining/react-router/blob/df77bd97b6fc90c16dc74803117ead7a87bfbae2/docs/API.md#onenternextstate-replace-callback).

Where are those docs now? What happened to `onEnter`?

I don't see anything to reflect the above in [the change log](https://github.com/ReactTraining/react-router/blob/master/CHANGES.md).

**Comment by timdorr** [comment]
There is a new version. The 3.x docs are under the v3 branch now.

**Comment by rizedr** [comment]
> What happened to onEnter?
>
> I don't see anything to reflect the above in the change log.

@timdorr What about the rest?

**Comment by qwertypants** [comment]
https://github.com/ReactTraining/react-router/blob/v3/docs/API.md#onenternextstate-replace-callback
