### ISSUE TITLE
Error for Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export 

### ISSUE THREAD

**Issue by Miteshdv** [ReactTraining/react-router#4700]
After update  Followed the guides for connected router and react-redux-router

Getting following error

Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in.
    at invariant (invariant.js:44)
    at ReactCompositeComponentWrapper.instantiateReactComponent [as _instantiateReactComponent] (instantiateReactComponent.js:77)
    at ReactCompositeComponentWrapper.performInitialMount (ReactCompositeComponent.js:367)
    at ReactCompositeComponentWrapper.mountComponent (ReactCompositeComponent.js:258)
    at Object.mountComponent (ReactReconciler.js:46)
    at ReactCompositeComponentWrapper.performInitialMount (ReactCompositeComponent.js:371)
    at ReactCompositeComponentWrapper.mountComponent (ReactCompositeComponent.js:258)
    at Object.mountComponent (ReactReconciler.js:46)
    at mountComponentIntoNode (ReactMount.js:104)
    at ReactReconcileTransaction.perform (Transaction.js:140)

**Comment by oxyno-zeta** [comment]
Yes I got the same error. It is because when you install "react-router-redux", we install this one : https://github.com/reactjs/react-router-redux and not the new library... 

How to get the new one is the question !

**Comment by timdorr** [comment]
`npm install react-router-redux@next`

**Comment by oxyno-zeta** [comment]
This is not working. The module is empty... There is only a "package.json" and "README.md" file in the package...

**Comment by timdorr** [comment]
Yeah, there was a bad publish. I'll get a 5.0.0-alpha.2 out shortly.

**Comment by timdorr** [comment]
5.0.0-alpha.2 is up on the `next` tag: `npm install react-router-redux@next` Sorry about that!

**Comment by Miteshdv** [comment]
Thanks !

**Comment by opreaadrian** [comment]
This kept me awake for 3 hours, last night. Thank you!
I really appreciate the effort you put in and that you give your knowledge away for free, so others can build, create, and be great. You should feel really good that the software you build is in some cases, enables some people to put food on the table.

**Comment by nibblesnbits** [comment]
@timdorr, so the documentation is for 5.0.0, no 4.0.0?

**Comment by nibblesnbits** [comment]
This issue either still exists or returned in `5.0.0-alpha.4`.

**Comment by iDuuck** [comment]
Yeah. Also having this issue. Really hindering me from continuing work :/

**Comment by opreaadrian** [comment]
@iDuuck As far as the tags are concerned, you can go ahead and try to install `5.0.0-alpha.2` instead of `next` until everything works out, so you can continue work.

By the time you'll be done with your work, I'm sure this will move to the stable version.

**Comment by jwaterfaucett** [comment]
getting same thing on 5.0.0-alpha.2, still not working.

**Comment by opreaadrian** [comment]
Do you have any code to show? If everything is ok and you installed `5.0.0-alpha.2`, the problem might be somewhere else. Here are the dependencies of a project of mine, working flawlessly with this version of the library: https://github.com/opreaadrian/workee.fit/blob/master/package.json

**Comment by jwaterfaucett** [comment]
Yes, everything is working. It was some kind of funky npm/yarn cache state. After ccahe clean,  rm -R and reinstall its working.

**Comment by jinuem** [comment]
Not working with Latest Version :(

**Comment by iDuuck** [comment]
Could you set up a bare project that replicates this issue. I moved on and it worked for me afterwards. Would be glad to help out.

**Comment by stevematdavies** [comment]
Still broken in latest

**Comment by timdorr** [comment]
It's not on latest, it's on next.

**Comment by aaroncrawford** [comment]
@timdorr are there any workarounds for react-router-redux at this given moment?  Been beating my head against the wall for the past 2 days trying to get this to work by tomorrow.

**Comment by menq** [comment]
I get this error because 
`import { Link } from 'react-router-dom' `
maybe help

**Comment by Azmeer-crescent** [comment]
I still keep getting this error and don't know what to do. Please help:
This is my AzForm.js saved at: "./components/testComponent"

`import React from 'react'
import { Provider } from 'react-redux'
//import { createStore } from 'redux'  //NOT sure whether I need it, but I still get the same error
import { reduxForm } from 'redux-form'

const SignInForm = props => {
    return (
      <form>
      </form>
    );
};

export default reduxForm({
  form: 'simple' // a unique identifier for this form
})(SignInForm)`

and this is an extract from index.js

`import React, { Component } from 'react';
import { AppRegistry, StyleSheet, Image } from 'react-native';
import { SignInForm } from "./components/AzForm";

export class HomeScreen extends Component {
  render() {
    return (
      <SignInForm />
    );
  }
}`

[http://azmeer.info/delme/RN-element-type-invalid-err.png](url)

**Comment by sbauch** [comment]
FWIW, I was getting this error when my import was from `react-router` rather than `react-router-dom`, which I guess I was just used to from previous versions?

So instead of 
```js
import { Link } from 'react-router';
```
it should be 
```js
import { Link } from 'react-router-dom';
```
or I suppose for react-native:
```js
import { Link } from 'react-router-native';
```

**Comment by menq** [comment]
@sbauch  thanks!  some error from the `Link`

**Comment by joshdcomp** [comment]
@sbauch's answer worked for me as well—as I've been upgrading several apps from @2/3 to @4 a good rule of thumb seems to be anything that's called as a component probably needs to be imported from `'react-router-dom'`

**Comment by ecastroItexico** [comment]
Im still gaving the issue with  
    "react-router-redux": "^5.0.0-alpha.9",

> Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

**Comment by thibault60000** [comment]
Hello ! I had the same error and the transition from version 4 to version 5 alpha 9 of react-router-redux solved my problem.

BUT I HAVE ANOTHER PROBLEM: Now, my <Link To = "/ route"> do not work anymore (The url changes but the redirection is not done)

import { Link, withRouter } from 'react-router-dom';

    "react": "^16.1.1",
    "react-dom": "^16.1.1",
    "react-redux": "^5.0.6",
    "react-router": "^4.2.0",
    "react-router-dom": "^4.2.2",
    "react-router-redux": "^5.0.0-alpha.9",

**Comment by tgdn** [comment]
Guys maybe it should be time to warn about this on [the README here](https://github.com/reacttraining/react-router/tree/master/packages/react-router-redux)
