### ISSUE TITLE
New `aria-current` property for `<NavLink>`

### ISSUE THREAD

**Issue by JasonEtco** [ReactTraining/react-router#4707]
Hello!

I'd like to propose a new property for the <NavLink> component, namely the `aria-current` attribute on the resulting `a` tag. There are a couple of possible values for the attribute, but the ones `<NavLink>` should propably care about are `page` and `step`. This would be great for accessibility as it tells the screenreader what to announce as the current page, and shouldn't be too hard to achieve since you're already detecting whether or not a link is "current" for `activeClassName`.

It could look like:
```jsx
<NavLink to="..." ariaCurrent="page" activeClassName="is-active" />
```

There is also the option of making `aria-current="page"` be on the active link by default, but the dev might not want that or they might want a different value (like `

I'm happy to make a PR, but its pretty straightforward in the `NavItem.js` file.

Let me know what you all think :)

**Comment by JasonEtco** [comment]
There is also the simpler `aria-current="true"` value, but I'm not sure what the benefits of a more descriptive one like `page` or `step` are over the boolean.

**Comment by timdorr** [comment]
Closing to move discussion over to the PR in #4708.
