### ISSUE TITLE
What API changes cause this two problem?

### ISSUE THREAD

**Issue by EasonWang01** [ReactTraining/react-router#4711]
1.

```
Warning: Failed prop type: The prop `history` is marked as required in `Router`, but its value is `undefined`.
```

2.

```
Uncaught TypeError: Cannot read property 'listen' of undefined
    at syncHistoryWithStore
```

There are no error for 3.0.2 but for lastest.

**Comment by advance512** [comment]
The documentation is lacking.. there have been big changes, it seems, and v5.0.0-beta2 (iirc) removed syncHistoryWithStore, and needs a specific version of history..

**Comment by jellomoose** [comment]
I am having similar/same issues:  
  
`bundle.js:2945Warning: Failed prop type: The prop `history` is marked as required in `Router`, but its value is `undefined`.
    in Router`

`Uncaught TypeError: Cannot read property 'location' of undefined
    at new Router `

**Comment by ashishrijal** [comment]
I am having the same problem, i switched back to react-router version 3.0.2 and the issue was gone.

**Comment by tylermcginnis** [comment]
Hi @EasonWang01. React Router v4 is a complete re-write of React Router and therefor you shouldn't have the expectation of upgrading and still having everything work (which is why it's v4 and not v3.X). With that said, feel free to stick with the previous version (v3) if it's working for you. If you'd like to take the time to upgrade, you can read all about the new api [here](https://reacttraining.com/react-router).

**Comment by sulanto** [comment]
@ashishrijal I had the same issue, and I was also blind to the fact that the new 4.0.0 imports from react-router-dom and not react-router.

import {BrowserRouter as Router, Route, Link} from "react-router-dom";

and not something like

import {Router, Route, Link} from "react-router";

which will cause weird error messages that seem unrelated. Hope this helps.

**Comment by jimitpatel** [comment]
@tylermcginnis Thanks for pointing out that. Still if anyone wants solution and who are new into this area (like me) below is the solution

Use
```
import createBrowserHistory from 'history/createBrowserHistory'

// IGNORE
const store = createStore(
  rootReducer,
  {},
  enhancers
)

// This is useful
export const history = syncHistoryWithStore(createBrowserHistory(), store)
```

This will create `history` object which is custom.

On other hand when you need to pass `history` to `Router`, this is what you need to do

```
import React from 'react'
import ReactDom from 'react-dom'
import { Router } from 'react-router-dom' // Instead of BrowserRouter as Router, only Router
import App from './containers/App'

import { Provider } from 'react-redux'
import { store, history } from './redux/store.js' // this is where above export const history was used

// IGNORE this line
let basePath = window.location.pathname.replace('index.html', '')

function initRender() {
  ReactDom.render((
    <Provider store={ store }>
      <Router basename={ basePath } history={ history }>
        <App />
      </Router>
    </Provider>
  ), document.getElementById('root'))
}

initRender()

```
