### ISSUE TITLE
Actions file Missing error

### ISSUE THREAD

**Issue by Miteshdv** [ReactTraining/react-router#4715]
After taking update i.e react-router-redux@next i am getting error ./actions missing from react-router-redux index.js

Please help

**Comment by Miteshdv** [comment]
Required to add actions.js and middleware from source code for time being to move ahead .
Please provide the update in next release

**Comment by evenchange4** [comment]
Related to #4709

**Comment by rogovdm** [comment]
Blocked by this issues. Any updates?

**Comment by timdorr** [comment]
Just pushed out alpha 3.
