### ISSUE TITLE
warning  Expected an assignment or function call and instead saw an expression  no-unused-expressions

### ISSUE THREAD

**Issue by pedroresende** [ReactTraining/react-router#4718]
## Version
4.0.0

## Steps to reproduce
```
import {
  Redirect
} from 'react-router-dom'
```
try to use 

```
<Redirect to='/admin/dashboard' /> on a submit
```

## Expected Behavior

The expected Behaviour would be to redirect to /admin/dashboard
## Actual Behavior

Returns the error 

```
warning  Expected an assignment or function call and instead saw an expression  no-unused-expressions
```

**Comment by timdorr** [comment]
That is an eslint error. That has nothing to do with the router.

**Comment by jsj14** [comment]
Are you sure, it has nothing to do with react-router? Never seen this before.  I keep getting this after having updated from v2 to v4.
Module build failed: Error: standard:
	Configuration for rule "no-unused-expressions" is invalid:
	Value "data["0"].allowTaggedTemplates" has additional properties.

**Comment by timdorr** [comment]
Yes, this can't possibly be caused by our code unless you are linting your node_modules or something like that. Linters are only supposed to operate on the code you write.

**Comment by jsj14** [comment]
No. I have listed node_modules in 'eslintignore' file. 
What is more concerning is the missing 'match()' in v4!
 Is there an alternative method for the good old  
 `match({ routes, location: req.url }, (err, redirectLocation, renderProps) => { }) `  ?

**Comment by timdorr** [comment]
4.0 is a complete rewrite. You will need to rethink much of how you do things and there isn't a straightforward upgrade path. For server rendering, check out that specific guide: https://reacttraining.com/react-router/web/guides/server-rendering
