### ISSUE TITLE
Parents knowledge about the child

### ISSUE THREAD

**Issue by Heedster** [ReactTraining/react-router#4720]
```
<Route path="/" component={DashboardViewContainer}>
            <Route path="users/:userId" component={UsersView} />
            <Route path="users/:userId/jobs" component={JobsView} />
 </Route>
```
In my app, with a similar above organization, DashboardViewContainer needs to know whether UsersView or JobsView is highlighted, (or what child url has been rendered) to do something in the UI. For example, DashboardViewContainer has a navbar which shows the links 'Users' & 'UserJobs' and it needs to highlight the one that is open right now. 
But according to the design philosophy of react-router, parents should not know about which child is rendered. But this scenario seems to be a valid one. How can I tackle this?

**Comment by wyze** [comment]
Inside DashboardViewContainer you should still be able to get `match.url` from props, just like examples show. I am assuming you are on v4?

**Comment by Heedster** [comment]
No. I am in v3 since v4 is in beta. I read about match.url in the v4 docs and yeah, that is one way of solving it. But why I am not fully comfortable with that solution is that now another component needs to compare an URL, which components should totally be ignorant about. It seems like a bad pattern to compare URLs in different components, wherever I want to achieve something like this. Is there any other way? 

Something I would prefer is something like a route name that we could set to a Route, and every parent gets an array of Child Route names.

**Comment by timdorr** [comment]
@Heedster 4.0.0 was released on Friday :)

Regardless of version, you can use `<Link activeClassName="active">` to accomplish this exact kind of thing. 4.0.0 gives you some extra options if you don't want to use an a tag.

**Comment by Heedster** [comment]
It might not always be a link

**Comment by taurose** [comment]
IIRC, you get `this.props.route` and `this.props.routes` in your route components. You can use them to inspect the active route objects with their props, e.g.:

```js
// config
<Route path="/" component={DashboardViewContainer}>
  <Route myName="users" path="users/:userId" component={UsersView} />
  <Route myName="jobs" path="users/:userId/jobs" component={JobsView} />
</Route>

// in DashboardViewContainer
const routeIndex = this.props.routes.indexOf(this.props.route);
const childRoute = this.props.routes[routeIndex+1];
const myChildRouteName = childRoute && childRoute.myName;
```

**Comment by ddemolina** [comment]
I have a use case like this:
```
Root.js:
<Route path='/' component={ApplicationLayout}>


ApplicationLayout.js:
<AppHeader match={this.props.match}/>
<div>
    <Switch>
        <Route path="/projects/:pid" component={MenuProjects}/>
        <Route path="/projects/:pid/slides/:slide_id" component={Slides}/>
    </Switch>
</div>
<div>
    <Switch>
        <Route path="/projects/:pid" component={Projects}/>
        <Route path="/projects/:pid/slides/:slide_id" component={Slides}/>
    </Switch>
</div>
```

When location.pathname is for example "/projects/1"  I can see that this.props.match passed down to AppHeader match is an empty object and I need the same params you get in Projects.(id) 

I have had this problem when I have migrated from v2 to v4 because in v2 parent component get params of the child match.

What can I do in v4?
