### ISSUE TITLE
BrowserRouter accepts history object

### ISSUE THREAD

**Issue by rogovdm** [ReactTraining/react-router#4727]
Usa case: Google Analytics + React Router.

- I want to use `history.listen` object to send data to GA outside of my components structure.
- Then I want to pass this `history` object to `BrowserRouter` so routes will use that history intance.

````
<BrowserRouter history={history}>
</BrowserRouter>
````

**Comment by timdorr** [comment]
Just use `<Router>` directly. [`<BrowserRouter>` is just a wrapper with a pre-built history](https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/modules/BrowserRouter.js), so you can do the same with custom history instance.

**Comment by rogovdm** [comment]
Yes, perfect. Thanks!

**Comment by kaushik143** [comment]
@rogovdm  @timdorr  I want to pass custom history with BrowserRouter so I used Router for the  same. But because of that window.location is not in sync with current url. 

Everything accept that seems to work.
