### ISSUE TITLE
[react-router-redux] time-travel does not change routes

### ISSUE THREAD

**Issue by BerndWessels** [ReactTraining/react-router#4729]
## Version
```js
  "dependencies": {
    "history": "^4.6.0",
    "preact": "^7.2.0",
    "preact-compat": "^3.14.1",
    "preact-redux": "^2.0.0",
    "ramda": "^0.23.0",
    "react-router": "^4.0.0",
    "react-router-dom": "^4.0.0",
    "react-router-redux": "^5.0.0-alpha.3",
    "redux": "^3.6.0"
  }
```

## Expected Behavior
When using `redux dev tools chrome extension` and time travel back across `@@router/LOCATION_CHANGE` actions the browser should change location accordingly.

## Actual Behavior
'Time travel` does not have any effect on the browsers location.

This is bad since it prevents to actually restore the full state and debug issues (which is the whole point of having `react-router-redux` in the first place).

**Comment by timdorr** [comment]
Yep, that's a known issue. Follow along with (or contribute to!) #4717 as we fix it.
