### ISSUE TITLE
location.href, when i goBack and refresh on iphone safari,get a  blank page

### ISSUE THREAD

**Issue by zhouzefei** [ReactTraining/react-router#4734]
## Version
2.8.1

## Test Case
http://jsbin.com/sacerobuxi/edit?html,js,output

## Steps to reproduce
iphone version:8.4
on iphone safari web browser
when i jump to a external links from Router use location.href, then i goBack, and refresh the page get a blank page(try a few times will appear).but if i revisit the page is ok. 

i test it on iphone version > 9.0 is ok

## Expected Behavior
goBack and refresh according to the normal

## Actual Behavior
goBack and refresh get a blank page

**Comment by timdorr** [comment]
Version 2.x isn't supported anymore. Also, I don't think we're going to support older versions of iOS, as they have known issues like this. [>9 usage is at 5%](https://developer.apple.com/support/app-store/)

**Comment by timdorr** [comment]
We'll do bug fixes for 3.0, but not any other major improvements. Most of the focus is on 4.0 now.
