### ISSUE TITLE
react-router-config documentation missing important parts

### ISSUE THREAD

**Issue by bytor99999** [ReactTraining/react-router#4736]
While trying to figure out how the new 4.0.0 react-router works, and with missing documentation to explain how to go from react-router 0.x to 4.0 I had to guess on many things. So I wanted to point out a few places that had things missing, specifically in the beta react-router-config documentation. The biggest part is missing imports and other necessary scaffolding. 

In the renderRoutes section it uses ReactDOM and BrowserRouter, both of which have no import statement in the documentation so that we could know where to find them, or that that was required. 

Also in the examples they have Root, Child, etc as their own classes and leaves us where we only have an App class in which we add the routes and BrowserRouter inside the render of the App class, we have no way to know what is required to get it to work at all.

Thanks.

**Comment by timdorr** [comment]
At the top of the readme, we state "This is alpha software". So, things are subject to (very likely) changes in the API surface that would affect documentation. You generally don't want to document something beyond the basics until the end, when the API is more solidified.

**Comment by bytor99999** [comment]
But you have to use it if you are using production release 4.0.0 Since that is the only way to do static routing. So I have no choice. I am surprised at how much React and its modules/plugins never have backwards compatibility, they are too quick to throw things away such that it is impossible for any real world business to upgrade once they start.

**Comment by timdorr** [comment]
You can continue to use 3.0 until the end of time. No one is forcing you to use 4.0. Upgrade whenever it makes sense for you, not whenever we release new versions.

**Comment by bytor99999** [comment]
No one is forcing us. But eventually you have to upgrade, you cannot use 3.0 until the end of time. If that was so that I can use React.js 0.13 till the end of time. Oh wait, I can't because in order to add the new features that my company wants me to add to our application requires components that ONLY work in React.js 15, so in many ways, while it is nice to think you never have to upgrade stuff, you do eventually. It is part of software development.
