### ISSUE TITLE
Server render question

### ISSUE THREAD

**Issue by hechuanhua** [ReactTraining/react-router#4740]
I'm using hashHistory，Error occurred：
React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client) sq4.1.0.0"><a href="#/" class="active" 
 (server) sq4.1.0.0"><a href="/" class="active"

**Comment by timdorr** [comment]
You can't use a hash history with server rendering. You have to use a browser history.
