### ISSUE TITLE
Make *match* renameable

### ISSUE THREAD

**Issue by sateffen** [ReactTraining/react-router#4741]
Hey,

I've got a problem with the *match* thing in the nested components. The name *match* is so universal, that it crashes with a lot of other, existing components. It would be great to have an option to change the name *match* to something like *routeMatch*.

The current documentation doesn't contain information about that.

It's not only the *match* property, but *location* and *history* as well. There should be an option to rename that (I personally would name them *routeLocation* and *routeHistory*, but other people won't, so optional).

Using react-router v4 here

**Comment by timdorr** [comment]
Sorry, but we use that nomenclature in so many places that changing it would be really painful. If you really want it renamed, just create a wrapper Route component that passes the object with different names to it's component or render function.
