### ISSUE TITLE
Typescript route

### ISSUE THREAD

**Issue by DimaDaxDadeco** [ReactTraining/react-router#4742]
Typescript.
I want to add custom parameter in route like "name"
`<Route name="News" path="news" component={News} />`
I try extend IRouteProps:
```
declare module 'react-router' {
  namespace ReactRouter {
    export interface IRouteProps {
      name?: string;
    }
  }
} 
```
But it don't work.

**Comment by timdorr** [comment]
This isn't really a React Router issue. I would ask in the appropriate support channels for Typescript.
