### ISSUE TITLE
router stops working if component is wrapped with react-redux connect()

### ISSUE THREAD

**Issue by vschoettke** [ReactTraining/react-router#4744]
After updating from 4.0.0-beta.6 to the release version 4.0.0 the routing stopped working for me (clicking on links will change the browser url but not change the app content). After some digging I found out that the problem is related to wrapping component that contained routes (but no router) with the react-redux `connect()` function for store access as props.

I made a small gist with example code to reproduce.
See https://gist.github.com/vschoettke/9d7440e1580fa2017d733f1df71ff9a5

**Comment by timdorr** [comment]
See this guide: https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/guides/blocked-updates.md

**Comment by epeli** [comment]
Some previous discussion https://github.com/ReactTraining/react-router/issues/4671

**Comment by bon-opina** [comment]
Thank you saved me a lot of time.
