### ISSUE TITLE
React Native from Navigator to React Router docs/example request 

### ISSUE THREAD

**Issue by MarkMurphy** [ReactTraining/react-router#4747]
After reading through the docs for native I'm still left with a couple of questions that I'd like to see addressed somewhere because I'm sure other people are thinking the same thing.

What steps would we need to take to migrate from using the React Native Navigator component to using react router. Specifically:

1. `Navigator` comes with a `NavigationBar` where we can define a title and a left and/or right button.
2. `Navigator` allows each route to specify how it's transitioned in eg. `Navigator.SceneConfigs.FloatFromLeft` or `Navigator.SceneConfigs.FloatFromBottom`, etc. [docs here](https://facebook.github.io/react-native/docs/navigator.html#scene-transitions). Yes, I've read the animations section in the docs for v4.

I'm assuming we'd have to take care of both of these from scratch ourselves. Same goes for screen/scene gestures as well.

**Comment by ryanflorence** [comment]
Yes that's right. Whether we create a "react-router-navigators" package that builds animated transitions on top of router or somebody else does, we're not sure. Had some conversations with native-navigation and react-navigation folks at ReactConf where there might be some collaboration but right now that is left up to user-land.

**Comment by MarkMurphy** [comment]
Gotcha, and thanks! I think it's worth adding as a note somewhere in the [new react router docs](https://reacttraining.com/react-router/native/guides/quick-start). Maybe as a new section under Guides?

**Comment by timdorr** [comment]
If you want to whip up a PR with some docs additions, that would be great!

**Comment by LeoLeBras** [comment]
@ryanflorence @satya164 @MarkMurphy @ericvicenti

Hi guys!

I'm currently working on an “add-on" to ```react-router``` named [```react-router-navigation```](https://github.com/LeoLeBras/react-router-navigation). The aim of this project is to provide tools to navigate between screens with [```react-navigation```](https://github.com/react-community/react-navigation/) and [```react-native-tab-view```](https://github.com/react-native-community/react-native-tab-view) inside react-router's context.

Note that the project is still at a very young stage and the API isn't finished yet. Even if a few things might change in the future, it’s pretty stable now!
Feel free to open an issue on the repo if you face a bug or have any question! 🚀
