### ISSUE TITLE
Server-side render with preloading data occurs react's warning

### ISSUE THREAD

**Issue by wellyshen** [ReactTraining/react-router#4749]
I followed the [doc](https://reacttraining.com/react-router/web/guides/server-rendering/data-loading) to pre-load data from SSR. But I got the react warning of "React attempted to reuse markup in a container but the checksum was invalid." If I didn't preload data from SSR, everything goes OK.

## Version
4.0.0

## Test Case
https://github.com/wellyshen/react-cool-starter/tree/RR4-SSR

## Steps to reproduce
`yarn install && yarn build:client && yarn start`

## Expected Behavior
Preloading data from SSR without React warning

## Actual Behavior
```
Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client)  react-empty: 8 --><div class="styles__U
 (server)  react-empty: 8 --><p data-reactid="9">L
```

**Comment by mrm007** [comment]
I cloned your repo and got an error:

```
$ better-npm-run clean:client
running better-npm-run in /Users/mrm/work/react-cool-starter
Executing script: clean:client

to be executed: rimraf ./build/public/assets
✨  Done in 0.41s.
running better-npm-run in /Users/mrm/work/react-cool-starter
Executing script: build:client

to be executed: webpack --progress --hide-modules --config ./tools/webpack/webpack.client.babel.js
Hash: 77edf01d177c71c47ced
Version: webpack 2.2.1
Time: 15326ms

ERROR in multi react react-dom redux react-redux redux-thunk react-hot-loader react-router react-router-redux react-helmet axios redbox-react chalk lodash
Module not found: Error: Can't resolve 'react-router-redux' in '/Users/mrm/work/react-cool-starter'
 @ multi react react-dom redux react-redux redux-thunk react-hot-loader react-router react-router-redux react-helmet axios redbox-react chalk lodash
error Command failed with exit code 2.
```

Looks like you forgot to add `react-router-redux` to your `package.json`... Let's try that.

```
$ yarn add react-router-redux@next
yarn add v0.21.3
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "chai-enzyme@0.6.1" has unmet peer dependency "cheerio@0.19.x || 0.20.x || 0.22.x".
warning "url-loader@0.5.8" has unmet peer dependency "file-loader@*".
[4/4] 📃  Building fresh packages...
success Saved lockfile.
success Saved 1 new dependency.
└─ react-router-redux@5.0.0-alpha.3
✨  Done in 6.98s.

$ yarn build:client && yarn start
yarn build:client v0.21.3
$ yarn run clean:client && better-npm-run build:client
yarn run v0.21.3
$ better-npm-run clean:client
running better-npm-run in /Users/mrm/work/react-cool-starter
Executing script: clean:client

to be executed: rimraf ./build/public/assets
✨  Done in 0.40s.
running better-npm-run in /Users/mrm/work/react-cool-starter
Executing script: build:client

to be executed: webpack --progress --hide-modules --config ./tools/webpack/webpack.client.babel.js
Hash: d6c6ab29b762bc49f76c
Version: webpack 2.2.1
Time: 15196ms
                 Asset     Size  Chunks                    Chunk Names
      main.0844cf30.js  54.3 kB       0  [emitted]         main
    vendor.efed1127.js   316 kB       1  [emitted]  [big]  vendor
     main.d27b128c.css  2.72 kB       0  [emitted]         main
  main.0844cf30.js.map   385 kB       0  [emitted]         main
 main.d27b128c.css.map  10.8 kB       0  [emitted]         main
vendor.efed1127.js.map  3.59 MB       1  [emitted]         vendor
✨  Done in 18.76s.
yarn start v0.21.3
$ better-npm-run start
running better-npm-run in /Users/mrm/work/react-cool-starter
Executing script: start

to be executed: nodemon ./index.js --exec babel-node
[nodemon] 1.11.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: index.js /Users/mrm/work/react-cool-starter/tools/flow/**/* /Users/mrm/work/react-cool-starter/tools/webpack/**/* src/server.js src/utils/renderHtmlPage.js
[nodemon] starting `babel-node ./index.js`
==> 🌎  Listening at http://localhost:3000
webpack building...
Hash: f8607efd002390901632
Version: webpack 2.2.1
Time: 8079ms
  Asset    Size  Chunks                    Chunk Names
main.js  5.6 MB       0  [emitted]  [big]  main
webpack built f8607efd002390901632 in 8079ms
```

So far so good... Let's check the browser.

![localhost:3000](https://www.dropbox.com/s/axrwl143zfiykrs/Screenshot%202017-03-15%2023.37.13.png?raw=1)

It's a different error than what you were getting, so this is progress.
Seems to be a misconfiguration in `webpack.client.babel.js`:

```
// css-loader server config
localIdentName: isDev ? '[name]__[local].[hash:base64:5]' : '[hash:base64:5]',

// css-loader client config
localIdentName: '[hash:base64:5]',
```

I'm sure you can figure it out from here 😎.

**Comment by wellyshen** [comment]
@mrm007 I got the error on development, so the `server config` might not involved.

**Comment by mrm007** [comment]
When you render on the server `css-loader` generates class names using `localIdentName ` from the server webpack config.
When rendering on the client that class name doesn't match the one generated by the client webpack config.

**Comment by wellyshen** [comment]
@mrm007 The problem also occurs in the development environment, however in the development environment, the webpack server config won't be involved. I using dev server for it.

**Comment by wellyshen** [comment]
@ryanflorence I don't why this issue is closed, I have point out that the problem also occurs in development environment, however in the development environment, the webpack server config won't be involved. @mrm007 could you try to run `yarn start` directly to see what I told about?

**Comment by mrm007** [comment]
@wellyshen Buddy, the issue was closed because you were given the solution. It was ~PEBKAC~ your webpack config. Change `localIdentName: '[hash:base64:5]'` in `webpack.server.babel.js` and you'll see how it _magically_ works.

**Comment by wellyshen** [comment]
@mrm007 I tried, not work!

**Comment by wellyshen** [comment]
@mrm007 By the way, on prod environment, the css-loader on both will be the same.

**Comment by ryanflorence** [comment]
feel free to send a PR w/ a failing test, but I'm confident there's nothing about the router that would be causing this, I'm sorry I can't help you debug your app :\

**Comment by wellyshen** [comment]
@ryanflorence It doesn't matter. I already solved the issue by async routes. BTW, if there's an example for the [Docs](https://reacttraining.com/react-router/web/guides/server-rendering/data-loading). It will be great.
