### ISSUE TITLE
hashHistory stopped working in 4.0.0

### ISSUE THREAD

**Issue by ehartford** [ReactTraining/react-router#4752]
## Version
4.0.0

## Test Case
the jsbin doesn't work because the library is too old, need 4.0.0

## Steps to reproduce
Upgrade to 4.0.0

    import { Router, hashHistory } from 'react-router';
    render(<Router history={hashHistory}>{routes}</Router>, root);

## Expected Behavior
It should work

## Actual Behavior
It doesn't work

    Warning: Failed prop type: The prop `history` is marked as required in `Router`, but its value is `undefined`.
    in Router
    printWarning
    localhost/:36 Uncaught TypeError: Cannot read property 'location' of undefined
    at new Router (eval at <anonymous>

**Comment by ehartford** [comment]
I found where it was removed.

https://github.com/ReactTraining/react-router/commit/d0414344b660e2d89352fd82b74bd730deba0602

How do I make hash history work now?

**Comment by emjaksa** [comment]
It has moved to a new package react-router-dom. Install the new package and follow the new [guides](https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/docs/api/HashRouter.md) for v4.x

**Comment by emjaksa** [comment]
It has been moved to a new package, react-router-dom. Install the new package and follow the docs for [HashRouter](https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/docs/api/HashRouter.md)

**Comment by ickata** [comment]
It's not clear how to use it from the docs. How to migrate this code for example:

```
ReactDOM.render((
   <Router history={ReactRouter.hashHistory}>
      <Route path="/" component={Login} />
      <Route path="dashboard" component={Dashboard} />
      <Route path="users" component={Users} />
   </Router>
), document.getElementById( 'page' ) )
```

**Comment by emjaksa** [comment]
The [getting started guide](https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/docs/guides/quick-start.md) might be more clear. Just replace BrowserRouter with HashRouter. You no longer need to pass the history as a prop anymore. So for your code it would be.

`
import React from 'react';
import ReactDOM from 'react-dom';
import {
  HashRouter,
  Route,
  Link
} from 'react-router-dom';

ReactDOM.render((
   <HashRouter>
      <Route path="/" component={Login} />
      <Route path="dashboard" component={Dashboard} />
      <Route path="users" component={Users} />
   </HashRouter >
), document.getElementById( 'page' ) )
`

**Comment by vineysagar** [comment]
hi 
i am new to React js . Actually i am trying to do routing but its not working.. see my code plz.

**Comment by codejockie** [comment]
@ickata You need to install  `react-router-dom` then do the following:
```
import React from 'react';
import { render } from 'react-dom';
import { HashRouter as Router, Route } from 'react-router-dom';

// import your components here

render(
    <Router>
        <Route path="/" component={Login} />
        <Route path="dashboard" component={Dashboard} />
        <Route path="users" component={Users} />
    </Router>,
    document.querySelector('#page')
);
```

**Comment by hendrixroa** [comment]
Great job!

**Comment by ShootToThrill** [comment]
how i use HashRouter to show my 404page?

**Comment by ShootToThrill** [comment]
what dose exact mean ? 
and how i transform these old code to HashRouter?
`<Router history={this.props.history} onUpdate={this.updateHandle.bind(this)}>`
`                  <Route path='/' component={App}>`
                    `<IndexRoute component={Home}/>`
                  `  <Route path='list' component={List}/>`
                    `<Route path='detail/:id' component={Detail}/>`
                    `<Route path="*" component={NotFound}/>`
               ` </Route>`
          `  </Router>`

**Comment by orangecoding** [comment]
@timdorr question on this one: we are currently upgrading from R-router 2 to 4. In 2, we had a file where we used `require('react-router').hashHistory;` to listen to the hashHistory (also used to push location changes)

How can I do this with the new component `HashRouter`?

**Comment by pshrmn** [comment]
@orangecoding https://github.com/ReactTraining/react-router/blob/master/FAQ.md#how-do-i-access-the-history-object-outside-of-components

**Comment by clthck** [comment]
@orangecoding you can still listen to history in react-router 4.

```js
class App extends React.Component {
  componentDidMount() {
    const { history } = this.props;
    history.listen(e => {
      console.log('listen', e.pathname);
    });
  }
  render() {
    ...
  }
}

...

ReactDOM.render(
  <Provider store={store}>
    <Router>
      <Route component={App} />
    </Router>
  </Provider>,
  document.getElementById('root')
);
```

**Comment by Anna098301065** [comment]
'react-router' does not contain an export named 'hashHistory'. why?

**Comment by clthck** [comment]
@Anna098301065 Please refer to https://github.com/ReactTraining/react-router/issues/4752

**Comment by timdorr** [comment]
@Anna098301065 The API in 4.0 was completely changed. Please read through the docs.

**Comment by Hiroki1116** [comment]
`import React from 'react';
import {
	HashRouter,
	Route,
	NavLink
}
from 'react-router-dom';
import Posts from './Posts';

export default class App extends React.Component {
	constructor(props) {
		super(props);
	}

	render() {
		return (
			<HashRouter>
				<div>
					<ul className="sidebar">
        				<li className="sidebar-list">
        					<NavLink to="/posts" >Posts</NavLink>
        				</li>
        			</ul>
					<div className="admin-contents">
						<Route path="/posts" component={Posts}/>
					</div>
				</div>
			</HashRouter>
		);
	}
}`


Accordting to emjaksa, using HashRouter would solve the error.

In my case, however, clicking Link (or NavLink) shows an error message
**"Warning: Hash history cannot PUSH the same path; a new entry will not be added to the history stack"**.
(although the page itself is properly renderted)

**Comment by as440133** [comment]
ll
