### ISSUE TITLE
React not rendering view when Link tag used inside redux

### ISSUE THREAD

**Issue by themirror178** [ReactTraining/react-router#4756]
After doing some researching, I found a similar issue regarding Redux's connect and {pure: false} workaround was fixed in react-router 3.0. I'm running react-router 4.0 (as part of react-router-dom) and still find this issue. https://github.com/reactjs/react-redux/issues/388

//bootstrap
```
ReactDOM.render(
    <Provider store={myStore}>
        <Router>
            <ConnectedMain />
        </Router>
    </Provider>, root_elem);
```

`var ConnectedAdminMain = connect( mapStateToProps, null, null)(Main);`

// Main
```
<div className="col-lg-12">
   <Route exact path="/" component={TestOne} />
      <Route path="/:id" component={ TestOneDetails} />
   </div>

```
// TestOne
`Has <Link to="/foo">bar</Link>`

## Version
4.0.0
    "react-redux": "^5.0.2",
    "react-router-dom": "^4.0.0",
## Expected Behavior
1. Link changes in URL
2. View re-renders
## Actual Behavior
1. Link changes in URL
2. View does not re-render
3. Refreshing the browser renders the correct view.

**Comment by pshrmn** [comment]
`{ pure: false }` would fix your issue. Otherwise, please see https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/guides/blocked-updates.md (or if you want a longer read, you can check out [this article I wrote](https://medium.com/@pshrmn/ditching-subscriptions-in-react-router-6496c71ce4ec#.7zjaemwl7) that goes into some more detail about the problem).

**Comment by pshrmn** [comment]
Anything that allows for your connected component to update when the location changes would work. Passing a `location` prop means that `sCU` can still block updates when the location has not changed. Whether this is important will vary from project to project, but I would say don't feel obligated to turn off all update blocking just for React Router's sake.

**Comment by wizardzloy** [comment]
What about the nested `<Route>` components? Are they prone to the same issue?

```js
React.render(
  <Router>
      <Route path="/", render={({ match }) => <App matchUrl={match.url}>} />
  </Router>
)

class App extends PureComponent  {
  render() {
    const { matchUrl } = this.props;
    return (
       <div>
           <Link to={matchUrl} >Home</Link>
           <Link to={`${matchUrl}about`} >Home</Link>
           <Route exact path={matchUrl} render={() => <h1>Home Component</h1>} />
           <Route path={`${matchUrl}about`} render={() => <h1>About Component</h1>} />
       </div>
    )
  }
}  
```

In other words, does it mean I always have to pierce all the `shouldComponentUpdate`s between `Route`s as well?

**Comment by edwardfhsiao** [comment]
```js
import { withRouter } from 'react-router-dom'
export default withRouter(connect(mapStateToProps)(Something))
```
does the trick. https://reacttraining.com/react-router/web/guides/redux-integration

**Comment by lazdinst** [comment]
Confirming @edvinerikson solution worked.

**Comment by HeNKiEeEeE** [comment]
withRouter() works, but you have to put it on the right component. For me that was the first child of the <Router>
Too bad none of the solutions mentioned on which component you had to put the "withRouter()" nonsense
