### ISSUE TITLE
The context `router` is marked as required in `Link`, but its value is `undefined`.

### ISSUE THREAD

**Issue by lucascavalcante** [ReactTraining/react-router#4759]
Guys, I need your help!

I already searched about this bug in many sites, including documentation for react-router.

I was implementing likewise the documentation recommends. But, this error persists.

Imports
```
import { 
    BrowserRouter as Router,
    Switch,
    Route,
    Link
} from 'react-router-dom';
```

Menu
```
<Link to="/" className="pure-menu-link">Home</Link>
<Link to="/author" className="pure-menu-link">Author</Link>
<Link to="/book" className="pure-menu-link">Book</Link>
```

Routes definition
```
<Router>
    <Switch>
	<Route exact path="/" component={Home} />
	<Route path="/author" component={AuthorBox} />
        <Route path="/book" component={BookBox} />
    </Switch>
</Router>
```

Error
The context `router` is marked as required in `Link`, but its value is `undefined`.

Thanks for your attention.

**Comment by pshrmn** [comment]
Please verify that you have version `4.0.0` of `react-router` and `react-router-dom` installed in your `node_modules`.

**Comment by lucascavalcante** [comment]
Hi, Paul!

The versions are `react-router@4.0.0`, and `react-router-dom@4.0.0-beta.8` (both are in node_modules).

**Comment by pshrmn** [comment]
Well I would recommend updating `react-router-dom` to `4.0.0` now that it is out of beta.

I've seen other people have context issues, but that was typically with earlier versions of `react-router` where the context was different.

If updating the dom package doesn't fix the issue, I would reset everything with a `rm node_modules && npm install`. Sometimes that folder seems to have a chaotic mind of its own.

**Comment by clintjansen** [comment]
https://github.com/ReactTraining/react-router/issues/4645 Fixed this exact issue for me

**Comment by lucascavalcante** [comment]
Doesn't work for me.

I did downgrade for 4.0.0-beta.6, and after for 4.0.0.

**Comment by pshrmn** [comment]
@lucascavalcante What doesn't work? Going back to beta versions isn't really a solution now that final is released.

**Comment by mjackson** [comment]
@lucascavalcante Just make sure you're rendering your `<Link>`s somewhere in the tree underneath your `<Router>` (i.e. in one of your `<Route component>` components). This won't work:

```js
<div>
  {/* This link needs to be a descendant of the <Router>. To fix, move the <Router> to the root! */}
  <Link></Link>
  <Router>
    ...
  </Router>
</div>
```

**Comment by luckybirdme** [comment]
@mjackson Fixed this exact issue for me

**Comment by charlesponti** [comment]
Anyone have a solution to this in terms of testing? Rendering your components within the context of your application Router is no issue when running the application, but is more difficult to do when you are writing tests for components. We shouldn't have to render out the whole app to run a unit test on a component that contains a Link, no?

**Comment by pshrmn** [comment]
@charlesponti Have you seen this? https://reacttraining.com/react-router/core/guides/testing/starting-at-specific-routes

**Comment by charlesponti** [comment]
@pshrmn Haven't seen that! Looks like exactly what I needed, should make for some interesting test cases 👍  Thanks so much

**Comment by YacheLee** [comment]
It works for me by the following lines of code
import {MemoryRouter} from 'react-router-dom';

<MemoryRouter>
 <MyComponent />
</MemoryRouter>

**Comment by xgqfrms-gildata** [comment]
# `<Router>`


> `<Router>` must be the top parent of all `<Link>`s.

@mjackson 
> You did a Good Job!

**Comment by shishirarora3** [comment]
I got this when parent Router was from 4 version and child Link was from 3 version.

**Comment by LionelJCastro** [comment]
Basically,
-------------------------------------------------------------------
<BrowserRouter> must be the top parent of all <Link>s.
In new versions seems you need a layout where to put your menu with your links
-------------------------------------------------------------------
`<BrowserRouter>
	<Layout>
		<Switch>
			<Route exact path="/" component={Homepage} />
			<Route path="/resources" component={Resources} />
			<Route component={Error404} />
		</Switch>
	</Layout>
</BrowserRouter>`

**----LAYOUT-----**
`const Layout = props => ({
	render() {
		return (
			<div className="o-container">
				<Header />
				<main>{props.children}</main>
				<Footer />
			</div>
		);
	}
});

export default Layout;`


**-----HEADER-----**
`import React, { Component } from 'react';
import { Link } from 'react-router-dom';

class Header extends Component {
	authButton() {
		return <button> Sign In </button>;
	}

	render() {
		return (
			<nav className="navbar navbar-light">
				<ul className="nav navbar-nav">
					<li className="nav-item">
						<Link to="/">Home</Link>
					</li>
					<li className="nav-item">
						<Link to="/resources">Resources</Link>
					</li>
					<li className="nav-item"> {this.authButton()} </li>
				</ul>
			</nav>
		);
	}
}

export default Header;
`
