### ISSUE TITLE
Timetravel in redux devtools does not work

### ISSUE THREAD

**Issue by micha149** [ReactTraining/react-router#4761]
## Version
react-router: 4.0.0
react-router-redux: 5.0.0-alpha.3

## Test Case
http://jsbin.com/pibofis/edit?html,js,output
(Open output in new tab to see url changes)

## Steps to reproduce
1. Open redux devtool extension in chrome devtools
2. Use navigation a few times
3. Jump back to any previous action in redux devtools

## Expected Behavior
Browser url will be updated/reseted and router renders the corresponding component

## Actual Behavior
Nothing happens

**Comment by v12** [comment]
See #4717. It's not yet "fixed". 😉

**Comment by micha149** [comment]
ah, I just searched over the issues and can't find any matching…
