### ISSUE TITLE
Question regarding non-route children of <Switch/>

### ISSUE THREAD

**Issue by matthewrobb** [ReactTraining/react-router#4762]
I have discovered and found it very useful that any component that's a direct descendant of `<Switch/>` can carry route-like props and be treated like a route. I was curious if this is intentional or if it's something I should avoid? If this is functionality you all plan on continuing to support I would recommend adding documentation for it because it is VERY useful!

Anyway, loving v4, your `wholeTeamShouldReceiveProps()` 😛

**Comment by timdorr** [comment]
It's intentional, mainly because it's actually more of a hassle to check the type of every element before checking it's props. While intended for `<Route>` and `<Redirect>`, it's valid to use it for any other element with a `path` or `from` prop.

**Comment by matthewrobb** [comment]
The reason this turns out to be very helpful is because I have an inner/outer model for routing where at any given layer I want to do:
```js
<Switch>
  <Subview path={`${match.url}/mount-path-1`} />
</Switch>
```
And then each subview defines it's sub-routes. It just works really nicely and if it is an intended feature it may be worth documenting.

**Comment by pshrmn** [comment]
It is not documented because while it works, it is not officially supported.

**Comment by timdorr** [comment]
This behavior could break in the future. There's no plans to explicitly break it, but we may need to at some point to support a refactor or other reasons. So, don't rely on it in the future. BTW, you can do this just as easily (and it's a little more explicit about what's going to happen):
```jsx
<Switch>
  <Route path={`${this.props.path}/mount-path-1`} component={Subview}/>
</Switch>
```

**Comment by matthewrobb** [comment]
@timdorr But you cannot easily pass params to Suvbiew in that case or render to it's children.

**Comment by timdorr** [comment]
```jsx
<Switch>
  <Route path={`${this.props.path}/mount-path-1`} render={() => <Subview foo="bar"/>}/>
</Switch>
```
