### ISSUE TITLE
StaticRouter adds trailing slash to basename

### ISSUE THREAD

**Issue by emjaksa** [ReactTraining/react-router#4764]
## Version
4.0.0

## Test Case
User StaticRouter  with a basename with trailing slash.

## Steps to reproduce
    
```
   const children = renderToString(
      <StaticRouter basename="/the-base/" location={req.url} context={context}>
        <App/>
      </StaticRouter>
    );
```

## Expected Behavior
<a href="/the-base/about' />

## Actual Behavior
<a href="/the-base//about' />

Causes a discrepancy between the server and client markup. BrowserRouter removes trailing slash. 

```
Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
(client) f="/the-base/about" data-reactid="5"><
(server) f="/the-base//about/" data-reactid="5">
```

**Comment by timdorr** [comment]
Just don't add a trailing slash on your basename. 

In the DOM, it can resolve the duplicate slashes to one, hence the render difference. That's how it handles a elements. But the basename is intended not to have that trailing slash, as the paths created underneath it will always be prefixed with a slash themselves.

If you want to see the trailing slash removed automatically, that would make for a good PR.
