### ISSUE TITLE
nesting children routes not working

### ISSUE THREAD

**Issue by scniro** [ReactTraining/react-router#4767]
How in the world does one use **nested routes.** The following worked well in previous versions...

    <Route path='/stuff' component={Stuff}>
      <Route path='/stuff/a' component={StuffA} />
    </Route>

Upgrading to 4.x throws the following warning...

 > Warning: You should not use <Route component> and <Route children> in the same route; <Route children> will be ignored

What in the heck is going on here? I've scoured the docs for hours and can not successfully get nested routes working. Why did something good go away?

Also, just about every tutorial, stack question, and general online resource instructs to nest these components as above. So, I guess that's all trash. Why did this leave and why is there no concise way to demo nested routes in the docs.

[this.](http://i0.kym-cdn.com/entries/icons/facebook/000/004/592/my-brain-is-full-of-fuck.jpg)

**Comment by pshrmn** [comment]
Nested routes are rendered inside of the parent component. See the `<Topics>` component of the [basic example](https://reacttraining.com/react-router/web/example/basic) for reference.

**Comment by scniro** [comment]
This is the worst project I've used my entire programming career. Your link doesn't help. Please provide an example to translate my example above to v4.x api compliance, if you feel so inclined.

**Comment by KraigWalker** [comment]
That'll be a very short career then... 😶

**Comment by scniro** [comment]
@KraigWalker lol thanks for the most non-constructive and annoying comment ever

**Comment by pshrmn** [comment]
If you take a closer look, you will see that what I linked shows exactly what you're trying to do. You can also check out the documentation of the `<Route>` component for more information.

Unfortunately, that is the extent of what I am going to say here. I don't mind helping people and providing some code snippets, but I have to draw the line somewhere and the tone of your comments has certainly crossed it.

**Comment by ryanflorence** [comment]
We just updated to version 4 last week, we need some good release notes ASAP (I'll do it) and need some upgrades guides.

Also, you don't have to upgrade. Just install 3.x.
