### ISSUE TITLE
matchPath ignoring queryString

### ISSUE THREAD

**Issue by brielov** [ReactTraining/react-router#4768]
Hi, I'm messing arround with server side rendering and I've noticed that matchPath works well with express' req.url but when I throw in a query string it stops matching. Is this intentional behavior or am I doing something wrong?

Without query: `{ path: '/topics', url: '/topics', isExact: true, params: {} }`
With query `null`

**Comment by pshrmn** [comment]
`<Route>`s only match a location's pathname.
