### ISSUE TITLE
The documentation example is not working

### ISSUE THREAD

**Issue by tashburn** [ReactTraining/react-router#4769]
I get the following errors

> 
> warning.js:36 Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in.
> 
> invariant.js:44 Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in.
>     at invariant (invariant.js:44)
>     at ReactCompositeComponentWrapper.instantiateReactComponent [as _instantiateReactComponent] (instantiateReactComponent.js:77)
>     at ReactCompositeComponentWrapper.performInitialMount (ReactCompositeComponent.js:367)
>     at ReactCompositeComponentWrapper.mountComponent (ReactCompositeComponent.js:258)
>     at Object.mountComponent (ReactReconciler.js:46)
>     at ReactCompositeComponentWrapper.performInitialMount (ReactCompositeComponent.js:371)
>     at ReactCompositeComponentWrapper.mountComponent (ReactCompositeComponent.js:258)
>     at Object.mountComponent (ReactReconciler.js:46)
>     at mountComponentIntoNode (ReactMount.js:104)
>     at ReactReconcileTransaction.perform (Transaction.js:140)
> 

With the following code (very close to the example)

```javascript
import React from 'react'
import ReactDOM from 'react-dom'

import { createStore, combineReducers, applyMiddleware } from 'redux'
import { Provider } from 'react-redux'

import createHistory from 'history/createBrowserHistory'
import { Route } from 'react-router'

import { ConnectedRouter, routerReducer, routerMiddleware, push } from 'react-router-redux'

// import reducers from './reducers' // Or wherever you keep your reducers

// Create a history of your choosing (we're using a browser history in this case)
const history = createHistory()

// Build the middleware for intercepting and dispatching navigation actions
const middleware = routerMiddleware(history)

// Add the reducer to your store on the `router` key
// Also apply our middleware for navigating
const store = createStore(
  combineReducers({
    // ...reducers,
    router: routerReducer
  }),
  applyMiddleware(middleware)
)

const Home = () => (<div>Home</div>)
const About = () => (<div>About</div>)
const Topics = () => (<div>Topics</div>)

ReactDOM.render(
  <Provider store={store}>
    { /* ConnectedRouter will use the store from Provider automatically */ }
    <ConnectedRouter history={history}>
      <div>
        <Route exact path="/" component={Home}/>
        <Route path="/about" component={About}/>
        <Route path="/topics" component={Topics}/>
      </div>
    </ConnectedRouter>
  </Provider>,
  document.getElementById('app')
)

```

However, it does work if I replace `ConnectedRouter` with `Router`

Any ideas?

**Comment by metelski** [comment]
Hey @tashburn! Just spent 2 hours struggling with the same... and finally it worked (at least error messages disappeared and the page was rendered).

Try installing `5.0.0-alpha.3` which is the most recent version. I used `yarn` instead of `npm`, as it seems that npm is listing `4.0.8` as the latest and this one will not work with React Router 4.

**Comment by timdorr** [comment]
react-router-redux needs some serious work. I haven't had time to get to it lately, so I wouldn't use it just yet. The skeletal structure is there for something good, but we have yet to nail the internals. I've got some ideas for it I hope to get out there soon. Sorry for the mess in the meantime!

**Comment by tashburn** [comment]
I understand -- thanks for the note.

**Comment by tashburn** [comment]
@metelski Thanks for the idea!

**Comment by blord-fullscreen** [comment]
Any update on this? The documentation still says to use `<ConnectedRouter>`, which is broken. Thanks.

**Comment by amackintosh** [comment]
Are we not to use ConnectedRouter still?

Mine is still detonating wholesale after `npm install react-router-redux@next`

I was just looking for the `store.dispatch(push())`

**Comment by amackintosh** [comment]
Oops, that actually does work. I just forgot to import `browserHistory` into my root, so those errors above are generated by passing undefined into `ConnectedRouter`. We can probably gain a bit of DX if someone were to attack that. :)

I changed it to:
```
<ConnectedRouter history={browserHistory}>
```

and it's actually working beautiful now and even fixed some issues I had before I mass refactored.

If anyone tries this, put this in your root file:
```
store.dispatch(push('/somescreen'))
```

You will see when it's working if you are listening to redux:
```
{type: "@@router/CALL_HISTORY_METHOD", payload: {…}}
logger.js:2 {type: "@@router/LOCATION_CHANGE", payload: {…}}
```

**Comment by ShawnXiao105** [comment]
@metelski It really works!!! Thanks for the notes!
