### ISSUE TITLE
Redirect inside the "connected" React component

### ISSUE THREAD

**Issue by PavelPolyakov** [ReactTraining/react-router#4773]
## Version
4.0.0

## Test Case
Here is the bug reproduction repository:
https://github.com/PavelPolyakov/react-router-redirect-vs-connect-issue

## Steps to reproduce
In order to reproduce - run the application and click the button.
The button opens the `Route` with the [component](https://github.com/PavelPolyakov/react-router-redirect-vs-connect-issue/blob/master/app/pages/SectionPage.js).
The component is connected to the redux store using `@connect` decorator. In case decorator is present - the redirect happens, but the correct route is not rendered. In case the decorator is commented out - the new route is not rendered at all.

The idea is to put user to the `/contact-information` page, which redirects him further to the `/contact-information/1` router.

I want to state that `/contact-information/1` route works, if I refresh the browser window.

## Expected Behavior
https://monosnap.com/file/1lt8nLGzOOjf2N9RJomFuNasGx6wIJ

## Actual Behavior
https://monosnap.com/file/ehMRPqlp00XY1CkHUZN6id2L4hnTCm

Please, let me know if I do something incorrectly.

Regards,

**Comment by timdorr** [comment]
Check out the blocked updates guide for how to do connected components right: https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/guides/blocked-updates.md

**Comment by PavelPolyakov** [comment]
@timdorr 
Thanks for pointing me to this doc. However, I can't get it :)

Could you, please, point me how the solution should look like for the case I provided as the example?

I tried to apply `location` to the `Switch`. I thought that location is updated and the component is rerendered then. But it doesn't work.
https://github.com/PavelPolyakov/react-router-redirect-vs-connect-issue/commit/a36cf58bae7c52e27f60653a5183ca001c9f32a2

And the location property remains the same:
![image](https://cloud.githubusercontent.com/assets/839290/24057017/2a9e7910-0b46-11e7-8b52-a1d5ac513d18.png)

Probably I'm missing something.

Regards,

**Comment by pshrmn** [comment]
@PavelPolyakov You aren't passing the route props to `<SectionPage>`
```js
// Change this
render={() => <SectionPage/>}
// to this
render={(props) => <SectionPage {...props} />}
// or this
component={SectionPage} />
```

**Comment by PavelPolyakov** [comment]
@pshrmn 
works like a charm!
thank you!
