### ISSUE TITLE
BrowserRouter match in 4.0.0 Warning: React.createElement: type is invalid

### ISSUE THREAD

**Issue by danielkhan** [ReactTraining/react-router#4777]
I'm on 4.0.0 and I'm running into `Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined.`error.

```js
return( // Warning 2 points to here
      
        <BrowserRouter>  
          <div>
            <Nav/>
            <Match exactly pattern="/download/*" component={SomeComponent}/> // Warning 1 points to here
          </div>
        </BrowserRouter>
       
    );
```

Any help is highly appreciated.

**Comment by pshrmn** [comment]
You are using syntax from the v4 alpha. `<Match>` no longer exists. You should be using the [`<Route>`](https://reacttraining.com/react-router/core/api/Route) component.

```js
<Route exact path='/download/*' component={SomeComponent}/>
```

**Comment by pmdownie** [comment]
I have the same problem here.
Tried using Route but get the same error.

**Comment by zcserei** [comment]
I'm also getting the same error, figured out that the API has changed since the alpha, but the current one is also producing this error.

**Comment by Kielan** [comment]
prematurely closed issue
