### ISSUE TITLE
create-react-app with NodeJS backend not loading routes instead forwarding request to backend

### ISSUE THREAD

**Issue by DVassilev** [ReactTraining/react-router#4779]
I am using create-react-app as described here with a NodeJS backend: https://fullstackreact.com/articles/using-create-react-app-with-a-server/

I just attempted to implement react-router but unfortunately if I try to go http://url/myroute it will attempt to load that path from the backend, not the frontend. Is there any way to avoid this?

Thanks,
Daniel

**Comment by BTMPL** [comment]
You need to configure your server to support browserHistory correctly:

https://github.com/ReactTraining/react-router/blob/v3/docs/guides/Histories.md#browserhistory

**Comment by DVassilev** [comment]
@BTMPL Thank you, this now loads the frontend correctly.
