### ISSUE TITLE
Redirect and Link are not working with mobx-react observer

### ISSUE THREAD

**Issue by mdanishs** [ReactTraining/react-router#4781]
I have a route which redirects after checking a condition like this

```
<Route exact path="/" render={()=>(
Store.isFirstTime ? <Redirect to="/intro" /> : <Home state={Store}/>)}/>

```
The url changes when the condition is true but the component is not mounted. The rest of the component code is as below.

```
render() {
    return (
      <div>
        ...
        <Route exact path="/" render={()=>(
          Store.isFirstTime ? <Redirect to="intro" /> : <Home state={Store} />         
        )} />
        <Route path="/intro" render={()=>(<IntroWizard state={Store.userInfo}/>)} />
        <Route path="/home" render={()=>(<Home state={Store}/>)} />
        <Route render={()=>(<h1>404 Not Found</h1>)} />
        <Footer />
      </div>
    );
  }
```
My App Component is contained with in the BrowserRouter like thi
```
ReactDOM.render(<BrowserRouter>
    <App/>
</BrowserRouter>,
  document.getElementById('root')
);
```

My App component is a observer from mobx-react and it is exported as shown below
```
let App = observer(class App { ... })
export default App
```

To verify the issue I created another project and tried to reproduce the issue, I have committed that code to this repository  [mobxtest](https://github.com/mdanishs/mobxtest/)

What should be done to use redirects and links with mobx observers?

**Comment by taurose** [comment]
It seems your problem is that react-mobx implements `shouldComponentUpdate` (sCU), thus blocking any re-renders after the URL changed. There's a (WIP?) guide about this [here](https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/guides/blocked-updates.md).

Since the sCU implementation of react-mobx compares the props, you can fix it by passing `location` as a prop using `withRouter` or a pathless `Route`:

```js
const App = withRouter(observer(class App extends Component { ... } ));
// or
ReactDOM.render(
  <BrowserRouter>
    <Route component={App} />
  </BrowserRouter>,
  document.getElementById('root')
);
```

**Comment by JohnTasto** [comment]
I've been banging my head against this for most of the day! I hope that guide makes it into the docs soon - it is essential for anyone using Redux or MobX. It solved my problem. Thank you.

**Comment by jozsi** [comment]
I've had the same problem:
```jsx
  <Provider store={store}>
    <ConnectedRouter history={history}>
      <Layout>
        <Switch>
          <Route path="/login" component={Login} />
          <PrivateRoute exact path="/" component={Home} />
        </Switch>
        {DevTools.enabled && <DevTools />}
      </Layout>
    </ConnectedRouter>
  </Provider>
```

`PrivateRoute /` was redirecting to `Route /login`, the URL has changed however the `Login` component did not render.

I needed to decorate `Layout` with `withRouter` in order to get it working:
```js
export default withRouter(connect(mapStateToProps, mapDispatchToProps)(Layout));
```

Thanks, @taurose ! 

P.S.: This should be more properly documented.
