### ISSUE TITLE
Repo for documentation website?

### ISSUE THREAD

**Issue by IljaDaderko** [ReactTraining/react-router#4787]
Hey guys, I've been working around this for last 2h https://reacttraining.com/react-router/native/guides/animation and am stuck mid way, mainly at where I know what sort of animation I need to trigger and when, but not being able to trigger one after another (i.e. fade out parent, fade in child). Documentation mentions that example is available in source code for the doc website, but I wasn't able to find it anywhere, has it been taken down or is it still available somewhere?

**Comment by pshrmn** [comment]
The source code for the documentation websites is in the [`react-router-website`](https://github.com/ReactTraining/react-router/tree/master/packages/react-router-website) package.
