### ISSUE TITLE
In 4.0.0, <Redirect /> `exact` and `strict` props are not documented

### ISSUE THREAD

**Issue by aldendaniels** [ReactTraining/react-router#4791]
Version: **4.0.0**

The `<Switch>` component consumes some of the props passed to `<Redirect>` including `exact` and `strict`, but these later are not included in the documentation for `<Redirect>`.

**Comment by timdorr** [comment]
That's because they don't apply to a plain `<Redirect>`, only the one within a `<Switch>`. It's actually an undocumented and unsupported feature that you can put *any* component inside of a Switch, as long as it has the right props.

**Comment by aldendaniels** [comment]
> It's actually an undocumented and unsupported feature that you can put any component inside of a Switch, as long as it has the right props.

I don't think it's true that this feature is undocumented. From the docs:

> **from** - A pathname to redirect from. This can be used to match a location when rendering a <Redirect> inside of a <Switch>.
\- https://reacttraining.com/react-router/web/api/Redirect

`from` is documented, but not `exact` or `strict`. I found this to be confusing. Admittedly, the fact that `<Switch>` strips the props from its children is generally surprising.

**Comment by timdorr** [comment]
I merged in #4826 after this issue was filed.
