### ISSUE TITLE
Navigation after loading async route doesn’t get cancelled by a later navigation

### ISSUE THREAD

**Issue by andrewbranch** [ReactTraining/react-router#4799]
I think I've found a bug, but maybe you disagree—let’s see! Sorry for the wordy title; I found this really hard to explain concisely. Feel free to edit the title if you can say it better.

## Version
2.0.0, 2.8.1, 3.0.2

## Test Case
http://jsbin.com/botepafeta/1/edit?html,js,output

## Steps to reproduce
1. Click on "Async Page" link
2. Within 2 seconds, change your mind and click on "Sync Page" link

## Expected Behavior
1. Nothing happens while "Async Page" is loading
2. After you change your mind and click on "Sync Page," that page loads immediately and the UI updates accordingly
3. Nothing else happens

## Actual Behavior
1. Nothing happens while "Async Page" is loading
2. After you change your mind and click on "Sync Page," that page loads immediately and the UI updates accordingly
3. After the two second timeout completes, you are transitioned to "Async Page," even though you obviously changed your mind about wanting to go there.

Obviously, this usually happens with asynchronously loaded chunks with Webpack instead of `setTimeout`. It's also worth noting (probably obvious to many) that Link has nothing to do with it—you can use your browser back/forward buttons to navigate and see the same behavior.

**Comment by timdorr** [comment]
Cancelling out the async action is left up to the user, as you may implement them in multiple ways. Here's a good guide of how to do that with Promises (but can be adapted to other forms): https://github.com/facebook/react/issues/5465#issuecomment-157888325

**Comment by andrewbranch** [comment]
@timdorr I was under the impression that there would be trouble if the callback argument wasn’t eventually called.

Before opening this issue, I attempted a solution that listened for later navigation changes, and if by the time `getComponent` was called, the transition was irrelevant, it would call `cb(null, null)` in an attempt to cancel or do nothing. In short, that didn't work.

Are you saying that the correct solution is just "never call the callback"?
