### ISSUE TITLE
fallback route handler always redirects on initial load

### ISSUE THREAD

**Issue by tracker1** [ReactTraining/react-router#4803]
## Version
4.0.0

## Test Case
      <Router history={this.props.history}>
        <div style={{ width: '100%', height: '100%' }}>
            <Route exact path="/dashboard" component={Dashboard} />
            <Route exact path="/jobs/query" component={Query} />
            <Route path="*" render={() => (<Redirect to="/dashboard" />)} />
        </div>
      </Router>

## Steps to reproduce

Load with a path of /jobs/query

## Expected Behavior

I expect it to display the component that matches the initial route/path the browser is in.

## Actual Behavior

On first load, it will *ALWAYS* redirect to /dashboard, even if it should be matching against /jobs/query, for example.

**Comment by pshrmn** [comment]
Use a [`<Switch>`](https://reacttraining.com/react-router/web/api/Switch).

**Comment by tracker1** [comment]
@pshrmn thanks, I found it shortly after posting my issue... could have sworn I'd closed it myself.
