### ISSUE TITLE
Persistent query string after route transition

### ISSUE THREAD

**Issue by sag1v** [ReactTraining/react-router#4810]
Hi, it would be a great if react-router will pass on the query string when rendering a new route.
For example,
**Current behavior:**
`/home?lang=fra` -> `/about`

**Desired behavior:**
`/home?lang=fra` -> `/about?lang=fra`

**Use case:**
When some one wants to share or save a URL after some routing took place, the URL will loose it's query params and if the application initializing it's store base on these query params it will fallback to defaults.
Given the links from the example above, if some one is browsing my app in french, and my app is initializing the `state.lang` based on this URL's query `lang=?` , after one route transition it will loose this param. when this URL will be saved to favorites or shared with someone else and this someone will open this "query string'less" URL the app will get a default `state.lang`.

It would be nice to have a flag that tells `react-router` whether or not pass on the query string.

**Comment by pshrmn** [comment]
In general, I think that I would prefer to have the language encoded in the `pathname`, but that may not be possible for you.

To make sure that every link includes the current `search` string, I would just create a function that returns location objects. The returned object's `search` property would be the current location's `search` string.

```js
const withSearch = (to, location) => {
  const navLocation = typeof to === 'string' ? { pathname: to } : { ...to }
  navLocation.search = location.search
  return navLocation
}

// usage

// Mynav is rendered by a <Route>, so it is passed the current location
const MyNav = ({ location }) => (
  <nav>
    <ul>
      <li><Link to={withSearch('/', location)}>Home</Link></li>
      <li><Link to={withSearch('/about', location)}>About</Link></li>
    </ul>
  </nav>
)
```

I have not actually tested that, so it is likely you will need to modify it.

**Comment by sag1v** [comment]
i would like to centralize this behavior, would it be possible to wrap the route itself?
for example something like this:
```
const withSearch = ({ search }) => { // don't know if search params are available on Route creation
  return (
    <Route path={`/?${search}`} name="App" component={App}>
      <IndexRoute name="Home Page" component={HomePage} />
      <Route path={`/home?${search}`} name="Home Page" component={HomePage} />
       <Route path={`/home?${search}`} name="Home Page" component={HomePage} />
    </Route>
  )
}
```
