### ISSUE TITLE
[native] Link replace and to props are passed to the children component

### ISSUE THREAD

**Issue by MatthieuLemoine** [ReactTraining/react-router#4812]
## Version
react-router-native 4.0.0

## Description

I'm using react-router-native with [react-native-web](https://github.com/necolas/react-native-web). When I use the ```Link``` component, the ```replace``` and ```to``` props are passed down through the tree until it reaches  the ``button`` html tag which raise an [Unknown prop warning](https://facebook.github.io/react/warnings/unknown-prop.html).

![react-router-native](https://cloud.githubusercontent.com/assets/8517072/24208331/a94e09b6-0f23-11e7-9edd-56378b68c1b2.png)

## Proposal

I'm not sure if it's intended to pass down those props as the Link's ``render`` method is already extracting the ```component``` prop.
```javascript
render() {
  const { component: Component, ...rest } = this.props
  return <Component {...rest} onPress={this.handlePress}/>
}
```

If not, the solution will be to extract those props as well : 
```javascript
render() {
  const { component: Component, to, replace, ...rest } = this.props
  return <Component {...rest} onPress={this.handlePress}/>
}
```

**Comment by timdorr** [comment]
Could you make a PR for this?

**Comment by MatthieuLemoine** [comment]
Sure!
