### ISSUE TITLE
function-as-child in NavLink

### ISSUE THREAD

**Issue by VinSpee** [ReactTraining/react-router#4815]
Hi! I'm loving v4! One of the concepts I really like is the ability to pass functions as children:

```jsx
<Route path="/talks/:slug/:subsection?">
  {({ match }) => (
    <Link
      to={`/talks/${match.slug}`}
      label="Up next"
    />
  )}
</Route>
```

I think this concept might also be useful for `<NavLink />`. I found myself desiring it when building a nav item like this:

```jsx
<NavLink
  exact
  to={to}
  className={tabClasses}
  activeClassName={tabActiveClasses}
  style={tabStyle}
>
  {({ active }) => (
    <div className={tabInnerClasses}>
      <span>
        {label}
      </span>
      <span className={active ? tabDetailActiveClasses : tabDetailClasses}>
        {detail}
      </span>
    </div>
  )}
</NavLink>
```

It's possible to use CSS to accomplish the custom classes, but what if I wanted to do something else that wasn't related to CSS? Is there an idiomatic way to accomplish this without a function-as-child? Am I over-thinking it?

**Comment by timdorr** [comment]
Tangentially related to #4625. Here are @ryanflorence's thoughts on it: https://github.com/ReactTraining/react-router/issues/4625#issuecomment-284948536

**Comment by VinSpee** [comment]
I certainly agree with not giving people a footgun, but I think this respects that because router still controls the surrounding tags / attributes of the `NavLink`

**Comment by ryanflorence** [comment]
Using Route and Link and skipping NavLink here makes the most sense to me. You can, ofc, make this pattern yourself in a component if you find it useful enough :)

**Comment by VinSpee** [comment]
Understood, and for posterity, here's how one might implement that: http://codepen.io/VinSpee/pen/qrYXdg?editors=0110

```jsx
const Navi = ({ to, children }) => (
  <NavLink
    exact
    to={to}
  >
    <Route>
      {(props) => {
        const matches = (props.location.pathname === to)
        return (
          <div
            style={{
              fontWeight: matches ? 700 : 200
            }}
           >
            {children}{matches ? '*' : ''}
          </div>
        )
      }}
    </Route>
  </NavLink>
);
```

**Comment by ryanflorence** [comment]
I was on my phone but wanted to post an example:

```jsx
const NavLinkWithChildren = ({
  to,
  exact = false,
  children
}) => (
  <Route path={to} exact={exact}>
    {({ match }) => (
      <NavLink to={to} {...rest}>
        {children(match)}
      </NavLink>
    )}
  </Route>
)
```

**Comment by VinSpee** [comment]
nice, great pattern. I updated the codepen and checked to allow non-function children too: http://codepen.io/VinSpee/pen/qrYXdg?editors=0110

thanks!
