### ISSUE TITLE
Handle prop updates to Redirect Component

### ISSUE THREAD

**Issue by ankitpopli1891** [ReactTraining/react-router#4819]
### Feature request:
 - Handle prop updates to  [Redirect] Component

### Version
4.0.0

### Code Snippet:
```jsx

<Router>
    <View>
        <Redirect to={path}/>

        <Route path='/item1' render={() => (
            <Item1 />
        )}/>
        <Route path='/item2' render={() => (
            <Item2 />
        )}/>
        
        <Sidebar
            open={this.state.drawerOpen}
            items={items}
            onItemClick={this.onSidebarItemClicked}
        />
    </View>
</Router>

```
```js
onSidebarItemClicked = (itemId) => {
        this.setState({
            drawerOpen: false,
            itemId: itemId,
            path: `/${itemId}`
        })
    }
```

The above example simply doesn't work since the `componentDidMount` will not be called again until we remove the component and re-render it, preventing react reconciler to re-use it. 

So, either we handle the props change and redirect automatically or we keep using a workaround like this:

```jsx
{  (renderRedirect) ? <Redirect to={path}/>: null }
```

I'm not sure if this was intentionally this way and was not meant to be implemented. I'm working on it [here] and will be happy to send a PR, if you guys approve this approach. It did solve my problem though.

[Redirect]: https://github.com/ReactTraining/react-router/blob/master/packages/react-router/modules/Redirect.js
[here]: https://github.com/ankitpopli1891/react-router/commit/9dc6c6f3f8a2c64dc80e0add553a7dc3c90fe95f

**Comment by timdorr** [comment]
A Redirect is meant as a once-off kind of component, where it will send your app to another location and most likely disappear from the tree. If it stays persistent and responded to updates, then you could very likely get into infinite loops of redirection. 

Instead, you should conditionally render it whenever it's needed and not leave it in the tree.

**Comment by ankitpopli1891** [comment]
@timdorr I get the point. I changed the way Redirect was being used and it helped. Thanks a lot for your time.
