### ISSUE TITLE
can't import hashHistory in .tsx file

### ISSUE THREAD

**Issue by fariyAhill** [ReactTraining/react-router#4820]
###  I got an error when I tried to import hashHistroy in .tsx file. I have installed `@types/react-router`
![react-router-error](https://cloud.githubusercontent.com/assets/12928690/24249373/f67f699c-100d-11e7-88f0-8e250a0a53bc.png)

### Here is the error message
` TS2305: Module ''react-router'' has no exported member 'hashHistory'.`

### And this is my tsconfig file and the version of react-router in package.json
`{
    "compilerOptions": {
        "target": "es5",
        "sourceMap": true,
        "noImplicitAny": true,
        "module": "commonjs",
        "jsx": "react",
        "experimentalDecorators": true,
        "removeComments": true,
        "preserveConstEnums": true,
        "moduleResolution": "node",
        "allowSyntheticDefaultImports": true,
        "allowJs": true
    },
    "include": [
        "./src/**/*"
    ],
    "exclude": [
        "node_modules",
        "**/*.spec.ts"
    ]
}`

` "react-router": "^3.0.2"`
`"@types/react-router": "^4.0.0`

**Comment by timdorr** [comment]
You have the wrong typings installed. Get ones for react-router 3.0.2 installed.

**Comment by jakelly** [comment]
I'm using `"react-router": "^4.1.1"`.  How do I know which types apply to this version?  Do the versions correlate with one another?  If so, I don't see version 4.1.1 types yet.
