### ISSUE TITLE
React Native scroll restoration

### ISSUE THREAD

**Issue by sospedra** [ReactTraining/react-router#4823]
I don't really get exactly how the scroll restoration spec implementation works. But looks like it depends on some browser env pieces. Currently I'm making a RN app and we use `react-router@v4` with the `MemoryRouter` is it possible to implement some sort of scroll (`ScrollView`) restoration from the router?

Thanks

**Comment by timdorr** [comment]
There are many ways to implement scrolling in a native app, so there isn't a single API for us to target. Instead, your route component should handle this with the React lifecycle. componentDidMount seems like a good place to implement something like it. @pshrmn's ScrollIntoView might offer some inspiration: https://github.com/pshrmn/rrc/blob/master/src/ScrollIntoView.js

**Comment by sospedra** [comment]
That's exactly what I did alongside with `ScrollView` `onScroll`. Many thanks for the reply.
