### ISSUE TITLE
router.history.push() changes URL but not the actual page

### ISSUE THREAD

**Issue by aneagoie** [ReactTraining/react-router#4824]
## Version
4.0.0

when wrapping a `<Link>`  and adding a `onClick` prop,
```
<Link
  to={to}
  onClick={this.beforeNavigate}
>
 {this.props.children}
</Link>
```

in `this.beforeNavigate`, `this.context.router.history.push()` exists, but when I call it with a custom path, the url changes but the page view doesn't. 

The reason I created this issue is because this behaviour only happens when I upgraded form `react-router-dom4.0.0-beta.6` to `react-router-dom4.0.0`. When using the `this.router.push` in the beta version, everything works. The app is wrapped in a `<BrowserRouter>` component

Curious to see if this may be a bug.

**Comment by pshrmn** [comment]
https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/guides/blocked-updates.md
