### ISSUE TITLE
Consider adding support for arrays/regexps as Route paths

### ISSUE THREAD

**Issue by fruchtose** [ReactTraining/react-router#4825]
It looks like `react-router`'s internal implementation relies on [path-to-regexp](https://github.com/pillarjs/path-to-regexp) to translate `Route` paths into regular expressions for matching URLs in `matchPath`. `path-to-regexp` currently allows the path argument to be a string, an array of strings, or a regular expression. Currently the docs specify that routing must be done with string paths. 

 I understand that exposing this implementation detail may not be ideal, but consider that [Express supports regular expressions in routes](https://expressjs.com/en/4x/api.html#router.METHOD) and [Koa's docs are transparent about its use of path-to-regexp](https://github.com/alexmingoia/koa-router#routergetputpostpatchdelete--router).

**Comment by pshrmn** [comment]
This was discussed and rejected in #4551.
