### ISSUE TITLE
Suggestions about how to use redial with RR4? since match function is not exist

### ISSUE THREAD

**Issue by idangozlan** [ReactTraining/react-router#4829]
Hi, 

Any suggestions about how to use `redial` with RR4? since `match` function is not exist, I can't use it anymore on RR4.

Maybe i'm missing something, but `match` function is not exist anymore, and it's a part of the `redial` module usage.

Thanks

Redial:
https://github.com/markdalgleish/redial
@markdalgleish

**Comment by timdorr** [comment]
Look at the data loading part of the server rendering guide: https://reacttraining.com/react-router/web/guides/server-rendering
