### ISSUE TITLE
Read out url parameters in page

### ISSUE THREAD

**Issue by jwamsterdam** [ReactTraining/react-router#4834]
Hi, I am currently deeplinking to a page which gets routed by react router.
I link in the following way:

```
<RaisedButton
    label="Submit"
    primary={true}
    keyboardFocused={true}
    onTouchTap={() => this.props.history.push('/results?origin=123')}
/>
```

What I cant really find in the documentation is how to read out the value of 'origin' in my results component. Any tips?

**Comment by timdorr** [comment]
https://github.com/ReactTraining/react-router/issues/4527#issuecomment-279541628

**Comment by jwamsterdam** [comment]
Is an external library like qs needed for this? Is this not out-of-the box functionality of React-Router v4?

**Comment by timdorr** [comment]
Yes, because all the libraries differ in implementation and we don't want to prescribe a best behavior. Plus, it reduces the router footprint significantly for those that don't use query parsing.
