### ISSUE TITLE
Query has been removed after first click on Link

### ISSUE THREAD

**Issue by optimatex** [ReactTraining/react-router#4842]
## Version
4.0.0

## Steps to reproduce
1) create a Link component like that
```
<Link to={{ pathname: '/homepage', query: {...oldQuery, image: 11} }}>
    Image capture
</Link>
```
2) Click the first time on this Link
3) Then check the HREF atribute of DOM <a> element

## Expected Behavior
After the first click DOM <a> element should be `<a href='/homepage?album=1&image=11'>`
## Actual Behavior
But actually it is `<a href='/homepage?album=1&image=11'>`

**Comment by pshrmn** [comment]
The `query` property of location objects is no longer supported. It would take me a while to explain all the details, but basically it boils down to there being query objects are not standardized and React Router/history not actually have an internal use for `query` objects. Instead, you should pick your own query package to parse and stringify `location.search`.

I wrote [`qhistory`](https://github.com/pshrmn/qhistory) for people who really want `query` support. It works basically the same way that `useQueries` did with `history` v2/3.

**Comment by optimatex** [comment]
Thank u for this clarifications!
so, i'll consider your library
