### ISSUE TITLE
react-router-dom  not working

### ISSUE THREAD

**Issue by waqaskhan540** [ReactTraining/react-router#4846]
I have following implementation of "react-router-dom", but  I am not able to get it working. can someone guide me what's the underlying issue.

**App.jsx**
`
```
import React from "react";
import Main from "../components/Main";
import Home from "../components/Home";
import { BrowserRouter, Match, Miss, Link } from 'react-router-dom';


  const App = () => (
   
   <BrowserRouter>
        <div>
            <Match exactly pattern="/" component={Main} />
            <Match pattern="/home" component={Home} />
        </div>
    </BrowserRouter>
  );

export default App;
```
`

**Index.jsx**
````
import React from "react";
import ReactDOM from "react-dom";
import Main from "./components/Main";
import Home from "./components/Home";

import Page from './components/Page';
import App from "./config/App";


ReactDOM.render( 
   <App/>,
    document.getElementById('app')
);
````

I get the following error :

>
![dfdf](https://cloud.githubusercontent.com/assets/15784870/24353982/9d55dbc2-1309-11e7-92da-47517857c656.PNG)

**Comment by overthemike** [comment]
I ran into this as well. I got it working by using Route instead of Match:

    import React from "react";
    import Main from "../components/Main";
    import Home from "../components/Home";
    import { BrowserRouter, Route, Link } from 'react-router-dom';


    const App = () => (
        <BrowserRouter>
            <div>
                <Route exact={true} path="/" component={Main} />
                <Route path="/home" component={Home} />
            </div>
        </BrowserRouter>
    );

    export default App;

**Comment by pshrmn** [comment]
As @overthemike said, you should be using the [`<Route>`](https://reacttraining.com/react-router/core/api/Route) component. `<Match>` and `<Miss>` were components from the alpha that were removed. `<Route>` and `<Match>` are essentially the same thing, but with slightly different prop names (`exactly -> exact`, `pattern -> path`).
