### ISSUE TITLE
React-router-dom & browser refresh 

### ISSUE THREAD

**Issue by vkouk** [ReactTraining/react-router#4848]
Hello everybody 
This topic may has been already posted but I haven't find yet something similar 
I would like to have a help in react router and browsers
I got version 4 and when browser does a reload I get that page for ex /login didn't found 
How this can be fixed in react-router-Dom version 4?

My route it's :

```js
ReactDOM.render(
    <BrowserRouter>
        <div>
            <Route component={TicketAppInterface}/>
            <Switch>
                <Route path="/login" component={Login}/>
                <Route path="/register" component={Register}/>
                <Route path="/" component={Home}/>
            </Switch>
        </div>
    </BrowserRouter>,
    document.getElementById('ticketappinterface')
); //render
```

**Comment by vkouk** [comment]
ReactDOM.render(
    <BrowserRouter>
        <div>
            <Route component={TicketAppInterface}/>
            <Switch>
                <Route path="/login" component={Login}/>
                <Route path="/register" component={Register}/>
                <Route path="/" component={Home}/>
            </Switch>
        </div>
    </BrowserRouter>,
    document.getElementById('ticketappinterface')
); //render

**Comment by vkouk** [comment]
Sorry for multiple posts please remove the above

https://pastebin.com/zpfq4BBL

**Comment by pshrmn** [comment]
Are you using a server or hosting static content? The issue you described typically happens with static content. `<BrowserHistory>` only works when you have a server that can handle requests for _any_ url. You will either need to use a server or switch from `<BrowserHistory>` to `<HashHistory>`.

---
Use three backticks on separate lines before and after your code to include multiline code snippets. (The `js` specifies to higlight the code as javascript).

\`\`\`js
const variable = 'let it be known'
\`\`\`

is formatted as

```js
const variable = 'let it be known'
```

**Comment by vkouk** [comment]
I currently use static localhost but I could make a server by my own in my home 

Could you please give me an example in the code I gave you before how it could be used with browser history ?

**Comment by pshrmn** [comment]
You wouldn't modify the above code. You would just add a server to handle requests. Basically it would use a wildcard to catch all requests (besides the ones for static files) and return your `index.html`.

You'll have to search around for implementation details (probably check stackoverflow), but that is the idea.
