### ISSUE TITLE
Broken server-side example

### ISSUE THREAD

**Issue by safm** [ReactTraining/react-router#4850]
## Version
4.0.0

## Test Case
http://jsbin.com/sacerobuxi/edit?html,js,output

## Steps to reproduce
I am following the example mentioned [here](https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/docs/guides/server-rendering.md)

When I try to import StaticRouter in my server.js file I am getting undefined.

```js
import { StaticRouter } from 'react-router';
console.log( StaticRouter )
//undefined 
```

**Comment by pshrmn** [comment]
Are you certain that you have the correct version of React Router installed? I'm guessing if you looked at `node_modules/ready-to-wear/package.json` you'd see something other than `version: 4.0.0`.

**Comment by safm** [comment]
Sorry my bad. My `package.json` has 4.0.0 however my `node_modules/react-router/package.json` was 2.8.1.

Thanks for your help. Closing this issue.
