### ISSUE TITLE
Routes do not respond/listen as expected when react-redux is present

### ISSUE THREAD

**Issue by ralphsmith80** [ReactTraining/react-router#4860]
## Version
4.0.0

## Test Case
https://github.com/ralphsmith80/react-router-and-redux

## Steps to reproduce
Run the app enter text in the `input` and press enter key. Note that the `ThirdView` text is not rendered as expected. If you refresh the page it will be rendered, but it will not be removed once you navigate to a new route, `Home` or `FirstView` links.

Additionally I had to add `withRouter` to [`App.js`](https://github.com/ralphsmith80/react-router-and-redux/blob/master/src/App.js#L53) which just seems plain weird.

## Expected Behavior
The `Route` should update even when using `react-redux`.

## Actual Behavior
I'm still trying to nail this all down in my larger application, but from the example app I'm providing it appears that every component that gets wrapped in a `connect` function needs to also be wrapped in a `withRouter` function.

## Other Notes
I'm working on updating from `4.0.0-alpha.6` and this is working with the alpha version.
I'm not using redux to store my routing although I did try that out just as a sanity check, but that did not fix the issue.
I have not used a previous version of `react-router` so I don't know if it should play with `react-redux` even if I'm not trying to make them play together. Seems like an issue if they can't work independently in the same app.

**Comment by iuliaL** [comment]
@ralphsmith80 
"it appears that every component that gets wrapped in a connect function needs to also be wrapped in a withRouter function."
I've just bumped into this and for now this solved my routing issue which I think was the exact same as yours, here is my repo https://github.com/iuliaL/diagonistician-ReactJS-Express-Mongoose-RestAPI
When on /list, can't go to /question/:id or to /list/add if I don't wrap Application component with withRouter; the path changes accordingly but no actual switch happens
I think it's something about the react-router version 4

**Comment by pshrmn** [comment]
Wrapping every connected component in `withRouter` is not optimal. See this guide for more information https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/guides/blocked-updates.md

**Comment by ralphsmith80** [comment]
@pshrmn, Certainly not optimal, but based on the doc you linked it sounds like the right approach.

> What happens when the component isn't being rendered by a `<Route>` and the component rendering it does not have the `location` in its variable scope?
You can wrap a component with the `withRouter` higher-order component and it will be given the current `location` as one of its props.

Of course I could be a little more specific and grep through each redux implementation I have, there's a lot, and pick out just the ones that really need it, but at the end of the day I don't want to think about that. And there's the issue of when I add another nested child and it doesn't update as expected because I didn't just wrap the parent with the `withRouter` HOC.

To that end I plan to add a HOC for the `react-redux` `connect` function that just always gets wrapped with `withRouter`. 

```
import { connect } from 'react-redux'
import { withRouter } from 'react-router-dom'

const withRouterConnect = (...connectArgs) => 
  (component) => withRouter(connect(...connectArgs)(component))
  
export default withRouterConnect

// Example usage: same as react-redux connect
// export default connect(mapStateToProps, mapDispatchToProps)(TodoApp)
```

**Comment by pshrmn** [comment]
When I rewrote that guide, I was intending to steer people away from using `withRouter` everywhere, but if it works for you and you aren't noticing performance implications, I can understand the convenience.

At the very least, do not do that with connected components that are already being rendered by a `<Route>`.

```js
// doing this
const MyComponent = withRouterConnect(...)(WrappedComponent)
const App = () => (
  // ...
  <Route path='/some-place' component={MyComponent} />
  // ...
)

// produces this
<Route path='/some-place'>
  <Route>
    <ConnectWrapper>
      <WrappedComponent />
    </ConnectWrapper>
  </Route>
</Route>
```

**Comment by damianobarbati** [comment]
@pshrmn what is a decent way to solve this **problem**? 
How to have the router rerender components after url change?
Lots of coders are having this issue, navigation/history/push are simply broken.

**Comment by pshrmn** [comment]
@damianobarbati The guide linked above describes what to do to deal with blocked updates.

**Comment by damianobarbati** [comment]
@pshrmn I tried to do that but nothing happen so far: "push" changes url in browser but router is not rendering it.

Using:
```
"react-router": "^4.0.0",
"react-router-dom": "4",
"react-router-redux": "next",
```
Store created as:
```
import { createStore, combineReducers, applyMiddleware } from 'redux';
import { composeWithDevTools } from 'redux-devtools-extension';
import { routerMiddleware, routerReducer, syncHistoryWithStore } from 'react-router-redux';
import thunkMiddleware from 'redux-thunk';
import promiseMiddleware from 'redux-promise';
import createLogger from 'redux-logger';

import { REHYDRATE } from 'redux-persist/constants';
import { persistStore, autoRehydrate } from 'redux-persist';
import createActionBuffer from 'redux-action-buffer';

import config from '../../config/config.js';
import auth from '../auth/auth.reducer.js';
import notification from '../notification/notification.reducer.js';
import forms from '../form/form.reducer.js';

const defaultReducers = { config: () => config, auth, notification, forms, routing: routerReducer };

const getStore = ({ reducers, history }) => {
    reducers = { ...defaultReducers, ...reducers };
    const finalReducer = combineReducers(reducers);
    const historyMiddleware = routerMiddleware(history);
    const loggerMiddleware = createLogger();
    const finalMiddleware = applyMiddleware(
    	thunkMiddleware,
    	promiseMiddleware,
    	historyMiddleware,
        loggerMiddleware,
    	createActionBuffer(REHYDRATE),
    );
    return createStore(finalReducer, composeWithDevTools(finalMiddleware, autoRehydrate({ log: false })));
};
export default getStore;
```
Router created as:
```
import React from 'react';

import { ConnectedRouter } from 'react-router-redux';
import { Switch, Route, Redirect } from 'react-router-dom';
import createHistory from 'history/createBrowserHistory'

export const history = createHistory({ basename: '/user' });

import Auth from '../auth/Auth';
import NotFound from './pages/notfound/NotFound';
import Layout from './pages/layout/Layout';
import Home from './pages/home/Home';

export default class Router extends React.Component {
    render() {
        return (
            <ConnectedRouter history={history}>
                <Layout>
                    <Switch>
                        <Route exact path="/" render={() => <Redirect to="/home" />} />
                        <Route exact path="/auth/:token?" component={Auth} />
                        <Route exact path="/home" component={Home} />
                        <Route path="*" component={NotFound} />
                    </Switch>
                </Layout>
            </ConnectedRouter>
        );
    }
}
```
Attempt to redirect after sign in:
```
import { push } from 'react-router-redux';

export const setToken = async ({ token }) => {
    return async (dispatch) => {
        dispatch({ type: SIGN_IN, value: token });
        dispatch(push('/home'));
    };
};
```
Components:
```
@withRouter
@connect((state, props) => ({})
export default class Auth extends React.Component {...}

@withRouter
@connect((state, props) => ({})
export default class Home extends React.Component {...}
```

What am I doing wrong here? 😞

**Comment by d-leeg** [comment]
I must say that the solution presented in the guide, though clear, is very inadequate.

This makes react-router an unacceptable companion to any moderately sized site that uses `redux` or `mobx`, which is a huge number of sites.

One can not afford the extra wrapping suggested in the guide simply to inject unneeded props just to circumvent the blocking. On top of the ugliness, it completely ruins modularity: whenever a component somewhere up the hierarchy gets connected to the redux-store, all nested components, no matter how deep, get blocked and stop routing. This is even a larger problem when different teams are responsible for these components.

I do not see why `react-router` should suffer from this deficiency where other libraries do not. E.g., a connected `react-redux` component does not get blocked if an ancestor is modified to connect too. Why can't react-router adopt the same solution?
One just needs to have `Route` listen to changes in `history` and force a redraw if the location changes; react-redux's `connectAdvanced` does this by simply calling `this.setState(dummyState)`.

This is a simple fix, and I can not see what disadvantage it has that should prevent its implementation.
