### ISSUE TITLE
React Router examples in ES6 Class Components

### ISSUE THREAD

**Issue by Numel2020** [ReactTraining/react-router#4862]
## My Views

My view is from a complete novice perspective to the react and react-router ecosystem, so after going through the various examples demonstrated on [reacttraining.com](https://reacttraining.com/react-router/web/guides/quick-start) I feel as though the overview perspective of react-router is more geared towards developers who have had previous experience of routing from those who see this as a completely new thing.

## 1. Both Functional and Class based examples
I feel the JavaScript functional type components do a nice and simple job of showing the user how to route. However in react you also have class components so it would also make sense to have class examples for those who are learning or already accustomed to using React in this fashion.

## 2. A barebones Tutorial
Tutorials do wonders in giving the reader a perspective on how something works, I see scope for this as a must have feature on the site.
For example maybe a small single page application were you take the user step by step in constructing normal routes and sub routes.

## 3. More commentary on the Api features with working examples.
The Api is so vast, so maybe small real world examples of what an Api feature does and how it can be implemented would help us better visualise and understand it’s usage.

## 4. A proper video introduction into react-router.
Something small and sharp which outlines, what the router is and why its so great for react developers.

Thank you for reading

Mr Numel

**Comment by timdorr** [comment]
This is more geared towards ReactTraining, not this library itself. If @ryanflorence, @mjackson, or @tylermcginnis want to respond here, they can. But I think something in the form of an email to them would be your best bet.

**Comment by ryanflorence** [comment]
Yeah, great feedback. I've got a guide that will check some of those boxes and we're working on a free course that will check off some more. We've got a couple projects at work ahead of the free course though :/ we'll launch it as soon as we get through these other things.

**Comment by Numel2020** [comment]
Hi Ryan

Thanks for the reply, I am looking forward to seeing some of my points
implemented, by the way if you need any help on feedback or further
improvements then please give me a call.

many tnxs
