### ISSUE TITLE
Location bar not updating with the URL when routing in default android browser

### ISSUE THREAD

**Issue by manikandan-ramar** [ReactTraining/react-router#4865]
## Version
2.x

## Description
When trying to route  a react application in default android browser on the Android versions 4.1.1 & 4.2.2, location bar in browser not showing the new url. Refreshing the page actually reloads the expected page, but if we try to copy a url of particular page it fails with previous urls.

**Comment by timdorr** [comment]
That version of Android's browser doesn't support `history.pushState`. You'll have to use a hash history for those versions.
