### ISSUE TITLE
BrowserRouter basename is case sensitive

### ISSUE THREAD

**Issue by nomad3k** [ReactTraining/react-router#4866]
## Version
4.0.0

## Test Case
Use BrowserRouter and set the basename property.  Routes are not case-sensitive, but the Router is.

## Steps to reproduce
    <Router basename='/xxx'>
        <Route path='/yyy' component={Something} />
    </Router>

## Expected Behavior
Should match all of the following:

    http://example.com/xxx/yyy
    http://example.com/xxx/YYY
    http://example.com/XXX/yyy
    http://example.com/XXX/YYY

## Actual Behavior
    http://example.com/xxx/yyy - PASS
    http://example.com/xxx/YYY - PASS
    http://example.com/XXX/yyy - FAIL
    http://example.com/XXX/YYY - FAIL

While the route is not case sensitive the router basename is.

**Comment by timdorr** [comment]
Hmm, this is interesting. We don't include the basename in our usage of path-to-regexp, so that's why there's a difference. Should be as simple as toLowercase()'ing the pathname when matching.

**Comment by pshrmn** [comment]
Fixed with https://github.com/ReactTraining/history/pull/459
