### ISSUE TITLE
@5.0.0-alpha.4 - No syncHistoryWithStore method

### ISSUE THREAD

**Issue by Manuelandro** [ReactTraining/react-router#4869]
Hi, i've just installed the mentioned version and noticed that there is no method "syncHsitoryWithStore", as you can see in the index.js file.

How to handle with it?

```
import _ConnectedRouter from './ConnectedRouter';
export { _ConnectedRouter as ConnectedRouter };

export { LOCATION_CHANGE, routerReducer } from './reducer';
export { CALL_HISTORY_METHOD, push, replace, go, goBack, goForward, routerActions } from './actions';
import _routerMiddleware from './middleware';
export { _routerMiddleware as routerMiddleware };
```

Notice that i needed to install this version cause of this issue:
https://github.com/ReactTraining/react-router/issues/4694

**Comment by timdorr** [comment]
Please read the readme. The API has changed.

**Comment by andreareginato** [comment]
I might be missing something but I can't see `syncHistoryWithStore` on both README.md and CHANGES.md. Could you please indicate where are those information living?

Thanks in advance

**Comment by tech4him1** [comment]
@timdorr I'm trying to understand the differences here -- do I have to use the middleware to replace this, or is it only necessary if I want to use it in Redux actions?

**Comment by donsalari** [comment]
which documentation are you referring to?
