### ISSUE TITLE
react-router-redux 5x : Integration with Immutable.js

### ISSUE THREAD

**Issue by aelmanaa** [ReactTraining/react-router#4874]
## Version
react-router-redux 5x

## Problem description
I updated react-router-redux so it is compatible with the last version of react-router (4x).
The problem is that syncHistoryWithStore doesn't seem to be supported anymore. I get the following error message:

Uncaught TypeError: (0 , _reactRouterRedux.syncHistoryWithStore) is not a function
I'm Immutable.js to have an immutable state. 

## Steps to reproduce
Use Immutable.js to have an immutable state.  For the routing reducer, you should have the following code (at least that was the case with react-router-redux 4x):
const history = syncHistoryWithStore(hashHistory, store, {
  selectLocationState (state) {
    return state.get('routing').toObject()
  }
})

## Expected Behavior
routing synchronized with the store. Thereore we should be able to perform time traveling using redux dev tool
## Actual Behavior
error in the console:
Uncaught TypeError: (0 , _reactRouterRedux.syncHistoryWithStore) is not a function

**Comment by timdorr** [comment]
We changed the API. Please read the readme.

**Comment by steffenmllr** [comment]
I'm having the same issue and can't really find the part in the readme or in the code where it is possible to get or set an immutable.

@aelmanaa did you solve it?

**Comment by couturecraigj** [comment]
@timdorr does this mean we no longer need to use `syncHistoryWithStore` Because the README says nothing regarding these changes and how to deal with them.

**Comment by seedlinktech-william** [comment]
@couturecraigj from the [source code](https://github.com/ReactTraining/react-router/blob/master/packages/react-router-redux/modules/index.js), I think `syncHistoryWithStore` is not support yet.

**Comment by Tarnadas** [comment]
This also seems very unclear to me.

Do we still have to use our own reducer or does the provided one support immutability?

**Comment by JustFly1984** [comment]
I use 5.0.0-alpha.6 without syncHistoryWithStore.

It feels like new API doesn't require to use store to keep history.

```
import {
  // immutable
  IMap,

  // redux
  createStore,
  compose,
  applyMiddleware,

  // 'history/createBrowserHistory'
  createBrowserHistory,

  // react-router-redux
  routerMiddleware,

  // redux-thunk
  thunk
} from '../../vendor'

import reducers from '../reducers'

export const history = createBrowserHistory()

const configureStore = (initialState = IMap()) => {
  console.log('store.development')

  if (history) {
    history.listen(location => {
      console.log('location.pathname: ', location.pathname)
    })

    return createStore(
      reducers,
      initialState,
      compose(
        applyMiddleware(routerMiddleware(history), thunk),
        window.devToolsExtension
          ? window.devToolsExtension()
          : fn => fn()
    ))
  }

  return createStore(reducers, initialState)
}

export const store = configureStore()
```

this is my store.development.js

For anybody wondering what a hell is
```
import {
...
} '../../vendor'
```
I have an answer: I import all dependencies in single file vendor.js for code splitting.
If you use code splitting on route level, you can't gain the bundle size reduce in prod build without vendor code splitting.

You can have multiple vendor files, and separate frequently updated packages from not so frequently, you can gain better browser caching experience. Also it is a good practice to separate development dependencies to separate file, so you do not bundle dev deps to production build.

**Comment by maackle** [comment]
The above comment doesn't help me. I still see there being a lack of explanation of how to deal with the removal of `selectLocationState`. That seems to be the crucial component that lets redux know about state changes in the context of using an ImmutableJS store. Here's my problem, using Immutable.Map as my store:

In my app, the initial render of any <Switch> correctly takes the location into account, but any subsequent use of history.push() or even the `push` provided by `import { push } from 'react-router-redux'` only causes the URL to change, but react-router does not notice, and the view does not change.

**If I refactor my app to use a plan JS object instead of an Immutable.Map, the routing works perfectly.**

There is a missing piece here. How do we specify how react-router can access the necessary state to know what route it's on?

**Comment by SnowSea-Dream** [comment]
Did you solve this problem?

**Comment by brianscroggins24** [comment]
Anything new with this issue. I'm using redux-immutable and can't get the routing to update along with history. Any solutions created?

**Comment by suzdalnitski** [comment]
Actually using `react-router-redux` with `immutable.js` is even simpler with version 5.

`syncHistoryWithStore` has been deprecated. `ConnectedRouter` will make sure to keep the store in sync with history. It does this by listening to history, and dispatching `LOCATION_CHANGE` actions.

In version 5 the store is being accessed in two places only:
1. `routerReducer`
2. `createMatchSelector`

To get things working the only thing one has to update is the `routerReducer`:
```js
import {Map}             from 'immutable';
import {LOCATION_CHANGE} from 'react-router-redux';

const initialState = Map({
                             location: null,
                             action:   null
                         });

export function routerReducer(state = initialState, {type, payload = {}} = {}) {
    if (type === LOCATION_CHANGE) {
        const location = payload.location || payload;
        const action   = payload.action;

        return state.set('location', location)
                    .set('action', action);
    }

    return state;
}
```

You don't have to patch `createMatchSelector` if you're not using it in your project.
