### ISSUE TITLE
[react-router-config]: how to pass `extraProps` to children ?

### ISSUE THREAD

**Issue by geminiyellow** [ReactTraining/react-router#4880]
## Version
4.0.0

## Steps to reproduce

v3: i use `React.cloneElement(children, extraProps)` to pass extra props to next component, 
but, v4, `react-router-config`, there is no way to do it. 

is a design or bug ?

**Comment by timdorr** [comment]
This is by design. You should have dedicated route components that can pass props into their children. Or you can use a function that takes the extra props and returns a component with them applied to it.

**Comment by lunikernel** [comment]
@timdoor would you mind providing a little code example please to show how to do this?

I'm trying to migrate from v3 to v4 and I'm getting lost.
