### ISSUE TITLE
Match blocking server side rendering with onEnter hook (under high load)

### ISSUE THREAD

**Issue by josepapaianni** [ReactTraining/react-router#4882]
## Version
3.0.3

## Steps to reproduce
Universal app setup, using onEnter hook to defer the page rendering until data is loaded, requests intervals should be shorter than data fetching/async task.

Probably the problem is [here]( https://github.com/ReactTraining/react-router/blob/v3/modules/TransitionUtils.js#L11).

## Expected Behavior
Match callback should be called on every request after the async task.

## Actual Behavior
Match callback is executed after all requests, seems that all async callbacks are queued in an unique stack.

**Comment by timdorr** [comment]
You shouldn't use onEnter for data loading. Instead, get your components from match and use static properties to determine what data is needed before you renderToString.
