### ISSUE TITLE
leading slash is added even for full qualified urls. 

### ISSUE THREAD

**Issue by joeuy** [ReactTraining/react-router#4885]
## Version
4.0.0

## Test Case
http://jsbin.com/jocakuxufi/1/edit?html,js,output

## Steps to reproduce
1) open jsbin test case
2) note  `<base href="https://cdnlocation.com">` in html file
3) note `<BrowserRouter basename={window.location.origin}>` in js file
4) hover over `about link` and observe left bottom corner to see the href to follow in chrome browser.

## Expected Behavior
url to follow should be http://jsbin.com/about

## Actual Behavior
url to follow is https://cdnlocation.com/http://jsbin.com/about

Leading slash is added always, even when basename is https://*
If you think behavior should change I can submit a PR. 

Scenario this will enable: all relative links in page (images, scripts, styles, etc) go to cdn, all react links go to my server. 

thanks.

**Comment by timdorr** [comment]
Basename can't be a full URL. If you want to link externally, just use an a tag.

**Comment by joeuy** [comment]
@timdorr  please consider: THIS IS NOT AN EXTERNAL LINK!

**the scenario is as follows:** 
we want to integrate the app with a cdn. So:
- scripts, styles, images, etc would come from cdn. 
- index.html  file will come from server. 

To achieve this we are using relative paths everywhere and specifying `<base href="https://cdnlocation.com/">`. This way all resources (images, scripts, styles, etc) go to cdn  without requiring to stamp the cdn host everywhere. This is very helpful because when you change cdn host, you don't have to go around and modify templates, scripts, styles, etc. you just change the index.html file and everything else works. 

**The problem is**: we need to make all our internal hrefs full URLs, otherwise the browser will prefix them with baseurl. React router does not support this today.

In my opinion if the URL is full qualified, it is good thing to skip the leading slash react router is appending. It will enable a variety of scenarios like the one I am describing. 

Thanks.

**Comment by timdorr** [comment]
This isn't supported by history.pushState, which is what's under the hood here. You can't push a path to a different origin. The browser won't allow it.

**Comment by joeuy** [comment]
@timdorr thanks for the reply.
Its not a different origin, it will be the current window.location.origin!

Here is a PR that illustrates the required change in history project: https://github.com/ReactTraining/history/commit/83667c9bc1fb93a0dd7ec812a5f084092e2151a6

**Also here is an example that further ilustrates the scneario/problem:**
http://jsbin.com/pidosoquto/1/edit?html,js,output

Things to note in the example: 
1. all image links are relative
2. we specify the cdn host name using   `<base href="https://c1.staticflickr.com">`
3. Images are loading correctly !!!
4. links are broken. instead of referring to `http://null.jsbin.com/about`, it will point to `https://c1.staticflickr.com/http://null.jsbin.com/about` thats because react-router-dom always add leading slash, and then the browser adds the base href.

**Comment by pshrmn** [comment]
Using the `<base>` tag for cdns is at best a hack. Paths to external resources should be URLs. 

From [whatwg](https://html.spec.whatwg.org/multipage/semantics.html#the-base-element)

> The base element allows authors to specify the document base URL for the purposes of parsing URLs, and the name of the default browsing context for the purposes of following hyperlinks. The element does not represent any content beyond this information.

**Comment by joeuy** [comment]
@pshrmn Thanks for the reply. 
Could you point me to any drawbacks on this approach?

From your quote to whatwg, you could also say we want the cdn to be the default browsing context. And it would be nice to specify another one in the router.

**Comment by scriby** [comment]
I've used the approach of setting base URL to a CDN for a few projects.

It ends up being a pretty clean solution because you can just use relative paths for all your static assets, and it will work in dev, on your test server, and in prod without having to do anything but change your base URL.

The only special thing you need to make the approach work is to make sure all actual links within your page are fully qualified. It's usually just a simple config switch in the router to set the base URL to the site's origin, assuming the router isn't smart enough to figure out that's what it should be using on its own.

**Comment by pshrmn** [comment]
> the name of the default browsing context **for the purposes of following hyperlinks**

The drawback is that you break the purpose of the browsing context and force links to be full URLs.

Anyways, this is really about `history`, not `react-router`, so this discussion would be more pertinent over there.
