### ISSUE TITLE
CALL_HISTORY_METHOD should include route params

### ISSUE THREAD

**Issue by rclai** [ReactTraining/react-router#4887]
The route change action payload looks like this:

```
{
type: "@@router/LOCATION_CHANGE"
payload
    pathname: "/some-route/3298/sub-page/220/4813/thing"
    search: ""
    hash: ""
    action: "PUSH"
    key: "hdu2xe"
    query: {}
}
```

Is there any reason why there is no `params` object in the action payload object? I feel like I'm re-doing work that's already done inside React Router by having to manually parse the `pathname`.

**Comment by timdorr** [comment]
We don't know​the parameters because they are relative to the route that matched. Multiple routes can match, so we don't know which one gets priority and which one's props to put in state, which is global.
