### ISSUE TITLE
Feature: keep routes in memory

### ISSUE THREAD

**Issue by halfninja** [ReactTraining/react-router#4888]
It would be useful if there were an option for rendered routes to be kept in memory/DOM when moving to a new route, so that returning to it is fast. In some apps, particular pages/routes can be inescapably slow to render and if memory usage is low it would make the app a lot faster if it could just hide and show rather than re-render from scratch.

I know this would have a few knock-on issues with no longer being able to treat the component lifecycle as being equivalent to page load/unload, plus deciding where to put the inactive routes in the DOM.

**Comment by timdorr** [comment]
This isn't how React itself works. When the component unmounts, it's gone. We don't have control over that. 

You could display: none a node with the render prop and match argument. But that will have unintended side effects most likely.
