### ISSUE TITLE
"#" is added to url, and child routes cannot be accessed.

### ISSUE THREAD

**Issue by ldlchina** [ReactTraining/react-router#4894]
I'm using react-router as below. 
Problems:
1. The '#' is included in the url, for example, I entered "http://localhost:3000/" in browser address bar, it's changed to "http://localhost:3000/#/".
2. Entered "http://localhost:3000/#/login" in browser address bar, it still displayed the content of "http://localhost:3000/#/".

I'm using Chrome v56 and Node v6.10.0.
Here are the react node modules I installed.
"react": "^15.4.1",
"react-dom": "^15.4.1",
"react-router": "^3.0.0",

How to remove the "#"?
How to make the child routes work?

Thanks

```
import React from 'react';
import ReactDOM from 'react-dom';
import { Router, Route, hashHistory } from 'react-router';
import Home from './views/home';
import Login from './views/login';
import './css/index.css';

//const browserHistory = createBrowserHistory();

ReactDOM.render(
    <Router history={hashHistory}>
        <Route path="/" component={Home}>
            <Route path="/login" component={Login}/>
        </Route>
    </Router>, document.getElementById('root')
);
```

**Comment by pshrmn** [comment]
1. You are using a hash history, which encodes the location in the hash fragment of a URI. Switch to a browser history if you want clean paths.
2. Nested routes should be relative, so remove the leading slash (`login` not `/login`).

**Comment by ldlchina** [comment]
Hi @pshrmn ,
I searched and also tried the code as below. But It did not work.
1.Changed to use browserHistory, the # was removed from "http://localhost:3000/#/", it's ok. But entered "http://localhost:3000/login", the route was not found. Entered "http://localhost:3000/#/login", it displayed the same content of "http://localhost:3000".
2.Remove the leading slash (login not /login), it did not work.

```
import React from 'react';
import ReactDOM from 'react-dom';
import { Router, Route, browserHistory } from 'react-router';
import Home from './views/home';
import Login from './views/login';
import './css/index.css';

//const browserHistory = createBrowserHistory();

ReactDOM.render(
    <Router history={browserHistory}>
        <Route path="/" component={Home}>
            <Route path="login" component={Login}/>
        </Route>
    </Router>, document.getElementById('root')
);

```

**Comment by pshrmn** [comment]
@ldlchina Your server needs to be able to handle any requested pathname. Please see https://github.com/ReactTraining/react-router/blob/v3/docs/guides/Histories.md#configuring-your-server for some examples of how to do this.

Also, searching your error leads to this page, which might help http://stackoverflow.com/questions/10216395/error-failed-to-lookup-view-in-express

**Comment by ldlchina** [comment]
@pshrmn ,

Ignore the error about express above, it's nothing with react-router, I have resolved it.

Thanks for clue from link: https://github.com/ReactTraining/react-router/blob/v3/docs/guides/Histories.md#configuring-your-server. It makes a progress.

Now "http://localhost:3000/login" can be opened. But it still displays the content of "http://localhost:3000". Any other suggestions?


P.S. There is a typo in the link https://github.com/ReactTraining/react-router/blob/v3/docs/guides/Histories.md#configuring-your-server. "response.sendFile" should be "response.sendfile".

**Comment by pshrmn** [comment]
Is your `<Home>` component rendering `this.props.children`? I put together this quick example with your provided route configuration. http://codepen.io/pshrmn/pen/bqzWBy

Also, `response.sendFile` is Express v4 API. I believe that `sendfile` is from an earlier version.

**Comment by ldlchina** [comment]
![login](https://cloud.githubusercontent.com/assets/4963202/24584159/8c90fc7c-1796-11e7-87fa-72fc0a6d3b1a.PNG)
with `this.props.children`, the Home and Login contents are displayed on login page. See screenshot attached.

I'm using express v4.2.0.

Also attached my code.
[store.zip](https://github.com/ReactTraining/react-router/files/888162/store.zip)

Thanks again for prompt response.

**Comment by ldlchina** [comment]
@pshrmn , Is there a good example about the integration of Express and React together without Redux. I would like to make a simple and clear template with Express and React.

**Comment by pshrmn** [comment]
Right. So the way that nested routes work is that the matched parent routes are also rendered. If you want your `<Home>` component to only render when the route is exactly `/`, you should use an `<IndexRoute>`.

```js
<Route path='/' component={App}>
  <IndexRoute component={Home}/>
  <Route path='login' component={Login}/>
</Route>
```

The `<App>` would just be a simple component. You can either just render `this.props.children` or possibly use it for layout.

```js
class App extends React.Component {
  render() {
    return this.props.children ? this.props.children : null
  }
}
```

Unless you're doing server side rendering, the example in that `histories` doc is really all you need to do in Express. If you do want to do server side rendering, you can check out [the server rendering guide](https://github.com/ReactTraining/react-router/blob/v3/docs/guides/ServerRendering.md) for more details.

Also, if you are just learning React Router and don't have a particular need for v3, I would recommend using React Router v4. It is a different approach to routing because it doesn't actually use a centralized configuration object. It is a more "React-like" approach to routing and I find it a lot more enjoyable to use.

**Comment by ldlchina** [comment]
That's it. Thanks @pshrmn . I learnt a lot.
