### ISSUE TITLE
Add render function prop to <Switch>

### ISSUE THREAD

**Issue by wacii** [ReactTraining/react-router#4899]
The problem is properly performing react-controlled route transitions ~~using React-Motion~~. You can mostly do this by passing a children function prop to `<Route>`, but there is no guarantee  on how many such components will be rendered. Which is not generally what you want.

So I propose extending `<Switch>` with a render function prop. This would be called with the associated component, if specified. If the matching `<Route>` instead uses its own render function, that would take precedence.

I'm willing to write this myself, just wanted to run it by you all first.

Its use would look something like this.

```js
import { spring, TransitionMotion } from "react-motion";

function TransitioningRoutes() {
  return (
    <Switch render={renderWithTransitions}>
      <Route path="/a" component={ComponentA} />
      <Route path="/b" component={ComponentB} />
      <Route component={ComponentDefault} />
    </Switch>
  );
}

function renderWithTransitions(Component, props) {
  const { pathname } = props.location;
  
  return (
    <TransitionMotion
        styles={{ key: pathname, data: { Component }, style: { opacity: spring(1) } }}
        willEnter={{ opacity: 0 }}
        willLeave={{ opacity: spring(0) }}>
      {interpolatedStyles => (
        interpolatedStyles.map(({style, data: { Component: TransitioningComponent }}) => (
          <TransitioningComponent {...props} style={style} />
        ))
      )}
    </TransitionMotion>
  );
}
```

**Comment by tomatau** [comment]
Could you use a similar technique but instead make a custom wrapper component/hoc around the Route component with your transition logic and use that within your switch?

**Comment by wacii** [comment]
Ah, I messed up the example. The children function of <TransitionMotion> was wrong. Lemme edit that.

<TransitionMotion> doesn't just animate the current component selected by <Switch>, but transitions the previous components out as well. Which wasn't really apparent before.

**Comment by pshrmn** [comment]
It would probably be simpler to write your own implementation of a `<TransitionMotionSwitch>`. Extending `<Switch>` to handle `react-motion`'s non-`children`-friendly syntax seems unnecessary.

If you take a look at [the `<Switch>` source code](https://github.com/ReactTraining/react-router/blob/master/packages/react-router/modules/Switch.js) you will see that it is just a simple loop over it's children. For an example of an alternative implementation, you can check out [`rrc/ConfigSwitch`](https://github.com/pshrmn/rrc/blob/master/src/ConfigSwitch.js). I got an implementation of this working with `rrc/wrapSwitch` that I can show you if you need help, but it is quite ugly and I have no plans to actually clean it up.

**Comment by wacii** [comment]
This isn't necessarily specific to React-Motion. The same example, this time using `<ReactCSSTransitionGroup>`.

```js
function TransitioningRoutes() {
  return (
    <Switch render={renderWithTransitions}>
      <Route path="/a" component={ComponentA} />
      <Route path="/b" component={ComponentB} />
      <Route component={ComponentDefault} />
    </Switch>
  );
}

function renderWithTransitions(Component, props) {
  const { pathname } = props.location;
  const items = [<Component key={pathname} {...props} />];
  
  return (
    <ReactCSSTransitionGroup transitionName='example'>
      {items}
    </ReactCSSTransitionGroup>
  );
}
```

**Comment by pshrmn** [comment]
I'm not trying to say that `<Switch render>` should not be a thing, but it is more complicated than what you have described.

Your examples seem to imply that the `render` function would render a route's `component`. This is incorrect. You need to render a `<Route>`. This has to be done to ensure that the proper context values are set. With `<TransitionMotion>`, this means that you have to transform a `<Route component>` into a `<Route render>` in order to pass the `style` to the component.

```js
function routeWithStyle(element, style) {
  const { component, ...rest } = element.props
  // ignore Redirects, also this will not work if
  // the route isn't <Route component>
  if (element.type !== Route || !component) {
    return element
  }
  return React.createElement(Route, {
    ...rest,
    render: function(routeProps) {
      return React.createElement(component, { ...routeProps, style })
     }
  })
}

function renderWithTransition(element) {
  
  return (
    <TransitionMotion
        styles={{ key: element.props.location.pathname, data: { element }, style: { opacity: spring(1) } }}
        willEnter={{ opacity: 0 }}
        willLeave={{ opacity: spring(0) }}>
      {interpolatedStyles => (
        interpolatedStyles.map(({style, data: { element }}) => (
          routeWithStyle(element, style)
        ))
      )}
    </TransitionMotion>
  );
}
```

The `<CSSTransitionGroup>` example you provided is already possible by wrapping the `<Switch>` with a `<CSSTransitionGroup>`. That said, there _is_ value in being able to render the `<CSSTransitionGroup>` inside of the `<Switch>` if you need to use the `match` object as the key.

```js
const App = () => (
  <Switch
    render={(route) => (
      <CSSTransitionGroup transitionName='example'>
        { React.cloneElement(route, { key: route.props.computedMatch.url }) }
      </CSStransitionGroup>
    )}
  >
    <Route path="/a" component={ComponentA} />
    <Route path="/b" component={ComponentB} />
    <Route component={ComponentDefault} />
  </Switch>
)
```

**Comment by wacii** [comment]
The proposal was limited to `<Route component>` to keep the discussion simple, more about the feature than the implementation. That being said, I totally missed `<Route>` updating context. I guess that's there to support nested/recursive routes?

Isn't the `<CSSTransitionGroup>` example only possible otherwise by using keys to force a remount? Is that a documented use? Do you know if it will still be supported post fiber? I'm not necessarily opposed to creative key use, but forcing a component to remount never feels right to me.

Guess I'll write the code before discussing it. Until then.

**Comment by pshrmn** [comment]
`<CSSTransitionGroup>` relies on the `key` to determine which components are entering/leaving (see [`TransitionGroup.cWRP`](https://github.com/reactjs/react-transition-group/blob/master/src/TransitionGroup.js#L48)). I think that you could also just place a `key` on the `<Route>` and not have to worry about cloning.

It would only add one additional line to `Switch.render` (and edit two others), so it isn't a difficult change to implement, it is just a matter of figuring out if this is a desirable API to add. That would be a question for @ryanflorence and @mjackson to decide the answer to.

**Comment by wacii** [comment]
Huh, I guess there is no real difference between having the key on `<Switch>` and having the key on its `<Route>` child. At least not to `<ReactCSSTransitionGroup>`. Having the key on `<Route>` makes more sense to me as you are conceptually switching between different route elements, even if React thinks you are just updating the props of the same element. So the remounting feels more justified. Anyways...

Do you mean something like this?
```js
<Switch
    render={routeElement => (
      <ReactCSSTransitionGroup transitionName='example'>
        {routeElement}
      </ReactCSSTransitionGroup>
    )}>
  <Route key="a" path="/a" component={ComponentA} />
  <Route key="b" path="/b" component={ComponentB} />
  <Route key="default" component={ComponentDefault} />
</Switch>
```
Doesn't help React-Motion. And I'm not sure how I like having a library pass me an element. But it is straightforward, and accomplishes what I was after for `<ReactCSSTransitionGroup>`.

**Comment by pshrmn** [comment]
Yes, `<Route>`s inside of a `<Switch>` should be thought of as config objects, not actually `<Route>`s. That is why I wrote `<ConfigSwitch>`. When you think about it like that, then I think that it makes more sense to animate a `<Switch>`.

The React Motion issue is why I referred to it as not-`children`-friendly. You can check out the [codepen](http://codepen.io/pshrmn/pen/xqBXyL) I referenced above and see what I had to do to get it to work with my `wrapSwitch`. I might have made some parts more complicated than they need to be because I have never really used react motion, but that should get the basic idea across.
