### ISSUE TITLE
Publish a new beta version of react-router-config

### ISSUE THREAD

**Issue by mijamo** [ReactTraining/react-router#4904]
Hello,

The current version on NPM of **react-router-config** is `beta1` from march 11th. That version does not match the current doc and is fundamentally broken/not suitable for use because it does not support `strict` /  `exact` for routes, which was added in #4826 .

I think it would really be worth publishing a `beta2` version of that package right now to fix that.

**Comment by timdorr** [comment]
We'll publish something soon, I'm sure.
