### ISSUE TITLE
Example app of React Router v4 with Redux

### ISSUE THREAD

**Issue by idangozlan** [ReactTraining/react-router#4905]
Hi,

It would be very helpful to create an example of app using RR4 with redux.
I'm trying to create app with react+redux+RR4 inc. server side rendering and it's impossible with the current documentation.

Thanks!

**Comment by timdorr** [comment]
We're still in alpha on react-router-redux, so we don't want to build that out while the API is still in flux. We'll put something together eventually.

**Comment by Sawtaytoes** [comment]
@idangozlan 

This might be helpful to you regardless:
https://github.com/Sawtaytoes/Ghadyani-Framework-Webpack-React-Redux/tree/develop

[server.jsx](https://github.com/Sawtaytoes/Ghadyani-Framework-Webpack-React-Redux/blob/develop/src/server.jsx) is what you'll wanna look at.

**Comment by idangozlan** [comment]
@Sawtaytoes thanks but it's not what i'm looking for. 
Actually what i'm looking for is under development, as mentioned above, so the solution is still not exist till it will be stable :) 

Thanks.
