### ISSUE TITLE
react-router-redux:+ jest: Cannot find module './actions' from 'index.js'

### ISSUE THREAD

**Issue by hackhat** [ReactTraining/react-router#4907]
## Version
5.0.0-alpha.2

## Steps to reproduce

Setup jest;
Make a simple test;
In your source code include react-router-redux library;

## Expected Behavior

Should work.

## Actual Behavior

Doesn't work.

Error:

```
Cannot find module './actions' from 'index.js'
      
      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:169:17)
      at Object.<anonymous> (node_modules/react-router-redux/index.js:21:16)
```

Basically the package.json of react-router-redux has these lines:

```

  "main": "index.js",
  "module": "es/index.js",

```

Webpack requires the `es/index.js` file, while jest requires the `index.js`. The `index.js` contains this line:

```
var _actions = require('./actions');
```

But there is not relative file named `actions` or any folder named `actions` in the root of the module.

![image](https://cloud.githubusercontent.com/assets/11173732/24655098/4318ed38-192c-11e7-8249-1bf823420aa2.png)

**Comment by timdorr** [comment]
This was fixed in the latest alphas. Please update.
