### ISSUE TITLE
applyRouterMiddleware function is undefined

### ISSUE THREAD

**Issue by tahaykACF** [ReactTraining/react-router#4909]
Version
-
4.0.0

Test Case
-
Just import `applyRouterMiddleware` function:
`import {applyRouterMiddleware} from 'react-router';`

Steps to reproduce
-

Expected Behavior
-
get the applyRouterMiddleware function

Actual Behavior
-
got undefined instead

**Comment by timdorr** [comment]
This API doesn't exist in 4.0. It has an entirely new API. Please read the docs.
