### ISSUE TITLE
ConnectedRouter not in exported 'react-router-redux' api

### ISSUE THREAD

**Issue by theengineear** [ReactTraining/react-router#4912]
Excited to play around with `react-router@4.0.0`! I tried following the example in the react-router-redux docs, but am unable to import the `ConnectedRouter`.

## Version
4.0.8

## Steps to reproduce
```
import * as ReactRouterReduxApi from 'react-router-redux';
console.log(
    'ReactRouterReduxApi',
    JSON.stringify(Object.keys(ReactRouterReduxApi))
);
// ReactRouterReduxApi
// [
//     "syncHistoryWithStore",
//     "LOCATION_CHANGE",
//     "routerReducer",
//     "CALL_HISTORY_METHOD",
//     "push",
//     "replace",
//     "go",
//     "goBack",
//     "goForward",
//     "routerActions",
//     "routerMiddleware"
// ]
```

## Expected Behavior

The example in the documentation specifies the following import:

`import { ConnectedRouter, routerReducer, routerMiddleware, push } from 'react-router-redux'`

However, `ConnectdRouter` is not in the API (nor is it the default export) from `react-router-redux`.

~~It seems like it the export might be wrong in `index.js`?~~

~~I.e., instead of:~~

~~`export ConnectedRouter from './ConnectedRouter'`~~

~~Perhaps you need:~~

~~`export {default as ConnectedRouter} from './ConnectedRouter'`~~

**Comment by theengineear** [comment]
^^ On second thought. `export routerMiddleware from './middleware'` in `index.js` seems to work just fine 🤷‍♂️.

**Comment by pshrmn** [comment]
As noted by the ["we're moving" section](https://github.com/reactjs/react-router-redux#were-moving) in reactjs/react-router-redux, the code there (`react-router-redux@4.0.8`) is for previous versions of React Router. You should be using `react-router-redux@5.0.0-alpha.4` for React Router v4.

**Comment by theengineear** [comment]
Gotcha. Thanks for the prompt response!

Just as a heads up the react router docs point folks [here](https://github.com/reacttraining/react-router/tree/master/packages/react-router-redux) right now (from https://reacttraining.com/react-router/web/guides/redux-integration), which was why I tried this in the first place.

**Comment by pshrmn** [comment]
That is the correct link. I'm guessing that you just didn't add the `@next` tag when you installed?

**Comment by theengineear** [comment]
I must have done something dumb :(. I just repeated it and got the proper version. Sorry for all the trouble!
