### ISSUE TITLE
how to use react-router with the router's path contrast location.hash no location.pathname

### ISSUE THREAD

**Issue by ZHlambo** [ReactTraining/react-router#4914]
just like  `<Router path="/path"></Router>`  and now the url is http://****/#/path
因为这样服务器那边就不需要做处理，我只需要用 http://www.url.com/index.html 获取到文件，然后拼接参数 http://www.url.com/index.html#/path 进行路由导航了，angularjs好像就是这样子做的用hash来匹配路由路径

**Comment by pshrmn** [comment]
When you use the [`<HashRouter>`](https://reacttraining.com/react-router/web/api/HashRouter) router component, React Router will encode URLs in the `window.location.hash` segment.
