### ISSUE TITLE
Routes do not update after dispatching replace with react-router-redux

### ISSUE THREAD

**Issue by coltonw** [ReactTraining/react-router#4916]
## Version
4.0.0

## Test Case
https://github.com/coltonw/routerexample

## Steps to reproduce
Pull down my repo and follow simple instructions of:

```
npm i
npm start
```

After 5 seconds, I have a timeout set which will dispatch a react-router-redux replace to the /about page which will happen but the page itself will still have the content of the Home page.

## Expected Behavior
Dispatching react-router-redux replace should properly change the page to a new page.

## Actual Behavior
Dispatching sets the path in the store and the history but the the Routes do not change appropriately to the new path, they remain on the old path.

**Comment by coltonw** [comment]
Sorry for the lack of codepen, I could not get it working in codepen so I set up a quick repo demonstrating.

**Comment by pshrmn** [comment]
The connected component is preventing updates. Please see the [blocked updates guide](https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/guides/blocked-updates.md)

**Comment by coltonw** [comment]
This guide is currently not on the docs website.  It looks like you haven't updated the doc website since this guide was added possibly?

**Comment by pshrmn** [comment]
Yes, the site has not been updated in a bit, so there are discoverability issues with the guide. Hopefully the site will be updated soon so that it is easier for people to naturally come across this.

Also, I'm working at getting a FAQ put together that should also point to that because questions related to update blocking are the most common issue here recently..

**Comment by coltonw** [comment]
Also, it seems to me that connected components have this problem in a non-obvious way. Your code will not mention PureComponents or shouldComponentUpdate anywhere but could STILL hit this problem if you have a connected component.

I know react-router-redux is in alpha and will have a working example as well as probably more documentation along with that so I would hope mentioning this in that readme would be strongly considered.

**Comment by kukuu** [comment]
This is a common problem in using connected components with redux. You can resolve it using location attribute in your routes. You will then have to wrap the main app component of the application in your applications index.js-  <App /> in a <Route /> component. The route's  (<Route />) components attribute will then be evaluated to {App }
