### ISSUE TITLE
Forward-slashes are not decoded in params

### ISSUE THREAD

**Issue by marksamman** [ReactTraining/react-router#4917]
This is similar to what #1865 expected. I expect apple%2Fbanana in the URL to result in apple/banana in the match.params variable.

## Version
4.0.0

## Steps to reproduce
Set up a route like this:
```
<Route path="/fruit/:name" component={Fruit} />
```
Enter /fruit/apple%2Fbana%20na from the browser URL bar.

## Expected Behavior
I expect match.params.name to contain:
```
apple/bana na
```

## Actual Behavior
match.params.name contains:
```
apple%2Fbana na
```

**Comment by pshrmn** [comment]
`history` uses `decodeURI` to decode pathnames. It does this because pathnames are encoded using `encodeURI`, which [does not encode forward slashes](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURI#Description). Since the forward slashes are not encoded, `decodeURI` does not decode `%2f` into a forward slash.

If you're just encoding the forward slash because you want to use repeating patterns, you should use the ["one or more" parameter](https://github.com/pillarjs/path-to-regexp#one-or-more).

```js
// location = { pathname: '/fruit/apple/bana%20na' }
<Route path="/fruit/:name+" component={Fruit} />
// match.params = { name: 'apple/bana na' }
```

**Comment by marksamman** [comment]
Thanks for the quick response! Sounds like it is by design then, FWIW it worked fine in react-router 3. My use case is a route that takes an ascii85 token.

**Comment by pshrmn** [comment]
So you're receiving an ascii85 token from the server and then either setting that as a Link's pathname or programmatically navigating using that?

**Comment by marksamman** [comment]
It's an OpenID flow, so the backend sends a redirect to the URL with the token.

**Comment by marksamman** [comment]
To clarify:
1) User clicks sign up/sign in on my website
2) User is redirected to external website for OpenID authentication
3) User is redirected to my backend service to verify the OpenID request
4) The backend service redirects to the website with an ascii85 token in the URL (e.g. http://example.com/auth/:user_id/:ascii85token)

**Comment by pshrmn** [comment]
Alright, so the one or more parameter is not relevant here. You can still just run an ascii85 decoder on `match.params.ascii85token`, correct? The only real issue is that it is no longer fully decoded automatically?

**Comment by marksamman** [comment]
My only problem is that the forward slash isn't being decoded, so I can't tell if it was a forward slash or if it actually just was %2F in ascii85. I can't just replace %2F with / in the param variable because %, 2, and F are all valid ascii85 characters so it might not actually have been a forward slash. I've switched to a hex representation of the token in my application for now to avoid characters that need escaping, but since this was working fine before upgrading from react-router 3 to 4 I assumed it was a bug. I prefer ascii85 over hex for the token since it's more entropy for less data over the wire.

**Comment by pshrmn** [comment]
Any reason not to place it in the `search` string? We leave that up to the dev to decode.

**Comment by sihil** [comment]
I've just hit this as well and am finding it extremely frustrating. I've managed to put in a workaround that seems to work but I'd advocate the introduction of an option that allows a alternate encoder scheme to be selected for a particular route such that forward slashes etc would be encoded and decoded as expected.
