### ISSUE TITLE
<Redirect /> can't convert additional parameters.

### ISSUE THREAD

**Issue by TossShinHwa** [ReactTraining/react-router#4919]
Hi,

In `react-router v3`, we can use `<Redirect />` like this:

```
  <Redirect from="profile/:userId" to="about/:userId" />
```

It will be covert correct:

```
/profile/123 -> /about/123
```

Unfortunately, it's not work in `react-router v4`. It will be get:

```
/profile/123 -> /about/:id  <---- params be output directly
```

Is there a new way to do this in v4?

*version: react-router-dom 4.0.0*

**Comment by pshrmn** [comment]
A `<Redirect>` doesn't do any pattern compiling. You have to give it the actual URI that you want to redirect to.

The approach that I would take would be to use a `<Route>` instead of a `<Redirect>` for the matching, and then use the parsed param to build the redirect URI.

```js
<Route path="/profile/:userId" render={({ match }) => (
  <Redirect to={`/about/${match.params.userId}`} />
)} />
```

**Comment by 1000hz** [comment]
> A <Redirect> doesn't do any pattern compiling.

It'd be a lot cooler if it did.

**Comment by Tim15** [comment]
@pshrmn
Is pattern-matching redirects a planned feature, or is it intentionally left out? Would you accept a pull request for it?

**Comment by pshrmn** [comment]
I'm not personally a fan of the idea because I don't like overloading the `<Redirect>` with functionality that only works inside of a `<Switch>`. I'm not even a fan of being able to use a `<Redirect>` directly in a `<Switch>`. I'm also not someone who makes decisions about this sort of thing, so I'm not the person to convince that it would be useful.

**Comment by jacobrask** [comment]
Couldn't `to` take a function argument returning a string/object?

**Comment by timdorr** [comment]
@jacobrask See #5368

**Comment by gouegd** [comment]
I'd also like to be able to pass a `to` function on the Redirect, so some querystring parameters can be preserved. Currently to access the location, one has to add an extra Router component (or withRouter wrapping) when it's not otherwise needed.

**Comment by Falieson** [comment]
Do I understand correctly that with the merging of #5368 we can go `<Route path='/account/:id' to='/account/:id/summary' component={AccountSummary} />` and the component will render whether or not /summary is on the url?

**Comment by Sparragus** [comment]
I used @pshrmn suggestion in https://github.com/ReactTraining/react-router/issues/4919#issuecomment-292229262 and created a Redirect component of my own. Now, instead of using React Router's Redirect, I use this:

```js
// Redirect.js
import React from 'react'
import {
  Redirect as ReactRouterRedirect,
  Route,
} from 'react-router-dom'

export default function Redirect (props) {
  const {
    from,
    to,
    ...rest
  } = props

  if (!from) {
    return <ReactRouterRedirect {...props} />
  }

  return (
    <Route
      path={from}
      render={({ match }) => {
        const paramKeys = Object.keys(match.params)

        const toWithReplacedParamsKeys = paramKeys.reduce((url, key) => (
          url.replace(`:${key}`, match.params[key])
        ), to)

        return <ReactRouterRedirect to={toWithReplacedParamsKeys} {...rest} />
      }}
    />
  )
}
```

Hope it helps.

**Comment by Sparragus** [comment]
@mjackson or @ryanflorence What do you think of https://github.com/ReactTraining/react-router/issues/4919#issuecomment-346709646? Is it worthy of a behavior that `Redirect` should do? If you like, I can try to implement it and open a PR with it.

**Comment by Xuhao** [comment]
If this feature not supported anymore, it's better to remove the example in docs: 
https://github.com/ReactTraining/react-router/blob/4a2821335daa1806ded29ad09359424053107e44/packages/react-router/docs/api/Redirect.md#from-string

**Comment by kylebebak** [comment]
@pshrmn 
>A <Redirect> doesn't do any pattern compiling. You have to give it the actual URI that you want to redirect to.

It's worth mentioning this runs contrary to the documentation:

<img width="521" alt="screen shot 2018-04-05 at 2 04 21 pm" src="https://user-images.githubusercontent.com/1524088/38386530-86e0120c-38da-11e8-93fb-46a4cbe221eb.png">

**Comment by timdorr** [comment]
That's in 4.3.0-rc.2
