### ISSUE TITLE
react-router-redux not controlling routes when passing location changes

### ISSUE THREAD

**Issue by Sawtaytoes** [ReactTraining/react-router#4920]
## Version
react-router 4.0.0-beta.8
react-router-redux 5.0.0-alpha.4

## Test Case
https://dev.tabletophelper.com/smash-up/randomizer/players-selector

## Repo
https://github.com/Sawtaytoes/Tabletop-Helper/tree/develop

## Steps to reproduce
1. Open Redux dev tools plugin in Chrome.
2. Click the links in the header to swap the route around a few times.
3. In Redux dev tools, replay the actions you took.

## Expected Behavior
It should replay the routes you took from the initial to the last.

## Actual Behavior
It stays on the current route and does not change. This is not the behavior I experienced in prior versions of react-router + react-router-redux.

**Comment by timdorr** [comment]
Time travel doesn't work with react-router-redux at the moment.

**Comment by lghinet** [comment]
any changes ?
