### ISSUE TITLE
[Question] How do I get to the current route outside of a <Route/>?

### ISSUE THREAD

**Issue by Industrial** [ReactTraining/react-router#4921]
Hi.

I have this situation:
```
<BrowserRouter>
  <Menu/>

  <Route path="/" component={Home}/>
  ...
</BrowserRouter>
```

What I want is my `Menu` to render the active item based on the selected route.

The problem is that these props are only available to the component of a Route, and not to all children of BrowserRouter.

How do I get this to work?

gr,

Tom

**Comment by pshrmn** [comment]
I don't understand what you mean by "I want my Menu to render the active item". What is the active item? 

The `<NavLink>` is a special `<Link>` that will add an "active" class and/or style to a `<Link>` when its `to` prop matches the current location.

**Comment by Industrial** [comment]
With Active Item I meant that I want to use the match prop's data to decide
which menu item to activate / show an active class on. The JSX used for
this may vary but right now I'm using Semantic UI React. I don't think a
Link with an active prop is enough since the JSX used to render the menu
may change per implementation/webapp.

Since a Link renders to an `<a>` tag, if only that elements gets an active
class then that might not be enough for a CSS framework because for example
it might use the active class on a parent `<li>` item instead.

**Comment by timdorr** [comment]
NavLink is actually pretty easy to read through. It's just [wrapping a Link in a Route](https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/modules/NavLink.js#L19-L35). So, you can do the same thing to add a class or whatever else you want.

One important thing to note: In 4.0, there is no singular match. Route can be used anywhere and multiple Routes can match at the same time. So, the concept of which Route is matching is intentionally gone. If you need that kind of behavior, check out setting up a route config in the docs.
