### ISSUE TITLE
[docs] Not clear how to use forceRefresh with Redirect component

### ISSUE THREAD

**Issue by rogovdm** [ReactTraining/react-router#4922]
There is a `forceRefresh` option on a Router level, but docs are not clear how to use with `Link` or with `Redirect` component.

**Comment by pshrmn** [comment]
You don't have to do anything differently with `<Link>` and `<Redirect>`. If you use `forceRefresh`, then when you navigate, the `history` object will set `window.location.href` instead of using `window.history.(pushState|replaceState)`
