### ISSUE TITLE
[feature request] propTypes

### ISSUE THREAD

**Issue by mqklin** [ReactTraining/react-router#4923]
There was `propTypes` module in 3.x: https://github.com/ReactTraining/react-router/blob/v3/docs/API.md#proptypes
Can somebody add it to 4.x too?

**Comment by timdorr** [comment]
We don't intend to add them, as they bloat the build quite a bit. `PropTypes.object` is sufficient for most use cases.

**Comment by mqklin** [comment]
They don't bloat, if you use tree shaking. And it's not sufficient, if you use `forbidExtraProps`. A lot of libs (redux-form for example) expose their propTypes. Well, I'm going to create my own `react-router-prop-types`. Amazing.
