### ISSUE TITLE
 A <Router> may have only one child element

### ISSUE THREAD

**Issue by EasonWang01** [ReactTraining/react-router#4928]
How to change this to fit it.

```
  <BrowserRouter>
      <Route path="/" component={App} />
      <Route path="/01" component={Record} />
  </BrowserRouter>
```

**Comment by pshrmn** [comment]
```js
<BrowserRouter>
  <div>
      <Route path="/" component={App} />
      <Route path="/01" component={Record} />
  </div>
</BrowserRouter>
```
The `<div>` could also be a `<Switch>` if you only want one `<Route>` to render.

**Comment by EasonWang01** [comment]
no,it will have App inside Record

**Comment by pshrmn** [comment]
I'm not exactly sure what you mean.

`<Route path="/">` matches all paths. You will need to use the `exact` prop if you want that route to only match when `location.pathname === '/'`.

**Comment by EasonWang01** [comment]
OK,but what's the different of `Switch` and `Div`

**Comment by pshrmn** [comment]
A `<Switch>` only renders the first child `<Route>` that matches the current location. The `<div>` would just be a placeholder to deal with the fact that (currently) React components can only return a single element.

**Comment by EasonWang01** [comment]
but who will write many <Route> for same route path?

**Comment by EasonWang01** [comment]
Ok,more clear after look at this https://reacttraining.com/react-router/web/api/Switch

**Comment by sanjeevpratapsingh** [comment]
Here is one catch and that is you forget wrap everything in **One Container**. So what you have to do is put all your routes in one container and then run the code it will work.
<BrowserRouter>
  <div>
      <Route path="/" component={App} />
      <Route path="/01" component={Record} />
  </div>
</BrowserRouter>

**This code showing one of the correct ways**, You can try some other ways as suggested by other guys.
