### ISSUE TITLE
Redirect `from` not being used.

### ISSUE THREAD

**Issue by michielboekhoff** [ReactTraining/react-router#4931]
## Version
Master

## Steps to reproduce
Currently, in the `Redirect` component, the `from` prop is not being used at all. See [`Redirect.js`](https://github.com/ReactTraining/react-router/blob/master/packages/react-router/modules/Redirect.js).

## Expected Behavior
Ideally, you'd want `from` to be part of browser state (for `react-router-dom`). 

## Actual Behavior
Right now, this prop is completely being ignored. 

I'd be very happy to open a PR to add this functionality to `react-router-dom`.

Thank you.

**Comment by pshrmn** [comment]
`from` only works inside of a `<Switch>`. It is effectively an alias for a `<Route>`'s `path` prop. Outside of a `<Switch>`, a `<Redirect>` will always match.
