### ISSUE TITLE
Components which is created with `connect` from ReactRedux breaks behavior of router

### ISSUE THREAD

**Issue by uaNikita** [ReactTraining/react-router#4936]
## Version
4.0.0

## Test Case
https://codepen.io/anon/pen/QpXYJB

## Steps to reproduce
Click to the Home and About link nothing happen. 
Then change LayoutConnect in App to Layout and click again - text is changing.

## Expected Behavior
LayoutConnect and Layout work the same way.

## Actual Behavior
LayoutConnect which is created with `connect` from ReactRedux breaks behavior. Links does not work.

**Comment by pshrmn** [comment]
Your `connect`ed component is blocking updates. Please see this guide for more information https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/guides/blocked-updates.md

**Comment by jcreamer898** [comment]
I'm having a ridiculously hard time getting this right ATM, so if there's an example of someone hooking up `connect` with `react-router`, I'd be super happy. :)

**Comment by damianobarbati** [comment]
@jcreamer898 I'm loosing countless hours of work because of this bug, not able to have withRoute working. Did you find any solution?

**Comment by jcreamer898** [comment]
Yeah, I'll throw up an example of how I solved it. Gimme' a sec.

**Comment by jcreamer898** [comment]
https://github.com/lonelyplanet/react-universal-starter/blob/master/app/universal/containers/universal.jsx#L30

**Comment by damianobarbati** [comment]
Great, solved! The problem was I had to use withRouter only in my main component rendering children!

**Comment by jcreamer898** [comment]
Nice!
