### ISSUE TITLE
react-router-dom v4 nested routes issue allover the internet

### ISSUE THREAD

**Issue by MasoodAhmad** [ReactTraining/react-router#4940]
In reference to the unresolved question (as a final conclusion) 

 - http://stackoverflow.com/questions/42984597/multiple-nested-routes-in-react-router-dom-v4
 -  http://stackoverflow.com/questions/42254929/how-to-nest-routes-in-react-router-v4

I am also getting the same issue.

https://reacttraining.com/react-router/web/guides/quick-start promotes `react-router-dom` in which there is no `<Switch>` or `<Match>`.

Also, people find better to `list down routes` in one file rather inside components.

@mjackson

**Comment by timdorr** [comment]
Use react-router-config for a central route configuration.

Match is an old API. Please read the updated docs. Switch is re-exported by react-router-dom: https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/modules/Switch.js

**Comment by MasoodAhmad** [comment]
@timdorr 
Thanks for responding.

I would, in reference to this ticket, recommend working examples of code for the mentioned issues devs are facing in common.

**Comment by timdorr** [comment]
There are plenty of examples of all the APIs for react-router-config on the Readme: https://github.com/ReactTraining/react-router/tree/master/packages/react-router-config

If those are sufficient, please submit a PR with some examples you would like included in the repo.

**Comment by harry91** [comment]
@MasoodAhmad I think the Readme doesn't contain what you and I want. If ```list down routes``` by using the solution in Readme, there will be too much code in route file. However, like you said, ```nested routes issue allover the internet```, I can't figure out which solution is appropriate.
