### ISSUE TITLE
[V3] console report errors in react-router@3.0.4

### ISSUE THREAD

**Issue by wssgcg1213** [ReactTraining/react-router#4943]
## Version
3.0.4

I updated my react-router from 3.0.2 to 3.0.4.  

![image](https://cloud.githubusercontent.com/assets/3922719/24847896/9b321e76-1df6-11e7-8d44-a9ace30e86db.png)

it works fine in 3.0.2.

ref: https://facebook.github.io/react/warnings/dont-call-proptypes.html

**Comment by wssgcg1213** [comment]
which change cause these errors and how do i fix them？  
thanks~

**Comment by krisaoe** [comment]
These warnings are caused by the changes to React v.15.5.0, as they are splitting PropTypes into a separate package. I imagine react-router will fix this soon.
You can read more about the changes and reasoning here https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html

**Comment by wssgcg1213** [comment]
@krisaoe thx, but my react version is 15.1.0.  
I guess it is related to 
https://github.com/ReactTraining/react-router/blob/c904dcccd676883103ee7f8d3e9b3dc9a8918359/modules/ContextUtils.js#L1

prop-types@^15.5.6
https://github.com/ReactTraining/react-router/blob/c904dcccd676883103ee7f8d3e9b3dc9a8918359/package.json#L41

I have no plan to update react to 15.5 yet, will react-router fix it?

**Comment by wssgcg1213** [comment]
I update my react to 15.3.2 and fix this problem.

**Comment by wssgcg1213** [comment]
sorry, I misread my page, it is still a lot of warnings in Console

**Comment by timdorr** [comment]
This was specifically fixed here: #3591

If something is running your PropType validations manually, it's not us.
