### ISSUE TITLE
import { browserHistory } from 'react-router';  API change?

### ISSUE THREAD

**Issue by EasonWang01** [ReactTraining/react-router#4946]
In v4 what is the alternative for

 ```
import { browserHistory } from 'react-router'; 
browserHistory.push('/main')
```

where can see the API change for v4?

**Comment by dananichev** [comment]
As far as i understand you will need to wrap the component inside ``<Route>`` and use ``this.props.history`` or ``this.props.location``.

For example
```js
<Route>
   <Header />
</Route>
```

```js
function Header(props) {
   // props.history and props.location are available now inside this component
}
```

**Comment by vorlov** [comment]
you need to use 
```javascript 
push
```
from react-router-redux package
