### ISSUE TITLE
react-router 3.0.4 own react elements become <Unknown/>

### ISSUE THREAD

**Issue by bovan** [ReactTraining/react-router#4947]
## Version
3.0.4

## Steps to reproduce
Project with 3.0.3:
![image](https://cloud.githubusercontent.com/assets/465649/24859996/d7247a68-1df2-11e7-8c02-f65958008e20.png)

`npm i -D react-router@3.0.4`

![image](https://cloud.githubusercontent.com/assets/465649/24860064/1e043ff4-1df3-11e7-8279-1859eac6bf6f.png)

## Expected Behavior
React-Router elements are still recognizable

## Actual Behavior
React-Router elements are `<Unknown/>` (but still works).

Causes enzyme-tests and react-inspecting to bug

**Comment by timdorr** [comment]
Looks like this is related to babel/babel#5554.

**Comment by timdorr** [comment]
Note that we can fix this on our end by just manually setting a displayName for our components. Would be an easy PR if anyone wants to take it on.

**Comment by timdorr** [comment]
OK, 3.0.5 is out which should fix this.
