### ISSUE TITLE
React Router 4.0 - if Root element under Router is connected via redux, navigation is broken

### ISSUE THREAD

**Issue by kellyrmilligan** [ReactTraining/react-router#4949]
## Version
4.0.0

## Test Case
https://github.com/kellyrmilligan/react-router-4-bug

## Steps to reproduce
in the entry point of the app, where reactdom.render occurs, place the browser router around your app.js file, with redux provider as well. 

```
ReactDOM.render(
  <Provider store={configureStore()}>
	<Router>
		<App />
	</Router>
  </Provider>,
  document.getElementById('root'), () => console.log('rendered')
);
```

## Expected Behavior
`Navlink` works as expected. 

## Actual Behavior
the url updates, but the render does not re-occur.

**Comment by pshrmn** [comment]
`connect` is blocking updates. Please see this guide for more information https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/guides/blocked-updates.md

**Comment by jcreamer898** [comment]
@kellyrmilligan did you figure it out? I think I'm having the same problem.

**Comment by kellyrmilligan** [comment]
@jcreamer898, I followed the guild and wrapped my connected component using withRouter, so connect to redux the wrap that in that util.

**Comment by jcreamer898** [comment]
@kellyrmilligan would you be able to update your example with the code you ended up using? I'm a tad confused exactly where to use the `withRouter` since right now I'm using `<Route path={} component={} />`. Thanks!

**Comment by kellyrmilligan** [comment]
@jcreamer898 updated the example for what did it for me. The redux guide in the same director above talks about this topic as well.

**Comment by jcreamer898** [comment]
Thanks!

**Comment by damianobarbati** [comment]
@kellyrmilligan where is the working example using withState? Thanks.

**Comment by kellyrmilligan** [comment]
It's withRouter and is in the example repo up top
