### ISSUE TITLE
Unknown prop 'replace' on <a> tag  using <Link> component  

### ISSUE THREAD

**Issue by andrewl913** [ReactTraining/react-router#4955]
When using the replace flag on a Link component, it get's passed down to the <a> tag and causes an error.

<Link to="destination" replace />

**Comment by timdorr** [comment]
I don't see how that's possible. We omit the `replace` and `to` props from the ones that get provided to the `<a>` tag: https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/modules/Link.js#L59

**Comment by timdorr** [comment]
Do you mean the react-native version? That would be susceptible to this. #4854 fixes it.

**Comment by timdorr** [comment]
I merged that in, so it should fix this (assuming you're on RN). A 4.0.1 is coming shortly.
