### ISSUE TITLE
How to solve the "checksum" error when using "withRouter()" method on SSR

### ISSUE THREAD

**Issue by wellyshen** [ReactTraining/react-router#4961]
I used the `withRouter()` to solve the problem of `push()` method doesn't update route. With the `withRouter()` I can make the route updated with redux container. But there's one little problem is that when I using the `withRouter()` with SSR, it will occur the checksum error between client and server side as below, does any suggest to solve this problem?

Here is how I set up the `withRouter()`:
```javascript
export default withRouter(connect(mapStateToProps, mapDispatchToProps)(Component))
```

Here is the problem:
<img width="1280" alt="2017-04-13 12 16 25" src="https://cloud.githubusercontent.com/assets/21308003/24968691/a39a5376-1fe0-11e7-9893-a645c855cbd8.png">

**Comment by timdorr** [comment]
withRouter shouldn't render any HTML itself. How you are you using ReactDOM.renderToString()? That shouldn't happen.

**Comment by wellyshen** [comment]
@timdorr Here's is my final settings of client and server side, by that the `push()` method works
 but the chunksum error still exist :

<img width="1279" alt="2017-04-13 10 52 27" src="https://cloud.githubusercontent.com/assets/21308003/24988256/5ab792c0-2037-11e7-9937-69af6164e486.png">

client.js :
```javascript
// ...

const renderApp = () => {
  const nonBlockingRouter = withRouter(BrowserRouter);

  render(
    <AppContainer>
      <Provider store={store}>
        <ConnectedRouter history={history}>
          <nonBlockingRouter>
            <App />
          </nonBlockingRouter>
        </ConnectedRouter>
      </Provider>
    </AppContainer>,
    document.getElementById('react-view'),
  );
};

// ...
```

server.js : 
```javascript
// ...

const routerContext = {};
const htmlContent = renderToString(
  <Provider store={store}>
    <StaticRouter location={req.url} context={routerContext}>
      <App />
    </StaticRouter>
  </Provider>,
);

// ...
```

I found if I remove the `<BrowserRouter>` from client side, everything works great, the `push()` method works no need `withRouter()` and the chunksum error solved. Because there's no document about react-router-redux with SSR, so I'm wondering is that setting correct?

The client.js works :
```javascript
// ...

const renderApp = () => {
  render(
    <AppContainer>
      <Provider store={store}>
        <ConnectedRouter history={history}>
            <App />
        </ConnectedRouter>
      </Provider>
    </AppContainer>,
    document.getElementById('react-view'),
  );
};

// ...
```

**Comment by timdorr** [comment]
Well, you've got different trees on the client and the server, which is the crux of the issue. You need to implement the same tree on both sides for it to work. That's up to you, not this library.

**Comment by wellyshen** [comment]
@timdorr If I use the react-router-redux, should the `BrowserRouter` need to be instead by `ConnectedRouter` or I need to keep both?

**Comment by timdorr** [comment]
You don't want two Router components in there. They both use `<Router>` under the hood and the inner one will override whatever history you set for `<ConnectedRouter>`.

**Comment by wellyshen** [comment]
@timdorr Cool, thanks a lot.
