### ISSUE TITLE
Protecting a route with react-router-config?

### ISSUE THREAD

**Issue by Geczy** [ReactTraining/react-router#4962]
How are routes protected using react-router-config now? v4

**Comment by timdorr** [comment]
This doesn't exist currently. However, it should be relatively easy to add. Want to submit a PR?

**Comment by Dustin-RW** [comment]
Hello, would you mind if I took this on?

**Comment by timdorr** [comment]
Go for it!

**Comment by Geczy** [comment]
Do it!! 💯

**Comment by Geczy** [comment]
How'd it go @Dustin-RW ?

**Comment by Dustin-RW** [comment]
Still working on it and don't want to PR until I know it's worth your while.  I'm new to React and understand if someone PR's before I do.  To help narrow down "protection," are you referring to authentication routes with default parameters/routes if not authenticated?

**Comment by Geczy** [comment]
Yes that's correct

**Comment by strues** [comment]
This might not be the best way, but it might help.  I'm still trying to find a better solution to implement that accounts for async data loading. Anyways...

[Routes file](https://github.com/strues/boldr/blob/develop/src/shared/routes.js#L154) where I've added auth to the object.

[Server routes](https://github.com/strues/boldr/blob/develop/src/server/boldrSSR/index.js#L43) where matchRoutes is called.

[Add routes)(https://github.com/strues/boldr/blob/develop/src/shared/core/addRoutes.js#L7) where the authorization check takes place.

[Render routes](https://github.com/strues/boldr/blob/develop/src/shared/components/App/App.js#L144) takes the mapped routes from the above file and does the component rendering. Notice it's calling renderRoutes, which is from react-router-config, but a reimplementation of it.

**Comment by truckingsim** [comment]
@strues what problems have you ran into with async loading this way?  I'm also trying to figure this out and have come up with a better way but also haven't ran into any big issues yet* 

\* - All of my fingers crossed knocking on wood hoping I don't run into any.

**Comment by strues** [comment]
@truckingsim the only real issue I've ran into is I've not been able to handle a nested route which needs to act as an "index route" for other routes. It might be how I've got my routes setup. 

No issues with data loading this way.

**Comment by gondar00** [comment]
@strues Thank you, i was scratching my head on how to fix this until i landed on this thread.

**Comment by githubdoramon** [comment]
following this one

**Comment by githubdoramon** [comment]
@strues your links does not exists anymore... Could you share your implementation of renderRoutes?

@timdorr any updates on how to do it officially?

**Comment by timdorr** [comment]
Someone needs to make a PR for it.

**Comment by githubdoramon** [comment]
PR created @timdorr 

https://github.com/ReactTraining/react-router/pull/5445

**Comment by timdorr** [comment]
BTW, this is what I think the config should look like:
```js
const routes = [
  { component: App,
    routes: [
      { path: '/',
        matches: args => checkAuth(args),
        component: Dashboard
      },
      { path: '/login',
        component: Login
      }
    ]
  }
]
```
Basically, add a `matches` property that takes a function for checking if this match is allowed. 

Does that seem sufficient?

**Comment by isaachinman** [comment]
@timdorr Still need a PR on this? I see #5445 wasn't the direction you wanted.

**Comment by inconduit** [comment]
this still seems to be an open issue. for anyone searching for a solution (like me) i wound up using a HOC as described here https://crysislinux.com/limit-access-to-redux-apps-with-higher-order-components/

and i use it in my routes.js like so:
```
      {
        path: '/somePrivateRoute',
        component: requireAuthentication(someComponent),
      },
```

**Comment by maciej-ka** [comment]
I'm interested in grabbing this. It would be a help to know:
1. Does react-router currently support something like a configuration posted by @timdorr ?
2. Is there a reason to not enable protected routes in JSX? As a Route property perhaps.

**Comment by isaachinman** [comment]
@maciej-ka I too am interested in taking this on, and am still waiting to hear from @timdorr.

**Comment by timdorr** [comment]
Don't wait for me.

**Comment by timdorr** [comment]
> Does react-router currently support something like a configuration posted by @timdorr ?

No, hence the issue.

> Is there a reason to not enable protected routes in JSX? As a Route property perhaps.

You can do this from within your render function. JSX doesn't need an API for this because it's more flexible.

**Comment by maciej-ka** [comment]
Right, in JSX that could be like:

```jsx
<Route path="/restricted" render={() =>
  isRouteAllowed
    ? <div>Restricted route</div>
    : <Redirect to="/" />
} />
```

So, in what scenario this wouldn't be enough? I ❤️ that `react-router` has no traditional config and would need a good reason to introduce one.

**Comment by xiaoyunyang** [comment]
If anyone is still looking for a solution to this, I have a working solution. I modified the `react-router-config`/[renderRoutes.js](https://github.com/ReactTraining/react-router/blob/master/packages/react-router-config/modules/renderRoutes.js) file to this:

```javascript
// renderRoutes.js

import React from 'react'
import Switch from 'react-router/Switch'
import { Route, Redirect } from 'react-router-dom'

const renderRoutes = (routes, authed, authPath, extraProps = {}, switchProps = {}) => routes ? (
  <Switch {...switchProps}>
    {routes.map((route, i) => (
      <Route
        key={route.key || i}
        path={route.path}
        exact={route.exact}
        strict={route.strict}
        render={(props) => {
          
          if( !route.restricted || authed || route.path == authPath) {
            return <route.component {...props} {...extraProps} route={route}/>
          }
          const redirPath = authPath ? authPath : '/login'
          return <Redirect to={{pathname: redirPath, state: {from: props.location}}}/>
        }}
      />
    ))}
  </Switch>
) : null

export default renderRoutes
```

I added `authed` and `authPath` as two new arguments to `renderRoutes` function.
* `authed` is true if user is logged in and false otherwise.
* `authPath` is the path you want to redirect to (e.g., /login) if `authed` is false. 

Here is how you call the `renderRoutes` function:
```javascript
// caller of renderRoutes

import React from 'react'
import { Switch } from 'react-router-dom'
//import { renderRoutes } from 'react-router-config'
import renderRoutes from '../renderRoutes'
import routes from '../routes3'

const authed = false // <-- You can change this
const authPath = '/login' // <-- You can change this

const Main = () => (
   <main>
      <Switch>
         {renderRoutes(routes, authed, authPath)}
      </Switch>
   </main>
)

export default Main
```

Having `authed` and `authPath` configurable from the caller of renderRoutes is desirable because it gives you more control over these parameters from `redux` / server side. I have not tried trying this solution out with `redux` or the server side logic for logging users in but that's what I'm going to be doing next.

Lastly, an important change need to be added to the routes object as part of this solution. Specifically, for each route, you need to specify a `restricted` field, which can be true if you want the page to be accessible only when `authed` is true, or false if the page is a public page that anyone can access. For example:

```javascript
// routes.js
import Home from './components/Home'
import Login from './components/User/Login'
import User from './components/User/User'

const routes = [
	{ path: '/',
		exact: true,
		restricted: false,  // <-- NEW
		component: Home,
	},
	{
		path: '/login',
		restricted: false, // <-- NEW
		component: Login,
	},
	{
		path: '/user',
		restricted: true, // <-- NEW
		component: User,
	},
	{
		path: '*',
		restricted: false, // <-- NEW
		component: NotFound
	}
]

```

For completeness, this is what the `Login` component looks like:

```javascript
// Login.js

import React from 'react'

class Login extends React.Component {
   render() {
      const { from } = this.props.location.state || { from: {pathname: '/' } }
         return (
	    <div>
	       <p>You must log in to view this page at {from.pathname} </p>
	          <button onClick={this.login}>Log in </button>
	     </div>
	 )
   }
}

export default Login
```

`this.props.location.state` tells you where you last were before you got directed to `/login`. The idea for this feature came out of the `PrivateRoute` [tutorial](https://reacttraining.com/react-router/web/example/auth-workflow).

**Comment by raibima** [comment]
@timdorr PR created #5893. Looking forward for feedbacks :)

**Comment by gorkalaucirica** [comment]
Maybe we should protect a route using render method as it's done in JSX.

```js
import React from "react";
import Switch from "react-router/Switch";
import Route from "react-router/Route";

const renderRoutes = (routes, extraProps = {}, switchProps = {}) =>
  routes ? (
    <Switch {...switchProps}>
      {routes.map((route, i) => (
        <Route
          exact={route.exact}
          key={route.key || i}
          path={route.path}
          render={props => route.render
            ? route.render(props)
            : <route.component {...props} {...extraProps} route={route}/>}
          strict={route.strict}
        />
      ))}
    </Switch>
  ) : null;

export default renderRoutes;
```

Usage:

```js
{
    {
        path: "/restricted-area",
        render: (props) => isUserLoggedIn() ? <RestrictedArea/> : <Redirect to="/login"/>
    },
    {
        path: "/login",
        component: Login
    }
}
```

WDYT?

**Comment by ankibalyan** [comment]
is there any workaround to this?

**Comment by declanelcocks** [comment]
Ended up just creating a `withAuth` HOC to help with this. Inside my `routes.js` file, I'm doing something like this:

```js
{
    path: '/',
    exact: true,
    component: generateAsyncRoute({
      loader: () => import(/* webpackChunkName: "home" */ './pages/Home'),
    }),
},
```

The main thing here is that `generateAsyncRoute` is taking care of resolving everything that needs to resolve before this component is ready (i.e. fetching data etc.), so adding in authentication just made this whole idea even more complicated.

So, inside each route I now just export something like `withAuth(Home)` and have this for `withAuth`:

```js
const withAuth = Component => {
  const AuthComponent = props => {
    if (props.authenticated) {
      return props.user.role === 'signup' &&
        props.location.pathname !== '/signup/2' ? (
          <Redirect
            to={{ pathname: '/signup/2', state: { from: props.location } }}
          />
      ) : (
        <Component {...props} />
      )
    }

    return (
      <Redirect
        to={{
          pathname: props.location.pathname === '/signup/2' ? '/signup/1' : '/',
          state: { from: props.location },
        }}
      />
    )
  }

  AuthComponent.propTypes = {
    location: PropTypes.object.isRequired,
    authenticated: PropTypes.bool.isRequired,
    user: PropTypes.object.isRequired,
  }

  return compose(
    withRouter,
    connect(state => ({
      authenticated: state.authentication.authenticated,
      user: selectUser(state.authentication),
    })),
  )(AuthComponent)
}
```

I'm sure it's not perfect & would be happy for people to suggest improvements, but it works for my situation.

**Comment by Grantlyk** [comment]
I think the implementation suggested by @gorkalaucirica works, 

does anyone have any objections or can I open a PR with those changes?

**Comment by Grantlyk** [comment]
Ahh, I can actually see this has been merged and resolved, is there a reason this issue hasn't been closed?

**Comment by timdorr** [comment]
Because it doesn't allow us to "back out" of a tree path if a deeply nested child route blocks matching for some reason. This would also solve the "404" problem.
