### ISSUE TITLE
withRouter - Cannot read property 'route' of undefined

### ISSUE THREAD

**Issue by hackingbeauty** [ReactTraining/react-router#4969]
## Version
4.0.0

Whenever I try to use withRouter in React-Router 4, I get the following error:

```
Uncaught TypeError: Cannot read property 'route' of undefined
```

I never received this error when using withRouter w/ React-Router 3.x.  Why is this happening?

**Comment by timdorr** [comment]
The API has changed significantly from 3.x. You probably want `match`, but check the docs to be sure.

**Comment by hackingbeauty** [comment]
I think I discovered the problem.  The component I was importing withRouter into was not nested inside of the ```<BrowserRouter />``` component.
