### ISSUE TITLE
Idea: Move react-router v3 to separate package

### ISSUE THREAD

**Issue by chrisblossom** [ReactTraining/react-router#4971]
Now that react-router v4 is out and since v3 is [still being maintained](https://github.com/ReactTraining/react-router/issues/3611#issuecomment-253818854), it would be very helpful to split react-router v3 into its own repo / npm package.

This will help with sorting through issues, and running ``npm outdated`` / ``yarn upgrade-interactive`` to show v3 instead of v4- not having to manually check for v3 releases. 

Sorry if this has already been discussed, I could not find anything.

**Comment by timdorr** [comment]
If we need to break semver, I'm squatting on react-router-dom. But so far the plan is to keep things in the same place. We're really only doing bug fixes on 3.0. If you want to do some major changes, a fork is the best option there.

**Comment by evan-scott-zocdoc** [comment]
@timdorr Does all the new `prop-types` stuff count as a bugfix? I distinctly remember someone on the RR team saying 3.x will be maintained indefinitely, which I would hope would include important changes like that.

**Comment by evan-scott-zocdoc** [comment]
@timdorr nvm just noticed the 3.x branch!

**Comment by chrisblossom** [comment]
@timdorr little off the scope of this, but can you recommend a way to see any updates to react-router v3 via npm/yarn? Especially for those of us that pin package versions. This is the biggest reason I'd like to see v3 split to its own package.

**Comment by timdorr** [comment]
If you pin to `^3.0.0`, then npm upgrade will get them. I've also been publishing them with the `previous` tag. You can see them all in `npm show react-router`

**Comment by chrisblossom** [comment]
@timdorr thanks for the suggestion, but from my experience and various best practice articles, using anything expect pinned package versions is not recommended for production apps.

I'll continue to manually check every week or so.
