### ISSUE TITLE
Impossible to use react-router-native with redux

### ISSUE THREAD

**Issue by inferusvv** [ReactTraining/react-router#4973]
## Version
4.0.0

## Problem
As I understand it is impossible to use out of the box `react-router-native` with redux, because `react-router-redux` [ConnectedRouter](https://github.com/ReactTraining/react-router/blob/master/packages/react-router-redux/modules/ConnectedRouter.js#L3) import web version of `react-router`.

**Comment by timdorr** [comment]
That isn't the web version. That would be react-router-dom. You can pass a memory history into ConnectedRouter with native, as far as I know.
