### ISSUE TITLE
What is equivalent method Route onEnter in version 4?

### ISSUE THREAD

**Issue by penteleq** [ReactTraining/react-router#4976]
I'm trying to fetch data on entering route.

There was method onEnter.

What is equivalent method Route onEnter in version 4 now?

**Comment by pshrmn** [comment]
You should use the lifecycle methods of the component that expects the data (`componentDidMount` or `componentWillMount` and `componentDidUpdate` or `componentWillUpdate`).

**Comment by pawarvijay** [comment]
Before changing route it comes to this
https://reacttraining.com/react-router/web/example/auth-workflow
