### ISSUE TITLE
Nested routing with reserved path components

### ISSUE THREAD

**Issue by cloutiertyler** [ReactTraining/react-router#4980]
Right now I'm having difficultly expressing the concept of a route that should only accept url parameters that fit into a certain set. For example consider, let's say we want to have a url scheme in which going to a user's username sends them to their profile. Under their profile there is a list of reserved paths for navigation within their profile, (e.g. tabs for {bio | blog | picture}). Also under their username are user named resources that are not known at compile time and are stored in a DB.

In essence, the following:
```jsx
<Switch> 
  <Route exact path="/:username" component={Profile} />
  <Route path="/:username/{bio | blog | picture}" component={Profile} />
  <Route path="/:username/:resource" component={ResourcePage} />
</Switch>
```

One way to do this is to create a separate path for each of the reserved words which also point to the `Profile`, and have everything else pass through to the `ResourcePage`.
```jsx
<Switch> 
  {[
    <Route exact path="/:username" component={Profile} />,
    Array.from(new Set(["bio", "blog", "picture"])).map(name => {
      return <Route path={"/:username/" + name} component={Profile} />;
    }),
    <Route path="/:username/:resource" component={ResourcePage} />,
  ].reduce((a, b) => a.concat(b), [])}
</Switch>
```
(pardon the lack of keys)

The thing is, now you've got yourself a few problems. The first of which is that ideally only the `Profile` should have to deal with routing within the `Profile` component, but here our logic is exposed in the parent of the `Profile`. The second is that when you go to express your nested routes inside of `Profile`, you'll find that building a nested route with the `match` property's `path` is not so helpful since it is also matching the subpath that you'd like to use for navigation within the `Profile`. i.e. it prevents the following:

```jsx
<Route path={match.path + "/" + "blog"} component={Blog}/>
```

Instead you have to transform the path by ripping off the last component before appending "blog" to it or doing something like
```jsx
<Route path={"/" + match.params.username + "/blog"} component={Blog}/>
```

You can also do a similar construction with by constructing a very complex regex for regex-to-path from the set. All of these solutions are confusing to read and none of them fix the problem that the internal routing of `Profile` is exposed in the parent.

The problem is somewhat mitigated by relative routes, but arguably it would be doubly confusing to have a nested route that looked like this,
```jsx
<Route path={"../blog"} component={Blog}/>
```
as you would imagine that `../` should be `./` but you have to remove the blog component from the matched path in the parent.

Is there anyway of fixing this problem currently or any proposals to make it easier to deal with?

You can also imagine you might want to route based on the query string and there definitely isn't a way to deal with that right now.

One (not so good) solution that I could imagine would be to allow a sort of `filter` function on the route. This function would take the current `location` as input and would either allow the path to match or not. 

e.g. (assuming a fictional `location.pathcomponents` and a set of reserved words `reserved`)
```jsx
<Switch> 
  <Route exact path="/:username" component={Profile} />
  <Route 
    path="/:username"
    filter={location => {
      return location.pathcomponents[1] && reserved.has(location.pathcomponents[1])
    }}
    component={Profile}
    />
  <Route path="/:username/:resource" component={ResourcePage} />
</Switch>

// or

<Switch> 
  <Route 
    path="/:username"
    filter={location => {
      return !location.pathcomponents[1] || reserved.has(location.pathcomponents[1])
    }}
    component={Profile}
    />
  <Route path="/:username/:resource" component={ResourcePage} />
</Switch>
```
Here the `match` object would be the expected value in that it would not include the sub route as part of it's match. You could even imagine allowing an asynchronous Promise version which would display some temporary loading component also specifiable on the route.

```jsx
<Switch> 
  <Route
    path="/:username/:resource"
    filter={location => {
      return server.doesResourceExistAsync(location.pathcomponents[1])
    }}
    waitingComponent={ResourceLoading}
    component={ResourcePage}
    />
  <Route component={NotFound} />
<Switch> 
```

The nice thing here is that the page would route directly to `NotFound` if the server filtered the route without requiring an awkward redirect after the path matched.

The filter function is not so nice because I imagine it could be confusing to people, but it would basically just be an additional filter on top of path.

Anyway, food for thought. It seems like a pretty common desire to do things like this (GitHub's url scheme is actually a great example of this). It would be super nice to have a built in way to verify with the server before navigating to a route based on the location.

**Comment by timdorr** [comment]
The problem us you can't render things asynchronously in React. And that's not really a problem for React Router to solve, since it's more generic than that. 

Potentially, it's something react-router-config could handle by adding an onEnter-like hook there. But you can solve it right now with the same techniques as the code splitting guide: https://reacttraining.com/react-router/web/guides/code-splitting
