### ISSUE TITLE
Switch doesn't react after async location change in react-native

### ISSUE THREAD

**Issue by dig3** [ReactTraining/react-router#4987]
## Version
react-router 4.1.1
react-router-native 4.1.1
react-router-redux 5.0.0-alpha.6
history 4.6.1

## Example repo
https://github.com/dig3/react-router-native-bug
Sorry for not adding styles ;)

## Steps to reproduce
1. `$ yarn`
2. `$ react-native run-ios`
3. Open Test-Native app in the simulator
4. Click the Link Page1
5. Click Async Page2 or Async Page2 Thunk
6. Wait 5 seconds

## Expected Behavior
After clicking one of the buttons in step 4 and waiting for 5 seconds, the location changes from `/page1` to `/page2` (the location change is showed in text below the `Welcome to React`), and the component associated with `/page2` is showed.

## Actual Behavior
The component associated with `/page2` never appears, nothing changes (I keep seeing the component associated with the last route `/page1`).

I tested the same behavior in a web app, and everything works! If it helps I can create a repo with that code.

**Comment by timdorr** [comment]
See this guide: https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/guides/blocked-updates.md

**Comment by dig3** [comment]
Thank you @timdorr !!!

**Comment by lynndylanhurley** [comment]
@dig3 - were you able to solve this? What was your workaround?

**Comment by dig3** [comment]
yep! :) I used the second approch that it's mentioned in the docs. 
Something like:
```
const Main = () => (
  <div>
    <Switch>
      <Route exact path="/" component={Index} />
      <Route exact path="/getting-started" component={GettingStarted} />
      <Route exact path="/signin" component={SignIn} />
      <Route component={NotFound} />
    </Switch>
  </div>
)
export default withRouter(connect(mapStateToProps)(Main))
```
