### ISSUE TITLE
 why React-Router destroy component instead of just hide it

### ISSUE THREAD

**Issue by GodEngine** [ReactTraining/react-router#4988]
My main aim is do not unmount components during navigate through the links. In my real project I have a complicated component with huge grid. So every time I go back to this component it sends request to server to get data. But I do not need such behavior。How to fixed it  and is there some config can make it？

hope your answer....

**Comment by timdorr** [comment]
This is just how React works. When a component disappears from the tree, it is removed from the DOM. If you want to leave components around, use the `render` prop of Route.

**Comment by ryanhomer** [comment]
I'm using React 15.5.4 and RR 4.1.0 and I'm using the Route `render` property but my component keeps getting re-created. I've even tried to create a single component in the parent component's constructor and re-use that each time. And it's not only that the component unmounts and remounts, but also gets recreated completely.

Any insight into why this is happening would be greatly appreciated.

```
class App extends React.Component {
  constructor(props) {
    super(props);
    this.myDashboard = React.createElement(Dashboard);
  }

  renderDashboard = () => {
    return this.myDashboard;
  }

  render() {
    return (
      <Router>
        <Route exact path="/" render={this.renderDashboard}/>
        <Route exact path="/maintenance/" render={this.renderDashboard}/>
      </Router>
    );
  }
}
```

**Comment by ryanhomer** [comment]
React 15.5.4, RR 4.10

I am using the `render` prop but in my case the behaviour is no different than using the `component` prop. Basically, I have this:
```
  <BrowserRouter>
    <Switch>
      <Route exact path="/" render={() => <Dashboard />}/>
      ...
    </Switch>
  </BrowserRouter>
```

With some logging in `constructor`, `componentDidMount` and `componentWillUnmount`, I can see that the `Dashboard` component unmounts when I switch away from it to another route and a new one gets created and mounted when I switch back to it. I've also tried without the `Switch`, no difference.

Furthermore, I've even tried to create a singular instance with `const dashboard = <Dashboard />` in the global space and reuse `dashboard` as in `<Route exact path="/" render={() => dashboard}/>` but I get the same exact results.

Any idea what the issue might be?

The dashboard is going to have many sections, some with graphs and I'm concerned that it's going to be too expensive to keep creating a new Dashboard.

**Comment by JustFly1984** [comment]
It is normal react behaviour.

If you need better performance in your dynamic charts, graphs, etc, use
<canvas /> based once, and use redux to store ref to canvas element, and
substitute canvas element on componentDidMount. BTW if you use websockets,
you can keep socket instance in redux too.

2017-05-31 7:01 GMT+08:00 Ryan Homer <notifications@github.com>:

**Comment by timdorr** [comment]
> BTW if you use websockets, you can keep socket instance in redux too.

100% **DO NOT** do this. Your Redux state should *always* be serializable. A websocket isn't.

**Comment by JustFly1984** [comment]
Please, explain, why can't I use redux to store socket reference?

I use immutable.js as initialState, and I do not see downsides. Why should
I care, about serializability of socket?

Currently my projects using this approach, and I do not see any memory
leaks. What bad could happen?

**Comment by timdorr** [comment]
Tons of Redux tooling relies on a serializable state. Things will break in unexpected and Very Bad™ ways when you pass that tooling something it can't serialize. You'll end up making headaches for your coworkers and future self.

**Comment by JustFly1984** [comment]
Can you name most often used tool for redux which does serialising?

Which other options do I have to save socket object, or HTML element like
canvas etc on componentWillUnmount and restore on mount?

**Comment by timdorr** [comment]
setState and context. You don't have to store everything in Redux. In fact, it's better the less you put in there.

**Comment by JustFly1984** [comment]
setState is useless in my case, cos it get lost on component unmount.

The idea about context sounds better, will try it. Thanx.

2017-06-05 22:09 GMT+08:00 Tim Dorr <notifications@github.com>:

**Comment by JustFly1984** [comment]
I Made a top HOC component SocketRouter, and providing sockets through
context, everything is fine.
Still have questions on how to store DOM elements like canvas.

The main issue is React rerendering parent component with child canvas,
while drawing happening, and drawing happens in memory by old canvas. So
currently on unmount I save reference to redux, but on componentWillMount,
substitute old canvas back.

How can I do that without redux?

2017-06-06 4:31 GMT+08:00 Alexey Lyahov <justfly1984@gmail.com>:

**Comment by jacobweber** [comment]
I'm pretty new to React. Am I understanding this correctly? Say you wanted to make, say, a multi-tabbed interface similar to Apple's iOS App Store app. When you switch tabs via URL using react-router, there's no way to make it just hide the tabs' DOM elements rather than destroying them? This seems crazy to me, but maybe I'm misunderstanding. This would mean that every little bit of state in each tab -- the scroll position, any user input, table sorting, etc. -- all needs to be pushed up to the parent component, and the DOM elements need to be re-created whenever you switch tabs. Is that correct? This seems like an unnecessarily slow and painful way to do things.
