### ISSUE TITLE
Link props pathname is double encoded with reserved characters

### ISSUE THREAD

**Issue by wilfrem** [ReactTraining/react-router#4990]
There is no way to set pathname which has encoded reserved character (`; , / ? : @ & = + $`)

## Version
4.1.1

## Test Case
https://codepen.io/wilfrem/pen/MmapNM

## Steps to reproduce
1. Set Link to.pathname encoded value. for example `/tag/foo%2Fbar` (`%2F` is encoded `/`)
2. render it and check link url

## Expected Behavior
link url is `/tag/foo%2Fbar`

## Actual Behavior
link url is `/tag/foo%25%2Fbar`

**Comment by timdorr** [comment]
Don't encode the values up-front. The history library does this for you. See: ReactTraining/history#442

**Comment by wilfrem** [comment]
Don't encode the values up-front?

So, What if the user input is included in the path?
`<Link to={"/tag/" +userInputValue}>` is correct usage?
if userInputValue is `foo/bar`, It's not match `<Route exact path="/tag/:tagValue" />`.
It's match `<Route path="/tag/:tagValue" />` but match.params.tagValue is `foo`, not `foo/bar`.

Should I post this question to https://github.com/ReactTraining/history/issues ?

**Comment by pshrmn** [comment]
If you have a path segment that might include a forward slash, I would use the [one or more `+`](https://github.com/pillarjs/path-to-regexp#one-or-more) symbol.

```js
<Route path="/tag/:tagValue+" />
```

**Comment by wilfrem** [comment]
Path segment is ok.
So, how about question mark?
if userInputValue is `foo?bar=baz`, `<Link to={"/tag/" + userInputValue}>` is match to `<Route path="/tag/:tagValue+" />`. but `match.params.tagValue` is `foo`.
`<Link to={{pathname: "/tag/" + userInputValue}}>` is well match to `<Route path="/tag/:tagValue+" /> and  `match.params.tagValue` is `foo?bar=baz`. but if user reload this page, `match.params.tagValue` become to `foo`

It seems necessary to escape only reserved characters (`; , / ? : @ & = + $ #`).

**Comment by pshrmn** [comment]
There is actually some discussion about this in https://github.com/ReactTraining/history/issues/461

I think that I jumped the gun a bit in encoding in history's `createPath` function. I'm working on a comment about this there, but right now I'm fairly certain that that can be removed without breaking the decoding functionality.

**Comment by wilfrem** [comment]
Ok. I watch this discussion.
Thanks.
