### ISSUE TITLE
Can't import modules in Android 4.0.x - 4.1.x stock browser

### ISSUE THREAD

**Issue by dmtrdmtr** [ReactTraining/react-router#4991]
```js
TypeError: Cannot assign to read only property '__esModule' of #<Object>
```

There is a V8 <a href="https://bugs.chromium.org/p/v8/issues/detail?id=3334">bug</a>.

Solution is to build in <a href="http://2ality.com/2015/12/babel6-loose-mode.html">loose mode</a>.

Is it possible to add <a href="https://github.com/reactjs/redux/blob/master/.babelrc#L27">plugin</a> to `.babelrc` file?

**Comment by timdorr** [comment]
We don't support browsers that old. Your best bet is to just import directly from git and transpile with babel with whatever setttings you need.
