### ISSUE TITLE
Can't use index path (/) as parent component?

### ISSUE THREAD

**Issue by guzgarcia** [ReactTraining/react-router#4992]
I mount a `<Dashboard />` component on `/` with the following route structure:

    <Switch>
          <Route
            exact
            path="/"
            component={Home}
          />
          <Route
            path="/flows"
            component={Flows}
          />
          <Route
            path="/users"
            component={Users}
          />
          <Route
            path="/campaigns"
            component={Campaigns}
          />
      </Switch>

But the only component that is rendered is `Home`. If I go to `/anything` I get a blank page. I can solve this using a simple `/dashboard` instead `/` but I want to know if this is possible.

**Comment by timdorr** [comment]
Switch only renders the first matching route in its children. So, you can just add another Route to match `/dashboard` in there. What you've got is entirely expected behavior.

**Comment by guzgarcia** [comment]
I can't understand you. Why I need to add a `/dashboard` route if precisely **I don't want this route as parent**?

I want achieve the following:

/ -> Dashboard
/anything -> Anything (rendered inside Dashboard)

**Comment by pshrmn** [comment]
@guzgarcia `exact` means that that `<Route>` will only match the pathname `/`. If you want `/` to function as a catch-all route, you should move it to the bottom of your `<Switch>` and remove the `exact` prop.

**Comment by guzgarcia** [comment]
@pshrmn Thanks for reply. I delete the `exact` prop and move the route to switch bottom. This is how it looks:

``` javascript
<Switch>
   <Route
      path="/flows"
      component={Flows}
    />
    <Route
       path="/users"
       component={Users}
    />
    <Route
       path="/campaigns"
       component={Campaigns}
    />
    <Route
       path="/"
       component={Home}
    />
</Switch>
```
The result is the same as before, the `Home` component is rendered but else don't. Sorry if I don't understand some concepts, I'm learning react-router yet.

**Comment by guzgarcia** [comment]
Solved. I forget delete the `exact` prop from main route.

Thanks for your time, guys.
