### ISSUE TITLE
ReactRouter.browserHistory  coming undefined

### ISSUE THREAD

**Issue by amit-mn** [ReactTraining/react-router#4995]
react router giving error of Uncaught TypeError: Cannot read property 'location' of undefined

**Comment by alessandrocm** [comment]
I am also getting this. How did you resolve it?

**Comment by timdorr** [comment]
BrowserHistory doesn't exist in 4.0. Please read the docs.

**Comment by cloover** [comment]
where is the docs for 4.0 ?

**Comment by u-can-miracle** [comment]
`BrowserHistory` now placed in `history` module here is solution
https://stackoverflow.com/questions/43822589/react-router-v4-browserhistory-is-undefined
