### ISSUE TITLE
Documentation Website IE 11 compatibility

### ISSUE THREAD

**Issue by hilde2** [ReactTraining/react-router#4999]
Hi !

Where can I found compatibility informations ?

V4 doesn't seems to work with IE11 (version 11), even the doc doesn't load : https://reacttraining.com/react-router/web/guides/quick-start

**Comment by timdorr** [comment]
We do specifically test IE11: https://github.com/ReactTraining/react-router/blob/master/packages/react-router/karma.conf.js#L48-L53

Without some sort of error message, there's nothing to indicate any problem with the library.

**Comment by Skeptron** [comment]
Same issue here. This page does not work : https://reacttraining.com/react-router/web/api/Prompt

The page seems to load forever. No error in the console. 

Tested with IE11 version 11.0.9600.18537

**Comment by pshrmn** [comment]
The error is:

```
Object doesn't support property or method 'find'
```

Caused by [this line](https://github.com/ReactTraining/react-router/blob/master/packages/react-router-website/modules/components/Guide.js#L11)

```js
const doc = data.guides.find(doc => mod === doc.title.slug)
```

I believe that the website just needs to add [`babel-polyfill`](https://babeljs.io/docs/usage/polyfill/) to its webpack config `entry`.
