### ISSUE TITLE
Changing Url

### ISSUE THREAD

**Issue by sughanpandita** [ReactTraining/react-router#5005]
How can I change current Url on button click event?
I don't want to navigate to component onClick event, Just wanted to change Url
Example:
Current Url:
www.googl.com
New Url:
www.google.com/user/1

**Comment by mjackson** [comment]
```jsx
<Route render={({ history }) => {
  <button onClick={() => history.push('/the/path') }>click me</button>
}/>
```

**Comment by sughanpandita** [comment]
Thanks @mjackson 

Is it possible change 
Example:-
www.google.com/user1/profile
to
www.google.com/user2/profile

without changing data in catche
