### ISSUE TITLE
Multilanguage

### ISSUE THREAD

**Issue by olegreznichenko** [ReactTraining/react-router#5006]
Hi!
How to setup multilanguage routing in v4.
1) Need to replace URL. example `/news` -> `ua/news`. `en` lang is a default and don't place in routes & URL.
2) Need to add to all links lang prefix.
I tried dynamic change `basename` prop in `BrowserRouter` but this doesn't work.
I tried dynamic change `path` prop in `Route` but this doesn't work.
I can add lang prefix to link like this `<Link to={`${lang}/news`}>`, but if i have many links in different pages, again and again, repeat yourself ? basename work for this perfect but he is static
Please help. thank.

**Comment by mjackson** [comment]
I'd suggest creating a function that you can use to wrap all your `<Route path>` and `<Link to>` strings.

```jsx
const langPrefix = (path) => `${getTheCurrentLanguage()}/${path}`

<Route path={langPrefix('home')}/>
```
