### ISSUE TITLE
A more proactive Switch (RFC)

### ISSUE THREAD

**Issue by fingermark** [ReactTraining/react-router#5011]
## Version
4.0.0

Let's say I wanted to prevent a user from navigating away from a certain page.  (Probably due to my own ignorance I find `block` to be fragile, as it seems like a lock, and with the prompt it could cause problems when trying to transition while a prompt is still up.)  So I define a stickyTo with a `Redirect` according to some props.  The problem is that if I'm already on the current page then the component unmounts with `Switch` because it removes that element and only returns the Redirect.  What if we could enhance `Switch` to return the Redirect *and* the current page we are about to transition to, which would be the current page in the case.  This way it doesn't unmount the component, mount the intended navigation, and then redirect and mount the current component again.

I haven't tested this code under various conditions, but what do you think?

```javascript
<Switch>
  {stickyTo && stickyTo !== location.pathname && <Redirect from={location.pathname} to={stickyTo} />}
  <Route exact path="/" component={Home} />
  <Route path="/about" component={About} />
  <Route path="/topics" component={Topics} />
  <Route component={NotFound} />
</Switch>
```

```javascript
import React from 'react';
import PropTypes from 'prop-types';
import warning from 'warning';
import { matchPath } from 'react-router-dom';

const isRedirectElement = element => {
  return !!element.props.to;
};

/**
 * The public API for rendering the first <Route> that matches.
 */
class Switch extends React.Component {
  static contextTypes = {
    router: PropTypes.shape({
      route: PropTypes.object.isRequired
    }).isRequired
  };

  static propTypes = {
    children: PropTypes.node,
    location: PropTypes.object
  };

  componentWillReceiveProps(nextProps) {
    warning(
      !(nextProps.location && !this.props.location),
      '<Switch> elements should not change from uncontrolled to controlled (or vice versa). You initially used no "location" prop and then provided one on a subsequent render.'
    );

    warning(
      !(!nextProps.location && this.props.location),
      '<Switch> elements should not change from controlled to uncontrolled (or vice versa). You provided a "location" prop initially but omitted it on a subsequent render.'
    );
  }

  render() {
    const { route } = this.context.router;
    const { children } = this.props;
    const location = this.props.location || route.location;

    // find a redirect from
    let fromMatch, fromChild;
    React.Children.forEach(children, element => {
      if (!React.isValidElement(element)) return;

      const { exact, strict, from, to } = element.props;

      if (fromMatch == null) {
        fromChild = element;
        fromMatch = from
          ? matchPath(location.pathname, { from, exact, strict })
          : null;
      }
    });

    // find a match of the location.pathname or from.to
    let match, child;
    React.Children.forEach(children, element => {
      if (!React.isValidElement(element)) return;

      const { path: pathProp, exact, strict, from } = element.props;
      const path = pathProp || from;

      // skip redirects if we've already discovered one
      if (fromMatch && isRedirectElement(element)) {
        return;
      }

      const pathname = (fromChild && fromChild.props.to) || location.pathname;

      if (match == null) {
        child = element;
        match = path
          ? matchPath(pathname, { path, exact, strict })
          : route.match;
      }
    });

    return [
      match
        ? React.cloneElement(child, { location, computedMatch: match })
        : null,
      fromMatch
        ? React.cloneElement(fromChild, { location, computedMatch: fromMatch })
        : null
    ];
  }
}

export default Switch;
```

EDIT: Requires React 16

**Comment by timdorr** [comment]
Well, first off, you can't render an array of elements (until React 16, at least).

But I'm a little confused here. You want to render the Redirect but not have it actually redirect under some certain conditions? Why can't your route component render the redirect instead of putting it in the Switch?

**Comment by fingermark** [comment]
Let's say I have 20 Routes.  1 route is activated by a prop.  For example, let's call it `status`.  When `status === 'active'` then I force the user to stay on `/active`.  If the user clicks on any other links, such as `/other` then they should be taken to `/active` without having Active unmount and lose its state.  `/active` will also have sub-routes that are navigable.

So, I do want the redirect to occur, but just no when the user is already on `/active` so that it's not an infinite redirect.  The main goal is of this change would be to prevent the unmounting of the component.  This change would also prevent a component from mounting when it's not even going to be rendered due to the redirect.

**Comment by fingermark** [comment]
Maybe this is something that's just specific to my problem.  Just to show how else I could have solved this, here's the alternative:

```javascript
const Block = ({to, location}) => {
  const { location, to } = this.props;

  const isBlocking = to !== '';

  return (
    <Prompt
      when={isBlocking}
      message={location => {
        if (matchPath(location.pathname, {path: to, exact: false }) === null) {
          return 'block';
        }
      }}
    />
  );
}

const RedirectIfNeeded = ({ to, location }) => {
  if (to && matchPath(location.pathname, {path: to, exact: false }) === null) {
    return <Redirect from={location.pathname} to={to} />;
  } else {
    return null;
  }
};

const getConfirmation = (message, callback) => {
  const allowTransition = message === 'block' ? false : window.confirm(message); // Eww
  callback(allowTransition);
};
```

**Comment by fingermark** [comment]
I'll re-open w/ a pull request if I think this is worthwhile.  For now I'm closing.
