### ISSUE TITLE
Routed Page Calling Const Variable

### ISSUE THREAD

**Issue by patientplatypus** [ReactTraining/react-router#5012]
This is less a bug than an annoyance. Suppose I have 
    
```
const StatisticsPage = () => {
      return(
        <div>
          <StatisticsPage/>
        </div>
      )
    }
```

Rather than being routed to the statistics page, like I would expect by calling 

`<Route path='/StatisticsPage' component={StatisticsPage}/>`

I am infinitely looped through the const variable as react router 4 doesn't understand that <StatisticsPage> means the page and not the const variable. Rather I have to do this: 

```
const xStatisticsPagex = () => {
      return(
        <div>
          <StatisticsPage/>
        </div>
      )
}

<Route path='/StatisticsPage' component={xStatisticsPagex}/>
```
Is there a simple way of changing this? 

## Version
4.0.0

## Test Case
https://codepen.io/ReactJSTraining/pen/jyYjeW

**Comment by pshrmn** [comment]
That is just recursion. Not even React specific, let alone React Router specific. JSX just obfuscates the function call.

**Comment by patientplatypus** [comment]
I understand that it's recursion. My issue is that react doesn't understand the difference between <StatisticsPage /> and const StatisticsPage. Please reread my post.

**Comment by timdorr** [comment]
You can't reference a variable like that. You're essentially doing `const foo = () => foo()`. This has nothing to do with this library or even React. It's just how JavaScript works.

**Comment by patientplatypus** [comment]
I'm not sure that I agree. I think that React should know the difference
between <variableforsheet/> and const variable. I don't know how much more
I can say to make my point clearer, but I think we're talking past each
other at this point. If it's something that you don't think is an issue,
that's fine, I just thought it might be an easy fix. It took me an hour or
two to figure out and I just wanted to help other people not waste their
time. But let's drop it, we can't come to an agreement.

**Comment by timdorr** [comment]
Again, this has nothing to do with React. It's a language level thing. You're creating an infinite loop.

Type this into the Javascript console: `const foo = () => foo()` and then run it: `foo()`. You'll get this error: `VM74:1 Uncaught RangeError: Maximum call stack size exceeded` That's what I mean.

In fact, look at the code [after it's been transformed from JSX](https://babeljs.io/repl/#?babili=false&evaluate=false&lineWrap=false&presets=react&targets=&browsers=&builtIns=false&debug=false&experimental=true&loose=true&spec=false&code=const%20StatisticsPage%20%3D%20()%20%3D%3E%20%7B%0A%20%20return(%0A%20%20%20%20%3Cdiv%3E%0A%20%20%20%20%20%20%3CStatisticsPage%2F%3E%0A%20%20%20%20%3C%2Fdiv%3E%0A%20%20)%0A%7D&playground=false):
```js
const StatisticsPage = () => {
  return React.createElement(
    "div",
    null,
    React.createElement(StatisticsPage, null)
  );
};
```
Presumably you're importing `<StatisticsPage>` somewhere above. Within the closure of the StatisticsPage functional component (the const), you are referencing a variable of the same name. That is overwriting the original import statement and therefore reference to it has changed when `React.createElement` finally gets called.

**Comment by patientplatypus** [comment]
I know what an infinite loop is. I'm saying that react should recognize
<variable /> and const variable as DIFFERENT, but it does not. Please
reread my original post.

**Comment by timdorr** [comment]
Did you see the transpiled code? It's not a matter of React recognizing anything. It's the variable you're referencing. You're redefining what the StatisticsPage variable points to. 

I'm sorry you're not getting this, but it's not something any library can solve. The problem is at the language level.
