### ISSUE TITLE
Default/404 route is always rendering

### ISSUE THREAD

**Issue by lumio** [ReactTraining/react-router#5013]
## Version
react-router-dom 4.1.1
react-redux 5.0.4

## Steps to reproduce
```jsx
ReactDOM.render(
  <Provider store={ store }>
    <Router>
      <Page>
        <Route exact path='/' component={ Home } />
        <Route exact path='/builder' component={ Builder } />
        <Route exact path='/form/:formId' component={ Form } />
        <Route component={ NotFound } />
      </Page>
    </Router>
  </Provider>,
  document.getElementById( 'root' ),
);
```

## Expected Behavior
The last `Route` should only render, if there is no other match.

## Actual Behavior
The last Route renders no matter what.

**Comment by YasserKaddour** [comment]
This is the correct behavior, for your expected behavior use [`Switch`](https://reacttraining.com/react-router/web/api/Switch)
```jsx
<Switch>
  <Route exact path='/' component={ Home } />
  <Route exact path='/builder' component={ Builder } />
  <Route exact path='/form/:formId' component={ Form } />
  <Route component={ NotFound } />
</Switch>
```

**Comment by lumio** [comment]
Ah, I must have overlooked the Switch component. Thank you

**Comment by hasanmumin** [comment]
```
<BrowserRouter>
                <Switch>
                    <Workspace>
                        <Route exact path='/' component={Dashboard} />
                        {routes}
                        <Route component={NotFound} />
                    </Workspace>
                </Switch>
            </BrowserRouter>
```
When i use customer component, it is still happening. Any idea or solution ?

**Comment by lumio** [comment]
Your `Switch` might have problems with `Workspace`. As far as I know the Switch component should only contain Routes and no other elements.

**Comment by hasanmumin** [comment]
@lumio i don't this it is "mandatory". You can use even a "div" instead of "Switch". this is not the case.

**Comment by mndvn** [comment]
Have you solved the problem? I came across with the same situation. Is there any person that can help me?

**Comment by hasanmumin** [comment]
if fixed problem by
```

<BrowserRouter>
<Workspace>
<Switch>
<Route exact path='/' component={Dashboard} />
{routes}
<Route component={NotFound} />
</Switch>
</Workspace>
</BrowserRouter>

```

`and export default Workspace to export default withRouter(Workspace)`

**Comment by mndvn** [comment]
Hi Hasan,

Thanks for your suggestion. I am gonna do that as much as possible. I have
a little problem. I will open an issue. Could you have a look to that?
https://github.com/mndvn/visioncenter.se/issues/4

Best Regards...
