### ISSUE TITLE
rendering component with Redirect

### ISSUE THREAD

**Issue by valorloff** [ReactTraining/react-router#5015]
`meteor npm install --save react-router-dom`
```
export default class Routes extends React.Component {
    render() {
      return (
      <Switch>
          <Redirect exact from="/" to="/catalog" />
          <Route path='/catalog' component={Test}/>
      </Switch>
    )
  }
}
```
if i go to "/catalog", component Test renders properly, but if i go to home "/", only url changed to "/catalog" and nothing renders.
I tried also:
`<Route exact path "/" render={()=><Redirect to="/catalog" />} >`
same result, url changed only without component rendering

**Comment by valorloff** [comment]
[update] 
this is strange, but after add data Container to component Test, which is wait for subscription data, redirect started working...

**Comment by timdorr** [comment]
Since you're using meteor, this should fix it: https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/guides/blocked-updates.md
