### ISSUE TITLE
Accessing push and goBack from helper functions?

### ISSUE THREAD

**Issue by IljaDaderko** [ReactTraining/react-router#5016]
I am wondering if it is possible to access push and goBack functions in a non react component file, i.e. within helper functions file in react-native project? At present when my app initiates I am storing these in a redux state, I have no need to store full router there, just these two functions so I can than programatically redirect user, but at present it feels verbose, hence the question.

Or will I have to connect router with my state / store to access these?

**Comment by timdorr** [comment]
Just use ConnectedRouter from react-router-redux@5

**Comment by IljaDaderko** [comment]
@timdorr could you please suggest history object that would go for react-native? As one shown in example `const history = createHistory()` mentions it is for browser.

**Comment by timdorr** [comment]
createMemoryHistory is designed for DOM-less environments
