### ISSUE TITLE
Ensuring that "path/modal/id" doesn't re-trigger "path/*"

### ISSUE THREAD

**Issue by IljaDaderko** [ReactTraining/react-router#5018]
I'm trying to set up routing for modals with logic somewhat like this:

**Page**
```
<Route
  path="/page/*"
  component={Page}
/>
```

**Modal**
```
<Route
  path="/page/modal/id"
  component={Modal}
/>
```

Now the reason behind routing like this is to make sure that page is still displayed behind the modal while it is open.

The issue I am experiencing is due to having animated page routes. Whenever user goes to modal path it also satisfies page rout hence triggering the animation, and it looks somewhat like this:

![example](https://media.giphy.com/media/3oKIPmMvOqKHekSFs4/giphy.gif)

As you can see every time modal is open, page behind it animates in again. Is there a way to bypass this and make sure that page only animates when path is `/page/`, but at the same time is still shown behind the modal?

Page animations are based on this guide: https://reacttraining.com/react-router/native/guides/animation

**Comment by pshrmn** [comment]
Am I right in assuming that you are setting the animation key using `location.pathname` (or possibly `location.key`)? If that is the case, then the issue that you are running into is that the key changes when the modal is opened.

What I would probably do is something like the [modal gallery example](https://reacttraining.com/react-router/web/example/modal-gallery) and keep a reference to the previous location. Then, when you  detect that you're in "modal" mode you would use the previous location as the `<Switch>` key.

If I am wrong on your implementation, hopefully this at least pushes you in the right direction.

Alternatively, you might benefit from something like the [`wrapSwitch`](https://github.com/pshrmn/rrc/blob/master/docs/wrapSwitch.md) function that I wrote in `rrc`. That allows you to use the `match` object generated by a `<Switch>` in setting the animated element's key`.

**Comment by IljaDaderko** [comment]
@pshrmn Thank you for the suggestion! Just adding state logic to modal routes solved my issue by not triggering page animations on those path changes :)
