### ISSUE TITLE
react-router-redux: context history errors

### ISSUE THREAD

**Issue by HoneyryderChuck** [ReactTraining/react-router#5022]
## Version
5.0.0-alpha.6
with
react-router-4.1.1

## Steps to reproduce

I'm trying to connect the router with the store, but haven't been successful since implementing react-router v4.

The setup is simple: I set the reducer with the router reducer:

```js
import { routerReducer } from 'react-router-redux'

const reducer = combineReducers({
  ...reducers,
  router: routerReducer
})
```

I then set an history context and the middleware:

```js
import { routerMiddleware } from 'react-router-redux'
import createHistory from 'history/createBrowserHistory'

const history = createHistory()

const finalCreateStore = compose(
  applyMiddleware(
		thunkMiddleware,
		routerMiddleware(history)
	)
)
```

and then I stitch it up in the main component:

```js
import { ConnectedRouter as Router } from 'react-router-redux' 

const preloadedState = window.__PRELOADED_STATE__
delete window.__PRELOADED_STATE__

const store = createStore(reducer, preloadedState, middlewareStore)

ReactDOM.render(
	<Provider store={store}>
		<Router history={history}>
			<App />
		</Router>
	</Provider>,
  root	
)
```

All of this is fairly standard and according to documentation, and the only difference I find is that there is no sync history step from the preloaded history and the browser history. 

However, it all loads with errors. 

## Expected Behavior

That links work and go through the redux state update loop.

## Actual Behavior

As I refresh the page, I get load errors referring to context:

```
Warning: Failed context type: The context `history` is marked as required in `Route`, but its value is `undefined`.
    in Route (created by withRouter(Connect(Navigation)))
    in withRouter(Connect(Navigation)) (created by App)
    in div (created by App)
    in IntlProvider (created by App)
    in App (created by Connect(App))
    in Connect(App)
    in Router (created by ConnectedRouter)
    in ConnectedRouter
    in Provider 
Warning: Failed context type: The context `route` is marked as required in `Route`, but its value is `undefined`.
    in Route (created by withRouter(Connect(Navigation)))
    in withRouter(Connect(Navigation)) (created by App)
    in div (created by App)
    in IntlProvider (created by App)
    in App (created by Connect(App))
    in Connect(App)
    in Router (created by ConnectedRouter)
    in ConnectedRouter
    in Provider  
```

Is this a usage error, or a not-yet-fixed alpha issue?

**Comment by Kevenvz** [comment]
Correct me if I'm wrong but your javascript is modular and the `history` variable isn't a global varaible so you should export and import it if the code is in different files.

**Comment by HoneyryderChuck** [comment]
@Kevenvz yes, it is being imported/exported.

**Comment by timdorr** [comment]
I don't see any reason for that to happen. ConnectedRouter is an ancestor in your tree. I've gotta chalk it up to a usage error because that's a React feature misbehaving. Maybe blow away node_modules and reinstall?

**Comment by HoneyryderChuck** [comment]
I got around to fix it. I was using "react-router-dom@next", everything else was using the exact same versions of react-router's "package.json". I upgraded to 4.1.1 and it's all good now.
