### ISSUE TITLE
React-redux-router doesn't trigger re-render when pushed in promise

### ISSUE THREAD

**Issue by Mathieuu** [ReactTraining/react-router#5029]
## Version
5.0.0-alpha.6

## Test Case
My use-case is submitting a form. When the form is submitted, I do an API call with an asynchronous action and if the promise resolves, then I redirect to the newly created document.

Here's a very simplified version of the problem:

In a container,
```js
// Url will change, action would be dispatched and the store updated but react-router won't be triggered
var Promise = require('bluebird');
[...]
function mapDispatchToProps(dispatch) {
  return {
    onSubmit: function() {
      Promise.resolve().then(function() {
        dispatch(require('react-router-redux').push('/login'));
      });
    });
  };
}
```

```js
// Without the promise, it works
var Promise = require('bluebird');
[...]
function mapDispatchToProps(dispatch) {
  return {
    onSubmit: function() {
        dispatch(require('react-router-redux').push('/login'));
    });
  };
}
```

```js
// React-router triggers if another action modifies the store right after (even push)
var Promise = require('bluebird');
[...]
function mapDispatchToProps(dispatch) {
  return {
    onSubmit: function(formData) {
      Promise.resolve().then(function() {
        dispatch(require('react-router-redux').push('/login'));
        dispatch(require('react-router-redux').push('/login')); // Or any other action modifying the store
      });
    });
  };
}

Any idea why this is happening?

**Comment by timdorr** [comment]
See this guide: https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/guides/blocked-updates.md

**Comment by atillaordog** [comment]
This guide you link everywhere did not help anyone so far. Linking a link is not providing a solution. I have the same issue, but the example given in the article did not help, at all. 

So, please, provide a better example, or help out people in threads. 

Seeing this link in every thread I open is starting to get annoying.
