### ISSUE TITLE
Scroll restoration doc: example not working as expected

### ISSUE THREAD

**Issue by Floriferous** [ReactTraining/react-router#5031]
## Version
4.0.0

In the docs about [scroll restoration](https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/docs/guides/scroll-restoration.md), the part which explains how to scroll to top on a route change:

Use this component:

```jsx
class ScrollToTop extends Component {
  componentDidUpdate(prevProps) {
    console.log(this.props); // no location prop
    if (this.props.location !== prevProps.location) {
      // never triggered
      window.scrollTo(0, 0);
    }
  }

  render() {
    return this.props.children;
  }
}
```

And incorporate it at the root of the Router like this (Router = BrowserRouter in my case):

```jsx
const RenderRoutes = () => (
    <Router>
      <ScrollToTop>
        <Switch>
          <Route path="/app" render={props => <UserRoutes {...props} />} />
          <Route path="/admin" render={props => <AdminRoutes {...props} />} />
          <Route path="/" render={props => <PublicRoutes {...props} />} />
        </Switch>
      </ScrollToTop>
    </Router>
);
```

However this currently does not work, as the component `<ScrollToTop />` does not have access to the `location` prop, and only has `children` when I log it. From my understanding, you get access to these router props only through `<Route />` components, which would explain why this does not work, or am I missing something?

**Comment by celsomtrindade** [comment]
Are you exporting the component using `withRouter`? Like this: `export default withRouter(ScrollToTop)`. If not, that may be the problem.

**Comment by Floriferous** [comment]
That was it, my bad! Didn't know that function existed.

Would it make sense if I made a tiny PR that adds one of these to make it even more friendly?:

At the top:
```jsx
import { withRouter } from 'react-router'
```

Or add an extra line in the text: 
"Make sure to export the component with `withRouter` to give it access to the router's props"

**Comment by celsomtrindade** [comment]
I'm not in position to answer that, but it seems like reasonable to me.

**Comment by codermango** [comment]
Hi, can I continue ask something about the window.scrollTo(0, 0) doesn't work.
Actually my project has desktop and mobile version, desktop works, but mobile doesn't work. The ScrollToTop component is on top of the both, I really don't know why it doesn't work on mobile.

**Comment by edoardo-bluframe** [comment]
Hey everybody!

I just created this to solve the scroll to top problem [https://github.com/bluframe/react-router-scroll-top](https://github.com/bluframe/react-router-scroll-top)

Please **please** go super easy on me

This is my first ever open source component, and I hope I am following best practices but there are probably **a lot** of things I missed - I hope I did it right!

Suggestions, improvements, PRs all welcome!

It's just a shorthand for exactly what the official `react-router` documentation suggests, and I linked to the documentation on `README.md`

For me it's really useful on the projects I'm building - I don't have to create a `ScrollToTop` component every time

Is this useful for you guys as well?
