### ISSUE TITLE
Improve examples in the docs for React Router Web

### ISSUE THREAD

**Issue by cquillen2003** [ReactTraining/react-router#5033]
I want a standard horizontal navbar (like Bootstrap's navbar) that routes to individual pages.  Each page will be a React component.  A couple of pages (login for example) will not have the navbar. Can someone point me to a simple way to do this using JSX or a route config?  Examples of both would be helpful.

I've read the docs and see that the Basic example and Sidebar example are similar, but neither example renders React components.  Both examples render only text or HTML.  One example uses JSX and the other uses a route config array.  Beyond reading the docs, I've also been trying to get this working but I cannot wrap my head around it.  I have a lot of experience with routing from AngularJS, Angular 2, and Ember, so I am not new to routing at all.  I honestly think the examples and/or docs need improvement.

Drawing from past experience, I've tried nesting routes, but that gives me a warning.  I must say that my experience with v4 so far has been a very time consuming and frustrating experience.  Any help will be greatly appreciated.

**Comment by ndaljr** [comment]
I was actually going to open an issue for this as well. The documentation is basic and is insufficient for use cases such as this. Tagging along this issue, is it possible to do something like this? It goes something like this. A login component only matches on the /login route. A navbar component only renders on routes that don't match login.

**Comment by timdorr** [comment]
Just use a Switch with a null rendering Route for any routes where you don't want things to appear:
```js
<Switch>
  <Route path='/login' render={() => null} />
  <Route path='/forgot_password' render={() => null} />
  <Route path='/' component={NavBar} />
</Switch>
```
As for improved examples, that is better done via PR. Just registering complaints doesn't really offer any guidance for how to improve them.  Offering up solutions, via a PR, both give us something specific to discuss and get things resolved significantly faster.
