### ISSUE TITLE
Having UNMET PEER DEPENDENCY warning while npm install

### ISSUE THREAD

**Issue by vincent714** [ReactTraining/react-router#5035]
## Version
4.1.1

## Test Case
https://codepen.io/ReactJSTraining/pen/jyYjeW

## Steps to reproduce
Tried to update react-router version from 2.7.0 to 4.1.1.
After installing, the log showed up 
```sh
UNMET PEER DEPENDENCY react-router@4.1.1
```
Does anyone know how to fix this?
Thanks.

**Comment by timdorr** [comment]
Upgrade your version of npm. It should be telling you what is requesting that peer dep.
