### ISSUE TITLE
Remove initial "@@router/LOCATION_CHANGE" action

### ISSUE THREAD

**Issue by DimitryDushkin** [ReactTraining/react-router#5038]
On `ConnectedRouter` (from `react-router-redux`) initialization action `@@router/LOCATION_CHANGE` is fired with current path as payload.

_I think this behaviour is misleading because no actual location change is happening._

If this behaviour is needed to fill state with initial data I suggest to rename it to something like `@@router/LOCATION_INIT`. 

## Version
4.0.0

**Comment by timdorr** [comment]
A location change is happening, just outside the context of your application. It's going from about:blank to whatever URL it loads up as. There's nothing special about this.

**Comment by DimitryDushkin** [comment]
And if I just refresh page? Location is not changed.

**Comment by DimitryDushkin** [comment]
Also native history api do not demonstrate such behavior.
