### ISSUE TITLE
Typescript error: Type 'typeof App' is not assignable to type 'StatelessComponent<void | RouteComponentProps<any>>

### ISSUE THREAD

**Issue by VALIKCOOL** [ReactTraining/react-router#5040]
hi everyone. I am using latest version of both React-Router and @types but having and issue with passing my components into Route component prop. Typescript throws an error:
```
(22,25): error TS2322: Type 'typeof App' is not assignable to type 'StatelessComponent<void | RouteComponentProps<any>> | ComponentClass<void | RouteComponentP
rops<a...'.
  Type 'typeof App' is not assignable to type 'ComponentClass<void | RouteComponentProps<any>>'.
```
![1](https://cloud.githubusercontent.com/assets/10166922/25446468/53b9a6b0-2aba-11e7-9db4-20fd1bc92990.PNG)
![2](https://cloud.githubusercontent.com/assets/10166922/25446473/55c29714-2aba-11e7-946b-78331bba1402.PNG)

**Comment by timdorr** [comment]
We don't maintain these typings. Please ask on the appropriate repo.
