### ISSUE TITLE
Improve connection with redux docs

### ISSUE THREAD

**Issue by vhuerta** [ReactTraining/react-router#5042]
Hi, i just be following the docs but when i start reading about how to connect with redux i can't found what to do after use withRouter function, so i just write this little gist after fight with my code for a while, maybe it would be a good improvement in the documentation example.

https://gist.github.com/vhuerta/4d47b099f3aae6a4d2a675496645f72d

Regards

**Comment by timdorr** [comment]
A PR would be better for this.
