### ISSUE TITLE
Export Route et al as connected/connectable components? [react-router-redux]

### ISSUE THREAD

**Issue by guy-kdm** [ReactTraining/react-router#5043]
Since [the SCU optimization doesn't seem to go away any time soon](https://github.com/reactjs/react-redux/pull/625) maybe we should address update blocking, and more generally having the redux store as the single source of truth™ more generally by allowing to switch the subscription module to the redux store. What do you think?

**Comment by timdorr** [comment]
Getting around that block happens at the route component, not on Route. You would basically have to reimplement Router and Route to make that work, which would kind of defeat the point.

**Comment by guy-kdm** [comment]
Hmm yeah, but this passing a prop just hack around SCU is somewhat error prone. Not sure but maybe it'll be a bit safer to get the Route component itself from the store, and have the ref update once in the store on url change. That way by default using Route with redux won't have an update blocking problem.
