### ISSUE TITLE
how to prevent render when i just need a hash redirect？

### ISSUE THREAD

**Issue by shanggqm** [ReactTraining/react-router#5048]
in Backbone.Router， there is a option named `trigger`  which is design for not trigger a hashchange event, 
```
router.navigate(url,{trigger:false});
```
is there a similar props for this feature？ how do i get this effect？
```js
/a                 -> /a/index?q=1
/a/index       -> /a/index?q=1
```

**Comment by timdorr** [comment]
There isn't anything like this in React Router.
