### ISSUE TITLE
Missing props in mapStateToProps

### ISSUE THREAD

**Issue by sun2rise** [ReactTraining/react-router#5049]
## Version
4.1.1

## Steps to reproduce
This component is querying a db via GraphQL thanks to Apollo. It is a GraphQL container.
It uses `compose` from `react-apollo` library in order to use [multiple enhanchers](http://dev.apollodata.com/react/api-graphql.html#compose) at the same time, in a readable way.

Example component:
```js
import React, { Component } from 'react';
import { connect } from 'react-redux';
import { graphql, compose, withApollo } from 'react-apollo';
import { myQuery } from './graphqlQuery';

class MyComponent extends Component {
  render() {
    const { exampleProp } = this.props;
    return null;
  }
}

function mapStateToProps(state, ownProps) {
  // I expect to see ownProps.exampleProp here but it is undefined
  console.log(ownProps.exampleProp);
}

export default compose(
  withApollo,
  connect(mapStateToProps),
  graphql(myQuery),
)(MyComponent);
```

## Expected Behavior
ownProps should contain the props passed to the component [as stated here](https://github.com/reactjs/react-redux/blob/master/docs/api.md#arguments)   
like:
```js
Object = {
  client: ApolloClient
  exampleProp: "propcontent",  // <-- this is going to be lost
  history: Object
  location: Object
  match: Object
  staticContext: undefined
  __proto__: Object
}
```

## Actual Behavior
instead ownProps contains only this:
```js
Object = {
  client: ApolloClient
  history: Object
  location: Object
  match: Object
  staticContext: undefined
  __proto__: Object
}
```
All the props that the component should have had from parents and from GraphQL response are missing, including, in this case, `exampleProp`.

**Comment by timdorr** [comment]
This doesn't have anything to do with React Router.

**Comment by sun2rise** [comment]
It happened just when I updated it from react-router v3.0.2, so I think it has.
Couldn't it be the connection with redux?

**Comment by timdorr** [comment]
Then it's most likely cause by this: https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/guides/blocked-updates.md

**Comment by sun2rise** [comment]
I read your link, thanks, but it doesn't seem the cause to me first because my component is actually re-rendered and second because is not location aware (I don't even try to read the location).

I tried to modify the export part like this:
```js
import { withRouter } from 'react-router-dom'

// ...

export default compose(
  withApollo,
  withRouter(connect(mapStateToProps)),
  graphql(myQuery),
)(MyComponent);
```
but it won't work neither
