### ISSUE TITLE
Create link react-router-redux?

### ISSUE THREAD

**Issue by rnYulianto** [ReactTraining/react-router#5052]
I use react, react-router, and redux, but I still dont understand how to create link. I try standard a tag but the page seems reload, so I try to put dispatch(push(location)) in my onClick handle function. My code looks like this:

`click = (event) => {
   event.preventDefault();
   this.props.dispatch(push('/a'));
}`

and my a component is:

`<a onClick={e=>this.click(e) >`

the action seems dispatched but the location didnt change. Am I wrong, or I miss something? thanks

**Comment by rnYulianto** [comment]
And using Link component from react-router-dom also didnt work

**Comment by timdorr** [comment]
You should just use the standard `<Link>` component. The location change will be synced to the store. If that's not working, I would look into what's gone wrong there. Have you got a ConnectedRouter at the top of the tree? What about using just a plain BrowserRouter?
