### ISSUE TITLE
Is it no longer possible to store a reference to the browser history outside of React?

### ISSUE THREAD

**Issue by evoyy** [ReactTraining/react-router#5055]
After upgrading to v4 it appears that storing a global reference to history does not work.

This worked pre-v4:

````javascript

    myApp.history = createBrowserHistory();

    <Router history={myApp.history}>
      //...
    </Router>

    const About = () => (
      <div>
        <button onClick={() => myApp.history.push('/')}>
            Return to Home
        </button>
      </div>
    )
````

but in v4 that does not seem to work. The address bar is updated but not the UI. It is only possible to trigger a UI update when the history is passed down as a prop within the React component hierarchy:

````javascript
    <Router history={createBrowserHistory()}>
      //...
    </Router>

    const About = ({ history }) => (
      <div>
        <button onClick={() => history.push('/')}>
            Return to Home
        </button>
      </div>
    )
````

Is my understanding correct or is this a bug?

**Comment by timdorr** [comment]
You can certainly create a history yourself and pass it to `<Router>`. That's all the other *Router components do.

**Comment by evoyy** [comment]
@timdorr I that case, I think this may be a bug. I have adapted the basic example from the documentation.

## Version

4.1.1

## Test Case

````javascript
// app.js

import React from 'react';  // 15.5.4
import ReactDOM from 'react-dom';  // 15.5.4
import createBrowserHistory from 'history/createBrowserHistory';
import { BrowserRouter as Router, Route, Link } from 'react-router-dom';  // 4.1.1

let myApp = { history: createBrowserHistory() };

const BasicExample = () => (
  <Router history={myApp.history}>
    <div>
      <ul>
        <li><Link to="/">Home</Link></li>
        <li><Link to="/about">About</Link></li>
        <li><Link to="/topics">Topics</Link></li>
      </ul>

      <hr/>

      <Route exact path="/" component={Home}/>
      <Route path="/about" component={About}/>
      <Route path="/topics" component={Topics}/>
    </div>
  </Router>
)

const Home = () => (
  <div>
    <h2>Home</h2>
  </div>
)

const About = () => (
  <div>
    <h2>About</h2>
  </div>
)

const Topics = () => (
  <div>
    <h2>Topics</h2>
    <button
        onClick={() => {
            console.log('Returning to Home...');
            myApp.history.push('/');
        }}
    >
        Return to Home
    </button>
  </div>
)

let appNode = document.getElementById('app');
ReactDOM.render(React.createElement(BasicExample), appNode);
````

## Steps to reproduce

Click on "Topics" link to render the Topics route component. Click on the button "Return to Home".

## Expected behaviour

The Home route should be rendered and the address bar should be updated to "/"

## Actual behaviour

The address bar is updated to "/" but the UI is not updated.

**Comment by pshrmn** [comment]
@evoyy You cannot pass your own history to a `<BrowserRouter>`

**Comment by evoyy** [comment]
@pshrmn Thanks for confirmation. I have been debugging this for hours. It doesn't seem that there is any mention of this caveat in the documentation.

**Comment by evoyy** [comment]
Codepen for future reference:

https://codepen.io/anon/pen/qmmXGr

**Comment by pshrmn** [comment]
The simplest approach to figuring out how React Router's components work would be to just look at React Router's source code. Finding the correct code can be slightly tricky if you are used to monorepos, but the actual code is very simple.

https://github.com/ReactTraining/react-router/blob/v4.1.1/packages/react-router-dom/modules/BrowserRouter.js

**Comment by evoyy** [comment]
Agree, that is nice and easy code to understand. I used to have a fear of React Router's source code. I am upgrading a large codebase to version 4 and having a few hiccups adjusting to the new paradigm, but I am beginning to like version 4. It makes more sense now.

**Comment by nojaf** [comment]
Not super happy about this decision here. I'm facing a scenario where I need to navigate from outside my React components (inside an AjaxInterceptor).

I had to create my custom router to expose the history along.

 ```js
import React from 'react'
import PropTypes from 'prop-types'
import createHistory from 'history/createBrowserHistory'
import { Router } from 'react-router'

export let myHistory;

export class BrowserRouter extends React.Component {
    static propTypes = {
        basename: PropTypes.string,
        forceRefresh: PropTypes.bool,
        getUserConfirmation: PropTypes.func,
        keyLength: PropTypes.number,
        children: PropTypes.node
    }

    constructor(props) {
        super(props);
        myHistory = createHistory(this.props);
    }



    render() {
        return <Router history={myHistory} children={this.props.children}/>
    }
}
```

Is there no better way of doing this?

**Comment by pshrmn** [comment]
@nojaf Please see Tim's comment above. You do not need to create a custom browser router. Just export the history object from its own module so you can import it anywhere.

**Comment by nojaf** [comment]
I'm afraid I'm not really seeing how to export the history object of the BrowserRouter.
Could you provide some sample code please?

**Comment by pshrmn** [comment]
https://codesandbox.io/s/owQ8Wrk3

**Comment by nojaf** [comment]
Ow I see, you are not using BrowserRouter at all. Thanks for the clarification.
