### ISSUE TITLE
Nested routes should have a way to pass props

### ISSUE THREAD

**Issue by tarjei** [ReactTraining/react-router#5056]
Hi, 

One usage pattern I find should be better handled in V4 is when you want to pass a set of props to a child route. F.x. if you want to show different views of a single parent object:

```js

class ParentContainer extends Component  {
   // is responsible for fetching the object ++. 
  render() {
     return <div><h1>{this.props.course.title}</h1>
      <route path={`${match.url}/start`} component={StartComponent} props={{course: this.props.course}}>
      <route path={`${match.url}/info`} component={InfoComponent} props={{course: this.props.course}}>
      <route path={`${match.url}/results`} component={ResultsComponent} props={{course: this.props.course}}>
    </div>
  }
}

<route path="/course/:id" component={ParentContainer}>

```

This is only possible using the render method at the moment but it would be cleaner with a prop to pass props to the child route.

**Comment by pshrmn** [comment]
This has been discussed before and the current implementation is intentional. You just need to use `render`.

**Comment by lunikernel** [comment]
@pshrmn would you mind explaining this in much greater detail please?  It's something that users such as myself really need to know when transitioning from version 3 but answers like this are so brief that I wouldn't even know where to start implementation the solution that you are suggesting.

What would that code look when you say "you just need to use render"?

thanks!

**Comment by tarjei** [comment]
@pshrmn 

You end up with something like this:

```
export default function renderWithExtraProps (component, extraProps) {
 const Component = component
  return function (props) {
      return <Component {...extraProps}/>
  }
}

...
<route component{renderWithExtraProps(MyPage, {someProps: somePropValue})} path="/foo"/>
```

**Comment by taurose** [comment]
You shouldn't do it like that, because you're creating a new component on every `<Route>` rerender, ie. every time `renderWithExtraProps` is called, which messes with the component lifecycle.

Instead, use `render` as was already mentioned:

`<Route render={routeProps => <MyComponent someProps={somePropsValue} {...routeProps} />} />`

Note that, if you don't like this API, you can easily wrap `<Route>`:

```js
const RouteWithProps = ({ component, props, ...extraProps }) => (
  <Route
    {...extraProps} 
    render={routeProps => <component {...props} {...routeProps} />} 
  />
);

// now you can do as originally suggested:
<RouteWithProps path={...} component={MyComponent} props={{someProps: somePropValue}} />
```

**Comment by ruifortes** [comment]
Is the reasoning behind this option documented?
