### ISSUE TITLE
v4 Fucking Sucks.

### ISSUE THREAD

**Issue by methodbox** [ReactTraining/react-router#5058]
A week ago pulling your router from npm produced a working app.

Now literally everything is deprecated and doesn't work.

You need to add react-router-dom as a dependency and an NPM note about breaking changes.

It fucked my app hard.

**Comment by 0m15** [comment]
completely agree, it seems that the unique reason they've rewritten and messed up everything has been made in order to offer their fantastic "react training". 
I'm going to abandon this library and look for something that works.

**Comment by bitcloud** [comment]
@methodbox If you are not not happy with what they are doing here, look for another library, make your own, fork the old version and maintain it yourself or do whatever fixes your problem. 
Ranting and not being constructive about something you even get for free is very lame!
It doesn't seem that you are part of any major OS project that you know how this works.

I have a great time with v4 and like it much better then the old one.

**Comment by 0m15** [comment]
it's frustrating when you've to rewrite a lot of code without knowing the reason.
js community should care more about stability and less about monetizing open source.

**Comment by timdorr** [comment]
Rename this to remove profanity. Since there isn't any good discussion to come out of this, I'm going to lock it. Feel free to discuss with/yell at me on Twitter.
