### ISSUE TITLE
How to assert tests on component instance wrapped with <MemoryRouter>?

### ISSUE THREAD

**Issue by evoyy** [ReactTraining/react-router#5059]
In v4 the recommended way to test Router-dependent components is to wrap them in a `<MemoryRouter>`. My test suite often needs a reference to the wrapped component in order to assert tests on it, for example to assert the existence of attached refs. It seems that when wrapped with `<MemoryRouter>` it is not possible to get a reference to the nested component.

Previously:

````javascript
    let component = ReactTestUtils.renderIntoDocument(<Sidebar/>);

    expect(component.foo).to.exist;  // ok
````

React Router v4:

````javascript
    let component = ReactTestUtils.renderIntoDocument(
      <MemoryRouter>
        <Sidebar/>
      </MemoryRouter>
    );

    expect(component.foo).to.exist;  // fail; component is MemoryRouter instance
````

I was unable to get a reference to the wrapped component by descending props.children:

````javascript
    console.log( component.props.children[0] );  // undefined
    console.log( JSON.stringify(component.props.children) );
        // '{"key":null,"ref":null,"props":{},"_owner":null,"_store":{}}'
````

Looking into the source of `<MemoryRouter>` and `<Router>` it seems that it may not be possible to get a reference to a wrapped component, since `<Router>` doesn't nest its children, and there is no tree to descend.

https://github.com/ReactTraining/react-router/blob/master/packages/react-router/modules/Router.js#L80

Stubbing out the routing context may be my only option. Is my understanding correct? Is there any other way to reference the wrapped component?

**Comment by timdorr** [comment]
This is more of a question for how you access child elements in a tree rendered by ReactTestUtils. We're not doing anything funky other than rendering a single child element. I'm not sure of the best way to do that in RTU, so maybe you might want something like Enzyme instead.

**Comment by pshrmn** [comment]
I think that [`findRenderedComponentWithType()`](https://facebook.github.io/react/docs/test-utils.html#findrenderedcomponentwithtype) would do the trick, but I also do not use `ReactTestUtils`.

**Comment by evoyy** [comment]
Enzyme wouldn't help in this case, since it can only read the state from root component, therefore same problem.

I realized the issue could be with the `@withRouter` higher order component and my understanding of how to access the wrapped component. I still can't work out how to access the wrapped component by descending the tree from a `<MemoryRouter>` root, if it is even possible - I'd love to know how. There are also other factors since I run my test suite in karma which makes debugging harder.

Eventually I decided to mock the router context when testing any components that use `@withRouter`.

I created this higher order component to stub the context:

````javascript
function stubRouterContext(Component) {

    return class extends React.Component {

        static childContextTypes = {
            router: PropTypes.object.isRequired,
        };

        // https://github.com/ReactTraining/react-router/blob/c5c40aab197e1f8d2de118fbad1e5ac9e18d1ea9/packages/react-router/modules/Router.js#L23
        getChildContext() {
            return {
                router: {
                    history: {
                        createHref: () => {},
                        push: () => {},
                        replace: () => {},
                    },
                    route: {
                        location: '/',
                        match: {
                            path: '/',
                            url: '/',
                            params: {},
                            isExact: true,
                        },
                    },
                },
            };
        }

        render() {
            return <Component ref={C => this.WrappedComponent = C} {...this.props} />;
        }
    };
}
````

It's possible to access a component wrapped with `@withRouter` using the WrappedComponent property. https://reacttraining.com/react-router/core/api/withRouter/ComponentWrappedComponent

This enables me to stub the router context in `<Sidebar>` like this:

````javascript
    let SidebarWithContext = stubRouterContext(Sidebar.WrappedComponent);
````

Then I can test my wrapped component like this:

````javascript
    let { WrappedComponent } = ReactTestUtils.renderIntoDocument(<SidebarWithContext/>);

    expect(WrappedComponent.foo).to.exist;  // ok
````

**Comment by indiesquidge** [comment]
> _This is more of a question for how you access child elements in a tree rendered by ReactTestUtils...I'm not sure of the best way to do that in RTU, so maybe you might want something like Enzyme instead._

@timdorr, I don't believe this is ReactTestUtils-specific, as I am having the same issue trying to access the wrapped component using Enzyme, and it looks like @evoyy was having the same trouble with Karma.

Here is what I get back when I try and see `<MemoryRouter>`'s 

```javascript
test('it puts the lotion in the basket', () => {
  const wrapper = mount(
    <MemoryRouter>
      <MyComponent />
    </MemoryRouter>
  )

  console.log(wrapper.props().children)
  /* output:
    { '$$typeof': Symbol(react.element),
      type: [Function: MyComponent],
      key: null,
      ref: null,
      props: {},
      _owner: null,
      _store: {}
    }
  */
})
```

This gives me access to the wrapped component's props, but I don't see any way to access the wrapped component's state, which is what I'm trying to make assertions on using Enzyme's [state getter](http://airbnb.io/enzyme/docs/api/ReactWrapper/state.html).

I posted a [SO question](https://stackoverflow.com/questions/44979735/how-does-one-access-state-on-a-component-wrapped-in-memoryrouter) about this same issue two weeks ago but unfortunately it hasn't received any possible solutions. I also posted the same question in the [reactiflux Discord app](https://discordapp.com/channels/102860784329052160/103538345837068288?jump=332989987207512064) the same day.

Just wondering if I'm missing something with how `<MemoryRouter>` is rendering its children on a full mount, and how I may get access to my wrapped component's state.

**Comment by evoyy** [comment]
@indiesquidge I think I came to the conclusion that it is not possible to access a component instance which is a child of `<MemoryRouter>`.  The only way is to not use MemoryRouter, but stub the routing context yourself for the component you want to test, using a higher order component that also stores a reference to the component as a property. I made a utility function to help with this:

````javascript
function wrapRender(Component, props) {

    // stub router context (for components using @withRouter or <Link>, etc
    let ComponentWithRouter = stubRouterContext(Component);

    let component = ReactTestUtils.renderIntoDocument(
        <ComponentWithRouter {...props} />
    );

    return component.WrappedComponent;
}
````

In a test:

````javascript
let component = wrapRender(Sidebar, {foo: bar});
expect(component.props.foo).to.equal("bar");
````

**Comment by dharanidhanapalan** [comment]
Hi,
Is there any other solution to get the instance of the <myComponent/> wrapped inside <MemoryRouter>?
Eg:
<MemoryRouter>
        <myComponent/>
<MemoryRouter/>

**Comment by indiesquidge** [comment]
If you have the privilege of being able to upgrade to Enzyme v3 (the upgrade path is relatively easy, I recommend it if you have the bandwidth), the new API contains instance methods that allow us to get at child component state.

[See here for more details and examples](https://stackoverflow.com/a/47318973/3893393).

**Comment by fjeansilva** [comment]
@indiesquidge I was stuck with this problem, but your tip salved me! Thanks Guy!

**Comment by Olegarius** [comment]
Thanks, Austin Wood.
It works for me:
`    const wrapper = mount(<MemoryRouter><myComponent /></MemoryRouter>).find(myComponent);
    const viewInstance = wrapper.instance();
`
