### ISSUE TITLE
Transitioning to V4- how to make props available to all routes?

### ISSUE THREAD

**Issue by lunikernel** [ReactTraining/react-router#5060]
*please add this to the migration guide*

In version 3 react-router I needed to ensure all components got an application object pushed down to them via props.  I did this by having a "createElement" function which was set as a prop on the router.

  createElement = (Component, props) => <Component {...this.props} application={application} />

<Router onUpdate={() => window.scrollTo(0, 0)} history={hashHistory} createElement={createElement}>

This no longer seems to work.

What is the correct way in version 4 react router to ensure all my routes get the application prop?

thanks

**Comment by timdorr** [comment]
Use the `render` prop on `Route` instead of `component`. It gives you this kind of control over creating instantiating your components.
