### ISSUE TITLE
Fill router reducer with initial data

### ISSUE THREAD

**Issue by DimitryDushkin** [ReactTraining/react-router#5061]
1. It will be nice to fill up `router` state with corresponding initial data (default value).
2. (again) Initial `LOCATION_CHANGE` action is still misleading and should be removed: 
    1. Location is actually not changing on page refresh for example
    2. Also if you opening some link from address bar location is not changing from `about: blank` by default (it should be configured), so location is not actually changing.
   3. History API does not fire such event on loading

**Comment by timdorr** [comment]
Please don't open duplicate issues. #5038

**Comment by DimitryDushkin** [comment]
@timdorr I've added one more proposal (didn't present in duplicate) and you didn't answered to my arguments in prior issue, so I've added them to this related issue.

**Comment by DimitryDushkin** [comment]
Anyway what's the point in closing issues without discussion and agreement?

**Comment by timdorr** [comment]
Because it's an alpha. Things will change and we haven't even figured out the basics, such as time travel. Give it time to solidify before going after the base semantics. The structure is going to change drastically very soon (once #4717 or something like it lands).

**Comment by DimitryDushkin** [comment]
Oh, I see. Thank you.
