### ISSUE TITLE
How to redirect url in redux actions after an api request was finished?

### ISSUE THREAD

**Issue by mrold** [ReactTraining/react-router#5062]
I think this version is unfriendly to redux .
In the process of upgrading to this version, I have encountered many problems.

### This is what I like:
*anywhere*
```
history.push('url')

```
#### AND
one place `routes.js` defined all the routes

### 我认为一个工具不断的改进是为了更简单、易用，而不是为了装逼。

**Comment by DimitryDushkin** [comment]
I think `react-redux-router` will help you.
