### ISSUE TITLE
Detect route change in router

### ISSUE THREAD

**Issue by vedran-milic** [ReactTraining/react-router#5064]
How to detect route change in v4? I have main menu which contains navlinks, and when i click it changes route without closing the menu. When I put onClick event (that closes the menu) on navlinks, router reloads page. So i need global trigger, whenever route changes, fire menu close action.

**Comment by pshrmn** [comment]
An `onClick` event should not cause a full page reload unless you are calling `event.preventDefault()` inside of it.

```js
class Menu extends React.Component {

  closeMenu = (event) => {
    // Do not call event.preventDefault() in here
    this.setState({ open: false })
  }

  render() {
    return (
      <...>
        <NavLink onClick={this.closeMenu} ... />
      </...>
    )
  }
}
```

If you aren't doing that and still experiencing issues, you can try stepping through the `<Link>`'s [`handleClick`](https://github.com/ReactTraining/react-router/blob/v4.1.1/packages/react-router-dom/modules/Link.js#L35) method to see why `history.push` is not being called.

**Comment by vedran-milic** [comment]
Thanks

**Comment by MaralS** [comment]
@pshrmn this trick don't slow down the application ? I have this impression on the development mode.
