### ISSUE TITLE
Is there documentation on reason behinds the design decision from v3 to v4?

### ISSUE THREAD

**Issue by zsxking** [ReactTraining/react-router#5067]
I just learnt about how big the change of v4 is, but I was not able to find the documentation about why the change, or what make v4 better than v3. I come across this post when searching https://news.ycombinator.com/item?id=12511419, but the link is no longer valid. Is it moved to somewhere?

I would really want to learn about the reason behind v4 so that I can properly value if it worth the effort to migrate from v3. It would be really appreciated if the doc is linked in the migration guide.

**Comment by pshrmn** [comment]
I believe that that link just leads to the old README. You can see that here https://github.com/ReactTraining/react-router/tree/v4.0.0-beta.8#v4-faq
