### ISSUE TITLE
Problem with Installing /website/package.json - jsxstyle

### ISSUE THREAD

**Issue by wallyfaye** [ReactTraining/react-router#5069]
## Version
4.0.0

## Test Case
install /website/package.json on a basic Docker Node instance https://hub.docker.com/_/node/

## Steps to reproduce
install /website/package.json on a basic Docker Node instance, the install fails at jsxstyle due to a problem with node-gyp. 

To fix, I ran `npm install node-gyp-install -g && ./node_modules/node-gyp-install/bin.js` and then ran `npm install` again and had no problem

I used this page to help solve the problem: https://github.com/bevacqua/perfschool/issues/5

## Expected Behavior
I didn't expect to have to do the extra command

## Actual Behavior
having to run the extra command

**Comment by timdorr** [comment]
This doesn't have anything to do with this library.

**Comment by wallyfaye** [comment]
got it, sorry for opening the issue. 

not sure it it'd maybe helpful to hint somewhere that jsxstyle is going to need node-gyp-install to work for the examples?

thanks anyway

**Comment by timdorr** [comment]
The website isn't something we expect people are going to install. It's marked as private and isn't published on NPM.
