### ISSUE TITLE
PropTypes are not working with the UMD build

### ISSUE THREAD

**Issue by pgn-vole** [ReactTraining/react-router#5070]
## Version
4.1.1

## Test Case
https://codepen.io/anon/pen/gWGbap?editors=1111

## Steps to reproduce

Use the UMD build. Because prop-types is merged within the standalone bundle all the property validation logic is stripped out.

## Expected Behavior

One should get warning when misusing the components.

## Actual Behavior

No warning are logged and a wrong usage (like in the example) results in react-router crashing silently.

**Comment by timdorr** [comment]
[We specifically strip out PropTypes for any build](https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/modules/.babelrc#L11), so this is expected. The UMD builds are built in Production mode, so they won't have validation logic anyways.
