### ISSUE TITLE
router.isActive to validate trailing params 

### ISSUE THREAD

**Issue by Goldy1131** [ReactTraining/react-router#5073]
I'm trying to check routes with Router.isActive

If the current route is /animals/edit

`(router.isActive('/animals/edit')
`
is true.

But if the current route is /animals/edit/23

`(router.isActive('/animals/edit/') 
`
is false.

How can I make a route that encompasses trailing params?

eg. /animals/edit/1, /animals/edit/0201, animals/edit/1212 should all be true if the router has animals/edit/ in it.

**Comment by timdorr** [comment]
`isActive` only works on the exact pathname, including parameters. You should check routes in some other way, most likely.
