### ISSUE TITLE
Bugs in code-splitting example in react-router-dom/docs

### ISSUE THREAD

**Issue by estaub** [ReactTraining/react-router#5074]
Re packages/react-router-dom/docs/guides/code-splitting.md

1.) The render() method blows up with createElement getting a null type when entered before loading is complete.  This is a repeat of https://github.com/ReactTraining/react-router/issues/4998, which was blown off.

Change
```javascript
render() {
    return this.props.children(this.state.mod)
  }
```
to

 ```javascript
render() {
    return this.state.mod ? this.props.children(this.state.mod) : null
  }
```

2.) The bundle shims drop the RouteComponentProps (match, location, history) that often are needed by the routed-to component.  This should be noted, with an example that passes them through, e.g. change

```javascript
const Dashboard = () => (
  <Bundle load={loadDashboard}>
    {(Dashboard) => <Dashboard/>}
  </Bundle>
)
```
to

```javascript
const Dashboard = (props) => (
  <Bundle load={loadDashboard}>
    {(Dashboard) => <Dashboard {...props}/>}
  </Bundle>
)
```

3.) The code also assumes that the routed-to component is the default export of the split module.  It would be good to say that somewhere, or still better, show an example where it isn't.

**Comment by timdorr** [comment]
Could you package this up as a PR? That will let us discuss the specific changes more directly. Thanks!

**Comment by estaub** [comment]
Sorry, no, too stretched!

**Comment by timdorr** [comment]
Just go here and click the Edit icon in the top right corner of the file: https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/docs/guides/code-splitting.md
