### ISSUE TITLE
Bundle size is bigger than necessary due to ES6 imports

### ISSUE THREAD

**Issue by ruiaraujo** [ReactTraining/react-router#5079]
I am using react-router-dom and webpack 2 and it seems the tree shaking does not work well enough to remove unused modules.

I managed to fix it locally by changing the import style from

```
import { Router } from 'react-router' 
```
to

```
import Router from 'react-router/Router' 
```
everywhere.

## Version
4.0.0

Is this something that would be interesting to do a PR on?

**Comment by pshrmn** [comment]
I don't know enough about tree shaking to give any real input on this, but I will mention that this is related to #4432.

**Comment by ruiaraujo** [comment]
The ES build with webpack 2.3 does not solve the issue. Only changing all the imports improved the situation since any import to react-router will bring in all the modules.

**Comment by timdorr** [comment]
Are you sure you're using the ES build? [It leaves import/exports untouched](https://unpkg.com/react-router-dom@4.1.1/es/index.js), so Webpack should be able to tree-shake it. 

I'm thinking this is either some misconfiguration of webpack or babel.

**Comment by ruiaraujo** [comment]
Yes I am sure, see the attached image. The StaticRouter, Prompt and createMemoryHistory should be removed they stay there.

When I check the reason using the webpack stats analyser, the reason for those files being included is the index file of react-router.

<img width="768" alt="stats analyser" src="https://cloud.githubusercontent.com/assets/303833/25778575/4c04b360-3302-11e7-89a4-44b5e7731a50.png">

**Comment by ruiaraujo** [comment]
These issues might be relevant.

https://github.com/webpack/webpack/issues/4080
https://github.com/mishoo/UglifyJS2/issues/1261

Also the image above was with using a babel plugin ([babel-plugin-transform-imports](https://www.npmjs.com/package/babel-plugin-transform-imports)) to do direct import otherwise the bundle looks like this. Nothing gets removed.
<img width="561" alt="no transform imports" src="https://cloud.githubusercontent.com/assets/303833/25778699/3af0a85a-3306-11e7-9893-0d59112f50c5.png">

**Comment by timdorr** [comment]
But are you sure it's using the es build that's included in the npm package? That's the key thing. What if you alias react-router to react-router/es?

**Comment by ruiaraujo** [comment]
I am sure (notice the 'es' folder above in the screenshots) and have tried the alias with the same result. 

So I am pretty sure that the build is pointing to the ES build. 

My question is whether a PR would be accepted with a change to fix this problem.

**Comment by timdorr** [comment]
Sure, but what would be the appropriate change? AFAIK, we're doing the same thing on Redux and it works fine there.

**Comment by ruiaraujo** [comment]
The change would the react router dom export refer to direct import instead of importing the top level of react-router.

I have tried this locally and it did fixed it.

**Comment by chrisdl** [comment]
Would fixing this issue solve this you think? @ruiaraujo.

I've recently upgraded to webpack 3 and am trying to optimize my bundle with the new `webpack.optimize.ModuleConcatenationPlugin()`.

```
# In my build command.
[35] ../node_modules/react-router-dom/es/index.js + 23 modules 41.6 kB {0} [built]
       ModuleConcatenation (inner): module is used with non-harmony imports from ...[list of my components importing { STUFF } from 'react-router'dom']
```

**Comment by ruiaraujo** [comment]
@chrisdl That is odd. You can try that branch in your local branch and report back.

**Comment by chrisdl** [comment]
@ruiaraujo im actually having some issues installing the PR locally. Is there a better way than using to your knowledge?

```
yarn add ReactTraining/react-router#5095/head
```

**Comment by comerc** [comment]
Do you know about babel-plugin-import?
