### ISSUE TITLE
More Native Components

### ISSUE THREAD

**Issue by mehcode** [ReactTraining/react-router#5083]
What's the direction that react-router wants to go with regards to deeper react-native integration and support?

Eg.. Do we want to provide:

**Stacks**

```jsx
<Stack>
  <Route exact path="/" component={List} />
  <Route exact path="/:id" component={Detail} />
</Stack>
```

**Animated**

```jsx
<Animated.Stack>
  <Route exact path="/" component={List} />
  <Route exact path="/:id" component={Detail} />
</Animated.Stack>
```

```jsx
<Animated.Switch>
  <Route exact path="/" component={List} />
  <Route exact path="/:id" component={Detail} />
</Animated.Switch>
```

I have a `Stack` component that's working nicely for me and I guess I'm asking if I should go the direction of a PR here or write a lib that works on top of react-router?

**Comment by timdorr** [comment]
Feel free to submit a PR. I think we'd be open to more native components. Just make sure it has good tests along with it.
