### ISSUE TITLE
react-router-redux for react-native (NativeRouter)

### ISSUE THREAD

**Issue by alvelig** [ReactTraining/react-router#5084]
Hi guys! Thank you for the great and very-very reasonable v4. 
The only thing to mention is that I'm lacking support for react-router-redux in react-native.
I'm ready to make a PR with the feature, as I see that this means to reimplement `<MemoryRouter>` just replacing `<Router>` with `<ConnectedRouter>` and wrap it with `<ConnectedNativeRouter>`.

Am I right? If no, then give me a key of where I'm mistaken, if yes just tell me go on and I'll help with this part.

**Comment by Kevenvz** [comment]
Hey,

I haven't tested this yet but I think you can already do this. You need to give the `<ConnectedRouter>` an in memory `history` object. (`history/createMemoryHistory`) See usage from the `history` package: https://github.com/ReactTraining/history#usage

**Comment by timdorr** [comment]
Right now native integration is lacking. But we're going to work on it. (I have a major product release at the end of the month, so I'm blocked on that until next month)

**Comment by cauldyclark15** [comment]
First thanks to this awesome library, but may I ask, is this issue resolved already?

**Comment by prohorov1981** [comment]
Hey man 

Did you integrated react native and react-router-redux?
When set 'history/createMemoryHistory' routerMiddleware, I have got message "cannot read property apply of undefined"
