### ISSUE TITLE
Warning about Hash history can not push to stack

### ISSUE THREAD

**Issue by iamashraful** [ReactTraining/react-router#5088]
Suppose from home I click home again then it shows the warning. 
`Warning: Hash history cannot PUSH the same path; a new entry will not be added to the history stack`

Anyhow it should handle. Thanks

**Comment by timdorr** [comment]
This is something for the history library.

**Comment by iamashraful** [comment]
I didn't use any history library. Did react used? If yes?then, why react router is not syncing react libraries? If no? then, where come from history library?

**Comment by timdorr** [comment]
React Router uses the `history` library under the hood. That error comes from that library: https://github.com/ReactTraining/history
