### ISSUE TITLE
[Docs] `children=` vs `render=`

### ISSUE THREAD

**Issue by halt-hammerzeit** [ReactTraining/react-router#5091]
In this example `children=` is used.
https://reacttraining.com/react-router/web/example/custom-link

And in the example before that one `render=` is used.

You should put an explanation there why would that example use `children=` instead of `render=`.

**Comment by halt-hammerzeit** [comment]
Moreover, `<Route/>` name is wrong and misleading.
It should be something like `<Match/>` or `<Location/>`.

**Comment by timdorr** [comment]
There is already documentation for this on the Route: https://reacttraining.com/react-router/web/api/Route/Route-render-methods
