### ISSUE TITLE
Match object in the store using react-router-redux

### ISSUE THREAD

**Issue by aszwemin** [ReactTraining/react-router#5096]
react-router-dom puts `match` in props among other things, but this is not part of the `router` redux binding. Would be great to include `match` as well as otherwise you need to rely on props rather than the store or you need to be parsing the pathname manually.

**Comment by timdorr** [comment]
There can be multiple matches, depending on how your component tree looks. It's the same reason we can't put the route in there, because the can be multiple matched routes in the tree.

**Comment by davbeck** [comment]
The solution I came up with for this is to use [`matchPath`](https://reacttraining.com/react-router/web/api/matchPath) to get at url params.

```js
import { matchPath } from 'react-router';
/// ...
       const { payload: { pathname } } = action;
      const match = matchPath(pathname, {
        path: '/groups/:id',
      });

      return {
        ...state,
        activeGroupId: match ? match.params.id : null,
      };
```
