### ISSUE TITLE
<Link to="/foo">click me</Link> not dispatch on Redux (@@router/LOCATION_CHANGE)

### ISSUE THREAD

**Issue by netojose** [ReactTraining/react-router#5097]
When I navigate via browser history buttons, the `@@router/LOCATION_CHANGE` is dispatched, but when I click on router link (`<Link to="/foo">click me</Link>`), the redux not is notified.

## Version
4.0.0

## Test Case
Sorry, I have no put to run with redux integration, but maybe a simple usage, [like this](https://github.com/ReactTraining/react-router/tree/master/packages/react-router-redux) with redux installed

## Steps to reproduce
Just have a basic app with react + redux + react-router + react-router-redux and try navigate via `<Link to="/foo">click me</Link>`

## Expected Behavior
`@@router/LOCATION_CHANGE` should be triggered on redux state stack 

## Actual Behavior
The navigation works, but the redux don't detect the state change

**Comment by timdorr** [comment]
Do you have another Router component in the tree somewhere? This definitely works, so it's likely just a usage error.

**Comment by netojose** [comment]
Nope, is a simples implementation. I will create a clean app to test

**Comment by kajm** [comment]
@netojose did you solve the problem? I am having the same issue

**Comment by netojose** [comment]
Nope @kajm , I not solved the problem.
My solution: I not made the [react-router-redux](https://github.com/ReactTraining/react-router/tree/master/packages/react-router-redux) integration :(

**Comment by Iuriy-Budnikov** [comment]
+1

**Comment by BeOleg** [comment]
I had a similar issue when moving from the same state to the same state only with query param change
