### ISSUE TITLE
Route documentation encourages bad coding practises

### ISSUE THREAD

**Issue by vdh** [ReactTraining/react-router#5101]
1. Re-declaring functions on every render

[`Route`](https://reacttraining.com/react-router/web/api/Route) has a lot of examples that go against the `eslint-plugin-react` rule, [`jsx-no-bind`](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-no-bind.md).

It's a no-nonsense rule. Any function declared inside JSX will inevitably cause more garbage collection than one declared outside the JSX as a constant.

There's also a lot of irritating [`no-use-before-define`](http://eslint.org/docs/rules/no-use-before-define) violations in the examples, for no particularly good reason…?

2. Confusing duplication of functionality 

Also, there's three props that do *almost* the exactly same thing: `component`, `render`, and `children`.
```js
class Stateful extends React.Component {
  /* something stateful… */
  render() { return <div />; }
};
const Stateless = () => <div />;
const SomeParent = () => (
  <div>
    <Route path="/one" component={Stateful} /> {/* renders a component… */}
    <Route path="/two" component={Stateless} /> {/* also renders a component… */}
    <Route path="/three" render={Stateless} /> {/* works, just doesn't render a real component */}
    <Route path="/four" children={Stateless} /> {/* doesn't exactly say what it does with the func…? */}
  
    {/* Not documented, but implied by the use of the `children` prop…? */}
    <Route path="/five">{Stateless}</Route>
  </div>
);
```
So `Route` has three props that all accept varying types of components, but only *one* of them (`component`) is designed to accept components with state…? What is going to happen if someone tries to use a component (with or without state) with `Route` in the normal React syntax?
```jsx
<Route path="/six"><Stateless /></Route>
<Route path="/seven"><Stateful /></Route>
```

I can sort of see the reasoning behind `render`, but `component` and `children` are way too confusing.

**Comment by timdorr** [comment]
1. Is actually OK in most cases. Yes, you should avoid anonymous functions normally. However, in the case of Routes, they tend to live high up in the tree and don't generally get re-rendered ever. There are plenty of exceptions to this, but the traditional reason against anonymous functions doesn't apply in general practical usage.

2. There are very specific reasons for having each one of those props. See the documentation for explanations: https://reacttraining.com/react-router/web/api/Route/Route-render-methods
