### ISSUE TITLE
Feature request: make Route render-on-match behaviour depend on a new property

### ISSUE THREAD

**Issue by Satyam** [ReactTraining/react-router#5106]
Sometimes it is far more convenient, even if only for some stylistic reason, to have code conditional to the Route as children of the `<Route>` component than a reference in the `component` property.  However, children are rendered unconditionally while components are rendered on match.

May I suggest to make this behaviour dependent on a `renderOnMatch` property (or something to that effect) which, to keep it backwards compatible, would default to `true` for `<Route component>` and `<Route render>` and `false` for `<Route children>`.

Thus, these two would behave the same:
```js
<Route exact path="/" component={Home}/>

<Route exact path="/" renderOnMatch>
   <Home />
</Route>
```

This would allow, for example, to pass the child some extra properties besides those provided by Route itself, without being forced to wrap said component in another one just to add that prop.

**Comment by timdorr** [comment]
Sorry, but we're not going to do this. This makes the API more complex and you can do the same thing with [`render`](https://reacttraining.com/react-router/core/api/Route/render-func)
