### ISSUE TITLE
[v4] BrowserRouter can't use history basename

### ISSUE THREAD

**Issue by eloytoro** [ReactTraining/react-router#5110]
### User story

I'm trying to create a site that uses a dynamic basename for language purposes, if the user selects spanish as a language the basename should be `/es-es` for any route of the site.

### Ideal API

Ideally creating a browser history with the basename prop should take care of things

```jsx
const history = createBrowserHistory({ basename: currentLanguage });

<BrowserRouter history={history} />
```

### Curent behaviour

* The basename is ignored when matching routes, so none of the routes match
* Pushing URLs to the history object directly bugs out the URL

### The issue

* The history object does not store the basename prop passed to it, so its impossible for the BrowserRouter to access it
* The BrowserRouter has no logic for dealing with a basename even if the history were to expose it

### The solution

* Allow history to expose the basename parameter
* Take in consideration the history's basename when matching routes in the browser

**Comment by Aprillion** [comment]
I just wanted to report the leg shooter that `BrowserRouter` silently ignores the `history` prop.

Would it be possible to throw an exception instead of silently ignoring unsupported props?

**Comment by Aprillion** [comment]
@eloytoro use `<Router history={history}>` instead of BrowserRouter...

**Comment by eloytoro** [comment]
Closing this as `<BrowserRouter />` doesnt support the history prop (as stated in the docs)
Using `<Router />` with a `history` prop or `<BrowserRouter />` with a `basename` prop solves this

**Comment by siddiq-rehman** [comment]
Hi,

I had the same issue, resolved by giving historyApiFallback to true in webpack, which load index.html and loads the route. Perfectly working for my requirement.
