### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by waleedarshad** [ReactTraining/react-router#5115]
These are my routes

When i use without index routes it work fine but when i use index routes routes i get error of maximum call stack. why?

	<Router history={history}>
		<Route path="/" component={Home}>
			<IndexRedirect to="/" /> // Causing error

			<Route path="about" component={About} />
			<Route path="signup" component={SignUp} />
			<Route path="*" component={NotFound} />
		</Route>
		
	</Router>

        		<Router history={history}>
                             <Route path="/" component={Home}>
                                  <Route path="about" component={About} />
                                  <Route path="signup" component={SignUp}/>
                                   <Route path="*" component={NotFound} />
                             </Route>
                        </Router>

 react-router version : ^2.8.1

**Comment by pshrmn** [comment]
An `<IndexRedirect>` matches the location `/` and your `<IndexRedirect>` redirects to `/`. This means that your `<IndexRedirect>` is redirecting to itself. You can read more about `<IndexRedirect>`s in the [documentation](https://github.com/ReactTraining/react-router/blob/v3/docs/guides/IndexRoutes.md#index-redirects)

**Comment by waleedarshad** [comment]
Ok thanks

**Comment by jasmo2** [comment]
Hi I have the same issue but with react-router-dom::4.1.1.
```
import React, { PureComponent } from 'react';
import {
    BrowserRouter as Router,
    Route,
} from 'react-router-dom';

import Polls from '../containers/pollsContainer';

class AppRouter extends PureComponent {
    render() {
        return (
            <Router >
                <Route path="/" component={Polls} />
            </Router>
        );
    }
}

export default AppRouter;

```

```
// Simple example of a React "smart" component
import React, { Component } from 'react';
import { connect } from 'react-redux';

import Polls from '../containers/pollsContainer';
import { getPolls } from '../actions';

// Which part of the Redux global state does our component want to receive as props?
const mapStateToProps = (state) => {
    const { polls } = state;
    return { polls };
};

const mapDispatchToProps = { getPolls };

class PollsContainer extends Component {
    componentWillMount() {
        this.props.getPolls();
        console.info('PollsContainer willMount');
    }

    render() {
        const { polls } = this.props;
        return <Polls polls={polls} />;
    }
}

export default connect(mapStateToProps, mapDispatchToProps)(PollsContainer);

```
