### ISSUE TITLE
v2.8.2, without React deprecation warnings?

### ISSUE THREAD

**Issue by obogobo** [ReactTraining/react-router#5121]
## Version
2.8.1

Hi there! We maintain a yeoman generator at work, with many users and production apps still using React Router v2.8.1. Recently, in React 15.5.0 - it seems as if React.createClass and React.PropTypes have been moved, and deprecation warnings added for React 16.

https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html

I know this is probably the very least of your priorities, but we'd greatly appreciate a patch release of React Router with changes to `RouterContext.js` as described in the migration guide provided by Facebook 😄 

There's a drop-in shim for React.createClass, and the propTypes change is a simple pass through with `sed`

Our developers would greatly appreciate these warnings suppressed during development - since 15.5.0 is likely of the last v15 React releases and we'd be able to shrink-wrap the generator and move to v16 with React Router @4 in the future.

Until then, thanks either way!

**Comment by timdorr** [comment]
You can use 3.0.5 safely with 2.x code. 3.0 is just 2.0 with the deprecation warnings (ours, not React's) removed. And 3.0.5 fixes for all the createClass and PropTypes deprecations.

**Comment by timdorr** [comment]
Also, there is a 15.6 planned that should ease things a bit: https://github.com/facebook/react/issues/9398
