### ISSUE TITLE
Push is using old state reference when using connect from react-redux

### ISSUE THREAD

**Issue by glundgren93** [ReactTraining/react-router#5123]
## Version
4.1.1

## Steps to reproduce

I have a modal that contains a button that dispatches the following async action:

```
export const searchNewConverters = () => {
  
  const url = `/api/Converters/SearchNewConverters`;

    return (dispatch, getState) => {
      dispatch(actions.closeModal());
      dispatch(actions.requesting());

      axios
        .get(url)
        .then(({ data }) => {
          dispatch(actions.searchNewConverters(data));
        })
        .then(() => {
          dispatch(actions.completed());
          dispatch(push("/converterList"));
        })
        .catch(error => {
          dispatch(globalActions.completed());
          console.log(error);
        });
    };
};

```

###  When using connect from react-redux in my component:

When I dispatch actions.searchNewConverters(), the newConverters Array inside my converter object in state is updated to this:

![image](https://cloud.githubusercontent.com/assets/3113318/26109150/f98e87da-3a24-11e7-9bdb-2e281e1e6075.png)

However, as soon as I dispatch push("/converterList"), the newConverters Array inside my converter object in state is updated to this:

![image](https://cloud.githubusercontent.com/assets/3113318/26109233/402b9a48-3a25-11e7-9c71-43feb8c5b65f.png)

###  When not using connect from react-redux in my component:

The push action does not update the newConverters Array.

![image](https://cloud.githubusercontent.com/assets/3113318/26109363/c101b666-3a25-11e7-84b6-be542d1045a9.png)

Am I missing something? Or is this unexpected behavior?

**Comment by timdorr** [comment]
Nothing in react-router-redux touches those other state properties. In fact, when used inside `combineReducers` it doesn't even have access to them.

My only guess is something else is going on with your `connect` argument functions. But that would have nothing to do with the router.
