### ISSUE TITLE
Where can active development on `react-router-redux` v5 be found and followed?

### ISSUE THREAD

**Issue by jvivs** [ReactTraining/react-router#5124]
## Version
`react-router-redux@v5.0.0-alpha6`

## Test Case
N/A

## Steps to reproduce
N/A

## Expected Behavior
N/A

## Actual Behavior
N/A

I was hoping to follow along with active development to get an idea about how the integration with the `react-router` v4 API is proceeding.

I've noticed active development of `react-router-redux` has been relocated here from the [reactjs](https://github.com/reactjs/react-router-redux) org. I've found `v5.0.0-alpha.6` on npm but I don't see any v5 tags in this repo. Are the prerelease tags being cut directly from master? If not, is there a different branch where I could follow along with active development?

Thanks for building and maintaining such a great set of packages for react apps. Looking forward to where things are going!

**Comment by timdorr** [comment]
We don't tag releases for react-router-redux because it's ahead of everything right now. All the code changes are happening on master. I haven't done anything with it in a while, but plan to return to it next month at some point.

**Comment by jvivs** [comment]
@timdorr thanks! I'll keep an eye out there.
