### ISSUE TITLE
Unable to type a URL with multiple "directories" and "navigate"

### ISSUE THREAD

**Issue by garyivy** [ReactTraining/react-router#5125]
## Version
4.1.1

## Test Case
Running on Chrome and web-pack-dev.
Can load to github if this would be helpful

## Steps to reproduce
Used snippet from https://reacttraining.com/react-router/web/example/basic.
Home page loaded
Clicked "Topics" Link
Clicked "Rendering with React" Link
Content Changes and url in address bar shows http://localhost:3000/topics/rendering
Cutting and Repasting that link into the address bar

## Expected Behavior
Shows the "Rendering with React" component

## Actual Behavior
fails (sends a server request).
I suspect it is a issue with a secondary directory since it works when I try http://localhost:3000/topics

**Comment by timdorr** [comment]
You need to configure your server to support this: https://github.com/ReactTraining/react-router/blob/v3/docs/guides/Histories.md#configuring-your-server

**Comment by garyivy** [comment]
Thanks Tim!

I was thinking that React caught the url navigation before it was sent to
the server.

I am using web-pack-dev-server so I'll need to check how it can always
return index.html on these routes.
