### ISSUE TITLE
Missing propTypes for props passed from withRouter

### ISSUE THREAD

**Issue by D-Buettner** [ReactTraining/react-router#5129]
Using the props passed from the withRouter HOC causes linting errors when using the `react/forbid-prop-types` rule from eslint-plugin-react. The `object` propType that is used in the withRouter docs violates this rule. This rule is used in the airbnb style guide, along with the mandatory declaration of propTypes, so I imagine that this is a pretty common problem.

I noticed that the propTypes for things like `history`, `location`, etc used to be exposed in the past, are there any plans to do this again?

**Comment by timdorr** [comment]
We don't plan to export the PropTypes like before, as they bloat the build quite significantly (it's really easy to end up shipping the whole `prop-types` library in production, unfortunately). We still recommend using `PropTypes.object` as a catch-all, even if it breaks on your particular eslint config.

I'd either disable that rule entirely, or at least disable it on a per-file/line basis in your code. I know it's not a great "solution", but we feel the alternative of easily accidentally shipping extra bytes is a greater problem.
