### ISSUE TITLE
react-router-config missing UMD build

### ISSUE THREAD

**Issue by michaelBenin** [ReactTraining/react-router#5130]
Hello,

Trying to open an issue with a repro case for this library.

From the readme:
`<script src="https://unpkg.com/react-router-config/umd/react-router-config.min.js"></script>`

This file is not published.

**Comment by michaelBenin** [comment]
Tried with another service, not available: https://wzrd.in/standalone/react-router-config@latest

Will make a sample github repo for the repro.

**Comment by timdorr** [comment]
Well, this is more of a packaging issue than a problem with unpkg.com. I'll check what's up with the build.

**Comment by michaelBenin** [comment]
Thank you!

**Comment by pshrmn** [comment]
It looks like the `package.json`'s `files` array just needs to have `es` and `umd` added to it.
