### ISSUE TITLE
Switch documentation missing `location` props

### ISSUE THREAD

**Issue by zhirzh** [ReactTraining/react-router#5135]
The source for [`<Switch />`](https://github.com/ReactTraining/react-router/blob/cc7cad4c228db773f2066879ad56dc55da3fc4ea/packages/react-router/modules/Switch.js#L18) has a `location` prop that is being used for matching the nested routes.

But this prop is missing from the [docs](https://github.com/ReactTraining/react-router/blob/cc7cad4c228db773f2066879ad56dc55da3fc4ea/packages/react-router/docs/api/Switch.md).

However, it is used in the example [modal gallery](https://reacttraining.com/react-router/web/example/modal-gallery).

**Comment by taurose** [comment]
Same for `<Route>` and `<NavLink>`.

**Comment by timdorr** [comment]
A PR to add this would be great!
