### ISSUE TITLE
`exact` match behavior

### ISSUE THREAD

**Issue by aesopwolf** [ReactTraining/react-router#5143]
## Feature request: a more 'exact' version of 'exact'

**Expected behavior:**

Given:

```jsx
<NavLink
  exact
  activeClassName="active"
  to={{
    pathname: '/blog',
    search: `?category=stuff`,
  }}
>
```

Then I would expect the url `example.com/blog?category=stuff` to have an `activeClassName` but the url `example.com/blog?category=things` to NOT have an `activeClassName`.

**Current behavior**

Regardless of the query params the active class name is attached as long as the pathname matches.

**Proposed Solution**

Expose new options on the `exact` prop. Some examples:

```jsx
exact // default - matches just the pathname
exact=["pathname"] // same as above, but explicit
exact=["search"] // only match against location.search
exact=["search", "pathname"] // matches against both location.search and location.pathname
exact="href" // same as above, "but shorthand"
```

**Comment by timdorr** [comment]
This is a limitation of path-to-regexp:

> Please note: The RegExp returned by path-to-regexp is intended for use with pathnames or hostnames. It can not handle the query strings or fragments of a URL.

Not really anything we can do that about. Since we don't process query strings, we can't trust `search`, since a lot of other things might match (`foo?bar=baz&fizz=buzz` is the same as `foo?fizz=buzz&bar=baz`, even if they aren't a string match).

**Comment by pshrmn** [comment]
You can use the [`isActive`](https://reacttraining.com/react-router/web/api/NavLink/isActive-func) prop to do more advanced active matching. It is a bit more involved, but it would work. Essentially you would write a factory function that takes a `search` string and only returns `true` when the location's `search` matches it.

```js
function matchSearch(search) {
  return function(match, location) {
    return location.search === search
  }
}

<NavLink
  exact
  activeClassName='active'
  to={{
    pathname: '/blog',
    search: '?category=stuff'
  }}
  isActive={matchSearch('?category=stuff')}
>
```

**Comment by aesopwolf** [comment]
Got it, thanks for the detailed responses. Looks like `isActive` it is.
