### ISSUE TITLE
Basename property is missing

### ISSUE THREAD

**Issue by Vanuan** [ReactTraining/react-router#5144]
## Version
4.1.1

## Test Case
https://codesandbox.io/s/QWgJONOmq

## Steps to reproduce
Use history with basename and ConnectedComponent

## Expected Behavior

Routed components have basename property in location

## Actual Behavior

There's no way to specify, thus I can't generate links. My use case is to generate links for authentication callback: `https://sso/auth?callback=/basename/callback`. Looks like I have to hardcode it somewhere globally.

**Comment by timdorr** [comment]
You need to pass the basename to the Router as well: https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/docs/api/BrowserRouter.md#basename-string

**Comment by Vanuan** [comment]
@timdorr 
That didn't work: https://codesandbox.io/s/QWgJONOmq

**Comment by Vanuan** [comment]
@timdorr Could you provide an example where this actually works? I've tested `ConnectedRouter`, `Router`, `BrowserRouter`, none of them seems to be passing basename.

**Comment by Vanuan** [comment]
How is this supposed to work?
The only properties that are passed to Router is history and children.

https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/modules/BrowserRouter.js#L21

**Comment by Vanuan** [comment]
Probably something has changed in the history? Previously I could get basename from the container's `location.basename`

**Comment by Vanuan** [comment]
Here's what I had to do:

```
const addLocationBasename = (history, basename) => {
        history.location = Object.assign(
                history.location,
                {
                        basename
                }
        );
};

export default (history, basename) => {
        addLocationBasename(history, basename);

        history.listen(() => {
            addLocationBasename(history, basename);
        });
}
```

**Comment by pshrmn** [comment]
What is your use case for wanting the `basename`? The `basename` represents the part of the URI's `pathname` that your application is told to ignore, so I don't know why you would want it to be part of the `location`.

**Comment by Vanuan** [comment]
The use case is providing URLs to external resources. Or opening a link in a new window.

**Comment by richardszalay** [comment]
FWIW, you can use `history.createHref()` to apply the basename to a URL generated via `generatePath` or any other means:

```
const { history } = this.props;

const pathname = generatePath(routeUrl, params);

const url = history.createHref({
  pathname
});

// url includes basename
```
