### ISSUE TITLE
Native Shared Element Transitions?

### ISSUE THREAD

**Issue by braco** [ReactTraining/react-router#5146]
This feature has landed in a few native routers. Any plans here?

http://airbnb.io/native-navigation/docs/guides/shared-element-transitions.html
https://github.com/exponent/ex-navigation/tree/master/example-shared-element-transitions
https://github.com/wix/react-native-navigation/tree/master/example/src/screens/transitions/sharedElementTransitions

**Comment by timdorr** [comment]
Nope, we're not going to build out animation tooling ourselves. That would be best left to an addon library. If someone wants to build one, we'd be more than happy to add it to the monorepo!
