### ISSUE TITLE
Unexpected '!' in 'bundle-loader

### ISSUE THREAD

**Issue by avishekjana** [ReactTraining/react-router#5148]
I'm getting this error while working on code splitting with React router. As per the guideline when I'm using bundle loader to lazy load a component, I'm getting this error constantly. I've also installed bundle-loader npm package, but no luck. My import statement is given below
`import loadSignin from 'bundle-loader?lazy&name=signin!./views/signin';`

## Version
4.0.0

## Test Case
https://codepen.io/ReactJSTraining/pen/jyYjeW

**Comment by timdorr** [comment]
This isn't a router issue.

**Comment by avishekjana** [comment]
Maybe but whatever documentation given here https://reacttraining.com/react-router/web/guides/code-splitting is not making things very clear.

**Comment by timdorr** [comment]
Are you using Webpack 2? You need to set it up and use it according to their docs: https://github.com/webpack-contrib/bundle-loader#usage

**Comment by kpyorala** [comment]
React Router documentation proposes to use Create React App for testing the examples (https://reacttraining.com/react-router/web/guides/quick-start) and maintainers of that project propose not to use bundle-loader (https://github.com/facebookincubator/create-react-app/issues/2477). And as syntax given in code-splitting example doesn't work with CRA, maybe it could be mentioned in the documentation.

**Comment by wucanqi** [comment]
I have the same errors
