### ISSUE TITLE
Navigator is deprecated and has been removed from this package

### ISSUE THREAD

**Issue by rahmanusta** [ReactTraining/react-router#5153]
I get the following error when I use react-router-native.

Navigator is deprecated and has been removed from this package. It can now be installed and imported from `react-native-deprecated-custom-components` instead of `react-native`. Learn about alternative navigation solutions at http://facebook.github.io/react-native/docs/navigation.html

```
"dependencies": {
		"react": "16.0.0-alpha.6",
		"react-native": "0.44.0",
		"react-redux": "^5.0.5",
		"react-router": "^4.1.1",
		"react-router-native": "^4.1.1",
		"redux": "^3.6.0",
		"redux-thunk": "^2.2.0"
	}
```

**Comment by rammi44** [comment]
Even I am getting the same.. What can i do?

**Comment by lostomato** [comment]
In ur project package use "npm list | grep react" to show the package list.
and try running "npm install react-router-native"
