### ISSUE TITLE
Routing doesn't work correctly when 'inferno-compat' is used.

### ISSUE THREAD

**Issue by Symbitic** [ReactTraining/react-router#5154]
## Version
4.1.1

## Test Case
```javascript
import React from 'react'
import ReactDOM from 'react-dom'

import {
  BrowserRouter as Router,
  Route,
  Link
} from 'react-router-dom'

const App = () =>
  <Router>
    <div>
      <ul>
        <li><Link to="/">Home</Link></li>
        <li><Link to="/about">About</Link></li>
      </ul>

      <hr/>

      <Route exact path="/" component={Home}/>
      <Route path="/about" component={About}/>
    </div>
  </Router>

const Home = () =>
  <div>
    <h2>Home</h2>
  </div>

const About = () =>
  <div>
    <h2>About</h2>
  </div>

ReactDOM.render(<App />, document.getElementById('root'))
```

```javascript
module.exports = {
  ...
  resolve: {
    alias: {
      'react': 'inferno-compat',
      'react-dom': 'inferno-compat'
    }
  },
  ...
}
```

## Steps to reproduce
Use `inferno-compat` in any project using `react-router-dom`.

Although everything renders correctly at first, actual routing will not after that, because components will not update (i.e. change) when the location changes.

The example given above works correctly when used with React/React-DOM, but when Inferno-compat is used, the issue will occur. I don't think this is intentional, as multiple developers have reported that react-router-dom works as expected when used with Preact-compat.

## Expected Behavior
Using the above example, when the user clicks on the "About" link, the location should change to `/about`, and "About" should be displayed instead of "Home".

## Actual Behavior
Although the location does change to `/about`, the Home component is still the one being rendered, so the page will still say "Home". If you hit the refresh button, it will then display "About" as expected, but then clicking on the "Home" link will result in the exact same problems.

**Comment by timdorr** [comment]
This sounds like an issue with inferno. We don't test against any other React-like libraries. I would open up an issue on that project's repo instead.
