### ISSUE TITLE
Firefox: state of <Link> missing after manual refresh (Click F5 in browser)

### ISSUE THREAD

**Issue by huchong26** [ReactTraining/react-router#5158]
## Version
"react-router": "2.4.1"
"react-router-redux": "4.0.4"

I also check the new version, the problem is the same.
    "react-router": "^4.1.1",
    "react-router-dom": "^4.1.1",
    "react-router-redux": "^4.0.8",

## Test Case
using Firefox browser
bound the history to the store of page in the code,
const pagehistory = syncHistoryWithStore(browserHistory, pagestore);

In the first page as parent 
use <Link to={{ pathname: `/XXXX`, state: { ChildID: item.axStationID, ChildNumber: item.StationNumber} }}>{item.StationNumber}</Link> to redirect to child page

## Steps to reproduce
1) click the link in parent page to redirect to child page
2) refresh the child page by manual after the child page initialized (press F5)

## Expected Behavior
the value in this.props.location.state is {ChildID: xxxxxxx, ChildNumber: xxxxxx}

## Actual Behavior
the value in this.props.location.state is {ChildID: xxxxxxx, ChildNumber: xxxxxx} before manual refresh
but the value is null after manual refresh

This problem only occur in Firefox, other browser(IE, Chrome, Safari) are ok.
there is no problem when user click the link to get into related child page.
but when user refresh the child page, the this.props.location.state is null

I had checked the this.props.location.key has change when refresh the page.
don't know why, it is werid!!!
and chrome, safari, IE, the key will not change, so the value match from sessionstorage @@History/xxxxxx is ok.

**Comment by timdorr** [comment]
`location.state` should disappear after a browser refresh. That is how you tie additional state to a location without having it survive refreshes. The fact that it's not is indicative of some other problem with your configuration.
