### ISSUE TITLE
Named routes

### ISSUE THREAD

**Issue by isergey** [ReactTraining/react-router#5160]
Hello. I can't find how to make named routes.
```jsx
<Router>
    <Route path="/user/:id" name="user" component={UserProfile}  />
</Router>
```
Then:
```jsx
<Link to={ name: 'user', params: { id: 123 }}>View profile</Link>
```
What about this?

**Comment by timdorr** [comment]
This hasn't existed in React Router since the pre-1.0 days. We aren't adding it back.

**Comment by vasilakisfil** [comment]
@timdorr how comes? I mean, not all sites are in english (imagine for a redirect having to write Arabic) + you can see all your routes in one place, you don't have to open all files to figure out what's going on.

**Comment by pedsmoreira** [comment]
I created a package for using named routes with react-router-dom v4. Here's the link for those looking to use named routes.

https://github.com/pedsmoreira/named-react-router
