### ISSUE TITLE
Child Routes not loading

### ISSUE THREAD

**Issue by AndrewKralovec** [ReactTraining/react-router#5163]
## Version
4.0.0

## Test Case
So i downloaded the new react-router, and i'm trying to load some child routes using the new react-router. However, when i navigate to the address it shows just a blank screen. So i dont know if this is a bug or if child routes are no longer supported. 

My repo can be found [here ](https://github.com/AndrewKralovec/React-Router-4)
## Steps to reproduce
Try to load child routes in your application. 

## Expected Behavior
For the pages to be loaded into App page 

## Actual Behavior
Navigates to a new page

**Comment by timdorr** [comment]
Please read the docs, as the API has changed significantly in 4.0. You appear to be using the 2/3 API.
