### ISSUE TITLE
StaticRouter adds leading slash to relative links

### ISSUE THREAD

**Issue by lewisdiamond** [ReactTraining/react-router#5165]
## Version
4.1.1

## Expected Behavior
StaticRouter should not add a leading slash to my relative `<Link>`s

## Actual Behavior
StaticRouter adds a leading slash to my relative `<Link>`s and causes React to NOT reuse the server-rendered markup.

The behavior is due to: 
[This](https://github.com/ReactTraining/react-router/blob/master/packages/react-router/modules/StaticRouter.js#L91)

**Comment by timdorr** [comment]
We don't support relative links....yet! See #5127
