### ISSUE TITLE
Access route-path

### ISSUE THREAD

**Issue by misantronic** [ReactTraining/react-router#5166]
I realized, react-router-redux's location-state exposes `hash`, `pathname` and `search` properties. Also when I add `withRouter` to my component, I have access to these props.
What I need (to build a breadcrumb) is the real route-path. f.e. the pathname is `/communication/messages/drafts/draft/9501`  and I want its route `/communication/messages/drafts/draft/:id`.

The Route itself gives me this information but my breadcrumb is not located there (its far in the upper scope) so I don't have access to this.
react-router v3 gave me this information in the `router`-prop which I could pass on to its child-components via context. How do I do this with react-router v4 or react-router-redux?

**Comment by timdorr** [comment]
`this.props.match.params` is the new location: https://reacttraining.com/react-router/web/example/url-params

**Comment by misantronic** [comment]
Perhaps I was not clear enough. Please see the attached screenshorts:

<img width="1037" alt="screen shot 2017-05-24 at 20 22 08" src="https://cloud.githubusercontent.com/assets/6033531/26419171/12e665ae-40bf-11e7-90a9-bb66b71e6601.png">

As you can see, the route has the path: `/communication/bulkmessages/drafts/draft/:id`

And here, in the upper scope is the breadcrumb:

<img width="804" alt="screen shot 2017-05-24 at 20 25 22" src="https://cloud.githubusercontent.com/assets/6033531/26419223/38cee4b2-40bf-11e7-83d6-e1f81747a185.png">

And I don't have access to the path there.

**Comment by timdorr** [comment]
Right, because it's not under the Route that collects that param. Route can be anywhere in your tree now, so multiple ones can match and they can have their own parameters. 

You probably want to look into something like react-router-config to get the older behavior.

**Comment by pwhipp** [comment]
Found this when encountering a similar problem upgrading my breadcrumb stuff to v4. Seems to me that you want to take advantage of the new behavior.

The Breadcrumb component can be a route that matches pretty much any path (any path you want a breadcrumb for) so if it is implemented that way and kept outside any switch statements, you get what you want. [Here's a codepen to demonstrate](https://codepen.io/Whippy/pen/xLEPdo).
