### ISSUE TITLE
react-router-redux: (v5) Add to state params and route mask (match.path)

### ISSUE THREAD

**Issue by a-x-** [ReactTraining/react-router#5167]
action `LOCATION_CHANGE` provides only low-level pathname and etc. now

**Comment by timdorr** [comment]
react-router-redux has never had access to the router params. And there are now multiple matches in a tree, so you can't put them into the store. There is not one canonical match in 4.0.

**Comment by a-x-** [comment]
App might have only single `BrowserRouter` with unambiguous (canonical) matches and may have multiple another Routers based on none-browser history (like MemoryRouter). Isn't it? How can work multiple `BrowserRouters`?

So conceptually match might be provided up to the store.

**Comment by timdorr** [comment]
No, match is local to the Route, not Router. There can be many Routes in the tree and therefore many unique matches.

**Comment by AyubaMakoa** [comment]
the way i do it is by getting the current route on willmount life cycle hook. then slite the route by / sign and then select the param i am interested in but you have to run all this in a setTimeout() before it will work

**Comment by a-x-** [comment]
well, and I want to read many unique matches from the redux store by some route's key for instance.

and in my case I have one matched route only always.
