### ISSUE TITLE
react-router-redux: (v5) action CALL_HISTORY_METHOD does not called when <Link> clicked

### ISSUE THREAD

**Issue by a-x-** [ReactTraining/react-router#5170]
## Version
react-router latest
react-router-redux next

## Steps to reproduce
Click onto react-router Link

## Expected Behavior
I expect `{type: CALL_HISTORY_METHOD, method: 'push'}` action will be fired

----

It's not code error

**Comment by timdorr** [comment]
Link doesn't use the action creators. This is expected behavior.

**Comment by a-x-** [comment]
Thank you,
I know it's expected now by code. But what is it operate like this?
My position, `react-router-redux` should provide `<Link/>` with implicit action creator and `dispatch` runner.

**Comment by timdorr** [comment]
Because the action creators are optional and just a convenience to get access to the history instance. You shouldn't be relying on that action type for any reason, as it's imperative. Instead, rely on the declarative nature of state and react to changes to the state tree when the location changes.
