### ISSUE TITLE
[Sarfari] history back fail only the first enter my site

### ISSUE THREAD

**Issue by Theo-codeitUp** [ReactTraining/react-router#5174]
It is my website -> https://redpages.hk
My bug is happened in Safari 10 only and other browser work 

im try to test back function of my app:
https://redpages.hk/Event?source=app
and click item to go in detail page and do goBack function
but it will goBack to index
https://redpages.hk/
;not the page of
https://redpages.hk/Event?source=app

It just only happen in first url and have domain name, and it not happened in my localhost(test or deploy version)

someone face the same problem?

I use "react-router": "^2.8.1"

**Comment by timdorr** [comment]
Upgrade to 3.0. It's just 2.0 without the deprecation warnings. It comes with history 3.0, which I believe fixes this bug.

**Comment by Theo-codeitUp** [comment]
it is fixed when I upgraded to react router@3.x, ty guy
