### ISSUE TITLE
What framework is used for docs on the react-router site?

### ISSUE THREAD

**Issue by GrigoryPtashko** [ReactTraining/react-router#5175]
Hello!

I'm very very sorry for the off-topic but could anyone tell me which framework (or a static site generator) is used to create the docs here https://reacttraining.com/react-router/web/guides/quick-start ?

Very good looking and easy to use!

Thank you!

**Comment by timdorr** [comment]
It's all custom built. Code is here: https://github.com/ReactTraining/react-router/tree/master/packages/react-router-website
