### ISSUE TITLE
location does not have previous path

### ISSUE THREAD

**Issue by marcogreselin** [ReactTraining/react-router#5177]
Hello,
In the documentation [here](https://reacttraining.com/react-router/web/api/location) you say "Locations represent where the app is now, where you want it to go, or even where it was.". I just asked in chat how to access the previous page path but I was told it is impossible to get the previous path so it seems like that's not correct.

**Comment by pshrmn** [comment]
Where you are now is represented by one `location` object. Where you just were is a separate `location` object. Except for memory history, the information on old `location`s is just stored by the browser. If you need to reference old locations, you will need to implement something to store that yourself.

**Comment by marcogreselin** [comment]
Right so if I understand correctly `location` does not tell me where I just was right? So the sentence in the doc should be amended I think.

**Comment by timdorr** [comment]
Please submit a PR in that case. Just saying it's wrong doesn't give us anything to work with 😄

**Comment by pshrmn** [comment]
If I'm understanding what your post is saying, you interpreted "locations represent" as "a single location represents". I don't think that there is anything wrong with the current phrasing, but I suppose that you could change the beginning of the sentence to "A location object can represent...".
