### ISSUE TITLE
Documentation typos in web/guides/code-splitting

### ISSUE THREAD

**Issue by clhenrick** [ReactTraining/react-router#5179]
In the 6th & 7th paragraphs you have what looks like a double negative. In paragraph 6:

**Why bundle loader, and not import()?** 

Do you mean **Why bundle loader, and not require.ensure()?**    
OR   
**Why bundle loader, and not System.import()?**

Then in paragraph 7:
> We’ve been using it for years and it continues to work while TC39 continues to come up with an official dynamic import. The latest proposal is import(), and we could adjust our Bundle component to use import() instead:

I believe you mean "...and we could adjust our Bundle component to use **require.ensure()** instead:" ?

**Comment by clhenrick** [comment]
In the code example you have:

```js
class App extends React.Component {
  componentDidMount() {
    // preloads the rest
    loadAbout(() => {})
    loadDashbaord(() => {})
  }

  render() {
    return (
      <div>
        <h1>Welcome!</h1>
        <Route path="/about" component={About}/>
        <Route path="/dashboard" component={Dashboard}/>
      </div>
    )
  }
}
```

I believe `loadDashbaord(() => {})` should be `loadDashboard(() => {})`; the "o" and "a" in "Dashboard" are mixed up.

**Comment by clhenrick** [comment]
Ah nevermind, I see that you're comparing `bundle-loader` and `import()`, so it's not a typo in the 6th and 7th paragraphs. Not sure why I was confused there!

**Comment by timdorr** [comment]
For typos, please just do a PR. Issues are only add noise.

That being said, thank you for the PR! 😄
