### ISSUE TITLE
Documentation: Why does react-router exist?

### ISSUE THREAD

**Issue by Pokute** [ReactTraining/react-router#5183]
I stumbled upon react-router when searching for a specific solution I had with Redux.

React Router documentation and videos show good cases on '**How**' to use React-router.

There's some information on '**What**' it does.

I couldn't see any info on '**Why**' I would use react-router and why I would benefit in using them.

Having to watch a 5 minute video and ponder a few at the code to realise what purpose react-router has is pretty bad. For someone who hasn't done web development the purpose or '**Why**' of react-router might never become clear.

**Comment by timdorr** [comment]
Sorry if the video doesn't do it for you. Feel free to submit a PR with a suggestion for change.
