### ISSUE TITLE
How to do a find() on <MemoryRouter />

### ISSUE THREAD

**Issue by dschinkel** [ReactTraining/react-router#5184]
Ok, stuck.  I know this isn't necessarily a bug but really wanted to get some help on this one.

I'm not able to enzyme `find()` my component.  What I get back is a mounted <MemoryRouter /> so not sure how to work with this.
 
And...pretty sure (not entirely though) I have jsdom setup using the newer jsdom sytax but not 100% sure yet but it certainly isn't causing me any errors so far.

**jsdom.js**
```
const jsdom = require('jsdom')
const { JSDOM } = jsdom

global.window = new JSDOM(`<!doctype html><html><body id='root'></body></html>`).window
global.document = window.document
```

Test
```
require('../jsdom')

describe('Protected Route', () => {
  let store, app, index, responseBody

  beforeEach(() => {
    store = initStore()

    const App = ({store}) => (
      <Provider store={store}>
        <Layout>
          <Switch>
            <ProtectedRoute component={DashboardContainer} path='/dashboard'/>
          </Switch>
        </Layout>
      </Provider>)

    app = mount(<MemoryRouter><App store={store} /></MemoryRouter>)
  })

  it.only('renders requested route if authenticated', () => {
    const dashboard = app.find(DashboardContainer)
    expect(dashboard).to.exist
  })
})
```

Here is what I see in WebStorm, looks like I have an instance of `<MemoryRouter />` coming back after mounting:

<img width="1117" alt="screen shot 2017-05-29 at 5 48 20 pm" src="https://cloud.githubusercontent.com/assets/338798/26563714/107934aa-449c-11e7-9807-2a6a29115b56.png">

**Comment by dschinkel** [comment]
eh nevermind I resolved it. Gonna do a blog post on it.

**Comment by meza** [comment]
Wanna share? :)
