### ISSUE TITLE
4.1.1 hashHistory not

### ISSUE THREAD

**Issue by ToWorkit** [ReactTraining/react-router#5186]
'react-router' does not contain an export named 'hashHistory'.

**Comment by pshrmn** [comment]
The [`<HashRouter>`](https://reacttraining.com/react-router/web/api/HashRouter) creates a hash history for you. For most projects, that should be all you need to do.

```js
import { HashRouter } from 'react-router-dom';

ReactDOM.render((
  <HashRouter>
    <App />
  </HashRouter>
), holder);
```
If you need to access the `history` object outside of your components, you will need to create your own `history` object and pass it to the [`<Router>`](https://reacttraining.com/react-router/core/api/Router).

```js
// history.js
import { createHashHistory } from 'history';
export default createHashHistory();

// index.js
import { Router } from 'react-router-dom';
import history from './history';

ReactDOM.render((
  <Router history={history}>
    <App />
  </Router>
), holder);
```
