### ISSUE TITLE
Should be able to test if a path will resolve with our route configuration.

### ISSUE THREAD

**Issue by benwiley4000** [ReactTraining/react-router#5189]
Feature request.

It doesn't appear (I could be wrong) that v4 has a way to test if an arbitrary path can be resolved with the current route config. I'm aware of `matchPath` but that seems to require a specific route as an argument. I want to test the existing route configuration in our router context.

I just need something like `willResolve(pathname)` - so I can treat the path as an external link otherwise.

e.g.

```javascript
@withRouter // provides willResolve
class CustomLink extends React.Component {
  constructor (props) {
    super(props);
    this.handleClick = this.handleClick.bind(this);
  }

  handleClick (e) {
    if (!this.props.willResolve(this.props.to)) {
      window.open(this.props.to);
      return;
    }
    if (typeof this.props.onClick === 'function') {
      this.props.onClick(e);
    }
  }

  render () {
    return <Link {...this.props} onClick={this.handleClick} />;
  }
}
```

Seems like something like this may have existed before, but was not carried over to v4. (#1207)

**Comment by pshrmn** [comment]
There really isn't a good way to do what you're asking for. There isn't a centralized route configuration where we can match against all of the possible routes.

The question that I am wondering is why you need a `<CustomLink>`? Or to put it another way, why can you not distinguish between in-app and external paths yourself and just render an anchor for external paths? That is the approach that you should be going for.

**Comment by timdorr** [comment]
There isn't a route configuration anymore. Route can live anywhere in your tree. You can test this same thing in two ways:

- Provide a Router with a memory history above the component(s) you wish to test, just like we do in [our tests for Route](https://github.com/ReactTraining/react-router/blob/master/packages/react-router/modules/__tests__/Route-test.js).
- Use react-router-config, which offers the ability to have a central config and to test it's matches more directly.

**Comment by benwiley4000** [comment]
@pshrmn I see your point - the short answer is that we need to dynamically assemble a menu of links that might exist in our React app, or not - and over time the React app will encompass more and more routes. It probably wouldn't be too much work to just specify an "external" key in link configs that should be treated externally - but it would be nice for that to be one less thing to maintain.

@timdorr thanks, react-router-config might be what I need! Is there a recommended way to manage routes that need to render a redirect, besides including a function in an otherwise-serializable route config?

**Comment by benwiley4000** [comment]
Also @timdorr - the [verbose explanation of router config internals](https://reacttraining.com/react-router/web/example/route-config) on the documentation page for react-router is nice, but it also might be worth linking to the package that accomplishes the same thing (I didn't know about it until you mentioned it here). 🙂
