### ISSUE TITLE
Allow caching and reuse of rendered components without remounting/re-rendering again

### ISSUE THREAD

**Issue by danikenan** [ReactTraining/react-router#5196]
When a loading a route requires heavy duty rendering it is sometimes best to just cache it and retuse the same component, like in tabs. 

Allow caching the component and use hide/show instead of mount/unmount when returning to same route with the same params (if any).

Proposed sample code:
```
<Route path="/about" cached={true} component={About}/>
```
Where **`cached`** can be `boolean` or `function` that accepts the same parameters as render and return whether to cache (hide and show instead on mount/unmount).

**Comment by timdorr** [comment]
Please don't open duplicate issues: #5195

**Comment by dt-rush** [comment]
@timdorr you closed that issue without so much as addressing it though, using a boilerplate response.
