### ISSUE TITLE
History push doesn't render navigated page

### ISSUE THREAD

**Issue by nihiluis** [ReactTraining/react-router#5205]
I got the following Router. I want to navigate to a new page. For this I tried <Redirect> first and `this.props.history.push("/login")` later.

In both cases the URL gets updated in the browser, but the page doesn't rerender.

I'm using redux, redux-actions, redux-saga, react-router, react-router-dom, react, redux-form, react-dom

Example component
```js
 export namespace Hom {
  export interface Props extends RouteComponentProps<void> {
    authenticated: boolean;
  }

  export interface State {}
}

//@connect(mapStateToProps, mapDispatchToProps)
class Hom extends React.Component<any, any> {
  // this function is bound
  goLogin = () => {
      return (
        <Redirect to="/login" />
      )
  }

  goLogin2 = () => {
    this.context.router.transition('/login');
  }

  componentWillMount() {
    if (!this.props.authenticated) {
      this.props.history.push('/login');
    }
  }

  render() {
    const { children, authenticated } = this.props;

    return (
      <div id="home">
        { authenticated && <div>
          <Header />
            <Row>
              <News /> 
              <LastSymbols />
            </Row>
          </div> }
      </div>
    );
  }
}

function mapStateToProps(state: RootState) {
  return {
    authenticated: state.auth.authenticated
  };
}

function mapDispatchToProps(dispatch) {
  return {};
}

export const Home = withRouter(connect<any, any, any>(mapStateToProps, mapDispatchToProps)(Hom))
```

```js
ReactDOM.render(
  <Provider store={store}>
    <BrowserRouter>
      <App>
        <Switch>
          <Route exact path="/" component={Home} />
          <Route path="/home" component={Home} />
          <Route path="/stock/:name" component={Stock} />
          <Route path="/login" component={Login} />
        </Switch>
      </App>
    </BrowserRouter>
  </Provider>,
  document.getElementById('root')
);
```

## Version
newest

## Steps to reproduce
apply code above

## Expected Behavior
render new page

## Actual Behavior
doesn't render new page

**Comment by florimm** [comment]
I also have the same behaviour when trying to push from sagas.

**Comment by KTruong888** [comment]
Did you manage to fix it? I'm having a similar problem where the location is changing but the wrong component is getting matched

**Comment by nihiluis** [comment]
solution: removed `@connect(mapStateToProps, mapDispatchToProps) on App

**Comment by nihiluis** [comment]
I dont really know since it's so old, but it seems I removed the @connect annotation

```ts
@connect(mapStateToProps, mapDispatchToProps)
class Hom ... {
```

and replaced it with
```ts
export const Home = withRouter(connect<any, any, any>(mapStateToProps, mapDispatchToProps)(Hom))
```

at the bottom

**Comment by fittyCent** [comment]
Hey thanks for the response. Yeah I have a connect (no annotations) at the bottom of my file just like yours and it didn't work. Guess I'll have to look further. Thanks man.

**Comment by gr8pathik** [comment]
@fittyCent Did you got the solution for this? I am also facing the same issue as yours.

**Comment by risaWY** [comment]
@gr8pathik Nope. I believe I just did something else and avoided having to do this. Please post your solution here if you find it. Sorry, and thanks
