### ISSUE TITLE
Question: how to do processing of route and possible redirecting the right way

### ISSUE THREAD

**Issue by vass-david** [ReactTraining/react-router#5216]
Hi. Maybe I've overlooked something in new version of `react-router` (or `react-router-redux` I'm using) but I couldn't find the right solution.

**Problem**
1. `react-router` matches route with and without trailing slash. I would like to permit only path without trailing slash and if user navigates to path with trailing slash, redirect him to path without trailing slash.
2. I'm working on website with localisation which requires language code at the beginning of path (e.g. `/eng/some-page`). If user navigates to path without language code, I want to redirect him to path with language code (e.g. from `/some-path` to `/eng/some-path`). Obviously I don't want to specify redirects for every single route.

These to problems are a bit different but IMO are very similar. You get some path and you want to check if it's correct, if not then redirect to correct one.

**My solutions so far**

1. Create redux middleware that checks for `LOCATION_CHANGE` and calls another action with correct path instead of passing action to next middleware. This proved to be wrong and I've ended up with warnings about setStates in render method. Not really sure why this error appears, but I didn't want errors in my console.
2. In main AppContainer put hoc that checks for location change in `componentWillMount` and `componentWillReceiveProps` and dispatches `replace`/`push` action if necessary.

Another possible solution would be to do same stuff as in second solution but in render method with redirects. But I don't think it's necessary to do these checks every time that some value changes in store.

Second solution works so far, but I'm curious if there is any better way to do this in new `react-router`. I remember that in old version of router there was `onEnter` property on route that could be used for such operations, but I couldn't find alternative in new version.

Thank you for all advices/suggestions!

Cheers.

**Comment by timdorr** [comment]
For the first one, just hook into your history instance. You can do that inside of a top-level component under your BrowserRouter, or supply your own with the plain Router: `<Router history={history}>`

For the second one, just have a pathless Route that inspects the incoming URL and redirects as necessary.
