### ISSUE TITLE
Warning: BackAndroid is deprecated. Please use BackHandler instead.

### ISSUE THREAD

**Issue by mgustin12** [ReactTraining/react-router#5217]
## Version
react-router 4.1.1
react-native 0.44

## Steps to reproduce

1. npm install react-router@4.1.1
2. Implement AndroidBackButton by wrapping App
3. Open application and the warning should be at the bottom of the screen
4. Or press the hardware back buttton

## Expected Behavior

Not display warning `Warning: BackAndroid is deprecated. Please use BackHandler instead.`
Expect node_modules/react-router-native/AndroidBackButton to have `import { BackHandler } from 'react-native'` just like it is here -> https://github.com/ReactTraining/react-router/blob/master/packages/react-router-native/AndroidBackButton.js

## Actual Behavior

Warning displaying `Warning: BackAndroid is deprecated. Please use BackHandler instead.` caused by react-router.
My local node_modules/react-router-native/AndroidBackButton has `import { BackAndroid } from 'react-native'`

**Comment by timdorr** [comment]
This is fixed by #5093 already. It hasn't been released yet.

**Comment by SuhairZain** [comment]
Hi @timdorr Do you have a tentative date for a release with this fix? Also, any idea why react-router-native is at 4.1.1 while react-router is at 4.1.2?
