### ISSUE TITLE
Calling PropTypes validators directly is not supported

### ISSUE THREAD

**Issue by Odol** [ReactTraining/react-router#5219]
Hi,

The new version of react router redux "^5.0.0-alpha.6" have problems, is showing me this message:

**Failed context type: Calling PropTypes validators directly is not supported by the `prop-types` package. Use PropTypes.checkPropTypes() to call them**
 
Im using a full typescript project whit out webpack
It is possible to avoid type checking?

regards!

**Comment by Odol** [comment]
Compiling the re react router package solves the problem. The umd version of react router repository seems to be outdated 🤔

**Comment by timdorr** [comment]
Yes, we need to rebuild with the latest prop-types version. This was fixed on their end. Dupe of #5173
