### ISSUE TITLE
Percent ("%") in pathname breaks <Link>

### ISSUE THREAD

**Issue by robertgrimm** [ReactTraining/react-router#5224]
It looks like there's a problem with how react-router automatically handles encoding/decoding of URLs when it comes to URLs that have a plain old percent in it (i.e. not percent-encoded characters but just "%").  The only way I can get it to work is if I manually encode it myself but I shouldn't have to do that since react-router automatically encodes/decodes other non-standard characters.

## Version
4.1.1

## Test Case
https://codepen.io/robertgrimm/pen/mweNvz?editors=1111

## Steps to reproduce
Run the given codepen and click on the "/foo%bar" link.

## Expected Behavior
Clicking on the `<Link to="/foo%bar">...</Link>` shouldn't result in an error and instead should follow that link.

## Actual Behavior
The `<Link to="/foo%bar">...</Link>` appears to correctly render into an `<a href="/foo%25bar">...</a>` tag, however, clicking on the link results in a URIError.  It works if I manually encode the percent myself before passing it to the Link tag, but I don't think I should have to do that if I'm understanding how react-router works.  Please correct me if I'm wrong.

**Comment by pshrmn** [comment]
`/foo%bar` is not a valid URI.

From [RFC 3986](https://tools.ietf.org/html/rfc3986#section-2.4)

> Because the percent ("%") character serves as the indicator for
   percent-encoded octets, it must be percent-encoded as "%25" for that
   octet to be used as data within a URI.

There are some websites that allow you to have un-encoded percent signs, but that isn't a standard and many sites will fail with malformed URIs (try to navigate to https://github.com/reacttraining/react-router/%).

Once (if?) https://github.com/ReactTraining/history/pull/465 is merged, automatic encoding will be removed. Then, `history` will rely on the browser to handle the encoding of the `pathname` if the user doesn't encode the `pathname` themself.

**Comment by robertgrimm** [comment]
I know it's not a valid URI but neither is "/foo^bar" yet react-router correct encodes that fine.  The point of this issue was that react-router seems to automatically handle encoding certain characters (like "^") but not others (like "%").  However, if you're going to remove automatic encoding then this is a moot point.

**Comment by dylanfpaul** [comment]
Any idea on when the removal of automatic-encoding is going to be brought to release?

**Comment by pshrmn** [comment]
@dylanfpaul Should be soon. The PR I linked earlier has been merged. The only thing holding it up still is that https://github.com/ReactTraining/history/pull/485 needs to be merged first, otherwise there will be a bunch of false positive warnings.

If you need the update ASAP, you could `git clone` and `npm link` the project. You'll just need to make the changes from the above PR yourself.

**Comment by pshrmn** [comment]
[`history@4.6.2`](https://github.com/ReactTraining/history/blob/master/CHANGES.md#v462) has now been released.
