### ISSUE TITLE
Redirect component doesn't use the history from Router component prop

### ISSUE THREAD

**Issue by gyurobenjamin** [ReactTraining/react-router#5225]
4.1.1 version with react-router-dom.

So here is my router.js:

```Javascript
import { BrowserRouter as Router, Route } from 'react-router-dom';
import createBrowserHistory from 'history/createBrowserHistory';

const history = createBrowserHistory();
render(
  <Router history={history}>
      <Route exact path="/one" component={One} />
      <Route path="/two" component={Two} />
  </Router>,
  document.getElementById('root'),
);
```

This is the componentOne where I'm calling the Redirect:
```Javascript
render(
  <Redirect push to={'two'} />
)
```

Works fine, but the history object in the Redirect will be a new instance.

And because of this I cant use eg.: history.listen in the first component.

**Comment by timdorr** [comment]
You must have something in the way along the context tree, as it most definitely [pulls the history from context](https://github.com/ReactTraining/react-router/blob/master/packages/react-router/modules/Redirect.js#L47).

**Comment by pshrmn** [comment]
#5114
