### ISSUE TITLE
Feature request: work with or alternative to redux-batched-actions

### ISSUE THREAD

**Issue by AJamesPhillips** [ReactTraining/react-router#5227]
## Version
[react-router-redux@5.0.0-alpha.6](https://github.com/ReactTraining/react-router/blob/master/packages/react-router-redux/modules/middleware.js)
[redux-batched-actions@0.2.0](https://github.com/tshelburne/redux-batched-actions/blob/master/src/index.js)

## Test Case

    import {createStore, applyMiddleware} from "redux";
    const History = require("history");
    import {routerMiddleware as createReduxRouterMiddleware} from "react-router-redux";
    import {enableBatching} from "redux-batched-actions";

    const history = History.createBrowserHistory();
    const reduxRouterMiddleware = createReduxRouterMiddleware(history);
    const reduxRouterStoreEnhancer = applyMiddleware(reduxRouterMiddleware);

    const appStore = createStore(
        enableBatching(function(state, action) { return state; }),
        reduxRouterStoreEnhancer
    );

    function dispatch(action: Action) {
        return appStore.dispatch(action);
    }

    dispatch(routerActions.push("/somepage"));
    dispatch(batchActions([
        routerActions.push("/somepage"),
    ]));

## Expected Behavior

Both calls to `dispatch` should result in a change to page "/somepage"

## Actual Behavior

The first `dispatch` correctly results in:

    {
        type: "@@router/LOCATION_CHANGE",
        payload: {
            hash: "",
            key: "s8lifw",
            pathname: "/somepage",
            search: "",
            state: undefined,
        },
    }

The second `dispatch` results the following and fails to cause a change in page to "/somepage":

    {
        type: "@@router/CALL_HISTORY_METHOD",
        payload: {
            args: ["/somepage"],
            method: "push",
        },
    }

Thanks for the fantastic library.  I would find batched actions with `react-router` really useful.  Am happy to help implement though I suspect the answer to this feature request will either be: "it's already done, check here"... or "it's not possible".

**Comment by timdorr** [comment]
It may be possible, but building support for every other library out there would involve a lot of hacking. Honestly, this sounds like something more in redux-batched-actions's court, which should support any type of action, including those that go through middleware. Although, I don't know the specifics of that library to be able to say that definitively.
