### ISSUE TITLE
no ConnectedRouter in react-router-redux?

### ISSUE THREAD

**Issue by zhangchier** [ReactTraining/react-router#5228]
## Version
4.0.0

## Test Case
https://codepen.io/ReactJSTraining/pen/jyYjeW

**Comment by septagram** [comment]
Closed with no reply? Please update the docs: README.md gives an example with `ConnectedRouter`, and you have to scratch your head a little and read source code to figure out it's being done via `syncHistoryWithStore()` now.

**Comment by timdorr** [comment]
Make sure you've installed the right version: `npm install react-router-redux@next` is 5.0 over here. The current `lastest` dist-tag is 4.0 over on @reactjs/react-router-redux
