### ISSUE TITLE
React-Router with React Native, history change anywhere in the code

### ISSUE THREAD

**Issue by BenBenz** [ReactTraining/react-router#5229]
Hello, 

I try to use history push anywhere in the code, so

my render method is just:

```
// all of my import ..
import { NativeRouter, Route, Switch, browserHistory } from 'react-router-native';
class MyApp extends React.Component {
	render() {
		return (
			<NativeRouter history={browserHistory}>
                                <Switch>
					<Route exact path="/" component={MainScene} />
					<Route path="/user" component={UserScene} />
					<Route path="/test" component={TestScene} />
                                </Switch>
			</NativeRouter>
		);
	}
}
AppRegistry.registerComponent('MyApp', () => MyApp);
```

In other parts of my code I tried to call like this:

```
import { browserHistory } from 'react-router';
browserHistory.push('/user');

```

I don't know if it is a bug in react native or me

**Comment by timdorr** [comment]
[NativeRouter doesn't take a history prop](https://github.com/ReactTraining/react-router/blob/master/packages/react-router-native/NativeRouter.js). It's ignoring the one you're providing. 

Also, react-router-native doesn't export `browserHistory`. You're mixing APIs between 2.0/3.0 and 4.0.

**Comment by BenBenz** [comment]
I have tried with MemoryRouter, but it is undefined

**Comment by BenBenz** [comment]
How I can have history with react-native ?

**Comment by BenBenz** [comment]
I have tried with MemoryRouter, but it is undefined

How I can have history with react-native ? we can do that with react-router with react-native ? @timdorr

**Comment by BenBenz** [comment]
@timdorr I have update my code

**Comment by pshrmn** [comment]
[`<MemoryRouter>`](https://github.com/ReactTraining/react-router/blob/v4.1.1/packages/react-router/modules/MemoryRouter.js) _also_ does not take a `history`. If you are providing your own `history`, you have to use the generic `<Router>`.

@BenBenz usage questions should be posted to StackOverflow/Reactiflux. The issues section here should mostly be for reporting bugs. Also, you should get a faster response on one of those two.

**Comment by BenBenz** [comment]
I've just do that and it works tanks @pshrmn ! 
Thanks you for your advice 

But all of that are not mentionned in the documentation ?
