### ISSUE TITLE
Feature request: custom router match function

### ISSUE THREAD

**Issue by otakustay** [ReactTraining/react-router#5232]
Current react-router use [matchPath](https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/api/matchPath.md) as the only implement of determine whether a `pathname` matches a router, however the regexp based solution won't work in some edge case.

A good example is the URL of github, for example we are browsing the `README.md` on branch `feature/3.0/fantastic`, we'll get a pathname like:

```
https://github.com/foo/bar/blob/feature/3.0/fantastic/README.md
```

Since the branch name `feature/3.0/fantastic` contains path separator `/`, we can't write a `path` string on `Route` component for this

In this case, I'd like to propose a `isMatch` function prop on `Route` so we can define our router like this:

```js
let matchGithubURL = (url, isExact) => {
    let lastSepratorIndex = url.lastIndexOf('/');
    let filename = url.substring(lastSepratorIndex + 1);
    let basePart = url.substring(0, lastSepratorIndex);
    let [match, username, repo, branch] = /^\/(\w+)\//(\w+)\/blob\/(.+)$/.exec(basePart);
    return {
        path: null, // No meaning
        url,
        isExact,
        params: {filename, username, repo, branch}
    };
};

<Route isMatch={matchGithubURL} component={FileBrowser} />
```

The `isMatch` function can remains the same signature of `patchPath` function so there should be only little modifications to current implement

**Comment by pshrmn** [comment]
I don't see this being rolled into the official `<Route>` component. You could always write your own `<Route>`-like component that supports this, but I'm not sure that that is necessary.

The following route works for me (test it out here: https://pshrmn.github.io/route-tester/#/foo/bar/blob/feature/3.0/fantastic/README.md)
```js
<Route path='/:username/:repo/blob/:branch+/:filename' component={FileBrowser} />
/*
{
  "path": "/:username/:repo/blob/:branch+/:filename",
  "url": "/foo/bar/blob/feature/3.0/fantastic/README.md",
  "isExact": true,
  "params": {
    "username": "foo",
    "repo": "bar",
    "branch": "feature/3.0/fantastic",
    "filename": "README.md"
  }
}
*/
```

**Comment by otakustay** [comment]
Oh I find the `+` token works great in my case, for more sophisticated senario, is it enough to implement my own `Component extends Route` which overrides `computeMatch`?

**Comment by otakustay** [comment]
May I ask where could I find all these special characters in `path` prop? I couldn't find it in react-router docs website

**Comment by pshrmn** [comment]
React Router uses [`path-to-regexp`](https://github.com/pillarjs/path-to-regexp) to parse the `path` strings. One thing to note while looking at that documentation is that we only support string paths. While relative routes/links are not built-in _yet_, we need to stick to strings in order to support those.

I haven't seen anyone do it. but I think that extending the `Route` class should work. That said, `path-to-regexp`'s parameter modifiers should almost always be able to support your desired path structure.
