### ISSUE TITLE
React-router with Express server: GET request does not work properly.

### ISSUE THREAD

**Issue by ilangra** [ReactTraining/react-router#5233]
## Version
4.1.1
Express: 4.14.1
http-proxy-middleware:  0.17.3

## Test Case
I am using an Express server to mock my REST calls. (also tried with other solution)
Once I add the react-router to handle the navigation, all the GET request return the index.html instead of the mock data.
For example:
`<Switch>`
	`<Route exact path='/' component={LoginPage}/>`
	`<Route exact path='/login' component={LoginPage}/>`
`</Switch>`

## Steps to reproduce
call GET /localhost:3000/login/authentication
## Expected Behavior
Response status 200, body with token
## Actual Behavior
I get in the response the index.html file.

Moreover, if in the path I add **v1.0** 
For example: GET /localhost:3000/**v1.0**/login/authentication, it will work.

**Comment by anuragasaurus** [comment]
It's not made to handle routing for express, it's made to use with react.

**Comment by ilangra** [comment]
I use React of course, express is used only as a server, and in my case, only to mock the REST calls.

**Comment by pshrmn** [comment]
Please ask usage questions on StackOverflow/Reactiflux. The issues section here is (mostly) for bugs.

If you open a question on StackOverflow, I would recommend including the actual code from your server. What you have included above does not provide nearly enough information for someone to help you.

I will say that if you're just handling routing in Express and not doing server side rendering, then all of your routes _should_ just be returning `index.html` and the client side should be handling the rendering. Once again, that is something that seeing the actual server code should clear up.

**Comment by ilangra** [comment]
Ok thank you for your help.
