### ISSUE TITLE
I can not find "syncHistoryWithStore" in the next version

### ISSUE THREAD

**Issue by hopefuture** [ReactTraining/react-router#5234]
I use immutable in project.
In pre version，I can use "syncHistoryWithStore" to redefined the history. The code 

```
const history = syncHistoryWithStore(browserHistory, store, {
    selectLocationState: createSelectLocationState(),
    adjustUrlOnReplay: true
  });
```

But I can not find "syncHistoryWithStore", please tell me how to redefine the history in next version.

Thank you !

**Comment by patrickhpan** [comment]
See #4869

**Comment by andreareginato** [comment]
@hopefuture did you find a way to solve the issue. I'm trying to define a custom selector using `syncHistoryWithStore`, but it not being present does not give me any idea on how to move further.

**Comment by timdorr** [comment]
@andreareginato There is no such API in 5.0. Please re-read the README, as it uses an entirely new API.

**Comment by andreareginato** [comment]
Hi @timdorr, thanks.
I might miss something, but I've been reading the [react-router-redux README](https://github.com/ReactTraining/react-router/tree/master/packages/react-router-redux) in master, and I could not find any info about creating a custom selector (needed to enable immutable compatibility). Probably things changed, but I can't find some information on this.

I'm sure I'm missing something. 
Thanks for your time
