### ISSUE TITLE
How to navigate outside of components in ReactRouter 4?

### ISSUE THREAD

**Issue by RamYadlapalli** [ReactTraining/react-router#5237]
In React Router (v3) I can accept a server response and use browserHistory.push to go to the appropriate response page. However, this isn't available in v4, and I'm not sure what the appropriate way to handle this is in React-Router V4 .

In below example when the server returns a success, the user is taken to the Cart page
```js
// actions/index.js
export function addProduct(props) {
  return dispatch =>
    axios.post(`${ROOT_URL}/cart`, props, config)
      .then(response => {
        browserHistory.push('/cart'); // no longer in React Router V4
      });
}
```
How can I make a redirect to the page from function in React Router v4?

I can find lot of references on navigation from components in my case i need to navigate from a function

**Comment by thisiserik** [comment]
@RamYadlapalli Here is one possible solution that I have found to work, although not ideal and definitely needs to be addressed in the core package. 

Given the following code, you can redirect to a different route by dispatching a `push` action. 

```js
import axios from 'axios'
import { push } from 'react-router-redux'
import { API_URL } from '../utils/apiUrl'

export const loginUser = creds => {
  return dispatch => {
    dispatch(loginRequest(creds))

    axios({
      method: "post",
      url: API_URL + "/auth_token",
      data: { auth: creds }
    }).then(res => {

       dispatch(push('/home')) /* dispatch an action that changes the browser history */ 

      })

    }).catch(err =>
      dispatch(loginFailure('Wrong email/password combination'))
    )
  }
}
```

I have looked and not found any other ways to do this yet. This becomes very messy because in your components, you will have callback functions on links if you want to change the route, like so: 
```js
<button className="btn btn-secondary btn-block"
    onClick={() => this.props.dispatch(push('/'))}>Home Page
</button>
```

If anyone has better ways of doing this, please share!

**Comment by anuragasaurus** [comment]
React-Router passes a `history` object to the component which you can use to make a redirect.

`
export function addProduct(props) {
    return dispatch =>
        axios.post(${ROOT_URL}/cart, props, config)
       .then(response => { 
           props.history.push('/cart');
       });
}

**Comment by anuragasaurus** [comment]
@thisiserik  React Router passes a history object in the props to the component. You can use it to create a redirect, like this,

```
<button className="btn btn-secondary btn-block"
    onClick={() => this.props.history.push('/')}>Home Page
</button>
```

**Comment by thisiserik** [comment]
@anuragasaurus But if you are working _outside_ of a component, there is no history object as far as I can tell, no?

**Comment by thisiserik** [comment]
@anuragasaurus When using `react-router-redux`, the suggested mention does not seem to work. The URL is changed, but the new component is not loaded because the redux state has not been updated. In order to change the state, you would have to dispatch an action as I have suggested.

**Comment by anuragasaurus** [comment]
@thisiserik yeah, i tried it without using `react-router-redux` and it worked.

**Comment by thisiserik** [comment]
@anuragasaurus But it doesn't work with `react-router-redux`, correct?

**Comment by timdorr** [comment]
You can build your own history instance and pass it to `<Router>`. This is all that BrowserRouter and the others like it do: https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/modules/BrowserRouter.js

**Comment by mrobrian** [comment]
If I'm understanding the suggestion correctly, if we need to access the history object outside of a component we basically have to create our own version of BrowserRouter and have it use a history object we've created. Wouldn't it be easier on users of this package if those history objects were available like they used to be, rather than having to create a slightly modified version of something that's already done?

**Comment by timdorr** [comment]
No, because they were singletons and that was sort of an anti-pattern. We had to have escape hatches with useRouter(). When you import a module, you shouldn't be getting an instance, but a class/function/constant definition.

**Comment by wdjungst** [comment]
If you are outside of a route you can wrap your component in withRouter to get the history object.

**Comment by kjs3** [comment]
I have multiple separate react apps on a page where each one can change the location and moving to RR4 obviously broke this. I made my own version of `BrowserRouter` that accepts a `history` prop and uses it if given. Otherwise it's identical. So now I can create a history outside of the Router and pass it to each app's router. 

@timdorr, would a PR with ☝️  that be welcome or do you not want people to be able to provide history? Am I missing something here that will come back to bite me?

**Comment by timdorr** [comment]
No, we don't want people providing a history to the preconfigured Routers. Just use `<Router history={myHistory}>`.

**Comment by timdorr** [comment]
Also, we're going to warn if you try to pass a history into the preconfigured Routers: #5151

**Comment by kjs3** [comment]
Ok cool.

**Comment by Huxpro** [comment]
@wdjungst I tried so many ways and I found `withRouter` is the easiest and most reasonable way to reach the `history` object. Thank you!

**Comment by tiemei** [comment]
if i want to nav to another path in Action, it's so difficult. I should create a history obj and pass it to then Action method.
any simple solution?

**Comment by code-matt** [comment]
If you are using react-router-redux as well as redux-thunk and have the middlewares hooked up correctly, as well as have your app wrapped in 
```
<Provider store={myStore}>
  <ConnectedRouter history={myHistory}>
    ...
```

--

You can import push into and then dispatch it in a new thunk action. Let your redux container know about the action in mapDispatchToProps and then you can dispatch that action to navigate from any container or things containers pass it down to.

In your other actions, you can do async things and use that action to navigate to one screen or another depending on the result.

**Comment by SunnyXiao** [comment]
For v4: I am using 'mobx-react-router', and the router is as following, when i use history.push() to change the url, and then the url is changed but the ui is not change, why?
`import { RouterStore,
         syncHistoryWithStore } from 'mobx-react-router';
import createHistory from 'history/createBrowserHistory';

const browserHistory  = createHistory()
const routing = new RouterStore();
export const history = syncHistoryWithStore(browserHistory, routing);

export default routing;`

`<Router history={history}>
            <App>
                <Switch>
                    <Route exact path='/' render={() => (<Redirect to="/login" />)} />  {/*重定向*/}
                    <Route path='/home' component={AsyncHome} />
                    <Route path='/home-mobile' component={AsyncHomeMobile} />
                    <Route path='/login' component={AsyncLogin}  key="empty" />
                    <Route path='/quotation' component={AsyncQuotation} />
                    <Route path="*" component={NoMatch} />
                </Switch>
            </App>
        </Router>`

**Comment by DominicTobias** [comment]
Just wrap the app in an extended BrowserRouter:

```js
import { BrowserRouter } from 'react-router-dom';
import { createBrowserHistory } from 'history';

export const history = createBrowserHistory();

export default class YourBrowserRouter extends BrowserRouter {
  history;
}
```

And `import { history } ...` where you need it outside of react components. For me I wanted to redirect to the login page from within my fetch method if the server responded with a 401.

**Comment by em** [comment]
Why does the project have a BrowserHistory to begin with when it's just a wrapper class for the straightforward configuration of Router. This is just bad API design.
