### ISSUE TITLE
<Link onClick={foo} /> errors; should "to" prop be optional?

### ISSUE THREAD

**Issue by bwhitty** [ReactTraining/react-router#5240]
## Version
4.1.1

## Test Case
https://codepen.io/anon/pen/gRwbOr

## Steps to reproduce
Render a `<Link onClick={handler} />` without a `to` prop. See the error:
```
TypeError: location is undefined  react-router-dom.js:868:8
	createPath https://unpkg.com/react-router-dom@4.0.0-beta.3/umd/react-router-dom.js:868:8
	createHref https://unpkg.com/react-router-dom@4.0.0-beta.3/umd/react-router-dom.js:1350:42
	render https://unpkg.com/react-router-dom@4.0.0-beta.3/umd/react-router-dom.js:1569:17
```

## Expected Behavior
If I pass an `onClick` handler it's possible I *may* want to handle the event right there in the handler. React Router v4 <Link /> [has support for this](https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/modules/Link.js#L40). I should be able to omit the `to` prop if I pass an `onClick` prop.

## Actual Behavior
The issue is on [this line](https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/modules/Link.js#L62) the library ends up blowing up because `to === undefined` and when it is destructured things blows up upon rendering of the `<Link />`. 

## Proposal
Since there's no way to know whether or not a handler will `preventDefault()`, I think it's reasonable to make the `to` prop optional *if the user provides an `onClick`*. This would require removing the prop type check and instead doing checks within the render method. What do you think? I can implement this and make a PR if that's agreeable.

**Comment by pshrmn** [comment]
If you just want to use your own `onClick` and skip the built-in navigation, why not just render an anchor yourself?

```js
<a onClick={event => {...}}>Anchor Text</a>
```

**Comment by bwhitty** [comment]
Sure, but say I'm building an abstraction over `<NavLink />` for RR's automatic classnames from that component, but want to only handle clicks with `onClick`. That'd require me to implement a dummy `to` prop in order to make it not error on render. Seems like the internal implementation details are leaking out there and that RR's API can be made more robust.

**Comment by pshrmn** [comment]
A `<NavLink>` uses the `to` prop [to determine whether or not it is active](https://github.com/ReactTraining/react-router/blob/v4.1.1/packages/react-router-dom/modules/NavLink.js#L22). If there is no `to` value, then that would be the equivalent to a pathless `<Route>`, with the `<NavLink>` always being considered active. That would seem to defeat the purpose of the `<NavLink>`.

**Comment by bwhitty** [comment]
Heh, thanks for pointing that out. Sorry, terrible example. I'm getting a little off track from my overall point which is having to know too much of the internals of RR. 

I've implemented an abstraction over `<Link />` and now I have to dig into the RR internals and implement logic conditionally rendering a `<Link />` vs an `<a />` dependent on those internals. I realize `to` has been defined on the public API as a required prop, but the functionality of `<Link />` seems to suggest it could be otherwise. If the stance here is to push this responsibility into user space (which is valid opinion to have), just let me know.

**Comment by pshrmn** [comment]
I don't think that it would be desirable to remove the `to` requirement because a `<Link>` with no `to` would render an anchor with no `href` (meaning that [the anchor would not be a link](https://stackoverflow.com/a/10510353/444829) and would break accessibility/not be styled as a `:link`). I'm not the one that makes the call on this sort of thing, but my guess is that the decision will be for the `to` prop to stay required.

I guess that part of my issue with this is that I don't really understand why you don't want your anchors to have `href` values. What are you doing in your `onClick` events? Are they not actually being used for navigation?

**Comment by bwhitty** [comment]
Correct, we have an abstraction over `<Link />` and with react router v2/3 that abstraction could handle both the case where we always wanted to handle the clicks in event handlers and the case where we passed `to` and allowed RR to do its thing. I'll close this for now since you've convinced me that this is probably not worth putting into RR.
