### ISSUE TITLE
Feature request: withRouter with mapped props

### ISSUE THREAD

**Issue by EloB** [ReactTraining/react-router#5245]
I think one big improvement to withRouter (hoc) is to be able to pick the props you want. I'm thinking about this pattern to not break backward compatibility.

```js
const withRouter = (mappedProps = false, mapProps = noop) => {
  if (mappedProps === true) {
    return ComposedComponent => class WithRouterWithMapProps extends Component {
      // The map props implementation
    }; 
  }
  const ComposedComponent = mappedProps;
  return currentImplemenation(ComposedComponent);
};
```

**How to use it:**
```js
const MySmartComponent = withRouter(true, ({ routeParams: { something } }) => ({
  myNeededComponentProp: something,
}))(MyDumbComponent);
```

The current problems I have right now is that I normally passes props like this. (Then I get issues with setting location, router, routeParams etc to the div resulting in warnings).
```js
const Something = ({ className, ...props }) => (
  <div {...props} className={classnames('something', className)} />
);
```

I use `recompose` at the moment and built a custom omitProps hoc to handle it but it's hard to maintain because you tend to forget to remove props that no longer in-use.
```js
const SomeSmartComponent = compose(
  withRouter,
  // someOtherHocs
  omitProps('location', 'routeParams', 'somethingElse')
)(SomeDumbComponent)
```

**Comment by timdorr** [comment]
What's the benefit here? You can safely ignore the props passed to the wrapped component if you don't need them.

**Comment by EloB** [comment]
The benefit is that you shouldn't pass props you don't need because they will break `PureComponent`.

**Comment by timdorr** [comment]
React added those warnings to DOM-backed elements specifically to discourage the use of `<div {...props}`. You should never blindly spread props into a DOM-backed element.

One very important use case for `withRouter()` is bypassing "pure" or sCU-implementing components, as we no longer subscribe to updates over context. So, this kind of behavior is expected and encouraged to be automatic. 

If you *really* need specific props, just wrap it with `<Route>`. [That's all `withRouter` does](https://github.com/ReactTraining/react-router/blob/master/packages/react-router/modules/withRouter.js#L13-L15).

**Comment by EloB** [comment]
I will totally disagree with the statement above. Why should I have to implement `onClick`, `onMouseMove` etc on all your components. It will just bloat the code.

Why are you using the context like that? It's a broken implementation in React. Please implement the context with an reactive approach instead and you won't have those types of issues. Example code how this could be done is `redux`.

**Comment by EloB** [comment]
Passing unnecessary props can end up in nasty bugs if suddenly a component will implement that prop.

**Comment by EloB** [comment]
**Quote from React homepage.** https://facebook.github.io/react/docs/context.html

Updating Context
Don't do it.

React has an API to update context, but it is fundamentally broken and you should not use it.

The getChildContext function will be called when the state or props changes. In order to update data in the context, trigger a local state update with this.setState. This will trigger a new context and changes will be received by the children.

**Comment by EloB** [comment]
@mjackson @ryanflorence what is your thoughts?

I think you can solve this either by adapting an rx library or create a tiny Observable implementation. Right now your updating your context and using a implementation even the React guys tell you to not use.

**Comment by timdorr** [comment]
`withRouter` is the recommended solution. We removed subscriptions because it puts the power back into the user's hands to determine when they want to take the performance hit of subscribing to history.
