### ISSUE TITLE
Why did we add WrappedComponent, and WrappedComponentRef?

### ISSUE THREAD

**Issue by ryanflorence** [ReactTraining/react-router#5248]
What are the use-cases? I'm just looking at it like ... but why?

**Comment by taurose** [comment]
Are you referring to this https://github.com/ReactTraining/react-router/pull/4838 ?

The PR and linked issue explain the motivation. The most important use case is testing the original component in isolation (without restructuring code). The ref can also be used for testing component instance methods, and for wrapping components that rely on instance methods (whether that's a good thing or not..).
