### ISSUE TITLE
can't work in android 4.2.2 system browser  -- react-router version 4.1.1

### ISSUE THREAD

**Issue by cxcshuaige** [ReactTraining/react-router#5252]
not chrome , just android 4.2.2 system browser
i tried this url's demo (https://reacttraining.com/react-router/web/example/basic)

it can work in chrome browser  but can't work in android 4.2.2 system browser

**Comment by dndxxiangyu** [comment]
you are very diao

**Comment by timdorr** [comment]
That version of Android doesn't support pushState. You have to use a hash history/router.
