### ISSUE TITLE
React Router 4 with Relay Modern

### ISSUE THREAD

**Issue by its-mahdi** [ReactTraining/react-router#5253]
I'm trying to use `react-router-dom` with Relay Modern which requires me passing my react components to relay's `createFragmentContainer()` function; But the resulting component stops my `<Route>`s to render when the URL changes via `<Link>`.

In other words, if I have pure react components with some `<Route>`s in it, it will work fine and it can render relay components as well; But if the `<Route>` is placed in a component that is passed to `createFragmentContainer()`, then it won't work.

Is this a bug or a known issue or am I not supposed to use React Router 4 with Relay Modern like this at all? I would appreciate any temporary workaround also.

**Comment by timdorr** [comment]
See this guide: https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/guides/blocked-updates.md
