### ISSUE TITLE
<Redirect/> does not override the current location and keeps adding to the history stack

### ISSUE THREAD

**Issue by FaisalJulaidan** [ReactTraining/react-router#5255]
as the Docs stated.
"Rendering a <Redirect> will navigate to a new location. The new location **will override the current location** in the history stack, like server-side redirects (HTTP 3xx)"

but that does not seem to be true. Whenever the user is redirected via the <Redirect/> component new locations are added to the history stack of the browser.

I do not know how to avoid that. that was possible in previous versions of react-router-dom though.

**Comment by timdorr** [comment]
Are you doing some sort of server-side rendering? [`<Redirect>` definitely does a `replace`](https://github.com/ReactTraining/react-router/blob/master/packages/react-router/modules/Redirect.js#L53)

**Comment by franzk** [comment]
That does not seem to be an issue with react-router. In latest Firefox and Chrome, ```history.replaceState()``` creates a distinct history entry, but nevertheless, the back button works as expected, jumping back across these replaceState entries.
