### ISSUE TITLE
withRouter not working if inside redux connect

### ISSUE THREAD

**Issue by alzalabany** [ReactTraining/react-router#5256]
Thank you for great library

## Steps to reproduce

1. create-react-app bug
2. cd bug
3. yarn add react-router react-redux redux
4. yarn start
5. open index.js and add

```
const App = () => <Router>
<Swtich>
  <route path="/a' component={()=><Link to="/b"}>B</Link>} />
  <route  component={()=><Link to="/a"}>A</Link>} />
</Switch>
<Router>
export const AppContainer =  connect(state, props)(withRouter(App));
ReactDOM.render(
      <Provider store={store}>
        <Router>
          <AppContainer store={store} />
        </Router>
      </Provider>,
    rootEl
  );
```

6. run application, click on any link the address bar will change but route will not change
7. edit index.js replace

 ```js
// export const AppContainer =  connect(state, props)(withRouter(App));
//with
export const AppContainer =  withRouter(connect(state, props)(App));
```

now every thing will work as expected.

## Version
4.0.0

## Expected Behavior
withRoute should work regardless of HOC

**Comment by timdorr** [comment]
You have your `withRouter` and `connect` in the wrong order: https://reacttraining.com/react-router/core/api/Prompt

**Comment by alzalabany** [comment]
yp, thats the issue, it shouldn't be (order sensetive)

**Comment by thomassuckow** [comment]
It should be a real component and force update. Then in react 16 it wouldn't even have to make an element.

**Comment by Fercho191** [comment]
I think it has to do with [this](https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/guides/redux.md)
