### ISSUE TITLE
Child routes don't have access to their parent route's params

### ISSUE THREAD

**Issue by lindslev** [ReactTraining/react-router#5260]
Unless I'm doing something wrong (which very well might be the case :[]), it appears that child routes don't have access to their parent route's params. I'm currently migrating my app from react-router 1.0.3 to 4.1.1 ( 💀 ). In 1.0.3, I had a route structure like so:

```
render((
  <Provider store={store}>
    <Router history={browserHistory}>
      <Route path="/" component={App}>
        <IndexRoute component={WelcomeView} />
        <Route path="user/:id" component={UserView}>
          <IndexRedirect to="one" />
          <Route path="one/:activityId" component={TabOne} />
          <Route path="two" component={TabTwo} />
          <Route path="three" component={TabThree} />
      </Route>
    </Router>
  </Provider>
), document.getElementById('root'));
```

With this structure, `TabOne` for example would have access to `id` and `activityId` in this.props.params.

In 4.1.1, my structure looks like:
```
const AppWithRouter = withRouter(App);

render((
  <Provider store={store}>
    <BrowserRouter>
      <AppWithRouter />
    </BrowserRouter>
  </Provider>
), document.getElementById('root'));
```

where `App` renders a `<Switch>`. Inside the Switch, I render Routes for the top level views (ie UserView). _Within_ the UserView component's render, I render the child Routes for TabOne, TabTwo, TabThree, etc. But it appears that in those tabs, their match.params only have _their own Route's params_, *not* their parent Route's params (ie TabOne only has activityId, not id). And when I wrap child components of the tabs with `withRouter`, they don't have the parent route's params either.

>How will it make current work-arounds straightforward? 

Assuming I'm not completely wrong here, it would prevent me from having to do a hacky assign of parent props to child route props. Right now I'm using Route's render prop instead of component so that I can manually pass those params.

I also depend on the params of the UserView route in many child components of the Tabs so it'd save a lot of manual prop passing and work-arounds to have easier access to user/:id.

**Comment by JustFly1984** [comment]
I'm not sure that you need to use withRouter in this case.


Try this:
```
import{
  ConnectedRouter
} from 'react-router-redux'

render(
    <Provider
      store={store}
    >
      <Router
        basename='/'
      >
        <ConnectedRouter
          history={history}
        >
          <App />
        </ConnectedRouter>
      </Router>
    </Provider>
    , document.getElementById(containerId)
  )
```

**Comment by timdorr** [comment]
You can get access via a pathless Route or `withRouter` (which uses a pathless Route): https://reacttraining.com/react-router/core/api/match

> If a Route does not have a path, and therefore always matches, you’ll get the closest parent match. Same goes for withRouter.

**Comment by malthejorgensen** [comment]
I'm sorry – I don't understand how using a pathless route or `withRouter` solves the original issue. They both get _the closest parent match_ so cannot be used to easily get the `:id` (of the user) in e.g. the `TabOne`-component.

What would @lindslev's code look like in React Router v4?

**Comment by malthejorgensen** [comment]
Okay, I think I figured it out. You should use the `render`-prop on `Route` as described in https://github.com/ReactTraining/react-router/issues/4105#issuecomment-287262726:

```jsx
<App>
  <Route path="/" component={WelcomeView} exact />
  <Route path="/user/:id" render={(userProps) => (
    <UserView match={userProps.match} userId={userProps.match.params.id}>
      <Route path={`${userProps.match.url}/one`} render={(props) => <TabOne userId={userProps.match.params.id} />} />
      <Route path={`${userProps.match.url}/two`} render={(props) => <TabTwo userId={userProps.match.params.id} />} />
      <Route path={`${userProps.match.url}/three`} render={(props) => <TabThree userId={userProps.match.params.id} />} />
    </UserView>
  )} />
</App>
```
