### ISSUE TITLE
Switch component incorrectly matching routes

### ISSUE THREAD

**Issue by justinpincar** [ReactTraining/react-router#5261]
Hi there, I don't think the `<Switch>` component is matching correctly, or at least I'm not using it correctly.

```
<Switch>
  <Route exact path="/" component={Home} />
  <About />
  <Route component={Splat} />
</Switch>
```

The `<About />` component contains its own routes:

```
<div>
  <Route path="/foo/one" component={One} />
  <Route path="/bar/two" component={Two} />
</div>
```

With this setup, I'm never able to render the Splat route since it thinks About is a match.

This codepen should illustrate my issue - https://codepen.io/justinpincar/pen/xrqQEZ

---
https://stackoverflow.com/questions/44642711/react-router-v4-catch-all-route

**Comment by pshrmn** [comment]
The answer on StackOverflow is pretty much correct (and I added a comment to clear up where it is incorrect).

**Comment by justinpincar** [comment]
Thanks Paul, I appreciate it. I understand the behavior now, but my issue still remains. This app has literally over a hundred routes, split into a few containers with common behavior but not shared url paths. Is this setup not possible with react-router v4?

**Comment by pshrmn** [comment]
If I had a number of routes that shared some parent container, I would probably write them like this:

```js
class About extends React.Component {
  render() {
    return (
      <div>
        {this.props.children}
      </div>
    )
  }
}

const One = (props) => (
  <About>
    <div>Page One</div>
  </About>
)

const Two = (props) => (
  <About>
    <div>Page Two</div>
  </About>
)

const App = () => (
  <Switch>
    <Route exact path='/' component={Home} />
    <Route exact path='/foo/one' component={One} />
    <Route exact path='/bar/two' component={Two} />
    <Route component={Splat} />
  </Switch>
)
```
There are other approaches that you could also take, such as writing a custom `<Route>` that automatically wraps its component in an `<About>`. I hesitate to bring this up because custom `<Route>`s can be tricky, but this one should be fairly straightforward.

```js
// you have to use component, not render or children
const AboutRoute = ({ component:Component, ...rest }) => (
  <Route {...rest} render={(props) => (
    <About>
      <Component {...props} />
    </About>
  )} />
)

const One = (props) => (
  <div>Page One</div>
);

const Two = (props) => (
  <div>Page Two</div>
);


const App = () => (
  <Switch>
    <Route exact path='/' component={Home} />
    <AboutRoute exact path='/foo/one' component={One} />
    <AboutRoute exact path='/bar/two' component={Two} />
    <Route component={Splat} />
  </Switch>
)
```

**Comment by justinpincar** [comment]
Makes sense, and thanks for taking the time to explain how the wrapper would work!

**Comment by AlastairTaft** [comment]
I'm having trouble with this, if I extend the `Route` into a `AboutRoute` does `<Switch />` treat it the same? I've found my custom `<AboutRoute />`'s are always rendered.
