### ISSUE TITLE
Checksum comparison failed with ssr and code splitting

### ISSUE THREAD

**Issue by viperin** [ReactTraining/react-router#5262]
I have an error displayed by react when I use react-router 4.1.1 for server rendering and code splitting.
I have "<!-- react-empty: 10" in the client and not in the server.
Any idea what to do ?

**Comment by pshrmn** [comment]
This is a known issue, but there really isn't a satisfying way to solve this. Basically what is happening is that  on the server you aren't rendering until your code split components have loaded. However, on the client side you are rendering immediately, so your code split component is rendering `null` (or something similar). 

I remember there being a couple projects that were attempting to address this, but I cannot recall what they were called. The basic idea was to determine which components were being async loaded on the server, pass that data to the client (`window._REQUIRED_MODULES_ = [...];`), and then ensure that any required modules are loaded before rendering.
