### ISSUE TITLE
'react-router' does not contain an export named 'browserHistory'

### ISSUE THREAD

**Issue by UNDERCOVERj** [ReactTraining/react-router#5263]
import {browserHistory} from 'react-router'。but throw the error that browserHistory does not exist..and  `Cannot read property 'location' of undefined`

**Comment by pshrmn** [comment]
There is no `browserHistory` export in v4. If you're using v2/3, then you just need to install the correct version (`npm install react-router@3`). If you are using v4, you should read [this section of the migration guide](https://github.com/ReactTraining/react-router/blob/25776d4dc89b8fb2f575884749766355992116b5/packages/react-router/docs/guides/migrating.md#the-router).

**Comment by Palkiarora** [comment]
Also you can refer 'A Simple React Router v4 Tutorial' 

https://medium.com/@pshrmn/a-simple-react-router-v4-tutorial-7f23ff27adf 

Where you need to install 'npm install react-router-dom --save' in your project directory and 
then you can include following 

import { BrowserRouter, Link, Route } from 'react-router-dom';

**Example :** 

import React from 'react';
import ReactDOM from 'react-dom';
import { BrowserRouter, Link, Route } from 'react-router-dom';

const App = () => (
    <div>App
        <Link to='/about' >About</Link>
    </div>
)
const About = () => (
    <div>About
        <Link to='/' >App</Link>
    </div>
)

ReactDOM.render(
    <BrowserRouter>
        <div>
            <Route path='/' component={App} />
            <Route path='/about' component={About} />
        </div>
    </BrowserRouter>
    , 
    document.getElementById('root')
);

Is working fine for me.

**Comment by Kavehbak** [comment]
I had the same problem and I wasted a couple of days to figure it out. This error happens simply because react-router v4 does not have the 'browserHistory'(donno if that's a good thing or not though). I solved the issue by installing v3 like this:   npm install react-router@3 --save

**Comment by vieckys** [comment]
Working for me too. Thanks

**Comment by nishankkumar1994** [comment]
Need Help: When I am on '/About' route, it's also rendering App component at the top of the page.
