### ISSUE TITLE
React-Router-Redux is never firing CALL_HISTORY_METHOD

### ISSUE THREAD

**Issue by beardedtim** [ReactTraining/react-router#5266]
I am currently trying to create some middleware that does business logic on route change. We are using redux observables/epics in order to react to actions asynchronously and need a way to fire an event before the URL changes but that is caused by the change url action.

According to [this](https://github.com/ReactTraining/react-router/blob/master/packages/react-router-redux/modules/reducer.js#L15) file, it seems that LOCATION_CHANGE is not the action that we want to hook into. However, it seems to be the only action that is emitted from the react-router-redux.

I could not find much information but the CALL_HISTORY_METHOD action looks like what I am wanting to react to within my system but I cannot find out how to have that action emitted into my store via the below versions.

I have tried using `push` from the package but I still only ever get `LOCATION_CHANGE` events, not `CALL_HISTORY_METHOD` events.

## Version
`"react-router-dom": "^4.1.1"`
`"react-router-redux": "^5.0.0-alpha.6"`

## Expected Behavior
For [this action](https://github.com/ReactTraining/react-router/blob/master/packages/react-router-redux/modules/actions.js#L7) to be emitted into my redux store

## Actual Behavior
No action is emitted.

**Comment by timdorr** [comment]
The middleware for it swallows the action by default: https://github.com/ReactTraining/react-router/blob/master/packages/react-router-redux/modules/middleware.js

If you need to pick up on that action type, make sure your middleware comes before the react-router-redux middleware.

**Comment by beardedtim** [comment]
@timdorr Thanks for the speedy reply and pointing me towards the answer!

**Comment by jamiemcconnell** [comment]
Hi - I just came across this and found that if the `routerMiddleware` is the first one after `combineReducers` or at least above `thunk` it works.. banged my head on this for a while.
