### ISSUE TITLE
react-router-dom how to use js jump new location?

### ISSUE THREAD

**Issue by luojinghui** [ReactTraining/react-router#5272]
Novice learning react-router v4, encountered a seemingly very simple question, how do I use javascript control location changes.
This is my code:
Index.js
```js
const history = createHistory();

ReactDOM.render(
    <Provider store={store}>
      <Router history={history}>
        <App/>
      </Router>
    </Provider>
    , document.getElementById('root'));
registerServiceWorker();
```

App.js
```js
import React, {Component} from 'react';
import {
    Route,
    Link
} from 'react-router-dom'
import './App.css';

class App extends Component {
  constructor(props) {
    super(props);
  }
  onClickJump() {
    //Here is the page I want to jump to '/about'
    //How to achieve it
  }

  render() {
    return (
          <div>
            <ul>
              <li><Link to="/">首页</Link></li>
              <li><Link to="/user">关于</Link></li>
              <li><div onClick={this.onClickJump.bind(this)}>按钮跳转</div></li>
            </ul>
            <hr/>
            <Route exact path="/" component={Home}/>
            <Route path="/about" component={About}/>
          </div>
    );
  }
}

const Home = () => (
    <div>
      <h2>首页</h2>
    </div>
);

const About = () => (
    <div>
      <h2>User</h2>
    </div>
);

export default App;

```

help me ,thanks

**Comment by yaodingyd** [comment]
I believe you can still use `history.push('/about')`

**Comment by pshrmn** [comment]
@yaodingyd is correct, although you also need to ensure that your `<App>` has `history` as one of its props. The easiest way to do this would be to change `<App />` to `<Route component={App} />`. Then, you can access it as `this.props.history` in your `<App>`. While that will work, I would caution you against doing navigation with non link elements because they can cause accessibility issues.

**Comment by magicdawn** [comment]
`this.props.history.push('/about')`

**Comment by luojinghui** [comment]
@pshrmn thank you very much.I will try to avoid using non-linked jumps, unless the last resort is forced.
