### ISSUE TITLE
Why I am not using react-router 4

### ISSUE THREAD

**Issue by JoeGrasso** [ReactTraining/react-router#5274]
I don't expect this to stay up long but at least I can vent.

Prior to 4.x, I was able to make dynamic routes with data from my db.

I can't for the life of me figure out how to move to 4.1 and do the same thing.

I searched, and I see comments from the react-router team, 

"Well, we are not here to give you examples, go to stackoverflow to find out(sic)"

Thanks guys. I think I'll pass on react-router 4

**Comment by timdorr** [comment]
If 4.0 doesn't work for you, so be it. Feel free to continue to use 3.0 indefinitely. It will never be unpublished from npm and will continue to receive bug fixes in the future.

**Comment by JoeGrasso** [comment]
Tim Door, you are exactly the Ahole who commented to someone to find a solution on satackoverflow because you ppl were offering insight.
