### ISSUE TITLE
Check if <Route/> component's render prop is actually a function

### ISSUE THREAD

**Issue by totymedli** [ReactTraining/react-router#5282]
I wrote this:

```jsx
<Route path="/" render={MyComponent} />
```

Instead of this:

```jsx
<Route path="/" component={MyComponent} />
```

And I got this really unhelpful error:

> Uncaught TypeError: Cannot call a class as a function

I thought there was an error in my component, but no. It took me too much time to debug this and realize that the problem was within the way it was called. This could be easily avoidable if there was a simple check for the `render` prop that makes sure it is indeed a function. I assume this already exist, but a simple type check doesn't help if you are transpiling and your ES6 classes become functions too. I propose a try-catch that catches this exception and gives a more usable error, as this looks like a mistake that can happen to tons of users.

**Comment by timdorr** [comment]
This should already be [handled by the PropTypes](https://github.com/ReactTraining/react-router/blob/master/packages/react-router/modules/Route.js#L15-L16). I would enable some sort of PropTypes checking in your project to catch this.

**Comment by totymedli** [comment]
@timdorr As I wrote, the PropType checking is not enough, because transpiled classes will become functions, so they will pass the validation silently!
