### ISSUE TITLE
Override href for dom Link

### ISSUE THREAD

**Issue by benwiley4000** [ReactTraining/react-router#5287]
**Feature request**

So, possibly weird use case, but here's our issue.

We're running a React app with React Router inside an iframe. The iframe uses a hash history which is kept in sync with `window.top.history`. Whenever I access a url in the outer window where the iframe is loaded, the path gets passed to the iframe as a hash to initialize React Router.

So when `window.top` is at: `/app/page1`

The iframe is at: `/iframeapp#/app/page1`

That all works fine, but the issue is when I try to copy a link or open a link in a new tab. We end up loading the iframe page directly rather than the outer page. This breaks the experience for our users.

What I really want is for our `Link` elements to behave exactly the same, but use the "fake" hash path for the `href` attribute on the contained `a` element, rather than using `history.createHref()`.

So the `to` prop is `/app/page2`
And the link looks like `<a href="/app/page2" ... />`
And opening the link in a new tab takes me to `/app/page2`
But the iframe will load `/iframeapp#/app/page2`

Not sure if the best way to do this is to just let us specify our own `href` prop (which would work fine) or if there should be a setting for not translating the path before adding it to the `href`.

If the `href` prop option were chosen, it might be important to emit a specific warning if a user specifies `href` but not `to` (to make sure they don't think those props are equivalent).

**Comment by timdorr** [comment]
[`<Link>` uses history's `createHref`](https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/modules/Link.js#L61) to generate the link in the `href` attribute. You can override that in the history you pass down from `window.top.history` and then pass that on to your iframe's Router:
```js
const iframeHistory = {
  ...window.top.history,
  createHref: iframeCreateHref
}
```

[The `createHref` function](https://github.com/ReactTraining/history/blob/master/modules/createHashHistory.js#L182-L183) is really simple, so customizing it shouldn't be a big deal.

**Comment by benwiley4000** [comment]
Ok... seems like a super hacky solution, but it is pretty simple so I can try it.

**Comment by benwiley4000** [comment]
I'm fairly certain you mean an instance created by `createHistory()` since `window.top.history` wouldn't contain the right API.

Anyway, I tried this, and my url updates, and copying links/opening in a new tab works, but my route transitions no longer work:

```javascript
import createHistory from 'history/createHashHistory';

const baseHistory = createHistory();
const history = {
    ...baseHistory,
    // remove '#' from front of hrefs
    createHref: location => baseHistory.createHref(location).slice(1),
};
```

**Comment by timdorr** [comment]
Oh yeah, sorry, I didn't realize you were making a new history instance. But yes, that's the right idea.

**Comment by benwiley4000** [comment]
My route transitions don't work with that, though.. 😕

**Comment by benwiley4000** [comment]
Can you reopen this issue? I don't think the solution you gave actually works.

**Comment by benwiley4000** [comment]
The reason that solution did not work is because `createHashHistory`'s `setState` method modifies the `history` instance available within the closure where `setState` was created, which is `baseHistory`.

This, however, does work and provide the functionality I asked for:
```javascript
const history = createHistory();
const createHashHref = history.createHref;
history.createHref = location => createHashHref(location).slice(1);
```

That said... monkey-patching `history` does feel a bit dirty, but whatever, I guess.
