### ISSUE TITLE
Matching # as part of a route path (V4)

### ISSUE THREAD

**Issue by rjewson** [ReactTraining/react-router#5289]
For a number of reasons (mostly legacy), I need to use # deep in the path.  For example:

/listpage/itemA#modalB/123

would match the pattern:

/listpage/:item#modalB/:id

I have a simple HashRoute component:
`
const HashRoute = <Route
    {...routeProps}
    component={({ location, ...props }) => 
      location.hash.startsWith(path) && <Component {...props} />}
  />;
`

Which works in simple situations, and I guess could be extended, but ideally I'd like to use arbitrary patterns with '#'.

**Comment by rjewson** [comment]
I should add, my current workaround is to use a different separator e.g. @ instead of #

**Comment by timdorr** [comment]
Unfortunately, this isn't going to be possible. The hash is a standard URL structural element, so we can't special case it without breaking the URL parsing spec.
