### ISSUE TITLE
revival of location.query in location object

### ISSUE THREAD

**Issue by ZeroCho** [ReactTraining/react-router#5292]
Currently, we can access query string by `location.search`
I think it would be better to provide `location.query` which excludes `?` from `location.search`.

For example, assume that we have a url like 'www.reactrouter.com?type=web',
`location.search` shows '?type=web'

and I request to have
`location.query` which shows 'type=web' without '?' letter.

[Node.js url module](https://nodejs.org/dist/latest-v8.x/docs/api/url.html#url_url_strings_and_url_objects) also provide both `location.search` and `location.query`.
I think providing both is useful for those who parse querystring. For me, I always have to substring url to exclude ? letter, and it's quite annoying.

**Comment by timdorr** [comment]
Please see #4410. In particular, see this comment: https://github.com/ReactTraining/react-router/issues/4410#issuecomment-302577498
