### ISSUE TITLE
v4 Nesting Routes.

### ISSUE THREAD

**Issue by Andrew1431** [ReactTraining/react-router#5301]
Hello. I know this question has been asked 100x lately, and I've read all those questions / answers, and I still can not figure out how to achieve such a simple functionality with v4. SO unlike all other questions, I was hoping I could just post a snippet as it currently exists in v3, and you could show me how the same would be achieved in v4. This has pushed back my development way too long. I've tried way too many things.

``` jsx
  <Router history={ history }>
    <Route path="/login" component={ Blank }>
      <IndexRoute component={ LoginView }/>
    </Route>

    <Route path="/" component={ userIsAuthenticated(Main) }>
      <IndexRedirect to="/orders"/>
      <Route path="discounts" component={ DiscountsView }/>
      <Route path="users" component={ UsersView }/>
      <Route path="orders" component={ OrdersView }/>
    </Route>
  </Router>
```

Login Page gets a blank template that doesn't have the application navigation bars, top bar etc.

THE REST of the app gets wrapped the MAIN component that has sidebar, and topbar. I want Discounts / Users / Orders to be CHILDREN of the Main component.

Thanks =)

**Comment by timdorr** [comment]
https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/guides/migrating.md#nesting-routes
