### ISSUE TITLE
BUG custom history in BrowserRouter

### ISSUE THREAD

**Issue by pierre-b** [ReactTraining/react-router#5303]
## Version
4.0.0

## Test Case
https://codepen.io/anon/pen/qjoYdK

## Steps to reproduce
Create a custom history from history/createBrowserHistory and pass it to the BrowserRouter

## Expected Behavior
According to the docs, the BrowserRouter should use this history and not creating a new one.

## Actual Behavior
The BrowserRouter merges its props from the ```<BrowserRouter basename... forceRefresh...>``` into a new history.

So if I want to attach a location listener I have to: 
```<BrowserRouter listen={(location, action) => console.log('location', location)}>```

## Fix
Either update the docs to explain that we should not create a custom history but pass the "history" props to the Router, or fix the Router class so it fully uses the <Router history={customHistory}>

**Comment by pshrmn** [comment]
If you need to use your own history object (which should only be the case when you need to use it outside of your components), then you have to use the `<Router>` component. `<BrowserRouter>` always creates its own history object.

> According to the docs, the BrowserRouter should use this history and not creating a new one.

Can you please link the documentation that states this? None of them should, so if one does it needs to be updated.

**Comment by pierre-b** [comment]
Alright, I should have seen a previous version of the docs.

What I want to do is tracking the routes in Google Analytics by listening the  history, and the ```<BrowserRouter>``` doesn't accept a ```listen={(location,action) => console.log(location)}``` property to feed the ```history```.

A workaround is to wrap the <Routes> with ```withRouter``` and attach the ```history.listen```in the wrapper.... but it's not convenient...

**Comment by pshrmn** [comment]
You can use the [`<OnUpdate>`](https://github.com/pshrmn/rrc/blob/master/docs/OnUpdate.md) component from `rrc` (or write your own, its really just adding a listener on mount and calling a function on update).

**Comment by pierre-b** [comment]
Thank you @pshrmn, didn't know about your plugin, but I think this feature should be first-class citizen in the v4 as it used to be in previous versions. The "web analytics tracking" use-case is mandatory for people doing serious apps.
