### ISSUE TITLE
Route Not render 

### ISSUE THREAD

**Issue by heinhoang** [ReactTraining/react-router#5304]
"react-scripts": "1.0.7"
windows 10
node v6.9.5
npm 3.10.10
"react-router-redux": "^4.0.8"
-----------------------------------
App.js
```js
...
    return (
        <Provider store={store}>
           {/**import { IntlProvider } from 'react-intl';**/}
            <IntlProvider locale={appLocale} messages={messages}>
                <HashRouter history={history}>
                    <Switch>
                        {/* this works */}
                        <Route exact path="/login" component={Login} />
                        {/* this works */}
                        <Route exact path="/" component={Layout} />
                    </Switch>
                </HashRouter>
            </IntlProvider>
        </Provider>
    );
...
```
Layout.js
```js
return (
                <div className="container-fluid">
                        <Switch>
                             {/* this works */}
                            <Redirect from="/" to="/dashboard" />
                             {/*????????? this not works ??????????*/}
                            <Route exact path="/dashboard" name="dashboard" component={Dashboard} />
                        </Switch>
                </div>
);
```
Dashboard.js
```
import React from 'react';

const Dashboard = (props) => {
    return (
        <div>
            Dashboard
        </div>
    );
};

export default Dashboard;
```
redirecting to dashboard works but don't render anything???

**Comment by pshrmn** [comment]
There are a few issues with your code.

1. You are providing a `history` to the `<HashRouter>`. If you want to use your own history object, you need to use the `<Router>` component.
2. The version of `react-router-redux` that you are using is for previous versions of React Router. v5 of `react-router-redux` is the one that works with React Router v4 (there was already a v4 of `r-r-r` when v4 was released, so `r-r-r` had to be bumped to v5 for the RRv4 compatible release).

**Comment by heinhoang** [comment]
hey,
Do you mean:
```
    "react-router-dom": "^4.1.1",
    "react-router-redux": "^5.0.0-alpha.6",
```
I've just updated like that, but it's still not working

**Comment by heinhoang** [comment]
I know which caused the problem now.
`<Route exact path="/" component={Layout} />` should not have exact.
