### ISSUE TITLE
V4 How to keep location.state when refresh?

### ISSUE THREAD

**Issue by Evacaca** [ReactTraining/react-router#5306]
## Version
4.0.0

## Test Case
https://codepen.io/ReactJSTraining/pen/jyYjeW

**Comment by timdorr** [comment]
You can't. It's intentionally not stored in the URL and does not survive a refresh. If you need something to survive a refresh, use the search property and a query string.

**Comment by pshrmn** [comment]
I'm not sure what is going on with your code, but `location.state` persists across refreshes. All that `history` does is to grab the `state` property from `window.history.state` (`history` stores `state` and `key` properties for locations) .
