### ISSUE TITLE
NotFound route always showing with static routes

### ISSUE THREAD

**Issue by albert-olive** [ReactTraining/react-router#5307]
Hi,

How can I define a notFound component with `React Router 4` and static routes?

I use the `next`version of `react-router-redux`. So, in my client:

    export default function appRoutes(history) {
      return (
        <ConnectedRouter history={history}>
          <div>
            {routes.map((route, key) => (
              <Route key={key} {...route} />
            ))}
          </div>
        </ConnectedRouter>
      );
    }

And routes is:

    export const routes = [
      {
        path: '/',
        component: App
      },
      {
        path: '/:lang/chat',
        component: Chat
      },
      {
        path: '/:lang',
        component: Listing
      },
      ...
      {
        path: '*',
        component: NotFound,
        status: 404
      },
    ];

With this approach, the component not found is always showing along with the matched route.

I have read that instead of wrapping the `appRoutes` method described above, with a div, I have to use Switch. But with this approach, the routes never match.

So, what I'm doing wrong?

**Comment by pshrmn** [comment]
You need to use a [`<Switch>`](https://reacttraining.com/react-router/web/api/Switch) in order to only render the first matching route.

**Comment by albert-olive** [comment]
But that's a problem because it only render one route. In the code I uploaded before, I have the `App` component rendering when path is `'/'` and where I have the `navbar` and other components. Then, when the path is `'/:lang'`, I want to render the component `Listing` along with the `navbar`. How I can do that then @pshrmn?

**Comment by albert-olive** [comment]
I found a solution that works for me. I have removed from static routes the `App` component and placed before and then I used `Switch` to render only one route.

    export default function appRoutes(history) {
      return (
        <ConnectedRouter history={history}>
          <div>
            <Route path='/' component={App} />
            <Switch>
              {routes.map((route, key) => (
                <Route key={key} {...route} />
              ))}
            </Switch>
          </div>
        </ConnectedRouter>
      );
    }
