### ISSUE TITLE
push can not contain chinese

### ISSUE THREAD

**Issue by wollld** [ReactTraining/react-router#5310]
push("/RadioSelect/m=%E6%88%91%E6%88%91%E6%88%91%E4%BB%AC%E7%9A%84%E5%AE%B6%E6%88%91") or
push("/RadioSelect/m=我我我们的家我");
in bowser it is become "RadioSelect/m=%11%11%11%EC%84%B6%11"
i can not get the value i need

**Comment by timdorr** [comment]
We have to URL encode the path, otherwise it would not be a valid URL. If you need that information, use the search/query section of the location.

**Comment by pshrmn** [comment]
You should ensure that you are using the most recent version of `history`. I just ran the following code in my browser and it worked as expected.

```js
const b = History.createBrowserHistory()

b.push("/RadioSelect/m=我我我们的家我")
console.log(window.location.pathname)
// /RadioSelect/m=%E6%88%91%E6%88%91%E6%88%91%E4%BB%AC%E7%9A%84%E5%AE%B6%E6%88%91

b.push("/RadioSelect/m=%E6%88%91%E6%88%91%E6%88%91%E4%BB%AC%E7%9A%84%E5%AE%B6%E6%88%91")
undefined
console.log(window.location.pathname)
// /RadioSelect/m=%E6%88%91%E6%88%91%E6%88%91%E4%BB%AC%E7%9A%84%E5%AE%B6%E6%88%91
```

**Comment by wollld** [comment]
chrome is ok and desk safari is ok too,but iphone safari is not ok
