### ISSUE TITLE
"children" property not called on routes inside a Switch

### ISSUE THREAD

**Issue by ljwagerfield** [ReactTraining/react-router#5311]
## Version
4.1.1

## Test Case
https://codesandbox.io/s/OW7zx02G

## Steps to reproduce
1. Create a `<Switch>...</Switch>` with a series of `<Route path="..." children={(props) => ...} />` inside.

## Expected Behavior
`children` should be called for all routes w/ `props.match == null` for those that don't match, as per `Switch`'s ruling.

Expected test-case output for rendering the `/` path (see above) is:
```
true: /
false: /about
false: /topics
false: *
```

## Actual Behavior
`children` is only called on the first matching route.

Actual test-case output for rendering the `/` path (see above) is:
```
true: /
```

---

Ultimately, `children` loses the functionality that differentiates it from `render` -- the two behave identically in this context, whereas AFAIK `children` _should_ be called regardless of a match.

**Comment by timdorr** [comment]
Switch only renders the first matching child. If you want that behavior, just remove the Switch: https://codesandbox.io/s/znw7k3WO

**Comment by ljwagerfield** [comment]
The suggested workaround does not produce the expected outcome above:
```
true: /
false: /about
false: /topics
false: *
```

Your suggestion produces:
```
true: /
false: /about
false: /topics
true: *
```

**Comment by timdorr** [comment]
Yes, that's expected. But we're not going to change the behavior of Switch.

**Comment by ljwagerfield** [comment]
Ok. Are we saying that it's very difficult to produce the desired result above using React Router?

(I'm just trying to verify that the correct approach here is to implement my own form of routing, if there's nothing out-the-box that can provide the above style of routing w/ React Router)

**Comment by timdorr** [comment]
It's not possible right now. To do so would involve a behavior change and a performance regression (we would have to look at all of Switch's children every render). That's what isn't going to happen. 

If you *really* need this, I would encourage you to build your own Switch. It's not hard to do and can re-use a lot of [the existing Switch code](https://github.com/ReactTraining/react-router/blob/master/packages/react-router/modules/Switch.js#L33-L52).
