### ISSUE TITLE
react router 4 - Nested Switch not render component

### ISSUE THREAD

**Issue by heinhoang** [ReactTraining/react-router#5314]
App.js
```
<ConnectedRouter history={history}>
	<Switch>
		<Route path="/components" component={FakeComponent} />
		<Route path="/dashboard" name="Layout" component={Layout} />
	</Switch>
</ConnectedRouter>
```
Layout.js
```
<Switch>
	<Route path="/" name="Dashboard" component={Dashboard} />
	<Route path="/a" component={A} />
	<Route path="/b" component={B} />
</Switch>
```
Problem:
navigating to '/dashboard/a' or '/dashboard/b' doesn't render A or B component.

**Comment by pshrmn** [comment]
You need to add the `exact` prop to the first `<Route>` in your `Layout.js`. Otherwise, the path `/` is going to match every route.

**Comment by heinhoang** [comment]
I've just added `<Route exact path="/" name="Dashboard" component={Dashboard} />` but it's no use.

**Comment by pshrmn** [comment]
Oh, I missed this before, but the other issue that you are having is because your nested routes are attempting to match the literal paths `/`, `/a`, and `/b` when what you really want are `/dashboard`, `/dashboard/a`, and `/dashboard/b`. While here you can hard code the value, with dynamic params, you would use `match.url` to create the path for nested routes:
```js
<Route path={`${this.props.match.path}/a`} component={A} />
```

**Comment by heinhoang** [comment]
Oh, sorry, your solution works for me. Thanks.

**Comment by heinhoang** [comment]
hey @pshrmn, I have one more question:
can you explain the difference between
1. `<Route path="/dashboard/a" component={A} />` and
2. `<Route path={`${this.props.match.path}/a`} component={A} />`
As I print out `${this.props.match.path}/a`, it outputs `/dashboard/a` but why the first one doesn't work but the second work???
