### ISSUE TITLE
Why react-router-redux 5.0.0 is always in an alpha version?

### ISSUE THREAD

**Issue by vicbell** [ReactTraining/react-router#5317]
Why react-router-redux 5.0.0 is always in an alpha version?

**Comment by timdorr** [comment]
Because it's not finished...

**Comment by vicbell** [comment]
Is there any release plan of react-router-redux 5.0.0? Tks!

**Comment by vicbell** [comment]
@timdorr Is there any release plan of react-router-redux 5.0.0? Tks!

**Comment by timdorr** [comment]
No, there is no plan in place.

**Comment by ovaldi** [comment]
Hi @timdorr  Could you release react-router-redux 5.0.0 asap? i have been waiting for a long time, :)

**Comment by timdorr** [comment]
Nope, it's not done.

**Comment by coder77** [comment]
@timdorr still not yet done? It's 2018 now.

**Comment by timdorr** [comment]
Yes, that is the current year.
