### ISSUE TITLE
2 apps with 1 router, is that possible ?

### ISSUE THREAD

**Issue by NicoYang21** [ReactTraining/react-router#5319]
Hi, i'm new to react so I dunno if my case possible with router or not
let's say I have a html name it FRONT and it contain only header and footer, while the body contain only div for react with index.js
and then I want to create BACK, with different html since it contain different header and footer,
of course I can't use index.js since it specifically return FRONT body,
so I create back.js
but I don't know how to connect my back.js with my BACK.html
can I solve it with router ?

**Comment by pshrmn** [comment]
Yes, you just need to create your own `history` object and then use the `<Router>` component instead of the specialty routers (e.g. `<BrowserRouter>`).

```js
// history.js
import { createBrowserHistory } from 'history'

export default createBrowserHistory()

// index.js
import { Router } from 'react-router'
import history from './history'

ReactDOM.render((
  <Router history={history}>
    <Front />
  </Router>
), document.getElementById('front'))

// back.js
import { Router } from 'react-router'
import history from './history'

ReactDOM.render((
  <Router history={history}>
    <Back />
  </Router>
), document.getElementById('back'))
```
