### ISSUE TITLE
Perform redirect also in `Redirect`'s `componentDidUpdate`

### ISSUE THREAD

**Issue by jfschwarz** [ReactTraining/react-router#5321]
I would like to be able to redirect dynamically based on state. However, the `Redirect` component only performs the redirect in `componentDidMount` and not from within `componentDidUpdate`. This restriction seems rather artificial and to me feels counterintuitive.

My use case is as follows: An infinite scrolling list that updates the currently active page index in the location state. Some stripped-down example code:

```jsx
const InfiniteList = ({ match, startIndex, rows, setStartIndex }) =>
  <div>
    <InfiniteScroll rows={rows} loadMoreRows={setStartIndex} />
    <Redirect key={index} to={`${match.url}/${startIndex}`} />
  </div>

export default compose(
  withState(
    'startIndex',
    'setStartIndex',
    ({ match }) => match.params.index || 0
  )
)(InfiniteList)
```

Note the `key={index}` prop on the `Redirect` element. This is my workaround for triggering `componentDidMount` again after every page switch. I would prefer if the redirect would just work™ without this hack.

**Comment by timdorr** [comment]
See #5163 and #5003
