### ISSUE TITLE
React v16, changing routes, componentWillMount of the new route is called before componentWillUnmount of the old route

### ISSUE THREAD

**Issue by gajus** [ReactTraining/react-router#5325]
## Version
4.1.1

## Test Case
codesandboxed crashed every time I tried to install react v16.

```js
import React from 'react';
import { render } from 'react-dom';
import { BrowserRouter as Router, Route, Link } from 'react-router-dom';

class About extends React.Component {
  componentWillMount () {
    console.log('About MOUNT');
  }

  componentWillUnmount () {
    console.log('About UNMOUNT');
  }

  render () {
    return <div>About</div>;
  }
}

class Topics extends React.Component {
  componentWillMount () {
    console.log('Topics MOUNT');
  }

  componentWillUnmount () {
    console.log('Topics UNMOUNT');
  }

  render () {
    return <div>Topics</div>;
  }
}

const BasicExample = () => (
  <Router>
    <div>
      <ul>
        <li><Link to="/about">About</Link></li>
        <li><Link to="/topics">Topics</Link></li>
      </ul>

      <hr />

      <Route path="/about" component={About} />
      <Route path="/topics" component={Topics} />
    </div>
  </Router>
);

render(<BasicExample />, document.body);

```

## Steps to reproduce

Navigate between About/ Topics pages.

## Expected Behavior

When navigating between routes, expecting to first get `componentWillUnmount` of the old component, followed by `componentWillMount` of the new component.

## Actual Behavior

Getting `componentWillMount` of the new route before `componentWillUnmount` of the old route.

**Comment by timdorr** [comment]
Well, React is free to implement mounting/unmounting behavior however it sees fit. There's more flexibility for out-of-order operations now. 

Honestly, this seems like a React issue to be resolved. I'm not sure what we would do on this library. I'd recommend coming up with a failing test case and submitting that as a PR to the React repo. If that's acceptable behavior to them, they can at least clarify that for you.

**Comment by ryanflorence** [comment]
Yep, this has nothing to do with React Router. Please open the issue with React 😑

**Comment by townmi** [comment]
@gajus hello buddy, do u have any solutions？

**Comment by damianobarbati** [comment]
@gajus same problem here: did you manage to solve? 
Did you find a way to have (on route change) the old route component unmount before next route component mount?
