### ISSUE TITLE
Add breaking change notation and requirement for react-router-dom as NPM warning

### ISSUE THREAD

**Issue by methodbox** [ReactTraining/react-router#5326]
## Version
4.1.1

## Test Case
https://codesandbox.io/s/n55VljYk7

## Expected Behavior
NPM warning that $npm install react-router will install a broken version of React Router v4 minus react-router-dom.

i.e. The install should warn you that you are installing a version of react-router which is non-functional without -dom.

## Actual Behavior

The update to v4 included a breaking change (or set of changes) which results in $npm install react-router actually installing a part of react-router-dom which doesn't meet most use cases.

The result is a frustrating Google search to find out you actually:

1) Needed to install an @ version to get a working router or
2) Needed to actually install react-router-dom 
3) If #3 is true also need to completely rewrite your router and reread the documentation.

The problem is simple:

$npm install react-router is not going to install a working version but *should* install a version prior to v4 that works as expected (per breaking changes)

There should be a warning to users installing $npm install react-router that, "this is version X and the latest version can be installed using $npm install react-router-dom" - like EVERY OTHER NPM PACKAGE DOES.

If you're wondering why so many users of your router are pissed off about breaking changes - this is it - you helped them download a broken version with no warning.

**Comment by pshrmn** [comment]
I'm not sure what the warning that like EVERY OTHER NPM PACKAGE DOES is. Are you saying that something should be output in the terminal when they `npm install`?

I just submitted #5327, which would make knowing that users probably want `react-router-dom`  more visible over on https://npmjs.com/package/react-router.

As far as users having to `npm install react-router@3` for older versions, that is how semantic versioning should work. For anyone that already has v2/3 of React Router installed, NPM will stick to their current major version if they need to update. Anyone that wants to start a new project with an old version just has to specify that they want an old version.

**Comment by methodbox** [comment]
Basically, yeah a better warning but also since the current equivalent of react-router@3 is really react-router-dom then the name react-router shouldn't install part of v4; it really should have been the last version of v3 with a deprecation or similar warning.

Obviously if you want a specific version, you can install it as such, but if you're reading the v3 docs, you'd install react-router with no indication there was a problem.

So a more visible message like you suggest would definitely be better.

**Comment by timdorr** [comment]
We can only add messages to npm installs via [a deprecation notice](https://docs.npmjs.com/cli/deprecate). But that would indicate the current version is deprecated, when it is not. Until npm gives some alternative tooling for this, we can't really do anything here.

**Comment by methodbox** [comment]
That's just it - it should have been. I'm not sure if you can customize that deprecation notIce but that might be a solution.
