### ISSUE TITLE
reac-router-redux 5.0.0 LOCATION_CHANGE has no state

### ISSUE THREAD

**Issue by eungchang** [ReactTraining/react-router#5328]
## Version
   "react-redux": "^5.0.5",
    "react-router": "^4.1.1",
    "react-router-dom": "^4.1.1",
    "react-router-redux": "^5.0.0-alpha.6",

## Test Case
this is my configuration of store
```js
export default function configureStore( history) {
  
  const myRouterMiddleware = routerMiddleware(history)

  const store = createStore(
    combineReducers({
    	side_navigation,
    	user_home,
    	study_schedule_list,
	    router: routerReducer
	}),

    compose(
		applyMiddleware(myRouterMiddleware, sagaMiddleware,   logger),
		autoRehydrate(),
		 window.devToolsExtension
	     ? window.devToolsExtension()
	     : fn => fn()
    )
  )
```
and used ConnectedRouter as api.
reducers in combineReducers are immutable Map type.
but, router reducer is Object type. 
is problem that diffrence between those reducers type???

 
## Expected Behavior

action LOCATION_CHANGE payload  has a state before transitions. 

## Actual Behavior

action @@router/LOCATION_CHANGE

payload has no state .

**Comment by timdorr** [comment]
If you're using an immutable library, you'll need to implement your own routerReducer.
