### ISSUE TITLE
React-Router handle server get request passport-facebook

### ISSUE THREAD

**Issue by hmontes** [ReactTraining/react-router#5329]
Hi.

I have this code in my server.

``
 app.get('/auth/facebook', passport.authenticate('facebook', {scope: 'email'}));
``

This simple code redirects the app to facebook page, and thell call a callback page (like /auth/facebook/callback) for auth the user (And obtain the user data).

So. My question is. How can i handle this route in React? I'm using create-react-app and when i put "localhost:3000/auth/facebook" in the browser, react-router (in the client) handles the route. Not the server. 

I want to implement facebook auth in my react, react-redux, react-router app.

Thanks

**Comment by timdorr** [comment]
You don't. Passport is meant as a middleware layer for your express server. It doesn't work or exist in the client at all.

**Comment by hmontes** [comment]
Okey. So, i need to find another way to do a Social Login. 

Thanks
