### ISSUE TITLE
Can I pass dynamic props to components by state in v3?

### ISSUE THREAD

**Issue by buptyyf** [ReactTraining/react-router#5332]
I want to pass dynamic props to components by state in v3. But it didn't work.

It's show a warning "[react-router] You cannot change <Router routes>; it will be ignored" when I use code below. Then in <Login /> component, it always shows this.props.userId is null.

```javascript
constructor(props) {
        super(props);
        this.state = {
            userId: null,
        }
    }
componentDidMount() {
    this.setState({
            userId: "123",
    })
}
render() {
return (
<Router history={browserHistory}>
            <Route path="/TeachingResourceManagement">
                <IndexRoute component={(props) => (<Login {...props} onChange={this.handleUserIdChange.bind(this)} userId={this.state.userId} />)}/>   
            </Route>
</Router>
)}

```

P.S. 
I had tried to use code below (use render to pass props) but it also didn't work and even couldn't render a scene normally.
```javascript
<Router history={browserHistory}>
            <Route path="/TeachingResourceManagement">
                <IndexRoute render={(props) => (<Login {...props} onChange={this.handleUserIdChange.bind(this)} userId={this.state.userId} />)}/>   
            </Route>
</Router>
```

**Comment by timdorr** [comment]
No, you cannot do this. You shouldn't be wrapping Router in a component. It should live near or at the top of the component tree.

**Comment by buptyyf** [comment]
@timdorr Router is at the top of the component tree in my code, I have updated it. And how can I pass dynamic props to components in v3?
