### ISSUE TITLE
Feature request: support StaticContext in react-router-redux

### ISSUE THREAD

**Issue by 0xR** [ReactTraining/react-router#5333]
I am using [StaticRouter](https://reacttraining.com/react-router/web/example/static-router) with server side rendering. I use the context object to set the return code of the server. (to send 404). 

However ConnectedRouter only connects the default `Router` not the `StaticRouter`. Reading [the source code](https://github.com/ReactTraining/react-router/blob/dc2149ec0c63bfc95b71e40c81431e34cfbfeda9/packages/react-router/modules/StaticRouter.js#L82) it seems like we only need to set the child context.

v5 alpha 6

**Comment by timdorr** [comment]
You should use a memory history on the server. This is exactly what v3/2 did with `match`. 

Syncing a StaticRouter doesn't make sense because it never changes the location. It stubs out a fake history to do this, so we can't integrate with something that is intentionally incomplete.

**Comment by 0xR** [comment]
Interesting since the [server rendering guide](https://reacttraining.com/react-router/web/guides/server-rendering) shows you need to use the `StaticRouter`. But I'll try it out and report back.

**Comment by 0xR** [comment]
You definitely need the `StaticRouter` to do server rendering. There is no other way to define the `staticContext` which you need to set http response code.

All I need the `ConnectedRouter` for is to ensure the location is stored in the redux store. To work around the issue I removed the `ConnectedRouter` and just dispatched a location change event myself:

```js
import {
  routerMiddleware,
  LOCATION_CHANGE,
} from 'react-router-redux';
import createHistory from 'history/createMemoryHistory';

function doIt() {
  const store = createStore();

  store.dispatch({
    type: LOCATION_CHANGE,
    payload: history.location,
  });
  ...
}
```

This works and had the added benefit that the url is available in redux before server side data fetching occurs. (I'm using [react-router-config](https://github.com/ReactTraining/react-router/tree/master/packages/react-router-config) for that)
