### ISSUE TITLE
this.props.history.go(0) not refreshing the page for firefox and safari.

### ISSUE THREAD

**Issue by hopbalabi** [ReactTraining/react-router#5334]
## Version
4.1.1

## Test Case
https://codesandbox.io/s/n55VljYk7

## Steps to reproduce
Add a button to the page and give `this.props.history.go(0)` to the click hander. It should refresh the page but it did it for only chrome not Firefox and Safari did not test for opera. Also not working for mobile.

NOTE: This is the history object of the router do not focus to the `this.history` part please.

## Expected Behavior
It should refresh the page.

## Actual Behavior
Nothing happens for Firefox and Safari, only works for chrome.

**Comment by timdorr** [comment]
This is intentional: https://bugzilla.mozilla.org/show_bug.cgi?id=86487

If you want to reload the page, use window.location.reload().

**Comment by hopbalabi** [comment]
Hi, i checked this bug also and saw that ticket. What i try to say why you are not doing this in the code. I mean when we call go function in your history you can simply override this as using window.location.reload(). right?
