### ISSUE TITLE
Browser URL grows with each click on Link tag

### ISSUE THREAD

**Issue by saadbinsaeed** [ReactTraining/react-router#5338]
I am using `react-router v3`. I have implemented code splitting by using this version. On my dashboard page when I click on any application's icon, route changes. Server serve the relative chunk and app starts working.

But if the internet speed is low, the relative chunk takes some time to be served and user clicks multiple times on the app icon

By doing so URL kept growing and appending the same route with each click.
```
printGridView(appsArray) {
    return appsArray.map(app => {
      return (
        <div className="app-drawer-icon" key={app.name}>
          <Link to={`app/${app.routes.path}`} >
            <IconComponent
              name={app.icons.name}
              shadow={'20px'}
              text={app.name} textColor="white"
              backgroundColors={app.icons.backgroundColors}
              png={app.png}
              size='120px'
            />
          </Link>
        </div>
      );
    });
  }
```
This function prints the Grid of applications.

Should I disable the click event in **IconComponent** and use` browerHistory.push` instead of `Link` and re enable it after sometime or there can be another better solution?

## Version
3.0.0

**Comment by timdorr** [comment]
You cant use a relative link. It must be absolute.
