### ISSUE TITLE
react-router-redux - no re-render after dispatching push

### ISSUE THREAD

**Issue by ap0yuv** [ReactTraining/react-router#5339]
## Version
"react-router-dom": "4.1.1"
"react-router-redux": "5.0.0-alpha.6"

## Description
I'm trying to integrate the newest Version of react-router & react-router-redux into a n example application from a react-book . But i can't get the example working with routing over react-router-redux push/replace function.
I'm not certain if its a bug or i'm using the functions wrong.

**actions/index.js**

    ...
    export function dismissVote(history) {
       // this changes the history locations and application re-renders
      //return () => history.push('/votes');
      
      // this changes the history locations but application doesnt re-render
      return dispatch => dispatch(push('/votes'))
    }
    ...

# App Repository (clone from github)
https://github.com/ap0yuv/voteapp.git

# How to reproduce my issue
- clone the repo. 
- cd ./myapp
- npm run start:hot && npm start
- Launch Application in Browser @ localhost:3000/votes/vote_1
- Click Button "Vote later"

## Expected Behavior
Browser Location is changed to localhost:3000/votes
AND
The List of all votes (localhost:3000/votes) is visible (VotePage.js)

## Actual Behavior
Browser Location is changed to localhost:3000/votes
AND
Page of Current Vote (vote_1) is still shown (SingleVotePage.js)

If i pass the history object to the function to route, the proper page is rendered.

More Information about the code:
src/common/containers/SingleVotePage is the entry point for /votes/vote_1
and passes dismissVote() from src/actions to <VotingComponent>

**Comment by timdorr** [comment]
See this guide: https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/guides/redux.md
