### ISSUE TITLE
React router component syntax isn't react-like / alternate design proposal

### ISSUE THREAD

**Issue by ChuckIrvine** [ReactTraining/react-router#5341]
I have react prototype that I've been working on for a while now and recently started to integrate it with react router. My requirement is that I need to be able let users create bookmarks to "pages" in my application.

To me the way that a routed-to component is specified seems un-react-like:

` <Route path="/dashboard" component={Dashboard}/>`

The first practical problem is that almost all of my react component take prop inputs and the react router "component" syntax about doesn't allow this. 

To me, an elegant alternate design would be:

```
<Route path="/dashboard">
   <Dashboard foo="foo" bar="bar"/>
</Route>
```

Thoughts?

**Comment by mjackson** [comment]
Thanks for stopping by, @ChuckIrvine. We actually do support the syntax you show here (try it!), though I wouldn't recommend it. Essentially, you're going to end up creating a bunch of elements that you will probably never actually render.

For example, what if the URL isn't `/dashboard`? In that case, you've now created a `<Dashboard>` element that is just going to be thrown away. Using the `<Route component>` prop lets us defer the decision of whether or not to actually create an element until we know if the URL matches the `<Route path>`.
