### ISSUE TITLE
React-router v4 eccentricity when using react-redux to update state and ui in lazy-loading component

### ISSUE THREAD

**Issue by hopperhuang** [ReactTraining/react-router#5349]
## Version
4.1.1

## Test Case
you can see my Scaffolding here:  https://github.com/hopperhuang/react-antd-Scaffolding/tree/dynamic-code
```
npm install
npm start 
```
then go into the /Bike/RedBike
you can see the test case.

## Steps to reproduce

I wanna optimize my apps with lazy-loading strategy.
So that  I watch the recomandation document and write a bundle.js  component like the document say.
u can see document in here:   https://reacttraining.com/react-router/web/guides/code-splitting

here is my bundle.js 
```
import React, { Component } from 'react';

// 首次加载，触发componentWillMount方法。
// 触发load方法。
// setState， 因为再componentWillMount方法内，所以不用re-render
// 发送异步加载组件的请求
// 首次render
// 异步请求成功，setState
// 触发re-render,加载异步组件。
//
// 若果再次点击进入同样的路由， 触发路由组件的componentWillReceiveProps方法。
// 判断load属性是否与之前的load属性一样，是的则不触发Load方法进行更新。
//
// 总结：从新进入同一个路由，会触发路由组件的componentWillReceiveProps方法。并re-render。
//
// 若果路由组件的状态进行更新，路由内部组件出现re-render，则视为重新加载组件，触发componentWillReceiveProps等首次加载方法。
// 如果重新点击进入子路由，则触发上级路由的componentWillReceiveProps方法，子路由组件重新加载。
//
// componentWillReceiveProps方法被触发，是因为props里面的路由属性改变所引起的。
// 这个组件内的componentWillReceiveProps方法的促发，因为，它被withRouter方法包裹了一层，包含了路由的相关属性。
//
// 路游级组件的变化，通常会由路由相关属性的变化引起。特别时url的变化，会到只props滨化，引起re-render。子路由的路由属性变化，会引起上级
// 路由属性的变化。

// 很重要的一点！！！
// 如果动态加载的组件产生变化，产生re-render，则引入这个组件的组件会重新加载，不会视为重新进入路由
// 所以，需要动态加载组件的上级组件，加载数据的动作，需要再路由促发，histroy.listen，否则，每次内部动态组件变化。
// 加载数据的动作就发生，页面被重置。


class Bundle extends Component {
  constructor(props) {
    super(props);
    this.state = {
      mod: null,
    };
  }
  componentWillMount() {
    console.log('willmount');
    this.load(this.props);
  }
  componentWillReceiveProps(nextProps) {
    // console.log('recieveprops');
    // console.log(nextProps.load !== this.props.load);
    if (nextProps.load !== this.props.load) {
      this.load(nextProps);
    }
  }
  load(props) {
    // console.log('load');
    this.setState({
      mod: null,
    });
    props.load((mod) => {
      this.setState({
        mod: mod.default ? mod.default : mod,
      });
    });
  }
  render() {
    // console.log(this.state.mod);
    return this.state.mod ? this.props.children(this.state.mod) : null;
  }
}

function MakeAsyncComponent(bundleLoaderComponent) {
  return function AsyncComponent() {
    return (
      <Bundle load={bundleLoaderComponent}>
        {Asyncmodule => <Asyncmodule />}
      </Bundle>
    );
  };
}


export default MakeAsyncComponent;
```

after finish this , i use bundle.js to make a lazy-loading component to optimize my apps 

here is my test apps than has import lazy-loding component

```
import React from 'react';
import { connect } from 'react-redux';
import PropTypes from 'prop-types';
import { Button } from 'antd';
import { withRouter } from 'react-router-dom';

class RedBike extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      number: 1,
    };
    this.addNumber = this.addNumber.bind(this);
  }
  addNumber() {
    let { number } = this.state;
    number += 1;
    this.setState({ number });
  }
  render() {
    const { dispatch, bike } = this.props;
    return (
      <div>
        <h1>this is red Bike</h1>
        <Button onClick={() => dispatch({ type: 'bike-addNumber' })}>Click me add numbers</Button>
        <div className="red_bike_number">
          { bike.number }
        </div>
        <div>
          stateNumber: {this.state.number}
          <Button onClick={this.addNumber}>addNumber</Button>
        </div>
      </div>
    );
  }
}

// const RedBike = function RedBike(props) {
//   const { dispatch, bike } = props;
//   return (
//     <div>
//       <h1>this is red Bike</h1>
//       <Button onClick={() => dispatch({ type: 'bike-addNumber' })}>Click me add numbers</Button>
//       <div className="red_bike_number">
//         { bike.number }
//       </div>
//     </div>
//   );
// };

RedBike.propTypes = {
  dispatch: PropTypes.func.isRequired,
};

const RedBikeContainer = withRouter(connect(state => ({ bike: state.bike }))(RedBike));
export default RedBikeContainer;
```

## Expected Behavior

when you clikck button 'Click me add numbers' , it will use redux-saga to change the state ,so i will call
a re-render  instead of a re-loading.

## Actual Behavior
when you clikck button 'Click me add numbers' , it will use redux-saga to change the state, but this change will call a re-loading . u can see the logs in the explorer, when u click 'Click me add number' button the string 'willmout' will appear in the logger. That meas it lead to a re-loading which cause the componentWillRecieveProps function run again and again.

I am concerned about another strange behavior, when u update the ui and state in the lazy-loading component with setState function, i will cause a re-render but not a re-loading.

Is it a bug? Or can u tell me what's principle about this strange behavior? Thank you!!

**Comment by pshrmn** [comment]
The way that you have defined these components, you are creating a new function on every render, which is what is causing your application to unmount/remount the components.
```js
<Route path="/Bike" component={MakeAsyncComponent(Bike)} />
<Route path="/Car" component={MakeAsyncComponent(Car)} />
<Route path="/World" component={MakeAsyncComponent(World)} />
```
Basically, the way you call `MakeAsyncComponent(XX)` inline means that `MakeAsyncComponent(XX)` will be called on every render. This will return a new function each time. React will unmount the existing component and replace it with the new one. You should instead create the async components above your `<Hello>` component.
```js
const AsyncBike = MakeAsyncComponent(Bike)
...
<Route path="/Bike" component={AsyncBike} />
```
For reference in the future, usage questions should be posted on StackOverflow or Reactiflux. I personally would recommend Reactiflux (it is a Discord chat group full of people that use React).

**Comment by hopperhuang** [comment]
@pshrmn  oh, i see. thanks for your answer!!   i am very appreciated it!!
