### ISSUE TITLE
Warning: BackAndroid is deprecated.  Please use BackHandler instead.

### ISSUE THREAD

**Issue by LengYXin** [ReactTraining/react-router#5353]
"react-native": "0.46.1",
    "react-router-native": "^4.1.1"

Use AndroidBackButton  react-native Warning: BackAndroid is deprecated.  Please use BackHandler instead.

**Comment by pshrmn** [comment]
Fixed in #5093 (but there hasn't been a release since that was merged).

**Comment by SuhairZain** [comment]
@pshrmn Any idea why react-router-native is still at 4.1.1 without this fix, when react-router is already at 4.1.2?
