### ISSUE TITLE
TypeError: Cannot read property 'location' of undefined

### ISSUE THREAD

**Issue by ifree92** [ReactTraining/react-router#5365]
Clean project. Here I see this exception:

![screenshot](http://i.piccy.info/i9/e00030f241ba52e1c16fe86f397bc4f6/1500715109/372475/1164055/Snymok_ekrana_2017_07_22_v_12_17_49.png)

Versions:

```json
 "dependencies": {
    "react": "^15.6.1",
    "react-dom": "^15.6.1",
    "react-router": "^4.1.2",
    "react-scripts": "1.0.10"
  }
```

**Comment by timdorr** [comment]
If you're using the Router from react-router (not a BrowserRouter or HashRouter from react-router-dom), you need to configure it with a history instance.

**Comment by paolavness** [comment]
@timdorr  I wonder if you can help... I'm using BrowserHistory and when wrapping in withRouter get the same error. Any  ideas?

**Comment by mreorhan** [comment]
You can try in import: {BrowserRouter as Router}
