### ISSUE TITLE
Switch component does not take style and other props

### ISSUE THREAD

**Issue by episodeyang** [ReactTraining/react-router#5366]
## Version
4.1.1

## Test Case
```jsx
<Switch style={{backgroundColor: 'red'}} className="does-not-work-either">
some text
</Switch>
```

this generates the html:
```html
<div>
some text
</div>
```

The div does not have any style associated with it 😱 

## Expected Behavior

I expect the styles to be respected, because this should be a higher order component.

## Actual Behavior

doesn't work.

**Comment by episodeyang** [comment]
Closing because it was my own mistake.

**Comment by MuneebJS** [comment]
What was your problem can you please elaborate it as I've got the same problem with my Switch.
