### ISSUE TITLE
usage of compose with new API

### ISSUE THREAD

**Issue by snggeng** [ReactTraining/react-router#5371]
## Version
Latest

## Steps to reproduce
Migrating to react-router v4 and tried this implementation of using redux. Ran into bugs running 
```
import thunk from 'redux-thunk'
import { Provider } from 'react-redux'
import createHistory from 'history/createBrowserHistory'
import { createStore, applyMiddleware, combineReducers, compose } from 'redux'
import { ConnectedRouter, routerReducer, routerMiddleware } from 'react-router-redux'
// ... other dependencies

// ...
// Add the reducer to your store on the `router` key
// Also apply our middleware for navigating
const store = createStore(
  combineReducers({
    ...reducers,
    router: routerReducer
  }),
  applyMiddleware(middleware, thunk)
)
```

Got the error `Actions must be plain objects. Use custom middleware for async actions.` suggesting that my middleware was not properly connected.
## Fix
Imported `compose` from `redux`
```
import { createStore, applyMiddleware, combineReducers, compose } from 'redux' and it worked
// ... other dependencies 

// ...
const store = createStore(
  combineReducers({
    ...users,
    router: routerReducer
  }),
  compose(
  applyMiddleware(middleware, thunk),
  window.devToolsExtension ? window.devToolsExtension() : (f) => f
  )
)
```

## Is this a bug?
Am I using the new version of `react-router-redux` wrongly or is this a bug? Am I expected to use `compose()` to handle middleware, and if so, it should be added into the readme.md

**Comment by timdorr** [comment]
This isn't a bug with the library. I would suggest reading more of the docs on how compose should be used.
