### ISSUE TITLE
Safari, iOS, v9, Prompt not transitioning on ok.

### ISSUE THREAD

**Issue by GoldenRust** [ReactTraining/react-router#5373]
Tested in Browserstack on ios, v9, safari, iphone 6s.

## Test Case
https://reacttraining.com/react-router/web/example/preventing-transitions

## Steps to reproduce
- Open [example](https://reacttraining.com/react-router/web/example/preventing-transitions) in safari on ios
- Enter anything into input 
- Click on one or two 
- Click ok

## Expected Behavior
Transition to linked page (`/one` or `/two`).

## Actual Behavior
Acts as if you click cancel.

### notes
It's been mentioned in another issue that this is an issue with history, but I followed the linked issue and it was dismissed since history doesn't use `beforeunload` and the original issue mentioned that. I'm not sure if the prompt component uses this or not.

I'm not sure if this issue is being looked on history's side, or if it even is an issue, and there's a different way to do this?

[history issue #406](https://github.com/ReactTraining/history/issues/406)
#4267
#4372

**Comment by timdorr** [comment]
This is an issue for history to solve. Unfortunately, I don't think it's possible given how iOS9 implements beforeunload stuff.
