### ISSUE TITLE
hashHistory.goback will cause componentDidMount of last component

### ISSUE THREAD

**Issue by leonardgithub** [ReactTraining/react-router#5375]
## Version
    "react": "15.5.4",
    "react-dom": "15.5.4",
    "react-router": "3.0.5",
    "react-router-redux": "4.0.8",

## Test Case
N/A

## Steps to reproduce
1. at component A
2. replace to component B by hashHistory.replace, for example, hashHistory.replace("/B")
3. call hashHistory.goBack()
4. componentDidMount of B is invoked

## Expected Behavior
componentDidMount of B will not be invoked

## Actual Behavior
componentDidMount of B is invoked

**Comment by timdorr** [comment]
HashHistory has all sorts of problems: https://github.com/ReactTraining/history/issues/427

This is ultimately a history bug if it's not going back to a state before a replace. Not much we can do here.

**Comment by leonardgithub** [comment]
@timdorr So, it seems it is fixed in v4? Thanks

**Comment by timdorr** [comment]
Possibly. history 4.0 is a rewrite, so it may not suffer from this issue. But I generally suggest against using hash histories, so I'm not sure if it would be.
