### ISSUE TITLE
Pass current props to NavLink.props.isActive()

### ISSUE THREAD

**Issue by joefraley** [ReactTraining/react-router#5376]
## Description of Problem

In my app I have some navigation UI that looks like this:
![](https://www.evernote.com/l/Ae-Gj_3_qmFL8qj65puhoNKhe5j966RPkGsB/image.png)

There are routes something like this:

```
# Examples of routes
/locations
/location/{id}
/organizations
/organization/{id}
/users
/users/{id}
etc...
```

I would like for these globally visible links to appear active both at the route that literally matches their given link, but _also_ at the route representing the singular entity of the corresponding kind.

For example, "Location" is active both at `/locations` and at `/location/{id}`

## Desired API

This would be trivially implemented by giving the `isActive` function access to the other NavLink props. Then, `isActive` could test against the `to` prop, or anything else aribitrarily.

For example:

```javascript
<NavLink to="/location" isActive={(match,location,{to}) => location.pathname.includes(to))}
```

It's impossible to generalize this idea without access to the props, since the necessary information with which to generalize is `NavLink.props.to`.

## Example of Problem
For example, in order to implement this with the existing API, you must manually specify the regex in every NavLink:

```javascript
// notice that this isActive function can't be written just once for all of these cases
<NavLink to="/locations" isActive={(match,location) => /location/.test(location.pathname)}
<NavLink to="/organizations" isActive={(match,location) => /organization/.test(location.pathname)}
<NavLink to="/users" isActive={(match,location) => /user/.test(location.pathname)}
```

## Actionable Idea

It looks like an easy PR that would not break any existing behavior. What are your thoughts?

[In the NavLink component](https://github.com/ReactTraining/react-router/blob/89093a4e09c430b5c32bfb6b86de66cffd9b97ec/packages/react-router-dom/modules/NavLink.js#L28) you can see that isActive receives `match`, and `location`.

```javascript
      const isActive = !!(getIsActive ? getIsActive(match, location) : match) <----

      return (
        <Link
          to={to}
          className={isActive ? [ className, activeClassName ].filter(i => i).join(' ') : className}
          style={isActive ? { ...style, ...activeStyle } : style}
          aria-current={isActive && ariaCurrent}
          {...rest}
        />
```

I'm imagining the change looks like this:

```javascript
      const isActive = !!(getIsActive ? getIsActive(match, location, props) : match)
```

**Comment by joefraley** [comment]
@timdorr I see you closed this issue almost instantly. Is that because this has come up before?

**Comment by eriklharper** [comment]
+1 for this feature, seems very light touch and potentially useful.  A simpler implementation that is even more of a light touch is to just pass the `to` prop as a third parameter to `isActive`.

**Comment by timdorr** [comment]
You had no content in this issue when you opened it.

**Comment by timdorr** [comment]
This will probably get pushback because you can do this yourself already:
```js
export const LooseNavLink = props => (
  <NavLink {...props} isActive={(match, location) => location.pathname.startsWith(props.to.pathname)}/>
)
```
In general, the consensus is to avoid adding things to the APIs if they are already possible without too much difficulty. We're trying not to grow the API surface, because it's very hard to roll back changes and it makes future improvements harder to do. 

I know this is just one arg on one prop on one component, but it's meant as a philosophy for development so that we don't suffer a death by a thousand cuts. Same thing happened with v1-v3, so we want to avoid that.

**Comment by pshrmn** [comment]
For reference, this PR was about essentially the same feature and was it ultimately decided against implementing it #4499

**Comment by joefraley** [comment]
@pshrmn one difference is that I only want to write `isActive` once for all of my navigation. That's only possible if I can access what's different among NavLinks from inside `isActive` (props). the solution described it #4499 still forces you to repeat input individually for each case:

```javascript
const isActive = to => (match,location) => location.pathname.includes(to))
<NavLink to="/users" isActive={isActive('user')} // still have to repeat the 'user' info every time
<NavLink to="/location" isActive={isActive('location')}
```

@timdorr's higher order solution is the only way to accomplish my aim, and it's reasonable. There happens to be a high impedance to writing HoC's in my codebase, but I appreciate that's not true for everyone.

@timdorr if `isActive` takes all props, it's a broad stroke that allows many arbitrary possibilities for determining active state. that feels high value and low impact, but maybe I'm underestimating the experience you had with earlier iterations of react-router.

**Comment by VladShcherbin** [comment]
@joefraley if your navigation urls will be `/users`, `/users/:id`, NavLink will have active state on both of them. Maybe it's easier to change urls?

**Comment by timdorr** [comment]
I think this is a pretty succinct answer: https://github.com/ReactTraining/react-router/pull/4499#issuecomment-284970451 So, I think we're definitely not going to implement this ourselves.

**Comment by joefraley** [comment]
@timdorr well it's your project, but the answer linked there has the cost described above. any such function must be refined individually for each NavLink by hand, because the isActive function does not receive the information it needs to be written once generally.

@VladShcherbin that is the desired behavior in this case. `/user(s)/anything/no/matter/what` should appear active.

**Comment by dovidweisz** [comment]
@timdorr : This is why I would prefer of you implemented this change:

https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-no-bind.md

> A `bind` call or arrow function in a JSX prop will create a brand new function on every single render. This is bad for performance, as it will result in the garbage collector being invoked way more than is necessary. It may also cause unnecessary re-renders if a brand new function is passed as a prop to a component that uses reference equality check on the prop to determine if it should update.
