### ISSUE TITLE
Reloading a Route based on change to params

### ISSUE THREAD

**Issue by dustwise** [ReactTraining/react-router#5380]
After extensive mulling through previous posts, what is the general consensus to this problem?

**Simple case:** I'm on /products/123 (:id) and I have a link that goes to /products/456 on the same route. My componentWillMount is responsible for an async action that displays a loading component until data is retrieved, using the route param to get the required data. The component is not remounted upon param change, hence no update takes place.

I've seen a bevy of thoughts, from custom HOC, forceRender, withRouter, componentWillReceiveProps and so forth. The only thing that seems consistent is that this is a desired functionality with no clear solution.

componentWillReceiveProps fires multiple times and unreliably and the other solutions don't work in all instances/situations or aren't clear enough in their workings to be agreed upon as a standard plan of attack.

Succinctly: If I wanted to run something once, upon a parameter change, how?

Where are we on this?

**Comment by timdorr** [comment]
componentWillReceiveProps doesn't fire multiple times unless you are changing multiple props. Be sure to check nextProps to ensure you actually need to do an update for a props change.
