### ISSUE TITLE
optional path parameters

### ISSUE THREAD

**Issue by theboyWhoCriedWoolf** [ReactTraining/react-router#5384]
Hello,

I have updated to React Router 4 and seem to be having an issue with the original paths for my routes.

I am trying to create a path that works for a few possibilities with optional path components. I was able to do this previously with `/(*/*/)` which would be my root path. It would work for both:
```
/
/optionalpath/optionalPath2/
```

Now however there seems to be an issue trying to get this to work.
I need a way to cater the following routes, where it will work if the optional values are present or not:
```
/ - root
/details
/optionalpath/optionalPath2/ - root
/optionalpath/optionalPath2/details
```

Thanks in advance.

**Comment by pshrmn** [comment]
React Router v4 uses [`path-to-regexp`](https://github.com/pillarjs/path-to-regexp) for pattern matching. We only allow patterns as strings, but you can check out the documentation there to see all of the valid syntax (such as [optional params](https://github.com/pillarjs/path-to-regexp#optional)).

You can also use this little app I wrote to test routes https://pshrmn.github.io/route-tester/#/
