### ISSUE TITLE
React 16 Support for React-Router 2

### ISSUE THREAD

**Issue by ncphillips** [ReactTraining/react-router#5385]
Our app is still using RR2. Upgrading to RR4 is pretty low priority for us right now, because the process is non-trivial and we are not experiencing any major issues by using RR2.

That said, React 16 will be coming out in the next couple months, and RR2 is currently using deprecated features of React, namely `createClass` and `prop-types`.

Is there any maintenance of RR2 ongoing? Will these deprecations be dealt with or should I fork the last v2?

**Comment by timdorr** [comment]
You should be on v3. It is the same thing as v2 with the deprecation warnings removed. We have already fixed the React deprecations on that version (3.0.4, specifically).

**Comment by timdorr** [comment]
That being said, I am curious to know if 16 has any issues with the latest v3 release. We're not using an private APIs, but it could be dependent on behaviors that have changed.

**Comment by ncphillips** [comment]
Ah I was not aware that v3 was compatible with v2, thanks!
