### ISSUE TITLE
'react-router' does not contain an export named 'IndexRedirect'.

### ISSUE THREAD

**Issue by elghali** [ReactTraining/react-router#5388]
## Version
4.1.1

## Steps to reproduce
`import { IndexRedirect } from 'react-router';`
`<HashRouter>
    <Route path="/" component={HomePage}>
      <IndexRedirect to="home" />
      <Route path="home" name="home page" component={Home} />
    </Route>
    <Route path="admin" component={AdminPage}>
      <IndexRedirect to="home" />
      <Route path="login" name="login page" component={Login} />
    </Route>
  </HashRouter>`
## Expected Behavior
works
## Actual Behavior
doesn't work:
'react-router' does not contain an export named 'IndexRedirect'.

**Comment by pshrmn** [comment]
You are using the old API. `<Index___>` components do not exist in v4. Check out the documentation to learn the new API https://reacttraining.com/react-router/
