### ISSUE TITLE
Support for children prop in ConnectedRouter

### ISSUE THREAD

**Issue by alexgvozden** [ReactTraining/react-router#5395]
I will still post here even though is not an issue maybe but a limitation,
however I would expect it to work

While

```
<Router history={browserHistory} children={this.props.routes} /> 
```

is supported in React router v4,using react-router-redux ConnectedRouter does not support it

for example

```
<ConnectedRouter history={this.props.history} children={this.props.routes} /> 
```

is there a way to pass routes as children prop, since this is easy way to build routes with objects

Thanks

**Comment by alexgvozden** [comment]
interestingly react-router provides opposite conversion

from React components to route object and they use it like that

```
import { Route, createRoutesFromReactChildren } from 'react-router'
 
    const routes = createRoutesFromReactChildren(
      <Route component={App}>
       <Route path="home" component={Dashboard}/>
        <Route path="news" component={NewsFeed}/>
      </Route>
    )
```

so I need opposite of this to run react-router-redux (instead of you just passing it or me modifying your code :) )

**Comment by timdorr** [comment]
[We pass in the props for ConnectedRouter, including children, directly into a Router.](https://github.com/ReactTraining/react-router/blob/master/packages/react-router-redux/modules/ConnectedRouter.js#L41). Also, the example on the Readme shows using children to the ConnectedRouter (as nested JSX, instead of a children prop, but it's the same thing).

**Comment by alexgvozden** [comment]
sorry but Router from react-router does not expect children to be type node only

if you look at the source code of Router from react-router you will see it is using both node and object for children
react-router actually provides opposite function createRoutesFromReactChildren that converts routes you supply as React components to object or just accepts the object

you can import this easily from import { createRoutesFromReactChildren } from 'react-router' :) 

so Router from react-router actually works not only with type node but with type object
it would be good if we could just pass this object, I will try modifying your code to support it but this could be included in your library for sure as it's default behaviour

**Comment by timdorr** [comment]
I'm very confused. Are you using react-router 3.0 with react-router-redux 5.0? Those versions are not compatible. `createRoutesFromReactChildren`is a v2/3 API.

**Comment by alexgvozden** [comment]
yes, you are right, I though it was v4... my bad, really sorry!!!
