### ISSUE TITLE
Redux: ConnectedRouter doesn't update when redux state changes, only when history object changes

### ISSUE THREAD

**Issue by alexrussell** [ReactTraining/react-router#5397]
## Version

- `react@15.6.1`
- `react-dom@15.6.1`
- `react-redux@5.0.5`
- `react-router@4.1.2`
- `react-router-dom@4.1.2`
- `react-router-redux@5.0.0-alpha.6`
- `history@4.6.3`

## Test Case

https://codesandbox.io/s/2RqOzqJrA

## Steps to reproduce

Click on a link or use forward/back buttons (after clicking around a bit).

## Expected Behavior

- Address bar should change as the history has been pushed
- Redux store should show a `@@router/LOCATION_CHANGE` action
- Content should update

## Actual Behavior

- Address bar updates
- Redux store shows change
- Content does not update

---

If you "reload" the page on a given URL the router works correctly. But clicking a link does not work. Nor do the back and forward buttons. (It's also worth pointing out that the behaviour happens when using `<Link />` components too as far as I can tell.)

Looking into it, the redux middleware is correctly doing its job. It takes `@@router/CALL_HISTORY_METHOD` actions and swallows them, instead telling the `history` object to do a `push`/`go`, etc.. This in turn will tell the `ConnectedRouter` subscriber about the location update, which itself fires off a `@@router/LOCATION_CHANGE` action. This is picked yup by the reducer and the store's state is updated.

What doesn't happen, however, is the `ConnectedRouter` actually updating its own internal state from its props (provided by the store). This means that:

1. Using `push` to alter the redux state won't update the actual router instance's idea of the location
2. Using the back buttons also won't (as they trigger on the `history` object which tells the `ConnectedRouter` which fires off the location change action which updates the redux state, but then this state is never 'read' by the `ConnectedRouter`.

So, is it something I'm doing wrong (maybe I have the wrong idea about how it's supposed to work), or is something missing that hooks up the actual redux store to sending artificial navigation events to the history, or whatever it's supposed to do?

**Comment by alexrussell** [comment]
Ahh just realised what's going on. It's because my top level "app" is a redux container, so doesn't pas the router context down to the `Route` components. Man, why do you always get the answer 2 mins after posting the issue?

**Comment by drodriguez56** [comment]
@alexrussell I have the same issue, can you please elaborate more on how you fixed it? thanks.

**Comment by alexrussell** [comment]
@drodriguez56 because my main component `App` is a redux container, it doesn't update/re-render until the props it cares about change, so its child components (i.e. the `<Route>`s within) won't actually update unless a property that the redux container itself cares about changes (i.e. the state as it comes out of `mapStateToProps`). To fix this you just need to wrap the `connect` call in yet another HOC `withRouter` from RR:

    App = withRouter(connect(null, {push})(App));

See [here](https://codesandbox.io/s/48w71y4r30) for the exact same pen from my original post but with the fix.
