### ISSUE TITLE
Redux: Not compatible with "time travelling"

### ISSUE THREAD

**Issue by alexrussell** [ReactTraining/react-router#5399]
## Version

- `react-router@4.1.2`
- `react-router-redux@5.0.5`

## Description of issue

Because of the way that the redux implementation works, time-travelling using redux does not work. The redux router relies on dispatching of `@@router/CALL_HISTORY_METHOD` which happens when you dispatch a react-router-redux `push` or `replace` action. This action is then swallowed by the middleware and turned into a `push`, `replace`, etc. call on the `history` instance, which in turn tells the `ConnectedRouter` subscriber that there's been a change, which then dispatches a `@@router/LOCATION_CHANGE` action which passes through the middleware unscathed and reduces into a state change using the react-router-redux reducer.

The problem is, dispatching `@@router/LOCATION_CHANGE` action alone won't do anything (except update the redux state) - the actual mechanics of the router remain unchanged, and rely heavily on the `history` instance. As such, using redux's "time travelling" ability (i.e. replacing the state) won't actually update the router's state.

The only way I can think to fix this is to invert the control: instead of dispatching `@@router/CALL_HISTORY_METHOD` in order to tell `history` to tell `ConnectedRouter` to dispatch `@@router/LOCATION_CHANGE` to update the state, we should simply update the state directly using `@@router/LOCATION_CHANGE`. When `ConnectedRouter` detects this change (using `componentWillReceieveProps` with a comparison of `reduxstate.router.key` I'd imagine) it should then tell the `history` instance about the update. That is to say, history shouldn't tell `ConnectedRouter` "this just happened" but instead `ConnectedRouter` should have the control and tell `history` to "go and do this". The issue here comes with something that is only controlled by `history`: browser back/forwards. We need some way to hook into these alone so we can update the redux state without then triggering `ConnectedRouter` to tell history to go and update (as the update came _from_ `history` in this one case).

So maybe the fix for this is to go back to having two separate actions (like we currently do), one for a simple "tell the state to update to X" and one for "kick off a history change". The difference being that the current "location change" action should be the one that kicks off the history change. Maybe I haven't thought about this thoroughly though.

**Comment by timdorr** [comment]
Already in progress in #4717

**Comment by alexrussell** [comment]
My bad, sorry about that.
