### ISSUE TITLE
Route's location is one step behind history if the routes are wrapped in redux's connect

### ISSUE THREAD

**Issue by Misiur** [ReactTraining/react-router#5401]
## Version
└─ react-router-redux@5.0.0-alpha.6

## Test Case
https://codesandbox.io/s/v88B5LG0
https://github.com/Misiur/ReactRouterReduxBug

## Steps to reproduce
1. Click few of the `<Link>`s
2. Click browser's back and forward a few times

## Expected Behavior
Normal history traversal
![Imgur](http://i.imgur.com/FUklYZx.gif)
## Actual Behavior
Route's prop location is one step behind the history
![Imgur](http://i.imgur.com/tOD8Lt1.gif)

**Comment by timdorr** [comment]
See this guide: https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/guides/redux.md

**Comment by Misiur** [comment]
Thank you

**Comment by alexrussell** [comment]
@Misiur specifically, you just need to wrap your routing-aware connected containers with `withRouter`: https://codesandbox.io/s/nZQ24Q9KY
