### ISSUE TITLE
Link adds leading slash (/) if rendered from node, and excludes the slash if rendered on client

### ISSUE THREAD

**Issue by scazzy** [ReactTraining/react-router#5406]
BUG: 

## Version
react: 15.6.1
react-router-dom: 4.1.1

## Steps to reproduce
1. Use `Link` component with a `to` attribute without the leading slash
eg: <Link to="category/hello-world">World</Link>
2. Render it from server using `node` or `babel-node`. Check the rendered component
3. Render on client (browser). Check the rendered component

## Expected Behavior
`<a href="/category/hello-world">World</a>`

## Actual Behavior
**Server:**
`<a href="/category/hello-world">World</a>`
**Client:** 
`<a href="category/hello-world">World</a>`

**Comment by timdorr** [comment]
You have to use absolute URLs for your Link's to prop. You cannot use relative URLs.

**Comment by scazzy** [comment]
@timdorr it's not a mandate to use absolute URLs. The relative URLs work fine (and should). The problem mentioned above is that it outputs different results when compiled for server and bundled for client

**Comment by timdorr** [comment]
Yes, it is. We don't support relative URLs in React Router.
