### ISSUE TITLE
react-router and surge.sh

### ISSUE THREAD

**Issue by erezLieberman** [ReactTraining/react-router#5410]
created react js app with react-router and deployed it to production with surge.sh

http://music-theory-tools.com/

when you click on one of the links that go well to the right root but if you try to go directly to one of the routes' for example:

http://music-theory-tools.com/chord-finder you got 404 page.

that does not happen on the local environment.

when I searched about this issue I found this post, I tried to change the index.html to 200.html as explained but that makes every page on the website a blank white page...

**Comment by pshrmn** [comment]
https://github.com/ReactTraining/react-router/blob/master/FAQ.md#why-doesnt-my-application-render-after-refreshing
