### ISSUE TITLE
Regarding the priority of 'exact' attribute

### ISSUE THREAD

**Issue by SantanMaddi** [ReactTraining/react-router#5412]
Team,
I would like to document a few details regarding the attribute 'exact'. 

```
<Router>
  <Route exact path="/" component={App} />
</Router>

App.js
<div>
  <Route exact path="/" component={ComponentA}/>
  <Route exact path="/b/:id" component={ComponentB}>
</div>
```
In this code, ComponentB will never get rendered even when I try to access the path _/b/1_. 

However, if I change my code to below. ComponentB is getting rendered at path _/b/1_.
```
<Router>
  <Route path="/" component={App} />
</Router>

App.js
<div>
  <Route exact path="/" component={ComponentA}/>
  <Route exact path="/b/:id" component={ComponentB}>
</div>
```
I would like to understand whether this is the desired behaviour. Could someone please explain on this.

**Comment by timdorr** [comment]
`exact` simply requires that the full pathname exactly matches the `path` given. If you want to have this sort of Route hierarchy, then using `exact` on your top level Route is probably not correct.
