### ISSUE TITLE
How do I exclude a path from a route path?

### ISSUE THREAD

**Issue by Dindaleon** [ReactTraining/react-router#5414]
Hello,

I am trying to exclude a path from a route.

This is my route:
`{ path: '*', component: NotFound, status: 404 }`

I would like to exclude the path `/assets` How could I do that?

I am using react-router version 3.0.0-alpha.1

**Comment by pshrmn** [comment]
Based on the `/assets` name, I assume that you mean on a server, in which case you should have a different request handler for your static assets. If you're using express, that would be something like this:

```js
const app = express();
app.use("/assets", express.static(__dirname + "/assets/"));
app.get('*', function(req, resp) {
  // do the react router request matching here
});
```
If you don't mean on the server, then the only way to ensure that the wildcard matches is to have a route whose path is `/assets` that comes before your wildcard route.

Also, you should probably update to the latest version of v3 (currently `3.0.5`).
