### ISSUE TITLE
Redirect with react-router-4 not updating history

### ISSUE THREAD

**Issue by dagda1** [ReactTraining/react-router#5416]
I am using `react-router-dom`:
```
import { BrowserRouter as Router, Route } from 'react-router-dom';
```
```
  <Provider store={store}>
    <Router>
      <App>
        <Route path="/" exact component={Home} />
        <Route path="/application" component={Application} />
      </App>
    </Router>
  </Provider>,
  document.getElementById('root')
);
```

I am using `<Redirect />` to redirect but only when a form is in valid state:

```
    </div>
    {submitSucceeded && <Redirect to={nextLink} />}
```

But when I go to the next link and click back it goes back to the route of the site, i.e. the history is not being updated.

**Comment by timdorr** [comment]
See this guide: https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/guides/redux.md

**Comment by rafaelpivato** [comment]
You must use `<Redirect push={true} />` to force creating a new history entry, as it will replace otherwise.
