### ISSUE TITLE
Code Splitting Example Should Recommend react-loadable

### ISSUE THREAD

**Issue by knpwrs** [ReactTraining/react-router#5418]
I was following the [code splitting](https://reacttraining.com/react-router/web/guides/code-splitting) example and ran into the problem that props would not be passed properly to the proxy-loaded component. I tried a few things and didn't get it working, but then I went and tried it with [`react-loadable`](https://github.com/thejameskyle/react-loadable) and it worked out of the box, no fuss.

I can contribute documentation but I'm pretty much booked solid this week. This issue can serve as discussion, however.

**Comment by timdorr** [comment]
A better code splitting and data preloading example would be great. Docs changes are better discussed over PRs, so we can wait until that to pick this up.
