### ISSUE TITLE
Switch acting different between different node env.

### ISSUE THREAD

**Issue by CVarisco** [ReactTraining/react-router#5421]
Hi,

thanks a lot for the library 🙂
We found a very strange behavior between the development version and the production one.
We don't know why but with the production build when a redirect happens the entire tree under the switch component is re-rendered from scratch.
### NODE_ENV = development
![dev](https://user-images.githubusercontent.com/7335613/29087007-c5ff4b60-7c74-11e7-8585-2bf1b0fdd8e5.gif)

### NODE_ENV = production
![prod](https://user-images.githubusercontent.com/7335613/29087006-c5fd1cbe-7c74-11e7-84fc-f15a7460a8c1.gif)

We noticed that in the production env keys are generated every time the route changes.

Someone knows why this is happening and what may be causing it?

## Version
`"react-router-dom": "4.1.1"`
`"react": "15.5.4"`

**Comment by timdorr** [comment]
It could be a side effect of your minification process. Try removing that and re-bundling to see if it still happens.

Outside of that, I'm not sure what would be causing it. React disables a number of things in production mode, but they shouldn't be affecting behaviors like that.

I'm not convinced this is anything to do with React Router. I'll close this for now, but will re-open if it's proven to be our issue.

**Comment by CVarisco** [comment]
Hi @timdorr !
thanks for your support 😊

I tried with an un-minified version of bundle and vendors but the results it is the same.
I'm creating an issue on react to get more information about this problem.

Thanks again.
