### ISSUE TITLE
Webpack HMR does not work if navigated to nested path

### ISSUE THREAD

**Issue by lekhnath** [ReactTraining/react-router#5423]
## Version
4.1.2

## Steps to reproduce
```
<Switch>
<Router exact path="/one" component={One} />
<Router path="/one/two" component={OneTwo} />
<Router path="/or/whatever" component={WhatEver} />
</Switch>
```

## Expected Behavior
Should Hot Reload also in nested path like `/one/two` , `/or/whatever` not only in `/one `

## Actual Behavior
When I am navigated to path /one in browser and edit some component hot reloading just works fine.
BUT
When I an navigated to path /one/two HMR does not work, entire browser reloads

In above **Steps to reproduce** example if i change `/one/two` to be only one level depth say `/blah` then it works.

# Other Info
* Webpack 2
* React hot reload

**Comment by timdorr** [comment]
Unfortunately, this doesn't sound like a bug with how React Router does things. It's just plain React code. It is likely something in react-hot-loader, or just a limitation in how it works. I would seek support through whatever their appropriate channels are.
