### ISSUE TITLE
Route should implicitly run decodeURI on pathnames to match browserHistory behavior

### ISSUE THREAD

**Issue by Kovensky** [ReactTraining/react-router#5424]
## Version
4.1.1

## Test Case
https://codesandbox.io/s/26WgmOzM

As you can see, the third link (ふが) that has its `to` argument set with the result of a `decodeURI` call will correctly detect as `active`, but the second link, while it will correctly navigate, will never be detected as active. In both cases, the browser's native `location.pathname` will be URL encoded, but the Router's `history.location.pathname` will not be URL encoded.

The ultimate cause is that the `history` package always implicitly calls `decodeURI` on the `pathname`s it generates internally, so the extra URL encoding present on the  URLs that do not go through `decodeURI` prevent them from ever matching in `matchPath`. The offending line is https://github.com/ReactTraining/history/blob/8d98aec/modules/LocationUtils.js#L37.

This does not affect plain ASCII or latin-1/cp1252 URLs, but it affects any URL in a non-western-european language. `decodeURI` will preserve dangerous escapes (e.g. `%2f` for escaping a `/`) so it should be safe to always implicitly call it.

## Steps to reproduce
Use `encodeURIComponent` (or even a `path-to-regexp` compiled URL, which uses `encodeURIComponent` internally) to generate a URL that contains URL encoding, and use it as a `Route`'s `path` or `NavLink` `to` argument.

## Expected Behavior
A `NavLink` that points to a URL with an `encodeURIComponent` component to always match after it is clicked.

## Actual Behavior
A `NavLink` (or `Route`) that has any URI encoded characters beyond the minimum necessary will never match.

**Comment by pshrmn** [comment]
Location objects are expected to have non-encoded pathnames. I updated your sandbox to remove the `encodeURI`/`decodeURI` calls and it works fine without them: https://codesandbox.io/s/wLp37MpR

**Comment by Kovensky** [comment]
The problem is easier to occur in practice when untrusted input may be used for the path.

Perhaps it should be recommended in the docs to pass such paths to `decodeURI` then.

**Comment by pshrmn** [comment]
If you open up a PR that updates the `<NavLink>` documentation to mention that the pathname passed to `to` should not be encoded, I'm sure it would be appreciated.
