### ISSUE TITLE
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in

### ISSUE THREAD

**Issue by MMRATXS** [ReactTraining/react-router#5425]
Hello guys!

I am working with react-navigation and it has been working fine for me before,
but now when I have to include it in an app, it gives me this error.

the project works fine without the navigation feature, 

I tried changing this line
`import {StackNavigator} from 'react-navigation';`
to
`import StackNavigator from 'react-navigation';`

but then navigation doesnt work, giving the error

(0 , _reactNavigation2.default) is not a function

Any help is highly appreciated

Thanks

**Comment by pshrmn** [comment]
You opened this issue on the wrong router repo :smile:

**Comment by MMRATXS** [comment]
lol sorry
