### ISSUE TITLE
history.push with setTimeout gives an error

### ISSUE THREAD

**Issue by sAs59** [ReactTraining/react-router#5426]
The following error occurs when I use history.push(path) inside setTimeout and wrapped by CSSTransition.

<img width="1019" alt="screen shot 2017-08-11 at 01 16 18" src="https://user-images.githubusercontent.com/9218560/29187750-bd10c438-7e32-11e7-8fab-b96b01a24b5b.png">

An intersting part is that it happens only at first try and then works as normal.
This is my App component:
```javascript
const App = ({ location }) =>
  <TransitionGroup>
    <CSSTransition
      key={location.pathname}
      timeout={{ enter: 300, exit: 200 }}
      classNames="fade"
    >
      <Switch location={location}>
        <Route path="/home" component={Home} />
        <Route path="/menu" component={Menu} />
      </Switch>
    </CSSTransition>
  </TransitionGroup>;
```
And here is the link in **Home** component that redirects to **Menu** component:
```javascript
<div
  onClick={() => {
    setTimeout(() => {
      this.props.history.push(`/menu`);
    }, 700)
  }}
>
```

**Comment by timdorr** [comment]
I have no idea why that would occur, but it appears to be something unrelated to react router. It's showing the error is in the dom-helpers module.
