### ISSUE TITLE
react-router-config does not match on later paths even if there is an exact path match later

### ISSUE THREAD

**Issue by terencechow** [ReactTraining/react-router#5429]
## Version
4.1.1

## Test Case
None

## Steps to reproduce
Create a react-router-config that has the following: 
```
    [{ component: someAuthorizedLayout
        routes: [
            {component: AuthorizedDashboard, path: '/home, exact: true}
       ]
     },
     { component: UnauthorizedLayout
         routes: [
            {component: Login, path: '/', exact: true}
        ]
     }]
```

Try to go to '/' and you are unable to. Why? Because the route matches the first route and "consumes" the request before it realizes that there is a '/' exact match
## Expected Behavior

I expect it to go to the Login page.

## Actual Behavior

It goes to no route because it traverses the routes tree and when it hits someAuthorizedLayout it finds no nested routes that match. 

Is this a bug? or is this by design?

**Comment by timdorr** [comment]
This does appear to be a bug in rrc. We're not doing any [testing of that form of routes](https://github.com/ReactTraining/react-router/blob/master/packages/react-router-config/modules/__tests__/matchRoutes-test.js), so the first step would be to add a failing test. Then we can go about fixing for it.

**Comment by terencechow** [comment]
@timdorr `renderRoutes` uses `Switch` internally and on documentation it says `Switch` is supposed to match exclusively. 

If you are saying this is a bug, that means `renderRoutes` should not use Switch internally. Is that correct? Are there any requirements for `renderRoutes` to use `Switch` internally? I need this context before looking into possible solutions... If there is a requirement for `renderRoutes` to use `Switch` internally then I don't see a possible solution since by definition Switch is supposed to match exclusively.

Please advise. I can see if I can help contribute to fixing this bug but need more info. Thanks

**Comment by Evgenyx82** [comment]
You can workaround this... set flag (variable) as UnauthorizedLayout/someAuthorizedLayout into routes config. Then use matchRoutes, to find matched route, check flag, then do redirect with some status if fail, or just render if it success )...

here is example:
```
const routes = [
  { component: Root,
    routes: [
      { path: '/',
        exact: true,
        component: App,
        loadData: (dispatch) => new Promise((resolve, reject) => {
          dispatch(setCounter(44));
          resolve('loadData set counter');
        })
      },
      { path: '/courses',
        component: Wrapper,
        routes: [
          { path: '/courses',
            exact: true,
            component: Courses,
            loadData: (dispatch) => new Promise((resolve, reject) => {
              dispatch(fetchCourses(() => { // pass promise callback 
                resolve('loadData set courses');
              }));
            })
          },
          { path: '/courses/public',
            component: CoursesPublic,
            auth: false
          },
          { path: '/courses/draft',
            component: CoursesDraft,
            auth: true
          }
        ]
      },
    ]
  }
]
```

**Comment by collegepinger** [comment]
Right Now I am facing Same type of logical Error I don't know how to Fix it 
[#5754](https://github.com/ReactTraining/react-router/issues/5754)

**Comment by wd2010** [comment]
@Evgenyx82  I have a trouble recently，if the router nest is very deep,how can i use react-router-config with <Route /> ? In the course of my use，i likely to use <Route />

**Comment by mjackson** [comment]
I believe `renderRoutes` should not be using a `<Switch>` internally, but rather should return an array of `<Route>` elements.
