### ISSUE TITLE
Never Receiving CALL_HISTORY_METHOD

### ISSUE THREAD

**Issue by beardedtim** [ReactTraining/react-router#5432]
## Version
"react-router-dom": "^4.1.2"
"react-router-redux": "^5.0.0-alpha.6"

## Steps to reproduce

1. Connect `react-router` and `react-router-redux` to a simple application
2. call a function that does `dispatch(push('/abc'))

## Expected Behavior
* That my system will receive `CALL_HISTORY_METHOD` emitted into it.

## Actual Behavior
* Only receiving `LOCATION_CHANGED`

----------------------------------------------------------

From [these](https://github.com/ReactTraining/react-router/blob/master/packages/react-router-redux/modules/actions.js#L7-L14) lines, it sounds like if we need to hook into URL changes BEFORE it affects our state, we should use `CALL_HISTORY_METHOD`. However, it seems that my system is never given the option to listen for this action. Am I missing something here? How would I listen for changes on the URL BEFORE they affect my state?

**Comment by timdorr** [comment]
The middleware swallows these actions: https://github.com/ReactTraining/react-router/blob/master/packages/react-router-redux/modules/middleware.js

You should set up a listener on the history instance that you create. As long as you do so before rendering your React app, it will get them first and you can choose to take action before the listener for RRR is fired.
