### ISSUE TITLE
<BrowserRouter />will make child component run more times,when page reloaded.

### ISSUE THREAD

**Issue by xianshannan** [ReactTraining/react-router#5433]
See the demo [https://github.com/xianshannan/test](https://github.com/xianshannan/test)
```jsx
import React from 'react';
import { render } from 'react-dom';
import { BrowserRouter } from 'react-router-dom';

class Test extends React.Component {
  componentWillReceiveProps(nextProps) {
    //这里页面重载时，不应该运行的
    //When page reloaded,it should not run.
    console.log('componentWillReceiveProps');
  }
  render() {
    console.log('render');
    return <div>test</div>;
  }
}
render(
  <BrowserRouter>
    <Test />
  </BrowserRouter>,
  document.getElementById('root')
);
```
Component Test componentWillReceiveProps should not run,when page reloaded.
`<HashRouter />` does not have this problem.

**Comment by pshrmn** [comment]
To clarify, you're saying that when you refresh your page, the `componentWillReceiveProps` function is being run? When you do a hard reload, the previous DOM contents should be wiped out. I can't think of a good reason why that would not be the case, but I would probably un- and re-install your dependencies in case something weird is happening with them.

**Comment by xianshannan** [comment]
I foget,it only happen in safari!!!

**Comment by pshrmn** [comment]
This sounds like a browser bug, so I'm not sure that there is a lot that React Router can do, but it certainly is weird that this is happening.

Unfortunately, I don't believe that I can install Safari on Linux (easily), so I don't have a good way to test this. What happens if you add a `componentWillMount` lifecycle function to `<Test>`? If `cWRP` is being called, I assume that that will not be called when you reload.

**Comment by xianshannan** [comment]
Here is the log after adding `componentWillMount`.
[Log] componentWillMount (bundle.js, line 46859)
[Log] render (bundle.js, line 46871)
[Log] componentWillReceiveProps (bundle.js, line 46866)
[Log] render (bundle.js, line 46871)

**Comment by pshrmn** [comment]
It sounds like there is an extra location emitted by `history`. Can you try running the following code?

```js
import { createBrowserHistory } from 'history';

const browserHistory = createBrowserHistory();
browserHistory.listen((location, action) => {
  console.log('LOCATION CHANGE:', location, action);
  console.trace();
});
```
You should be able to set that as the `index.js` content of your `create-react-app` project. If it is an issue with `history`, then that should log twice when you reload the page.

Also, if this does turn out to be related to `history`, we should probably move the conversation to a new issue over there.

**Comment by xianshannan** [comment]
`src/index.js ` code:
```js
import { createBrowserHistory } from 'history';

const browserHistory = createBrowserHistory();
browserHistory.listen((location, action) => {
  console.log('LOCATION CHANGE:', location, action);
  console.trace();
});
```
Only safari has log info below,other browsers have no log info.
[Log] LOCATION CHANGE: (2) (bundle.js, line 21763)
[Log] console.trace()
	（匿名函数）
	listener
	（匿名函数）
	forEach
	notifyListeners
	setState
	（匿名函数）
	confirmTransitionTo
	handlePop
	handlePopState

**Comment by lcoder** [comment]
I met the same problem.when hard refresh ,`componentWillReceiveProps` will run. so the `render` run twice when page loaded.

**Comment by lcoder** [comment]
为什么删我评论啊？
