### ISSUE TITLE
Support for case sensitive routes

### ISSUE THREAD

**Issue by apoh** [ReactTraining/react-router#5435]
Currently Route handles paths in non case sensitive way. We want to add support for case sensitive paths.

Example:
```
   <Route sensitive path={"/example"} />
```

|path|location.pathname|sensitive|matches|
|---|---|---|---|
|/one|/one|false|true
|/one|/One|false|true
|/one|/one|true|true
|/one|/One|true|false

By default sensitive could be false to keep the behaviour downward compatible.
We believe this can be easily implement since path-to-regex has a support for this option [path to regex documentation](https://github.com/pillarjs/path-to-regexp#usage).

One of the reasons for this feature is for example to avoid duplicate content that has negative impact on search engines.

Please let us know if you have any comments about this. We are thinking make a pull request for this feature.

**Comment by pshrmn** [comment]
I would recommend making that PR. That is the best way to get traction with a feature request. I think that it will require maybe 5 lines of code in the actual modules (plus you will need to write a number of tests).
