### ISSUE TITLE
When redirecting to a route under a container, the child components won't get rendered.

### ISSUE THREAD

**Issue by THPubs** [ReactTraining/react-router#5436]
I have several session routes like `/login` and `/forgotpassword`. I wrap these routes in the `SessionContainer`. The rest of the routes I wrap in the `MainAppContainer`. My app looks like this:

      <Provider store={store}>
        <Router>
          <div className="App" >
            <ProgressBar />

            <MuiThemeProvider theme={theme}>
              <div>
                <div id="container">
                  <Switch>
                    <SessionContainer>
                      <Route exact path="/login" component={Login} />
                      <Route exact path="/forgotpassword" component={ForgotPassword} />
                    </SessionContainer>

                    <MainAppContainer>
                      <Route exact path="/" component={Home} />
                    </MainAppContainer>
                  </Switch>
                </div>
              </div>
            </MuiThemeProvider>
          </div>
        </Router>
      </Provider>

In the app container, I check whether the user is there in my redux state and redirect the user to the app if true. In the app container I reidrect to login if the user is not there. Example (My app container):

    const MainAppContainer = ({ children, user }) => {
      if (user) {
        return (<div>
          <Sidebar />

          <MainContainer>
            <UserMenu />

            <InnerContainer>
              {children}
            </InnerContainer>
          </MainContainer>
        </div>);
      }
      return <Redirect to="/login" />;
    };

The problem is, if I go to the app without logging in, the redirection happens as intended but, only the session container is loaded. The child components are not getting loaded. Any idea why this is happening?

**Comment by timdorr** [comment]
See this guide: https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/guides/blocked-updates.md

**Comment by THPubs** [comment]
@timdorr I tried passing the location to my child components but still not working. I tried console logging the pathname in both containers. Console log gives the pathname but there's a problem. If I visit `/` it prints `/` and re-directs to `/login`. I also have a console log in login. But it won't get called if redirected. If I visit login directly, that console log will be called and I get `/login` as the pathname.

**Comment by THPubs** [comment]
I tried to reproduce the issue in sandbox ([https://codesandbox.io/s/github/THPubs/react-router-multiple-containers](https://codesandbox.io/s/github/THPubs/react-router-multiple-containers)) but in there sometimes the error comes but sometimes it won't. I added the code here: [https://github.com/THPubs/react-router-multiple-containers](https://github.com/THPubs/react-router-multiple-containers).

If you can clone it, `yarn install` and `yarn start` then you'll see the issue. Go to `/login`. You should see two titles. Then go to `/`. It will get redirected to `/login` and the title that says login won't be there. When preparing the code I noticed that it happens only when we attach redux!

**Comment by jackjwilliams** [comment]
I'm also having a similar issue, and have posted a question on StackOverflow here:

https://stackoverflow.com/questions/45748355/react-router-redux-component-never-renders

Unfortunately, I'm new to react, react-router & react-router-redux and am getting a little confused by the write up at https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/guides/blocked-updates.md.

My setup is a little different, I'm just trying to get basic stuff working: Bootstrap NavMenu, you click links and it renders the appropriate component.

**Comment by timdorr** [comment]
The redux-specific guide may be more helpful then: https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/guides/redux.md

**Comment by jackjwilliams** [comment]
Using withRouter did not work for me. Thank you for the guides though. I've even inlined my <Layout><Route/></Layout> direclty in my ReactDOM.render to no avail. I may just get back to the basics without react-router-redux.

**Comment by THPubs** [comment]
I just solved it! Everything works well until we add Redux. Redux prevents the container's location from getting updated.

@jackjwilliams In your container, use the router's location prop but when connecting redux, add `withRouter` first and then add the redux `connect` like this:

    export default withRouter(connect(mapStateToProps)(Container));

Have a look at this stackoverflow question: https://stackoverflow.com/questions/45731078/when-redirecting-to-a-route-under-a-container-the-child-components-wont-get-re
Make sure you read the comments.
