### ISSUE TITLE
Docs - MemoryRouter and StaticRouter links don't work

### ISSUE THREAD

**Issue by jlongster** [ReactTraining/react-router#5440]
## Version
4.1.1

## Test Case

It's the docs website, right here: https://reacttraining.com/react-router/web/api/Router

The code for it is here: https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/api/Router.md

## Steps to reproduce

Click on MemoryRouter or StaticRouter. Those links don't work on the docs website, you are taking to the root page: https://reacttraining.com/react-router/

## Expected Behavior

You should be taken to the right docs page for each type of router.

## Actual Behavior

It takes you to https://reacttraining.com/react-router/

I would fix it but I don't know how the docs are generated. It looks like they are relative links, whereas the others that do work are not:

```
- [`<BrowserRouter>`](../../../react-router-dom/docs/api/BrowserRouter.md)
- [`<HashRouter>`](../../../react-router-dom/docs/api/HashRouter.md)
- [`<MemoryRouter>`](MemoryRouter.md)
- [`<NativeRouter>`](../../../react-router-native/docs/api/NativeRouter.md)
- [`<StaticRouter>`](StaticRouter.md)
```

But it looks like those relative links are intentional and should keep you on the current web/native/core section.

**Comment by pshrmn** [comment]
Thanks, this is one of those bugs that I'm surprised no one has brought up until now.

The site uses a markdown loader that "fixes" links with dot segments in their path, so I just prepended `./` to those broken links.

**Comment by kevinzwhuang** [comment]
@pshrmn @timdorr Looks like the site needs to be rebuilt/redeployed? 

I ran the react-router-website server locally on my machine and the links are fixed currently, but when I tried out the links on https://reacttraining.com/react-router/web/api/Router and the MemoryRouter and StaticRouter links are still broken.
