### ISSUE TITLE
React router native: Black background when long press on <Link/>

### ISSUE THREAD

**Issue by nuocgansoi** [ReactTraining/react-router#5449]
Please help me to remove it.
This is a screenshot:
https://drive.google.com/open?id=0B7b1B5PgFf-cM1l6S29UYnJ6YlE
Thanks.
-----------------------------------------------------
"react": "^16.0.0-beta.5",
"react-native": "0.47.1",
"react-router": "^4.1.2",
"react-router-native": "^4.1.1",

**Comment by nuocgansoi** [comment]
Just use "component" prop to custom for my app.
Sorry for stupid question.

**Comment by carlosangon** [comment]
@nuocgansoi How did you exactly resolve this?

I'm having the same issue.

**Comment by carlosangon** [comment]
For what its worth, you are can passed a native component to the <Link component>

```
import { TouchableOpacity } from 'react-native';

<Link component={TouchableOpacity} to={'/your_path}> Link to some view <Link />

```

That should eliminate the back bg on press for anyone else having this issue.
