### ISSUE TITLE
Ignore an url path pointing to an html page.

### ISSUE THREAD

**Issue by thihara** [ReactTraining/react-router#5450]
I have a react app that's hosted on AWS Cloudfront, and the default root is set to index.html, which loads the react app.

So far so good.

I created a new html page page1.html, and then tried accessing it using the full URL, https://my.site.com/page1.html.

Uh oh.

The React app is loaded, and it's router intercepted the URL, and displayed the page not found error. React has no knowledge of the html page, which sounds about right.

If the cache is cleared the page1.html file loads correctly, however as soon as the react app is loaded, the react router starts intercepting the page1.html URL.

Why is that? I kind of expected the direct URL to load the html file bypassing the react app.

And is there a way to add an exception in react router to allow the page to be loaded without being intercepted?

**Comment by timdorr** [comment]
This is something you need to handle on your server side. You should have a wildcard route handler or middleware after anything that can load up static assets.
