### ISSUE TITLE
Multiple state update and redraw of the component

### ISSUE THREAD

**Issue by oiljin** [ReactTraining/react-router#5451]
https://github.com/ReactTraining/react-router/blob/f1a600b2baf491e9e90df00926c831c92ea285ec/packages/react-router/modules/Route.js#L100

this.setState called. If you change state only when this.state.match !== this.computeMatch() might increase performance.

you can use the utility from fb
https://github.com/facebook/fbjs/blob/master/packages/fbjs/src/core/shallowEqual.js

**Comment by timdorr** [comment]
React will optimize that for us when using the default shouldComponentUpdate. It does a shallow comparison by default.
