### ISSUE TITLE
Render a Route-Like or an extension of Route in renderRoutes.js in react-router-config.[Feature Request]

### ISSUE THREAD

**Issue by ax-hd** [ReactTraining/react-router#5453]
I am using react-boilerplate (https://github.com/react-boilerplate/react-boilerplate) for my react project. Specifically the branch with react-router 4 (https://github.com/react-boilerplate/react-boilerplate/pull/1746). Here the developer has wrapped a route within AsyncRoute object for dynamic loading. In the renderRoutes.js file (react-router-config) can we take a Component from developer to render instead of Route. Currently it renders the Route Component. I am trying to extend the boilerplate with server-side rendering so I think this feature would be a good addition.

```
const AsyncRoute = ({ path, load }) => (
  <Route
    path={path} render={(props) => (
      <Bundle load={load} {...props} />
  )}
  />
);

export default AsyncRoute;
```
Imagine providing the AsyncRoute component to react-router-config.

```
const routes = [
  { component: Root,
    routes: [
      { path: '/',
        exact: true,
        component: Home
        routeType: AsyncRoute
      },
      { path: '/child/:id',
        component: Child,
        routeType: AsyncRoute
        routes: [
          { path: '/child/:id/grand-child',
            component: GrandChild
          }
        ]
      }
    ]
  }
]
```
```
//renderRoute.js
import React from 'react'
import Switch from 'react-router/Switch'
import Route from 'react-router/Route'

const renderRoutes = (routes, extraProps = {}) => routes ? (
  <Switch>
    {routes.map((route, i) => (
      (route.routeType ? <route.routeType
        key={route.key || i}
        path={route.path}
        exact={route.exact}
        strict={route.strict}
        render={(props) => (
          <route.component {...props} {...extraProps} route={route}/>
        )}
      /> :
       <Route
        key={route.key || i}
        path={route.path}
        exact={route.exact}
        strict={route.strict}
        render={(props) => (
          <route.component {...props} {...extraProps} route={route}/>
        )}
      />
      )
    ))}
  </Switch>
) : null

export default renderRoutes
```
The one big problem with my code is that, here I am not able to provide props to my custom route component. I will look into this. Meanwhile, Is this a valid feature request?

**Comment by timdorr** [comment]
I don't think we're going to do this. This exposes too much of the internals of `renderRoutes`. It's a really simple function anyways, so recreating it yourself should be simple enough.
