### ISSUE TITLE
Please upgrade 'history' lib to 4.7.2

### ISSUE THREAD

**Issue by GBT3101** [ReactTraining/react-router#5456]
your current version of the history lib is buggy, causing tests to fail.

read here:
https://github.com/ReactTraining/history/issues/513

please upgrade to 4.7.2 to fix it.

**Comment by timdorr** [comment]
`history` is [a dependency](https://github.com/ReactTraining/react-router/blob/master/packages/react-router/package.json#L39) of the project, but uses a version string that will download the latest version for you. If you `npm install react-router`, you will get the 4.7.2 release. We don't have to do anything here.
