### ISSUE TITLE
Not proper props.children value when none of the children routes match within the parent component

### ISSUE THREAD

**Issue by anvk** [ReactTraining/react-router#5458]
## Version
4.1.1

## Test Case
https://codesandbox.io/s/98m413nxqo

## Steps to reproduce
Add a nested route is a component with `Switch` or multiple `Route` components within. Now navigate to the nested route but in a such way that none of the children routes will match.

In More details:

Parent Component A which is rendered on route `/admin` has multiple children routes: `/admin/details`, `/admin/home`. If `/admin/donotexist` is called then Component A will have its `props.children` resolved to an array of `Route` React components

## Expected Behavior
In case when none of the child routes matched you expect to see `props.children` to be `null`.

## Actual Behavior
In case when none of the child routes marched it is either `Switch` component or an array of `Route` components.

**Comment by timdorr** [comment]
I'm not sure what you're doing differently, but that's not what I see:

![image](https://user-images.githubusercontent.com/17882/29633282-c1a908e4-8813-11e7-9706-e69721ac5901.png)

**Comment by anvk** [comment]
No but it is exactly the problem. Shouldn't it `props.children` to be null when route does not match anything inside the `Switch`? Also if you navigate to `/admin` which is 4th link from the top you still get `Switch` as children. In my current project which we want to migrate to the new `react-router` (which is fantastic. Great job btw!) we have many UI which rely on children routes not being matched and then parent component UI looks very different. Like in case of `/admin` and `/admin/:userId/details` for example.

**Comment by timdorr** [comment]
You have that component in your children tree. You can't remove an element from the tree from within that element. That's just how React works.

**Comment by anvk** [comment]
I guess that's the difference with `react-router v2`. Maybe it is worth of mentioning in the docs when developers migrate?

The problem that in the old implementation we have plenty of old code similar to the following:

```
<Route path="customers" component={AdminManageCustomersPage}>
    <Route path=":userId">
        <Route path="details" component={AdminManageCustomersDetail} />
        <Route path="address-books" component={AdminManageCustomersAddressBooks} />
    </Route>
</Route>
```

Old router would return `props.children` as null for the cases when routes do not match.

Basically `AdminManageCustomersPage` is a parent component which might change its look if a child component a present within. It is almost a HTML grid with a user list sidebar and a central part of the page with space dedicated for the `props.children`. And then when route is simply `/customer` we are showing a side bar and central part asking to select user.

**Comment by anvk** [comment]
So for those who is still looking for a solution to this problem. This is a kinda way I managed to solve this in `react-router v4`.

So for the old `v2` code:

```
<Route path="customers" component={AdminManageCustomersPage}>
    <Route path=":userId">
        <Route path="details" component={AdminManageCustomersDetail} />
        <Route path="address-books" component={AdminManageCustomersAddressBooks} />
    </Route>
</Route>
```

I converted into the following code:

```
const AdminManageCustomerRoutes = ({ match }) =>
  <AdminManageCustomersPage>
    <Switch>
      <Route path={`${match}/:userId/details`} component={AdminManageCustomersDetail} />
      <Route path={`${match}/:userId/address-books`} component={AdminManageCustomersAddressBooks} />
    </Switch>
  </AdminManageCustomersPage>;

...

<Route exact path='/customers' component={AdminManageCustomersPage} />
<Route path='/customers' component={AdminManageCustomerRoutes} />
```
