### ISSUE TITLE
Did you guys really think it's was a good idea to nest all those ternary operators?

### ISSUE THREAD

**Issue by leidegre** [ReactTraining/react-router#5459]
https://github.com/ReactTraining/react-router/blob/620ff29f65deef6aa6a65e65f46af16c914d735c/packages/react-router/modules/Route.js#L112

...I mean, there's a more readable, although less verbose alternative, no?

**Comment by timdorr** [comment]
Yes.

**Comment by jimbolla** [comment]
Rewritten without the ternaries:

```js
  render() {
    const { match } = this.state
    const { children, component, render } = this.props
    const { history, route, staticContext } = this.context.router
    const location = this.props.location || route.location
    const props = { match, location, history, staticContext }

    if (component)
      return match ? React.createElement(component, props) : null;

    if (render)
      return match ? render(props) : null;

    if (typeof children === 'function')
      return children(props);

    if (children && !isEmptyChildren(children))
      return React.Children.only(children);

    return null;
  }
```

This way is shorter, more readable, and the clarity makes the comments redundant.

**Comment by timdorr** [comment]
Oh, I like that. Thanks, Jim! We've also got some other places with nested ternaries, I believe. I'll see about wrapping that up into a PR.

**Comment by leidegre** [comment]
@timdorr hehe, no offense taken really. I just lost it when I had a lot of stuff to do and had to parse that to understand what was going on @jimbolla change is an improvment. Compact can be nice but there's a breaking point, to people have different tolerances and/or styles.
