### ISSUE TITLE
React-router-dom 4.2.0 Error, BrowserRouter.js and HashRouter Error, Module not found.

### ISSUE THREAD

**Issue by fudgecakes** [ReactTraining/react-router#5461]
## Version
4.2.0

I am trying to build a web application using React-router-dom 4.2.0 on Jenkins. After running the website I am getting this error. 

ERROR in ./~/react-router-dom/BrowserRouter.js
--
  | Module not found: Error: Can't resolve 'warning' in '/usr/src/app/node_modules/react-router-dom'
  | @ ./~/react-router-dom/BrowserRouter.js 5:15-33
  | @ ./src/js/App.js
  | @ multi (webpack)-dev-server/client?http://0.0.0.0:8080 babel-polyfill ./src/js/App.js

ERROR in ./~/react-router-dom/es/HashRouter.js
--
  | Module not found: Error: Can't resolve 'warning' in '/usr/src/app/node_modules/react-router-dom/es'
  | @ ./~/react-router-dom/es/HashRouter.js 7:0-30
  | @ ./~/react-router-dom/es/index.js
  | @ ./src/js/components/preferences/Preferences.js
  | @ ./src/js/App.js
  | @ multi (webpack)-dev-server/client?http://0.0.0.0:8080 babel-polyfill ./src/js/App.js

I am importing that package with this line:

import BrowserRouter from 'react-router-dom/BrowserRouter';

**Comment by timdorr** [comment]
This isn't a bug in React Router. Your CI isn't installing the `warning` npm package for some reason. That doesn't have anything to do with this library.

**Comment by kesne** [comment]
@timdorr It looks like `warning` is being imported by files in the `react-router-dom` package, but it's not a dependency in the `react-router-dom` package.json (it's only in the `react-router` package.json)

**Comment by timdorr** [comment]
Ah, you are correct. Adding react-router or warning as a dep on your project will fix this for now. I'll have to push out a fix tonight.

**Comment by fudgecakes** [comment]
Awesome thank you!!

**Comment by timdorr** [comment]
react-router-dom 4.2.1 should fix this for you.

**Comment by pinguo-pengxiaolong** [comment]
As one "typescript + webpack" project, I fix this error by modifying the config of **resolve** field  in webpack.config.js, by changing its **extensions** from extensions: ['.ts', '.tsx' ] to ['.ts', '.tsx', '.js', '.jsx' ]

**Comment by tibic** [comment]
hello sir , i had try react-router-dom 4.2.1,but not work

ERROR in ./node_modules/react-router-dom/es/index.js
Module not found: Error: Can't resolve './BrowserRouter'

ERROR in ./node_modules/react-router-dom/es/index.js
Module not found: Error: Can't resolve './HashRouter'

ERROR in ./node_modules/react-router-dom/es/index.js
Module not found: Error: Can't resolve './Link' 

"dependencies": {
    "axios": "^0.18.0",
    "express": "^4.16.3",
    "react": "16.2.0",
    "react-dom": "16.2.0",
    "react-hot-loader": "next",
    "react-router": "^4.2.0",
    "react-router-dom": "4.2.1",
    "serve-favicon": "^2.5.0"
  }
