### ISSUE TITLE
Route always renders children: Surprising

### ISSUE THREAD

**Issue by hdon** [ReactTraining/react-router#5463]
This is not a bug report (at best a documentation bug report) but it was and remains pretty counterintuitive to me that Route children are always rendered.

If someone could offer me some clarity on why this is, it would be much appreciated :)

Q: If the intuitive use case for Route children is to render contained elements only when the route matches the current location, what is the use case for always rendering children?

**Comment by timdorr** [comment]
https://reacttraining.com/react-router/web/api/Route/children-func

> Sometimes you need to render whether the path matches the location or not. In these cases, you can use the function children prop. It works exactly like render except that it gets called whether there is a match or not. 
> 
> The children render prop receives all the same route props as the component and render methods, except when a route fails to match the URL, then match is null. This allows you to dynamically adjust your UI based on whether or not the route matches
