### ISSUE TITLE
change route programmatically

### ISSUE THREAD

**Issue by elhampour** [ReactTraining/react-router#5464]
i have a service class like this:
`import jQuery from 'jQuery';
import Toastr from 'Toastr';

class baseApi{
  static ajax(options) {
    return jQuery.ajax(jQuery.extend({}, options, {
      error: (jqXHR, textStatus, errorThrown) => {
        if (jqXHR.status === 401) {
          Toastr.error('unathorized');
        }
      }
    }))
  }
}

export default baseApi;

`

i want to change route to '/dashboard' after  Toastr.error('unathorized'); .

how can i achieve this ?

this is my index.js file: 
import React from 'react';
import ReactDOM from 'react-dom';
import { HashRouter, Route, Switch } from 'react-router-dom'
import { createBrowserHistory } from 'history';

// Containers
import Full from './containers/Full/'

// Views
import Login from './views/Pages/Login/'
import Register from './views/Pages/Register/'

const history = createBrowserHistory();

ReactDOM.render((
  HashRouter history={history}>
    Switch>
      Route exact path="/login" name="Login Page" component={Login} />
      Route exact path="/register" name="Register Page" component={Register} />
      Route path="/" name="Home" component={Full} />
    /Switch>
  /HashRouter>
), document.getElementById('root'))

**Comment by pshrmn** [comment]
This is a bug tracker, not a support system.

https://stackoverflow.com/questions/31079081/programmatically-navigate-using-react-router/42121109#42121109
