### ISSUE TITLE
Link.js:9 Uncaught TypeError: BrowserRouter.push is not a function?

### ISSUE THREAD

**Issue by vipin733** [ReactTraining/react-router#5467]
I'm trying to logout page for this I'm trying to use push method but its throwing error 
Link.js:9 Uncaught TypeError: BrowserRouter.push is not a function? and I'm also used 
import createHistory from 'history/createBrowserHistory';
but probel with this yes my router changed but DOM not changed its still showing same page instead of 
```
  import React from 'react';
import createHistory from 'history/createBrowserHistory';
import { BrowserRouter} from 'react-router-dom';

const history = createHistory();
export default class Link extends React.Component {

  onLogout() {
    BrowserRouter.push('/');
   // history.push('/');
  }
  render() {
       return (
         <div>
           <h1>Links</h1>
           <button onClick={this.onLogout.bind(this)}>Logout</button>
         </div>
       );
  }
}
```

**Comment by pshrmn** [comment]
https://stackoverflow.com/questions/31079081/programmatically-navigate-using-react-router/42121109#42121109
