### ISSUE TITLE
Does Link support set parameter, auto fill path ?

### ISSUE THREAD

**Issue by eromoe** [ReactTraining/react-router#5473]
I mean something like:
```
const docId, name, tagValue = this.props;

<Link to="/doc/:docId" params={ docId: docId}>detail</Link>
<Link to="/doc/:docId?search=:name&tag=:tag" params={ docId: docId, name:name, tag:tagValue}>detail</Link>
```

For now, I have to write a function to do such thing:

```
function docUrl(docId) {
  return `/doc/${docId}`;
}

<Link to={docUrl(n.id)} >detail</Link>
```

Use `PatternUtils.formatPattern` is something similar,  hope this feature can be embed in `Link`.

**Comment by timdorr** [comment]
Unfortunately, no. Our underlying library (path-to-regexp) is one-way and doesn't support rebuilding URLs with named parameters.

**Comment by eromoe** [comment]
I think it is a quite common requirement.  May I ask the reason?  Performance ?

**Comment by pshrmn** [comment]
`path-to-regexp` [does support this](https://github.com/pillarjs/path-to-regexp#compile-reverse-path-to-regexp), but React Router isn't really configured to take advantage of it. The feature that you're requesting works best when you have named routes, which React Router does not have. Instead, with React Router, you are always using the full pathname.

You could in theory write your own `<Link>` component to take advantage of this, but I don't really see the advantage of doing so.

For example, this:
```js
<Link to="/doc/:docId" params={{ docId: docId }}>detail</Link>
```
is more verbose than this:
```js
<Link to={`/doc/${docId}`}>detail</Link>
```
If you have named routes, then you can do the following, but named routes and dynamic routing don't really flow together.
```js
<Link to="Detail" params={{ docId: docId }}>detail</Link>
```
Also, `path-to-regexp` only does pathname matching/compiling, so the query string that you include in your example would not work even if React Router supported this.
