### ISSUE TITLE
Wrap `NavLink` in `<ul>` to make it semantically-correct HTML

### ISSUE THREAD

**Issue by benjaminhoffman** [ReactTraining/react-router#5478]
Since `NavLink` is used for navigation links, wouldn't it be semantically correct to make it an unordered list?  ([w3c menu structure](https://www.w3.org/WAI/tutorials/menus/structure/)).  I wasn't sure at first but then noticed RR does include the `aria-current` attribute for `NavLink` so I was curious if it makes sense to go the extra step and turn `NavLink` into `<ul>`s with no styling?

## Expected Behavior
- possibly wrap [`NavLink`](https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/modules/NavLink.js#L31-L37) within `<ul>` & `<li>` elements then remove styles?

**Comment by pshrmn** [comment]
A `<NavLink>` does not have to be rendered as a child of a `<nav>`. It is possible that the name originated because it is correlated with `<nav>` elements (I'm not terribly fond of the name, but it is what it is), but a `<NavLink>` is just a link that detects whether or not it is active.
