### ISSUE TITLE
Route#render documentation clarity

### ISSUE THREAD

**Issue by liushigit** [ReactTraining/react-router#5480]
In the API doc for [Route#render](https://reacttraining.com/react-router/web/api/Route/render-func)

The sentence 

> "The render prop receives all the same route props as the component render prop." 

 should be changed to 
"The render prop receives all the same route props, which can be used as the component render prop." for better clarity.

## Version
4.1.1

**Comment by timdorr** [comment]
Please submit a PR for docs changes Just hit the edit pencil icon on the doc in this repo. 👍

**Comment by liushigit** [comment]
@timdorr [PR](https://github.com/ReactTraining/react-router/pull/5481) submitted.
