### ISSUE TITLE
[react-router-redux] propagate location state through Redux instead of context

### ISSUE THREAD

**Issue by wzrdzl** [ReactTraining/react-router#5484]
There was said a lot about the RR4's decision to ditch the subscription mechanism, I totally respect that decision but it is needless to say that it made the developer experience slightly worse so that even the [official guide of how to deal with the blocked updates was created](https://reacttraining.com/react-router/web/guides/dealing-with-update-blocking).

There were some valid (at least to my opinion) [comments](https://medium.com/@esamatti/subscriptions-in-react-redux-do-work-547bf9d66aa3) on that topic that were saying that subscription mechanism works great in `react-redux` so if they managed to come up with a reliable solution why can't we have the same. I would slightly evolve this idea to the point of "if `react-redux` does a great job of reliably propagating state updates through the react tree, why won't we use it for location state as well?"

I definitely wouldn't propose to refactor the core `react-router` to use redux, but `react-router-redux` looks like a good candidate: 
 - it is created for the people that prefer the "redux" approach to their state management
 - it already uses redux for some parts but state propagation.

So answering the question:

> How will it make current work-arounds straightforward?

I would say, it will completely eliminate the hassle of dealing with the blocked updates.

My proposal is to include react-router-redux's implementations of `Route`, `Switch`, etc, that are "connected" to redux and take the location state from it instead of context. The final solution is a subject for the future discussion though, as for now, I would just like to hear your opinion on the idea.

cc @epeli

**Comment by epeli** [comment]
That would be good  but I still think react-router should just implement subscriptions like react-redux and forget this blocking "feature" completely. I think there's huge api design smell if we need 500+ words of documentation on how deal with this when it could be avoided.

I actually use a Redux wrapper to get around this issue:

 https://gist.github.com/epeli/764ff6ca76daad2b07a2c3dd02694ae7

It's so nice to not have to have deal with the blocking updates.

**Comment by timdorr** [comment]
Redux uses context to propagate state to connected components: https://github.com/reactjs/react-redux/blob/master/src/components/connectAdvanced.js#L136-L143

Outsourcing to Redux wouldn't buy us anything. We would also be subject to the semantics of how it operates, which are often at odds with how window.history works. 

As for the subscriptions issue, this has been discussed to death already. Search through other issues. We're not going to implement it.

**Comment by laustdeleuran** [comment]
This ties into this issue, as well as some of the reasons it probably won't change: 
https://github.com/reactjs/react-router-redux/issues/597#issuecomment-328958394
