### ISSUE TITLE
react-router 4.2.0 is throwing Maximum call stack size exceeded when using Redirect in Jest tests

### ISSUE THREAD

**Issue by duro** [ReactTraining/react-router#5486]
## Version
`react-router-dom@4.1.2` with child dep of `react-router@4.2.0`

## Test Case
https://github.com/duro/react-router-err-reproduction

Since a code sandbox doesn't let me show a reproduction in a Jest like environment, I had to mock up a simple repo project.

The reproduction steps and some notes the test case are in the README of the repo.

## Steps to reproduce
1. Setup a test that renders a `<Route />` which in turn renders a `<Redirect />`

## Expected Behavior
I Should be able to render a `<Redirect />` inside a test when it is wrapped in a `<MemoryRouter />`

## Actual Behavior
When I render a `<Redirect />` inside a <Route />` in my test after switching to react-router `4.2.0` it begins throwing the following error:

```
    RangeError: Maximum call stack size exceeded

      at valueEqual (node_modules/value-equal/cjs/index.js:7:20)
      at node_modules/value-equal/cjs/index.js:35:14
      at Array.every (native)
      at valueEqual (node_modules/value-equal/cjs/index.js:34:18)
      at node_modules/value-equal/cjs/index.js:35:14
      at Array.every (native)
      at valueEqual (node_modules/value-equal/cjs/index.js:34:18)
      at node_modules/value-equal/cjs/index.js:35:14
      at Array.every (native)
      at valueEqual (node_modules/value-equal/cjs/index.js:34:18)
      at node_modules/value-equal/cjs/index.js:35:14
      at Array.every (native)
      at valueEqual (node_modules/value-equal/cjs/index.js:34:18)
      at node_modules/value-equal/cjs/index.js:35:14
      at Array.every (native)
```

**Comment by pshrmn** [comment]
When you render a `<PrivateRoute>` with no path, that means that the component is always going to match. What that means is that when you redirect and the re-render, you will render the redirect again.
```js
<BrowserRouter>
  {/* the following route will always render, no matter where you redirect to */}
  <Route render={() => <Redirect to={`/${Math.random()`} />
</BrowserRouter>
```
If you don't want the infinite loop to happen, a `path` prop should prevent that. Similarly, rendering inside of a `<Switch>` that matches other routes prior to the one the does the redirecting should do the trick.

**Comment by duro** [comment]
Thanks @pshrmn, that did the trick

**Comment by duro** [comment]
I upgraded my test tree to look like this:

```
<MemoryRouter initialEntries={['/dashboard']} initialIndex={0}>
  <PrivateRoute path="/dashboard" component={FakeComponent} />
</MemoryRouter>
```
