### ISSUE TITLE
Pass the other props for the respective children components using route config.

### ISSUE THREAD

**Issue by aniruddhashevle** [ReactTraining/react-router#5491]
## Version
4.1.1

## Discussion about the Approach

I've referred https://reacttraining.com/react-router/web/example/route-config
And **I've to pass the other props for the respective children components using react-router only**. (Not using other packages like [react-router-config](https://www.npmjs.com/package/react-router-config), etc.)

route config:
```
export const routes = [
  {
    path: '/dashboard',
    component: Dashboard,
    routes: [
      {
        path: '/dashboard/test',
        component: Test
      },
      {
        path: '/dashboard/test/1',
        component: Test1
      },
      {
        path: '/dashboard/test/2',
        component: Test2
      },
    ]
  }
]
```

sub routes:

```
// wrap <Route> and use this everywhere instead, then when
// sub routes are added to any route it'll work
export const RouteWithSubRoutes = (route) => (
  <Route path={route.path} render={props => (
    // pass the sub-routes down to keep nesting
    <route.component {...props} routes={route.routes} />
  )}/>
)
```

In the Dashboard component, I've used,

```
<div className="test">
  {this.props.routes.map((route, i) => (
    <RouteWithSubRoutes key={i} {...route} />
  ))}
</div>
```
## Actual Behavior
It behaves properly. And respective components **Test, Test1, Test2** are rendered inside the Dashboard component's div having **className test**. And those components are rendered according to the routes path as well properly.

## Expected Behavior
However I need to send some props(other props) from the Dashboard components to its children components **Test, Test1, Test2** using the same router config.
Like we usually do,
`<Test myProp1="prop1" myPropFun1={this.propFun1} />`

## Changes made by me
I've just made following changes to make the above expected behaviour

Starting with the other props that I wanted,
So in the Dashboard component,

```<div className="test">
{this.props.routes.map((route, i) => (
  route.path === "/dashboard/test" ?
    <RouteWithSubRoutes key={i} myData='test' myFun={this.myFunTest} {...route}/>
 
    : route.path === "/dashboard/test/1" ?
    <RouteWithSubRoutes key={i} myData='test1' myFun={this.myFunTest1} {...route}/>

    : route.path === "/dashboard/test/2" ?
    <RouteWithSubRoutes key={i} myData='test2' myFun={this.myFunTest2} {...route}/>

    : <RouteWithSubRoutes key={i} {...route}/>
))}
</div>
```

sub routes:

```// wrap <Route> and use this everywhere instead, then when
// sub routes are added to any route it'll work
export const RouteWithSubRoutes = (route) => (
  <Route path={route.path} render={props => (
    // pass the sub-routes down to keep nesting
    <route.component {...props} routes={route.routes} otherProps={route}/>
  )}/>
)
```
In the above, I've added **otherProps** to which I've assigned the whole route object as it also contains other props like **myData**, **myFun** passed through the Dashboard component shown above.

Used these other props inside the children components.
In Test component,

```
render() {
  const {
    myData,
    myFun
   } = this.props.otherProps

   return (
     <div>
         <div>Hit Test component with prop {myData}</div>
         <div{myFun()}</div>
      </div>
    )
}
```

## Questions
What do you think about this approach?

And what are the pitfalls I'll be facing due to this approach?

## Problem
Problem that I'm facing is, while hitting the route path '/dashboard/test/1', expected behaviour is to only Test1 component should be rendered(as defined in route config). BUT both Test and Test1 components are rendered even after using "exact" prop in the Route.

**Comment by timdorr** [comment]
This is a bug tracker. For discussions, I would take this to Reactiflux.

**Comment by aniruddhashevle** [comment]
@timdorr : Can you please give me the updates re:the above!

**Comment by aniruddhashevle** [comment]
@timdorr : Please give me the updates.
