### ISSUE TITLE
withRouter not working with multiple HOC components

### ISSUE THREAD

**Issue by dagda1** [ReactTraining/react-router#5493]
I am using `react-router-dom` and `withRouter` will not work with my quite deep nesting of multiple HOC's like this:
```
export default withRouter(
  connect(state => {
    const formValues = fields.length && selector(state, ...fields);

    return {
      initialValues: {
        currentName: state.application.applicant.currentName,
        previousNames: state.application.applicant.previousNames
      },
      api: {
        countries: state.api.countries.data
      },
      formValues
    };
  })(reduxForm(reduxFormOptions)(CurrentName))
);
```
This history is not being updated.

Is there something I am doing wrong, should `withRouter` wrap the entire `connect` call?

I have reverted to `history.push` which does work but I am curious to know why `withRouter` is not working.

**Comment by timdorr** [comment]
Unless one of the HoCs is overwriting the router prop, this should work.

**Comment by dagda1** [comment]
it really does not and nothing is overwriting the router, i am using <Redirect /> whivh might be part of it.  how do i go about pricing this?
