### ISSUE TITLE
react-router + history = error

### ISSUE THREAD

**Issue by RoyalHunt** [ReactTraining/react-router#5503]
Hi there! I've checked everywhere and don't know how to solve my issue.
"react-router-dom": "^4.2.2",
"history": "^4.7.2",

history.js
```
import createBrowserHistory from 'history/createBrowserHistory'

const history = createBrowserHistory()
export default history
```

index.js
```
import history from './history'
import { Router } from 'react-router-dom'

<AppContainer>
  <Router history={history}>
    <Provider store={store}>
      <Component />
    </Provider>
  </Router>
</AppContainer>,
```

And in app have errors:
./~/react-router/es/Redirect.js
42:17-31 'history' does not contain an export named 'createLocation'.

./~/react-router/es/Redirect.js
45:8-25 'history' does not contain an export named 'locationsAreEqual'.

when I made console.log(history), I'm receiving next object: 
![capture image](https://user-images.githubusercontent.com/22590130/30206592-3c0c127e-9495-11e7-8188-1ca752b7f9d4.png)

**Comment by RoyalHunt** [comment]
Found the problem in webpack config! thx

**Comment by sandersky** [comment]
@RoyalHunt Care to shed some light as to what the error was in your Webpack config? I seem to be running into the same issue.

**Comment by teriu** [comment]
@sandersky any luck on this one? Having the same issue here

**Comment by RoyalHunt** [comment]
Hey, guys! Sorry for that late response. My problem was in Webpack config in resolve modules section. I put at first place **node_modules** and problem gone
