### ISSUE TITLE
Feature request: <Prompt /> should render children props

### ISSUE THREAD

**Issue by bbthorntz** [ReactTraining/react-router#5504]
Currently, the `<Prompt />` component always renders `null`. Like so:

```js
render() {
    return null;
}
```

This causes a problem when we create a prompt HOC because we must insert an additional `<div>` which can easily break flex layouts. Here's a snippet of the HOC.

```jsx
const promptOnPageChange = () => (Component) => {
    const HOC = (props) => {
        return (
            <div>
                <Prompt when={props.prompt} message={props.promptMessage} />
                <Component {...props} />
            </div>
        );
    };

    return HOC;
}
```

If the `<Prompt />` component rendered it's children (defaulting to `null`) then the component could be used more easily within an HOC. For example:
```js
render() {
    return this.props.children;
}
```

```jsx
const promptOnPageChange = () => (Component) => {
    const HOC = (props) => {
        return (
            <Prompt when={props.prompt} message={props.promptMessage}>
                <Component {...props} />
            </Prompt>
        );
    };

    return HOC;
}
```

**Comment by timdorr** [comment]
It doesn't make semantic sense to allow children. That implies that the children *are* the prompt, which isn't the case. This would likely cause more problems than it solves.

Incidentally in React 16, this won't be an issue, as you can return arrays.

**Comment by bbthorntz** [comment]
Thanks for the reply @timdorr. Aware that in React 16 this isn't an issue, but until it's out of beta, it's not an option. Will implement a custom <Prompt /> HOC in the meantime.
