### ISSUE TITLE
NavLink reporting current status incorrectly to NVDA screen reader

### ISSUE THREAD

**Issue by AlmeroSteyn** [ReactTraining/react-router#5507]
## Version
4.2.2

## Test Case
This occurs with every use of the `NavLink` component. Also in a vanilla implementation of `react-router-dom` in a clean application. 

## Steps to reproduce
Use the `NavLink` component in an app. Run the app in Firefox and activate the NVDA screen reader.

Now browse the links with `TAB` and `Shift+TAB` and activate them with `Enter` and check the screen reader response.

I do not yet know if this is an issue only in NVDA and if other screen readers are also involved.

## Expected Behavior
Only the currently highlighted link should be read out as `current`. On selecting a link it should be read out as being `current` only once.

## Actual Behavior

The following graphic shows the NVDA speech viewer with a basic application containing only `react-router-dom`:

![nvdareactrouter](https://user-images.githubusercontent.com/5063473/30264223-31fa80e6-96d8-11e7-94ee-92a128b730da.jpg)

The blue dotted outline:

This shows that every link in the set is read out as current, regardless of the setting of `aria-current`.

The dashed red outline:

This shows that when activating a router link, NVDA reads out the word "current" multiple times. 

I will shorly submit a pull request to fix the isue from the blue dotted outline.

As for the red dashed outline, I have not been able to track down yet if this is due to the way the component renders or if it is an actual issue with the implementation in NVDA or how Firefox exposes the accessibility tree.

**Comment by AnthonyYY** [comment]
remove aria-current from inactive link seems not prevent NVDA from reading "current" multiple times
could you pls help to check this fiddle https://jsfiddle.net/n5u2wwjg/238066/
