### ISSUE TITLE
Current path is not changed after react router basename has changed

### ISSUE THREAD

**Issue by Y-Taras** [ReactTraining/react-router#5509]
##  User story

I'm creating multi language app. I'm using  : React Intl; React Router v4; Redux.  
 Paths in my app are going to be depending on locale:  

    / <-- default expecting this to be uk
    /en
    /ru
    /posts <-- uk
    /en/posts
    /ru/posts

## Ideal API

Ideally using a BrowserRouter with the basename prop should take care of things

       <BrowserRouter basename={lang}>

## The issue

Changing `basename` property from `'en'` to `'uk'` updates prefix in all links and routes, but the path in the browser. The path remains unchanged (contains previous `basename`).

**Comment by timdorr** [comment]
We don't support dynamic basenames. That would involve re-creating the history instance, thereby blowing away all your previous history and creating a whole new class of bugs to deal with.

For your particular use case, this is something you'll have to manage yourself.
