### ISSUE TITLE
Allow passing props to <Route> to be passed down to the component it renders

### ISSUE THREAD

**Issue by bigblind** [ReactTraining/react-router#5521]
# The concept
Allow passing props to `Route` to be passed to the component it renders. For example:

```jsx
<Route path="/foo" component={MyComponent} foo="bar" />
```

In that case, if the route matched, `MyComponent` would be rendered as follows:

```jsx
<MyComponent match={...} history={...} foo="bar" />
```

Or, if you don't like `Route` accepting arbitrary properties, maybe we can achieve the same with something like:

```jsx
<Route path="/foo" component={MyComponent} extraProps={{foo: "bar"}} />
```

# Use case

Sometimes, I have a component that I want to render in a Route, but make it reusable in such a way that it doesn't have to know about the URL structure that it is in. For example, consider a Twitter clone's  `UserProfile` component:

```jsx
// Somewhere in the app:
<Route path="/users/:userId" component={UserProfile} />

let UserProfile = ({match}) => {
  return <div>
    {/* ... user profile stuff ... */}
    <Route path={match.path + "/followers"} component={UserFollowers} />
  </div>
}
```

The `UserFollowers` component needs access to the `userId` of the user to show their followers, and it can get that from `match.params`, but what if we also have some kind of dashboard that displays the currently logged-in user's followers?

```jsx
// Somewhere in the app:
<Route path="/dashboard/" component={Dashboard} />

let Dashboard = ({match}) => {
 // ... Somehow obtain the userId
  return <div>
    {/* ... dashboard stuff ... */}
    <Route path={match.path + "/followers"} component={UserFollowers} />
  </div>
}
```

In order to pass the `userId` variable to `UserFollowers`, I'd need to use `render`, and create a whole new function, just to pass the prop to my component. Or, I'd have to use a HOC like [recompose's `withProps`](https://github.com/acdlite/recompose/blob/master/docs/API.md#withprops). Both of these options work, but I think it'd be more elegant to just have a way to pass props through via `Route`.

**Comment by timdorr** [comment]
This has been discussed [many](https://github.com/ReactTraining/react-router/issues/5391), [many](https://github.com/ReactTraining/react-router/issues/4105), [many](https://github.com/ReactTraining/react-router/issues/4627), [many](https://github.com/ReactTraining/react-router/issues/4942) times.

The simplest solution is just to use `render` instead:
```js
<Route path="/abc" render={()=><TestWidget num="2" someProp={100}/>}/>
```

**Comment by odrzutowiec** [comment]
Yeah, many many many times means people really really really want that. ;)

**Comment by henrypenny** [comment]
If anyone is refactoring their code to use this solution. Don't forget to remove `component={...}`

**Comment by NES-Elliott** [comment]
"Warning: Functions are not valid as a React child. This may happen if you return a Component instead of <Component /> from render. Or maybe you meant to call this function rather than return it." is an error I receive when using the method mentioned above. This could be alleviated by allowing the Route's component prop to take in JSX tags.

**Comment by cakraww** [comment]
`<Route path="/abc" render={(props) => <TestWidget {...props} someProp={100} />} />`
is more complete as it forwards the default props as well (e.g: `match` prop).

**Comment by moparlakci** [comment]
just to confirm that it works for me also ;)
<Route exact path='/orders-confirmed-list' render={(props) => <Orders {...props} status={'CONFIRMED'} />} />
