### ISSUE TITLE
Feature Request: TabRouter for React Native

### ISSUE THREAD

**Issue by iamclaytonray** [ReactTraining/react-router#5526]
Feature Request:

So the idea is more-or-less inspired by <a href='https://reactnavigation.org/'>react-navigation</a> and <a href='https://reactnavigation.org/docs/navigators/tab'>here is the docs for their TabNavigator component.</a>

`react-navigation` is currently backed up (with only 2 maintainers right now) and have some issues with their TabNavigator. Also, I feel like react-router-native is semi-incomplete without a native TabRouter. If it's added to the react-router-native library as an official component, I think it would cut down on a lot of unneeded OS components that does the same thing, which would help cut down on compatibility issues with react-router.

Here is a super simple/contrived (not great) example. I can do a better example to follow up with this later. But this is the general idea:

``` javascript

const TabRoutes = () => (
  <TabRouter position={'bottom'} style={styles.icon}>
    <Link to='/'>
      <Icon name='ion-ios-home' type='ionicon' />
    </Link>
    <Link to='/about'>
      <Icon name='ion-ios-information-circle-outline' type='ionicon' />
    </Link>
    <Link to='/account'>
      <Icon name='ion-ios-person-outline' type='ionicon' />
    </Link>
  </TabRouter>
);

const styles = StyleSheet.create({
  icon: {
    color: 'blue',
    width: 30,
    height: 30,
  }
});

**Comment by timdorr** [comment]
We already have that as an experimental component: https://github.com/ReactTraining/react-router/blob/master/packages/react-router-native/experimental/TabRoutes.js

Some help expanding it would be most appreciated!

**Comment by iamclaytonray** [comment]
Cool, I'll try playing around with it a bit and see if I make any progress. Thanks!
