### ISSUE TITLE
Preserve params in Redirect

### ISSUE THREAD

**Issue by jochenberger** [ReactTraining/react-router#5533]
I'm trying to use `Redirect` to migrate to a new URL schema. For example I have a page to edit contacts. The old URL was `/contactedit/:id` and the new one is `/contacts/:id`.
```jsx
<Redirect from="/contactedit/:id?" exact to="/contacts/:id" />
```
does not work because `:id` is not extrapolated in `to`.
See also https://github.com/ReactTraining/react-router/issues/1034#issuecomment-113526156.

**Comment by timdorr** [comment]
Duplicate of #5209 (which could use some love)
