### ISSUE TITLE
Eslint Warning with unused variables in Link render

### ISSUE THREAD

**Issue by pdjota** [ReactTraining/react-router#5535]
Hi, I was viewing this and noticed that the replace was not used in the context of the render method:

https://github.com/ReactTraining/react-router/blob/f77440ec9025d463c6713039ab1a6db1faca99bb/packages/react-router-dom/modules/Link.js#L64

Could be enough to keep:
`const { to, innerRef, ...props } = this.props;`

Are you keeping it for some particular reason, kind of filtering the properties for the Anchor?

**Comment by pshrmn** [comment]
Yes, we unpack `replace` so that it doesn't get passed as a prop of the anchor.
