### ISSUE TITLE
redux push action doesn't work the first time. Reducer updated, match.params is not.

### ISSUE THREAD

**Issue by tleunen** [ReactTraining/react-router#5538]
## Version
```
"react-router-dom": "^4.2.2",
"react-router-redux": "^5.0.0-alpha.6",
```

## Steps to reproduce
- Setup some routes, with React Router Link and push action to navigate.
- Notice the links work as expected
- Altough the route changes in the url bar, the push action doesn't work the first time. It needs to be triggered twice.

## Expected Behavior
Both the React router link and the push action should produce the same result.

## Actual Behavior
- The content of `match.params` doesn't match the location from the router reducer
- The action needs to be triggered twice in order to really switch the route

![image](https://user-images.githubusercontent.com/1972567/30624209-f1952930-9d70-11e7-842f-e908fa5f64f0.png)
First log is on load
Second log is when using the push action
Third log is when clicking on a <Link>

**Comment by timdorr** [comment]
See this guide: https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/guides/redux.md

**Comment by tleunen** [comment]
I have seen it. Thank you.

The log I show is from my main component in which I'm interested to render. So the rendering is triggered, but `match` doesn't contain the updated route.

**Comment by tleunen** [comment]
After wrapping that component with `withRouter`, my render is called twice, instead of once when clicking on a Link.

Twice, first one with the wrong match. Then with the right match.

**Comment by tleunen** [comment]
Even if I wrap this component with `withRouter`, which is not needed since I know the render function si called. It still doesn't work.

**Comment by tleunen** [comment]
the `withRouter` was missing on another parent component. So problem fixed I guess...
