### ISSUE TITLE
Why do we need the full path to a route?

### ISSUE THREAD

**Issue by winterblack** [ReactTraining/react-router#5558]
This isn't really an issue, just a question. Why do we need to include the full path of a route that's inside another component? For example, if I have a router that looks like this:

```
    <HashRouter>
      <div>
        ...some other routes...
        <Route path='/profile' component={ Profile } />
      </div>
    </HashRouter>

```

and then a Profile component that looks like this:

```
      <div>
        <Route path='/profile/welcome' render={()=><div>welcome</div>}/>
        <Route path='/profile/details' render={()=><div>details</div>}/>
      </div>

```
Why do I need to include '/profile' in the path of each item? No other starting path is going to render this component anyway...and even if it does, maybe I want to render the same thing regardless of the initial path that rendered this component.

Just curious what the thinking is, and also whether there is a way to name paths relatively.

**Comment by timdorr** [comment]
#5127

**Comment by winterblack** [comment]
That was a little over my head. I'll just assume there was a good reason to do it this way and move on. ;)
