### ISSUE TITLE
Add a sentence about react-router-redux versioning to this repo.

### ISSUE THREAD

**Issue by joearasin** [ReactTraining/react-router#5559]
It isn't clear that react-router-redux 5.x.x.alpha.x is the only viable version to use with react-router 4 based on the information in this repo. It probably makes sense to copy over the versioning blurb over from https://github.com/reactjs/react-router-redux to make things clear if a user finds their way here first.

**Comment by pshrmn** [comment]
You can always open up a PR :smile:

You just need to go to the [README](https://github.com/ReactTraining/react-router/blob/master/packages/react-router-redux/README.md), click the "edit this file" button (:pencil2:), make the desired changes, then at the bottom select the "create a new branch..." option and open a PR here.

**Comment by joearasin** [comment]
Done -- Also updated the npm badge to point to the right place.
