### ISSUE TITLE
Add support for React v16 in react-router v3

### ISSUE THREAD

**Issue by kaelig** [ReactTraining/react-router#5561]
Thank you for building react-router, it's amazing!

I'm using react-router v3 on a project and the jump to v4 is quite significant so I'll be putting it off for a while.
At the moment, React v16 + react-router v3 seem to have an issue because of the usage of PropTypes directly from React (support dropped in React v16).

I get this error when compiling my project:

```
path/to/myproject/node_modules/react-router/lib/PropTypes.js:8
var func = _react.PropTypes.func,
```

Could there please be a v3.x patch released to support React v16?

**Comment by timdorr** [comment]
Already done. Check version 3.2.0

**Comment by kaelig** [comment]
Sweet, you're the best!

**Comment by Youngdi** [comment]
I got the same issue on React v16 + react-router v4.2.0. Please check it out! Thank you.
