### ISSUE TITLE
Feature Request: Replace State on PopState

### ISSUE THREAD

**Issue by ccorcos** [ReactTraining/react-router#5562]
In older versions of React Router, the route state was held in a local cache and only a key was saved in actual browser route state. The benefit of this approach was that I was able to effectively replace the state of a route on the popstate event without preventing the browser from changing routes. 

This was particularly useful for saving scroll position before leaving a page. It would be great if there were some way to do this again.

**Comment by timdorr** [comment]
That's a history concern. I would bring that up over there: https://github.com/ReactTraining/history
