### ISSUE TITLE
React16 support

### ISSUE THREAD

**Issue by brucewpaul** [ReactTraining/react-router#5563]
Now that react16 has been published, would it be possible to update the dependencies to reflect this? Let me know if you me to put up a pr, Thanks!

**Comment by timdorr** [comment]
We already do. Any version equal to or greater than 15 works.

**Comment by emilyrohrbough** [comment]
Has React 16 been tested for `react-router-dom`? I see `react-router` v3.2.0 has been released to offer 16 support.

**Comment by timdorr** [comment]
Yeah, it works just fine.

**Comment by webmobiles** [comment]
yes, I confirm;, and it's working 2x fast !!!

**Comment by emilyrohrbough** [comment]
@webmobiles awesome! Tested on v4.0.0?

**Comment by webmobiles** [comment]
@emilyrohrbough v4.0.2 my best combination of packages:

  "dependencies": {
    "apollo-client": "^1.9.3",
    "apollo-test-utils": "^0.3.2",
    "graphql-tools": "^1.2.3",
    "jwt-decode": "^2.2.0",
    "react": "^16.0.0",
    "react-apollo": "^1.4.16",
    "react-dom": "^16.0.0",
    "react-redux": "^5.0.6",
    "react-router": "^4.2.0",
    "react-router-dom": "^4.2.2",
    "react-scripts": "1.0.14",
    "redux-form": "^7.0.4",
    "styled-components": "^2.2.0"
  },

**Comment by dmiranda2791** [comment]
Hi 🙂! Does v2.6.1 have support for React 16?

**Comment by timdorr** [comment]
Use 3.2.0. It's the same as 2.6.1 without the deprecated features. If you don't get warnings from deprecations in your app, you can upgrade without any changes.

**Comment by dmiranda2791** [comment]
Great, thanks! 😃
