### ISSUE TITLE
Link component doesn't update the document.referrer

### ISSUE THREAD

**Issue by Iliyass** [ReactTraining/react-router#5564]
## Version
4.1.1
I'm using BrowserHistory as my history object and pass it to the Router component as `history` property as the docs referenced 
## Expected Behavior
If Link is using `pushState` it should update `document.referrer`
## Actual Behavior
Using Link component doesn't update the `document.referrer`

**Comment by timdorr** [comment]
This is expected behavior. It's just how the underlying pushState API works. A pushState doesn't count as a true navigation, so it does not set a referrer.

**Comment by Iliyass** [comment]
@timdorr thanks for your input, is there any alternative way change the document.referrer ?
My use case is that we heavily rely on Alexa ranking, we switched to React, but the ranking is dropping due to the pushState API and this doesn't update the document.referrer, so I'm stuck here to find an alternative solution updating the referrer.

**Comment by timdorr** [comment]
You would have to avoid using Link. It's how the standard is defined and is implemented at the browser level. There is no way to set this.

**Comment by Iliyass** [comment]
Thanks @timdorr
