### ISSUE TITLE
Invalid React peer dependency - react-router-redux and React 16

### ISSUE THREAD

**Issue by kim-knudsen** [ReactTraining/react-router#5565]
After updating to **React 16** - installing `react-router-redux@5.0.0-alpha.6` warns about invalid peer dependency.

```sh
npm install --save react-router-redux@next
npm WARN saveError Problems were encountered
npm WARN saveError Please correct and try again.
npm WARN saveError peer invalid: react@^15, required by react-router-redux@5.0.0-alpha.6
```

The `peerDependencies` declaration in `package.json` seems to be the issue.

```json
"peerDependencies": {
    "react": "^15"
}
```

**Comment by timdorr** [comment]
It's fixed on master, but hasn't been published yet. There are a few more things to get in there, but I'll try to publish an update soon.

**Comment by damianobarbati** [comment]
+1 😱

```
reax-form-sample@1.0.1 /Users/damz/Desktop/reax-form-sample
└─┬ react-router-redux@5.0.0-alpha.6
  └── react@15.6.2  extraneous
```

**Comment by webmobiles** [comment]
I'm using just react-router and redux separately,  must I use  react-router-redux ? what is for ?

**Comment by timdorr** [comment]
Nope, you don't have to use it at all.

**Comment by webmobiles** [comment]
thanks, i hope not be important ;-)
