### ISSUE TITLE
npm start error after git clone from github

### ISSUE THREAD

**Issue by Alexis374** [ReactTraining/react-router#5566]
## Version
4.1.1

## Test Case
https://codesandbox.io/s/n55VljYk7

## Steps to reproduce
1. `git clone https://github.com/ReactTraining/react-router.git`
2. run `lerna bootstrap`
3. run `npm start`
## Expected Behavior
run npm correctly
## Actual Behavior

ERROR in ./modules/components/App.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../../../packages/react-router-dom/BrowserRouter in /Users/enniu/toys/react-router/website/modules/components
 @ ./modules/components/App.js 9:21-80

ERROR in ./modules/ReactRouterDOMShim.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../../packages/react-router-dom in /Users/enniu/toys/react-router/website/modules
 @ ./modules/ReactRouterDOMShim.js 6:22-64
Child html-webpack-plugin for "index.html":
         Asset    Size  Chunks       Chunk Names
    index.html  560 kB       0
webpack: Failed to compile.

**Comment by timdorr** [comment]
Make sure you build all the other projects before attempting to build the website. It uses the local copy in the repo, not from npm.
