### ISSUE TITLE
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. Check the render method of `t`

### ISSUE THREAD

**Issue by meluyue** [ReactTraining/react-router#5567]
In the minified production build of React, we avoid sending down full error messages in order to reduce the number of bytes sent over the wire.

We highly recommend using the development build locally when debugging your app since it tracks additional debug info and provides helpful warnings about potential problems in your apps, but if you encounter an exception while using the production build, this page will reassemble the original text of the error.

The full text of the error you just encountered is:

Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. Check the render method of `t`

**Comment by timdorr** [comment]
This has nothing to do with React Router.

**Comment by NickyYo** [comment]
I think it does @timdorr , I now get this error when I started using the `<ConnectedRouter />` component the 'react-router-redux' is maintained in this repo....  If I use `<Router />` instead it works... the example and build is broken.

**Comment by NickyYo** [comment]
@meluyue I think this is because you're not working with react-router-redux@5.*
Install it `npm i react-router-redux@next`
