### ISSUE TITLE
When will be published the release of react-router-redux v5.0.0

### ISSUE THREAD

**Issue by hopefuture** [ReactTraining/react-router#5568]
I want to use react-router-redux, but it is an alpha. 
I want to know when the release will publish.
I hope to use the release version in the near future. Next month is best.
I find the react had published v16. The react-router-redu should publish v5.0.0

Thanks!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by timdorr** [comment]
Dupe of #5565
