### ISSUE TITLE
react-router not work with React 16.0.0 

### ISSUE THREAD

**Issue by threescales** [ReactTraining/react-router#5575]
![image](https://user-images.githubusercontent.com/15061441/31003106-77fed2c0-a4b3-11e7-8c1a-6079115c95ec.png)

react-v16.0.0
react-router-v1.0.2
It's baseRouters.js

![image](https://user-images.githubusercontent.com/15061441/31003201-f292977e-a4b3-11e7-8e20-d44d5be8228c.png)

**Comment by StorytellerCZ** [comment]
Updating to react-router v3.2.0 will solve the issue.

**Comment by threescales** [comment]
@StorytellerCZ I have resolved it.thx.It's right

**Comment by YasserKaddour** [comment]
Don't forget to close the issue :smile:
