### ISSUE TITLE
Schedule for React 16 Support?

### ISSUE THREAD

**Issue by Panoplos** [ReactTraining/react-router#5577]
## Version
5.0.0-alpha.6

We are planning a transition to React 16. Is there a schedule for 16 support by this module?

**Comment by timdorr** [comment]
No schedule exists for releases.

**Comment by Panoplos** [comment]
It is working as-is, so far. Have not tested SSR environment, though.

**Comment by hafeez1042** [comment]
After upgrading to react 16.0.0, on server I'm getting following error
``Warning: Failed prop type: Invalid prop `component` of type `object` supplied to `Route`, expected `function`.``
