### ISSUE TITLE
react-router-redux has a too narrow peerDependency on react 

### ISSUE THREAD

**Issue by laurensrouw** [ReactTraining/react-router#5581]
## Version
react-router-redux 5.0.0-alpha.6

## Test Case
n.a.

## Steps to reproduce
1. Create a new project with `react@16`, `react-router`, `react-router-dom` and `react-router-redux`.
2. Run `yarn install` to install all dependencies
3. Run `yarn check`

## Expected Behavior
The `yarn check` command exits succesfully

## Actual Behavior
The `yarn check` command exists with an error, complaining about a version mismatch between `react` and `react-router-redux` as shown below

    error "react-router-redux#react@^15" doesn't satisfy found match of "react@16.0.0"
    error Found 1 errors.

Looking through the commit history it seems that the peerDependency was loosened for all packages with the react-router 4.2.0 release (https://github.com/ReactTraining/react-router/commit/94e68fdca73ae522a2edff3f8e301f4a28181dd5), but the react-router-redux package was never updated and the version that is published to npmjs.org still contains the old strict peerDependency.

This is causing problems with our CI that runs `yarn check` as part of the build process.

**Comment by timdorr** [comment]
We'll publish a release with updated peerdeps soon.

**Comment by AdamBoxall** [comment]
Any ETA on when the release will happen @timdorr?

**Comment by timdorr** [comment]
Nope.
