### ISSUE TITLE
Create CodeSandbox examples

### ISSUE THREAD

**Issue by CompuIves** [ReactTraining/react-router#5582]
React-router is one of the [most used dependencies on CodeSandbox](https://codesandbox.io/search?refinementList%5Bnpm_dependencies.dependency%5D%5B0%5D=react-router-dom&page=1). This week I also saw that the sandbox by @pshrmn (https://codesandbox.io/s/vVoQVk78) passed the 1000 forks.

I started to think about this and I think it would be beneficial for react-router to have sandboxes of the official examples and link them in the documentation. This would allow everyone to play with the given examples and use one of the examples as a way to give an easy reproduction if they find an issue. It would also help users that search for react-router examples on CodeSandbox, because the examples cover a lot of use cases and questions.

I'd love to open a PR for this, but I first wanted to know your thoughts. I can make the sandboxes automatically stay in sync with the examples on the website and on GitHub. This means that if you change the file in Git it will be automatically reflected in CodeSandbox.

I'm curious what you think, I can open a PR if you're interested 😄 .

**Comment by timdorr** [comment]
Is the syncing something we need to manage, or would you do so on your end? If it's all on you, I have no problem doing nothing! 😄

**Comment by CompuIves** [comment]
The syncing will work the same like we do with Redux. So this means that the source of truth is in the git repository. For every request to the sandbox we check if the commit sha has changed, and sync if it has.

I'll open a PR today! 😄

**Comment by timdorr** [comment]
Closing in favor of keeping the discussion in #5586
