### ISSUE TITLE
NavLinks with parentheses in the path do not set active className

### ISSUE THREAD

**Issue by esiegel** [ReactTraining/react-router#5584]
The active link for NavLinks are not created for paths that have parentheses.  It seems that the underlying regex that is generated by path-to-regex does not escape the parentheses in the generated regex and instead interprets it as a match group.  Notice in the example how the active classname is not set for the about component.

## Version
4.1.1

## Test Case
https://codesandbox.io/s/n55VljYk7

## Steps to reproduce
Create a NavLink component whose path has parentheses, ie `/some/path (1)`.

## Expected Behavior
When the component is routed to and rendering the active classname should be added.

## Actual Behavior
The classname is missing.

I wasn't sure if this was expected behavior in the underlying path-to-regex, so I figured it'd be best to ask here first.

**Comment by esiegel** [comment]
Oops, didn't save the Test Case:

https://codesandbox.io/s/qqov6y0w3q

**Comment by pshrmn** [comment]
If you want to submit a PR for this, I think that you would need to modify [the value passed to `path`](https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/modules/NavLink.js#L23) by escaping any of `path-to-regexp`'s ["special" characters](https://github.com/pillarjs/path-to-regexp/issues/76#issuecomment-219085357).

**Comment by esiegel** [comment]
Thanks for the info.  I did a poor job searching `path-to-regexp's` issue list.  I'll try my hand at tackling this issue.  Should be easy enough.
