### ISSUE TITLE
react-router is not displaying NotFound (404) when no routes matches

### ISSUE THREAD

**Issue by phun-ky** [ReactTraining/react-router#5587]
## Version
4.1.1

## Test Case
https://gist.github.com/phun-ky/84cbfa1143768ec6639d7e425b0ad79c

## Steps to reproduce
Use given setup in the proviced gist
## Expected Behavior
404 component displayed
## Actual Behavior
404 component not displayed

I am at wit's end here, whatever I try I can't get the NotFound (404) component to render. I see that in the DOM, all I get (when I am on a 404 page) is this:

    <div location="[object Object]" computedmatch="[object Object]"></div>

**Comment by pshrmn** [comment]
All of the direct children of a `<Switch>` are considered routes. It doesn't matter if the element is a `Route`, a `Redirect`, a `Whatchamacallit`, or a `div`. That means that when you have
```js
<Switch>
  <div>...</div>
</Switch>
```
The `<div>` will be treated as a pathless `Route` (meaning that it will always match).

**Comment by phun-ky** [comment]
@pshrmn cool, thanks! But with the updated gist: https://gist.github.com/phun-ky/84cbfa1143768ec6639d7e425b0ad79c

How can I just render the following routes without rendering `<HandleLogin>` ?

    <Route exact path="/callback" component={SomeComponent} />
    <Route exact path="/loginFailed" component={SomeComponent} />
    <Route exact path="/unauthorized" component={SomeComponent} />
    <Route exact path="/error" component={SomeComponent} />

**Comment by phun-ky** [comment]
Got it sorted. Thanks for the help anyway :)

**Comment by rimatla** [comment]
@phun-ky How?
