### ISSUE TITLE
V3 Support

### ISSUE THREAD

**Issue by Jony-Y** [ReactTraining/react-router#5588]
Hi,
I have a few issues that I cant seem to resolve with V4.
[https://stackoverflow.com/questions/46552850/react-router-4-defining-layout-routes-with-no-paths](url)
If you have a solution for my issue, please help.

My question is, if I stick to V3. Will there be continues support? as far as updating dependencies and such? Are you planing on maintaining both versions? or will V3 end up "deprecated" and the safe move would be to upgrade?

**Comment by timdorr** [comment]
V3 will be supported indefinitely.

**Comment by openjck** [comment]
Just to be crystal clear, it sounds like you mean full support including security updates. Is that correct?

**Comment by timdorr** [comment]
Yeah, although we've never had a security issue before.
