### ISSUE TITLE
Support Glamor's `css` prop on <NavLink>

### ISSUE THREAD

**Issue by fk** [ReactTraining/react-router#5593]
`<NavLink>` throws a warning when trying to use Glamor's `css` prop to style it:
https://github.com/ReactTraining/react-router/blob/08dfc5ec31aa5212166a9b4c03fa5e1584315c05/packages/react-router-dom/modules/NavLink.js#L49

`PropTypes.oneOfType([PropTypes.string, PropTypes.object])` would be ✌️

**Comment by timdorr** [comment]
This isn't correct. className always has to be a string. This is a React rule.

**Comment by fk** [comment]
My bad, sorry for the noise! FWIW just learned from someone way smarter than me that this might be a bug in glamor.

**Comment by bogdansoare** [comment]
I have the same issue.

@timdorr actually className can be object. The returned object from Glamor's `css` has a [`toString`defined](https://github.com/threepointone/glamor/blob/5c03f879d66313bcc7c1ad6166b9f855d86a9f21/src/index.js#L235-L237 )  which the object initializer spec says [toString is called on](http://www.ecma-international.org/ecma-262/6.0/#sec-topropertykey) if a computed property key is an object. Thus it's like calling css({}).toString()), which yields the css classname.

If you try using the `css` function from glamor on the normal Link component, you would see that there isn't any issues, the issues appears with NavLink.

**Comment by jeffutter** [comment]
I have run into this issue as well. I tried digging up the prop type definition for the build in react components but can't find it for the life of me.

**Comment by jsonmaur** [comment]
Same issue, this should not be closed. `Link` works just fine when passing a glamor object to `className`--React calls `.toString` for it under the hood. Thus `NavLink` should follow the same behavior and pass it through.
