### ISSUE TITLE
New version of eslint-config-airbnb gives error on <Link to="/path">

### ISSUE THREAD

**Issue by plhosk** [ReactTraining/react-router#5598]
```
react-router-dom@4.2.2

eslint-config-airbnb@^16.0.0
eslint@^4.8.0
eslint-plugin-jsx-a11y@^6.0.2
eslint-plugin-import@^2.7.0
eslint-plugin-react@^7.4.0
```
When I use ```<Link to="/path">``` I get the following linting error:

[eslint] The href attribute is required on an anchor. Provide a valid, navigable address as the href value. (jsx-a11y/anchor-is-valid)
https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/docs/rules/anchor-is-valid.md

**Comment by pshrmn** [comment]
From the linked page, you need to [configure the rule](https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/docs/rules/anchor-is-valid.md#rule-details). Specifically, this line implies that you should add `to` to the `specialLink`:

> For the components option, these strings determine which JSX elements (always including <a>) should be checked for the props designated in the specialLink options (always including href).

Alternatively, you could just not include `<Link>` in the `components` and be confident knowing that React Router always renders an anchor with an `href`.
