### ISSUE TITLE
Add example for ServiceWorker reload on next user navigation

### ISSUE THREAD

**Issue by stereobooster** [ReactTraining/react-router#5602]
Complicated story. There is this [practice with ServiceWorkers to show toast](https://github.com/facebookincubator/create-react-app/pull/2426) if new content is available and suggest user to reload browser. I see simpler solution here, instead of showing this message simply reload browser on next navigation. I suppose it is easy to do custom link component, which will render simple `<Link>` by default and in case of new content in SW it will render `<a>`, which will trigger reload in browser when clicked. WDYT?

**Comment by timdorr** [comment]
A PR would be better to discuss this.
