### ISSUE TITLE
Uncaught TypeError: Cannot read property 'func' of undefined

### ISSUE THREAD

**Issue by maixing** [ReactTraining/react-router#5605]
React upgrade to 16.0.0 react-router3, <Uncaught TypeError: Cannot read property reported'func'of undefined>, react-router3 source code, use the React.PropTypes, the react16.0.0 has been abandoned, starting with prop-types. Will react-router3 update?

**Comment by timdorr** [comment]
Use the latest 3.x version of react-router (3.2.0). This is working.

**Comment by maixing** [comment]
Thanks for problem solving

**Comment by sg28** [comment]
@timdorr thank you versioning seems to be a great issue here

**Comment by nafisahmedkhan9** [comment]
I have same issue in this code:
import React from 'react';
import ReactDOM from 'react-dom';
import { Router, Route, hashHistory} from 'react-router'

import Archives from './modules/Archives';
import Layout from './modules/Layout';
import Featured from './modules/Featured';
import Settings from './modules/Settings';
console.log('hi');
ReactDOM.render((
    <Router history={hashHistory}>
        <Route exact path='/' component={Layout}>
            <Route exact path='/featured' component={Featured}/>
            <Route exact path='/archives/:id' name='archives' component={Archives}/>
            <Route exact path='/settings' name='settings' component={Settings}/>
            </Route>
    </Router>
    ),document.getElementById('app'));

**Comment by nafisahmedkhan9** [comment]
In ReactDOM.rendere i have used router

**Comment by zwp1994** [comment]
[](url)

**Comment by rijulzalpuri** [comment]
:+1:

**Comment by larrystone** [comment]
I am using react-router-dom 4 and I have the issue above, any ideas how I can solve it?
