### ISSUE TITLE
Feature Request: Immutable react-router-redux

### ISSUE THREAD

**Issue by bristoljon** [ReactTraining/react-router#5606]
We use `combineReducers` from `redux-immutable` which isn't playing nicely with the latest `v5` alpha of `react-router-redux`.

I was hoping to be able to just let the `router` slice of the state tree stay as a plain JS object seeing as all interactions with it will be via `react-router-redux` and there aren't any performance gains from using immutable props without refactoring all the components but that doesn't work.

The problem occurs where the reducer uses `Object.assign` to merge the new location payload with the state. I get ` One of the sources for assign has an enumerable key on the prototype chain. Are you trying to assign a prototype property? ...`.

Anyway, it would be great if you could import an immutable reducer and selectors e.g.

`import { routerReducer } from 'react-router-redux/immutable'`

I forked the repo [here](https://github.com/bristoljon/react-router/commit/d939b6bd6b4a748f0daeb37527b39cd7583e7327) and added the above exports which allowed me to do:

`import { routerReducerImmutable } from 'react-router-redux'`

This appeared to work at first and I was able to dispatch the `LOCATION_CHANGE` actions using the `push()` action creator. However this was using `npm link` and when I moved the code into it's [own repo](https://github.com/bristoljon/react-router-redux) on github (which I had to do because it is nested in packages), my app crashes on `push`. It's really hard to work out why, the `CALL_HISTORY_METHOD` appears to hit the middleware but it doesn't hit an error, just crashes. This is react-native app by the way.

Anyway, are there any plans to add this? I will try to get my fork working and tidied up for a pull request but thought it was worth raising an issue to see if there is much support for this feature and whether I can get any help with it.

**Comment by timdorr** [comment]
The old instructions still apply: https://github.com/reactjs/react-router-redux#what-if-i-use-immutablejs-or-another-state-wrapper-with-my-redux-store

**Comment by bristoljon** [comment]
@timdorr ahh thanks dude. Saved me a lot of head scratching

**Comment by bristoljon** [comment]
Actually I have a follow up question. How come you don't provide the full history implementation as a redux reducer? i.e. why are there 2 sources of truth when using `react-router-redux`?

Seems like if all the history state logic was handled inside redux by a reducer there would be no need for a separate history object and `<ConnectedRouter/>` could just receive it as a prop via `connect` and pass it down via context as before.

The history props navigation actions could be dispatch wrapped action creators providing the same API to the components but negating the need for any middleware to keep the 2 places in sync..

**Comment by bristoljon** [comment]
Also, it looks like the old instructions don't apply. There is no `syncHistoryWithStore` or `selectLocationState` option to provide your own selector. Neither string occurs anywhere in my node_modules. Although, looking at the source, nothing actually uses `store.location` anyway so I guess just providing your own immutable reducer is enough but that kind of leads me back to the point above.. If the store can't be relied on as a source of truth, what's the point of `react-router-redux`?

**Comment by 2Pacalypse-** [comment]
I have the same question(s) as bristoljon. Old instructions definitely don't still apply and some clarification would be appreciated.

**Comment by bristoljon** [comment]
@2Pacalypse- The second point in the old instructions does still apply but you can ignore the first. All you need to do is provide an immutable reducer and it should all work. Here's what I'm using:

```
// routerReducer.js

import { fromJS } from 'immutable'

const LOCATION_CHANGE = '@@router/LOCATION_CHANGE'

const initialState = fromJS({
  location: null
})

export function routerReducer(state = initialState, { type, payload } = {}) {
  if (type === LOCATION_CHANGE) {
    return state.set('location', fromJS(payload))
  }

  return state
}
```

**Comment by 2Pacalypse-** [comment]
@bristoljon Thanks for the help, but I'm actually more concerned with the first point :P

If I remember correctly now, `react-router-redux` expected your state being in certain shape, something like `state.routing.locationBeforeTransitions` which was terribly verbose. You could change that though, as explained in that first point, by using `selectLocationState`. And since I can't find a single mention of `selectLocationState` in the new `react-router-redux` repo, I assume that's not possible anymore? I'm not really sure what I'm missing here, and some documentation on the new version of this library would be quite helpful.

**Comment by bristoljon** [comment]
I'm not sure about previous versions but appears that this one doesn't use the `state.routing` data at all. It only keeps it updated with the history state and provides a mechanism to update both by dispatching actions. Essentially the history (memoryHistory, browserHistory or whatever) is the source of truth so there is no need to provide a selector and it's up to you what your reducer does with  `LOCATION_CHANGE` actions
