### ISSUE TITLE
Route doesn't match the link

### ISSUE THREAD

**Issue by DongShelton** [ReactTraining/react-router#5609]
## Version
react: 16.0.0
react-dom: 16.0.0
react-router-dom: 4.2.2

## Test Case
https://codesandbox.io/s/myo0pnpoqj

## Steps to reproduce
Clike the mike link or jerry link.

## Expected Behavior
It should show "mike" or jerry.

## Actual Behavior
It always show "home"

**Comment by timdorr** [comment]
You have two Routers. You need to use one (you should only ReactDOM.render() once) or need to use a plain Router instance (not BrowserRouter) and share a history instance between them.
