### ISSUE TITLE
Migrate from React.PropTypes

### ISSUE THREAD

**Issue by bchecket** [ReactTraining/react-router#5610]
Will you be updated React-Router to be compliant with React v15.5.0+ by using the new prop-types and create-react-class packages?

https://reactjs.org/blog/2017/04/07/react-v15.5.0.html

Migrating from React.PropTypes
Prop types are a feature for runtime validation of props during development. We’ve extracted the built-in prop types to a separate package to reflect the fact that not everybody uses them.
In 15.5, instead of accessing PropTypes from the main React object, install the prop-types package and import them from there:

Migrating from React.createClass
When React was initially released, there was no idiomatic way to create classes in JavaScript, so we provided our own: React.createClass.
Later, classes were added to the language as part of ES2015, so we added the ability to create React components using JavaScript classes. Along with functional components, JavaScript classes are now the preferred way to create components in React.
For your existing createClass components, we recommend that you migrate them to JavaScript classes. However, if you have components that rely on mixins, converting to classes may not be immediately feasible. If so, create-react-class is available on npm as a drop-in replacement:

**Comment by timdorr** [comment]
We already are doing this. This was done in the [3.0.4 release](https://github.com/ReactTraining/react-router/releases/tag/v3.0.4) and [4.1.1 release](https://github.com/ReactTraining/react-router/releases/tag/v4.1.1)
