### ISSUE TITLE
warning "react-router-redux@5.0.0-alpha.6" has incorrect peer dependency "react@^15".

### ISSUE THREAD

**Issue by monkseal** [ReactTraining/react-router#5611]
## Version
react-router-redux@5.0.0-alpha.6

## Steps to reproduce
```
yarn add react@^16.0.0
yarn add react-router-redux@next
yarn check
```

## Question
Does react-router-redux work with React 16? Everything is working for me locally in an app I'm working on.

**Comment by homer0** [comment]
I have the exact same issue. The weird thing is the last commit on the `package.json` ([link](https://github.com/ReactTraining/react-router/commit/d845c201197211bc918dbecee8943a8156065059)), it says "Publish", but the `5.0.0-alpha.6` doesn't have those changes.

**Comment by Havret** [comment]
+1

**Comment by timdorr** [comment]
I'll publish an update soon.

**Comment by monkseal** [comment]
was this released?

**Comment by homer0** [comment]
@monkseal nop

**Comment by gravitycode** [comment]
+1

**Comment by lrn2prgrm** [comment]
? what are we supposed to do?

**Comment by mistermendez** [comment]
why is this closed? I am still getting this error.

**Comment by homer0** [comment]
@mistermendez I haven't tried yet, but I think the last alpha release (`5.0.0-alpha.8`) fixed the warning.

**Comment by mistermendez** [comment]
@homer0 thx! that worked
