### ISSUE TITLE
browserHistory.push() intermittently fails

### ISSUE THREAD

**Issue by viridia** [ReactTraining/react-router#5613]
I have many calls to browserHistory.push() in my code, and most of them work reliably. However, in some places in the code a call to push() will work some cases and fail in other cases. No error is reported, but no navigation happens. Example:

```
browserHistory.push({
  pathname: '/pv/100',
  state: { selection: [101], autoScroll: true },
});
```
This code will sometimes fail, but if executed a second time will succeed.

I thought this might be a bug in my code or my configuration - but if that's the case, why does it work the second time?

Note: I don't use the withRouter() HoC because you can't inherit from a base class wrapped in a HoC. I use the browserHistory singleton everywhere consistently, including in my routing table.

## Version
3.0.5, 3.2.0

## Test Case
Happens very rarely, hard to isolate

## Expected Behavior
Navigation should occur.

## Actual Behavior
No change in the url, no error.

**Comment by timdorr** [comment]
Something else has to be going on outside of the system. Perhaps some browser extension? Without a reproducible test case, there isn't really much we can do here. It works consistently for us.
