### ISSUE TITLE
Screen reader still reading out validation messages from previous url

### ISSUE THREAD

**Issue by dagda1** [ReactTraining/react-router#5615]
I am using react-router-dom 4.1.1 and react-router-redux 5.0.0-alpha.6.

I have a validation summary that looks a bit like this:

```
<div aria-live="assertive">
  <div aria-hidden="false">
     <h2 tabindex="-1">There were some errors found on this form:</h2>
     <h3>Please fix the following errors</h3>
     <div>
        <ul>
          <li>
              <a " href="#contactDetails.email">
                 <span>Please enter a valid email address.</span>
              </a>
          </li>
        </ul>
      </div>
   </div>
 </div>
````

I am using `Switch` to render my routes
```
        <Switch>
          {routes.map(step =>
            <Route
              key={step.url}
              path={`${match.url}/${step.url}`}
              component={step.component}
            />
          )}
        </Switch>
```

The problem is that when I go to a new route using a push action `dispatch(push(url))`.

The screen reader is still reading out validation messages from the previous url in the ValidationSummary component that I outlined at the start because of the `aria-live` attribute.

I would have thought that the components were being destroyed, is react-router holding onto the view or anything like that which would make the component still in memory?

**Comment by timdorr** [comment]
Perhaps the reader doesn't behave well with React in general? We don't do anything out of whack that might keep a DOM node around. It could be how the reader is referencing the DOM node that prevents it from being cleared? Not sure, but it doesn't sound like anything we're doing wrong on our end.
