### ISSUE TITLE
Built react project shows blank page when I use <Switch>

### ISSUE THREAD

**Issue by hosseinsalemi** [ReactTraining/react-router#5617]
## Version
4.2.2

## Steps to reproduce
I'm using `react-scripts`.
1. run `react-scripts build`.
2. open `/build/index.html` in browser.

## Expected Behavior
I think Switch uses `location.pathname` instead of `match.path`. When remove `<Switch>` project run correctly.

## Actual Behavior
The `<Switch>` can't find correct path because `location.pathname` is `file:///path/to/index.html`. however `match.path` is `/`.

**Comment by timdorr** [comment]
You have to use a HashRouter with local files. Use create-react-app and start a server so you can use BrowserRouter.
