### ISSUE TITLE
Undocumented Switch behaviour

### ISSUE THREAD

**Issue by sz-piotr** [ReactTraining/react-router#5626]
I wanted to create a custom route component. It looked something like this
```javascript
const AuthRoute = props =>
  canAccess(props.user, props.path)
    ? <Route exact path={props.path} component={props.component} />
    : <Route exact path={props.path} component={Unauthorized} />
```
To my surprise it didn't work when i put it in a switch like this:
```javascript
const Routes = props =>
  <Switch>
    <AuthRoute path='/home' component={Home} user={props.user} />
    <AuthRoute path='/home/about' component={About} user={props.user} />
  </Switch>
```
When accessing `/home/about` neither `Home` nor `About` were rendered. What I found after examining the source was that the `Switch` component checks the `exact` prop on its children. This means that for my example to work i needed the `exact` prop on my AuthRoute component (which doesn't use it!).

Here is the relevant source code:
https://github.com/ReactTraining/react-router/blob/c3d453ee4eba703bf606a77f61ce08eac8a64d0a/packages/react-router/modules/Switch.js#L53

I would suggest adding some sort of information documenting that behaviour.

**Comment by timdorr** [comment]
If you have an idea for the documentation, please submit a PR.
