### ISSUE TITLE
Doc proposal: Code-splitting + server rendering

### ISSUE THREAD

**Issue by bertho-zero** [ReactTraining/react-router#5628]
> ## Code-splitting + server rendering
> We’ve tried and failed a couple of times. What we learned:
> 
> 1. You need synchronous module resolution on the server so you can get those bundles in the initial render.
> 2. You need to load all the bundles in the client that were involved in the server render before rendering so that the client render is the same as the server render. (The trickiest part, I think its possible but this is where I gave up.)
> 3. You need asynchronous resolution for the rest of the client app’s life.
> 
> We determined that google was indexing our sites well enough for our needs without server rendering, so we dropped it in favor of code-splitting + service worker caching. Godspeed those who attempt the server-rendered, code-split apps.

from here: https://reacttraining.com/react-router/web/guides/code-splitting/code-splitting-server-rendering

Did you try https://github.com/thejameskyle/react-loadable/ ? It works perfectly well.

**Comment by timdorr** [comment]
If you have a specific suggestion for the docs, a PR is best.
