### ISSUE TITLE
when use the browserHistory.push to change the url, the page do not re render!

### ISSUE THREAD

**Issue by Sailor20** [ReactTraining/react-router#5633]
when i user the browserHistory.push to change the url from http://localhost:3006/home/api/list  to 
http://localhost:3006/home/api/list?keyword=1,the page do not re render! what should i do?

thanks for first!

**Comment by timdorr** [comment]
See this guide: https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/guides/blocked-updates.md
