### ISSUE TITLE
Cannot find module './selectors' from 'index.js'

### ISSUE THREAD

**Issue by thoughtassassin** [ReactTraining/react-router#5639]
This is still broken. I simply have  "react-router-redux": "^5.0.0-alpha.7" specified in my dependencies and npm install. When I try to build my project it fails. On line 6 of index.js, it is looking for **var _selectors = require('./selectors');** It looks like that file is is /es. I think changing the require to require('./es/selectors) will fix it.

**Comment by jordie23** [comment]
Seeing the same thing from alpha-7

**Comment by timdorr** [comment]
It needs to be republished.

**Comment by thoughtassassin** [comment]
@timdorr How often does that happen?

**Comment by bytesnail** [comment]
what is the next time of republishing? @timdorr

**Comment by adomrockie** [comment]
why is this closed? This is a major problem blocking our release..

**Comment by timdorr** [comment]
Whenever I get to it. You're using alpha software. Don't do that in production.
