### ISSUE TITLE
Link with parenthesis does not get Active class

### ISSUE THREAD

**Issue by OllieJennings** [ReactTraining/react-router#5641]
Hi so this is more of a question.

When a url contains a parenthesis such as: `https://hydal.xyz/pricewatch/027357/intel-core-i7-7820x-(boxed)`

A link element `<NavLink to="/pricewatch/027357/intel-core-i7-7820x-(boxed)">link</NavLink>` will not be active, when on this page.

Is there anyway to make it active? would you have to use the `exact` prop to do this?

FYI using versions:
```
"react-router": "^4.2.0",
"react-router-dom": "^4.2.2",
```

**Comment by pshrmn** [comment]
#5596 fixes this (but has not been released yet). If you need this in the short term, I would probably copy that code into it's own module in your project (you just need to fix the imports).
