### ISSUE TITLE
Multiple nesting in the same router

### ISSUE THREAD

**Issue by kaueDM** [ReactTraining/react-router#5644]
## Version
`"react-router-dom": "^4.2.2"`

## Router Structure

```
<Router>
    <Switch>
        <Route exact path='/' component={Login} />
        <Home>
            <Switch>
                <Route exact path="/dashboard" component={Dashboard} />
                <Route exact path="/tasks" component={Tasks} />
                <Route exact path="/users" component={Users} />
                <Works>
                    <Switch>
                        <Route exact path="/works/all" component={workAll} />
                        <Route exact path="/works/active" component={workActive} />
                        <Route exact path="/works/done" component={workDone} />
                        <Route exact path="/works/stopped" component={workStopped} />
                        <Route exact path="/works/waiting" component={workWaiting} />
                    </Switch>
                </Works>

                <InfoTabs>
                    <Switch>
                        <Route exact path="/work/:uid/details" component={WorkDetails} />
                        <Route exact path="/work/:uid/tasklist" component={TaskList} />
                    </Switch>
                </InfoTabs>

                <Route path="*" render={() => {
                    return <Redirect to="/dashboard" />
                }} />

            </Switch>
        </Home>
        {/* Wildcard */}
        <Route path='*' component={E404} />
    </Switch>
</Router>
```

## Expected Behavior
Component `Home`: Header and sidebar for all components inside it;
Component `Works`: Tabs for all components inside it;
Component `InfoTabs`: Different tabs for `WorkDetails` and `TaskList`

## Actual Behavior
Using the structure above, i get the behavior expected for `Home` and `Works`, but the `InfoTabs` component is rendered inside `Works`. If i move anything under the first tabs group (`Works`), it will render the `Works`component instead.

 In this structure dashboard, tasks and works (and his children) are accessible

```
<Home>
    <Switch>
        <Route exact path="/dashboard" component={Dashboard} />
        <Route exact path="/tasks" component={Tasks} />
            <Works>
                <Switch>
                    <Route exact path="/works/all" component={workAll} />
                    <Route exact path="/works/active" component={workActive} />
                </Switch>
            </Works>
    </Switch>
</Home>
```

In this, dashboard and works (and his children) are accessible. If i try "/tasks", i'll get works instead
 
```
<Home>
    <Switch>
        <Route exact path="/dashboard" component={Dashboard} />
            <Works>
                <Switch>
                    <Route exact path="/works/all" component={workAll} />
                    <Route exact path="/works/active" component={workActive} />
                </Switch>
            </Works>
        <Route exact path="/tasks" component={Tasks} />
    </Switch>
</Home>
```

I found nothing about something similar. How can i achieve the expected behavior?
Thanks in advance.

**Comment by pshrmn** [comment]
You can't just throw every element into a `<Switch>`. The only direct children elements of a `<Switch>` should be `<Route>`s and `<Redirect>`s. Technically speaking, you can use any component, but you will most likely end up with unexpected behavior (`<Works>` inside of a `<Switch>` matches the same as a `<Route>` with no path, which is to say that it matches **every** location).

I would recommend looking at the [`<Switch>` render method](https://github.com/ReactTraining/react-router/blob/v4.2.2/packages/react-router/modules/Switch.js#L41) to get a better understanding of how `<Switch>` works. It is just a loop over the children and attempting to match them against the location.

**Comment by kaueDM** [comment]
Ok, so how can i implement what i want? I can't find examples or hints about how to do it.
