### ISSUE TITLE
Docs not updated

### ISSUE THREAD

**Issue by vinpac** [ReactTraining/react-router#5648]
At https://reacttraining.com/react-router/web/guides/server-rendering is not equal `server-rendering.md`.
I would PR this, but looks like it was just not deployed to website yet.

## Expected content
```
routes.some(route => {
  // use `matchPath` here
  const match = matchPath(req.path, route)
  if (match)
    promises.push(route.loadData(match))
  return match
})
```

## Actual content
```
routes.some(route => {
  // use `matchPath` here
  const match = matchPath(req.url, route)
  if (match)
    promises.push(route.loadData(match))
  return match
})
```

**Comment by timdorr** [comment]
I have no idea who or what updates them, but I believe it's a manual process. For now, just read the docs on Github.
