### ISSUE TITLE
Cannot find module './selectors' from 'index.js'

### ISSUE THREAD

**Issue by maxww** [ReactTraining/react-router#5649]
## Version
react-router-redux@next

error message 
Cannot find module './selectors' from 'index.js'
at Object.<anonymous> (node_modules/react-router-redux/index.js:6:18)

In the actual folder I don't see selectors.js either...

**Comment by timdorr** [comment]
Update to alpha.8

**Comment by maxww** [comment]
@timdorr it works now, thanks! should we keep "next" in our package.json or for now we change it to "5.0.0-alpha.8" to be safe?

**Comment by timdorr** [comment]
Keep it @next. I had the wrong dist-tags.
