### ISSUE TITLE
Scroll a long list page, then click item go to detail page and then click back won't render well on ios Safari

### ISSUE THREAD

**Issue by edwardfhsiao** [ReactTraining/react-router#5654]
## Version
4.1.1

## Test Case
https://github.com/edwardfhsiao/react-router-failing-test

## Steps to reproduce
Firstly, it has to be **Safari** on ios and has to be a very long list on the Home(list) page that allows you to **scroll down at the very bottom**.

Secondly, tap or click the item which takes you to the Show(detail) page, then just click **Back** and the rendering issue occured(**whole white screen**). However, if scroll it a bit, then the rendering will be normal.
## Expected Behavior
scroll to the bottom of the page and click the route and then click back, the previous page should not be changed.
## Actual Behavior
the previous page not rendering well.

## Note
1. ios has the issue.
2. Chrome does not have the issue. Only Safari does.
3. If the data(my example in repo is movielist) does not come from **network(ajax)**, is does not have the issue as well.

## Work around
My current work around is whenever I re-visit the home page I do a scroll page to the top

![image](https://user-images.githubusercontent.com/11728228/31935643-f379e140-b874-11e7-9fff-9af2f22afcd6.png)

![image](https://user-images.githubusercontent.com/11728228/31935683-0e15c302-b875-11e7-81b5-b705b4a52535.png)

![image](https://user-images.githubusercontent.com/11728228/31935749-37c429be-b875-11e7-8d5c-3d85f5d397c7.png)

**Comment by timdorr** [comment]
You've got a blocked update. See this guide: https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/guides/blocked-updates.md

**Comment by edwardfhsiao** [comment]
@timdorr I tried withRouter but it does not work. I don't think its a blocked updates case, because chrome does not have the problem, neither on mac Safari, only Safari on Ios does.

**Comment by edwardfhsiao** [comment]
well, ios11 Safari back does not trigger
```js
componentWillMount() {
    alert(1);
    this.props.setMovieList(null);
    this.props.fetchMovieList(`https://facebook.github.io/react-native/movies.json`);
  }

  componentWillReceiveProps({ app }) {
    alert(2);
    if (this.props.app.movieList == null && app.movieList != null) {
      this.setState({ isLoading: false });
    }
  }
```
not even I add 
```js
  window.onpageshow = function(event) {
    if (event.persisted) {
      window.location.reload();
    }
  };
```
It just use cache.

**Comment by lee1994522** [comment]
@edwardfhsiao Have you solved with this problem?

**Comment by edwardfhsiao** [comment]
@lee1994522 no, I did not

**Comment by lpkvadim** [comment]
I had a similar problem. I fix it by removing the css height properties from the app-container
