### ISSUE TITLE
react-router-redux Redirects no longer trigger an action to the reducer

### ISSUE THREAD

**Issue by NorfAlrin** [ReactTraining/react-router#5655]
## Version

react-router-redux@5.0.0-alpha.7 & react-router-redux@5.0.0-alpha.8

## Summary
Redirects in a route nolonger trigger an action to the reducer.

## Steps to reproduce
My routes setup.
```
const Routes = ({store}) => (
  <CoreLayout>
    <Switch>
      <Route exact={true} path='/' render={Routes.homeRedirect} />
      <Route path='/photos/:folder*' component={PhotoView} />
    </Switch>
  </CoreLayout>
)

Routes.homeRedirect = () => (
  <Redirect to='/photos' />
)
```

## Expected Behavior
In version alpha.6 both the initial page load and the redirect are sent to the reducer.
```
{
  type: '@@router/LOCATION_CHANGE',
  payload: {
    pathname: '/',
    search: '',
    hash: ''
  }
}
```
```
{
  type: '@@router/LOCATION_CHANGE',
  payload: {
    pathname: '/photos',
    search: '',
    hash: '',
    key: 'mswocw'
  }
}
```

## Actual Behavior
With version alpha.7 and 8 the only initial page load is sent to the reducer
```
{
  type: '@@router/LOCATION_CHANGE',
  payload: {
    pathname: '/',
    search: '',
    hash: ''
  }
}
```

**Comment by timdorr** [comment]
Other than build tooling updates and a relaxed React peer dep, nothing was changed between alpha.6 and alpha.8. Was anything changed in your app when upgrading?

**Comment by NorfAlrin** [comment]
I know I had a look look through the commits to see if I could pinpoint the
problem.

If I downgrade to alpha.6 then I get the expected result, upgrading results
in the problem surfacing again.

I'll try to put together an example tonight to reproduce the problem.


On 24 Oct. 2017 10:08 pm, "Tim Dorr" <notifications@github.com> wrote:

Other than build tooling updates and a relaxed React peer dep, nothing was
changed between alpha.6 and alpha.8. Was anything changed in your app when
upgrading?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ReactTraining/react-router/issues/5655#issuecomment-339002548>,
or mute the thread

**Comment by sturzynski** [comment]
Experiencing this issue as well. 

Connected Router beings listening to history in componentDidMount and react-router Redirect performs the history push in componentDidMount as well. Because componentDidMount is called on children before the parent, there is a moment where a Redirect pushes a new history but the Connected Router is not yet listening to history.

**Comment by eKazim** [comment]
I have the similiar problem.
In my case, action `@@router/LOCATION_CHANGE` triggered twice with different pathname in wrong order: first, with pathname that is equals to `Redirect to` property, and then with pathname that equals `Redirect from` property. So reducer receives wrong last location.
P.S. i using React 16 and alpha.8 version of react-router-redux. Maybe this problem caused by new React version?

**Comment by sturzynski** [comment]
Can confirm moving `this.unsubscribeFromHistory = history.listen(this.handleLocationChange);
` from ConnectedRouter componentDidMount to componentWillMount fixes this issue

**Comment by boba-keyost** [comment]
Or moving  this.handleLocationChange(history.location); to componentDidMount

**Comment by Iuriy-Budnikov** [comment]
The same issue in 5.0.0-alpha.7 and 5.0.0-alpha.8.

**Comment by timdorr** [comment]
@sturzynski Can't do that because of #5203, which solves an SSR memory leak. We have to keep listening in cDM. 

@boba-keyost That seems like it might also be wrong, as we want to have the redux state ready for the component *before* it renders the rest of the tree. cWM lets us set this ahead of time, since we're near the top of the tree at this point.

I'm not sure what a good solution would be here. Can we get a repro together on codesandbox.io?

**Comment by boba-keyost** [comment]
Maybe you need to check if loaction was changed between cWM and cDM and if so, trigger location change action.
It would make sense because location was changed.

**Comment by sturzynski** [comment]
@timdorr Issue is reproduced there https://codesandbox.io/s/kmyj73qrr7

**Comment by artalar** [comment]
@sturzynski why u use ConnectedSwitch? Default Switch works fine.

I have same trouble - Redirect changle path, but not trigger action => not rerender component. I solve it by wrap every component when i have `routing` to Route.

@NorfAlrin try to replace <Routes /> to <Route component={Routes}/>

**Comment by valentin93** [comment]
A similar problem.
After it rolled back to 5.0.0-alpha.6 there is no problem

**Comment by elitenoire** [comment]
I have the same problem too. LOCATION_CHANGE action isn't triggered when using Redirect.
my version is 5.0.0-alpha.8.
Please any new fix or walk around?

**Comment by yoavniran** [comment]
joining in. upgrading to alpha.7 or 8 breaks my UI. downgrading back to 6 solves the issue.
without delving into what changed I can see that the location change dispatch happens too late compared to how it was in the previous version.

**Comment by maxbates** [comment]
Plus one's aren't helpful, but me too. This is preventing our migration to react 16, since it's an invalid peer dependency.

**Comment by codler** [comment]
Tried to downgrade from alpha 8 to 6, but the problem still exists, I never see the new LOCATION_CHANGE in middleware

**Comment by RyotaSugawara** [comment]
Downgraded alpha8 to alpha6 and still exists same problem.
How can we detect redirect route in server side?

**Comment by jpeyper** [comment]
Downgrading to alpha.6 did fix the issue for me.

For those who it did not work for, just ensure you don't have your version set to still grab alpha.8, in your package.json, `"react-router-redux": "5.0.0-alpha.6"` instead of `"react-router-redux": "^5.0.0-alpha.6"` (not the *^*)

**Comment by EdwardSalter** [comment]
I have also just come across this issue and downgrading to alpha.6 also worked for me.
As a workaround you could also add in a nasty hack to push the new route after a timeout:
```js
componentDidMount () {
    setTimeout(() => {
      this.props.redirectToLogin()
    }, 200)
  }
```

**Comment by Iuriy-Budnikov** [comment]
I removed BrowserRouter from ConnectedRouter and dispatch works well again! Maybe it will helps somebody.

**Comment by timdorr** [comment]
Alpha 9 is up. We'll get this right at some point...

**Comment by talhamuhammadashraf** [comment]
yes that was problem with version
