### ISSUE TITLE
"active" class broken again with "react-redux" and "react-router-4".

### ISSUE THREAD

**Issue by johnunclesam** [ReactTraining/react-router#5658]
## Version
```
"react-redux": "~5.0.6",
"react-router-dom": "^4.2.2",
```

Active class on `NavLink` is **not working again*** (*https://github.com/ReactTraining/react-router/issues/3536, https://github.com/ReactTraining/react-router/pull/3430, https://github.com/react-boilerplate/react-boilerplate/issues/993) if I use this:

`export default connect(mapStateToProps)(Navbar);`.

**It is working again** if I use this instead:

`export default connect(mapStateToProps, null, null, { pure: false })(Navbar);`

Why? Is this (https://github.com/ReactTraining/react-router/pull/3430) a fix for this problem? Is this a problem? Using `{pure: false}` am I stroggling down performances?

**Comment by timdorr** [comment]
See this guide: https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/guides/blocked-updates.md

**Comment by johnunclesam** [comment]
@timdorr, can you answer on this subsequent question? https://github.com/ReactTraining/react-router/issues/5660
