### ISSUE TITLE
"React does not recognize the `staticContext` prop on a DOM element"

### ISSUE THREAD

**Issue by arempe93** [ReactTraining/react-router#5665]
## Version
4.2.2

## Test Case
https://codesandbox.io/s/2vp8w3rx1r

Click the link to "Course 1" and open browser console. See React-thrown error.

## Steps to reproduce
1. Apply `withRouter` to a `<Link />` element
2. Inspect console

## Expected Behavior
The `staticContext` prop is not passed to the `<a />` element, but is caught similar to `match`, `history`, etc

## Actual Behavior
The `staticContext` prop is passed to the `<a />` element causing a console error

**Comment by timdorr** [comment]
You should do what NavLink does and wrap it in a Route inside CourseLink: https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/modules/NavLink.js

**Comment by yamsellem** [comment]
@timdorr the documentation give this code as a sample:

```
  <Router>
    <div>
      <ul>
        <li>
          <Link to="/">Home</Link>
        </li>
        <li>
          <Link to="/about">About</Link>
        </li>
        <li>
          <Link to="/topics">Topics</Link>
        </li>
      </ul>

      <hr />

      <Route exact path="/" component={Home} />
      <Route path="/about" component={About} />
      <Route path="/topics" component={Topics} />
    </div>
  </Router>
```

Does your answer indicate it's wrong? That this code will throw a `React does not recognize the `computedMatch` prop on a DOM element`?

May you precisely indicate what wrapping of NavLink you're referring to?
Pointing the entire file make it hard to properly understand what you're talking about.

Thanks.
