### ISSUE TITLE
getDefaultProps Warning using <Link /> in React 16 with 3.2 

### ISSUE THREAD

**Issue by stevenmusumeche** [ReactTraining/react-router#5667]
## Version
3.2

## Steps to reproduce
Use <Link> tag in React 16.

## Expected Behavior
No warning.

## Actual Behavior
Warning: getDefaultProps is only used on classic React.createClass definitions. Use a static property named `defaultProps` instead

**Comment by timdorr** [comment]
This is likely caused by something else. [v3 uses the `React.createClass` API](https://github.com/ReactTraining/react-router/blob/v3/modules/Link.js#L42), so it won't trigger this warning itself.
