### ISSUE TITLE
Code Splitting document is confusing

### ISSUE THREAD

**Issue by benjie** [ReactTraining/react-router#5668]
I was starting to read about using `react-loadable` with regard to performing server-side rendering with code-splitting; during my research I found the following document:

https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/docs/guides/code-splitting.md

It's great because it links to loads of resources to further my studies, however the code sample on that document is very confusing:

```js
import loadable from 'react-loadable';
import Loading from './my-loading-component';

// components load their module for initial visit
const About = (props) => (
  <Bundle load={loadAbout}>
    {(About) => <About {...props}/>}
  </Bundle>
)

const Dashboard = (props) => (
  <Bundle load={loadDashboard}>
    {(Dashboard) => <Dashboard {...props}/>}
  </Bundle>
)

class App extends React.Component {
  componentDidMount() {
    // preloads the rest
    loadAbout(() => {})
    loadDashboard(() => {})
  }

export default class App extends React.Component {
  render() {
    return <LoadableComponent/>;
  }
}
```

Questions this raises:

- Why is App defined twice? Presumably those definitions should be merged?
- I'm guessing `loadAbout` is something I define myself; what might that look like - is it simply `() => import('./About')` or does it need to hook into `react-loadable` somehow?
- What is the `Bundle` component? Where does it come from?
- Where is the `loadable` import used?
- Where is the `Loading` imported component used?
- What is the `loader` option mentioned in the text below the code snippet?

I might come back to this with a PR later once I've figured it all out :+1:

Thanks for the awesome library :pray:

**Comment by timdorr** [comment]
A PR is the best way to deal with docs issues. Critiques, while useful to know, don't really give us anything actionable to work with.

BTW, it looks like the issues stem from #5443. I'll see about fixing some of the App oddness.
