### ISSUE TITLE
https://reacttraining.com/react-router/ is broken down

### ISSUE THREAD

**Issue by Aaronphy** [ReactTraining/react-router#5672]
the offical website could not be open..

**Comment by KarandikarMihir** [comment]
Can confirm

**Comment by RinatMullayanov** [comment]
I have same problem, I get 520 Error.

**Comment by littlee** [comment]
I head to the md files
https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/docs/guides/basic-components.md

**Comment by timdorr** [comment]
It's working now. In the future, you can use the markdown files directly in the repo. They're used to build the website.
