### ISSUE TITLE
chevron character in Link

### ISSUE THREAD

**Issue by crg63** [ReactTraining/react-router#5677]
Hi I have problem with my Link. 

if write this code

```

const Project = () => (
	<div className="Projects">
		<Grid>
			<Row className="show-grid">
				<Col xs={10} xsOffset={1}>
					<div className="BlockPrincipal">
						<h2 className="banner">Projects</h2>
						{projects}
					</div>
					
					<div className="NextPage"> 
          				<Link to='/Presentation'>  </Link>   

          			</div>

          			<div className="NextPage">
          				<Link to='/Contact'> > </Link>   
          			</div>
				</Col>
			</Row>
		</Grid>
	</div>

```

is work this code he don't work 

```


const Project = () => (
	<div className="Projects">
		<Grid>
			<Row className="show-grid">
				<Col xs={10} xsOffset={1}>
					<div className="BlockPrincipal">
						<h2 className="banner">Projects</h2>
						{projects}
					</div>
					
					<div className="NextPage"> 
          				<Link to='/Presentation'> < </Link>    <!-- Here -->
          			</div>

          			<div className="NextPage">
          				<Link to='/Contact'> > </Link>   
          			</div>
				</Col>
			</Row>
		</Grid>
	</div>
```

it's a strange mistake no ? 

Message of error is 

> 
> Failed to compile
> ./src/component/js/Project.jsx
> Syntax error: Unexpected token (49:42)
> 
> ```
>   47 | 					
>   48 | 					<div className="NextPage"> 
> > 49 |           				<Link to='/Presentation'> < </Link>
>      |           				                            ^
>   50 | 
>   51 |           			</div>
>   52 | 
> ```
> This error occurred during the build time and cannot be dismissed.
> 

(Sorry I speak small English I learn)

**Comment by pshrmn** [comment]
This isn't a React Router issue. Your issue is that the code converting from JSX to `React.createElement` is interpreting the first angled bracket as a part of a JSX tag. You can fix this by replacing the text `<` with `{'<'}`.

**Comment by crg63** [comment]
I did not sit thoughtful. Thank you
