### ISSUE TITLE
Anchor links within same page not working on mobile

### ISSUE THREAD

**Issue by DianaPilat** [ReactTraining/react-router#5682]
## Version
4.0

I have a bug related to navigation within same page. The anchor links are working perfectly fine on the desktop, but when tested on mobile devices they navigate to the top of the page, no matter what link has been clicked. This issue is happening on actual mobile devices, because when I tested in chrome mobile simulator the links are working fine. Did a lot of research and not seem to understand why this behavior is happening. Please help.

My code: 

```
const Sidebar = ({ backUrl }) => (
  <div className="App-sidebar">
      <ul>
      <li><Link to="/my-projects"><span className="fa-Icon-MT-Emblem"/></Link></li>
      <li><Link to={backUrl}><span><MdArrowBack className = "fa-Icon" /></span></Link></li>
      <li><a href="#info"><span><MdInfoOutline className = "fa-Icon" /></span></a></li>
      <li><a href="#team"><span><MdPeopleOutline className = "fa-Icon" /></span></a></li>
      <li><a href="#schedule"><span><MdSchedule className = "fa-Icon" /></span></a></li>
    </ul>
  </div>
);
```

**Comment by timdorr** [comment]
If you're using a HashRouter, there may be some problems with a tags using hash links. If you switch it out to BrowserRouter, it should work OK.

**Comment by DianaPilat** [comment]
Thanks for your response, but I am actually using BrowserRouter in my app. The issue still persists.
