### ISSUE TITLE
Router Redirects Routes to Root on First Load, or Empty Cache Reload

### ISSUE THREAD

**Issue by ronaldroe** [ReactTraining/react-router#5683]
## Version
4.1.1

## Test Case
https://shapefitness.us/main/classes

## Steps to reproduce
1. Visit the page
2. See that on first load, you are redirected to the root.

Can also be reproduced after first visit by

1. Going to any page other than root.
2. Open Chrome Dev tools.
3. Click and hold the browser's refresh button and select "Empty Cache and Hard Reload"
4. See that you are redirected to the root

## Expected Behavior
The route is loaded

## Actual Behavior
User is redirected to root

I have searched far and wide, and I can't find anything like this issue anywhere. My routing code is below:
```
      <BrowserRouter basename={location}>

        <div>
          <Switch>
            <Route exact path="/" render={props => <Front {...this.state} {...props} openTrialForm={this.openTrialForm} />} />
            <Route exact path="/tos" render={props => <Terms {...this.state} {...props} openTrialForm={this.openTrialForm} />} />
            <Route exact path="/privacy" render={props => <Privacy {...this.state} {...props} openTrialForm={this.openTrialForm} />} />
            <Route exact path="/trialpass" render={props => <TrialPass {...this.state} {...props} openTrialForm={this.openTrialForm} PROSPECTS_ENDPOINT={PROSPECTS_ENDPOINT} SEARCH_PROSPECTS_BY_TERMS={SEARCH_PROSPECTS_BY_TERMS} />} />
            <Route exact path="/locations" render={props => <Locations {...this.state} {...props} openTrialForm={this.openTrialForm} API_BASE={API_BASE} />} />
            <Route exact path="/about" render={props => <About {...this.state} {...props} openTrialForm={this.openTrialForm} />} />
            <Route exact path="/classes" render={props => <Classes {...this.state} {...props} openTrialForm={this.openTrialForm} API_BASE={API_BASE} />} />
          </Switch>
        
          <Footer />

        </div>

      </BrowserRouter>
```
I've tried without the Switch as well. This is running on an Apache server. Initially, it showed a 404 error, but we discovered that was caused by PyroCMS, which is also on the server. Once we got the site moved to another directory, it started redirecting to the root.

**Comment by ronaldroe** [comment]
Turns out this wasn't a React Router issue at all, which I'm sure someone would have pointed out. It's HTML5 pushState and Apache.

You just need a .htaccess in the folder with the following, and it works like a champ.
```
<ifModule mod_rewrite.c>
  Options +FollowSymLinks
  IndexIgnore */*
  RewriteEngine On
  RewriteCond %{REQUEST_FILENAME} !-f
  RewriteCond %{REQUEST_FILENAME} !-d
  RewriteRule (.*) index.html
</ifModule>
```

**Comment by willbee28** [comment]
Where does this file go? Having a similar issue.
