### ISSUE TITLE
Add usage in reacttraining.com

### ISSUE THREAD

**Issue by wangyi7099** [ReactTraining/react-router#5686]
Have a feature request?
 The url [Code splitting](https://reacttraining.com/react-router/web/guides/code-splitting)

When I read to "Why bundle loader, and not import()?"

I saw the right guide says  
<pre><Bundle load={() => import('./something')}>
  {(mod) => ()}
</Bundle></pre>
So , I think we should add the changes corresponding to the Bundle class . The load function shoule be something like this
<pre>props.load().then((mod) => {
        this.setState({
          // handle both es imports and cjs
          mod: mod.default ? mod.default : mod
        });
      })</pre>
   to avoid making mistakes to the novice.

**Comment by wangyi7099** [comment]
<!--
Thank you for contributing!

 


Have a feature request?
 The url [Code splitting](https://reacttraining.com/react-router/web/guides/code-splitting)

When I read to "Why bundle loader, and not import()?"

I saw the right guide says  
`<Bundle load={() => import('./something')}>
  {(mod) => ()}
</Bundle>`
So , I think we should add the changes corresponding to the Bundle class . The load function shoule be something like this `props.load().then((mod) => {
        this.setState({
          // handle both es imports and cjs
          mod: mod.default ? mod.default : mod
        });
      })`   to avoid making mistakes to the novice.

**Comment by timdorr** [comment]
If you have a documentation suggestion, a PR is the best way to go about it. You can find the documentation in the repo.
