### ISSUE TITLE
Update to the react router redux recommendation

### ISSUE THREAD

**Issue by RyanAtViceSoftware** [ReactTraining/react-router#5689]
I'd recommended at a minimum updating the wording for this recommendation. Having router state in redux can be very valuable for both debugging and testing. Simple example is authorization flow. If you are a developer that is responsible for this feature then you would want to make sure that:

1) User goes to protected route
2) User is then redirected to sign in page

If this breaks you might also want to have the action log sent to the server for debugging. If you have no way of recording what the router is doing (or playing it back) then it can be very hard to test and support these types of routing scenarios.

**Comment by timdorr** [comment]
I'm not sure what you're referring to. But if you have a specific recommendation for the documentation, please use a PR.
