### ISSUE TITLE
a:hover style does not seem to be applied to Link or NavLink

### ISSUE THREAD

**Issue by amackintosh** [ReactTraining/react-router#5694]
## Version
    "react-router-dom": "^4.2.2",
    "react-router-redux": "^5.0.0-alpha.8",

## Test Case
n/a

## Steps to reproduce
1) Try this code:
```
        <div id="subnav">
          <div className="subnav_menu-item">
            <Link to="/records/create" className="subnav_link">Add a New Record</Link>
          </div>

          <Spacer />

          <div className="subnav_menu-item">
            <a
              className="subnav_link"
              onClick={(e) => e.preventDefault()}}>
              Show Inactive
            </a>
          </div>
        </div>
```
2) With this CSS:
```
#subnav {
  display: flex;
  flex-direction: row;
  justify-content: center;
  align-items: center;
  flex: 0;
  width: 100%;
  padding-top: 8.9rem;
  padding-right: 0.4rem;
  padding-left: 0.4rem;
  box-sizing: border-box;
  user-select: none;
  font-size: 2.3rem;
  line-height: 2.3rem;
  font-weight: 600;
  color: red; }

a.subnav_link:link {
  text-decoration: none; }

a.subnav_link:hover {
  cursor: pointer;
  color: gray; }

a.subnav_link:visited {
  color: red; }

a.subnav_link:active {
  color: red; }

.subnav_menu-spacer {
  margin-left: 0.4rem;
  margin-right: 0.4rem;
  color: gray; }
```

## Expected Behavior
The two links should have the same CSS applied to them.

## Actual Behavior
Link hover state doesn't seem to work when it has the exact same DOM appearance as a normal <a> tag.

Here is a GIF:
![report1](https://user-images.githubusercontent.com/25964567/32463129-b5850406-c2f0-11e7-9d27-533f45531b5c.gif)

Here is the DOM. They look the same, so I don't know how this is possible:
![report2](https://user-images.githubusercontent.com/25964567/32463190-ebf93426-c2f0-11e7-9db6-eebee2e2db45.gif)

![report3](https://user-images.githubusercontent.com/25964567/32463275-2ad0d848-c2f1-11e7-9c06-a70c54a252d2.png)

I tried using Link and NavLink and also `activeStyle` but it is the same behaviour.

**Comment by timdorr** [comment]
You have an extra squigly bracket on your onClick prop.

But this code works fine if you fix that: https://codesandbox.io/s/pqjwwz20q Something is going wrong on your end. It's not the library.

**Comment by amackintosh** [comment]
Hmm ok thanks. That squiggler was a rogue after I deleted the extra poop in there. SASS must be giving me some sass.

**Comment by amackintosh** [comment]
@timdorr I changed the style name to a unique name and it still doesn't work.

I think it has to do with this:
https://stackoverflow.com/questions/34381701/react-router-links-dont-get-visited-style

Radium also has all kinds of issues with it it looks like.

That sandbox probably works because it isn't really visiting the link in a real browser.
