### ISSUE TITLE
Documentation Site IE11

### ISSUE THREAD

**Issue by robertmess** [ReactTraining/react-router#5700]
Hi!

V4 is still not working on IE11 (version 11.0.9600.18816), on Windows 7 Enterprise Service Pack 1.
The doc doesn’t load: https://reacttraining.com/react-router/ .

It works fine on Chrome on the same machine.

I get the following error message: SCRIPT5022: Minified React error #109; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=109&args[]=e for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 

I’ve tried both in normal and Private mode. I’ve attached a snip below:

![untitled](https://user-images.githubusercontent.com/30634959/32495045-a22b2782-c3cc-11e7-8875-984a1c72ac03.png)

**Comment by timdorr** [comment]
We don't target IE on the docs site. You should use Chrome or Edge to browse them.

**Comment by robertmess** [comment]
@timdorr the problem is that I get the same thing on my own app when using V4. I thought that by giving the docs as an example would be easier to understand where the problem is.
