### ISSUE TITLE
generatePath is not exported from index.js

### ISSUE THREAD

**Issue by JAndritsch** [ReactTraining/react-router#5701]
## Version
4.1.1

## Test Case
https://codesandbox.io/s/jz97zr9z0v

## Steps to reproduce
1. `import { generatePath } from 'react-router';`
2. Try to use `generatePath`

## Expected Behavior
Importing `generatePath` from `react-router` gives me access to the `generatePath` function, which accepts a path template string and params and then returns a compiled path.

## Actual Behavior
`generatePath` is `undefined` because it is not part of the main exports in `index.js`.

**Comment by pshrmn** [comment]
#5661
