### ISSUE TITLE
'react-router' does not contain an export named 'hashHistory'.

### ISSUE THREAD

**Issue by EstebanBorai** [ReactTraining/react-router#5702]
imported `import { Router, Route, hashHistory } from 'react-router'` and I'm receiving this error.
I'm using **create-react-app** indeed!

**Comment by timdorr** [comment]
That API has changed in v4. You need to install v3, or update your usage for v4.

**Comment by kiransiluveru** [comment]
My react-router is of 4.3.1 version but still getting the above error. Please help me with this?
