### ISSUE TITLE
exact route match with child routes

### ISSUE THREAD

**Issue by Fredkr** [ReactTraining/react-router#5704]
I'm unsure if this is a bug, expected behaviour or just me not understanding how it should work...
Go ahead and close if the latter (but please explain ;)

## Version
4.1.1

## Test Case
https://codesandbox.io/s/qv2xqm18nj

## Expected Behavior
url '/tacos' => should render Tacos
url '/tacos/carnitas => should render Tacos and Carnitas
url '/foo' => should render 404
url '/tacos/foo' should render 404

## Actual Behavior
If exact is set on parent route the child route does not match, but 404 is rendered as expected.

 If exact is not set on parent, the child route match but so does for example "/tacos/foo" which should render 404.

**Comment by pshrmn** [comment]
With React Router, once a parent route has matched, there is no way to "unmatch" it. Instead, you need to include a 404 route in that component.

```js
const Tacos = ({ match }) => (
  <Switch>
    <Route exact path={`${match.url}` component={Taco} />
    <Route path={`${match.url}/carnitas`} component={Carnitas} />
    <Route component={Tacos404} />
  </Switch>
);

const App = () => (
  <Switch>
    <Route path='/tacos' component={Tacos} />
    <Route component={Root404} />
  </Switch>
);
```
