### ISSUE TITLE
Why can the Router only have one child?

### ISSUE THREAD

**Issue by selbekk** [ReactTraining/react-router#5706]
Well, basically - why is there a limit on `<Router />` having a single child? 

I tried looking at the code, but I couldn't really make sense of the why:

https://github.com/ReactTraining/react-router/blob/7cda4bda61dd039ee0de51841c3a64dd486c2ff8/packages/react-router/modules/Router.js#L54

Thanks for a great library by the way - I just want to understand why stuff is like it is.

**Comment by marekkobida** [comment]
@selbekk

https://reactjs.org/docs/glossary.html#jsx
https://reactjs.org/docs/context.html#parent-child-coupling

# 1.

```
const A = () => (
  <Router>
    <div>
      <h1>Index</h1>

      <Route path="/first" component={First} />
      <Route path="/second" component={Second} />
    </div>
  </Router>
);
```

Without `<div />` It will not work. `<div />` is one child.

# 2.

```
const Index = () => (
  <div>
    <h1>Index</h1>

    <Route path="/first" component={First} />
    <Route path="/second" component={Second} />
  </div>
);

const A = () => (
  <Router>
    <Index />
  </Router>
);
```

**Comment by timdorr** [comment]
Because `<Router>` belongs at the top of the component tree, near your `ReactDOM.render`. And because it just returns its children when rendering, that will go straight to up to the top. So, this:
```js
ReactDOM.render(
  <Router>
    <div />
    <div />
  </Router>
)
```
is basically this:
```js
ReactDOM.render(
  <div />
  <div />
)
```
And that's not valid input for `render`. So, we use `React.Children.only` to ensure we only have one child. (That's the main use case for that function)

**Comment by selbekk** [comment]
Ah that’s why! Thanks a ton for taking the time to explain it to me :-)

**Comment by nicolaerusan** [comment]
Also @selbekk thanks for asking it - had the same question myself & was nice to see it explained clearly here. Thanks for the clear response @timdorr!
