### ISSUE TITLE
Prompt in React 16 "Warning: A history supports only one prompt at a time"

### ISSUE THREAD

**Issue by fdev** [ReactTraining/react-router#5707]
## Version
react-router-dom 4.2.2
react 16.0.0

## Test Case
https://codesandbox.io/s/rrn9vww8pn

## Cause
There is a [breaking change in React 16](https://reactjs.org/blog/2017/09/26/react-v16.0.html#breaking-changes):

> When replacing `<A />` with `<B />`, `B.componentWillMount` now always happens before `A.componentWillUnmount`. Previously, `A.componentWillUnmount` could fire first in some cases.

In the Test Case above each page (Home, About, Topics) has a `Prompt` component. Because of the asynchronous nature of the React 16 lifecycle, history warns about two prompts being mounted at the same time:

> Warning: A history supports only one prompt at a time

At no point in time are there actually two `Prompt` components "on screen", but this warning does get triggered.

Issue https://github.com/ReactTraining/history/issues/536 is caused by the same breaking change.
Perhaps issue https://github.com/facebook/react/issues/11106 will provide an answer how to resolve this problem.

**Comment by timdorr** [comment]
I wonder if we can [wrap this line](https://github.com/ReactTraining/react-router/blob/master/packages/react-router/modules/Prompt.js#L64) in a `setTimeout` and call it a day?

**Comment by fdev** [comment]
@timdorr The problem is `componentWillUnmount` triggers _after_ `componentWillMount`. Your solution doesn't change that.

Using `setTimeout` in `componentWillMount` _might_ change the order, but I'm not sure you have any guarantee it will.

**Comment by timdorr** [comment]
Yeah, sorry, I had that backwards. What about changing to cDM? Will that work? I'm not a user of `<Prompt>`, so I'm not well-versed here.

**Comment by pshrmn** [comment]
`cDM` should work since it will be called after the `cWU` of the unmounting component.

**Comment by bora89** [comment]
We have the same issue, do you have some workaround guys?

**Comment by kbaird5** [comment]
The suggested workaround to setting 'when' to true in cDM works. Prompt.js should follow this suggestion and update its code to use cDM instead of cWM. This would get rid of the warning message.

**Comment by kateli** [comment]
i have the same issue too, it makes me headache . sos

**Comment by kateli** [comment]
i  solved it finnaly
![image](https://user-images.githubusercontent.com/8436428/42152164-e8a6250e-7e11-11e8-98f0-5c6133ea0ecd.png)
![image](https://user-images.githubusercontent.com/8436428/42152180-f2ab8530-7e11-11e8-8a07-ccce910a7c7d.png)
