### ISSUE TITLE
route url change but view not change

### ISSUE THREAD

**Issue by naxiaoguang** [ReactTraining/react-router#5717]
Think you found a bug?
======================
route path change but view not  

import React,{Component} from 'react';
import ReactDOM from 'react-dom';
import { Provider } from 'react-redux';
import { ConnectedRouter } from 'react-router-redux';

import { createStore, applyMiddleware, combineReducers } from 'redux';
import createHistory from 'history/createBrowserHistory';
import { routerReducer, routerMiddleware} from 'react-router-redux';

import { connect } from 'react-redux';
import { Switch } from 'react-router';
import LazyRoute from "./LazyRoute";
import SideBar from "./view/SideBar";
import View from "./components/View";
import TopBar from "./view/TopBar";

import "./css/index.css";

const history = createHistory();

const initialState = {
    isAuthenticated: false
};

const authReducer = (state = initialState , action) => {
    switch (action.type) {
        case 'AUTH_SUCCESS':
            return Object.assign({}, ...state, {
                isAuthenticated: true
            });
        case 'AUTH_FAIL':
            return Object.assign({}, ...state, {
                isAuthenticated: false
            });
        default:
            return { ...state };
    }
};

const store = createStore(
    combineReducers({ routerReducer, authReducer }),
    applyMiddleware(routerMiddleware(history)),
);

const ConnectedSwitch = connect(state => ({
    location: state.location ,
}))(Switch);

class PrivateRouteContainer extends Component {
    render() {
        let initPath = () => import('./view/Login') ;
        let sideBarWidth = 0 ;
        if(this.props.isAuthenticated){
            initPath = () => import('./view/Order') ;
            sideBarWidth = 1;
        }
        return(
            <div style={{width: "100%", height: "100%"}}>
                {this.props.isAuthenticated ?  <SideBar/> : ""}
                <View style={{float:"left", width:(window.total_width - sideBarWidth + "rem"),height:'100%'}}>
                    {this.props.isAuthenticated ?  <TopBar/> : ""}
                    <ConnectedSwitch>
                        <LazyRoute exact path="/" component={initPath}/>
                        <LazyRoute path="/about" component={() => import("./view/About")}/>
                        <LazyRoute component={() => import("./view/NotFound")}/>
                    </ConnectedSwitch>
                </View>
            </div>
        )
    }
}

const PrivateRoute = connect(state => ({
    isAuthenticated: state.authReducer.isAuthenticated ,
    history : history
}))(PrivateRouteContainer);

const AppContainer = ({ location }) => (
    <PrivateRoute />
);

const App = connect(state => ({
    location: state.location,
}))(AppContainer);

ReactDOM.render(
    <Provider store={store}>
        <ConnectedRouter history={history}>
            <App/>
        </ConnectedRouter>
    </Provider>,
    document.getElementById('root'),
);

"devDependencies": {
    "babel-plugin-syntax-dynamic-import": "^6.18.0",
    "babel-plugin-transform-object-rest-spread": "^6.26.0",
    "babel-plugin-transform-runtime": "^6.23.0",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-stage-1": "^6.24.1",
    "babel-runtime": "^6.26.0",
    "bable-loader": "0.0.1-security",
    "css-loader": "^0.28.7",
    "dll-link-webpack-plugin": "^2.0.3",
    "eslint": "^4.10.0",
    "eslint-config-react-tools": "^1.0.10",
    "extract-text-webpack-plugin": "^3.0.1",
    "happypack": "^4.0.0",
    "history": "^4.7.2",
    "html-webpack-plugin": "^2.30.1",
    "prop-types": "^15.6.0",
    "react-redux": "^5.0.6",
    "react-router": "^4.2.0",
    "react-router-dom": "^4.2.2",
    "react-router-redux": "^5.0.0-alpha.8",
    "react-table": "^6.7.4",
    "redux": "^3.7.2",
    "style-loader": "^0.19.0",
    "webpack": "^3.8.1"
  }

**Comment by pshrmn** [comment]
https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/guides/blocked-updates.md
