### ISSUE TITLE
Route path can be string or regexp

### ISSUE THREAD

**Issue by thorntonrp** [ReactTraining/react-router#5724]
The Route path property allows both string and regexp types as supported by the path-to-regexp library. But React reports a warning in the console because the proptype for the Route path property is described only as string.

**Comment by thorntonrp** [comment]
For example:
```
<BrowserRouter>
    <Switch>
        <Route path={/.*\.html/} component={Editor}/>
        <Route path={/.*/} component={DocumentList}/>
    </Switch>
</BrowserRouter>
```
While this works, I get the following error logged in my console:

```
proxyConsole.js:54 Warning: Failed prop type: Invalid prop `path` of type `regexp` supplied to `Route`, expected `string`.
```

**Comment by thorntonrp** [comment]
**Workaround:**
According to the path-to-regexp documentation, it looks like it will accept a regular expression inside the string path as long as the expression is inside parenthesis.

For example:
```
<BrowserRouter>
    <Switch>
        <Route path="/(.*).html" component={Editor}/>
        <Route path="/(.*)" component={DocumentList}/>
    </Switch>
</BrowserRouter>
```
It would be nice to be able to supply a regexp type, though without getting the warning.

**Comment by timdorr** [comment]
I'm not sure prop-types has support for a regexp type, which is the underlying issue.

**Comment by timdorr** [comment]
OK, so it's not built-in, but you can simply do `PropTypes.instanceOf(RegExp)`.

**Comment by timdorr** [comment]
I think we're not going to do this. Overriding the path-to-regexp library by accepting custom regexp's is going to have unintended side effects. Instead, please use strings and the inline regexp match features of path-to-regexp.

**Comment by bogdansoare** [comment]
@thorntonrp @timdorr How you write a regexp with path-to-regexp that doesn't match a specific route ?

For example every route besides */dashoard*
```
<Route
  path={/^((?!\/dashboard).)*$/}
/>
```

**Comment by timdorr** [comment]
I'd use a <Switch> with one <Route> for /dashboard and one without a path to catch everything else.

**Comment by bogdansoare** [comment]
@timdorr thanks for the solution
