### ISSUE TITLE
Feature Request: Make NavLink a Functional Component

### ISSUE THREAD

**Issue by ricardobrandao** [ReactTraining/react-router#5728]
I'm using Material Components Web in a project and in order to properly [initialise](https://github.com/material-components/material-components-web/tree/master/packages/mdc-tabs#mdc-tabs) a tab component I need a reference to the NavLink itself. Something like this would be helpful:
```C#
<NavLink
	...
	ref={control => (this.control = control)}
>
	...
</NavLink>
```

However, since NavLink is a stateless functional component, this won't work.

**Comment by timdorr** [comment]
We can just pass through the ref prop to the underlying Link.

**Comment by ricardobrandao** [comment]
Hi Tim, thanks for the quick reply.

Not sure how that would work because stateless functional components in React are given a **null**  value to the **ref** property. Furthermore, an exception is thrown when we pass a ref property to the component.

**Comment by timdorr** [comment]
`<Link>` is stateful.

**Comment by ricardobrandao** [comment]
Sorry, I misunderstood your suggestion. That won't work because I'm using the ```activeClassName```property:

```javascript
<NavLink
	exact
	activeClassName="mdc-tab--active"
	className="mdc-tab"
	disabled={this.props.disabled}
	to={this.props.to}
	ref={control => (this.control = control)}
>
	{this.props.children}
</NavLink>
```

**Comment by timdorr** [comment]
Yes, and `<NavLink>` uses [a `<Link>` under the hood](https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/modules/NavLink.js#L37-L43), that [is stateful](https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/modules/Link.js#L12). So, passing along the ref prop will carry through to the eventual DOM node.

**Comment by ricardobrandao** [comment]
Yes, that is correct. However, React still shows a warning ([see the console in this example](https://codesandbox.io/s/x3393l6224)). I'm just trying to get rid of this warning 😄

**Comment by timdorr** [comment]
Sorry, I meant to say we'd use an `innerRef` prop, like we do with `withRouter`'s `wrappedComponentRef`.

**Comment by ricardobrandao** [comment]
Ahah! Great! I had not yet realized [this](https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/modules/Link.js#L21) pattern yet 👍

**Comment by ricardobrandao** [comment]
Using ```innerRef``` is the proper way to do it. 

Thanks Tim.
