### ISSUE TITLE
Clarify react-router-redux' relationship to react-router-dom

### ISSUE THREAD

**Issue by fatso83** [ReactTraining/react-router#5733]
This is more of a feature/bug? request on the docs for `react-router-redux`. The current docs explicitly use imports from `react-router`, while the docs for react-router explicitly tells people _not_ to depend on the base package, but rather either the `react-router-dom` package or its native equivalent. That makes for confusion.

If the current approach is due to wanting to stress this package works for both native and dom, I'd rather see you have _two_ examples, rather than one example that contradicts advice given elsewhere in the other packages. So for the normal dom approach, go with  `var Route = require('react-router-dom').Route`.

edit: Updated to reflect that this is with reference to the `react-router-redux` package. Biproduct of sharing an issue tracker for multiple products :)

**Comment by timdorr** [comment]
If you have a suggestion for the documentation (including the README), please submit a PR.

react-router-dom just re-exports things from react-router, with some DOM-specific additions. It's fine to use react-router itself.

**Comment by fatso83** [comment]
I'll try to find the time to push a PR. Was just unsure of what it actually would contain, but now I do. thanks.
