### ISSUE TITLE
Time support for Redirect component

### ISSUE THREAD

**Issue by JulianKowalczuk** [ReactTraining/react-router#5743]
For now to switch route after a couple of seconds I have to use setTimeout and history prop in component exported using withRouter function. This force on me using component with state. It would be nice if Redirect component would fire after some time, not instantly after render.

**Comment by timdorr** [comment]
React components generally ignore time for the sake of declarative code. If you need to violate the declarative form, you should implement your own Redirect component. This isn't something that belongs in the library itself.
