### ISSUE TITLE
[BUG] RR5-a6 Go back button is not working with <Switch /> and <Route />

### ISSUE THREAD

**Issue by kopax** [ReactTraining/react-router#5747]
## Problem

I have a react app and I use `react-router-dom` 4.4.8.

My click on the go back button update the location but doesn't rerender the route component.

## Reproduction

I am using the following dependencies:

 - `react-redux`: **4.4.8**
 - `react-router-dom`: **4.2.2**
 - `react-router-redux`: **5.0.0-alpha.6**

This is how I have configured `<Provider />` and `<ConnectedRouter />`:

```jsx
import React from 'react';
import ReactDOM from 'react-dom';
import { Provider } from 'react-redux';
import createBrowserHistory from 'history/createBrowserHistory';
import { ConnectedRouter, routerMiddleware, LOCATION_CHANGE, routeReducer } from 'react-router-redux';
import { createStore, applyMiddleware, compose, combineReducers } from 'redux';

const initialState = {};
const history = createBrowserHistory();
const store = configureStore(initialState, history);


const middlewares = [
	routerMiddleware(history),
];

const enhancers = [
	applyMiddleware(...middlewares),
];

// If Redux DevTools Extension is installed use it, otherwise use Redux compose
/* eslint-disable no-underscore-dangle */
const composeEnhancers =
process.env.NODE_ENV !== 'production' &&
typeof window === 'object' &&
window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__ ?
  window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__ : compose;
/* eslint-enable */

const store = createStore(
	combineReducers({
	  route: routeReducer,
	}),
	fromJS(initialState),
	composeEnhancers(...enhancers)
);

ReactDOM.render(
	<Provider store={store}>
	  <ConnectedRouter history={history}>
	    <App />
	  </ConnectedRouter>
	</Provider>,
	document.getElementById('app')
);
```

This is how I have configured my `<Switch />`, `<Route />` and `<Redirect />`:

```jsx
<Switch>
      <Route exact strict key="home" path="/" component={Home} />
      <Route strict key="quickStart" path="/doc/getting-started/quick-start" component={QuickStart} />
 </Switch>
```

1. I navigate using `<Link to="/doc/getting-started/quick-start" />`
2. The location redirect me to `/doc/getting-started/quick-start` and the `<Switch />` is rendering the appropriate component
3. In Google Chrome, I click on go back button and it does not go back.

## Expected:

I expect the location to update with the previous location and the `<Switch />` to update the previous component.

## Result

The location is updated with the previous location and the `<Switch />` is not updating it's component.

## Question

- Is my configuration incorrect ? 
- We have seen #5655 , we expect later to use `<Redirect />` but I don't think my issue is related is it?

**Comment by IamMille** [comment]
@kopax What was the problem?
