### ISSUE TITLE
Redirect is not computing the params from the `from` path to the `to` path

### ISSUE THREAD

**Issue by Sparragus** [ReactTraining/react-router#5753]
## Version
4.2.2

## Test Case
Code: https://github.com/Sparragus/react-router-redirect-bug/blob/master/src/App.js
Demo: https://redirect-bug-cbfahyusjk.now.sh/

## Steps to reproduce
1. Go to https://redirect-bug-cbfahyusjk.now.sh/
2. You will be automatically redirected to `/users` (This is expected behavior)
3. Click on "@sparragus". You will go to `/users/sparragus`. (This is expected behavior)
4. Go back to `/users`
5. Click con "@horse_js". You should be redirected from `/profile/horse_js` to `/users/horse_js`. However, you will be redirected to `/users/:username`. (This is unexpected behavior).

## Expected Behavior
When clicking on the link to @horse_js's profile at `/users`, you are redirected from `/profile/horse_js` to `/users/horse_js`.

## Actual Behavior
When clicking on the link to @horse_js's profile `/users`, you are redirected from `/profile/horse_js` to `/users/:username`.

**Comment by Sparragus** [comment]
This should be working, but I think Redirect is not receiving the `computedMatch` props. This prop should be passed by Switch to the Redirect in https://github.com/ReactTraining/react-router/blob/73348d9c7fdfed0d3c29fea20e2d49d2651dbeab/packages/react-router/modules/Switch.js#L57, but it seems something is buggy and this isn't happening.

**Comment by Sparragus** [comment]
Currently I'm doing this to make it work as  expected: https://github.com/ReactTraining/react-router/issues/4919#issuecomment-346709646

**Comment by pshrmn** [comment]
I believe this is the feature that you're referring to https://github.com/ReactTraining/react-router/pull/5209. It has been merged, but there hasn't been a release since then.

**Comment by Sparragus** [comment]
@pshrmn Oooooh. Looking forward to it! Thanks :)
