### ISSUE TITLE
className no longer allowed on Link or NavLink

### ISSUE THREAD

**Issue by waynebrantley** [ReactTraining/react-router#5760]
## Version
4.0.19

## Test Case
```
                        <Link to={`/somurl/edit`} className="btn btn-default pull-right">
                                Edit
                        </Link>

```

## Steps to reproduce
The above no longer compiles with the definitions in 4.0.19.  Version 4.0.18 works fine.

## Expected Behavior
Should compile

## Actual Behavior
Indicates className is not allowed on Link.

This same problem exists on Link and NavLink.
@johnnyreilly

**Comment by timdorr** [comment]
4.0.19 and 4.0.18 aren't versions of React Router. We [pass through any extra props](https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/modules/Link.js#L76) directly to the `<a>`, so className definitely works.

**Comment by HansCronau** [comment]
@timdorr's argument is convincing.
Nonetheless I'm somehow experiencing the same issue with v4.2.2 of react-router-dom.
Replacing the `Link` with an `a` makes the class(Name) visible again (which of course is not a solution I suggest).
