### ISSUE TITLE
match prop always changes even if no routing activity was done

### ISSUE THREAD

**Issue by darkalor** [ReactTraining/react-router#5762]
## Version
4.2.2

## Test Case
https://codesandbox.io/s/j2o6w1kko3
Click the added button and check console

## Steps to reproduce
Check changed props in any component if no actual router activity occured

## Expected Behavior
If no routes were changed: `this.props.match === new.Props.match  => true`

## Actual Behavior
If no routes were changed: `this.props.match === new.Props.match  => false`
Specifically `match.params` seems to be changing to a new empty object every time.

**Comment by timdorr** [comment]
You shouldn't be checking for equality of the match each time. Look at `location` instead. `this.props.location === new.Props.location` is true.

**Comment by darkalor** [comment]
@timdorr Sorry, that wasn't the point. I'm saying that a `Route` is generating a new match prop on any activity even when no actual routing was done. This is just not semantic and can lead to false positives when deciding to re-render components.

I believe it would make sense to not have an unconditional `setState` here
https://github.com/ReactTraining/react-router/blob/master/packages/react-router/modules/Route.js#L101

E.g. roughly something like this
https://github.com/darkalor/react-router/commit/5bcabb74f166bce81e5af82a8fdc01b24254f2d4
