### ISSUE TITLE
[react-router-redux@5.0.0-alpha.7] params from withRouter prop is always empty (using a hashHistory)

### ISSUE THREAD

**Issue by MaxInMoon** [ReactTraining/react-router#5769]
## Version
react-router-redux@5.0.0-alpha.7
react-router-dom@4.1.1
react@16.0.0
history@4.6.1

## Test Case
https://codesandbox.io/s/7y8pj28rrj

## Steps to reproduce
Use a router (`ConnectedRouter`) with `react-router-redux`with a `hashHistory` from `history`. See the code codesandbox for the setup.

## Expected Behavior

`withRouter()` hoc  should provide `match.params` to the encapsulated component, as it does for a `Route`.

## Actual Behavior

`withRouter()` `match.params` object is always empty

**Comment by timdorr** [comment]
The params are only provided to the route they are defined on. They aren't global. This is expected behavior.

**Comment by MaxInMoon** [comment]
But the [doc](https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/api/withRouter.md) says:

> You can get access to the history object's properties and the closest <Route>'s match via the withRouter higher-order component. withRouter will pass updated match, location, and history props to the wrapped component whenever it renders.

!?

**Comment by timdorr** [comment]
The closest Route's ancestor component. It doesn't work in the other direction (children) because they could define conflicting params at any point in the tree.
