### ISSUE TITLE
State parameter in history.push or <Redirect> component does not get passed to the store in alpha.8

### ISSUE THREAD

**Issue by olup** [ReactTraining/react-router#5771]
Between alpha .6 et .8 of react router the *state* parameter of location.history or of the *to* prop of the redirect component is ignored.
Parameters passed on route redirection are then lost.
Worked on alpha.6, broken in .8

**Comment by timdorr** [comment]
Nothing about that has changed in between the alphas. Something else is going on in your app.

**Comment by olup** [comment]
Sorry but i tested the problem this very morning, worked great on my local env with alpha .6 and did not work in my colleagues env or on our production env with latest version. Forcing alpha .6 in our package.json solved the problem.
