### ISSUE TITLE
When is the new release coming?

### ISSUE THREAD

**Issue by atlanteh** [ReactTraining/react-router#5776]
Last release was two months ago.
1 day later Redirect with Params was introduced, but since then no new release was published.
Is there something blocking the release?

**Comment by timdorr** [comment]
Whenever.

**Comment by atlanteh** [comment]
How does that answer the question?

**Comment by timdorr** [comment]
It doesn't. There is no release schedule.

**Comment by GrantJamesPowell** [comment]
Thats not very nice @timdorr
