### ISSUE TITLE
Native docs contain Browser/DOM references

### ISSUE THREAD

**Issue by njwest** [ReactTraining/react-router#5778]
Am very happy to use react-router on Native, thank you guys for the great software!

The API docs under /native/ (e.g. [react-router/native/api/StaticRouter/](https://reacttraining.com/react-router/native/api/Route) ) are a bit confusing, as a lot of the example code uses `react-dom` implementations of `react-router-web` components.

I am not sure if this is overlap by design (/native and /web /api use the same component docs?) or something else, but the Native docs would be more legible if they contain explicitly `react-router-native` examples, even if the difference in suffix is trivial to code-level component implementation.

**Comment by timdorr** [comment]
This is a side effect of how we build the examples. We don't have unique copies for each flavor of the library, so it's code reuse getting in the way. Not sure of the best way to handle this, as just a search-and-replace step added to Webpack probably isn't sufficient.

**Comment by njwest** [comment]
It may be worthwhile to rethink how you do the examples for native docs, as the current state of the documentation is an adoption deterrent
