### ISSUE TITLE
Is there a way to get the query params in index.js (outside react components) 

### ISSUE THREAD

**Issue by firaskrichi** [ReactTraining/react-router#5788]
Is there a way to get the query params in index.js (outside react components) 

Can't use this.props.location 

Thank you!

**Comment by pshrmn** [comment]
You can just grab `window.location.search` and parse that.

If you need to do this on every location change, you can use `history.listen` to subscribe to location changes, but that will require you to create your own history (`<Router history={history}>` instead of `<BrowserRouter>`).

**Comment by firaskrichi** [comment]
Gotcha! Thanks
