### ISSUE TITLE
v4 "Guide" suggestion: query parameters

### ISSUE THREAD

**Issue by jamesplease** [ReactTraining/react-router#5789]
I've been migrating an app over to v4, and I was curious to know what the latest tips are for managing query parameters. I thought there might be a good guide on this topic on the website, given how important query parameters are to URLs, and how v3 provided a more out-of-the-box solution that needs to now be implemented in userland.

A quick look at the website suggests that this guide doesn't exist, but I think users would appreciate it. The information in [this issue](https://github.com/ReactTraining/react-router/issues/4410) is a goldmine of great ideas, but it's not particularly discoverable nor organized in the easiest-to-digest format.

Perhaps y'all have considered this, and didn't think it was a good fit for the website. Or maybe you're too busy to write a new guide right now (I understand; I am, too). Either way, no worries. This was just something that would have helped me today that I thought could be useful for others, too, so I thought I'd open an issue.

Thanks for reading, and thanks for your hard work on this awesome library! 👌 👍 :v:

**Comment by saltas888** [comment]
@jamesplease 
I just made this in order to avoid many changes while updating to react-router v4
https://github.com/saltas888/react-router-query-middleware
