### ISSUE TITLE
when query parameters changed, the same component will unmount and then mount.

### ISSUE THREAD

**Issue by nai6514531** [ReactTraining/react-router#5793]
when query parameters changed, the same component will unmount and then mount.for example:
I have a url like /admin and also have a component called Admin. In Admin, there are some inputs for searching. I add a query parameters after /admin like /admin?userId=123.The componet's componentDidMount will excute again. Is there any way to prevent this?

**Comment by pshrmn** [comment]
The issues section is not for questions; you should ask questions on StackOverflow or Reactiflux. That said, I will point you in the direction I think will help you:

From here https://reacttraining.com/react-router/web/api/Route/Route-props

> When you use component (instead of render or children, below) the router uses React.createElement to create a new React element from the given component. That means if you provide an inline function to the component attribute, you would create a new component every render. This results in the existing component unmounting and the new component mounting instead of just updating the existing component. When using an inline function for inline rendering, use the render or the children prop (below).
