### ISSUE TITLE
Opening external link with 'target' does't work as expected

### ISSUE THREAD

**Issue by aberba** [ReactTraining/react-router#5798]
With reference to issue https://github.com/ReactTraining/react-router/issues/1147 from 2015, `<Link />` does not support opening external link in new tab with the `target="__blank"` since react router blocks than action. The `<a>` was supposed to be used to get that behaviour. 

Now I'm using `  "react-router-dom": "^4.2.2"` and even the `<a>` tag is still has `target="_blank"` blocked. Its may be a bug.

**Comment by pshrmn** [comment]
React Router is not aware of any `<a>` elements, so it cannot block navigation. I through together this quick demo to show an `<a target="_blank">` working: https://codesandbox.io/s/720n0r8z16 You can fork and edit it if you think I've missed something, but I have to imagine that any blocking issues are on your end and are not coming from React Router.
