### ISSUE TITLE
param handling in <Redirect /> unreleased.

### ISSUE THREAD

**Issue by timothyjlaurent** [ReactTraining/react-router#5802]
## Version
4.2.0

React-router doesn't currently handle url parameters in <Redirects /> as is asserted in documentation for `<Redirect />`.

This was fixed back in September but hasn't been released in any way.

I have tried to install from the Git repo but wasn't able to with yarn.

Would it be possible for a @next release to go out where the Redirect handles url params?

**Comment by timdorr** [comment]
Not yet.

**Comment by allanhortle** [comment]
@timdorr Is it possible to remove this from the docs until has been released? I just spent an hour wondering why my code wasn't behaving according to the docs. Only when I went digging through issues did I find this.

**Comment by timdorr** [comment]
We'll release something soon.

**Comment by seniorquico** [comment]
For anyone looking to achieve parameterized redirects while we await a new release:

```js
<Switch>
  <Route path="/users/:id" render={({ match }) => <Redirect to={`/users/profile/${match.params.id}`} />} />
</Switch>
```
