### ISSUE TITLE
Support all <Route> props in react-router-config

### ISSUE THREAD

**Issue by jaap3** [ReactTraining/react-router#5803]
Recently the `sensitive` flag was added, but it seems that it is not possible to set this flag when building routes using react-router-config.

**Comment by timdorr** [comment]
It is. You'll use the `extraProps` or `switchProps` to do this: https://github.com/ReactTraining/react-router/blob/master/packages/react-router-config/modules/renderRoutes.js#L5

**Comment by jaap3** [comment]
`extraProps` are passed to the child component, not to the `Route` component. 

To be clear, I'm talking about the flag added by PR #5438. It's comparable to the `exact`, `strict` flags.

**Comment by timdorr** [comment]
Then `switchProps` can be used when that is released. 

A good PR might be to simplify things by just passing all the options on the route object to the `<Route>` as direct props, not a subset of them.

**Comment by pshrmn** [comment]
It looks like `renderRoutes` [is manually passing `strict` and `exact`](https://github.com/ReactTraining/react-router/blob/v4.2.2/packages/react-router-config/modules/renderRoutes.js#L11-L12), so it needs to be updated to also pass `sensitive`. @jaap3 a PR that makes this change would be appreciated (with a test, please).

`matchRoutes` already just passes the `route` object to `matchPath`, so it doesn't need any changes.

**Comment by sylvainpina** [comment]
6 months and no update... :cry:

**Comment by mjackson** [comment]
Thanks for re-opening this, @pshrmn.

> A good PR might be to simplify things by just passing all the options on the route object to the <Route> as direct props, not a subset of them.

I agree @timdorr, we should probably just spread the `route` object as props to the `<Route>` component so it transparently supports all the same props.
