### ISSUE TITLE
Router does not re-renders class based Components but does for pure functions

### ISSUE THREAD

**Issue by vinitkumar** [ReactTraining/react-router#5806]
I am not sure if this is a bug in react-router or my code. I am a beginner with React-Router so please excuse my lack of experience.

## Version
4.1.1

## Test Case
https://codesandbox.io/s/github/vinitkumar/github/tree/master/

## Steps to reproduce

On clicking the links on the left side, the render only happens once for Gist Component. After that
the route changes, the props update, but the re-render of Gist component never happens.

## Expected Behavior
The Gist component should render fresh every time the props change.

## Actual Behavior
The Gist component does not render again after the first render.

**Comment by timdorr** [comment]
React is re-using the previous Gist component instance, but isn't picking up the prop change. Easiest thing to do is to add a key: `<Gist key={match.params.gistId} ...`

**Comment by vinitkumar** [comment]
Awesome. Thanks for the help :) 👍
