### ISSUE TITLE
Prompt doesn't prevent refresh with `when` set to true

### ISSUE THREAD

**Issue by wldcordeiro** [ReactTraining/react-router#5807]
## Version
4.2.2

## Test Case
N/A

## Expected Behavior

That hooking up a `Prompt` would prevent navigation or refreshes

## Actual Behavior

It only prevents the navigation

I may have misunderstood how to use this? I'm not seeing a way that covers refreshing as well.

**Comment by timdorr** [comment]
Prompt doesn't handle refreshing.

**Comment by wldcordeiro** [comment]
@timdorr it looks like there's a PR from August that added the functionality. Is there a request issue? Could I get that PR up to snuff? PR in question https://github.com/ReactTraining/react-router/pull/4372

**Comment by timdorr** [comment]
Sure, you can make another one. Nothing about a PR makes it "reserved". Whichever code is best.

**Comment by wldcordeiro** [comment]
I don't want to invalidate someone else's work. I maintain other OSS and I know contributors can take it harshly when someone else just jumps on something they've been working on. To be honest though the experience I'm having just trying to get information from the maintainers here is making me **not** want to contribute as it's entirely too impersonal and feels like you aren't reading a word I write.

**Comment by timdorr** [comment]
I'm reading this. What information are you looking for?
