### ISSUE TITLE
window.onhashchange is not being raised by navigating through hash links

### ISSUE THREAD

**Issue by kripod** [ReactTraining/react-router#5809]
## Version
4.2.0

## Test Case
`<Link to="/#top" />`

## Steps to reproduce

1. Attach a handler to the browser window's "hashchange" event
2. Click on the link

## Expected Behavior

The "hashchange" event should fire.

## Actual Behavior

The "hashchange" event is not fired.

**Comment by timdorr** [comment]
These aren't hash change events. This is using history.pushState under the hood. If you need to change the hash, just use a normal `<a>` tag.

**Comment by Firanolfind** [comment]
I need to handle hash change with <BrowserRouter>, how can I do it now?
