### ISSUE TITLE
Links containing percent-encoded character trigger URIError in react-router

### ISSUE THREAD

**Issue by Reventl0v** [ReactTraining/react-router#5812]
## Version
    "react-router-dom": "4.2.2",
    "react-dom": "16.0.0",
    "react": "16.0.0"

## Test Case

https://codesandbox.io/s/zj7ok3l5x (WARNING: codesandbox has some problems with this test case, this link is just here to ease the test case bundle download)

## Steps to reproduce

1. Create a router with path equal to "/:id", and with a component being a simple display component displaying the id.
2. Create a Link  with a "to" parameter equal to something containing a percent-encoded percent sign: (e.g.  ```to = {`/${encodeURI("%foobar")}`}``` )
3. Click on the link
4. Refresh

## Expected Behavior

When refreshing, you get the same page as when you click on the link (so, after step 4 you get the same display as before step 4).

## Actual Behavior
When refreshing, you get an error:
    URIError: Failed to decode param '/%foobar'

After the click on the link, the url bar in the browser contains "/%foobar", and not "/%25foobar", which is nonetheless the actual destination of the Link.

Sample video showing the problem (notice that the "%netflix" link is correctly percent-encoded by looking at the bottom left of the video when hovering the link):  https://ptpb.pw/UBJc.mkv 

Mirror of the codesandbox:  https://ptpb.pw/tOIr.zip

**Comment by timdorr** [comment]
This is caused by the history library. There is a bug being tracked there: ReactTraining/history#505
