### ISSUE TITLE
React router redux SSR and basename

### ISSUE THREAD

**Issue by dimooze** [ReactTraining/react-router#5813]
## Version
React Router 4.2.0
React Router Redux 5.0.0-alpha.9

Hi ! 
I'm experiencing a warning when rendering `ConnectedRouter` on the server/client with `basename`, all links are rendered without it on server side.
On client side i'm using history to add the `basename` to `ConnectedRouter`. On server side createMemoryHistory doesn't support `basename` and as mjackson pointed it out in this PR [https://github.com/ReactTraining/history/pull/522#issuecomment-345830553](url) there's no history at all on server side. 

So as i've seen in the recent alpha of `react-router-redux` a flag for SSR, i'm wondering if we could use it to render on server side a `StaticRouter` instead of a `Router` something like : 
```
render() {
    const { history, isSSR, context, children, basename } = this.props
    return isSSR ? 
    <Router history={history} children={children} /> : 
    <StaticRouter context={context} location={history.location} basename={basename} children={children} />
  }
```
That way we could also have the `context`. I could make a PR :)

Or do we get rid of `ConnectRouter` for server side rendering and use a `StaticRouter` with a dispatch of `LOCATION_CHANGE` with the current location ?

Thanks for any feedback !

**Comment by timdorr** [comment]
Yes, on the server side, you should be using StaticRouter. Syncing a history with a redux store on the server doesn't make sense because you `renderToString` once and you don't have navigation events in that context.

**Comment by dimooze** [comment]
Thanks @timdorr ! 
Just for my intention so why add a `isSSR` flag and the purpose of this PR : [https://github.com/ReactTraining/react-router/pull/5714](url)

**Comment by timdorr** [comment]
For those that are still using it on the server side. They shouldn't, but they may not have time for a refactor and that's a quick workaround for a memory leak.
