### ISSUE TITLE
URL's with %25 get decoded to "%" which breaks back navigation.

### ISSUE THREAD

**Issue by synaestheory** [ReactTraining/react-router#5816]
## Version
4.2.0

## Test Case
https://codesandbox.io/s/mmpro4pm9p
NOTE: codesandbox crashes when you click on the link to "Search 100%"
I haven't officially determined that this bug is the cause, but feel somewhat confident that it is.
We are encoding the "100%" search term so that it links to "/search/100%25" (Line 7 of code sandbox), however react-router decodes the %25 into just "%" during navigation which causes problems when we need to navigate "back" to that route.

## Steps to reproduce
• navigate to a route that has an encoded "%" character i.e. "/search/100%25"
• Observe the path get decoded "/search/100%"
• navigate elsewhere
• use browser back or history.goBack() -- LocationUtils throws a decodeURI error attempting to decode the previous URL, "/search/100%"

## Expected Behavior
"%25" does not get decoded, much like "%20" does not get decoded.

## Actual Behavior
"%25" is decoded and saved in browser history as "%"

**Comment by timdorr** [comment]
This is caused by the history library. There is a bug being tracked there: ReactTraining/history#505
