### ISSUE TITLE
Link component will PUSH new location regardless of location

### ISSUE THREAD

**Issue by qamil** [ReactTraining/react-router#5817]
## Version
4.1.1

## Test Case
The issue occurs in the default sandbox: https://n55vljyk7.codesandbox.io/

## Steps to reproduce
Click some link, for instance "Topic". Then just click "Topic" several times more, and then several times on the back button.

## Expected Behavior
The `Link` component recognises that the location of the Link is already active and doesn't emit a new history `PUSH` event (but rather a `REPLACE`? But I'm not sure.).

## Actual Behavior
The `Link` component always emits a history `PUSH` regardless of the current location. This pollutes the history stack of the user.

**Comment by timdorr** [comment]
https://github.com/ReactTraining/react-router/issues/5500#issuecomment-327806119

Check on ReactTraining/history#507
