### ISSUE TITLE
Make Link work as a decorator

### ISSUE THREAD

**Issue by ericaprieto** [ReactTraining/react-router#5819]
I would be great if the Link component worked as a decorator for any component that implements onClick, like the Link on next.js

https://github.com/zeit/next.js/#with-link

**Comment by timdorr** [comment]
Closing per #5497

**Comment by timdorr** [comment]
Also, if you need this kind of thing, you can use `withRouter` and get the `history` instance to `push()` on your own. It's quite easy :)
