### ISSUE TITLE
Router with history prop not working with HMR

### ISSUE THREAD

**Issue by sam019** [ReactTraining/react-router#5826]
when specify Router history property like this 
`<Router history={history}>
          <App/>
        </Router>`
when HMR triggered, React-Router complaining - `Warning: You cannot change <Router history>`
and then router can't working (change url can't render the right component), is there some wrong i make?

**Comment by sam019** [comment]
My mistake, i move history to a independent module, so when i change code, it can't create a new history

**Comment by veeramarni** [comment]
@sam019 What you mean by independent module? Is it on another npm package?
