### ISSUE TITLE
the problem on query of <Link> component

### ISSUE THREAD

**Issue by stoneyallen** [ReactTraining/react-router#5827]
## Version
4.1.1

## Test Case
when i use a case of Link:

`<Link to={{pathname:'/anyPath/',query:{a:1,b:2}}}></Link>`

click the element, the page will jump to new path, and we can get 'a' from the location of props, but when I refresh the current page, we can't get the 'a' with undefined. I think the 'query' of props is saved by memory, so when I refresh the page,I can't get 'a' again

## Expected Behavior
can you resolve this problem of getting 'a' with undefined, when I refresh the page.

**Comment by timdorr** [comment]
There is no query processing in 4.x. You need to do this yourself, or just use the `search` property of a location.
