### ISSUE TITLE
Call a function when user confirms Prompt?

### ISSUE THREAD

**Issue by wldcordeiro** [ReactTraining/react-router#5828]
## Version
4.2.2

Is there a way to show the prompt from an attempted `history.push` and then only call a function when the user hits the "okay" option? I'm looking over the docs and don't see anything like this.

**Comment by timdorr** [comment]
Your best bet is to wait until the location changes. The history library doesn't have a good way to handle blocking callbacks at the moment. If you want that added, I'd ask [over there](https://github.com/ReactTraining/history).

You can also just call `window.confirm` yourself and look at the results directly.
