### ISSUE TITLE
Fail on go back to a previous page that was loaded with history.push with parameters

### ISSUE THREAD

**Issue by mserranog** [ReactTraining/react-router#5832]
## Version
4.2.2

## Steps to reproduce
Go from page1 to a page2 using history.push with custom parameters like:
this.props.history.push({
        pathname: '/page2',
        parameters: {
          parameter1: parameterObject1,
          parameter2: parameterBoolean2
        }
      });
The navigate with link to page3 and go back.
## Expected Behavior
Show page2
## Actual Behavior
Goes page1 because on history.goback parameters passed to page2 are gone

**Comment by timdorr** [comment]
`parameters` isn't a property of a location.

**Comment by mserranog** [comment]
I know, but I tested with this and same behaviour:
this.props.history.push({
pathname: '/page2',
state: {
parameter1: parameterObject1,
parameter2: parameterBoolean2
}
});

Is there any other way to pass objects and parameters to a route manually? Thank you

**Comment by pshrmn** [comment]
You can use `location.state` to pass serializable data during navigation, but I generally wouldn't recommend it. A global store where you can lookup data based on pathname or query params is almost always better.

The only time that I _would_ recommend using `location.state` is for redirect information (i.e. the user attempts to visit a protected page, so you redirect them to a login page and store the original location in `location.state` to redirect back to after logging in).
