### ISSUE TITLE
TypeError: 'undefined' is not an object (evaluating 'this.context.router.history.createHref')

### ISSUE THREAD

**Issue by andi1984** [ReactTraining/react-router#5834]
I'm using `react-router-dom` in a project of mine and see now that something is broken for a Safari 5.1.6 user. All I use is `Switch`, `Route`, `BrowserRouter` and `Link`. I guess this error comes from the latter one in `Link`.

## Version
4.2.2

## Steps to reproduce

Seems to be an issue with Safari 5.1.6

## Expected Behavior

Should work as for the other browsers.

## Actual Behavior

Breaks with `TypeError: 'undefined' is not an object (evaluating 'this.context.router.history.createHref')`

**Comment by timdorr** [comment]
Safari 5 isn't supported. That is a 6 year old browser.
