### ISSUE TITLE
Switch Component renders the first component that is renderable regardless of it being of type Route or Redirect

### ISSUE THREAD

**Issue by govindrai** [ReactTraining/react-router#5841]
The [react-router documentation for the Switch component](https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/api/Switch.md) states: 

> Renders the first child <Route> or <Redirect> that matches the location.

However, `Switch` renders the first React element it encounters regardless of it being of type `Route` or `Redirect`. This is a problem.

Say this is my routing declaration:

```
        <Router>
          <Switch>
            <Route exact path="/" component={Landing} />
            <Route path="/register" component={RegistrationForm} />
            <Route path="/login" component={LoginForm} />
            <ProtectedRoutes isAuthenticatedUser={this.props.isAuthenticatedUser}>
              <ProtectedRoute
                path="/stripe-checkout"
                component={StripeCheckout}
              />
            </ProtectedRoutes>
            <Route component={NoMatch} />
          </Switch>
        </Router>
```

Side Note: 
> All the `ProtectedRoutes` component is doing is injecting the `isAuthenticatedUser` prop into it's children (`ProtectedRoute` components). It's children are rendering standard react-router `Route` components and are using the passed down `isAuthenticatedUser` prop to determine whether to render the specified component or `Redirect` (to my Login component).
> 
> Upon render the above <ProtectedRoutes> is renders this:
> `<Route path="/strip-checkout" render={callback which renders StripeCheckout or Redirect}` . 

Now, If I go to "/blah", I expect the `NoMatch` to render since it does not match any of the routes. However, the `NoMatch` component will never render because `ProtectedRoutes` end up rendering (and displays nothing because the inner `Route` path `/stripe-checkout` does not match blah). 

Not really sure of a solution to this, but this definitely caused frustration as I couldn't understand why the `Switch` component was rendering `ProtectedRoutes` even though the path I was navigating to did not match the `Route`.

Regardless, the documentation should be updated to reflect this behavior. In the short therm, maybe throw an error if nesting components not of type `Route` or `Redirect` in `Switch` components (as per the documentation).

I solved this issue by simply removing the `Switch` component, but this didn't occur to me until I had spent 2 hours fiddling. :'(

**Comment by pshrmn** [comment]
Every direct child of a `<Switch>` is treated as a `<Route>`, so a component has to have a `path` (`<Redirect from>` is just an alias for `<Route path>`) or it will always match. While you can technically pass any component as a direct child of `<Switch>`, the documentation doesn't mention this because passing anything besides a `<Route>` or `<Redirect>` is generally not encouraged (this might be a little bit misleading since other parts of the documentation do pass custom `<___Route>` components as children of a `<Switch>`). A PR to the docs that would make this clearer would be welcome.

**Comment by govindrai** [comment]
@pshrmn I don't know how I can then go about dealing with my "Protected" routes only rendering when authentication is valid. I would have to pass a prop to each and every protected route, in my case there are 30 protected routes. Is there no other way?
