### ISSUE TITLE
Route's `render` callback not called when Redirect component changes route

### ISSUE THREAD

**Issue by Sawtaytoes** [ReactTraining/react-router#5843]
## Version
history: 4.7.2
react: 16.2.0
react-dom: 16.2.0
react-redux: 5.0.6
react-router-dom: 4.2.2
react-router-redux: 5.0.0-alpha.9
redux: 3.7.2

## Test Case
**Working**: https://codesandbox.io/s/6wl8v8n27k
**Broken**: https://codesandbox.io/s/4j7nlno909

## Steps to reproduce
1. Setup Redirect components to change the URL to `/login` if not authenticated and to `/` if going to `/login` and authenticated.
2. Create 2 routes for `/` and `/login`
3. Click the Login button.
4. Click the Logout button.

## Expected Behavior
Clicking Login should get you to `/` and clicking Logout should get you to `/login`.

## Actual Behavior
The URL changes, but the `render` callback on Route isn't fired a second time after the Redirect occurs so the button reads LOGIN on both routes and you're unable to logout.

When using BrowserRouter, this works fine, but when using ConnectedRouter, a single `connect` function wrapping the component holding routes causes Route's `render` callback to not occur the second time through. It's calling `render` when the component is updated, but not when the route changes from a Redirect.

**Comment by Sawtaytoes** [comment]
Pressed "Submit" by mistake. Will reopen after it's been finalized if this is an actual bug.

**Comment by Sawtaytoes** [comment]
Verified this is a bug, but it occurs with ConnectedRouter, not BrowserRouter. Could very well be a configuration issue on my end.

**Comment by Sawtaytoes** [comment]
Even if it's not used, if I pass the `routerReducer` state into my props object from mapStateToProps, then it listens for route changes properly.

I don't know if this should be the case though because I thought Route's `render` prop should fire anytime router is updated. It may be Route isn't listening for Redux updates on `router` state changes.

**Comment by timdorr** [comment]
See this guide: https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/guides/blocked-updates.md

**Comment by Sawtaytoes** [comment]
After reading through that, I think it might just be simpler for react-router to create Redux-specific components. For instance, it doesn't matter if the parent container doesn't rerender if every `Route`, `Switch`, etc is going to force a rerender when the routerReducer fires and update. Utilizing `withRouter()`, I could create this file myself:

```js
import { connect } from 'react-redux'

import {
	Redirect as DumbRedirect,
	Route as DumbRoute,
	Switch as DumbSwitch,
} from 'react-router-dom'

const mapStateToProps = ({ router }) => ({ ...router })

export const Redirect = connect(mapStateToProps)(DumbRedirect)
export const Route = connect(mapStateToProps)(DumbRoute)
export const Switch = connect(mapStateToProps)(DumbSwitch)
```

And now the problem is solved because each `Redirect`, `Route`, and `Switch` is connected to the Redux `store` for updates instead of `history`.

This could be easily put into react-router-redux. If you'd like, I can make a PR and set it up as multiple files that compose their react-router-dom counterparts. The only issue I can see is it's not importing components directly from react-router, but instead from react-router-dom. Since react-route-redux doesn't necessarily deal with the DOM, there should probably be a better solution.
