### ISSUE TITLE
React-Router-Redux version

### ISSUE THREAD

**Issue by yoerivdm** [ReactTraining/react-router#5848]
When can we expect to see a React-Router-Redux binding version that is production ready?
Imo, it already is but work forbids me to use alpha nor beta-versions in production environments.

So given this, I just want to know if I need to seek alternatives or just stick with RR?

Y.

**Comment by timdorr** [comment]
I don't know. This isn't a corporate product. There are no roadmaps, burndown charts, or sprint planning sessions. It'll happen when it happens.
