### ISSUE TITLE
Please merge the relative route PRs

### ISSUE THREAD

**Issue by wmertens** [ReactTraining/react-router#5852]
#4695 #4539 are as ready as they can be. Relative routes are sorely missing and they are the keystone to making pluggable application parts.

I tried making it work by wrapping `<Route>`, but then it turns out I also needed to wrap `<Redirect>` and in fact completely replace `<Switch>`, since the `matchPath` logic can't be overridden.

Relative links are a different beast, so just having relative Routes will already be nice. Child-only links like ``<Link to={`./${item.id}`}/>`` or `<Redirect to="./home" />` would be nice but they can easily be done with a wrapper.

**Comment by timdorr** [comment]
No.

**Comment by timdorr** [comment]
To clarify, they are not ready yet. Please don't make demands like this.
