### ISSUE TITLE
How do I change the href in JS not in COMPONENT

### ISSUE THREAD

**Issue by DanielWLam** [ReactTraining/react-router#5854]
I am really confused why remove ```browserHistory``` API. We use that a lot in js. The v4 API are all component, which is quite limited. Think about this situation: 
1. dispatch an action to DELETE something
2. go back to ```index```

I just don't know how to do this without those api

**Comment by timdorr** [comment]
You can still do this on your own. Just create the history instance yourself. Then use a `<Router>` instead of one of the preconfigured ones and pass it in as a prop.

https://reacttraining.com/react-router/web/api/Router
