### ISSUE TITLE
Why the header component displayed even in Nomatch route ?

### ISSUE THREAD

**Issue by kilaniba** [ReactTraining/react-router#5856]
I created my routes : 
`<Route path='/' component={Header} />`
              `<Switch> `        
                `<Route exact path="/home" component={Home} />`
                `<Route exact path="/about" component={About} />`
                `<Route component={Nomatch}/>`
              `</Switch>` 
When I type an route not matched , the `Notmatch` component displayed but also the `Header` component persist to display .

**Comment by timdorr** [comment]
That route is non-exact and not within the Switch. It will match any URL and always show itself. You need to be within a switch to only match one direct child Route.

**Comment by kilaniba** [comment]
@timdorr But when I try this 
`<Switch>`
`<Route exact path='/' component={Header} />`
`<Route exact path="/home" component={Home} />`
`<Route exact path="/about" component={About} />`
`<Route component={Nomatch}/>`
`</Switch>`
Always only the header displayed and the rest not displayed.

**Comment by timdorr** [comment]
Yes, that's expected. You probably need to think through your application design a bit more. Each of the components on your top level routes should be the entire contents of your page. You can build a layout-style component to make that easy to duplicate. 

This isn't impossible, it just requires some care in your architecture design process.
