### ISSUE TITLE
Possible bug? Regexp based Route not rerendered on location change, when regexp still matched.

### ISSUE THREAD

**Issue by r3wt** [ReactTraining/react-router#5859]
**UPDATED WITH A TEST CASE ON THE SANDBOX SITE**

## Version
4.1.1

## Test Case
https://codesandbox.io/s/03x03kqjp

## Steps to reproduce
```js
<Route exact path='/search/:view(list|grid|map)?' component={Search} />
```
when view parameter of route change, the view does not rerender with new props. 

## Expected Behavior
component rerender with new props

## Actual Behavior
location change but component does not rerender

**Comment by timdorr** [comment]
I modified the test case and it works perfectly: https://codesandbox.io/s/l2454ymxwm

See this guide: https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/guides/blocked-updates.md

**Comment by r3wt** [comment]
@timdorr please check the link again. That was the default test case link you visited. i updated it with the correct link.

**Comment by r3wt** [comment]
correct link is https://codesandbox.io/s/03x03kqjp

**Comment by timdorr** [comment]
You're not doing a setState() anywhere. The state isn't changing because you're not changing it.

**Comment by r3wt** [comment]
@timdorr Look again. Clicking the `Link` changes the url. thus one would expect the, the new component should be rerendered with the new location in props, and thus the state should be updated? but, react router does not rerender the new component since it has already been rendered previously. this is a bug.

**Comment by r3wt** [comment]
feels like you've closed this issue out of spite based on past history. what a shame.

**Comment by timdorr** [comment]
No, that's how React works. It's re-using the existing component, rather than creating it from scratch. If you have the same component tree between renders, it will re-use the same instance and the same state.

**Comment by timdorr** [comment]
https://reactjs.org/docs/reconciliation.html#component-elements-of-the-same-type

**Comment by r3wt** [comment]
I see. Thank you for your patience with me lol 🤗 my apologies for wasting your time

On Jan 10, 2018 12:35 PM, Tim Dorr <notifications@github.com> wrote:

https://reactjs.org/docs/reconciliation.html#component-elements-of-the-same-type
