### ISSUE TITLE
Searchable v3 docs

### ISSUE THREAD

**Issue by mnieber** [ReactTraining/react-router#5864]
Hi, as a user of React Router v3 it would be great to have a version of the documentation that can be globally searched. Is that possible? At the moment, I'm opening the different chapters of the docs and search in each chapter.

I also tried compiling the docs locally into html, but that did not work out (mainly because the internal links point directly to github).

**Comment by timdorr** [comment]
Unfortunately, because of how GitHub works, this isn't possible. But you can clone the repo locally, check out the v3 branch, and search from your computer.
