### ISSUE TITLE
why render method of route creating component each time state changes

### ISSUE THREAD

**Issue by harry1064** [ReactTraining/react-router#5867]
According to this render method of Route in react-router package
```
render() {
    const { match } = this.state;
    const { children, component, render } = this.props;
    const { history, route, staticContext } = this.context.router;
    const location = this.props.location || route.location;
    const props = { match, location, history, staticContext };

    if (component) return match ? React.createElement(component, props) : null;

    if (render) return match ? render(props) : null;

    if (typeof children === "function") return children(props);

    if (children && !isEmptyChildren(children))
      return React.Children.only(children);

    return null;
  }
}
```
Why its always creating new React  Component. 
hence componentDidUpdate method of one of children component is not getting fired.

**Comment by timdorr** [comment]
That's just JSX without the JSX. It's equivalent to:
```js
    if (component) return match ? <component {...props} /> : null;
```
It's not creating a new component instance. React will recycle the existing instance if the tree layout is the same.

**Comment by harry1064** [comment]
I was passing component props as function that return a React component. In case of component of type `function`, it will create it everytime.
