### ISSUE TITLE
FeatureRequest: Switch with derivative routes

### ISSUE THREAD

**Issue by jenglert** [ReactTraining/react-router#5871]
It would be nice if <Switch> elements could contain derivatives of Route.  For example example, consider the following derivative route:

```
LoadingRoute = () => {
    if (this.state.isLoading) {
      return <Route render={() => <div>Loading...</div>} />
    } else {
      return null;
    }
  }
```

if LoadingRoute is used within a switch statement, it will match the switch statement even if `state.isLoading` is false.  For example,

```
<Switch>
  <LoadingRoute />
  <Route render={() => "I will never be rendered."} />
</Switch>
```

**Comment by timdorr** [comment]
Switch actually doesn't care about the component used, just its props. It's a bit of a hack to get some v3 behavior back. So, this isn't possible with how it's architected.

You could do this at a higher level by wrapping the switch itself. Or by nesting switches. You have a few options here.
