### ISSUE TITLE
react router v4  shows same component in modal as well as in background page

### ISSUE THREAD

**Issue by naiduprakash** [ReactTraining/react-router#5872]
![screenshot 21](https://user-images.githubusercontent.com/24874853/34913159-79f1f5fa-f91b-11e7-99db-f444dc0a07f3.png)

After loading the modal when i refresh the page the component is open in a page rather than a modal.
at this moment when i refresh the page twice and go back using the back arrow of browser the component is shown inside the modal as well as in the background page.

**Comment by pshrmn** [comment]
I wrote the modal example and its location state management definitely isn't perfect, but it is "good enough" to demo the behavior most of the time. If you want to submit a PR that optimizes the behavior across refreshes, please go ahead and do so.
