### ISSUE TITLE
[Feature Request] Global params object

### ISSUE THREAD

**Issue by goodbomb** [ReactTraining/react-router#5876]
As it stands, the current way that match.params works means that it's not possible to have a global params object that's available everywhere within the application (at least not without a lot of hacky code to enable it). I understand that this was done to follow more of a React uni-directional data-flow pattern, but it causes problems for things like custom BreadCrumbs components that need access to the URL parameters at all times.

My suggestion would be to enable it in the `react-router-redux` library and have it be a part of the `routerReducer`. That way it can live as part of the redux application state and keep the React-Router library as is.

**Comment by r3wt** [comment]
@goodbomb i was facing a similar problem. the solution i came up with was:

`<Router>
<AppLayout>
</AppLayout>
</Router>`
AppLayout is decorated with `withRouter` and passes a prop called `crumbs={crumbs}` to my `<Header>` component. So each time a route change, the header gets new props and passes down to the breadcrumbs. can illustrate if you need. I just figured it out today.

**Comment by timdorr** [comment]
This is fundamentally impossible. The params of a match are relative to the `<Route>` that matched it. There can be multiple matches in the same tree, so there is no single canonical version to make globally available.
