### ISSUE TITLE
props.location.state gets cleared if I open a link in a new tab.

### ISSUE THREAD

**Issue by prakharrke** [ReactTraining/react-router#5883]
The state passed to component using,
`<Link to={{
   pathname : '/path/name' ,
   state: {
   someID : 'SOME_ID'  
}
}}>Click</Link>
.
.
.
.
.
.
.
// Route is defined here... <Route path="/path/name component = {MyComponent}/>`

If I click on the link, MyComponent component gets mounted and `this.props.location.state.someID` is accessible.
But if I open the link in a new tab (by right clicking on the link and selecting 'Open in new Tab' or by doing CTRL+Left click), `this.props.location.state.someID` gets cleared. I do not know if it is an issue. Please help.

**Comment by pshrmn** [comment]
This is how `state` (which comes from the [`History` API](https://developer.mozilla.org/en-US/docs/Web/API/History_API)) works. State is attached to a location in a session and does not exist (or rather, is `null`) when you navigate directly to a page.

In general, I would not recommend using `location.state` for passing anything but temporary data (like a redirect location). If you need data attached to a location I would recommend using either path params or search params and having a store that you can lookup that data from.
```js
// path params
{ pathname: `/path/name/${SOME_ID}` }
// search params
{ search: `?someID=${SOME_ID}` }
```
If you really want to use `location.state`, your route will need to have some sort of backup plan for using some default value when `location.state` is `null`.

**Comment by prakharrke** [comment]
Thank you. That really helped.
