### ISSUE TITLE
NavLink no longer updates activeClassName when a parent component has componentDidMount

### ISSUE THREAD

**Issue by JaSpr** [ReactTraining/react-router#5886]
## Version
4.2.0

## Test Case
https://codesandbox.io/s/6vyol3o86n

## Steps to reproduce
Make a parent component have a `componentDidMount` method

## Expected Behavior
NavLink active state updates after link click

## Actual Behavior
NavLink active state only updates on page refresh.

**Comment by timdorr** [comment]
I'm not seeing that behavior at all. Your first NavLink isn't `exact`, so it always matches. But clicking between the two others, I see the active class toggle on and off. cDM isn't a blocking behavior in React.

**Comment by chcald** [comment]
I put this in my nav component and it worked

export default connect(mapStateToProps, null, null, {
  pure: false
})(TodoApp)

**Comment by daryn-k** [comment]
timdorr, I wonder, what an idiot you are. You library doesn't work correctly in many cases, but you're writting stupid evasions.
