### ISSUE TITLE
Routes don't work when live and viewed from Firefox private tab

### ISSUE THREAD

**Issue by kirkins** [ReactTraining/react-router#5888]
## Version
4.1.1

Sometimes my routes go to 404. I can consistently make it not work by viewing the online version in firefox private browser.

In which case the root will work but not routes. https://pocard.club vs https://pocard.club/about

Yet if I run on localhost I don't see this problem.

My brother said he saw a similar issue on safari on his iphone.

Since it doesn't happen on localhost I'm wondering if it is an issue with the hosting? Anyone experienced something similar?

## Routes
```
// ....
const BasicExample = () => (
  <Router>
    <div>
      <Navigation></Navigation>
      <Route exact path="/" component={Home}/>
      <Route path="/about" component={About}/>
      <Route path="/login" component={Login}/>
      <Route path="/test" component={Test}/>
      <Route path="/privacy" component={Privacy}/>
      <Route path="/confirm" component={Confirm}/>
    </div>
  </Router>
)
export default BasicExample
```
_Compiled and hosted on GH-Pages with Cloudflare DNS: https://github.com/kirkins/pocard.club/_

**Comment by pshrmn** [comment]
https://github.com/ReactTraining/react-router/blob/master/FAQ.md#why-doesnt-my-application-render-after-refreshing

**Comment by josepot** [comment]
That's not a problem with react-router, [have a look at this](https://github.com/rafrex/spa-github-pages)

**Comment by kirkins** [comment]
@josepot  @pshrmn thank you
