### ISSUE TITLE
Using BrowserRouter includes HashRouter in bundle 

### ISSUE THREAD

**Issue by andriijas** [ReactTraining/react-router#5898]
## Version
4.1.1
webpack 3.x with react-scripts (`create-react-app`)

## Steps to reproduce
Using only BrowserRouter pulls in HashRouter, createHashHistory and createMemoryHistory and adds unesscary size to the bundle. This has been reported before #3642 and closed of as backward compatible issue but that was 2 years ago, maybe we can improve performence with new non backward compat relase?

## Expected Behavior
- dont bundle code not used 

## Actual Behavior
![actual](https://i.imgur.com/7ZZPMuB.png)

**Comment by timdorr** [comment]
This was already fixed in #5095. Please update to the latest version.

**Comment by andriijas** [comment]
@timdorr sorry about the confusion, im on the latest version: 4.2.2

but as far as i can see there are a couple of PR merged during the fall that might be related and its been a while since last release, can we cut a new one?

Thanks
