### ISSUE TITLE
Switch with Router inside does not work in production

### ISSUE THREAD

**Issue by osoft17** [ReactTraining/react-router#5899]
Hi,

Here is the Main.js code

import React from 'react';
import { Switch, Route } from
    'react-router-dom';

import Project from './P';
import ProjectTask from './PT';

const Main = () => (
    <main>
        <Switch>
            <Route exact path='/' component={PT}/>
            <Route exact path='/PT/:id' component={PT}/>
        </Switch>
    </main>
)

export default Main;
========================

P.js

I have a button with onclick method   navigateToTask(i,j) {
   window.location.assign(`/PT/${i}`);
}

Clicking this button changes the navigation link as http://localhost:port/PT/123 but components won;t 
render in the production, but same works in development env.

did i miss anything here

Thanks,

**Comment by pshrmn** [comment]
You have to use a [`history`](https://reacttraining.com/react-router/core/api/history) object for navigation. If you are using a `<BrowserRouter>`, a `history` object is created for you and will be injected into every component that is rendered by a `<Route>`. If you need to perform navigation outside of your components, you will have to create your own `history` instance.

```jsx
class MyComponent extends React.Component {
  handleClick() {
    this.props.history.push('/PT/123');
  ]
}
// usage
<Route component={MyComponent} />
```

**Comment by osoft17** [comment]
Hi,
Thanks for the reply,

I tried using the same, to better understand  adding some more code here 

====================== Main.js ===========

import React from 'react';
import { Switch, Route } from
    'react-router-dom';

import P from './P';
import PT from './PT';


const Main = () => (
    <main>
           <Switch>
            <Route exact path='/' component={P}/>
            <Route exact path='/PT/:id' component={PT}/>
           </Switch>
    </main>
)

export default Main;

===============  App.js ===========

import React from 'react';
import './App.css';
import Main from './Main';

const App = () => (

    <div className="panel-body ">
        <Main/>
    </div>

)

export default App;
~
======================= index.js ===========

import React from 'react';
import ReactDOM from 'react-dom';
import App from './App';
import {BrowserRouter} from 'react-router-dom';
import registerServiceWorker from './registerServiceWorker';

ReactDOM.render(
    <BrowserRouter>
        <App />
    </BrowserRouter>, document.getElementById('root'));

registerServiceWorker();


==========P.js =============
 navigateToTask(i,j) {

this.props.history.push('/PT/${i}')
}


  <Table
                        handleSort={this.handleSort}
                        handleRemove={this.handleRemove}
                        startEditing={this.startEditing}
                        editIdx={this.state.editIdx}
                        stopEditing={this.stopEditing}
                        handleChange={this.handleChange}
                        columnToSort={this.state.columnToSort}
                          navigateToTask={this.navigateToTask}
                        data={orderBy(
                            this.state.query
                                ? this.state.data.filter(x =>
                                    x[this.state.columnToQuery]
                                        .toLowerCase()
                                        .includes(lowerCaseQuery)
                                )
                                : this.state.data,
                            this.state.columnToSort,
                            this.state.sortDirection
                        )}

============================

Clicking the button does not navigate to next page if i use props.history.push ();

This works without any issues in dev env, when we generate client code by running
npm run build and using production version, then it breaks.

BrowserRouter version 4.2

**Comment by pshrmn** [comment]
@osoft17 Please try either StackOverflow and Reactiflux. Those sites are designed for answering usage questions.
