### ISSUE TITLE
Inconsistent behavior of match API between use history.push and browser refresh

### ISSUE THREAD

**Issue by minipai** [ReactTraining/react-router#5904]
## Version
react-router-dom 4.2.2 (history 4.7.2)

## Steps to reproduce
- use component ` <Route path="/client/:clientId" component={MyComponent} />`
- `history.push(http://localhost:3001/client/mycom.auth0.com%252F_auth0%257C5a5ae699ca52174a0ba131e4)`
- then refresh the browser 
- url remains same

## Expected Behavior
in `MyComponent`,  `this.props.match.params` give same results

## Actual Behavior
`this.props.match.url ` is
- first: `/client/mycom.auth0.com%252F_auth0%257C5a5ae699ca52174a0ba131e4` 
- after refresh: `/client/mycom.auth0.com%2F_auth0%7C5a5ae699ca52174a0ba131e4`

## My workaround
use native location.pathname

--
Didn't set up live demo online because this involves url change. Thanks.

**Comment by timdorr** [comment]
This is caused upstream by history: ReactTraining/history#505
