### ISSUE TITLE
Warning: React does not recognize the `activeClassName` prop on a DOM element. 

### ISSUE THREAD

**Issue by razzkumar** [ReactTraining/react-router#5909]
## Version
4.1.1

## Test Case
https://codesandbox.io/s/n55VljYk7

**Comment by razzkumar** [comment]
Warning: React does not recognize the `activeClassName` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `activeclassname` instead. If you accidentally passed it from a parent component, remove it from the DOM element. in li (at Navigation.jsx:27) in ul (at Navigation.jsx:26) in div (at Navigation.jsx:25) in div (at Navigation.jsx:10) in nav (at Navigation.jsx:9) in div (at Navigation.jsx:8) in Navigation (at Nav.jsx:39) in div (at Nav.jsx:23) in Nav (at App.js:26) in div (at App.js:25) in App (at index.js:13) in Router (created by BrowserRouter) in BrowserRouter (at index.js:12)

**Comment by timdorr** [comment]
This is an error with your code, not the library.

**Comment by mnemanja** [comment]
(sarcastically) love the description why it's the error with his code...
