### ISSUE TITLE
Feature Request: Allow to set an url pattern in NavLink

### ISSUE THREAD

**Issue by erasmo-marin** [ReactTraining/react-router#5912]
Use case:

You have a sidebar with some menus, for example a users CRUD. You have a URL for different actions, for example: "/users/create", "/users/edit/:id?" and "/users/list". You want a NavLink that redirects to "/users/list" but you also need it to be active if you are in "/users/:any?/:thing?". Would be a nice feature to have a match prop, something like this:

`<NavLink to="/users/list" match="/users/:any?/:thing?">Users</NavLink>
`

**Comment by timdorr** [comment]
You can do this with [the `isActive` prop](https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/modules/NavLink.js#L34). It takes a function with the args of `match` and `location`. 
```js
<NavLink to="/users/list" isActive={(_, { pathname } => pathname.match(/\/users\/\d*\//)}>
```

**Comment by erasmo-marin** [comment]
Hi @timdorr thanks you for your answer. If I do a PR with that feature in my proposal, will it be accepted? Think in it as syntax sugar.

**Comment by timdorr** [comment]
I'd rather not expand the API we have to support. It's already possible today as-is.

**Comment by erasmo-marin** [comment]
Ok, I understand, thank you!
