### ISSUE TITLE
How do you use the history npm package along with BrowseRouter?

### ISSUE THREAD

**Issue by esteem8** [ReactTraining/react-router#5914]
I'm using BrowserRouter
`
<BrowserRouter history={customHistory}>
                    <Route component={Index}/>
                </BrowserRouter>
`

And would like to be able to program a `history.push("/some/path", {});` in pure JS along with making BrowserRouter actualize. "location.pathname" is changing from BrowserRouter even if the url is changing.

I've looked for similar issue and found a lot of solutions with are all more exotic of one an other.
What is a proper way to make it works?

A solution presented in the doc would be very great.

**Comment by timdorr** [comment]
Just use the plain `<Router>`. [That's what `<BrowserRouter>` does under the hood](https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/modules/BrowserRouter.js#L30). It's not a huge component, so you can clone that behavior and make the history instance available globally however you'd like.
