### ISSUE TITLE
React-Router and Flask-Admin

### ISSUE THREAD

**Issue by cinjon** [ReactTraining/react-router#5927]
I have a setup with ReactJS where the routing is handled client sided by React-Router.

Flask-Admin sets up routes prefixed by '/admin'. However, when trying to use these together, the React-Router is clobbering the calls to Flask-Admin.

Is there a way to selectively excuse certain routes from React-Router's purview?

**Comment by pshrmn** [comment]
`<Link>`s are only for links within your application. Use an anchor (`<a>`) for anything else, which includes any links to locations on the same server that shouldn't be handled by the router.
