### ISSUE TITLE
Feature Request: Only render a route when the path doesn't match.

### ISSUE THREAD

**Issue by RocketPuppy** [ReactTraining/react-router#5928]
I've found that there are some cases where I want to render something on every page but one, or two. For example, something like a navigation header, or a site footer. You may want to remove those things in, for example, a checkout flow to remove distractions from the user. On the other hand, I definitely don't want to repeatedly add `<NavHeader />` and `<Footer />` everywhere. It would be nice if I could do something like this:

```javascript
const Footer = () =>
  <Route
    path="/checkout"
    invert={true}
    render={() =>
      <div>
        Some cool footer links here.
      </div>
   } />;
```

#5866 is tracking work on allowing path to accept an array, which would fulfill my use cases exactly. Right now I'm working around this with a component wrapping a `Route` that always renders and doing some checking on the location using `matchPath` before rendering. E.g.

```javascript
<Route
  children={(route) => {
    const anyMatch = Ramda.any(
      r =>
        !!matchPath(route.location.pathname, { path: r, exact: false, strict: false }),
      this.props.paths
    );
    if (!anyMatch) {
      return this.props.children;
    }
    return null;
  }} />
```

**Comment by timdorr** [comment]
Just use a Switch: https://reacttraining.com/react-router/web/example/no-match
