### ISSUE TITLE
set prop-types as peerDependencies ?

### ISSUE THREAD

**Issue by HairyRabbit** [ReactTraining/react-router#5931]
## Version
react-router-redux
version: 5-alpha.9

## Test Case
Hi, I use the umd version in the browser with react-router-redux, it need require prop-types, is that expect?
```html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
  <title></title>
  <script src="https://unpkg.com/react@16.2.0/umd/react.development.js"></script>
  <script src="https://unpkg.com/react-router@4.2.0/umd/react-router.js"></script>
  <script src="https://unpkg.com/react-router-redux@5.0.0-alpha.9/umd/react-router-redux.js"></script>
</head>
<body>
</body>
</html>
```

![image](https://user-images.githubusercontent.com/5752902/36039548-c3d9a284-0dfd-11e8-9045-1e227f361105.png)

[jsbin](http://jsbin.com/tekewuyaru/edit?html,console,output)

**Comment by timdorr** [comment]
Yes, you need it when using the UMD builds: https://github.com/ReactTraining/react-router/blob/master/packages/react-router-redux/rollup.config.js#L14

**Comment by HairyRabbit** [comment]
Thanks, but why this lib is different with other packages, like react-router@4, I see it also require prop-types.

**Comment by timdorr** [comment]
They made the change in React 15.5: https://reactjs.org/docs/typechecking-with-proptypes.html
