### ISSUE TITLE
Use new getDerivedStateFromProps lifecycle method in React 16.3

### ISSUE THREAD

**Issue by ricardobrandao** [ReactTraining/react-router#5932]
As of react 16.3, `componentWillReceiveProps` has been marked as unsafe and should be replaced by `getDerivedStateFromProps`. RFC can be found [here](https://github.com/reactjs/rfcs/blob/master/text/0006-static-lifecycle-methods.md#state-derived-from-propsstate).

**Comment by timdorr** [comment]
We're aware of it, but some of this stuff is still being worked out. Those functions will not be changed in 16.3 from what I understand, but I may be out of date from my last meeting with the React team. Until there is actually a change in place to test against (16.3.0-alpha.0 doesn't have this), this is premature.

**Comment by ricardobrandao** [comment]
`getDerivedStateFromProps` has already [landed](https://github.com/facebook/react/pull/12028) and it is available on 16.3.0-alpha.0. It seems that they will only remove deprecated lifecycle methods on v17 but will start warning about deprecation on v16.4.

**Comment by timdorr** [comment]
The deprecation warnings have not, though. Things aren't in place for us to test against yet. And we're not testing this library against alpha versions.
