### ISSUE TITLE
react-router-config published in NPM is old.

### ISSUE THREAD

**Issue by Vusluk** [ReactTraining/react-router#5936]
I have install `react-router-config` from NPM. And there is no `switchProps` argument in `renderRoutes` function as described in README. Please update npm package.

**Comment by timdorr** [comment]
There hasn't been a release of the current master version.

**Comment by jsartisan** [comment]
same issue. my version of npm does not have switchProps.

**Comment by jsartisan** [comment]
*version of react-router installed through npm does not have switchProps.

**Comment by danieljuhl** [comment]
@timdorr any chance, we can have a release in near future?

**Comment by jsartisan** [comment]
@timdorr we are waiting for the release :/

**Comment by danieljuhl** [comment]
Or said in another way. What's holding it back? react-router-config seems pretty small and simple, and the changes in master is non breaking. Also we are in a pre-release state (beta4). Is there anything we can do to fix whatever is holding back a release?
