### ISSUE TITLE
Proposal: optionally accept history as a prop in Link

### ISSUE THREAD

**Issue by tlvince** [ReactTraining/react-router#5943]
It'd be nice if `<Link>` could optionally read `history` from a prop rather than from context.

https://github.com/ReactTraining/react-router/blob/9cd19e25191aeb20fd99b2532fa71ac20dd5966b/packages/react-router-dom/modules/Link.js#L46

The change could simply be:

```diff
-const { history } = this.context.router;
+const history = this.props.history || this.context.router.history;
```

 ### Background

 Multiple "sub-apps", which are integrated together via a parent app. Sub apps should be able to run standalone and set up their own routing. The parent app "mounts" each sub-app under a child route (via [basename](https://github.com/ReactTraining/history#using-a-base-url)).

 ### Use case

 When you want to link between sub-apps. Given basenames are prefixed to all URLs, the sub-app can't "break out" of its child route.

### Example

See https://codesandbox.io/s/5yvrq309n. Note the basename is prefixed to the link in sub app 1 and 2, so they're broken. As the parent's `history` is passed through to sub app 3, the link (to cross link between sub app) works as expected.

Curious to hear your thoughts on this or other approaches. Thanks! 👋

**Comment by timdorr** [comment]
You can just wrap it up in another Router, overwriting the current context.
```js
const CrossLink = ({ history, ...props }) => <Router history={history}><Link {...props} /></Router>
```
I don't think we need to add this for now.
