### ISSUE TITLE
Auto-deploy website

### ISSUE THREAD

**Issue by mjackson** [ReactTraining/react-router#5944]
[The website](https://reacttraining.com/react-router) should always reflect docs for the code on the master branch. This has been out of sync in the past, and has caused some confusion. To start, the website will only reflect the master branch. We may add support for other branches/tags in the future, but I don't want to complicate things for now.

**Comment by timdorr** [comment]
Where does the website actually live? I can make it happen, I just need some details.

**Comment by mjackson** [comment]
It's in the ReactTraining/reacttraining.com repo, which is private. I just got the website auto-deploying from Travis the other day, so my plan is to have a deploy step in this repo (running on Travis) that checks if there were any changes made to the `website` directory. If so, clone the reacttraining.com repo, build the website into its `public/react-router` dir, make a commit, and push it back to GitHub. This will trigger a new build/deploy of reacttraining.com.

I'm happy to do this work today, but if you'd like to take it on I certainly won't stop you :) I'd just need to make sure that our build env has the ability to clone/push to private repos on GitHub.

**Comment by mjackson** [comment]
Ah, looks like I'll need to setup a special deploy key in order to push to GitHub. I found a useful guide [here](https://github.com/alrra/travis-scripts/blob/master/doc/github-deploy-keys.md). Why don't you let me tackle this one? I just don't wanna block you.

**Comment by timdorr** [comment]
I don't have enough access to things to make it happen anyways. Carry on!

**Comment by pshrmn** [comment]
The one issue I can see with this is that the `master` branch is ahead of what has been released. I would suggest keeping unreleased commits in another branch (e.g. make PRs against `dev` like Vue), but monorepos can make merging back into `master` complicated if everything isn't released at the same time.

**Comment by mjackson** [comment]
Good point, @pshrmn. What if we use a `website` branch instead? That would make it nice and explicit.

**Comment by timdorr** [comment]
We essentially do the same thing on Redux. That works well as a solution.

**Comment by mjackson** [comment]
Fixed in 3595c5ccf190d70c8751dce014db20a935e7ac78

**Comment by mjackson** [comment]
Now, pushing to the `website` branch will trigger a deploy of the website to https://reacttraining.com/react-router
