### ISSUE TITLE
history.push

### ISSUE THREAD

**Issue by shivasai09** [ReactTraining/react-router#5945]
hello, I am using the push method as shown below.. basically passing state along with pathname:-
history.push('/url',search:"someText");
but when i reload my page , only url exists and the state is gone.. 
how to resolve this issue

**Comment by pshrmn** [comment]
`location.state` does not persist across page loads. It should only be used for temporary data, like the location to redirect to after logging in.

If you need to ensure that data is attached to a location, you will need to use either `location.search` or `location.hash` (or include the data in the `pathname`).

```js
history.push({ pathname: '/url', search: '?someText' });
```

**Comment by shivasai09** [comment]
@pshrmn i have understood your explination. But what if i say that my state should be persistant and i dont want to show the data in the URL . so is there any way ?

**Comment by pshrmn** [comment]
`localStorage` might work.

I would recommend asking either on StackOverflow or Reactiflux. Those venues are setup for answering questions, while the issues section here is intended for reporting bugs.
