### ISSUE TITLE
Why react-router-dom must be absolute url path?

### ISSUE THREAD

**Issue by rockmandash** [ReactTraining/react-router#5946]
Hello!
**I just want to know why react-router must be absolute url path?**
Tha hash router can be relative url path right?

If I put my static project which using HashRouter under any url path...
eg.
https://example.com
https://example.com/a
https://example.com/a/b
All cases with routing and assets will work right?
And I don't need to specific basename. It will work too.

But the BrowserRouter will not work right?
If I put it into...
https://example.com/a
and if I...
`history.push('/about')`
Then I will go to...
https://example.com/about <-- breaks here because It should be https://example.com/a/about
And the assets path will break too right?
Because assets like javascript is under https://example.com/a/main.js
But it then go to the wrong url https://example.com/about
So it assumes main.js is under https://example.com/about/main.js which is wrong.

So why not BrowserRouter can auto detect basename?
If I go to https://example.com/a then my basename is /a and it will handle everything for me.

**Comment by timdorr** [comment]
You can pass in a `basename` prop to your BrowserRouter to change the basename.

**Comment by rockmandash** [comment]
![carbon](https://user-images.githubusercontent.com/7580792/36220231-d16318ea-11f4-11e8-8722-c799e2e785df.png)
@timdorr Thank you.
