### ISSUE TITLE
props.match.params not consistent with URL in ShouldComponentUpdate() after <Link> click

### ISSUE THREAD

**Issue by emcelyea** [ReactTraining/react-router#5951]
## Version
4.1.1

## Steps to reproduce
* Url path should be something like path="/item/:id" where :id is a unique identifier.
* Click a <Link> with a to="/item/1"
* Click a <Link> with a to="/item/2", no other props/state changes should happen but this :id change
* Watch for :id changes in ShouldComponentUpdate() (the last place you can safely setState())
* this.props.params.match.id !== :id in the url, in the render() function the value has been updated, but in shouldComponentUpdate() the props have not been updated yet. See screenshot (URL :id != match.params.id):
![screen shot 2018-02-16 at 12 23 56 pm](https://user-images.githubusercontent.com/28745743/36327797-93c0255c-1314-11e8-95fe-d2e0fe85783c.png)

## Expected Behavior
shouldComponentUpdate() will receive this.props.match.params that are consistent with URL

## Actual Behavior
shouldComponentUpdate() contains params from the previous URL.

**Comment by rjharmon** [comment]
I think this is invalid.  You should check nextProps instead.

https://reactjs.org/docs/react-component.html#shouldcomponentupdate

**Comment by timdorr** [comment]
Correct, you are looking at the wrong props.
