### ISSUE TITLE
not able to mergeProps with connect.

### ISSUE THREAD

**Issue by srikar237** [ReactTraining/react-router#5953]
Hi ,

I would like to access the reducer state and dispatch an action in the same component. i am looking for something like this... 
const Home = connect((state,dispatch) => ({
    createUserList: () => { 
        invokeUserListSaga('GET_REQUESTED');
    },
    getUserListState: () => { 
        return state;
    }    
}))(HomeContainer)

but when i get an error saying that dispatch is not a function and does not give reducers' state, any work around to this...?

**Comment by pshrmn** [comment]
This isn't a React Router issue.
