### ISSUE TITLE
Update path-to-regexp dependency

### ISSUE THREAD

**Issue by rjharmon** [ReactTraining/react-router#5954]
path-to-regexp is locked to `^1.7.0`.  Would like to keep up-to-date, just on principle.

(also, I'm adding a PR that needs some of its 2.x goodness)

With path-to-regex v2.1, we still pass all except for one (1) react-router unit test - which expects a trailing slash to be allowable with `<Route exact>`.  

```
  ● A <Route exact> › renders when the URL has trailing slash

    expect(string).toContain(value)

    Expected string:
      ""
    To contain value:
      "bubblegum"

      287 |     );
      288 |
    > 289 |     expect(node.innerHTML).toContain(TEXT);
      290 |   });
      291 | });
      292 |

      at Object.<anonymous> (modules/__tests__/Route-test.js:289:28)
```

## Version
@master - ecc9a73230f574cba138929cd8ef829592609006

See also https://github.com/pillarjs/path-to-regexp/issues/140

**Comment by rjharmon** [comment]
I do not see how `<Route path="/foo/" exact>` should match `/foo` without trailing slash.  Exact is exact, and having an exact route with trailing slash shouldn't match on a path having no trailing slash.

My feeling is that the failing unit test is testing a wrong expectation.  I'm deleting that test in my fork.

**Comment by timdorr** [comment]
This has already been attempted in #5470. We're sticking with 1.0 for now.
