### ISSUE TITLE
per-route args

### ISSUE THREAD

**Issue by rjharmon** [ReactTraining/react-router#5955]
Having dynamic params in the route is great.  You can name them with `path="/foo/bar-:bar"`... or you can make them optional with `path="/foo/:bar?"`.  But you can't do both - out of scope for path-to-regex.  So managing those params, and managing links to them, gets unwieldy fast.

Having access to one set of query ("search") parameters from a route is also useful... except that it's a global namespace, rather than being bound together with a specific route.  

When we write complicated apps with multi-level routes, there are very often use-cases where each level of routing has a responsibility for a set of its own named settings, which should be persisted back to the URL [and/or to a hidden state in history, depending on the case].  In any one of these, I want to be able to specify the behavior of those args (e.g. defaults, hidden-ness, required-ness).  For example:

```
<Route path="/customers" args={{active:1,sort:"name",search:""}}>
```
This sample describes a customers route that has 3 args, whose defaults are shown inline.  A `<Link>` shouldn't have to specify any of these args if it can live with the defaults.

I also want to be able to update any of these args incrementally, allowing a `<Route>`ed component to initiate a small change of URL, e.g. with history.push(...something-with-just-one-arg-changed...).

```
<Route path="/customers" args={{active:1,trashed:0,search:""}} render={({match, update}) => {
   <SearchBox onChange={(needle) => h.push(update({search:needle})) />
   <CheckBox onChange={(checked) => h.replace(update({active:!checked})) label="Include Idle Customers" />
}} />
```

Note that in complicated application environments, clicking one of these customers is likely to lead to a more deeply-nested route like `${match.url}/show`, `${match.url}/edit`, or `${match.url}/invoices.late-1/72942` (these nested routes can add contextual panels without obscuring the customer list - THANKS TO React-Router for partial-routing!).  

We want the higher-level routes to be completely insulated from the nested routes, even to the extent of allowing any of those nesting-levels to use "search", "active", or any other arg names... _*without knowledge or concern of them having been used by a different route entry*_.

**Comment by rjharmon** [comment]
Will make a pull request along this line.  It's not perfect, but it's a good start.  It augments a `path="/customers"` with an `.:args?` dynamic parameter, thus continuing (and extending) leverage of path-to-regex.  WHEN the `args` prop is specified in a `<Route>`, it extracts the args with `import querystring`, expanding their details into `match.params`.  

And it makes an `update()` function available - this reverses the expansion by leveraging the `compile()` function in path-to-regex, with costs deferred until usage.

**Comment by timdorr** [comment]
This sounds an awful lot like just a plain query string. For a variety of reasons, it's not something we support. 

It seems like you're getting too far into the specifics of the path-to-regexp API. We're abstracting over that, so there are places that aren't exactly 1:1. For application-specific use cases, we generally recommend writing small wrapper components to make these kinds of things easier:
```js
export const FooBarLink = ({ id, category, ...props }) => (<Link to={`/foo/${category}/bar/${id}`} {...props}/>)
```
Or something along those lines. We would rather maintain a smaller API surface that solves many use cases, than try to cover every edge case out there.
