### ISSUE TITLE
Let routes depend on location.state

### ISSUE THREAD

**Issue by polkovnikov-ph** [ReactTraining/react-router#5957]
`<Route>` component allows `location` objects in its `path` prop, but [actually](https://github.com/ReactTraining/react-router/blob/master/packages/react-router/modules/Route.js#L68) matches only on `pathname`. It's almost an expected behavior to have

```javascript
<Switch>
	<Route exact path="/a" component={X} />
	<Route exact location={{pathname: '/a', state: 'test'}} component={Y} />
</Switch>
```

and see either `X` or `Y` rendered depending on whether `state` is `undefined` or `'test'`. Currently there is no simple way to do this. You have to use `withRouter` and implement routing by hand, which defeats the purpose of the library in such situations.

I see a problem that there are several possible ways to match on `state`, but it's possible to implement something generally useful (match on primitive type, shallow-match on object) and put a HOC into API that takes a `matcher(state, mask, isExact)` callback and returns a `{Route, Switch, Link, NavLink, ...}` object.

**Comment by timdorr** [comment]
We have never allowed matching on `state`. This is an explicit design decision because it's meant to not be stored in the URL. At the simplest level, we are matching against what is in the URL bar in your browser. State isn't there, so we don't match on it.
