### ISSUE TITLE
matchRoutes only returns first matching route

### ISSUE THREAD

**Issue by bslinger** [ReactTraining/react-router#5959]
`matchRoutes` uses `.some` which returns after the first truthy value is returned, meaning that if there are multiple routes that match passed in, only the first will be returned on `branch`.

https://github.com/ReactTraining/react-router/blob/e6f9017c947b3ae49affa24cc320d0a86f765b55/packages/react-router-config/modules/matchRoutes.js#L8

If there's not a specific reason for this, would you accept a PR for this to use forEach instead?

In my specific use case I am pre-loading data on the server, and would like to be able to logically split up my loading functions by feature. Some of these features will be present on the same route, so I would like matchRoutes to return all of them so I can iterate over those that match and run the functions.

**Comment by timdorr** [comment]
There is a reason. We want it to behave like Switch, where there is only one matching route returned. It's intended for top level configuration where you're only choose one "page" of the app to display.

**Comment by bslinger** [comment]
OK, no problems - will make my own modifications for my use case. Thanks!
