### ISSUE TITLE
Training page is down

### ISSUE THREAD

**Issue by raeesaa** [ReactTraining/react-router#5960]
## Test Case

"Get Training" page on react router [website](https://reacttraining.com/react-router/) is down.

## Steps to reproduce

- Go to "https://reacttraining.com/react-router/"
- Click on "Get Training"

## Expected Behavior

- Training page should be rendered.

## Actual Behavior

- Blank page is rendered with an error in console.

**Comment by vernondegoede** [comment]
It's up again.
