### ISSUE TITLE
props.location.state is null when <Link ... target="_blank">My App</Link>

### ISSUE THREAD

**Issue by Kenigmatic** [ReactTraining/react-router#5962]
## Version v4.2.0

This is essentially the same issue reported in #5883, except that the new tab/window is launched using the React-Router Link property `target="_blank"` instead of the browser's `right-click ... open in new tab` sequence. Using URL parameters is not an option for me, so I was hoping that I could pass some properties via location.state. Unfortunately my app has a requirement of opening a new window (or tab) when launched from its dashboard page.

## Steps to reproduce
`<Link to={{ pathname: '/path/name', state: { foo: "bar" } target="_blank" }}>Launch App</Link>
`
## Expected Behavior
Component at /path/name should see `props.location.state.foo === "bar"`

## Actual Behavior
`props.location.state === null`

**Comment by timdorr** [comment]
State isn't included in the URL. If you're opening a new window, that will load the app up fresh, using the incoming URL to route. This is intentional. You can add to the search string or open the window yourself and do some postMessage magic.

**Comment by Kenigmatic** [comment]
Tim,

Thanks for the suggestions. Using location.search would be the easiest except that the content appears in the address bar and I need to keep the URLs clean. But that may be useful for other others who come across this thread.

Ken
