### ISSUE TITLE
Very bad documentation, add search box

### ISSUE THREAD

**Issue by DmitryOlkhovoi** [ReactTraining/react-router#5967]
Every time I've ever want to read about something (this time about nested routes) I cant find it.
You've splitter react router into separate modules that confuse a lot.

I found docs about Nested Routes accidentally in "Philosophy" guide. It seems strange to me.
Please, guys, do something about it. You do a great thing, thanks a lot, I've used it for a very long time, but now, it's really hard to find something fast, and it's frustrating.
Add search box to docs and nested sub nav items

Thanks!

**Comment by timdorr** [comment]
Adding search is not straightforward, as our build process is custom. We would have to build that ourselves somehow. For now, you can use a site-specific search: https://www.google.com/search?q=site%3Ahttps%3A%2F%2Freacttraining.com%2Freact-router%2F+nested+routes

As for other comments about the docs, issues aren't normally very actionable. A PR would be the correct way to handle it.
