### ISSUE TITLE
activeClassName not set in PureComponent when use NavLink

### ISSUE THREAD

**Issue by b-ponomarenko** [ReactTraining/react-router#5968]
## Version
`react-router-dom: 4.2.2`

## Test Case
https://codesandbox.io/s/ovnoznw9

## Steps to reproduce
Open sandbox and click to links

## Expected Behavior
When click on link active class should be set to clicked dom element

## Actual Behavior
Active class not set to clicked dom element

I think this behaviour associated with `shouldComponentUpdate` lifecycle hook in PureComponent, because when I change PureComponent to Component everything is working.
I want to understand is it bug of expected behaviour. Thanks!

**Comment by timdorr** [comment]
See this guide: https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/guides/blocked-updates.md

This will go away with the new context API in React 16.3.
