### ISSUE TITLE
Add server configuration docs for BrowserRouter

### ISSUE THREAD

**Issue by natkuhn** [ReactTraining/react-router#5975]
Posting this here at the the request of Michael Jackson.

My email to hello@reacttraining is below, about the lack of information in the documentation on how to configure servers so that &lt;BrowserHistory&gt; will work.

The "one tutorial" I refer to below was Paul Sherman's https://medium.com/@pshrmn/a-simple-react-router-v4-tutorial-7f23ff27adf .  I posted a comment on it, and heard this back from him:

The closest explanation in the RR repo is this FAQ entry I wrote https://github.com/ReactTraining/react-router/blob/master/FAQ.md#why-doesnt-my-application-render-after-refreshing.

This is hard to find and in any case IMO the subject would benefit from a more careful treatment.

Thanks! Nat Kuhn

<-- original email -->
Hi, react-router looks really great!

react-router info on configuring the server seems to have disappeared from the docs!

Unfortunately, it is very hard to tell what is required from a server to use &lt;BrowserHistory&gt;.

This page (https://reacttraining.com/react-router/web/api/HashRouter) says “we encourage you to configure your server to work with &lt;BrowserHistory&gt; instead” without a link.

One tutorial says you need a “dynamic server” rather than a “static server,” which doesn’t quite seem to be standard terminology, and without much additional explanation.

A number of places (include SO answers) refer to this dead link: https://github.com/ReactTraining/react-router/blob/master/docs/guides/Histories.md#configuring-your-server

I was not able to track down the correct version on my own, but stumbled on one: https://github.com/ReactTraining/react-router/blob/v2.0.0-rc5/docs/guides/basics/Histories.md#configuring-your-server.  Unfortunately,  the information there is incomplete, covering only express and nginx. There seems to be more complete handling of express here: https://github.com/reactjs/react-router-tutorial/tree/master/lessons/11-productionish-server. Not much good for those of us whose production code goes on apache servers.

Googling is very problematic because when you google “react-router server configuration” you get a ton of hits about server-side rendering.

This seems like the most complete exposition: https://www.gitbook.com/book/gkedge/react-router-in-the-real/details. However, it also assumes that your app is the root of your domain.  It would be great to document how to configure when you are deploying to a subfolder like example.com/demos/app

This post seems to have some discussion of that: https://stanko.github.io/react-router-subfolder-on-server/

Otherwise, both the product and the documentation are great!

Thanks, Nat

**Comment by timdorr** [comment]
A PR for this would be most helpful!

**Comment by natkuhn** [comment]
@timdorr I am pretty much a total newb--and have very little time on my hands--but I will put this on my list and hope it bubbles up. If someone else wants to do it, I am more than happy to help.

**Comment by tarang9211** [comment]
Is this still open guys?

**Comment by timdorr** [comment]
Yup

**Comment by tarang9211** [comment]
Could you let me know what has to be done? I use react-router but I am not an expert so to say.

**Comment by timdorr** [comment]
The OP explains it.

**Comment by tarang9211** [comment]
@natkuhn Totally new to contributing to this repo. Could you let me know the needs exactly?

**Comment by timdorr** [comment]
We keep guides here: https://github.com/ReactTraining/react-router/tree/master/packages/react-router/docs/guides

You can add one for server configuration. Don't worry about hooking it up to the website. We can do that afterwards.

**Comment by tarang9211** [comment]
Awesome, but what about the content? I am not sure about what content goes in there.

**Comment by timdorr** [comment]
Look at any of the other guides for formatting examples.

**Comment by natkuhn** [comment]
I am also totally new to this, too, which is why I haven’t done the PR myself

**Comment by tarang9211** [comment]
Yea, but what about the content? I am not too sure what server configuration is. Sorry :(

**Comment by natkuhn** [comment]
@tarang9211 Then you may not be the best person to do the PR at this point

**Comment by tarang9211** [comment]
This is a PR that is labeled good for first time contributors.

**Comment by tarang9211** [comment]
@timdorr could you guide me a little bit more?

**Comment by timdorr** [comment]
This is probably not something you should work on then. You need to at least know what the subject is about. The OP describes it, so if that's not making sense, I'm not sure what I can do for you.

**Comment by tarang9211** [comment]
Ok. I was really looking forward to contributing here since I am actively using this library :(

**Comment by natkuhn** [comment]
That’s really wonderful that you want to give back! I hope that this has not discouraged you, that is not the intention. Stick with it, learn more, and one day there will be something that you either already understand or you have a pretty good idea how to get there, and then take off!  All the best, Nat

**Comment by timdorr** [comment]
Yeah, sorry for being a Negative Nancy, I just don't think this is a good fit for you personally. But browse through the other issues and see if any strike a chord. We've got a few dozen open opportunities to contribute.

**Comment by pshrmn** [comment]
Is this asking for information about configuring the server for single-page applications? That seems a bit broad for us to keep documented since there are so many possible ways to setup servers.

There is [this article](https://medium.com/@baphemot/understanding-react-deployment-5a717d4378fd) by @btmpl that should point you in the right direction for configuring Apache.

**Comment by timdorr** [comment]
It's basically this: https://github.com/ReactTraining/react-router/blob/v3/docs/guides/Histories.md#configuring-your-server

**Comment by tarang9211** [comment]
No worries. If this is basically copying & pasting content, I can do it @timdorr .

**Comment by natkuhn** [comment]
Ack! I see that all my &lt;BrowserHistory&gt; tags had disappeared; I edited the OP. @timdorr your link to the v3 docs is very helpful since unlike the doc I managed to find it includes apache configuration. It would be lovely to format that with some subsection headers for the 3 servers (express, nginx, apache). As mentioned in the OP would be great to document is what to do if your app is not at the root of your domain but is some other page, and @pshrmn's link has something on that.

**Comment by ItamarShDev** [comment]
> It's basically this: https://github.com/ReactTraining/react-router/blob/v3/docs/guides/Histories.md#configuring-your-server

this seems to be the answer, 
I wanted to jump in and help, but fail to  see what more needs to be added there
