### ISSUE TITLE
NavLink not working without pathname

### ISSUE THREAD

**Issue by hellqvist** [ReactTraining/react-router#5977]
## Version
master (commit: https://github.com/ReactTraining/react-router/commit/e6f9017c947b3ae49affa24cc320d0a86f765b55)

## Test Case
https://codesandbox.io/s/3x3oxk33k6

## Steps to reproduce
Add a NavLink without pathname, only search in the to object. 

## Expected Behavior
Classname active shall be added on all paths as long as the query matches the search value. 

## Actual Behavior
TypeError
Cannot read property 'replace' of undefined

Before escaping characters in path we need to verify that it's not null or undefined.

**Comment by hellqvist** [comment]
No but Link (and NavLink) is working today with only search set. It will only set the query and leave the actual path as it is. In 4.2.2 NavLink is working fine with only search. As long as no special characters is used in the path

**Comment by timdorr** [comment]
That's because #5596 landed after 4.2.2 was released. 

But that brings up a good point. The check for a blank pathname would be better.

**Comment by timdorr** [comment]
Fixed in 6d9c4250. Thanks!

**Comment by hellqvist** [comment]
Great job
