### ISSUE TITLE
React router config install without react-router get warning

### ISSUE THREAD

**Issue by Rukeith** [ReactTraining/react-router#5979]
## Version
"react-router-config": "^1.0.0-beta.4"
"react-router-dom": "^4.2.2"

## Test Case
None

## Steps to reproduce
yarn add react-router-config

## Expected Behavior
Without warning

## Actual Behavior
Get warning
`warning " > react-router-config@1.0.0-beta.4" has unmet peer dependency "react-router@^4.2.0".`

I expect it won't get this warning. I use `react-router-config` with `react-router-dom`. Is `react-router-config` need to install both of `react-router` and `react-router-dom` ?

**Comment by timdorr** [comment]
Yes, you need to install both. It's fine, as it's already installed by react-router-dom, so it's nothing more than one line in your package.json file.

**Comment by Rukeith** [comment]
@timdorr Thank your response. I just afraid that it might crash my project
