### ISSUE TITLE
Route component doesn't update component upon store update

### ISSUE THREAD

**Issue by abubakkarbutt** [ReactTraining/react-router#5982]
I am new to react, react-router, redux and react-redux. I am trying to connect() route component to store like this.
`export default connect(mapStateToProps, null)(UserPage);`
```
<Router>
  <Route path="/" component={HomePage} />
  <Route path="/user" component={UserPage} />
</Router>
``` 
But when store is updated the UserPage component doesn't not re-render and get props.
Please help me solve it. Thanks

**Comment by timdorr** [comment]
See this guide: https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/guides/blocked-updates.md
