### ISSUE TITLE
NavLink doesn't get active on hash links

### ISSUE THREAD

**Issue by vince1995** [ReactTraining/react-router#5995]
## Version

16.2

## Steps to reproduce

```
<NavLink>  
    to="/foo/#bar"  
</NavLink>
```

## Expected Behavior

Being on path"/foo/#bar" the NavLink should be active.

## Actual Behavior

The NavLink isn't active.

## Workaround
```
const to="/foo/#bar"  
<NavLink>  
    to={to}  
    isActive={()=>{  
        return window.location.pathname + window.location.hash === to;  
    }}  
</NavLink>
```

**Comment by timdorr** [comment]
We don't support hash links. This is because of HashRouter and the need to support a hash-based history.

**Comment by vince1995** [comment]
Ok, I understand this, but how come `/foo#bar` is working?

**Comment by timdorr** [comment]
It's the trailing slash. We parse out /foo/#bar to `{pathname: '/foo/', hash: 'bar'}` and strip the trailing slash for the matching to provide normalization. It's an implementation quirk.
