### ISSUE TITLE
<Router basename={'/path'}></Router> not working as expected

### ISSUE THREAD

**Issue by pzehle** [ReactTraining/react-router#5997]
## Version

"react-router-dom": "^4.2.2"

## Test Case
https://funnel.garritz.com/doncarro/ (it should redirect to /doncarro/login/), instead it is just rendering the 404 error I put there.

## Steps to reproduce
Trying to deploy to subdirectory on my server.

**.htaccess**
`Options -MultiViews
    RewriteEngine On
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^ index.html [QSA,L]`

**Router**
`<Router basename={'/doncarro'}>
        <Switch>
                <Route exact path={`${process.env.PUBLIC_URL}/dashboard`} component={Dashboard}></Route>
                <Route exact path={`${process.env.PUBLIC_URL}/campaigns`} component={Campaigns}></Route>
                <Route exact path={`${process.env.PUBLIC_URL}/leads`} component={Leads}></Route>
                <Route exact path={`${process.env.PUBLIC_URL}/admin`} component={Admin}></Route>
                <Route exact path={`${process.env.PUBLIC_URL}/admin/users`} component={AdminUsers}></Route>
                <Route exact path={`${process.env.PUBLIC_URL}/admin/users/:id`} component={AdminUserInfo}></Route>
                <Route exact path={`${process.env.PUBLIC_URL}/admin/users/:id/edit`} component={AdminUserEdit}></Route>
                <Route exact path={`${process.env.PUBLIC_URL}/user`} component={User}></Route>
                <Route exact path={`${process.env.PUBLIC_URL}/logout`} component={Logout}></Route>
                <Redirect exact from={`${process.env.PUBLIC_URL}/`} to={`${process.env.PUBLIC_URL}/dashboard`} />
                <Route component={NotFound} status={404}></Route>
        </Switch>
</Router>`

**package.json**
`{
  "homepage": "https://funnel.garritz.com/doncarro",
  "name": "funnel",
  "version": "0.0.1",
  "private": true,
  "dependencies": {
    "babel-polyfill": "^6.26.0",
    "react": "^15.6.1",
    "react-datepicker": "^0.54.0",
    "react-dom": "^15.6.1",
    "react-router-dom": "^4.2.2",
    "victory": "^0.24.2"
  },
  "devDependencies": {
    "react-scripts": "1.0.7"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  }
}`

## Expected Behavior
It should be rendering https://funnel.garritz.com/doncarro/dashboard or /doncarro/login (depending on localStorage).

## Actual Behavior
It is just showing the 404 error there. It seems to not be considering the `basename={'/doncarro'}` at all, as if I remove it, build it and upload it again to public_html -> doncarro, it seems to work just fine. Either I am doing something wrong, or it seems that in my case it is just worthless to include `basename={'/doncarro'}`.

Hope you can help me. Thanks!

**Comment by pshrmn** [comment]
When you use a `basename`, the `basename` should _not_ be included in the `pathname`.

```jsx
<BrowserRouter basename='/test'>
  <Route exact path='/' /> {/* this matches the url example.com/test */}
</BrowserRouter>
```

**Comment by pzehle** [comment]
I feel so stupid now. Thank you!
