### ISSUE TITLE
"Prevent page from creating additional dialogs" breaks Prompt

### ISSUE THREAD

**Issue by Midgar77** [ReactTraining/react-router#6000]
## Version

**4.2.0**

## Steps to reproduce
1. Use IE 11 or Firefox (or probably any recent browser except Chrome). Use Prompt for any situation where user clicks something to leave the page and a Prompt dialog appears.
2. Click 'Cancel' to stay on the page
3. Trigger the Prompt dialog again
4. This time there should be an option to 'Prevent page from creating additional dialogs." Select that, click cancel.
5. Now any action (like clicking Back button) that should have triggered a Prompt do absolutely nothing. The buttons/links become dead because the Prompt dialog is suppressed.

## Expected Behavior
When user selects for page to not create additional dialogs, Prompt dialog should no longer appear, but the action should still happen. Ex: If clicking on back button, should still go back a page but see no Prompt.

Prompt should have a way to still trigger the action even if the call to `history.block` was suppressed.

## Actual Behavior
After additional dialogs are suppressed, any action that would have triggered a Prompt is completely dead. Ex: Clicking back button does absolutely nothing after user selects "Prevent page from creating additional dialogs."

**Comment by pshrmn** [comment]
This is a browser feature. If you _really_ need to get around this, you can use a custom `getUserConfirmation` function for your history that detects if dialogs are blocked and automatically navigates if they are. 

https://reacttraining.com/react-router/web/api/BrowserRouter/getuserconfirmation-func

https://stackoverflow.com/questions/11571015/how-to-detect-prevent-this-page-from-creating-additional-dialogs

**Comment by Midgar77** [comment]
Hmm yeah the "prevent additional dialogs" is a browser feature, but it seems like a bug for Prompt to make a button click be completely ignored because of it. I would think that Prompt should still enable the action, just not show the dialog
