### ISSUE TITLE
Prompt breaks when "prevent page from creating additional dialogs" is selected

### ISSUE THREAD

**Issue by Midgar77** [ReactTraining/react-router#6001]
## Version

**4.2.0**

## Steps to reproduce
**This IS a bug with Prompt because it does not have correct behavior in this case.**
1. Use IE 11 or Firefox (or probably any recent browser except Chrome). Use Prompt for any situation where user clicks something to leave the page and a Prompt dialog appears.
2. Click 'Cancel' to stay on the page
3. Trigger the Prompt dialog again
4. This time there should be an option to 'Prevent page from creating additional dialogs." Select that, click cancel.
5. Now any action (like clicking Back button) that should have triggered a Prompt do absolutely nothing. The buttons/links become dead because the Prompt dialog is suppressed.

## Expected Behavior
When user selects for page to not create additional dialogs, Prompt dialog should no longer appear, but the action should still happen. Ex: If clicking on back button, should still go back a page but see no Prompt.

Prompt should have a way to still trigger the action even if the call to `history.block` was suppressed. This is what any other functional website does when user selects to prevent additional dialogs.

## Actual Behavior
After additional dialogs are suppressed, any action that would have triggered a Prompt is completely dead. Ex: Clicking back button does absolutely nothing after user selects "Prevent page from creating additional dialogs."

**Comment by pshrmn** [comment]
Please do not open duplicate issues (#6000).

As I said before, you can use a custom `getUserConfirmation` function if you want to implement functionality to get around a user preventing dialog popups. `window.prompt` is the default, but the prompt can be anything you want it to be.

**Comment by Midgar77** [comment]
@pshrmn But I'm not trying to get around user preventing dialog popups. The issue is not that the user has the ability to prevent dialog popups, the issue is that when the user selects that, the action that would normally trigger the Prompt dialog popup is completely ignored. This IS a bug
