### ISSUE TITLE
withRouter blocks rendering if somewhere above the path <Route children with non matched path exists

### ISSUE THREAD

**Issue by istarkov** [ReactTraining/react-router#6004]
`withRouter` blocks rendering if somewhere above the path 
`<Route children` with non matched path exists.

Example:
https://codesandbox.io/s/7mzr57yv4j

content of `Hello.js` is not rendered,
but if remove `withRouter` HOC from it all works fine.

**Comment by timdorr** [comment]
This is already fixed by #5964. It's not yet released.
