### ISSUE TITLE
browserHistory doesn't exist in react-router

### ISSUE THREAD

**Issue by ShubhamKushwah** [ReactTraining/react-router#6007]
```javascript
import { browserHistory, Router, Route, IndexRoute } from 'react-router'
```
Shows error: 
```
'react-router' does not contain an export named 'browserHistory'.
```

Here is the code [https://github.com/ReactTraining/react-router/blob/v2.0.0-rc5/docs/guides/basics/Histories.md#example-implementation](Code)

PS: I want to user v3+

**Comment by timdorr** [comment]
You have to install v3 of react-router. You have the wrong version installed.

**Comment by ShubhamKushwah** [comment]
Thanks! @timdorr I got it.

this link helped: [npm-package@version](https://www.npmjs.com/package/@version/react-router-v3/tutorial)

```
npm i @version/react-router-v3
```

**Comment by timdorr** [comment]
That is not the right version and not a package we maintain. I wouldn't trust that. `npm install react-router@3` is the correct way to install.

**Comment by ShubhamKushwah** [comment]
Is there any page where I can found some alternatives for browserHistory?

Such as:
for redirecting instead of using:

```
browserHistory.push("/back")
```

we can use 

```
this.props.history.push("/back")
```
and pass it through an onClick function in your Component.
etc. etc.

**Comment by timdorr** [comment]
https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/guides/migrating.md

**Comment by ShubhamKushwah** [comment]
Thanks man! that's awesome
Exactly what I wanted.
