### ISSUE TITLE
<Link onClick={e => e.stopPropagation} />

### ISSUE THREAD

**Issue by braco** [ReactTraining/react-router#6010]
```
const noPropagation = e => e.stopPropagation()
const LinkNoPropagate = props => <Link {...props} onClick={noPropagation} />

<LinkNoPropagate to="/next">Test</LinkNoPropagate>
```

Doing this seems to break react-router, is that expected? The URL will change, but not the page content. 

I'm trying to capture a click with a `<Link />` inside a Table cell from material-ui. Material-ui is taking the click event as a row selection.

**Comment by timdorr** [comment]
Yes, you use propagation/default prevention as a signal to Link to not process this click: https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/modules/Link.js#L39

**Comment by braco** [comment]
So that means there's no way to use stopPropagation properly, doesn't it? How would I stop a parent container from registering the Link click event?

Also, as noted, the URL still changes, the transition just doesn't happen, is that a bug?

**Comment by timdorr** [comment]
It's not a bug because it's still a regular `a` tag. This is causing it to fall back to the default behavior. 

If you want to stop propagation, do so at a higher level. Wrap it in a component that intercepts the event and stops it there.

**Comment by braco** [comment]
You're saying something like this?

```
const noPropagation = e => e.stopPropagation()
const LinkNoBubble = props => <span onClick={noPropagation}><Link {...props} /></span>
```

It still breaks parts of the routing.

I switched to a regular `<a href="/.." onClick={noPropagation} />` and everything works again.
