### ISSUE TITLE
nested route not rendered or accessible with Authentication implemented from example of docs

### ISSUE THREAD

**Issue by dhirajbasukala** [ReactTraining/react-router#6012]
## Version

react-router: 4.2.2 

## Test Case

https://codesandbox.io/s/50o13jz42l

## Steps to reproduce

After clicking login button the first of route gets rendered even when only there is not path match. 

## Expected Behavior

Should render the corresponding sub-component after logging in like if URL-path is '/one' should render One component and same for '/two', but in both cases first route defined gets rendered. It seems a bit out of place. 

## Actual Behavior
None of the nested routes inside authenticated route gets rendered.

**Comment by timdorr** [comment]
Your Route props are wrong. You use `path`, not `to`.
