### ISSUE TITLE
react-router-redux: page not changing

### ISSUE THREAD

**Issue by nWidart** [ReactTraining/react-router#6018]
## Version

- react-router-dom@^4.2.2
- react-router@^4.2.0
- react-router-redux@5.0.0-alpha.9

## Steps to reproduce

Folllowing the readme, to setup the store.

## Expected Behavior

Ability to change pages

## Actual Behavior

`@@router:LOCATION_CHANGE` is dispatched and the state is changed, but page does not change.

My code:

```js
# store.tsx
import { applyMiddleware, createStore } from 'redux';
import { composeWithDevTools } from 'redux-devtools-extension/developmentOnly';
import thunk from 'redux-thunk';
import rootReducer from './reducers';
import createHistory from 'history/createBrowserHistory';
import { routerMiddleware } from 'react-router-redux';

export const history = createHistory();
const routerMiddlewareObject = routerMiddleware(history);

export const store = createStore(
  rootReducer,
  composeWithDevTools(applyMiddleware(thunk, routerMiddlewareObject)),
);
```

```js
#reducers.tsx
import { combineReducers } from 'redux';
import { authenticationReducerObject } from 'react-auth';
import { routerReducer } from 'react-router-redux';


const rootReducer = combineReducers({
  routerReducer,
  // my reducers
});

export default rootReducer;

```

```js
#app.tsx
import * as React from 'react';
import { Provider } from 'react-redux';
import { store, history } from '../state/store';
import { ConnectedRouter } from 'react-router-redux';


class App extends React.Component {
  render() {
    return (
      <Provider store={store}>
        <ConnectedRouter history={history}>
          // my app
        </ConnectedRouter>
      </Provider>
    );
  }
}

export default App;
```

Did I miss something?

Thanks!

**Comment by timdorr** [comment]
See this guide: https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/guides/blocked-updates.md

**Comment by nWidart** [comment]
Thank you for the comment.

I don't see why this is needed, what it acoomplishes.
Furthermore, the [documentation](https://github.com/ReactTraining/react-router/tree/master/packages/react-router-redux) of `react-router-redux` doesn't mention this anywhere.

**Comment by timdorr** [comment]
It's not an issue of RRR. It's React Redux (`connect` specifically) blocking context updates, which React Router relies on. That document has all the info you need on that problem (which will go away in React 16.3 and React Router 4.4)

**Comment by nWidart** [comment]
Ok thank you for the explanation.
I've tried wrapping every component that uses `connect` with `withRouter` sadly it still doesn't work.

I guess I'll have to wait until the next version of react is released.

**Comment by kongdewen1994** [comment]
How to solve
