### ISSUE TITLE
Should I use react-router-redux 5 or react-router-redux 4 with react-router4 ?

### ISSUE THREAD

**Issue by vipcxj** [ReactTraining/react-router#6019]
In the document of react-route-redux, it says react-router-redux 5 works for react-router4. But there is only alpha version of react-router-redux 5. And in the issure, I found a lot of people still use react-router-redux 4 with react-router 4.

**Comment by pshrmn** [comment]
You need to use `react-router-redux` v5 with `react-router` v4; `react-router-redux` v4 isn't compatible with RRv4. You should probably look into whether or not you really need to use `react-router-redux` (you most likely will get along fine without it).
