### ISSUE TITLE
Redirect doesn't work in Route's render method?

### ISSUE THREAD

**Issue by thian4** [ReactTraining/react-router#6021]
I follow the pattern of authentication of https://reacttraining.com/react-router/web/example/auth-workflow but somehow my attempt doesn't work with `<Redirect />` 

## Version
Latest

**Please replace this sentence with the React Router version that you are using.**

## Test Case
https://codesandbox.io/s/qkx5k827vw

## Steps to reproduce
visit https://qkx5k827vw.codesandbox.io/dashboard and you shall see it doesn't redirect.
 
## Expected Behavior
It can redirect using <Redirect />

## Actual Behavior
Show warning, then nothing happens

**Comment by pshrmn** [comment]
```js
// this
const { Component: component, ...rest } = this.props;
// should be
const { component: Component, ...rest } = this.props;
```
For future usage questions, please use either StackOverflow or Reactiflux. Those sites are setup for answering questions, whereas the issues section here is intended for bug reports.
