### ISSUE TITLE
Feature Suggestion

### ISSUE THREAD

**Issue by thecodecafe** [ReactTraining/react-router#6028]
I would like to suggest a feature for React Router Native, there are cases where on one will want to reset the current route stack and navigate to a new router as the base.

## Scenerio
A user launches the mobile app, goes to the login form and enters his login details, after the person has been authenticated, he gets redirected to the home scene, from there, even when the user clicks on the back button the routes do not navigate back to the login form.

I hope I get listened to, I haven't giving it a shot at developing anything for React Native so far, so I don't really know how to go about doing that, If I did would have implemented and done a PR, but all the same I hope I get listened to, and thanks for your efforts so far to the open source community, been using React Router from day one.

**Comment by timdorr** [comment]
You can do this by forcing React to re-create the NativeRouter instance with a `key` prop:
```js
<NativeRouter key={currentUser.id} />
```
