### ISSUE TITLE
Documentation on Switch

### ISSUE THREAD

**Issue by ExceptionCaught** [ReactTraining/react-router#6032]
In the documentation for Swtich: 
https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/api/Switch.md
It quotes:
> if the URL is `/about`, then `<About>`, `<User>`, and `<NoMatch>`

Is it meant to be `/` only? Then it will match default, "/about" and "/:user"

**Comment by timdorr** [comment]
I'm not sure what you're asking here. That sentence is correct.
