### ISSUE TITLE
Link component is not rendered in modal using portal

### ISSUE THREAD

**Issue by dshivprasad** [ReactTraining/react-router#6033]
Context is not passed when modal is opened using a portal, which appends the modal dom outside the context.
## Version
react-router-dom 4.2.2

## Test Case
https://codesandbox.io/s/yq0jy7n1nv  (without context provider)
https://codesandbox.io/s/00r23nynzw (with context provider)

When opened this issue with atlassian library, according to below link, it is coming from the latest version of react router. Please refer below link
https://bitbucket.org/atlassian/atlaskit-mk-2/issues/16/context-is-not-passed-to-modal-dialog

## Steps to reproduce
Use Link component from react-router-dom to component rendered outside dom

## Expected Behavior
Link should be rendered
## Actual Behavior
getting error "You should not use <Link> outside a <Router>"

**Comment by timdorr** [comment]
[It looks like](https://bitbucket.org/atlassian/atlaskit-mk-2/src/master/packages/core/layer-manager/src/components/Portal.js?at=master&fileviewer=file-view-default) they don't use [React's official Portal API](https://reactjs.org/docs/portals.html), so it's not surprising this doesn't work. One of the big things the official API added was context along the portal boundary. You won't be able to use "DIY portals" with React Router.
