### ISSUE TITLE
BrowserRouter displays only 1 route while there are 4 routes

### ISSUE THREAD

**Issue by MorelCisse** [ReactTraining/react-router#6038]
Hi, I use the "React-Router" for a while but I have a problem. Here are the screenshots. Has anyone ever encountered this problem? I use this with laravel.

App.js
BrowserRouter as Router
![capture du 2018-03-23 13-59-20](https://user-images.githubusercontent.com/26247346/37830431-79fbf0e8-2ea2-11e8-9385-547448106a7d.png)

React developpers Tools - Console
![browserrouter](https://user-images.githubusercontent.com/26247346/37830066-aa45cfe0-2ea1-11e8-97f9-5dfca496b6d2.png)

Package.json
"react": "^16.2.0",
![package json](https://user-images.githubusercontent.com/26247346/37830145-dcd1b802-2ea1-11e8-99ac-a678b55c637f.png)

I placed 4 routes in my router but in the react developer console, I have a unique route that appears and when I click on the links of my navbar, i'm not redirect automaticaly. Help me please.

**Comment by pshrmn** [comment]
React's dev tools is only displaying the components that are rendered. The way that `<Switch>` works is that it is iterating over your `<Route>`s (in the order they are defined) to find the first one that matches the current location's `pathname`.

In the screenshot above, you can see that the location's pathname is `/`, so your Home `<Route>` is the one that gets rendered.

As far as what is happening with your navbar, you haven't actually provided any code to see what is happening. I would recommend opening up a question on StackOverflow or checking out the React Router room in the Reactiflux chatroom. Those places are setup to answer questions, while the issues section here is intended to be used for bug reports.

**Comment by MorelCisse** [comment]
Okay Thank you @pshrmn !!!
