### ISSUE TITLE
withRouter() is needed, it should have thrown error.

### ISSUE THREAD

**Issue by manu1222** [ReactTraining/react-router#6040]
I have been dealing with an issue where I was getting a blank page, after spending so much of time, somehow I found this link: https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/guides/redux.md#blocked-updates and I was able to resolve the issue.

But I believe if it could throw me some errors, it would be great for me to think like that instead of feeling blank and spending so much of time that could have been spent on actual development.

So my code was: `export default connect(mapStateToProps)(AdminLayout)` and it has to be `export default withRouter(connect(mapStateToProps)(AdminLayout));` that was it, but I had to spend the tremendous amount of time.

**Comment by timdorr** [comment]
There isn't a way for us to detect this. The underlying issue (blocking unseen context properties) makes this fundamentally impossible. If we could detect it, we wouldn't throw an error, we would just fix the issue! :)
