### ISSUE TITLE
https://reacttraining.com/   can't open

### ISSUE THREAD

**Issue by msforest** [ReactTraining/react-router#6041]
![image](https://user-images.githubusercontent.com/16268045/37870509-7eaa8bd6-300a-11e8-92a6-3b4a99707244.png)

please check that. I am from china.

thanks in advance

**Comment by richb-hanover** [comment]
More info: https://reacttraining.com/ fails with this `twttr is not defined` error, and a blank page

https://reacttraining.com/react-router/ has the same error, but renders the expected page

**Comment by mjackson** [comment]
Access to Twitter is currently blocked in China, so it's probably blocking the twitter.js file as well. I'll fix that on reacttraining.com.

However, we aren't even loading twitter.js anywhere in the router documentation site, so you shouldn't be seeing the error on reacttraining.com/react-router. Can you please double check, @richb-hanover?

**Comment by richb-hanover** [comment]
Sorry, I only offered an incomplete bug report. 

1. As noted, the main https://reacttraining.com site previously was blank. Console showed an error about `twttr not defined...`

2. The https://reacttraining.com/react-router site previously displayed as desired in the browser. However, at that time, Console showed the same/similar `twttr not defined`

3. Everything is good now: the main page and react-router page both display as expected, with only a minor error in Console for the latter page

**Comment by msforest** [comment]
thank you. now everything is okay.

**Comment by mjackson** [comment]
You're welcome 👍
