### ISSUE TITLE
building of react-router-dom fails

### ISSUE THREAD

**Issue by original001** [ReactTraining/react-router#6043]
## Version
react-router-dom
**4.3.0-rc.1**

## Test Case
simple build with webpack

## Steps to reproduce
build with webpack

## Expected Behavior
package should be bundled without errors

## Actual Behavior
webpack crashes with error:
```
ERROR in ./~/react-router-dom/index.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./generatePath in /Users/vova/works/cement/keweb/KEWeb.React/node_modules/react-router-dom
 @ ./~/react-router-dom/index.js 50:21-46
```

**Comment by timdorr** [comment]
Ah, good catch. We added that file as a new one to the repo, but it didn't get included in the package.json file list.

**Comment by timdorr** [comment]
Pushed out 4.3.0-rc.2, which should fix this. Thanks for the report!
