### ISSUE TITLE
react-router-redux dispatch(push()); changes Url but doesnt rerender

### ISSUE THREAD

**Issue by Eurythmax** [ReactTraining/react-router#6045]
After trying every Bugfix found on the internet we still cant redirect without problems. The current state is, that after push the link changes but the DOM doesn't re-render.
This is an issue because it cant be that hard to redirect so it's totally unusable.

index.js
`const DOMTarget =	document.getElementById('root');

ReactDOM.render(
	<Provider store={store}>
		<ConnectedRouter history={history}>
			<MuiThemeProvider theme={theme}>
				<App />
			</MuiThemeProvider>
		</ConnectedRouter>
	</Provider>,
	DOMTarget
);
registerServiceWorker();
`
App.js
`import React from 'react';
import { Reboot } from 'material-ui';
import { Switch, Route, BrowserRouter as Router, withRouter } from 'react-router-dom';

import Shell from '../Shell';
import Home from '../Home';
import Verify from '../Verified';
import Event from '../Event/EventWrapper';
import RoomWrapper from '../Room/RoomWrapper';
import Room from '../Room/RoomComponent';

const App = () => (
	<React.Fragment>
		<Reboot/>
		<Router>
			<div>
				<Shell/>
				<Switch>
					<Route exact path="/" component={Home}/>
					<Route exact path="/room" component={RoomWrapper}/>
					<Route path="/room/:id" component={Room}/>
					<Route exact path="/event" component={Event}/>
					<Route exact path="/verify" component={Verify}/>
				</Switch>
			</div>
		</Router>
	</React.Fragment>
);

export default withRouter(App);
`

and in my Action
`import { push } from 'react-router-redux';

export const ROOM_CREATE = 'ROOM_CREATE';

export const valueRoomCreate = (roomName, roomHash) => ({
	type: ROOM_CREATE,
	roomName,
	roomHash,
	created: true,
});

export const valueRoomCreateWithRouteChange = (roomName, roomHash) => (dispatch) => {
	dispatch(valueRoomCreate(roomName, roomHash));
	dispatch(push(`/room/${roomHash}`));
};
`

**Comment by timdorr** [comment]
See this guide: https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/guides/blocked-updates.md

**Comment by heisaman** [comment]
@timdorr I have the same issue. Following your guide doesn't help too much.

**Comment by iamawwsome** [comment]
The issue is  the push action doesn't trigger the address to change. Even if you dispatch @@router/LOCATION_CHANGE, the router will not render the desired component.

Here is a solution that works for me.

```
// constants.js
export const REDIRECT = 'REDIRECT';
```

```
// actions.js
export function redirect(path) {
  return {
    type: REDIRECT,
    path,
  };
}
```

```
// reducer.js
import { REDIRECT } from './constants';

export function reducer(state = initalState, action) {
  switch(action.type) {
    case REDIRECT:
      return state.set('redirect', fromJS({
        path: action.path,
      }));
  }
}
```

```
// MyComponent.js
import { Redirect } from 'react-router-dom';

const MyComponent = (props) => {
  const { redirect } = props;


  if (redirect.get('path', false)) {
    return <Redirect to={redirect.get('pathname')} />;
  }

  return <p>Hello Wordl!</p>
}

const mapStateToProps = ...

export default connect(mapStateToProps)(MyComponent);

```
