### ISSUE TITLE
Feature Request：Migrating from v3 to v4

### ISSUE THREAD

**Issue by SnowFlowers** [ReactTraining/react-router#6046]
Thank you for contributing!

Have a feature request?
=======================
I was asked to be responsible for the migration scheme for our production. There are almost thirty projects used react-router v3.  But v4 loose several important functions . such as onEnter,onLeave and nested dynamic routes for code split.  Completely changed. so i had to realize this by myself, especially code split for routes not for component. so i hope v4 can reliaze these excited functions.  

v4 is a real router.  Combined with React so perfect. 
Because i don't konw why the author haven't realize it . so i don't report a pull request.

**Comment by timdorr** [comment]
https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/guides/migrating.md

**Comment by SnowFlowers** [comment]
@timdorr i can't find result form this doc for my feature request.  maybe the title of this issue is not suitable. i hope you can read the content again. thanks

**Comment by timdorr** [comment]
The onEnter/onLeave are replaced by standard React lifecycle methods. If you need a top-level route config, look at react-router-config.

**Comment by SnowFlowers** [comment]
@timdorr OKOK,thank you. my fault.
