### ISSUE TITLE
Docs layout is broken around 1280px

### ISSUE THREAD

**Issue by vgrafe** [ReactTraining/react-router#6052]
Hi there, I am not sure if this is the right repo to create an issue into but the layout on [reacttraining.com](https://reacttraining.com/react-router/) breaks here and there when the browser width is around 1280px.

Example:
![screen shot 2018-03-30 at 2 42 54 pm](https://user-images.githubusercontent.com/3950855/38149530-d674ecd6-3428-11e8-8259-bcf1456f316f.png)

**Comment by mjackson** [comment]
Yep @vgrafe, this is the correct repo. You can find the website code in [the `website` directory in the repo root](https://github.com/ReactTraining/react-router/tree/master/website).

**Comment by vgrafe** [comment]
Hi @mjackson! Sorry, I am kindof new participating in OSS - I cloned the repo and am trying to `yarn && yarn start` the website, but get webpack errors on both `master` and `website` branches. Am I missing something ?

**Comment by vgrafe** [comment]
Maybe the error messages will help 😀

```
ERROR in ./modules/components/App.js
Module not found: Error: Can't resolve '../../../packages/react-router-dom/BrowserRouter' in '/Users/vgrafe/Perso/react-router/website/modules/components'
 @ ./modules/components/App.js 9:21-80
 @ ./modules/index.js
 @ multi ../node_modules/webpack-dev-server/client?http://0.0.0.0:8081 ./modules/index.js

ERROR in ./modules/ReactRouterDOMShim.js
Module not found: Error: Can't resolve '../../packages/react-router-dom' in '/Users/vgrafe/Perso/react-router/website/modules'
 @ ./modules/ReactRouterDOMShim.js 6:22-64
 @ ./modules/components/App.js
 @ ./modules/index.js
 @ multi ../node_modules/webpack-dev-server/client?http://0.0.0.0:8081 ./modules/index.js
```

**Comment by pshrmn** [comment]
@vgrafe 

1. This shouldn't be causing your errors, but this repo uses `npm` not `yarn` (so using `yarn` would generate unnecessary yarn lock files).
```bash
npm install
```
2. You don't need to touch the `website` branch, just create a branch off of `master` to make your changes in.
```bash
git checkout master
git checkout -b website-fix
```
3. Can you be more specific about the errors? After you `npm install`, Lerna (the monorepo support package RR uses) should bootstrap (install dependencies for all of our packages), so in theory everything should be ready to go at that point.

**Comment by pshrmn** [comment]
@vgrafe Run `npm run build` in the root.

**Comment by vgrafe** [comment]
Ok so my solutions:

* A straightforward solution could be to increase the breakpoint defined [there](https://github.com/ReactTraining/react-router/blob/website/website/modules/base.css#L134)  (1355px seems safe for all examples). Is it too high?
* min-width could be set a `min-width` for the `.api-doc-wrapper` parent div.
* we can set word-wrap to the code examples. 

Let me know what seem to be the best way to to that and I'll be happy to open a tiny PR!

**Comment by mjackson** [comment]
Thanks for your suggestions, @vgrafe :)

Would you mind posting another screen shot with how things look with your suggestions so we can see how it looks with the changes?

Thank you!

**Comment by timdorr** [comment]
Looks like increasing the breakpoint size will fix it. PR for that is here: #6107
