### ISSUE TITLE
Use new forwardRef API in withRouter HOC

### ISSUE THREAD

**Issue by sanniassin** [ReactTraining/react-router#6056]
React 16.3 is out and now we have an "official" way to pass ref through HOCs with new [forwardRef API](https://reactjs.org/docs/react-api.html#reactforwardref). Would you like to use it as a replacement for `wrappedComponentRef` prop to make wrapping transparent for parent components?

Can submit a PR.

**Comment by pshrmn** [comment]
@sanniassin The issue with using `forwardRef` right now is that React Router still supports React < 16.3. Unless there is a polyfill for forwarding refs like there is with new/legacy context via `create-react-context`, RR won't be able to support this until its React min dep is increased.

**Comment by sanniassin** [comment]
@pshrmn It should be easy to check if `forwardRef` is available and pass ref argument only if it is. The only problem is potential breaking change when ref callbacks on wrapped components suddenly become callable, but I don't think it's a real problem because React alerts you if you try to define ref on stateless component without ref forwarding.

**Comment by timdorr** [comment]
We're dealing with this on react-redux as well: reactjs/react-redux#914

I think it's mainly about forwarding in the ref properly, not anything to do with BC support.

**Comment by jathanasiou** [comment]
I just decided to move to the `forwardRef` API for the HOCs in our application because there is a large amount of logic relying on `ref` for various components that I recently rewrote with composition. Of course right now the `Route` calls are complaining with:  
```
Warning: Failed prop type: Invalid prop `component` of type `object` supplied to `Route`, expected `function`. in Route
```
as the object being passed as `component` prop to `<Route>` right now is

```
{$$typeof: Symbol(react.forward_ref), render: ƒ}
```

Is there any workaround that could be used to forward refs to Components wrapped by a HOC while simultaneously having functional routing?

**Comment by jathanasiou** [comment]
@kevinL5 It's been a while since I look into this matter but I *think* I had partial success with passing the refs through my outer HOCs like so:
```javascript
export default function outerHOC() {
	return function(WrappedComponent) {
		return class Better extends React.Component {
			render() {
				// ...
				return <WrappedComponent passedRef={this.props.passedRef} { ...this.props}/>
			}
		}
	}
}

// unlike the Better HOC, this always wraps MyActualBaseComponent
export default function innerHOC() {
	return function(WrappedComponent) {
		return class Stronger extends React.Component {
			render() {
				// ...
				return <WrappedComponent ref={this.props.passedRef} { ...this.props}/>
			}
		}
	}
}

class MyActualBaseComponent extends React.Component {/*...*/}
export outerHOC()(innerHOC()(MyActualBaseComponent))


import BetterStronger from './MyActualBaseComponent'
class IndexControlComponent extends React.Component {
	constructor(props) {
		super(props)
		this.neededRef = React.createRef()
	}
	render() {
	const betterStronger = <BetterStronger passedRef={this.neededRef} {/*some props*/} />
	}
	needyFunction () => { // needs to control the wrapped MyActualBaseComponent instance
		this.neededRef.current.doSomethingBetter()
		this.neededRef.current.doSomethingStrong()
	}
	// ...
}
```

It is a very hacky workaround however. Ideally we should try to avoid using refs with HOCs until this issue is resolved on react-router.

**Comment by mdecaffmeyer** [comment]
Same problem with react-router using forwardRef
> Warning: Failed prop type: Invalid prop `component` of type `object` supplied to `Route`, expected `function`. In Route [...]

**Comment by mjackson** [comment]
Please see #6327. I believe that should fix this issue?

**Comment by mjackson** [comment]
Ah, sorry. I think I misunderstood what this issue was about when I commented before.

Yes, we should update `withRouter` to use the `React.forwardRef` API. As @pshrmn noted above, we can't do it in 4.x because it is compatible with React 15 and the `forwardRef` API [was introduced in 16.3](https://reactjs.org/blog/2018/03/29/react-v-16-3.html#forwardref-api).

We will fix this in version 5 when we upgrade our dep to React 16.7+.

**Comment by oreporan** [comment]
Hey, I needed to forward refs a couple of times in my code due to creating styled-elements that were to be reused.

What I ended doing was creating a `withForwardingRef` 

```ts
import React from 'react';

const withForwardingRef = <Props extends {[_: string]: any}>(BaseComponent: React.ReactType<Props>) =>
    React.forwardRef((props, ref) => <BaseComponent {...props} forwardedRef={ref} />);

export default withForwardingRef;

```

usage:

```ts
const Comp = ({forwardedRef}) => (
 <Whatever ref={forwardedRef} />
)
const EnhanceComponent = withForwardingRef<Props>(Comp);  // Now Comp has a prop called forwardedRef
```

**Comment by esellin** [comment]
I see that v5 is out now (https://reacttraining.com/blog/react-router-v5/), but I'm struggling to find any documentation on how to use forwardRef and withRouter() together. Can anyone help?

**Comment by timdorr** [comment]
@esellin We haven't bumped the React version in 5.0, so we can't yet support forwardRef.

**Comment by bsotodo** [comment]
I just renamed the `ref` prop in the outter componente to `myRef` and pass it down to the component I want a ref from.

**Comment by charlax** [comment]
This also applies to `NavLink` btw, and since material-ui's v4, it's raising a lot of warnings for things such as `<ListItem component={NavLink} ...>`...

> Warning: Failed prop type: Invalid prop `component` supplied to `ForwardRef(ButtonBase)`. Expected an element type that can hold a ref. Did you accidentally provide a plain function component instead? For more information see https://material-ui.com/guides/composition/#caveat-with-refs

**Comment by eps1lon** [comment]
@charlax And this is why the section describes a workaround. We even explicitly document it for react-router: https://material-ui.com/components/links/#third-party-routing-library

**Comment by charlax** [comment]
Indeed! I knew about this page but did not think to look it up when using `NavLink`. Thanks!

**Comment by ranjith-s** [comment]
> React 16.3 is out and now we have an "official" way to pass ref through HOCs with new [forwardRef API](https://reactjs.org/docs/react-api.html#reactforwardref). Would you like to use it as a replacement for `wrappedComponentRef` prop to make wrapping transparent for parent components?
> 
> Can submit a PR.

Finally, I have done this way! this will work for sure

import { withRouter } from 'react-router';

//Just copy and add this withRouterAndRef HOC
const withRouterAndRef = (WrappedComponent) => {
class InnerComponentWithRef extends React.Component {    
      render() {
          const { forwardRef, ...rest } = this.props;
          return <WrappedComponent {...rest} ref={forwardRef} />;
      }
  }
  const ComponentWithRouter = withRouter(InnerComponentWithRef, { withRef: true });
  return React.forwardRef((props, ref) => {
      return <ComponentWithRouter {...props} forwardRef={ref} />;
    });
}

class MyComponent extends Component {
   constructor(props) {
      super(props);
   }
}

//export using withRouterAndRef
export default withRouterAndRef (MyComponent);

**Comment by ranjith-s** [comment]
> React 16.3 is out and now we have an "official" way to pass ref through HOCs with new [forwardRef API](https://reactjs.org/docs/react-api.html#reactforwardref). Would you like to use it as a replacement for `wrappedComponentRef` prop to make wrapping transparent for parent components?
> 
> Can submit a PR.

> React 16.3 is out and now we have an "official" way to pass ref through HOCs with new [forwardRef API](https://reactjs.org/docs/react-api.html#reactforwardref). Would you like to use it as a replacement for `wrappedComponentRef` prop to make wrapping transparent for parent components?
> 
> Can submit a PR.

Finally, I have done this way! this will work for sure

```
import { withRouter } from 'react-router';

//Just copy and add this withRouterAndRef HOC

const withRouterAndRef = (WrappedComponent) => {
class InnerComponentWithRef extends React.Component {    
      render() {
          const { forwardRef, ...rest } = this.props;
          return <WrappedComponent {...rest} ref={forwardRef} />;
      }
  }
  const ComponentWithRouter = withRouter(InnerComponentWithRef, { withRef: true });
  return React.forwardRef((props, ref) => {
      return <ComponentWithRouter {...props} forwardRef={ref} />;
    });
}

class MyComponent extends Component {
   constructor(props) {
      super(props);
   }
}

//export using withRouterAndRef

export default withRouterAndRef (MyComponent)
```

**Comment by pandaiolo** [comment]
As suggested [in original SO question](https://stackoverflow.com/a/57823539/1644131), here is a version built on @ranjith-s work, a bit simpler and that supports `displayName` which can be useful in tests or dev tools.

```js
const withRouterAndRef = Wrapped => {
  const WithRouter = withRouter(({ forwardRef, ...otherProps }) => (
    <Wrapped ref={forwardRef} {...otherProps} />
  ))
  const WithRouterAndRef = React.forwardRef((props, ref) => (
    <WithRouter {...props} forwardRef={ref} />
  ))
  const name = Wrapped.displayName || Wrapped.name
  WithRouterAndRef.displayName = `withRouterAndRef(${name})`
  return WithRouterAndRef
}
```

**Comment by KaDaniil** [comment]
I think it is easier to create your own component like this
```
import React from 'react';
import { Link as MaterialLink } from '@material-ui/core';
import { Link as RouterLink } from 'react-router-dom';

export default function (props) {
  const MiddlewareLink = React.forwardRef((props, ref) => <RouterLink innerRef={ref} {...props} />);
  return <MaterialLink component={MiddlewareLink} {...props} />;
}
```

**Comment by eps1lon** [comment]
I guess this can be closed anyway since `withRouter` is no longer part of the API in v6.
