### ISSUE TITLE
Docs navigation broken on mobile

### ISSUE THREAD

**Issue by mjackson** [ReactTraining/react-router#6058]
Shrink your browser down to < 600px so you see the mobile optimized page (single column) and click on any of the navigation. You'll get an error like this in the console:

![screen shot 2018-04-02 at 3 02 33 pm](https://user-images.githubusercontent.com/92839/38218716-9d9d8ae2-3687-11e8-8292-18aede059253.png)

I tracked down the error, and it looks like we may not be using the proper `NODE_ENV` when we build the website in production.

![screen shot 2018-04-02 at 3 06 31 pm](https://user-images.githubusercontent.com/92839/38218751-b22843d0-3687-11e8-88d4-63945f2d8992.png)

**Comment by mjackson** [comment]
Just noticed this was already reported in #6023.

**Comment by sag1v** [comment]
@mjackson I think after moving to react 16

[this line](https://github.com/ReactTraining/react-router/blob/master/website/modules/animated/targets/react-dom.js#L40):  
` comp._reactInternalInstance`

Should be:
`comp._reactInternalFiber`

Not sure though :thinking:

**Comment by sag1v** [comment]
@mjackson  After playing around, the change i proposed above :arrow_up:  did help, however there is another error, now within `react-css-property-operations/lib/CSSPropertyOperations.js`.
There is no `_currentElement` property in `component` (again i think it's a conflict with the new react 16).
There is however a `_debugOwner` property.

![fiberowner](https://user-images.githubusercontent.com/9153149/38275248-f6481c58-3799-11e8-8302-a1b15ae33089.jpg)

I'm not sure what was the reason for using `react-css-property-operations` but it seems that it is [abandoned](https://github.com/meyer-archives/react-css-property-operations).

<hr/>

**As a side note**, I had a lot of errors while trying to run the website locally. seems like most of the paths to the modules in `react-router-dom` are off. 
They are targeting to the root of `react-router-dom` instead to `react-router-dom/modules`

Just to name a few: [ReactRouterDOMShim](https://github.com/ReactTraining/react-router/blob/master/website/modules/ReactRouterDOMShim.js#L16), [generatePath](https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/modules/generatePath.js#L2), [MemoryRouter](https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/modules/MemoryRouter.js#L2) and the list goes on...

I guess this should be on a different issue then.

Hope I helped :)

**Comment by pshrmn** [comment]
@sag1v you have to run `npm run build` in the root so that the monorepo packages get built. I updated the `CONTRIBUTING.md` file earlier to reflect this, but as I mentioned in #6061, we should probably auto-build after install so that new contributors don't have to go looking for build instructions.

**Comment by mjackson** [comment]
I created an un-minified webpack build to try and figure out what is going on here (see attached) 🕵️

It looks like our bundle includes a `process` shim which is preventing `process.env.NODE_ENV` from being evaluated properly at build time, so the debugging code with the `_debugID` isn't being stripped out.

<img width="687" alt="screen shot 2018-04-24 at 9 25 36 am" src="https://user-images.githubusercontent.com/92839/39200635-8abf2874-47a1-11e8-8d8f-5076b6921ed2.png">

However, it also looks like we have a **bundle within our bundle**, probably because the Animated code isn't an actual dependency (it's just copied over from an older version of the library) 🙃

For example, you can see here that entry # 463 in the outer bundle actually exports a webpack bundle of the Animated library:

<img width="639" alt="screen shot 2018-04-24 at 9 28 06 am" src="https://user-images.githubusercontent.com/92839/39200743-d58e7580-47a1-11e8-8603-4b92335bb6bc.png">

So I'm guessing we need to either a) fix that inner bundle and get the `process` shim out of it so the webpack `DefinePlugin` can do its job and replace all the `process.env.NODE_ENV` references or b) figure out which commit (`git bisect`, anyone?) caused this weird behavior and undo the regression.

I've uploaded my build here in case anyone would like to go poking around

👇
[build.zip](https://github.com/ReactTraining/react-router/files/1943678/build.zip)
