### ISSUE TITLE
multiple level Redirect doesn't work

### ISSUE THREAD

**Issue by xiechao06** [ReactTraining/react-router#6064]
## Version

react-router-dom 4.2.2

## Test Case
https://codesandbox.io/s/5mv2v0w93n

## Steps to reproduce

  * click a
  * click b
  * click item1

## Expected Behavior

go to route /item/1
   

## Actual Behavior
stay in route /b,  (in fact, go to /item/1 and back to /b again)

BTW, if open https://5mv2v0w93n.codesandbox.io/b, then click item1, everything works.

**Comment by timdorr** [comment]
Your Nav component is overriding the redirect below it.
