### ISSUE TITLE
Visited links not recognized as visited in IE11

### ISSUE THREAD

**Issue by aij** [ReactTraining/react-router#6067]
## Version

react-router 3.2.0, also tested with latest react-router-dom (4.2.2) in sandbox.

IE version 11.0.9600.18953

## Test Case

https://codesandbox.io/s/3rzmpz67o1

(sandbox shows buggy behavior on IE 11 and Chrome 65, but expected behavior on Firefox 58)

## Steps to reproduce

Set a style for visited links, for example

```
a:visited {
    color: #800080;
}
```

Have users using Internet Exploder 11. (Use yourself for testing, MS has VM images available.)

Click on a <Link >, then go back to the previous page.

## Expected Behavior

Links  should be recognized as visited after following them.

## Actual Behavior

Links do not get the visited style applied in IE11, but do in Firefox and Chrome.

Upon further experimentation, it appears IE11 doesn't even consider the URL to be visited, even if it is currently showing in the Location field. I also noticed it reverts the favicon back to the IE logo.

Reloading while on a specific page *does* result in links to that page appearing as visited.

I'm not sure what the best way to fix this is. One possible workaround would be to keep track of all the pages visited from within JS and apply a `className` with a style matching the visited style. Getting that to work properly will be pretty ugly though.

**Comment by timdorr** [comment]
If there's a browser bug where they are not counting `pushState` calls as visits, there's not much we can do about that. You may be able to find a solution with traversing the history location stack, but that's not something we're going to implement.

**Comment by aij** [comment]
Fair enough. Is there any documentation on which browsers are supported? It's pretty common for JS libraries to implement workarounds for bugs in supported browsers, though I couldn't tell whether IE is even supposed to be supported by react-router. 

I haven't tested yet, but it sounds like Edge might be broken too.

**Comment by timdorr** [comment]
We use Babel, so it should cover any browser that supports ES5 code. The BrowserRouter should be anything that supports history.pushState, so IE11+.

**Comment by aij** [comment]
Here's the Microsoft issue just for the record: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/11373805/

(No workarounds listed as of this date)
