### ISSUE TITLE
please include history action (PUSH, POP, REPLACE) in LOCATION_CHANGE payload

### ISSUE THREAD

**Issue by ilovett** [ReactTraining/react-router#6068]
It is beneficial to know **how** a user navigating, for example in a location change saga.  I don't see why it can't be included in the action payload.

**Comment by timdorr** [comment]
Check the current history's `location.action` if you need to know why.

**Comment by ilovett** [comment]
Ah, I did not realized I could hook into it that way.  Thank you.  Apologies for the issue.
