### ISSUE TITLE
"react-router-dom": "4.2.1", 报错

### ISSUE THREAD

**Issue by tibic** [ReactTraining/react-router#6071]
"dependencies": {
    "axios": "^0.18.0",
    "express": "^4.16.3",
    "react": "16.2.0",
    "react-dom": "16.2.0",
    "react-hot-loader": "next",
    "react-router": "^4.2.0",
    "react-router-dom": "4.2.1",
    "serve-favicon": "^2.5.0"
  }

ERROR in ./node_modules/react-router-dom/es/index.js
Module not found: Error: Can't resolve './BrowserRouter' in '/Users/valentine/reactjs_webpack_demo/node_modules/react-router-dom/es'
 @ ./node_modules/react-router-dom/es/index.js 1:0-45
 @ ./client/app.js
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8888 webpack/hot/dev-server react-hot-loader/patch ./client/app.js

ERROR in ./node_modules/react-router-dom/es/index.js
Module not found: Error: Can't resolve './HashRouter' in '/Users/valentine/reactjs_webpack_demo/node_modules/react-router-dom/es'
 @ ./node_modules/react-router-dom/es/index.js 3:0-39
 @ ./client/app.js
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8888 webpack/hot/dev-server react-hot-loader/patch ./client/app.js

ERROR in ./node_modules/react-router-dom/es/index.js
Module not found: Error: Can't resolve './Link' in '/Users/valentine/reactjs_webpack_demo/node_modules/react-router-dom/es'
 @ ./node_modules/react-router-dom/es/index.js 5:0-27
 @ ./client/app.js
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8888 webpack/hot/dev-server react-hot-loader/patch ./client/app.js

ERROR in ./node_modules/react-router-dom/es/index.js
Module not found: Error: Can't resolve './MemoryRouter' in '/Users/valentine/reactjs_webpack_demo/node_modules/react-router-dom/es'
 @ ./node_modules/react-router-dom/es/index.js 7:0-43
 @ ./client/app.js
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8888 webpack/hot/dev-server react-hot-loader/patch ./client/app.js

ERROR in ./node_modules/react-router-dom/es/index.js
Module not found: Error: Can't resolve './NavLink' in '/Users/valentine/reactjs_webpack_demo/node_modules/react-router-dom/es'
 @ ./node_modules/react-router-dom/es/index.js 9:0-33
 @ ./client/app.js
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8888 webpack/hot/dev-server react-hot-loader/patch ./client/app.js
The question has bothered me for a long time, what should I do?

**Comment by timdorr** [comment]
This isn't a problem with react-router. It's with your build tooling/configuration or installation.
