### ISSUE TITLE
Switch does not reflect redirect by history.push in parent component lifecycle method

### ISSUE THREAD

**Issue by iki** [ReactTraining/react-router#6073]
## Version

- react-router-dom@4.2.2
- react-router-redux@4.0.8
- react-router@4.2.0

## Steps to reproduce

Redirect by history.push in parent component lifecycle method. Eg. in a security container that perform authorization and redirects accordingly

## Expected Behavior

Switch renders the new path.

## Actual Behavior

Switch renders the old path. Which may break if it expects some state, that is not available.

Upon inspection, this is caused by `Switch` using the `location` property, which doesn't reflect the `history.location` property updated with `history.push`.

Solution would be using `history.location` instead. Proved with workaround 2 below.

## Workaround 1

Detect redirect in the parent component and do not render children, including Switch:

```
import { branch, compose, lifecycle, renderComponent, withHandlers } from 'recompose'

const isRedirecting = ({ history, location }) => history.location.pathname !== location.pathname

const enhancers = [
  withRouter,
  ...
  branch(
    props => isRedirecting(props),
    renderComponent(props => console.debug('auth.redirecting', props) || null),
  ),
]

```

## Workaround 2

Force `location` property on `Switch` to be `history.location`.

```
const SwitchWithProps = ({ children, ...props }) => (
  <Switch location={props.history.location}>
    {React.Children.map(children, child =>
      React.cloneElement(child as any, { ...props, location: props.history.location }),
    )}
  </Switch>
)
```

**Comment by timdorr** [comment]
The problem is in your auth container's `render` method. It should not be rendering children if there isn't authorization. Check out the auth example: https://reacttraining.com/react-router/web/example/auth-workflow
