### ISSUE TITLE
[feature] [conceptual] register Switch children through algebraic effects

### ISSUE THREAD

**Issue by tjallingt** [ReactTraining/react-router#6077]
React's new "suspense" feature uses (a form of) algebraic effects to pause and resume rendering of components. It does this by throwing a `Promise` which is caught in a component higher in the tree and when resolved it continues/re-renders. 

It would be nice if react router `Route`s could throw a `RouteRegistration` that could either be caught by the `Router` or by the `Switch`. The `Router`s behaviour would be to continue the rendering of all `Route`s whereas the `Switch` could register all thrown `RouteRegistrations` and continue rendering on a single matching `Route`.

The advantage of this over a callback based api is that it becomes a lot of wiring to make sure the correct registration ends up in the right parent component. Currently this is done in reverse where the `Switch` is in charge of registering it child `Route` instead of the `Route`s registering themselves with the `Switch`.

Related issue(s): https://github.com/ReactTraining/react-router/issues/5546

Currently the "suspense" API is internal to React (and unreleased/unstable) so it hard to say if this is/will ever be possible but who knows...

Thoughts and opinions are welcome 😄

~~~if none of this makes sense lemme know and/or close the issue idk...~~~

**Comment by timdorr** [comment]
Interesting idea, but for now, this is entirely covered via Context (for deep child communication) and there's the fact that Switch only operates on its direct children. And that's intentional, because you could end up with unexpected behavior depending who's in your ancestry, which you might not control.
