### ISSUE TITLE
Where is the react-router-redux documentation?

### ISSUE THREAD

**Issue by ir-fuel** [ReactTraining/react-router#6080]
The only thing I found is:

https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/guides/redux.md

Otherwise there are no docs whatsoever on how to use it. 

Am I looking in the wrong places?

**Comment by timdorr** [comment]
The readme: https://github.com/ReactTraining/react-router/blob/master/packages/react-router-redux/README.md

**Comment by ir-fuel** [comment]
Interesting definition of "documentation" you have. Half of the existing actions aren't even shown in that readme.

**Comment by timdorr** [comment]
Yep, it's minimal. A PR to improve it would be appreciated!
