### ISSUE TITLE
history.push cannot replace full url

### ISSUE THREAD

**Issue by Kenzku** [ReactTraining/react-router#6081]
## Version

4.2.2

## Test Case
```es6

/*<base href="http://127.0.0.1">*/
export function historyPushState(state = {}, title = '', url = '') {
  let baseTag = document.getElementsByTagName('base')[0];
  if (!!baseTag) {
    let realRequestDestination = baseTag.getAttribute('href');
    let maskedRequestDestination = window.location.origin;
    if (maskedRequestDestination !== realRequestDestination) {
      return history.pushState(state, title, `${realRequestDestination}${url}`);
    }
  }
  return history.pushState(state, title, url);
}

export function historyPush(reactRouterHistory = {}, url = '') {
  let baseTag = document.getElementsByTagName('base')[0];
  if (!!baseTag) {
    let realRequestDestination = baseTag.getAttribute('href');
    let maskedRequestDestination = window.location.origin;
    if (maskedRequestDestination !== realRequestDestination) {
      return reactRouterHistory.push(`${realRequestDestination}${url}`);
    }
  }
  return reactRouterHistory.push(url);
}
```
## Steps to reproduce
Hej,

1. the `historyPushState` can replace browser's url to another url e.g. `http://127.0.0.1` to `http://localhost`; while `historyPush` can replace the url's path e.g. `http://localhost/path?a=b1` to `http://localhost/another/path?a=b2`

2. if there is base tag in the entry html file, and the base tag having a different href attribute than the url in the browser, history push will complain Same Origin Policy violation

3. with `historyPushState `, I can by pass the step 2 error, but I cannot use the same logic for `historyPush ` i.e. with react-router's history push function. 

Assume in my browser, I have url http://localhost, and in the base tag, I have href as http://127.0.0.1.

Then, with `historyPush ` I will get something like http://127.0.0.1/http://127.0.0.1

I guess there are other approaches out of react-router, like I can make update the base tag to be the same as the browser's url at the entry point, but sometimes, this is not always true, and sometimes, assuming the base tag is fixed.

## Expected Behavior
I was expecting the react-router's history push acts like history.pushState that can also replace the full url. 
## Actual Behavior
I will get something like http://127.0.0.1/http://127.0.0.1 (a url appended to another url)

**Comment by timdorr** [comment]
`history.pushState` follows the same origin policy, so that is not correct. It will return an error like this:

> history.pushState({}, 'test', 'https://test.com')

> Uncaught DOMException: Failed to execute 'pushState' on 'History': A history state object with URL 'https://test.com/' cannot be created in a document with origin 'https://github.com' and URL 'https://github.com/ReactTraining/react-router/issues/6081'.

Check step 2, substep 4 of the specification: https://www.w3.org/TR/2011/WD-html5-20110113/history.html#dom-history-pushstate
