### ISSUE TITLE
Feature Request: ConnectedRouter does not support basename

### ISSUE THREAD

**Issue by gu3st** [ReactTraining/react-router#6083]
Hi:

So, I've been building an application that uses Redux and I've been getting errors that my <Link>'s differ between SSR and Client Side rendering.  The SSR links seem to lack the basename.  I've tried setting the basename property, but it seems that functionality is actually only implemented in BrowserRouter/StaticRouter/HashRouter.

It's valuable for my application, as the application I build is mounted at a subpath to the actual top level domain and routed to via a top level nginx proxy.

If there's functionality I've missed (or a somewhat easy thing to add to my store creation) that'd be a good help (and then I can go and try to add that to documentation somewhere.

Thanks,

**Comment by timdorr** [comment]
For server rendering, you should be using StaticRouter. There is no point in connecting your history to the store because there isn't a second render pass for it to be effective down the tree.

**Comment by gu3st** [comment]
Ok, but this still doesn't address basename not being supported by ConnectedRouter.

There is also value in ConnectedRouter (Or even possibly a ConnectedStaticRouter) on the server side, as an application could dispatch actions in the SSR phase that could require issuing a redirect.

StaticRouter does have some useful functionality (the context obj so I can handle 301/404 from SSR), but lacks the ability to actually redirect via dispatching actions during SSR which my application actually has the capability to do so.

**Comment by gu3st** [comment]
MemoryHistory doesn't contain basename.
