### ISSUE TITLE
NavLink fails to apply activeClassName or activeStyle with long complex URLs

### ISSUE THREAD

**Issue by Jahans3** [ReactTraining/react-router#6086]
My site has some long URLs, consisting of an area code and some locations the user has set. I want to use `NavLink` for the menu links. All I need to do is apply a class but the `activeClassName` and `activeStyle` props are not working with these long URLs.

I can see that a match has actually been found - the `match` argument from the `isActive` callback is not null as expected, however no active classes or styles are applied.

This does not seem to affect shorter, less complex URLs.

## Version
4.2.2

## Test Case
https://codesandbox.io/s/m390wqpomp

## Steps to reproduce
1. Open the codesandbox.io link above
2. Copy the link sitting inside the `to` prop of the `NavLink`
3. Paste into code sandbox browser URL bar
4. Inspect "This fails" in the code sandbox browser
5. See that the `activeClassName` has not been applied

## Expected Behavior
The string inside the `activeClassName` prop should have been applied to the element.

## Actual Behavior
No active class was applied to the link

**Comment by timdorr** [comment]
The issue is the URL-encoded segments of the link. This is actually an issue with the underlying history library and is tracked here: ReactTraining/history#505
