### ISSUE TITLE
5.0 (@next): Error for Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export #4700

### ISSUE THREAD

**Issue by cannibal** [ReactTraining/react-router#6087]
Error for Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export #4700

Occurs on import of ConnectedRouter. Fresh install of 5.0 using Yarn.

I note that the issue #4700 is closed, but people are still getting the problem.

Code to reproduce:
```
import React from 'react';
import PropTypes from 'prop-types';
import {Switch, Route} from 'react-router';
import { ConnectedRouter, routerReducer, routerMiddleware, push } from 'react-router-redux'


class App extends React.Component {
  render() {
    const {history, ...rest} = this.props;

      return (<ConnectedRouter> <div/></ConnectedRouter>

    );
  }
}

App.propTypes = {
    history: PropTypes.object.isRequired
};

export default App;

```

**Comment by timdorr** [comment]
There is something wrong with your build tooling or your install. That error happens when you pass a non-component to React.createElement, which is most commonly the case when there is an error in imports or the system doing those imports under the hood.

**Comment by cannibal** [comment]
Thanks Tim

Do you have any suggestions as to how I can debug this - we are using an ejected create-react-app (was based on react-15)?

**Comment by arashmilani** [comment]
Try cleaning your package manager cache and remove the `node_modules` directory.
if you are using yarn run `yarn cache clean`. Then install the packages normally, it should fix the issue.
