### ISSUE TITLE
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

### ISSUE THREAD

**Issue by oOBobbyOo** [ReactTraining/react-router#6088]
![image](https://user-images.githubusercontent.com/12425983/38729586-0cf1f6d2-3f46-11e8-8133-34e065256110.png)

![image](https://user-images.githubusercontent.com/12425983/38729513-cbb7f14e-3f45-11e8-8a28-250411617d2d.png)

**Comment by timdorr** [comment]
Check that you have the right version of react-router-redux installed.
