### ISSUE TITLE
[Safari] - history goBack not working as expected

### ISSUE THREAD

**Issue by vTrip** [ReactTraining/react-router#6089]
`"react-router": "^4.1.2", "react-router-dom": "^4.1.2"`

OSX Safari v11.0.2
iOS 11.3

When navigating to a page via `<Link to="/foo">` and then using `history.goBack()`, app remains
on the same page. Only until 2 or more invocations of `history.goBack()` via some interaction (button) does the page actually go back.

Worth noting also, replacing `goBack` with `go(-1)` does not solve the problem either.

This has been isolated to Safari only. Not able to reproduce on Chrome or Firefox.

Using the Safari browser back button gives the exact same behaviour.

Click and holding the browser back button to reveal the history shows extra pages on the browser history stack.

**Comment by timdorr** [comment]
First, you are using an outdated version of the library. Make sure you're up to date.

Secondly, you're looking at the wrong library. Any issue like this would be from the history library: https://github.com/ReactTraining/history
