### ISSUE TITLE
Why is changing route refreshing the browser?

### ISSUE THREAD

**Issue by sabbiu** [ReactTraining/react-router#6096]
Clicking the `Link` to change the routes and navigating back and forward is Okay!

But, when I follow these steps, all the bundles and files are reloaded.

1. I am in `/routeA` 
2. Now, I manually change the route in the browser adress bar to `/routeB`
3. Browser reloads everything i.e, all the bundle.js files (this is expected behavior)
4. Now, when I press `<-` (back) button in browser i.e, from `/routeB` to `/routeA`, it again reloads everything (all the bundle files). Can't it use the already loaded `bundle.js` file to manipulate? 

Could you give me some insight in this?

**Comment by timdorr** [comment]
You did a navigation outside of the DOM history. It can't go back to other pages, even on the same origin, for a number of reasons. That's just how browsers work.
