### ISSUE TITLE
Can't route to another page

### ISSUE THREAD

**Issue by leyaannie** [ReactTraining/react-router#6099]
import React, { Component } from 'react';
import { connect } from 'react-redux';
import { login } from '../../redux/reducer';
import { LoginForm } from '../LoginForm/LoginForm';
import { BrowserRouter as Router,Switch,Route, Link } from "react-router-dom";

class HomePage extends React.Component {

previousLocation = this.props.location;

  componentWillUpdate(nextProps) {
    const { location } = this.props;
    // set previousLocation if props.location is not modal
    if (
      nextProps.history.action !== "POP" &&
      (!location.state || !location.state.modal)
    ) {
      this.previousLocation = this.props.location;
    }
  }

 render() {
 const { location } = this.props;
    const isModal = !!(
      location.state &&
      location.state.modal &&
      this.previousLocation !== location
    );
 return(
  <Router>
    <div>
    
      <Link to="/" label="Home" />
      <Link to="/about" label="About" />
      <Link to="../../LoginForm/LoginForm" label="Login" />
      <Link to="/gallery" label="Gallery" />
      <Link to="/contact" label="Contact" />

      <hr/>
      <Switch location={isModal ? this.previousLocation : location}>
      <Route exact path="/" component={Home} />
      <Route path="/about" component={About} />
      
      <Route path="../../LoginForm/LoginForm" component={Login}/>
      <Route path="/gallery" component={Gallery}/>
      <Route path="/contact" component={Contact}/>
       </Switch>
    </div>
 </Router>
  
  );
 }
}

const Home = () => (
  <div>
    <h2>Home</h2>
  </div>
);

const About = () => (
  <div>
    <h2>About</h2>
  </div>
);

const Login = () => (
  
    <LoginForm/>
  
);

const Gallery = () => (
  <div>
    <h2>Gallery</h2>
  </div>
);
const Contact = () => (
  <div>
    <h2>Contact Us</h2>
  </div>
);

export default HomePage;

This is my homepage.js... I want to route  to loginpage.. but that doesn't works.. What can I do now??

**Comment by pshrmn** [comment]
Your link and route are using a relative path (`../../LoginForm/LoginForm`). You need to use an absolute path, like `/login`.

**Comment by leyaannie** [comment]
but my loginform.js is in a folder named loginform.. Also I tried that way but no change..

**Comment by pshrmn** [comment]
`<Route path="/login">` and `<Link to="/login">`.

For any other usage questions you have, please use StackOverflow or Reactiflux. The issues section here is intended for bug reports.
