### ISSUE TITLE
it got errors when run npm start

### ISSUE THREAD

**Issue by zzzgit** [ReactTraining/react-router#6100]
## Version

the latest

## Test Case
npm run start

## Steps to reproduce
1. npm start
2.got the errors:
![image](https://user-images.githubusercontent.com/1060733/39025417-60e07fe2-4479-11e8-9a1e-87ba7d4b4cd4.png)

**Comment by pshrmn** [comment]
From the screenshot, I assume you are referring to the React Router documentation website. If you follow the repo's [contributing setup instructions](https://github.com/ReactTraining/react-router/blob/master/CONTRIBUTING.md#setup) everything should get setup correctly for you.
