### ISSUE TITLE
why not separate matchPath ?

### ISSUE THREAD

**Issue by DimaRGB** [ReactTraining/react-router#6101]
## Version
react-router@4

## Test Case
https://runkit.com/dimargb/5ada1f5123f4100012e9cc1b

## Question
what do you think about moving matchPath to separate package, or to react-router-config ?

https://github.com/ReactTraining/react-router/blob/master/packages/react-router/modules/matchPath.js

**Comment by timdorr** [comment]
We use it all over the place in react-router. It's not specific to react-router-config.
