### ISSUE TITLE
Using styled-components in production to wrap the router breaks it

### ISSUE THREAD

**Issue by gemma-ferreras** [ReactTraining/react-router#6103]
## Version 
4.2.0

Using electron 1.7.11

## Binaries:
 - Node: 8.9.4 - /usr/local/bin/node
 - Yarn: 1.3.2 - /usr/local/bin/yarn
 - npm: 5.6.0 - /usr/local/bin/npm
 - Watchman: 4.7.0 - /usr/local/bin/watchman
## npmPackages:
 - babel-plugin-styled-components: ^1.5.1 => 1.5.1 
 - styled-components: ^3.2.6 => 3.2.6 

## Steps to reproduce

When we build for production the router stops working. It works perfectly in development. If we change the UserPanelSectionRouting styled component to a regular div with inline styles the routing will work. 

```
class UserPanel extends PureComponent {

    constructor(props) {
        super(props);
    }

    render() {
        console.log('UserPanelSectionRouting', UserPanelSectionRouting)

        return(
            <MainSceneBackgroundContainer>
                <Menu />

                <UserPanelSectionRouting>
                    <Routes />
                </UserPanelSectionRouting>

            </MainSceneBackgroundContainer>
        )
    }
}


```

```

import styled                               from 'styled-components';

const UserPanelSectionRouting = styled.div`
    font-family: "Avenir Next";
    background-attachment: fixed;
    background-size: cover;
    flex: 1;
    position: relative;
    overflow-y: auto;
    margin-top: 80px;
    margin-bottom: 80px;
    margin-right: 44px;
`;

export default UserPanelSectionRouting;

```

```
const Routes = (props) => {
    let { match } = props;

    return(
        <Switch>
            <Redirect   exact   from={match.path}   to={`${match.url}/profile`} />

            <Route              path={`${match.path}/history`}          component={History}         />
            <Route              path={`${match.path}/not-authorized`}   component={NotAuthorized}   />
        </Switch>
    )
};

export default withRouter(Routes);


```

## Expected Behavior
It should work as in development.

## Actual Behavior
The routes are not rendering in production.

**Comment by timdorr** [comment]
This sounds like an issue with styled-components. My best guess is a blocked update: https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/guides/blocked-updates.md
