### ISSUE TITLE
HasRouter not encoding % as in browserUrl

### ISSUE THREAD

**Issue by snownoop** [ReactTraining/react-router#6111]
Hello. I have a problem with router that partially encoding symbols.

I am using:
`"react-router-dom": "^4.2.2",`

In my Component Code i defined route like this:
```javascript
import { HashRouter, Route } from 'react-router-dom';
<HashRouter>
    <div>
      <Route
        exact
        path="/approval/:objectName/:objectLabel/:objectItemName/:objectId"
        component={someComponent}
      />
    </div>
  </HashRouter>
```

Than i go next match:
```javascript
{
    isExact:true,
    params: {
        objectId:"something4",
        objectItemName:"kotik%*%3A",
        objectLabel:"something3",
        objectName:"something2",
    },
    path:"/approval/:objectName/:objectLabel/:objectItemName/:objectId",
    url:"/approval/something2/something3/kotik%*%3A/something4",
}
```

but in browser url i got kotik%25*%3A

Why **%** is not coming as encoded **%25** to match.params ?
That can break my code when i try to do `decodeUriComponent(match.params.objectItemName)` and objectItemName has **%**  symbol in it.

Thanks.

**Comment by timdorr** [comment]
ReactTraining/history#505
