### ISSUE TITLE
SyntaxError: export declarations may only appear at top level of a module

### ISSUE THREAD

**Issue by English3000** [ReactTraining/react-router#6115]
**Version:** "^4.2.0"

```js
require.register("react-router-native/main.js", function(exports, require, module) {
  require = __makeRelativeRequire(require, {}, "react-router-native");
  (function() {
    export * from 'react-router'

import BackButton from './BackButton'
import DeepLinking from './DeepLinking'
import Link from './Link'
import NativeRouter from './NativeRouter'

export {
  BackButton,
  BackButton as AndroidBackButton,
  DeepLinking,
  Link,
  NativeRouter
}
  })();
});
```

using Brunch.

The issue is (according to a Babel developer):

the package that you're using is published as ES6
and Babel is only running on your own local files

I had the same exact issue with `@absinthe/socket-relay`: https://github.com/babel/babel-brunch/issues/66

Is there a CommonJS version of this package?

**Comment by timdorr** [comment]
This isn't a react-router-native or React Router issue. It appears you're using Brunch, which doesn't support ES modules. I'm not sure why you're using that, as it's not the tooling to use with React Native. Either that or you shouldn't be using react-router-native.

**Comment by English3000** [comment]
I'm using `react-native-web`
