### ISSUE TITLE
Take the Router Challenge

### ISSUE THREAD

**Issue by grahammendick** [ReactTraining/react-router#6120]
[The Router Challenge](https://github.com/grahammendick/router-challenge) aims to be to Routers what TodoMVC is to MV* frameworks. It offers the same Music Catalog application built in React using different Routers. For it to be successful I need the help of Router writers like you. Will you [take the Router Challenge](https://github.com/grahammendick/router-challenge/blob/master/CONTRIBUTING.md) and implement the Music Catalog application using the React Router, please?

**Comment by timdorr** [comment]
If anyone wants to build this and submit a PR, I can look it over. I believe the idea would be to submit a PR to https://github.com/grahammendick/router-challenge, but we can track things here too. 

@grahammendick Do you want to move this to an issue on the router-challenge repo instead? We can link back to this issue so folks find their way over there.

**Comment by grahammendick** [comment]
Thanks @timdorr. I've created the issue as you suggested, https://github.com/grahammendick/router-challenge/issues/3

**Comment by mjackson** [comment]
Thanks, @grahammendick. Let's follow up in the router-challenge repo.

**Comment by grahammendick** [comment]
@mjackson Can we keep this open, please, because nobody will see the ticket on the router-challenge repo?
