### ISSUE TITLE
React-router causes components to be re-constructed after pushState redirects

### ISSUE THREAD

**Issue by helgiborg** [ReactTraining/react-router#6122]
## Version

package.json:

```
{
  "name": "basic_react_client",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "react": "^16.3.2",
    "react-dom": "^16.3.2",
    "react-router": "^4.2.0",
    "react-router-dom": "^4.2.2",
    "react-scripts": "1.1.4"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  }
}
```

## Test Case
```
import React from "react";
import { BrowserRouter as Router, Switch, Route, Link} from "react-router-dom";

const App = () => (
  <Router>
    <Switch>
      <Route exact path="/" component={Home} />
      <Route path="/area" component={AreaRouter} />
    </Switch>
  </Router>
);

const AreaRouter = (props) => {
  if (props.match.isExact)
    return <AreaList />

  return (
    <Route exact path={`${props.match.url}/:areaId`} component={Area} />
  );
};

class Home extends React.Component {
  constructor(props) {
    super(props);
    console.log("Home constructor");
  };

  render() {
    return (
      <div>
        <h2>Home</h2>
        <div><Link to="/area">AreaList</Link></div>
      </div>
    );
  }
};

const AreaList = () => (
  <div>
    <h2>Areas</h2>
    <ul>
      <ol><Link to="/area/rvk">Reykjavik</Link></ol>
      <ol><Link to="/area/aku">Akureyri</Link></ol>
    </ul>
    <div><Link to="/">Home</Link></div>
  </div>
);

const Area = ({match}) => (
    <h2>Area {`${match.params.areaId}`}</h2>
);

export default App;
```

## Steps to reproduce
1. Run
1. Click on "AreaList" to redirect to http://localhost:3000/area
1. Click on "Home" to redirect back to http://localhost:3000/

## Expected Behavior
The constructor for the Home component should just be run once.

## Actual Behavior
The constructor for the Home component runs multiple times.

**Comment by helgiborg** [comment]
Updated to 4.3.0-rc.3, but it still runs the constructor multiple times.

```
{
  "name": "basic_react_client",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "react": "^16.3.2",
    "react-dom": "^16.3.2",
    "react-router": "^4.3.0-rc.3",
    "react-router-dom": "^4.3.0-rc.3",
    "react-scripts": "1.1.4"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  }
}
```

**Comment by timdorr** [comment]
When you take that set of actions, you're unmounting the Home component for the AreaList and then mounting it again when going back to the root path. This is entirely expected behavior.

**Comment by helgiborg** [comment]
Got it. Thanks for your answer! I found the doc (https://reacttraining.com/react-router/web/api/Route/component). I overlooked this important info the first time.

Would it be possible to add an option to persist a component after it has been routed to the first time? That component would then be constructed a single time and it's state would be the same next time it was visited.

That option could look something like this:
`<Route exact persist path="/" component={Home} />`

**Comment by pshrmn** [comment]
I wouldn't recommend this. If you want state to persist, I would keep it higher up the chain or in a global store.

If you _really_ want to keep old components around, you can use the `<Route>`'s `children` render-invoked prop to render even when a the route's `path` doesn't match the current location. You would also have to remove the `<Switch>` for that to work. Again, I wouldn't recommend it, but you _could_ do that.
