### ISSUE TITLE
isActive Bug

### ISSUE THREAD

**Issue by adammenges** [ReactTraining/react-router#6123]
## Version

`"react-router": "^4.2.0"`

## Test Case + Steps to reproduce
Consider the following code:

``` javascript
const isAboutActive = (match, location) => {
	const ret = (location && (location.pathname === '/about' || location.pathname === '/about/'));
	console.log('ret1: ' + ret); // logs true
	console.log('ret2:', typeof ret); // logs boolean
	console.log('ret3:', ret === true); // logs true
	return ret
};
```

This function set as the `isActive` prop of a `<Link>` doesn't work. It's returning `true` in the cases were it should, along with some console logging to prove a point, but the link is never active on a page refresh.

However, if I change the code to always return true, so:

``` javascript
const isAboutActive = (match, location) => {
	const ret = (location && (location.pathname === '/about' || location.pathname === '/about/'));
	console.log('ret1: ' + ret); // logs true
	console.log('ret2:', typeof ret); // logs boolean
	console.log('ret3:', ret === true); // logs true
	return true
};
```

The link is always active. Even on a page refresh. It's blowing my mind.

## Expected Behavior

The return boolean of `isActive` is used to determine if a link should have an active class or not.

## Actual Behavior

The return boolean of `isActive` doesn't seem to matter, if it's returning a variable, otherwise it does? Something weird is going on here.

## Misc

Starting at the root and clicking around has the desired effect, but when refreshing the page the `isActive` doesn't appear to be working the way I would have thought. Everything else about the page displays correctly.

For what it's worth, it's a simple site created with `react-static` and the basic template.

**Comment by pshrmn** [comment]
`isActive` is a prop of the [`<NavLink>`](https://reacttraining.com/react-router/web/api/NavLink/isactive-func), not the `<Link>`.
