### ISSUE TITLE
[Feature Request] collect data from all current routes

### ISSUE THREAD

**Issue by vipcxj** [ReactTraining/react-router#6125]
Here is a situation. We get some dynamic route configs from network, and others are static. And we have some custom data in the route, for example label shown in the [navigation bar](https://ant.design/components/breadcrumb/). However, the route data is hard to collected. Because the children route data are lazy fetch. On the other hand, all these route config will be passed to the Route component, no matter how they are fetched. If we can get all these data from a hoc like `withRouter`, the world will be better.

**Comment by timdorr** [comment]
Since routes can come into existence dynamically, we don't have a central way to register them. I'd suggest building a wrapper HoC or render prop component that can "register" the component instance with a central store (perhaps Redux?). You can track them that way.

**Comment by vipcxj** [comment]
@timdorr But in v3, `withRouter` provide `routes` which hard to gotten in v4
