### ISSUE TITLE
history.createLocation is not a function

### ISSUE THREAD

**Issue by stern-shawn** [ReactTraining/react-router#6126]
## Version

react-router-dom 4.2.
history 4.7.2
react-router-redux 5.0.0-alpha.9

## Steps to reproduce

I have a protected route that generates a redirect when the user attempts to access an area of the app they don't have appropriate roles for like so (basically the same as the [example](https://reacttraining.com/react-router/web/example/auth-workflow) in the docs) :

```jsx
const RoleRoute = ({ component: RoleComponent, ...rest }) => {
     // ... logic for determining `hasRole`
      return (
        <Route
          {...rest}
          render={() =>
            hasRole
              ? <RoleComponent {...rest} />
              : <Redirect to={url} />
          }
        />
      );
    };
```

Higher up in the app, I have a history.js file as below
```js
import createHistory from 'history/createBrowserHistory';

export default createHistory();
```

It is connected to the app in this manner
```jsx
import { Provider } from 'react-redux';
import { ConnectedRouter } from 'react-router-redux';
import history from './history';
...
// Create redux store with history
const initialState = {};
const store = configureStore(initialState, history);

const render = () => {
  ReactDOM.render(
    <Provider store={store}>
      <ConnectedRouter history={history}>
        <App />
      </ConnectedRouter>
    </Provider>,
    document.getElementById('app')
  );
};
...
```

## Expected Behavior

This was working as of a few weeks ago. 

If a user navigates to an unauthorized role route, they simply get redirected back to the root url for that user sans role (`url` is pulled from `this.props.match.url` earlier in scope, don't worry, it's definitely defined).

## Actual Behavior

Lately I did another check of the functionality while checking to make sure everything is still working after updating to React 16.3.2. Noticed that the app crashes if I navigate directly to an unauthorized route with this error:

```
Uncaught TypeError: (0 , _history.createLocation) is not a function
    at Redirect.componentDidUpdate (Redirect.js:59)
    at commitLifeCycles (react-dom.development.js:9792)
    at commitAllLifeCycles (react-dom.development.js:11455)
    at HTMLUnknownElement.callCallback (react-dom.development.js:100)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:138)
    at invokeGuardedCallback (react-dom.development.js:187)
    at commitRoot (react-dom.development.js:11594)
    at completeRoot (react-dom.development.js:12502)
    at performWorkOnRoot (react-dom.development.js:12452)
    at performWork (react-dom.development.js:12370)
```

The error is occuring on this line...
```
Redirect.prototype.componentDidUpdate = function componentDidUpdate(prevProps) {
    var prevTo = (0, _history.createLocation)(prevProps.to);
```

and looking higher up in the Redirect.js code output from Webpack, it's correctly importing my history instance:
```
exports.__esModule = true;

var _react = __webpack_require__(/*! react */ "./node_modules/react/index.js");
...
var _history = __webpack_require__(/*! history */ "./app/history.js");
...
var Redirect = function (_React$Component) {
```

I've looked around and can't seem to find any good references on this bug in other issues or on the web at large.

**Comment by timdorr** [comment]
Something is wrong on this line:

```js
var _history = __webpack_require__(/*! history */ "./app/history.js");
```
It should be [importing from the history package](https://github.com/ReactTraining/react-router/blob/v4.2.2/packages/react-router/modules/Redirect.js#L5), not your history.js file/module. Something is up with your build setup in that case. This isn't a bug in the library.

**Comment by stern-shawn** [comment]
Much appreciated @timdorr, that put me on the right track.

For others that maybe run into this or similar:
This was a webpack config issue. If I changed the name of my file to something other than `history.js`, it started working as expected again, so it must be because it shares the same name as the node_modules/.../history.js from the `history` library.

In my config, my resolve statement was as such:
```js
resolve: {
  modules: [
    'app',
    'node_modules',
  ],
...
```

Swapping the order so that `node_modules` is resolved first fixed it:
```js
resolve: {
  modules: [
    'node_modules',
    'app',
  ],
...
```

This is actually similar to https://github.com/ReactTraining/react-router/issues/5503#issuecomment-336832799
