### ISSUE TITLE
withRouter triggers a warning about static getDerivedStateFromProps in React 16.3.2

### ISSUE THREAD

**Issue by tmcw** [ReactTraining/react-router#6130]
## Version

- react-router 4.2.0
- react-dom 16.3.2
- react 16.3.2

## Test Case

https://codesandbox.io/s/rmn760jv9m

## Steps to reproduce

- Create a stateful component that uses `static getDeriveStateFromProps`
- Wrap that component with `withRouter`

## Expected Behavior

The wrapped component should behave similarly to the unwrapped component, and not produce any additional errors.

## Actual Behavior

The wrapped component generates the following warning:

> Warning: withRouter(BaseComponent): Stateless functional components do not support getDerivedStateFromProps.

**Comment by pshrmn** [comment]
`withRouter` uses `hoist-non-react-statics` to hoist functions. RR `v4.2.0` was released before `gDSFP` existed, so the version of `h-n-r-s` it uses doesn't not know not to hoist `gDSFP`.

If you switch to the next release candidate (`v4.3.0-rc.3`), the error goes away.

**Comment by joeynimu** [comment]
Hi,

I was also getting the same error so I tried updating it with `npm i react-router-dom@v4.3.0-rc.3 --save` but the error persists. Looking in the `package.json` file I can see that it was updated to `"react-router-dom": "^4.3.0-rc.3"`
