### ISSUE TITLE
can React Router DOM be used from a CDN?

### ISSUE THREAD

**Issue by tsiq-swyx** [ReactTraining/react-router#6134]
when trying React Router DOM on codepen, I get this:

https://codepen.io/swyx/pen/OZxvBY

```
pen.js:11 Uncaught ReferenceError: ReactRouterDOM is not defined
    at VM588 pen.js:11
```

No matter what I try, I can't get this to work. I am even more shocked to find that the last mention of CDN in the issues here dates back to 0.x version of react router. is webpack/some sort of build system a hard dependency? very surprised since you also make unpkg...

Just asking in case I am missing something blindingly obvious here. thank you!

**Comment by timdorr** [comment]
You're referencing an extremely old version of React Router DOM in that codepen. I'd use at least version 4.2.0.

**Comment by tsiq-swyx** [comment]
surprised to hear that 4.0.0 is "extremely old". ok. thank you @timdorr that pushed me in the right direction. fixed.
