### ISSUE TITLE
Link and NavLink also push location to location stack when the current location is already the linked location

### ISSUE THREAD

**Issue by vince1995** [ReactTraining/react-router#6137]
## Version

4.2.2

## Steps to reproduce

Be on your website with something like a navigation bar. Click on a link which refers to the location where you're staying.

## Expected Behavior

It shouldn't push a new location to the location stack.

## Actual Behavior

It pushes a new location to the location stack.

**Comment by timdorr** [comment]
ReactTraining/history#470
