### ISSUE TITLE
Link bug - Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by jtheberge** [ReactTraining/react-router#6139]
I'm getting the error below after updating to the latest packages, and I now get this error when changing links with the Link element.
![linkerror](https://user-images.githubusercontent.com/13157499/39803832-221c4112-5327-11e8-952c-f5d3d494a60b.png)
## Steps to reproduce
Implement Link component with latest packages and click on link

## Expected Behavior
No console errors

## Actual Behavior
Error above

My apologies about the bug report being so vague, but I'm not exactly sure how to trace this error.

**Comment by timdorr** [comment]
Can you provide a reproduction of this somewhere? Codesandbox.io is best, since you can show the original code. 

It would seem like a build tooling issue, but there aren't enough specifics to go on.

**Comment by jtheberge** [comment]
Looks like it was caused by calling "this" on a newly static function I made due to linting recommendations, and it went unnoticed until now. Thank you for your help!
