### ISSUE TITLE
i keep getting this error --You should not use <Link> outside a <Router> 

### ISSUE THREAD

**Issue by rosselpha** [ReactTraining/react-router#6140]
## Version
"react-router-dom": "^4.2.2"

## Test Case
https://codesandbox.io/s/7zwjlm2j3q

**Comment by pshrmn** [comment]
The non-router components from React Router rely on being descendants of a router component (`<BrowserRouter>`, `<MemoryRouter>`, `<Router>`, etc.). That error means that you are trying to render a `<Link>` component from React Router, but that it doesn't have an ancestor router component.

```jsx
// no ancestor router, so this won't work
ReactDOM.render((
  <Link to="/">Home</Link>
), holder);

// ancestor router, so this will work
ReactDOM.render((
  <BrowserRouter>
    <Link to="/">Home</Link>
  </BrowserRouter>
), holder);
```
