### ISSUE TITLE
withRouter docs are using wrong import

### ISSUE THREAD

**Issue by deadcoder0904** [ReactTraining/react-router#6141]
I haven't used React Router in a while (I mean I used v1 or v2) but in the docs its importing from `react-router` & not `react-router-dom`.

Some places its importing from `react-router` & some places its importing from `react-router-dom`.

[Here](https://reacttraining.com/react-router/web/api/withRouter) `withRouter` is imported from `react-router` & [here](https://reacttraining.com/react-router/web/example/auth-workflow) `withRouter` is imported from `react-router-dom`.

Another questions is for web, do we need `react-router` at all or `react-router-dom` will work for everything❓

**Comment by timdorr** [comment]
react-router-dom re-exports everything from react-router, so you can use either. It's pointing to the exact same code.
