### ISSUE TITLE
Layout is not rendering while refresh page

### ISSUE THREAD

**Issue by vicky-blr** [ReactTraining/react-router#6142]
I've recently started with react-router and stuck with one issue. I've below router code and it works perfectly. Layout is just a top navigation bar. When I'm at <url>/about, it renders about page with top header. But as soon as I refresh layout disappears, only about component renders. Is there a way to retain layout by following some other approach? I am using React-router-dom v4.
```
BrowserRouter >
      <Switch>
        <Layout >
          <Route exact path="/" component={App} />
          <Route exact path="/about" component={About} />
        </Layout>
      </Switch>
    </BrowserRouter>
```

**Comment by timdorr** [comment]
You can't out multiple levels of components inside a Switch. The routes must be the first level children.

**Comment by vicky-blr** [comment]
Do you mean like below:

BrowserRouter >
  <Layout >
      <Switch>
          <Route exact path="/" component={App} />
          <Route exact path="/about" component={About} />
      </Switch>
  </Layout>
    </BrowserRouter>
