### ISSUE TITLE
@types/react-router-redux support Redux v4

### ISSUE THREAD

**Issue by SangKa** [ReactTraining/react-router#6143]
## Version

**v4**

## Expected Behavior
`@types/react-router-redux` support Redux v4.

## Actual Behavior
Now in the strict mode of TypeScript, if use the Redux v4, the types doesn't match and fail to compile.
The reason is that the newest version of `@types/react-router-redux` just depend on Redux 3.7.

```ts
export interface State {
  router: RouterState;
}

export const rootReducer: Reducer<State> = combineReducers<State>({
  router: routerReducer,
});
```

**Comment by timdorr** [comment]
We don't maintain those typings.
