### ISSUE TITLE
react withRouter create a new object for match everytime when mapStateToProps is called

### ISSUE THREAD

**Issue by kennyma603** [ReactTraining/react-router#6144]
## Version

i am using: "react-redux": "5.0.7", "react-router": "4.2.0", "react-router-dom": "4.2.2"

## Test Case
so I have a component like this,

shouldComponentUpdate = (nextProps) => {
    // shallow compare each prop and see which one is changed
    console.log(nextProps.history === this.props.history) // true, good
    console.log(nextProps.location === this.props.location) // true, good
    console.log(nextProps.match === this.props.match) // false, what? althought the value inside match is the same? why match is a new object/reference every time?
}

const mapStateToProps = (state, ownProps) => {
  nothing special here, just merge state and ownProps. (Router location/match/history is in ownProps, withRouter inject them in i think)
  at the end of this function i just return the merge of {state, ownProps}
  same issue exists even without my own mapStateToProps
}

export default withRouter(connect(mapStateToProps, mapDispatchToProps)(MyComponent))

## Expected Behavior
'match' from router should be same every time mapStateToProps() or shouldComponentUpdate() is called.

## Actual Behavior
'match' is different very time, looks like a new match object is created every time, even the data inside match is the same.

every time there is a state change, mapStateToProps is called. withRouter inject location/match/history is into ownProps. But for some reason 'match' is a new object every time when mapStateToProps is called, and thus it causes unnessarry re-rendering.

**Comment by timdorr** [comment]
Yes, this is created fresh each time. If you need equality checks, check `location` instead.

**Comment by kennyma603** [comment]
@timdorr , please answer my question above. it think the ticket status is closed so no one else would look into this issue? Thanks!

**Comment by kennyma603** [comment]
@timdorr I already posted the same question on https://stackoverflow.com/questions/50259081/react-withrouter-create-a-new-object-for-match-everytime-when-mapstatetoprops-is 

but no one answered, strange that no one has this issue before.

anyway, thanks!
