### ISSUE TITLE
react-rotuer 4 - NavLink does not re-render the components

### ISSUE THREAD

**Issue by trogne** [ReactTraining/react-router#6147]
Maybe it's not a bug and I'm missing something, but I don't know where else to look.

I have opened this question : 
https://stackoverflow.com/questions/50299398/react-router-v4-navlink-not-rerendering-components

The problem is that, with react-router 4, clicking on a NavLink link is not causing a rerendering of components.
The same app works pefectly with react-router 2 and Link.

And also, this tutorial have the exact same problem : 
https://github.com/reactjs/redux/blob/master/docs/advanced/UsageWithReactRouter.md

Clicking on the NavLink is not updating the todos list.

The problem is exactly here, on the VisibleTodoList component  : 

```
const mapStateToProps = (state, ownProps) => {
  console.log(ownProps.filter);
  return {
    todos: getVisibleTodos(
        state.todos,
        ownProps.filter
    ),
  };
};
```

With react-router v4, after clicking a NavLink, I do not get the console.log.

With react-router v2 and Link, I get the console.log for every NavLink click.

**Comment by timdorr** [comment]
See this guide: https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/guides/blocked-updates.md

**Comment by trogne** [comment]
I already tried "withRouter" on the App component, still not working.

**Comment by trogne** [comment]
This is what I use : Footer.js : 
```
const Footer = () => (
  <p>
    Show:
    {" "}
    <FilterLink filter="all">
      All
    </FilterLink>
    {", "}
    <FilterLink filter="active">
      Active
    </FilterLink>
    {", "}
    <FilterLink filter="completed">
      Completed
    </FilterLink>
  </p>
);
```

```
const FilterLink = ({ filter, children }) => {
    return (
        <NavLink
            exact
            to={filter === "all" ? "/" : `/${filter}`}
            activeStyle={{ textDecoration: "none", color: "red" }}
        >
            {children}
        </NavLink>
    );
};
```

VisibleTodoLists.js : 

```
const mapStateToProps = (state, ownProps) => {
  console.log(ownProps.filter);
  return {
    todos: getVisibleTodos(
        state.todos,
        ownProps.filter
    ),
  };
};
const mapDispatchToProps = (dispatch) => ({
    onTodoClick(id) {
        dispatch(toggleTodo(id))
    },
});

const VisibleTodoList = connect(
  mapStateToProps,
  mapDispatchToProps
)(TodoList);
```

And App.js, with "withRouter" : 

```
let App = ({ match: { params } }) => {
  return (
    <div>
      <AddTodo />
      <VisibleTodoList filter={params.filter || 'all'} />
      <Footer />
    </div>
  )
}
    
App = withRouter(App); // or withRouter(connect()(App));
export default App;
```

**Comment by trogne** [comment]
Project is here so you can have a look : https://github.com/trogne/rr4_navlink

**Comment by trogne** [comment]
If finally works now.  It was not a matter of "blocked updates", as in https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/guides/blocked-updates.md 

As you can see in the updated repo,  the Root component is now simply a
Route,  and index.js wraps the route with the Provider and the Router.

**Comment by trogne** [comment]
I can make it work without a separate Root component,   but I think it's not very efficient to pass the store twice like that in index.js : 

```

const Root = () => (
<Route path='/:filter?' component={App} />
);
export default class TopApp extends Component {
render() {
return (
<Provider store={store}>
<Router>
<Root store={store} />
</Router>
</Provider>
)
};
```
