### ISSUE TITLE
react-router v4 docs need better introduction, structure, and more standard and simple examples

### ISSUE THREAD

**Issue by ttaranov** [ReactTraining/react-router#6151]
I was looking at v4 docs - it seems like docs are packed full of good documentation of some kind, but it seems like it's poorly organized or uses a wrong format (without providing context or apparently assuming that a user is already knowledgeable about react router 4 api). 

Perhaps docs need a basic introduction section, similar to https://github.com/ReactTraining/react-router/blob/v3/docs/Introduction.md - that would take a user from having several react containers/pages linked into a web site?

/ - > Index
/inbox -> Inbox
/about -> About

Perhaps a basic Introduction section with more description, reference to json based configuration and other more standard and basic ways of building web applications/sites would be a better start than what is currently under https://reacttraining.com/react-router/web/guides/philosophy.

**Comment by timdorr** [comment]
A PR is the best way to change things. Just complaining about docs doesn't really do anything.

**Comment by timdorr** [comment]
Sorry, I was being short. I haven't yet had my coffee.

Regardless, issues aren't very actionable when it comes to documentation. A PR is the best form for getting things done because it gives us actual content to discuss. There is no perfect solution, but something is better than nothing.

**Comment by brycepj** [comment]
Just wanted to add that I had a similar experience to OP today. The docs look really slick, but really don't contain enough detail to be helpful. I also think OP goes quite a bit further than complaining, and gives maintainers some good ideas of where they could fill gaps. 

IMHO the onus of improving the docs rests on people who are intimately familiar with and built the actual technology (maintainers), not people trying to learn about how the technology works. 

Closing an issue and requiring a PR communicates that either you don't actually agree with OP that the docs need significant improvement or you just don't care enough to carry on a conversation about it.
