### ISSUE TITLE
Async mounting or walking the React tree will cause the LOCATION_CHANGE action to be dispatched twice

### ISSUE THREAD

**Issue by daviddt** [ReactTraining/react-router#6152]
## Version

**v5.0.0-alpha.6**

## Steps to reproduce

Use a library like:

- React async boostrapper https://github.com/ctrlplusb/react-async-bootstrapper
- React tree walker https://github.com/ctrlplusb/react-tree-walker
- React async component https://github.com/ctrlplusb/react-async-component

## Expected Behavior

When hydrating the application after walking the react tree, the **LOCATION_CHANGE** action should only be dispatched once.

## Actual Behavior

Libraries like the above make it possible to execute async actions before hydrating the application. This can be useful for async rendering of components, resolving data and other use cases. Libraries like this will invoke **componentWillMount** ( and componentWillUnmount ),  but not actually mount the component. The **ConnectedRouter** currently dispatched the action **LOCATION_CHANGE** on **componentWillMount**. 

## Suggested solution

Move the dispatch of **LOCATION_CHANGE** in **ConnectedRouter** from  **componentWillMount** to **componentDidMount**

**Comment by timdorr** [comment]
This isn't a use case we need to support. cWM is deprecated anyways, so it will change for that anyways.
