### ISSUE TITLE
<Redirect>  refresh issues

### ISSUE THREAD

**Issue by shivasai09** [ReactTraining/react-router#6164]
so i have something like this in my rederMethod
```

render() {
    if (this.state.toDashboard === true) {
      return <Redirect to={{
  pathname: '/gotosomepage',
  search: '?utm=your+face',
  obj: { referrer: "my state"}
}}/>
    }
```

so when i  change or set my state object (toDashboard) to `true ` it is successfully redirecting my page, and i am able to access my `obj` thourgh ` this.props.location.obj` but the problem is when i refresh my page the `obj`  is gone. is it a default behaviour of the react-router, if not this is a bug ..

**Comment by timdorr** [comment]
You can't set arbitrary properties on the location object. You either need to use state or the search property.

**Comment by shivasai09** [comment]
@timdorr  is it react-router default behavior, i mean why we have to use  only `state `and `search `property..
can i get a good valid reason for why not to use arbitrary properties

**Comment by pshrmn** [comment]
@shivasai09 A `location` object reflects the current location and mirrors the properties of `window.location` ([Location API](https://developer.mozilla.org/en-US/docs/Web/API/Location)) that are useful for a single-page application.

`location.state` isn't actually a location property; it is the current `history.state` (from the [History API](https://developer.mozilla.org/en-US/docs/Web/API/History_API)), but it is merged onto the `location` for convenience.
