### ISSUE TITLE
Allow period, full stop, dot within urls

### ISSUE THREAD

**Issue by TashaRolland92** [ReactTraining/react-router#6166]
## Version

react-router: Version 2.3.0
types/react-router: Version 4.0.12

## Steps to reproduce
Adding the below code to my routes.tsx file
`<Redirect exact={false} from='/original-page.aspx' to='/original-page' />
`
## Expected Behavior
Page should simply redirect

## Actual Behavior
React breaks behaviour when it find the period within the URL

**Comment by mjackson** [comment]
Thanks for the bug report, @TashaRolland92. We no longer support version 2 because it is several years old at this point. Please update to a more recent version and we'll be able to help you out :)

**Comment by TashaRolland92** [comment]
Ok @mjackson thank you,  I will do - fingers crossed! xD
