### ISSUE TITLE
NavLink maintains isActive after nagivation

### ISSUE THREAD

**Issue by pspeter3** [ReactTraining/react-router#6167]
## Version

`react-router-dom@4.2.2`

## Test Case
https://codesandbox.io/s/01y77yzkwv

## Steps to reproduce
Create NavLink with activeStyle or className

## Expected Behavior
isActive for initial route is removed after navigation

## Actual Behavior
isActive for initial route is maintained after navigation

**Comment by timdorr** [comment]
You need to use the `exact` prop.

**Comment by pspeter3** [comment]
Thanks!
