### ISSUE TITLE
Can't find resolve 'react' after installing react-router-dom

### ISSUE THREAD

**Issue by ankurcs** [ReactTraining/react-router#6176]
I have installed react-router-dom v 4.2.2 and just imported BrowserRouter in index.js.

I am getting the following error in my screen.
./node_modules/react-router-dom/es/BrowserRouter.js

Module not found: Can't resolve 'react' in '/Users/ankur.gupta/Desktop/repo-name/node_modules/react-router-dom/es'

## Version
react-router-dom 4.2.2

**Comment by timdorr** [comment]
This isn't a bug with this library. Check your bundler and npm setup.
