### ISSUE TITLE
React router should export PropTypes

### ISSUE THREAD

**Issue by erfanio** [ReactTraining/react-router#6177]
A lot of us work in lint enforced environments, on of these lints is usually good `propTypes`.
All linters aside prop types are great documentation and also help you figure out problems.

Right now the only option to have prop types for `match` or `history` is to use `PropTypes.object`. This basically leaves a big hole in the security prop types provides. Also `PropTypes.object`, `PropTypes.any` and others are usually frown upon in big code bases.

MobX solved this by [exporting a set of prop types](https://github.com/mobxjs/mobx-react#proptypes).

Something similar would be very nice for react router.
```js
import { PropTypes as RouterPropTypes } from 'react-router';

class RandomComponent extends React.Component {
  static propTypes = {
    history: RouterPropTypes.history,
    match: RouterPropTypes.match,
    location: RouterPropTypes.location,
  }
  
  .
  .
  .

```

**Comment by bitcloud** [comment]
I'm actually undecided on this approach with a tendency to not like it. 

For example if there is a major version upgrade that changes the API of any of those parameters, you won't catch that, because the propType validators silently update as well. Otherwise you know that you need to update your code and where because of the warnings.

And when you import the propTypes you and up always requiring all parameters, not only those you really need for your component to work.

**Comment by erfanio** [comment]
@bitcloud I understand your perspective.
In a perfect world everyone put the exact tue things they need in prop types.
But in reality a lot of people just use `PropTypes.object` to describe these objects which is not very useful for someone looking at prop types trying to figure out what a component needs.

**Comment by bitcloud** [comment]
Do you think those people who use `PropTypes.object` would then start using the exported propType? ;-)
I think if the really start worrying about using better PropTypes then `PropTypes.object` they should go the whole 9 yards and put the exact things they need in prop types.
Putting that in place would more or less support or even encourage not doing it right :)

**Comment by timdorr** [comment]
We don't maintain strong PropTypes internally, so there's not really anything to export. We don't pass anything around, and [we rely on `PropTypes.object` a lot](https://github.com/ReactTraining/react-router/blob/master/packages/react-router/modules/Route.js#L22). We also tend to not put a lot of value in PTs. A strongly typed system like TypeScript or Flow is probably going to serve you better.
