### ISSUE TITLE
Support redux 4.0.0

### ISSUE THREAD

**Issue by makesitgo** [ReactTraining/react-router#6181]
### The Problem

A pain-point arises when trying to use Typescript to write an app with React, Redux, and react-router-redux in their latest versions.  Redux recently released 4.0.0 version and with it a new `Reducer` declaration.  This new type is incompatible with how `routerReducer` is currently defined.

In Redux 3.x, the Reducer's type declaration was:

```js
export type Reducer<S> = (state: S, action: AnyAction) => S;
```

However, in Redux 4.x, the Reducer's type declaration is:

```js
export type Reducer<S = any, A extends Action = AnyAction> = (state: S | undefined, action: A) => S;
```

Unfortunately, react-router-redux is still using Redux 3.6.0 and the type declaration for `routerReducer` is:

```js
export const routerReducer: Reducer<RouterState>;
```

If one tries to use this library alongside Redux 4.x, the Typescript compiler will complain about the missing `Action` type arg.

### Proposed Solution

Bring Redux 4.x into react-router-redux's codebase, and then update the `routerReducer`'s type declaration to be:

```js
export const routerReducer: Reducer<RouterState, AnyAction>;
```

### Current Workarounds

Live in the Redux 3.x world. As my current app requires redux-thunk and typescript-fsa-redux-thunk as dependencies, those need to remain pinned at versions 2.2.0 and 5.0.0-alpha.9, respectively.  With the above changes, these dependencies would be able to reach their latest and greatest (at the time of this writing, >= 2.3.0 and >= 5.0.0-alpha.11, respectively).

### Next Steps

Apologies in advance if this is not the proper forum to bring up a Typescript-related issue with the react-router-redux package.  Is migrating to Redux 4.x on the roadmap for this library?

**Comment by timdorr** [comment]
We don't maintain the TypeScript typings for react-router-redux. I'd bring this up on DefinitelyTyped, which is where I think they're coming from.

**Comment by makesitgo** [comment]
Fair, I was just thinking that this repo would need to support Redux 4.x before those typings could ever be written.
