### ISSUE TITLE
Cannot create default exact Route component inside a Switch

### ISSUE THREAD

**Issue by charlax** [ReactTraining/react-router#6187]
## Version

4.2.0

## Test Case

https://codesandbox.io/s/kxk110lqy3

## Steps to reproduce

1. Define an `ExactRoute` component:`const ExactRoute = ({exact, ...rest}) => <Route exact={true} {...rest} />`
2. Use a bunch of `Route` inside a `Switch` (this bug does not apply when no `Switch` are used)
3. Among those routes, define one using `ExactRoute`, for instance: `<ExactRoute path="/about" component={About} />`

## Expected Behavior

I am trying to circumvent the fact that `exact` defaults to false (see #4958) by creating my own `ExactRoute` component. I would expect my `ExactRoute` component to match only if it is an exact match.

## Actual Behavior

If you go to `/about/me` (a non-exact match), the `About` component will render

Alternatively, the matching will be exact only if `exact` is an argument of `ExactRoute`: `<ExactRoute exact path="/about" component={About} />`

**Comment by timdorr** [comment]
[`Switch` reads the props of its children directly](https://github.com/ReactTraining/react-router/blob/master/packages/react-router/modules/Switch.js#L49-L55). So, a dirty little secret is that you can actually put _any_ component under it and it will work as long as the props are present.

So, you can't wrap a Route component and pass it to a Switch, unfortunately.

**Comment by charlax** [comment]
Should this be clarified in the docs?

**Comment by nfantone** [comment]
@timdorr 

> So, you can't wrap a Route component and pass it to a Switch, unfortunately.

May I ask again why not? We are doing this in pretty much every project we have and seems to be working fine for us.

```jsx
<Switch>
      <Route
        exact
        path="/login"
        render={props =>
          isAuthenticated() ? (
            <Redirect to={{ pathname: '/myfiles', from: props.location }} />
          ) : (
            <LoginPage {...props} />
          )
        }
      />
      <Route exact path="/logout" component={LogoutPage} />
      <PrivateRoute exact path="/myfiles" component={MyWCABFilesPage} />
      <PrivateRoute exact path="/search" component={SearchPage} />
</Switch>
```

The above behaves just like you'd expect. `PrivateRoute` is a `Route` wrapper that redirects users to `/login` if they are not authenticated.

**Comment by timdorr** [comment]
Because you are using the same props as a vanilla Route. The OP is trying to avoid using the `exact` prop, but Switch reads that directly, so it wouldn't be available to read.

**Comment by nfantone** [comment]
I see now, thanks for the clarification. But, IMO, your original answer might mislead some people and seems to imply something different.

**Comment by timdorr** [comment]
I added a small clarification there.

**Comment by nfantone** [comment]
@timdorr Many thanks 😄
