### ISSUE TITLE
New version 5.x but not maintained anymore??

### ISSUE THREAD

**Issue by rickerd** [ReactTraining/react-router#6188]
This react-redux-router is fairly new but now already deprecated and not maintained anymore?
The option given is a complete different approach.

Wwhhhyyyy....

**Comment by haakenlid** [comment]
There another project that links here: 
https://github.com/reactjs/react-router-redux

> 
> We're moving!
> react-router-redux is going to live alongside react-router. In fact, it's already set up over there. Go take a look!
> 
> This repo is for react-router-redux 4.x, which is only compatible with react-router 2.x and 3.x
> 
> The next version of react-router-redux will be 5.0.0 and will be compatible with react-router 4.x. It is currently being actively developed over there. Feel free to help out!

Except when you go to https://github.com/ReactTraining/react-router/tree/master/packages/react-router-redux we're told to go to some other seemingly unrelated project? What's going on?

**Comment by pshrmn** [comment]
There are a few reasons:

1. It probably isn't necessary. For most projects, you don't actually need to store routing information in your Redux store. This will be even more true for people who add it to their store for deep updates. `v4.4` will add the new context API, so you'll get deep updates for "free".
2. It isn't a priority. It has been in alpha for over a year with no real changes and no one coming in to try and champion working on the package.
3. There are alternative projects that are interested in this problem, such as the one linked from the `react-router-redux` README, so it makes more sense to steer people in their direction.
