### ISSUE TITLE
Redirect not passing params when using template literals

### ISSUE THREAD

**Issue by worc** [ReactTraining/react-router#6189]
I have a redirect inside of a switch that's not passing params from `from` to `to`. Both `from` and `to` are using template literals. The `from` side seems to get triggered correctly. But the `to` expression is redirects to a URL with *:param* instead of the **value** of the param.

The code is pretty straightforward:

`<Redirect from={`${path}/:param`} to={`${path}/:param/some-deeper-route`} />`

This looks like [an issue that's cropped up before](https://stackoverflow.com/questions/43399740/react-router-redirect-drops-param) that's apparently marked resolved. But I'm looking at `react-router-dom@4.2.2` with the same bug. I'm going to look into the workarounds on that stackoverflow question, but this does seem like some sort of issue.

**Comment by pshrmn** [comment]
@worc `v4.3` was released today, which I believe has the fix. Please try using that.
