### ISSUE TITLE
Not able to fetch react router@4.3.1

### ISSUE THREAD

**Issue by parabameya** [ReactTraining/react-router#6190]
I am trying to install react-router-dom@4.3.1 which has these dependencies

dependencies:
history: ^4.7.2
invariant: ^2.2.4
loose-envify: ^1.3.1
prop-types: ^15.6.1
react-router: ^4.3.1
warning: ^4.0.1

and when I try to do npm view react-router

npm view react-router

react-router@4.3.0 | MIT | deps: 6 | versions: 118
Declarative routing for React
https://github.com/ReactTraining/react-router#readme

keywords: react, router, route, routing, history, link

dist
.tarball https://maven.infra.dp-dev.jcpcloud2.net/repository/npm/react-router/-/react-router-4.3.0.tgz
.shasum: 23939cb228df17bd1a2403c55f35f46f0e47fa24
.integrity: sha512-wZsL9h/Jd/bECcdLLY9Icq+dYXiBhH9kutYK2nVog4Nd+n2GB2JaG023XnK+GAUlVg61kz41xteOBlCh5AVzEQ==
.unpackedSize: 185.2 kB

dependencies:
history: ^4.7.2
hoist-non-react-statics: ^2.5.0
invariant: ^2.2.4
loose-envify: ^1.3.1
path-to-regexp: ^1.7.0
prop-types: ^15.6.1

maintainers:
- mjackson <npm@mjackson.me>
- timdorr <timdorr@timdorr.com>

dist-tags:
latest: 4.3.0     previous: 3.2.1
next: 4.3.0-rc.3

published 11 hours ago by timdorr <timdorr@timdorr.com>

I am not able to find 4.3.1

all my builds are failing. Please help

**Comment by pshrmn** [comment]
Do you have some sort of cache layer going on? I see `4.3.1` as the latest for both `react-router` and `react-router-dom`.

```bash
XXX ~ $ npm dist-tag ls react-router
latest: 4.3.1
next: 4.4.0-alpha.0
previous: 3.2.1
XXX ~ $ npm dist-tag ls react-router-dom
latest: 4.3.1
next: 4.4.0-alpha.0
```

**Comment by timdorr** [comment]
Based on the tarball URL, it looks like they do. Closing, as it's not a library issue.
