### ISSUE TITLE
[feature request] Redirect render a hidden a tag to support SEO.

### ISSUE THREAD

**Issue by xialvjun** [ReactTraining/react-router#6191]
Can I do it?
```js
const app = <StaticRouter context={context}>XXXXXXX</StaticRouter>;
const stream = renderToNodeStream(app);
stream.pipe(res);
stream.on('end', () => {
  if (context.url) { res.redirect(context.url) }
});
```

No, I can not.

**HTTP doesn't support Redirect in the middle of body.**

But I want to use `renderToNodeStream` to shorted uses' waiting time. I want SSR for SEO too.

But many crawlers of the search engine don't support js. They don't know to redirect to another url without HTTP status 302. 

So, why not give them an `a` tag?

Then:
- Browser receives node_stream, and hydrate, and found `<Redirect to={xxxx}/>`,  then redirect.
- Crawler receives node_stream, found an `a` tag, crawl it.

**Or leave what to render to user**: `<Redirect to={xxx}>{url => <a style={{display:'none'}} href={url} />}</Redirect>`

**Comment by timdorr** [comment]
Just render the `a` directly if you're on the server.

**Comment by xialvjun** [comment]
@timdorr How can I render the `a`?  I'm using `renderToNodeStream `

**Comment by timdorr** [comment]
Set something global that defines if you're on the server:
```js
render() {
  return serverRendered ? <a href={url}/> : <Redirect to={url}/>
}
```

**Comment by xialvjun** [comment]
@timdorr You mean?

```jsx
<Switch>
  <Route xxxx />
  <Route xxxx />
  <Route xxxx />
  <Route render={props => is_server ? <a href="xxxx"/> : <Redirect to="xxxx" />} />
</Switch>
```

**Comment by timdorr** [comment]
Yes, that would work.
