### ISSUE TITLE
Extra attributes in SSR app after upgrade react-router-dom

### ISSUE THREAD

**Issue by Mati365** [ReactTraining/react-router#6193]
## Version

**react-router-dom 4.3.1**

## Steps to reproduce
`<NavLink  to={to} activeClassName='active_class'> {children}</NavLink>`

## Actual Behavior
Generates React hydrate error in server side rendered apps.

After upgrade react prints:
`Warning: Extra attributes from the server: class,aria-current`

**Comment by timdorr** [comment]
You must be passing into your StaticRouter or client router the wrong URL somehow. The match is computed at instantiation of the Router, so it would have the NavLink as active on both the server and client for a given URL. Hence, that URL must differ in some way.

**Comment by tomkelsey** [comment]
Hey @timdorr 

Just to say upgrading from 4.2.2 (?) to 4.3.1 introduced this error for me too.

It previously worked fine. So not sure if the older version was just more lax or if the newer version has introduced a bug?

**Comment by Mati365** [comment]
@timdorr I have checked my code before report Issue. URL passed to component is correct.

**Comment by timdorr** [comment]
Can you post a repo with a test case? I need some code to be able to diagnose.

**Comment by Mati365** [comment]
@timdorr At the moment i'm not able to send you repo because it is a part of closed source project.
@tomkelsey Can you provide code?

**Comment by timdorr** [comment]
Closing in favor of #6201
