### ISSUE TITLE
Feature request: Forward ref on NavLink to Link component

### ISSUE THREAD

**Issue by lcsrinaldi** [ReactTraining/react-router#6195]
## Description

Nowadays it's not possible to pass ref to `NavLink` because it's a functional component and that's ok. The thing is, I want to get a reference to the underlying `Link` component instance but there's no way, since React doesn't let me use the `ref` property and the `innerRef` points to the DOM element below `Link` (`a` tag).

## Possible solution

React has this `forwardRef` utility function which could be used in this stateless component to point the `ref` property to `Link`. See https://reactjs.org/docs/forwarding-refs.html

**Comment by timdorr** [comment]
That is a 16.3+ only feature, so we can't add it without breaking backwards compatibility for most versions of React. We still support 15+ for now.

**Comment by lcsrinaldi** [comment]
@timdorr any possibility for a linkRef property? I don't see how I could workaround this.

**Comment by timdorr** [comment]
You can write your own. It's only a Link wrapped with a Route: https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/modules/NavLink.js#L28-L50

**Comment by lcsrinaldi** [comment]
Well thought! Thanks :)
