### ISSUE TITLE
Feature Request: Update Switch to ignore HOCs

### ISSUE THREAD

**Issue by AlastairTaft** [ReactTraining/react-router#6200]
It would be nice if the `<Switch />` component ignored higher order components. That way I could structure my code like the below.

```js
<Switch>
  <Route path="/login" component={LoginWithQueryString} />
  <Route path="/authorizing" component={Authorizing} />
  <AuthorizedHOC>
      <Route path="/select-repository" component={RepositorySelect} />
      <Route path="/repo/:repository" component={RepositoryEditWithRepoName} />
  </AuthorizedHOC>
  <Redirect to="/login" />
</Switch>
```

Or perhaps there is a better pattern?

**Comment by timdorr** [comment]
Switch examines it's children directly, so that form wouldn't work. You'd have to put those within the Routes' render props.
