### ISSUE TITLE
Props of Route are not forwarded

### ISSUE THREAD

**Issue by raviteja83** [ReactTraining/react-router#6204]
## Version

**4.3.1**

## Test Case
https://codesandbox.io/s/ppnq16rpwx

## Steps to reproduce
I want to handle title passed as a prop to Route in the component that is rendered by route. 

## Expected Behavior
All the extra props should be passed down to the component that is rendered.

## Actual Behavior
Only match, location, history are passed to the component that is rendered.
https://github.com/ReactTraining/react-router/blob/master/packages/react-router/modules/Route.js#L116

**Comment by mjackson** [comment]
If you want to pass extra props, use the `render` prop:

```js
<Route path="/your/path" render={props => (
  <YourComponent {...props} yourOwn="prop" />
)}/>
```

**Comment by raviteja83** [comment]
@mjackson Is there any particular reason why the props are not passed to the component?
