### ISSUE TITLE
'react-router' does not contain an export named 'Link'

### ISSUE THREAD

**Issue by SashaSobol** [ReactTraining/react-router#6207]
Failed to compile
./src/components/UserListElement.js
102:24-28 'react-router' does not contain an export named 'Link'.
This error occurred during the build time and cannot be dismissed.

Help pls.

**Comment by SashaSobol** [comment]
CONSOLE ERROR! HELP PLS.

Uncaught TypeError: Cannot read property 'Component' of undefined
    at react-router.min.js:1
    at react-router.min.js:1
    at react-router.min.js:1
UserListElement.js:71 Uncaught Error: Cannot find module "./stylesheets/main.scss"
    at Object../src/index.js (UserListElement.js:71)
    at __webpack_require__ (bootstrap f66be1252f95a37cfb21:678)
    at fn (bootstrap f66be1252f95a37cfb21:88)
    at Object.0 (users.js:71)
    at __webpack_require__ (bootstrap f66be1252f95a37cfb21:678)
    at ./node_modules/ansi-regex/index.js.module.exports (bootstrap f66be1252f95a37cfb21:724)
    at bootstrap f66be1252f95a37cfb21:724
index.js:2178 ./src/components/UserListElement.js
102:24-28 'react-router' does not contain an export named 'Link'.
__stack_frame_overlay_proxy_console__ @ index.js:2178
index.js:2178 ./src/index.js
31:52-66 'react-router' does not contain an export named 'browserHistory'.
__stack_frame_overlay_proxy_console__ @ index.js:2178
index.js:2178 ./src/index.js
36:35-49 'react-router' does not contain an export named 'browserHistory'.
__stack_frame_overlay_proxy_console__ @ index.js:2178
index.js:2178 ./src/index.js
63:32-42 'react-router' does not contain an export named 'IndexRoute'.
__stack_frame_overlay_proxy_console__ @ index.js:2178
index.js:2178 ./src/index.js
Module not found: Can't resolve './stylesheets/main.scss' in 'C:\Users\Солнце\Desktop\merehead\src'
__stack_frame_overlay_proxy_console__ @ index.js:2178
index.js:2178 ./node_modules/react-router-bootstrap/lib/LinkContainer.js
Module not found: Can't resolve 'react-router-dom' in 'C:\Users\Солнце\Desktop\merehead\node_modules\react-router-bootstrap\lib'

**Comment by pshrmn** [comment]
If you are using React Router v2/3, make sure that you are installing the correct version.

For v4, the `<Link>` component comes from the `react-router-dom` package.
