### ISSUE TITLE
Feature Request: add title option to react Route component

### ISSUE THREAD

**Issue by ell33t** [ReactTraining/react-router#6208]
Hey there,

I think it would be neat if you could edit the title of the browser depending on which Route component you've got rendered, something like:

`<Route exact path='/home' component={Home} title='WebAppName - Home'/>`

You can already set the document.title inside react components, but it would be much neater/nicer if it could be done in the scope of the Switch and Route of 'react-router-dom'.

**Comment by timdorr** [comment]
Because you can have multiple Route matches anywhere in the tree, which one would win? This is also something that needs special handling for SSR. Its a rather complex thing left up to dedicated libraries like react-helmet.
