### ISSUE TITLE
Cannot read property 'getCurrentLocation' of undefined

### ISSUE THREAD

**Issue by ericmorand** [ReactTraining/react-router#6211]
I'm trying to setup a router using V3 and following the basic example of the documentation and I have the following error:

`Cannot read property 'getCurrentLocation' of undefined`

Here is my whole app:

```
import * as React from 'react';
import * as ReactDOM from 'react-dom';
import {Router, Route} from 'react-router';

class A extends React.Component {
    render() {
        return 'A';
    }
}

class B extends React.Component {
    render() {
        return 'B';
    }
}

ReactDOM.render(
    <Router>
        <Route path="/" component={A}>
            <Route path="callback" component={B}/>
        </Route>
    </Router>,
    document.getElementById('app')
);
```

Inspired from the route configuration doc:

https://github.com/ReactTraining/react-router/blob/v3/docs/guides/RouteConfiguration.md

**Comment by pshrmn** [comment]
The code in that guide is not complete. You need to pass [a `history` prop](https://github.com/ReactTraining/react-router/blob/v3/docs/guides/Histories.md) to the router.
