### ISSUE TITLE
link component jump bug

### ISSUE THREAD

**Issue by flasco** [ReactTraining/react-router#6215]
react-router in latest version.
see this pic

![image](https://user-images.githubusercontent.com/20221600/41636709-ae74e07a-7482-11e8-8051-4e16733444f9.png)

link component will replace my url, I can't jump to another url in my website.

codeSandBox url - https://codesandbox.io/s/j2kxx9yy3

maybe it's my problem, if you know how to achieve it, please tell me, thanks!

**Comment by timdorr** [comment]
Link isn't for external URLs. Just use an a tag.
