### ISSUE TITLE
Require a way to proxy the path in react router so it doesn't redirect the browser url

### ISSUE THREAD

**Issue by viveksanthosh** [ReactTraining/react-router#6218]
**Problem statement**: React router does not work with google cache.

**Explanation**: I have a server-rendered react site and it is viewed in google cache the page appears and disappears. After a lot of research, I found that this is due to react router now knowing what route it is in, and it just returns a blank HTML object in the dom.

I have found articles advising me to use. the onEnter interceptor and replace the pathname with the replace method.
```js
const projectCanonnicalAddr = "http://localhost",
cacheQueryParser = (query) => {
    let out = '';
    if (typeof query === 'string') {
        out = query.split(':').pop().replace(/^[^/]*/, '');
    }
    return out;
},
intercepPath = (next, replace) => {
    if (next.location.pathname === '/search'
        && next.location.query.q
        && next.location.query.q.indexOf('cache') === 0
        && next.location.query.q.indexOf(projectCanonnicalAddr) > -1) {
        replace(null, cacheQueryParser(decodeURIComponent(next.location.query.q)));
    }
};
```
But this solution causes a page redirect and I don't want that. 

**Suggestion**: Add a way to proxy the URL instead of just replacing it, maybe a third parameter in the onEnter/onLeave interceptors. This can change the value of next.location.path without forcing a redirect by the browser.

**Benefits**: 

1.  Can help resolve issues when there is a cache system like google cache involved.
2. Can be used for internal routing (in case of sensitive routes)

**Comment by bitcloud** [comment]
I think this would be a feature better located in the history module. The router gets its location from the browser history. So if you would implement a wrapper for the history and pass that to the router, it would be completely transparent for the router.

Perhaps it would be a feature for the history model to have some kind of an url parsing plugin for both ways, browser -> consumer (invoked link) or consumer -> browser (e.g. history.push)

**Comment by timdorr** [comment]
This is for React Router 3, which is only receiving bug fixes at this point, not new features.

Regardless, handling Google cache specifically, isn't an edge case we want to handle. You can handle this by crafting your own history instance with wrappers to handle the specifics of this URL structure.
