### ISSUE TITLE
react-router-config allow skipping Switch for child routes

### ISSUE THREAD

**Issue by jchip** [ReactTraining/react-router#6224]
Current react-router-config always use `<Switch>` on the routes to be matched.

Sometimes it is desirable to skip the `<Switch>`, especially for child routes.  As explained in the doc for `<Switch>`:

> This is by design, allowing us to compose <Route>s into our apps in many ways, like sidebars and breadcrumbs, bootstrap tabs, etc.

I think one approach is to add a `useSwitch` flag:

```js
const routes = [
  { component: Root,
    useSwitch: false,
    routes: [
      { path: '/',
        exact: true,
        component: Home
      },
      { path: '/child/:id',
        component: Child,
        routes: [
          { path: '/child/:id/grand-child',
            component: GrandChild
          }
        ]
      }
    ]
  }
]
```

- Then update the API `matchRoutes` to take another param `useSwitch` that defaults to `true`
- Add a new API `renderFlatRoutes` to render routes without `<Switch>` and update `renderRoutes` to use it internally.

I am happy to submit a PR if something similar is accepted.

Thanks.

**Comment by timdorr** [comment]
I'm not sure I understand the use case here. `matchRoutes` doesn't use a Switch in its implementation. 

I'm also not too keen on exposing an API tied to a particular implementation. `renderRoutes` could be changed to not use a Switch, so would this API still apply?

**Comment by timdorr** [comment]
I'm still not sure what the point of removing the Switch would be. It's just an implementation detail. matchRoutes does the same thing, just without any React code because of the context where it runs. 

If you don't want the Switch for some reason, just use matchRoutes.

**Comment by jchip** [comment]
Thanks for replying.  I will update if I get some sample to iron out the use case.
