### ISSUE TITLE
react-router-redux not triggering handleLocationChange from push action

### ISSUE THREAD

**Issue by dagda1** [ReactTraining/react-router#6225]
I am trying to get to the bottom as to why a push action is not getting triggered from a push action, I am using `react-router-redux@5.0.0-alpha.9` and I am doing the render on the server:
```
const store = configureStore({ router: { location: req.url } }, createMemoryHistory());

  const context: any = { store };

  store.dispatch(push(req.url));

  const app = (
    <Provider store={store}>
      <StaticRouter location={req.url} context={context}>
        <Application />
      </StaticRouter>
    </Provider>
  );
```

My client code looks like this:
```
import createHistory from 'history/createBrowserHistory';
import * as React from 'react';

export interface AppProps {
  store: Store<State>;
}

export class App extends React.Component<AppProps> {
  render() {
    const { store } = this.props;

    return (
      <>
        <Helmet>
          <title>PVG Online</title>
        </Helmet>
        <Provider store={store}>
          <ConnectedRouter history={createHistory()}>
            <Application />
          </ConnectedRouter>
        </Provider>
      </>
    );
  }
}
```

The same code works on a bundled browser only version.

What reason would there be for that to happen or can anyone give me any pointers as to why this would happen.

`handleLocationChange` but the middleware does the `history.push` but as the code never makes it to the reducer, a re-render does not happen.

**Comment by timdorr** [comment]
RRR is deprecated.

**Comment by dagda1** [comment]
OK but for anyone else with this problem I had 2 different history objects that was causing the problem.

I was passing a new instance into the router middleware and creating a new instance for the `ConnectedRouter`.

That is a real pity this is being deprecated, it is extremely useful and nice to isolate the side effect in an action.
