### ISSUE TITLE
how to make ambiguous-matches doesn't work?

### ISSUE THREAD

**Issue by alexxxcs1** [ReactTraining/react-router#6229]
In the react-router v3, I can do that like this : 

       <Route path='/Home' component={Home} /> 

       <Route component={NotFound}/> 

when url is '/Home/dd' ,it match NotFound ,but in V4 it was matched /Home,

so i config like this : 

       <Route exact  path='/Home' component={Home} /> 

       <Route component={NotFound}/> 

it work ,but went i set a childroute with /Home like this :  

<Switch>

          <Route path='/Home/firstchild' component={HomeChildFirst} /> 

</Switch>

father route is set exact true make  /Home/firstchild can't match

I think is ambiguous-matches make this situation

**Comment by timdorr** [comment]
You want to use a `<Switch>`.
