### ISSUE TITLE
Pass props to child of <Route />

### ISSUE THREAD

**Issue by RobertBroersma** [ReactTraining/react-router#6230]
Hi guys. I'm running into an issue with using `<Route children />`. 

I would like to use this, but don't like to pass children as a prop. I've tried passing the component as a child:
```js
<Route path={`${match.path}/test1`} >
  <Group>1</Group>
</Route>
```

But this way my component doesn't receive a `match` props, because of this line: https://github.com/ReactTraining/react-router/blob/d28d46dce08a5756a085f7e5eebb5169ea59e40b/packages/react-router/modules/Route.js#L124-L125

What would be the implication of replacing L125 with `React.cloneElement(children, props);` ? 

Perhaps I'm missing something, but if not, I'd happy to create a PR!

**Comment by timdorr** [comment]
If this.props.children was an array/set of elements, then you would run into an error there immediately. Typically, most components just render children directly and don't mess with them, so this is just sticking with established norms.
