### ISSUE TITLE
Create "ignorePath" attribute on <Switch>

### ISSUE THREAD

**Issue by felops** [ReactTraining/react-router#6233]
I would like to ignore one specific route on Switch, so I can use an URL when I need to make specifics requests directly on server. I thought something like that:

```jsx
<Switch ignorePath="/oauth">
  <Route path="/about" component={About}/>
  <Route path="/:user" component={User}/>
  <Route component={NoMatch}/>
</Switch>
```

**Comment by timdorr** [comment]
Just check for that path in your NoMatch component and navigate directly: `window.location = '/oauth'`
