### ISSUE TITLE
<Prompt> doesn't work if we didn't provide exact in <Route>.

### ISSUE THREAD

**Issue by melvin2016** [ReactTraining/react-router#6234]
## Version

**4.3.1**

## Test Case
https://codesandbox.io/s/xz9ly786mo

## Steps to reproduce
Set up a ``` <Route> ``` without the ``` exact ```  and make a ``` <Prompt> ``` inside the corresponding component it navigates to .
Eg : 
 ```
<Prompt
  when={true}
  message="Are you sure you want to leave?"
/>
```
## Actual Behavior
It simply fails to output the prompt when not provided with ``` exact ``` property.

## My Repo. Link to Problem code
[Repo. Link](https://github.com/melvin2016/reactTry)

**Comment by RaedsLab** [comment]
Seems to be working here.


![working_prompt](https://user-images.githubusercontent.com/1442690/42626033-8a0cc07e-85c9-11e8-80f8-2362882aa944.PNG)

**Comment by timdorr** [comment]
Yeah, I can't reproduce it either.
