### ISSUE TITLE
withRouter won't subscribe to any history change if inside some <ReactNewContext.Consumer />

### ISSUE THREAD

**Issue by rockmandash** [ReactTraining/react-router#6235]
First, thanks for this wonderful library!

Please see this example.
[![Edit 2zqm5l36ry](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/2zqm5l36ry)

**Inside a React new Context API Consumer, any of my component with "withRouter" will not trigger new render if history changed.**

**There is no compose, no other HOC, just only withRouter.**
I don't know if this is a bug.
Please help~ Thank you!

**Comment by timdorr** [comment]
This will be fixed by #5908
