### ISSUE TITLE
babel-plugin-import-inspector is obsolete 

### ISSUE THREAD

**Issue by Jacky-fe** [ReactTraining/react-router#6241]
please update the document
that made me confusing for hours
i tried some methods but i get "Module not found: Error: Can't resolve 'import-inspector' "
so i install the "import-inspector" module
the problem resolved

**Comment by timdorr** [comment]
The linked documentation shows how to install that plugin.

**Comment by Jacky-fe** [comment]
the documentation says ssr via "babel-plugin-import-inspector" but it does not work
the "import-inspector" is correct
