### ISSUE TITLE
[Feature Request] support custom data in Route component and collect them in a hoc.

### ISSUE THREAD

**Issue by vipcxj** [ReactTraining/react-router#6242]
It looks like this:
```javascript
// use api to create custom route data with a key.
const data = Route.createData('key', someObject);

<Router>
  <App>
    { /* 'data' is a extra prop for provide the custom data. */ }
    <Route path="/to/some/path1" component={Component1} data={data} />
      ...
    { /* withRouteData is a hoc which provide the wrapped component with the custom data of special keys */ }
    <Route Path="/to/some/path2" component={withRouteData(['key'])(Component2)} />
  </App>
</Router>
```

**Comment by pshrmn** [comment]
If you want to pass extra data to the component rendered for a route, you should use [`<Route render>`](https://reacttraining.com/react-router/core/api/Route/render-func).

```jsx
<Router>
  <App>
    <Route
      path="/to/some/path1"
      render={routeProps => (
        <Component1 {...routeProps} data={data} />
      )}
    />
  </App>
</Router>
```

**Comment by vipcxj** [comment]
@pshrmn Please reopen it. The key is collect data in some where, not provide the data.

**Comment by pshrmn** [comment]
@vipcxj based on what you have provided, I do not see this being implemented in core React Router. Maybe it should just exist as a separate package?

If you are really convinced that this is something that should exist in RR, you will need to at the very least write up a few paragraphs describing exactly what abilities the feature should perform and why this cannot be accomplished other ways/why it is better than other approaches. More ideally, you would write a PR to add this functionality yourself, but as I said, I don't think this would be added to core RR, so you should start with the outline.
