### ISSUE TITLE
switched from 2.8.1 to 4.3.1. Made no code migration. Why is it working?

### ISSUE THREAD

**Issue by againksy** [ReactTraining/react-router#6248]
I have used 2.8.1 version and now switched to 4.3.1 . I made no code migration6 just updated npm package, why is it still working? Should i wander? Or everything is ok?

**Comment by timdorr** [comment]
There might be some things working, but you should look at the migration guide to be sure: https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/guides/migrating.md
