### ISSUE TITLE
replace issue

### ISSUE THREAD

**Issue by vertic4l** [ReactTraining/react-router#6249]
Got the following issue:
{domain}{?someParams}#/{route}

That's my url, i need to update {?someParams} while preserving #/{route}.

Is there any elegant way for doing this?

Edit:
Right now i get:

{domain}{?someParams}#/{route}{?someParams}

when i try to replace it.

Or how can preserve the query params through out routes?

**Comment by timdorr** [comment]
We don't process query parameters for you, so it's up to you to handle this. However, I would avoid using a HashRouter, as you're going to run into problems like this. A BrowserRouter won't have this issue.
