### ISSUE TITLE
Path is showing as "/browse" but props shows "/"

### ISSUE THREAD

**Issue by idanlo** [ReactTraining/react-router#6250]
Hey, i am making a project using the Spoitfy API. after logging in with spotify i store the user data with the redux state and then i use  `this.props.history.push("/browse")`
 so that i go to the main app page. in the URL tab on the top side of the chrome browser i can see clearly http://localhost:3000/browse but when i  `console.log(this.props.location)` 
the pathname is "/" and there are hashes still left from the spotify log in, so my route doesn't get rendered. But if i make the route's path="/" it will render the page.

react-router: ^4.3.1

**Comment by timdorr** [comment]
See this guide: https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/guides/blocked-updates.md

**Comment by idanlo** [comment]
thanks timdorr, my withRouter() was inside my redux connect() and not outside
