### ISSUE TITLE
Breaking change on 4.3, matchPath doesn't detect pathless routes anymore

### ISSUE THREAD

**Issue by cloud-walker** [ReactTraining/react-router#6252]
Hi,

on my server side code I use `matchPath` to detect the page that will be rendered (for server side rendering purposes):

```javascript
const routes = [
  {path: '/foo', component: FooPage}, 
  {path: '/bar', component: BarPage}, 
  {component: DefaultPage},
]
// ...
const middleware = (req, res) => {
	const route = routes.find(route => matchPath(req.path, route)) // undefined on 4.3.1, {component: DefaultPage} on 4.2.2
	// ...
}
```

## Test Cases
- version 4.2.2: https://codesandbox.io/s/jjn8mwqnyv
- version 4.3.1: https://codesandbox.io/s/wk8966q5j7

For my problem I can easily check for undefined and assume that the component is the `DefaultPage`, but I think this was a breaking change and its worth for a discussion 👍 

Thanks in advance!

**Comment by timdorr** [comment]
This was an intentional change to fix #4695. You should be using react-router-config for these kinds of patterns.
