### ISSUE TITLE
Rerendering components with iframe leads to browser history duplicates

### ISSUE THREAD

**Issue by smschick** [ReactTraining/react-router#6259]
## Version
react-router: 4.3.1
react-router-dom: 4.3.1

## Test Case
https://codesandbox.io/s/v8z2j10pm0   <- with editor
https://v8z2j10pm0.codesandbox.io/changelog/  <- opens in browser window **(will show broken behavior)

## Steps to reproduce
Using BrowserRouter and withRouter either push to history or a Link to.  Change the route path to the same route/component but with a different parameter.  Component renders itself with the iframe and change the iframe's source depending on parameters/state.

## Expected Behavior
Route changes and only pushes to the History api once.  Then when you click the back button it goes immediately to the previous "page"/route

## Actual Behavior
Route changes and pushes the History location twice.  Back button takes two click to go to actual previous page/route

This has something to do with the iframe as if you replace the iframe with an object tag you will achieve expected behavior

I found this old "closed" issue that seems to be the exact same thing:  [https://github.com/ReactTraining/history/issues/526]

Still seems to be an issue though

**Comment by timdorr** [comment]
This is just how iframes work, unfortunately. The navigation events of the iframe (change its `src` attribute in this case) are propagated up to the parent window as well. So your duplication is just coming from the iframe itself.

Unfortunately, because CodeSandbox messes with history in its sandboxing, the issue is a bit obscured (removing the iframe results in no navigation events). But in a real world site, that's the behavior you'd see even without React Router.

**Comment by smschick** [comment]
For anyone in this situation this was my "fix":

I create the iframe on render… then on component did mount I set it’s source:
`componentDidMount() {
    if (this.state.html5 && this.state.type === 'iframe') this.ifrm.src = this.htmlGameSrc
  }
`
 THEN on component did update, instead of setting the source I replace the iframe’s contentWindow location… that doesn’t add to the history
`componentDidUpdate(prevProps) {
    if (this.state.html5 && this.state.type === 'iframe' && prevProps.location !== this.props.location) {
      this.ifrm.contentWindow.location.replace(this.htmlGameSrc)
    }
  }`


The iframe's source is set on first render and then replaced if it's updated/different.
