### ISSUE TITLE
‘warning’ dependency version conflict

### ISSUE THREAD

**Issue by andraaspar** [ReactTraining/react-router#6263]
When doing a flat install with yarn, I get:

```
info Unable to find a suitable version for "warning", please choose one by typing one of the numbers below:
  1) "warning@^4.0.1" which resolved to "4.0.1"
  2) "warning@^3.0.0" which resolved to "3.0.0"
Answer?:
```

Any chance to use only one version of warning?

https://github.com/ReactTraining/react-router/blob/2b94b8f9e115bec6426be06b309b6963f4a96004/packages/react-router/package-lock.json#L4301

https://github.com/ReactTraining/react-router/blob/2b94b8f9e115bec6426be06b309b6963f4a96004/packages/react-router/package-lock.json#L9334

**Comment by timdorr** [comment]
That would be dependent on history updating, so it's a question for that library.
