### ISSUE TITLE
Page refresh/reload is needed to update the rendered component when using render prop with <Route/>

### ISSUE THREAD

**Issue by mghazanfar89** [ReactTraining/react-router#6264]
## Version

4.3.1

## Test Case
I've many `<Route />` component inside of `<Switch>` as children. This `<Switch>` is obviously wrapped with `<BrowserRouter/>`. All works well when I pass the component to be rendered in the prop "component" but when I use render prop so I can pass custom props, the link in the browser changes but the component remains the same. If I refresh the tab, it shows up the component that was supposed to render when Link was clicked. So, It shows as if the component gets rendered but it needs a page refresh so it could show us the rendered component. This behavior is odd and irritating. Please help me!

## Steps to reproduce
```js
<Switch>
  <Route
    exact
    path="/"
    render={props => <Main {...props} {...loginProps} />}
  />
  <Route
    path="/forgot-password"
    render={props => <Main {...props} {...forgotProps} />}
  />
  <Route
    path="/set-password/:username"
    render={props => <Main {...props} {...setPasswordProps} />}
  />
</Switch>
```

## Expected Behavior
Render and show the updated component when Link is pressed.
## Actual Behavior
Shows rendered component only if 'component' prop is used to pass the expected rendered component. Does not update expected component to be rendered if passed through 'render' props. It updates the UI if the Browser's window/tab is refreshed.

**Comment by timdorr** [comment]
See this guide: https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/guides/blocked-updates.md

**Comment by mghazanfar89** [comment]
@timdorr Thank you. it was really helpful!
