### ISSUE TITLE
Text passed as a URL parameter changes before it gets to Route

### ISSUE THREAD

**Issue by goleary** [ReactTraining/react-router#6267]
## Version

6.0.0

## Test Case
https://codesandbox.io/s/q8mz5x03j6

## Steps to reproduce

- call encodeURIComponent on the ID provided
- pass as URL param
- call decodeURIComponent on the URL param received by the route.
the url parameter used in this link changes by the time it gets to the route.
This results in some unfortunate consequences in my application

## Expected Behavior

the text of the URL parameter has changed by the time it gets to the Route

## Actual Behavior

The text should remain the same and it should output `true` next to 'same as before' in the example.

It looks like the root of the problem is that `%2520` within the param is being converted to `%20` somewhere along the way

**Comment by timdorr** [comment]
This is ultimately caused by history. Here's the issue open to track the bug: ReactTraining/history#505
