### ISSUE TITLE
Invalid prop path supplied to route.

### ISSUE THREAD

**Issue by DanZeuss** [ReactTraining/react-router#6270]
## Version

4.3.0

## Steps to reproduce
Set an array of paths in the ``path`` prop. 
<Route path={["/et", "/et/:edit/:engagement/:id/:view"]} component={EngagementTrackerContainer}/>

## Expected Behavior
According the documentation, the ``path`` prop accepts any valid URL path that ``path-to-regexp`` understands, however, according the ``path-to-regexp`` documentation, the path parameter could be a string or an array of strings which is the case that I'm using in the example above.

## Actual Behavior
It throws the following exception:
`Failed prop type: Invalid prop 'path' of type 'array' supplied to 'Route', expected 'string'. in Route`

**Observation:** Even setting an array of path, ``react-router``renders the view, but, throws the exception.

**Comment by DanZeuss** [comment]
Before going to fix it, I'd like to ask you @mjackson or @timdorr  agree with the issue above.

**Comment by pshrmn** [comment]
The documentation is incorrect (or at least, unclear). `<Route path>` only supports strings, although at some point it may also support arrays. If you would like to open a PR to fix the documentation (probably change `valid URL path` to `valid URL string`), that would be appreciated.

**Comment by DanZeuss** [comment]
But, don't you agree that, even the document being wrong and it's accepting the array with the paths (working throwing the exception though) is an issue?
