### ISSUE TITLE
How to prevent history.push if location didn't change?

### ISSUE THREAD

**Issue by daryn-k** [ReactTraining/react-router#6271]
If current page is `site.com/one` and I'm clicking on `<Link to='/one'>One</Link>`, it pushing new item to `history ` on every click (but location don't changing). How to prevent that? It's really stupid behaivor.

**Comment by timdorr** [comment]
It's how the history API works.

**Comment by daryn-k** [comment]
timdorr, no, it's how your react-router4 works... stupid.
