### ISSUE TITLE
<Router history={history}> does not execute <Route>

### ISSUE THREAD

**Issue by Bowfish** [ReactTraining/react-router#6273]
I need to use `<Router history={history}>` in `index.js` instead of `<BrowserRouter>` like this:
```javascript
import React from 'react';
import ReactDOM from "react-dom";
import { Router } from 'react-router-dom'
import { Route } from 'react-router-dom'
import { syncHistoryWithStore } from 'react-router-redux'
import browserHistory from './redux/history'

import store from "./redux/store";

const history = syncHistoryWithStore(browserHistory, store)

ReactDOM.render((
	<DrizzleProvider options={drizzleOptions} store={store}>
		<LoadingContainer>
			<Router history={history}>
				<Route path='/' component={AppContainer} />
			</Router>
		</LoadingContainer>
	</DrizzleProvider>
	),
	document.getElementById('root')
);
```
Like this it does not execute the specified route. If I use `<BroeserRouter>` it works but then I don't have my custom route. How can I solve this?

## Version
react 16.4.1
react-redux 5.0.7
react-router-dom 4.3.1
react-router-redux 4.0.8
history 4.7.2

**Comment by nuthinking** [comment]
I am also trying to figure out how to listen to history change with BrowserRouter

**Comment by timdorr** [comment]
react-router-redux 4.x doesn't work with React Router 4.0. It's been deprecated in favor of libraries like connected-router.
