### ISSUE TITLE
Feature request: an updateStaticContext function

### ISSUE THREAD

**Issue by callumlocke** [ReactTraining/react-router#6275]
Thanks for making react-router 4, I'm really liking it so far. But I'm having trouble with one thing, and it affects compatibility with some tooling.

The issue is with `staticContext`. It's unusual (and a bit brittle) to pass a singleton object around to be freely mutated, and it causes all sorts of problems with static analysis. It's impossible to type-annotate cleanly. Even if I customise the type definition in the [react-router flow-typed libdef](https://github.com/flow-typed/flow-typed/blob/master/definitions/npm/react-router_v4.x.x/flow_v0.63.x-/react-router_v4.x.x.js#L62-L64) I still have problems. It also breaks an [ESLint rule](https://eslint.org/docs/rules/no-param-reassign.html) that I'd prefer not to override.

It would be great if you could add a new item to the the standard server router context, `updateStaticContext`, allowing the user to pass a _pure function_ to replace the static context without forcing them to mutate anything – typically by spreading the old object into a new one, Redux-style:

```js
const NotFound = () => (
  <Route
    render={({ updateStaticContext }) => {
      if (updateStaticContext) {
        updateStaticContext(context => ({
          ...context,
          status: 404,
        }));
      }
      return <h1>Not found</h1>;
    }}
  />
);
```

You could keep `staticContext` around for those who prefer it, so this would only need to be a minor update. Would you consider adding this? If so I would be happy to PR.

**Comment by timdorr** [comment]
That seems sensible. 

One counter-thought: Could you set that function as a property in the staticContext? That would seem to serve the same purpose. You could even try to make a mini Redux and give it those kinds of semantics, which are type-able.

**Comment by callumlocke** [comment]
Good idea. I'll try that. Happy for you to close this, unless you want to add it formally to RR's API.
