### ISSUE TITLE
Parameter inconsistency between history.push() and <Link/>

### ISSUE THREAD

**Issue by adam-nielsen** [ReactTraining/react-router#6279]
## Version

4.1.1

## Test Case
https://codesandbox.io/s/lp9zpl5lr9

## Steps to reproduce
1. Click on 'Roster'
2. Click on 'Ben Blocker'
3. Observe the URL contains `?number=1` and the console log shows this value appearing in the `location.search` field, with the `match.params.number` field as blank.
4. Click the 'history push' button, which uses `this.props.history.push()` to move to the new URL.
5. Observe that the URL now (hopefully) contains a different `?number=X` value, however in the console this information is no longer in `location.search` (which is now null), instead being accessed through `match.params.number` instead.
6. Click the 'Next player' link.
7. Observe that the value from the URL has now moved back to `location.search`.
8. If you click the 'history push' button a few times, the value will consistently be found in `match.params.number`, but when you use the back button a few times to go back again, those values will appear in `location.search` instead.

## Expected Behavior
The search parameters in the URL should always appear in the same variable, rather than move around depending on the method used to navigate to the page.

## Actual Behavior
When clicking links, the search parameters appear in `location.search`, however when using `history.push()` the same search parameters instead appear in `props.match.params`, with `location.search` being empty.

Although this example uses `HashRouter`, the same problem appears with `BrowserRouter`.

**Comment by pshrmn** [comment]
You are passing `history.push()` an object, but putting search information in the `pathname` segment. The `history` package only parses the provided location if you pass it a string, so you should either do that or pass the `search` segment as a separate property from the `pathname`.

```js
// this won't work
history.push({ pathname: "/search?number=1" });

// either pass a string
history.push("/search?number=1");

// or split the pathname and search segments
history.push({ pathname: "/search", search: "?number=1" });
```

Also, the issues section for this repo is intended for bug reports, not support. If you have any more issues, please ask on StackOverflow or in the Reactiflux discord. Both of those are better suited for answering support questions.

**Comment by adam-nielsen** [comment]
Oh my apologies, it looked like a bug to me, I didn't think to recheck `history.push()` since it appeared to work correctly otherwise.  Sorry for the noise, and thanks for your solution!
