### ISSUE TITLE
react.proptypes is undefined

### ISSUE THREAD

**Issue by mrpanchal** [ReactTraining/react-router#6280]
i have made a simple programme on react-roucter ...but it is not working properly,i can't understand what's going wrong here
my React version is "16.3.2" and router version is "2.8.1" 
here is my code of react-router:

**index.js**
`   import React, { Component } from 'react';
    import ReactDOM from 'react-dom';
    import { Router, browserHistory} from 'react-router';
    import routes from './routes';

ReactDOM.render(
    <Router history={browserHistory} routes={routes} />,
    document.querySelector('.container')
);`

**routes.js**
`import React, { Component } from 'react';
import { Route, IndexRouter } from 'react-router';
import App from './components/app';

export default(
  <Route path="/" component={App} />
);`

but it shows errpr like this: **unable to get property 'func' of undefined or null refernce** in the microsoft edge,

in mozilla firefox : **react.PropTypes is undefined**

**Comment by pshrmn** [comment]
For better or for worse, the prop types are now an external package, separate from the React package. You will need to use v3 of React Router, which is essentially the same as v2 but with deprecated code removed.

Also, if you have any further support questions, but ask them on StackOveflow or the Reactiflux discord. Both of those places are setup to answer support questions, while the issues section here is intended for bug reports. Thanks!
