### ISSUE TITLE
NavLink with activeClassName and react-redux problems

### ISSUE THREAD

**Issue by fejes713** [ReactTraining/react-router#6282]
# Might be a bug, or might be my lack of knowledge.

I am working on a personal project and I've run into a small problem. I've implemented navigation with `BrowserRouter` and `NavLink`. Each `NavLink` has a `activeClassName` prop and it works flawlesly.

Today I've started implementing Redux into my application. As soon as I connected the commponent with `{ connect } from 'react-redux'` the Navigation's activeClassName prop stopped working. 

I am using version `"^4.3.1"` of `react-router-dom`.

### Any idea of what could be a problem on my side of implementation?

Here is the simplified version of it:

MainRouter - App component makes use of it.
 
```js
import { BrowserRouter as Router, Route } from 'react-router-dom';

const MainRouter = () => (
  <div className="container">
    <Router>
      <div>
        <Header />
        <Route path="/time-sheet" component={TimeSheet} />
        <Route path="/clients" component={Clinets} />
        <Footer />
      </div>
    </Router>
  </div>
);
```

Header component

```js
const Navigation = () => (
  <nav>
    <ul className="menu">
      <li>
        <NavLink to="/time-sheet" className="btn nav" activeClassName="active">
          TimeSheet
        </NavLink>
      </li>
      <li>
        <NavLink to="/clients" className="btn nav" activeClassName="active">
          Clients
        </NavLink>
      </li>
    </ul>
  </nav>
```

#### Untill this point everything worked flawlessly.

Then I connected  my application with Redux store.

```js
const initialState = {};
const store = createStore(reducers, initialState, applyMiddleware(reduxThunk));

ReactDOM.render(
  <Provider store={store}>
    <App />
  </Provider>,
  document.getElementById('root')
);
```

And then I connected App.js with store via react-redux's `mapStateToProps` and `connect` functions

Any guidance will help me! Thanks. 😄

**Comment by timdorr** [comment]
See this guide: https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/guides/blocked-updates.md
