### ISSUE TITLE
Redirect to the same path with different search.

### ISSUE THREAD

**Issue by ChiuMungZitAlexander** [ReactTraining/react-router#6290]
Dear friends,

Currently I am working on a project using react router.

I met a situation -- redirect to another url with same path but different search like this
prevURL: `/clients?page=1`
curURL: `/clients?page=2`
```<Redirect to={`/clients?page=${page}`} />```

However, the browser warned that "you tried to redirect to the same route you're currently working on...".

I solved the problem by just using ```window.location.href = `/clients?page=${page}` ```. But I don't think it is the best practice. Could you please give me any hints?

**Comment by timdorr** [comment]
You need to pass in the object form of the location in that case: `<Redirect to={{ pathname: '/clients', search: `page=${page}`}} />
