### ISSUE TITLE
Modal Route with React 16.4.2

### ISSUE THREAD

**Issue by SugarDarius** [ReactTraining/react-router#6292]
Hi ! 

I would to share with you guys about modal routes with React 16.4.2. 
Now methods like componentWillUpdate are considered unsafe. 

Which is the best way to create modal routes without unsafe methods ? 

Thanks, 
Aurélien

**Comment by timdorr** [comment]
Those APIs are still safe to use for now. But if you want to avoid them, you should probably use setState and getDerivedStateFromProps to derive a state value from the previous location, which would allow you to pop or not pop the modal.

If you want to submit a PR with documentation changes, that would be welcomed.
