### ISSUE TITLE
SSR hangs when building for production with webpack version 4.

### ISSUE THREAD

**Issue by bring2dip** [ReactTraining/react-router#6294]
## Version

3.2.0

## Steps to reproduce
Build with webpack ver 4 for in prod mode.

It works totally fine in development mode. But when I build the app for production mode, the `reactRouter.match` never executes the callback. I digged into the code and find that the `transitionManager.match` doesn't return.

**Comment by timdorr** [comment]
Webpack shouldn't be involved in your SSR process. You should be running your code directly. It sounds like a configuration issue, but it's definitely something outside of our control.
