### ISSUE TITLE
onClick not in documentation

### ISSUE THREAD

**Issue by eddyerburgh** [ReactTraining/react-router#6295]
## Version
Current

## Expected Behavior

Link `onClick` is documented

## Actual Behavior

Link `onClick` is documented

Is this intentional? If not, I'm happy to make a PR

**Comment by timdorr** [comment]
Link is a wrapped for an `<a>`, so it provides all the same props. The fact we have some special case handling for `onClick` isn't an API detail. We document that we pass through all props: https://reacttraining.com/react-router/web/api/Link/others
