### ISSUE TITLE
Uncaught TypeError: Cannot read property 'func' of undefined

### ISSUE THREAD

**Issue by cptiwari20** [ReactTraining/react-router#6296]
Getting an error inside the browser console:
 **'Uncaught TypeError: Cannot read property 'func' of undefined;'**

and in bundled index.js there is a line where app fails:
var func = _react.PropTypes.func,

File index.js
`import React from 'react';
import ReactDOM from 'react-dom';
import { Provider } from 'react-redux';
import { createStore, applyMiddleware } from 'redux';
import { Router, browserHistory } from 'react-router';
import reducers from './reducers';
import routes from './routes'

const createStoreWithMiddleware = applyMiddleware()(createStore);

ReactDOM.render(
  <Provider store={createStoreWithMiddleware(reducers)}>
    <Router history={browserHistory} routes={routes} />
  </Provider>
  , document.querySelector('.container'));
`

File ./src/routes.js
`import React from 'react';
import { Route, IndexRoute } from 'react-router';

import App from './components/app';

export default (
  <Route path="/" component={App} />
);
`
Versions of the packages:
    "react": "16.3.2",
    "react-dom": "16.3.2",
  "react-router": "^2.8.1",

Unable to understand what is the actual reason and how can I solve this?

**Comment by timdorr** [comment]
You need a newer version of React Router, at least 3.2.0.

**Comment by harisbaig100** [comment]
> Getting an error inside the browser console:
> **'Uncaught TypeError: Cannot read property 'func' of undefined;'**
> 
> and in bundled index.js there is a line where app fails:
> var func = _react.PropTypes.func,
> 
> File index.js
> `import React from 'react';
> import ReactDOM from 'react-dom';
> import { Provider } from 'react-redux';
> import { createStore, applyMiddleware } from 'redux';
> import { Router, browserHistory } from 'react-router';
> import reducers from './reducers';
> import routes from './routes'
> 
> const createStoreWithMiddleware = applyMiddleware()(createStore);
> 
> ReactDOM.render(
> 
> 
> 
> , document.querySelector('.container'));
> `
> 
> File ./src/routes.js
> `import React from 'react';
> import { Route, IndexRoute } from 'react-router';
> 
> import App from './components/app';
> 
> export default (
> 
> );
> `
> Versions of the packages:
> "react": "16.3.2",
> "react-dom": "16.3.2",
> "react-router": "^2.8.1",
> 
> Unable to understand what is the actual reason and how can I solve this?

**Comment by harisbaig100** [comment]
hi, It looks like a react-router bug (related to prop types.) It's working on react-router 3.2.0
i think you should `sudo npm install --save react-router@3.2`
it works! :) :)

**Comment by cptiwari20** [comment]
Thank You. ... :)
