### ISSUE TITLE
The `click` event will trigger the next page's eventListener

### ISSUE THREAD

**Issue by manglobe** [ReactTraining/react-router#6299]
https://codesandbox.io/embed/lpw25lv547

In page _B_, I bind a `click` event  on window in `componentDidMount`.
In page _A_, I click a `Link`  to change router to _B_, then the event is triggered .
It feels strange, I bind a event on B, but triggered because of A's event.

**Comment by timdorr** [comment]
You have to remove the event listener or it will stay around. You're not loading a new page in the browser, so it's the same DOM with the same event listeners.

**Comment by manglobe** [comment]
@timdorr  I knew react-router was not loading a new page. 
The problem is I'm click a router `Link` in page A at first, but the page B's event was bind in `componentDidMount`. It should't be trigger.
