### ISSUE TITLE
Republish docs site?

### ISSUE THREAD

**Issue by callumlocke** [ReactTraining/react-router#6300]
I updated the docs in #6274 a few weeks ago, but it's still not showing on the website. Is re-rendering the docs site a manual job?

**Comment by timdorr** [comment]
As far as I know, it's automatic. But @mjackson has the keys, so I don't know exactly how it gets published.

**Comment by mjackson** [comment]
The website only gets updated when we push to the `website` branch, but 904e248542c9e4f870087e9ace585487ddbd23c3 is only in `master`. I'll go ahead and update it.

**Comment by mjackson** [comment]
This is done. You can see the build here: https://travis-ci.org/ReactTraining/react-router/builds/422630473

And the docs up to date here: https://reacttraining.com/react-router/web/guides/redux-integration

Thanks, @callumlocke :)

@timdorr Just a heads up, I merged the `website` branch into `master` and force-pushed the `website` remote with `master`. So now whenever we want to update the website all we have to do is merge `master` into the `website` branch.

**Comment by timdorr** [comment]
Cool. Thanks!
