### ISSUE TITLE
Active Class not added when the url contains the '?' in the to attribute of navlink   

### ISSUE THREAD

**Issue by adityatandon007** [ReactTraining/react-router#6302]
## Version

**4.2.2**

## Test Case
https://codesandbox.io/s/ox39vpo359

## Steps to reproduce
In the test case try going to about section the active class doesn't apply because the  **to** attribute contains the **?**. In the test case it applies for some seconds and then removes it as you can see. But in my actual code in doesn't even flicker for some seconds, it just simply doesn't apply the class. 

## Expected Behavior
Active class should be applied 

## Actual Behavior
Active class is not applied

**Comment by timdorr** [comment]
https://github.com/ReactTraining/react-router/issues/6268#issuecomment-408450350
