### ISSUE TITLE
Click `Link` will trigger the next page's eventListener

### ISSUE THREAD

**Issue by manglobe** [ReactTraining/react-router#6303]
Would you mind see the code clear at first?

https://codesandbox.io/embed/lpw25lv547

In page B, I bind a click event on window in componentDidMount.
In page A, I have a `Link` to page B.

- 1. I'm in page A at first , there was no event on window !  
- 2. I click the `Link` to page B.
- 3. The event witch bind in page B's `componentDidMount` was triggered ! 

Is that right? When I click page A's `Link` ,the page B's event was not declared !

#6299

**Comment by timdorr** [comment]
The click event is first being processed on the underlying `<a>` DOM node, which triggers the full React render cycle. Once that is done, execution can continue propagating the event up to `window`, where you event listener is waiting to receive it.

You can stop the propagation to fix it:
```js
<Link to="./b" onClick={e => e.stopPropagation()}>go to b</Link>
```

**Comment by manglobe** [comment]
@timdorr  Thanks for your answer.
I think  maybe it should be write into the document.
Use any other event to trigger a `history.push` , will also cause this problem.
