### ISSUE TITLE
Feature Request: Improvements to testing redirects in <MemoryRouter>

### ISSUE THREAD

**Issue by nathanperkins** [ReactTraining/react-router#6310]
Is there a possibility that the functionality of MemoryRouter could be extended with a method that allows a test to push changes to the history directly? That would greatly simplify the amount of code needed to do integration testing on flows that go from one page to another. The navigation testing example in the documentation shows a possible way for testing synchronous navigation, but seems like it would become awkward for async.

As an example: I'm trying to do integration testing on a form that submits a comment to an API, then redirects to another route that will fetch and show the comments. Most code examples I find online show it is easy to test that a redirect happened and where it redirected to. The ReactRouter documentation has the only example I could find that could actually test content on the redirected page. The code there is relatively complex.

**Comment by timdorr** [comment]
You can make your own memory router with a separate history instance. Then you can push to it externally however you'd like. It's simple:
```js
import { createMemoryHistory } from "history";
import { Router } from "react-router";

const history = createMemoryHistory();
const tree = mount(<Router history={history} />);

history.push('/foo');
```
