### ISSUE TITLE
Render creates components every time, doesn't update them as expected

### ISSUE THREAD

**Issue by dusanx** [ReactTraining/react-router#6314]
## Version

"react-router-dom": "^4.3.1"

## Test Case
https://codesandbox.io/s/oo5vovjm06

## Steps to reproduce

- create react app
- add react-router-dom
- create simplest case where child component reports if it is created or updated
- test with or without router, modify App.js, line 14 on codesanbox

## Expected Behavior

- Without using react-router-dom child component should be created once and updated on every props change
- With using react-router-dom child component should behave exactly the same as without it

## Actual Behavior

- Without react-router-dom everything works as expected, component is created once and updated multiple times
- With react-router-dom component is created on every render

**Comment by pshrmn** [comment]
You should be using `<Route render>`. You are creating a new component every single render by doing this:
```jsx
<Route exact path="/" component={this.render2.bind(this)} />
```
Please read the second paragraph of the [`<Route component>` documentation](https://reacttraining.com/react-router/core/api/Route/component) for an explanation.

**Comment by dusanx** [comment]
Thank you.
