### ISSUE TITLE
React Native Router navigation is reset any time Expo does live reload

### ISSUE THREAD

**Issue by kirill-konshin** [ReactTraining/react-router#6317]
## Version

RRN: 4.3.0
Expo: 29.0.0
RN: 0.55.4
R: 16.3.1

## Steps to reproduce

Open an app with React Native Router, make sure Live Reload is on (not Hot Reload), navigate to some page and do something with the code.

## Expected Behavior

App is reloaded, user stays on the same page as before.

## Actual Behavior

Index page is opened.

**Comment by timdorr** [comment]
RRN uses a memory router, so that state is getting discarded when you live reload. This isn't something we are going to handle.

**Comment by kirill-konshin** [comment]
Is there anything I can do with that? Say, supply a persisted history object, if there are any of that kind?
