### ISSUE TITLE
npm install --save react-router-dom -error

### ISSUE THREAD

**Issue by jefferyvincent** [ReactTraining/react-router#6318]
## Version
4.3.1

## Test Case
https://codesandbox.io/s/7zwjlm2j3q

## NPM Version
6.1.0

## Node Version
8.11.2

## Steps to reproduce
npm install --save react-router-dom

## Expected Behavior
It installs the package correctly instead of an error.

## Actual Behavior
npm ERR! request to https://registry.npmjs.org/react-router-dom failed, reason: Hostname/IP doesn't match certificate's altnames: "Host: registry.npmjs.org. is not in the cert's altnames: DNS:a.sni.fastly.net, DNS:a.sni.global-ssl.fastly.net"

**Comment by timdorr** [comment]
This is a network error on your end. It has nothing to do with this library.

**Comment by jefferyvincent** [comment]
Thanks! It's all good now. Stupid npm error though, should more clear.
