### ISSUE TITLE
Wrong example in docs

### ISSUE THREAD

**Issue by jddxf** [ReactTraining/react-router#6320]
Updates of `UpdateBlocker`  in the [docs](https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/guides/blocked-updates.md) will not be blocked as its `children` prop will always change when its parent re-renders.

Change its render method to:
```
render() {
  return (
    <NavLink to='/about'>About</NavLink>
    // <a href='/about' class='active'>About</a>
    <NavLink to='/faq'>F.A.Q.</NavLink>
    // <a href='/faq'>F.A.Q.</a>  
  );
}
```
should work.

**Comment by pshrmn** [comment]
PRs are always appreciated!
