### ISSUE TITLE
[Discussion] Income via Open Source

### ISSUE THREAD

**Issue by jing-c** [ReactTraining/react-router#6322]
Hello React Router developers, creator of [Boost Lab](https://boost-lab.app) here.

First of all, I’ve been loving React Router ever since the v4 update, and I’ve used it extensively in my web app. From my experiences, the technology, documentation, and community behind React Router are absolutely amazing! 👍

I created Boost Lab because I believe that financially supporting open source developers should & could be a lot simpler.

The idea behind my app is simple. Donors use it to support the projects they love. And when a pull request gets merged, an algorithm will pay the authoring developer a portion of the available funds.

With this approach, funds are automatically distributed without any additional work from maintainers or developers. And each developer gets paid (somewhat) proportionally to the amount of work they contribute.

My app is not perfect. And I know there are a lot of ways I can improve it. I would love to work with a couple of open source projects to refine the idea. If you are interested, it would be an honor to work with the developers of React Router.

Cheers!

**Comment by timdorr** [comment]
React Training supports Michael Jackson's efforts on the library. I'm rich AF, so I don't accept payment for my OSS work. Thanks, but I think we have the support systems in place for this project.
