### ISSUE TITLE
History version for react-router 3.2.0

### ISSUE THREAD

**Issue by ArtanisAce** [ReactTraining/react-router#6328]
Hi guys, recently I've updated to react-router 3.2.0 (after upgrading to React 16), and I'm having this error message on the console:

`Uncaught TypeError: Cannot read property 'getCurrentLocation' of undefined`

After reading https://github.com/ReactTraining/react-router/issues/4255, probably the issue is on my `history` version, but I've been trying a few (from 3.0.0 till 4.x), and the issue is not going away. What's the exact `history` version I should use with react-router 3.2.0? Thanks a lot! :)

**Comment by timdorr** [comment]
You should use a 3.x version of history with a 3.x version of React Router. You don't need to install it directly, as react-router will pull it in as a dependency and the Node module resolution algorithm will find it automatically.

**Comment by ArtanisAce** [comment]
Hey @timdorr, I'm still getting the same error... pretty desperate here. I'm using `react-router: 3.2.0`, and `history: 3.3.0` (following your advice, I let react-router install it). Any idea what can I try? Thanks for your quick response!
