### ISSUE TITLE
[feature] customize <Link> element type

### ISSUE THREAD

**Issue by tommytroylin** [ReactTraining/react-router#6330]
I would like to use `div` instead of `a`

e.g.
```jsx
<Link>About</Link> // <a>About</a>
<Link as="div">About</Link> // <div>About</div>
```

**Comment by pshrmn** [comment]
This has been requested a few times, but isn't going to happen. The reasoning is that using a non-anchor for links provides a poor user experience. You can see some discussion around this in #5182.

If you _really_ want a non-anchor to be used as a link, your best solution would be to make a copy of the `<Link>` module and update it to render components other than an anchor.
