### ISSUE TITLE
When I use redrict to report an error，

### ISSUE THREAD

**Issue by steady-join** [ReactTraining/react-router#6331]
## Version

"react": "^16.5.0",
"react": "^16.5.0",
"react-router-dom": "^4.2.2",

![image](https://user-images.githubusercontent.com/29935583/45478803-592e5500-b777-11e8-9dde-0824673962ad.png)
```
 <HashRouter>
          <Switch>
            <Route path="/authority/usermanage" exact component={UserManage} />
            <Redirect from='/authority' to='/authority/usermanage' />
          </Switch>
      </HashRouter>

**Comment by pshrmn** [comment]
This is an issue with your build process. `path-to-regexp` is automatically installed when you install `react-router-dom`, so it _should_ exist. but it might not hurt to re-install your dependencies just to be sure.

That said, the issues section here is for bug reports, not support. If you continue to have issues with your project, please try either StackOverflow or the Reactiflux Discord chat; both of those places are setup to help people. Thanks!
