### ISSUE TITLE
Feature request: add url(except optional path parameter) property props.match

### ISSUE THREAD

**Issue by jin60641** [ReactTraining/react-router#6332]
Now
```javascript
// Parent Component
<Route path="/child/:var?" render={(props) => (
  <Child {...props}
    url="/child"
  />
)}/>
```
```javascript
// Child
render(){
  const { url } = this.props;
  return(
    <NavLink to={`${url}/foo`}  /> // It will be '/child/var/foo' when use this.props.match.url
  );
}
```

After
```javascript
// Parent Component
<Route path="/child/:var?" render={(props) => (
  <Child {...props} />
)}/>
```
```javascript
// Child
render(){
  const url = this.props.params.match.urlExceptOptionalParameter; // property name is must be change
  return(
    <Link to={`${url}/foo`}  />
  );
}
```

_this.props.params.match.url_ is not fixed when using with optional parameter.
I think it would be nice if there were additional property for this situation.

**Comment by pshrmn** [comment]
When a `<Route>` matches, its [`match` object](https://reacttraining.com/react-router/core/api/match)  has two similar properties: `url` and `path`.

`path` is the string that was used to match a route. For example, `<Route path="/child/:var?">` would have a `match.path` of `/child/:var?`.

`url` is the string of the portion of the current `location`'s `pathname` that matched the path. Using the same above `<Route>`, for the `pathamem` `/child`, `match.url` would be `/child` and for `/child/yo`, `match.url` would be `/child/yo`.
