### ISSUE TITLE
OnLeave route path

### ISSUE THREAD

**Issue by aledg** [ReactTraining/react-router#6333]
Hello I'm Using v 4.3.1, what I've to do for call a function on event onLeave route?
For example: 

- My user is in this path of my routing:
- http://localhost/mypath
- Inside I've my business logic and my business tools
- The user want to navigate to other different path but with same layout
- http://localhost/otherPath
- OnLeave of that path I want to trigger a alert with a message: Are you sure? You want to leave this page without saving? ....(for example)

**Comment by pshrmn** [comment]
That is what the [`<Prompt>`](https://reacttraining.com/react-router/core/api/Prompt) is for.
