### ISSUE TITLE
Animatied transition launch render() multiple time FIX

### ISSUE THREAD

**Issue by Arseniy-II** [ReactTraining/react-router#6334]
Hello to all!

I have tried to implement your [animated transitions example ](https://reacttraining.com/react-router/web/example/animated-transitions). It works fine, but I noticed that components from `<Route exact path="/rgb/:r/:g/:b" component={RGB} />` launch `render()` 4 times on enter. I believe it isn't very good. I have solved this problem by adding small imporvement.

```javascript
...
import { Component } from 'react';
class PreventUnexpectedReRender extends Component {
    shouldComponentUpdate = ( nextProps ) => false;

    render() {
        return this.props.children;
    }
}
...
        <TransitionGroup>
              {/* no different than other usage of
                CSSTransition, just make sure to pass
                `location` to `Switch` so it can match
                the old location as it animates out
            */}
              <CSSTransition key={location.key} classNames="fade" timeout={300}>
                <PreventUnexpectedReRender>
                  <Switch location={location}>
                    <Route exact path="/hsl/:h/:s/:l" component={HSL} />
                    <Route exact path="/rgb/:r/:g/:b" component={RGB} />
                    {/* Without this `Route`, we would get errors during
                      the initial transition from `/` to `/hsl/10/90/50`
                  */}
                    <Route render={() => <div>Not Found</div>} />
                  </Switch>
                </PreventUnexpectedReRender>
              </CSSTransition>
            </TransitionGroup>
```

**Comment by timdorr** [comment]
This will prevent it from ever re-rendering, even for legitimate reasons, which is not what we want. The extra renders are expected, as they're just how react-transition-group works.

**Comment by Arseniy-II** [comment]
Hello, @timdorr!
No. It will not :)
[Here is test repo](https://github.com/Arseniy-II/test/tree/master/src), sorry for not providing it right away.
As usual you should do
`npm i`
`npm run dev`
go to `http://localhost:8090/`

check console from [History page](https://github.com/Arseniy-II/test/blob/master/src/containers/pages/HistoryContainer.js) while moving between pages.
Then remove `<PreventUnexpectedReRender>` from [MainComponent](https://github.com/Arseniy-II/test/blob/master/src/components/layout/MainComponent/index.js) and check console again.
