### ISSUE TITLE
LICENSE file for packages/*

### ISSUE THREAD

**Issue by Bosch-Eli-Black** [ReactTraining/react-router#6337]
Hello,

At the moment, the react-router/ package has a LICENSE file, which is great!

Could you please also add LICENSE files to the projects in the packages/* folder? For example, to the react-router/packages/react-router-dom/ project?

**Comment by timdorr** [comment]
They all share the same top level MIT license.

**Comment by Bosch-Eli-Black** [comment]
@timdorr, thanks for the reply. What you said makes sense, but I still think it'd be nice to have a LICENSE file in each package, because not having one messes up license scanners.

**Comment by brianespinosa** [comment]
I'm surprised this was closed so quickly. While there is in fact a proper license file in the root of this repository, the `react-router-dom` package is published on NPM completely separate from `react-router` and has no license file in it by itself.

**Comment by timdorr** [comment]
The license entry is included in the package.json for all 5 modules:

https://github.com/ReactTraining/react-router/blob/master/packages/react-router/package.json#L6    
https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/package.json#L6    
https://github.com/ReactTraining/react-router/blob/master/packages/react-router-native/package.json#L6    
https://github.com/ReactTraining/react-router/blob/master/packages/react-router-config/package.json#L6    
https://github.com/ReactTraining/react-router/blob/master/packages/react-router-redux/package.json#L6

While perhaps a bit more opaque, a license scanner should pick up on this. npm itself recognizes this:
```sh
 ⇶ npm view react-router license
MIT
```
Upgrading Lerna is something we should do, but it's a relatively big ask. When we get to it, you'll have a separate file for the license as well. For now, I believe this is sufficient.
