### ISSUE TITLE
<Link to="/" target="_blank"> opens a new tab with malformed URL

### ISSUE THREAD

**Issue by numatay** [ReactTraining/react-router#6344]
## Version

**react-router-dom: "4.3.1"**

## Test Case
https://codesandbox.io/s/v3mm3qoqx0

## Steps to reproduce
Create a link `<Link to="URL" target="_blank"> `that needs to open specified URL in a new tab.

## Expected Behavior
When I'm on the page "ab.com" and I open the `<Link to="example.com" target="_blank">example.com</Link>`, it needs to be opened in a new tab with example.com in the address bar.

## Actual Behavior
When I'm on the page "ab.com" and I open the `<Link to="example.com" target="_blank">example.com</Link>`, it opens a new tab with malformed URL. For example, `ab.comexample.com`.
It appends a new URL to the existing URL, which results to malformed URL.

**Comment by timdorr** [comment]
Don't use `<Link>` for external URLs. Just use an `<a>`.
