### ISSUE TITLE
Differentiate between refresh and going back.

### ISSUE THREAD

**Issue by arol** [ReactTraining/react-router#6346]
When you want to differentiate whether the current page was loaded after a reload or because your user pressed the back button, there's no way to do that.

The `history.action` passed to the component is `PUSH` if you're coming from a `Link` or `push` but is `POP` if you reload or come back from another page. In the case of a reload it feels a bit strange, shouldn't it be something like `REPLACE`, `SET` or `RELOAD`?

To reinforce this argument, check this steps, checking `history.action` on page B:

1. You're on page A and you click a link to page B.
2. Page B is loaded, it's `history.action` is set to `PUSH`.
3. Reload the page. B is mounted again, it's `history.action`'s value is `POP`.

I also think this feels kind of wrong. I don't defend its new value should be `PUSH` but something like `ROOT`, `REFRESH` or `SET`.

What do you think about that?
Why is the action's default value set to `POP`?

**Comment by arol** [comment]
Hi again, any thoughts on this?

Maybe I'm completely missing a point in design here. If it's not the case, say it and I can work in a solution in a PR.

**Comment by timdorr** [comment]
This is mirroring the DOM history API's `popstate` event: https://developer.mozilla.org/en-US/docs/Web/Events/popstate

In general, most history event's are a `POP`. We make an exception for `push` and `replace`, as they are unique to our library.

**Comment by 8427003** [comment]
@timdorr why close the issues , is it a important feature?
 going back and show the previous page！ we usually expect the page no refresh， but now can't do it。
