### ISSUE TITLE
PrivateRoute to index ("/") throws "infinite loops" error 

### ISSUE THREAD

**Issue by jrp-23** [ReactTraining/react-router#6353]
## Version

"react-router-dom": "^4.3.1"

## Test Case
<none>

## Steps to reproduce
1) I copied the "Redirects (Auth)" example from the documentation.  URL is below:
https://reacttraining.com/react-router/web/example/auth-workflow

2) I changed the below 2 lines, changing path from "/protected" to "/".
`<Link to="/">Protected Page</Link>`
`<PrivateRoute path="/" component={Protected} />`

## Expected Behavior
When initially navigating to the index page ("/"), since the user is not yet logged in, they will get redirected to the "/login" page.

## Actual Behavior
The page does not render.  Instead, the following error is thrown in the browser console.

Uncaught Error: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.

**Comment by pshrmn** [comment]
React Router does non-exact matching by default, so the path `"/"` matches every location. Add the `exact={true}` prop to your `<PrivateRoute>` (make sure that the `PrivateRoute` passes on all of its props to the `<Route>` it renders) and your application will work as expected.
