### ISSUE TITLE
@@router/LOCATION_CHANGE gets called twice on searching

### ISSUE THREAD

**Issue by ktignites** [ReactTraining/react-router#6354]
@@router/LOCATION_CHANGE gets called twice, once with 'PUSH' action which pushes a query string in stack and then with a 'REPLACE' action which replaces the existing string with itself.

Note- if no query is passed it only triggers a 'PUSH' action.
Versions-
"react-router": "3.2.1",
"react-router-redux": "4.0.8"

![screen shot 2018-09-26 at 12 50 11 pm](https://user-images.githubusercontent.com/26088676/46063562-d6e85c80-c18a-11e8-8e3f-cb7c5a0694fe.png)

**Comment by timdorr** [comment]
react-router-redux is deprecated.
