### ISSUE TITLE
Sync versioning going forward

### ISSUE THREAD

**Issue by mjackson** [ReactTraining/react-router#6356]
We currently use [`independent` versioning](https://github.com/ReactTraining/react-router/blob/afebe674caff9751ce821de9c0bae544eaac8bf2/lerna.json#L3) for all our packages, but I think it'd be better if we kept them all in sync like `react` and `react-dom` do, mainly just so people can pretty easily tell what version of a package are designed to work with what other version.

Of course, this will mean that a change in *any* of the packages will require a new version for all of them. In the worst case, a breaking change will cause everything to get a major bump.

What do you think @timdorr @pshrmn ?

**Comment by timdorr** [comment]
This was previously a hard requirement for react-router-redux, which was a major ahead. Since that's getting moved out, we should be clear. 

React Router Config could use some love to graduate from beta. There are some PRs and issues for the things that will make it more robust.

**Comment by pshrmn** [comment]
That should be fine. There are few enough packages that there shouldn't be many "no code changes, purely a version bump" releases.

At least for the short term, the only breaking change I can think of will be abandoning legacy context, which would require a major release for every package anyways.

**Comment by pshrmn** [comment]
I just look a closer look at Lerna's sync mode and I guess it doesn't actually bump a package if there are no changes.

> Fixed mode Lerna projects operate on a single version line. The version is kept in the lerna.json file at the root of your project under the version key. When you run lerna publish, if a module has been updated since the last time a release was made, it will be updated to the new version you're releasing. This means that you only publish a new version of a package when you need to.

**Comment by mjackson** [comment]
Thanks for the feedback. Honestly, `lerna publish` kinda scares me. I'm never sure exactly what it's doing, and so I don't know how to recover if it fails. And npm is asking me for a one-time password these days, so I'm not even sure we can automate publishing anymore, which makes lerna even less useful.

Let's just publish manually for now and keep the versions of `react-router`, `react-router-dom`, and `react-router-config` in sync. `react-router-native` is its own thing, and will follow its own version, similar to how `react-native` is versioned independently of `react`.
