### ISSUE TITLE
it has 'basename' that don't match my expectations.

### ISSUE THREAD

**Issue by liuzhiyang0113** [ReactTraining/react-router#6357]
i use 'basename="base"'.
and router config
<pre><code>
&lt;Switch>
      &lt;Route path="/" exact component={Index1} />
      &lt;Route path="/page1" component={Page1} />
      &lt;Route path="/page2" component={Page2} />
      &lt;Route render={() => <Redirect to="/" />} />
    &lt;/Switch>
</code></pre>
Results displayed     '/base/page1' === '/page1',why?

**Comment by timdorr** [comment]
We follow the same semantics as the base tag: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base

It's for Links you use, not for matching.
