### ISSUE TITLE
Redirect from, to does not rewrite window.location

### ISSUE THREAD

**Issue by SpLouk** [ReactTraining/react-router#6359]
Using redirect like so:

`<Redirect from="foo" to="bar" />`

Does not rewrite window.location as expected. As a result, although the above will result in the user ending up at route 'bar', if they were to click the refresh button, they will be direct back to '/foo'.

This seems to happen on Firefox, and not Chrome.

**Comment by timdorr** [comment]
It could be a timing thing. When are you checking `window.location`? If it's during some React lifecycle method, it may be too soon for the value to update. You should be checking what's in the history/router's location internally.

**Comment by SpLouk** [comment]
This is probably it, thanks. I think I was misusing window.location when I should have been using the location provided by the router.
