### ISSUE TITLE
Add a warning about using different builds

### ISSUE THREAD

**Issue by mjackson** [ReactTraining/react-router#6361]
Before 4.4, you could do this w/out problems:

```js
import MemoryRouter from 'react-router-dom/MemoryRouter';
import { Link } from 'react-router-dom';

<MemoryRouter>
  <Link /> // Error!
</MemoryRouter>
```

It's not very obvious, but those two `import` statements may actually reference different builds. The first one is using our CommonJS build, and the second one may be using the ES modules or the CommonJS build, depending on how your build is setup and where you told it to find files from the `react-router-dom` package. If you're using webpack (which you probably are) then it's probably pulling from the ES modules build.

In the case where `<Link>` is coming from a different build (or any other component, e.g. `<Route>`), you will currently run into an error like this:

> You should not render a \<Link> outside a \<Router>

This is because of the context object mismatch, which is a problem introduced by our using the new context API. Basically, each build has its own context object, and components from different builds can't be used together.

For this reason, I think it'd be nice to provide a better warning for folks who might be pulling the files from different builds accidentally, like I was doing (see 6460fe0862c40b7f726cc3d47d03cc9bbde74ff4). Maybe something like:

> You are using two different builds of React Router in the same application. To fix this, please make sure you always `import` from the same build. [link to a gist or some docs page that explains the issue more thoroughly].

**Comment by mjackson** [comment]
Also, thank you to @pshrmn who took the time to explain this issue to me in https://github.com/ReactTraining/react-router/pull/6209#issuecomment-425680210

**Comment by jimthedev** [comment]
Is this also a concern for libraries that `import {Link} from "react-router-dom";` and then are imported into an application which has its own router?

**Comment by pshrmn** [comment]
@jimthedev as long as every `react-router-dom` (technically `react-router` because that is where the context is created) import refers to the same module, there isn't an issue.

Issues are most likely to be cause by:

1. Mixing with "cherry picked" imports where one uses the ESM build and the other the CJS build.
```js
import { Route } from "react-router-dom"; // esm
import Link from "react-router-dom/Link"; //cjs
```
2. `react-router` version mismatch, which should only happen if the package version gets hard-coded.

**Comment by mjackson** [comment]
Now that we have a single entry point for each build, this could probably be as easy as defining a global variable like `globals.ReactRouterModuleFormat = 'umd'`. Then, at the top of each build we do something like

```js
if (globals.ReactRouterModuleFormat && globals.ReactRouterModuleFormat !== "cjs") {
  // warn
}
```

And we would only do this in `__DEV__` ofc. Whatcha think?

**Comment by hugomallet** [comment]
Hi,

I have a package A (built with CRA) that uses another package B built using babel in a monorepo configuration.

The code looks like this
```jsx
// Package A
import { BrowserRouter as Router } from 'react-router-dom';
import B from '@monorepo/B';

export default () => (
    <Router>
        <B />
    </Router>
);
```

```jsx
// Package B
import { Link } from 'react-router-dom';

export default () => (
    <div>
        <Link />
    </div>
);
```

They both have the dependency react-router-dom: ^5.0.0

But i get the following error : 
`Error: Invariant failed: You should not use <Link> outside a <Router>`

**Comment by pshrmn** [comment]
@hugomallet can you verify that they are using the same build? It is possible that one is importing the CJS build while the other is importing the ESM build. I think that the most likely scenario for that would be if one of the packages doesn't use the `module` field in its `package.json` while the other does, but I'm a bit fuzzy on how bundlers pick which build to use.

**Comment by prayerslayer** [comment]
Hey @hugomallet we had literally this exact same problem here since a couple of hours. Managed to fix it by enforcing the ESM build by importing every `react-router` component from `react-router-dom/esm/react-router-dom`. I don't know yet what in our toolchain apparently chose different builds.

**Comment by hugomallet** [comment]
@pshrmn How can i check that they use the same build ? 
Package B is only passed to babel, not bundled. Only package A is bundled (using CRA).

I have downgraded to 4.3.1 for now.

**Comment by pshrmn** [comment]
I would find the package in your `node_modules` folder, add `console.log()` statements to each of them, and run the application.

**Comment by MuhammadSulman** [comment]
what if we have to use react-router-dom 5.0.0 with core-ui ?

**Comment by draftitchris** [comment]
@hugomallet @pshrmn we are having this exact same problem using a lerna monorepo with yarn workspaces.  Except in our case we are importing A into B taking from hugomallets example.  Have triple checked all versions are the same and even attempted enforcing an import from react-router-dom/esm/react-router-dom but we still go the same invariant error. Downgrading to 4.3.1 works as well for us for now

**Comment by hugomallet** [comment]
I think the workaround with **lerna** is to **hoist dependencies**. Webpack seems to bundle dependencies based on relatives paths (not packages versions). So if two files require react from two different locations then react will be duplicated in the bundle (which is not permitted with react-router@5).
