### ISSUE TITLE
redux-first-history -> alternative to react-router-redux

### ISSUE THREAD

**Issue by salvoravida** [ReactTraining/react-router#6364]
https://github.com/salvoravida/redux-first-history

Hi all,

maybe you could find usefull my solution!

Let me know!

**Comment by mjackson** [comment]
Hi @salvoravida, please don't use our issue tracker to advertise your own projects. There are plenty of other places that would be great for that, but not here. Thanks :)

**Comment by salvoravida** [comment]
i'm sorry. as you discontinued rrr i think that my different approch could be usefull for react-router users.
anyway, you are right.
