### ISSUE TITLE
external link doesn't throw an error, doesn't work

### ISSUE THREAD

**Issue by worc** [ReactTraining/react-router#6368]
I ran into the issue where `<Link/>` isn't meant for external links and had a few thoughts about improving the current documentation around the issue:

First, https://github.com/ReactTraining/react-router/issues/1147 was closed without a real resolution. The [docs](https://reacttraining.com/react-router/web/api/Link) should've been updated about this gotcha. At first glance a `<Link/>` looks and behaves like a regular anchor tag, but it really only generates an anchor tag within the context of the application's router. That should be called out first in the `<Link/>` api documentation since it's the first place people look, it's unexpected behavior and it causes a workaround for a very common use case of a web page.

Second, it looks like URLs with a protocol used to throw an error or warning, but don't now and really should. We used to have a fail-fast state with an immediate message to the developer that could be improved: `warning: <Link/> does not handle external URLs, use <a> instead`. Instead, we have a time sink: *google around for a bit, dig through the issue archives, double-check the docs, okay maybe Link doesn't actually handle external URL*.

And lastly, the [workaround](https://github.com/ReactTraining/react-router/issues/1147#issuecomment-381615771) at the end of #1147 doesn't work and is misleading. That thread needs to be unlocked to call that out, or that last post deleted.

**Comment by neb42** [comment]
I think this is a recent change. I found it when upgrading from 4.2.2 to 4.3.1.

**Comment by pavelhamrik** [comment]
Ran into this as well, using 4.3.1. My Links and NavLinks are wrapped inside another component, so I can easily detect an external link and provide a different logic, but it seems to me that this could be easily handled by this library itself.

**Comment by mjackson** [comment]
Thanks for bringing this up, @worc. I agree with you on all points.

I've re-opened #1147 until we can both a) update the docs and b) add back the warning to `<Link>` about using external URLs. At that time we can close both #1147 and this issue.

**Comment by mjackson** [comment]
I'm still planning on fixing this.
