### ISSUE TITLE
Typescript Definition File on DT

### ISSUE THREAD

**Issue by semiautomatix** [ReactTraining/react-router#6374]
I understand this is maintained on DT - the issue is it's incomplete and I'm getting issues using wrappedComponentRef. There are posts from month's ago about the same issue on react-redux, so I don't expect it to be resolved soon.

Any ideas?

**Comment by timdorr** [comment]
Unfortunately, we're not going to be able to help you here. You should open an issue via DT's support channels.

**Comment by semiautomatix** [comment]
I managed to resolve the issue by first casting the component to **any**. Not ideal, but in the absence of any other alternatives: 

```
// cast as any to bypass missing typescript defs
const SideMenuWithRefs = SideMenu as any; 
```

I'm leaving this here so that anyone with the same issue with won't waste your (clearly) limited time 👎
