### ISSUE TITLE
Use Link for area tags

### ISSUE THREAD

**Issue by lucasmoeskops** [ReactTraining/react-router#6375]
Is there a way to use the Link functionality for map [areas](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/area)? They kind of act like links, but have a different tag (area instead of a). Would be nice if they could benefit from routed urls as well.

**Comment by timdorr** [comment]
You would have to implement your own component for `<area>` tags. But the actual core of Link is ust [this one line](https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/modules/Link.js#L35) in an onClick handler. Simple as that!
