### ISSUE TITLE
Redirect urls with colon causes error on the page.

### ISSUE THREAD

**Issue by ojassvi** [ReactTraining/react-router#6376]
## Version
```
react-router-dom: ^4.3.1
react: 16.5.0
react-dom: 16.5.0
```

## Test Case
https://stackblitz.com/edit/react-temicd

## Steps to reproduce
Go to the above url, click on the *test* link on the page. The page will show error. It causes error only for the Redirect, but works fine in other cases. E.g. if you click on the *Details 2* link it has the same url but it works fine.

## Behavior
It causes error on Redirect, if the redirect *to* url value contains a colon e.g. 
Failure case
```<Redirect from="/test" to="/details/2018-10-02T00:00" />``` 

But it works fine for Link,
```<Link style={styles.link} to="/details/2018-10-02T00:00">Details 2</Link> ``` this works.

**Comment by pshrmn** [comment]
React Router uses `path-to-regexp` to compile path patterns into regular expressions for matching locations, which interprets colons as params. In order for the `<Redirect>` to support redirects to routes with params, it compiles the `to` prop passed to the `<Redirect>` and attempts to inject any matched params from the `from` path.

While not perfect, I think that that best solution would be to escape the colon (`00\:00`).

**Comment by ojassvi** [comment]
@pshrmn, Thanks, your solution worked. I will close the issue.
