### ISSUE TITLE
Remove all warnings in <StrictMode>

### ISSUE THREAD

**Issue by jaredpalmer** [ReactTraining/react-router#6385]
RR4 beta still fails `<StrictMode>` because it uses the legacy context API. We should consider moving to `create-react-context` to prepare for future React releases.

**Comment by mjackson** [comment]
We actually are using `create-react-context`, but we are *also* using the legacy context API for the sake of people who might have (against our recommendation) been using `this.context.router` directly.

If it's going to be a show-stopper, we can just remove the old context code. But I was hoping to ship 4.4 with both and then just print a bunch of warnings if you access the old stuff.

Another option might be to only run that code if we're running an older build of React...

```js
if (!React.createContext) {
  Route.childContextTypes = ...
}
```

**Comment by mjackson** [comment]
Going to cherry-pick the `<StrictMode>` tests from #6287 to make sure we get rid of this problem once and for all.

**Comment by kafein** [comment]
@mjackson 
What about legacy context api? If possible please remove old context stuff. If you have a time please look issue #6348, I think its related to legacy context.

**Comment by mjackson** [comment]
I closed this prematurely. Will keep looking into it.

**Comment by mjackson** [comment]
So, I'm trying to trigger the `<StrictMode>` warning about legacy context usage so I can make a test that we don't trigger that warning, but I can't get the warning to fire no matter what I do.

Here's the test for the warning message I'm trying to trigger in React core: https://github.com/facebook/react/blob/4773fdf7cdf5d6d775ad0960f23ee1a830e7b82b/packages/react/src/__tests__/ReactStrictMode-test.internal.js#L819-L911

And here's the code I'm using to try to cause that warning to fire: https://codesandbox.io/s/k265vz8z8v

I've checked to make sure that `<StrictMode>` fires on other violations, like using `componentWillReceiveProps`, and that works fine. But I can't trigger the error with legacy context for some reason...

**Comment by mjackson** [comment]
Hey @jaredpalmer, I decided to just go ahead and run all of our tests in `<StrictMode>` to make sure we weren't triggering warnings anywhere, and we're good now on master. I'm going to cut another beta today. Please let me know how it goes!
