### ISSUE TITLE
Using Unicode routes

### ISSUE THREAD

**Issue by bragovo** [ReactTraining/react-router#6386]
## Version

4.3.0

## Steps to reproduce
```
const path = '/%D0%BF%D1%80%D0%B8%D0%BC%D0%B5%D1%80';

<NavLink to={path}>
  Posts
</NavLink>

<Switch>
  <Route path={path} component={Posts} />
</Switch>
```

## Expected Behavior
Show Posts component.

## Actual Behavior
Empty page.

## Main problem
path and location.pathname looks like `/%D0%BF%D1%80%D0%B8%D0%BC%D0%B5%D1%80` and `/пример` and does not match. In Route I can use `<Route path={decodeURIComponent(path)} component={Posts} />`. But fir NavLink I need encoded path for correct HTML code (can't decode it), but NavLink get location.pathname (decoded) from history and I can't encode it. So, NavLink never get active state. Only one way is set custom function to isActive, but its very uncomfortable.

**Comment by timdorr** [comment]
This is caused by history under the hood. There's an open issue about it here: ReactTraining/history#505
