### ISSUE TITLE
Build products and package structure

### ISSUE THREAD

**Issue by mjackson** [ReactTraining/react-router#6387]
In the current 4.4 beta, we provide 4 different builds of all our code in the `react-router`, `react-router-dom`, and `react-router-config` packages:

- A development CommonJS build in separate files in the package root
- A development ES modules build in separate files in the `es` folder in the package root
- A development UMD bundle in the `umd` folder in the package root
- A production UMD bundle in the `umd` folder in the package root

## The Proposal

There are 2 things I'd like to change:

- We should provide production versions (w/out warnings) of our CJS and ESM builds. This is honestly just an oversight in our current build strategy.
- We should stop providing separate files and deprecate stuff like `require('react-router/BrowserRouter')`. The separate files were supposed to provide a way for users to include only a portion of the library w/out including the whole thing (i.e. "poor man's" tree shaking). We actually take advantage of this ourselves in a few builds (e.g. [the CJS version of `react-router-dom`](https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/modules/.babelrc#L10-L17)) to include only the modules from `react-router` that we need using `babel-plugin-transform-imports`. However, tools like rollup and webpack 4 have made it possible to do real tree shaking, so I'd prefer to tell people to update their build tooling instead of providing a bunch of separate files. This would also let us remove `babel-plugin-transform-imports` and simplify some of our tooling.

## The Plan

4.4: Use rollup for all our builds, including CJS and ESM. Builds should be available in one of 3 folders that denotes the type of the build: `cjs`, `esm`, or `umd`. So e.g. we should have the following files for the `react-router` package:

- `cjs/react-router.js` (new)
- `cjs/react-router.min.js` (new)
- `esm/react-router.js` (new)
- `esm/react-router.min.js` (new)
- `umd/react-router.js`
- `umd/react-router.min.js`

To help users with the migration, we can keep separate files in place that print warnings telling them to `require`/`import` the main package instead of that individual file. For bundlers using the CJS/ESM builds, we can provide a small stub file as the entry point that exports either the development or production build depending on the value of `process.env.NODE_ENV`. For example, the CJS entry point for `react-router` would look something like this:

```js
if (process.env.NODE_ENV === 'production') {
  module.exports = require('./cjs/react-router.min.js');
} else {
  module.exports = require('./cjs/react-router.js');
}
```

Users can set `process.env.NODE_ENV` in their bundler to opt in to one build or the other, same as they do when bundling React itself.

5.0: Remove the stubs with warnings and stop supporting old `require`/`import` from separate files.

Thoughts and/or concerns? /cc @timdorr @pshrmn

**Comment by mjackson** [comment]
BTW, this change would cut down on the probability that users are including two separate builds of the router in their apps, making #6361 much less of a problem.

**Comment by pshrmn** [comment]
You're going to need to export the context consumer from `react-router` in order for `react-router-dom` to access it. The reason this isn't an issue right now is that the transform exports plugin [cherry picks the context import](https://unpkg.com/react-router-dom@4.4.0-beta.1/RouterContext.js).

While I think that single bundle packages are ideal, Babel still does not compile classes with static properties into pure functions. This technically breaks tree shaking, but I believe that using `sideEffects: false` with Webpack gets around this (though it is still a bit annoying).
