### ISSUE TITLE
Rollup bundle sizes

### ISSUE THREAD

**Issue by pshrmn** [ReactTraining/react-router#6393]
## Version

`v4.4.0-beta.2`

I was just looking at the build sizes on unpkg and they are much bigger than I expected.

For the ES/CJS builds, I believe that all dependencies should be considered externals. With Curi, I [import the dependencies from `package.json` and pass the package names to Rollup as externals](https://github.com/pshrmn/curi/blob/master/packages/router/scripts/build.js#L12-L14).

The UMD builds also grew from [beta 1](https://unpkg.com/react-router-dom@4.4.0-beta.1/umd/) to [beta 2](https://unpkg.com/react-router-dom@4.4.0-beta.2/umd/), but I'm not sure about the cause for that.

There is also a great Rollup plugin that I have been using to see bundle sizes: [`rollup-plugin-size-snapshot`](https://github.com/TrySound/rollup-plugin-size-snapshot).

**Comment by TrySound** [comment]
I added size snapshot here.
https://github.com/ReactTraining/react-router/pull/6395

After merge I can send PRs with optimisations.

**Comment by henryqdineen** [comment]
I'm loving these v4.4 betas but we are also running into bundle size issues unfortunately.

For our custom setup it would be preferred if we could externalize at least `prop-types`, `history`,  `create-react-context`, `hoist-non-react-statics` and `path-to-regexp`.  Let me know if there is any way I can help.

**Comment by TrySound** [comment]
It's coming in my next pr, dont worry

**Comment by mjackson** [comment]
If we externalize all that stuff, it'll technically be a breaking change since we have historically bundled all our deps. We can't ask everyone to install all that stuff as peer dependencies, can we?

**Comment by TrySound** [comment]
@mjackson No, you don't bundle anything.
https://unpkg.com/react-router@4.3.1/es/index.js

UMD is not used by bundlers so it's good to have a few small dependencies bundled in it. But cjs and esm should be free from bundled deps to share them with other dependecies.

**Comment by mjackson** [comment]
Ah, sorry. I was mixing up the CJS and UMD builds. You're right, @TrySound, we shouldn't be bundling anything in our CJS + ESM builds. That was an oversight on my part.

Did you still want to do some more work here? Or can we close?

**Comment by timdorr** [comment]
I think we did it. High five! ✋
