### ISSUE TITLE
Maybe please update the use case of render function of Route component.

### ISSUE THREAD

**Issue by TomIsion** [ReactTraining/react-router#6403]
## Version

"react-router-dom": "^4.3.1"

## Steps to reproduce

I was confused by document of react-router here:

> When you use component (instead of render or children, below) the router uses React.createElement to create a new React element from the given component. That means if you provide an inline function to the component prop, you would create a new component every render. This results in the existing component unmounting and the new component mounting instead of just updating the existing component. When using an inline function for inline rendering, use the render or the children prop (below).

from: https://reacttraining.com/react-router/web/api/Route/component

as the demo right:

```
<Route path="/user/:username" component={User} />;

const User = ({ match }) => {
  return <h1>Hello {match.params.username}!</h1>;
};
```

But by the demo, maybe the inline function return the pure html elements, so I cannot get the unmount & mounting. So I change the demo like after: 

```
<Route path="/user/:username" component={User} />;

const User = ({ match }) => {
  return <Demo />;
};

class Demo extends Component () {
  componentDidMount() {
    console.log('did mount');
  }
  
  // here other lifecycle function here
  
  render() {
    return <h1>Hello World!</h1>;
  }
}
```

when I change the url from **/user/tom** to **/user/jerry**

I found the lifecycle `componentDidMount` / `componentWillUnmount` don't execute at all.

So the doc explain the use case of `render` / `children` may be wrong ?

I think maybe the use case of `render` may like this: https://github.com/ReactTraining/react-router/blob/master/FAQ.md#how-do-i-pass-props-to-the-component-rendered-by-a-route

Because when use `component` prop of `Route`, the `props` of the output component only be after:

- match
- location
- history

**But I am new in React, so the reuse of function component may be new in React 16? After all, maybe you can update the doc for component & render function of Route.**

**Comment by timdorr** [comment]
Check #6362
