### ISSUE TITLE
Teaching BAD routing philosophies, use Query Parameters!

### ISSUE THREAD

**Issue by Falieson** [ReactTraining/react-router#6404]
For years react-router has taught tens of thousands of developers how to do routing in react. Unfortunately, many times a year I have to un-teach colleagues routing philosophies taught in the documentation.

Query Parameters, particularly IDs, should not be a middle part of a URL! The primary reason is it makes doing tracking very difficult.
Is the best url really
`animals/dogs/:dogId/breed` and  `animals/dogs/:dogId/description`  versus
`animals/dogs/breed/:dogId` and `animals/dogs/description/:dogId`
I get it! the breed and the description are for the :dogId so it should be in this order... 

Think about it as a product analyst. You don't care about the :dogId, what you are interested in is how many people are using the `breed` or `description` pages by `dogs`. 

When you hook up GA with default settings you will immediately understand this problem.

I think React-router's documentation should recommend usage of the QueryParameters API over placing IDs arbitrarily through the url like `animals/dogs/breed?dogId=` 

Improving React Router's documentation with expert opinions will save every developer using the library from having to refactor when a business person actually cares about their work.

**Comment by timdorr** [comment]
You're literally posting this on a website with IDs in the middle of the URL...
```
https://github.com/*ReactTraining*/*react-router*/issues/*6404*
```
This is a fundamental property of REST and is supported by RFC 1738/3986.

It may be a bad for your particular use case, but I really doubt any business people care much about URL structure. Sorry, but we're going to keep supporting it.

**Comment by Falieson** [comment]
@timdorr  Please be open minded. I am not making this claim on some whim but after years of frustration.

"I really doubt any business people care much about URL structure. "

I used to be a web analytics expert. I have been responsible for reporting on millions of dollars of web advertising and like I stated, **TODAY I regularly have to teach react developers the problems taught by this naive structure.**
An expert like me isn't too hindered by developers making this mistake because we know advanced analytics techniques to get around it! But most developers are working in small shops and don't have access to a GA expert. They rely on your advice for setting up react-router, usually while they are still first learning react.

From the front page of React-Router guide
```
app.get("/", handleIndex);
app.get("/invoices", handleInvoices);
app.get("/invoices/:id", handleInvoice);
app.get("/invoices/:id/edit", handleInvoiceEdit);
```

`/invoices/:id:/edit` is wrong, it should be /invoices/edit?id=:id`

This is very different than your counter example where it goes `github.com/:entityName:/:projectName:/feature/` , this is an SEO and Feature Friendly url that is using Names **not IDs**. 

`invoices/:id/edit` is WRONG and should not be taught.

Just because github has experts to get around this issue doesn't mean  you should keep propogating bad knowledge! Most people using react-router aren't implementing it in coordination with product owners. This means that they will have to refactor when they first get a non-expert that sets up GA and can't use behavioral analysis because of a bad philosophy on route naming.

**Comment by Falieson** [comment]
https://xkcd.com/1053/
<img src="https://imgs.xkcd.com/comics/ten_thousand_2x.png" />

**Comment by pshrmn** [comment]
React Router is open source; feel free to fork it.
