### ISSUE TITLE
BrowserRouter getUserConfirmation does not work correctly for the Browser Back button

### ISSUE THREAD

**Issue by nicewaytodoit** [ReactTraining/react-router#6407]
## Version
   "react-router": "^4.3.1"
+
    "react": "^16.5.2",
    "react-dom": "^16.5.2",
    "react-router-dom": "^4.3.1",
    "react-scripts": "2.0.5"

Google Chrome
Version 69.0.3497.100 (Official Build) (64-bit)
Version 70.0.3538.67 (Official Build) (64-bit)

## Test Case
https://github.com/nicewaytodoit/browser-back-bug

## Steps to reproduce
Simple logic for getUserConfirmation has been written and attached to the BrowserRouter:

`BrowserRouter getUserConfirmation={userConfirmation}`

```
const userConfirmation = (msg, callback) => {
    console.log(' @--- User confirmation', msg);
    var data= JSON.parse(msg);
    // Just simple circular logic when links are pressed 
    if (data.allowBack) {
        callback(true);
    } else {
        callback(false);
    }
}
```
In App.js a simple logic regulates when to display a Prompt question:
```
        <Prompt
          when={(!allowBack)}
          message={() => this.messageGetter(allowBack.toString())}
        />
```
And the function that sends the data info to getUserConfirmation when page is switched:
```
  messageGetter = (allowBack) => {
    return {
      "allowBack": ${allowBack}
    }
  }
```

## Expected Behavior
It is expected that each time, when user clicks on the Link or clicks on Browser Back button, if getUserConfirmation Callback return FALSE it will just output a single log line "@--- User confirmation". 
In other words, React controls will not refresh or go into control's life cycle.

## Actual Behavior
Instead, there are 3 type of behaviors:
1. When LINK is clicked if getUserConfirmation's callback is FALSE control will display a correct behavior.
 
2. When [Browser Back] button is clicked and getUserConfirmation's callback is FALSE, it will stop going to other page - but it will go to trough life cycle of update for both App and the Page user is currently on as shown below:
```
@ App: Will Update App.js:64
@ App: RENDER Page5.js:18
@ 5page: Will Recieve Props Page5.js:22
@ 5page: Will Update Page5.js:34
@ 5page: RENDER Page5.js:26
@ 5page: DID Update App.js:41
@ App: DID Update
```
At some extent this is not desirable but can be acceptable/tolerable.
This behavior is kept even if we do the right click on [browser back button] and choose some of other pages that will respond to the described logic.

3. Now, a strange thing happen if we already visited a few pages. Let say in following order Page1, Page2, Page3, Page4, Page5, then if we check right click on the [browser back button] it should be 5 pages. At this point if we click on the browser tab REFRESH button and then click [NO BACK] inside of the page to set the state that has been lost in the process, functionality should prevent user going back through mechanism of getUserConfirmation. But, after clicking on the [Browser Back button] current page (let say Page5) will stay and control will not go trough life cycle -- but with each click, address bar will change the link and Browser History will reverse for one page, until blank page is reached at that point browser will display blank tab or switch to previous web site.

Bonus: Furthermore, in the version v3 react-router with React 15.4 (code is slightly different) behavior is similar for the point 1 and 3 and in regards to point 2 there is double PopUp behavior with first '/pagex' and action PUSH and then the same address '/pagex' with POP action. Both App and PageX will  render a full React component life cycle.

I am not sure how does is work currently so I will trow few ideas/question at this point:  
Is full react history kept in react-router or history component? 
Does the the browser refresh causing lose of that state too? 
Would it be possible to hook or allow user to hook that state and persist the history state within local storage or any other way (e.g. database, sessions etc.)? 
Third behavior is not acceptable, although it could be circumvented by let say additional popup that will prevent user closing the page and refreshing  -- but that is not a solution it is just a hack.

So, question is what is good measure between what is desired behavior and what is possible?

**Comment by jrgleason** [comment]
Does it work at all I am trying this and it doesn't work... 

https://stackoverflow.com/questions/53876066/using-react-browserrouter-v4-how-do-i-recognize-when-the-location-has-changed
