### ISSUE TITLE
link in another repo is broken

### ISSUE THREAD

**Issue by mustmodify** [ReactTraining/react-router#6425]
in [react-router-redux's README.md file](https://github.com/reactjs/react-router-redux/blob/master/README.md), the text "Go take a look!" links to: 

https://github.com/ReactTraining/react-router/tree/master/packages/react-router-redux

which is a 404

**Comment by mustmodify** [comment]
I would have created a ticket over there but

> This repository has been archived by the owner. It is now read-only."

**Comment by timdorr** [comment]
I'll see about editing that. Thanks!
