### ISSUE TITLE
Use PureComponents for react-router-dom

### ISSUE THREAD

**Issue by khaledosman** [ReactTraining/react-router#6434]
## Version
4.3.1

This is a feature request.

## The problem

When using tools to monitor & optimize unnecessary rendering of components like why-did-you-update <https://github.com/maicki/why-did-you-update>

It shows that react-router-dom components like Route , Switch, Link, etc.. are being rendered unnecessarily when the props don't change. (i.e: when typing in a text field of a form calling setState in onChange)

![image](https://user-images.githubusercontent.com/2937633/47640876-f2b59880-db64-11e8-9a21-f04e63dcd68f.png)

## Solution
This can be optimised by making the component a pure component and avoiding arrow functions and such in the render methods.

This not only improves the application's performance by avoiding unnecessary renders high up the component tree, but also helps with the developer experience when you're actually trying to figure out which components can be optimized, but find a lot of third party components in your console that you can't really optimize

**Comment by timdorr** [comment]
Unfortunately, this will block any context updates from legacy context API users. While not a problem when using `createContext()`, we're not quite there yet as an ecosystem.
