### ISSUE TITLE
Is generatePath a public API?

### ISSUE THREAD

**Issue by ElForastero** [ReactTraining/react-router#6435]
Currently, we use `path-to-regexp` package to generate URLs to the routes.

And since we use `path-to-regexp` v2 and `react-router` uses v1, we have both versions in our bundle.

Would be nice to use the `generatePath` function. Can we document it?

**Comment by timdorr** [comment]
https://github.com/ReactTraining/react-router/blob/3e78f2889c823f99b7dd4697d3d5fb42de244e99/packages/react-router/modules/index.js#L8

A PR to [add the docs here](https://github.com/ReactTraining/react-router/tree/master/packages/react-router/docs/api) would be appreciated! 🙂

**Comment by ElForastero** [comment]
https://github.com/ReactTraining/react-router/pull/6437
