### ISSUE TITLE
Beta 5 throwing Failed prop type: Cannot read property 'isValidElementType' of undefined

### ISSUE THREAD

**Issue by paradoxxxzero** [ReactTraining/react-router#6445]
Since I upgraded to beta-5 I keep getting this error with webpack for some reason at this line: https://github.com/ReactTraining/react-router/blob/master/packages/react-router/modules/Route.js#L132

Upon further inspection, in the compiled file I have: 
```es6
/* harmony import */ var react_is__WEBPACK_IMPORTED_MODULE_9__ = __webpack_require__(/*! react-is */ "./node_modules/react-is/index.js");
/* harmony import */ var react_is__WEBPACK_IMPORTED_MODULE_9___default = /*#__PURE__*/__webpack_require__.n(react_is__WEBPACK_IMPORTED_MODULE_9__);

// ...

if (props[propName] && !react_is__WEBPACK_IMPORTED_MODULE_9___default.a.isValidElementType(props[propName])) {
```
and `react_is__WEBPACK_IMPORTED_MODULE_9___default.a` is `undefined` but `react_is__WEBPACK_IMPORTED_MODULE_9__.isValidElementType` exists.

**Comment by mjackson** [comment]
Related discussion here: https://github.com/ReactTraining/react-router/pull/6209#issuecomment-434754775

**Comment by paradoxxxzero** [comment]
I confirm it now works with beta 6.
Thanks!
