### ISSUE TITLE
PropType warning when passing React.lazy in component Route prop

### ISSUE THREAD

**Issue by MrTibbles** [ReactTraining/react-router#6450]
## Version

`"react-router-dom": "4.3.1"`

## Test Case
https://codesandbox.io/s/7kjzjow9r6

## Steps to reproduce
Pass a React component to the `component` property on a `Route` which was loaded with `React.lazy`.

## Expected Behavior
No `propType` warning.

## Actual Behavior
Console:
> Warning: Failed prop type: Invalid prop `component` of type `object` supplied to `Route`, expected `function`.

## Notes
The code sandbox link about displays the described prop type warning in the console window.

**Comment by pshrmn** [comment]
See #6420.
