### ISSUE TITLE
Version 4.3.0 of react-router-dom breaks NavLink bootstrap show/collapse behavior

### ISSUE THREAD

**Issue by rgamage** [ReactTraining/react-router#6452]
## Version
Using React version 16.1.1, react-router-dom 4.2.2 -> 4.3.0
bootstrap 4.1.3
jquery 3.2.1

## Test Case
Using react-router-dom 4.2.2 or earlier, bootstrap collapse / show behaviors are working as expected, using NavLink and bootstrap's collapse behaviors:

                        <NavLink className="form-control" to="#profileNotifications" data-toggle="collapse" role="button" aria-expanded="false">
                            Click here to show notification preferences
                        </NavLink>

\<div>className="collapse" id="profileNotifications">
    \<p>hidden content, show when click the above link\</p>
\</div>

## Expected Behavior
In the example code above, clicking in the NavLink should expand/show the hidden content in the profileNotifications div below.

## Actual Behavior
Using 4.3.0+, the expand behavior does not work.  The div below is always hidden, the 'show' class is not added to the div, as it should be.

I've read that it may not be recommended to mix bootstrap.js behaviors with React, but I've only read that as a side comment from one poster.  If that is indeed the official recommendation from the React community, then I'm fine with replacing this implementation with react-style showing/hiding.  However, if the intent is to co-exist with bootstrap, then I'd like to get this working.  I seem to recall that if I simply leave out bootstrap.js, then I get errors that it is a required dependency of bootstrap.

Thanks in advance for the help.

**Comment by timdorr** [comment]
You should be using a plain `<a>` here. This isn't a valid NavLink (wrong `to` prop), so you don't need to use it. 

I'd also look into a react bootstrap integration library. Using the vanilla bootstrap code with React is going to cause problems, as it will modify the DOM without its knowledge. It doesn't like that.
