### ISSUE TITLE
Add esm build to react-router

### ISSUE THREAD

**Issue by lishengzxc** [ReactTraining/react-router#6455]
Hi guys,

I want to import 'react-router' with esm in browsers,
It is not clear whether the official will provide it?

like this:

```html
<script type="module">
import React from 'https://unpkg.com/react-ecmascript@1.2.0/react.development.mjs';
import ReactDOM from 'https://unpkg.com/react-ecmascript@1.2.0/react-dom.development.mjs';
import ReactRouter from 'https://cdn/react-router.esm.js';

// ...
</script>
```

**Comment by lishengzxc** [comment]
@TrySound  I think it can not use in browsers.

**Comment by timdorr** [comment]
You can use the `module` feature of Unpkg to do this: https://unpkg.com/react-router@4.4.0-beta.6/esm/react-router.js?module
