### ISSUE TITLE
Route get remounted

### ISSUE THREAD

**Issue by jormot** [ReactTraining/react-router#6461]
Related: #4578

## Version

4.3.1

## Test Case
With `render`: https://codesandbox.io/s/7jz5ozwky0?expanddevtools=1&hidenavigation=1&view=preview
With `component`: https://codesandbox.io/s/l5wok42x49?expanddevtools=1&hidenavigation=1&view=preview

## Steps to reproduce
1. Click /a. Notice console `Component A DidMount`.
2. Click /b. Notice console `Component B DidMount`.
3. Click /a. Notice console `Component A DidMount`.

## Expected Behavior
Component should not be re-mounted. As per docs (https://reacttraining.com/react-router/web/guides/basic-components):

> You should not use the component prop with an inline function to pass in-scope variables because you will get undesired component unmounts/remounts.

## Actual Behavior
Component is being remounted on every route change, regardless of using `component` or `render.

**Comment by timdorr** [comment]
This is expected behavior. You have two separate Route's and two separate components, so each one is coming into the tree with each route change. This will cause it to not display the message more than once:
```jsx
          <Switch>
            <Route path="/a" component={ComponentA} />
            <Route path="/b" component={ComponentA} />
          </Switch>
```
