### ISSUE TITLE
react-router-dom is not working 

### ISSUE THREAD

**Issue by mainul35** [ReactTraining/react-router#6466]
## Version

**4.3.1**

## Test Code
```
import {Component} from 'react'
import React from 'react'
import ReactDOM from 'react-dom'

import {BrowserRouter as Router} from 'react-router-dom'
import Route from 'react-router-dom/Route'

const Login = ()=>{
    return (
        <h1>Login page</h1>
    )
}

const Navigation = ()=>{
    return (
        <h1>Navigation component</h1>
    )
}


class Index extends Component {
    render() {
        return (
            <Router>
                <div>
                    <h1>Hello, react</h1>
                    <Route path='/login' component={Login}/>
                    <Route path='/navigation' component={Navigation}/>
                </div>
            </Router>
        )
    }
}

ReactDOM.render(<Index/>, document.getElementById("root"))
```

## Expected Behavior

localhost:3000/login should show me the login page
localhost:3000/navigation should show me the navigation page

## Actual Behavior
Cannot GET /login

**Comment by pshrmn** [comment]
You don't have a server setup to handle dynamic requests. You can use something like [create react app](https://facebook.github.io/create-react-app/) to get you started or write your own server.

If you need help with this, I would recommend asking on StackOverflow or the Reactiflux discord. Those are both setup for helping people solve their issues, while the issues section here is intended for bug reports. Thanks!

**Comment by mainul35** [comment]
Well, I have installed live-server and run with it.

**Comment by mainul35** [comment]
However, Thanks for your suggestion :)
