### ISSUE TITLE
Error importing react-router-dom

### ISSUE THREAD

**Issue by VirginiaBalseiro** [ReactTraining/react-router#6476]
## Version: 

**react-router@4.3.1 - react-router-dom@4.3.1**

## Actual Behavior
After installing react-router and react-router-dom, I get the following error when trying to import:
```
Failed to compile.

./node_modules/react-router-dom/es/index.js
Module not found: Can't resolve 'C:\Users\Usuario\{myproject}\node_modules\react-scripts\node_modules\babel-loader\lib\index.js' in 'C:\Users\Usuario\{myproject}'
```
The installation itself is not giving any errors.

**Comment by timdorr** [comment]
There's something wrong with your build tooling. It looks like you don't have babel-loader installed. This isn't a React Router issue.
