### ISSUE TITLE
Using withRouter breaks defaultProps use with TypeScript

### ISSUE THREAD

**Issue by Kizmar** [ReactTraining/react-router#6477]
## Version
4.3.1

## Test Case
This is related to tslint yelling when props aren't passed.

## Steps to reproduce
Say you have the following:
```
ReactDOM.render(
    <Provider {...stores}>
        <Router history={history}>
            <Layout />
        </Router>
    </Provider>,
    document.getElementById('root') as HTMLElement
);
```

Then the layout component looks something like this (simplified for brevity):
```
// These properties are being injected with mobx
interface ILayoutComponentProps extends IRouteComponentProps {
    leftDrawerIsOpen: boolean;
    leftDrawerWidth: number;
}

class LayoutComponent extends React.Component<ILayoutComponentProps, any> {
    public static defaultProps: Partial<ILayoutComponentProps> = {
        leftDrawerIsOpen: false,
        leftDrawerWidth: 0
    };
    ...
}

export const Layout = inject((stores: any) => ({
    leftDrawerIsOpen: stores.navigationStore.leftDrawerIsOpen,
    leftDrawerWidth: stores.navigationStore.leftDrawerWidth
}))
(observer(LayoutComponent));
```
This works as expected, in that the use of LayoutComponent doesn't require you to pass the props. I'm doing this to get around having to mark them as `leftDrawerIsOpen?: boolean` and using `this.props.leftDrawerIsOpen!` every time I access one.

## Expected Behavior
No tslint error.

## Actual Behavior
When I wrap the layout component in `withRouter()`:
```
export const Layout = withRouter(inject((stores: any) => ({
	leftDrawerIsOpen: stores.navigationStore.leftDrawerIsOpen,
	leftDrawerWidth: stores.navigationStore.leftDrawerWidth
}))
(observer(LayoutComponent)));
```
I get this where I'm using `<Layout />`:
> [ts] Type '{}' is not assignable to type 'Readonly<Pick<ILayoutComponentProps, "leftDrawerIsOpen" | "leftDrawerWidth">>'.   Property 'leftDrawerIsOpen' is missing in type '{}'. [2322]
> 
> (alias) const Layout: React.ComponentClass<Pick<ILayoutComponentProps, "leftDrawerIsOpen" | "leftDrawerWidth">, any>
> import Layout

I barely understand how the whole `defaultProps: Partial` stuff works, so I'm not sure where this is going wrong, or if it's just something I need to work around when using `withRouter` in conjunction with `defaultProps`.

**Comment by timdorr** [comment]
We don't maintain any typings for React Router. If you're getting them from DefinitelyTyped, you'll need to use their support resources to get help.
