### ISSUE TITLE
Prompts not working with external links

### ISSUE THREAD

**Issue by selbekk** [ReactTraining/react-router#6485]
## Version
4.3.1 (but I guess all versions)

## Test Case

https://codesandbox.io/s/j4xo67jl29

## Steps to reproduce

Click the different links (and the back button) in the provided sandbox to verify

## Expected Behavior

I assumed that the `<Prompt />` component would catch all navigations out of my site, no matter how it happened.

## Actual Behavior

Prompts only show up when you click a `<Link />` or use the `location.(push|replace)` methods. Nothing happens for external links (links that use a good ol' `<a href />` tag) or when you use `window.location.href`. 

What's the reasoning for this design choice? Also - if this is something that can't / won't be supported, could we add a note to the readme explaining this? Took me a bit of time before I understood what was the issue.

**Comment by timdorr** [comment]
See #4372
