### ISSUE TITLE
history.listen() order is wrong after async redirect

### ISSUE THREAD

**Issue by Cap32** [ReactTraining/react-router#6486]
## Version

react-router-dom@v4.3.1

## Test Case

https://codesandbox.io/s/2ok5o94olp

## Steps to reproduce

Open test case link, and open `console` panel. You could click "retry" to reproduce again.

## Expected Behavior

Should log

```
location /1
location /2
```

## Actual Behavior

```
location /2
location /1
```

**Comment by timdorr** [comment]
This is because the entire React render loop and history update process runs synchronously. The setTimeout is pushing that message to the very end of the queue and it doesn't get a chance to run until React has finished rendering. That's just how React works, so we can't get around that.
