### ISSUE TITLE
history.push() doesn't work with RN and react-router-native.

### ISSUE THREAD

**Issue by ruxes7** [ReactTraining/react-router#6488]
## Version
    "expo": "^31.0.2",
    "react": "16.5.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-31.0.0.tar.gz",
    "react-router-dom": "^4.3.1",
    "react-router-native": "^4.3.0",

# My code

import React from 'react';
import { StyleSheet, Text, View, Button, Dimensions, Image } from 'react-native';
import { NativeRouter,  Switch, Route, Link } from 'react-router-native';
import createHistory from 'history/createMemoryHistory';

const history = createHistory();

export default class App extends React.Component {
  render() {
    return (
      <Router>
        <Switch>
          <Route exact path="/" render={(props) => <HomeScreen history={history} {...props} />} />
          <Route path="/details" render={(props) => <DetailsScreen history={history} {...props} />} />
        </Switch>
      </Router>
    );
  }
}

class HomeScreen extends React.Component {

  render() {
    return (
          <View>
            <Button title='details' onPress={() => history.push("/details")} />
          </View>
    );
  }
}

class DetailsScreen extends React.Component {
  render() {
    return (
      <View>
        <Text>Details Screen</Text>
        <Link to="/" underlayColor="#f0f4f7"><Text>Go to Home</Text></Link>
        <Link to="/details"><Text>Go to Other</Text></Link>
      </View>
    );
  }
}

## Expected Behavior
I wanna move to 'DetailsScreen' when I push <Button>. (by 'onPress={() => history.push("/details")}')

## Actual Behavior
If I push <Button> tag, nothing happens.  
I can see history object from console.log(history);.

**Comment by pshrmn** [comment]
The `<NativeRouter>` creates its own history, so the one that you create doesn't actually affect navigation. Remove your `createHistory()` call, change these lines, and everything should work as expected.

```diff
- <Route exact path="/" render={(props) => <HomeScreen history={history} {...props} />} />
- <Route path="/details" render={(props) => <DetailsScreen history={history} {...props} />} />
+ <Route exact path="/" component={HomeScreen} />
+ <Route path="/details" component={DetailsScreen} />
```

That said, the issues section here is intended for bug reports, not support questions. Please use Stackoverflow and the Reactiflux Discord chat for support. Both of those locations are setup to have people assist you. Thanks!

**Comment by ruxes7** [comment]
I put that code like so but It doesn't work for history. When I pushed back button of Android device, App is closed. I wanna back to previous page when I pushed back button. Or I wanna move between pages by push() or any method. 

How can I use?

**Comment by b33son** [comment]
Same issue here. Push does not work. Nothing happens when calling push. Nothing happens when using the Redirect component. Something is broken.

**Comment by rdrnt** [comment]
@b33son Have you had any luck solving this issue? I'm having the same problem.
