### ISSUE TITLE
Allow NavLink url to match solely on the url hash

### ISSUE THREAD

**Issue by bschlenk** [ReactTraining/react-router#6491]
It would be nice if the `NavLink` component was able to be active based solely on the `hash` portion of the url. I have a bunch of `NavLink` components on a page and each one just updates the url `hash`:

```jsx
<NavLink to="#first" activeClassName="active" />
<NavLink to="#second" activeClassName="active" />
<NavLink to="#third" activeClassName="active" />
```

These won't ever get the `active` class because the `NavLink` component doesn't consider it a match. I can add this to the `isActive` prop:

```jsx
const hash = "#first";
<NavLink to={hash} isActive={(_, location) => location.hash === hash} />
```

but it would be so much cleaner if this just matched by default.

**Comment by timdorr** [comment]
This isn't possible because we have HashRouter and may use the hash for routing.
