### ISSUE TITLE
reactRouter.Router.computeRootMatch is not a function

### ISSUE THREAD

**Issue by sgtram** [ReactTraining/react-router#6492]
I'm trying to upgrade react-router-config from 1.0.0-beta.4 to 4.4.0-beta.6 and I'm getting this error

## Version

**react-router@4.3.1**
**react-router-dom@4.3.1**
**react-router-config@4.4.0-beta.6**

## Console log

TypeError: reactRouter.Router.computeRootMatch is not a function
    at /.../node_modules/react-router-config/cjs/react-router-config.js:19:26
    at Array.some (<anonymous>)
    at matchRoutes (/.../node_modules/react-router-config/cjs/react-router-config.js:17:10)

**Comment by timdorr** [comment]
You have mismatched versions. RRC 4.4 can only be used with Router 4.4. If you want to keep using Router 4.3, switch back to the 1.0.0-betas.

**Comment by sgtram** [comment]
👍 thanks! it works!
