### ISSUE TITLE
is react-router not compatible with react fiber?

### ISSUE THREAD

**Issue by bansalvks** [ReactTraining/react-router#6494]
Hi Team,

First of all, you are doing an amazing job :) 

I am facing a warning when using **react-router-dom 4.3.1** with **react fiber 16.6**

here is a screen shot which I am getting
<img width="781" alt="screenshot 2018-11-28 at 4 51 39 pm" src="https://user-images.githubusercontent.com/8565993/49149929-75cb3980-f331-11e8-97ff-944412afc170.png">

Please suggest what should I do

Many thanks
Vikas Bansal

**Comment by pshrmn** [comment]
v4.4, which is currently in beta, will be compatible.
