### ISSUE TITLE
typescript react.lazy not working

### ISSUE THREAD

**Issue by xpioneer** [ReactTraining/react-router#6495]
## Version

```
"react": "^16.6.3"
"react-router-dom": "4.3.1"
...
"@types/react": "^16.7.7"
"@types/react-router-dom": "^4.3.1"
```

## Test Case

https://github.com/xpioneer/react-typescript `(code splitting not working)`

## Expected Behavior

https://github.com/xpioneer/react16-lazy `(It's working, code splitting is normal)`

## Actual Behavior

In typescript，React.lazy doesn't split the code. 
typescript project screenshot:
![image](https://user-images.githubusercontent.com/30486161/49287717-7dc5dd80-f4d9-11e8-91c0-7bac515d594e.png)

the normal splitting react16-lazy screenshot:
![image](https://user-images.githubusercontent.com/30486161/49287759-a057f680-f4d9-11e8-9461-23687ef2180d.png)

Do I need to use babel or change webpack config file?

How can I change the router so that it working?  Thanks~~

**Comment by pshrmn** [comment]
I threw together a minimal test using Create React App, TypeScript, and React Router and the code splitting worked. While I cannot say _why_ code splitting isn't working in your application, I am confident that React Router is not the cause.

**Comment by xpioneer** [comment]
Thank you very much, I will review my code. Then read the code generated by Create React App.

**Comment by kodermax** [comment]
@xpioneer Did your typescript example work?

**Comment by xpioneer** [comment]
@kodermax I changed the loader, use babel...It's working~~
