### ISSUE TITLE
Redirect not work correctly with params (when have same base url)

### ISSUE THREAD

**Issue by NKozlov** [ReactTraining/react-router#6504]
## Version

react-router-dom version 4.3.1

## Test Case

https://codesandbox.io/s/738zk3y3x0

I want redirect "/procurement/:id" to "/procurement/:id/items", but it doesn't work.

## Expected Behavior
Redirect works.

## Actual Behavior
Error: You tried to redirect to the same route you're currently on: "/procurement/123/items" and no render component.

## Workaround
If i change redirect "/procurement/:id" to "/notEqualProcurement/:id/items", all works fine.

**Comment by henryqdineen** [comment]
Have you tried to add an `exact` prop to your `<Route path="/procurement/:id" />`?

I believe the `<Switch />` is always choosing the route because it will match even for `/procurement/123/items`.

**Comment by timdorr** [comment]
You're using a plain `<a>` for your link. If you're making a route change, you need to use `<Link>`.

**Comment by NKozlov** [comment]
@henryqdineen , you r right. Even for `/procurement/123/items` matches to pattern `/procurement/:id`.
Exact works fine, thank you. Also, if placed line with `Route` to `/procurement/:id/items` above `Redirect`, it works fine too. `<Switch/>` will work from  particular to general (and break when find route). Thank all! It works!
