### ISSUE TITLE
When I try to use replace, will the location search value be automatically transcoded?

### ISSUE THREAD

**Issue by steady-join** [ReactTraining/react-router#6506]
example:
this.props.history.replace(`/collection/result?condition=${测试}`);
result：
first：Search in location contains 测试
second：Location test transcoded into %e6%b5%8b%e8%af%95
Q：
When I use componentWillReceiveProps, will there be two different behaviors?

**Comment by timdorr** [comment]
This is caused by the underlying history library. See: https://github.com/ReactTraining/history/issues/505
