### ISSUE TITLE
Unexpected Route path behaviour

### ISSUE THREAD

**Issue by mrenrich84** [ReactTraining/react-router#6507]
## Version

    "react-router-dom": "^4.3.1",

## Test Case

https://codesandbox.io/s/5znr8oxvp

## Expected Behavior
> var re = pathToRegexp('/:id', keys, {strict: false})
undefined
> re.exec('/update/1')
null

## Actual Behavior
In the test code above, this route:   
 `<Route path="/:id" component={ReadJob} />`
is swallowing the /update/1 path somehow and thus the next route:     
`<Route exact path="/update/:id" component={UpdateJob} />`
will unexpectedly be not executed

**Comment by timdorr** [comment]
That is essentially a wildcard route. You can either mark it as `exact` or move it to the last route in the Switch.
