### ISSUE TITLE
Upgrade hoist-non-react-statics (Out in react-router@4.3.0-rc.2)

### ISSUE THREAD

**Issue by kubijo** [ReactTraining/react-router#6508]
_Originally posted by @timdorr in https://github.com/ReactTraining/react-router/issues/6057#issuecomment-377987576_

Can we please have this bumped in the version 3 as well?

**Comment by jfirebaugh** [comment]
Using react-router with a component that uses [`contextType`](https://reactjs.org/docs/context.html#classcontexttype) triggers:

> Warning: withRouter(Feedback): Function components do not support contextType.

https://stackoverflow.com/questions/53240058/use-hoist-non-react-statics-with-withrouter#comment93369276_53241270

Upgrading the hoist-non-react-statics dependency to 3.1 or later will fix this. https://github.com/ReactTraining/react-router/commit/5407993bd01647405586bbdd25f24de05743e4a7 did so, but isn't in any released version (even 4.4.0 betas).

**Comment by jfirebaugh** [comment]
The above mentioned change is included in v5.0.0 and later, so I think this can be closed.
