### ISSUE TITLE
NavLink with get params in the url is not marked as active

### ISSUE THREAD

**Issue by The-Code-Monkey** [ReactTraining/react-router#6510]
I know this has been asked a-lot but there is no reason why you should be using search on urls,

I cant see any logical reason why if you could explain why this is the choice as the other explanations just say you aren't doing it, there is a reason why in the last time someone asked you this you replied you get a lot of downvotes about it, there is a reason why you get the downvotes as it doesn't make sense to be taking that into account as if you pass to a search page it may be user inputted its impossible to match if your including the query string. please change your stance on this.

if you don't want to make this the default maybe a bool that is added to the url that will get only window.location.pathname rather than everything?

**Comment by timdorr** [comment]
https://github.com/ReactTraining/react-router/issues/6268#issuecomment-408450350

**Comment by The-Code-Monkey** [comment]
Yeah that's exactly the comment I'm talking about it gives no reasoning as to why you think parsing a query string into a active route is a good idea as that's not the route, that is something which modifys the data in the route but doesn't display a different route?
