### ISSUE TITLE
setState() will trigger own state reset when using react-router?

### ISSUE THREAD

**Issue by SAMJAYHK** [ReactTraining/react-router#6511]
### **Version**
<hr />
react-router-dom@4.3.1

### **Problem**
<hr />
Sorry for my stupid question. I'm facing a most trouble when using react-router. I have develop a simple react app including using react-router, which have a simple setState() function as a props and pass to child component. But when child component trigger this function which will also reset the own state to default value. I dont know how the problem trigger, because when I simply just call child component with function without react-router it will not reset the own state. Here is my code:

App.js
```
import React, { Component } from 'react';
import User from './User'
import { BrowserRouter as Router, Route, Link, Switch } from "react-router-dom";

class App extends Component {
	constructor(props) {
		super(props);
		this.state = {
			name: ''
		};
	}
	
	handle = () => {
		this.setState({name: 'apple'}) 
	}
	
  render() {
    return (
      <div className="App">
		<Router>
		<>
		<Link to="/me" >Me</Link>
		<Route exact path="/me" component={() => <User handle={this.handle} />} />
		</>
		</Router>
      </div>
    );
  }
}

```
User.js
```
class Users extends Component {
	constructor(props) {
		super(props);
		this.state = {
			type: ''
		};
	}
	
	handleClick = () => {
		this.setState({type: 'orange'}) // this line i have setState type to 'orange' before calling the parent function. 
		this.props.handle() // this line is just to change the parent state by using handle()
		console.log(this.state) // this line is just print the own state.
	}
	
  render() {
    return (
      <div className="App">
		<div onClick={this.handleClick}>Click!</div>
      </div>
    );
  }
}

```
-Response:
```
{name: "apple"}
{type: ""} => but is should be "orange" not empty.
```

Could anyone can help me? Thanks.

**Comment by pshrmn** [comment]
```jsx
<Route exact path="/me" component={() => <User handle={this.handle} />} />
```
Please see the second paragrpah of the [`<Route children>` docs](https://reacttraining.com/react-router/web/api/Route/component).

For future support questions, please use either StackOverflow or the Reactiflux Discord. Both of those are setup to answer support questions, while the issues sections here is intended for bug reports. Thanks!
