### ISSUE TITLE
Async/sync location updates after history back/forward

### ISSUE THREAD

**Issue by OliverJAsh** [ReactTraining/react-router#6512]
## Version

4.2.2

## Steps to reproduce

If I understand correctly:

1. `history.goBack` delegates straight to the History API.
2. Immediately afterwards,  `window.location` refers to the previous page.
3. When the `popstate` event is emitted (via `history.listen`), `Route` components will be updated with the new `location` prop (derived from the current `window.location`).

I have a modal component which calls `history.goBack` when it's closed, just like the example here: https://reacttraining.com/react-router/web/example/modal-gallery.

My problem:

- Components may re-render themselves any number of times between `history.goBack` (1, above) being called and the `popstate` event being emitted (3).
- During these re-renders, the `location` prop will refer to the *old* `location` (the one prior to the `history.goBack` call).

This means the modal will remain mounted (because the current `location` is still the modal), and the user may try to close the modal again, resulting in another call to `history.goBack`.

1. user comes to our site (`/`) from another site (e.g. Google)
2. user clicks through to a modal `location` (`/modal`)
3. user closes modal. URL immediately updates (`/`), but old modal `location` remains (`/modal`; due to no `popstate` event yet), thus modal remains mounted
4. user tries to close modal again, and location reverts to Google (!)

I'm wondering if React Router should synchronously/immediately update route components with the new location after a call to `history.go{Back,Forward}`, rather than waiting for the `popstate` event (which is asynchronous). This should eliminate problems like the example I gave above.

(I'm also wondering why there is such a long delay between `history.goBack` and `popstate`—perhaps because we have a lot of other work to complete in the stack frame that `history.goBack` is called.)

(I'm hoping I haven't misdiagnosed the problem here…)

**Comment by pshrmn** [comment]
While this does not address the underlying issue, the quickest fix would be to disable closing the modal after its close/back button has been clicked (e.g. use  an instance variable to track if the modal has been "closed").

**Comment by OliverJAsh** [comment]
@pshrmn Thanks, that is what I ended up doing, but since the official modal example follows the same approach, I thought about raising it as an issue.

**Comment by OliverJAsh** [comment]
In some situations the delay seems to be quite significant. I added a lot of console logging and I could see a few Redux actions being dispatched, in response to data being loaded, between the call to `history.goBack` and `popstate` being received. If that's all happening in the same stack frame (thus delaying the `popstate` event), that's a sign of performance problems on our end, but nonetheless it still feels like the `location` should be correct in the interim period.

Here's a video of the "double back" modal bug I described above: https://www.dropbox.com/s/5xcjam2ts7ya9qe/back-to-google.mov?dl=0. You can see there's a period of about 5 seconds between the first and second call to `history.goBack` (i.e. when user tries to close modal), with no sign of the modal being removed from screen (due to no new `location`).

**Comment by OliverJAsh** [comment]
Any further thoughts on this?

**Comment by OliverJAsh** [comment]
@pshrmn IIRC, I did add a `console.log` to the `history.listen` inside React Router, and I saw that it didn't fire during that delay.

**Comment by lostPixels** [comment]
Just found this lovely bug today in my own codebase. My routes render components that AJAX load their data. For some reason those AJAX requests are now all loading the wrong URLs at the wrong time. It's been fine for 1.5 years, and just happened out of no where.
