### ISSUE TITLE
Parsing error: Unexpected token for Route

### ISSUE THREAD

**Issue by udf2457** [ReactTraining/react-router#6514]
Node v10.14.1
Router-dom 4.3.1

According to the docs (https://reacttraining.com/react-router/web/guides/quick-start) , this should be possible:

`<Route path={`${match.path}/:id`} component={Topic} />`

However this seems to yield a parsing error on my side (I've tried replacing the ticks with quotes, but it makes no difference, I have also tried this.props.match.path)

```
  Line 6:  Parsing error: Unexpected token

  4 | 
  5 | class GalleryRouter extends Component {
> 6 |     <Route path={`${match.path}/:id`} component={GalleryApp} />
    |     ^
  7 | }
  8 | 
  9 | export default GalleryRouter;
```

**Comment by timdorr** [comment]
This is something with your Babel setup. It has nothing to do with React Router.
