### ISSUE TITLE
What is the difference between props.history.location and props.location?

### ISSUE THREAD

**Issue by 951565664** [ReactTraining/react-router#6515]
Have a usage question?
======================
What is the difference between props.history.location and props.location in my Component or Container?I found out that in my component they will appear at the same time，I printed their values and found that their values are equal.

**Comment by pshrmn** [comment]
[They are the same.](https://github.com/ReactTraining/react-router/blob/0853628daff26a809e5384f352fada57753fc1c3/packages/react-router/modules/Router.js#L19) `location` is a frequently used property, so it is made "first class" by passing it as its own prop. The `history` object is more useful if you want to programmatically navigate (use its `push`/`replace` methods).
