### ISSUE TITLE
Can't run RecursiveExample 

### ISSUE THREAD

**Issue by zwl1619** [ReactTraining/react-router#6520]
https://reacttraining.com/react-router/web/example/recursive-paths

![image](https://user-images.githubusercontent.com/13177997/50381284-2b35a680-06be-11e9-9022-0791ef024948.png)

**Comment by timdorr** [comment]
Without knowing more about your system, I'm not able to see what's going on exactly. But I just copied that example into a fresh CRA install and it worked fine.
