### ISSUE TITLE
Can't run ParamsExample

### ISSUE THREAD

**Issue by zwl1619** [ReactTraining/react-router#6521]
https://reacttraining.com/react-router/web/example/query-parameters

![image](https://user-images.githubusercontent.com/13177997/50381573-946ce800-06c5-11e9-8a41-107e26585faa.png)

**Comment by timdorr** [comment]
Yeah, this is a wonky example that doesn't work outside of the example context because it's built with a Router instance around everything. But it's meant to be just a simple example, not something you actually use, so don't think it's important to fix this.
