### ISSUE TITLE
[React.memo] Warning: Failed prop type: Invalid prop ...... expected `function`

### ISSUE THREAD

**Issue by ddzy** [ReactTraining/react-router#6524]
## Version
![issue_bug_2](https://user-images.githubusercontent.com/33921398/50436375-98e10d00-0920-11e9-846f-138ec3bd8fd7.jpg)
![issue_bug_3](https://user-images.githubusercontent.com/33921398/50436376-98e10d00-0920-11e9-9aa4-6aa713dd59cf.jpg)

## Expected Behavior
I want to know how to fix it?🤔🤔🤔
## Actual Behavior
This error always occurs in my app, just like this
![issue_bug_1](https://user-images.githubusercontent.com/33921398/50436478-1dcc2680-0921-11e9-8509-3bfa7c920a8a.jpg)

**Comment by pshrmn** [comment]
This will be fixed in the next minor release. See #6471.
