### ISSUE TITLE
history.listen is fired after Route's componentDidMount (POP action only)

### ISSUE THREAD

**Issue by ukasa** [ReactTraining/react-router#6525]
## Version

**react-router-dom: 4.3.1**

## Test Case

https://codesandbox.io/s/myo52m80x8

## Steps to reproduce

Try navigating route by clicking links (PUSH action). Then navigate to another route using back or next buttons (POP action).

## Expected Behavior

```
PREPARING NAVIGATE TO /chat
MOUNTED /chat
```

## Actual Behavior

```
MOUNTED /chat
PREPARING NAVIGATE TO /chat
```

**Comment by timdorr** [comment]
The router's subscription to the history comes before yours, so React is getting priority. This is expected. If you don't want this behavior, make your own instance of history, subscribe to it first, and then pass it to a plain Router instance.

**Comment by ukasa** [comment]
Pardon, how to subscribe the history and pass it to Router? Can you show me the code?

**Comment by timdorr** [comment]
Just do what one of our pre-configured Routers does: https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/modules/BrowserRouter.js

**Comment by timdorr** [comment]
You'll want to add your listener on this line, as an example: https://github.com/ReactTraining/react-router/blob/0853628daff26a809e5384f352fada57753fc1c3/packages/react-router-dom/modules/BrowserRouter.js#L12

**Comment by ukasa** [comment]
Still same even after turn it like this

```
class CustomRouter extends React.Component {
  history = createBrowserHistory(this.props)

  componentDidMount() {
    this.unlisten = this.history.listen(({ pathname }) => {
      console.log('PREPARING REDIRECT TO ' + pathname)
    })
  }

  componentWillUnmount() {
    this.unlisten()
  }

  render() {
    return <Router history={this.history} children={this.props.children} />;
  }
}

render(
  <CustomRouter>
    <App />
  </CustomRouter>,
  document.getElementById('root')
)

```

Correct me if I'm wrong.

**Comment by timdorr** [comment]
You need to listen in your constructor. cDM is too late.

**Comment by ukasa** [comment]
OMG, u r right. Thank you so much, I've spent days to figuring this out. Great work anyway :+1:
