### ISSUE TITLE
Change url without refresh with react router. 

### ISSUE THREAD

**Issue by rubossq** [ReactTraining/react-router#6527]
**What I propose**: add a param to disable page refresh after url change.

**Why I propose that**
Many people need to change url without reloading a page. I have few issues because every url change make re-render entire application. For example:

### Search
When a user enter some query or activate a filter - I would like to make a request and change url in his browser inside my component. Instead I have full re-render application tree and observables state lost. 

**constructor**
```
if(!isServer()){
      dispatch(clearDietList());
}
```
I need to clear current state because some pages reuse the state and it can be changed from many pages.
**ComponentDidMount**
```
const {fetched, error, isFetching} = this.props;
if((!fetched && !error && !isFetching)){
      dispatch(fetchList(newQuery));
}
```
**onFilterChanged**
`history.replace(location.pathname + '?' + stringifyParams(newQuery));`

In **onFilterChanged** I change url and it will automatically affect new data loading. Instead some may use another behavior like simple fetching data from a server: `dispatch(fetchList(newQuery));`. But with react router **we can't.**

Also in this case observables are useless because of state lost. An observable recreates.
I use Rxjs and debounceTime with distinctUntilChange won't work after page refresh.
```
this.subscription = this.handleChange$.pipe(
    filter(ev => ev && ev.target),
    pluck('target', 'value'),
    debounceTime(500),
    map(val => val.trim()),
    distinctUntilChanged()
).subscribe(query => {
    onChange(query);
});
```

### Hash

I would like to show a side - view with some data (look attachment). I also want to change url - add a hash. To let people copy url with new state. 
<img width="583" alt="screen shot 2018-12-28 at 8 25 33 pm" src="https://user-images.githubusercontent.com/16590371/50531950-cb853400-0adf-11e9-9c32-301d1811234d.png">
Why should main container refresh and reload data from a server if I it need to load data for side view only?
The link before was **app/block1** then user opened side-view and link become **app/block1#block2**

### Side effects
Like custom libraries what  change url and don't know about page reloading because of react-router

I am new in react. Maybe I am absolutely wrong with my requirements to the router or with the code above. Please let me now. I only want to say that change url without refreshing would be nice thing to add in future versions. 
Anyway I have tried to make it better.
Thank you!

**Comment by timdorr** [comment]
The router shouldn't be refreshing the entire page if you're changing the URL via Link components. This is already something we do. Look at any of the examples, for instance.
