### ISSUE TITLE
Issues redirecting programmatically with history.push when using HashRouter

### ISSUE THREAD

**Issue by vaibhavtel** [ReactTraining/react-router#6529]
## Version

4.3.1

## Test Case
https://codesandbox.io/s/o442p59yq9

## Steps to reproduce
1, open the link https://o442p59yq9.codesandbox.io/
2, click on "Topics" link
3, click on "Components" link under "Topics"
4, click on "Go To About Page" button
## Expected Behavior
Should redirect to about page (history.push("about"))
https://o442p59yq9.codesandbox.io/about 
## Actual Behavior
Redirecting to "About" page under topics
https://o442p59yq9.codesandbox.io/topics/about

**Comment by timdorr** [comment]
You need to use an absolute URL when using the history API. It doesn't support relative links.
