### ISSUE TITLE
Please accept Ref to wrappedComponentRef

### ISSUE THREAD

**Issue by DavidSvetlik** [ReactTraining/react-router#6530]
## Version

react-router-dom@4.3.1

## Test Case

React devs introduced new way to create Refs instead of an function via React.createRef(), it would be useful if React Router's "wrappedComponentRef" would support it as well.

## Steps to reproduce

Simply try to use wrappedComponentRef={this.myRef}. It actually works, strangely, but it throws warnings.

## Expected Behavior

No warnings, accept created Ref.

Thank you.

**Comment by timdorr** [comment]
This will be available in 4.4, which uses React.forwardRef. You can try out the beta release now.

**Comment by DavidSvetlik** [comment]
@timdorr Great, thanks!
