### ISSUE TITLE
Uncaught DOMException: Failed to execute 'pushState' on 'History'

### ISSUE THREAD

**Issue by ezrogha** [ReactTraining/react-router#6533]
I am relatively new to react-router-dom and have enjoyed using it in react apps. Currently, am trying to add react to my web page, but have failed to make a route because react-router-dom keeps producing this error.

![react-router-dom](https://user-images.githubusercontent.com/35653907/50734921-8df76980-11b7-11e9-98c3-49982164ae2c.PNG)

I followed this demo https://codepen.io/schafeld/pen/yzvZPj

**Comment by timdorr** [comment]
You cannot use a BrowserRouter with a file:// path. It's a security thing. Either set up a small web server or use HashRouter.
