### ISSUE TITLE
location.pathname contains basename in initial request

### ISSUE THREAD

**Issue by methodus** [ReactTraining/react-router#6536]
## Version

4.3.1

## Steps to reproduce

main.ts
```
import { Router } from 'react-router';
import { createBrowserHistory } from 'history';

const history = createBrowserHistory({ basename:'/addon/homer' })

ReactDOM.render(
    <Router history={history}>
      <Container />
    </Router>,
  document.getElementById('root')
);
```

container.ts

```
export const Container = hot(module)(withStyles(styles)(withRouter(
class Container extends React.Component<Container.AllProps> {

  render() {
    return (
      <div className={classes.container}>
            <Switch>
              <ActivityRoute exact path="/" activity={App} />
              <ActivityRoute path="/functions" activity={Functions} />
              <ActivityRoute path="/rooms" activity={Rooms} />
              <ActivityRoute path="/devices" activity={Devices} />
              <ActivityRoute activity={Empty} />
            </Switch>
      </div>
    )
  }
}
)))
```

## Expected Behavior

The basename is stripped from location.pathname for every request.

Requests made:
1) https://example.com/addons/homer/ --> location.pathname === /
2) https://example.com/addons/homer/functions --> location.pathname === /functions
3) https://example.com/addons/homer/ --> location.pathname === /

It should render:
1) App
2) Functions
3) App

## Actual Behavior

The basename is only stripped when I go back to / by clicking on a <Link to="/" /> component. The first request however will always result in having the basename in location.pathname.

Requests made:
1) https://example.com/addons/homer/ --> location.pathname === /addons/homer
2) https://example.com/addons/homer/functions --> location.pathname === /functions
3) https://example.com/addons/homer/ --> location.pathname === /

It actually renders:
1) Empty (i.e. not found)
2) Functions
3) App

Hope someone can help.

**Comment by timdorr** [comment]
The basename is only used for matching. It's not used for storing the location itself.

**Comment by methodus** [comment]
I understand that. However it does not work for matching in the first attempt in my case.
It gives me `match.path="/"` and `match.isExact=false` while location.pathname="/addons/homer/" when I open the page the very first time. For subsequent requests I get  `match.path="/"` and `match.isExact=true` with location.pathname="/". After the `location.pathname` is adapted correctly to the basename, the matching is working as intended. This is why I thought that the incorrect location.patzname is causing the issue.

I could strip off the basename from the location.pathname it it exists, but this won't fix the matching issue.

Any ideas?
