### ISSUE TITLE
Feature request: make <Route /> respect a `null` (or non-`undefined`) `computedMatch`

### ISSUE THREAD

**Issue by lemonmade** [ReactTraining/react-router#6542]
My application has a mechanism for creating asynchronously loaded components that can be preloaded. Basically, most of our route components are created in this form:

```jsx
const HomePage = createAsyncComponent({
  load: () => import('./HomePage'),
});

// Renders the page
<HomePage />

// Preloads the bundle and any async dependencies, like GraphQL queries
<HomePage.Preload />
```

I am building a tool that will determine a URL the user is likely to navigate to, and will automatically render the preloading component for that route. What I would like to do is to reuse our existing routing setup to register these preloads. So, I have built a custom route component that effectively boils down to:

```jsx
function CustomRoute(props) {
  return <>
    <RegisterPreload path={props.path} component={props.component} />
    <Route {...props} />
  </>
}
```

Now, this works fine and dandy, until I start putting my route in a `Switch`. There, if the path does not match, my route component is never rendered at all, and so I can never register my preload component. I got pretty far by just writing a custom `Switch` component that *does* render all of its children; where the existing `Switch` ignores all but a single matched route, mine clones all all children with a `computedMatch={null}` prop:

```jsx
// Mostly just copied from the React Router source, the different part is our collection of all children and the cloning of non-matched ones with computedMatch: null

export default class Switch extends React.Component<Props> {
  render() {
    return (
      <Route>
        {({location, match}) => {
          let foundMatch: null | typeof match = null;

          const children = [];

          // We use React.Children.forEach instead of React.Children.toArray().find()
          // here because toArray adds keys to all child elements and we do not want
          // to trigger an unmount/remount for two <Route>s that render the same
          // component at different URLs.
          React.Children.forEach(this.props.children, (child) => {
            if (
              match == null &&
              React.isValidElement<{path?: string; from?: string}>(child)
            ) {
              const path = child.props.path || child.props.from;

              foundMatch = path
                ? matchPath(location.pathname, {...child.props, path})
                : match;

              children.push(
                foundMatch
                  ? React.cloneElement(child, {location, computedMatch: match})
                  : React.cloneElement(child, {location, computedMatch: null}),
              );
            } else {
              children.push(
                React.cloneElement(child, {location, computedMatch: null}),
              );
            }
          });

          return React.createElement(React.Fragment, {}, ...children);
        }}
      </Route>
    );
  }
}
```

That brings me to the feature request: `<Route />` currently [checks `computedMatch`](https://github.com/ReactTraining/react-router/blob/master/packages/react-router/modules/Route.js#L25-L29) for falsiness only. If a more restrictive check were performed (for example, checking for explicitly `=== undefined`), I could pass the computedMatch as I do here and everything would just work.

I am likely using private API (as this prop is not present in the prop typings for the Route component), so I totally understand if this is a no-go on your side. The alternative for our project is simply to mirror all the route declarations for the preloaded components, which isn't the end of the world.

Thanks for continuing to build such an excellent library!

**Comment by timdorr** [comment]
You're correct that `computedMatch` is a private API. As such, I'm not seeing a compelling reason to change things from our perspective. I guess it is technically more correct to be explicit about our checks, but for readability, having `if (computedMatch)` is better. 

Thanks for the detail on this issue, but I think we're going to keep things as-is for now.
