### ISSUE TITLE
hashRouter，this.props.history.push trigger popstate? 

### ISSUE THREAD

**Issue by Vibing** [ReactTraining/react-router#6543]
I use `this.props.history.push()` in my project to run in chrome, which always fires `popstate`. Is there a solution?

My English is not good, please forgive me.

## Version

"react-router-dom": "^4.3.1",

**Comment by pshrmn** [comment]
The hash router relies on setting `window.location.hash` and calling `window.location.replace()`. Both of these result in a `popstate` event. The only navigation that doesn't cause `popstate` are `history.pushState` and `history.replaceState` (which are used by the browser router).

That said, there shouldn't be any issues with these `popstate` events. The hash router listens for `hashchange` events to detect forward/back button presses, so `popstate` shouldn't interfere with that.
