### ISSUE TITLE
 React-Router only rendering the "/" route

### ISSUE THREAD

**Issue by hcsgzh** [ReactTraining/react-router#6549]
Hi there,
## Version
I am using 
```
"dependencies": {
    "react": "^16.7.0",
    "react-dom": "^16.7.0",
    "react-router-dom": "^4.3.1",
    "react-scripts": "2.1.3"
  },
"devDependencies": {
    "@babel/core": "^7.2.2",
    "@babel/plugin-proposal-class-properties": "^7.2.3",
    "@babel/preset-env": "^7.2.3",
    "@babel/preset-react": "^7.0.0",
    "reload": "^2.4.0",
    "babel-loader": "8.0.4",
    "webpack": "4.19.1",
    "webpack-cli": "^3.2.1"
  }
```

## Test Case
I have a problem with react-router when I use "Route" with webpack and babel. React-Router only rendering the "/" route.
The problem is React-Router rendering only "/" route, If I use webpack and babel to generate the bundle.js. But when I use "react-scripts start", React-Router will render properly.

There are three routes in the project.

"/main"

"/"

"about"

Here is my simple test App.

https://github.com/hcsgzh/testapp

## Steps to reproduce
1. When I run the same code by using react-scripts start. The React-Router will render properly. 

`npm start`

```
      Object(C_node_reactJS_testapp_node_modules_babel_runtime_helpers_esm_createClass__WEBPACK_IMPORTED_MODULE_1__["default"])(_default, [{
        key: "render",
        value: function render() {
          return react__WEBPACK_IMPORTED_MODULE_5___default.a.createElement(react_router_dom__WEBPACK_IMPORTED_MODULE_6__["BrowserRouter"], {
            __source: {
              fileName: _jsxFileName,
              lineNumber: 14
},
            __self: this
}, react__WEBPACK_IMPORTED_MODULE_5___default.a.createElement(react_router_dom__WEBPACK_IMPORTED_MODULE_6__["Switch"], {
            __source: {
              fileName: _jsxFileName,
              lineNumber: 15
},
            __self: this
}, react__WEBPACK_IMPORTED_MODULE_5___default.a.createElement(react_router_dom__WEBPACK_IMPORTED_MODULE_6__["Route"], {
            path: "/main",
            render: function render() {
              return react__WEBPACK_IMPORTED_MODULE_5___default.a.createElement("h2", {
                __source: {
                  fileName: _jsxFileName,
                  lineNumber: 16
},
                __self: this
}, "Main");
},
            __source: {
              fileName: _jsxFileName,
              lineNumber: 16
},
            __self: this
}), react__WEBPACK_IMPORTED_MODULE_5___default.a.createElement(react_router_dom__WEBPACK_IMPORTED_MODULE_6__["Route"], {
            path: "/",
            exact: true,
            render: function render() {
              return react__WEBPACK_IMPORTED_MODULE_5___default.a.createElement("h2", {
                __source: {
                  fileName: _jsxFileName,
                  lineNumber: 17
},
                __self: this
}, "Home");
},
            __source: {
              fileName: _jsxFileName,
              lineNumber: 17
},
            __self: this
}), react__WEBPACK_IMPORTED_MODULE_5___default.a.createElement(react_router_dom__WEBPACK_IMPORTED_MODULE_6__["Route"], {
            path: "/about",
            render: function render() {
              return react__WEBPACK_IMPORTED_MODULE_5___default.a.createElement("h2", {
                __source: {
                  fileName: _jsxFileName,
                  lineNumber: 18
},
                __self: this
}, "About");
},
            __source: {
              fileName: _jsxFileName,
              lineNumber: 18
},
            __self: this
})));
}
}]);

      return _default;
}(react__WEBPACK_IMPORTED_MODULE_5__["Component"]);
```
2. However, if I run the same code by using webpack --mode development and run the code. The React-Router will render only "/" route.

`npm run watch`

```
_createClass(_default, [{
    key: "render",
    value: function render() {
      return react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement(react_router_dom__WEBPACK_IMPORTED_MODULE_1__["BrowserRouter"], null, react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement(react_router_dom__WEBPACK_IMPORTED_MODULE_1__["Switch"], null, react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement(react_router_dom__WEBPACK_IMPORTED_MODULE_1__["Route"], {
        path: "/main",
        render: function render() {
          return react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement("h2", null, "Main");
}
}), react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement(react_router_dom__WEBPACK_IMPORTED_MODULE_1__["Route"], {
        path: "/",
        exact: true,
        render: function render() {
          return react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement("h2", null, "Home");
}
}), react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement(react_router_dom__WEBPACK_IMPORTED_MODULE_1__["Route"], {
        path: "/about",
        render: function render() {
          return react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement("h2", null, "About");
}
})));
}
}]);
```
## Expected Behavior
I want to use webpack to generate the bundle.js file.  `webpack --mode development` or `webpack --mode production`

The three routes should render when I hit it. Not just "/" route rendering.

## Actual Behavior
When I run the same code by using react-scripts start. The React-Router will render properly. 

`npm start`

The three routes will render as I exspected.

However, if I run the same code by using webpack --mode development and run the code. The React-Router will render only "/" route.

`npm run watch`

Just "/" route renders.

## Guess
I think the problem is after the babel translated the JSX code and the result JS code is different when I use `react-scripts start` and `webpack --mode development`.

React-scripts will translate the code correctly but the webpack will translate wrong. Hence, I guess the problem is from the bable. Maybe my babel did not configure properly. Could someone take a look in my .babelrc file? and please explain to me.

```
{
    "presets": [
        "@babel/env", "@babel/react"
    ],
    "plugins": [
        "@babel/plugin-proposal-class-properties"
    ]
}
```

**Comment by Hisagr** [comment]
If you created your app with create-react app it already contains webpack config. You need either to use just CRA and delete all webpack configs or don't use CRA at all and configure everything yourself.
Alternatively, you can also eject CRA and customize everything, but it's not recommended.

**Comment by hcsgzh** [comment]
I figured out the problem. 

Actually, It is not about React-Router or my babel configuration. It is because of the different routes that could not match the index.html file. This testapp project used reload to server the react app. The reload did not match every route to the index.html.

### The solution 

> Handles any requests that don't match the backend API to index.html

For example,  if you use express as a backend for your react app, you would like to have the code below.
```
app.get('*', (req,res) =>{
//make sure here is your production path if you deploy your app
    res.sendFile(__dirname+'/public/index.html'); 
});
```
With the code above, if I hit the route like "localhost:3000/main", I will get the content as I expected.
Also for route "/" and "about", I  will get the right content.

So, the "problem" solved. I am going to close the topic.
