### ISSUE TITLE
useEffect() not available when using Route w/render instead of component => Hooks can't be passed

### ISSUE THREAD

**Issue by desmap** [ReactTraining/react-router#6555]
If you use useEffect() (from React Hooks) in a component which `<Route>` routes to via `render=` instead of `component=`, useEffect is in that component obviously not available/working because 
_Hooks can only be called inside the body of a function component._ 

But you need to use `render=` if you want to pass props, e.g. if you want to pass a root Hook to children components down the tree. In this https://github.com/ReactTraining/react-router/issues/4105#issuecomment-317902366 the inline render is the 'preferred winner' to pass props. So actually we need a new and proper way to pass props with `component=`, also without the remounting issue. Otherwise react-router can't employ React Hooks' new feature set (custom hooks, useState, useEffect, etc.). Or I missed something.

**Comment by Voronar** [comment]
Working as expected.
https://codesandbox.io/s/vy8q12kw1l

**Comment by timdorr** [comment]
Yep, it works fine.

**Comment by desmap** [comment]
@Voronar. thx for preparing a Sandbox, here my version where a custom hook is passed and which doesn't work: https://codesandbox.io/s/o4wxn5y8k5 @timdorr pls check as well

**Comment by desmap** [comment]
Ok, found the bug in my local code, my bad and thanks for you quick response.
