### ISSUE TITLE
Feature Request: Ignore Router basename in <NavLink>

### ISSUE THREAD

**Issue by whizkid77** [ReactTraining/react-router#6564]
Allow `<NavLink>`s to ignore the basename that is set in its encompassing `<Router>`.  I'm nesting routers, and I'd like to be able to route to a parent router from within a child router.  For example:

Main.jsx:
```
<BrowserRouter>
  <Route path="/aaa" .../>
  <BrowserRouter basename="/foo">
     <Route path="/bbb" component={Home}/>
  </BrowserRouter>
</BrowserRouter>
```

Home.jsx:
```
...
 // this links to "/bbb/aaa", when I want it to just go to "/aaa"
<NavLink to="/aaa">My link</NavLink> 
...
```

**Comment by timdorr** [comment]
You shouldn't have multiple BrowserRouters on the page. That won't work regardless, as it's talking to the nearest Router ancestor. Once you wrap another Router, you've created a new history instance and therefore a whole subset of routes and links. This is how our examples work on the website, for instance.
