### ISSUE TITLE
<Route> throws an exception when using an array with "path"

### ISSUE THREAD

**Issue by enriquemorenotent** [ReactTraining/react-router#6566]
This seems to be the same issue as #6270 by @DanZeuss but it is still not solved.

This is my code:

```html
<Route path={['/events/list/table', '/events/review']} render={() =>  <MyComponent />} />
```
And it works. The problem though is on the developer tools, where this exception message can be read:

> Warning: Failed prop type: Invalid prop `path` of type `array` supplied to `Route`, expected `string`.

But the [documentation says that arrays are a valid input](https://reacttraining.com/react-router/web/api/Route/path-string-string).

This exception should not be thrown.

**Comment by timdorr** [comment]
This is forthcoming in the 4.4 versions.

**Comment by enriquemorenotent** [comment]
@timdorr Thanks you! Good to know.
