### ISSUE TITLE
matchPath return null without slash before queryString

### ISSUE THREAD

**Issue by trofivan** [ReactTraining/react-router#6568]
## Version

Latest (4.3.1)

## Test Case

https://codesandbox.io/s/04r7m439ww

## Steps to reproduce
Open console on codesandbox and run script

## Expected Behavior
Result: [Object, Object, Object, null]

## Actual Behavior
Result: [null, Object, Object, null]

**Comment by timdorr** [comment]
We don't process query strings, so that is being included in the full path match. It's null because `"/path?foo=bar" != "/path"`, essentially.

**Comment by vijaybritto** [comment]
Can we ignore query strings while trying to match?
