### ISSUE TITLE
Proposal: Use onbeforeunload for Prompt

### ISSUE THREAD

**Issue by bali182** [ReactTraining/react-router#6570]
## Version
4.3

When preventing navigation with `Prompt` a custom message has to be provided, and it does a great job preventing `push` style navigation. 

```ts
<Prompt 
    when={this.shouldBlockNavigation()} 
    message="Changes that you made may not be saved." 
/>
```

It looks like a normal prompt:

<img width="461" alt="screen shot 2019-02-01 at 10 16 35" src="https://user-images.githubusercontent.com/3879181/52117015-930ad580-260a-11e9-85e0-e99baf92924d.png">

However this doesn't notify the user when refreshing the page or simply typing in a different URL. To prevent this, I have to use a `window.onbeforeunload` callback:

```ts
componentDidUpdate() {
  //...
  window.onbeforeunload = this.shouldBlockNavigation() ? alwaysTrue : undefined
}
```

<img width="473" alt="screen shot 2019-02-01 at 10 16 48" src="https://user-images.githubusercontent.com/3879181/52117165-f85ec680-260a-11e9-821f-0e294a2464ac.png">

**Shouldn't the `Prompt` fall back to the default dialog, in case no message is provided? Is it even possible? The 2 different behaviour can be quite confusing for users (without why it happens).**

**Comment by timdorr** [comment]
#4372
