### ISSUE TITLE
History in location.search (makes auxiliary routing possible)

### ISSUE THREAD

**Issue by ondrejpar** [ReactTraining/react-router#6574]
Hi, could there be a history object that would store path in a named query string parameter (I mean, location.search)?

My use case: I'm building a page with several independent sections and I want to use routing in each of them, independently. Now I can have URLs like these:
/app/news/page/12
/app/photos/gallery/3/photo/5

But I'd like to have something like this:
/app?news=page/3&photos=gallery/3/photo/5

Would something like this be feasible?

**Comment by timdorr** [comment]
No, we don't do query string processing. You would have to build that yourself.
