### ISSUE TITLE
4.4 beta 6 - withRouter() causes subsequent <Route>-Renderings to fail.

### ISSUE THREAD

**Issue by MischkowskyM** [ReactTraining/react-router#6581]
## Version

* react-router: 4.4.0-beta.6
* react-router-dom: 4.4.0-beta.6
* react-dom: 16.7.0
* react: 16.7.0

## Test Case

https://codesandbox.io/s/k2ll7nroqv

## Steps to reproduce

Wrapping any component that renders a ```<Route/>``` with ```withRouter()``` will cause an invariant violation:

> `Invariant failed: You should not use <Route> outside a <Router>`

Minimal example:

```js
const export SubRoute() => { // using this export works
    return <Route component={DummyComponent} />
}

export default withRouter(SubRoute); // using this export fails.
```

## Expected Behavior

The ```<Route/>``` should work regardless of whether or not it's parent is wrapped with ```withRouter```.

This is sometimes needed where access to the current match object is needed for proper routing - like this: ```<Route to={`${this.props.match.url}\new} />```.

## Actual Behavior

Route throws an invariant violation.

**Comment by MischkowskyM** [comment]
It seems like I missread the error message and stacktrace. From what I can tell, withRouter() itself fails, not the subsequent <Route/>. 

After poking around in the code, I found the cause:  Importing withRouter from "react-router" instead of "react-router-dom".  That is quite unfortunate, as the documentation / examples for 4.3 indicate one should import withRouter from the "react-router" package. As seen here:

https://reacttraining.com/react-router/web/api/withRouter 

Meaning one has to alias the existing imports or change all occurances. I'd consider this a breaking change.

**Comment by pshrmn** [comment]
There are two ways I was able to get your sandbox working:

1. Move the `withRouter` import:

```js
import { withRouter } from "react-router-dom";
```

2. Remove the `react-router` dependency

---

It feels like a bug in CodeSandbox's module loading (cc @CompuIves). The reason for the error is that your application has two instances of React Router's context: one from the `react-router` dependency and one from `react-router-dom`'s `react-router` dependency. Those _should_ be the same thing (if I download and run it locally, there are no issues), which is why I think that it is a bug.

**Comment by MischkowskyM** [comment]
@pshrmn This is not exclusive to codesandbox. I stumbled accross this issue in a normal application too.

Using npm 6.5.0, webpack 4.29.0, and Babel 7.

Did you use yarn to try the reproduction locally?

**Comment by pshrmn** [comment]
I've tried installing its deps with both yarn and npm and both worked.

**Comment by CompuIves** [comment]
Can confirm that there's a duplicate version. Looking into it now!

**Comment by CompuIves** [comment]
Fixed with https://github.com/codesandbox/dependency-packager/commit/20033fd31afb7e93ec5dd49a4c404eeaa34ef4b8. It may take a while to propagate since we have pretty strong caching on the dependencies.

**Comment by pshrmn** [comment]
Nice. Thanks Ives!.
