### ISSUE TITLE
Getting redirected on reload in Mozilla Firefox

### ISSUE THREAD

**Issue by HonzsSedlomn** [ReactTraining/react-router#6582]
## Version

**4.3.1**
## Steps to reproduce
1. Have an API
2. Redirect user with Link to GitLab OAuth login
3. Redirect back with access token from GitLab
4. Go to any protected route
5. Refresh page
## Expected Behavior
I expect that if I reload page, I'll stay on that page.
## Actual Behavior
 For example, I'm logged and on route /projects. If I reload page, I get redirected back to /gitlab/oauth?token=....
I was looking for any type of bug and found nothing. **This is happening only in Mozilla Firefox Dev/Stable even in incognito mode.**

**Comment by timdorr** [comment]
Can you provide your code or an example of this issue on Codesandbox?

**Comment by HonzsSedlomn** [comment]
Okay, so the problem was with *Redirect* component. If you redirect someone from some url and then user refresh page, it takes him one page back because *Redirect* does not implicitly push url to history. At least this is hapenning in Firefox.

**Comment by timdorr** [comment]
Perhaps FF has a delay to when it commits a history.push to the actual history, and if the page disappears before it has a chance to do that commit, it's dropped. Just a theory. Try a setTimeout wrapped around your redirection to give it enough time to commit the entry.

Unfortunately, if this is FF's behavior, it doesn't appear to be following the spec. We can't really do anything about that on our end.
