### ISSUE TITLE
Custom path parameters bug in 4.4.0-beta.6

### ISSUE THREAD

**Issue by daarxwalker** [ReactTraining/react-router#6583]
## Version 

4.4.0-beta.6

## Test Case
My app si too much big for codepen or something, i ll try reproduce:
Route in Suspense and Switch, Category component using React.lazy import
```
<Route
	path={getCategoryRoute()}
	render={(props) => <Category {...props} menuKey='categories' />}
	cached={true}
/>
```
And i have service this service to create params:
```
export const getCategoryRoute = () => {
	const params = history.location.pathname.split(PARAMS_DIVIDER).filter(item => item.length > 0).slice(1)
	const pageSeparatorIndex = params.indexOf(KEY_PAGE)
	const sortSeparatorIndex = params.indexOf(KEY_SORT)
	const categories = params.splice(0, pageSeparatorIndex)
	const categoriesLength = categories.length
	let i = 0
	let url = ''

	// Create levels of categories
	for ( ; i < categoriesLength; i++) {
		url += `:${KEY_NAME}${i}/`
	}

	// Create page
	if (pageSeparatorIndex > 0) url += `${KEY_PAGE}/:${KEY_PAGE}`

	// Create sort
	if (sortSeparatorIndex > 0) url += `${KEY_SORT}/:${KEY_SORT}`

	return `/${KEY_CATEGORY}/${url}`
}
```
## Steps to reproduce
When I change route to Category, there's no params, just /category/
But if I reload this URL, all working fine.

## Expected Behavior
There have to be params, because with version 4.3.1 all working fine, except error: Failed prop type: Invalid prop `component` of type `object` supplied to `Route`, expected `function`. It was reason why I switched to beta version.

## Actual Behavior
Not working, but in version 4.3.1, it's ok.

Hope I reproduced good. GL in good work!

**Comment by Grantlyk** [comment]
@daarxwalker Can you make a smaller version in codepen that still reproduces the issue? It doesn't need to be your whole app in the codepen, just something so that we can reproduce it and fix this bug

**Comment by mjackson** [comment]
Thanks for following up here, @Grantlyk. Closing this one as stale. If @daarxwalker can provide a repro, we'll look into it.
