### ISSUE TITLE
import error: 'react-router' does not contain a default export (imported as 'useRouterHistory').

### ISSUE THREAD

**Issue by josedaudi** [ReactTraining/react-router#6584]
I am trying to import useRouterHistory i end up with the error, **import error: 'react-router' does not contain a default export (imported as 'useRouterHistory').** is there a fix for this.

## Version
4.3.1

**Comment by TrySound** [comment]
There is no such api. Where did you find it?
![image](https://user-images.githubusercontent.com/5635476/52910194-05371780-32a5-11e9-82c2-e48469935a0e.png)
