### ISSUE TITLE
[Safari (iOS)] - Prompt does prevent the browser to go back 

### ISSUE THREAD

**Issue by freeboarder42** [ReactTraining/react-router#6585]
## Version

4.3.1

## Test Case

https://github.com/freeboarder42/react-router-safari-prompt-bug-demo

## Steps to reproduce

- Create a simple React app with two components besides App.jsx (Home.jsx, ComponentWithPrompt.jsx)
- Create routings to `Home` and `ComponentWithPrompt` in App.jsx
- Place a link to `ComponentWithPrompt` on `Home`
- Place a link to `Home` on `ComponentWithPrompt`
- Place a `Prompt` on `ComponentWithPrompt` with `when={true}` and `message="Really navigate away"`
- Run the app in Safari on iOS (12)
- Use the link to `ComponentWithPrompt` to go to `ComponentWithPrompt`
- Tap the browser's back button
- Tap the `Home` link

## Expected Behavior

The browser should display the prompt and go back to the `Home` component if the user confirms the navigation.

## Actual Behavior

The browser does not display the prompt and does not go back to the `Home` component. After this, even the `Home` link does not work anymore.

**Comment by timdorr** [comment]
This is actually caused by the history library. I would open up an issue over there: https://github.com/ReactTraining/history
