### ISSUE TITLE
React Router website newsletter signup form submitted by default

### ISSUE THREAD

**Issue by Grantlyk** [ReactTraining/react-router#6587]
## Version
I'm viewing your website

## Steps to reproduce
1. go to the react router website; https://reacttraining.com/react-router/
2. scroll down and see that the email signup form has already been submitted

## Expected Behavior
I would expect that when I first visit the website the form has the correct default state so that the capture looks more like this;
![image](https://user-images.githubusercontent.com/3958482/53013898-b8874400-343e-11e9-9a1a-3f0932459ef5.png)

## Actual Behavior
The website shows the newsletter form as if it has already been submitted and you have captured our email
![image](https://user-images.githubusercontent.com/3958482/53013594-12d3d500-343e-11e9-9896-bdf25085d26f.png)

## Investigation
I tested this on Chrome and Firefox on two devices, one mobile and one laptop. I also investigated the codebase to see if this was an obvious error, everything seems fine when the site is running locally, either the website is an older version than what's in github or there's a bug here, would be good if someone else could confirm this is happening to them too

**Comment by justsml** [comment]
If it's been fixed running `master` locally, it might be related to #6595
