### ISSUE TITLE
React Router Redux link not working @ reacttraining.com

### ISSUE THREAD

**Issue by fila90** [ReactTraining/react-router#6589]
## Test Case

https://reacttraining.com/react-router/web/guides/redux-integration

## Steps to reproduce

Go to site and click `React Router Redux` at the end of text

## Expected Behavior

Redirect to working page or remove it completely as it's deprecated 

## Actual Behavior

Redirects to 404 GitHub page

not sure if this is the best place to report this bug, but anyway, there it is.
Cheers :tada:

**Comment by fila90** [comment]
also `<Route> Documentation` in [Basic Components](https://reacttraining.com/web/api/Route) is broken.

**Comment by timdorr** [comment]
Can you submit a PR?

**Comment by fila90** [comment]
I could, but I have no idea where to redirect the URLs, where are new docs?

**Comment by timdorr** [comment]
https://github.com/supasate/connected-react-router is the new thing.

**Comment by pshrmn** [comment]
[That guide](https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/guides/redux.md) has already been updated. Not sure about the others.

**Comment by timdorr** [comment]
Ah, we need to merge master into the website branch in that case. For this issue, it looks like we're already fixed.
