### ISSUE TITLE
Validation.Required.URL.Redirect reported in AppScan

### ISSUE THREAD

**Issue by ilovepumpkin** [ReactTraining/react-router#6591]
I am using react-router-dom 4.3.1 and when I use IBM Security AppScan Source for Analysis to scan my project, I get a High issue "Validation.Required.URL.Redirect"

![image](https://user-images.githubusercontent.com/11310645/53174979-027e4e80-3626-11e9-809e-9fcb0724f263.png)

![image](https://user-images.githubusercontent.com/11310645/53174750-8257e900-3625-11e9-9a17-5629c3046516.png)

The related code is below
`
 var replaceHashPath = function replaceHashPath(path) {
    var hashIndex = window.location.href.indexOf('#');
    window.location.replace(window.location.href.slice(0, hashIndex >= 0 ? hashIndex : 0) + '#' + path);
  };
`

Based on the description of the AppScan tool, to avoid this issue is reported, my understanding is that we only need to change the code as below.
`
 var replaceHashPath = function replaceHashPath(path) {
    var hashIndex = window.location.href.indexOf('#');
    var newPath = window.location.href.slice(0, hashIndex >= 0 ? hashIndex : 0) + '#' + path;
    window.location.replace(newPath);
  };
`
Currently my probject keeps reporting this issue for several releases, so I really need to resolve this. Please let me know if this little change could be accepted. If needed, I can create a PR. Please review and let me know. Thanks!

**Comment by pshrmn** [comment]
The code that you refer to comes from the `history` package, so it would be more relevant to discuss this [in the `history` repo](https://github.com/ReactTraining/history).

**Comment by ilovepumpkin** [comment]
oh, right, sorry, thanks!
