### ISSUE TITLE
Odd issues with <Link> and <NavLink> updating location but not DOM

### ISSUE THREAD

**Issue by kmcaloon** [ReactTraining/react-router#6594]
## Version

react@16.8.2
react-router@4.3.1
react-router-dom@4.3.1

## Problem

Hey, so running into a very strange issue that has me stumped. I created a quick video to run through the problem, but basically I refactored my app with the latest CRA, converted classes to functional components using hooks, updated some other packages (see package.json below), and now in most places `<Link>` and `<NavLink>` are updating the history but the app is not rerendering the correct routes. All routes render correctly on initial load, but most subsequent links broken.

What adds to the mystery here is that all `<NavLinks>` within a navigation menu using antd's `<Menu>` component are working. The only difference between this and my other components that I can see is that it is a class-based component vs. functional.  Here is a link to quick video, hopefully it is helpful.

https://drive.google.com/file/d/1KGl7XtpbmePXAaQ11Eew9qGarINIn4FQ/view

## package.json

```
{
  "name": "hi-there",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@material-ui/core": "^3.9.2",
    "@sentry/browser": "^4.5.3",
    "antd": "^3.13.2",
    "await-to-js": "^2.1.1",
    "axios": "^0.18.0",
    "bootstrap": "^4.3.0",
    "classnames": "^2.2.6",
    "craco-preact": "^1.1.0",
    "date-fns": "^1.30.1",
    "directory-named-webpack-plugin": "^4.0.0",
    "js-cookie": "^2.2.0",
    "material-ui": "^0.20.2",
    "node-sass": "^4.11.0",
    "rc-queue-anim": "^1.6.11",
    "react": "^16.8.1",
    "react-cache": "^2.0.0-alpha.1",
    "react-dom": "^16.8.1",
    "react-helmet": "^5.2.0",
    "react-infinite-scroller": "^1.2.4",
    "react-loadable": "^5.5.0",
    "react-router": "^4.3.1",
    "react-router-dom": "^4.3.1",
    "react-scripts": "^2.1.5",
    "react-use": "^5.3.0",
    "reactstrap": "^7.1.0",
    "sass-rem": "^2.0.1",
    "tiny-slider": "^2.9.1",
    "webpack-bundle-analyzer": "^3.0.3",
    "webpackbar": "^3.1.5"
  },
  "scripts": {
    "start": "nodemon -w craco.config.js -w ./src/lib/ant-theme.less --exec 'craco start'",
    "pilots-dev": "REACT_APP_APP=pilots nodemon -w craco.config.js -w ./src/lib/ant-theme.less --exec 'craco start'",
    "start-live-api": "REACT_APP_API=null craco start",
    "build": "craco build",
    "test": "craco test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": [
    ">0.2%",
    "not dead",
    "not ie <= 11",
    "not op_mini all"
  ],
  "devDependencies": {
    "@babel/plugin-proposal-class-properties": "^7.3.0",
    "@babel/plugin-proposal-decorators": "^7.3.0",
    "@craco/craco": "^3.4.1",
    "craco-antd": "^1.10.0",
    "nodemon": "^1.18.10"
  }
}

```

**Comment by timdorr** [comment]
It is likely an update blocking issue. Try using the 4.4 betas for now.

**Comment by kmcaloon** [comment]
Well that was easy. Working now, thanks
