### ISSUE TITLE
Add onKeyPress for Link component to respond Enter and Space by default for accessibility

### ISSUE THREAD

**Issue by Hongbo-Miao** [ReactTraining/react-router#6600]
## Version

react-router-dom: 4.3.1

## Test Case

https://codesandbox.io/s/24mwr7w1p

## Steps to reproduce

I am trying to add accessibility. After I use the package [reactjs/react-a11y](https://github.com/reactjs/react-a11y), it gives some warnings for Link (NavLink) component.

Open the codesandbox, and click refresh first (otherwise will show error), then click Home link, you will see error

> [react-a11y]: Link - You have an `onClick` handler but did not define an `onKeyDown`, `onKeyUp` or `onKeyPress` handler. Add it, and have the "Space" key do the same thing as an `onClick` handler. See 'https://www.w3.org/WAI/GL/wiki/Making_actions_keyboard_accessible_by_using_keyboard_event_handlers_with_WAI-ARIA_controls' for more info.

 
![image](https://user-images.githubusercontent.com/3375461/53369467-22509380-3900-11e9-9751-ae50efa4f28b.png)

I know developer can always add `onKeyPress` by themselves.
But I am thinking does it make sense to add `onKeyPress` in `Link` component to handle **Enter** (default behavior) keyboard by default? And if developer provides its own `onKeyPress`, let it overwrites the default one.

If it makes sense, I can create a pull request.

**Comment by Sam-son** [comment]
Adding to this- `Link` has support for `Enter` keypresses but does not handle space, which goes against the [ARIA guidelines for buttons](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/button_role#Keyboard_interactions).

**Comment by StringEpsilon** [comment]
Oh, this is still open.

@Hongbo-Miao: 

I don't think this issue is going to be addressed. To mirror the comment I got on my PR:

> Hey StringEpsilon, thanks for the PR. However, I do not believe that this is necessary because an anchor already works with the Enter key. The react-a11y warning seems more geared towards non-accessible elements. If the link has an onClick prop, it will be called when the user clicks navigates using the Enter key.

You can also pass a custom onKeyPress handler through Link to the underlying anchor, if you should need to:

```jsx
<Link onKeyPress={() => { /* do accessible stuff */ }/> 
<NavLink onKeyPress={() => { /* do accessible stuff */ }/> 
```

NavLink and Link both pass down all props not specific to them down to the rendered anchor element.
