### ISSUE TITLE
No chunk generated when using react-loadable in Route render prop

### ISSUE THREAD

**Issue by lauterry** [ReactTraining/react-router#6602]
## Version

react-router 4.3.1
webpack 2.3.2
react-loadable 5.5.0

## Test Case

Given the following route, using `Loadable` from `react-loadable` 

```
<Route
	path="/listing"
	render={props => {
                 /* Some code using props */

		const ListingContainer = Loadable({
			loader: () => import(/*webpackChunkName: "listing"*/ "app/pages/Listing/ListingContainer"),
			loading: () => false,
		});

		return <ListingContainer {...props} />;
}}
/>
```

I didn't manage to generate a separate chunk when using the render prop of `Route`.

However, the following code works fine and generates the expected chunk when I use the `component` prop.

```
<Route
        path="/product"
	component={Loadable({
		loader: () => import(/*webpackChunkName: "listing"*/ "app/pages/Product/ProductContainer"),
		loading: () => false,
	});}
/>
```

## Steps to reproduce

Use `Loadable` from `react-loadable` in `Route` `render` props to lazy load a route.

## Expected Behavior

I expected a separate chunk to be generated

## Actual Behavior

No chunk is generated.

Best regards

**Comment by timdorr** [comment]
This isn't a problem with this library. You should consult the Webpack support resources.
