### ISSUE TITLE
Add formatRoute function to react-router-config

### ISSUE THREAD

**Issue by sapkra** [ReactTraining/react-router#6603]
I'm using the `formatRoute` function of [react-router-named-routes](https://github.com/adamziel/react-router-named-routes) for quite a while and this function makes totally sense and I wish to have it in the official package (`react-router-config` maybe).

To use this function the right way the routes `Route Configuration Shape` needs to be in an object instead of an array so that you can reference a specific route path in a component.
Because this package is still in alpha it should be not a big deal to change the API again.

```jsx
import { routesConfig } from 'config/routes';

<Link
  to={
    formatRoute(routesConfig.app.routes.user.path, {
      userId: user.id,
    })
  }
/>
```

**Comment by timdorr** [comment]
We've already got that: https://github.com/ReactTraining/react-router/blob/a163b3ae57714563ffd4113e995220d4cd64bc25/packages/react-router/docs/api/generatePath.md

**Comment by sapkra** [comment]
Ah okay haven't seen it.
But there is still the problem with referencing one route path from the routes config.
