### ISSUE TITLE
reproduce issue #6520

### ISSUE THREAD

**Issue by shufengwu5946** [ReactTraining/react-router#6604]
## Version

**v 4.3.1**

## Steps to reproduce

In react-router/website/modules/examples/Recursive.js  Line 12
```javascript
const find = id => PEEPS.find(p => p.id == id);
```

why use "==" instead of "===" ? 

if I use "===", issue #6520 (closed) will reproduce.

Thank you.

**Comment by timdorr** [comment]
Type coercion. A string of `"123"` is not `===` to `123`, but it is `==`.
