### ISSUE TITLE
Does react router support fully hooks?

### ISSUE THREAD

**Issue by musti-91** [ReactTraining/react-router#6612]
I have a project where I able to use **Hooks** in it,  combined with react-router.

One of my containers has **useReducer()**  hook In it, and the Error that I got:

> Hooks can only be called inside the body of a function component. (https://fb.me/react-invalid-hook-call)

When I comment the line with useReducer(reducer, initialState)
it will work.
```typescript 
const AnyContainer: SFC<iOwnProps> = props => {
  const [state, dispatch] = useReducer(reducer, INITIAL_STATE)
  return(
     <div>AnyContainer</div>
    )
  }

```
So I don't know if react-router supported hooks or not?

- react-router: ^4.3.1
- react: ^16.8.3

**Comment by pshrmn** [comment]
React Router does not currently provide any routing hooks, but there is no reason that it should interfere with using hooks. You most likely have one of the three reasons described in the linked warning.

**Comment by musti-91** [comment]
I'm aware of these reasons already
