### ISSUE TITLE
withRouter wrapped component cannot access params when used in NavLink

### ISSUE THREAD

**Issue by zfletch** [ReactTraining/react-router#6613]
I've searched the related issues and I didn't find this exact bug. Apologies if I missed it.

The issue is that when I try to use a component wrapped with `withRouter` inside a `NavLink`, I don't get the correct `match` prop. Weirdly, this is only an issue with `NavLink`. Everything works correctly within a regular `Link`. 

## Version

React Router Dom 4.3.1

## Test Case

https://gist.github.com/zfletch/28bbaa330756607d40e4c2acf7d980b2

(Uncomment the `NavLink` code and click on the `person 2` to see it break).

## Steps to reproduce

1. Create a component using `withRouter`
2. Use `this.props.match.params` in that component
3. Place that component in a `<NavLink>` tag

## Expected Behavior

It should work like in any other component (including `<Link>`). The `match` and `params` should be present.

## Actual Behavior

`match` is `null` in some cases and `{}` in other cases. This causes incorrect behavior and errors when one of these components is used inside `<NavLink>`.

**Comment by timdorr** [comment]
`withRouter` wraps your component in a Route, so it overrides any Route context above it. NavLink uses a Route as well. I'm not sure of a fix we could do on our end, but the simpler solution is to just remove the `withRouter` wrapper. It's not needed on that component since the NavLink is using a Route anyways.

**Comment by zfletch** [comment]
Thanks for the quick response!

> I'm not sure of a fix we could do on our end, but the simpler solution is to just remove the `withRouter` wrapper. 

I'm not sure I understand this suggestion. If I remove the `withRouter` wrapper and use the `Text` component directly, then the component doesn't receive the `match` prop whether or not it's used inside a `<NavLink>`.


For some context around why this is an issue and how I ran into it, the real-world use case is for some internationalization code I'm writing. The code works by with `withRouter` and looking at the `match.params.locale` to render different text.

```react
<div>
  <div>
    <I18n t="information" />
  </div>
  <div>
    <I18n t="description" />
  </div>
  <Link to="/about">
    <I18n t="about" />
  </Link>
</div>
```

The code was working as expected until I turned the `Link` into `NavLink`:

```react
<NavLink to="/about">
  <I18n t="about" />
</NavLink>
```

When I did this, `match.params.locale` was no longer passed in to the wrapped component (even though it works fine with regular `Link`(. For my particular use case, the workaround I used was writing my own `NavLink` component from scratch, but I still think this behavior is a bug. I would expect wrapped components to work the same in `NavLink` and `Link`.

**Comment by pshrmn** [comment]
@zfletch can you verify if the issue still exists using the `4.4` beta?

**Comment by zfletch** [comment]
I tried it with `4.4.0-beta.7` and the issue still occurs.

I've also created a repository with the code from my gist [here](https://github.com/zfletch/react-router-navlink-example).

**Comment by austin-garrard** [comment]
I am seeing something simliar, also on 4.3.1 and 4.4.0-beta.7. In the snippet below, the log will show that the location prop updates as expected, but not the match prop. Interestingly, the `exact` key seems to update correctly for the match prop, but nothing else.

```javascript
import React from 'react'
import { BrowserRouter, Route, Link, withRouter } from 'react-router-dom'

const Thing = withRouter(({ match, location }) => {
  console.log(match, location)
  return 'darn '
})

const Index = () => 'index'
const About = () => 'about'

export default () => (
  <BrowserRouter>
    <div>
      <Thing />
      <Link to='/'>LinkToIndex </Link>
      <Link to='/about'>LinkToAbout </Link>
      <Route path="/" exact component={Index} />
      <Route path="/about" component={About} />
    </div>
  </BrowserRouter>
)
```

**Comment by StringEpsilon** [comment]
There is quite a lot going on for such little code. I originally stumbled on this bit in ```Route```:

```js
const match = this.props.computedMatch
  ? this.props.computedMatch // <Switch> already computed the match for us
  : this.props.path
    ? matchPath(location.pathname, this.props)
    : context.match;
```

Here, match gets reassigned to ```matchPath(location.pathname, this.props)``` and is null afterwards for the rest of the chain.

The matchPath call looks like this:

```js
matchPath("/person/foo", { path: \\/person\\/1, exact: undefined, strict: undefined, location: undefined });
```

The culprit is NavLink. That component overwrites the path-prop of route with an escaped version of the "to"-prop (in this example "/person/1").  That re-assigned path-prop then gets passed down the chain and causes the last match provided by withRouter() to be null.

**Comment by StringEpsilon** [comment]
A fix would be to forgoe using the match provided by Route in NavLink and instead call matchPath() there directly.

Something like this: (Snippet)

```js
// NavLink render():
<Route
  location={location}
  children={({ location }) => {
    const match = location.pathname && escapedPath ?
      matchPath(location.pathname, { path: escapedPath, exact, strict}):
      null;
    const isActive = !!(isActiveProp
      ? isActiveProp(match, location)
      : match);
```

**Comment by MeiKatz** [comment]
I think there is currently a pending pr solving this problem: #6623
