### ISSUE TITLE
4.4.0-beta.7 Can't resolve create-react-context from react-router/esm

### ISSUE THREAD

**Issue by hally9k** [ReactTraining/react-router#6614]
## Version
4.4.0-beta.7

## Steps to reproduce
Import `react-router-dom` into a project using react@16.8.4 

## Expected Behavior
To compile successfully without the missing `create-react-context` dependency.

## Actual Behavior
Attempts to import `create-react-context` in `react-router/esm` but fails as it's not a dependency or a peer dependency.

_Note:_
Patched in the meantime by yarn adding  `create-react-context` as a direct dependency in my project.

**Comment by timdorr** [comment]
Something's up with your bundler. It's definitely a dependency of react-router: https://github.com/ReactTraining/react-router/blob/master/packages/react-router/package.json#L43
