### ISSUE TITLE
Forward and back buttons not working consistently

### ISSUE THREAD

**Issue by o-t-w** [ReactTraining/react-router#6616]
## Version

4.3.1

## Test Case

My project is so tiny and simple that _is_ a reduced test case already.
https://github.com/o-t-w/reonic

## Actual Behavior
The back button works inconsistently. The forward button doesn't work.

**Comment by timdorr** [comment]
My best guess is Ionic is interfering in some way. What happens if you remove their stuff from the app?

**Comment by o-t-w** [comment]
@timdorr It looks like you may be correct. I don't seem to experience the same issue when using a regular HTML select element so have filed a bug with Ionic.
