### ISSUE TITLE
React Redux Auth login and sidenav bar redirect

### ISSUE THREAD

**Issue by rjsajnani1** [ReactTraining/react-router#6617]
Hey guys i having some issues with redirection not sure where i'm going wrong. I have shared my stackoverflow link below. Any help is much appreciated thanks.

https://stackoverflow.com/questions/54994564/react-web-redux-auth-with-sidebar-view-after-login

**Comment by timdorr** [comment]
This is a bug tracker, not a support system. Thanks!
