### ISSUE TITLE
npm run build fails on windows machines

### ISSUE THREAD

**Issue by StringEpsilon** [ReactTraining/react-router#6622]
## Version

Latest master branch.

## Steps to reproduce

On any windows machine, run the following code:

```
git clone https://github.com/ReactTraining/react-router.git
cd react-router
npm ci
npm run build
```

## Expected Behavior

Build completes successfully and the output is the same as on Linux or macOS.

## Actual Behavior

Two problems:

1. The build exits in a failure as the size-snapshot plugin crashes: ```Error: ModuleNotFoundError: Module not found: Error: Can't resolve './MemoryRouter.js' in '/'```
2. The build output is unuseable / incomplete.

The problem seems to be the isBareModuleId() function in the rollup.config.js:

```js
function isBareModuleId(id) {
  return !id.startsWith(".") && !id.startsWith("/");
}
```

On windows, no module path ever starts with a leading slash. So the function returns ```false``` for every single module.

**Comment by StringEpsilon** [comment]
Changing the function to 
```js
function isBareModuleId(id) {
  return !id.startsWith(".") && !id.includes("react-router" /*package name*/);
}
```

seems to fix the problem for the npm packages. The website build still fails because the build-command isn't windows friendly:

```NODE_ENV=production webpack -p```

**Comment by timdorr** [comment]
We all use either macOS or Linux for building. We don't support building on Windows for now. If you want to make a PR to add it, we can take a look.

**Comment by StringEpsilon** [comment]
If you are open to fixing this, why not simply add the "help wanted" label instead of closing the issue?

Closing it makes it seem like you don't want to support building on windows. I mainly use Linux, so I'm not invested enough in this issue to make a PR.

**Comment by timdorr** [comment]
We don't want to support it. None of use Windows, so we can't.
