### ISSUE TITLE
how reg router file

### ISSUE THREAD

**Issue by khanhnam99** [ReactTraining/react-router#6625]
I want to url 👍 
https://github.com/demo-123.html
- with :
 +demo : is string
 +123 : is ID
 +html : is string

So how in this path?
<Route path="/" component={Demo} />

## Version

**Please replace this sentence with the React Router version that you are using.**

## Test Case

https://codesandbox.io/s/7zwjlm2j3q

**Comment by pshrmn** [comment]
React Router uses [`path-to-regexp`](https://github.com/pillarjs/path-to-regexp) for path matching, so you should check out its documentation for hints on how to write a particular path. You can also play around with my [route tester](https://pshrmn.github.io/route-tester/#/) to test paths.

**Comment by khanhnam99** [comment]
Thanks a lot,
