### ISSUE TITLE
There is no Context.Provider at the top of the Switch component

### ISSUE THREAD

**Issue by chnliquan** [ReactTraining/react-router#6626]
In the source code of the [<Switch>](https://github.com/ReactTraining/react-router/blob/master/packages/react-router/modules/Switch.js#L15 ), `<Context.Consumer>` is used. However, according to the usage of the document, the outer layer of this component is not repackaged, so the `context` should be empty, so the location and match are not available in the following Router？

**Comment by pshrmn** [comment]
The `<Router>` [renders a `<Context.Provider>](https://github.com/ReactTraining/react-router/blob/4736cfe01dc71b6fa69b76ab946b6205447c3faa/packages/react-router/modules/Router.js#L55).

**Comment by chnliquan** [comment]
@pshrmn I know that `<Router>` renders the` Provider`, but the outermost usage of the [Switch](https://reacttraining.com/react-router/web/api/Switch) according to the document does not wrap any components, including `<BrowserRouter>` `<Router>`

**Comment by pshrmn** [comment]
Are you referring to this?

```jsx
import { Switch, Route } from 'react-router'

<Switch>
  <Route exact path="/" component={Home}/>
  <Route path="/about" component={About}/>
  <Route path="/:user" component={User}/>
  <Route component={NoMatch}/>
</Switch>
```

None of the code snippets are "real". A real application would have to create the elements inside of a function (or a `ReactDOM.render` call); we show the JSX to demo how the component is used, not where.
