### ISSUE TITLE
Trie based routing instead of Regex based routing

### ISSUE THREAD

**Issue by silver-xu** [ReactTraining/react-router#6627]
React router is currently using regex based routing to loop through the path table. 

```matchPath.js
function matchPath(pathname, options = {}) {
  if (typeof options === "string") options = { path: options };

  const { path, exact = false, strict = false, sensitive = false } = options;

  const paths = [].concat(path);

  return paths.reduce((matched, path) => {
    if (matched) return matched;
    const { regexp, keys } = compilePath(path, {
      end: exact,
      strict,
      sensitive
    });
    const match = regexp.exec(pathname);

    if (!match) return null;

    const [url, ...values] = match;
    const isExact = pathname === url;

    if (exact && !isExact) return null;

    return {
      path, // the path used to match
      url: path === "/" && url === "" ? "/" : url, // the matched portion of the URL
      isExact, // whether or not we matched exactly
      params: keys.reduce((memo, key, index) => {
        memo[key.name] = values[index];
        return memo;
      }, {})
    };
  }, null);
```

Regex based routing within a loop could have computational complexity of up to O(n^2), it is relatively inefficient compared to trie based routing (worst O(n)). Since React router is utilising path-to-regexp module to convert paths, I am proposing to use route-trie module instead to fill the same shoe.

```
trie.define('/:type/:id([a-z0-9]{6}')
var match = trie.match('/post')
match = trie.match('/post/abc123')
```

This should help to improve routing performance of SPAs with relatively large number of path patterns.

If you'd like, I am happy to make a PR for this.

**Comment by timdorr** [comment]
This generally isn't a problem because it only comes into play when switching routes. And when you're doing so, there are much more expensive operations in play around rendering the new DOM state. Regexps are compiled down to native code in Chrome (via Irregexp), so running them is quite fast.

I don't see any reason to lose the benefits and features of path-to-regexp for a premature optimization.

**Comment by silver-xu** [comment]
Fair enough.
