### ISSUE TITLE
@mmahalwy What I was describing was creating your own equivalent of `browserHistory` that you can import. Previously the exported routers all created a history instance for you and there wasn't a way to import that instance. With the `<Router>` component taking a `history` prop, you can create a history instance in a module and import it throughout your project so that you don't have to mess around with props to access it.

### ISSUE THREAD

**Issue by landstrider** [ReactTraining/react-router#6628]
@mmahalwy What I was describing was creating your own equivalent of `browserHistory` that you can import. Previously the exported routers all created a history instance for you and there wasn't a way to import that instance. With the `<Router>` component taking a `history` prop, you can create a history instance in a module and import it throughout your project so that you don't have to mess around with props to access it.

```js
// history.js
import { createBrowserHistory } from 'history'

// configure, create, and export the project's history instance
export default createBrowserHistory()
```

```js
// App.js
import history from './history'

const App = () => (
  <Router history={history}>
    <div>...</div>
  </Router>
)
```

```js
import history from './history'

export function* signin(api, { payload }) {
  const response = yield call(api.auth.signin, payload);

  if (response.ok) {
    yield put(AuthActions.signinSuccess({ user: response.data.data }));
    yield call(history.push, '/dashboard');
```

_Originally posted by @pshrmn in https://github.com/ReactTraining/react-router/issues/3972#issuecomment-264805667_

**Comment by landstrider** [comment]
@pshrmn `yield call(history.push, '/dashboard'` is blocking call. If `signin` generator function is invoked once, it is never invoked again.

**Comment by pshrmn** [comment]
I'm not sure the point of this issue is. You're quoting me from a 2+ year old issue to let me know that some pseudo-code that I copied from someone else's comment doesn't work?

**Comment by mmahalwy** [comment]
how did i get looped into this? haha
