### ISSUE TITLE
Proposal: Add `scope` prop for <Link> to avoid "use <Link> outside <Router>" error

### ISSUE THREAD

**Issue by acrazing** [ReactTraining/react-router#6629]
Sometimes, a project maybe contains two or more `SPA`, and we want to reuse some components across those SPA. Unfortunately, we will meet some problems if use some components contains `<Link>`:

1. if we use it outside `Router`, will get an error like `"use <Link> outside <Router>"`.
2. if we use it in different `SPA`(or `<Router>`), the page went blank.

So, we hope to add a `scope` property for `<Link>` component to avoid it:

1. `<Link>` should expose a static API to set current page's scope:
  ```ts
  export class Link extends PureComponent {
    static scope: any = null
    static setScope(scope: any) {
      Link.scope = scope;
    }
    // ...
  }
  ```
2. `<Link>` accepts a required props `scope`, and if `this.props.scope === Link.scope`, will render it as original form, else will fallback to render as a pure html `a` element.
  ```ts
  export class Link extends PureComponent {
    static scope: any = null
    static setScope(scope: any) {
      Link.scope = scope;
    }
    // ...
    render() {
      if(this.props.scope !== Link.scope) {
        const { to, scope, children, ...props } = this.props;
        return <a href={toString(to)} {...props}>{children}</a>
      }
      // do the original staff
  }
  ```
3. any page uses `<Router>` must call `Link.setScope` method to indicate current page's `scope`.
4. any components use `<Link>` must pass `scope` to indicate the target url's `scope`.

**Comment by timdorr** [comment]
Setting it statically would break a lot of other use cases. You simply should not use a Link component if you don't intend to use it with a router. Just use a normal `a`.
