### ISSUE TITLE
upgrade error

### ISSUE THREAD

**Issue by lhkg1988** [ReactTraining/react-router#6633]
<img width="676" alt="企业微信截图_15527310923731" src="https://user-images.githubusercontent.com/7578173/54473753-06f9e980-4817-11e9-81ed-a3129b204a3c.png">

**Comment by timdorr** [comment]
I can't reproduce this one. You should be using a relatively modern version of npm or yarn to install your dependencies. It doesn't appear to be an issue with our library.

**Comment by lhkg1988** [comment]
Thanks
