### ISSUE TITLE
Clarification on update blocking from docs

### ISSUE THREAD

**Issue by giorgi-m** [ReactTraining/react-router#6635]
I am asking this here hoping to get feedback with someone well familiar with router.
Here: https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/guides/blocked-updates.md#dealing-with-update-blocking, you first say:

> By default, the current location is passed implicitly to components using React's context model. **When the location changes, those components should re-render** using the new location object from the context.

Then here

> When the location changes, the `<UpdateBlocker>` does not detect any prop or state changes, so its child components will not be re-rendered.

My question is why the `NavLink `in that code can't rerender **on its own**? The docs seem to suggest that in order for the `NavLink `to rerender its parent `<UpdateBlocker>` must rerender, right? Why? (AFAIK in react for child component to rerender it is not required for parent component to rerender too, or am I wrong?)

**Comment by pshrmn** [comment]
The update blocking docs have to do with the old context, where blocking an update meant that the entire descendant tree would not re-render (unless you built in your own subscription system like Redux).

The new context avoids blocking issues, which `4.4` uses, makes this documentation redundant (it will probably be removed soon).

**Comment by giorgi-m** [comment]
Ah, I see. IMHO this refers to same thing: https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/guides/redux.md#blocked-updates.
