### ISSUE TITLE
Make prop-types and @babel/runtime as peerDependencies

### ISSUE THREAD

**Issue by retyui** [ReactTraining/react-router#6640]
The new version 4.4.0 of react-router-dom add new dependencies

https://github.com/ReactTraining/react-router/blob/eef79d529efb037d84d99efdedef2baa0941c8c1/packages/react-router-dom/package.json#L46-L49

Why you didn't use  `peerDependencies` for:

- prop-types
- @babel/runtime

**Comment by timdorr** [comment]
Because they are hard dependencies of the package. We cannot rely on peerdeps, which won't install them automatically.
