### ISSUE TITLE
About React Router 4.3.1 and the "Support for the latter will be removed in the next major release." warning

### ISSUE THREAD

**Issue by PerryM123** [ReactTraining/react-router#6647]
Question! 

I was getting the same `Support for the latter will be removed in the next major release.`
warnings as described in https://github.com/ReactTraining/react-router/issues/6630

I'm also using react router dom 4.3.1 and was getting this same warning the other morning but after many hours of trying to debug it, the warning seems to have disappeared.

I'm wondering was it because I deleted my node modules with yarn.lock and ran yarn install.

Did anyone run into this as well or is this just coincidence?

Sorry if this is the wrong place to ask.

Thank you.

**Comment by timdorr** [comment]
This was added in 4.4/5.0, so you had things installed incorrectly if you were seeing it under 4.3.1.

**Comment by timdorr** [comment]
There was a temporary publishing problem yesterday. That's been fixed via publishing 4.4 as 5.0. You won't see that message again.

**Comment by PerryM123** [comment]
@timdorr 
Got it! Thank you for the prompt reply!
