### ISSUE TITLE
Can't resolve '@babel/runtime/helpers/esm/extends'

### ISSUE THREAD

**Issue by quentincrinon** [ReactTraining/react-router#6648]
## Version

`"version": "4.4.0"`

## Issue

When I try to launch my app I get these errors (My app is in a monorepo): 

`../node_modules/history/esm/history.js
Module not found: Can't resolve '@babel/runtime/helpers/esm/extends' in '/Users/quentincrinon/Desktop/work/platform_frontend/node_modules/history/esm`

![Screenshot 2019-03-19 at 14 50 05](https://user-images.githubusercontent.com/15238155/54616130-267f5500-4a57-11e9-9bdf-bd972b864f38.png)

I tried to use the last released version (5.0.0) but yarn can't find it so I have to stay with the 4.4.0
In my package.json :
```   
 "react-router": "^5.0.0",
 "react-router-dom": "^5.0.0",
```

Has anyone already had these errors ?

**Comment by timdorr** [comment]
This isn't an issue with the library. I'd try removing your node_modules folder and reinstalling.

**Comment by danmolitor** [comment]
@quentincrinon I'm having the same issue. Did you ever figure out what the problem was?

**Comment by fgiarritiello** [comment]
Same problem here. Any help?

**Comment by quentincrinon** [comment]
I have upgraded my react and react-scripts versions to the latest, and it has solved the problem.
