### ISSUE TITLE
Warning: Please use `require("react-router").Router` instead of `require("react-router/Router")`. Support for the latter will be removed in the next major release.

### ISSUE THREAD

**Issue by BaumVitaly** [ReactTraining/react-router#6650]
## 4.3.1

But i'm not using `react-router`. I'm using `import {withRouter} from 'react-router-dom'`

Also i have errors:

`Uncaught Invariant Violation: You should not use <Route> or withRouter() outside a <Router>`

But all my components works inside BrowserRouter from react-router-dom. And all was working fine 2 days ago and yesterday all broke

**Comment by pshrmn** [comment]
Please try a fresh installation. There was a release (`4.4`) that caused a number of issues for people; that was unpublished and re-published as React Router `v5.0.0`. The warning message comes from `4.4`/`5`, but if you're on `4.3.1`, you should not see it.

**Comment by BaumVitaly** [comment]
@pshrmn 

How to fix it:

yarn list v1.15.2
warning Filtering by arguments is deprecated. Please use the pattern option instead.
├─ react-router-dom@4.3.1
│  └─ react-router@4.4.0 // it need to be 4.3.1
└─ react-router@4.3.1
Done in 0.98s.

**Comment by BaumVitaly** [comment]
I'm using yarn install and in my package json i have this:

    "react-router": "4.3.1",
    "react-router-dom": "4.3.1",

but inside react-router-dom i have react-router v4.4.0

**Comment by TomiS** [comment]
I had to add resolution field in yarn to get rid of the errors:
```
  "resolutions": {
    "react-router-dom/react-router": "4.3.1"
  }
```
Having only `react-router-dom` as a dependency pointing at `4.3.1` will resolve to having `react-router` at `4.4.0`. Having both dependencies like in @BaumVitaly's example will introduce duplicate dependency of `react-router` `4.4.0` and `4.3.1`.

**Comment by timdorr** [comment]
Yarn's cache still has 4.4.0 in it. I don't know of a way to get it removed from the cache. For now, the solution is to use npm or install react-router explicitly.
