### ISSUE TITLE
handleClick on <Link /> ref no longer works with 5.0.0

### ISSUE THREAD

**Issue by cherouvim** [ReactTraining/react-router#6653]
I've been using a ref on a `<Link />` so I can trigger it via code but upgrading from 4.3.0 to 5.0.0 breaks this behavior. Calling `handleClick` on the `React.createRef()` which was assigned to a Link via: `<Link ref={...} />` now throws an error.

To reproduce visit https://codesandbox.io/s/l5o9l1j8l7 (uses 4.3.0 which works) and click on button. The URL will move to "/foo" and "link pressed" will be logged in console. If you upgrade to 5.0.0 then clicking on the button will throw:
```
Uncaught TypeError: Cannot read property 'push' of undefined
    at Link.handleClick (react-router-dom.js:174)
    at onClick (index.js? [sm]:23)
    at HTMLUnknownElement.callCallback (react-dom.development.js:149)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:199)
    at invokeGuardedCallback (react-dom.development.js:256)
```

**Comment by pshrmn** [comment]
The function that you are calling expects [a second argument: the `history` object](https://github.com/ReactTraining/react-router/blob/2359f870b3508dca4b426d7034de9bbb398c58a5/packages/react-router-dom/modules/Link.js#L15). You could fix your error by passing the app's `history` instance to the function call, but to be perfectly honest, I'm not sure why you want to call a `Link`'s `handleClick` method via a `ref`.

**Comment by cherouvim** [comment]
> I'm not sure why you want to call a Link's handleClick method via a ref.

Is there another way to click on a `<Link />` via code? If yes I'll happily use that.

**Comment by pshrmn** [comment]
You could use the `innerRef` to get the actual `a` and click that.

```jsx
<Link
  to="/foo"
  innerRef={this.ref}
  onClick={e => console.log("link pressed")}
>
  /foo
</Link>

<button onClick={e => this.ref.current.click()}>
  Press me to click Link via Ref
</button>
```

**Comment by cherouvim** [comment]
Thanks a lot.
