### ISSUE TITLE
Old react-router 0.13.x - be more React 15 targeted

### ISSUE THREAD

**Issue by natocTo** [ReactTraining/react-router#6654]
Hello, I hope the title do not scary you to much. :)

I our app we still use old React Router 0.13. We recently upgrade React from 0.14 do 15. Hope we can soon try update React-router as well (and React go up to 16) but it is hard upgade whole big apps so quickly I would wish.

When we test out app with Jest, we receive a lot of typical React 15 post update warning (do not call React.createClass and use the package, do not call React.PropTypes and use the package atc).

The changes to solve warning are not big: https://github.com/natocTo/react-router/commit/b132c7715a704e2e78d377444185f2fc79444b06

There was just one problem with test "scrollTop", the `y` was not precisely 50. Do you have any clue why?

Maybe is to late to update so old library, is not it? But if it could be released as 0.14 I would have much better day. :)

The PR could not be sent because 0.13 is only tag and not branche.

**Summary - proposal changes**
- peerDependencies - react - ^15.5.0 only
- use "create-react-class" lib instead of "React.createClass"
- use "prop-types" lib insteaf of "React.PropTypes"
- remove "react-addons-test-utils" and use "react-dom/test-utils"
- instead of "React.DOM.a" use "React.createElement('e')"

BTW: Congrats to version 5. 👍

**Comment by natocTo** [comment]
So it look like it will not so easy. :/

**Comment by pshrmn** [comment]
Yeah, we don't maintain anything less than 3 (and not even 3 really) anymore. If you really need to stick with the version, I would recommend forking it and making local modifications.
