### ISSUE TITLE
RegEx does not work for paths passed as array to path prop

### ISSUE THREAD

**Issue by staylor** [ReactTraining/react-router#6655]
## Version

5.0.0

## Test Case

This works:
https://codesandbox.io/embed/l934ronjx9

This does not:
https://codesandbox.io/embed/5zk69x2lmk

This does:
https://codesandbox.io/embed/nw4k2yyl2p

## Steps to reproduce

when using an array in the `path` prop, RegEx validation is not properly supported. It *does* work when using a string as the value of `path`

## Expected Behavior

These all behave the same way:

`path="/:year"`
`path="/:year(\d{4})"`
`path={["/:year"]}`
`path={["/:year(\d{4})"]}`

## Actual Behavior

The first 3 work, the 4th does not.

On the New York Times website, these paths do not work as part of an array passed to `path`:

```
/slideshow/:year(\d{4})/:month(\d{2})/:day(\d{2})/:section/:subsection?/:slug/s/:splat(.+)(.)html

/slideshow/:year(\d{4})/:month(\d{2})/:day(\d{2})/:section/:subsection?/:slug
```

**Comment by timdorr** [comment]
Unfortunately, this is a limitation of our underlying path parsing library: path-to-regexp. It accepts an Express-like string or an array of plain strings, but not both. The theory being you can express the contents of the array via the regexp. It's not something we're able to fix.

A workaround is to just map out the paths as separate Routes:
```js
paths.map(path => <Route path={path} />)
```

**Comment by pshrmn** [comment]
@staylor This is actually caused by how the JSX is transformed.  You need to double escape (`\\d`) the regular expression in order for the backslash to exist in the string. You would also run into the issue if you used:
```jsx
<Route path={"/slideshow/:year(\d{4})/:month/:day"} />
```
When you pass a string, the string is automatically double escaped for you.
```jsx
// input
<Test one="\test" two={"\test"} />

// output
React.createElement(Test, {
  one: "\\test",
  two: "\test"
});
```

**Comment by staylor** [comment]
@pshrmn you are correct! thank you for the example
