### ISSUE TITLE
How do I determine if I'm in a <Router> in v5?

### ISSUE THREAD

**Issue by jwineman** [ReactTraining/react-router#6656]
I tried upgrading to react-router 5 and one of my dependencies, [`react-router-transition-switch`](https://github.com/jcoreio/react-router-transition-switch/blob/master/src/index.js#L26) is erroring because its depending on the old context API. Per https://github.com/ReactTraining/react-router/issues/6430#issuecomment-434693095 it looks like the new context wont be part of the public API so I'm curious if you have any suggestions for how to best detect whether I'm inside a `<Router/>` in v5?

**Comment by timdorr** [comment]
That particular issue is why we yanked the 4.4.0 release. 

I'm not sure of a good "official" way to detect context use if you're not supposed to be using the `RouterContext`. You can technically get to it via the `__RouterContext` export, but there is no guarantee that will work in the future.

**Comment by jwineman** [comment]
Makes sense, the library author ended up fixing it like this: https://github.com/jcoreio/react-router-transition-switch/commit/be8f9fc7b604331f4f2cb902a2d2036f83c92c8d

I was thinking about the problem too narrowly, I think you guys made the right decision not to expose the context i just had tunnel vision on how to solve this particular issue with the new API.

**Comment by mjackson** [comment]
We don't support being able to tell if you're inside a `<Router>` or not. AFAICT the only use case for a `<TransitionSwitch>` is to be able to transition between two `<Route>`s, right? Can't you just [use a normal `<TransitionGroup>` instead](https://github.com/ReactTraining/react-router/blob/2359f870b3508dca4b426d7034de9bbb398c58a5/website/modules/examples/Animation.js#L43-L63)?

**Comment by jwineman** [comment]
@mjackson your `<TransitionGroup/>` approach would probably work fine as well.  I didn't look at his code too closely but I think hes letting `withRouter()` do the check instead now.
