### ISSUE TITLE
v3: using withRouter in Modal Gallery/Pinterest example, router params change in the background

### ISSUE THREAD

**Issue by rickharris** [ReactTraining/react-router#6659]
## Version

3.2.1

## Test Case

https://codesandbox.io/s/w2926kj1nl

The test case was adapted from the Pinterest example on the `v3` branch. For reference, here's what I changed: https://github.com/ReactTraining/react-router/compare/v3...rickharris:v3-modal-gallery-with-router-example

## Steps to reproduce

You can see the issue by:

1. Click on "go to some deep route" from the Pinterest example root route
2. Click on "Link to picture with Modal"

## Expected Behavior

In the test case, I'd expect the second set of parameters to stick around when you open the modal.

I made another example to show the expected behavior on master https://codesandbox.io/s/vq63xkwkx0. Again for reference, here is the diff for what I did based off of master: https://github.com/ReactTraining/react-router/compare/master...rickharris:modal-gallery-with-router-example

In this example, you can follow the same steps to reproduce and both sets of printed parameters will stick around when you open the modal.

## Actual Behavior

In the test case, what actually happens is that the first set of printed parameters stick around when you open the modal, but the second set, which comes from `withRouter`, does not.

**Comment by timdorr** [comment]
This is just how v3 operates. withRouter will only pull from the top level current location. With v4, we can override the current location for any subtree via the location prop on the Switch above it. There isn't really a way around this because of how v3 was architected.

**Comment by rickharris** [comment]
Why does this only happen with `withRouter`, though, and not with the rest of the components that keep using the previous router location?

**Comment by timdorr** [comment]
withRouter in v3 goes to the location at the root of the tree via context because it doesn't get overridden by any interleaving ancestors. In v4, you can overload the context location value via something like `<Switch location={someOtherLocation}>`, which applies to any descendants. It's just fundamental to how each version is built, so it's not fixable because it's not "broken".

**Comment by rickharris** [comment]
Ok, thanks for the explanation!
