### ISSUE TITLE
ComponentDidUpdate doesn't call when using Redirect and ref

### ISSUE THREAD

**Issue by fuafa** [ReactTraining/react-router#6660]
## Version

version: 5.0

## Test Case

https://codesandbox.io/s/8lmvq3yq68

## Expected Behavior
I want the `componentDidUpdate` in the `Superhero` is called when calling `this.superheroElement.current.changeName()`
## Actual Behavior
`componentDidUpdate` doesn't invoke.

**Comment by timdorr** [comment]
That's not how you're supposed to be using refs. Regardless, you'll notice the name isn't updating either. This isn't a React Router issue, it's how you're using React. I'd read up on props and passing data properly.

**Comment by fuafa** [comment]
I know I solve the problem by lifting the prop, but if I don't use the Redirect,  the name can be updated success.
