### ISSUE TITLE
Using ScrollToTop and Switch does not work one or another

### ISSUE THREAD

**Issue by MariuzM** [ReactTraining/react-router#6665]
I have followed this guide to get the ScrollToTop but then i cant get Switch to work: https://reacttraining.com/react-router/web/guides/scroll-restoration

## Version
5

## Steps to reproduce
When i use this code, ScrollToTop does not work
```
    <BrowserRouter>
      <Navbar />
      <ScrollToTop>
        <Switch>
          <Route exact path="/" component={Home} />
          <Route path="/about" component={About} />
          <Route path="/contact" component={Contact} />
          <Route component={PageNotFound} />
        </Switch>
      </ScrollToTop>
    </BrowserRouter>
```

And when switching the Switch and ScrollToTop then i get the Error page `{PageNotFound}` on all pages.
```
    <BrowserRouter>
      <Navbar />
      <Switch>
        <ScrollToTop>
          <Route exact path="/" component={Home} />
          <Route path="/about" component={About} />
          <Route path="/contact" component={Contact} />
          <Route component={PageNotFound} />
        </ScrollToTop>
      </Switch>
    </BrowserRouter>
```
## Expected Behavior
How can i combine ScrollToTop and Switch (for error page) for them both to work?

**Comment by MeiKatz** [comment]
First: your second example will not work in all circumstances because the `<Switch />` component only matches elements who are direct children of the component itself. Therefore only `<ScrollToTop />` is checked and will not match.

Second: your first example should work but only if you wrap `<ScrollToTop />` with the HOC `withRouter()`. Did you do this?

**Comment by MariuzM** [comment]
I'm an idiot forgot to `import { withRouter } from 'react-router';`

**Comment by MeiKatz** [comment]
You're welcome.

**Comment by MariuzM** [comment]
If any one is curious this is what i have done, i wanted to have everything in one App (js/jsx) file
`import './App.scss';

import React, { Component } from 'react';
import { withRouter } from 'react-router';
import { Route, BrowserRouter as Router, Switch } from 'react-router-dom';

// import ScrollToTop from './components/ScrollToTop';

import Navbar from './components/Navbar';
import Home from './components/Home';
import About from './components/About';
import Contact from './components/Contact';
import PageNotFound from './components/PageNotFound';

class ScrollToTop extends Component {
  componentDidUpdate(prevProps) {
    if (this.props.location.pathname !== prevProps.location.pathname) {
      window.scrollTo(0, 0);
    }
  }

  render() {
    return this.props.children;
  }
}

const Scroll = withRouter(ScrollToTop);

export default function App() {
  return (
    <Router>
      <Navbar />
      <Scroll>
        <Switch>
          <Route exact path="/" component={Home} />
          <Route path="/about" component={About} />
          <Route path="/contact" component={Contact} />
          <Route component={PageNotFound} />
        </Switch>
      </Scroll>
    </Router>
  );
}
`
