### ISSUE TITLE
multiple redirect components in Switch cause Uncaught Invariant Violation: Maximum update depth exceeded

### ISSUE THREAD

**Issue by capaj** [ReactTraining/react-router#6667]
## Version

5.0.0

## Test Case

[![Edit react-router MultipleRedirectProblem](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/07v1766zv?fontsize=14)

## Steps to reproduce

just click anywhere in the codesanbox app

## Expected Behavior

Redirect is triggered and app changes route correctly to `/`

## Actual Behavior

`Uncaught Invariant Violation: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.`

There was also a brief conversation on twitter about this bug with original author of the codesandbox: https://twitter.com/capajj/status/1110332407293665280

**Comment by timdorr** [comment]
The multiple Redirects are causing each one to loop back on the other, so this makes sense. Instead, you should move them up outside of the Switch to one that wraps the whole animated component.
