### ISSUE TITLE
Incorrect behavior of "revertPop" method in Browser Histrory

### ISSUE THREAD

**Issue by PetrivskyiTaras** [ReactTraining/react-router#6670]
Hi, try to describe the problem.

I user Link component for navigation.
Step for reproducing:
1. Block transition to back - history.block(message) in my case message is boolean true or false
2.  Call history.goBack() transition is blocked!
3. Inside will be called method "revertPop" with fromLocation param (it is a location that was created with "getDOMLocation" method and use event.state data). In my keys state is empty. It is browser event data.
As a result, will be called "go(delta)" with incorrect delta (See attached file)
![revertPop](https://user-images.githubusercontent.com/34395038/55140943-e9dfe780-5141-11e9-9f89-19c34dba777e.jpg)

**Comment by timdorr** [comment]
See ReactTraining/history#690

**Comment by PetrivskyiTaras** [comment]
Thanks a lot, I didn't find that issue.
I've got your point. Will find another solution.
