### ISSUE TITLE
Router re-render v5 change - Documentation/release notes

### ISSUE THREAD

**Issue by samsch** [ReactTraining/react-router#6671]
## Version
v4 -> v5

## Test Case
With RRv4: https://jsfiddle.net/samsch/z4m7o1as/1/
With RRv5: https://jsfiddle.net/samsch/z4m7o1as/

## Steps to reproduce
In each fiddle, click the "Push New Query" button.

In v4 version, the Router component (and children) always re-renders. In the v5 version, only the Route is updating (and presumably anything else using context would, such as Links, Switches, etc).

## Expected Results
In an ideal world where everyone uses a perfect flow with React, this rendering change wouldn't matter.

However, even given good flows, seeing that rendering difference was unexpected.

I suspect this is the culprit behind #6657.

## Desired Action
Add this change to the release notes for v5, or even better, general notes about how re-rendering works in v5 (no more update blocking issue, etc).

**Comment by timdorr** [comment]
The number of renders isn't really a big change. If anything, it's a performance optimization. Listing out every small behavior change would be quite exhaustive and doesn't really have any impact on correctly architected React apps.
