### ISSUE TITLE
5.0 Router does not provide React Context

### ISSUE THREAD

**Issue by pickypg** [ReactTraining/react-router#6672]
## Version

5.0.0 (with React 16.8.5)

## Test Case

TypeScript code:

```jsx
import React from 'react';
import ReactDOM from 'react-dom';
import PropTypes from 'prop-types';

import { BrowserRouter as Router } from 'react-router-dom';

class App extends React.Component {

  static contextTypes: React.ValidationMap<any> = {
    router: PropTypes.shape({
      history: PropTypes.shape({
        push: PropTypes.func.isRequired,
        createHref: PropTypes.func.isRequired
      }).isRequired
    }).isRequired
  }

  constructor(...args) {
    super(...args);

    // this will log "[{},{}]"
    console.log(JSON.stringify(args));
    // this will log "{}"
    console.log(JSON.stringify(this.context));
  }

  public render() {
    return (
      <p>Router {this.context.router ? 'defined' : 'is not defined'}</p>
    );
  }
}

// Wrap the `App` in the `Router` so that it provides it the `router` as context
ReactDOM.render(
  <Router>
    <App />
  </Router>,
  document.getElementById('root')
);
```

## Steps to reproduce

Attempt to render the above page and observe that the router in not defined.

## Expected Behavior

`this.context.router` to be defined.

## Actual Behavior

`this.context.router` is not defined, which also causes warnings due to the `contextTypes` expecting it.

The exact same code works with `react-router-dom` 4.3.1.

**Comment by pickypg** [comment]
This looks like it changed because the way that the React `Context` is supplied did change between 4.x and 5.0:

4.x:

https://github.com/ReactTraining/react-router/blob/3d233bf0b6dd5bf68d9bac9c94273ae25646b207/packages/react-router/modules/Router.js#L19-L21

5.0:

https://github.com/ReactTraining/react-router/blob/ea8eba843bf899daf8a51c2617d05c179b38369d/packages/react-router/modules/Router.js#L55-L63

**Comment by pshrmn** [comment]
Directly accessing the context was never part of the public API; the recommended way to access the context has always been to use `withRouter`.

**Comment by pickypg** [comment]
Well then, that explains it! Thanks for the quick response @pshrmn!
