### ISSUE TITLE
React router shows a blank page for a short while between redirects

### ISSUE THREAD

**Issue by abilashs1990** [ReactTraining/react-router#6681]
## Version

**React Router - 4.3.1, React Router DOM - 4.3.1**

## Steps to reproduce

Let's say I have a root component with all the routes listed.

I hit a URL *http://localhost:300/testing*

I decide on `componentDidMount` that I should redirect him to *http://localhost:300/wonderful*. I use `this.props.history.replace`to achieve this redirect.

The URL gets updated, but the component takes time to get mounted. In the meanwhile, I get a blank screen. After a delay of 1 or 2 seconds, the component mounts and works as usual.

The control in these 2 seconds doesn't enter the components.

I have redux connects with all these components and am exporting a Higher Order Components.

## Expected Behavior

The Component should be mounted immediately after the URL changes

## Actual Behavior

There is a delay of 1 or 2 seconds after the URL changes to the component being mounted.

**Comment by pshrmn** [comment]
Can you create a [sandbox](https://codesandbox.io) to replicate this behavior? The redirect should be instantaneous. If you create your own `history` object, you could add a custom listener to listen for new locations.

```js
import { createBrowserHistory } from "history";

const history = createBrowserHistory();

history.listen((location, action) => {
  console.log(`new location via ${action}`, location);
});

ReactDOM.render((
  <Router history={history}>
    {/* ... */}
  </Router>
), root);
```
That said, your screen going blank makes it seem like there is a request being made to the server and the current document is unloaded and replaced with the server's response. I have no idea if this is the case, but it is something to consider.

**Comment by abilashs1990** [comment]
Hey @pshrmn, I dug deep and found the issue to be `Update Block`!

Sorry for logging this issue while there was documentation, I couldn't find the document in the first go.

For people who are searching for the same issue, here is the link to the document.

https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/guides/blocked-updates.md
