### ISSUE TITLE
Feature request: Redirect *if*

### ISSUE THREAD

**Issue by JamesPlayer** [ReactTraining/react-router#6683]
Feature request: Redirect *if*

It would be great if the Redirect component was able to take a condition so it could act as a gatekeeper to a child component, so rather than writing:
```
loggedIn ? (
  <Redirect to="/dashboard"/>
) : (
  <PublicHomePage/>
)
```

You could write
```
<Redirect to="/dashboard"/ if={loggedIn}>
  <PublicHomePage/>
</Redirect>
```
which arguably reads a little nicer. Anyway, just a thought :)

**Comment by timdorr** [comment]
Not sure I agree. Why would Redirect be in the tree if it's not doing anything? That seems more confusing to me. Thanks, but I don't see a strong case for this.

**Comment by StringEpsilon** [comment]
@timdorr You could make a case that a ```<Redirect when={} />``` would match philosophy of ```<Prompt when={} />``` 

Also, the appeal of that is shorter render() functions:

``` jsx
render() {
  return (
    <div>
      <Redirect to="/foo" when={this.state.shouldRedirect} />
      {/* Rest of the component */}
    </div>
  )
};
``` 

vs.

``` jsx
render() {
  if (this.state.shouldRedirect) {
    return <Redirect to="/foo"/>
  }
  return ( 
    <div> {/* Rest of the component */} </div>
  )
};
```
