### ISSUE TITLE
302 redirect to external url (server-side rendering)

### ISSUE THREAD

**Issue by arasmussen** [ReactTraining/react-router#6684]
React router works great for 302 redirects within the same domain / React app. I can do something like:

```js
match({
  history,
  routes,
  location: requestURL,
}, (error, redirectLocation, renderProps) => {
  if (redirectLocation) {
    response.writeHead(302, {
      Location: redirectLocation.pathname + redirectLocation.search,
    });
```

302 redirects are very important for SEO reasons. If you have a page that ranks on Google, and it moves to a different domain, you want to set up a redirect to let Google know where it moved to. Otherwise you could lose a bunch of SEO juice!

However, as your product grows, you end up having different domains, and you might want to move a page from one React app to another.

It'd be super nice if there was an `<ExternalRedirect>` component of some kind, so that I can redirect to another domain in React Router, and then pipe that logic through to my server-side rendering redirect logic.

It seems like the typical response to this feature request is `just use window.location or <a href>`, but this doesn't help me send a 302 response from my server.

Of course I could manually catch the URLs on my server, and redirect there, but this feels like app routing logic that should live with the rest of my app routing, in React Router.

On the client, `<ExternalRedirect>` would just set `window.location`. You could probably configure whether you want to `push` or `replace`, just like `<Redirect>`. On the server, it would pass a `redirectLocation` into the `match` callback, that has the `hostname` in addition to the `path`/`search`.

**Comment by timdorr** [comment]
We don't know anything about your server request from within React, so this isn't possible. You can redirect to a location with some `state` attached that indicates an external link.

**Comment by arasmussen** [comment]
Hey @timdorr, thanks for the prompt response!

I'm a little confused though – where did you get the idea that React would need to know anything about my server request? The code snippet I shared is something that works today.

**Comment by pshrmn** [comment]
Is there any particular reason this couldn't exist as a third party component? I guess that I'm not seeing why this would need to be part of RR's core.

**Comment by arasmussen** [comment]
Totally could! I'm planning on building it myself, but thought I'd drop a note here to let you guys know that I thought it'd be a nice core feature to have.

**Comment by arasmussen** [comment]
Here's what I ended up with, in case anyone finds it useful. https://gist.github.com/arasmussen/f2c01dc858481590f6bffae6b540632c
