### ISSUE TITLE
Attribute basename of StaticRouter work a little strange

### ISSUE THREAD

**Issue by fimars** [ReactTraining/react-router#6686]
## Version
`"react-router": "^4.3.1"`
`"react-router-dom": "^4.3.1"`

## Test Case

https://codesandbox.io/s/n50pvx92v4

## Steps to reproduce

Just open the Codesandbox case, inspect any Link component's `<a>` tag, check the `href` attribute.

## Expected Behavior

when I use the basename as `/` on `StaticRouter`, just normally be the `/`, `/topics`, etc;

## Actual Behavior

now, i got the `//` `//topics`;

**Comment by StringEpsilon** [comment]
https://github.com/ReactTraining/react-router/blob/017f692af74f5797c65d86265c063bc0ea829e13/packages/react-router/modules/StaticRouter.js#L16-L19

Problem is that "location.pathname" defaults to "/". Hence we get "//".

**Comment by pshrmn** [comment]
If your website's pages exist at the root, you do not need a `basename`. The `basename` represents a non-root segment at the beginning of the `pathname` component of a URL, a forward slash followed by the segment string (e.g. `/base`).

**Comment by fimars** [comment]
I use the `BrowserRouter` before, that's component set '/' as basename attributes is work, I mistakenly think that this is the expected behavior of your design. 😅 

@pshrmn thanks for your reply.

**Comment by pshrmn** [comment]
@fimars the `StaticRouter` is a bit weird because it uses a fake history object. A real history [ensures a basename has the correct format](https://github.com/ReactTraining/history/blob/baef9348138be6c7f520f09a36b1c0cb372c1394/modules/createBrowserHistory.js#L51), which turns the `basename` `/` into an empty string.
