### ISSUE TITLE
What happened to react-router-dom: ^4.4.0?

### ISSUE THREAD

**Issue by john-aws** [ReactTraining/react-router#6688]
Hi, I'm no longer able to `npm install` a project that has the following dependency:

```
"react-router-dom": "^4.4.0"
```

This project is a few weeks old and now fails to install with:

```
No matching version found for react-router-dom@>=4.4.0 <5.0.0
```

What happened to 4.4.0? Thanks.

**Comment by timdorr** [comment]
https://reacttraining.com/blog/react-router-v5/

**Comment by john-aws** [comment]
Ah, more specifically:

> In the end, we decided that the fix that would cause the least pain for everyone would be to npm unpublish version 4.4.0 and re-release it as 5.0.0.

Got it. Thanks for the quick update.
