### ISSUE TITLE
Installing 5.0.0 gives you a warning about non-maintained package inside

### ISSUE THREAD

**Issue by vladshcherbin** [ReactTraining/react-router#6697]
## Version

5.0.0

## Test Case

Not sure how to show it on codesandbox since it's a package installation issue.

## Steps to reproduce

yarn add react-router-dom

## Expected Behavior

Package installs with no errors or warnings.

## Actual Behavior

Package installation gives a warning:

```
warning react-router-dom > react-router > create-react-context > fbjs 
> core-js@1.2.7: core-js@<2.6.5 is no longer maintained. Please, upgrade 
to core-js@3 or at least to actual version of core-js@2
```

After reading the [v5 announce article](https://reacttraining.com/blog/react-router-v5/) with mention of 5 months of tests before release, this is a bizarre and terrible thing to see in console.

**Comment by StringEpsilon** [comment]
This should be fixed with #6692, since I switched out fbJS for tiny-warning.

**Comment by timdorr** [comment]
Also, it's not like the code doesn't work. It's just a warning from a sub-sub-sub-sub-dependency about the status of that project.

**Comment by vladshcherbin** [comment]
@timdorr this is a warning about status of a package used inside. If it's fine for you to have packages with warnings inside your project, this gives info about the status of your whole project.

@StringEpsilon thank you, hopefully it will be released soon.
