### ISSUE TITLE
Request: given a path-to-regexp compliant string and a string, extract the url parameters.

### ISSUE THREAD

**Issue by AlexFrazer** [ReactTraining/react-router#6700]
I am proposing adding a function with the following signature:

```
/**
* @param {String} matchPath the path-to-regexp compliant url string
* @param {String} testPath the path to apply the path-to-regexp to
*/
function deconstructUrl(
  matchPath: string,
  testPath: string
);
```

Basically, there exists a function currently to make a new url from parameters and a path-to-regexp compliant string.

What I am hoping for is the reverse; getting parameters from a path and a path-to-regexp compliant string

Here is the use case.

```
export const viewProjectPage = '/projects/:projectId/view/:fileId?';
```

Which I will use in my route like so:
```
<Route path={viewProjectPage} component={ViewProject} />
```

The addition of `generatePath` makes it great for being able to re-use this string and generate a path. Say for example if I wanted to make a link to this page.

```
import * as React from 'react';
import { Link } from 'react-router-dom';

export default function ProjectLink({
  children,
  projectId,
  fileId,
}: Props) {
  const to = React.useMemo(
    () => generatePath(viewProjectPage, projectId, fileId),
    [projectId, fileId],
  );
  return <Link to={to}>{children}</Link>
}
```

However, what I sometimes would want is the ability to deconstruct the current url and retrieve the params. It would look more or less as follows:

```
const { projectId } = deconstructPath(viewProjectPage, history.location.pathname);
if (projectId) {
  console.log('You are on this project page: ', projectId)
}
```

**Comment by StringEpsilon** [comment]
You could just make a short wrapper around matchPath:

```js
function deconstructPath(pathname, path, options) {
  const match = matchPath(pathname, { path }, options);
  return match && match.params ? match.params : {};
}
```

I'm not sure such a trivial wrapper warrants inclusion, unless it's in really high demand.

**Comment by timdorr** [comment]
I agree. You can get 99% of the way there with matchPath.
