### ISSUE TITLE
react server render  Component  componentDidMount

### ISSUE THREAD

**Issue by Pecking** [ReactTraining/react-router#6701]
![image](https://user-images.githubusercontent.com/27414779/55926263-3861ab80-5c43-11e9-9d17-1863a83ff45e.png)
When I use server-side rendering, I configured routerconfig. After that, my component's componentDidMount is executed. This is not the case.

**Comment by timdorr** [comment]
There is no mounting on the server, so cDM doesn't run. This isn't a React Router issue.
