### ISSUE TITLE
Rerendering when other parts of the context change

### ISSUE THREAD

**Issue by TJSomething** [ReactTraining/react-router#6702]
I am using React Router with React Redux. I'm having a problem where any component that uses the routing context (e.g. `<Link>`) rerenders whenever the Redux store updates. Since I have a lot of links and frequently update the store, I'd like to prevent this rerendering.

My suspicion is that it's rebuilding the routing context object each time the context changes, which causes every consumer of the context to update. So, I think that could be fixed by caching the context in `Route` and `Router`, as prescribed in [the React documentation's advice on context](https://reactjs.org/docs/context.html#caveats).

My workaround is to reimplement `Link` so that it memoizes its anchor and can receive props from `withRouter`, which seems to have solved the problem. But I would rather not have to do that.

**Comment by timdorr** [comment]
What versions of each library are you using? It shouldn't be doing this.

**Comment by TJSomething** [comment]
The latest one: 5.0.0.

**Comment by timdorr** [comment]
What about React Redux?

**Comment by TJSomething** [comment]
Oh whoops. React 16.8.0, Redux 4.0.1, and React Redux 6.0.1.

**Comment by TJSomething** [comment]
I should have made sure everything was up to date first. Upgrading to React-Redux 7.0.1 fixed it.
