### ISSUE TITLE
Push with custom history not working since 5.0.0

### ISSUE THREAD

**Issue by namelesswc** [ReactTraining/react-router#6705]
## Version

**5.0.0**

## Test Case

https://codesandbox.io/s/ox4y7z6w4q?fontsize=14

## Steps to reproduce

Go to About section.
Click on 'go to home without props' button.

## Expected Behavior

Expecting 'Home' component to be loaded. Same behaviour as if you would click the other button.

## Actual Behavior

Url changes but home component is not loaded.

This worked for me on older projects but not in my newest project so I guess it is because of v5. I don't want to use props because I want to push my history inside a redux action creator which is not a react component.

**Comment by namelesswc** [comment]
My current workaround is passing this.props.history to my action creator.

**Comment by pshrmn** [comment]
You are using the wrong router component. In order to pass a custom `history`, you need to use `Router`, not `BrowserRouter`.

**Comment by StringEpsilon** [comment]
Additionally, your import in `index.js` is wrong. You're importing from `history` there, but from `/components/history` in the about component..

**Comment by namelesswc** [comment]
Thank you. I missed the "BrowserRouter as Router" in import and thought I was already using Router. lol... only one day lost
