### ISSUE TITLE
Receiving ESM Error but not using ESM

### ISSUE THREAD

**Issue by merlinpatt** [ReactTraining/react-router#6708]
## Version

5.0.0

## Steps to reproduce

1. Install React Router and Dom
2. Add line `import {HashRouter, Switch, Route} from 'react-router-dom';`
3. Build app

## Expected Behavior

In my console I see this error
```
Please use `import { Router } from "react-router"` instead of `import Router from "react-router/es/undefined"`. Support for the latter will be removed in the next major release
```

## Actual Behavior

I am not importing anything with the `es/undefined` syntax so this error should not appear.

**Comment by StringEpsilon** [comment]
Can you create a minimum reproduction repository? This really shouldn't happen, unless a step in your build process changes the imports or another dependency of yours uses the old import style.

**Comment by timdorr** [comment]
You likely have some build plugin that is rewriting those imports. If you remove it, this error will go away.
