### ISSUE TITLE
Link should properly work without `pathname` set

### ISSUE THREAD

**Issue by extempl** [ReactTraining/react-router#6713]
Although the linking inside react works as indented, the url in html is wrong.
If you pass `{hash: '#somehash'}` to the `to` parameter, in the html it will be set as `/#somehash` which is wrong, it should be without the leading slash. The same is for the `search` parameter.

I've seen #3662 and #3657, but it looks like the first one wasn't fixed because of the second one and the second one just looks as outdated as for me (is `to` still can get function as a parameter? Because it doesn't work and there is no `function` option in the [docs](https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/docs/api/Link.md)).

**Comment by MeiKatz** [comment]
I don't think that this is much of a big problem. But I don't know if this is a intended behaviours by the maintainers. What do you think @timdorr?

**Comment by extempl** [comment]
Well, docs says that you can have `any` of these parameters to be set, so `none` of them actually is required. And by leading slash it breaks the `copy as link`, `save as link`, `open in new tab` and alike browser functionality.

**Comment by extempl** [comment]
Also, but it is probably a different request, I'd like to have a revert thing (probably by a special key):
If we are on a `/something?search` page and we building a link with a `{pathname: '/something-different' }` I'd like to save the `search` parameter. Currently, I am using a `Link` wrapper for this and reading the `search` directly from the `location`. 
The context is I need to have some `redirectTo` parameter persist on navigation and on `close-and-open` case.

**Comment by MeiKatz** [comment]
@extempl I think your last problem could be solved by something like #3657.

Anyway, I will see if I have some time in the next days to create a pull request for your (first) problem.

**Comment by timdorr** [comment]
This is following the HTML standard for location. It is defined as such:

> Is a DOMString containing an initial '/' followed by the path of the URL.

https://developer.mozilla.org/en-US/docs/Web/API/Location#Properties

So this is expected behavior not just for this library, but also the browser.

**Comment by MeiKatz** [comment]
@timdorr I don't think that this is a behaviour that is covered by the linked specification.

**Comment by extempl** [comment]
@MeiKatz I am afraid he is right. It reads `initial '/'`. And if you open, for example, GitHub at the root and read `location` it will contain pathname: '/'. So, as long as the lib implements `location` following specs, it sets `pathname: '/'` as a default value, if not set or falsy. So, if we want to have different behavior, like, reusing pathname/search/hash if not specified - it won't be a `location` anymore, but some custom entity/wrapper over location.

**Comment by extempl** [comment]
So, to have `#somehash` applied without `/`, we should pass a string to `to` parameter, and not a `location`.

**Comment by MeiKatz** [comment]
@extempl Mh, I will try this when I am back home.

**Comment by extempl** [comment]
However, following the same logic, the lib already modifies location object with the current `origin` and does not allows using a custom `origin`, so it is already not exactly a `location` implementation.

**Comment by MeiKatz** [comment]
@extempl When I am at `example.org/en/news` (for example) and set `location.hash = "#foobar"` then the result will be `example.org/en/news#foobar` and not `example.org/#foobar`. Same if I click on an anchor with `href="#foobar"`. Therefore I don't think using `<Link to={{ "hash": "#foobar" }} />` is against the specification. Or do I miss a thing, @timdorr?

**Comment by StringEpsilon** [comment]
Additionally: The `baseName` of the Router  is appended in case of 

```jsx
<BrowserRouter baseName="/foo">
  <Link to={{ hash: "#bar"}} /> {/* links to "/foo/#bar", where strict adherences to the standard suggests "/#bar" */}
</BrowserRouter>

**Comment by timdorr** [comment]
When you set location.hash, you are mutating the existing location object. So it has a pathname already on it.

**Comment by extempl** [comment]
I'd suggest to add a key 'reuseNotPassedProperties' and when is true - use any of the props if set and not passed, when falsey - just go with original logic. That is obviously add some handy on usage of the component, otherwise it is useless in half of situations and requires some wrapper.
