### ISSUE TITLE
Link to={locationObject} has inconsistent behavior between search and hash.

### ISSUE THREAD

**Issue by StringEpsilon** [ReactTraining/react-router#6718]
## Version

5.0.0

## Test Case

https://codesandbox.io/s/wyxq313458

## Expected Behavior

Based on the comments on #6713, I expect that  `<Link to={{ hash: "hash"}}/>` and `<Link to ={{ search: "search"}}/>` behave the same, in that they link to the basename of the router. Or that both link to the current location + hash / search.

Especially noteworthy is the difference between `{ search: "search"}` - which just appends the search - and `{ hash: "hash", search: "search"}` which links to basename + hash + search. 

I'd also expect that after navigating with such a Link, that the URL I see in the browser is reflected in the routing. But that isn't the case.

### Part 1: Link targets

Given the basename "root" and the current location "path":

| "to" prop | target url |
|---|---|
| `{hash: "hash"}` | /root#hash
| `"#hash"` | /root/path#hash
| `{search: "search"}` | **/root/path?search**
| `"?search"` | /root/path?search
| `{search: "search", hash: "hash"}` | **/root#hash?search**

Consistent would be:

| "to" prop | target url |
|---|---|
| `{hash: "hash"}` | /root#hash
| `"#hash"` | /root/path#hash
| `{search: "search"}` | **/root?search**
| `"?search"` | /root/path?search
| `"#hash?search"` | /root/path#hash?search
| `{search: "search", hash: "hash"}` | **/root#hash?search**

### Part 2: Routing

When clicking on a Link without a pathname specified, the user is navigated to the baseName / root URL. But the Router still matches the prior path. You can test that in the above sandbox by clicking on the "otherpath", then clicking on the "HASH location object" link. It still matches and renders the `OtherPath` route.

![Screenshot_2019-04-23 CodeSandbox](https://user-images.githubusercontent.com/5951778/56579941-b2921880-65d1-11e9-9fb1-6a2acd8d3222.png)

### Part 3: BrowserRouter vs. HashRouter

Edit: I just had the idea to check if the behavior is the same for different Routers. It's not. MemoryRouter and BrowserRouter seem to behave the same, but HashRouter is different for `{ search: "search"}`.  Both in terms of target URLs (see below) and in that the location object sans pathname causes the expected route change based on the new URL.

| "to" prop | target url - browserRouter | target url hashRouter
|---|---|---|
| `{hash: "hash"}`                  | /root#hash             | #/root#hash            
| `"#hash"`                         | /root/path#hash        | #/root/path#hash       
| `{search: "search"}`              | /root/path?search      | **#/root?search**      
| `"?search"`                       | /root/path?search      | #/root/path?search     
| `"#hash?search"`                  | /root/path#hash?search | #/root/path#hash?search
| `{search: "search", hash: "hash"}`| /root#hash?search      | **#/root/path#hash?search**

**Comment by StringEpsilon** [comment]
Addendum:

I think the hash property is just completely broken. 

`<Link to={{ pathname: "/otherpath", hash: "#hash" }}/>`

Clicking that Link also doesn't update the route matching and location objects in RR.  See this slimmed down sandbox:

https://codesandbox.io/s/0qz5wvw1vn

**Comment by MeiKatz** [comment]
Honestly, I would expect the following behaviour:

"to" prop | target url
--------- | ----------
`{hash: "hash"}` | `/root/path#hash`
`#hash` | `/root/path#hash`
`{search: "search"}` | `/root/path?search`
`"?search"` | `/root/path?search`
`"#hash?search"` | `/root/path#hash?search`
`{search: "search", hash: "hash"}` | `/root/path?search#hash`

**Comment by MeiKatz** [comment]
I will take a closer look at it later. I think the solution for both problems has the same origin.

**Comment by StringEpsilon** [comment]
I appeneded differences between HashRouter and BrowserRouter.

**Comment by MeiKatz** [comment]
By the way: I think the base path shouldn't be part of the hash in `HashRouter`.

**Comment by MeiKatz** [comment]
I am currently struggling with how the expected behaviour should be when you click on a link without `search` and/or `hash`. Should it keep the `search` / `hash` when the pathname changes (default browser behaviour) or should it drop both?

**Comment by timdorr** [comment]
I'm not sure I follow what the issue is here. We're following the spec pretty well. Getting the `pathname` value from a location is has [this processing step](https://html.spec.whatwg.org/multipage/history.html#dom-location-pathname):

> If url's path is empty, then return the empty string.

So, we shouldn't be using a value for that when determining the URL to show. 

For the string form, we follow the URL parsing rules, particularly when it comes to [parsing relative URLs](https://url.spec.whatwg.org/#relative-state).

AFAICT, this is the correct, by-the-standard way of handling these locations.

**Comment by StringEpsilon** [comment]
@timdorr 

> So, we shouldn't be using a value for that when determining the URL to show.

But that's what's happening with a location object of `{ search: "search"}`. The current path is retained, whereas with `{ hash: "hash" }` the standard is followed and the current path is dropped. By your argument, that is **not** spec compliant behavior.

There is also part 2 and part 3 of my original issue: 

* Navigating to `{ search: "search"}` doesn't update the RR tree, when using `BrowserRouter`
* HashRouter and BrowserRouter exhibit different behavior. Namely in that `HashRouter` is in line with the spec, where BrowserRouter isn't. 

I suggest you play around with the codesandboxes I linked. If the examples and my explanations are to convoluted, let me know and I'll rework my issue report and the sandboxes. I'd also be happy to separate it into 3 separate issues - but I think this only has one root cause.

**Comment by timdorr** [comment]
Oh, whoops, I was looking at the second table, not the first one. Yeah, that's quite odd that we handle the blank pathname differently. Where does that behavior even come from? 🤔

**Comment by StringEpsilon** [comment]
Sandbox demonstrating the difference between `{ search: "search" }` and `{ hash: "hash" }`:

https://codesandbox.io/s/rrxp9rqlp4

The same sandbox, but with a HashRouter doesn't exhibit that difference:

https://codesandbox.io/s/6z1y252q2r

Sandbox demonstrating that a location object with a search or hash attribute doesn't update the tree, when a pathname is also provided:

https://codesandbox.io/s/vplzv3847

Note that in the first sandbox, the search link **does** trigger an update.

**Comment by timdorr** [comment]
For reference, the code is here: https://github.com/ReactTraining/history/blob/763fc13bc8a52aff91d9594a7c1d944faa97961a/modules/PathUtils.js#L51-L56

**Comment by StringEpsilon** [comment]
@timdorr I don't believe that the issue in in that portion. But I just double-checked: `history` and `react-router-dom` have unit tests covering the generated URIs. And if you check the sandboxes, the URLs generated on the anchor elements are also correct for all buggy `Link`s.

**Comment by StringEpsilon** [comment]
Seems like history.listen() isn't fired if there is a hash on the new location:

https://codesandbox.io/s/r5rn1rym74

Above, I added a simple logger to history.listen().

**Comment by pshrmn** [comment]
@StringEpsilon I believe that your sandbox is running into some bug with CodeSandbox's fake history implementation. If you use the "open sandbox in new window", you'll see the logs for the other links.

**Comment by StringEpsilon** [comment]
@pshrmn Well, that's a bummer.

All this and it's just a bug in codesandbox. I'll close the issue and open a new one on codesandbox. Sorry for all the hassle.

@timdorr: You might find it interesting that `<Link to={{ hash: "#hash"}}/>` works as #6713 requested when using the codesandboxes in a separate window:

https://rrxp9rqlp4.codesandbox.io/foo/otherpath?search

That might still be a codesandbox bug, but I thought I'd let you know anyway.
