### ISSUE TITLE
Link component doesn't work on IE 9

### ISSUE THREAD

**Issue by augugiaco** [ReactTraining/react-router#6719]
Hi guys!

I've a bug with Link component on Internet Explorer 9 only.

I've 16.8.4 version of React in my project and every works fine, but when I use the Link component on IE 9 to navigate in the app, I've found a critical bug.

When I click in an anchor that have been generated by Link component the expected behavior is that I can navigate through my app without page refreshes and this works well on Chrome, Safari and IE 10 and 11, but with IE 9 when I do click in the anchor, the entire page is refreshed and I lose redux's and javascript's state.

Are there anyone with this issue?

Thanks!

**Comment by pshrmn** [comment]
[IE9 doesn't support the History API](https://caniuse.com/#search=pushState), so the `history` package falls back to [setting `window.location.href`](https://github.com/ReactTraining/history/blob/baef9348138be6c7f520f09a36b1c0cb372c1394/modules/createBrowserHistory.js#L202). You should be seeing this message in the console to let you know why this is happening:

> Browser history cannot push state in browsers that do not support HTML5 history

**Comment by augugiaco** [comment]
@pshrmn Thank you for response! 
So, there is not way to work with react router with IE 9, right?

**Comment by StringEpsilon** [comment]
@pshrmn Should RR and History have a documentation section about supported browsers / minimum versions? I could only find the .browserlistrc, which isn't the first choice of reference when you have an issue like this.

@augugiaco I strongly recommend you move away from IE 9. It's almost 3 years out of support and misses a whole lot of features. And no, React Router won't work for you if IE 9 is a requirement. Nor would any other current routing solution do you any good.

**Comment by augugiaco** [comment]
@StringEpsilon In effect, I couldn't find any documentation about browser support.
Thank you so much for your answer! Now I have confirmation about my suspicion.

@pshrmn I apologize if my post doesn't accomplish some rule. Thank you!
