### ISSUE TITLE
Jest/Enzyme testing component that renders Link throws an error.

### ISSUE THREAD

**Issue by okhy** [ReactTraining/react-router#6721]
Hello all, I'm developing a simple app and trying to test everything along the way. Recenlty I've added `react-router` and in component below replaced wrapping `div` with `Link` component. After that all existing test cases started to fail (not even run actually). I went through issues, stackoverflow etc. and did wrap component in test cases in `MemoryRouter` but to no avail, my tests are still broken.

I'd greatly appreciate any kind of help or direction to resolve this issue.

## Version

 "react": "^16.8.4",
 "react-dom": "^16.8.4",
 "react-router-dom": "^5.0.0",

## Test Case / Code

Component:
```typescript
const MovieGridItem: React.SFC<MovieTypes.IMovie> = ({
  id,
  title,
  poster,
  releaseDate,
  genres
}) => (
  <Link to={`/movie/${id}`}>
    <Poster url={poster} />
    <div className={styles.data}>
      <div className={styles.baseData}>
        <span className={styles.title}>{title}</span>
        {!!releaseDate && releaseDate.length > 3 && (
          <span className={styles.releaseDate}>{releaseDate.substr(0, 4)}</span>
        )}
      </div>
      {!!genres && !!genres.length && (
        <span className={styles.genres}>{genres.join(" & ")}</span>
      )}
    </div>
  </Link>
);
```

Test:
```typescript
it("... renders without errors", () => {
    const wrapper = shallow(
      <MemoryRouter>
        <MovieGridItem {...mockMovie} />
      </MemoryRouter>
    );

    expect(wrapper.find(MovieGridItem)).toBeTruthy();
  });
```
## Steps to reproduce
run test for said component

## Expected Behavior

Tests at least run.

## Actual Behavior

An error is thrown:
```
TypeError: checkPropTypes is not a function

      51 |   it("... renders no-poster message ", () => {
      52 |     const wrapper = shallow(
    > 53 |       <MemoryRouter>
         |       ^
      54 |         <MovieGridItem {...mockMovie} poster="" />
      55 |       </MemoryRouter>
      56 |     );

      at validatePropTypes (node_modules/react/cjs/react.development.js:1666:5)
      at Object.createElementWithValidation [as createElement] (node_modules/react/cjs/react.development.js:1755:5)
      at Object.<anonymous> (src/components/MovieGrid/components/MovieGridItem/MovieGridItem.test.tsx:53:7)
```

**Comment by MeiKatz** [comment]
`checkPropTypes` is a function defined by the package `prop-types`. So I think it is a problem with this library and that is not installed / included correctly. Every component of React Router defines `propTypes` in development mode.

**Comment by okhy** [comment]
Thank you for quick response @MeiKatz. I do have a follow-up questions though:
1. in that case how should PropTypes be set up for that to work?
2. shouldn't that be considered a bug as I don't think anyone using router should be required to solve this every time they set up tests (unless my understanding of that is wrong).

**Comment by timdorr** [comment]
Yeah, that doesn't appear to be a problem with the library. That's not our code.

I think you also need to be using `mount` instead of `shallow` for rendering, but I can't see your full test to know for sure (in case you are shallow()'ing on an element of the root).

**Comment by okhy** [comment]
Just as an afternote - it is indeed not a router problem as I can replicate it without react-router components. Sorry.
