### ISSUE TITLE
Context mismatch issue during SSR

### ISSUE THREAD

**Issue by tstirrat15** [ReactTraining/react-router#6722]
## Version

"react-router-dom": "5.0.0"

## Test Case
I don't have a good test case yet, namely because I'm still looking for help on where to look for a diagnosis.

Here's what's happening:

We use `react-router-dom@5.0.0`. `react@16.8.4`, `react-dom@16.8.4`, `webpack@4.30.0`, and `@babel/*@7.4.3`.

In a development environment, everything works just fine. There are no context errors, and nothing in the way of warnings beyond some `<StrictMode>` warnings unrelated to `react-router`.

When we go to create a production build, that build fails with the following error:
```
Error: Invariant failed: You should not use <Route> outside a <Router>
    at invariant (/home/me/development/react-universal/node_modules/tiny-invariant/dist/tiny-invariant.cjs.js:13:11)
    at Object.children (/home/me/development/react-universal/node_modules/react-router/cjs/react-router.js:454:21)
    at a.render (/home/me/development/react-universal/build/server.js:83464:64)
    at a.read (/home/me/development/react-universal/build/server.js:83461:58)
    at renderToString (/home/me/development/react-universal/build/server.js:83473:83)
    at /home/me/development/react-universal/build/server.js:50336:91
```

Which points to [this code](https://github.com/ReactTraining/react-router/blob/master/packages/react-router/modules/Route.js#L22), which throws if the context is unavailable.

This isn't the first time I've run into this problem with our React upgrade - the first issue was with a similar problem with `react-redux` and it being unable to find its context, and working on fixing that led me to this react issue: https://github.com/facebook/react/issues/13991

I used webpack module aliases to force `react` to resolve to the specific `node_modules` path, per a suggestion in the aforementioned issue:
```
  resolve: {
    alias: {
      react: path.resolve(path.join(__dirname, '../node_modules/react')),
      'react-dom': path.resolve(path.join(__dirname, '../node_modules/react-dom')),
    },
  },
```
And this fixed the issue with `react-redux`, but that's when I started seeing the issue with `react-router`. It's unclear whether this caused the issue with `react-router` or just uncovered it.

I went looking through the source code and found the [context API polyfill](https://github.com/ReactTraining/react-router/blob/master/packages/react-router/modules/RouterContext.js#L2), and was curious whether it was somehow incorrectly polyfilling the context in one place but not another, but installing and then importing it and then checking `createReactContext === React.createContext` returned `true`.

The place where the provider is set up for SSR looks like this:
```jsx
import { StaticRouter } from 'react-router-dom';
// ...
  const routerContext = {};
  const children = renderToString((
    <Provider store={store}>
      <StrictMode>
        <StaticRouter
          location={req.url}
          context={routerContext}
        >
          <CssProvider context={context}>
            <UserAgentProvider ua={req.headers['user-agent']}>
              <FacebookProvider appId={__FB_APP_ID__}>
                <Routes />
              </FacebookProvider>
            </UserAgentProvider>
          </CssProvider>
        </StaticRouter>
      </StrictMode>
    </Provider>
  ));
```

And the first place where a consumer is throwing an error is in the `Routes` component, which looks a bit like this:

```jsx
import { Route, Switch, withRouter } from 'react-router-dom';
class Routes extends Component {
  componentDidMount() {
    this.props.getUser();
  }

  render() {
    const { loading } = this.props;
    return (
      <Fragment>
        <SvgDefs href={svgdefs} />
        <Switch>
          {/* ... */}
          <Route component={PageNotFound} />
          {/* ... */}
        </Switch>
      </Fragment>
    );
  }
}
export default withRouter(Routes);
```

The `withRouter` usage here is as a diagnostic tool to throw an error - I realize it would be weird to wrap a component that looks like this with `withRouter`.

Some other notes:

* For the server bundle, the webpack minimization flag is set to `false`, so it's probably not a problem with Terser and minimization.
* I've verified that there's only one version of React installed (`npm ls react` returns a single entry)

Any thoughts on where to look next for the source of the problem? I've been getting mostly blank stares in places like the `reactiflux` discord.

## Steps to reproduce
See above.
## Expected Behavior
It loads nicely.

## Actual Behavior
I see a context error.

**Comment by timdorr** [comment]
In general, this is caused by duplicate/mismatched versions of react-router and react-router-dom. I would use `npm ls` to see that you only have one in the tree. I would also explicitly install react-router as a dependency, just to be sure. 

Another thing to try is removing StrictMode, since that's disabled in production mode and that will emulate things in dev mode.

Outside of that, I don't believe this is a problem with the library itself.

**Comment by tstirrat15** [comment]
Right, but why would this be happening with one context-based library but not another? As far as I understand it, this library uses the same mechanisms as `react-redux`, but `react-redux` isn't having the same problems, and it's higher in the tree.

**Comment by timdorr** [comment]
The same singleton instance of Context needs to be used between the two. That singleton doesn't match up if you're pointing to two copies of the library that creates it (react-router, in this case). That burnt a fair number of people when we published 4.4.0, which is why we jumped to 5.0 without breaking changes (the breakage was for 4.3.1).

**Comment by tstirrat15** [comment]
Between the provider and the consumer, or between the two different context-using libraries?

I'm familiar with the singleton nature of `createContext`, and the ways that it can potentially cause problems if the provider and consumer aren't using the same instance. What isn't clear to me is why `react-redux`'s provider and consumer line up, but `react-router`'s don't seem to. Is this one of those things where it's possible for that to happen despite both libraries being correct?

**Comment by timdorr** [comment]
Between the Consumer/Provider pair. They must be extracted from the same Context instance, otherwise they won't "see" each other.

React Redux is one single library. React Router is 2 (react-router and react-router-dom), so there is the potential for those to mismatch or be duplicated, especially in complex applications where you might be consuming code bundled/resolved by different systems (webpack vs node built-in).

**Comment by tstirrat15** [comment]
Ahhhhh. Thank you! That distinction helps a lot. I'll have a look at the way they're interacting.

**Comment by ajsharp** [comment]
I’m having this issue as well with SSR. I’m not using two copies of the library accidentally. This seems like a bug with react router. 

@tstirrat15 how did you end up dealing with it?

**Comment by ajsharp** [comment]
I solved my problem -- I think it was being caused by wrapping a routed component in a hypernova function, which I'm using for SSR rendering. Apologies on any confusion here.

**Comment by tstirrat15** [comment]
Yeah. These are frustrating issues, because they tend to be related to infra or other libraries. I'm still wrestling with a 16.8 upgrade and it's been a couple of months now...
