### ISSUE TITLE
Show alert on browser back button click on react

### ISSUE THREAD

**Issue by ashokraghu14** [ReactTraining/react-router#6729]
Hi,

I wanted to show an alert on the page when the browser back button is clicked. Thanks in advance.

**Comment by StringEpsilon** [comment]
Please use the issue template and don't ask general support or usage questions. This issue tracker is for bug reports and feature requests only. If you have a usage question, [StackOverflow](https://stackoverflow.com/questions/tagged/react-router) or the [reactiflux discord ](https://www.reactiflux.com/) server are a much better choice.
