### ISSUE TITLE
React Training page is down

### ISSUE THREAD

**Issue by MisterKatCodes** [ReactTraining/react-router#6731]
Test Case
"Get Training" page on react router website is down.

Steps to reproduce
Go to "https://reacttraining.com/react-router/"
Click on "Get Training"
Expected Behavior
Training page should be rendered.
Actual Behavior
Blank page is rendered with an error in console.

**Comment by StringEpsilon** [comment]
Seems to work just fine from my machine. But also just in general:

https://downforeveryoneorjustme.com/reacttraining.com 

https://isitdownorjust.me/reacttraining-com/ 

And down.com also reports it as "up".

**Comment by 0xpr03** [comment]
This issue persists. If you have the low-tracking-blocking in firefox on, the website stays black except for the menu.

**Comment by arvigeus** [comment]
Same for me, except I get 522. Works when I run it through proxy
