### ISSUE TITLE
react-router: Make Router's staticContext a part of public API

### ISSUE THREAD

**Issue by Dattaya** [ReactTraining/react-router#6733]
## Version

5.0.0

Thank you for this awesome library. What do you think about making Router's [`staticContext`](https://github.com/ReactTraining/react-router/blob/master/packages/react-router/modules/Router.js#L61) to be a part of the public API. I use [qhistory](https://github.com/pshrmn/qhistory) that can parse/stringify query params and need to provide it on the server as well: `<Router history={qhistory(...)} staticContext={staticContext}>`, but `staticContext` is not described in the docs and is missing in TS definitions, so I assume it's considered a private API.
Related to https://github.com/DefinitelyTyped/DefinitelyTyped/issues/35279

**Comment by StringEpsilon** [comment]
The types over at the DefinetlyTyped repository are not maintained by react-router maintainers, and as such is not reflective of what consists of react routers public API. Also: The [staticContext part is documented here](https://reacttraining.com/react-router/web/api/StaticRouter/context-object)

[With an example here.](https://reacttraining.com/react-router/web/example/static-router)

**Comment by Dattaya** [comment]
Is it a good idea to add it here?
![image](https://user-images.githubusercontent.com/387256/57369366-04bc6780-7196-11e9-804f-575ae25fe735.png)

**Comment by Dattaya** [comment]
I'm using low level `Router`

**Comment by StringEpsilon** [comment]
The staticContext is only available if you're using a ```StaticRouter```. 

There are some internal shenanigans for dealing with the Static-ness of a that special router, which depend on the staticContext being absent or present. So, adding it to all ```Router```s would require some reworking of those mechanisms. But ultimately, the purpose of the staticContext is to assist in Server Side Rendering code, not to be a general-purpose storage.

**Comment by Dattaya** [comment]
Yep, I use it on the server, but isn't `staticContext` property already properly handled by `Router`: https://github.com/ReactTraining/react-router/blob/master/packages/react-router/modules/Router.js#L61 ?

**Comment by timdorr** [comment]
`staticContext` is the internal API for `<StaticRouter>` to implement [its `context` prop](https://reacttraining.com/react-router/web/api/StaticRouter/context-object). It's not meant as a public API.
