### ISSUE TITLE
URL Is Changing, but the View Does Not Change

### ISSUE THREAD

**Issue by serdarkaraca** [ReactTraining/react-router#6742]
## Version

**react-router-dom@5.0.0**
**react-router@5.0.0**

### index.js 
```
import { BrowserRouter as Router } from 'react-router-dom';

ReactDOM.render(
    (
        <Router >
            <App />
        </Router>
    )
    ,document.getElementById('root'));

```

### App.js 
```
import React, { Component } from 'react';
import {Switch, Router, Route, Redirect} from 'react-router-dom';
import Header from './Header';
import Sidebar from './Sidebar';
import Footer from './Footer';
import PageHome from './Components/PageHome';
import PageAbout from './Components/PageAbout';
import PageContact from './Components/PageContact';
import PageCategoryDetail from './Components/PageCategoryDetail';
import PostDetails from './Components/PostDetails';


class App extends Component{
  
  render()
  {
    return(
      <div>
          <Header />
               <Switch basename="{process.env.PUBLIC_URL}">
		     <Route exact={true} path='/' render={(routeProps) => (<PageHome {...routeProps} PostItems={this.state.PostItemProps} />)} />
		     <Route path='/yazi/:slug' Component={PostDetails} />
		     <Route path='/kategori/:slug' component={PageCategoryDetail}></Route>
		     <Route exact={true} path='/kimim-ben' component={PageAbout}/>
		     <Route exact={true} path='/iletisim' component={PageContact}/>
		     <Route render={this._redirectToHome} />
		 </Switch>
	   <Sidebar />
           <Footer/>
      </div>
    )
  }
}

export default App;
```

## Expected Behavior

When I click on the category links in `<Sidebar />` the first time I want to open the category page. So the URL / category / news is happening and it works correctly.
However, when I click on the link / category / sport in this URL, the url changes but the view still remains in the category / news / view. So the view does not change.

I'm not having this problem I clicked on the links in `<Header />`

I also looked at the solutions of those who had the same problem in Github, but my project still continues.

How else can I fix this problem?

**Comment by StringEpsilon** [comment]
Can you provide a smaller example with the complete code in a small github repository or a [codesandbox](https://codesandbox.io) ?

**Comment by serdarkaraca** [comment]
> Küçük bir github deposundaki kodun tamamını veya bir [kod kutusunu](https://codesandbox.io) daha küçük bir örnek [verebilir](https://codesandbox.io) misiniz?
> 
> Sağladığınız kodda yanlış bir şey göremiyorum.

I'm dealing with adding codesanbox right now. I haven't been there at all yet, I guess it will take some time :)

**Comment by serdarkaraca** [comment]
> Can you provide a smaller example with the complete code in a small github repository or a [codesandbox](https://codesandbox.io) ?
> 
> I can't see anything wrong with the code you provided.

I'm dealing with adding codesanbox right now. I haven't been there at all yet, I guess it will take some time :)

**Comment by StringEpsilon** [comment]
BTW, I have to mention that this is a bug tracker and not a support system. Before submitting a new issue here, you might want to consider asking [StackOverflow](https://stackoverflow.com/questions/tagged/react-router) or on the `react-router` channel on the [reactiflux](https://www.reactiflux.com/) discord server.

If the issue gets closed prematurely, feel free to ping me on reactiflux.

**Comment by timdorr** [comment]
Yup, closing for that reason.

**Comment by serdarkaraca** [comment]
> Can you provide a smaller example with the complete code in a small github repository or a [codesandbox](https://codesandbox.io) ?
> 
> I can't see anything wrong with the code you provided.

https://1326ol8qw4.codesandbox.io/

**Comment by serdarkaraca** [comment]
I made a small version of the project for my problem. When you click the links in the categories you can see that the content has not changed.

https://1326ol8qw4.codesandbox.io/

**Comment by StringEpsilon** [comment]
@serdarkaraca You only get determine the match parameter on mount. But your category component is never unmounted and re-mounted. It's stays mounted through the URL change, but gets a new parameter through the match prop.

https://codesandbox.io/s/lx3x7j0jmz <- in this sandbox, I fixed your bug.
