### ISSUE TITLE
The context `router` is marked as required in `Link` v5.0.0

### ISSUE THREAD

**Issue by orangecoloured** [ReactTraining/react-router#6743]
## Version
**5.0.0**

## Steps to reproduce
I have a private external lib of reusable components. Among others there's a couple of components using Link. These components are built using babel. And I can import them like
`import Component from 'my-components/some/path/Component'`
Using the `4.3.1` version of `react-router-dom` I have no issues. Switching to the version `5.0.0` I have this error `The context `router` is marked as required in `Link`, but its value is `undefined``.

## Expected Behavior
Be able to use my external components that use Link.

## Actual Behavior
An error `The context `router` is marked as required in `Link`, but its value is `undefined``.

**Comment by timdorr** [comment]
You're mixing versions of React Router. 5.0 uses the new React Context API, which is incompatible with the legacy version used in 4.3 and older. You need to make sure to compiling these components with the same version as the host app.

**Comment by orangecoloured** [comment]
I am not mixing versions.
I made sure, both, my app and my external components were using the same react-router version.

**Comment by timdorr** [comment]
It's also important that you're using the same instance of the library. The new Context API requires that we use the Provider and Consumer pair from the exact same createContext call. It's not sufficient that the same code is used. It's up to you how you want to define that singular copy of the library, but most likely a UMD bundle from the sound of it. Depending on how you are bundling things, you'll want to mark React Router as external and include it once as a separate script tag.

**Comment by orangecoloured** [comment]
@timdorr are there any such examples? I'm using `create-react-app`.

**Comment by timdorr** [comment]
Not offhand, mainly because it's very specific to your particular build tooling. But the basic idea would be to add the UMD build of react-router/react-router-dom as a script tag and then make use of window.ReactRouter/ReactRouterDOM.
