### ISSUE TITLE
location.search is empty when we are trying to pass state

### ISSUE THREAD

**Issue by MatteoGioioso** [ReactTraining/react-router#6744]
## Version
```
"react": "^16.5.2",
"react-dom": "^16.5.2",
"react-redux": "^5.0.7",
"react-router-dom": "^4.3.1",
```

## Test Case
Every time I pass some state together with the `pathname`
```
...push({
 pathname: '/somepath?key=value
 state: {...}
})
```
the property `location.search` appears to be empty

I have managed to reproduce the bug in this codesandbox
https://codesandbox.io/s/l550q8o5l

## Expected Behavior
It should populate the `search` property

## Actual Behavior
It only populates the `search` property if the page is reloaded

**Comment by StringEpsilon** [comment]
This is most likely a bug in `history`.

I modified your example to use a normal `Router` and a provided history object from `createBrowserHistory` so I could add a listener. When I click on the buggy button, I get this log:

```json
{
  "hash": "",
  "key": "u926oe",
  "pathname": "/about?name=value",
  "search": "",
  "state": "hello",
}
```

It should instead be 

```json
{
  "hash": "",
  "key": "2b7nm5",
  "pathname": "/about",
  "search": "?name=value",
  "state": undefined,
}
```

I also tested this locally to make sure it's not another codesandbox bug (see #6718 ).
