### ISSUE TITLE
Feature Request - provide ability to further parse/type parameters

### ISSUE THREAD

**Issue by togakangaroo** [ReactTraining/react-router#6745]
Feature Request: Allow automatic parsing of parameters to the appropriate type.

I have the following component:

```
export const EditCandidate = ({match: {params: {id}}}) => {
  const [candidate, setCandidate] = useState(null)
  useOnNotificationAndNow(UserStatusModifiedContext, (x) => {
    if(x && id !== x.id)
      return
    getCandidate(id).then(x => setCandidate(x.data))
  }, [id])
```

note that `if` statement that is checking whether the passed in id is matching the param id.

In the case where ids are numeric this fails as the parameter id is a string. So it should actually be a `!=` but...of course...that's just subject to someone thinking they found a bug and "fixing" it (plus linters yelling at you).

I realize there's about a dozen ways to solve this situation (going to use a render prop for the moment), but it would be nice if react-router could provide a solution. For example instead of this

```
    <Route component={EditCandidate} path="/candidates/:id(\d+)" />
```

if I could do something like

```
    <Route component={EditCandidate} 
                  path="/candidates/:id(\d+)"
                  paramParsers={({id: parseFloat})} />
```
and have the `id` parameter automatically run through the `parseFloat` function after validation.

**Comment by StringEpsilon** [comment]
All parameters are strings, because RR passes them down straight as they come from [path-to-regexp](https://github.com/pillarjs/path-to-regexp/tree/v1.7.0).

I'm not sure that the ability to parse or further validate params beyond that should be part of react-router. You can either write your own alternative `Route` that implements this or do it in your own components.

Another aspect to consider, before implementing this:

* Should a Route match, if one of the paramParsers returns null oder undefined?

That has implications for how `<Switch />` operates.

**Comment by timdorr** [comment]
This creates an API for what should be a userspace problem. If you want to do more complex validation (check the ID against a server endpoint), then this gets pretty crazy pretty quickly. 

It's much easier to just add `const id = parseFloat(this.props.match.params.id)` to your code and call it a day.

**Comment by MeiKatz** [comment]
@StringEpsilon The last point you mentioned is why I think there should be something like this implemented into RR. Maybe not the ability to cast the parameters but to check against some validation function.

**Comment by timdorr** [comment]
@MeiKatz This is already built in via path-to-regexp: https://github.com/pillarjs/path-to-regexp/tree/v1.7.0#custom-match-parameters

**Comment by MeiKatz** [comment]
@timdorr You're right. I missed that.
