### ISSUE TITLE
Why did this happened?console warning  <Route component> will be ignored

### ISSUE THREAD

**Issue by WaSantu** [ReactTraining/react-router#6746]
the consle waring 'Warning: You should not use <Route component> and <Route children> in the same route; <Route component> will be ignored'

`<Switch>
    <Redirect path="/" exact={true} to="/index" />
    <Route component={Index} path='/'>
     <Route path='/index' component={Indexpage}/>
     <Route path='/artical' component={ArticalList}/>
     </Route>
</Switch>`
I already tried like this code 

`<Switch>
    <Redirect path="/" exact={true} to="/index" />
    <Index>
     <Route path='/index' component={Indexpage}/>
     <Route path='/artical' component={ArticalList}/>
     </Index>
</Switch>`

it's not working

**Comment by StringEpsilon** [comment]
What the warning says: You can't use the `component` prop and children at the same time. You can only use `component`, `render` xor children, but not combine any of the three.

The issue with the second code blob seems to be the `<Index/>` component blocking `Switch` from properly working.

Please note that this is not a support platform, but a bug tracker. If you have issues, please consult [StackOverflow](https://stackoverflow.com/questions/tagged/react-router) or the [reactiflux](https://www.reactiflux.com/) discord server. This issue will be closed by a maintainer soon.

**Comment by WaSantu** [comment]
> What the warning says: You can't use the `component` prop and children at the same time. You can only use `component`, `render` xor children, but not combine any of the three.
> 
> The issue with the second code blob seems to be the `<Index/>` component blocking `Switch` from properly working.
> 
> Please note that this is not a support platform, but a bug and feature request tracker. If you have usage questions or want general advice, please consult [StackOverflow](https://stackoverflow.com/questions/tagged/react-router) or the [reactiflux](https://www.reactiflux.com/) discord server. This issue will be closed by a maintainer soon.


Thanks for ur reply,just because the <Index/> component which render for tow times blocking my process.Thank you!
