### ISSUE TITLE
Can you provide some examples?

### ISSUE THREAD

**Issue by xiaofengqqcom123** [ReactTraining/react-router#6749]
version: react-router@5.0.0
1、Official documents not updated
2、I can't find some examples about this

**Comment by MeiKatz** [comment]
Not sure what you are talking about. Anyway, this is a bug tracker, not a wishlist.

**Comment by xiaofengqqcom123** [comment]
How can I find an example about react-router@5.00?
https://react-guide.github.io/react-router-cn/
