### ISSUE TITLE
Behavior for links with target "_self" has changed in v5

### ISSUE THREAD

**Issue by apehead** [ReactTraining/react-router#6750]
Hi!

I'm not sure if this is a bug or not, but since [v4.4.0-beta.4](https://github.com/ReactTraining/react-router/releases/tag/v4.4.0-beta.4) using `target="_self"` in a link component doesn't let the browser handle the route.

The  `target="_self"` approach was dicussed in https://github.com/ReactTraining/react-router/issues/3109, and we have been relying on this for a very long time. 

The change was introduced in https://github.com/ReactTraining/react-router/pull/6138 but I don't understand why, so maybe @ericyang89 can provide more information about it.

We faced this issue when upgrading to v5. I know we can just use anchor tags, but I'd like to know if this change was intended. If so, I think it would be nice to add the new behavior to a breaking changes section.

Thanks!

**Comment by timdorr** [comment]
If you want the browser to handle it, just use an `<a>` tag instead.

**Comment by apehead** [comment]
Thanks @timdorr
