### ISSUE TITLE
compilePath does not find a match on the server does with the supplied code

### ISSUE THREAD

**Issue by dagda1** [ReactTraining/react-router#6763]
## Version

5.0.0

## Test Case

When running this code locally `compilePath#regexp#exec` finds a match but on the server it always returns null.

```
const pathToRegexp = require("path-to-regexp");

const cache = {};
const cacheLimit = 10000;
let cacheCount = 0;

function compilePath(path, options) {
  const cacheKey = `${options.end}${options.strict}${options.sensitive}`;
  const pathCache = cache[cacheKey] || (cache[cacheKey] = {});

  if (pathCache[path]) return pathCache[path];

  const keys = [];
  const regexp = pathToRegexp(path, keys, options);
  const result = { regexp, keys };

  if (cacheCount < cacheLimit) {
    pathCache[path] = result;
    cacheCount++;
  }

  return result;
}

let match = compilePath("\/", {
  end: true,
  strict: true,
  sensitive: false
}).regexp.exec("/");

console.log(match); 
// [ '/', index: 0, input: '/', groups: undefined ] when running here
// but the same code with the same values in production returns null
```

## Expected Behavior

Should return a match on our prod env.

## Actual Behavior

null is returned and I am desperate to know why

**Comment by dagda1** [comment]
I'm fairly sure this is to do with #6201.

I did:

`npm i path-to-regexp -S`

Suddenly everything works.

**Comment by timdorr** [comment]
I would ensure you've installed 1.7.0 with that command, as they have since moved on to 3.0 with significant breaking changes. While that will ensure you're using the right version of the library, you do want to be sure it's the same version as your client.

**Comment by dagda1** [comment]
@dagda1 is this a bug though as it is still the same behaviour as highlighted in #6201
