### ISSUE TITLE
evt.stopPropagation not working in Firefox

### ISSUE THREAD

**Issue by andreasremdt** [ReactTraining/react-router#6768]
## Version

5.0.1

## Test Case

https://codesandbox.io/s/thirsty-fast-2wsz7

## Steps to reproduce

1. Open the CodeSandbox
2. Click on the checkbox inside the "About" link

## Expected Behavior

In **Chrome** and **Safari**, the click on the checkbox doesn't trigger a redirect to the "About" page, since `evt.stopPropagation()` is being used in the event handler.

## Actual Behavior

In **Firefox (latest version)**, this is not working and react-router redirects to the "About" page, which means that the checkbox can't be selected.

**Comment by StringEpsilon** [comment]
This is definitely a firefox but and not a router issue.

Your sandbox also misbehaves when using a normal anchor tag for the link. So the `<Link />` component doesn't do anything wrong specifically.

See also 
* https://bugzilla.mozilla.org/show_bug.cgi?id=62151 
* https://stackoverflow.com/questions/16437188/stoppropagation-and-anchor

**Comment by andreasremdt** [comment]
Oh, I see. Thanks for pointing that out! This issue can be closed in this case.
