### ISSUE TITLE
Missing route params when using multiple match

### ISSUE THREAD

**Issue by Snivik** [ReactTraining/react-router#6771]
When specifying multiple routes in the path, route params get lost in a random behavior. When using same route with string "route", all params are passed back just fine

## Version

4.0.0-beta3 in codepen, 4.3.1

## Test Case

https://codepen.io/snivik/pen/QXLdJo

## Steps to reproduce

Just click on different routes in the preview. You'll see that only working version returns both params in the route

## Expected Behavior

Both "id" and "page" are passed down as params when it matches ["/users/:id/comments/:page", "/users/:id/comments/:page"]

## Actual Behavior
Depending on how you order the array, either :id or :page comes down, but the other one disappears. You can see that on string path it works just fine.

**Comment by timdorr** [comment]
Arrays weren't supported in React Router until version 5. You can't use them with previous versions, as most things will break.

**Comment by Snivik** [comment]
Oh, sorry about that. I've updated prod code & codepen version and now it works fine. There is no mention in docs that this is a recent version thing, and since it recognizes "array" paths in older version as well & I didn't find a mention of the issue on tracker I thought it's just an issue. Good luck!
