### ISSUE TITLE
Still get "invalid prop `path`of type `array`" warning

### ISSUE THREAD

**Issue by johnfiorilla-refundlabs** [ReactTraining/react-router#6772]
## Version

"react-router-dom": "^5.0.0"

## Test Case

https://7crru.codesandbox.io/

Hello,

From what I have gleaned from going over many threads and docs, it seems like the `path` prop of `Route` can fully accept `string || string[]` as of `react-router-dom` v5.0.0.

I have integrated it into the routing architecture in my app, and it works perfectly (which is awesome!). However, I still seem to be getting the classic "Failed prop type: Invalid prop `path` of type `array` supplied to `Route`" console warning as seen below:

```checkPropTypes.js:19 
Warning: Failed prop type: Invalid prop `path` of type `array` supplied to `Route`, expected `string`.
    in Route (created by AuthenticatedAppBody)
...
```

Is there a way I can mute this warning? Is the only way to add `prop-types` to the project and set my own `propTypes`? Appreciate any insight. Please see my snippet below in case I'm using it incorrectly:-

```
const casePaths = [
  `clients/:clientId/add-case`,
  `cases/:ticketId`
];

const AuthenticatedAppBody = () => (
      <div id="AuthenticatedAppBody">
          ...
          <Switch>
            <Route path={casePaths} component={() => <div>hi</div>} />
            ...
          </Switch>
      </div>
)
```

**Comment by timdorr** [comment]
I'm not seeing this with the Codesandbox: https://codesandbox.io/s/7crru 

Here's one where it works: https://codesandbox.io/s/react-router-gywjd and https://gywjd.codesandbox.io/cases/123

One thing of note, you must have absolute paths, so `/clients/:clientId/add-case` and `/cases/:ticketId`.

My best guess is you have mismatched versions of react-router and react-router-dom. You can check with `npm ls react-router`.

**Comment by johnfiorilla-refundlabs** [comment]
Sweet the mismatch was it thank you
