### ISSUE TITLE
How to ignore Router basename in <Link>

### ISSUE THREAD

**Issue by xiaofengqqcom123** [ReactTraining/react-router#6777]
<HashRouter basename="/center">
        <Route to="/focus" component=Focus>
           .....
          <Redirect from="" to='/focus' />
        </Switch>
      </HashRouter>

Focus:
` <Link to="/home">`

this links to "/center/home", when I want it to just go to "/home", what should i do?

**Comment by MeiKatz** [comment]
This is a problem related to the missing support for elative paths. Maybe I announce my pull request on this again so this feature will be added soon (and not until v6).

**Comment by xiaofengqqcom123** [comment]
Do you know any other plans?

**Comment by MeiKatz** [comment]
No, sorry, no ways related to React Router.

**Comment by pshrmn** [comment]
The `basename` applies to every location within the application, i.e. every `pathname` within your application would begin with `/center`. If you want to link to a location that does not begin with the basename `/center` (a location that is _not_ within your application), you should use an anchor (`<anchor href="/home">`).

**Comment by xiaofengqqcom123** [comment]
thank you
