### ISSUE TITLE
add href prop to Link

### ISSUE THREAD

**Issue by TrejGun** [ReactTraining/react-router#6780]
Hi there
Yeah I know you dont want to add this because you have reasons but listen to my reasons to add it

first of all I'm not asking to replace `to` with `href` for backward compatibility

Link component is often consumed through other libraries

for example
https://material-ui.com/components/links/
https://react-bootstrap.github.io/components/navs/
https://atlaskit.atlassian.com/packages/core/button

all or at least most of them implements `href` so users code looks like this

```js
import {Link} from "@material-ui/core";
import {Link as RLink} from "react-router-dom";

export default function MyLink (){
  return <Link href="#" to="#" component={RLink}>text</Link>
}
```

This way we have to support `href` because it is marked as required prop from the UI lib and `to` as it actually does the job this is super annoying 

Link's `to` supports strings, objects and now functions so may be you want to consider to add `href` as alias to string variant with some addititonal optimization

**Comment by timdorr** [comment]
That would be the fault of the library then. We're not going to change our API because someone is using it incorrectly, sorry.

**Comment by TrejGun** [comment]
![13757956923171](https://user-images.githubusercontent.com/185285/59496467-8b094f00-8ea2-11e9-994b-69a69cd60bcd.jpg)
