### ISSUE TITLE
[react-router-config] matched params should not contain the query string

### ISSUE THREAD

**Issue by wszgxa** [ReactTraining/react-router#6781]
## Version
version: `5.0.1`, `1.0.0-beta.4`, I guess `version 4` also have this issue.
Related issue: https://github.com/ReactTraining/react-router/issues/5132

Because the old issue is closed, I can't comment. So I open this one. 

## Steps to reproduce

```
var matchRoutes = require('react-router-config').matchRoutes;

function noop() {}

var routes = [
  {
    path: '/search/:slug',
    component: null,
    loadData: noop
  },
];

var branch = matchRoutes(routes, '/search/news?test=teststing');

console.log(branch[0]); 
```
the result will be:
```
{ route:
   { path: '/search/:slug',
     component: null,
     loadData: [Function: noop] },
  match:
   { path: '/search/:slug',
     url: '/search/news?test=testString',
     isExact: true,
     params: { slug: 'news?test=testString' } } }
```

![query-strings](https://user-images.githubusercontent.com/6060475/59407415-b37e4400-8de3-11e9-8691-622284512a4d.png)
As the definition, URL params and search query string should be different.

We can just parse the full URL, but I think it should be done in react-router-config.

## Expected Behavior

Params should not contain the search query string `?test=testString`

## Actual Behavior

Params contain the search query string

**Comment by wszgxa** [comment]
I have done a quick spike:

It's restricted by the `path-to-regexp`: 
> The RegExp returned by path-to-regexp is intended for ordered data (e.g. pathnames, hostnames). It can not handle arbitrarily ordered data (e.g. query strings, URL fragments, JSON, etc).

So it will not handle `query string` and `url fragments`.


I think the correct behavior should be:

1. Match path should only depend on the router parameter
2. The match results should return the query string.

We can split the pathname to `router parameter` and `query string` at here: https://github.com/ReactTraining/react-router/blob/master/packages/react-router/modules/matchPath.js#L43
And then parse the query string, match the path, combine the results.

If you agree with the above, I am very happy to send a PR.

**Comment by timdorr** [comment]
`matchRoutes`' second arg is the pathname, not a full URL. You need to specifically obtain the pathname before you call it.

**Comment by wszgxa** [comment]
Okey. I need to parse the URL and pass the URL data to the client side.
