### ISSUE TITLE
Nesting with RouteWithSubRoutes not working along with Switch & without Switch Not able to add Default route

### ISSUE THREAD

**Issue by storesbuzz** [ReactTraining/react-router#6783]
## Version
^5.0.0

## Test Case
Implemented same Route Config solution shared at https://reacttraining.com/react-router/web/example/route-config

## Steps to reproduce
In case your component 'RouteConfigExample' in example modified as follow to display only routes in whole page.
```js
function RouteConfigExample() {
  return (
    <Router>
      <div>
        {routes.map((route, i) => (
          <RouteWithSubRoutes key={i} {...route} />
        ))}
      </div>
    </Router>
  );
}
```
## Expected Behavior
Should support Default Route

## Actual Behavior
Added default route is getting rendered in each sub routes as we don't have Switch over parent routes.

**Comment by timdorr** [comment]
Switch doesn't work with nested routes, only the ones described at the top level. You will need to convert your route structure to a flat list.
