### ISSUE TITLE
react-router - Unable to resolve “warning” from "node_modules/react-router/MemoryRouter.js

### ISSUE THREAD

**Issue by Larney11** [ReactTraining/react-router#6785]
Hi,

I was using react-router-native **version 4.3.0** and recently **upgraded to 5.0.1**.

The app will no longer run and I get the following error on the terminal:
_Unable to resolve "warning" from "node_modules/react-router/MemoryRouter.js"_

The simulator displays a similar error:
**_Unable to resolve "warning" from "node_modules/react-router/MemoryRouter.js.
MemoryRoter.js does not exist in the Haste module app"_**

I have reviewed the [change log](https://github.com/ReactTraining/react-router/releases) and there should be no problem with the upgrade.

Any help is greatly appreciated.

**Versions**
React: 16.5
react-router: ^5.0.1,
react-router-native: 5.0.1
expo: 32.0.0

This is what I had working before the update:
```
     import { NativeRouter, Route, withRouter } from 'react-router-native';
        
        render() {
          return(
                      
            <NativeRouter>
                <Route exact path="/" component={ HomeScreen }/>
                <Route path="/login/" component={ LoginScreen }/>
                <Route path="/activate/" component={ ActivateScreen } />
                <Route path="/athlete/" component={ AthleteScreen } />
                <Route path="/activity/" component={ ActivityScreen } />
            </NativeRouter>
          ) 
    }
```

**Comment by timdorr** [comment]
This isn't an error with the library. Something didn't install the library correctly, which isn't anything we can help with here.
