### ISSUE TITLE
Suggestion to change documentation on <Route>'s render prop

### ISSUE THREAD

**Issue by cbdeveloper** [ReactTraining/react-router#6786]
I have a suggestion for the documentation.

I'm using the **render prop** from the "Route" component to implement protected routes.

https://reacttraining.com/react-router/web/api/Route/render-func
And this example from the link above got me really confused since the first time I read it.

> render: func
> The render prop receives all the same route props as the component render prop.

After reading the line from the quote above, I immediately began thinking that the components that I'll render with the `render` prop will automatically receive the router `props` as it happens with when I use the `component` props.

And this example only made things worse for me.

```
const FadingRoute = ({ component: Component, ...rest }) => (
  <Route {...rest} render={props => (
    <FadeIn>
      <Component {...props}/>
    </FadeIn>
  )}/>
)
```

The `props` parameter inside the render `prop` is basically the **router props** `match`, `history`, and `location`, right?

I spent a long time thinking that these `props` were refering to the parent component `props`. That is **not true** and also when you name it as `props` it **also **shadows** the `props` that are coming the parent component**, then you can't access the parent props.

Imagine that someone would like to do something like this:

```
function Parent(props) {
  return(
    <Route path='/' render={(props)=>{
       return(
         props.userFromParent ?   // THAT CAN'T BE DONE BECAUSE INNER 'PROPS' IS SHADOWING OUTER 'PROPS'
           <ProtectedComponent/>
         : <Login>
       );
    }}/>
  );
}
```

---

I think this example would be better:
- Naming the render prop `props` as `routerProps` instead of `props`.
- I suggest doing that also for other examples that name the `routerProps` as `props`

```
const FadingRoute = ({ component: Component, ...rest }) => (
  <Route {...rest} render={routerProps => (
    <FadeIn>
      <Component {...routerProps}/>
    </FadeIn>
  )}/>
)
```

Also I think it should be clear that if you need the `routerProps` inside the Component that you're rendering... you need to spread them like in the example. 

> render: func
> The render prop receives all the same route props as the component render prop.

The line above made me think that it would be automatic.

What do you guys think?

**Comment by timdorr** [comment]
That seems fine to me. Can you submit a PR?

**Comment by cbdeveloper** [comment]
@timdorr I've created PR https://github.com/ReactTraining/react-router/pull/6792 . That is my first PR ever. If you can, please check to make sure everything is ok. Thanks!
