### ISSUE TITLE
HEEEEEELP!!

### ISSUE THREAD

**Issue by mjackson** [ReactTraining/react-router#6787]
Somebody please help me! I can't get my code to work!

**Comment by mjackson** [comment]
@timdorr @pshrmn @StringEpsilon when someone asks a support-type question, we now have the `support` label that we can apply so they know where they can get help.

**Comment by StringEpsilon** [comment]
I'd still include the invitation to "repeal", but this should help in cutting down the issues. And poor @timdorr won't have to take the blame anymore ;-)

> Please feel free to clarify your issue if you think it was closed prematurely.

**Comment by mjackson** [comment]
Happy to accept a PR :)
