### ISSUE TITLE
Failed prop type: Invalid prop 'component' supplied to 'Route': the prop is not a valid React component

### ISSUE THREAD

**Issue by Kashio** [ReactTraining/react-router#6791]
I have a reference to an object containing `getComponent(...)` method for obtaining a React component.
I try to render this component inside a nested route like so:
```
const component = React.cloneElement(object.getComponent(...), {...});
<Route path={`home/${object.route}`} component={component}/>;
```
and I get the following error:
`Failed prop type: Invalid prop 'component' supplied to 'Route': the prop is not a valid React component`.
I've seen similar issues like [6741](https://github.com/ReactTraining/react-router/issues/6471)
where the issue is resolved by upgrading the library version to `react-router-dom@5.0.0`, but my dependencies are up-to date:
```
"react": "^16.4.2",
"react-dom": "^16.4.2",
"react-router-dom": "^5.0.0"
```

Any ideas on how can I solve this problem ?

**Comment by timdorr** [comment]
Do you also have react-is installed? That needs to be the same version as React for it to work.
