### ISSUE TITLE
Anchor links in the website is leading to home page

### ISSUE THREAD

**Issue by moshfeu** [ReactTraining/react-router#6794]
Steps, for example

1. Go to https://reacttraining.com/react-router/web/guides/quick-start
1. Click on "installation"

<img width="493" alt="Screen Shot 2019-06-17 at 23 09 09" src="https://user-images.githubusercontent.com/3723951/59633365-02660980-9155-11e9-8c24-d129e7741d4a.png">

## Expected Behavior
Should leads to https://reacttraining.com/react-router/web/guides/quick-start#quick-start-installation

## Actual Behavior

Leads to https://reacttraining.com/react-router/web/guides/quick-start/installation and then redirect to https://reacttraining.com/react-router/web/guides/quick-start/installation

It's true for all of the links in that page.

Thanks

**Comment by timdorr** [comment]
It's the same for all the other guides as well. The API appears to be fine.

**Comment by moshfeu** [comment]
The API? Do you mean that the problem is with the docs but not with the library's API? If so, I agree.

**Comment by timdorr** [comment]
I mean the API pages.

**Comment by pshrmn** [comment]
I'm still piecing together the issue (there is a `Redirect` happening because of an issue with the `/react-router` basename that is getting matched by a route for some reason) because it only exists on the live site, but I should be able to get a fix put together later today.

**Comment by timdorr** [comment]
That fix should be going out now.

**Comment by moshfeu** [comment]
Confirmed, Thanks.
