### ISSUE TITLE
Feature Request - Render Link component from text string on the client

### ISSUE THREAD

**Issue by cbdeveloper** [ReactTraining/react-router#6796]
I don't know how frequent my use case is, but my situation is the following.

I'm building a website (single page app with client-side routing) that is like an ecommerce but it also has a blogging section. I'm currently building an admin form `AddBlogPost` for the admins to add new `blogPosts` to the website.

So the form has lots of **textareas** and **file inputs** so the admin can create the elements for the `blogPost`, upload the images to storage and save text content and image src's to the database.

But what happens is that inside some paragraphs of the `blogPost`, sometimes it will be necessary to **add links to other sections (products), or even other posts of the website.** And this is done inside a `textarea` along with the text value for the content of the paragraph.

I'm currently doing this:

```
"This is a blogPost paragrah, you can also check this [other blog post]('path/to/other/blog/post')
```

That basic hyperlink syntax `[link description](linkURL)` which I'm currently replacing with an `<a>` tag and rendering it as html markup by using `dangerouslySetInnerHTML`.

It works, but since I'm not using the `Link` component, **my App refreshes when I click on the link.**

It would be nice if the router had some helper function that I could send a text containing basic hyperlink syntax and that function would automatically replace all occurences of the pattern [link description](linkURL) with a corresponding `Link` component. 

I really don't know how it would be implemented and I really have no idea how feasible this is. Or if it would help other developers.

What do you guys think?

**Comment by StringEpsilon** [comment]
I think this is way to special use case for being part of core `react-router`.

**Comment by timdorr** [comment]
Yeah, this really has very little to do with React Router. You need to write a Markdown parser that emits React components. That's not something we can help with.

**Comment by cbdeveloper** [comment]
Thank you. You are right. Also, I've found out this package that might help with this task: https://www.npmjs.com/package/react-html-parser
