### ISSUE TITLE
browser back error

### ISSUE THREAD

**Issue by xianweics** [ReactTraining/react-router#6799]
## Version
```
"react": "latest",
"react-dom": "latest",
"react-router-dom": "latest"
```
**Please replace this sentence with the React Router version that you are using.**

## Test Case

https://codesandbox.io/s/7zwjlm2j3q

## Steps to reproduce

1. Click 'About' button more than once.
2. Click back icon once in the embed browser. 

Now you will find that url hasn't been changed.

## Expected Behavior

When I click back icon once, the url changes and goes back to homepage instead of 'About'.
## Actual Behavior

 The url hasn't been changed. The route can't go back to homepage until you click back icon many times. I know when I click navigation 'About' once, the react-router will push history once. It will push once after I click 'About' again, so that I cannot able to reach homepage. 

Please help me solve this problem.

**Comment by StringEpsilon** [comment]
@timdorr This isn't a support question. The issue as described is replicable.

Compare:

* #5897
* #5500
* #5362
* #5039 
* #5363

Also see history https://github.com/ReactTraining/history/issues/470

I agree with all previous issues that the proper fix should be implemented in history. But Maybe we should just let one instance of this issue open here, reference the history issue and lock it. That might help prevent people from reopening it a 7th time.

**Comment by xianweics** [comment]
> @timdorr This isn't a support question. The issue as described is replicable.
> 
> Compare:
> 
> * #5897
> * #5500
> * #5362
> * #5039
> * #5363
> 
> Also see history [ReactTraining/history#470](https://github.com/ReactTraining/history/issues/470)
> 
> I agree with all previous issues that the proper fix should be implemented in history. But Maybe we should just let one instance of this issue open here, reference the history issue and lock it. That might help stop people from reopening it a 7th time.

thx.
