### ISSUE TITLE
Component unmounting after every route change

### ISSUE THREAD

**Issue by Werter12** [ReactTraining/react-router#6804]
Let' say we have the following code. I am trying to figure out is the component unmounting previuos component and mount new  will be triggered every time we click on the Link with new route? 
Profile, Home, Dasboard class components in which I added console logs for `componentDidMount` and `componentWillUnmount` lifecycle hooks. Every transition leads to `unmount` previous component and `mount` new. Is it expected behavior? (I added the `Dashboard` route with function in component attribute -  intentionally because it behaves the same like other and I don't see a difference)

```
      <Router>
        <div>
          <nav>
            <ul>
              <li>
                <Link to="/">Home</Link>
              </li>
              <li>
                <Link to="/profile">Profile</Link>
              </li>
              <li>
                <Link to="/dashboard">Dasboard</Link>
              </li>
            </ul>
          </nav>
          <Switch>
            <Route path="/" exact component={Home} />
            <Route path="/profile" render={(props) => <Profile {...props} />} />
            <Route path="/dashboard" component={() => <Dasboard />} />
          </Switch>
        </div>
      </Router>
```

**Comment by pshrmn** [comment]
The `Switch` only renders the route that matches. When you navigate to a new location, the old location's matched route will unmount and the new location's matched route will mount.

If you have a nested route (e.g. `/profile/user`) where the `Profile` component renders a switch to differentiate between `/profile` and `/profile/user`, then navigating between those locations will not unmount the `Profile`.

```jsx
function Profile({ match }) {
    return (
      <Switch>
        <Route exact path={match.path} component={BaseProfile} />
        <Route exacth path={`${match.path}/user`} component={User} />
      </Switch>
    );
}
```

**Comment by Werter12** [comment]
@pshrmn Thanks!
