### ISSUE TITLE
Modal Route with server side rendering

### ISSUE THREAD

**Issue by singlepageprogrammer** [ReactTraining/react-router#6805]
Hello.
how i can make a modal route with server side rendering (for example like instagram.com) ?

[click on any post in instagram and see what happens ...](https://www.instagram.com/diarioas/?hl=en)

i have this :
```
// Routes.js
import React from "react";

import { asyncComponent } from "@jaredpalmer/after";

import Load from "../components/helpers/Load";

export default [
  {
    name: "Main",
    path: "/",
    exact: true,
    component: asyncComponent({
      loader: () =>
        import(/* webpackChunkName: "Home" */ "../components/views/main/Main"),
      Placeholder: () => <Load />
    })
  },
  {
    name: "NotFound",
    exact: true,
    component: asyncComponent({
      loader: () =>
        import(
          /* webpackChunkName: "NotFound" */ "../components/views/NoMatch"
        ),
      Placeholder: () => <Load />
    })
  }
];
```
how i can use Switch and control location for handle this routes ?
how i can check the location state ?
i can handle this in client side but i need to handle server side with that routes.
bc i have to fetch data from server and just i can fetch server side when i have a server route.
anyone can help me ?

**Comment by pshrmn** [comment]
Modal sites display different content when directly navigating to a location vs opening it as a modal. You can check this [example](https://reacttraining.com/react-router/web/example/modal-gallery) for a reference on how this is done on the client; the server implementation would be pretty much the same.
