### ISSUE TITLE
react-router@3.2.2 miss `umd` folder

### ISSUE THREAD

**Issue by zombieJ** [ReactTraining/react-router#6811]
version 3.2.2 miss the `umd` folder cause build failed.

ref:
* https://unpkg.com/react-router@3.2.1/
* https://unpkg.com/react-router@3.2.2/

**Comment by Leannechn** [comment]
+1

**Comment by chvin** [comment]
+1

**Comment by timdorr** [comment]
Whoops. I'll get a 3.2.3 out with the UMD build included later this morning. Stick with 3.2.1 for now if you need it.

**Comment by timdorr** [comment]
OK, I just published 3.2.3. Sorry about missing that!
