### ISSUE TITLE
Link not passing state to location.state in FireFox

### ISSUE THREAD

**Issue by rralbritton** [ReactTraining/react-router#6813]
## Version
react-router-dom": "^4.3.1
react-dom": "^16.4.2

## Test Case
Example: 
             <Link to={{
                  pathname: `/facilities/permits/permitplanapproval/${this.props.id}`,
                  state: { facility: facility }
                }}>Create</Link>

## Steps to reproduce
pass props as state in Link within FireFox (67.0.2 (64-bit))
(works in Chrome)

## Expected Behavior
receive props as state in this.props.location.state

## Actual Behavior
location.state = undefined
even if I code in something like if(!this.props.location.state){ return <div>Loading...</div>
props never show up in state

Note: I am not using withRouter
only connect (i.e. export default connect(mapStateToProps)(PermitInfo);)

**Comment by pshrmn** [comment]
Please ensure that you are reading the correct location. If you use `location` without grabbing it from the React Router props, then you will be accessing `window.location`, which has no `state` property (the current location's `state` is accessible via `history.state`)

https://codesandbox.io/s/distracted-rain-9wyjf

**Comment by rralbritton** [comment]
@pshrmn -

My mistake for not being more clear. The example I provided location has been decontructed. I am actually looking at this.props.location.state
And state is undefined.
But it is not undefined in Chrome

**Comment by pshrmn** [comment]
@rralbritton If you can provide a small reproducible demo (either a [sandbox](codesandbox.io) or a repo that I can clone) I can take a look at it; as is I don't have enough information to make a guess at what is happening.
