### ISSUE TITLE
Passing an object to the path prop of the Route component

### ISSUE THREAD

**Issue by bensampaio** [ReactTraining/react-router#6814]
I am currently working on a SPA with multiple routes which always require the user to have certain permissions to be accessed. This means that my routes should somehow be aware of permissions. To solve that I created the `AuthRoute` component which receives all the same props as a `Route` component plus the `permissions` prop. It looks like this:

```jsx
<AuthRoute component={SomeScreen} path="/some/path" permissions={['FEATURE_NAME']} />
```

* When the route matches and the user has permissions it simply renders a `Route` component with the exact same props except the `permissions` prop.
* When the route matches but the user hasn't permissions it renders a `NotFound` component.

This works well with the `Switch` component because it has the exact same signature as `Route` components except that it receives an extra prop.

I have been using this solution for a while and I am quite happy with it. However, there are some improvements I would like to make to it but I am blocked by the current implementation of the `Switch` component. I would like to be able to pass a list of paths to the `path` prop and specify their permissions. Something like:

```jsx
const paths = [
  { pathname: "/first/path", permissions:['FEATURE_NAME_1']},
  { pathname: "/second/path", permissions:['FEATURE_NAME_2']},
];

<AuthRoute component={SomeScreen} path={paths} />
```

However, this won't work because internally `Switch` expects every path to be a `string`. So my question is: would it be possible to support the ability to pass an object as a path to a `Route` component? This object would respect the exact same structure as the ones that can be passed to the `Link` components. Basically something like this:

```jsx
<Route component={SomeScreen} path={{ pathname: '/some/path' }} />
<Route component={SomeScreen} path={[{ pathname: '/first/path' }, { pathname: '/second/path' }]} />
```

In this way, I would be able to inject the permissions in those objects, `Switch` would determine which route matches and in my `AuthRoute` component I would be able to determine the necessary permissions based on the matched route.

In the future, this idea could even be expanded to support routes that target only query params or hashes. This is just an idea, not something I require. Something like:

```jsx
<Route component={SomeScreen} path={{ hash: '#/some/path' }} />
```

Would this be possible? Or would this add way too much complexity?

**Comment by pshrmn** [comment]
I would encourage you to write a custom switch component. I think that you could copy the source code form React Router's `Switch` and modify it to do what you want.

```js
React.Children.forEach(this.props.children, child => {
  if (match == null && React.isValidElement(child)) {
    element = child;

    const path = Array.isArray(child.props.path)
      ? child.props.path.map(item => item.pathname)
      : child.props.path.pathname;
    match = path
      ? matchPath(location.pathname, { ...child.props, path })
      : context.match;
  }
});
```

**Comment by timdorr** [comment]
This is pretty use-case specific, not something we should adopt as a general API.

**Comment by MeiKatz** [comment]
There are plans for RR 5.1 / 6.0 that there will be a `validate` property for `<Route />` components. That's not exactly what you are looking for, but you could use it as starting point for your custom problem.

**Comment by bensampaio** [comment]
@pshrmn thanks for the suggestion, I had the same idea. That's actually what lead me to write this issue. I would like to avoid creating my own `Switch` component because that might make it more difficult to upgrade `react-router` in the future. But I'll give it some thought again.

@MeiKatz is there any place where I could read about this `validate` prop? Thanks!

**Comment by MeiKatz** [comment]
@bensampaio Ryan Florence mentioned the `validate` prop in the [latest blog entry](https://reacttraining.com/blog/reach-react-router-future/). It will work something like that (warning: currently it is just a proposal and might change!):

```jsx
<Route
  component={SomeScreen}
  path="/first/path"
  validate={() => hasPermission("FEATURE_NAME_1")}
/>
<Route
  component={SomeScreen}
  path="/second/path"
  validate={() => hasPermission("FEATURE_NAME_2")}
/>
```
