### ISSUE TITLE
Error: Invariant failed: You should not use <Switch> outside a <Router>

### ISSUE THREAD

**Issue by jazblueful** [ReactTraining/react-router#6815]
## Version

**5.0.1**

## Steps to reproduce

I have a monorepo setup:
```
apps/
  app1/
    lib/
      app.js <- webpack output
    src/
      App.tsx <- webpack entry
packages/
  server/
    src/
      server.tsx
```

App.tsx
```typescript
import { Switch, Route } from 'react-router-dom';
...
const App = () => (
  <Switch>
    <Route path="/" exact component={Home} />
  </Switch>
);

export default App;
```
server.tsx
```
import { renderToString } from 'react-dom/server';
import { StaticRouter } from 'react-router-dom';

import App from '../../../apps/app1/lib/app'; // Error: Invariant failed: You should not use <Switch> outside a <Router>
// import App from '../../../apps/app1/src'; // everything works as expected
...
renderToString(
  <StaticRouter location={location} context={context}>
    <App />
  </StaticRouter>
);
...
```
## Expected Behavior

No error is thrown

## Actual Behavior

False positive error is thrown: "Error: Invariant failed: You should not use \<Switch\> outside a \<Router\>"

**Comment by StringEpsilon** [comment]
This error is often thrown when multiple instances of `react-router` are included in the final bundle(s).

I started a first aid gist, but it's not gotten a lot of love since the reports died down. Might still help you:

https://gist.github.com/StringEpsilon/88c7b049c891425232aaf88e7c882e05

**Comment by timdorr** [comment]
https://github.com/ReactTraining/react-router/issues/6789#issuecomment-502490351
