### ISSUE TITLE
Nested react router with user authentication

### ISSUE THREAD

**Issue by paufar** [ReactTraining/react-router#6817]
I am trying to make my app use nested React routers to navigate through my app but am not managing to do the following: I have a router to switch between the login page and the homepage and a router in the homepage to switch between the body content

Return to login page on clicking log out. If i click logout the url goes to /login but does not render the right component. Upon refreshing the page the right component is rendered.

When inputing a direct page in the url eg. localhost:3000/about, the page doesn't load anything

My desired functionality is the following:

On load of localhost:3000/ - If user is logged in it loads the "About" component ELSE if user is logged out it is redirected to /login
On load of localhost:3000/contact - If user is logged in it loads the homepage and switches the body content to show the contact component , if user is logged out it redirects to the login page but on login takes the user to the contact component
Clicking log out returns to the login component
I have added the source code here: https://codesandbox.io/embed/loving-engelbart-x3ns3
The first router is in App/App.jsx and the body content router is in _pages/HomePage.jsx
Unfortunately i had to remove the login authentication so the login does not work but maybe there is a clear issue with my code that can be outlined.

Thanks

**Comment by MeiKatz** [comment]
This is also a case for the `validate` prop of the `<Route />` component, that might be added in React Router 5.1/6.0. Currently there is no really good solution for this. Maybe you should create your own `<Switch />` component for your use case.

**Comment by paufar** [comment]
I did create 2 Switch components but it's not working
