### ISSUE TITLE
nested routes keep rerendering

### ISSUE THREAD

**Issue by sibelius** [ReactTraining/react-router#6818]
## Version

**Please replace this sentence with the React Router version that you are using.**
^5.0.1

## Test Case

https://github.com/sibelius/nested-rerender
https://codesandbox.io/s/github/sibelius/nested-rerender

## Steps to reproduce

Go to codesanbox demo, click on Nested Tab A link, then click on Nested Tab B, and you will see that both Main and Nested components will rerender, but they should not.

You can also clone the github repo, and run `yarn start`

## Expected Behavior
It should not rerender "parent" components of nested routes

## Actual Behavior
It is rerender all components that match the nested path

I think this is caused because `<Route>` subscribe to ReactRouter context, keep all Route rerendering

We need something similar to react-redux approach to only rerender components that needs to be rerender

My idea is to avoid rerender is to only rerender Route when `match` state change

I've tried something like this:

```jsx
const hasMatch = (props) => {
  const location = props.location || location;
  const match = props.computedMatch
    ? props.computedMatch // <Switch> already computed the match for us
    : props.path
    ? matchPath(location.pathname, props)
    : false;

  return match;
};

export default memo(Route, (
  prevProps, nextProps
) => {
  const prevMatch = hasMatch(prevProps);
  const nextMatch = hasMatch(nextProps);

  console.log('memoRoute: ', prevMatch, nextMatch, nextProps.location, nextProps.path);
  return prevMatch === nextMatch;
});
```

It is breaking because I can't access context on `memo`

**Comment by StringEpsilon** [comment]
You sure this is new in 5.0? I get the same console output when I change the version to 4.3.1 in your sandbox.

I also don't think the additional rerenders qualify as a bug. It should not cause any issues whatsoever. Even performance impact should be negligible, since route changes don't happen very frequently.

**Comment by MeiKatz** [comment]
@StringEpsilon Yes and no. Performance is the one side, but think about related actions on mounting. Maybe there are AJAX requests or similar, that take some time, and that get started on every path change.

**Comment by StringEpsilon** [comment]
@MeiKatz They should not remount, just rerender. React pretty much takes care of that if you have class component or memoized functional component.

**Comment by sibelius** [comment]
This is causing a delay of 2/3 seconds in our app, when moving from one route to another

this codesanbox solves the problem using shouldComponentUpdate: https://codesandbox.io/s/nested-rerender-cv7g9?fontsize=14

```jsx
import React, { Component } from "react";
import equal from "fast-deep-equal";

const propsWithoutLocation = props => {
  const { location, ...rest } = props;
  return rest;
};

export default WrappedComponent => {
  class HOC extends Component {
    shouldComponentUpdate(nextProps) {
      if (
        equal(propsWithoutLocation(nextProps), propsWithoutLocation(this.props))
      ) {
        return false;
      }
      return true;
    }
    render() {
      return <WrappedComponent {...this.props} />;
    }
  }
  return HOC;
};
```

**Comment by pshrmn** [comment]
This is the expected behavior in a React application; the `Router` is informed of the navigation and schedules an update. Barring update blockers (`sCU`, `memo`) or React's internal optimizations (skipping re-rendering the same element), the entire tree will be re-built.

Have you tried using the React Dev Tools profiler to see which components take so long during the navigation? A delay of 0.6 seconds seems astronomical; I can't picture a situation where this delay is caused by React Router's components.

**Comment by MeiKatz** [comment]
@StringEpsilon My mistake. I read "remount" instead of "rerender".

**Comment by timdorr** [comment]
Correct, this isn't a React Router issue. You have performance issues elsewhere if it's taking hundreds of milliseconds to render your component. Unfortunately, that's not something we can assist with.
