### ISSUE TITLE
Remove react-is in favor of PropTypes.elementType

### ISSUE THREAD

**Issue by croraf** [ReactTraining/react-router#6819]
`prop-types` has introduced `elementType` so you can remove `react-is` dependency, right?

For example in here: https://github.com/ReactTraining/react-router/blame/master/packages/react-router/modules/Route.js#L82-L88

**Comment by timdorr** [comment]
Yep, although that uses react-is under the hood, I believe. A PR would be appreciated.

**Comment by croraf** [comment]
Indeed it is using react-is under the hood: https://github.com/facebook/prop-types/blob/master/factoryWithTypeCheckers.js#L285-L295
