### ISSUE TITLE
Website down - https://reacttraining.com

### ISSUE THREAD

**Issue by thexpand** [ReactTraining/react-router#6820]
It's been down for more than a week already.
It shows up Cloudflare's Error 522 - Connection timed out:
![Screenshot from 2019-07-08 17-16-26](https://user-images.githubusercontent.com/14979167/60817349-29d45300-a1a4-11e9-9edf-5a495dd72dd2.png)

**Comment by timdorr** [comment]
This isn't a React Router issue. It's with the parent React Training website. We don't control that, so you should reach out to @mjackson and/or @ryanflorence directly.

**Comment by thexpand** [comment]
@timdorr I sent an e-mail to @mjackson and @ryanflorence but none of them responded. What's next? Recently I started doing React development and I've been trying to reach out the docs of react-router, but with no success. Are they accessible elsewhere, say in a repository on GitHub?

**Comment by pshrmn** [comment]
@thexpand please see https://github.com/ReactTraining/react-router/issues/6797.

**Comment by thexpand** [comment]
@pshrmn Thanks, I've posted a comment there, too. Let's hope they'll fix it soon. Seems like it's been almost a month since it's been down.
