### ISSUE TITLE
The state passed to "to" prop as object in "Link persists even on refresh .

### ISSUE THREAD

**Issue by pk936** [ReactTraining/react-router#6821]
I am using react router dom 5. I dont know whether its a bug or feature, but I could not find anything helpful from docs about this.

```
<Link to={{pathname: '/app/tasks', state: { category: 'allTasks'}}}
>All Tasks</Link>
```

When I click on all task button and then navigate to routed page, I can access the state value in the component as props. But this state value remains there even after I refresh the page.

Is this a bug and is it normal ? Also, please add more info in document about Link's state and other things.

**Comment by pshrmn** [comment]
This is how the browser's [History API](https://developer.mozilla.org/en-US/docs/Web/API/History_API#The_pushState()_method) works. The provided state is associated with that specific location in the browser's session history. If you refresh or if you navigate to a new location and then click the browser's back button, that state is still associated with the location in the session.

In general, I would recommend not using state for anything but ephemeral data (e.g. a location to redirect to after a user logs in). State doesn't exist when a user navigates directly to a page (via the address bar or from an external link), so you cannot rely on it to exist.
