### ISSUE TITLE
Nested Routes don't work unless the same Route reference is used

### ISSUE THREAD

**Issue by xlash123** [ReactTraining/react-router#6825]
This happens when subrouting different components in multiple files. I have been able to get around this by passing the Route component as a prop to the component I'm trying to route and then using that same Route object to route to another component.

The documentation only shows examples where all components exist in one file, so this weird occurrence was hard to diagnose.

## Version

react-router-dom v.5.0.1

## Test Case

https://codesandbox.io/s/react-router-basic-ip907

## Steps to reproduce
1. Crete a component in a JS file and have it Route to another component in a different file.
2. Create another route within the routed file to another component (either in the same file or another).

## Expected Behavior
All routes should successfully load their routed components.

## Actual Behavior
The route doesn't load the seemingly matched component.

## Edit
Ah, I see what the issue is. When importing BrowserRouter across multiple files, it breaks. When directly importing Route from 'react-router-dom' however, it works. Not sure whether or not I should close this issue.

The code, in case what I said wasn't clear: https://codesandbox.io/s/react-router-basic-ss2bs

**Comment by timdorr** [comment]
```js
import { BrowserRouter as Route, Link } from "react-router-dom";
```
`BrowserRouter` isn't a `Route` component type. It's a `Router`, hence the name. `Router`s don't accept the props you're giving them.
