### ISSUE TITLE
Trying to encode search string to use with history.push(URL)

### ISSUE THREAD

**Issue by cbdeveloper** [ReactTraining/react-router#6827]
I have a search input that I need to send the encoded search string to the URL by using:

`history.push('/search/encodedSearchString');`

So far I'm not able to do this. By now, what I got is:

**Search string:** 
`this is á test`

**Result visible in the URL:** 
`http://localhost:8080/search/this%20is%20á%20test`
**Note:** see that the accented char `á` is not encoded.

**EXTRA: Somehow, when I copy it (from URL bar) and paste it here, it becomes:**
`http://localhost:8080/search/this%20is%20%C3%A1%20test`
**Note:** see that the accented char `á` becomes encoded. I didn't expect that, by the way.

I did my best to follow through this issue: https://github.com/ReactTraining/history/issues/505
Also this PR https://github.com/ReactTraining/history/pull/656

I tried both:

`history.push('/search/' + inputValue);`
`history.push('/search/' + encodeURI(inputValue));`

Both produce the same results.

Is this a normal behavior? Shouldn't accented characters also be encoded in the URL bar? Am I doing something wrong? What's the workaround to this?

I'm using: 

```
"react": "^16.8.6",
"react-dom": "^16.8.6",
"react-router-dom": "^5.0.0",
```

**Comment by pshrmn** [comment]
Your expectations are correct. However, the `history` fix hasn't been released and I'm not exactly sure what the timeline on that getting released is. Sorry!

[This comment](https://github.com/ReactTraining/history/issues/505#issuecomment-462328076) shows one possible solution for the time being. I've never used `patch-package`, so I can't say how straightforward it is to use. Alternatively you could also build `history` off of the `master` branch and vendor it in your application.
