### ISSUE TITLE
Components recieving prop updates even though they don't match during pop eventd

### ISSUE THREAD

**Issue by lostPixels** [ReactTraining/react-router#6828]
## Version
React Router DOM v 5.0.1

## Steps to reproduce
Create a router `<switch>` statement with multiple `<routes>`. Click a few `<link>`s, then use the browser back button. Not sure if it's relevant, this is a larger React Application with Redux, and loadables.

## Expected Behavior
When the back button is pressed, previously mounted but no longer relevant routes should unmount their children without changing their props. 

## Actual Behavior
The components mounted under the previously relevant `<route>` will get at least one prop update. This update contains a `pathname` and `search` that do not pass the `path="/blah"` validation. They also will not match the current window.location.

**Comment by timdorr** [comment]
Can you provide a reproduction of this problem on Codesandbox?

**Comment by lostPixels** [comment]
I narrowed this down to the connected-react-router library. Sorry for the confusion.
