### ISSUE TITLE
Default route and lazyload don't working  together

### ISSUE THREAD

**Issue by polRk** [ReactTraining/react-router#6832]
```tsx
<React.Suspense fallback={null}>
<Switch>
        <PrivateRoute path={'/'} exact component={Home} />
        <Route path="/signIn" component={React.lazy(() => signIn())} />
        <Route path="/signUp" component={React.lazy(() => signUp())} />
        <Redirect to={'/'} />
</Switch>
</React.Suspense>
```
If the user is not authorized:
In the address bar **/signIn** => **/** => **/signIn**
In the address bar **/signUp** => **/** => **/signIn**
In the address bar **/nonexistent** => **/** => **/signIn**

And the second error
```tsx
<React.Suspense fallback={null}>
<Switch>
        <PrivateRoute path={'/'} exact component={Home} />
        <Route path="/signIn" component={React.lazy(() => signIn())} />
        <Route path="/signUp" component={React.lazy(() => signUp())} />
        <Route component={() => <h1>Not Found</h1>} />
</Switch>
</React.Suspense>
```
There is a drawing **signIn component** and drawing **Not Found**

**Comment by StringEpsilon** [comment]
I'm not sure I understand what your error is. But you should know that `React.Suspense` renders the fallback whenever any child `React.lazy` component is loading.

In your case, that means the whole `Switch` and all it's routes will be replaced with  `null` until the  lazy component can be rendered.

I found and modified this sandbox to illustrate the issue. Keep an eye on that `<strong>Switch</strong>` when clicking the links: 
https://codesandbox.io/s/async-react-router-v4-w-suspense-p4bw8
