### ISSUE TITLE
Please allow disable NavLink when is active

### ISSUE THREAD

**Issue by borm** [ReactTraining/react-router#6833]
Please add something like `activeClassName` to access us disable or change NavLink component as example to `span`

```jsx
<NavLink
  to={...}
  activeClassName="active"
  activeComponent={'span' || props => 'span'}
/>

**Comment by timdorr** [comment]
See #5437

**Comment by borm** [comment]
And? How `component` should help me?
How i will understand what ```<NavLink />``` isActive?

**Comment by borm** [comment]
@timdorr up
