### ISSUE TITLE
RR animated transition example doesn't work properly/is buggy on iOS on back and your example is broken (example or docs need an update)

### ISSUE THREAD

**Issue by desmap** [ReactTraining/react-router#6834]
BUG TEMPLATE

## Version

"react-router-dom": "^5.0.0"

## Test Case

Your animated transition example is the test case: https://3vo2mnwl9p.codesandbox.io/hsl/10/90/50

Open https://3vo2mnwl9p.codesandbox.io/hsl/10/90/50 on iOS' Safari, navigate around and then go back by using iOS gesture swipe (from left edge to right); you'll see that after going back, still an animation is triggered which looks super odd/broken. 

If this is intended, there should be a note in the docs that animated transitions do not work properly on iOS. Animated transitions between routes are done to create a polished appearance and this behavior creates the exact opposite.

## Steps to reproduce

1. Open your animated transition example on an iPhone on https://3vo2mnwl9p.codesandbox.io/hsl/10/90/50
2. Navigate around using the links
3. Go back by using iOS' gesture swipe back

## Expected Behavior

I'd suggest to not do any animated transition  in this special case  or if improvement is impossible to put a note in the docs.

## Actual Behavior

Safari goes back shows the prev. page and then a short transition kicks in which doesn't make sense because the prev. page was shown already. Looks like a buggy/broken page.

**Comment by timdorr** [comment]
This is just a simple example of how you can create animated transitions. It doesn't need to work in all browsers, because it's not meant to be the _only_ way you can do it. 

We also are using an older version of react-transition-group, so there may be bug fixes there. If you want to submit a PR to fix it and update things, I'll happily take a look.

**Comment by desmap** [comment]
The example signals that you can do animated transitions with RR but probably you can't and it doesn't matter if you it's with RTG, react-spring or whatever. There should be a note or anything.

Or do you think there is a way to do them properly with RR and any motion library?
Is there a way to not animate on back?

**Comment by timdorr** [comment]
I'm not sure. The iOS behavior is a somewhat non-standard UI, creating a temporary draggable "sheet" which appears to be just a screenshot of the last page. This creates a problem where the animations that are triggered on URL transition mismatch the state of that screenshot. 

The best thing I could think to do is to watch for that gesture event and disable transitions when it occurs. I found another Codesandbox with a potential way to do that: https://codesandbox.io/s/9o7x4m497y

**Comment by desmap** [comment]
hey thanks for your thoughts! will look into it it
