### ISSUE TITLE
Typescript interface of match, location and history

### ISSUE THREAD

**Issue by josias-r** [ReactTraining/react-router#6838]
## Version

^4.3.4

## Steps to reproduce

With typescript I create simple components the following way:
```
import React from "react";

const Page: React.FC = ({ children }) => {
  return <div>{children}</div>;
};

export default Page;
```
But when passing a component inside a route, I get the three additional properties match, location and history.

Therefore the following code will throw a typescript error:
`Property 'location' does not exist on type '{ children?: ReactNode; }'.`
```
import React from "react";

const Page: React.FC = ({ location }) => {
  console.log(location);
  return <div>page</div>;
};

export default Page;
```

## Expected Behavior

There should be an interface exported from react-router-dom that defines those three pros.
I should be able to do something like this:

```
import React from "react";
import RouterProps from "react-router-dom"; // this is an interface

const Page: React.FC<RouterProps> = ({ location }) => {
  console.log(location);
  return <div>page</div>;
};

export default Page;
```

## Actual Behavior
I couldn't find such an interface and currently, have to define it myself, which is not great since an update could break my code.
For instance:
```
interface RouterProps {
  location?: {
    hash: string;
    pathname: string;
    search: string;
    state?: number; // not sure about that
  };
}

```

**Comment by timdorr** [comment]
We don't maintain the types here. They're in the Definitely Typed repo, so you can consult their support resources for help.
