### ISSUE TITLE
getUserConfirmation 在导航切换的时候不会被触发

### ISSUE THREAD

**Issue by webSongNO1** [ReactTraining/react-router#6846]
在BrowserRouter中使用getUserConfirmation的时候，在导航切换时不会触发，而是尽在页面刷新时才会触发。
getUserConfirmation={this.confirm('确认吗？', this.getSate)}
confirm = (msg, callback) => {
    let state = window.confirm(msg);
    callback(state)
  }
  getSate = (state) => {
    console.log(state)
  }

**Comment by timdorr** [comment]
I'm sorry, but none of the maintainers speak Chinese.
