### ISSUE TITLE
[Proposal] Accessing router params from getter functions instead of keys of object

### ISSUE THREAD

**Issue by mattiapontonio** [ReactTraining/react-router#6849]
According to these problems:
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/17355
So it's difficult to define an interface for the match scope, I suggest to expose the access of url parameters from getter functions.
Something like:
- https://developer.mozilla.org/en-US/docs/Web/API/URL/searchParams

**Comment by timdorr** [comment]
We don't build this library in TS, nor maintain the types here. So we don't intend to make affordances for external systems at this time.
