### ISSUE TITLE
No documentation for history.listen()

### ISSUE THREAD

**Issue by siddhant1** [ReactTraining/react-router#6850]
## Version
4

## Test Case

https://codesandbox.io/s/7zwjlm2j3q

## Steps to reproduce
Visit https://reacttraining.com/react-router/web/api/history

## Expected Behavior
The listen property should be documented at https://reacttraining.com/react-router/web/api/history
## Actual Behavior
The documentation is at https://github.com/ReactTraining/history#properties

**Comment by timdorr** [comment]
That's because it's not code from this library. The documentation here links to the history library's docs.
