### ISSUE TITLE
History push and replace don't work when trying to change page ID

### ISSUE THREAD

**Issue by developdeez** [ReactTraining/react-router#6851]
I've read this is an issue in other forums. Seems like there should be a fix but both push('page/123) and replace(page/567), do nothing if your url ends in /page.... :/

**Comment by timdorr** [comment]
BTW, make sure you push with an absolute url (`push('/page/123')`). Relative URLs don't work.

**Comment by developdeez** [comment]
Thanks @timdorr, I tried: 
            this.props.history.replace(`/event/${targetID}`);
Same result

**Comment by pshrmn** [comment]
If you can create a sandbox (there was a link to a React Router starter on the template you deleted), I can take a look at it, but the behavior you're describing sounds like there is a bug in your application, because that definitely works.
