### ISSUE TITLE
Is there a mistake in the `Route.md`?

### ISSUE THREAD

**Issue by ystarlongzi** [ReactTraining/react-router#6852]
The document has the following paragraphs describing the priority of`component`, `render`, and `children` props.

> **Warning:** Both `<Route component>` and `<Route render>` take precedence over `<Route children>` so don't use more than one in the same `<Route>`.

But according to the code logic, `<Route children>`  should have the highest priority.

https://github.com/ReactTraining/react-router/blob/a2134c64342a2fe44eac0f968e9e40afa3cfb3e8/packages/react-router/modules/Route.js#L61-L72

**Comment by timdorr** [comment]
Looks like it. If you want to submit a PR, feel free!

**Comment by ystarlongzi** [comment]
Ok, I will submit a PR.

**Comment by pshrmn** [comment]
`component` and `render` definitely used to take precedence. It looks like that was changed when `Route`s switched to a render invoked function. I'm not sure if it would be better to change the documentation or revert to the original order.
