### ISSUE TITLE
react-router can't differentiate between an actual route and a route with params

### ISSUE THREAD

**Issue by prak281993** [ReactTraining/react-router#6861]
## Version

**Please replace this sentence with the React Router version that you are using.**

## Test Case

https://codesandbox.io/s/7zwjlm2j3q

**Comment by prak281993** [comment]
I have routes as:
     `<Route exact path="/auth" component={Auth} />
      <Switch>
     <PrivateRoute exact path="/" component={HomePage} />
    <PrivateRoute path="/:userName" component={TimeLinePage} />
     </Switch>`

whenever I navigate to /:userName with some params it works fine
but, when I navigate to /auth it renders both Auth component and TimeLinePage component

**Comment by timdorr** [comment]
You need a `<Switch>` to make different routes exclusive.
