### ISSUE TITLE
NavLink's location prop no longer is passed to isActive as the documentation describes

### ISSUE THREAD

**Issue by rbdrenn** [ReactTraining/react-router#6862]
## Version
5.0.1

## Steps to reproduce
Commit [a38ef04](https://github.com/ReactTraining/react-router/commit/a38ef042697ccc1c70bcdaf07d05ad994a31594d) changed the `isActive` function parameters on the `NavLink` component from checking for `this.props.location` to override the location to just passing `context.location`. The docs still specify that you can override the location although this is not the case. This is a breaking change for those passing custom location props.

This works in version 5.0.0 but was broken in 5.0.1.

## Expected Behavior
For the location prop to be passed to the isActive function OR the docs/release notes updated notifying you can no longer do this.

## Actual Behavior
`isActive` function is being passed the actual location prop regardless of whether you specify a location prop on the NavLink

**Comment by timdorr** [comment]
Looks like we need to change `pathToMatch` to `locationToMatch` and use that both for matching and the isActive function. Should be a simple fix if you want to make a PR.

**Comment by timdorr** [comment]
@StringEpsilon Was there any intention in using context.location? Just want to make sure I'm not missing anything obvious.

**Comment by StringEpsilon** [comment]
It was not an intenional thing. I just removed the `<Route />` and because that got rid of the `location` variable, I wiggled my way through the component code til I was done. So just a case of careless programming. Sorry bout that.

**Comment by timdorr** [comment]
Oh no blame intended. Just wanted to make sure I didn't miss anything.
