### ISSUE TITLE
Router modifies external target location of  <a> 

### ISSUE THREAD

**Issue by Darmun** [ReactTraining/react-router#6865]
## Version

5.0.1

## Test Case

https://codesandbox.io/embed/relaxed-goldberg-k95uv?fontsize=14

## Steps to reproduce

To reproduce a problem, i imported react router, created few "Link" elements and one "a" element with "href" attribute set to external website (e.g. www.google.com) inside 'About' component.

## Expected Behavior

<a> link suppose to redirect to google site.

## Actual Behavior

App redirects to relative path '/www.google.com' of an application.

**Comment by timdorr** [comment]
That has nothing to do with React Router. You have to include the protocol scheme with any URL in an href. `<a href="https://www.google.com">google</a>`
