### ISSUE TITLE
activeClassName does NOT work with css class modules ...

### ISSUE THREAD

**Issue by capey0** [ReactTraining/react-router#6866]
## Version

"react": "^16.8.6",
"react-dom": "^16.8.6",
"react-router": "^5.0.1",
"react-router-dom": "^5.0.1"

## Steps to reproduce

Create a component (Eg,js) with a NavLink in it. You can use the "activeClassName" prop if you want but it is not necessary (default activeClassName is "active").
Create a css class module (Eg.module.css) with the a.[your-class-name-here] css defs and import it into your component. (If using the default, replace "[your-class-name-here]" with "active").

Work-around:
Create a regular css file (Eg.css) and put you the a.[your-class-name-here] css defs in there and import it into your component. This will enable the "active" class behaviour.

## Expected Behavior

The "active" class css defs should be applied to the active <a>

## Actual Behavior

The "active" class css defs are not applied to the active <a>

**Comment by timdorr** [comment]
This doesn't have anything to do with React Router. I would look into how your build system is importing those modules.
