### ISSUE TITLE
Replace is broken when changing state on same page.

### ISSUE THREAD

**Issue by developdeez** [ReactTraining/react-router#6870]
I have a simple inbox page that opens user messages. The trouble is that when a user clicks a message from the inbox from the inbox page...nothing happens. I understand why this is the case for push but for replace it seems like a bug.

Attempting as so:

this.props.history.replace({
              pathname: "/inbox",
              state: { chatID: targetID }
            });

**Comment by timdorr** [comment]
Please stop opening the same issue repeatedly.

**Comment by developdeez** [comment]
Oops where's the old one?

**Comment by timdorr** [comment]
https://github.com/ReactTraining/react-router/issues?q=is%3Aissue+author%3Adevelopdeez+sort%3Aupdated-desc

**Comment by developdeez** [comment]
Those were closed by bot. Is this not the place to post bugs? If not where?

**Comment by timdorr** [comment]
Like it was stated in the first issue: Please create a Codesandbox project reproducing this issue. We can't diagnose from the limited code you've provided. The API is in used by a number of different projects, so it's unlikely there is a bug.

**Comment by developdeez** [comment]
You were correct. I wasn't checking for the change in my shouldComponentRerender.
Thanks
