### ISSUE TITLE
Request: react-router-native option to hide navigation bar (Android)

### ISSUE THREAD

**Issue by DavidSvetlik** [ReactTraining/react-router#6872]
Since I haven't found any ticket or question regarding this feature, here comes my request:

It would be really useful to have some option to hide (and show, and maybe change the color of) bottom navigation bar in Android for fullscreen apps. All tutorials/guides I found were always referring to `navigationOptions`, but that's `react-navigation` thing. For simple show/hide I imagine some simple Component's static prop, or it can be a method to call for more versatile usage.

Note: https://github.com/thebylito/react-native-navigation-bar-color didn't work for me (probably because of Expo).

**Comment by pshrmn** [comment]
That isn't really in the scope of what `react-router-native` does. `react-navigation` has built-in components, like the navigation bar, while rrn provides low level primitives for route matching/navigating, but leaves components like a navigation bar up to you.
