### ISSUE TITLE
error TS2315: Type 'Location' is not generic.

### ISSUE THREAD

**Issue by BubbleM** [ReactTraining/react-router#6873]
node_modules/@types/react-router/index.d.ts:72:13 - error TS2315: Type 'Location' is not generic.

72   location: H.Location<S>;
               ~~~~~~~~~~~~~

node_modules/@types/react-router/index.d.ts:82:13 - error TS2315: Type 'Location' is not generic.

82   location: H.Location<S>;
               ~~~~~~~~~~~~~

{
    "compilerOptions": {
        "outDir": "./app",
        "rootDir":"./",
        "sourceMap": false,
        "noImplicitAny": false,
        "module": "commonjs", 
        "target": "es6", 
        "watch":false,
        "alwaysStrict": true,
        "removeComments": true,
        "preserveWatchOutput": true,
        "experimentalDecorators": true,
        "jsx": "react"
    },
    "include": [
        "./server/**/*"
    ],
    "exclude": [
        "node_modules"
    ]
}

**Comment by timdorr** [comment]
We don't maintain these types.
