### ISSUE TITLE
Component not rendering 

### ISSUE THREAD

**Issue by AbednegoTM** [ReactTraining/react-router#6874]
## Version

**v5.0.1**

## Test Case

https://codesandbox.io/s/staging-shadow-m219i

## Steps to reproduce
 In the Component where BrowserRouter is imported: 
 Click the Link component 

## Expected Behavior
Expect **Route** to render the component specified in the *Component* prop of **Route**
## Actual Behavior
 Nothing happens , No errors showing .

**Comment by StringEpsilon** [comment]
`component` not `Component`. Props are case sensitive.
