### ISSUE TITLE
Ambiguous routes (/static/:dynamic + /:dynamic/:dynamic)

### ISSUE THREAD

**Issue by Naxus28** [ReactTraining/react-router#6875]
# Version

**4.3.1**

## Code
I have the following routes (plus several others) within a <Switch> block:
```javascript
<Router>
     <Switch>
            ...
           <Route exact path="/support/article/technical/:id" component={Article} />
           <Route exact path="/support/article/admin/:id" component={Article} />
           <Route exact path="/support/article/:supercategory/:category" component={ArticleCategories} />
            ...
     </Switch>
</Router>
```

Note: `:supercategory` is either "technical" or "admin".

## Problem
First and second route work fine because the third piece of the path is different (technical vs. admin). However, the last route does not render `ArticleCategories` but `Article` (obviously it breaks the component because it doesn't pass the "id"). If I move that route above the other two then those two routes render `ArticleCategories` instead of `Article`.

I read the docs but there doesn't seem to be an answer (example) that covers this scenario.

## Expected Behavior
Ambiguous routes match the correct component.

## Actual Behavior
Ambiguous routes are matching the first component on the Router block.

**Comment by pshrmn** [comment]
Are you saying that if you had a `test` category, you would want `/article/technical/test` to be matched by the `ArticleCategories` component? This isn't really possible; I would recommend rethinking your URL structure to not be ambiguous. You could also have your `Article` component determine whether the params is an `id` or `category`, but I think that non-ambiguous paths would be a better choice.

**Comment by Naxus28** [comment]
Yeah, that is what I imagined. Thanks for confirming it.
