### ISSUE TITLE
NavLink active state not consistent when to is string vs object

### ISSUE THREAD

**Issue by rafrex** [ReactTraining/react-router#6877]
## Version

5.0.1 Browser Router

## Test Case

https://codesandbox.io/s/affectionate-black-f79dp
I've found the in-editor browser to be inconsistent for state changes - view the result it it's own window here: http://f79dp.csb.app

## Steps to reproduce
`to` prop for `NavLink`: use a string with hash and compare it to using a an object with hash.
```js
to="/home#top"
// vs
to={{ pathname: '/home', hash: '#top' }}
```

## Expected Behavior
Both would have the same `active` behavior.

## Actual Behavior
`to` as an object ignores the hash and only compares the path for determining if the `NavLink` is active. GOOD
`to` as a string never matches (even when both path and hash match). BAD

## Preferred Behavior
The string version of `to` would act the same as the object version (only compare the path and ignore the hash). This makes the behaviors consistent and allows other libraries to build on top of the RR path only `match` with a custom `isActive` function. For example, I'd like to implement something like the following in [`react-router-hash-link`](https://github.com/rafrex/react-router-hash-link) to only make the link active if both path and hash match:
```js
isActive={(match, location) => match && hashMatch(location)}
// where hashMatch just compares the hashes to determine if they match
```

**Comment by pshrmn** [comment]
I believe that the `master` branch currently works this way, but have been released.

https://github.com/ReactTraining/react-router/blob/24a3bfbbaf9f8188a163b5993a6c28df881a5e1d/packages/react-router-dom/modules/NavLink.js#L35

**Comment by rafrex** [comment]
That would makes sense.. I spent 30min reading the code hoping I could make a quick PR but couldn't find the issue 😅

**Comment by pshrmn** [comment]
Yeah, I'd like to have the repo in a `master`/`dev` so master only reflects the latest release. The current setup can be pretty confusing (our docs unfortunately include unreleased API).

I think that a minor release is overdue, but it needs an @mjackson seal of approval.
