### ISSUE TITLE
[BUG: react-router-config can not render sub routes]

### ISSUE THREAD

**Issue by lvvlan** [ReactTraining/react-router#6879]
## Version

"react": "^16.9.0",
"react-dom": "^16.9.0",
"react-router-config": "^5.0.1",
 "react-router-dom": "^5.0.1",

## Test Case

https://codesandbox.io/s/intelligent-jackson-cjwc4

## Expected Behavior

render component Child

## Actual Behavior

can not render sub routes

**Comment by timdorr** [comment]
It passes the child component to the parent via props.children.

**Comment by lvvlan** [comment]
Sorry, I don't understand, could u tell me, how to change? Very thx~  :)

**Comment by gaoyiniy** [comment]
same problem, how to solve this?
