### ISSUE TITLE
RRv5 `componentWillReceiveProps` warning

### ISSUE THREAD

**Issue by babakness** [ReactTraining/react-router#6880]
Hello, I'm using v5 (dom)

I tried using a Link component within a Function Component, top level is wrapped with `BrowserRouter`. Clicking on the Link, I get `componentWillReceiveProps` warnings. I am unclear if this API actually removed in v5 (reading RoadMap, looks to my interpretation checked off) and if this is expect for now.

Thanks.

**Comment by timdorr** [comment]
This error isn't caused by this library. Something else is using those lifecycle methods.
