### ISSUE TITLE
Route#render documentation of mount/unmount

### ISSUE THREAD

**Issue by garhiggins** [ReactTraining/react-router#6882]
The documentation for using the Route#component prop says:
```
When using an inline function for inline rendering, use the render or the children prop (below).
```
This is great advice, but the render function can have the same pitfall if the parent component re-renders.

I think the documentation assumes the parent component will never re-render. But there's lot's of reasonable cases where you might have components above react-router that can update over the life of the app. For example, I might have a <ThemeProvider> wrapping my app, and allow users to update their theme and immediately re-render the page. But, when the Router and Route components re-render, they will receive a new inline function, and the component will go through an unmount/mount cycle unexpected.

It's easy for things to go wrong if you use an inline function to render a stateful component in react. I think the documentation for Route#render should discuss that it's safe to do so _only_ if the Router will never be re-render.

**Comment by timdorr** [comment]
When you provide `render`, [we just call the function and return it](https://github.com/ReactTraining/react-router/blob/24a3bfbbaf9f8188a163b5993a6c28df881a5e1d/packages/react-router/modules/Route.js#L68). So the inline function itself isn't rendered as a function component, just called as a regular function. As long as the components and props are the same between renders, the normal rules for React re-renders will apply.

**Comment by garhiggins** [comment]
Thanks, Tim. :) Sorry for the noise.
