### ISSUE TITLE
Setting Page Title (2)

### ISSUE THREAD

**Issue by OnkelTem** [ReactTraining/react-router#6888]
The previous thread hasn't got any solition but was closed:
https://github.com/ReactTraining/react-router/issues/2844

This is a follow-up with the same name.

So the goal is to change titles when routes are changed. IIUIC we need to configure a middleware properly to get it working, but in the previous topic nobody posted an example of this. Please provide one.

**Comment by timdorr** [comment]
You're looking for [react-helmet](https://github.com/nfl/react-helmet)

**Comment by vpillinger** [comment]
It is pretty sad to introduce a new dependency for something that is a one-line change.

In the History object, there is a push function that is a wrapper for the DOM object pushState: https://developer.mozilla.org/en-US/docs/Web/API/History_API

However, this wrapper function takes out the "title" option and sets it to null.
```
  function push(path, state) {
    process.env.NODE_ENV !== "production" ? warning(!(typeof path === 'object' && path.state !== undefined && state !== undefined), 'You should avoid providing a 2nd state argument to push when the 1st ' + 'argument is a location-like object that already has state; it is ignored') : void 0;
    var action = 'PUSH';
    var location = createLocation(path, state, createKey(), history.location);
    transitionManager.confirmTransitionTo(location, action, getUserConfirmation, function (ok) {
      if (!ok) return;
      var href = createHref(location);
      var key = location.key,
          state = location.state;

      if (canUseHistory) {
        globalHistory.pushState({
          key: key,
          state: state
        }, null, href);

        if (forceRefresh) {
          window.location.href = href;
        } else {
          var prevIndex = allKeys.indexOf(history.location.key);
          var nextKeys = allKeys.slice(0, prevIndex === -1 ? 0 : prevIndex + 1);
          nextKeys.push(location.key);
          allKeys = nextKeys;
          setState({
            action: action,
            location: location
          });
        }
      } else {
        process.env.NODE_ENV !== "production" ? warning(state === undefined, 'Browser history cannot push state in browsers that do not support HTML5 history') : void 0;
        window.location.href = href;
      }
    });
  }
```

This change can literally be done by just respecting the underlying browser API.


```
```
  function push(path, state, title) {
    process.env.NODE_ENV !== "production" ? warning(!(typeof path === 'object' && path.state !== undefined && state !== undefined), 'You should avoid providing a 2nd state argument to push when the 1st ' + 'argument is a location-like object that already has state; it is ignored') : void 0;
    var action = 'PUSH';
    var location = createLocation(path, state, createKey(), history.location);
    transitionManager.confirmTransitionTo(location, action, getUserConfirmation, function (ok) {
      if (!ok) return;
      var href = createHref(location);
      var key = location.key,
          state = location.state;

      if (canUseHistory) {
        globalHistory.pushState({
          key: key,
          state: state
        }, title, href);

        if (forceRefresh) {
          window.location.href = href;
        } else {
          var prevIndex = allKeys.indexOf(history.location.key);
          var nextKeys = allKeys.slice(0, prevIndex === -1 ? 0 : prevIndex + 1);
          nextKeys.push(location.key);
          allKeys = nextKeys;
          setState({
            action: action,
            location: location
          });
        }
      } else {
        process.env.NODE_ENV !== "production" ? warning(state === undefined, 'Browser history cannot push state in browsers that do not support HTML5 history') : void 0;
        window.location.href = href;
      }
    });
  }
```

**Comment by vpillinger** [comment]
@OnkelTem Your best bet is to just put

document.title = 'some title' in your componentDidMount() method on the component being rendered by a route and hope that nothing blows up your component while its loading.

**Comment by sapkra** [comment]
I've created the following solution. Because this is a really useful feature a lot of guys are asking for I've wrote a documentation and published it on npm and github. Would be nice to get some feedback also if it's working in your environment because I don't have test environments for all cases yet as well as automated test (PRs welcome).

https://github.com/lynoapp/react-router-title
