### ISSUE TITLE
I can't start my project with react-router history

### ISSUE THREAD

**Issue by Oligocalse** [ReactTraining/react-router#6891]
## Version
```
    "react": "^16.9.0",
    "react-app-polyfill": "^1.0.2",
    "react-dev-utils": "^9.0.3",
    "react-dom": "^16.9.0",
    "react-router-dom": "^5.0.1",
```

## Test Case
add the modules from react-router-dom like this
![image](https://user-images.githubusercontent.com/36029402/64087411-78026e80-cd6f-11e9-9cf3-b3a806f8f135.png)

NOT add the modules from react-router-dom like this
![image](https://user-images.githubusercontent.com/36029402/64087431-98cac400-cd6f-11e9-85bc-8c70d6872789.png)

## Steps to reproduce
this is a react project that created by create-react-app and run eject, then I add the dependeices of react-router-dom, however it can not start successfully

**Comment by MeiKatz** [comment]
If you read carefully then you will notice that this is an issue related to the *history* library that React Router uses internally. Please open an issue over there.
