### ISSUE TITLE
<Redirect /> redirect to a new URL without query string

### ISSUE THREAD

**Issue by fengxinming** [ReactTraining/react-router#6892]
`/redirect?foo=bar` redirect to `/foo/child` without query string

## Version

react-router@5.0.1

## Test Case

https://codesandbox.io/s/sleepy-shannon-94cxh

**Comment by MeiKatz** [comment]
That is not a bug, but a feature. We are working like it is defined in the written RFC (I have to look up which RFC it is). If you want to keep the query string then you have to add it explicitly by yourself.
