### ISSUE TITLE
encoded ampersands in query params in react-router v3

### ISSUE THREAD

**Issue by believer-ufa** [ReactTraining/react-router#6896]
Hello guys. Thank you for support react-router v3 which still used in many projects, we use it in our https://rawg.io project too.

We have one bug with parsing query string. As i realised, you already fixed it there: #343. But it seems that you fixed it already in v4 branch of library.

Can you kindly fix it in v3 branch too?

**Comment by timdorr** [comment]
That Issue and PR are from when we were before version 1.0. They don't apply to 4.x/5.x, as encoding continues to be an ongoing issue.

I'm not sure what the specific issue is here. Can you either provide a test case or submit a PR to fix the problem you're experiencing? I'm going to close this until we have more detail.

**Comment by believer-ufa** [comment]
I created very simple reproduce of that error.

There is code of that example: https://codesandbox.io/s/patient-field-cfg0i.

Can you open it with `keyWithoutAmpersand=value&query=max%20&%20sam` query and click on "Open New Window" btn on top right side:
![image](https://user-images.githubusercontent.com/801727/64360914-e58af500-d024-11e9-9804-944d32cf1f61.png)

After it you should went into some page like that:
https://cfg0i.csb.app/?keyWithoutAmpersand=value&query=max%20&%20sam

And there you can open browser console and check `location.query` object where you can see exactly that problem which was fixed in #343.

![image](https://user-images.githubusercontent.com/801727/64360854-c3917280-d024-11e9-9468-afcf039e48d2.png)
