### ISSUE TITLE
Cannot render route's component when the page was translated to other language

### ISSUE THREAD

**Issue by mrsepdiana** [ReactTraining/react-router#6902]
Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

Error when the page was translated to other language (chrome browser translate feature), when I click the Link and it should render the component route, but it's not render the component of the route.

![image](https://user-images.githubusercontent.com/11883550/64522750-ed98ac80-d324-11e9-9774-d0e4cbbdf314.png)

**Comment by timdorr** [comment]
The browser is manipulating the DOM outside of React's control, and React doesn't like that. This doesn't have anything to do with React Router.
