### ISSUE TITLE
history.push add trailing slash before query in root path

### ISSUE THREAD

**Issue by saintego** [ReactTraining/react-router#6905]
Hi,
I'm using react-router-dom: 5.0.0 and I have
```
      <Router basename={`${path}`}>
        <AppWrapper>
          <Route path="/" exact component={() => <Configurator {...props} flat />} />
```
When I'm using later
``` 
    history.replace({
      pathname,
      search,
    });
```
router add trailing slash to the url before question mark if pathname is empty. So my url is like `http://localhost:3000/?query`. I'd expect to have `http://localhost:3000?query` like for every other pathname.

**Comment by MeiKatz** [comment]
To make things clear: `http://localhost:3000?query` is **not** a valid url. If the path after the domain and port is empty, then there must be at least a single slash.

**Comment by saintego** [comment]
Sorry, this is localhost. I production we have www.domain.com/something as
path to the app. In that case we get www.domain.com/something/?query

**Comment by pshrmn** [comment]
@saintego I would open an issue in the `history` repo. I'm not sure if it will be changed, but it would be better to discuss it over there.
