### ISSUE TITLE
ComponentType is not assignable to parameter of type ComponentClass

### ISSUE THREAD

**Issue by basslagter** [ReactTraining/react-router#6906]
When passing something other than a ComponentClass type (like a FunctionComponent or ComponentType) to the withRouter hoc I get "ComponentType is not assignable to parameter of type ComponentClass" I got this issue when passing in the withTranslation hoc from react-i18next (see: https://github.com/i18next/react-i18next/issues/938).

This issue was introduced when upgrading from Typescript 3.5.3 to the newest 3.6.2.

**Comment by timdorr** [comment]
We don't maintain the types for this library. Please consult the support resources for DefinitelyTyped.
