### ISSUE TITLE
How can I run the project

### ISSUE THREAD

**Issue by fengshengbing** [ReactTraining/react-router#6908]
when I download and run 'cd packages/react-router-dom' and execute 'npm run test' and then it tips ' Cannot find module './cjs/react-router.js' from 'index.js'.  where is the cjs ? How can I get the cjs ？ when  I read package.json I can't find any key infomation about 'cjs'. I need you help I am confiused.

**Comment by MeiKatz** [comment]
I think you have to build it first, but not too sure about it.

**Comment by fengshengbing** [comment]
> I think you have to build it first, but not too sure about it.
you are right! thanks so much. I can find cjs in rollup.config.js, Now I know it was built by rollup
