### ISSUE TITLE
Redirect exact doesn't work outside of switch (not mentioned in docs)

### ISSUE THREAD

**Issue by goleary** [ReactTraining/react-router#6911]
## Version

    "react-dom": "16.8.6",
    "react-router-dom": "5.0.1",

## Test Case

https://codesandbox.io/s/react-router-70bc5

## Steps to reproduce

Create project with Redirect component with exact prop outside of switch.  `exact` does nothing (i.e. every page triggers redirect even with the path does not match exactly)

## Expected Behavior

only redirect from '/' instead of every path

## Actual Behavior
redirects every url navigation (& reloads, not navigations using Link component) to the 'to' path.

Seems to be referenced here: https://github.com/ReactTraining/react-router/issues/5258 but makes no mention in documentation that you can only use these props if the `<Redirect>` component is a child of a `<Switch>`

**Comment by timdorr** [comment]
If you would like to discuss doc changes, please submit a PR. That's the most actionable way to deal with it.
