### ISSUE TITLE
How to render with and without layout?

### ISSUE THREAD

**Issue by popuguytheparrot** [ReactTraining/react-router#6917]
I want render /about without layout, but i got /about in Topic component. 

https://codesandbox.io/s/react-router-basic-i38i6

**Comment by pshrmn** [comment]
https://reacttraining.com/react-router/web/api/Route/exact-bool

**Comment by popuguytheparrot** [comment]
@pshrmn

Lol, nice, its not working. 
Cool to close a issue without solving it
