### ISSUE TITLE
Feature request - Passing custom component to Link

### ISSUE THREAD

**Issue by SuddenlyPineapple** [ReactTraining/react-router#6918]
https://github.com/ReactTraining/react-router/blob/0394c5eaac3b3f5fec2091225b9bc6baf1b24b35/packages/react-router-dom/modules/Link.js#L22

Hi, i've recently faced interesting problem, when using Link from here. What I wanted to do is to pass custom Link component from other library and I was unable to do that with as it is now. 

For example. I have style library like bootstrap, but classes are hashed. Soo if I cannot pass children component to Link component, I basically cannot use styling from other libraries. 

I've thinked it could works this way for ex: 
`<Link to="something" component={(<MyCustomLinkComponent />})" ></Link>`

There is a solution for that problem or any good workaround?

**Comment by timdorr** [comment]
Added in #6462, but not yet released.
