### ISSUE TITLE
Feature request - Route parameters.

### ISSUE THREAD

**Issue by stephan-v** [ReactTraining/react-router#6919]
Please add route parameters so I can do what 99% of all other routing solutions have implemented:

A Vue.js example taken from: https://router.vuejs.org/guide/essentials/navigation.html

```
// named route
router.push({ name: 'user', params: { userId: '123' } })
```

This seems extremely basic and a fundamental to routing. I know you can pass in state by having to manually sync in the router again is something you should not have to do.

**Comment by timdorr** [comment]
https://reacttraining.com/react-router/web/example/url-params

**Comment by stephan-v** [comment]
This works with the `Link` component but does not specify anything about 'programatically' navigating to a route with parameters which is the problem here.
