### ISSUE TITLE
Run Jest from repo root

### ISSUE THREAD

**Issue by mjackson** [ReactTraining/react-router#6921]
Right now we have [a custom test script](https://github.com/ReactTraining/react-router/blob/master/scripts/test.js) that runs the tests for each package by `cd`ing into that package's root and running `yarn test`. However, ideally we would have only one Jest installation for the entire repo and be able to run `jest` to run all the tests or e.g. `jest packages/react-router-dom` to filter out the tests for a specific package.

Just leaving this here in case anyone wants to take a stab at it.

/cc @rickhanlonii

**Comment by mjackson** [comment]
I should probably mention that I tried to tackle this yesterday afternoon but ran into some Babel configuration issues. Babel 7 [suggests using a single `babel.config.js` file](https://babeljs.io/docs/en/config-files#monorepos) in the repo root, which is different from our current `.babelrc` per-package approach.

**Comment by rickhanlonii** [comment]
You could use Jest projects for this but as you said, getting the babel config right is tricky

**Comment by jnielson94** [comment]
@mjackson - What kind of babel configuration issues did you run into?

If you're needing to have a different babel config for different packages you might not be able to do the `jest` runs all test way since they'd probably all be run through the same babel config. Though I guess it might be possible to use some fancy jest [`transform`](https://jestjs.io/docs/en/configuration#transform-object-string-pathtotransformer-pathtotransformer-object) setup to get it to run babel with different configurations in different packages...

**Comment by pshrmn** [comment]
Is there an issue with using Lerna to run each package's tests? I've had success with that.

**Comment by mjackson** [comment]
@rickhanlonii Hmm, I hadn't heard of Jest projects before. Will look into it, thanks.

@jnielson94 I think the only config that needs to be different is the Babel preset for react-router-native which needs `metro-react-native-babel-preset`.

@pshrmn That would be similar to what we're doing right now with separate Jest installations for each package. I'm trying to get down to just one Jest install.

**Comment by timdorr** [comment]
Do Yarn Workspaces not hoist into one Jest install?

**Comment by tgallacher** [comment]
I literally just went through this with a repo at work where we converted to Lerna. Happy to take a stab.

Is there already a base branch where this should start, or just `master`?

**Comment by mjackson** [comment]
@timdorr Yes, Jest is installed once. But we still invoke it multiple times, once per package. I want to run all the tests in a single Jest instance.

**Comment by tgallacher** [comment]
got it down to 1 test failing in the RN package. Still digging; I'll clean up and push to see if anyone notices something that may be missing. But we're close.. 🤞
