### ISSUE TITLE
react-router@3 Unsafe Lifecycle warning in React >= 16.3 

### ISSUE THREAD

**Issue by hiyangguo** [ReactTraining/react-router#6923]
## Version
react@16.8.6
**react-router@3.2.4**

## Steps to reproduce
Use react-router in react16.8.6

## Expected Behavior
without warning
## Actual Behavior

warning for `componentWillReceiveProps` `componentWillMount`

**Comment by pshrmn** [comment]
Version `3.2.4` shouldn't have the unsafe lifecycle warnings. Those modules prefix the unsafe lifecycles when the detect React version is >= 16.3. Can you please verify that you are actually using `3.2.4`.

**Comment by timdorr** [comment]
Yes, you are either using the wrong version or this is coming from another library.

**Comment by hiyangguo** [comment]
Yes, I'm wrong thank you very much.

**Comment by karlsandin** [comment]
I also encountered warnings and these were caused by an outdated yarn.lock file. Updating it removed the warnings.
