### ISSUE TITLE
history.replace() in Firefox issue

### ISSUE THREAD

**Issue by gtsopour** [ReactTraining/react-router#6926]
## Version

4.3.1

## Steps to reproduce
By using `history.replace('/', null)` I am getting in Firefox (69.0.1 (64-bit)) console the message `Warning: Hash history cannot replace state; it is ignored` and my current url is not replaced in the Browser History. This is not happening in all the other browsers.

**Comment by timdorr** [comment]
You should upgrade to the latest release of React Router. Despite the major version bump, it's actually a minor release. 

Using a HashRouter is not recommended unless you have to. You should use a BrowserRouter, as there are some known quirks like this. 

I would search the issues on the history repo, as this is actually coming from that library instead.
