### ISSUE TITLE
Quick route switch on mobile is slow

### ISSUE THREAD

**Issue by matis-dk** [ReactTraining/react-router#6927]
PWA is starting to getting more popular, and a fundamental part of that is often a fixed bottom navigator, where you can switch quickly between routes.
But currently, it seems like there is a small amount of time, where the UI is blocked, and doesn't register clicks from the user. You quickly perceive the app as slow, when the app doesn't respond to user input. 

I'm not sure how much is related to React still missing a concurrent mode though. 

I not able to reproduce it on desktop. Perhaps because of higher processing power.

## Version
"5.1.0"

## Test Case
Repo:
https://codesandbox.io/s/naughty-rain-c5ks4

For mobile:
https://c5ks4.csb.app/

## Steps to reproduce
Open the link on mobile, and switch quickly between routes. 
(I'm using a iPhone 7)

## Expected Behavior
Register all user inputs and change route accordingly.

## Actual Behavior
A small delay where the UI is blocked, and you can't switch route.

**Comment by matis-dk** [comment]
I made a fork adding timestamp for start - and end time. Not sure how accurate those measurement is tough.

Repo with timestamps:
https://codesandbox.io/s/hungry-wozniak-s5mx0

Desktop route change (High performant desktop):
2-4ms

Mobile route change (iPhone 7): 
15-30ms

**Comment by matis-dk** [comment]
After some further investigation, it seems like it might not be related the react-router-dom afterall.

When measuring the tapping speed on mobile, I'm not able to get under 350ms. 
This is significant higher that the time for each route change above.

Repo for tapping speed:
https://codesandbox.io/s/optimistic-fog-71i7q

**Comment by timdorr** [comment]
That sounds exactly like the tap delay: https://developers.google.com/web/updates/2013/12/300ms-tap-delay-gone-away

That's not anything React or React Router controls.
