### ISSUE TITLE
WithRouter deprecation

### ISSUE THREAD

**Issue by Domino987** [ReactTraining/react-router#6929]
Hello Router Team,
Great work!
I have a question regarding the release announcement of 5.1.
At the end you say:

Again, although withRouter is not deprecated in 5.1, it's a weird API when you can compose your state with hooks instead. It will also most likely be deprecated in a future release.

Does that mean to use reaxt-router v6 in January, I cannot use the withRouter HOC and I have to convert all class components, which use routing, to functional components?

If that would be the case, I would strongly advise against it because it would make using react-router much more opiniated and forces the user to ditch class components if though their are a total valid way to write react components.

I hope you reconsider the deprecation of withRouter and keep supporting it.

Keep up the great work. 
Thanks.

**Comment by MeiKatz** [comment]
As long as it is not deprecated, it is not deprecated. I think there will be enough time between adding depreciation warnings to `withRouter` and the final removal of the HOC. Anyway, your demur is valid and I cannot think of a way we could replace it for class components. Even so HOCs are kind of ugly.
