### ISSUE TITLE
BrowserRouter is not working when deploying the site on tomcat (Servlet Container)

### ISSUE THREAD

**Issue by zbeedatm** [ReactTraining/react-router#6930]
## Version
5.0.1

## Test Case

https://codesandbox.io/s/fragrant-morning-267l5

## Steps to reproduce

1) run: npm run build
2) take the content of build folder and put it under WebContentFolder of a war (to be deployed as a servlet in tomcat)
3) start tomcat with that war
4) the site is loaded with no errors at this location: http://localhost:8080/my-app, but nothing happens and the screen is empty!

## Expected Behavior
The App component should be loaded

## Actual Behavior
Nothing is shown and no errors!!

NOTE
====
If I use HashRouter instead of BrowserRouter, the site is responding bu when redirecting to other route getting 404 error.

Please see these issues that I opened on stackoverflow:
https://stackoverflow.com/questions/58082196/getting-empty-screen-when-deploying-react-site-as-a-servlet-on-tomcat

https://stackoverflow.com/questions/57770197/deploy-react-applications-in-a-servlet-environment/58086653#58086653

**Comment by pshrmn** [comment]
You need to use a [`basename`](https://reacttraining.com/react-router/web/api/BrowserRouter/basename-string) when hosting the application in a non-root directory.

**Comment by zbeedatm** [comment]
I used it, and followed the instructions form these posts:

http://frugalisminds.com/react-js/deploy-react-js-in-tomcat/#comment-26210

https://www.megadix.it/blog/create-react-app-servlet/

` <Router basename={process.env.REACT_APP_ROUTER_BASE || ''}>`

And as it explained in my stackoverflow post, If I replace the router entry points to point to functions instead of other components it works:

` import React, { Component } from 'react';
import './App.css';

// import Main from "./components/Main";
// import Login from "./components/Login";
// import ProjectCustomize from "./components/ProjectCustomize";
import {BrowserRouter, Link, Route, Switch} from "react-router-dom";


class App extends Component {

    render() {

        return (
            <div className="App">

                <BrowserRouter basename={process.env.REACT_APP_ROUTER_BASE || ''}>
                    <div>
                            <ul className="nav">
                                <li><Link to="/">Homepage</Link></li>
                                <li><Link to="/login">Login</Link></li>
                                <li><Link to="/customize">Customize</Link></li>
                            </ul>
                    <Switch>
                        <Route path="/" exact component={Main} />
                        <Route path="/login" component={Login} />
                        <Route path="/customize" component={ProjectCustomize} />
                        {/*<Redirect path="*" to="/" />*/}
                    </Switch>
                        </div>
                </BrowserRouter>

            </div>
        );
    }

}

function Main() {
    return (
        <div>
            <h1>Home</h1>
            <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam,
                eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.</p>
        </div>
    );
}

function ProjectCustomize() {
    return (
        <div>
            <h1>Blog</h1>
            <h4>Some blog post</h4>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
            <h4>Another blog post</h4>
            <p>Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
            <p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>
            <h4>Even more blog post</h4>
            <p>Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
        </div>
    );
}

function Login() {
    return (
        <div>
            <h1>About</h1>
            <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam,
                eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.</p>
        </div>
    );
}


export default App;`

so why it's not working when pointing to the real components?!!
