### ISSUE TITLE
5.1.0 have bug with to="#"

### ISSUE THREAD

**Issue by Saibamen** [ReactTraining/react-router#6931]
Version 5.1.0 have bug.
```
import { NavLink as Link } from 'react-router-dom';
import { NavLink } from 'reactstrap';
<NavLink tag={Link} to="#" onClick={logout}>{t('navMenu.logout')}</NavLink>
```

Result:
`<a aria-current="page" class="nav-link active" href="/admin">Logout</a>`

Expected:
`<a aria-current="page" class="nav-link" href="/admin">Logout</a>`

**Comment by timdorr** [comment]
That is not a valid location string. Link/NavLink isn't meant to be a replacement for an `<a>` element. Just use an `<a>` if you don't intend to navigate with the router.
