### ISSUE TITLE
[Proposal] useRedirect hook

### ISSUE THREAD

**Issue by debel27** [ReactTraining/react-router#6932]
**Current situation**

To perform redirects inside an application, `react-router` exposes a `Redirect` component. 

The component works pretty well, but redirects are imperative by nature. With a declarative solution like `Redirect`, you need to have a state somewhere to keep track of the redirect target.

```javascript
import {useState}, React from 'react';
import { Redirect } from 'react-router';

function App(props) {
  const [redirectTo, setRedirectTo] = useState(null);

  return (
    <React.Fragment>
      {{redirectTo && <Redirect to={redirectTo} />}}
      <button onClick={() => setRedirectTo('/about')}>
        about
      </button>
    </React.Fragment>
  );
}
```

Setting up a state each time I need to perform a redirect feels a bit like unnecessary boilerplate.

**Proposal**

Expose a `useRedirect` hook that would prevent the need of an intermediary state.

```javascript
import {useState}, React from 'react';
import { useRedirect } from 'react-router';

function App(props) {
  const redirect = useRedirect();

  return (
    <button onClick={() => redirect('/about')}>
      about
    </button>
  );
}
```

I realize this is not a substantial improvement to developer experience, but it would help reduce friction :)

The API of the `redirect` function returned by the hook (inspired by [the current API](https://reacttraining.com/react-router/web/api/Redirect)) could be something in the lines of

```javascript
(to: string | Object, opts: {/* ... */}) => void
```

**Comment by mjackson** [comment]
What's wrong with `useHistory`?

```js
import { useHistory } from 'react-router-dom';

function App(props) {
  let history = useHistory();

  return (
    <button onClick={() => history.replace('/about')}>
      about
    </button>
  );
}
```

**Comment by debel27** [comment]
Nothing. Let's close this
