### ISSUE TITLE
Issue with `useParams` hook on unmounted component

### ISSUE THREAD

**Issue by brandon-pereira** [ReactTraining/react-router#6938]
# Version

5.1.0

## Test Case

https://codesandbox.io/s/jolly-field-rm0sb

## Steps to reproduce

Use the `children` prop on a `<Route />` to render a component. 

## Expected Behavior

Like with accessing `match` off of props, `useParams()` should return `null` or an empty object.

## Actual Behavior

`useParams` errors when reading property off null.

**Comment by brandon-pereira** [comment]
To fix, update this line: https://github.com/ReactTraining/react-router/blob/0c058adc5b56c6d9b409af5e4d8330c645fac00c/packages/react-router/modules/hooks.js#L39 to 

```
const match = useContext(Context).match
return match ? match.params : {}
```

**Comment by timdorr** [comment]
That's the right place for it, so if you want to submit a PR, go right ahead!

**Comment by brandon-pereira** [comment]
@timdorr PR has been opened :)
