### ISSUE TITLE
TypeError with useHistory hook

### ISSUE THREAD

**Issue by CodeColde** [ReactTraining/react-router#6939]
#6383  
# Version

5.1.0

## Test Case

https://codesandbox.io/s/usehistory-type-issue-0556g

## Steps to reproduce

Simply defined useHistory within a component or any function within  a typescript project. This works absolutely fine in regular javascript projects.

1. Add a component in react
2. `let history = useHistory();` inside the functional component
3. do anything

## Expected Behavior

Acquire access to the history property. Component should render without bugs and I should have access to the history prop.

## Actual Behavior

TypeError: Cannot read property 'history' of undefined

Stack trace points directly to the hook function 
```
Module.useHistory
.../node_modules/react-router/esm/react-router.js:704
  701 |     !(typeof useContext === "function") ? process.env.NODE_ENV !== "production" ? invariant(false, "You must use React >= 16.8 in order to use useHistory()") : invariant(false) : void 0;
  702 |   }
  703 | 
> 704 |   return useContext(context).history;
  705 | }
  706 | 
  707 | function useLocation() {
```

**Comment by timdorr** [comment]
You have to use it from a component that's placed under your Router in the tree. It doesn't work at the top level because the context hasn't been added to the tree at that point. 

I moved it to the Index component and it works fine: https://codesandbox.io/s/usehistory-type-issue-zkyny

**Comment by keeganstothert** [comment]
I have the exact same issue after updating to 5.1.2

my BrowserRouter is the very root of my app, I downgraded and it works fine again.

**Comment by zen0822** [comment]
> 
> 
> I have the exact same issue after updating to 5.1.2
> 
> my BrowserRouter is the very root of my app, I downgraded and it works fine again.

Me too

**Comment by tianhuil** [comment]
Using `BrowserRouter` worked for me.  However, could we make this error more descriptive @timdorr ?  Ideally, the error message about "React >= 16.8" should only apply if my react version is low.

**Comment by timdorr** [comment]
That would be up to React to implement in `useContext`.
