### ISSUE TITLE
redirect will cause loop serState when version is big than 4.3.1

### ISSUE THREAD

**Issue by closertb** [ReactTraining/react-router#6943]
## Version

**Please replace this sentence with the React Router version that you are using.**
4.3.1 is right
4.4.0 and 5.1.0 is wrong

## Test Case
it`s a comany project, so i just show the code

// validPaths and menu are an array; only pathname in validpath can render the right component, or it will redirect to home component;
```javascript
    <Router history={history}>
      <div className="content">
        {menu.map(({ path, component }) => (
          <Route exact key={path} path={path} component={Pages[component]} />
        ))}
        {!validPaths.includes(pathname) && <Redirect from={pathname} to="/home" />}
      </div>
    </Router>
```

## Steps to reproduce
when i input an url are not in validPath, the page will crash

## Expected Behavior
it render right
## Actual Behavior
![image](https://user-images.githubusercontent.com/22979584/65751006-3aa9ba80-e13c-11e9-873c-b3cea0c299f5.png)

![image](https://user-images.githubusercontent.com/22979584/65751051-52813e80-e13c-11e9-8a34-8e855db8b5e4.png)

the setState repeat call until the page crash

**Comment by pshrmn** [comment]
It is difficult to say without a working demo, but I believe that if you wrap your routes & redirect in a `Switch`, the issue will go away.

If you take a look at the [`Redirect from`](https://reacttraining.com/react-router/web/api/Redirect/from-string) documentation, you will see that it only works in a `Switch`. Outside of a `Switch`, the `Redirect` will attempt to redirect every time it renders.

**Comment by closertb** [comment]
> It is difficult to say without a working demo, but I believe that if you wrap your routes & redirect in a `Switch`, the issue will go away.
> 
> If you take a look at the [`Redirect from`](https://reacttraining.com/react-router/web/api/Redirect/from-string) documentation, you will see that it only works in a `Switch`. Outside of a `Switch`, the `Redirect` will attempt to redirect every time it renders.

I know Switch. i do not use it because some lib incompatible switch model, so i just ues route and use Redirect with condition. why in version 4.3.1, It works well. Is there other way to fix it
