### ISSUE TITLE
<Link> Component Does Not Set Browser History

### ISSUE THREAD

**Issue by vpillinger** [ReactTraining/react-router#6945]
The \<Link\> component uses the History object, which uses the the built-in pushState function from the browser. However, the History object does not implement the full range pushState parameters.

This creates an issue with the browser history where the page titles are not accurately reflected.
In order for the Browser History to be set correctly in all cases, it needs to have the title set in the pushState call. Currently, React Router does not support this because the "title" parameter is forced to null.

One can manually call document.title to set the title in the browser history after the fact, which works in Chrome, IE, and Firefox. But if something interrupts the script before document.title is called, then the title will be incorrect in the browser history.

I put in the relevant code here.
https://github.com/ReactTraining/react-router/issues/6888

**Comment by timdorr** [comment]
`pushState`'s second arg (`title`) isn't supported in any browser, as far as I know. So implementing that wouldn't have any effect anyways.

We recommend using something like react-helmet because it offers a more complete title management API. That includes more complex scenarios, like SSR.
