### ISSUE TITLE
Hooks are not documented on main website

### ISSUE THREAD

**Issue by jrop** [ReactTraining/react-router#6946]
The main website (https://reacttraining.com/react-router/) does not seem to document the new hooks API(s).  I am quite excited to use the new API, and would like to refer to something more official than the announcement blog post.  Is there an issue/PR that is tracking this?  Once the docs are up, I am also waiting on the typings from DefinitelyTyped (which seems to recently have landed).

**Comment by timdorr** [comment]
I just merged in master to the website branch. That should update things shortly!

**Comment by mjackson** [comment]
I'm working on it!!!

**Comment by mjackson** [comment]
Until they are up on the official site, you can always find the latest docs here on GitHub, @jrop. Just for future reference.

**Comment by mjackson** [comment]
Whoops. Looks like the build of the website branch failed and actually ended up taking down the whole site https://travis-ci.org/ReactTraining/react-router/jobs/590575401

I've reverted the change in the website repo for now, so the docs should be back up shortly. But let's not push to `website` again until this is fixed.

**Comment by mjackson** [comment]
Gonna re-open until this is fixed.

**Comment by jrop** [comment]
@mjackson Just wanted to clarify that I am not intending to express any entitlement here.  Neither am I wanting to rush you.  My intent was to create a source to "track this": if it is just noise, please close.

Thanks for such a great project.  And also, thanks for the new hooks!  🍰 🚀

**Comment by mjackson** [comment]
Thanks, @jrop. I appreciate it.

I'm working on fixing things right now. Should have those docs up shortly 👍

**Comment by mjackson** [comment]
Fixed the website deploy script. There are some layout issues on the site, but we can fix those later.
