### ISSUE TITLE
how to always re-render when change url. (with /:id)

### ISSUE THREAD

**Issue by huurray** [ReactTraining/react-router#6949]
this is example code
```javascript
<Switch>
      <Route path={`/user`} component={User} />
      <Route path={`/user/:id`} component={UserDetail} />
</Switch>
```

hello. i always would like to re-render when i change url. 
this is situation.
once i go url '/user/1' for example, and i go url 'user/2' too
and if i go url '/user/1' again, UserDetail Component with id which is 1 never re-render.

how can i always re-render this??  thanks for reading this!

**Comment by StringEpsilon** [comment]
`<Switch/>`  will rerender the *first matching* route. In your case, `/user/1234`  will still match `/user`.

You can either switch the order of your routes, or put the `exact` prop on the first:

```jsx
<Switch>
  <Route path="/user" exact component={User} />
  <Route path="/user/:id" component={UserDetail} />
</Switch>

// or:

<Switch>
  <Route path="/user/:id" component={UserDetail} />
  <Route path="/user" component={User} />
</Switch>
```
