### ISSUE TITLE
how to get unmount event correctly when change url (/:id)

### ISSUE THREAD

**Issue by huurray** [ReactTraining/react-router#6950]
hello! this is example code
```javascript
<Switch>
      <Route exact path={`/user`} component={User} />
      <Route exact path={`/user/:id`} component={UserDetail} />
</Switch>
```

```javascript
export default function UserDetail() {
   useEffect(()=> {
      return () => {
        console.log(111)
      }
   }, [])
   return (
    ...
   )
}
```

hello. i would like to get unmount event when i change url.
this is situation.
once i go url '/user/1' for example.
and when i go url 'user/2', i can't get 'console.log(111)' correctly.

how can't i get unmount event? thanks for reading.

**Comment by MeiKatz** [comment]
You could at a key to the route. This should fix things.

**Comment by pshrmn** [comment]
If you pass the `id` params to `useEffect`'s dependency array, then the returned function will be called when changing users.

https://codesandbox.io/s/silly-tdd-ukq4l
