### ISSUE TITLE
Redirect doesn't work inside Switch when Fragment has been used.

### ISSUE THREAD

**Issue by jamil-alisgandarov** [ReactTraining/react-router#6953]
## Version

`"react-router": "5.0.1",`

## Test Case

```tsx
<Switch>
    <Route
        component={TestComponent}
        key={TestComponentPath}
        path={TestComponentPath}
        exact
    />
    {
        exampleCondition && (
            <>
                 <Route
                    component={TestComponent2}
                    key={TestComponentPath2}
                    path={TestComponentPath2}
                    exact
                 />
                 <Route
                    component={TestComponent3}
                    key={TestComponentPath3}
                    path={TestComponentPath3}
                    exact
                 />
            </>
        )
    }
    <Redirect to={redirectUrl} />
</Switch>
```
                                        

## Steps to reproduce
Showed example `Switch`, `Redirect` use case.

## Expected Behavior

Should redirect to the given `redirectUrl` path if no path is matched.

## Actual Behavior

Acts like no `Redirect` has been provided at the end of switch. Problem is probably caused by `React.Fragment` that has been used inside `Switch`. Redirection works fine when it's removed.

**Comment by timdorr** [comment]
This is expected behavior. Switch doesn't traverse Fragments.

**Comment by BrunoQuaresma** [comment]
Is there any workaround?
