### ISSUE TITLE
Suggestion: use history.action for ScrollToTop component

### ISSUE THREAD

**Issue by schuylr** [ReactTraining/react-router#6959]
I was reading the [Scroll Restoration](https://reacttraining.com/react-router/web/guides/scroll-restoration) documentation but found the current implementation a little lacking, mainly because the effect would invoke a scroll-to-top on every route change, regardless of a `PUSH` or `POP`.

I would like to suggest that you change the documentation to have this component implementation instead which keeps track of the `history.action` property as well:

```
const ScrollToTop = ({
  children,
  history: { action },
  location: { pathname }
}) => {
  useEffect(() => {
    if (action == "PUSH") {
      window.scrollTo(0, 0);
    }
  }, [pathname]);

  return children || null;
};

export default withRouter(ScrollToTop);
```

That way, the component will send the user to the top of the page whenever they proceed to click a `Link` element, but will get out of the way when the user clicks back or forward in their history, allowing the browser's Scroll Restoration to take care of the rest.

Happy to submit a PR with this updated component, an alternative component, and some explanation if you have some guidance on what you would like it to say.

**Comment by timdorr** [comment]
A PR would be the better format for this, but I don't think we need to change the example. It's simplified intentionally. I would use something like react-router-scroll-memory instead if you need more specific behavior.

**Comment by schuylr** [comment]
@timdorr Maybe you missed my point - I wouldn't want to use react-router-scroll-memory at all, in fact my modification leverages the Browser Scroll History spec just like your documentation mentions. This component as it stands currently in the documentation clobbers the Browser Scroll History entirely.

Does that make more sense?
