### ISSUE TITLE
<Link component={X}> causes console warning: "Invalid value for prop `navigate`..."

### ISSUE THREAD

**Issue by justingrant** [ReactTraining/react-router#6962]
A quirk of using the V5.1 `component` prop of `<Link>` is that the component receives a `navigate` prop (which is helpful in some use-cases!) but if you passthrough that prop to a DOM component, then you'll get a React warning message in the console.

A workaround is simple: just strip out `navigate` before passing the props to any underlying component. Like this: 
```js
const CustomLink = props => {
  const { navigate, ...rest } = props;
  return (<a {...rest} />);
}
```

But it was unexpected to have to wrap my existing components to strip that prop, because I'd assumed that I could use existing `<a>`-based components as-is.

This behavior is on the boundary of a bug report and a feature request, because I'm not sure if it's expected to always have to wrap existing components. Is it expected?  Or is there something that react-router should do to prevent this React warning without requiring components to strip out the `navigate` prop?

This requirement (to strip out navigate before passing props to DOM) seems worth documenting when the `component` prop is documented.  In the meantime, I'm filing this issue to make it easy for folks to Google when they run into the same console warning.

## Version

5.1.2 (on React 16.10.1)

## Test Case

https://codesandbox.io/s/dank-waterfall-f0myq

```js
import React from "react";
import ReactDOM from "react-dom";
import { Link, BrowserRouter } from "react-router-dom";

const CustomLink = props => <a {...props} />;
const App = () => (
  <BrowserRouter>
    <Link component={CustomLink} to={"/"}>Link</Link>
  </BrowserRouter>
);

ReactDOM.render(<App />, document.getElementById("root"));
```

## Steps to reproduce
1. Load that page in the browser OR click the link in the page
2. Look at the console

## Expected Behavior
No errors or warnings in the console

## Actual Behavior
```
Warning: Invalid value for prop `navigate` on <a> tag. 
Either remove it from the element, or pass a string or 
number value to keep it in the DOM. For details, see 
https://fb.me/react-attribute-behavior
    in a (at src/index.js:5)
    in CustomLink (created by Context.Consumer)
    in Link (at src/index.js:10)
    in Router (created by BrowserRouter)
    in BrowserRouter (at src/index.js:9)
    in App (at src/index.js:17)   
```

**Comment by timdorr** [comment]
We went through this same thing when React 16 landed. Much of the community needed to update to better handle props passing, as they were doing it unsafely. You shouldn't be passing them along blindly, especially to DOM elements.

**Comment by justingrant** [comment]
Sounds right, thanks.
