### ISSUE TITLE
Isolated Component Instances for Route

### ISSUE THREAD

**Issue by mbrahimi617** [ReactTraining/react-router#6964]
So I have a route like so which is supposed to render a `GuidePage` component for the following path pattern. This component contains a Dashboard component which is essentially a container for a context for the side menu which assists in toggling it to be opened or closed. 

```jsx
<Route exact path="/:platform" component={GuidePage} />
```

I eventually came to realize that React router doesn't actually create a new component for each platform, nor does it seem to unmount and remount them. Rather there's only one such `GuidePage` instance for all platforms be it /Dell or /Lenovo etc. They all use the same Dashboard, same context, same everything except for the location match. That being said I was wondering if there's a way to isolate matches belonging to the same Route.

**Comment by MeiKatz** [comment]
Yes, there is:
```jsx
<Route exact path="/:platform" key={location.pathname} component={GuidePage} />
```

You get `location.pathname` either from `withRouter`, wrapping another `<Route />` around it or from `useLocation()` hook.

**Comment by mbrahimi617** [comment]
Can you demonstrate that or point to the docs?

**Comment by MeiKatz** [comment]
```jsx
function Wrapper() {
  const { pathname } = useLocation();

  return (
    <Route exact path="/:platform" key={pathname} component={GuidePage} />
  );
}
```
And that's everything. React looks for a `key` prop on every component and if this changes it will handle components as different ones. Therefore a component with `key="Dell"` is another one as the one with `key="Lenovo"`.

**Comment by mbrahimi617** [comment]
This doesn't appear to be working. Let me send a Code Sandbox.

**Comment by mbrahimi617** [comment]
https://codesandbox.io/embed/boring-herschel-080df

**Comment by mbrahimi617** [comment]
Each time a different platform is clicked, there should be a different ID in the corner signifying a different context.

**Comment by MeiKatz** [comment]
If done right, this works very well: https://codesandbox.io/s/adoring-brattain-3s9e1

**Comment by mbrahimi617** [comment]
Ok awesome. Thank you. I'm not sure why this isn't the default behavior. Thanks again.
