### ISSUE TITLE
Feature Request: support lazy loaded components for <Route children />

### ISSUE THREAD

**Issue by MeiKatz** [ReactTraining/react-router#6965]
@mjackson you told me, that I should open an issue because writing code. So here's my first try.

There is currently an open issue (https://github.com/ReactTraining/react-router/issues/6960#issuecomment-537983562) where a user mentioned, that dropping `<Route render />` and `<Route component />` would be a little of a feature loss because `<Route component />` supports lazy loaded components. `<Route children />` does not support it currently – well, it does, but it makes things a little harder because we have to save the return of `React.lazy()` in a variable, so we can use it afterwards.

Therefore I would like a feature that detects lazy loaded components via `React.lazy()` and initializes them for the user, something like the following:
```jsx
<Route path="/foo">
  {React.lazy(() => import("./foo"))}
</Route>
```

**Comment by timdorr** [comment]
This seems like a React concern, not a Router one. 

I'm not sure what the Router is supposed to try and do exactly. The parent element has control here and by the time Route gets its children, they've already been created/instantiated. How is Route going to stop that?

Just do `const Foo = lazy(() => import('./foo'))` at the top of your file. It's the same number of lines as a static import, so I don't see what inlining everything gets you.

**Comment by MeiKatz** [comment]
@timdorr Valid point. Seems as if I was tempted by the moment and not thought about this in the deep. I think we can close it.

**Comment by ainama** [comment]
> Warning: Failed prop type: Invalid prop `component` of type `object` supplied to `Route`, expected `function`.
    in Route

```js
import React, { Suspense, lazy } from 'react';
import ReactDOM from 'react-dom';
import { Provider } from 'react-redux';
import { BrowserRouter as Router, Route } from 'react-router-dom';
import store from './store/index.js';

const App = lazy(() => import('./page/app.jsx'));
const PageOne = lazy(() => import('./page/pageOne.jsx'));
const PageTwo = lazy(() => import('./page/pageTwo.jsx'));
const Hook = lazy(() => import('./page/hook.jsx'));

function app() {
  return (
    <Provider store = { store }>
      <Router>
        <Suspense fallback = { null }>
          <div>
            <Route exact path = '/' component = { App } />
            <Route exact path = '/pageOne' component = { PageOne } />
            <Route exact path = '/pageTwo' component = { PageTwo } />
            <Route exact path = '/hook' component = { Hook } />
          </div>
        </ Suspense>
      </Router>
    </Provider>
  );
};

ReactDOM.render(
  app(),
  document.getElementById('root')
);

```

> React.lazy takes a function that must call a dynamic import(). This must return a Promise which resolves to a module with a default export containing a React component.
https://reactjs.org/docs/code-splitting.html

**Comment by mjackson** [comment]
Just wanted to note here that in v6 `<Route element>` will be able to preload `React.lazy` components. I currently have a hacky solution for this if they don't include support for it in React.
