### ISSUE TITLE
React-router v3 should remove obsolete lifecycle methods

### ISSUE THREAD

**Issue by MastroLindus** [ReactTraining/react-router#6968]
V3 still uses componentWillReceiveProps and componentWillMount so react warns about it.
I know that v3 is not activately developed (I plan to migrate to V6 if the API is going to be good, sorry I am not a fan of v4 or v5 API) but I think it is still maintained right? It would be already enough to just rename the lifecycles in their UNSAFE variant.

Even if I am not using the latest releases, thank you for you hard work guys!

**Comment by timdorr** [comment]
This was fixed in #6961, but hasn't been released yet.
