### ISSUE TITLE
Docs for Animated Transitions Example are broken.

### ISSUE THREAD

**Issue by evgenitsn** [ReactTraining/react-router#6973]
## Version

v.5.1.2

## Steps to reproduce

Go to https://reacttraining.com/react-router/web/example/animated-transitions
There is an error:

> Something went wrong while fetching the sandbox: file not found at: https://raw.githubusercontent.com/ReactTraining/react-router/master/website/modules/examples/Animation/styles.css

## Expected Behavior

The site should load the example w/o errors.

## Actual Behavior

The site shows error about missing .css file.

**Comment by mjackson** [comment]
I think this might have happened when you tried to load a cached version of the website. I moved the examples from `/website/modules/examples` to `/packages/react-router-dom/examples`. But everything appears to be working properly now. Please clear your cache and try again.
