### ISSUE TITLE
<Prompt/> doesn't work on mobile browsers

### ISSUE THREAD

**Issue by B2alex** [ReactTraining/react-router#6979]
## Version
"react-router-dom": "^4.3.1"

## Steps to reproduce

Create component with <Prompt/> and try to change location on mobile browsers (latest chrome and firefox on Android), I haven't tested it out iOS and Safari yet.

```
render() {
    return (
        <div className={styles.container}>
           <Prompt message="Don't leave"/>
           <div className={styles.headingcontainer}>
                <h4 className={styles.heading}>Enter things</h4>
           </div>
        </div>
    );
}
```

## Expected Behavior

Prompt user before location change

## Actual Behavior

Does not prompt user like desktop browsers.

**Comment by timdorr** [comment]
Mobile browsers don't support `onbeforeunload`. Nothing we can do about that, unfortunately.
