### ISSUE TITLE
Error in exporting useHistory

### ISSUE THREAD

**Issue by EdDevs2503** [ReactTraining/react-router#6987]
![image](https://user-images.githubusercontent.com/45980184/66577894-23a99600-eb48-11e9-9099-b5f28b328046.png)

And i have this error

![image](https://user-images.githubusercontent.com/45980184/66577946-38862980-eb48-11e9-9e09-bd0a9820114e.png)

**Comment by timdorr** [comment]
It's definitely in there and exported: https://unpkg.com/browse/react-router@5.1.2/cjs/react-router.js

My best guess is you are using direct imports (which are deprecated) or you need to blow away your node_modules and reinstall.
