### ISSUE TITLE
redunant history in same url

### ISSUE THREAD

**Issue by LitileXueZha** [ReactTraining/react-router#6990]
example likes below:
https://stackoverflow.com/questions/54252787/link-component-update-browser-history-when-location-is-the-same

most people like to use gestures on mac, but when you clicked `Link` again and again, it lose.

**Comment by timdorr** [comment]
This is just how the history API works in the browser. If you open up the console and type `history.pushState({}, "test", "/test")` a bunch of times, you'll see it adds to the history stack even though the URLs are the same.
