### ISSUE TITLE
Feature - Ability to name routes and pass the name to generatePath instead of the pattern

### ISSUE THREAD

**Issue by bradleylandis** [ReactTraining/react-router#6992]
This would prevent you from having to update the pattern in each location where you have a link when you want to change the patterns.

Where you are configuring your routes:

```
<Route path="/user/:id/:entity(posts|comments)" name="userEntityRoute">
        <UserEntity />
</Route>
```

where you want to create a link:

```
import { generatePath } from "react-router";

generatePath("userEntityRoute", {
  id: 1,
  entity: "posts"
});
// Will return /user/1/posts
```

**Comment by timdorr** [comment]
This hasn't existed in React Router since the pre-1.0 days. We aren't adding it back.
