### ISSUE TITLE
Documentation Breaks on Firefox with Tracking Protection

### ISSUE THREAD

**Issue by Zaldos** [ReactTraining/react-router#6996]
## Test Case
View documentation pages: Examples e.g. [https://reacttraining.com/react-router/web/example/basic](https://reacttraining.com/react-router/web/example/basic)

## Steps to reproduce
1. Enable tracking protection on Firefox
![image](https://user-images.githubusercontent.com/350699/66810424-2d0b7780-ef27-11e9-9d8e-abfe46efbabd.png)
2. View examples page on documentation [https://reacttraining.com/react-router/web/example/basic](https://reacttraining.com/react-router/web/example/basic)

## Expected Behavior
1. I should be able to view the react router examples.

## Actual Behavior
Errors in console and no page loading
![image](https://user-images.githubusercontent.com/350699/66810542-5d531600-ef27-11e9-9490-ce00b039c969.png)
![image](https://user-images.githubusercontent.com/350699/66810573-693ed800-ef27-11e9-9b31-b7f9097bd78d.png)

**Comment by timdorr** [comment]
This is on Codesandbox's end. You can try opening up an issue with them: https://github.com/codesandbox/codesandbox-client

**Comment by mreishus** [comment]
It doesn't load for me in Firefox, even with enhanced tracking off (I went to codesandbox and turned it off there as well, then tried turning it off completely in the preferences).  I get a CORS error

![Screenshot](https://i.imgur.com/2Smklhd.png)
