### ISSUE TITLE
Make match.router available from hooks

### ISSUE THREAD

**Issue by gndelia** [ReactTraining/react-router#6997]
### Feature Request

[match.path](https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/api/match.md) is not available through any hook. I can access it by using `withRouter`, but if I am using hooks the idea (I believe) is not to use HOC anymore

I need it because  my routes are something of the line like

```jsx
<Route path='/company/:companyId/dashboard/:mode'>
  <Component1 />
</Route>
<Route path='/dairy/:dairyId/dashboard/:mode'>
  <Component2 />
</Route>
```

both `<Component1>` and `<Component2>` use a commont `<CommonComponent>` which, among its lines, has

```jsx
const onCallback = () => {
  // match.path has "/company/:companyId/dashboard/:mode" or "/dairy/:dairyId/dashboard/:mode" which is what I need
// but match is not available with the new router hooks, only from withRouter HOC
  const createUrl = match
      .path
      .replace(/:mode/, 'create') // I am in mode, let's say "view" and I navigate to "create"
      .replace(knowVariableWithRegexForIntermediateParameter, id) // replacing :companyId or :dairyId
  history.push(createUrl)
}
```

history is accessed with `useHistory`

**Comment by MeiKatz** [comment]
Why don't you use the `useRouteMatch()` hook?

**Comment by gndelia** [comment]
unless I misinterpreted the docs, `useRouteMatch()` requires me to pass the URL to match a parameter. But I do not want to match a parameter, but the url. I would have to know the URL in advance in order to pass it as a parameter, but that is what I want to access instead

**Comment by MeiKatz** [comment]
If you don't pass a parameter the path of the closes parent route will be used.

**Comment by gndelia** [comment]
I see, cool. That made it work. Thanks!

Is it documented anywhere? I couldn't find that behaviour on docs.

Closing, btw

**Comment by MeiKatz** [comment]
Not sure about the documentation part, but I think that the code is documentation is enough: https://github.com/ReactTraining/react-router/blob/master/packages/react-router/modules/hooks.js#L43

**Comment by bocong** [comment]
It's not quite the same, especially because useRouteMatch can be used outside of a Route.

The Typescript defs for it reflect this (it returns a the match object or null), which makes it difficult to use.

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-router/index.d.ts#L160
