### ISSUE TITLE
v3.2.5 with #6961 fix.

### ISSUE THREAD

**Issue by erictaylor** [ReactTraining/react-router#6998]
https://github.com/ReactTraining/react-router/pull/6961 fixed the bug in regards to how react versions are detected and was merged in 14 days ago but no new version has been cut with this fix. Can we get a 3.2.5 with that fix?

cc: @timdorr

**Comment by oliverhughes** [comment]
Yes please, this would be great 👍

**Comment by timdorr** [comment]
Sorry for the delay. Just pushed it now. `npm install react-router@previous`
