### ISSUE TITLE
Using useHistory() hook on main app component is re-rendering the main component on react route change

### ISSUE THREAD

**Issue by Jayabratha** [ReactTraining/react-router#7001]
## Version

**5.1.2**

## Test Case

https://codesandbox.io/embed/react-router-t9i3m

## Steps to reproduce
Using useHistory() hook on main app component is re-rendering the main component on react route change.

Click on reach route link to see the alert getting invoked from the app component.

## Expected Behavior
On route change the main app should not re-render.
## Actual Behavior
The entire app is rendering on reach route change when we have an reference of useHistory() on app component.

**Comment by MeiKatz** [comment]
Same as https://github.com/ReactTraining/react-router/issues/6999
