### ISSUE TITLE
useMatch hook

### ISSUE THREAD

**Issue by jamesmfriedman** [ReactTraining/react-router#7004]
Maybe this was just an oversight, or I'm missing something... When I saw that hooks were added I was really excited. Getting the location and history object without having to endlessly pass them down the props chain or import a global history object is great.

Except the thing that I have to pass around constantly is the match object... Like everywhere. All over the app, anytime I want to add a link, new route, or something that is url aware, it's generally based off the current match.

So, anyways I was extremely surprised when I looked at the hooks implementation of the 4 that are currently available only to see that implementing a match hook would take 3 lines of code (not including the DEV console logging). 

I went ahead and implemented this myself in one of my projects using the ultra private variable.

```
// My own implementation
export function useMatch() {
  return useContext(__RouterContext).match;
}
```

So, why is useMatch not an available hook for react-router proper?

**Comment by MeiKatz** [comment]
It exists, but it's called `useRouteMatch`.

**Comment by jamesmfriedman** [comment]
useRouteMatch is not the same functionality.

useRouteMatch takes the same type of parameters the Route component takes and gives you a true fales back.

the useMatch example I posted exposes the current match from somewhere higher up in the tree. A contrived example.

A typical example of how things currently work
```javascript
<Route path='/' render={(match) => <MyComp match={match} />}

function MyComp({match}) {
  return <AnotherComp match={match} />
}

function AnotherComp() {
  return <Link to={`${match.path}/details`} />
}
```

How this works with the useMatch hook I posted:
```javascript
<Route path='/' render={() => <MyComp />}

function MyComp() {
  return <AnotherComp />
}

function AnotherComp() {
  const match = useMatch();
  return <Link to={`${match.path}/details`} />
}
```

The devil is in the details. userRouteMatch requires you to know the parent route your matching. In the examples I posted, the child is unaware of its parent routes (as it should be). All it knows is that a Route was matched somewhere higher in the tree and that it can get access to it.

**Comment by MeiKatz** [comment]
`useRouteMatch` can do two since:
1. you can pass a path to it and it checks if it matches the current url.
2. if you omit the `path` parameter it will use the clothest `<Route />` match and will return it. Therefore this should be, what you are searching for.

**Comment by jamesmfriedman** [comment]
Thanks @MeiKatz! That particular detail is definitely missing in the documentation, but I'll take your word for it.
