### ISSUE TITLE
componentWillUnmount hadn't been called If a Component rendered by using ReactDom.render whiling switched router

### ISSUE THREAD

**Issue by yanyu0517** [ReactTraining/react-router#7005]
There is a Component that had been rendered into the router by using ReactDom.render. 
While switched the router to other paths, the componentWillUnmount of the Component wasn't called.
You can see the example, `<Extension>` Component would be inserted to the dom which id is 'slot', the router path will be changed after clicking the Schedule Link. But the componentWillUnmount of `<Extension>` Component willn't be called

https://codesandbox.io/s/a-simple-react-router-v4tutorial-ns454

**Comment by timdorr** [comment]
That's not how you're supposed to render content in other parts of the DOM. You should be using a portal there.
