### ISSUE TITLE
Cannot read property 'location' of undefined at useLocation

### ISSUE THREAD

**Issue by lewislbr** [ReactTraining/react-router#7015]
## Version

"react": "^16.11.0",
"react-router-dom": "^5.1.2"

## Test Case

https://stackblitz.com/edit/react-router-uselocation-error

## Steps to reproduce

1 - Create a variable referencing a useLocation call.
2 - Try to access the variable.

## Expected Behavior

The variable being accessible.

## Actual Behavior

An error happens in line 713 of the `react-router.js` file of the `react-router` package.

```
Uncaught TypeError: Cannot read property 'location' of undefined
    at useLocation (react-router.js?4f2e:713)
```

The fragment is:

```javascript
...
function useLocation() {
  if (process.env.NODE_ENV !== "production") {
    !(typeof useContext === "function") ? process.env.NODE_ENV !== "production" ? invariant(false, "You must use React >= 16.8 in order to use useLocation()") : invariant(false) : void 0;
  }

  return useContext(context).location; // Error here.
}
...
```

---

Am I missing something?

Thanks.

**Comment by timdorr** [comment]
You can't use any of the hooks from within the same component that puts the Router into the tree. 

You need to move your BrowserRouter out of that component. It can go in the ReactDOM.render() call, for instance.

**Comment by lewislbr** [comment]
Ahhh got it! Thanks!
