### ISSUE TITLE
children route has been rendered without matching url in no switch

### ISSUE THREAD

**Issue by lovelyJason** [ReactTraining/react-router#7017]
just like this
`<Router>
<Route path="/a" exact component={ComA}></Route>
                <Route path="/b" exact component={ComB}></Route>
                <Route path="/render" exact>
                    {
                        data => {
                            return (<div>render
                                render component
                            </div>)
                        }
                    }
                </Route>
                <Route path="/C" exact component={ComC}></Route>
</Router>`
Now, the problem is, there is no Switch wrap these routes up,when I open links 'http://localhost:3000/404',normally,it should be rendered last route component 'ComC' on the web page,because I have not use Switch to  wrap these routes up.I can understand.But, why the component of url '/render' has also been rendered on the page.This must be unreasonable.Right?this is my question, thank you for your reading.

**Comment by MeiKatz** [comment]
It depends on the version of RR you are working with. There was a breaking change in the last minor version. Previous of it routes with `children` rendered always, ignoring the `path` property. In the latest version it works as you expected it to work.
