### ISSUE TITLE
Examples on the website don't work in Firefox

### ISSUE THREAD

**Issue by tad-lispy** [ReactTraining/react-router#7018]
## Version

N/A

## Test Case

N/A

## Steps to reproduce

1. Use Firefox 70.0.1

   64bit OSX

1. Navigate to https://reacttraining.com/react-router/web/example/basic

   or any other example page

1. Observe that the main section of the site is blank

   ![image](https://user-images.githubusercontent.com/1684495/68212846-abb17d00-ffda-11e9-89d3-27ac79846734.png)

1. Open developers' console and observe that the a request was blocked by CORS policy

   ```
   Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://codesandbox.io/api/v1/sandboxes/define?json=1. (Reason: CORS request did not succeed).
   ```

## Expected Behavior

All parts of the website are working well with all standards compliant browsers.

## Actual Behavior

As described above, the examples do not render. It works fine on latest Chromium and Chrome.

---

Thank you for all your work on React Router and the website. It's a solid piece of software and other than this issue the website is very helpful. Hope my report helps you make it even better.

**Comment by etisdew** [comment]
Can confirm and reproduce. Hope to have documentation available via the site ASAP. Not sure what alls changed since last using a client router.

**Comment by pshrmn** [comment]
I'm pretty sure that you have something installed (quite possible Privacy Badger) that is blocking CodeSandbox.

**Comment by wojtekmaj** [comment]
Yeah, for me it was Privacy Badger blocking codesandbox.io.

**Comment by tad-lispy** [comment]
> I'm pretty sure that you have something installed (Privacy Badger, if I had to guess) that is blocking CodeSandbox.

Yes, that is correct.

**Comment by tad-lispy** [comment]
Please excuse my persistence, but are you sure this issue should be closed? We now understand the technical reason of the issue, but it's gone. Perhaps you should at least consider to change the website to be compatible with this extension, and arguably to be more privacy respecting.

One way would be to provide code samples as static text with links to live examples on codesandbox. Or at least to display some explanation (links?) if the content is blocked. I understand that it's some extra work and I respect your time, but please consider it.

**Comment by timdorr** [comment]
We don't control CodeSandbox's CORS headers. Moreover, we can't fix this if the extension you are using is manipulating the page content after we publish it. Either make an exception for the RR docs site or disable the extension. There's nothing we can do on our end.

**Comment by etisdew** [comment]
My issue is with the sandbox itself, even dropping my guard completely my network refuses the cors and simply forking the source and testing with it (unprotected) the example falls apart on any signifigant changes. Perhaps there are known issues causing this on their side, but it does seem like this should be closed. I'd reccomend anyone evaluating recent changes just fork and use the examples in repo.

**Comment by tad-lispy** [comment]
> We don't control CodeSandbox's CORS headers [...] There's nothing we can do on our end.

Well, but you do control the content of your website, right? You do not have to use CodeSandbox. Again, I respect your time, I'm grateful for the effort you put into this project and hate to be the pain in the back. It's ok if you say you won't act on it, but I don't think it's fair to say "there's nothing we can do on our end".

**Comment by wojtekmaj** [comment]
Privacy Badger blocks requests based on its heuristics; you can overwrite these if you feel like something is broken. I switched codesandbox.io from Blocked to "No cookies" and everything worked just fine. There's nothing they can do on their end.
