### ISSUE TITLE
Small mistake in Redux Integration documentation

### ISSUE THREAD

**Issue by canibanoglu** [ReactTraining/react-router#7019]
## Version
v5.1.2

This is actually a small mistake in the documentation that I came across. In `packages/react-router/docs/guides/redux.md` it is mentioned that `redux` implements `shouldComponentUpdate` but this is not true, it is `react-redux` that "implements" this. That in itself is a bit leading because as far as I can see `react-redux` doesn't implement this but rather mimics it to force an update if there is a change to the current context's store state. 

Relevant section: 
> The problem is that Redux implements shouldComponentUpdate and there's no indication that anything has changed if it isn't receiving props from the router. 

Probably something like `The problem is that as far as redux and react-redux is concerned that there haven't been any changes to the store`. 

I'd be happy to submit a PR when we agree on a wording for this. Splitting hairs, but still :)

**Comment by timdorr** [comment]
We actually don't do that anymore. The correct change is to just to remove it entirely!

**Comment by canibanoglu** [comment]
Or that :)
