### ISSUE TITLE
Warning: <MemoryRouter> ignores the history prop appears while Memory Router still accepts and handle this property  

### ISSUE THREAD

**Issue by TeplyyMaksim** [ReactTraining/react-router#7021]
## Version
react-router 5.*, react-router-native 5.*

## Test Case
Pass history property (created by `createMemoryHistory`) to NativeRouter or MemoryRouter

## Steps to reproduce
Check dev tools

## Expected Behavior
Warning message does not appear

## Actual Behavior
Warning message appears

## Note
This message confuses me because with proper `history` it works great, so I do not understand is it bad practice to use history in `Memory`/`NativeRouter` or warning is invalid.

**Comment by timdorr** [comment]
If you're making your own history, just use `<Router>` instead.

```js
const history = createMemoryHistory()
<Router history={history} />
```
