### ISSUE TITLE
Incomplete information on scroll restoration and how it relates to React Router

### ISSUE THREAD

**Issue by BBaysinger** [ReactTraining/react-router#7024]
There are a few things that are not clear in your information about scroll restoration. It would be very helpful if these issues could be addressed in your documentation:

https://stackoverflow.com/questions/58772954/scroll-restoration-in-chrome-broken-for-react-spa

Party on!

**Comment by timdorr** [comment]
Thanks, but a PR is the best form for documentation discussion.
