### ISSUE TITLE
useParams returns empty object when used outside of Route

### ISSUE THREAD

**Issue by eden-lane** [ReactTraining/react-router#7026]
## Version

5.1.2

## Test Case

https://codesandbox.io/s/react-router-url-parameters-c8hhf

## Steps to reproduce
1. Try to use `useParams` outside the route

## Expected Behavior
1. `useParams` returns object with current url params

## Actual Behavior
1. Empty object is being returned

**Comment by timdorr** [comment]
This is expected behavior. Params are defined by the Route, so they can't exist outside of that subtree.

**Comment by eden-lane** [comment]
Is there any other way to get params outside of the subtree? I have a component that requires that information (can't use NavLink in that scenario)

**Comment by timdorr** [comment]
You can use the `matchPath` function instead: https://reacttraining.com/react-router/web/api/matchPath
