### ISSUE TITLE
Link to primary components is broken on the React Router website

### ISSUE THREAD

**Issue by morgan-tr** [ReactTraining/react-router#7028]
The link to the "primary components" section at the bottom of the [quick start]( https://reacttraining.com/react-router/web/guides/quick-start) page is broken. 

The current link is:
https://reacttraining.com/react-router/primary-components.md

The link should be:
https://reacttraining.com/react-router/web/guides/primary-components

**Comment by gpltaylor** [comment]
Fixed in #7034
