### ISSUE TITLE
TypeError: b.a.compile is not a function using react-router's switch and redirect

### ISSUE THREAD

**Issue by bobleujr** [ReactTraining/react-router#7032]
I've been trying now for a couple of days to understand a weird behavior and my best guess is that there is something with react-router (in an app based on create-react-app). Whenever I serve this locally through `react-scripts start` everything seems to work properly. Once I deploy this using a static file server, I start getting the following.

    backend.js:6 TypeError: b.a.compile is not a function
        at compilePath (react-router.js:235)
        at generatePath (react-router.js:258)
        at react-router.js:277
        at Vj (react-dom.production.min.js:6658)
        at Uj (react-dom.production.min.js:5530)
        at Mj (react-dom.production.min.js:5519)
        at xj (react-dom.production.min.js:5251)
        at react-dom.production.min.js:2774
        at t.unstable_runWithPriority (scheduler.production.min.js:256)
        at Yf (react-dom.production.min.js:2739)
    r @ backend.js:6
    vi @ react-dom.production.min.js:4482
    Qi.r.callback @ react-dom.production.min.js:4927
    Bg @ react-dom.production.min.js:2997
    Ag @ react-dom.production.min.js:2985
    Wj @ react-dom.production.min.js:6221
    t.unstable_runWithPriority @ scheduler.production.min.js:256
    Yf @ react-dom.production.min.js:2739
    Kj @ react-dom.production.min.js:5984
    xj @ react-dom.production.min.js:5266
    (anonymous) @ react-dom.production.min.js:2774
    t.unstable_runWithPriority @ scheduler.production.min.js:256
    Yf @ react-dom.production.min.js:2739
    ag @ react-dom.production.min.js:2769
    bg @ react-dom.production.min.js:2759
    Hg @ react-dom.production.min.js:5040
    enqueueSetState @ react-dom.production.min.js:3029
    D.setState @ react.production.min.js:61
    updateAccessTokenState @ App.tsx:189
    _callee3$ @ App.tsx:165
    tryCatch @ runtime.js:45
    invoke @ runtime.js:264
    e.<computed> @ runtime.js:98
    asyncGeneratorStep @ asyncToGenerator.js:3
    _next @ asyncToGenerator.js:25
    Promise.then (async)
    asyncGeneratorStep @ asyncToGenerator.js:13
    _next @ asyncToGenerator.js:25
    (anonymous) @ asyncToGenerator.js:32
    (anonymous) @ asyncToGenerator.js:21
    componentDidMount @ App.tsx:62
    Wj @ react-dom.production.min.js:6200
    t.unstable_runWithPriority @ scheduler.production.min.js:256
    Yf @ react-dom.production.min.js:2739
    Kj @ react-dom.production.min.js:5984
    xj @ react-dom.production.min.js:5266
    (anonymous) @ react-dom.production.min.js:2774
    t.unstable_runWithPriority @ scheduler.production.min.js:256
    Yf @ react-dom.production.min.js:2739
    ag @ react-dom.production.min.js:2769
    bg @ react-dom.production.min.js:2759
    Hg @ react-dom.production.min.js:5040
    gk @ react-dom.production.min.js:6933
    hk @ react-dom.production.min.js:6942
    sk @ react-dom.production.min.js:7202
    render @ react-dom.production.min.js:7252
    (anonymous) @ index.tsx:32
    Promise.then (async)
    (anonymous) @ index.tsx:30
    Promise.then (async)
    1649 @ index.tsx:25
    f @ (index):1
    796 @ tools.svg:1
    f @ (index):1
    a @ (index):1
    e @ (index):1
    (anonymous) @ main.8c9875e9.chunk.js:1
    logging.ts:11 Error: App._onStartSignin: failed to get the existing access token. Exception: TypeError: b.a.compile is not a function

 My code using react-router is

    class Content extends React.Component<{}, any> {
      static hist = createBrowserHistory();
    
      componentDidMount()
      {
        Sidebar.init(Content.hist);
      }
    
      render() {
        return (
          <Router history={Content.hist}>
            <Switch>
              <Route path= {RoutingPath.somePath}  render={props => <AdminLayout {...props} />} />
              <Redirect from="/" to= {RoutingPath.somePath + "/some-view"} />
            </Switch>
          </Router>
        );
      }
    }

and inside another component I have

    render() {
        return (
          <>
            <div className="wrapper">
              <div
                className="main-panel"
                ref="mainPanel"
              >
                <Switch>{this.getRoutes(routes)}</Switch>
              </div>
            </div>
          </>
        );
      }

The versions that I am using are

"@types/react": "^16.9.7",
"@types/react-dom": "^16.9.2",
"@types/react-router": "^5.1.2",
"@types/react-router-dom": "^5.1.0",
"react-router": "5.1.2",
"react-router-dom": "5.1.2",
"react-scripts": "3.0.1",
"react-dom": "16.10.2",

**Comment by timdorr** [comment]
That's just calling path-to-regexp: https://github.com/ReactTraining/react-router/blob/master/packages/react-router/modules/generatePath.js#L10

Something isn't providing or installing that library. That's not anything to do with React Router, but must have something to do with your build chain. Check that the right version of path-to-regexp is being installed.
