### ISSUE TITLE
Nested Router Component inside Switch

### ISSUE THREAD

**Issue by javierguzman** [ReactTraining/react-router#7036]
Hello all,

Sorry about this, but I am not sure if this is a bug or is the expected behaviour, it would be appreciated if someone can clarify that to me.

I have an Auth Router Component:
```
const authRouter = () => {
  return (
    <>
      <PublicRoute restricted path="/login" exact component={Login} />
      <PublicRoute path="/reset" exact component={ResetPassword} />
      <PublicRoute restricted path="/register" exact component={Register} />
      <PrivateRoute path="/logout" exact component={Logout} />
    </>
  );
};
```
And then in my main Router I have the following:
```
export default function Router() {
  return (
    <BrowserRouter>
      <Suspense fallback={<LoaderSuspense height={500} weight={500} />}>
        <Switch>
          <PublicRoute path="/" exact component={Landing} />
          <AuthRouter />
          <PublicRoute component={NotFound} />
        </Switch>
      </Suspense>
    </BrowserRouter>
  );
}
```
When I enter in a page that does not match anything, it does not go to NotFound component since I created AuthRouter. Fefore I had everything in and it was working fine. Is this a bug or the expected behaviour?

Thank you in advance and regards

p.s. Public/Private Route returns a Route Component

**Comment by timdorr** [comment]
Switch only works on direct, first-level children.
