### ISSUE TITLE
Support side effects when a route is matched

### ISSUE THREAD

**Issue by mnieber** [ReactTraining/react-router#7039]
Hi, I'm trying to find a good way to trigger a side effect when a route is matched. In my case, the side effect is loading some data. Currently, I'm solving this by wrapping the rendered Component with a HOC (`withExtraDataLoading`) that loads the data in a `React.useEffect` call.

```
        <Route exact path={"/app/lists/:ownerUsername"}>
          {withExtraDataLoading(() => (
            <CtrProvider>
              <MainPage />
            </CtrProvider>
          ))}
        </Route>
```

but my code would look much better like this

```
        <Route exact path={"/app/lists/:ownerUsername"} onEnter={loadExtraData}>
            <CtrProvider>
              <MainPage />
            </CtrProvider>
        </Route>
```
This latter version is better because I can get rid of the HOC, I don't need the `React.useEffect` call (that was inside the HOC), and finally, I can drop the anonymous function. Also, conceptually this version is better because the side effect has nothing todo with rendering, so preferably I would not mix these concerns.

I apologize if there is already an elegant way to do this, I tried hard to find one.

**Comment by rob2d** [comment]
just a side comment here: `HOC` is quite a bit of bloat just for a hook; you could create a custom hook and use that in `CtrProvider` which just implements `useEffect`. Much less overhead as a general pattern vs HOC with explicit hook (not to mention this was one of the reason for hooks). You could also just `useRouteMatch` with a result and check that it matches in an effect. If so, load the data.

Having a side effect in the hook is in a similar vein mixing concerns IMHO (make-up/functionality).

**Comment by timdorr** [comment]
Yeah, you should be putting that kind of logic inside of your route component. 

Since you're not passing any props, you don't need an HOC. You can just wrap it in a regular component that runs the effect.

**Comment by mnieber** [comment]
Some points in response:

- in my opinion, it's problematic to assume that side effects (of routing) can always be performed in render functions. I mean, yes, there is probably always a way to use `render` for that, but it seems like an invitation to mix up concerns.

- in my example, `CtrProvider` is designed to be agnostic of data loading, so for the sake of the argument, please accept that `CtrProvider` is not the place where I'd want to put this.

- the React Suspense documentation also suggests that it's an option to decide the loading of data in the router: "This poses a question of how do we know what to fetch before rendering the next screen. There are several ways to solve this (for example, by integrating data fetching closer with your routing solution)."

- (**my main point**) since the Routing code is so central to the application, I would like to make my Router code as expressive as possible. Ideally, I would read the Router code, and directly see what happens if a particular route is rendered. This means that I would prefer not to hide the "extra data loading" step in the render function of some component, but rather show it immediately in the `Route`. The current HOC is serving that purpose, but it's clunky.

**Comment by rob2d** [comment]
@mnieber What you're saying makes sense, with one exception: correct me I'm wrong (to any dev maintainers), but it seems that as the `hooks` are fundamentally linked to `react-router` via a shared context, so we do have that connection if we use `useRouteMatch` 🤔. 

This does not have to exist within `CtrProvider` specifically as you can create a re-usable hook e.g. `useCtrData` -- personally, as an example, I tend to have a `useAutoDataFetcher` hook that I use in my apps which initiates redux actions (created via `redux-wings`), and this essentially can take a param for what action to run when component is loaded automatically. If you generalize your data loading into a hook that is consistent with your app, you don't need to type `useEffect` and add that bloat -- one of the cool things about hooks is re-usability. Obviously this approach isn't *the correct* way or something like that, just thought one could probably use even less boilerplate with a re-usable auto data fetching hook that takes a simple param and calls `useEffect`/etc than without.

[also I'm commenting more for curiosity/discussion on software patterns than to resolve this... not actually a maintainer and don't have a concrete op either way 😅]

**Comment by mnieber** [comment]
Hi @rob2d, yes, we *can* now use hooks for side effects, but we should compare this to the traditional approach of using callback functions.

For example, html elements have `onFocus` in case the programmer wants to create a side-effect of receiving focus. Now imagine that it becomes possible to do this in a different way: when the contents of the div are rendered, we can detect that we just received focus, and produce a side effect there. I think this would obscure the code, it would not be an improvement :-). This is especially true when the side-effect has nothing to do with rendering. In that case, it means an unnecessary mixing of concerns.

**Comment by TroySchmidt** [comment]
I think we are wanting to know how to move beyond the Fetch-On-Render data retrieving pattern to the Suspense leveraging Render-as-you-Fetch.  That would require that data fetching be supported separately as the rendering and that they occur in parallel.
