### ISSUE TITLE
feature request: non-Route children for Switch

### ISSUE THREAD

**Issue by seansfkelley** [ReactTraining/react-router#7041]
This is a (sort of) revival of the recently-closed https://github.com/ReactTraining/react-router/issues/5546.

I would like to be able to provide children to Switch that wrap Routes. This is because I want to colocate my Typescript types for route/query parameters with the methods that read/write those template strings. I also want to allow my components to be mounted anywhere in the path tree, so they have to have totally self-contained behavior when it comes to paths and URLs.

Here's one such file, a little notionalized from reality:

```tsx
export interface RouteParams {
  pointId: string;
  nodeId: string;
}

export interface QueryParams {
  source?: string;
}

export const RouteParams = {
  getPathTemplate: (baseUrl: string) => `${baseUrl}/n/:nodeId/p/:pointId`,
  templateUrl: (baseUrl: string, route: RouteParams, query?: QueryParams) => {
    const url = `${baseUrl}/n/${route.nodeId}/p/${route.pointId}`;
    return query == null ? url : `${url}?${stringify(query)}`;
  },
};

interface Props extends RouteComponentProps<RouteParams> {
  site: Site;
  notificationBanner?: React.ReactNode;
}

export const RoutedPointPage = (props: Props) => (
  <PointPage
    nodeId={props.match.params.nodeId}
    pointId={props.match.params.pointId}
    defaultSourceId={(parse(props.location.search) as QueryParams).source}
    timezone={props.site.settings.timezone}
    notificationBanner={props.notificationBanner}
  />
);
```

the way this is currently used by the parent component is as follows

```tsx
import { RoutedPointPage, RouteParams as PointPageRouteParams } from "./RoutedPointPage";

export interface Props extends RouteComponentProps<{}> {
  site: Site;
  notificationBanner?: React.ReactNode;
}

export class RoutedMainPage extends React.PureComponent<Props> {
  private createUrlForPoint = (
    nodeId: string,
    pointId: string,
    source?: string,
  ) =>
    PointPageRouteParams.templateUrl(
      this.props.match.url,
      { nodeId, pointId },
      { source },
    );

  // decodeRouteParams is a utility method that I wrote to wrap a `Route.render` handler to do URL decoding.
  private renderPointPage = decodeRouteParams(
    (routeProps: RouteComponentProps<PointPageRouteParams>) => (
      <RoutedPointPage {...routeProps} site={this.props.site} notificationBanner={this.props.notificationBanner} />
    ),
    { nodeId: true, pointId: true },
  );

  render() {
    return (
      <Switch>
        <Route
          // escapeRoutePath is another utility method that's used to allow parentheses and other special characters
          // in the path template as literals rather than changing the matching rules.
          path={PointPageRouteParams.getPathTemplate(escapeRoutePath(this.props.match.url))}
          render={this.renderPointPage}
        />
        {/* other routes here that deep link with createUrlForPoint  */}
      </Switch>
    );
  }
}
```

The parent has to do a bunch of stuff in this model: is has to know that it should encode/decode things, it has to juggle a bunch of type definitions and provide a wrapper function to forward other props.

Ideally, I could wrap all that noise up in the file that defines it rather than dump it on the parent components:

```tsx
export interface RouteParams {
  /* as before */
}

const RouteParams = /* as before */;

export interface QueryParams {
  /* as before */
}

export interface Props {
  baseUrl: string;
  site: Site;
  notificationBanner?: React.ReactNode;
}

export const RoutedPointPage = (props: Props) => (
  <Route
    path={RouteParams.getPathTemplate(escapeRoutePath(baseUrl))}
    render={decodeRouteParams(
      routeProps  => (
        <PointPage
          nodeId={routeProps.match.params.nodeId}
          pointId={routeProps.match.params.pointId}
          defaultSourceId={(parse(routeProps.location.search) as QueryParams).source}
          timezone={props.site.settings.timezone}
          notificationBanner={props.notificationBanner}
        />
      ),
      { nodeId: true, pointId: true },
    )}
  />
);
```

then the parent could just do

```tsx
export class RoutedMainPage extends React.PureComponent<Props> {
  // This function is still necessary to wrap, because this parent component 
  // is responsible for choosing the URL mount point for the PointPage and
  // needs to provide a way for other pages to deep link to the right place.
  private createUrlForPoint = (
    nodeId: string,
    pointId: string,
    source?: string,
  ) =>
    PointPageRouteParams.templateUrl(
      this.props.match.url,
      { nodeId, pointId },
      { source },
    );

  render() {
    return (
      <Switch>
        <RoutedPointPage
          baseUrl={this.props.match.url}
          site={this.props.site}
          notificationBanner={this.props.notificationBanner}
        />
        {/* other routes here that deep link with createUrlForPoint */}
      </Switch>
    );
  }
}
```

which I hope you'll agree is a lot cleaner!

But I'm sure as you're aware, Switch [digs around in children's props](https://github.com/ReactTraining/react-router/blob/e81dfa2d01937969ee3f9b1f33c9ddd319f9e091/packages/react-router/modules/Switch.js#L31), which means this thing has to duck-type like a Route.

~~I did play around with a HOC that would make that duck-typed thing, but I didn't like it much and it was messy. I can try to clean it up and provide it here if it would be helpful.~~ The HOC was actually wrong and fundamentally flawed. Because Switch accesses `props` directly, `path` must be present on the props, i.e., the parent _must_ provide it. No amount of wrapping the component changes what the parent is providing to the component it renders. I guess I could inject things onto `this.props` in the constructor or use a proxy/getter, but those are pretty awful. Maybe instead of a HOC it would just be a function you call that returns a Route? So it'd be _like_ a functional component, but cannot actually be used as one.

**Comment by timdorr** [comment]
This has been requested or asked about in many forms before. The crux of the argument against it is: when do you stop looking through the tree? Route's can be placed anywhere in the tree, and if they happened to be under a Switch they would behave differently with no explanation for why that is the case.

Beyond just being a giant technical problem (how do we track all the Routes and communicate between them, especially in Concurrent Mode?), there are a ton of logical gotchas to work through. It's really only solvable with a very complex architecture and tons of new APIs. That's not something we want to do with the library, so we're going to leave the behavior as-is.
