### ISSUE TITLE
Generic scroll restoration

### ISSUE THREAD

**Issue by nhooyr** [ReactTraining/react-router#7046]
The current docs at https://github.com/ReactTraining/react-router/blob/e81dfa2d01937969ee3f9b1f33c9ddd319f9e091/packages/react-router-dom/docs/guides/scroll-restoration.md#scroll-to-top

recommend the following:

```js
function ScrollToTop() {
  const { pathname } = useLocation();

  useEffect(() => {
    window.scrollTo(0, 0);
  }, [pathname]);

  return null;
}
```

The problem with this is described in the docs:

It does not restore scroll positions of the window and overflow elements on "back" and "forward" clicks. On every pathname change, it will scroll to the top which includes the back and forward transitions. If instead the component in the docs was the following, things would work as expected:

```js
function useScrollMemory() {
  const history = useHistory()
  useEffect(() => {
    if (history.action == "PUSH" || history.action == "REPLACE") {
      window.scrollTo(0, 0)
    }
  })
}

function ScrollMemory() {
  useScrollMemory()
  return null
}
```

This ensures that we only scroll up if the history was pushed to. This does not include back or forward navigations. Back navigations cause the action to become POP and forward navigations do not affect the action.

I think it'd also be wise to make this default behaviour but allow passing a prop to the router disable since the vast majority of apps would prefer this behaviour.

Previous discussion at https://github.com/ReactTraining/react-router/issues/3950#issuecomment-281181809

cc @ryanflorence

**Comment by nhooyr** [comment]
Whoops that's obviously incorrect and only worked in my specific example as useEffect was only being called on page transitions.

**Comment by nhooyr** [comment]
Fixed:

```js
function useScrollMemory() {
  const history = useHistory()
  useEffect(() => {
    if (history.action !== "POP") {
      window.scrollTo(0, 0)
    }
  }, [history.location.key])
}

function ScrollMemory() {
  useScrollMemory()
  return null
}
```

That should work in general.

**Comment by timdorr** [comment]
Can you resubmit as a PR? That's generally the best form for this sort of thing.

**Comment by nhooyr** [comment]
Wanted to discuss and get approval first. Does it look good to you?

**Comment by timdorr** [comment]
Discussing over actual code is better. We can comment on individual lines that way.
