### ISSUE TITLE
conflict between react router and react-transition-group documentation and examples.

### ISSUE THREAD

**Issue by laurencefass** [ReactTraining/react-router#7048]
## Version

5.1.2

## Test Case
Example from your website.
https://codesandbox.io/s/react-router-animated-transitions-07rue?from-embed

## Steps to reproduce
Comparing your example against official advice given by React-transition-group for use with React Router. The two examples dont appear compatible as RTG specifically advises AGAINST using switch statements but you are using <switch> in your demonstration of the package. Your example doesnt work correctly for nested animated routes.

http://reactcommunity.org/react-transition-group/with-react-router

## Expected Behavior

React Router and React-Transition-Group should reference the same examples.

## Actual Behavior

I cant set up animated sub-routes using your example and I dont know which example is correct.

**Comment by timdorr** [comment]
Either example is a valid approach. We don't need to choose just one. You can either use children functions or pass location into a Switch to achieve the same result.
