### ISSUE TITLE
Prompt's with same messages on different pages

### ISSUE THREAD

**Issue by ShamansCoding** [ReactTraining/react-router#7050]
## Version

v.5.1.2

## Steps to reproduce
I have two pages with a Prompt component on both of them. Both pages have the same messages pass as properties to Prompt.

Page 1:
```
   <Prompt
 	when={blockLeavePage}
 	message="Do you want leave the page? All unsaved changes will be lost!"
   />
```

Page 2:
```
   <Prompt
     when={blockLeavePage}
     message="Do you want leave the page? All unsaved changes will be lost!"
   />
```

Both of those pages have cross-links to each other.

## Expected Behavior

Prompt will work even with the same messages on different pages.

## Actual Behavior
Then I navigate to the page with Prompt on it with the same message as the page from which i came, the Prompt doesn't work anymore.

I fount the pease of code in the Prompt  component, which responsible for such behavior:
```
 return (
	 <Lifecycle
	   onMount={self => {
	     self.release = method(message);
	   }}
	   onUpdate={(self, prevProps) => {
	     if (prevProps.message !== message) {
	 	self.release();
	 	self.release = method(message);
	     }
	   }}
	   onUnmount={self => {
	     self.release();
	   }}
	 message={message}
	 />
 );
```
prevProps.message !== message - is the problem.

Is this line has any special meaning or some special case? I definitely would like to have the same messages on all the pages of my editor part of the app.

**Comment by timdorr** [comment]
I'm not 100% sure why that line is there, but I believe it's to stop an infinite loop.

The easiest way to workaround this is to put a `key={location.key}` prop on your Prompt so that the component is reinstantiated each time and doesn't have any previous props.

**Comment by ShamansCoding** [comment]
> I'm not 100% sure why that line is there, but I believe it's to stop an infinite loop.
> 
> The easiest way to workaround this is to put a `key={location.key}` prop on your Prompt so that the component is reinstantiated each time and doesn't have any previous props.

This solution didn't work.
