### ISSUE TITLE
The react training site is not reachable from North Macedonia

### ISSUE THREAD

**Issue by Shizuri** [ReactTraining/react-router#7053]
## Problem

I am unable to access the React Router website from the country of North Macedonia. The problem seams to be specifically with the [Telekom](https://www.telekom.mk/company-profile.nspx) ISP. I can access the site from a different provider in the country [A1](https://www.a1.mk/za-nas/za-a1-makedonija) and from online proxy services. It seams that the Cloudflare Always Online service for the region is hosted in Bulgaria and there have been some problems with that before #6835. 

## Steps to reproduce
Visit [https://reacttraining.com/react-router/](https://reacttraining.com/react-router/)
## Expected Behavior
For the site to open without a problem.
## Actual Behavior
Error 522
![image](https://user-images.githubusercontent.com/43163607/69807832-93eaa480-11e6-11ea-8334-58fe93772d42.png)

I have contacted the Telekom ISP and they have replied that the site is not being blocked by their service.

Thank you for your time and I apologize if I have made a mistake in this post, it's my first GitHub issue report.

**Comment by mozinator** [comment]
I have the same issue in Bulgaria

**Comment by Shizuri** [comment]
As of today, I can access the site again. I would like to know if it was an issues with the site or my ISP but it's not a necessity. Closing the issue.
