### ISSUE TITLE
How to change route with react-router-dom <Link> with out call url and not request to server

### ISSUE THREAD

**Issue by ebrahimiaval** [ReactTraining/react-router#7054]
I use react-route-dom in React SSR (server side rendering) project. when i click on Links i want change route but not request to server (not request in SPA mode - request only in direct call)

i think we can use event.preventDefault() to stop default action of but i don't know how do it with Link.

[question in stackoverflow](https://stackoverflow.com/questions/59092946/how-to-change-route-with-react-router-dom-link-with-out-call-url-and-not-reque)

**Comment by timdorr** [comment]
That is what Link will do for you. You must put it underneath a Router for it to work.

**Comment by ebrahimiaval** [comment]
it's not my question solution. tell me, how can i do it with react-router or react-router-dom. i think this package can not support it.

**Comment by timdorr** [comment]
React Router supports SSR. I'm not sure what you're asking, because your original question isn't clear. Do you have example code to look at?
