### ISSUE TITLE
No longer working with dynamic-cdn-webpack-plugin

### ISSUE THREAD

**Issue by SamMorrowDrums** [ReactTraining/react-router#7055]
I'm having issues when using with https://github.com/mastilver/dynamic-cdn-webpack-plugin. For some reason it seems to be loading the UMD version from the CDN, but it must be loading the ES version too.

## Version

"react-router-dom": "^5.1.2",

## Steps to reproduce

Build app with webpack and `dynamic-cdn-webpack-plugin` (which worked with previous 4.x version I used), but then using the latest version I am getting errors. I have ensured I'm only importing with `import {} from 'react-router-dom';` syntax, but when using the CDN tool it doesn't work.

## Expected Behavior

Loading should work with the CDN plugin and without. It does work perfectly without it.

## Actual Behavior

Get the warning about two versions, and then redux connected router fails to work.  Even passing the exclude parameter, this fails to work. Maybe my setup is just to complex, and I have wondered if the new context is getting broken with loading in this way, bit it's really hard to debug.

packages:

    "@hot-loader/react-dom": "^16.11.0",
    "@sentry/browser": "^5.9.1",
    "babel-polyfill": "^6.26.0",
    "bootstrap": "^4.3.1",
    "chalk": "^2.4.1",
    "chart.js": "^2.7.2",
    "classnames": "^2.2.6",
    "compression": "^1.7.2",
    "connected-react-router": "^6.6.1",
    "draft-js": "^0.10.5",
    "draft-js-export-html": "^1.2.0",
    "draft-js-import-html": "^1.2.1",
    "express": "^4.16.3",
    "fontfaceobserver": "^2.0.13",
    "history": "^4.7.2",
    "immutable": "^3.8.2",
    "immutable-props": "1.1.0",
    "install": "^0.12.1",
    "intersection-observer": "^0.5.1",
    "ip": "^1.1.5",
    "jquery": "^3.4.0",
    "local-storage-fallback": "^4.0.2",
    "lodash": "^4.17.15",
    "minimist": "^1.2.0",
    "moment": "^2.22.2",
    "moment-business-days": "^1.0.6",
    "moment-range": "^4.0.1",
    "moment-timezone": "^0.5.13",
    "morgan": "^1.9.1",
    "mustache": "^3.0.0",
    "mustache-express": "^1.2.5",
    "node-sass": "^4.13.0",
    "npm": "^6.13.1",
    "path": "^0.12.7",
    "popper.js": "^1.14.3",
    "postcss-jsx": "^0.34.0",
    "postcss-styled": "^0.34.0",
    "prop-types": "^15.6.2",
    "querystring": "^0.2.0",
    "rc-slider": "^8.6.1",
    "react": "^16.11.0",
    "react-async-script": "^1.1.0",
    "react-autocomplete": "^1.8.1",
    "react-collapse": "^4.0.3",
    "react-datepicker": "^2.9.6",
    "react-day-picker": "^7.4.0",
    "react-dom": "^16.11.0",
    "react-dropzone": "^6.2.4",
    "react-element-to-jsx-string": "^14.0.1",
    "react-height": "^3.0.0",
    "react-hot-loader": "^4.12.18",
    "react-inlinesvg": "^0.8.1",
    "react-loader": "^2.4.5",
    "react-motion": "^0.5.2",
    "react-popper": "^1.3.6",
    "react-pure-render": "^1.0.2",
    "react-rating": "^1.4.0",
    "react-redux": "^7.1.3",
    "react-redux-toastr": "^7.6.3",
    "react-router-dom": "^5.1.2",
    "react-select": "^2.0.0",
    "react-spinners": "^0.6.1",
    "react-timeout": "^1.1.2",
    "reactstrap": "^8.0.1",
    "reduce-reducers": "^0.4.3",
    "redux": "^4.0.4",
    "redux-immutable": "^4.0.0",
    "redux-rollbar-middleware": "^0.1.0",
    "redux-saga": "^1.1.1",
    "request": "^2.88.0",
    "reselect": "^4.0.0",
    "rollbar-browser": "^1.9.5",
    "sanitize.css": "^7.0.3",
    "styled-components": "^4.4.0",
    "superagent": "^4.0.0-beta.5",
    "superagent-retry": "^0.6.0",
    "uuid": "^3.3.2",
    "webpack": "^4.41.2",
    "webpack-dev-middleware": "^3.7.2",
    "webpack-hot-middleware": "^2.25.0",
    "whatwg-fetch": "^3.0.0"

**Comment by timdorr** [comment]
This doesn't have anything to do with React Router.
