### ISSUE TITLE
Typed url without '/' will fall into path='/' case

### ISSUE THREAD

**Issue by PengfeiWeng** [ReactTraining/react-router#7056]
Hi,

I wanna report an interesting thing about React-Route.
I notice if the user types www.whatever.com/baselink in the browser's address bar, it will actually trigger the path='/' case in Switch.

That is to say, www.whatever.com/baselink acts exactly as www.whatever.com/baselink/ (notice the / at the end).

Is it by design for some reason? 

Thanks,

Pengfei

**Comment by gpltaylor** [comment]
I'm not an expert here but I think this is a side affect of using path-to-regexp.
Here "/" and "" creates the same regex and therefore both match in React Router.

https://github.com/pillarjs/path-to-regexp

**Comment by timdorr** [comment]
Yes, we ignore the trailing slash by design.
