### ISSUE TITLE
React Router nesting reloads page

### ISSUE THREAD

**Issue by m-pd** [ReactTraining/react-router#7057]
This is a copy of my SO question - https://stackoverflow.com/questions/59136493/react-router-nesting-reloads-page

------------------------------------------------------------------------------------------

I'm trying to set up nested routes in React using React Router so that the nested components load directly, however the page reloads when I attempt to go to a nested route.

~~Even the official example does the same - https://reacttraining.com/react-router/web/example/nesting~~

One thing I noticed was that if I actually change the route from within one of the child route components the page *does not reload*. But this is bad practice and I want to change the route in the component that defines the routes.

Has something changed recently? How can I achieve nested routes changes without page reload?

**Parent**

    import { BrowserRouter as Router, Route, Switch } from "react-router-dom";

    // At route /home
    const Parent = (props: RouteComponentProps<any>) => {
      const changeRoute = () => {
        props.history.push('/home/test'); // Reloads page
      };
    
      return (
        <Router>
          <Switch>
            <Route component={Test} path="/home/test" />
            <Route component={Default} />
          </Switch>
          <button onClick={changeRoute}>Click</button>
        </Router>
      );
    };
    
    export default withRouter(Parent);

**Child**

    const Default = (props: RouteComponentProps<any>) => {
      const changeRoute = () => {
        props.history.push('/home/test'); // Does not reload page
      };
    
      return (
        <button onClick={changeRoute}>Click</button>
      );
    };
    
    export default withRouter(Default);

I'm using react-router-dom v5.1.2.

**Comment by gpltaylor** [comment]
> Even the official example does the same - https://reacttraining.com/react-router/web/example/nesting

Note that the page is only refreshing in the designer. if you view the sample using "open in new window" this is working as expected.

**Comment by m-pd** [comment]
@gpltaylor Thanks. Can you see anything in my example code that could be wrong?

**Comment by m-pd** [comment]
The problem was that I was using <Router> in Parent even though Parent was itself within <Router> tags. Replacing <Router> with <div> in Parent fixed the issue.
