### ISSUE TITLE
Custom history is not stable depending on Router import

### ISSUE THREAD

**Issue by tar-aldev** [ReactTraining/react-router#7058]
## Version

"react-router-dom": "^5.1.2"

## Test Case

https://codesandbox.io/s/react-router-gh6n7

## Steps to reproduce
I found that there is an ability to create custom history object using createBrowserHistory();
My code is as follows:
```
import { Router } from "react-router-dom";
import { createBrowserHistory } from "history";

export const history = createBrowserHistory();

ReactDOM.render(
  <Provider store={store}>
    <Router history={history}>
      <App />
    </Router>
  </Provider>,
  document.getElementById("root")
);
```
I then use history in some places.

## Expected Behavior
BrowserRouter history prop should work correctly.
## Actual Behavior
If I ` import { Router } from "react-router-dom";` everything is working as expected then.
However if I `import { BrowserRouter as Router } from "react-router-dom";` I have a bug:
For first load, the url path does not match the component that should be rendered.
E.g. url is "login", but the component being rendered is not LoginComponent.
Am I missing something?

**Comment by pshrmn** [comment]
The BrowserRouter is just a wrapper around the Router that creates a browser history insurance for you. If you are creating to own history instance, you need to stick with the Router.
