### ISSUE TITLE
Route's path as regexp - fail proptypes validation

### ISSUE THREAD

**Issue by brunoscopelliti** [ReactTraining/react-router#7063]
## Version

5.1.2

## Test Case

I've use a regexp to set the `path` of a Route.

```
<Route path={/\/(?!login)/} render={() => <Header />} />
```

## Actual Behavior

The code works as expected, and the `<Header />` component is rendered everywhere, but in the login route; anyway I got this warning:

```
Warning: Failed prop type: Invalid prop `path` supplied to `Route`.
    in Route (created by AppRoot)
    in AppRoot
```

It seems due to Route's propTypes.
Accordingly to its propTypes, Route's path should be a string, or an array of string. Any reason why it should not allow regexp (given that it seems to support it).

**Comment by timdorr** [comment]
We cache based in the string value, so a regex would break that. Also, we use the path-to-regexp library, so that would be redundant anyways.
