### ISSUE TITLE
Use a modal with subroutes.

### ISSUE THREAD

**Issue by andrzey** [ReactTraining/react-router#7064]
On the website there is an [example](https://reacttraining.com/react-router/web/example/modal-gallery) showing how to render two different screens at the same url, depending if it should be opened as a modal or not. The code that works lik a charm for that purpose is pasted below:

```
  let background = location.state && location.state.background;

  return (
    <div>
      <Switch location={background || location}>
        <Route exact path="/" children={<Home />} />
        <Route path="/gallery" children={<Gallery />} />
        <Route path="/img/:id" children={<ImageView />} />
      </Switch>

      {/* Show the modal when a background page is set */}
      {background && <Route path="/img/:id" children={<Modal />} />}
    </div>
```

However I have a set of subroutes that needs to be opened as a modal from another subroute. Something like this:

```
  let background = location.state && location.state.background;

  return (
    <div>
      <Switch location={background || location}>
        {/* One component exports one set of routes */}
        <Switch>
          <Route exact path="/" children={<Home />} />
          <Route path="/gallery" children={<Gallery />} />
        </Switch>
        
        {/* Another component exports another set of routes*/}
        <div>
          <Switch>
            <Route path="/img/:id" children={<ImageView />} />
          </Switch>
          
          {/* Show the modal when a background page is set */}
          {background && <Route path="/img/:id" children={<Modal />} />}
        </div>
      </Switch>
    </div>
  );
```

So when I'm in `Gallery` I want to open up `ImageView` as a modal, but I'm having difficulties understanding if I need to restructure my code or if there is a solution I havent thought of yet. Do anyone have an idea that could point me in a right direction?

**Comment by MeiKatz** [comment]
Also this is not a support page, the short answer goes like this: put another `<Route />` with `path="*"` inside the first inner `<Switch />`, and inside of this you put the routes from another component.
