### ISSUE TITLE
Proposed modal solution wont render modal in case of query parameters

### ISSUE THREAD

**Issue by rgbskills** [ReactTraining/react-router#7066]
Hello,

If you use the Modal solution proposed here: https://reacttraining.com/react-router/web/example/modal-gallery and pass query params to the modal route, then the modal will not render unless you refresh the page.

Repo with issue (2 pages where page 1 contains a link to a modal):
https://github.com/rgbskills/react-router-modal-query-param-issue

**Comment by timdorr** [comment]
You need to put the query string in the `search` property of the location you're linking to: 
```jsx
      <Link
        to={{
          pathname: `/modal`,
          search: '?id=12'
```
