### ISSUE TITLE
replace use state with moment.js fail

### ISSUE THREAD

**Issue by shaodahong** [ReactTraining/react-router#7069]
## Version

**5.1.2**

## Test Case

https://codesandbox.io/s/react-router-itbzo

## Steps to reproduce

1. open devtool console
2. trigger click button
3. console log

```bash
Uncaught DOMException: Failed to execute 'replaceState' on 'History': function (number) {
            var b = number % 10,
                output = (toInt(number % 100 / 10) === 1) ...<omitted>... } could not be cloned.
```

## Expected Behavior
replace success

## Actual Behavior
replace fail

**Comment by timdorr** [comment]
You can't put functions on state. You need to convert that to a serializable value. Preferably a string or Date.
