### ISSUE TITLE
useRouteMatch doesn't work with MemoryRouter

### ISSUE THREAD

**Issue by amiramix** [ReactTraining/react-router#7070]
## Version

5.1.2

## Test Case

https://jsfiddle.net/amiramix/duhq50c1/

## Steps to reproduce

Observe the initial route, or click any of the routes (in the jsfiddle).
When a new route is pushed to the history the little box titled Route shows the current route and values returned from `useRouteMatch`.

## Expected Behavior

The values returned from `useRouteMatch` are the same as values used by the `Route` component. If `Route` rendered a component for route `/r1` the same path should be returned from `useRouteMatch`.

This expectation steams from the description of this function in the documentation:
[useRouteMatch](https://reacttraining.com/react-router/core/api/Hooks/useroutematch)

In particular:

> The useRouteMatch hook attempts to match the current URL in the same way that a `<Route>` would.

## Actual Behavior

Values returned from `useRouteMatch` are always `/`

**Comment by timdorr** [comment]
Nothing is triggering your App component to re-render, so that hook isn't getting re-run. `useRouteMatch` does not subscribe to the history, so it will be the same value when the Routes inside are rendered.

**Comment by amiramix** [comment]
Of course the component re-renders, just click one of the links as stated in the defect description. Here is an updated fiddle:
https://jsfiddle.net/amiramix/duhq50c1/23/
