### ISSUE TITLE
Redirect does not work with Route together?

### ISSUE THREAD

**Issue by RonnieRen** [ReactTraining/react-router#7071]
## Version
here is the libraries' version
 "react": "^16.12.0",
    "react-dom": "^16.12.0",
    "react-router": "^5.1.2",
    "react-router-dom": "^5.1.2",
    "react-scripts": "3.3.0",
    "typescript": "~3.7.2"

## Steps to reproduce

here is the code I used:
<Switch>
   <Redirect to={'/inbox'}/>,
   <Route path={'/inbox'} component={Inbox}/>
</Switch>

## Expected Behavior
Inbox component is render-ed correctly
## Actual Behavior
Inbox is not loaded.

if I change the order of both Redirect and Route in the array like this: 
<Switch>
   <Route path={'/inbox'} component={Inbox}/>,
   <Redirect to={'/inbox'}/>
</Switch>
it works as expected.

**Comment by timdorr** [comment]
Your Redirect has no `from` prop, so it's matching all paths and is basically sitting in a loop. You should probably put that at the end anyways, if not using a `from` prop.
