### ISSUE TITLE
What is the equivalent API in react-router like 'navigate' in reach-router

### ISSUE THREAD

**Issue by chloesun** [ReactTraining/react-router#7072]
Coming from `reach-router` and I want to refactor with `react-router`, and I use `navigate` a lot from reach-router: https://reach.tech/router/api/navigate, something like this:

```
import { navigate } from "@reach/router"

const Invoices = () => (
  <div>
    <NewInvoiceForm
      onSubmit={async event => {
        const newInvoice = await createInvoice(
          event.target
        )
        navigate(`/invoices/${newInvoice.id}`)
      }}
    />
  </div>
)

```

What is the equivalent API in react-router?

Thank you!

**Comment by timdorr** [comment]
history.push, which you can get from [the useHistory hook](https://reacttraining.com/react-router/web/api/Hooks/usehistory) or as props on a Route component
