### ISSUE TITLE
useRouteMatch doesn't work with MemoryRouter

### ISSUE THREAD

**Issue by amiramix** [ReactTraining/react-router#7074]
## Version

5.1.2

## Test Case

https://jsfiddle.net/amiramix/duhq50c1/

## Steps to reproduce

Observe the initial route, or click any of the routes (in the jsfiddle).
When a new route is pushed to the history the little box titled Route shows the current route and values returned from `useRouteMatch`.

## Expected Behavior

The values returned from `useRouteMatch` are the same as values used by the `Route` component. That should include both scenarios - the initial render and any further render. If `Route` rendered a component for route `/r1` the same path should be returned from `useRouteMatch`.

This expectation steams from the description of this function in the documentation:
[useRouteMatch](https://reacttraining.com/react-router/core/api/Hooks/useroutematch)

In particular:

> The useRouteMatch hook attempts to match the current URL in the same way that a `<Route>` would.

## Actual Behavior

Values returned from `useRouteMatch` are always `/`

**Comment by pshrmn** [comment]
You're using `useRouteMatch` at the root level, so it inherits the default match. If you use `useRouteMatch` inside of a component rendered by a `Route`, you will see the expected values.

https://codesandbox.io/s/optimistic-banzai-dimlb
