### ISSUE TITLE
No Match 404 route render on all routes: react-router-dom

### ISSUE THREAD

**Issue by narendrasinghrathore** [ReactTraining/react-router#7076]
Using same example from [react-router-dom](https://reacttraining.com/react-router/web/example/no-match).
Just refactoring the route part ( i.e. Separation of  `<Route />`  in a component and passing as children in between `<Switch>` ).

![github router error](https://user-images.githubusercontent.com/4208015/71321839-67743080-24e5-11ea-9e18-c4a828fd23e6.gif)

**No Match 404 should be rendered if specified route doesn't match, it is working.**

_But it's still rendering with all matching routes._

````
import React from "react";
import {
  BrowserRouter as Router,
  Route,
  Link,
  Switch,
  Redirect,
  useLocation
} from "react-router-dom";

// You can use the last <Route> in a <Switch> as a kind of
// "fallback" route, to catch 404 errors.
//
// There are a few useful things to note about this example:
//
// - A <Switch> renders the first child <Route> that matches
// - A <Redirect> may be used to redirect old URLs to new ones
// - A <Route path="*> always matches

export function RouterNavigation() {
  return (
    <>
      <Route exact path="/">
        <Home />
      </Route>
      <Route path="/old-match">
        <Redirect to="/will-match" />
      </Route>
      <Route path="/will-match">
        <WillMatch />
      </Route>
      <Route path="*">
        <NoMatch />
      </Route>
    </>
  );
}

export default function NoMatchExample() {
  return (
    <Router>
      <div>
        <ul>
          <li>
            <Link to="/">Home</Link>
          </li>
          <li>
            <Link to="/old-match">Old Match, to be redirected</Link>
          </li>
          <li>
            <Link to="/will-match">Will Match</Link>
          </li>
          <li>
            <Link to="/will-not-match">Will Not Match</Link>
          </li>
          <li>
            <Link to="/also/will/not/match">Also Will Not Match</Link>
          </li>
        </ul>

        <Switch>
          <RouterNavigation />
        </Switch>
      </div>
    </Router>
  );
}

function Home() {
  return <h3>Home</h3>;
}

function WillMatch() {
  return <h3>Matched!</h3>;
}

function NoMatch() {
  let location = useLocation();

  return (
    <div>
      <h3>
        No match for <code>{location.pathname}</code>
      </h3>
    </div>
  );
}

````
## Version
"react": "^16.12.0",
"react-dom": "^16.12.0",
"react-redux": "^7.1.3",
"react-router-dom": "^5.1.2",

## Test Case

https://codesandbox.io/embed/react-router-no-match-404-8eiv9?fontsize=14&hidenavigation=1&theme=dark

**Comment by MeiKatz** [comment]
You have to wrap your routes inside of a `<Switch />` component. Then only the first route that matches will be rendered.

**Comment by narendrasinghrathore** [comment]
@MeiKatz , is that not same ?

````
export function RouterNavigation() {
  return (
    <>
      <Route exact path="/">
        <Home />
      </Route>
      <Route path="/old-match">
        <Redirect to="/will-match" />
      </Route>
      <Route path="/will-match">
        <WillMatch />
      </Route>
      <Route path="*">
        <NoMatch />
      </Route>
    </>
  );
}


<Switch>
   <RouterNavigation />
</Switch>
````

**Comment by MeiKatz** [comment]
@narendrasinghrathore no, all `<Route />` components must be direct anchenstors of the `<Switch />` component. In your example there is a `<Fragment />` component in between.

**Comment by narendrasinghrathore** [comment]
Instead of using Switch in separate component , if used in same component it works which is weird.



````
export function RouterNavigation() {
  return (
    <Switch>
      <Route exact path="/">
        <Home />
      </Route>
      <Route path="/old-match">
        <Redirect to="/will-match" />
      </Route>
      <Route path="/will-match">
        <WillMatch />
      </Route>
      <Route path="*">
        <NoMatch />
      </Route>
   </Switch>
  );
}

export default function App() {
return (
 <RouterNavigation />
);
}
````

> @narendrasinghrathore no, all `<Route />` components must be direct anchenstors of the `<Switch />` component. In your example there is a `<Fragment />` component in between.


As per documentation in [reactjs](https://reactjs.org/docs/fragments.html) 
> A common pattern in React is for a component to return multiple elements. Fragments let you group a list of children without adding extra nodes to the DOM.


Is that is the real issue or i am missing something?

Regards

**Comment by MeiKatz** [comment]
It is not weird at all: `<Fragment />` components are not rendered to the DOM, but they are React components like the others. Therefore your first solution will not work.

**Comment by narendrasinghrathore** [comment]
As routing do work 
1) Route match - Component shown with  No match route
2) Route not matched No match component shown.
But wrapping them with Fragment can produce unexpected behaviour, that something is strange.

Closing my issue and replacing Fragment with Switch as direct parent make it working as expected.

Thanks

**Comment by MeiKatz** [comment]
@narendrasinghrathore you're welcome
