### ISSUE TITLE
Page reload should go to current route instead  of "/"

### ISSUE THREAD

**Issue by saiteja2145** [ReactTraining/react-router#7079]
Assume I am in "/dashboard" route and if I refresh the page request will go to the server and server redirect to "/" and I am moving "/" route instead of "/dashboard" 
Can anyone help me in resolving this issue?

**Comment by MeiKatz** [comment]
When the server sends a response with a status code of 301 or 302 and it redirects to `/`, then this of course lets React Router only match a route with a path like `/` and not like `/dashboard`. React Router is not responsible for the way your server handles routes, at least not when you don't use React Router on the server side.
