### ISSUE TITLE
Website crashes with malformed URLs

### ISSUE THREAD

**Issue by pladaria** [ReactTraining/react-router#7083]
## Version

v5.1.2

## Test Case

https://codesandbox.io/s/react-router-ytq4i
see line 12

## Steps to reproduce

1. Goto https://reacttraining.com/react-router/web/example/basic
2. Edit sandbox preview URL, navigate to `/%`

## Expected Behavior

React Router could be resilient to malformed URLs

## Actual Behavior

Website crashes

**Comment by timdorr** [comment]
This was fixed in ReactTraining/history#656, but wasn't released in any version yet. You can track this via ReactTraining/history#745 for now.
