### ISSUE TITLE
index.js: 1437 Warning: Please use `require("react-router-dom").withRouter

### ISSUE THREAD

**Issue by yosvani** [ReactTraining/react-router#7084]
You cannot use this statement
 import {withRouter} from "react-router-dom/withRouter";

 because it gives this error

index.js:1437 Warning: Please use `require("react-router-dom").withRouter` instead of `require("react-router-dom/withRouter")`. Support for the latter will be removed in the next major release

**Comment by pshrmn** [comment]
We are getting rid of releasing a package with multiple modules in favor of a single package. This means that everything will have to be imported from `react-router-dom`; you can no longer cherry pick imports from a nested module. Right now, we have helper modules that allow you to use the cherry picking syntax, but with warnings that this is going away.

```js
import { withRouter } from 'react-router-dom';
```
