### ISSUE TITLE
UseLocation value of location.state cannot be updated, original value persists refresh

### ISSUE THREAD

**Issue by Seanmclem** [ReactTraining/react-router#7085]
## Version

react-router-dom 5.1.2

## Steps to reproduce
Using a Link component to set a location.state
```
               <Link key={art._id} to={{
                   pathname: `/my/path/here`,
                   state: {myObject: value},
               }}>
                   link title
               </Link>
```
I use useLocation to get the location.state value in my Link'd component. I don't want this value to persist a refresh. However, it does. I update the value to undefined after I use it, but it reverts to the old value. There should be some way, any way to update it and have it persist. It seems like a valid use-case

## Expected Behavior
useLocation should allow you to set the value of location.state and the new value should persist just as if it were set some other way. Example `location.state = undefined` should persist a refresh. Or anything. `location.updateState(undefined)`, or `location.clearState()`

## Actual Behavior
Persists all the time until replaced in a way exactly like it was set.

**Comment by timdorr** [comment]
You change `location.state` by changing location, either with history or a Link. Once the location has been changed, then you should use something else to update global state. That's not what `location.state` is used for.
