### ISSUE TITLE
<AndroidBackButton /> is not working anymore after upgrading to react-router-native v5

### ISSUE THREAD

**Issue by XianAquino** [ReactTraining/react-router#7086]
I'm trying to update to react-router-native to v5.1.2. I'm getting this error `TypeError: Cannot read property 'Consumer' of undefined` when I use `<AndroidBackButton />`.

**Comment by timdorr** [comment]
You have a different version of `react-router` in your project somewhere. You can use `npm ls react-router` to find it and upgrade it to the same version as react-router-native.
