### ISSUE TITLE
5.1.2 can't get data in localStorage

### ISSUE THREAD

**Issue by avillarubia** [ReactTraining/react-router#7087]
Good day,
## Version

**react-router-dom 5.1.2
react 16.12.0.**

## Steps to reproduce
using react-router-dom 4.2.1 the localStorage.get('key') works well
but in the current version won't

## Expected Behavior
localStorage.get('key') should return output

---------
Hoping that I am not bothering you guys.
Thank you

**Comment by timdorr** [comment]
We don't touch localStorage, so something else must be going on. 

Also, it's `localStorage.getItem`, not `.get`. That might be your issue.

**Comment by avillarubia** [comment]
@timdorr sorry about that is a typo only, on my code is **getItem**
