### ISSUE TITLE
`cannot update during an existing state transition` warning when using `push` with downshift's useSelect

### ISSUE THREAD

**Issue by TLadd** [ReactTraining/react-router#7090]
## Version

react-router-dom 5.1.2

## Test Case

https://codesandbox.io/s/hopeful-currying-hvx2p

## Steps to reproduce

In the above codesandbox, use the `Toggle` button and select one of the other pages.

## Expected Behavior

No `cannot update during an existing state transition` warning appears

## Actual Behavior

`cannot update during an existing state transition` warning appears in the console.

Not sure this is necessarily a problem with react-router. Came here after filing [an issue in downshift](https://github.com/downshift-js/downshift/issues/874) for the same thing. It's oddly specific and I think has to do with the combination of downshift's [useEnhancedReducer](https://github.com/downshift-js/downshift/blob/master/src/hooks/utils.js#L85) and how react-router syncs the location between history and react-router-dom's component state. I also created [another codesandbox](https://codesandbox.io/s/charming-goldwasser-s20rz) that used neither downshift nor react-router and results in the same warning (happens on the second button click for some reason). Hoping y'all may have encountered integration issues like this before and may know what's going on.

**Comment by timdorr** [comment]
I'm thinking this is more an issue on downshift's side than ours. We do have a global object (`window.history`) that can update during a render, but there's no way around that. If that's being fired during a render, that's not really our fault. Internally, our usages of `history.push` are all done safely and within React's state transitions (at least until CM drops).

In the meantime, you can force it to sync with the render cycle by pushing the imperative navigation to a declarative state update:
```js
  const { push } = useHistory();
  const [selected, setSelected] = useState()
  const items = ["/about", "/users", "/"];
  const {
    getToggleButtonProps,
    isOpen,
    getMenuProps,
    getItemProps
  } = useSelect({
    onSelectedItemChange: changes => {
      setSelected(changes.selectedItem);
    },
    items
  });

  useEffect(() => {
    if (selected) push(selected)
  }, [selected, push])
```

**Comment by TLadd** [comment]
Thanks for looking into this and the workaround. So `onSelectedItemChange` gets called within a `useReducer` inside downshift's `useEnhancedReducer`, which I think might technically be a part of `render`? My hunch is that is the culprit, but unsure. I expect you're right that it isn't anything related to react-router. Thanks again.
