### ISSUE TITLE
Error when trying to install React Router

### ISSUE THREAD

**Issue by Mireia17** [ReactTraining/react-router#7095]
This is the error I am getting after trying to install React Router and start to run the program in the local host. 

Failed to compile.

/Users/mireia.palmero/Desktop/node_modules/react/index.js
Module not found: Can't resolve './cjs/react.development.js' in '/Users/mireia.palmero/Desktop/node_modules/react'

Could you help me please?

I searched the issue in different forums and tried many things but nothing seems to be working.

**Comment by timdorr** [comment]
This doesn't have anything to do with React Router.
