### ISSUE TITLE
[Docs] withRouter being imported from react-router instead of react-router-dom

### ISSUE THREAD

**Issue by davinakano** [ReactTraining/react-router#7096]
Hi there 👋 

First of all, I just wanted to say thank you very much for everyone's work on react-router! It is great, really!

By following the website's documentation, it seems that `react-router-dom` is the preferred (possibly only) package to be installed in order to use React Router. Also, all pages from the docs that I have came across so far get their imports from that package.

However, when I checked the `withRouter` API documentation, it imports from `react-router` instead. After checking this repository, it seems that the page was [re-exported from core](https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/docs/api/withRouter.md).

I am not sure if it would be correct to change the core documentation import from `react-router` to `react-router-dom` but I will open a PR anyway just in case.

I am really sorry if this issue is not in the format as I thought it wasn't a bug or a support question. Since I am still a beginner in all things open source, any input in how I can improve the issue writing skill is highly appreciated!

Cheers and keep on rocking! 🍻 💯 🚀

**Comment by timdorr** [comment]
It doesn't really matter, as the exports from react-router-dom are just re-exports from react-router. withRouter is also not DOM-specific, so we want the docs to be more broadly applicable for native users.
