### ISSUE TITLE
react-router-native:  How to go to the previous route from current route?

### ISSUE THREAD

**Issue by Yandamuri** [ReactTraining/react-router#7098]
By using `histoy.entries` we can see all the routes that have been traversed. But I would like to go to the previous route from current route. I didn't find any way like `history.previous` or such a declarative thing.

Can anybody let me know how to achieve this?

**Comment by MeiKatz** [comment]
`history.back()`

**Comment by Yandamuri** [comment]
@MeiKatz Thank you. Is possible to know the previous route before going it. I would like to go back based on condition if it is some specific route.

**Comment by MeiKatz** [comment]
You could create your own history by listening to changes of the path:
```js
history.listen((location) => ...);
```
