### ISSUE TITLE
useLocation search value is empty

### ISSUE THREAD

**Issue by ARKKYN** [ReactTraining/react-router#7099]
## Version

5.1xx

## Steps to reproduce
```
 <Link to={`/app/instances/draft/${row.ID}?clone=true`}>
```
When I use link tag like above and on the target page, if I use `useLocation()` Hook it gives following 
<img width="623" alt="Screenshot 2020-01-09 at 2 58 04 PM" src="https://user-images.githubusercontent.com/10711160/72062253-6cb2e700-32fd-11ea-8a5b-c58407af9a1a.png">

if I use  link tag like below
```
 const temp = `/app/instances/draft/${row.ID}?clone=true`; 
 <Link to={temp}>

```
it gives this output
<img width="729" alt="Screenshot 2020-01-09 at 2 59 00 PM" src="https://user-images.githubusercontent.com/10711160/72062413-c74c4300-32fd-11ea-8807-9978a7d39543.png">

the 'search' value in the location object is empty

**Comment by timdorr** [comment]
I can't reproduce this. If you can provide a Codesandbox that reproduces this, we can look into it. But this points to being something else outside of React Router.

**Comment by indigane** [comment]
We ran into this same issue. Version `5.1.2`.

I don't have a reproducible sandbox, but in case it helps anyone, the workaround for us was to change

```jsx
<Link
  to={`/path/to/resource/${id}?foo=bar`}
/>
```

to

```jsx
<Link
  to={{
    pathname: `/path/to/resource/${id}`,
    search: '?foo=bar'
  }}
/>
```
