### ISSUE TITLE
Check the render method of `App` ERROR

### ISSUE THREAD

**Issue by videmout** [ReactTraining/react-router#7102]
How may i render it ?

Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `App`.

Here is app code: >>

import React, {Component} from "react";
import ReactDOM from "react-dom";
import '@fortawesome/fontawesome-free/css/all.min.css';
import "bootstrap-css-only/css/bootstrap.min.css";
import "mdbreact/dist/css/mdb.css";
import { MDBContainer, MDBRow, MDBCol } from "mdbreact";
import "./index.css";
class App extends Component {
    constructor(props){
        super(props);
        this.state = {
            events: [
        {time: '10:00',title: 'New assigment'},
        {time: '12:20',title: 'Create issues'}

    ],
        title: 'MMMNS',
        time: '13 : 99'
    
    }
    }
    myLoopFunction (){
    var myArray = [];
    var i;
    for (i = 0; i < this.state.events.length; i++) {
      myArray[i] = (
        <Event
          time={this.state.events[i].time}
          title={this.state.events[i].title}
        />
      );
    }
    return myArray;
  }

    render() {
      return (
        <React.Fragment>
          <MDBContainer lg="6" >
          <h3>{this.state.title}-{this.state.time} </h3>
          <button onClick={() => {
                this.setState({title:'New title name'});
                this.setState({time: '12:00'});
                console.log(this.state.title);
                console.log(this.state.time);
            }
        }
        
            >Change</button>

          <h3> {this.myLoopFunction()} </h3>

            </MDBContainer>
          </React.Fragment>

      );
    }
   
}

ReactDOM.render(<App/>, document.getElementById("root"));

class Event extends Component {
    render() {
      return (
        <React.Fragment>
          <h3>
            {this.props.time} - {this.props.title}
          </h3>
        </React.Fragment>
      );
    }
  }

**Comment by timdorr** [comment]
This has nothing to do with React Router.
