### ISSUE TITLE
Docs - Examples break when localStorage is unavailable

### ISSUE THREAD

**Issue by B-Reif** [ReactTraining/react-router#7110]
On the docs page, the example content breaks and renders nothing when localStorage cannot be reached.

## Version
N/A
## Test Case
N/A

## Steps to reproduce
1) Block third-party cookies.
- Using Chrome: go to chrome://settings/content/cookies and enable **Block third-party cookies**.
- Or use Brave which does this by default.
2) Navigate to any **example** page in the docs, such as the [basic Web example](https://reacttraining.com/react-router/web/example/basic).

## Expected Behavior
I expect the example content to be rendered. If the page truly requires access to third-party cookies in order to work, I expect a helpful error message to be rendered.

## Actual Behavior
The example content is completely blank. The example is not rendered. No error message is rendered.

![image](https://user-images.githubusercontent.com/12357846/72939727-4a1fc580-3d22-11ea-9ce0-f87e12387e63.png)

**Comment by B-Reif** [comment]
We could fix this by implementing an error boundary around the SandboxExample component. That way, any error thrown by the third-party CodeSandbox components could be caught and rendered.

**Comment by timdorr** [comment]
This is really a CodeSandbox issue. I believe they know about it.

**Comment by timdorr** [comment]
BTW, here you go: https://github.com/codesandbox/codesandbox-client/issues/2877
