### ISSUE TITLE
Extending goBack, adding canGoBack, regressions in v4

### ISSUE THREAD

**Issue by AlexReff** [ReactTraining/react-router#7112]
https://github.com/ReactTraining/react-router/issues/408

This issue should be re-opened and addressed. When searching online for how to accomplish a 'can I go back' concept with react-router, this is the only link discussing it going back 5+ years, ending with supposed feature regression.

My current goal is to be able to provide a 'history back' link that can optionally navigate to a URL if the 'go back' action did not change the route. Or, determine if there is any history in our app to 'go back' to.

The only working suggestion I've seen so far is to use a different library.

**Comment by timdorr** [comment]
You can pull out history with `useHistory()` and then run `history.goBack()`. It's part of its API: https://github.com/ReactTraining/history/blob/master/docs/Navigation.md

**Comment by AlexReff** [comment]
That's not what I'm looking for. I know I can call goBack. The issue is with detecting whether or not goBack has anything to go back to, or if calling goBack worked. I don't know of a good way to accomplish this. goBack still does not return a boolean value.

**Comment by timdorr** [comment]
The main difference in 4.0 and onward is there is no longer the concept of "the route", or a singular matching route for a URL. Routes can be anywhere in the tree and multiple ones can match at the same time. So, there is no singular state of "I am at this route". 

It's a declarative approach that matches React better. It may not match your use case anymore, but it still matches the majority and is drastically simpler to implement. I'm sorry if that doesn't work for you, but it's the decision we made a few years ago and are sticking to it.

**Comment by AlexReff** [comment]
That's fine if that was the decision made, I just didn't see any explanation in that thread or elsewhere about it. That's totally understandable for Routes, but it doesn't seem quite applicable to 'history' which is still a singular concept. There are not multiple 'histories' on a single page, just the history, as far as I understand it. Is there a problem with adding back the boolean return type on goBack? That seems like it would give developers useful information, unless there are complications to adding it.
