### ISSUE TITLE
procedurally Generated List of Link or NavLink Components Does Not Render on Firefox

### ISSUE THREAD

**Issue by frastlin** [ReactTraining/react-router#7114]
### Version

react-router-dom v5.1.2

### Test Case

https://stackblitz.com/edit/react-dom-bug

### Steps to reproduce

1. Open:
https://react-dom-bug.stackblitz.io/home
in both Chrome and Firefox.
2. Observe that in Chrome, there are links and in Firefox there are no links.

### Expected Behavior

In both Firefox and Chrome there should be links.

### Actual Behavior

In Firefox there are no links when there should be.

### Comments

For some reason, a dynamic list of procedurally generated Links or NavLinks are not showing up on Firefox.
I am attempting to build a dynamic sidebar that only shows the pages that the user can access. I have done this by iterating through the list of allowed pages and wrapping the accessible pages in a NavLink element. In the render function, I then insert this list of NavLinks.
On Chrome, I am able to see the links just fine. On Firefox Version 72.0.2 (64-bit), the links do not show up at all.
I have tried the following:

1.	Replace NavLink with Link, but the same problem happens.
2.	Wrap each NavLink into a <li> element and the list into a ul tag, but the bullets show up without any links on Firefox.
3.	If I have Link or NavLink tags that are not procedurally generated, they show up just fine.

**Comment by MeiKatz** [comment]
Actually, I tried it in Chrome 79 and in Firefox 72, and the behaviour was in both case the same: the links are there – buth they have no label and therefore are not visible to you. The reason for this is clear:
```jsx
getSidebar(pages){
  return(
    pages.map(page=>(
      <NavLink key={page.props.path} to={page.props.path}>{page.sidebarTitle}</NavLink>
    ))
  )
}
```
For the `key` and `to` prop you are accessing the props via `page.props`, for the label you miss the `props` part. If you add it in your problem should be fixed.

**Comment by frastlin** [comment]
Wow, thank you, silly bug!
Why does it render correctly on Chrome? It should not show up in either place.

**Comment by MeiKatz** [comment]
@frastlin As I pointed out, (for me) it neither did render correctly on Chrome nor on Firefox.
