### ISSUE TITLE
History has undefined state

### ISSUE THREAD

**Issue by kynrai** [ReactTraining/react-router#7119]
## Version

^5.1.2

## Test Case

https://codesandbox.io/s/competent-thunder-ddx49

## Steps to reproduce

Line 8 of App.tsx where location state has the typescript definition of PoormansUnknwon stops the code from compiling or ever having location state

## Expected Behavior

Location state should have correct typescript definitions

## Actual Behavior

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/history/index.d.ts#L55

This stops code compiling and holding correct state

**Comment by timdorr** [comment]
We don't maintain the types. You should consult the support resources for DefinitelyTyped.
