### ISSUE TITLE
Why did you stop the ability to pass history in?

### ISSUE THREAD

**Issue by DominicTobias-b1** [ReactTraining/react-router#7123]
Hi, since v5 you guys have removed the ability to pass a custom history object into the browser router. This was essential for interfacing with things like Apollo links (https://www.apollographql.com/docs/link/links/error/) as a centralized place to handle errors (e.g. given an invalid JWT token message redirect to /login).

Is there an alternative? Context and hooks are not a replacement of this functionality since since they only work in components.

Thanks, and I did post this on SO but seems too specific for non-authors to answer. https://stackoverflow.com/questions/60052418/programmatic-access-to-history-history-push-etc-in-react-router-v5-outside-of

**Comment by MeiKatz** [comment]
Not sure, what you are talking about, nur you can pass a custom history object at all (see react-router/Router).

**Comment by DominicTobias-b1** [comment]
In v4 you could do this:

```js
import { Route } from 'react-router-dom';
import { createBrowserHistory } from 'history';

const history = createBrowserHistory();

<Router history={history}>
   <App />
</Router>
```

This is a method used by 1000s of apps to redirect users to login pages when tokens have expired or some other error from the server in a centralized place OUTSIDE of react components. For example in an apollo link error handler - https://www.apollographql.com/docs/link/links/error/

You used to be able to do `history.push('/path')` with the instance of history you passed in.

**Comment by MeiKatz** [comment]
Als I told you before: you can so this also in v5. There was no change.

**Comment by DominicTobias-b1** [comment]
I think I got confused as I was previously using `Router` from the dom package. This time I'm using `BrowserRouter` for Node SSR which doesn't have the ability to have a history prop unfortunately

**Comment by MeiKatz** [comment]
BrowserRouter, like HashRouter and StaticRouter, are shortcuts for Router + the related history object.

**Comment by DominicTobias-b1** [comment]
Ah ok, perhaps it's the types which are incorrect then

![Screenshot 2020-02-04 at 5 59 51 PM](https://user-images.githubusercontent.com/58683337/73734190-32abf800-4778-11ea-91f9-e7cfe7451e37.png)

**Comment by MeiKatz** [comment]
There ist no `history` prop ..
