### ISSUE TITLE
[Migration Guide] Suggest upgrading history to 5@next

### ISSUE THREAD

**Issue by kysley** [ReactTraining/react-router#7127]
## Version

Upgrading from `v5` -> `v6-alpha.1`

## Test Case

Working example with `history@next (5.0.0-beta.4)`[1]
https://codesandbox.io/s/zen-bas-9yy9h

Breaking example with `history@4.10.1`[2]
https://codesandbox.io/s/zen-elgamal-1ug1y

## Steps to reproduce
Navigating around on example [1] works as expected. Navigating around on example [2] throws `Cannot read property 'pathname' of undefined`

I ran into this error in a Greenfield project we are testing this alpha on. In hindsight, upgrading `history` along with `react-router` and `react-router-dom` makes sense, but it wasn't our first guess.

**Comment by Hotell** [comment]
this should be resolved with [alpha 1](https://github.com/ReactTraining/react-router/releases/tag/v6.0.0-alpha.1)
