### ISSUE TITLE
[Feature Request] Config based Routes component

### ISSUE THREAD

**Issue by otakustay** [ReactTraining/react-router#7131]
I see `6.0` provides `useRoutes` which resolves a configuration into route element, and `<Routes>` components is using it internally.

I believe hooks should be a logic reuse part in react, not a element reuse solution, so why not provide a `<ConfiguredRoutes>` like:

```
<ConfiguredRoutes routes={...} baseName="" caseSentive={fasle} />
```

This JSX syntax is more readable than `useRoutes` call and could be more easily to nest in component structure.

**Comment by timdorr** [comment]
This is exactly what Routes is, just with children instead of a routes prop. We don't need to add this.

**Comment by otakustay** [comment]
@timdorr Sorry to continue this after closed, but this is NOT exactly the same, we need a config based component because a configuration can be traversed and manipulated by program, for example we can find all leaf routes and wrap their `element` prop with a `TrackPageView` parent, this cannot be archived via children based component since we don't have control with how `Routes` traverse and use its children
