### ISSUE TITLE
<NavLink /> active state behavior changed in v6

### ISSUE THREAD

**Issue by smmoosavi** [ReactTraining/react-router#7134]
## Version

=> Found "react-router@6.0.0-alpha.1"
=> Found "react-router-dom@6.0.0-alpha.1"

## Test Case

v6
https://codesandbox.io/s/react-router-716hw

v5
https://codesandbox.io/s/react-router-i4kkx

## Steps to reproduce

Click on the topic link and then click on components topic link

## Expected Behavior
`<NavLink to="/topics" />` has active state in `/topics/components` same as v5

## Actual Behavior
in version 6:
`<NavLink to="/topics" />` has inactive state in `/topics/components`

**Comment by yousefelgoharyx** [comment]
I think a good fix for this is this
```js
export function useMatch(to, exact = false) {
  let location = useLocation();
  let resolvedLocation = useResolvedLocation(to);
  // TODO: Try to match search + hash as well
  // return location.pathname === resolvedLocation.pathname;
      return exact ? location.pathname.startsWith(resolvedLocation.pathname)
                   : location.pathname === resolvedLocation.pathname;
}
```

idk if it will work for all the use cases since I haven't put too much thought into it but the must-work solution is the code from v5 repo which did this exact job

**Comment by nevir** [comment]
The [docs for `NavLink`](https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/docs/api/NavLink.md#exact-bool) seem to imply that the v5 behavior is correct and that this is a bug

**Comment by gerbyzation** [comment]
@yousefelgoharyx good suggestion, although I think you have the expressions in the ternary operator swapped around

**Comment by eDubrovsky** [comment]
I have the same error. 
@yousefelgoharyx thanks for the solution. 

Some news about a fix it in v6?

**Comment by emiledesad** [comment]
Hello all.
Thanks for your work.

I had the same question.
So +1 to this ticket.

Regards.

**Comment by timdorr** [comment]
We just need an `exact` prop like before.

**Comment by gopeter** [comment]
https://github.com/ReactTraining/react-router/releases/tag/v6.0.0-alpha.5 introduced and `end` prop. Now we can build the same `activeClass` behavior as before :)

**Comment by smmoosavi** [comment]
Thanx, I think the migration guide needs to be updated.

**Comment by hnryjms** [comment]
The behavior in v6 still isn't quite a match to earlier versions when using `end={true}` ... Specifically, it's no longer checking `search` params when comparing URLs.

I'm feeling like `end` should be replaced with a more consistent `exact` parameter, that does a full match of the address instead of only on `pathname`, for anyone who needs search params to be part of the `isActive` check.

```
<NavLink
  to={{
    pathname: "/docs",
    search: `dueBefore={DateTime.local().toISODate()}`
  }}
>Overdue</NavLink>
```

https://github.com/remix-run/react-router/blob/main/packages/react-router-dom/index.tsx#L550
