### ISSUE TITLE
(v6) Best practices navigating in a thunk/saga

### ISSUE THREAD

**Issue by JoseExposito** [ReactTraining/react-router#7135]
Hi,

I'm migrating my React/Redux app to React Router v6.

The migration guide encourages to use `useNavigate` instead of accesing the `history` object directly.

My understanding is that I could do something like this to be able to access the `navigate` function from my thunks:

Client side entry point:
```
<BrowserRouter>
  <App />
</BrowserRouter>
```

App.jsx:
```
const App = () => {
  const navigate = useNavigate();
  
  return (
    <ReduxProvider store={configureStore(navigate)}>
      // ...
    </ReduxProvider>
  );
}
```

However, I'm not sure if using the `navigate` function in a thunk or saga could cause conflicts with the `useTransition` React Router v6 uses under the hood or mess up with concurrent mode.

Could anyone provide some guidance about the recommended way for this use case?

**Comment by Andersonfrfilho** [comment]
I'm also having the same doubt, and I'm also seeing the option to migrate to the react-router. Would there be any way to perform a service so that we can browse any page after running processes in sagas?

**Comment by salvoravida** [comment]
@JoseExposito 
you should try https://github.com/salvoravida/redux-first-history/releases/tag/v4.6.0-beta.1
