### ISSUE TITLE
Route path not working in production

### ISSUE THREAD

**Issue by suresh777** [ReactTraining/react-router#7138]
I am using react router for routing. I have two react pages in my application, I deployed in IIS server. In production i am not able to navigate to specific path. I am getting 403 forbidden access.

Code:

```
<Router basename="/bucket/">
        <div>
        </div>
          <Switch>
              <Route path="/" exact  component={ConfigurationExplorer}/>
              <Route path="/sample" exact  component={Sample}/>
          </Switch>
    </Router>
if i try http://example.com/bucket/sample, i am getting 403
```

**Comment by timdorr** [comment]
This has nothing to do with React Router. Check your setup for IIS.
