### ISSUE TITLE
[react-router-dom + TypeScript] RouteComponentProps changing state type

### ISSUE THREAD

**Issue by antoinerousseau** [ReactTraining/react-router#7139]
## Version

react-router-dom 5.1.2
@types/react-router-dom 5.1.3

## Test Case

https://codesandbox.io/s/react-router-dom-state-bug-1s753 (see `Home.tsx`)

## Expected Behavior

The state for the current route could have a different shape than the one for the route we want to go to

## Actual Behavior

Shares state type between `history.push` & `history.replace`

**Comment by antoinerousseau** [comment]
I realize this might be more of a typings issue, and that the types are hosted separately at DefinitelyTyped.
I opened an issue there: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/42274
Feel free to close this issue if it's not relevant here.

**Comment by timdorr** [comment]
Yeah, we haven't converted to TS yet. But that's coming in 6.0.
