### ISSUE TITLE
Redirect `props.from` propType should support array

### ISSUE THREAD

**Issue by acaua** [ReactTraining/react-router#7140]
## Version

5.1.2

Since the <Redirect> `from` prop is "Any valid URL path that path-to-regexp@^1.7.0 understands." (per the docs, here: https://reacttraining.com/react-router/web/api/Redirect/from-string )

I believe it could also be an array, besides a string, since Route `props.path` can be both. (here: https://github.com/ReactTraining/react-router/blob/master/packages/react-router/modules/Route.js#L93 )

But probably not a regExp, per https://github.com/ReactTraining/react-router/pull/6165#issuecomment-430040284

I'm using an array and it is working but it gives me this warning:
```
Warning: Failed prop type: Invalid prop `from` of type `array` supplied to `Redirect`, expected `string`.
    in Redirect (created by bound StaticSectionTemplate)
    in bound StaticSectionTemplate (created by InnerLoadable)
    in InnerLoadable (created by Context.Consumer)
    in Unknown (created by ForwardRef)
    in ForwardRef (created by bound Content)
    in ErrorBoundary (created by bound Content)
    in bound Content (created by InnerLoadable)
    in InnerLoadable (created by Context.Consumer)
    in Unknown (created by ForwardRef)
    in ForwardRef (created by Context.Consumer)
    in Route (created by App)
    in ErrorBoundary (created by InnerLoadable)
    in InnerLoadable (created by Context.Consumer)
    in Unknown (created by ForwardRef)
    in ForwardRef (created by AbstractTemplate)
    in AbstractTemplate (created by InnerLoadable)
    in InnerLoadable (created by Context.Consumer)
    in Unknown (created by ForwardRef)
    in ForwardRef (created by App)
    in bound MostReadProvider (created by App)
    in App (created by Context.Consumer)
    in withRouter(App)
    in LastLocationProvider (created by Context.Consumer)
    in withRouter(LastLocationProvider)
    in Router (created by BrowserRouter)
    in BrowserRouter
```

**Comment by timdorr** [comment]
> Any valid URL path that path-to-regexp@^1.7.0 understands.

We mean that literally as "any valid _singular_ URL path", so we don't support an array for the `from` prop. If you need to support multiple paths, just use multiple `Redirect`s.
