### ISSUE TITLE
useRouteMatch doesn't return current path when omitting path parameter

### ISSUE THREAD

**Issue by daviddelusenet** [ReactTraining/react-router#7144]
## Version
`5.1.2`

## Expected Behavior
In issue #7004 @MeiKatz says the following:

"`useRouteMatch` can do two things:

- you can pass a path to it and it checks if it matches the current url.
- if you omit the `path` parameter it will use the closest `<Route />` match and will return it. Therefore this should be, what you are searching for."

## Actual Behavior
When you omit the `path` parameter you always get the same result. 

```
// console.log(useLocation());
{
    pathname: "/communication",
    search: "",
    hash: "",
    state: null,
    key: "8ipv88"
}

// console.log(useRouteMatch());
{
    path: "/",
    url: "/",
    params: {…},
    isExact: false
}
```

Another route:

```
// console.log(useLocation());
{
    pathname: "/club",
    search: "",
    hash: "",
    state: null,
    key: "i1by7d"
}

// console.log(useRouteMatch());
{
    path: "/",
    url: "/",
    params: {…},
    isExact: false
}
```

My problem is that if my `<Route />` `path` is `/club/:clubId` that the `pathname` returned by `useLocation` returns the actual `/club/actualClubId` instead of just `/club/:clubId`.

How can I get the current `path` when using a hook without needing the hardcode every instance in the `useRouteMatch` hook?

**Comment by timdorr** [comment]
Do you need the actual params? You can use the `useParams` hook for that.

**Comment by daviddelusenet** [comment]
No, I need the `path` where I'm on. So not the resolved `pathname` but the actual `path`, `/club/:clubId` for example.

**Comment by daviddelusenet** [comment]
@timdorr did you see my previous comment?

**Comment by snazzypants** [comment]
@daviddelusenet Did you ever manage to solve this? I also need to find the path from a component that is unaware of its parent (like your example `/club/:clubId` 

@timdorr Is there any way of doing this?

**Comment by daviddelusenet** [comment]
I didn't got it to work the way I was hoping for, I solved my problem with this function:

```tsx
export const getRouteText = (isOnMatchDetailsRoute: boolean): ReactNode => {
    let { pathname } = useLocation();
    const externalMatchId = useSelector(({ matchDetails }) => matchDetails.match.ExternalMatchId);
    const flattenedPrivateRoutes: (NestedPrivateRouteChild | PrivateRoute)[] = [];
    let value: keyof Translations = 'Error_404';
    const variables: LocalizedStringProps['variables'] = {};

    if (pathname.endsWith('/')) {
        pathname = pathname.slice(0, -1);
    }

    getPrivateRoutes().privateRoutes.forEach((privateRoute) => {
        flattenedPrivateRoutes.push(privateRoute);

        if (isNestedPrivateRoute(privateRoute)) {
            flattenedPrivateRoutes.push(...privateRoute.children);
        }
    });

    const activeRoute = flattenedPrivateRoutes.find((privateRoute) => privateRoute.path === pathname);

    if (activeRoute) {
        value = activeRoute.text;
    }

    if (isOnMatchDetailsRoute) {
        value = 'MatchDetails';
        variables.number = externalMatchId || '';
    }

    return <LocalizedString value={value} variables={variables} />;
};
```

So the 'important' part is the is the `if (isOnMatchDetailsRoute)` part. This is how I call the function above:

```tsx
const isOnMatchDetailsRoute = useRouteMatch<{
    publicMatchId: string;
}>(ROUTES.competitionAffairs.matchDetails);

getRouteText(Boolean(isOnMatchDetailsRoute))
```
