### ISSUE TITLE
Error in Safari and Chrome on IOS mobile or Mac. 

### ISSUE THREAD

**Issue by achavhantexada** [ReactTraining/react-router#7147]
## Version
react-router-dom 

## Steps to reproduce
Open any Brower Safari or Chrome on IOS or Mac. 
## Actual Behavior
`ERROR: The above error occurred in the &lt;Rr&gt; component:
 in Rr (created by RentalsList) 
in div (created by RentalsList) 
in RentalsList (created by inject-RentalsList-with-contractsStore-actions-commonStore) 
in inject-RentalsList-with-contractsStore-actions-commonStore (created by RentalsTabs) 
in div (created by RentalsTabs) 
in main (created by RentalsTabs)
 in div (created by RentalsTabs)
 in RentalsTabs (created by Context.Consumer)
 in Route (created by Dashboard) 
in Switch (created by Dashboard) 
in div (created by Dashboard) 
in Dashboard (created by inject-Dashboard-with-commonStore) 
in inject-Dashboard-with-commonStore (created by Context.Consumer) 
in Route (created by Routers) in Switch (created by Routers) 
in div (created by Layout) 
in Layout (created by Routers) 
in Router (created by Routers) 
in Routers (created by inject-Routers-with-actions-commonStore) 
in inject-Routers-with-actions-commonStore in ProviderConsider

 adding an error boundary to your tree to customize error handling behavior.Visit https://fb.me/react-error-boundaries to learn more about error boundaries.LOGError: TypeError: e.addEventListener is not a function. (In 'e.addEventListener("change",c)', 'e.addEventListener' is undefined)`

It is working on Android and other devices expect Apples. 
PS: I don't know exactly error is because of react-router`

![IMG_0048](https://user-images.githubusercontent.com/42725599/74598197-1f800e80-503b-11ea-82d2-d6fba0db66d7.PNG)

**Comment by timdorr** [comment]
This has nothing to do with React Router.

**Comment by achavhantexada** [comment]
Yeah sorry I figured it out, it was MediaQueryList, because  it is still using addListener in IOS and Mac browsers but in my code I am using AddEventListener to add the handler for change event.
