### ISSUE TITLE
performance fix : loading 200+ Route definition in the initialize.

### ISSUE THREAD

**Issue by cullsin** [ReactTraining/react-router#7149]
Hello, 

We have a enterprise single page application product where we have 200 Route definitions. So all these definitions need to be load on init and along with that, it carries over in this.props.children and becomes very heavy. Can you please suggest me how do I load only necessary route and then every route, I can load the related routes.

Thanks,
Raja K

**Comment by MeiKatz** [comment]
Why don't you use suspense and lazy loading?
