### ISSUE TITLE
In <Route/> matchPath and resolve params, why not using the api "match" of path-to-regexp lib

### ISSUE THREAD

**Issue by KelWenGek** [ReactTraining/react-router#7150]
in path-to-regexp, the logic of resolving params  underneath maybe is better for one param key of multiple value!  like the case of path "/foo/:bar+"
`if (key.modifier === "*" || key.modifier === "+") {
        params[key.name] = m[i].split(key.prefix + key.suffix).map(value => {
          return decode(value, key);
        });
      } else {
        params[key.name] = decode(m[i], key);
      }`

**Comment by timdorr** [comment]
I'm not understanding what you're saying, unfortunately. But you might be looking at a newer version of path-to-regexp, whereas RR 4/5 are pinned to path-to-regexp@1.x

**Comment by KelWenGek** [comment]
why not using path-to-regexp@6.x, there is an api named “match” which can parse the named parameter value into array. like “/foo/:bar+”, when the pathname is “/foo/1/2”, here we get the param of key name “bar” will be an array [‘1’,’2’], then this form of params is more useful!🤔

**Comment by KelWenGek** [comment]
Why not using path-to-regexp@6.x. There is an api named “match” which can parse the named parameter into an array! For example, the path of “/foo/:bar+”, when match the pathname of “/foo/1/2”, here we get param of key name “bar” will be an array [‘1’,’2’], in my opinion, this form of params will be more useful!

**Comment by timdorr** [comment]
https://github.com/ReactTraining/react-router/issues/6899#issuecomment-528858118
