### ISSUE TITLE
Update get started and migration links in release v6.0.0-alpha.0

### ISSUE THREAD

**Issue by iamandrewluca** [ReactTraining/react-router#7153]
In release [v6.0.0-alpha.0](https://github.com/ReactTraining/react-router/releases/tag/v6.0.0-alpha.0) there are some links references that were moved

* https://github.com/ReactTraining/react-router/blob/dev/docs/guides/getting-started.md
* https://github.com/ReactTraining/react-router/blob/dev/docs/guides/migrating-5-to-6.md

New links
* https://github.com/ReactTraining/react-router/blob/dev/docs/installation/getting-started.md
* https://github.com/ReactTraining/react-router/blob/dev/docs/advanced-guides/migrating-5-to-6.md

**Comment by timdorr** [comment]
Fixed them now. Thanks for the heads up!
