### ISSUE TITLE
Why do we need react-router when bumping react-router-dom: ^5.1.2 -> ^6.0.0-alpha.1

### ISSUE THREAD

**Issue by colesanderson** [ReactTraining/react-router#7155]
I just upgraded my project from `react-router-dom`: `^5.1.2` -> `^6.0.0-alpha.1`. There was no `react-router` in the project and I got error message that said its required to install `react-router`. Why is that? 

The error I am getting is:

```
./node_modules/react-router-dom/react-router-dom.js
Module not found: Can't resolve 'react-router' in `/path/to/project`
```

**Comment by timdorr** [comment]
react-router is now a peer dep. You must install it now. You would have been warned about this when installing the newer version of react-router-dom.
