### ISSUE TITLE
Has no updates when basename prop changed

### ISSUE THREAD

**Issue by apostololeg** [ReactTraining/react-router#7157]
## Version
 5.1.2

## Test Case
https://codesandbox.io/s/react-router-dom-dynamic-basename-lstx4

## Steps to reproduce
Click submenu link (now url is `/sp/sub`)
Click button "toggle basename"

## Expected Behavior
1) Browser address has changed to `/en/sub`
2) Links has change attribute `href` respectively current basename

## Actual Behavior
1) Browser address still `/sp/sub`
2) Links `href` are not changed

**Comment by timdorr** [comment]
Basename is only used for initial matching and is not expected to be updated past the initial render.
