### ISSUE TITLE
Possibility to add an RouteGuard in v5 or v6 ?

### ISSUE THREAD

**Issue by vertic4l** [ReactTraining/react-router#7158]
Hi,

i'd like to use @aws-amplify/auth and check the given Authentication before changing the route.
Otherwise redirect to a login route.

Is there any possibility?

In vue-router there is a `beforeEach` method to do this.
And even better with `react-router-config` to configure it nicely in one place?

**Comment by vertic4l** [comment]
Well, similiar to https://github.com/reach/router/pull/332

**Comment by timdorr** [comment]
We're not going to add this, but you're free to create your own version of this kind of thing.
