### ISSUE TITLE
[Feature request] No history forward/back hooks in v6

### ISSUE THREAD

**Issue by davidbailey00** [ReactTraining/react-router#7159]
## Version

6.0.0-alpha.1

## Description

In the v5 API, it's possible to navigate back and forward with the `useHistory` hook:

```js
function MyComponent() {
  const { goBack } = useHistory();
  return <button onClick={goBack}>Back</button>;
}
```

In v6, I can see that this is only possible with the `useNavigate` hook using numbers to indicate how many items to pop off the stack:

```js
function MyComponent() {
  const navigate = useNavigate();
  return <button onClick={() => navigate(-1)}>Back</button>;
}
```

Is this the recommended way to navigate back/foward in v6, or are there plans to add a more readable API similar to v5?

Note: I'm happy to submit a PR to implement something like this if it's deemed appropriate for the new API.

**Comment by timdorr** [comment]
It's now `back` and `forward`: https://github.com/ReactTraining/history/blob/dev/docs/navigation.md

**Comment by davidbailey00** [comment]
Thanks for the link, though it seems that the `history` property from `LocationContext` isn't directly exposed anywhere in the current v6 API as far as I can tell?

**Comment by davidbailey00** [comment]
The only place I can see the history API partially exposed is https://github.com/ReactTraining/react-router/blob/c240986/packages/react-router/index.js#L396, i.e. the `navigate(-1)` described in my original issue - are there plans to expose a back/forward function as well?

**Comment by davidbailey00** [comment]
@timdorr Would it be possible to reopen this per the comments above? Or is the recommended approach to use `navigate(±N)` via the `useNavigate` hook? (Or is there somewhere that `back` and `forward` are exposed from `LocationContext`'s `history` property that I've missed?)

**Comment by timdorr** [comment]
navigate(-1) and navigate (1) are wrappers around go(), which is exactly what the back/forward functions do in the history library. Router just wraps that into one API.

**Comment by davidbailey00** [comment]
@timdorr Thanks :slightly_smiling_face:  I understand that these both work functionally the same, though my other question concerns whether `useNavigate()` + `navigate(-1)` in Router v6 will be the recommended migration from `useHistory()` + `goBack()` in v5, or if there are plans for other APIs in v6 which use the words "back" and "forward", just for code readability purposes? Kinda like how in v5 at the moment there's `go(-1)` as well as `goBack()` which are both functionally the same.

If those are the recommended replacements I'm happy to write a PR for the migration guide, since I think this is something currently missing. I can also try a PR for a new `useHistory` hook that just exposes `go/back/forward` in order to make code more readable + make migration from v5 slightly easier, only if you think it's worth adding.

**Comment by timdorr** [comment]
AFAIK, Michael wants to keep it to just a single API. If you want to add some stuff to the migration guide for that, by all means submit a PR!
