### ISSUE TITLE
V6 conditionally navigating

### ISSUE THREAD

**Issue by jacobjuul** [ReactTraining/react-router#7162]
https://github.com/ReactTraining/react-router/issues/7156

I asked in this issue if `withRouter` is deprecated, to which the answer was yes. 

in V6 I am supposed to use `useNavigate` to programmatically navigate to a new route. 
However, I am unsure about what to do, when a component (that needs the `useNavigate` logic) sometimes renders outside of the context of react-router (since hooks can't be conditional).

**Comment by timdorr** [comment]
It's the same as previous versions: create a history instance and pass that as a prop to a Router. Make that instance available globally and you can use it anywhere in your code.
