### ISSUE TITLE
Error to install following documentation

### ISSUE THREAD

**Issue by HenriqueOmena** [ReactTraining/react-router#7174]
im trying follow [Documentation](https://github.com/ReactTraining/react-router/blob/dev/docs/installation/add-to-a-website.md#quick-install) and i receive error msg on installation.
Sound like not exist

## Version

**Version 6**

## Steps to reproduce
`npm install history@5 react-router@6 react-router-dom@6`

## Expected Behavior
Install the router

## Actual Behavior
```
 npm install history@5 react-router@6 react-router-dom@6
npm ERR! code ETARGET
npm ERR! notarget No matching version found for react-router-dom@6.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\henrique.omena\AppData\Roaming\npm-cache\_logs\2020-02-27T15_00_48_840Z-debug.log
```

**Comment by timdorr** [comment]
It's still in prerelease, so you need to install either that specific version or the `next` tag:
```
npm install history@next react-router@next react-router-dom@next
```
