### ISSUE TITLE
Passing in custom component causes full page refresh

### ISSUE THREAD

**Issue by alaboudi** [ReactTraining/react-router#7175]
## Version

5.1.2 (but I believe this should be present in current version too)

## Test Case

https://codesandbox.io/s/react-router-73em2

## Steps to reproduce
use the component prop
```
const MyLink = (props) => <a {...props}>{props.children}</a>
<Link component={MyLink} to="/" />
```
## Expected Behavior
It should not refresh the entire app

## Actual Behavior
It refreshes the entire app.

Reason: 
The main reason this refreshes the entire application is because the custom component replaces `LinkAnchor` in the library. `LinkAnchor` has some logic to prevent default behaviour. The behavior written [here](https://github.com/ReactTraining/react-router/blob/b77283cb75efc909c34e48c7cdcb7f50281f4055/packages/react-router-dom/modules/Link.js#L35)  should be extracted and done in the `Link` component.

I can volunteer to put up a PR and fix it.

**Comment by MeiKatz** [comment]
I strongly disagree because then it would be impossible for custom components to implement a different handling on click. Therefore your custom component should implement a similiar event handling If you want.

**Comment by timdorr** [comment]
Correct, this part is left up to you to implement. This enables your to create non-a Links. We cannot implement this for all component types, as we don't know the implications. 

As a counter example, your component may have it's a deeply nested in some styling divs/spans. Therefore, blindly applying the click handler at the top level won't actually do anything.

**Comment by alaboudi** [comment]
@MeiKatz why not just wrap around the user provided `onClick` logic?

@timdorr I can argue against the counter example. If a user has an <a> tag that is deeply nested in divs in their custom component, then the user should consider the top most <div> to  intrinsically be part of navigation component. Meaning, clicking the div should also navigate a user. You can argue that maybe the user doesn't want to top most div to be clickable. If that is the case, I'd argue that this hypothetical navigation component is inflated with layout concerns along with some navigation concerns.

Also I understand that we want to give the user liberty to design the components the way they want, but ironically the currently implementation is very controlling of the contract that that a custom navigation component should take up. I would have personally loved to have been able to use my component in and out of the react-router-dom context without having my component contract being dictated by a library.
