### ISSUE TITLE
React router affecting dependency tracking with useCallback/useEffect

### ISSUE THREAD

**Issue by gitonthescene** [ReactTraining/react-router#7177]
## Version

react-router-dom 5.1.2

## Test Case
https://github.com/gitonthescene/routerbug/tree/master/src

I tried to make this as small an example as possible, but I'm not sure how to reduce it to a test.

In my real world example, this issue with dependency tracking is causing an infinite loop since I'm updating the state in my useEffect call.  Without using the router there is no such infinite loop.

## Steps to reproduce
The demo above shows how using react router is affecting dependency tracking with useCallback.  You can set useRouter to either true or false and it should render the same component.  ( Some pains are taken to ensure you're using the router or not, but not a combo
of the two. )

Click on the button and observe the output in the console.

## Expected Behavior
I expected the output in the console to be the same whether using react router or not.

## Actual Behavior
When not using the router, updating the top level state does not change the updateState property passed to CompA because it's passed as a memoized value using useCallback.  Thus the dependency in useEffect is not triggered.

When using the router, updating the top level state somehow affects the memoized value created by useCallback thus triggering the dependency tracking of useEffect in compA and sending a second "here" to the console.

**Comment by gitonthescene** [comment]
This example is a little slimmer:

https://codesandbox.io/s/react-router-wbgsp

**Comment by gitonthescene** [comment]
I'm no expert, but after a little debugging it appears that changing the state when using the router triggers a "mountEffect" while without the router, it triggers an "updateEffect".  In updateEffectImpl there's a check that the hook inputs are equal, but there is no such check in mountEffectImpl.

Should the Route be remounted if the Switch is not changing?

**Comment by timdorr** [comment]
Your `route.main` is creating a new instance of the `component` prop on each render, so this is blowing away the state each time. You should use `children` instead of `component` at this issue will go away.

**Comment by gitonthescene** [comment]
Indeed, it does.  Thanks!
