### ISSUE TITLE
<Redirect /> is not working 

### ISSUE THREAD

**Issue by tejaswi-m** [ReactTraining/react-router#7178]
![Screenshot (39)](https://user-images.githubusercontent.com/53425249/75678230-2c476800-5cb3-11ea-9aff-830789452e9b.png)
![Screenshot (38)](https://user-images.githubusercontent.com/53425249/75678234-2e112b80-5cb3-11ea-8983-286c68a19e67.png)

It is entering into the function but not navigation to other components.

**Comment by MeiKatz** [comment]
`<Switch>` takes the first route or redirect that matches. So it will take your route for SpeechListForm and will not try your redirect.

**Comment by tejaswi-m** [comment]
@MeiKatz  I tried removing the switch. Or else it there anything should I modify?

**Comment by timdorr** [comment]
Also, please don't ignore and erase the issue template.
