### ISSUE TITLE
Redirect component not working (react router v6)

### ISSUE THREAD

**Issue by RodyGL** [ReactTraining/react-router#7185]
## Version

**6.0.0-alpha.2**

## Test Case

https://codesandbox.io/s/react-router-basic-y33tl

## Steps to reproduce

1. Add Routes component
2. Add Route's inside
3. Add Redirect at the end
4. Test any invalid route and see that Redirect is not working

## Expected Behavior
Redirect to the route specified on the "to" prop.

## Actual Behavior
Not redirecting

**Comment by MeiKatz** [comment]
You are missing the `from` prop of `<Redirect />`

**Comment by RodyGL** [comment]
Hi @MeiKatz, is that a requirement for v6? I never had to use `from` prop before v6

**Comment by MeiKatz** [comment]
Then this was a bug. It was always required.

**Comment by RodyGL** [comment]
omg hahaha, thanks @MeiKatz. Glad this is solved. This is working as expected. 👍
