### ISSUE TITLE
Prompt is rendering and causing warnings of history only supports one prompt

### ISSUE THREAD

**Issue by owen-stellar** [ReactTraining/react-router#7186]
## Version

5.1.2

## Test Case

https://codesandbox.io/s/react-router-he65g

## Steps to reproduce

The test case above isn't perfect as I tried to minimize what was needed to recreate. Here's the scenario:
I have a form that's in a modal. The form has multiple tabs, which cause a route change (each tab has a unique route). I have a Prompt in that component that checks to see if the form is dirty and hasn't been submitted and in order to keep the prompt from showing when browsing around in the tabs I use the function option on the message prop to provide logic to show the message only if the location is headed somewhere outside the form. This works well.
The challenge is that in some of the tabs there is the ability to add/edit items to a list. This adding happens in another modal, which itself has a Prompt in order to properly prompt the user if they leave the form. This prompt uses a simply when bool (if form is dirty and not submitted) but as soon as it becomes dirty AND if I've happened to make the top level form dirty as well I get a warning message that only one prompt is supported at a time. 
The app functions as expected, only prompting if I attempt the close the form. However the warning is concerning and I wouldn't want to roll to production with it happening. 

My provided test case doesn't show this exact scenario but instead shows a simplified version: 
- Click on about: No prompt is necessary due to function logic
- Click on topics (a sub route of about): The top level prompt still shouldn't show as we're still in the context of about url, the Topics prompt also shouldn't show as we're now in topics, however we immediately get the warning of two prompts. 
- Click on about: I get prompted properly about leaving topics.

## Expected Behavior
The bug, or my misunderstanding, lies in the fact that I have provided logic in my message prop that the prompt should not happen, thus I would expect that a warning shouldn't occur. I only have one active Prompt. I think it should not warn if the logic in my message function resolves to true and not an actual message. 
My expectations are based on the fact that when I use the when prop I am able to achieve using nested Prompts in the way I describe above, however I'm unable to get access to the location (like I am inside the function option in the message prop). This means a potential solution is providing location in a function option for the when prop. 
## Actual Behavior
The warning of multiple prompts happens even if multiple prompts don't resolve to "prompting" per the message function.

**Comment by timdorr** [comment]
You should be using the `when` prop to determine if the Prompt should be active or not.

**Comment by owen-stellar** [comment]
That's the problem. The when prop doesn't have a way to check what location someone is trying to browse to so there is no way to use the when prop successfully for my scenario.
