### ISSUE TITLE
v6 - " Failed prop type: Invalid prop `path` of type `array` supplied to `Route`, expected `string`"

### ISSUE THREAD

**Issue by schester44** [ReactTraining/react-router#7187]
Having trouble with finding documentation on the upgrade path from v5 to v6 when `<Route/>` `path` prop values are an array.

I'm getting the error

```
 Failed prop type: Invalid prop `path` of type `array` supplied to `Route`, expected `string`.
```

**Comment by timdorr** [comment]
You can't pass an array of paths to a Route anymore. You'll have to make separate routes instead.
