### ISSUE TITLE
Is `element` attr of `Route` accept string? (v6)

### ISSUE THREAD

**Issue by numb86** [ReactTraining/react-router#7188]
Passing string to `element` attr of `Route` gives an error by `prop-types`.

```javascript
// Warning: Failed prop type: Invalid prop `element` of type `string` supplied to `Route`, expected a single ReactElement.
<Route path="/" element="This is index page." />
```

But this is working for now.

The "fallback" attribute of "Suspense" receives the element likewise, allow string (and number, boolean, more).

I want to know the policy from now on of the "element" attr.
Allow only Narrowly defined `React Element`? Or Allow another value(e.g. string) too?

If allow another value too, I proposal fix specify of `prop-types`.
For example, use `PropTypes.node` instead of `PropTypes.element`.

**Comment by timdorr** [comment]
Yes, we need that to be an element because the Route component is simply a function that returns that. Returning a string from a component is not valid.

**Comment by numb86** [comment]
Thanks response.
But component can return other than element too from React v16.
https://reactjs.org/blog/2017/09/26/react-v16.0.html#new-render-return-types-fragments-and-strings

So I guess there is no problem returning something other than element from component. Why not allow it?

This is not proposal or objection, pure question. I am glad if you can answer.
