### ISSUE TITLE
export 'useHistory' was not found in 'react-router-dom'

### ISSUE THREAD

**Issue by DominikLevitsky** [ReactTraining/react-router#7189]
## Version
"react": "^16.8.6",
"react-router": "^6.0.0-alpha.2",
"react-router-dom": "^6.0.0-alpha.2"
## Steps to reproduce
Try to use history hook in a React function component:
`import { useHistory } from 'react-router-dom';`
...
`const history = useHistory();`
## Expected Behavior
History should work as expected.
## Actual Behavior
Getting the error:
`export 'useHistory' was not found in 'react-router-dom'`

**Comment by timdorr** [comment]
There is no `useHistory` hook in 6.0. Switch back to 5.1.2 or adjust your code to not use that hook.

**Comment by krunal90** [comment]
@timdorr I updated react-router-dom to 5.1.2 still i am getting error .../@types/react-router-dom has no exported member 'useHistory'

**Comment by hfabio** [comment]
I'm using react-router-dom 5.2.0 and got this error as well..
And when it imports i cant use its properties, like push
``` 
TypeError: Cannot read property 'push' of undefined
```

**Comment by sylwiasuwalska** [comment]
> I'm using react-router-dom 5.2.0 and got this error as well..
> And when it imports i cant use its properties, like push
> 
> ```
> TypeError: Cannot read property 'push' of undefined
> ```

Same here.

**Comment by akroll1** [comment]
same issue here.

**Comment by YannickLeRoux** [comment]
Just installed v5.2.0 to try the hook API and I got the same issue

**Comment by ekamanelly** [comment]
There is no useHistory hook in 6.0. Switch back to 5.1.2 or adjust your code to not use that hook @timdorr , if useHistory can't be found in react-router-dom, where can we find it? or should i use History package

**Comment by iamgollum** [comment]
same issue as @sylwiasuwalska using 5.2.0.

In my component library I have `useHistory` and when I import it within a component whose ancestor (parent up the tree) is a BrowserRouter, I get `TypeError: Cannot read property 'push' of undefined`

**Comment by Aujemd** [comment]
Same issue here :(

**Comment by mirismaili** [comment]
@timdorr 
I wanted to set a logger middleware using `history.listen(...)` (that logs any navigation). Is there an alternative in v6?

**Comment by patrickmcdougle-okta** [comment]
This happens when the versions of the @types are mismatched. Removing both from yarn.lock and running yarn install fixed the version mismatch for me.

**Comment by kascoding** [comment]
I use this in V6 and it works
import {useNavigate } from 'react-router-dom'

const navigate = useNavigate() // inside the function

 navigate(`/section/`)

**Comment by golani2112** [comment]
useNavigate thing is working fine

**Comment by ehsanpaknejad** [comment]
> I use this in V6 and it works import {useNavigate } from 'react-router-dom'
> 
> const navigate = useNavigate() // inside the function
> 
> navigate(`/section/`)

It solve my problem

**Comment by dot-neat** [comment]
In react-router-dom **V6**, you should **switch** from _useHistory_ to _useNavigate_. 

So in v5, you can have:
import { useHistory } from "react-router-dom";
let history = useHistory();
history.push("/home");
  
**But** in v6, you have to switch it to : 
import { useNavigate } from "react-router-dom";
let navigate = useNavigate();
navigate("/home");

**Comment by gami34** [comment]
in RRD v6, compared to the old RRD v5, there has been a change in name and some basic functionality.

if you had to install React-Router-Dom by doing either :

yarn add react-router-dom OR
np install react-router-dom

without specifying the version, you are likely using the recent RRD v6 as at this time of giving this comment.

import { useNavigate } from 'react-router-dom'
 kindly make us of useNavigate() instead

const navigate = useNavigate()
navigate("/address")

**Comment by KUSUM24** [comment]
In react-router-dom version 6,
useHistory => useNavigate

import { useNavigate } from "react-router-dom";
const navigate = useNavigate();
navigate("/categories");

**Comment by patelrohan750** [comment]
Quick solution:

To fix this error, you need to replace useHistory with the useNavigate hook. Because that will return a function that allows you to navigate programmatically. Example const navigate = useNavigate().

We get this error because the useHistory() hook has been replaced by the useNavigate() hook in react-router-dom v6. We need to change the useHistory hook to the useNavigate hook.

The useNavigate() hook returns a function that allows us to navigate between pages programmatically.
You can check my article on [export useHistory was not found in react-router-dom](https://reactjsguru.com/usehistory-was-not-found-in-react-router-dom/)
