### ISSUE TITLE
How I can create route, its use another components

### ISSUE THREAD

**Issue by kedcomsci** [ReactTraining/react-router#7190]
I want to create route

example:

/setting/profile > render component Profile

/setting/password > render component Password

**Comment by pshrmn** [comment]
You can nest routes. https://reacttraining.com/react-router/web/example/nesting

**Comment by kedcomsci** [comment]
> You can nest routes. https://reacttraining.com/react-router/web/example/nesting

I want to use this path "/setting/:setting"

and check path after setting
example: 

"/setting/profile" > render component profile
"/setting/password" > render component password

all path in setting not same component
