### ISSUE TITLE
How to disable anonymous urls hitting the application

### ISSUE THREAD

**Issue by dinukadesilva** [ReactTraining/react-router#7191]
Taking following as an exacmple.
https://reacttraining.com/react-router/web/example/basic

On it's browser, If I type
```https://bnpsd.csb.app/abcd/efgh/567```

I still see the menus and the application loaded. What really need is make it not going to the allocation. I know that can add not found page. But, instead what I need is to make it not going to the application. 

Is there anyway this can be done?

**Comment by dinukadesilva** [comment]
https://stackoverflow.com/questions/60663690/how-to-disable-anonymous-urls-hitting-the-application

**Comment by dinukadesilva** [comment]
@yuchi @timdorr 
Still I couldn't find an answer to this question. Is there anyway you could help here?

**Comment by yuchi** [comment]
As the bot said, please don’t use the issue tracker for questions ans support.
I will answer your question on Stackoverflow.

**Comment by yuchi** [comment]
By the way, why did you mention me?
