### ISSUE TITLE
Route nesting failed (v6) 

### ISSUE THREAD

**Issue by sessionboy** [ReactTraining/react-router#7192]
hi guy!. 
I am trying to use react-router v6.
I encountered a problem when using route nesting, the child routes were not rendered.
```js
<Route path="settings" element={<Setting />}>
  <Route path="account" element={<SettingAccount />} />
  <Route path="profile" element={<SettingProfile />} />
</Route> 
```
When access `/settings/account`, it renders `Setting`, but the child route `SettingAccount` does not appear.
I printed `props`, then children is null.
```js
// Setting component
export default props => {
  console.log(props.children); // null
  return (
    <div>
      { props.children }  // nothing 
    </div>
  )
}
```

version: 6.0.0-alpha.2

**Comment by sessionboy** [comment]
Now I know that rendering child routes requires the use of the Outlet component.
I still have a question, how to render the first child route by default.

**Comment by sessionboy** [comment]
Now I know that rendering child routes requires the use of the Outlet component.
I still have a question, how to render the first child route by default.

**Comment by timdorr** [comment]
Just make a Route with no path prop or one with an empty string.
