### ISSUE TITLE
Docs for BrowserRouter are incorrect

### ISSUE THREAD

**Issue by jjsmclaughlin** [ReactTraining/react-router#7197]
The docs give incorrect usage for the BrowserRouter tag. A self-closing tag as seen in the docs will have no effect. You need to wrap your BrowserRouter tag around all your Links and other routing tags for it to have an effect. See here:

https://reacttraining.com/react-router/web/api/BrowserRouter/basename-string

The example as given is wrong:

```
<BrowserRouter basename="/calendar" />
<Link to="/today"/> // renders <a href="/calendar/today">
```

This will not render href="/calendar/today" as stated. It will render href="/today".

The example should read:

```
<BrowserRouter basename="/calendar">
    <Link to="/today"/>
    <Link to="/tomorrow"/>
    ...
</BrowserRouter>
```

**Comment by pshrmn** [comment]
I think that the idea with that documentation is that the `Link` is a child somewhere or the `BrowserRouter`, but a PR to make this change would be appreciated.

**Comment by smkamranqadri** [comment]
I would like to take this issue.
