### ISSUE TITLE
Router path parameter casting undefined to string

### ISSUE THREAD

**Issue by totalolage** [ReactTraining/react-router#7207]
This bug is back: https://github.com/ReactTraining/react-router/issues/4138

## Version

```bash
$ npm list react-router
> Project
> ├── react-router@5.1.2 
> └─┬ react-router-dom@5.1.2
>   └── react-router@5.1.2  deduped
```

## Steps to reproduce

1. Make a `<Route>` with an optional parameter in the path
2. Access url without that parameter present in your url

## Expected Behavior

`match.params.{your optional param}` should actually be `undefined`

## Actual Behavior

`match.params.{your optional param}` is the string \`'undefined'\`

---

I'm hotfixing it with
```js
//-- TEMPORARY HOTFIX
Object.entries(props.match.params)
  .forEach(([paramName, paramVal]) => {
    if (paramVal === 'undefined')
      props.match.params[paramName] = undefined
  })
```

**Comment by timdorr** [comment]
6.13.7 isn't a valid version of this library. What version are you using?

**Comment by totalolage** [comment]
> 6.13.7 isn't a valid version of this library. What version are you using?

Sorry, accidentally grabbed npm version. I've edited the issue.

**Comment by totalolage** [comment]
Oops turns out it was my fault. The fact that the bug was on the books threw me off my own trail. Apologies.
