### ISSUE TITLE
history.push changes url but doesn't update component

### ISSUE THREAD

**Issue by xitanggg** [ReactTraining/react-router#7209]
## Version

"react-router-dom": "^5.1.2",

## Test Case

https://codesandbox.io/s/history-push-not-render-component-f3w08

```javascript
import React from 'react';
import ReactDOM from 'react-dom';
import { BrowserRouter as Router, Switch, Route } from 'react-router-dom';
import { createBrowserHistory } from 'history';

const MyApp = () => {
    const history = createBrowserHistory();
    return (
        <Router history={history}>
            <div>
                <ul>
                    <li>
                        <button onClick={() => history.push('/')}>Home</button>
                    </li>
                    <li>
                        <button onClick={() => history.push('/about')}>About</button>
                    </li>
                </ul>

                <Switch>
                    <Route exact path='/'>
                        <Home />
                    </Route>
                    <Route exact path='/about'>
                        <About />
                    </Route>
                </Switch>
            </div>
        </Router>
    );
};
```

```javascript
function Home() {
    return (
        <div>
            <h2>Home</h2>
        </div>
    );
}

function About() {
    return (
        <div>
            <h2>About</h2>
        </div>
    );
}

ReactDOM.render(<MyApp />, document.getElementById('root'));
```

## Steps to reproduce
Sample code renders two buttons (home and about) and two page component (also Home and About). Upon clicking each button, the button calls history.push to go to the respective page.

## Expected Behavior
Url is changed and also the component is rendered.

## Actual Behavior
Url is changed but component doesn't render.

This is temporarily fix by passing the `{ forceRefresh: true }` property when creating browser history like this `const history = createBrowserHistory({ forceRefresh: true });` Still, not sure why this occur and why forceRefresh solves the problem.

That reason I didn't use the `<Link>` component to wrap around the button is because I want to call a function to execute something before redirecting when the button is clicked. Would love to know if there is another way to do this. Thanks.

**Comment by pshrmn** [comment]
You are passing a `history` object to a `BrowserRouter`. You can only pass a custom history object to the base `Router` component.

https://reacttraining.com/react-router/web/api/Router

Also, you shouldn't create the `history` object in a component because you will be creating a new one every render. That should be hoisted outside.

```js
const history = createBrowserHistory();
function App() {
  return <Router history={history}>...</Router>
}
```

**Comment by xitanggg** [comment]
@pshrmn thank you so so much Paul. You make my day! Sorry I misunderstood the documentation. It works like charm now.
