### ISSUE TITLE
Simple Documentation Fix: Tell People useParams Requires a Router and to Use useRouteMatch Instead if Not in One

### ISSUE THREAD

**Issue by machineghost** [ReactTraining/react-router#7210]
In https://github.com/ReactTraining/react-router/issues/7026 I learned the useful information that useParams doesn't work outside of a router tag.  This was obvious in retrospect (I even saw the context being used in the code, via the dev tools), but I just didn't think of it until I found that ticket ... so I spent more time than I care to admit trying to figure out why `useParams` wasn't giving me the params that I could see were obviously there.

It seems to me that hook should really throw an error when it can't find its context, since it can never be of any use in that situation, and failing silently can only lead to confusion on the user's part.  Loudly screaming "THIS WON'T WORK HERE" seems like the best outcome to me.

But that's up to you library maintainers.  This ticket is for something simpler, which hopefully will require no thought: I shouldn't have had to go to that issue page to learn this fact :)

One sentence under the description of `useParams` could solve this:

Existing:
>useParams returns an object of key/value pairs of URL parameters. Use it to access match.params of the current <Route>.

New:
> useParams only works within a Router (eg. BrowserRouter) component's hierarchy; to work with parameters outside of that context use the useRouteMatch hook instead

P.S. Also the route https://reacttraining.com/react-router/web/example/url-params is broken *for me*, but I'm too lazy to determine whether it's an issue for anyone else (and file a separate ticket for it), so unless you see the issue yourself immediately you can ignore this.

**Comment by timdorr** [comment]
Can you submit a PR instead? An issue isn't really the best format for documentation fixes.
