### ISSUE TITLE
Examples are gone!

### ISSUE THREAD

**Issue by imjared** [ReactTraining/react-router#7213]
## Steps to reproduce

try to view web examples in chrome or safari (eg. https://reacttraining.com/react-router/web/example/basic), get a blank, black page. it might just remind you of the hopelessness of trying to upgrade your legacy application

## Expected Behavior

i expect a chat bot on this page that connects to ryan florence's cell phone and he gently walks me through the v2 => v5 upgrade path. or at least some code that i can wrangle into my app

## Actual Behavior

emptiness. loneliness

![image](https://user-images.githubusercontent.com/525011/77482948-6a8cfe80-6dfd-11ea-87d3-bd454f55e6cc.png)

I'm getting a note about CORS in my console:
```
Access to fetch at 'https://codesandbox.io/api/v1/sandboxes/define?json=1' from origin 'https://reacttraining.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

I thought this might be related to #7110 but I'm not blocking third-party cookies.

**Comment by elebumm** [comment]
Getting this error as well.

**Comment by IvanCaceres** [comment]
I ran into this same thing, seeing all of the examples gone as well.
Luckily I was able to find all of the examples in the repo for now:
https://github.com/ReactTraining/react-router/tree/master/packages/react-router-dom/examples

**Comment by pshrmn** [comment]
Normally when I see this issue it is because Privacy Badger is blocking CodeSandbox, but today it appears that is having CORS issues.

![image](https://user-images.githubusercontent.com/1127037/77490548-5e527280-6df8-11ea-964e-ca2eb329b3d2.png)

**Comment by CompuIves** [comment]
I'm sorry for the inconvenience on this, we changed our ingress which didn't take into account the CORS headers. It should now work as expected again.

**Comment by timdorr** [comment]
Thanks for the quick response Ives!

**Comment by Mustard** [comment]
<img width="890" alt="docs-borked" src="https://user-images.githubusercontent.com/310408/77596162-548f5300-6f4f-11ea-98c9-f8fe04f1575c.png">

**Comment by CompuIves** [comment]
Hey @Mustard. I've just committed a fix for this, should be live within 20min!
