### ISSUE TITLE
upstate react-router from 5.X to 7.x trow error

### ISSUE THREAD

**Issue by 5j2f** [ReactTraining/react-router#7217]
![reducerinjecter](https://user-images.githubusercontent.com/8499421/77718038-d8634100-701c-11ea-9c95-c990ff62d4d8.png)
 when upstate react-router from 5.X to 7.x , can't get store

**Comment by 5j2f** [comment]
![image](https://user-images.githubusercontent.com/8499421/77718231-4d367b00-701d-11ea-8f9e-64c32d19980e.png)
![image](https://user-images.githubusercontent.com/8499421/77718259-67705900-701d-11ea-8b41-1179623ec617.png)
![image](https://user-images.githubusercontent.com/8499421/77718318-8b339f00-701d-11ea-808f-57586bcfbc89.png)

**Comment by timdorr** [comment]
This isn't a React Router issue.
