### ISSUE TITLE
URL parameters incorrectly parsed when using location state (Modal Gallery example)

### ISSUE THREAD

**Issue by asliwinski** [ReactTraining/react-router#7218]
## Version

latest

## Test Case

https://codesandbox.io/s/react-router-modal-gallery-li0g3

## Steps to reproduce
Go to "Visit the Gallery".
Pull out the console tab.
Click on any link.
Note the incorrect `id` (4?q=test) being logged in the console.

## Expected Behavior
URL parameter being parsed correctly (e.g. `4` instead of `4?q=test`).

## Actual Behavior
URL parameter includes query string.

![image](https://user-images.githubusercontent.com/14044823/77718245-65bc7c00-6fb0-11ea-8e41-a2201ef4ae4a.png)

**Comment by timdorr** [comment]
You're setting the query as a part of the `pathname` for the Link. Use the `search` property on that location instead.

**Comment by asliwinski** [comment]
@timdorr Gotcha! Thanks a lot!
