### ISSUE TITLE
[v3] Use the new context API

### ISSUE THREAD

**Issue by rostislavbobo** [ReactTraining/react-router#7219]
The legacy context API will be removed in a future major version, which means `react-router@3` will not be compatible with `react@17`.

Why don't we migrate v3 to the new context API? There are many projects that use `react-router@3` and cannot migrate to new versions of it and still want to use the latest React.

I have tried it locally, everything works just fine. The only thing it affects is the `peerDependencies`:
```diff
  "peerDependencies": {
-    "react": "^0.14.0 || ^15.0.0 || ^16.0.0"
+    "react": "^16.3.0"
  },
```

Looking forward to hearing your thoughts

**Comment by timdorr** [comment]
We can't update and maintain compatibility with older apps. That would be a major breaking change, which we've already done with 4.0. 

3.x is only in bugfix mode. For newer versions of React, you should use 5.x and higher.

**Comment by rostislavbobo** [comment]
> That would be a major breaking change, which we've already done with 4.0.

That's exactly what I meant, agree.
Thanks!
