### ISSUE TITLE
[v5.1.2] props aren't passed when the route is rendered

### ISSUE THREAD

**Issue by eyeamkd** [ReactTraining/react-router#7224]
## Version : 

**5.1.2.**

## Test Case

```
import React from 'react'
import ReactDOM from 'react-dom'

import { BrowserRouter as Router, Route, Link } from 'react-router-dom'

function App() {
  return (
    <Router>
      <div>
        <ul>
          <li>
            <Link
              to={{
                pathname: '/topics',
                state: {
                  value: 'hi'
                }
              }}
            >
              Topics
            </Link>
          </li>
        </ul>
        <hr />

        {/* <Route path="/topics" component={Topics} /> */}
        <Route path="/topics" render={() => <Topics />} />
      </div>
    </Router>
  )
}
function Topics({ match }) {
  console.log(this.props)
  return (
    <div>
      <h2>Topics</h2>
      <ul>
        <h1>This is a topic</h1>
      </ul>
    </div>
  )
}

ReactDOM.render(<App />, document.getElementById('root'))
```

 codesandbox kept giving an unknown save error, therefore pasted the code

### Actual Behaviour : no props get passed, hence throwing an undefined error 

PS: this occurs only when the render method is used instead of component in ```<Route/>```

**Comment by MeiKatz** [comment]
How should this work? You don't pass the arguments passed to the lambda function further to your component.

**Comment by eyeamkd** [comment]
> How should this work? You don't pass the arguments passed to the lambda function further to your component.

should it just be  ?
```<Route path="/topics" render={(props) => <Topics {...props} />} />```

**Comment by MeiKatz** [comment]
@eyeamkd right.

**Comment by eyeamkd** [comment]
Thank you @MeiKatz

**Comment by MeiKatz** [comment]
@eyeamkd You're welcome!
