### ISSUE TITLE
[Feature proposal] Switch & route for location search params

### ISSUE THREAD

**Issue by T0nio** [ReactTraining/react-router#7226]
Hello,

We had a need in our app: using a route / switch logic based on search params.

#### Concrete example

We have a widget in the homescreen, that can be open by clicking on it, and have different steps in it's behaviour (selecting a mode, then doing an action on the selected mode). We wanted to use the URLSearchParams for storing the state of that component (to be able to have it after a refresh, or to share an URL).
We found the `react-router-dom` switch / route perfect for this need.

#### Feature

We didn't find a way to make it work with the current implementation of Route / Switch, so we built a new SearchRoute & SearchSwitch (based on the classical Route & Switch).

#### Proposal

So we wondered if it interest the project that we contribute upstream with those two new components ? 
I would be pleased to open a PR to share that part of code ! :)

Cheers,
Tonio

**Comment by timdorr** [comment]
No, we have no plans to deal with query parameters and and parsing them. We leave that up to the user to implement.
