### ISSUE TITLE
Route Children render does not provide routerProps

### ISSUE THREAD

**Issue by Taymindis** [ReactTraining/react-router#7227]
This is a code snippet, the childRoute will causing error  due to no routeProps. But working fine if i'm using other render method like `render` or `component` 
``` Cannot read property 'params' of undefined ```
```jsx
const ChildRoute = ({match}) => (<div>{match.params.id}</div>)

const App = () => (
  <Router>
    <Route
      render={({ location }) => (
          <Switch location={location} key={location.pathname}>
            <Route exact path="/">
              <div>HOME</div>
            </Route>
            {/* Route children has no route props */}
            <Route exact path="/:id">
              <ChildRoute />
            </Route>
            {/* <Route exact path="/image/:id" component={SingleImage} /> */}
          </Switch>
      )}
    />
  </Router>
);
```

**Comment by timdorr** [comment]
You either need to use the `render` prop or use the `useParams` hook to access those props. It's getting no props because you're not passing any into it.

**Comment by Taymindis** [comment]
Noted, just wondering docs said that child component has routeprops as well, but i use with this to solve the Issue

```jsx
  <Route exact path="/:id">
       {ChildRoute}
  </Route>
```

Thanks
