### ISSUE TITLE
matchPath get query string as parameter

### ISSUE THREAD

**Issue by sayjeyhi** [ReactTraining/react-router#7233]
`matchPath` returns query string as `params` :

```
{
  path: '/search/:term',
  url: '/search/h?categories=277609',
  isExact: true,
  params: { term: 'h?categories=277609' }
}
```

**Comment by timdorr** [comment]
matchPath expects that you've already broken up a URL into it's constituent parts. You should be passing in only the pathname to it and should have already extracted the search.
