### ISSUE TITLE
React-Router installation wont go further

### ISSUE THREAD

**Issue by Heisenberg-ch** [ReactTraining/react-router#7234]
Hi guys

Thats my realy first atemp for Coding. I bought a Video Starting guide for Java and i did some first steps like installing Visual Studio Code and NodeJs. Now the Turtorial says i need to istall react router but if i type npm install react-router-dom --save (in Visual Studio Code) this window in Powershell pop ups and it won't go further.  Any Advice for me?
![react-router-dom](https://user-images.githubusercontent.com/63145500/78424815-396bc400-7670-11ea-8e44-927478c0daf2.png)

**Comment by timdorr** [comment]
It looks like you didn't create a git repo. This isn't a React Router issue.
