### ISSUE TITLE
[v6-alpha.3] generatePath cannot replace splat parameter with empty value

### ISSUE THREAD

**Issue by CXuesong** [ReactTraining/react-router#7237]
## Version

v6.0.0-alpha.3

## Test Case
https://codesandbox.io/s/react-router-hjwu2
```ts
generatePath('/topics/*', { '*': '' })
```

## Steps to reproduce
Just retrieve the result of the snippet above.

## Expected Behavior
```
/topics/
```

## Actual Behavior
```
/topics/*
```

I think at least the last `*` should be allowed to fill in some empty value, but apparently the code does not allow it.

https://github.com/ReactTraining/react-router/blob/f778b05e39347ad09df2d141c290298c44645b0b/packages/react-router/index.js#L745-L749

**Comment by timdorr** [comment]
Simple fix:
```js
     .replace(/\*$/, splat => params[splat] == undefined ? params[splat] : splat); 
```

**Comment by CXuesong** [comment]
This fix is the best I can think of 😂

**Comment by vladshcherbin** [comment]
@timdorr After merging https://github.com/ReactTraining/react-router/pull/7238:

```js
generatePath('/:lang/login', {
  lang: ''
})
```

This will generate `//login` path, not sure if it's a bug or a feature. Optional params are not supported in v6, which could help solve this.

**Comment by timdorr** [comment]
Ah, maybe just the splat should allow it then? I'll fix that up.

Regardless, this should be closed now.

**Comment by mjackson** [comment]
I think we should probably just `throw` if someone is missing a param that is not a `*`. I don't think anyone will actually want to get back a `/:lang/login` path *after* calling `generatePath`, because that's kind of the whole point of the function. I'll fix it up.
