### ISSUE TITLE
[v6-alpha.3] Plus sign (+) in URL path gets decoded into space

### ISSUE THREAD

**Issue by CXuesong** [ReactTraining/react-router#7240]
## Version

v6.0.0-alpha.3

## Test Case

https://codesandbox.io/s/react-router-medzs

## Steps to reproduce
![temp1](https://user-images.githubusercontent.com/11611687/78678231-42cc8900-791b-11ea-8361-5d88e39497ba.gif)

## Expected Behavior
I should be able to see something like "new features in c++ 20".

## Actual Behavior
I see "new features in c   20". Plus signs are converted into space.

## Notes
This seems like a regression of #716 #2426

**Comment by timdorr** [comment]
You can't put an unencoded path into the pathname. We don't do any URL encoding or decoding. That's expected to be done by the user. We just put it in the `href` directly without any modification:

![image](https://user-images.githubusercontent.com/17882/78685878-58609500-78c0-11ea-82d6-a03577102f93.png)

If you expect non-URL-safe characters in your params or URLs, you are expected to encode and decode them yourself.

**Comment by CXuesong** [comment]
Okay... So I'll go with `decodeURIComponent`. I just wanted to keep slashes in the (splat) parameter unescaped so I suppose `decodeURIComponent` with a `%2f` -> `/` replacing should work.

Just want to mention two things. First,

> We don't do any URL encoding or **decoding**.

Yeah and I'm happy with this decision, especially on the encoding part. But I think you *have* actually done URL decoding with `decodeURIComponent` when parsing the parameters in `pathname`. I've changed the code sandbox above a little, so you can see
```ts
to="new+features+in+c%23 8.0"
```
gets decoded automatically into
![image](https://user-images.githubusercontent.com/11611687/78689267-b6c15e00-7928-11ea-835c-8c2210b6f3dd.png)

I'm not sure whether this is consistent with your statement. Not that I'm dissatisfied with this, I'm just a little bit confused and surprised to see the parameter in `pathname` *gets* decoded.

Second, I suspect `+` is a valid character in the path. See
* https://github.com/ReactTraining/react-router/issues/716#issuecomment-71346876
* https://stackoverflow.com/questions/1005676/does-a-in-a-url-scheme-host-path-represent-a-space

However, such discussion can come into nuisance so I think the best I can do is to escape it.
