### ISSUE TITLE
Cannot read property 'location' of null when use useRoutes

### ISSUE THREAD

**Issue by carlrip** [ReactTraining/react-router#7241]
## Version

6.0.0-alpha.3

## Test Case

https://codesandbox.io/s/frosty-panini-ifqcj?file=/src/App.js

## Steps to reproduce

- Open the codesandbox project
- You'll see an error is thrown straight away: Cannot read property 'location' of null

## Expected Behavior

I'd expect "home" to be rendered in the page

## Actual Behavior

An error, Cannot read property 'location' of null, is thrown

**Comment by timdorr** [comment]
You have to wrap it with a Router, preferably at the root of the tree.

**Comment by nanxiaobei** [comment]
Hi, how you solved this case? Same issue here.

**Comment by gugadev** [comment]
@timdorr I have a `BrowserRouter` containing the routes. But still throws the error. Seems that can't create a context.

````jsx
export const App = () => {
  const routes = useRoutes(appRoutes);

  return (
    <Provider store={store}>
      <BrowserRouter>
        <aside>
          Menu lateral
        </aside>
        { routes }
      </BrowserRouter>
    </Provider>
  );
};
````

**Comment by timdorr** [comment]
You're still using the hook before the router component. You have to have it above that component or move the useRoutes down the tree.

**Comment by gugadev** [comment]
@timdorr I got it, just put the useRoutes inside a child componente of `App` and it works. Thank you!
