### ISSUE TITLE
[v6-alpha.3] navigate(-1) does not work after refresh

### ISSUE THREAD

**Issue by mystical-ryan** [ReactTraining/react-router#7242]
## Version

**[v6-alpha.3]**

## Test Case

https://codesandbox.io/s/distracted-https-4s5zs
Sandbox have 2 pages: 

- Page One to Page Two with a "Go Back" button using navigate("/"); Works fine after refresh
- Page One to Page Three with a "Go Back" button using navigate(-1); Does not work after refresh
## Steps to reproduce

1. Route to next page with a "Back" button using navigate(-1)
2. Refresh the page
3. `navigate(-1)` no longer works

## Expected Behavior
Go back to previous page after refresh.

## Actual Behavior
Unable to navigate back after refresh.

**Comment by timdorr** [comment]
This is how history has always behaved. When you refresh the page, you're resetting the history stack to one item. So, there is nothing to "go back" to. This is intended behavior.

**Comment by mystical-ryan** [comment]
Noted and thanks. But can check is there any means to "go back" using "-1" rather than "path", as the "Back" button is a common component that are used by many different components.
