### ISSUE TITLE
react-router with error-boundary and lazy-load, link failure

### ISSUE THREAD

**Issue by iugo** [ReactTraining/react-router#7247]
## Version

5.1.3

## Test Case

https://codesandbox.io/s/react-router-9dg7u

## Steps to reproduce

1. Trigger an error.
2. Click Link on the error page.

## Expected Behavior

Link is valid.

## Actual Behavior

Link is invalid.

## Temporary Solution

Use ErrorBoundary in components without lazy load.

or

Use `a` instead of `Link`.

**Comment by timdorr** [comment]
This seems like more of a React issue when using context around error boundaries with suspense components.
