### ISSUE TITLE
Use PureComponents or memo for react-router-dom

### ISSUE THREAD

**Issue by theboolean** [ReactTraining/react-router#7248]
## Version

5.1.2

**This is a feature request.**

This issue is a copycat of #6434, since it was closed because the ecosystem was not ready to lose support for legacy context API. More than 1 year passed since then, and IMHO since v6 is out in alpha and it already contains breaking changes, we can go one step further and take the decision of optimizing `react-router-dom` components for the final v6, mentioning in the migration guide to upgrade to new context API.

In my case for example I have a list component that receives an array of items and I can't avoid that when one single item changes, all the `Link`s in other items re-renders, creating a big performance hit in the application.

**Comment by timdorr** [comment]
Seems like an easy enough fix. Want to make a PR?

**Comment by theboolean** [comment]
@timdorr here you are! #7258
