### ISSUE TITLE
how to match children path with matchPath?

### ISSUE THREAD

**Issue by 5j2f** [ReactTraining/react-router#7249]
for example: I want to matchPath('/project/A' ,{path:'/project'}) 、matchPath('/project/B' ,{path:'/project'}) 、matchPath('/project/C' ,{path:'/project'})  all return true , how？

**Comment by MeiKatz** [comment]
`matchPath()` works like this: the first argument is the current path and the second argument is the path you want to check against. Therefore your three examples work correct. In your case you have to swap the arguments, e.g. `matchPath("/project", { "path": "/project/A" })`
