### ISSUE TITLE
Make history a field inside StaticRouter

### ISSUE THREAD

**Issue by phapdinh** [ReactTraining/react-router#7250]
# Version

### This is a feature request

Inside https://github.com/ReactTraining/react-router/blob/master/packages/react-router/modules/StaticRouter.js, you defined the history object inside the render method. Why not make the history object a field inside the component and set default props. This will help performance because you won't have to create a new object reference every time you rerender.

**Comment by timdorr** [comment]
StaticRouter is for server rendering, so it doesn't ever get rerendered.
