### ISSUE TITLE
Match params are getting lowercased/uppercased if the address bar is used to call the page for the second time

### ISSUE THREAD

**Issue by devserkan** [ReactTraining/react-router#7252]
## Version

5.0.0

## Steps to reproduce

Go to the route: http://example.com/TheFirstRoute and after the first load, click the address bar and hit Enter.
Go to the route: http://example.com/TheFirstRoute/1/item and after the first load, click the address bar and hit Enter

## Expected Behavior
Keep the routes as they are.

## Actual Behavior
For the first case, it changes to http://example.com/TheFirstRoutE (yes, uppercasing the last letter only)
For the second case, it changes to http://example.com/firstroute/1/item lowercasing all

Sorry for the inconvenient bug report but this issue is eating me and I can't find a reason/solution. Most probably this is not a bug in React Router but I can't understand this behavior.

I'm creating dynamic routes by using the data I get. I have two other routes: http://example.com/Second and http://example.com/Third. The only difference is those are one letter. I don't see this issue for those two routes.

I'm pretty sure this is happening because of a bug in my code but I can't find where. Because everything seems fine. My routes working as expected. Even if I directly open that buggy route, it works. I refresh the page it works. But when I click the address bar, hit Enter, it changes the route. Either the last letter or all words according to which route I am.

I just want to know what is the difference by opening a fresh route or refreshing the page then clicking the address bar and hitting the enter.

I created a simple sandbox simplifying my code but I can't reproduce the same bug there. If you want to see the sandbox I can share it.

**Comment by devserkan** [comment]
I've found that the issue is valid only on Chrome. I can't reproduce it on Firefox. Also, Chrome on Android also is not causing this issue. Very weird.

**Comment by timdorr** [comment]
This is a browser issue. We can't work around this because the casing is changed before it gets to the DOM.
