### ISSUE TITLE
Convert Route and Switch into functional component

### ISSUE THREAD

**Issue by phapdinh** [ReactTraining/react-router#7253]
# Version

### this is a feature request

For the route and switch component, https://github.com/ReactTraining/react-router/blob/master/packages/react-router/modules/Route.js, it looks like route is a presentation component so there is no need for Route to ever have state or lifecycle methods that are currently being inherited from the Component class. Shouldn't route then be converted to a functional component for performance reasons and readability?

**Comment by MeiKatz** [comment]
The only reason I can think about, why it is not a functional component, is, that we add error messages in development mode.

**Comment by phapdinh** [comment]
@MeiKatz functional components still have access to their prototype so I don't see how the error messages will be affected.

**Comment by MeiKatz** [comment]
I never tried this, actually, but thought that functional components don't have hook methods. I might be wrong. If you knew it better, then go for it.

**Comment by phapdinh** [comment]
@MeiKatz it doesn't matter if functional components have lifecycle methods. ES6 classes are only wrappers around es5 prototype inheritance. You can add methods to the prototype chain by modifying the prototype https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/Object_prototypes#Modifying_prototypes

**Comment by MeiKatz** [comment]
That's not the point. It matters if React handles them different.

**Comment by timdorr** [comment]
Gregor is right. There isn't really any functional difference, so there's no need to change these up.
