### ISSUE TITLE
Route children always renders when function, but only if path matches when component

### ISSUE THREAD

**Issue by evansjohnson** [ReactTraining/react-router#7255]
## Version
5.1.2

## Test Case
https://codesandbox.io/s/react-router-playground-kqv2q

## Steps to reproduce
Change dependency version from left panel - 5.0.1 -> 5.1.2 changes behavior (seems like 5.1.0 5.1.1 contained a bug causing this example to error)

## Expected Behavior
Children behavior should be the same if it is a function or a component

https://reacttraining.com/react-router/web/api/Route/children-func
children is documented as being a function

There is a lot of discussion at https://github.com/ReactTraining/react-router/issues/6362 about how rendering children only if the `path` matches was expected behavior all along and not marked as a breaking change.

The docs state (see link above) "Sometimes you need to render whether the path matches the location or not. In these cases, you can use the function children prop. It works exactly like render except that it gets called whether there is a match or not."

It sounds like the decision was already made to go against what the docs state and only render children if the path matches - I agree this is a much more intuitive API.  However it does seem like this is a breaking change and notice should be provided in v5 release notes.

## Proposed fix
I think the docs should be updated to reflect #6362 and children should follow the behavior outline in #6362 if provided as a function.

I'd be willing to look into opening a PR if this sounds good.

## Actual Behavior
Children always renders if a function, but not if component

**Comment by timdorr** [comment]
Notice was provided. Michael did a separate blog post for this release: https://reacttraining.com/blog/react-router-v5-1/

**Comment by evansjohnson** [comment]
Hey @timdorr this issue was specifically not commenting on that decision/notice of it but rather that the documentation is out of date.  I know you probably get a lot of annoying issues in a repo this big but the documentation describing behavior that no longer exists caused problems for me and I think it's something that should be addressed.  There is also the issue that `children` behaves differently if provided as an inline function as the example shows - potentially the documentation should be broken out as a separate issue from what is outlined here.

Sorry if it seemed I was complaining about this behavior change - I think it's great and am looking forward to using the new API!

**Comment by evansjohnson** [comment]
Hey @timdorr I think this needs a second look.  I don't want to recommend my team use v5 with the new `children` pattern that would be so great to have if the docs for it are out of date and the API is not consistent with children as a function vs component.

Happy to contribute a PR for this but it seems like it may be a waste of time if it's closed as quickly as this issue was.  I sympathize with all the issues you have to triage with a library this large and am sorry for pinging you twice here but I put time into figuring out why your library was not working as expected and would appreciate a more thought through answer here.

Thanks
