### ISSUE TITLE
Request: withRouter for v6

### ISSUE THREAD

**Issue by nicoburns** [ReactTraining/react-router#7256]
Reading through the v6 migration guide, it seems that the new API is intended to be hooks-only. However, [you cannot use hooks inside class components](https://reactjs.org/docs/hooks-faq.html#should-i-use-hooks-classes-or-a-mix-of-both). This would mean that in order to upgrade to v6, I would need to convert all my class components that use routing into functional components even though [react has no intention of deprecating class components](https://reactjs.org/docs/hooks-faq.html#do-i-need-to-rewrite-all-my-class-components). I believe a new version of the `withRouter` HOC should be supported in order to enable use of class components.

Note: I don't need support older versions of React, so `withRouter` can use hooks under the hood. I believe this makes the implementation pretty trivial:

```javascript
function withRouter (Child) {
     return function withRouter (props) {
          const location = useLocation();
          const history = useHistory();
          // other relevant props
          ...
          return <Child {...props} history={history} location={location} />;
    }
}
```

I could of course write this myself, but I think it makes sense for this to be in `react-router` core.

**Comment by timdorr** [comment]
Because there are several different hooks and a non-trivial cost to using them all, having a big single mega-HOC wouldn't be the right approach. But given that writing a small wrapper component that uses the right hook and passes it as props, it's best that this is left to the user to implement.
