### ISSUE TITLE
activeClassName has a problem with path-to-regexp

### ISSUE THREAD

**Issue by ZeroCho** [ReactTraining/react-router#7262]
https://github.com/ReactTraining/react-router/issues/6201

As mentioned in the issue above, if a webpack's resolve.modules option is anything else than 'node_modules', activeClassName is not applied.

https://github.com/ReactTraining/react-router/issues/6201#issuecomment-449239823

```
npm i path-to-regexp@1.7.0
```
This command solve the issue, but is there any way without installing an additional module?

**Comment by timdorr** [comment]
That module is already installed, as it's a dependency of this project. That will just lock it to the version needed.
