### ISSUE TITLE
Behavior when using `/*` in nested Routes (v6)

### ISSUE THREAD

**Issue by numb86** [ReactTraining/react-router#7263]
## Version

react-router@6.0.0-alpha.3

## Steps to reproduce

I write the following code.
Access `/userdetail`.

```javascript
const User = () => (
  <div>
    User
    <br />
    <Routes>
      <Route path="/" element={<div>index page of user</div>} />
      <Route path="detail" element={<div>detail page of user</div>} />
    </Routes>
  </div>
);

const App = () => {
  return (
    <BrowserRouter>
      <Routes>
        <Route path="/" element={<div>home</div>} />
        <Route path="user/*" element={<User />} />
      </Routes>
    </BrowserRouter>
  );
};
```

## Expected Behavior

In this case, I think it's correct to see only the `User`.

## Actual Behavior

However,  the`detail page of user` is displayed too.

In other words, it doesn't matter whether they are separated by `/`.
I think `detail page of user` must be displayed only when I access `user/detail`.

**Comment by pierreneter** [comment]
try:

```jsx
const User = () => (
  <div>
    User
    <br />
    <Outlet />
  </div>
);

const App = () => {
  return (
    <BrowserRouter>
      <Routes>
        <Route path="/" element={<div>home</div>} />
        <Route path="user" element={<User />}>
          <Route path="/" element={<div>index page of user</div>} />
          <Route path="detail" element={<div>detail page of user</div>} />
        </Route>
      </Routes>
    </BrowserRouter>
  );
};

```

**Comment by pierreneter** [comment]
use `import { Outlet } from "react-router-dom";`

**Comment by numb86** [comment]
Thanks your comment.

However, that code changes the conditions under which the `User` is displayed.
In the original code, when I access `user/foo` it display `User`, but in your code nothing is displayed.

How to display the `detail page of user` properly is not my concern.
This is just example.
I want to know the current behavior of nesting `Routes` is as intended or a bug that should be fixed.

**Comment by pierreneter** [comment]
To make it easier, you should design the `User` as a wrapper, I saw you do it in the example and I just correct it.
If you want to use `/foo` as username, you should use:

```jsx
<Route path=":username" element={<div>detail page of user</div>} />
```

As you said, it's not a bug, it's behavior as intended, the right concept of v6.

Using `path="user"`` and its nested means that it will handle the `user/*` part according to the routes in it.
And you should only use `user/*` to handle routes that you are unsure of.

Let me correct it for you again:

```jsx
const User = () => (
  <div>
    User
    <br />
    <Outlet />
  </div>
);

const App = () => {
  return (
    <BrowserRouter>
      <Routes>
        <Route path="/" element={<div>home</div>} />
        <Route path="user" element={<User />}>
          <Route path="/" element={<div>index page of user</div>} />
          <Route path=":username" element={<div>detail page of user</div>} />
          <Route path="/*" element={<div>anything else</div>} />
        </Route>
      </Routes>
    </BrowserRouter>
  );
};
```

You should refer to this article before getting started with React Router v6: https://reacttraining.com/blog/react-router-v6-pre/

**Comment by numb86** [comment]
I appreciate your polite comment.
Thanks!
