### ISSUE TITLE
Status={404} doesnt actually thow a 404 httpcode

### ISSUE THREAD

**Issue by jeanpoelie** [ReactTraining/react-router#7266]
## Version

v5.1.2

## Test Case

https://github.com/wdjungst/react-project/blob/master/create-react-project/blueprint/modules/routes.js

## Steps to reproduce

Use the example above.
Go to [url]/test
In the browser network you will still see a 200 OK message. (see attachment 1)

![attachment 1](https://user-images.githubusercontent.com/10237926/79545800-98c6cc80-8091-11ea-920e-4a52d967f9c2.png)

## Expected Behavior

To see a 404 Not Found (to tell the client NOT to cache the page)

## Actual Behavior

caches te page because it had a 404, clients run into other issues because of this.

## Our issue

If a user is online on our react platform, and we do a new deployment, the chances are that the user refreshes/opens a page or navigates to a new page.
This will result in them having a part of the website and the otherpart being 'replaced' with our 404 not found page.
We have had multiple moment where the user had their main.chunk.js file but the contents of it where the 404 missing page or even the static index.html page.

## Replica's / other issues

I have searched for this issue and found multiple other issues like:
#7257
#7076
#6900

But I can't seem to find anyone who is running into the same caching issues as we are.

**Comment by jeanpoelie** [comment]
Also the demo from react-router does not actually throw a 404 not found: https://reacttraining.com/react-router/web/example/no-match

**Comment by timdorr** [comment]
This is a client side library, so we don't control how the server responds. For Codesandbox, we also don't control the server side of things, so we can't instruct it to return a particular status code. That is left up to you to implement in whatever server framework/library you're using.
