### ISSUE TITLE
Recursive Path example throws an error.

### ISSUE THREAD

**Issue by vicary** [ReactTraining/react-router#7272]
##  Version
Latest? The version bundled in https://reacttraining.com/react-router/native/example/recursive-paths as of the time of writing.

## Test Case
https://codesandbox.io/s/react-router-recursive-paths-h74vx

The sandbox directly embedded in the official website.

## Steps to reproduce
Just open it.

## Expected Behavior
Not throw.

## Actual Behavior
`Array.find()` doesn't like that your path param id is a string, while having the actual data in number.

**Comment by timdorr** [comment]
The web example works fine: https://reacttraining.com/react-router/web/example/recursive-paths

We just haven't updated the RN version. Want to make a PR?
