### ISSUE TITLE
React App with router not opening on ios 13.4.x

### ISSUE THREAD

**Issue by nvnvenki** [ReactTraining/react-router#7278]
## Version

**4.2.2**

## Steps to reproduce

We have app hosted at https://www.perfios.com/argentum/login
We use react router in this app.

Below is the package.json of react and routers

 "react": "16.8.4",
 "react-dom": "16.8.4",
 "react-router-dom": "^4.2.2"

## Expected Behavior

It works fine on all the Android versions and lower ios versions.

## Actual Behavior
When you open this app in  browser the page just keeps loading forever. This is happening in chrome, safari and also firefox.

Below is screenshot of about phone with versions

![image](https://user-images.githubusercontent.com/1863449/79943232-0013c080-8486-11ea-9888-798cb5c19e41.png)

![image](https://user-images.githubusercontent.com/1863449/79943244-07d36500-8486-11ea-8f0c-3df92eb158c8.png)

**Comment by rohith94** [comment]
facing same issue in currently in  **ios 13.4.1**

**Comment by timdorr** [comment]
Just confirmed I'm seeing this on my iPad too. But I don't see any problems with the examples on the docs site. This has to be something related to your setup. Hook up the Dev Tools and see what's going on behind the scenes. The fact nothing is loading points to a server issue.
