### ISSUE TITLE
Warning for standard use of Link in react-router-native

### ISSUE THREAD

**Issue by allpwrfulroot** [ReactTraining/react-router#7281]
## Version 

react-router-native, 5.1.2
## Steps to reproduce

```
<Link to="/login" testID="login">
     <Text>Sign in</Text>
</Link>
```
or
```
<Link to="/login" component={TouchableOpacity} testID="login">
     <Text>Sign in</Text>
</Link>
```
## Expected Behavior

Should work as documented

## Actual Behavior

Failed prop type: Invalid prop 'component' of type 'object' supplied to 'Link', expected 'function'

<img width="483" alt="Screen Shot 2020-04-23 at 10 15 12 PM" src="https://user-images.githubusercontent.com/2465035/80168475-f175f800-85b0-11ea-89f6-266ff3a4ef7c.png">

**Comment by timdorr** [comment]
Fixed in #7276. Not released yet.
