### ISSUE TITLE
Add usePrompt hook

### ISSUE THREAD

**Issue by sixers** [ReactTraining/react-router#7286]
It seems that currently the only way to prevent `react-router` from navigating is to use `<Prompt>` component. It seems like it's not a "real" component, but more like a reusable piece of logic wrapped as an empty component. I want to propose an alternative solution: a custom hook, as it seems like a better fit for this use case.

I think it can be as simple as:

```js
function usePrompt(message, when) {
    const history = useHistory();
    const unblock = useRef(null);

    useEffect(() => {
        if (when) {
            unblock.current = history.block(message);
        } else {
            unblock.current = null;
        }
        return () => {
            if (unblock.current) {
                unblock.current();
            }
        }
    }, [when, history, message])
}
```

Example: https://codesandbox.io/s/react-router-preventing-transitions-with-hooks-uio0m?file=/example.js

`react-router` could also expose another hook, which would allow customization. It could return a prompt state (active / non-active) and callbacks for confirming and cancelling navigation.

I'm sure there is a better way to do it, but here's a naive way which doesn't touch any internals:

```js

function useCallbackPrompt(when) {
    const history = useHistory();
    const [showPrompt, setShowPrompt] = useState(false);
    const [lastLocation, setLastLocation] = useState(null);
    const [confirmedNavigation, setConfirmedNavigation] = useState(false);

    const cancelNavigation = useCallback(() => {
        setShowPrompt(false);
    }, []);

    const handleBlockedNavigation = useCallback((nextLocation) => {
        if (!confirmedNavigation) {
            setShowPrompt(true);
            setLastLocation(nextLocation);
            return false;
        }
        return true;
    }, [confirmedNavigation]);

    const confirmNavigation = useCallback(() => {
        setShowPrompt(false);
        setConfirmedNavigation(true);
    }, []);

    useEffect(() => {
        if (confirmedNavigation && lastLocation) {
            history.push(lastLocation.pathname);
        }
    }, [confirmedNavigation, lastLocation]);

    usePrompt(handleBlockedNavigation, when);

    return [showPrompt, confirmNavigation, cancelNavigation];
}
```

> Note: It was inspired by [this post](https://medium.com/@michaelchan_13570/using-react-router-v4-prompt-with-custom-modal-component-ca839f5faf39)

Here's an example which integrates with antd's [Modal](https://ant.design/components/modal/) and implements what I think is a common use case: prompt on unsaved changes: https://codesandbox.io/s/react-router-preventing-transitions-custom-modal-with-hooks-l215t?file=/example.js

**Comment by rvision** [comment]
The example on codesandbox doesn't intercept clicking on a bookmark link in browser's toolbar. I've tried to use https://www.npmjs.com/package/react-router-navigation-prompt which catches this, but it has issues with hashrouting, path is updated no matter what you choose, and component rendered is invalid.

Btw, does anyone know any decent working solution?

**Comment by vdh** [comment]
@rvision That's not an in-page navigation, that's basically the equivalent of closing the tab and re-opening a new page in a new tab. Direct navigation would need a very different workflow to catch.

**Comment by rvision** [comment]
@vdh I don't know what kind of navigation is that - but on facebook, for example, it prompts default browser prompt when clicking on bookmark link. How can this be intercepted or there is no way to prevent default browser prompt from displaying?

**Comment by MeiKatz** [comment]
@rvision Not sure if Facebook does this, but you can add a bookmark link like `javascript:prompt('Foo?');`. This would show the prompt on every page.

**Comment by rvision** [comment]
@MeiKatz that's not what we're referring here to, that's "classic" javascript prompt. Facebook prompts user about unsaved changes, asking him to confirm page leave.

**Comment by MeiKatz** [comment]
@rvision Not sure about your problem but Facebook uses the beforeunload event.

**Comment by rvision** [comment]
@MeiKatz correct

Is there any way to intercept that AND in-page navigation and display custom confirm dialog?

**Comment by MeiKatz** [comment]
@rvision short answer: no. It would be a security risk.

**Comment by rvision** [comment]
@MeiKatz yeah, that's what I thought so... 

I'm probably going to combine this prompt with https://github.com/jacobbuck/react-beforeunload and use both to achieve this.

Thanks everyone
