### ISSUE TITLE
[v6-alpha.3] Link propTypes does not include number

### ISSUE THREAD

**Issue by wadamek65** [ReactTraining/react-router#7289]
## Version

**6.0.0-alpha.3**

## Test Case
```
<Link to={-1}>link</Link>
```

https://codesandbox.io/s/react-router-bs15h?file=/index.js

## Steps to reproduce
Supply `to` prop in `Link` with a number.

## Expected Behavior
No error in development is shown.

## Actual Behavior
It works, but a proptype error is shown in development because `Link` propTypes include only an Object or a String. `navigate` can be used with a number so `Link` should be able to accept a number in it's `to` prop.

I'd be happy to create a PR if this is indeed an oversight.

**Comment by illuminist** [comment]
Have never heard of this feature before. What does number do in Link?

**Comment by wadamek65** [comment]
It navigates you by the number of entries you provide in the history. So for example -1 will simply move you backwards.

**Comment by illuminist** [comment]
I'm not sure which `navigate` you're talking about. Do you actually mean `history.go`?

**Comment by BenKalungi** [comment]
have you submitted, a PR already???

**Comment by wadamek65** [comment]
I believe after conversion to typescript this should be fixed and the issue can be closed. Need to double-check though.

**Comment by timdorr** [comment]
This isn't a feature of v6. We only accept string and object `to` types.
