### ISSUE TITLE
Router does not re-render Component when search params change

### ISSUE THREAD

**Issue by manrajgrover** [ReactTraining/react-router#7293]
## Version

5.1.2

## Steps to reproduce

1. Change query params while keeping route pathname same in `<Link />`

## Expected Behavior

Component re-renders with new query params

## Actual Behavior

Component ignores query params change and Component does not re-render

**Comment by timdorr** [comment]
Without any code to look at it an example on codesandbox.io, it's hard to know what's going on here. But this definitely does work, so I would check your code.
