### ISSUE TITLE
Migrate codebase to TypeScript?

### ISSUE THREAD

**Issue by murbanowicz** [ReactTraining/react-router#7295]
Hi,

there is few issues here about providing typing, but I would propose to go further - migrating codebase to TypeScript.

TS nowadays became industry standard and it is not only "nice to have typed code", but it makes it easier to maintain and contribute.

I would love to help with that by preparing the first PR which would enable writing TS files, linting them and compile all together - JS and TS to ready to ship code. 
It would enable maintainers and contributors to gradually migrate codebase to TypeScript.

What do you think? 
If you say yes, I will prepare "Enable TypeScript migration" PR as soon as possible (for v6 of course).

**Comment by timdorr** [comment]
It's happening in #7292 right now.
