### ISSUE TITLE
Feature request: <Link> can compose routes using parameters + route definition

### ISSUE THREAD

**Issue by robpaveza** [ReactTraining/react-router#7296]
Hello! I've been working on a portal for a nonprofit and we're considering a modest refactor (new skin, etc.) and one of the things I've been considering doing is factoring out some app state into routes to be more consistent (particularly for sharing). We have an annual summer program for high schoolers, and the year of the program is the root for the purposes of the data model. Today, that datum is stored within the Redux store, which means it's local per-user-instance:

```
https://my.site/students/pending
```

I'd like that to instead be:

```
https://my.site/2021/students/pending
```

I'm not worried about composing the routes. That's easy enough. However, I don't want to have to do this with all my links:

```tsx
<li><Link to={`/${year}/students/pending`}>Pending</Link></li>
<li><Link to={`/${year}/students/invoiced`}>Invoiced</Link></li>
```

...particularly because then I have to also pull the route match from any place in which the links are being generated.

Instead, I want to be able to write this within my router:

```tsx
<Route to="/:year/students/:state" exact component={Students} />
```

...and this within my links:

```tsx
<li><Link to="/:year/students/pending">Pending</Link></li>
<li><Link to="/:year/students/invoiced">Invoiced</Link></li>
```

And further, if I want to customize the links, we can pass them in with an optional `params` property:

```tsx
<li><Link to="/:year/students/:state" params={{state: 'pending'}}>Pending</Link></li>
<li><Link to="/:year/students/:state" params={{state: 'invoiced'}}>Invoiced</Link></li>

-- or --

<Link to="/:year/students" params={{year:2019}}>Compare to last year</Link>
```

The truth is I want to define my routes as constants elsewhere and reference them as constants so I don't run the risk of mis-typing....

```
import { STUDENTS_ROOT } from './routes';
<Link to={STUDENTS_ROOT.path} />
```

and then everything just fits together.

Summary:

 - When a `<Link>` encounters a URL parameter (`:something`) in its path, it should:
  -- Check for an optional `params` property containing an object with the matched URL parameter in its property list, and if found, substitute it in the rendered output
  -- If the first lookup failed, look at the current router context and whether the current match contains the same URL parameter, substituting that on success
  -- Otherwise, don't substitute at all

Thanks!

**Comment by timdorr** [comment]
You're looking for the generatePath function: https://reacttraining.com/react-router/core/api/generatePath
