### ISSUE TITLE
[v6] animated switch between routes in v6

### ISSUE THREAD

**Issue by MeiKatz** [ReactTraining/react-router#7297]
Are there any plans on how somebody could realise animated transitions between routes? In v5 we could use the `location` prop of the `<Switch />` component, but in the new `<Routes />` component there isn't any replacement for this. Or is there an other way to do it in v6?

**Comment by timdorr** [comment]
I think two things need to happen: 

- `useRoutes` needs to accept a provided location. 
- We should switch those positional args to an `options` object.

The latter is optional, but more scalable as an API.

Then adding a location prop to `<Routes>` is easy.

**Comment by MeiKatz** [comment]
This sounds good to me. For me it would be fine to only add it to the `useRoutes` hook. `<Routes />` is just a wrapper around it and can be implemented on my own.

**Comment by MeiKatz** [comment]
Related pull request: #7298

**Comment by AdrienLemaire** [comment]
Can someone explain the advantages of adding location in Routes with a usage example?

I personally don't use 3rd-part transition/animation library, and can do animated page transition using useNavigate, useEffects and css.

In the example below, I set a timeout of 500ms in an effect, and a 500ms opacity transition when clicking on a button.
```tsx
export default function Welcome() {
  const navigate = useNavigate();
  const [path, setPath] = useState<string | null>(null);

  function handleClick(path: string) {
    setPath(path);
  }

  useEffect(() => {
    if (path) setTimeout(() => navigate(path), 500);
  });

  return (
    <div
      className={path ? cn(container,   "transition-opacity", "duration-500", "ease-linear", "opacity-0") : container}
      style={{ backgroundImage: `url(${jigsaw})` }}
    >
      <Button
        onClick={() => handleClick("/discover/")}
        className={pinkButton}
        disabled={path !== null}
      >
        <span className="m-auto">Discover</span>
      </Button>
```

**Comment by MeiKatz** [comment]
@AdrienLemaire Well, within a `<Routes />` there can be only **one page** active at a time. When you want a transition between two pages you want **two pages** to be active at a time. That means that you need **two locations** to be used at a time. `<Routes />` (like `<Switch />` in RRv5) can only handle **one location** at a time. Therefore you need a way to tell one `<Routes />` to use the **current location** and the other one to use the **upcoming location**. And here `<Routes location />` comes in handy.

**Comment by AdrienLemaire** [comment]
@MeiKatz makes sense in order to show parts of both pages at the same time during the animation.

Another thought: Wouldn't [the useDeferredValue hook](https://reactjs.org/docs/concurrent-mode-patterns.html#deferring-a-value) from upcoming concurrent mode also help with that, providing an alternative to the Routes location solution? I have not yet managed to get it working in my case with the experimental branches.

**Comment by MeiKatz** [comment]
@AdrienLemaire The `useDeferredValue` hook might help here, but it doesn't challenge the use case of `<Routes location />`. Therefore the both features might go well together.

**Comment by MeiKatz** [comment]
This issue is still fresh even so there is a pending pull request.

**Comment by MeiKatz** [comment]
@woollsta You're right, but the approach I realised in my referenced PR makes it a lot easier. Currently the problem is, that @mjackson and @ryanflorence are busy doing other stuff and therefore RRv6 makes no progress at all. Hopefully this will change in the near future. Would be a pity if not.

**Comment by MeiKatz** [comment]
You can clone my repository and run the install script..

**Comment by tranvansang** [comment]
in my project, I didn't use `Switch` either to achieve animation. Instead, I found that at least in v5, `Route` exposes a `computedMatch` props, which enables me to use `matchPath` to get the matched route and its matched params (something like `<Route computedMatch={matched}><matchedRoute.component/></Route>`.

I also use `react-transition-group`, which remembers the props of the last (the going to disappear) component. So that it does not give the incorrect matched params while the animation happens.

I haven't tried with v6 yet. But hope that there will be another workaround if the `computedMatch` props is removed.

**Comment by jymbob** [comment]
I've just come across this attempting to pair react-spring with React Router v6.

Example with v5 (linked from react-spring): https://codesandbox.io/s/jp1wr1867w - old component leaves, new component enters

Example with v6: https://codesandbox.io/s/react-router-spring-b5941 - old component is immediately replaced, then animates out and back in

@MeiKatz could you explain what changes, if any, I'd need to get this working with your PR?

**Comment by MeiKatz** [comment]
@jymbob in RRv6 there is no `<Switch />` component. The replacement is the `<Routes />` component that does nearly the same but with one essential difference: it has no `location` prop. There the only location that is available comes from the routing context. And therefore you cannot implement route transition at all.

**Comment by jymbob** [comment]
@MeiKatz I understand that's true as of now. Would your PR bring back this ability, or have I misunderstood?

**Comment by MeiKatz** [comment]
@jymbob Definitely! `<Routes />` uses the hook ´useRoutes()` internally. If we add the `location` prop to `useRoutes()` and `<Routes />` we could change the location that all routes below are matched against.

The only reason why this does not work, is that @ryanflorence and @mjackson are currently working on their [main project](https://remix.run) and have no time for RR. Actually, that is kind of a really bad situation right now.

**Comment by meenaaaa** [comment]
I'm running into the [same issue](https://stackoverflow.com/q/65639437/10841085), thank you for addressing it @MeiKatz. I hope your fix is merged soon.

**Comment by MeiKatz** [comment]
@meenaaaa I hope so, I hope so. If there is no fix until end of 2021 we should think about a fork of RR.

**Comment by AdrienLemaire** [comment]
Looking forward to seeing you champion the fork @MeiKatz <3

**Comment by MeiKatz** [comment]
> @MeiKatz if I may ask, it's May of 2021, what are you using for animated route switching now?
> Is the easiest way to do this via patch-package on #7298 ? (But that PR once again has merge conflicts)
> 
> +1 for a new fork btw. 

I have not switched to V6 yet. And this issue is one of the reasons why.
