### ISSUE TITLE
[V6] useRoutes not exported from react-router(-dom)

### ISSUE THREAD

**Issue by aress31** [ReactTraining/react-router#7299]
I followed the example provided on: https://reacttraining.com/blog/react-router-v6-pre/

But it seems that the hook `useRoutes` is not exported from neither `react-router` nor `react-router-dom`.

I am using the following version of `react-router-dom`:
    `"react-router-dom": "^6.0.0-alpha.3",`

The following list shows the methods exported from `react-router-dom`:
```
export {
    generatePath,
    Prompt,
    MemoryRouter,
    RedirectProps,
    Redirect,
    RouteChildrenProps,
    RouteComponentProps,
    RouteProps,
    Route,
    Router,
    StaticRouter,
    SwitchProps,
    Switch,
    match,
    matchPath,
    withRouter,
    RouterChildContext,
    useHistory,
    useLocation,
    useParams,
    useRouteMatch,
} from 'react-router';
```

Am I missing something?

**Comment by timdorr** [comment]
That is the wrong version of react-router-dom. You also have `Switch` instead of `Routes`. I would try deleting your node_modules folder and reinstalling.
