### ISSUE TITLE
Full-app re-render

### ISSUE THREAD

**Issue by aress31** [ReactTraining/react-router#7300]
## Version

- "react-router": "^6.0.0-alpha.3"
- "react-router-dom": "^6.0.0-alpha.3",

**Please replace this sentence with the React Router version that you are using.**

## Steps to reproduce
```
export default () => {
  return (
    <Root scheme={scheme} theme={muiTheme}>
      <Header />
      <Sidebar />
      <Content>
        <React.Suspense fallback={<Loader />}>
          <BrowserRouter>
            <Routes>
              {routes.map((route) => (
                <Route
                  key={uid(route)}
                  element={<route.component />}
                  path={route.path}
                />
              ))}
            </Routes>
          </BrowserRouter>
        </React.Suspense>
      </Content>
      <Footer />
    </Root>
  );
};
```

## Expected Behavior
On my application, I have a set layout, Header, Sidebar, Footer and Content . Obviously most of the UI does not change, namely, the Header, Sidebar, Footer, the only layout part that changes according to the routes is my Content. However, when I go from route A to route B, the entire application gets re-render, this is absolutely not the expected behaviour.

## Actual Behavior
The question (bug?) here is how to not cause the entire application to re-render but only the section within the Content? I am not sure if it is possible on a location change to not trigger an application re-render, maybe with some client-side routing?

**Comment by MeiKatz** [comment]
When it is a bug, then it is not a bug of RR. RR only takes control of everything below the `<BrowserRouter />` component.

**Comment by aress31** [comment]
@MeiKatz the issue happen in the root application component below the `<BrowserRouter>` component, changing the route should not trigger the entire application to re-render, am I wrong?

**Comment by MeiKatz** [comment]
@aress31 You're right, it shouldn't, but the way React works there is nothing RR could do to cause such behaviour.

**Comment by aress31** [comment]
So this is the expected behaviour and can't be fixed, am I getting this right?

**Comment by MeiKatz** [comment]
@aress31 There might be a solution but I think RR is the wrong location for it.

**Comment by timdorr** [comment]
@MeiKatz is correct. React Router isn't causing this.
