### ISSUE TITLE
Route Element for / is not shown inside Layout

### ISSUE THREAD

**Issue by DennisBB** [ReactTraining/react-router#7301]
## Version

6.0.0-alpha.3
## Steps to reproduce

`<Routes>
<Route path="/" element={<Layout />}>
<Route path="/" element={<Home />} />
<Route path="about" element={<About />} />
</Route>
</Routes>`

Upon visiting `/` `<Home />` is never shown

## Expected Behavior

`<Routes>
<Route path="/dashboard" element={<Layout />}>
<Route path="/" element={<Home />} />
<Route path="about" element={<About />} />
</Route>
</Routes>`

Where is in this example, upon visiting `/dashboard` `<Home />` is shown correctly

**Comment by timdorr** [comment]
Routes only matches one Route underneath it. You should put both your Home and Dashboard components under one Route if you want both displayed.

**Comment by DennisBB** [comment]
ok. So I was misunderstood completely. I'll try explaining one more time, before creating a test case.

> Nested routes may use path="/" to indicate they should render at the path of the parent component.

In the second example, the Home element will be correctly displayed for '/dashboard' path (the expected behavior).

But, if the parent element has "/" path, the home element will not be shown (that's the bug).

Changing "/" to anything else, will make the Home element display correctly again.

**Comment by DennisBB** [comment]
@timdorr do you see the issue?

**Comment by timdorr** [comment]
Sorry, you didn't have triple backtick code blocks, so I couldn't see that it was nested.

You're looking to have a common layout? I would either move the Layout component out of the render tree, as you don't need it to be part of the routing. Otherwise, I would either use a wildcard route for the Layout route, or use a Navigate to send the root URL to the "default" route.

**Comment by DennisBB** [comment]
The issue has been fixed in 6.0.0-alpha.4
