### ISSUE TITLE
Can not able to access the location state when open link in a new tab (target="_blank")

### ISSUE THREAD

**Issue by adityashrivastwa** [ReactTraining/react-router#7303]
I am using React router version `"react-router-dom": "^5.1.2"`. I am not able to access the location state when try to open the link with "open link a new tab" or target="_blank".

Here is my code:
  `<Link target="_blank" to={{
     pathname="/page"
     state= {
       referrer: 12
      }
}}  rel='noopener noreferrer' >Page</Link> `
In the Page Component 
function Page(props) {
const {referrer} = props.location.state;
console.log(referrer);
return(
<p>Page Component</p>
);
}

When I am not using target="_blank", it works fine as a normal link and able to get the location state.

**Comment by jackyleehong** [comment]
The issue is still there
