### ISSUE TITLE
Use MemoryRouter within BrowserRouter not working

### ISSUE THREAD

**Issue by vickylance** [ReactTraining/react-router#7305]
I have a use case where we want most of the routes to use MemoryRouter and some of the Routes to use BrowserRouter. But currently its not possible because of the limitation in react-router.

## Version

V.5.1.2

## Steps to reproduce

1. Use BrowserRouter and then inside it wrap with MemoryRouter and use Switch inside it.
2. Define routes inside MemoryRouter and Define routes outside of MemoryRouter but inside of BrowserRouter for routes that should use MemoryRouter and BrowseRouter respectively.
3. Try to navigate between pages using BrowserRouter and MemoryRouter interchangably, it doesnt work

## Expected Behavior

1. Routes defined within the BrowserRouter should work with BrowserRouter and Routes defined within MemoryRouter should work with MemoryRouter.

## Actual Behavior

1. The Route does not happen

**Comment by timdorr** [comment]
Can you add a codesandbox.io example of this? I'd need to see what's going on with some code.
