### ISSUE TITLE
[v6.0.0-alpha.4] useSearchParams type

### ISSUE THREAD

**Issue by bokelley** [ReactTraining/react-router#7311]
## Version

v6.0.0-alpha.4

## Test Case

This is the same error I got in my code, replicated with `search-params-test.ts` in the `react-router-dom`.

Produces the following error (with strict typescript compilation on):
```
   __tests__/search-params-test.ts:16:30 - error TS2339: Property 'get' does not exist on type 'URLSearchParams | ((nextInit: any, navigateOpts: any) => void)'.
      Property 'get' does not exist on type '(nextInit: any, navigateOpts: any) => void'.

    16     let query = searchParams.get('q');
                                    ~~~
```
This also impacts the other side of the array:
```
 18     function handleSubmit(event) {
                                 ~~~~~
    __tests__/search-params-test.ts:20:7 - error TS2349: This expression is not callable.
      Not all constituents of type 'URLSearchParams | ((nextInit: any, navigateOpts: any) => void)' are callable.
        Type 'URLSearchParams' has no call signatures.
```

## Expected Behavior

Should return `[URLSearchParams, ((nextInit: any, navigateOpts: any) => void)]`

## Actual Behavior

Returns `URLSearchParams | ((nextInit: any, navigateOpts: any) => void)`

## Suggestion

This seems to fix the issue in the test:

```
-export function useSearchParams(defaultInit: URLSearchParamsInit) {
+export function useSearchParams(defaultInit: URLSearchParamsInit): [URLSearchParams, (nextInit: URLSearchParamsInit, navigateOpts?: any) => void] {

```

I suggest 1) switching tests over to typescript via `ts-jest` (either in `checkJs` mode or by actually moving the tests to be `.tsx`. 2) In general, explicitly casting return values for any exported functions, so the interface with the outside world is explicit and not left to the compiler's interpretation.

**Comment by timdorr** [comment]
This is fixed in #7309 and will be in the next release.
