### ISSUE TITLE
Hash appended automatically if entered wrong URL

### ISSUE THREAD

**Issue by Harshmakadia** [ReactTraining/react-router#7312]
## Version
**4.1.1**

## Test Case

https://un8xu.csb.app/#/

## Steps to reproduce
- Open https://un8xu.csb.app/#/  (which is hash router)
- Load https://un8xu.csb.app/pop (which is kind of browser router is dummy and fake)
It redirects to https://un8xu.csb.app/sample#/ so I'm unable to load the 404 route instead

How to redirect any wrong URL to 404 page
Like redirect https://un8xu.csb.app/pop to https://un8xu.csb.app/404 and not https://un8xu.csb.app/pop#/

How to redirect any wrong route to 404 page it is not possible currently

## Expected Behavior

- 404 route should be loaded, Hash should not be appended automatically if entered wrong URL

**Comment by timdorr** [comment]
You're using a HashRouter. This is expected behavior.
