### ISSUE TITLE
[v6] `basename` being moved from `Router` to `Routes` isn't documented in migration guide

### ISSUE THREAD

**Issue by Vivalldi** [ReactTraining/react-router#7313]
## Version

**6.0.0-alpha.4**

The `basename` prop found in `BrowserRouter`, `HashRouter`, and `StaticRouter` has been moved to the new `Routes` component. The [migration guide](https://github.com/ReactTraining/react-router/blob/dev/docs/advanced-guides/migrating-5-to-6.md) doesn't mention this change.

Are there any other known `Router` props that were moved to the `Routes` component?

Where in the migration doc should this be noted?

**Comment by timdorr** [comment]
v6 isn't complete, so the docs aren't considered complete either. If you want to make a PR to fix this, it would be appreciated.
