### ISSUE TITLE
Allow `element` in `useRoutes` to be a function

### ISSUE THREAD

**Issue by larsbs** [ReactTraining/react-router#7314]
This is more a suggestion than a question.

What would be the downsides of allowing `element` in `useRoutes` to be a function apart from a React element?

I have something like this in mind:

```ts
useRoutes([{
  path: '/',
  element: (context: RouterContext) => <Home />,
}]);
```

## Why am I asking this?

Because I'm trying to create some kind of "guarding" system that would verify if everything's correct before rendering the route and, using a function, we could take advantage of React `<Suspense />` element doing the following:

```ts
useRoutes([{
  path: '/',
  element: (context: RouterContext) => {
    const isOkToRender = // use a Suspense ready wrapped promise
    return <Home isOkToRender={isOkToRender} />
  },
}]);
```
And in the route component itself:

```ts
const Home = ({ isOkToRender }: any) => {
  if (!isOkToRender.read()) {
    return 'You shouldn't be here!';
  }

  return;  // Render component normally
};
```

## Example

An example codesandbox showing the process can be found here: https://codesandbox.io/s/gifted-tesla-iruyt?file=/src/App.tsx

**Comment by timdorr** [comment]
This would end up making the logic more complex around routing, and isn't really needed. Just wrap around your element with one that will conditionally render its children:
```js
{ path: '/', element: <CheckAuth><Home /></CheckAuth> }
```
Or you can wrap that `isOKToRender` logic in a hook you can use from within your components.

**Comment by larsbs** [comment]
If you follow that approach, you can't have asynchronous validation and take advantage of having a `Suspense` element handling the fallback. 

Also, you start validation as soon as you make the transition. That way, when you finish rendering the UI, the validation could has already been finished and you don't have to wait.

So again, it's a really small API change and opens alternatives that are just not possible right now or suboptimal.
