### ISSUE TITLE
[feature request] Smarter goBack

### ISSUE THREAD

**Issue by JanKaifer** [ReactTraining/react-router#7316]
I use goBack for navigation inside my app.
But when someone lands on my webpage trough a link (from Google, qr code etc.) It will navigate out of my app, which is undesirable.

It seems that you can workaround this by adding something to the location state (but that doesn't feel right and bit hackish).

This feature was implemented in previous versions #408.

**Comment by timdorr** [comment]
History is split into its own repo: https://github.com/ReactTraining/history You should ask this there, as that's where we get the API from.
