### ISSUE TITLE
[v6] feature suggestion: allow to use named parametres in `<Routes>` `basename` prop

### ISSUE THREAD

**Issue by dan-maximov** [ReactTraining/react-router#7317]
Sometimes you need to have slug in the start of the link and it was hard to work with it in react-router `<=v5`. So if `v6` is for nested routes user expirience impovement, there is a feature suggestion: allow to use params in `<Routes>` `basename` prop.

So if we have code that looks like this:
```jsx
const Home = () => (
  <div>
    <span>home</span>
    <Link to="info">go to info</Link>
  </div>
);

const App = () => (
  <BrowserRouter>
    <Routes basename=":slug">
      <Route path="/" element={<Home />} />
      <Route path="info" element={<span>info</span>} />
    </Routes>
  </BrowserRouter>
);
```

I suggest, that if you visit `/ReactTraining/home` and `/react-router/home`, in both cases you will see home text and go to info link, and that link will point to `/ReactTraining/info`, or `/react-router/info` based on your position now.

**Comment by dan-maximov** [comment]
It will simplify work with `Link`s. Now we have to create a component like this:
```jsx
const LinkWithPefix = ({ to, ...props }) => {
  const { slug } = useParams<{ slug: string }>();
  return <Link to={`/${slug}/${to}`} />
}
```

**Comment by MeiKatz** [comment]
Honestly, if you want to do something like this you can do the following:
```jsx
const App = () => (
  <BrowserRouter>
    <Routes>
      <Route path=":slug">
        <Route path="/" element={<Home />} />
        <Route path="info" element={<span>info</span>} />
      </Route>
    </Routes>
  </BrowserRouter>
);
```
But I get your point and this is reason why I opened an [issue](https://github.com/ReactTraining/react-router/issues/7331) today.

**Comment by timdorr** [comment]
Exactly. There are already ways to handle this. The basename should be a static string.
