### ISSUE TITLE
useParams hook returning new objects every time its called

### ISSUE THREAD

**Issue by csantos1113** [ReactTraining/react-router#7318]
## Version

react-router-dom: `5.1.2` (also happening on `6.0.0-alpha.4`)

## Test Case

https://codesandbox.io/s/useparams-v0yd2?file=/example.js

## Steps to reproduce

1. Open console panel to see the "analytic calls" on page load (handled by `useAnalyticsPageLoad`)
2. Click any of the main links
3. Click on "Sort results desc" button
4. Click on "Sort results asc" button

## Expected Behavior
useEffect inside **`useAnalyticsPageLoad`** should be called only when its dependencies has changed (`pathname` or `params`).
It should not be fired, if you only change `search` within the same page.

Meaning: fire it **only** when clicking on "Netflix", "Zillow Group" or "No params" links.

## Actual Behavior
useEffect inside **`useAnalyticsPageLoad`** is called every time.

![2020-05-07 11 46 21](https://user-images.githubusercontent.com/9648559/81315564-73a5f800-9058-11ea-9d87-3bf1b21e2a29.gif)

**Comment by timdorr** [comment]
You shouldn't depend on the whole params object. Instead, depend on a specific param (such as `params.id`).

**Comment by janusch** [comment]
@timdorr Could you elaborate a bit. I am using react-router-dom@6 and experience the same problem.

using `useParams()`:

```
const { id, processId } = useParams();
const parsedIdParam = parseInt(id);
...
````

When I enable `why-did-you-render` to check what is up I get the following warning:

```
{Component: ƒ} "Re-rendered because of hook changes:"
 [hook useContext result]
   different objects that are equal by value.
```

I am not using useContext, this must be coming from useParams.
What would be a better way to use `useParams()` hook preventing to re-render when the params have not changed?

Thank you in advance for clearing that up for me!

**Comment by gdelmas** [comment]
@timdorr when you say
> Instead, depend on a specific param (such as params.id)" 

i assume you mean to access or de-structure it like
```
const { id } = useParams();
```

still if the value or identity of `id` does not change, but the one of the object returned by `useParams` the component will re-render. i guess this comes down to that components re-render when the return value of a hook changes, specifically when used in `deps`.

therefore we would need to either provide the param we are interested in as an argument or `useParams` internally might need to keep a reference to the returned object and only change there is a change.

**Comment by timdorr** [comment]
In your analytics hook, your dependency on `params` should be on `params.id`.

**Comment by LoayH98** [comment]
> @timdorr Could you elaborate a bit. I am using react-router-dom@6 and experience the same problem.
> 
> using `useParams()`:
> 
> ```
> const { id, processId } = useParams();
> const parsedIdParam = parseInt(id);
> ...
> ```
> 
> When I enable `why-did-you-render` to check what is up I get the following warning:
> 
> ```
> {Component: ƒ} "Re-rendered because of hook changes:"
>  [hook useContext result]
>    different objects that are equal by value.
> ```
> 
> I am not using useContext, this must be coming from useParams.
> What would be a better way to use `useParams()` hook preventing to re-render when the params have not changed?
> 
> Thank you in advance for clearing that up for me!

did you found a solution for it?

**Comment by ajberasategui** [comment]
Experiencing same issue here.

**Comment by ViktorReib** [comment]
I have the same error, do not quite understand how this can be?

**Comment by JacobCutshall** [comment]
Any update? I am having the same issue

**Comment by sarit-sotangkur-infinitusai** [comment]
@timdorr I believe there is a misunderstanding of the issue here. The RouterContext's value is not memoized like the other contexts used by react-router (e.g. [NavigationContext](https://github.com/remix-run/react-router/blob/main/packages/react-router/lib/components.tsx#L430) , [LocationContext](https://github.com/remix-run/react-router/blob/main/packages/react-router/lib/components.tsx#L455) ). When the code that creates the RouterContext runs it will always trigger `useParams` to run because the RouterContext value is referentially inequal even when the values inside are exactly the same. This is what @janusch was referring to above when talking about the `why-did-you-render` debugging tool.

The issue is that the code that uses `useParams` reruns unnecessarily. This has nothing to do with what value is being accessed or dereferenced from useParams, it's already too late, the hook has already triggered the rerender.

**Comment by apeiniger** [comment]
I'm still experiencing this in the newest react router version. Any workarounds how to solve this better?
