### ISSUE TITLE
[V6] useSearchParams returns an empty object

### ISSUE THREAD

**Issue by john-pc** [ReactTraining/react-router#7319]
## Version

Version 6.0.0-alpha.4

## Test Case

https://codesandbox.io/s/react-router-1qjhd?file=/index.js

## Steps to reproduce

just use the useSearchParams hook

## Expected Behavior

return an object of searchParams at the first element of the returned list

## Actual Behavior

the searchParams object is always an empty object

**Comment by timdorr** [comment]
It is a `URLSearchParams` object. You need to use its API to access the data inside: https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams
