### ISSUE TITLE
[v6] feature suggestion: `validate` prop for routes

### ISSUE THREAD

**Issue by MeiKatz** [ReactTraining/react-router#7323]
I think there was this idea in v5 to add a `validate` prop on `<Route />` components. There somebody could add a function that is evaluated in a `<Switch />` (`<Routes />` component in v6) and will decide if this route is routable in the current context or not. E. g. a useful context would be validation of props before routing or pages that are accesable only under special conditions like admin pages:

```jsx
<Routes>
  <Route
    path="/admin"
    validate={() => isAdmin(user)}
    element={<AdminPage />}
  />
  <Route
    path=""
    element={<ErrorPage />}
  />
</Routes>
```
or
```jsx
<Routes>
  <Route
    path="/users/:user_id"
    validate={(props) => Number.isInteger(props.user_id)}
    element={<UserPage />}
  />
</Routes>
```

btw: this would be a small addition in `matchRouteBranch()` only

**Comment by NicholasBertazzon** [comment]
Actually, I think this could be implemented inside the preload prop, since it's called before rendering, a true/false value retured by the function could be the pass for react-router to decide if it should or not render the route
