### ISSUE TITLE
feature-suggestion: accept function in the `when` prop of the Prompt component

### ISSUE THREAD

**Issue by ntocampos** [ReactTraining/react-router#7330]
My suggestion is to accept a function for the  `when` prop of the  `Prompt` component. This function would receive the `location` object as an argument.

With that, we would have the power to define more selective prompt conditions. For example, we could use the location’s state to force the redirection to a route, skipping the prompt on some occasions, with something like

```js
history.push('/some-route', { force: true })
// and for the prompt, on a far far component
<Prompt
  when={({ state }) => !state?.force && someOtherCondition}
  message="Are you sure?"
/>
```

Another use case is whitelisting some routes in a prompt. “If the user is trying to go to this specific path, this prompt shouldn’t be triggered.”

I understand that, ideally, you would have control of the prompt condition, but sometimes the `<Prompt />` component and the other component trying to skip the verification are too far apart in the React DOM tree. Well, sometimes they’re even sibling DOM nodes, making the creation of a state for the common parent a bit of an overkill.

The solution would be simple enough, and would only touch the `Prompt` API, with the changes being fully backward compatible.

I can implement it, I think, but first I’d like to know if you all think this is a good idea or if there’s any underlying complexity I’m overlooking. Thanks!

**Comment by timdorr** [comment]
Just use the useLocation hook to get access to the state and do the logic in that anonymous function directly.
