### ISSUE TITLE
[v6] discussion: isn't <Routes> quite the same as <Route>?

### ISSUE THREAD

**Issue by MeiKatz** [ReactTraining/react-router#7331]
Hi, I thought about this for quite a while and it seems to me that `<Routes />` is nearly the same as `<Route />`.

Why? Let's take the example from the [blog entry](https://reacttraining.com/blog/react-router-v6-pre/#nested-routes-and-layouts#nested-routes-and-layouts) (I added the `basename` prop):
```jsx
function App() {
  return (
    <BrowserRouter>
      <Routes basename="rrv6">
        <Route path="/" element={<Home />} />
        <Route path="users" element={<Users />}>
          <Route path="/" element={<UsersIndex />} />
          <Route path=":id" element={<UserProfile />} />
          <Route path="me" element={<OwnUserProfile />} />
        </Route>
      </Routes>
    </BrowserRouter>
  );
}
```
Here the routes inside of `<Route path="users" />` would also be ranked. The same as in `<Routes />`, just with the simple difference, that we don't define a `path` or `element` for `<Routes />`. But in `<Routes />` we have the prop `basename`. A basename in the root is IMHO the same as a parent path of a `<Route />`. So the only big change would be, that the `element` prop for `<Route />` components would be optional (what is currently the case!).

So the changed api would be:
```jsx
function App() {
  return (
    <BrowserRouter>
      <Route path="rrv6">
        <Route path="/" element={<Home />} />
        <Route path="users" element={<Users />}>
          <Route path="/" element={<UsersIndex />} />
          <Route path=":id" element={<UserProfile />} />
          <Route path="me" element={<OwnUserProfile />} />
        </Route>
      </Route>
    </BrowserRouter>
  );
}
```
Any arguments against my point?

**Comment by timdorr** [comment]
Routes and Route are quite different. Route doesn't do anything without a Routes wrapping it directly. 

The naming might be a bit confusing, but I wouldn't try to combine the two together. A component that functions drastically differently when provided different props is going to be a recipe for lots of user errors.

**Comment by MeiKatz** [comment]
@timdorr Maybe we should drop the `basename` support for `<Routes />` in favour of `<Route path />`? It isn't clear when to use which.

**Comment by timdorr** [comment]
`basename` is distinctly different from `path`, though. One supports dynamic route segments, the other doesn't. I don't think re-using the same name is a good idea, as it's likely to cause confusion as to why there are differences in functionality.

**Comment by MeiKatz** [comment]
@timdorr I get your point but I think that `basename` is just a simpler version of `path`. So my latest intention was to fully drop the support for `basename` on `<Routes />` and only support the `path` prop on `<Route />` components. In RRv5 there was no `basename` prop for `<Switch />` components either.

So my idea would reduce confusion about when to use `basename` on `<Routes />` or `path` on `<Route />`.
