### ISSUE TITLE
`useTransition` is not exported by React.

### ISSUE THREAD

**Issue by ashubham** [ReactTraining/react-router#7334]
## Version

6.0.0-alpha.4

**Please replace this sentence with the React Router version that you are using.**

Please release a new alpha with the `useTransition` removed. The built `react-router` downloaded from `npm` after a install, has a hard dependency on `useTransition` in the imports.

**Comment by timdorr** [comment]
This was already fixed in 89b7280404ff5726f4f33480122a708cfc379a7f. It will be in the next release.
