### ISSUE TITLE
[v6] Navigate to external site does not work as expected

### ISSUE THREAD

**Issue by Ethan-Arrowood** [ReactTraining/react-router#7341]
## Version

"^6.0.0-alpha.4"

## Test Case

Using the new v6 types I've declared a route that navigates to auth0:

```
<Route path="/login" element={<Navigate to={`https://${process.env.auth0_domain}/authorize`} replace />} />
```

When I then go the `/login` route, my page changes the route to: `http://localhost:1234/login/https:/ethan-arrowood.auth0.com/authorize` instead of actually redirecting to the external page.

## Expected Behavior

Maybe I'm using the API wrong, if so this should be included in the documentation.

**Comment by MeiKatz** [comment]
Currently RRv6 supports relative and absolute paths under the same domain only. Not sure if this is wanted. But it would be easy to add support for redirects to other domains (starting either with `http://`, `https://`, or `//`).

**Comment by timdorr** [comment]
All of React Router's components that navigate are for routing within the same page. This library doesn't deal with external navigation.
