### ISSUE TITLE
if no path is given to <Route> then componentDidMount in the component render on every state change

### ISSUE THREAD

**Issue by shivasai09** [ReactTraining/react-router#7344]
## Version

**4.3.1**

## Test Case

https://codesandbox.io/s/strange-kilby-3i73k?file=/src/App.js

## Steps to reproduce
1.open console in above url
2. click on button `render modal in Route` button
3.click on `Open modal` button
4. click on `Close modal` button in the modal

## Expected Behavior
when we do the above repro steps 2,3,4 then the message in the component did mount prints 3 time

## Actual Behavior

the message in the component did mount should print only one time

**Comment by timdorr** [comment]
Your component is an anonymous function that gets recreated on every render. React is (correctly) re-rendering it because it's a new instance every time.
