### ISSUE TITLE
Gotcha: Redirect can break Route

### ISSUE THREAD

**Issue by dimaqq** [ReactTraining/react-router#7347]
Suppose I want to display a user table at `/users/` and if someone lands in my spa without the trailing slash, I want to automatically add it.
(additionally there are pages like `/users/alexa.siri/profile/`)

This works:
```jsx
const Router = (props) => <Switch props={props}>
  <Route path="/users/" component={ListUsers}/>
</Switch>;
```

This doesn't work (redirect works, but component is never displayed):
```jsx
const Router = (props) => <Switch props={props}>
  <Redirect exact from="/users" to="/users/"/>
  <Route path="/users/" component={ListUsers}/>
</Switch>;
```

And this works again:
```jsx
const Router = (props) => <Switch props={props}>
  <Redirect exact strict from="/users" to="/users/"/>
  <Route path="/users/" component={ListUsers}/>
</Switch>;
```

I'm sure I just had to read the docs more carefully, but it seems it's the 3rd time I'm bitten by this in a year, because I recall having to add `strict` before 😭 

I'm not sure what's best technically, but please save us poor devs from such dev UX 🙏

**Comment by timdorr** [comment]
Feel free to open up a PR to add something about this to the docs.

**Comment by timdorr** [comment]
This is basically the same as #4841
