### ISSUE TITLE
[v6-alpha.5] Are there any plans for props.history alternatives?

### ISSUE THREAD

**Issue by numb86** [ReactTraining/react-router#7350]
This is feedback to v6.

`props.history` of `Route` removed in v6.0.0-alpha.5.
But this feature is used in the test of history. (e.g.  `history.location.pathname`, `history.location.state`)
https://reacttraining.com/react-router/web/guides/testing/checking-location-in-tests

Are there any plans for `props.history` alternatives?

**Comment by MeiKatz** [comment]
Just use `useHistory` or `useLocation` and you're done.
```jsx
test("clicking filter links updates product query params", () => {
  let history, location;

  function TestComponent() {
    location = useLocation();
    history = useHistory();
    return null;
  }
  
  render(
    <MemoryRouter initialEntries={["/my/initial/route"]}>
      <App />
      <Route path="*" element={<TestComponent />} />
    </MemoryRouter>,
    node
  );

  act(() => {
    // example: click a <Link> to /products?id=1234
  });

  // assert about url
  expect(location.pathname).toBe("/products");
  const searchParams = new URLSearchParams(location.search);
  expect(searchParams.has("id")).toBe(true);
  expect(searchParams.get("id")).toEqual("1234");
});
```

**Comment by numb86** [comment]
Oh, that is a simple way! I didn't notice...

`useHistory` is not yet available in v6, but I can use `useLocation` instead of it.

Thanks!

**Comment by MeiKatz** [comment]
@numb86 My bad: `useHistory` will not ship with v6. There is no need to test the `history` object, because you can access it's props via `useLocation` and `useParams`, and navigate via `useNavigate`.

**Comment by numb86** [comment]
I understood. Thank you for your polite advice!
