### ISSUE TITLE
advance recipes section

### ISSUE THREAD

**Issue by baltsevicha** [ReactTraining/react-router#7352]
Hello, i'm a big fan of react-router and often do some advanced tricks with it. The most of frontend teams do not use even half the possibilities of react-router. I've started some small project for sharing knowledge in Russian community and i've translated it to English too.

For example i've created [video](https://youtu.be/RYo3kwdDdBI), [github](https://github.com/Sin9k/react-router-dom-tricks#popups-routes) and [demo](https://sin9k.com/popups-routes/posts) site with the name "Managing pop-ups using react-router" or the same for "Perfect multi-step form is it real!" ([demo](https://sin9k.com/stepper), [github](https://github.com/Sin9k/react-router-dom-tricks#perfect-multistep-form), [video](https://youtu.be/-j8s0RNOZ8U)). [Whole playlist](https://www.youtube.com/playlist?list=PL5ZjqPd3zeFBG5_GadUuhL3zfTgnQ7--j) (and [RU](https://www.youtube.com/playlist?list=PLz_dGYmQRrr-HEb1I-yfLru28HO2PrdwI))

I suggest you to create some new section in your documentation with advanced recipes. And i can help you to create new videos if you have some other ideas for advanced example in two languages (EN, RU)

What do you think about it?

**Comment by timdorr** [comment]
Thanks for the interest. React Training maintains the library officially, so there might be a conflict of interest there. Plus, it wouldn't be possible for the broader community to contribute or update those videos over time, as would be the case with documentation. 

If you want to put together a docs PR, that would be the best format to look over these kinds of things. Thanks!
