### ISSUE TITLE
[v6] setParams from useSearchParams ignores current location

### ISSUE THREAD

**Issue by d3dc** [ReactTraining/react-router#7353]
## Version

6.0.0-alpha.5

## Test Case

https://codesandbox.io/s/react-router-1w91e

## Steps to reproduce

call setParams() in a Container with an outlet.

## Expected Behavior
search params are appended to the current path

## Actual Behavior
search params replace the current path.

I assume this is because "*" doesn't actually pop any route segments - I'm struggling to find v5 docs that warn about this however.

**Comment by vjpr** [comment]
I am seeing this issue too. Pretty sure it is a bug...

**Comment by clarkbynum** [comment]
@mjackson @ryanflorence can we reopen this issue?

**Comment by renatobenks** [comment]
cc @timdorr

**Comment by kombuchafox** [comment]
I'm also seeing this unfortunately

**Comment by kombuchafox** [comment]
So the work around is just doing     
```
const location = useLocation();
...
navigate({
      pathname: location.pathname,
      search: "?" + createSearchParams({ ...newParams }),
    });
```
The issue is that `useSearchParams` tries to navigate to the parent path (?) which breaks children paths
https://github.com/ReactTraining/react-router/blob/dev/packages/react-router-dom/index.tsx#L418

**Comment by chandlervdw** [comment]
+1 for reopening this. `useSearchParams` does not take into consideration the current location. @mjackson @ryanflorence
