### ISSUE TITLE
 Invalid type element error

### ISSUE THREAD

**Issue by mrcarlao** [ReactTraining/react-router#7355]
Could you help me with this error?

Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `MaterialTopTabView`.

This error is located at:
    in MaterialTopTabView (at createMaterialTopTabNavigator.tsx:41)
    in MaterialTopTabNavigator (at Routes.js:13)
    in TaskTab (at SceneView.tsx:98)
    in StaticContainer
    in StaticContainer (at SceneView.tsx:89)
    in EnsureSingleNavigator (at SceneView.tsx:88)
    in SceneView (at useDescriptors.tsx:125)
    in RCTView (at CardContainer.tsx:199)
    in RCTView (at CardContainer.tsx:198)
    in RCTView (at CardSheet.tsx:33)
    in ForwardRef(CardSheet) (at Card.tsx:526)
    in RCTView (at createAnimatedComponent.js:144)
    in AnimatedComponent (at createAnimatedComponent.js:194)
    in ForwardRef(AnimatedComponentWrapper) (at Card.tsx:508)
    in PanGestureHandler (at GestureHandler.native.tsx:13)
    in PanGestureHandler (at Card.tsx:502)
    in RCTView (at createAnimatedComponent.js:144)
    in AnimatedComponent (at createAnimatedComponent.js:194)
    in ForwardRef(AnimatedComponentWrapper) (at Card.tsx:498)
    in RCTView (at Card.tsx:492)
    in Card (at CardContainer.tsx:164)
    in CardContainer (at CardStack.tsx:497)
    in RCTView (at Screens.tsx:70)
    in MaybeScreen (at CardStack.tsx:490)
    in RCTView (at Screens.tsx:48)
    in MaybeScreenContainer (at CardStack.tsx:388)
    in CardStack (at StackView.tsx:433)
    in KeyboardManager (at StackView.tsx:431)
    in SafeAreaConsumer (at StackView.tsx:429)
    in RNCSafeAreaView (at SafeAreaContext.tsx:50)
    in SafeAreaProvider (at SafeAreaProviderCompat.tsx:42)
    in SafeAreaConsumer (at SafeAreaProviderCompat.tsx:32)
    in SafeAreaProviderCompat (at StackView.tsx:428)
    in RCTView (at StackView.tsx:427)
    in StackView (at createStackNavigator.tsx:82)
    in StackNavigator (at Routes.js:27)
    in Routes (at ToDoManeger/index.js:16)
    in RCTSafeAreaView (at SafeAreaView.js:51)
    in ForwardRef(SafeAreaView) (at ToDoManeger/index.js:15)
    in EnsureSingleNavigator (at BaseNavigationContainer.tsx:288)
    in ForwardRef(BaseNavigationContainer) (at NavigationContainer.tsx:64)
    in ThemeProvider (at NavigationContainer.tsx:63)
    in ForwardRef(NavigationContainer) (at ToDoManeger/index.js:14)
    in wrappedRoutes (at renderApplication.js:45)
    in RCTView (at AppContainer.js:109)
    in RCTView (at AppContainer.js:135)
    in AppContainer (at renderApplication.js:39)

createFiberFromTypeAndProps
    ReactNativeRenderer-dev.js:23069:21
createFiberFromElement
    ReactNativeRenderer-dev.js:23096:41
reconcileSingleElement
    ReactNativeRenderer-dev.js:10103:44
reconcileChildFibers
    ReactNativeRenderer-dev.js:10188:34
reconcileChildren
    ReactNativeRenderer-dev.js:12970:43
updateContextProvider
    ReactNativeRenderer-dev.js:15387:19
invokeGuardedCallbackImpl
    ReactNativeRenderer-dev.js:286:4
invokeGuardedCallback
    ReactNativeRenderer-dev.js:497:2
beginWork$$1
    ReactNativeRenderer-dev.js:22028:27
performUnitOfWork
    ReactNativeRenderer-dev.js:20871:23
workLoopSync
    ReactNativeRenderer-dev.js:20848:38
performSyncWorkOnRoot
    ReactNativeRenderer-dev.js:20456:22
performSyncWorkOnRoot
    [native code]:0
runWithPriority$argument_1
    ReactNativeRenderer-dev.js:5703:31
unstable_runWithPriority
    scheduler.development.js:818:23
flushSyncCallbackQueueImpl
    ReactNativeRenderer-dev.js:5698:21
flushSyncCallbackQueue
    ReactNativeRenderer-dev.js:5686:28
scheduleUpdateOnFiber
    ReactNativeRenderer-dev.js:19845:30
dispatchAction
    ReactNativeRenderer-dev.js:11880:16
dispatchAction
    [native code]:0
React.useCallback$argument_0
    useSyncState.tsx:39:22
React.useCallback$argument_0
    useOnAction.tsx:87:18
dispatch
    useNavigationHelpers.tsx:42:30
dispatch
    useNavigationCache.tsx:79:10
UploadTask.prototype.on
    index.cjs.js:2397:36
tryCatch
    runtime.js:45:36
invoke
    runtime.js:274:29
tryCatch
    runtime.js:45:36
invoke
    runtime.js:135:27
PromiseImpl.resolve.then$argument_0
    runtime.js:145:18
tryCallOne
    core.js:37:13
setImmediate$argument_0
    core.js:123:24
_callTimer
    JSTimers.js:135:14
_callImmediatesPass
    JSTimers.js:183:16
callImmediates
    JSTimers.js:446:30
callImmediates
    [native code]:0
__callImmediates
    MessageQueue.js:396:6
__guard$argument_0
    MessageQueue.js:144:6
__guard
    MessageQueue.js:373:10
flushedQueue
    MessageQueue.js:143:4
flushedQueue
    [native code]:0
invokeCallbackAndReturnFlushedQueue
    [native code]:0

**Comment by mrcarlao** [comment]
This is the code

 import {createStackNavigator} from '@react-navigation/stack';
   import {App, Login, Register, ToDoTasks, DoneTasks} from '../screens/Screens';
   import {createMaterialTopTabNavigator} from '@react-navigation/material-top-tabs';
   import React from 'react';
   

   
   const Stack = createStackNavigator();
   const Tab = createMaterialTopTabNavigator();

   export const TaskTab = () => {
      return (
        <Tab.Navigator
          tabBarOptions={{
            activeTintColor: 'tomato',
            inactiveTintColor: 'gray',
            iconStyle: {width: 20, height: 20},
          }}>
          <Tab.Screen name="To Do" component={ToDoTasks} />
          <Tab.Screen name="Done" component={DoneTasks} />
        </Tab.Navigator>
      );
    };
    
const Routes = () => {
      return (
      <Stack.Navigator headerMode="screen">
         
      <Stack.Screen
      name="Login"
      component={Login}
      options={{headerShown: false}}
      />
      <Stack.Screen name="Register" component={Register}/>
      <Stack.Screen name="TaskList" component={TaskTab}/>
      </Stack.Navigator>
      );
     };

export default Routes;

**Comment by illuminist** [comment]
You posted on wrong repository.

This repo is for `react-router` but you're using `react-navigation` so go to this link https://github.com/react-navigation/react-navigation/issues.

**Comment by mrcarlao** [comment]
Thank you @illuminist  I will post in the correct repository.
