### ISSUE TITLE
[v6] "Hash" in location breaks Codesandbox routing

### ISSUE THREAD

**Issue by d3dc** [ReactTraining/react-router#7356]
## Version

6.0.0-alpha.5

## Test Case

https://codesandbox.io/s/react-router-qgkx9

## Steps to reproduce

Open link side-by-side with editor. Click topics link.

## Expected Behavior

Topics route matches.

## Actual Behavior

Route doesn't change. Reloading the app will cause Topics route to match. ~~When route is matched, URLSearchParams is empty and the hash contains the search params (including '?').~~

**Comment by MeiKatz** [comment]
That's not a bug but you took the wrong order of query and hash. In your case the query string is part of the hash:
```
// wrong
/topics#test?hello=world
```

```
// right
/topics?hello=world#test
```

**Comment by MeiKatz** [comment]
I did some tests and it seems that the search params do not change because somehow the location object does not change (in the `<Router />` and also in the `<LocationProvider />`)  when there is a hash in the url.

**Comment by MeiKatz** [comment]
@d3dc I remember that there were other cases before where CodeSandbox brook while using RR.
