### ISSUE TITLE
How to avoid routing jumps and component rerendering?

### ISSUE THREAD

**Issue by VitaminCtea** [ReactTraining/react-router#7357]
In the React function component, you route from component A to component B, and then from component B to component A, component A and component B will rerender again, the data is asynchronous! What I want is to cache the render once and then jump back and forth to the first render. How can I do that? Are there caching components like Vue's keep-alive?

## Expected Behavior
What I expect is that when jumping to the same routing component, there will be no re-rendering, keeping the first component's rendering and populated data, because the page refresh is controlled by a button!

## Actual Behavior
In practice, the component will be unloaded and loaded every time it jumps to a Route. According to the official documentation, the Route component property will be unloaded and reloaded every time. The render property will not! I understand. Any questions? The desired effect should be the same as the behavior of the Vue's keep-alive component.

**Comment by MeiKatz** [comment]
That's the way React Router works. The components will re-render when the route changes. But you could cache your data so you can access immediately when your component is re-rendered. Therefore it should not be noticeable, that there was a re-render.

**Comment by VitaminCtea** [comment]
@MeiKatz If so, should the data be stored in localStorage or sessionStorage? Are there routing cache component libraries like Vue's keep-alive?

**Comment by MeiKatz** [comment]
@VitaminCtea This depends on what you want to do: `localStorage` saves your data per website (data will be shared over many tabs), and `sessionStorage` saves your data per tab. So it's your decision.

**Comment by VitaminCtea** [comment]
@MeiKatz Does that prevent components from being re-mounted and unmounted?

**Comment by MeiKatz** [comment]
@VitaminCtea No. Re-rendering is done very quickly. What takes some time is either heavy computation or fetching data from the server. And we are talking about the last one. So you can speed up everything, if you don't re-fetch your data on every render.

**Comment by VitaminCtea** [comment]
@MeiKatz In this case, the only way to optimize is to cache the data! However, when there is a lot of data on the page, it may be difficult to store the data using session or local

**Comment by MeiKatz** [comment]
@VitaminCtea And here comes the hard part: you have to decide what's best in your case. There's a lot of options you have: Redux, MobX, localStorage, sessionStorage, ... You have to decide what fits your needs the best.

**Comment by VitaminCtea** [comment]
@MeiKatz It's too difficult! Thank you for your answer!

**Comment by krishna-saini** [comment]
hi
is that correct understanding that changing the route unmounts the current component and mounts new route comonent  ?

**Comment by sergiodxa** [comment]
> hi
> is that correct understanding that changing the route unmounts the current component and mounts new route comonent  ?

If the user goes from /posts/1 to /posts/2 and both are the same route then the component is not mounted again, the loaders (if using data or framework mode) is revalidated with the new route params from the URL and the component will re-render with the new data and route params

If the user goes from /abc to /def and those are different routes then yes, the abc route component will unmount and the def component will mount

---

Also, don't revive old threads from many years ago, it's better to open a new discussion
