### ISSUE TITLE
Existing search params are ignored when using hash router

### ISSUE THREAD

**Issue by Moeriki** [ReactTraining/react-router#7358]
## Version

5.2

## Test Case

https://github.com/Moeriki/react-router-window-location-bug

## Steps to reproduce

```
yarn install
yarn start
# separate terminal
yarn run open
```

## Expected Behavior

React Router takes the existing search param into account.

If I open the App at `http://localhost:1234/?query=value` I expect to end up at `http://localhost:1234/#/?query=value`

## Actual Behavior

I end up at `http://localhost:1234/?query=value#/` and my search param is undetected by React Router.

**Comment by timdorr** [comment]
HashRouter doesn't read in the existing location when loading up. If you go to `http://localhost:1234/test`, you'll be redirected to `http://localhost:1234/test#/` as well. You need to provide the URL inside of the hash if you want to use HashRouter. Otherwise, you should use a BrowserRouter.

**Comment by Moeriki** [comment]
Sadly we can't use BrowserRouter because of hosting restrictions.

We get a server-side redirect with a search param. I don't think the server should be aware of the technical workings of front-end routing.

The only solution we have now is reading search params that we know to be set server-side from `window.location` and other search params from `useLocation()`.

I still think this could be best handled in initialization of the Router.
