### ISSUE TITLE
useParams hook doesn't work correctly when route changes over the lifetime of the component

### ISSUE THREAD

**Issue by capaj** [ReactTraining/react-router#7360]
## Version

5.2.0

## Test Case

https://codesandbox.io/s/react-router-gh6n7

## Steps to reproduce

have a component outside of any `Switch` and call `useParams` hook inside it.

## Expected Behavior
params returned match those specified in current route, component rerenders any time the route or params change

## Actual Behavior
not sure, but it does not rerender

**Comment by timdorr** [comment]
Without any code to look at it, it's not possible to see what's going on here. However, if you change the Topic component in the test case you ignored to this, it will work fine:
```js
function Topic() {
  const params = useParams()

  return (
    <div>
      <h3>{params.topicId}!</h3>
    </div>
  )
}
```

**Comment by capaj** [comment]
oh sorry, the example was the default one. Forgot it there in a hurry. Anyway, this is by design-`useParams` must be used inside a react-route. Obviously outside of it, it doesn't know what to match the route against. I kinda thought that the currently matched params are stored on react-router provider and so that I can place the hook in any of the children of the Provider. This is not true. Thanks for closing the issue so fast.

**Comment by vijaysriramadas** [comment]
is there anyway to passit as a props
