### ISSUE TITLE
`canGo()` is not exposed

### ISSUE THREAD

**Issue by simonzack** [ReactTraining/react-router#7364]
## Version
5.2.0

## Expected Behavior
The `canGo()` method is not exposed, so there's no way to know if we can go forwards or backwards.

https://github.com/ReactTraining/react-router/issues/4178 apparently exposed it, but this is no longer exposed anymore.

**Comment by timdorr** [comment]
We have never exposed that API. If you need it, create your own history instance and use `<Router history={myHistory}>`. But be warned that it's going away in history v5.
