### ISSUE TITLE
[v6] Feature suggestion: restore scroll as prop on Route

### ISSUE THREAD

**Issue by NicholasBertazzon** [ReactTraining/react-router#7365]
Hi, I'm using v6 and it's great, I mean really great, but I was wondering, right now I'm using the new preload to do this:

```
function scrollTop(){
  window.scrollTo(0, 0);
}

<Route path="/login" element={<Login />} preload={scrollTop}/>
```
Since the scroll restoration is widely used (or at least I use it), why not add a true/false prop on the route to trigger the scroll restoration automatically?

PS: I've seen on the source code that when the preload function is called there is no await, so I still can't use a fetch to retrieve data before render right?

**Comment by aress31** [comment]
+1 for this feature!

**Comment by 6graNik** [comment]
What would not be sufficient API, because the next step would be to decide persistence of the scroll in runtime, and we will end up with prop, and a function, which is not great, keeping simple preload function will give us more flexibility without expanding API

**Comment by bogdansoare** [comment]
Any news on this?

**Comment by timdorr** [comment]
This is best handled by a third party library. There are a lot of intricacies to how scroll position can be restored, so it's a complex project that should live on its own.

**Comment by bogdansoare** [comment]
@timdorr does a third party library exist?

**Comment by timdorr** [comment]
https://github.com/ipatate/react-router-scroll-memory#readme

https://github.com/ytase/react-router-scroll

https://github.com/trevorr/react-scroll-manager

**Comment by denisvely** [comment]
+1

**Comment by grit-ki** [comment]
+1 for this feature!!!

**Comment by pzhine** [comment]
> https://github.com/ipatate/react-router-scroll-memory#readme
> 
> https://github.com/ytase/react-router-scroll
> 
> https://github.com/trevorr/react-scroll-manager

These are all for RR 4 or 5. Has anyone seen a scroll manager package working with RR v6?

**Comment by SultanNasyrovDeveloper** [comment]
+1

**Comment by brophdawg11** [comment]
We're adding [`<ScrollRestoration>`](https://beta.reactrouter.com/en/dev/components/scroll-restoration) in `6.4.0` (you can test it out on `6.4.0-pre.9`).  It's based on the Remix implementation with some minor API changes.
