### ISSUE TITLE
[v6]alpha5 isActiveClass assigned to two <NavLink>s

### ISSUE THREAD

**Issue by mustafawm** [ReactTraining/react-router#7366]
### version : 6 alpha 5

codesandbox: https://codesandbox.io/s/small-smoke-7g9uj?file=/src/App.js

Hello,
I just upgraded v6 from `alpha 4` to `5` and started seeing the below behavior:
> NavLink with `to=''` property is always active even when other NavLinks are selected

## Steps to reproduce
Click on nav items 
## Expected Behavior
One NavLink to have isActiveClass
## Actual Behavior
NavLink with `to=''` 

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/13101565/82525876-bd183c00-9b5c-11ea-8881-bc1300c13abf.gif)

**Comment by timdorr** [comment]
This is expected behavior. NavLink now matches loosely, so that if you're in a nested route (say `/users/:userId/posts/:postId/comments`) with a global navigation, the appropriate link will still be active. If you want the NavLink to be strict in matching, add the prop `end={true}`.
