### ISSUE TITLE
Link component can't have nullable value for the "to" props

### ISSUE THREAD

**Issue by thexpand** [ReactTraining/react-router#7367]
The following JSX code triggers a warning:
```
<Link to={null}>Currently disabled link</Link>
```
because it's expected that the to value is always present.
However, this is not correct, because when using simple HTML anchors in React, we can pass `null` for the `href` prop/attribute like so:
```
<a href={null}>Currently disabled link</a>
```
which is a completely valid JSX and results in a link that can't be clicked.
Note that this is different from setting the href to `#`.

I would expect that react-router's `Link` component work the same and doesn't trigger a warning for the empty `to` prop.

**Comment by timdorr** [comment]
That doesn't make much sense in the context of the Router. While they are similar, they are not intended to be exact clones. This isn't an edge case we need to address. Just fall back to a normal `<a>` if you have a null-ish location.

**Comment by thexpand** [comment]
@timdorr This isn't always the case. In my current use case, I've created a custom component, which renders react-router's Link component. I have a `isDisabled` prop on the custom component and I'm using styled components to add some styling, based on the `isDIsabled` prop. If the `isDisabled` prop is `true`, I'm re-setting the `to` from `props` to `null`, so that there is no clickable link, so it makes more sense to re-set the link instead of re-rendering a completely different component. I don't see a reason for closing this issue, don't we try to mimic as best as possible a normal HTML link, but with "enhanced" capabilities?
