### ISSUE TITLE
Support multiple Prompt

### ISSUE THREAD

**Issue by Losses** [ReactTraining/react-router#7370]
Use case:
Pop multiple models, while pressing 'back', the last model popped would be closed, every model component has its own <Prompt /> and there will be an warning called:

```
react_devtools_backend.js:6 Warning: A history supports only one prompt at a time
```

Will there be the support of multiple `<Prompt />`?

**Comment by timdorr** [comment]
Nope, that wouldn't make much sense logically. You can only set one handler for onbeforeunloar anyways.
