### ISSUE TITLE
Switch uses 'path' prop without resolving pure function component first

### ISSUE THREAD

**Issue by BTOdell** [ReactTraining/react-router#7371]
## Version

**5.2.0**

## Test Case

https://codesandbox.io/s/react-router-k9zg4?file=/index.js

## Steps to reproduce

In the link above, I'm using a pure function component `<CustomRoute>` which produces a `<Route>` with an augmented `path` prop. However, it appears the `<Switch>` component looks into the props of its children without first resolving the element into a route component: https://github.com/ReactTraining/react-router/blob/master/packages/react-router/modules/Switch.js#L31

This behavior ignores the core philosophy of React's composition-based design.

## Expected Behavior

The pure function component (or any component, really) should be fully resolved before the `path` prop is checked.

## Actual Behavior

The routing functionality completely breaks.

**Comment by timdorr** [comment]
This is expected behavior. You can actually have anything under Switch. We use these props as a config for Switch.
