### ISSUE TITLE
Route children not work in v6

### ISSUE THREAD

**Issue by Vibing** [ReactTraining/react-router#7372]
[this is demo address](https://codesandbox.io/s/charming-solomon-16zgq)

```jsx
return (
    <div className="App">
      <HashRouter>
        <Routes>
          <Route path="invoices" element={<div>1</div>}>
            <Route path=":id" element={<div>2</div>} />
            <Route path="sent" element={<div>3</div>} />
          </Route>
        </Routes>
      </HashRouter>
    </div>
  );
```
`http://xxx/#/invoices` is working, but `http://xxx/#/invoices/sent` and `http://xxx/#/invoices/23` is not work

Is there something wrong with my coding ？

**Comment by MeiKatz** [comment]
That ist not a bug. You should use the `<Outlet />` component in the parent element.
