### ISSUE TITLE
[v6] bad setState() warning in preload function

### ISSUE THREAD

**Issue by insanecoding** [ReactTraining/react-router#7374]
## Summary

I was playing around with the new `preload` function and wanted to use it with Suspense-aware fetching library like `use-async-resource`. I actually achieved my goals and it worked for me, but I had a warning in the console:
```
Warning: Cannot update a component (`App`) while rendering a different 
component (`Routes`). To locate the bad setState() call inside `Routes`, follow the stack trace as 
described in https://fb.me/setstate-in-render
```

I contacted the author but it turns out the problem is not in his library. (our conversation details: https://github.com/andreiduca/use-async-resource/issues/1)
He found an equivalent case without any fetching involved, which yields the same warning. And that's basically the thing I want to report.

So this code:
```jsx

const App = () => {
  const [categories, setCategories] = useState();

  const preloadCategories = React.useCallback(() => {
    setCategories(['one', 'two', 'three']);
  }, []);

  return (
      <Router>
        <Routes>
          {/*...*/}
          <Route
            path="categories"
            element={<Categories list={categories} />}
            preload={preloadCategories}
          />
          {/*...*/}
        </Routes>
      </Router>
  );

const Categories = ({ list }) => {
  if (list === undefined) return null;

  return (
    <ul>
      {
        list.map(item => <li key={item}>{item}</li>)
      }
    </ul>
  )
}
```
— gives the same warning.

Seems like the preload function is called synchronously with the rendering of the element, i.e. inside the render method that renders the element. But React forbids that.

## Version 

**6.0.0-alpha.5**

## Test Case

https://codesandbox.io/s/peaceful-blackburn-cfjbr?file=/src/app.js

## Steps to reproduce

1. switch to 'categories' tab
2. open the console

## Expected Behavior

No warnings in the console

## Actual Behavior

You see this warning:
```
Warning: Cannot update a component (`App`) while rendering a different component (`Routes`). To locate the bad setState() call inside `Routes`, follow the stack trace as described in https://fb.me/setstate-in-render
    in Routes (at app.js:22)
    in Router (created by BrowserRouter)
    in BrowserRouter (at app.js:17)
    in Suspense (at app.js:16)
    in App (at src/index.js:10)
    in StrictMode (at src/index.js:9)
```

**Comment by timdorr** [comment]
You shouldn't be using setState inside of a preload function. It is intended to work with a cache, not state. That is, you should call some sort of caching data fetcher that stores its cache outside of state. React actually introduced this warning to prevent this exact kind of behavior, so everything (including React) is working as intended here.
