### ISSUE TITLE
Examples missing from react-router's docs

### ISSUE THREAD

**Issue by konaraddi** [ReactTraining/react-router#7377]
[For v5.0.1 of react-router-website](https://github.com/ReactTraining/react-router/tree/21a62e55c0d6196002bd4ab5b3350514976928cf/website), there appears to be an issue with the Examples in the docs for Web and Native. The code samples under "Examples" are missing.

For example, the below is what I see when I visit https://reacttraining.com/react-router/web/example/basic 
![Screen Shot 2020-05-26 at 8 54 47 PM](https://user-images.githubusercontent.com/19355185/82964331-37005900-9f93-11ea-9d7f-b3baf4ad9133.png)

**Comment by timdorr** [comment]
Looks like Codesandbox is having an issue. @CompuIves Do you know what's up?

**Comment by willdelphia** [comment]
Is there a mirror somewhere?

**Comment by CompuIves** [comment]
Ah, I just missed this before going to bed! There was an issue with creating the sandbox on the server, due to the format of the lz-string. It happened because we updated a library. It's now fixed and I'm writing a test so it won't happen again. I'm sorry for the inconvenience!

**Comment by konaraddi** [comment]
Thank you for fixing it! (and thank you for creating codesandbox!) I'm going to close this issue.
