### ISSUE TITLE
TypeError: Cannot read property 'history' of undefined in 5.2.0 version

### ISSUE THREAD

**Issue by shubham7jain** [ReactTraining/react-router#7378]
## Version
5.2.0

## Steps to reproduce
I am getting following error while loading the app after I update the react-router-dom package from 5.1.2 to 5.2.0:

> TypeError: Cannot read property 'history' of undefined in 5.2.0 version

This is happening when I am doing bundling using webpack but I am not getting this issue when trying to run the app locally without bundling. Any idea about it?

**Comment by timdorr** [comment]
Without any code to look at, I've got to assume this is a webpack issue. If you can provide some example code, I can take a look, but there isn't enough information to know exactly what's going on here.
