### ISSUE TITLE
[v6] add location state type as a generic to useLocation hook

### ISSUE THREAD

**Issue by asterikx** [ReactTraining/react-router#7384]
I'm trying to implement the "private route" component from the [docs](https://reacttraining.com/react-router/web/example/auth-workflow) using react-router v6. Unfortunately, the `useLocation` hook does not allow the expected type of the state prop. 

```js
const location = useLocation();
const { from } = location.state || { from: { pathname: '/' } }; // Property 'from' does not exist on type '{}'.ts(2339)
```

Making the `useLocation` hook generic to account for the location's state type should fix this.

A temporary fix

```js
import { Location } from 'history';

const location = useLocation() as Location<{ from: { pathname: string } }>;
```

**Comment by timdorr** [comment]
https://github.com/ReactTraining/react-router/pull/7326#issuecomment-626418225
