### ISSUE TITLE
React-Router not issuing Error when basename deployment is wrong

### ISSUE THREAD

**Issue by ErikAGriffin** [ReactTraining/react-router#7386]
## Version

react-router-dom 5.1.2

## Test Case

The issue is when deploying the react app to a non-root path, I don't believe this can be emulated by codesandbox.

## Steps to reproduce

Add a `"homepage"` property to package.json and a `basename` prop to your `<Router>` component.  This is what directory the react app expects to be deployed under.
For example
```
<Router basename="/blog">
```

Now, if you happen to accidentally deploy to `/bloge` instead, the you get a blank white page.
However, a 200 response is returned by the request and the console gives no helpful errors, and Sentry is not catching any thrown errors.

## Expected Behavior

Some sort of error should be thrown

## Actual Behavior

Nothing is thrown.

========

I'm really looking for some understanding of what is happening when a basename is applied, and how we might have the browser report when a deployment such as this has gone wrong.  Thanks for any help

**Comment by timdorr** [comment]
It's showing a blank page because no routes match that URL structure. We can't fix this because it's what you're telling the library to do.

**Comment by ErikAGriffin** [comment]
> It's showing a blank page because no routes match that URL structure. We can't fix this because it's what you're telling the library to do.

@timdorr I understand that.  What I'm asking is, how could we throw an error when no route matches the path?  If one wants to ensure a route is always matched

**Comment by MeiKatz** [comment]
@ErikAGriffin Just add a "match all" route at the end of your list:
```jsx
<Switch>
  <Route path="/blog"><Blog /></Route>
  <Route path=""><NotFound /></Route>
</Switch>
```

**Comment by ErikAGriffin** [comment]
Yes I have that.  However I think having a basename on the router prevents it from catching the route when the app is deployed incorrectly.  What I would like is to be able to monitor an incorrect deployment (_that is, the route of the basepath does not match the route the react app is deployed to)_

**Comment by MeiKatz** [comment]
I think that `basename` is nasty. Just wrap everything below a parent route with the path `/blog` and you're good to go.

**Comment by ErikAGriffin** [comment]
@MeiKatz like this?
```jsx
(
    <Router>
        <Switch>
          <Route path="/blog">
              <Route exact path="/" render={() => <BlogHome />} />
              <Route path="/start" component={Signup} />
              <Route path="*" component={NotFoundPage} />
            </Route>
        </Switch>
    </Router>
  );
```

**Comment by MeiKatz** [comment]
Almost:
```jsx
<Router>
  <Switch>
    <Route path="/blog">
      <Route exact path="/" render={() => <BlogHome />} />
      <Route path="/start" component={Signup} />
    </Route>
    <Route path="*" component={NotFoundPage} />
  </Switch>
</Router>
```

**Comment by ErikAGriffin** [comment]
Hmm that didn't seem to work even for a correct deployment, that is deploying with the nested <Route> to '/blog' also rendered a white page, the fallback not working.

Unless I'm running into a caching issue.  I'm going to try to set up an environment to showcase what I'm experiencing
