### ISSUE TITLE
[v6] feature suggestion: remove/de-emphasize Route component usage

### ISSUE THREAD

**Issue by trappar** [ReactTraining/react-router#7387]
I don't see why the Route component exists. It seems like it only serves to add unnecessary syntactic sugar. I was shocked when I realized that the following routes are functionally equivalent in V6:

```jsx
<Routes>
    <Route path="/test" element={<Test/>}/>
    <Route path="/test"><Test/></Route>
    <Test path="/test"/> // Receives "path" prop, but otherwise identical
</Routes>
```

And in the following example, `AppRoutes1` and `AppRoutes2` are also functionally similar:

```jsx
import {Outlet, Route, Routes} from "react-router";

const Users = () => (
    <div>
        <nav>
            <Link to="me">My Profile</Link>
        </nav>
        <Outlet />
    </div>
);

const Me = () => (
    <div>Some content</div>
);

const AppRoutes1 = () => (
    <Routes>
        <Route path="/users/*" element={<Users/>}>
            <Route path="me" element={<Me/>}/>
        </Route>
    </Routes>
)

const AppRoutes2 = () => (
    <Routes>
        <Users path="/users/*">
            <Me path="me"/>
        </Users>
    </Routes>
)
```

It seems like the only real purpose of `Route` is to ensure that the "path" property is not forced onto a component which needs to reserve that for another usage. This seems like a concern that would be easily handled by documentation. For example:

"If you need to use the path prop in your component, you can simply wrap your component in a wrapper like:"

```jsx
const Route = ({element}) => element;
<Route path="/hello" element={<MyComponent path="some value"/>}/>
```

As a casual user of the library, I only found all of this accidentally in the process of implementing a "ProtectedRoute" style component. When I first tried using my component, it worked fine, so I moved on. Later I became immensely confused when I realized that I hadn't wrapped the component in a route at all, and that somehow it was still working despite seemingly violating every usage example I had seen. As far as I can tell this usage is not documented in any of the available blog posts, migration guides, docs, etc. I was only able to put together what was going on by looking at the source code and some trial and error.

I'll admit that something working where I would expect it not to is kind of a weird issue. Perhaps this is just a documentation issue, but I think that even with proper documentation users are going to find a lot of confusion surrounding the Route component.

Thoughts?

**Comment by idkjs** [comment]
To be more precise in my question, what is the migration path for `ProtectedRoute` to v6?

**Comment by trappar** [comment]
I'm not entirely sure what you mean, but here's my implementation of ProtectedRoute, which doesn't utilize Route at all.

```jsx
export function ProtectedRoute({element, children, allow, redirect}) {
    const location = useLocation();
    return allow
        ? element || children
        : <Navigate to={redirect} replace={true} state={{from: location.pathname}}/>;
}

// ProtectedRoute is used to create specific types of protected routes like this...
export function UserRequiredRoute(props) {
    const user = useSelector(getUser); // This can be any method of determining that the user is logged in
    return <ProtectedRoute allow={!!user} redirect="/login" {...props}/>;
}
```

I can then use this like...

```jsx
<Routes>
    <UserRequiredRoute path="/protected-page"><ProtectedPage/></UserRequiredRoute>
</Routes>
```

**Comment by idkjs** [comment]
@trappar sorry. Realize now that I had written an incomplete sentence. I was just asking a general question to no one in particular. Having that said that, you have provided valuable guidance. Thank you, sir.

**Comment by timdorr** [comment]
This has been the case of Switch in 4.x/5.x, and remains for Routes in 6.x: They inspect the props of their direct children to determine what to match. 

However, Route still serves a purpose: to establish types for those props (PropTypes or TypeScript). If you want strict typing, you'll need to use it. 

As for protecting routes, often the solution is just to move up the auth check outside of the Routes/Switch:
```js
<Routes>
  {authorized ? 
    (
      <Route path="/account" />
    )
    :
    (
      <Route path="/login" />
      <Route path="/register" />
    )
  }
</Routes>
```
