### ISSUE TITLE
__RouterContext doesn't be exported from v5.2.0 react-rotuer-dom?

### ISSUE THREAD

**Issue by inthewalter** [ReactTraining/react-router#7393]
I read the issue that history is separated from its own context (https://github.com/ReactTraining/react-router/pull/7103).
From the result of that, `__RouterContext` doesn't be exported from v5.2.0 react-rotuer-dom? @_@ 

Acutally, I have used `__RouterContext` for making own custom hooks because there not exists hooks before 5.1.0 @_@... from this update(5.2.0), that does not export `__RouterContext` @_@...now I have to refactor all my code If I want to use latest vesion

**Comment by timdorr** [comment]
We haven't changed the exports from react-router-dom.

**Comment by jedwards1211** [comment]
@timdorr yes you have, `react-router-dom` used to `export * from 'react-router'`, then when it was changed to only explicitly export things in https://github.com/ReactTraining/react-router/commit/e951e1d78edacbdf72c458e97938f92da3a43512, `__RouterContext` is no longer exported.

**Comment by flip-it** [comment]
It's still available in `react-router`, which you can import from instead of `react-router-dom`.
