### ISSUE TITLE
useLocation's search parameter changes when passed a space

### ISSUE THREAD

**Issue by selbekk** [ReactTraining/react-router#7394]
## Version

Latest stable (5.x)

## Test Case

https://codesandbox.io/s/lively-bash-4vmb6?file=/src/App.js

## Steps to reproduce

Replace the search string with something with a space in it. In my example you do that by clicking the button

## Expected Behavior

I'd expect `useLocation`'s `search` parameter to resolve to the decoded string right away.

## Actual Behavior

`useLocation`'s `search` parameter first returns the encoded version of the space (so `for%20example` in my repro), and then immediately changes to `for example`.

I'm using the `search` parameter to trigger a `useEffect` (which in turn calls our API), so this kind of blows 😅

I'm not sure where this parsing is happening - perhaps in the `history` package?

**Comment by timdorr** [comment]
This is a side-effect of using a HashRouter. This doesn't occur if you use a BrowserRouter. 

Any decoding happens in `history`, so I would check the issues over there instead.
