### ISSUE TITLE
Open source should not be linked to  racism

### ISSUE THREAD

**Issue by MatchaDog** [ReactTraining/react-router#7396]
## Version

**Please replace this sentence with the React Router version that you are using.**

## Test Case

https://codesandbox.io/s/react-router-gh6n7

**Comment by MeiKatz** [comment]
To be honest: I really support what @mjackson and @ryanflorence are doing in supporting the protests in the USA. But I am not sure why a start page with this contents wouldn't do it. Open Source is politics and is linked to it all times.
