### ISSUE TITLE
[v6] Back button does not update route in production mode

### ISSUE THREAD

**Issue by joehua87** [ReactTraining/react-router#7398]
## Version
6.0.0-alpha.5
## Steps to reproduce
* Go to: https://react-router-v6-back-not-update-route.now.sh
* Click Dashboard
* Then click Back button (the url in address bar is updated to home, but the content is still on Dashboard)

Code: https://github.com/joehua87/react-router-v6-back-not-update-route

## Expected Behavior
* Back button should update route component in production mode
## Actual Behavior
* It won't work on production mode, but work well in dev mode

**Comment by chris-mo** [comment]
Thanks for filing this!!

I'm experiencing this with version 4.3.1

**Comment by chris-mo** [comment]
From what I gathered looking into this, `history.location` is 1 step behind on production after clicking back button.

**Comment by chris-mo** [comment]
Has anyone viewed this issue/taken a look?

**Comment by pilotocheg** [comment]
The same on 5.1.2v

**Comment by BZaragoza0** [comment]
Hi, recently I've been developing an app and I had the same issue because I was wrapping a <HashRouter>into another one, maybe you are making the same mistake. There's more detailed info here [https://github.com/ReactTraining/react-router/issues/4975](#4975)

**Comment by mseyfayi** [comment]
I have the same issue in 6.6.1.
Any update?
