### ISSUE TITLE
Catch all route only works when refresh

### ISSUE THREAD

**Issue by iamchathu** [ReactTraining/react-router#7399]
## Version

"react-router-dom": "5.2.0",

## Test Case

https://codesandbox.io/s/react-router-catchall-routes-pmzds

## Steps to reproduce

create setup with two routes and catchall route and setup some links to test as in codesandbox demo.

```tsx
<Suspense fallback={<Loading />}>
      <Router>
        <Switch>
          <Layout>
            {publicRoutes.map((route) => (
              <Route key={route.path} {...route} />
            ))}
            <Route path="*" render={() => <Redirect to="/login" />} />
          </Layout>
        </Switch>
      </Router>
    </Suspense>
```

## Expected Behavior

When I press home link in AppBar which send user to `/` should be redirected to `/login`

## Actual Behavior

Currently if start the site from `/` it redirect to `/login` but if i click a Link pointing to `/` it doesn't redirect.

**Comment by timdorr** [comment]
Your Switch needs to go inside your Layout component. It only works on direct children.
