### ISSUE TITLE
useRouteMatch fired for route and all subroutes.

### ISSUE THREAD

**Issue by andrushkodmytro** [ReactTraining/react-router#7402]
I have route "/company" and subroute "/company/:id" and i want to detect only "/company" route. useRouteMatch( "/company" ) fired for this two route. I expected the same behavior like on Switch Route exact. 
strict: true doesn't help in this situation. 
I can compare match obj path and location.pathname but maybe you can add exact or something else. Thanks

"react-router-dom": "^5.1.2",
![Screenshot from 2020-06-05 13-28-00](https://user-images.githubusercontent.com/36206134/83866386-6865eb00-a730-11ea-95d3-1d7fb6be8bfa.png)

**Comment by timdorr** [comment]
useRouteMatch uses whatever matching you're doing on the closest Route above it. So you would set `exact` there to control when it matches.
