### ISSUE TITLE
Router doesn't support basename

### ISSUE THREAD

**Issue by alisajadih** [ReactTraining/react-router#7403]
im using Router in my app, because i need to navigate out of react component (e.g axios interceptor) , so i use my own browserhistory and use it in `<Router />` component, 
but now i cant use basename prop , it supports only in BrowerRouter. if i use BrowserRouter instead , i cant navigate out of a component , what can i do ?

**Comment by timdorr** [comment]
You shouldn't use Router unless you have a custom history to use. If you've got a custom history, just pass the basename setting to it when creating it.
