### ISSUE TITLE
[Feature Request] React Helmet Integration

### ISSUE THREAD

**Issue by aress31** [ReactTraining/react-router#7404]
Since things are changing quite a bit for React Router V6, I thought that suggesting a feature that would make React Helmet integration with React Router would be welcomed.

Indeed, in most case the page HTMl Header is defined on a route basis, route n.1 needs a specific title, route n.2 needs another specific title and so on). Since React and all these modern framework are all about making dev life easier, I was wondering whether adding custom properties to routes or passing the entire Helmet node would be possible?

**Comment by timdorr** [comment]
This would be something you would build in another library. That could take in a route config that can read extra properties for react-helmet. We don't need to build anything into the library for that.
