### ISSUE TITLE
[v6] Feature suggestion: Add `toString` method to location

### ISSUE THREAD

**Issue by afzalsayed96** [ReactTraining/react-router#7405]
I'm not sure if there is already a way to achieve this but it might be useful to have a `toString` method for location object which can be used to get a fully constructed pathname - `/pathname#hash?search` .

Example usage
```jsx
import { Navigate, useLocation } from 'react-router-dom'

function LoginRedirect() {
  const location = useLocation()

  return <Navigate to={`/login?redirect=${location.toString()}`} >
}
```

**Comment by MeiKatz** [comment]
This would be a feature for the `history` library.

**Comment by timdorr** [comment]
Yep, I agree, that's a good idea. Can you open up an issue over there? https://github.com/ReactTraining/history

**Comment by afzalsayed96** [comment]
Hi @timdorr, #799 was closed as the feature already exists with `createPath` function.
Is there way we could also export and use this function in `react-router`?
