### ISSUE TITLE
MIT Licensing concern

### ISSUE THREAD

**Issue by chadradams** [ReactTraining/react-router#7407]
**mini-create-react-context** has been flagged for the following reason: License is proprietary or includes usage restrictions.  Any chance for updating or removal of code.  This code flags react-router as a whole as non MIT license compliant.

**Comment by jasonnutter** [comment]
@chadradams The license on Github appears to be the standard MIT license: https://github.com/StringEpsilon/mini-create-react-context/blob/master/LICENSE

Can you clarify where you are seeing the restricted license referenced? (I presume [this is the license in question](https://github.com/jamiebuilds/license))

**Comment by timdorr** [comment]
Yeah, we don't use Jamie's version for the licensing issues he created a few years ago (and which got him banned from Twitter...).

I think you're looking at the wrong package. This has the right licensing.
