### ISSUE TITLE
v6: history cannot work in the case of asynchronous

### ISSUE THREAD

**Issue by Vibing** [ReactTraining/react-router#7408]
this is the demo: https://codesandbox.io/s/charming-solomon-16zgq

when i use 
```js
setTimeout(()=>{
  history.push('/login')
})
```
enter address: `https://16zgq.csb.app`
result:
![Xnip2020-06-09_14-37-10](https://user-images.githubusercontent.com/10387532/84114398-e0991d00-aa5e-11ea-9d4b-74a75699dd7a.jpg)

when i use:

```js
history.push('/login')
```
enter address: `https://16zgq.csb.app`
result:
![Xnip2020-06-09_14-54-43](https://user-images.githubusercontent.com/10387532/84115869-5c946480-aa61-11ea-9362-3ff204bebfc3.jpg)

I need to use it in the axios interceptor, when the status code is 401, I need to jump to the login page, I don’t know what to do

**Comment by timdorr** [comment]
You should put that check and that call inside your React component so it's a part of the render cycle. Otherwise, it's just going to run whenever it can and that may not coincide with a render. Hence your out of date display.

**Comment by Vibing** [comment]
https://codesandbox.io/s/charming-solomon-16zgq

```js
export default function App() {
  useMemo(() => {
    setTimeout(() => {
      history.push("/login");
    });
  }, []);

  useEffect(() => {
    setTimeout(() => {
      history.push("/login");
    });
  }, []);

  return (
    <div className="App">
      <HashRouter>
        <Routes>
          <Route path={"/login"} element={<Login />} />
          <Route path={"/"} element={<Navigate to={"/home"} />} />
          <Route path={"/home"} element={<Home />} />
        </Routes>
      </HashRouter>
    </div>
  );
}
```
I put it in `useMemo` and `useEffect`, it's not working.
In the above code, I used setTimeout to simulate the interceptor
I will use the axios interceptor in the global environment to decide whether to jump to the login page. 
```js
axios.interceptors.response.use(
  response => {},
  error => {
    const { status } = error.response
    if (status == 401) {
      history.push("/login");
    } 
  },
)
```
I should have coding it wrong, can you show me the way?

my English is not good, sorry
