### ISSUE TITLE
[v6] React Router does not work as global script

### ISSUE THREAD

**Issue by bela53** [ReactTraining/react-router#7410]
## Version

6.0.0-alpha.5

## Test Case

https://codesandbox.io/s/serene-fermat-tchxk?file=/public/index.html:1379-1705

## Steps to reproduce
The sandbox shows a minimal, equivalent program with React Router @5.2.0, which is working.
Now, comment the v5 script tag under public/index.html and uncomment the v6 ones.

Script sources:
v5:
```
<script src="https://unpkg.com/react-router-dom@5.2.0/umd/react-router-dom.min.js"></script>
```
v6:
```
<script src="https://unpkg.com/react-router@6.0.0-alpha.5/umd/react-router.production.min.js"></script>
<script src="https://unpkg.com/react-router-dom@6.0.0-alpha.5/umd/react-router-dom.production.min.js"></script>
```

## Expected Behavior
There is no error for v6, as with v5.

## Actual Behavior
Error: 
> TypeError
t.useRef is not a function

I am not entirely sure about the cause, as `useRef` rather is React.  I suspected it to be some kind of environment transpilation problem with Codesandbox. Though, I could reproduce an error outside Codesandbox as well.

**Comment by pierreneter** [comment]
I think `react-router` v6 requires hooks feature of React.

> Hooks are a new addition in React 16.8 (https://reactjs.org/docs/hooks-intro.html)

I see your example in React 16.3.1 so that why it does not work.
Upgrade your React version. I upgraded React at your example to 16.13.1 and add

```html
<script src="https://unpkg.com/history@5.0.0/umd/history.production.min.js"></script>
```

And it works: https://codesandbox.io/s/priceless-boyd-i8bxs?file=/public/index.html:0-2118

**Comment by timdorr** [comment]
Yeah, don't know how I missed that when I first looked. It's the wrong version of React.
