### ISSUE TITLE
querying keys from useParams is sometimes undefined

### ISSUE THREAD

**Issue by reduxdj** [ReactTraining/react-router#7412]
"react-router": "^5.2.0",
    "react-router-dom": "^5.2.0",
**Please replace this sentence with the React Router version that you are using.**

## Test Case

https://codesandbox.io/s/react-router-gh6n7
N/A

## Expected Behavior

So we have a certain route, nothing crazy defined with a parameter like this
```js
<Route exact path="/person/:personId" component={SuperComponent} />
```
And you know references like this all over the place....
```js
const {personId} = useParams()
```

About half the time, we notice the personId is undefined? Is this expected? We can still grab the parameter off the window.location object directly

We have a modal container and it's presented with a series of cloneElement calls, seems to be compounding the problem as only this avenue of code is affected.

**Comment by timdorr** [comment]
Something else must be going on here outside of the library. There isn't a way for that code to produce different outputs. You would need to be removing the parent Route from the tree for it not to have those values.

Can you provide a reproduction of the issue on Codesandbox?
