### ISSUE TITLE
[v6] react routes with absolute paths?

### ISSUE THREAD

**Issue by Bluskript** [ReactTraining/react-router#7413]
While using React Router v6, I noticed that it is no longer possible to create non-relative react routes. Here's why I need them:

```jsx
const Root = React.memo(() => {
    <Routes>
      <Route path="/entry/:page/*" element={<EntryPage />} />
    </Routes>
});
```
```jsx
const pages = {"serverselect": 0, "auth": 1};
export const Entry = React.memo(() => {
  const { page } = useParams();
  return (
    <Stepper activeStep={pages[page]}>
    </Stepper>
    <Routes>
      <Route path="/entry/serverselect" element={<ServerSelect />} />
      <Route path="/entry/auth/:mode" element={<AuthPage />} />
    </Routes>
  );
};
```
As seen here, I need both the page parameter available in Entry (for the stepper), while also being able to use the parameter as part of a route (for rendering the actual steps). However, this does not work as expected. In order for ServerSelect to render, I must go to `/entry/*/entry/serverselect` instead of `/entry/serverselect`

**Comment by timdorr** [comment]
Duplicate of #7335
