### ISSUE TITLE
history.push not rendering component in Router

### ISSUE THREAD

**Issue by riwu** [ReactTraining/react-router#7415]
## Version
    "react-router-dom": "^5.2.0",

## Test Case
For some peculiar reason this bug is not reproducible on CodeSandbox, please clone https://github.com/riwu/react-router-dom-bug instead.
 
```
import React from "react";
import { Router, Route } from "react-router-dom";
import { createBrowserHistory } from "history";

const history = createBrowserHistory();

export default function App() {
  return (
    <Router history={history}>
      <Route
        exact
        path="/"
        component={() => (
          <button onClick={() => history.push("/2")}>click</button>
        )}
      />
      <Route path="/2" component={() => "page 2"} />
    </Router>
  );
}
```

## Steps to reproduce
1. `git clone https://github.com/riwu/react-router-dom-bug.git`
2. `yarn install`
3. `yarn start`
4. Click the "click" button.

## Expected Behavior
"page 2" should be rendered.

## Actual Behavior
blank page is rendered.

**Comment by riwu** [comment]
@timdorr why is this tagged `support`? I have outlined the steps to show that it's a reproducible bug with the library.

**Comment by eebasadre20** [comment]
I experienced same issue now. The URL changed to the supposed history.push("/myURL"), however, the page is not rendering the component.

Any thoughts about this? I am using `Router` not the `BrowserRouter`

**Comment by elenarojas** [comment]
@riwu I had the same issue, after checking this https://medium.com/@shoaibbhimani1392/react-router-frequently-faced-problems-f7d30d02087e it was still failing. I had history@5.0.0 and after moving it to version 4.10.1 it worked.

**Comment by riwu** [comment]
@elenarojas thanks for the info. I have opened a new issue since timdorr mistagged this as support and refuses to reopen for some reason.

**Comment by cdosborn** [comment]
I resolved this issue by ensuring my version of history was the same as used by react-router:
```
$ yarn list history
yarn list v1.13.0
warning Filtering by arguments is deprecated. Please use the pattern option instead.
├─ history@5.0.0
├─ react-router-dom@5.2.0
│  └─ history@4.10.1
└─ react-router@5.2.0
   └─ history@4.10.1

$ yarn add history@4.10.1
```

**Comment by timdorr** [comment]
Your example code doesn't have react-router used in it anywhere. But like it was pointed out, you have to use history 4.x with React Router 4.x/5.x. History 5.0 is not compatible.

**Comment by riwu** [comment]
@timdorr the code uses https://www.npmjs.com/package/react-router-dom which links to this repo.
Regarding the incompatibility, should that be explicitly mentioned in the docs?

**Comment by timdorr** [comment]
No, it doesn't: https://github.com/riwu/react-router-dom-bug/search?q=router

**Comment by riwu** [comment]
Must have forgotten to push the changes, updated now.

**Comment by piyushjha97** [comment]
I am still getting the same issue with history v5. i.e. the URL is changed but the component is not rendered. I didn't find any solution to this anywhere on the internet.
please help

**Comment by cdosborn** [comment]
@piyushjha97 you may try ensuring that the call to history.push does not happen during rendering by wrapping it in a `useEffect`.

**Comment by piyushjha97** [comment]
Thank you for your response @cdosborn .
I am using class component and most importantly I uninstalled version 5 and installed version 4  of npm history then it is working normally.

**Comment by NiklasRz** [comment]
I had the same problem and can confirm that this is a bug with history 5.x. It works with history 4.x i.e. after i run "npm uninstall history" and "npm install history@4.10.1"

**Comment by hhgnsc** [comment]
see [https://github.com/ReactTraining/react-router/issues/7506#issuecomment-678019319](https://github.com/ReactTraining/react-router/issues/7506#issuecomment-678019319)

**Comment by hieunc229** [comment]
This works for me https://github.com/ReactTraining/react-router/issues/7415#issuecomment-670672375

> I resolved this issue by ensuring my version of history was the same as used by react-router

**Comment by dimmg** [comment]
Can anyone acknowledge that this is working outside of a React component?
I'm trying to use custom history in an axios interceptor and even downgrading **history** to @4.10.1 and ensuring that both **react-router** and **react-router-dom** have the same version did not work for me.

**Comment by actuallymentor** [comment]
> see [#7506 (comment)](https://github.com/ReactTraining/react-router/issues/7506#issuecomment-678019319)

I see this issue is closed, but is this issue being acknowledged?

**Comment by hhgnsc** [comment]
> > see [#7506 (comment)](https://github.com/ReactTraining/react-router/issues/7506#issuecomment-678019319)
> 
> I see this issue is closed, but is this issue being acknowledged?

No, it's not acknowledged by the developer of react-router or history, but I find this way by reading the source code of react-router. And I use in my project, it works.

**Comment by NoCtrlZ1110** [comment]
> I resolved this issue by ensuring my version of history was the same as used by react-router:
> 
> ```
> $ yarn list history
> yarn list v1.13.0
> warning Filtering by arguments is deprecated. Please use the pattern option instead.
> ├─ history@5.0.0
> ├─ react-router-dom@5.2.0
> │  └─ history@4.10.1
> └─ react-router@5.2.0
>    └─ history@4.10.1
> 
> $ yarn add history@4.10.1
> ```


Thank god for letting me read your comment !!!

**Comment by ajw725** [comment]
same issue here. same solution worked, i.e. uninstall and then `yarn add history@4.10.1`.

**Comment by KamrulSh** [comment]
> I had the same problem and can confirm that this is a bug with history 5.x. It works with history 4.x i.e. after i run "npm uninstall history" and "npm install history@4.10.1"

I am facing that issue although I have downgraded from history 5.x to history@4.10.1. Is there any solution?

**Comment by KamrulSh** [comment]
> same issue here. same solution worked, i.e. uninstall and then `yarn add history@4.10.1`.

I am facing that issue although I have downgraded from history 5.x to history@4.10.1. Is there any solution?

**Comment by ajw725** [comment]
@KamrulSh did you make sure that you fully removed the 5.x version before reinstalling, and did you make sure that 4.10.1 is the exact version installed by react-router?

this entire approach felt too fragile to me, so i just ended up referencing the history package implicitly through react-router and telling eslint to ignore the warning about the implicit dependency.

**Comment by KamrulSh** [comment]
@ajw725 yeah,  I have done all this. I have solved this problem by downgrading react v16.14.0 from v17 and changed  BrowserRouter with Router. In v17, Router was not working in my project that's why I have used BrowserRouter. Thanks, buddy.

**Comment by Jasioski** [comment]
I see this is closed, but simply downgrading is not a valid solution. Is there any updates on this being fixed in future releases of history?

**Comment by designervoid** [comment]
Downgrade helps me too.
@Jasioski did u delete `node_modules` and `package-lock.json` after `yarn add history@4.10.1` or `npm install history@4.10.1`?

**Comment by Jasioski** [comment]
@designervoid 

I know history@4.10.1 works. It fixed the issue for me too...
The point is simply downgrading is not really really a solution, there should be initiative either on the side of the history devs, or react-router-dom, to get compatibility working with latest releases.

What if there is a security vulnerability that's fixed in a later release, is everyone who wants routing to work stuck with the vulnerable 4.10.1 version?

Thanks for the help, but I really think this should be more looked at more closely by the devs  of history and react-router dom.

**Comment by timdorr** [comment]
React Router v6 uses History v5, so it will be supported whenever that version is released. Nonetheless, you shouldn't have to install `history` separately, as `react-router`/`react-router-dom` will request the right version automatically. You can rely on this sub-dependency without explicitly installing it in your app.

**Comment by kamleshwebtech** [comment]
I have below routing in app function:

```
<Route exact path="/" component={ListOfItems}></Route>
<Route path="/list/:searchquery?" component={ListOfItems}></Route>
```

second Route is working well when i pass any search term but when i try to access first route '/' using history.push('/') calling by function it changes the url in the browser but does not render the component of '/' route.

```
import { createBrowserHistory } from "history";
const history = createBrowserHistory();

const redirectToHome = () => {
    history.push('/');
  }
```

could you please suggest me what is the issue? Thanks a lot.

**Comment by BenReichwein** [comment]
> I had the same issue, after checking this https://medium.com/@shoaibbhimani1392/react-router-frequently-faced-problems-f7d30d02087e it was still failing. I had history@5.0.0 and react-router-dom@5.2.0 and after moving history to version 4.10.1 it worked.

This worked for me

**Comment by durai001** [comment]
import { Router, Route } from "react-router-dom"
 instead of this try  below
import { BrowserRouter as Router, Switch, Route } from "react-router-dom";

**Comment by FerJSsilva** [comment]
> I resolved this issue by ensuring my version of history was the same as used by react-router:
> 
> ```
> $ yarn list history
> yarn list v1.13.0
> warning Filtering by arguments is deprecated. Please use the pattern option instead.
> ├─ history@5.0.0
> ├─ react-router-dom@5.2.0
> │  └─ history@4.10.1
> └─ react-router@5.2.0
>    └─ history@4.10.1
> 
> $ yarn add history@4.10.1
> ```

This is a common major problem! This was hard to find!

So everybody that install the latest version of react-router-dom and history will need to find this comment and match the versions?

This is not a support matter! This is something to be fixed! Oh gosh!

**Comment by renatobenks** [comment]
I think this is solved in v6 @FerJSsilva, so maybe that's why no one has taken care of it.

**Comment by d-kocheski** [comment]
> I resolved this issue by ensuring my version of history was the same as used by react-router:
> 
> ```
> $ yarn list history
> yarn list v1.13.0
> warning Filtering by arguments is deprecated. Please use the pattern option instead.
> ├─ history@5.0.0
> ├─ react-router-dom@5.2.0
> │  └─ history@4.10.1
> └─ react-router@5.2.0
>    └─ history@4.10.1
> 
> $ yarn add history@4.10.1
> ```

Life Saver !!!!

**Comment by wallace-sf** [comment]
Still facing the problem.

**Comment by timdorr** [comment]
@wallace-sf As pointed out above, you can only use history 4.x with react-router-dom 5.x. history 5.x is not compatible.

**Comment by wallace-sf** [comment]
> @wallace-sf As pointed out above, you can only use history 4.x with react-router-dom 5.x. history 5.x is not compatible.

Thank you. It worked.
