### ISSUE TITLE
On ios, animation (transition) doesn’t work, for SVG.

### ISSUE THREAD

**Issue by fedkam** [ReactTraining/react-router#7417]
Hi!

Drew attention to strange behavior. 
Doesn't work transition (css) for SVG on ios(Safari, Chrome):
```
.logo_inactive {
  fill: grey;
  transition: all 0.7s linear;
}
```
But working on desktop(windows) and android.

[**Example**(open on ios)](https://codesandbox.io/s/wtf-not-work-transition-sjl98?file=/src/App.js) 

_Please tell me, is this a bug? Or am I doing something wrong?_

**Comment by timdorr** [comment]
Doesn't look like a bug in the library. Possibly something in iOS, but I don't see this on my iPad.
