### ISSUE TITLE
[v6] useRoutes does not work with loadable/component

### ISSUE THREAD

**Issue by shwao** [ReactTraining/react-router#7421]
## Version

6.0.0-alpha.5

## Test Case

https://codesandbox.io/s/react-router-loadable-component-t97j0?file=/src/App.jsx

## Steps to reproduce
I created a route config array and added the name of the page component as a string:
```
const routes = [
  {
    path: "/",
    componentName: "Home"
  },
  {
    path: "/about",
    componentName: "About"
    children: [
      {
        path: "me",
        componentName: "AboutMe"
      }
    ]
  },
  {
    path: "/users",
    componentName: "Users"
    children: [
      {
        path: ":user",
        componentName: "User"
      }
    ]
  }
]
```
I created a component `<AsyncPage component="componentName" />` which returns a `loadable/component`:
```
const AsyncPage = loadable(props => import(`./pages/${props.component}`));
```
I created a function to recursively map the `<AsyncPage>` to the `element` property.
```
const mapRoutesForUse = routes => {
  return routes.map(({ path, componentName, children }) => ({
    path,
    element: <AsyncPage component={componentName} />,
    children: children && mapRoutesForUse(children)
  }));
};
```
I created a `<ProjectRoutes>` component with `useRoutes`:
```
const ProjectRoutes = () => useRoutes(mapRoutesForUse(routes));
```
I added the `<ProjectRoutes />` component to my App:
```
const App = () => {
  return (
    <div>
      <ul>
        <li>
          <Link to="/">Home</Link>
        </li>
        <li>
          <Link to="/about">About</Link>
          <ul>
            <li>
              <Link to="/about/me">Me</Link>
            </li>
          </ul>
        </li>
        <li>
          <Link to="/users">Users</Link>
        </li>
      </ul>
      <ProjectRoutes />
    </div>
  );
};
```
I added an `<Outlet>` component to the `<About>` and `<Users>` page components:
```
const About = () => (
  <>
    <h1>About Page</h1>
    <Outlet />
  </>
);
```
## Expected Behavior
I would expect this setup to work and the router to render the requested pages.

## Actual Behavior
- When you are on the ["Home" page](https://t97j0.codesandbox.io/) of the testcase and you click on a link in the navigation, the URL changes but does not get rendered.
- When you are on the ["About" page](https://t97j0.codesandbox.io/about) and click on the "Home" or "Users" link nothing happens. But clicking on the "Me" link works!
- When you are on the ["Me" page](https://t97j0.codesandbox.io/about/me) and click on the "Home" or "Users" link it will take you to "About".
- When you are on the ["Users" page](https://t97j0.codesandbox.io/users) its same as on the "About" page. Clicking the links to the "User" pages works but clicking on "Home" or "About" takes you again to "Users".

## Workaround
I created a function to recursively map the route config to `<Route>` components:
```
const mapRoutes = routes => {
  return routes.map(({ path, componentName, children }, key) => (
    <Route
      path={path}
      key={key}
      element={<AsyncPage component={componentName} />}
      children={children && mapRoutes(children)}
    />
  ));
};
```
And use it in the App like this:
```
      ...
      </ul>
      <Routes>{mapRoutes(routes)}</Routes>
    </div>
  );
};
```
This works great and every link navigates to the correct page.
But shouldn't this be the same as what `useRoutes` returns?

**Comment by k00p** [comment]
@shwao I have no idea how much time you just saved me. I started with `useRoutes`, and the component mounting behavior was working well until I changed *something*.  Unfortunately, I was not able to pin down exactly what change caused it to no longer work correctly, much to my frustration. I _think_ it may have something to do with how the `useRoutes` is nested, because I was implementing error handling when it stopped working. I'm suspicious that there may be something to do with classed, functional, or a mixture of classed and functional components in the `useRoutes` lineage that causes this behavior, but investigating this is not something I can commit time to ATM. 

Thank you very much for your workaround (I can confirm that it resolved my issue as well), and yes - I think this behavior may be worth understanding so that it can have test cases or documentation written against it.

**Comment by bbuchanan** [comment]
I'm migrating from v5 to v6 in a test app. The v5 app I had also loaded components dynamically. The switch from Component to Element has me scratching my head as to how I should accomplish functionality I had working great in v5. I have a similar array to yours (route name, component, etc). Now when I try to assign that to <Route>, it fails because it's looking for an Element, not a component.

Is this the only/best way to assign components to routes dynamically? I feel like I'm missing something easy.

So I have to use the component name as a string and create it via loadable?

Appreciate any help/guidance.

**Comment by danilobrinu** [comment]
@shwao I fixed ur issue -> https://codesandbox.io/s/react-router-loadable-component-forked-m0hfr?file=/src/App.jsx

**Comment by shwao** [comment]
Yes it works, thank you @danilobrinu ! But do you know why? Is that a bug or is it supposed to be like that? I cant think of reason why that would make a difference.

**Comment by shwao** [comment]
@bbuchanan Yes use a string of the component name and create via loadable like in danilobrinu's example. But you do not need to have the components imported like in his sandbox.

Here i forked it and removed the components so that it is cleaner: https://codesandbox.io/s/react-router-loadable-component-forked-vx1g0

**Comment by danilobrinu** [comment]
> Yes it works, thank you @danilobrinu ! But do you know why? Is that a bug or is it supposed to be like that? I cant think of reason why that would make a difference. 

@shwao it's supposed to be like that because loadable return a React.Function instead of React.Element but you can get the React.Element just calling to a React.Function.

So the way to do that is assigning the result of loadable to a variable (in my case is Component) a calling like a React.Component (<Component />). Don't forget the element prop expect to a React.Element, so is you the pass component itself doesn't work.

**Comment by shwao** [comment]
Ah okay, that makes sense. Thanks again for your help, i will close this issue.

**Comment by shwao** [comment]
There is something wrong here. The way @danilobrinu showed to use useRoutes works but i changed my private project to use it and i discovered a problem with react-spring. 

I came to the conclusion that it must be because of the `Component` inside the `mapRoutes` function. I changed the `mapRoutes` function from this (which works but with the react-spring problem): 
```
return routes.map(({ path, component, routes }) => 
{
	const Component = loadable(() => import(`shared/pages/${component}/index`));

	return {
		path,
		element: <Component />,
		children: routes && mapRoutes(routes),
	};
});
```
to this where i use the same `AsyncPage` component like in my first issue post:
```
const mapRoutes = (routes: ProjectRoute[]): PartialRouteObject[] =>
{
	return routes.map(({ path, component, routes }) => ({
		path,
		element: <AsyncPage component={component} />,
		children: routes && mapRoutes(routes),
	}));
};
```
And it works in my project! The page components are being lazy loaded and react-spring also works!
But then i tried the same again in the codesandbox and it does not work! Its the same behaviour like i described above.

It makes no sense to me why it would work in my project but not in the sandbox. I think this is a bug and i will reopen this issue.

**Comment by danilobrinu** [comment]
> There is something wrong here. The way @danilobrinu showed to use useRoutes works but i changed my private project to use it and i discovered a problem with react-spring. 
> 
> I came to the conclusion that it must be because of the `Component` inside the `mapRoutes` function. I changed the `mapRoutes` function from this (which works but with the react-spring problem): 
> ```
> return routes.map(({ path, component, routes }) => 
> {
> 	const Component = loadable(() => import(`shared/pages/${component}/index`));
> 
> 	return {
> 		path,
> 		element: <Component />,
> 		children: routes && mapRoutes(routes),
> 	};
> });
> ```
> to this where i use the same `AsyncPage` component like in my first issue post:
> ```
> const mapRoutes = (routes: ProjectRoute[]): PartialRouteObject[] =>
> {
> 	return routes.map(({ path, component, routes }) => ({
> 		path,
> 		element: <AsyncPage component={component} />,
> 		children: routes && mapRoutes(routes),
> 	}));
> };
> ```
> And it works in my project! The page components are being lazy loaded and react-spring also works!
> But then i tried the same again in the codesandbox and it does not work! Its the same behaviour like i described above.
> 
> It makes no sense to me why it would work in my project but not in the sandbox. I think this is a bug and i will reopen this issue.

@shwao that code is wrong, if you want to lazy load components (using dynamic import) dynamically you need to be explicit.

So the next code should works, let me know if something is wrong.

```
// This only works is the extension is .js
const Component = loadable(() => import(`shared/pages/${compoment}/index`))
// In other cases you need to be explicit like in the example that I share you
const Component = loadable(() => import(`shared/pages/${compoment}/index.jsx`)) 
```

**Comment by shwao** [comment]
Please remove the quote from your comment it makes the thread hard to read. 

My project is Typescript and it works so it is not wrong.

**Comment by danilobrinu** [comment]
> Please remove the quote from your comment it makes the thread hard to read. 
> 
> My project is Typescript and it works so it is not wrong. 

Can you provide an codesandbox for that ?

**Comment by shwao** [comment]
You mean a working Typescript example like I have in my project now? That makes sense. I will try to set one up.

**Comment by shwao** [comment]
I created a sandbox in Typescript but im having the same problem. But it does fully work in my larger more complex project, so there must be something! I will try to find out why it works but that could take some time as i do not have enough time right now.

**Comment by danilobrinu** [comment]
> You mean a working Typescript example like I have in my project now? That makes sense. I will try to set one 

I just need a basic example

**Comment by danilobrinu** [comment]
@shwao I think is some related to how you are implementing because I created a basic example with TypeScript and works very well. https://codesandbox.io/s/falling-smoke-ye0jz?file=/src/App.tsx:565-568

**Comment by shwao** [comment]
Yes you are correct, i did the mistake again and returned the loadable component directly. So instead like you:
```
const AsyncComponent: React.FC<AsyncComponentProps> = ({ name, ...props }) => {
  const Component = loadable(() => import(`./components/${name}.tsx`));

  return <Component {...props} />;
};
```
I did:
```
const AsyncComponent = loadable(({ name }) => import(`./components/${name}.tsx`));
```
And i am doing it like this in my project and it works! But it does not work in the sandbox. Only your way of wrapping it works. Thats what i dont understand, why does it work for me?

But if i understand you correctly, passing the loadable component directly **should not work** and the only correct way is to wrap it in a component?

And what purpose do the rest props in the AsyncComponent serve? Your example still works if i remove that.

**Comment by danilobrinu** [comment]
@shwao yep the only way to do that when you lazy load components dynamically is warpping it. About the rest props is not necessary but that means you can pass some props to the route component and that component can receive that props.

**Comment by shwao** [comment]
Okay i understand. Thank you very much for your help, it's greatly appreciated!
I can finally close this issue.

---

For everyone having problems to get typescript + react-router v6 + loadable components to work, look at this sandbox from @danilobrinu : https://codesandbox.io/s/falling-smoke-ye0jz?file=/src/App.tsx
