### ISSUE TITLE
Link component prop example provided in documentation does not work

### ISSUE THREAD

**Issue by thepeted** [ReactTraining/react-router#7424]
## Version

5.20

## Test Case

https://codesandbox.io/s/winter-tdd-q8weu?file=/src/App.js

## Expected Behavior

The example documented at https://reacttraining.com/react-router/web/api/Link/component-reactcomponent should render a clickable link.

## Actual Behavior

Does not work.

I might have got the wrong end of the stick but the documentation suggests that I can provide a custom component to <Link/> using example:

```
const FancyLink = React.forwardRef((props, ref) => (
  <a ref={ref}>💅 {props.children}</a>
))

<Link to="/" component={FancyLink} />
```

This does not seem to work.  I note href is available on the props so perhaps this is closer to the intended use case:

```
const FancyLink = React.forwardRef((props, ref) => (
  <a ref={ref} href={ props.href }>💅 {props.children}</a>
))

<Link to="/" component={FancyLink} >Go</a>
```

**Comment by alzapiedi** [comment]
did you resolve this? I experience a similar issue with the example where the clickable link is rendered, however it does not have any `href` or on click behavior, and manually adding `href` breaks the typical `Link`  functionality and triggers a page reload
