### ISSUE TITLE
v6: migrating-5-to-6.md misses generatePath change (it no longer encodes URI components)

### ISSUE THREAD

**Issue by jellevandenhooff** [ReactTraining/react-router#7428]
I ran into a small snag when trying out v6. The v6 version of `generatePath` no longer automatically URI encodes passed params. The old v5 version does. This change is not documented in https://github.com/ReactTraining/react-router/blob/dev/docs/advanced-guides/migrating-5-to-6.md.

The symmetry in the v6 API between `generatePath` and `useParams` is an improvement, though thinking about this some more, I wonder if making both APIs call encode and decodeURIComponent automatically would be even nicer. With the v6 API, generatePath will create paths that `<Route>` does not match, eg. `generatePath("user/:id/edit", {id: "bob/likes/slashes"})` will generate `user/bob/likes/slashes/edit`, which does not match `<Route path="user/:id/edit">`.

(As an aside, the suspense support in the experimental branch is very cool! Thanks for that.)

Repro:

old: https://codesandbox.io/s/react-router-s011k?file=/index.js
new: https://codesandbox.io/s/react-router-p3hh0?file=/index.js

Relevant source:

https://github.com/ReactTraining/react-router/blob/8bae34cd4a900822df08ae50c985e056d283924a/packages/react-router/index.tsx#L802

https://github.com/ReactTraining/react-router/blob/b6a7fb2ac998377c82eee5cd2d8b991465609203/packages/react-router/modules/generatePath.js#L23

**Comment by timdorr** [comment]
We don't get into URL encoding for a variety of reasons. This is an intentional choice. If you want to open up a PR to add something to the migration docs, feel free!

**Comment by EugeneGoroschenya** [comment]
The link to show how it was in v5 is no longer actual because of `"react-router-dom": "latest"` in `package.json`
> old: https://codesandbox.io/s/react-router-s011k?file=/index.js

Updated old: https://codesandbox.io/p/sandbox/react-router-djn774?file=%2Findex.js
