### ISSUE TITLE
[v6] change return type of  useRoutes hook

### ISSUE THREAD

**Issue by MHA15** [ReactTraining/react-router#7433]
Hi
I was thinking about that it is a good idea to return the matched object from useRoutes maybe a tuple witch contains both element and matchedRoute

it's usecase is when we add more custom fields to route objects for example  `needsAuthenticate , needsHeader , footerMode , ...` and we want to use them after match to run an effect or returning null instead of element or any other decision 

```js

   const [element , matchedRoute] = useRoutes(myRoutes);
   if(matchedRoute.needsAuthenticate)
       return null;

   return element

```

**Comment by timdorr** [comment]
We can't do that for the input to useRoutes because it accepts a specific type (`PartialRouteObject` specifically). We can't accept those other properties on the object.

Instead, you should use props on the `element` for the route. That would be the "proper" way of handling this.

**Comment by MHA15** [comment]
> We can't do that for the input to useRoutes because it accepts a specific type (`PartialRouteObject` specifically). We can't accept those other properties on the object.

I didn't use V6 yet but I rememeber that in V5 you let us pass any object extends RouteProps so wouldn't you let us pass any object extend PartialRouteObject in V6 ?

> Instead, you should use props on the `element` for the route. That would be the "proper" way of handling this.
 
I think that I couldn't tell you my purpose , I want to use those properties in the parent element and set effects and conditions depend on it not to render some other component and pass these props to it to handle these logics
