### ISSUE TITLE
Linking component libraries causes an invariant error

### ISSUE THREAD

**Issue by monsonjeremy** [ReactTraining/react-router#7436]
## Version

`^5.0.0`

## Test Case

https://github.com/monsonjeremy/react-router-linking-issue

## Steps to reproduce

First run the app to see that it works without linking
```sh
npm install
npm start
```

go to `localhost:3000` and see the app rendered

Now link to the component library and see that it will not work

```sh
cd component-lib
npm install
npm run build
npm link
cd ..
npm link jeremy-test-lib
npm start
```

Now when navigating to `localhost:3000` there will be an invariant error

`Error: Invariant failed: You should not use <Link> outside a <Router>`

## Expected Behavior

Should properly render the app.

## Actual Behavior

`Error: Invariant failed: You should not use <Link> outside a <Router>`

**Comment by timdorr** [comment]
You need to wrap your component in some sort of Router component when rendering. This isn't a bug.

**Comment by monsonjeremy** [comment]
@timdorr The code I provided has a Router. It’s 2 components, wrapped inside a `StaticRouter` component.
