### ISSUE TITLE
Router component with custom history not working

### ISSUE THREAD

**Issue by alexiusp** [ReactTraining/react-router#7437]
## Version

^5.2.0

## Test Case

https://codesandbox.io/s/react-router-no-match-404-g2oir

## Steps to reproduce

click on links in navigation

## Expected Behavior

corresponding components are rendered

## Actual Behavior

always shows 'No match for' component with empty pathname

**Comment by timdorr** [comment]
You're using the wrong version of `history`. 5.x/4.x of Router are only compatible with history 4.x.
