### ISSUE TITLE
I want to get params in path inside Class component

### ISSUE THREAD

**Issue by duongvanan97** [ReactTraining/react-router#7439]
with react-router-dom v5 and v4 have withRouter to get params. But i don't see any function to get path params inside Class component. I just get it hooks and i don't want it. Please update it, thanks alot

**Comment by timdorr** [comment]
Just wrap it in a functional component and pass them in as props. You can also use the withRouter wrapper.

**Comment by duongvanan97** [comment]
I mean in react-router-dom v6 @timdorr
