### ISSUE TITLE
Should <Redirect> have the same API as <Link> ?

### ISSUE THREAD

**Issue by eedrah** [ReactTraining/react-router#7440]
Link's `to` attribute accepts all of `string`, `object` and `function` which modifies the current location.

Redirect's `to` is similar, but only supporting `string` and `object`.

I was wondering if there was interest in letting `<Redirect>` also accept a functionʔ This way we could redirect using the current location as a parameter (without the extra call to `useLocation` or the need to obey the Rules of Hooks).

**Comment by timdorr** [comment]
There aren't any Rules of Hooks that apply to useLocation because it's a custom hook.

Regardless, you should either use useLocation or the Redirect with parameters feature added in #5209.
