### ISSUE TITLE
Get params in path inside Class component react-router-dom v6

### ISSUE THREAD

**Issue by duongvanan97** [ReactTraining/react-router#7441]
Hi
react-router-dom v6 not support withRouter. I really want it to use inside Class component (i can't use hooks useParams in Class component). Please update it
Thanks alot

**Comment by timdorr** [comment]
If you would rather not refactor your class components, just wrap them with a small function component and pass in the params you need as props.

```js
function WrappedApp(props) {
  const params = useParams()
  return <App params={params} {...props} />
}
```
