### ISSUE TITLE
<Prompt>: Allow dialog customization

### ISSUE THREAD

**Issue by dingens** [ReactTraining/react-router#7442]
Currently, `<Prompt>` only allows defining a dialog text. This allows to create dialogs like the following:

```
+------------------------------------+
| CONFIRM                            |
+------------------------------------+
| Are you sure you want to quit      |
| without saving your changes?       |
|                                    |
|                [ Cancel ]   [ OK ] |
+------------------------------------+
```

However, this is bad UI. The user must read the text very carefully to find out what will happen when they click each of the buttons.

The better UI would be something like the following, but this is not currently possible:

```
+------------------------------------+
| DISCARD CHANGES                    |
+------------------------------------+
| Are you sure you want to quit      |
| without saving your changes?       |
|                                    |
|     [ Keep Editing ]   [ Discard ] |
+------------------------------------+
```

I'd like to suggest adding more options to `<Prompt>` to allow customizing this, for example `<Prompt title="Discard changes" message="Are you ..." yesmsg="Discard" nomsg="Keep Editing">` or something.

(I know that the default handler for the confirmation dialog is `window.confirm`, which doesn't support this kind of configuration. But it isn't even possible to pass these kinds of parameters to a custom confirm dialog handler.
Part of this issue is finding a solution for this: either change the default to use a custom `confirm` function, or ignore the additional parameters in that case – however, this may create the problem that the `message` can become hard to understand without the according button labels.)

**Comment by timdorr** [comment]
This is [a feature of the history library](https://github.com/ReactTraining/history/blob/master/docs/api-reference.md#historyblockblocker-blocker) that we use under the hood, so you should ask for this over there.
