### ISSUE TITLE
History API's state does not persist in deployed application

### ISSUE THREAD

**Issue by jayendrasharan** [ReactTraining/react-router#7445]
I have an issue in understanding the History API's state. The problem I am facing is the different behaviour between ```localhost``` and the actual deployed application.

So after I save something in ```state```, and refresh the page I see two different behaviours.

1. localhost keeps a copy post refresh
2. production environment doesn't keep a copy after the refresh.

I have gone through the documentation,

https://developer.mozilla.org/en-US/docs/Web/API/History_API

it talks about, the state should be serializable and the max size. But I am storing exactly the same data, in both the environments, because it's the same flow of the application.

Could anyone help with this?

I am using react-router-dom, here is the code snippet:

```
// inside the component,
this.props.history.push('/some/route', {
  data: data
});


// in component did mount
if (this.props.location.state) {
  // do something with this.props.location.state
})
```

```
"react-router-dom": "^4.3.1",
"react-dom": "^16.8.6",
"react": "^16.8.6",
```

**Comment by timdorr** [comment]
You should ask this on the history repo: https://github.com/ReactTraining/history
