### ISSUE TITLE
`useLocation` return value does not have `origin` nor `host`

### ISSUE THREAD

**Issue by vfonic** [ReactTraining/react-router#7446]
I'm trying to find where this is documented, but can't find anything.

No matter where I write this block of code, it always outputs `undefined`:

```js
const loc = useLocation();
console.log('Origin: ', loc.origin); // => Origin: undefined
console.log('Origin: ', window.location.origin); // => Origin: https://the-actual-url
```

## Version

"react-router": "^5.1.2", => resolved to 5.1.3 in yarn.lock
"react-router-dom": "^5.1.2", => resolved to 5.1.3 in yarn.lock

## Test Case

Here's the test case:
https://codesandbox.io/s/react-router-ru6ko?file=/index.js:693-797

## Expected Behavior

origin is printed

## Actual Behavior

origin is undefined and empty string is printed instead

**Comment by timdorr** [comment]
That's never been a part of our location API. It's not a clone of the DOM API, just a close mirror. Some things like this aren't implemented.

**Comment by vfonic** [comment]
@timdorr ah thanks! I thought it has the same API as DOM API. That would be great, but oh well...

Thanks!
