### ISSUE TITLE
Typing for useRouteMatch is not nice to use in TS strict mode

### ISSUE THREAD

**Issue by capaj** [ReactTraining/react-router#7449]
currently typing for `useRouteMatch` always returns `match<Params> | null` which is not ergonomic when using TS strict mode.
To satisfy the compiler , we now have to write:
```ts
  const orgDetailPath = '/organisation/:organisationId'
  const { params } = useRouteMatch(orgDetailPath) as match<{
    organisationId: string
  }>
```

or 
```ts
  const orgDetailPath = '/organisation/:organisationId'
  const match = useRouteMatch<{
    organisationId: string
  }>(orgDetailPath)
  if (!match) {
   return null
  // we could throw some kind of an error here that the component is used in wrong url path, but that is superflous, because if we omit this error handling the error on the destructuring is descriptive enough for any average programmer to understand
  }
  const { params } = match
```
It would be better, if the typing always returned the provided generic argument without nullability. Many other libraries do it like that when interfacing with type unsafe interfaces.
The routing with string paths cannot be made 100% typesafe as the TS compiler will never understand the route match strings. So in this case it is okay to rely on the user to trust that the generic argument is correct in the current context.

**Comment by timdorr** [comment]
The types for 5.x aren't maintained here. Consult the support resources for DefinitelyTyped, which is where they are written and maintained.
