### ISSUE TITLE
Status on upgrading `path-to-regexp`?

### ISSUE THREAD

**Issue by JamyGolden** [ReactTraining/react-router#7450]
## Version
5.2.0

## Problem
Any update on upgrading `path-to-regexp`?
There are issues with `path-to-regexp` >=2.0.0 and react-router https://github.com/ReactTraining/react-router/issues/5469

@mjackson mentioned that he would look into it since he doesn't like `""` resolving to `"/"`: https://github.com/ReactTraining/react-router/pull/5470#issuecomment-329023066

Both the issue and the PR have been closed so I'm unable to comment and follow up there.

**Comment by timdorr** [comment]
We're not planning on it. The 1.7.0 release works just fine. Old code != bad code.

However, v6 drops the dependency entirely, so it's going away for future versions.

**Comment by JamyGolden** [comment]
Cool, yeah old code !== bad cod. Having version issues with latest versions of `react-router` and `local-web-server` due to the dependency. Yay for v6 😊

**Comment by HTMLGhozt** [comment]
Not to grave dig, I also have issues when trying to use `@koa/router` and `react-router` in a yarn monorepo.
