### ISSUE TITLE
withRouter(withTracker(... not working in 5.2

### ISSUE THREAD

**Issue by RealHandy** [ReactTraining/react-router#7453]
## Version

5.2

## Test Case

none

## Steps to reproduce

1. Have a Meteor app that is using the `withRouter(withTracker(...` syntax and working properly with ReactRouter 4.3.1 or 5.1
2. Update with `npm i react-router@5.2 react-router-dom@5.2`

## Expected Behavior
It still works.

## Actual Behavior
This error: `You should not use <Route> outside a <Router>`
and in the devtools console, the stack says that it's doing things with `"withRouter(undefined)"`

**Comment by RealHandy** [comment]
I think I'm reporting a bug that 5.2 doesn't work when 4.3.1 and 5.1 do work, regarding withRouter(withTracker(...

**Comment by MeiKatz** [comment]
Looks like an error with `withTracker()` and not with RR

**Comment by RealHandy** [comment]
You think? It works fine in RR 4.3.1 and 5.1, but updating to 5.2 breaks it w/o changing any code?
