### ISSUE TITLE
Router with custom history doesn't render route, only URL is updated

### ISSUE THREAD

**Issue by kolodziejczakM** [ReactTraining/react-router#7455]
## Version

5.2.0

## Test Case

https://github.com/kolodziejczakM/cra-router-dom-custom-history

## Steps to reproduce

1. `npx create-react-app demo-app`
2. `cd demo-app`
3. `yarn add react-router-dom`
4. `yarn add history`
5. Open `src/App.js` and replace existing code with this: 

```
import React from 'react';
import { Router, Route, Link, Switch } from 'react-router-dom';
import { createBrowserHistory } from 'history';

function Home() {
  return <h2>Home</h2>;
}

function About() {
  return <h2>About</h2>;
}

function Users() {
  return <h2>Users</h2>;
}


const history = createBrowserHistory();

export default function App() {

  return (
    <Router history={history}>
      <div>
        <nav>
          <ul>
            <li>
              <Link to="/">Home</Link>
            </li>
            <li>
              <Link to="/about">About</Link>
            </li>
            <li>
              <Link to="/users">Users</Link>
            </li>
          </ul>
        </nav>

        {/* A <Switch> looks through its children <Route>s and
            renders the first one that matches the current URL. */}
        <Switch>
          <Route path="/about">
            <About />
          </Route>
          <Route path="/users">
            <Users />
          </Route>
          <Route path="/">
            <Home />
          </Route>
        </Switch>
      </div>
    </Router>
  );
}
```
6. `yarn start`

## Expected Behavior

After clicking on Link: URL is updated, but also corresponding route is rendered.

## Actual Behavior

After clicking on Link: URL is updated, route isn't rendered at all.

**Comment by timdorr** [comment]
You're using the wrong version of `history`. 5.x/4.x of Router are only compatible with history 4.x.

**Comment by GendelfLugansk** [comment]
@timdorr I see the same bug using history 4.0.0

**Comment by tpoppen** [comment]
Compatible versions should be included in the documentation here: https://reactrouter.com/web/api/Router 
Currently there is no mention of this, and I spent a decent bit of time trying to figure out why the api wasn't working as described. Changing my history dependency to 4.x worked. But the only reference to this solution is this git issue.
