### ISSUE TITLE
feature request - sub routes component

### ISSUE THREAD

**Issue by KutnerUri** [ReactTraining/react-router#7459]
In my app, I am nesting a lot of routes, from different places.

```tsx
//  overview page
//...
subRoutes.push({ path: '/overview', children: <Overview/>});

// details page
// ...
subRoutes.push({ path: '/details', children: <Details/>} );

// main page
const { path } = useRouteMatch();
return (
  <Switch>
    {subRoutes.map( x => <Route {...x} path={`${path}/${x.path}Ï}/>}
  </Switch>
);
```

distilling this a bit, I arrive at this function:
```tsx
import { useRouteMatch, Route, RouteProps } from 'react-router-dom';

export function SubRoute(props: RouteProps) {
  const { path } = useRouteMatch();
  const fullPath = `${path}/${props.path}`;

  return <Route {...props} path={fullPath} />;
}
```

The logic works, but it doesn't seem to work under `<Switch/>`, and the subroutes don't render at all.
I'm assuming this is because Switch only works with immediate children.

Not sure that it fits with the ReactRouter5 philosophy, but `<SubRoute/>` could be a nice addition.

**Comment by timdorr** [comment]
Yes, Switch works by looking at the props of it's children, so they need to be directly available to it (same render). But this doesn't really make sense with the way v5 is built. You should just use react-router-config here.

**Comment by KutnerUri** [comment]
The example is oversimplified, I want dynamic links, and react-router-config is static.

I ended up creating a custom switch like so:
```tsx
export addRoute(route) {
  //OVERSIMPLIFIED! this is not the real code
  setRoutes(routers.concat(route));
}

function Routing() {
  const [routes, setRoutes] = useState([]);

  return <SubRouter routes={routes}>
}

export function SubRouter({ routes }: { routes: RouteProps[] }) {
  const { path: basePath } = useRouteMatch();

  return (
    <Switch>
      {routes.map((route, idx) => (
        <Route key={idx} {...route} path={ExtendPath(basePath, route.path)} />
      ))}
    </Switch>
  );
}
