### ISSUE TITLE
[v6] Incorrect warning that `navigate` should be called in a `useEffect`

### ISSUE THREAD

**Issue by andycarrell** [ReactTraining/react-router#7460]
## Version

react-router-dom: 6.0.0-beta.0
react: 16.13.1
react-dom: 16.13.1

## Test Case

https://codesandbox.io/s/react-router-should-call-navigate-rt7qj?file=/index.js

## Steps to reproduce

Use the 'setParams' from `useSearchParams`, but wrap it and pass from a parent consumer to a child:

`const [params, setParams] = useSearchParams()`

## Expected Behavior

Set params updates the search params, and there are no warnings in the console

## Actual Behavior

Search params are not updated, warning in the console about calling navigate in a useEffect:
```
You should call navigate() in a useEffect, not when your component is first rendered. 
    in ChildBroken (at index.js:42)
    in Parent (at index.js:78)
    in Home (at index.js:67)
    in App (at index.js:91) 
```

**Comment by lneves12** [comment]
I am seeing the exact same problem. The search parameters are not being updated and I see the exact same warning

**Comment by hyochan** [comment]
Any updates? I am experiencing this in `test` code.

**Comment by andycarrell** [comment]
As an FYI, coming up to the year anniversary of this issue I guess it's worth noting that I'm still seeing the original warning (at least) `You should call navigate() in a useEffect` - even though, we've been using the beta in production for that time and never had a user facing issue 🤷 - not sure what to make of that one.

**Comment by rojserbest** [comment]
Same problem

**Comment by isimmons** [comment]
Same warning here. Using hoc to get useNavigate in a class component and then return the user to the not-found url if a movie does not exist.

`componentDidMount() {
    const { id } = this.props.params;
    const { navigate } = this.props;

    const genres = getGenres();
    this.setState({ genres });

    if (id === 'new') return;

    const movie = getMovie(id);
    if (!movie) return navigate('/not-found', { replace: true });

    this.setState({ data: this.mapToViewModel(movie) });
  }`

**Comment by lqsbznh** [comment]
Maybe componentDidMount is rendered after useEffect, so `activeRef.current = false` in the source code.
You can fix it like this

> 
> ```
> componentDidMount() {
>     const { id } = this.props.params;
>     const { navigate } = this.props;
> 
>     const genres = getGenres();
>     this.setState({ genres });
> 
>     if (id === 'new') return;
> 
>     const movie = getMovie(id);
>     if (!movie) return setTimeout(() => {navigate('/not-found', { replace: true })}, 0)
> 
>     this.setState({ data: this.mapToViewModel(movie) });
>   }
> ```

**Comment by mcsimps2** [comment]
This issue should be reopened.  I'm also facing this warning from using `useSearchParams`.

**Comment by joshribakoff-sm** [comment]
I'm also getting this error, also when passing the callback down the tree. I see in the source code you bail out of applying the `navigate()` if a ref is `false` ([which normally gets set to `true` is a `useEffect` hook](https://github.com/remix-run/react-router/blob/0f9435a8134b2b5dddfd716a18d17aefe4461fe1/packages/react-router/lib/hooks.tsx#L155-L158)).

In my case, I'm just passing a curried callback down the tree. The `useEffect` of my child component runs prior to the effects of the parent component, and I guess `react-router-dom` will only flip that flag when the effect of the parent component runs.

It appears to me `react-router-dom` is trying to use a heuristic that is too brittle, which is preventing a valid and pretty necessary use case.

Why is this closed @mjackson @timdorr ?

**Comment by shamseerahammedm** [comment]
@isimmons does navigate work for you ? it doesnt for me i also get this warning , i am using using HOC to inject navigate to class component

**Comment by Haraldson** [comment]
I’m also getting this when using `navigate` from a class component. I wonder if `requestAnimationFrame` would also work? Still a code smell, but feels closer to its intended use.
