### ISSUE TITLE
feature request: Expose a way to selectively re-render from router changes in ReactRouter 6

### ISSUE THREAD

**Issue by Alphy11** [ReactTraining/react-router#7463]
We have been toying around with React Router 6, and are loving the interface.  Super excited!

I have found a bit of a gap though we had to work around.  Previously, when we could use a global history, we could manually listen to the url.  But now that it is going away, we have no way to have a component listen to only a certain piece of the url.

See the below hook we use to read from the URL.
```tsx
export default function useLocation<
    T,
    Q extends Record<string, string | string[]>
>(selector: (location: Location<Q>) => T): T {
    const browserHistory = getBrowserHistory<Q>();

    const curentSelection = selector(
        browserHistory.getCurrentLocation() as Location<Q>
    );

    const forceUpdate = useForceUpdate();
    const previousSelection = useRef<T>(curentSelection);

    useEffect(() => {
        const unsubscribe = browserHistory.listen((location: Location<Q>) => {
            const selection = selector(location);
            if (!shallowEqual(selection, previousSelection.current)) {
                forceUpdate();
                previousSelection.current = selection;
            }
        });
        return () => unsubscribe();
    }, [forceUpdate, selector, browserHistory]);

    return curentSelection;
}

```
This forces the component to update if the specific piece of the location it cares about is updated, not every time location is updated.  But now that we cannot access the same history object react router uses we cannot achieve this without some hacks, like accessing history on our own.

A couple of solutions:
1: Allow useLocation to take in a selector, and only cause a rerender if the selector returns a new value.
2: Expose history(or at least the listen function) via context or a hook so we can kick off our own events from the listeners.

**Comment by timdorr** [comment]
You can still use your own history. You just have to `listen` on your own and pass that into `Router` now. You can do what BrowserRouter does: https://github.com/ReactTraining/react-router/blob/dev/packages/react-router-dom/index.tsx#L92-L117

**Comment by andresgutgon** [comment]
@timdorr is this the recomended way? We are on react-router 3.x and we are planing to migrate to 6.x during this year. I'm trying to remove all deprecated APIs that we use from 3.x. For instance we use this
``` javascript
import { browserHistory } from 'react-router

// ...later in my component
const location = browserHistory.getCurrentLocation()
```

I understand this way of accessing current location will not be available on 6.x right?

**Comment by timdorr** [comment]
You should use the `useLocation` hook instead.
