### ISSUE TITLE
useParams depends on multiple path order

### ISSUE THREAD

**Issue by jbdemonte** [ReactTraining/react-router#7468]
## Version

5.1.2

## Test Case

https://codesandbox.io/s/react-router-89vgr?file=/index.js:0-936

## Steps to reproduce

Click on `Client : Create`

## Expected Behavior

`:action` should be defined

## Actual Behavior

`:action` stay undefined

## Informations

This seems to be due to the path order in the route:

`:action` stay undefined with this declaration:
```
   <Route path={['/clients', '/clients/:action']} component={Clients} />
```

If I reverse the path order with :

```
   <Route path={[ '/clients/:action', '/clients']} component={Clients} />
```

It works like a charm

**Comment by timdorr** [comment]
That's because it's matching the `/clients` route first. If you use the `exact` prop, this will go away.

**Comment by jbdemonte** [comment]
Ok, thanks

I was confused because I didn't understood at this moment why `path='/clients/:action'` didn't do the tricks for both routes
