### ISSUE TITLE
[Website] Link/Docs broken

### ISSUE THREAD

**Issue by ljosberinn** [ReactTraining/react-router#7470]
Confirmed that it's broken on at least 3 devices, so it's not cache or something.

https://reacttraining.com/react-router/
- click on Web

or go directly to https://reacttraining.com/react-router/web

![image](https://user-images.githubusercontent.com/29307652/86404032-1e304500-bcaf-11ea-9102-3cf5639a1b65.png)

**Comment by timdorr** [comment]
Not getting this locally. You might have some sort of extension blocking it?

**Comment by ljosberinn** [comment]
No, this in guest mode without any extensions active, I have it on phone too and initially it wasn't me noticing this but someone on discord.

**Comment by Xesued** [comment]
I can confirm, I'm getting the same issue.
