### ISSUE TITLE
[feature request] - remountOnParamChange prop for Route component

### ISSUE THREAD

**Issue by ctbucha** [ReactTraining/react-router#7471]
Right now, the Route component does not remount its children components (which makes sense as a reasonable default behavior in React). However, sometimes it is useful to remount the children components of the Route component when the query params change. E.g. if the user navigates from the location `/users/1` to `/users/2`, it may seem reasonable to the developer that the users detail page should remount since the application will be displaying a different page to the user.

### Current workaround
```
function Remount({ children }) {
  const params = useParams();
  return React.cloneElement(
    React.Children.only(children),                                
    { key: JSON.stringify(params) }  
  );
}

<Route path="users/:id">
  <Remount><UserDetail /></Remount>
</Route>
```

### Feature request
Add a `remountOnParamChange` prop to the `Route` component to remount the child props of `Route` when the params change.

**Comment by timdorr** [comment]
This isn't how React is designed to work. You should build your components to respond to props changes and not depend on being remounted/reinstantiated.
