### ISSUE TITLE
[website] "Information" is partially hidden

### ISSUE THREAD

**Issue by ChaituKNag** [ReactTraining/react-router#7472]
Pertaining to this URL: https://reactrouter.com/web/guides/server-rendering

The heading text `Adding app specific context information` is hidden under the right side pane.

## Steps to reproduce

Simply go to this page in a PC or a MAC browser

## Expected Behavior

Should look like this:

![image](https://user-images.githubusercontent.com/13428505/86477327-d15b7580-bd65-11ea-8189-07e3cd2dfb96.png)

## Actual Behavior

Looks like heading text is partially hidden:

![image](https://user-images.githubusercontent.com/13428505/86477433-0d8ed600-bd66-11ea-9419-f4547ab22e92.png)

**Comment by ChaituKNag** [comment]
I can raise a fix PR if the issue is approved.

**Comment by timdorr** [comment]
You can always open a PR. No need to get approval from anyone.
