### ISSUE TITLE
[v6] use of <Link> broke on upgrade to 6.0.0-beta.0 from alpha.3

### ISSUE THREAD

**Issue by kcoyner** [ReactTraining/react-router#7478]
## Version
react-router and react-router-dom: 6.0.0-beta.0
react and react-dom: 16.13.1

Using 6.0.0-beta.0, the following link worked:

```
<Link to={`/s/${inc.slug}/${uslug}`} key={inc.slug}>
```
After upgrading to alpha.3, it produced the following error:
```
Warning: Failed prop type: The prop `location` is marked as required in `Router`, but its value is `undefined`.
```
I've downgraded back to alpha.3 and have it working again but would like to figure out why it breaks on the upgrade.

**Comment by timdorr** [comment]
Can you provide a reproduction of this in codesandbox.com?

**Comment by mavidalma** [comment]
R
