### ISSUE TITLE
Redirection fails without error

### ISSUE THREAD

**Issue by jbdemonte** [ReactTraining/react-router#7483]
## Version

5.2.0

## Desc

When I tried at first to create a codepen, I finally got an error which help me a bit: https://codesandbox.io/s/react-router-g7j9e?file=/index.js

Searching it, I end on this comment: https://github.com/ReactTraining/react-router/issues/7015#issuecomment-548420654

> You can't use any of the hooks from within the same component that puts the Router into the tree

And it seems correct, I fixed my issue, but I failed finding it in the documentation, is there anything somewhere about this limitation? the hooks documentation page does not provide any info about it (maybe i misread it)

## Test Case

This code does not log any error on my side, while it does on codepen with the same library versions

```
import React from 'react';
import { BrowserRouter as Router, Link, Route, Switch, useRouteMatch, useHistory } from 'react-router-dom';

const Clients = () => {
  const history = useHistory();
  let { path } = useRouteMatch();
  return (
    <div>
      <h1>Clients</h1>
      <Router>
        <Switch>
          <Route exact path={`${path}/create`} render={() => <button onClick={() => history.push(path)}>ok</button>} />
          <Route exact path={path} render={() => <Link to={`${path}/create`}>Créer</Link>} />
        </Switch>
      </Router>
    </div>
  );
};

export default Clients;

```
## Steps to reproduce

click on the [OK] button to go back to the main route

## Expected Behavior

Go Back to the main route

## Actual Behavior

Stay on the same page while the url change or throw an error

Thanks for your help

**Comment by MeiKatz** [comment]
That's not a limitation of React Router but React itself, because that's the way the Context api works.

**Comment by timdorr** [comment]
Yes, you have to have your Router outside of any component that uses hooks.

**Comment by jbdemonte** [comment]
Yes, I get it, but I was hoping to find more information
