### ISSUE TITLE
[v6.0.0-beta.0] The routing address cannot match exactly

### ISSUE THREAD

**Issue by world56** [ReactTraining/react-router#7485]
## Version

react-router-dom: 6.0.0-beta.0
react: 16.13.1
react-dom: 16.13.1

## Test Case

https://codesandbox.io/s/react-router-6-issue-wysyg?file=/src/App.js

## Steps to reproduce

I have two routing components, "/user/" and "/userPro/",
but The URL is "/userPro/" and it points to “/user/”

## Expected Behavior

The URL 'userPro/u1' should point to the 'u1' component instead of the 'user' component

## Actual Behavior

Routing component matching error

**Comment by rstrand** [comment]
I can get your example working by swapping the order of the user and userPro routes.

**Comment by timdorr** [comment]
Yeah, this is just a specificity problem. The most specific route should go first.

**Comment by world56** [comment]
> Yeah, this is just a specificity problem. The most specific route should go first.

There will be no such problem in V5 version. How can I design my route? Thank you
