### ISSUE TITLE
[v6.0.0-beta.0] Can't resolve 'history'

### ISSUE THREAD

**Issue by sketchnotes** [ReactTraining/react-router#7487]
## Version

react-router-dom@6.0.0-beta.0
@types/react-router-dom@5.1.5

## Test Case

```
// App.tsx

import React from 'react';
import { BrowserRouter, Routes, Route } from "react-router-dom";
import { AppIntro } from './pages/app-intro';
import { Settings } from './pages/settings';

function App() {
  return (
    <div className="App">
      <BrowserRouter>
        <Routes>
          <Route path='/' element={<AppIntro />} />
          <Route path='/settings' element={<Settings />} />
        </Routes>
      </BrowserRouter>
    </div>
  );
}

export default App;
```

## Steps to reproduce
1) create a react project `yarn create react-app app --template typescript`
2) install `react-router-dom@5.2.0`
3) read an article [The Future of React Router and @reach/router](https://reacttraining.com/blog/reach-react-router-future/)
4) remove `react-router-dom@5.2.0`
5) install 'advance' solution `@reach/router`
6) adapt the code
7) get notification about 'advance-advance' solution [React Router v6 Preview](https://reacttraining.com/blog/react-router-v6-pre/#introducing-routes)
8) remove 'advance' solution `@reach/router`
9) install 'advance-advance' solution `react-router-dom@6.0.0-beta.0`
10) adapt the code
11) get an 'advance-advance' error
12) hope to see an 'advance-advance-advance' solution `@reach/react-router-dom@f***`

## Expected Behavior
working code

## Actual Behavior
```
Failed to compile.

./node_modules/react-router/index.js
Module not found: Can't resolve 'history' in '/home/app/node_modules/react-router'
```

**Comment by timdorr** [comment]
You need to install `history` as a dependency. It's listed as a peer dep, so yarn would have notified you about this.
