### ISSUE TITLE
Attempted import error: 'Routes' is not exported from 'react-router-dom'.

### ISSUE THREAD

**Issue by inshalayaz** [ReactTraining/react-router#7490]
```js
import React from 'react';
import './App.css';
import { BrowserRouter, Routes , Route } from 'react-router-dom'
import Header from './components/Header'
import Home from './components/Home'
import Products from './components/Products'


function App() {
  return (
    <BrowserRouter>
    <div className="App">
        <Header />  
        <Routes>
          <Route path='/' element={<Home />}></Route>
          <Route path='products' element={<Products />}></Route>
        </Routes>    
    </div>
    </BrowserRouter>
  );
}

export default App;
```
![issue](https://user-images.githubusercontent.com/52293580/86748001-969f5900-c055-11ea-8389-bae3840fefea.JPG)

I'm trying to use react routes and it says import error

**Comment by timdorr** [comment]
Make sure you're using React Router v6.

**Comment by akmalick** [comment]
@timdorr  **React Router v6** is still in [**beta**](https://github.com/ReactTraining/react-router/releases/tag/v6.0.0-beta.0) . Do you suggest using that in a production grade app. 
I see that **5.2.0** has been inconsistent and breaking for all major versions of node.  At first I though this to be a node-version compatibility issue since I was using latest LTS. **V6** works fine in my case but I am wary of using it in production. 
How to get around this? 
I also couldn't find the schedule for the stable release of **V6**.

**Comment by timdorr** [comment]
v5 is working just fine for all versions of Node and browsers they we know about. I'm not sure where you're getting that impression, but it's in use by many very popular applications (Twitter, for instance) as we speak.

**Comment by akmalick** [comment]
I get you but in my case I get below error no mater what I try. Only the V6 beta seems to work.

![image](https://user-images.githubusercontent.com/5765159/111731497-99677480-8899-11eb-9c23-a5b948955968.png)

```javascript

import logo from "./logo.svg";
import "./App.css";
import { Routes, BrowserRouter as Router, Route } from "react-router-dom";
import { Home, GetDetails, NotFound } from "./pages";
import { Provider } from "react-redux";

function App() {
  return (
    <div>
      {/* <Provider> */}
      <BrowserRouter>
      <Routes>
        <Route path="/" element={<Home />} />
        <Route path="app-2/element-details" element={<GetDetails />} />
        <Route path="*" element={<NotFound />} />
      </Routes>
      </BrowserRouter>
      {/* </Provider> */}
    </div>
  );
}

export default App;


```

```javascript

import logo from "./logo.svg";
import "./App.css";
import { Routes, Router, Route } from "react-router-dom";
import { Home, GetDetails, NotFound } from "./pages";
import { Provider } from "react-redux";

function App() {
  return (
    <div>
      {/* <Provider> */}
      <Routes>
        <Route path="/" element={<Home />} />
        <Route path="app-2/element-details" element={<GetDetails />} />
        <Route path="*" element={<NotFound />} />
      </Routes>
      {/* </Provider> */}
    </div>
  );
}

export default App;

```

Using 5.2.0, none of the above works for me. I get same error in both cases. 


My package.json:

```javascript

    "react-router": "^5.2.0",
    "react-router-dom": "^5.2.0",

```

I'm really not getting the essence. Nothing seems to work.

**Comment by timdorr** [comment]
You're attempting to use the v6 API with v5. `Routes` is new in v6. You are getting that error because it doesn't exist in older versions.

**Comment by akmalick** [comment]
Thanks for the guidance. I'll make the changes.
