### ISSUE TITLE
where is the wiki ?

### ISSUE THREAD

**Issue by jerome-diver** [ReactTraining/react-router#7491]
I'm searching for your wiki page.

**Comment by timdorr** [comment]
We don't have one.

**Comment by jerome-diver** [comment]
do you plan to make one ?

**Comment by timdorr** [comment]
Nope.

**Comment by jerome-diver** [comment]
@timdorr 
i find this: [react-router help](https://reactrouter.com/web/)
so now, you can share with users who ask for wiki, this link.
There is also a kind of API viewer.
Maybe you want to add it to your README file.
