### ISSUE TITLE
Are floating routes deprecated?

### ISSUE THREAD

**Issue by hinok** [ReactTraining/react-router#7493]
### I want to ask whether using floating `Route` is allowed or not. Is it going to work in v6?

The blog post https://reacttraining.com/blog/react-router-v5-1/#useroutematch recommends replacing floating routes with `useRouteMatch`.

> Replace any "floating" (not inside a <Switch>) <Route> elements with useRouteMatch

If I do this, `useParams` "doesn't work anymore" as I'd expect. I have a special use case when I have to implement routable modals.

**Demo:** https://codesandbox.io/s/react-router-modal-gallery-smm2r?file=/example.js

Comment/uncomment this part of code to see the issue.

```jsx
      {/*
        It seems that this pattern is not recommended because this is "floating route"
        and should be replaced with useRouteMatch
        @source https://reacttraining.com/blog/react-router-v5-1/#useroutematch
      */}
      {/* <Route path="/gallery/:id">
        <Modal />
      </Route> */}

      <FloatingRoute path="/gallery/:id">
        <Modal />
      </FloatingRoute>
```

Below is minimum of code that shows the problem (it's copied from [the demo](https://codesandbox.io/s/react-router-modal-gallery-smm2r?file=/example.js))

**App**

```jsx
    <Switch>
      <Route exact path="/" children={<Home />} />
      <Route path="/gallery" children={<Gallery />} />
    </Switch>
```

**Gallery**

```jsx
const FloatingRoute = ({ path, strict, sensitive, children }) => {
  const match = useRouteMatch({
    path,
    strict,
    sensitive
  });

  return match ? children : null;
};

FloatingRoute.defaultProps = {
  strict: false,
  sensitive: false
};

function Gallery() {
  return (
    <div>
      {IMAGES.map(i => (
        <Link key={i.id} to={`/gallery/${i.id}`}>
          <Thumbnail color={i.color} />
          <p>{i.title}</p>
        </Link>
      ))}

      {/*
        It seems that this pattern is not recommended because this is "floating route"
        and should be replaced with useRouteMatch
        @source https://reacttraining.com/blog/react-router-v5-1/#useroutematch
      */}
      {/* <Route path="/gallery/:id">
        <Modal />
      </Route> */}

      <FloatingRoute path="/gallery/:id">
        <Modal />
      </FloatingRoute>
    </div>
  );
}
```

**Modal**

```jsx
function Modal() {
  let history = useHistory();
  let params = useParams(); // If FloatingRoute is used then this will be an empty object

  const match = useRouteMatch({
    path: "/gallery/:id" // The only way to retrieve params in such case is to use again useRouteMatch and provide path...
  });

  console.log({
    params: JSON.stringify(params),
    matchParams: JSON.stringify(match.params)
  });
```

It feels a bit wrong because:
- `useRouteMatch` needs to be used twice: once in `FloatingRoute` and again in a nested component (in this case `Modal`)
- `useParams` won't work so `useRouteMatch` needs to used again and we have to somehow pass original `path`

**Comment by timdorr** [comment]
Yes, this the direct we're headed. Simplest thing to do is just wrap the single Route in Routes.
