### ISSUE TITLE
[v6] types for react-router and react-router-dom

### ISSUE THREAD

**Issue by sumanthratna** [ReactTraining/react-router#7494]
## Version

6.0.0-beta.0

## Test Case

n/a

## Steps to reproduce

1. create a typescript project with create-react-app
2. try to install `@types/react-router-dom@6.0.0-beta.0` (fails because types haven't been updated)

## Expected Behavior

- `yarn add @types/react-router-dom@6.0.0-beta.0` works without errors because there's a version for v6 on the npm registry
- I can import and use the new props and elements from v6, such as `Routes`

## Actual Behavior

- the installation of types fails
- because I don't have the v6 types, I can't implement the prop rename from `component` to `as` (fortunately `element` is available)
- because I don't have the v6 types, I can't import `Routes` because typescript thinks `Switch` still exists

**Comment by timdorr** [comment]
The types are included in v6. You don't need the separate @types package.

**Comment by sumanthratna** [comment]
Thanks for the quick reply. I'll comment here because I think it's related:

Do you know why `yarn run start` results in the following?
```
Module '"../.yarn/cache/@types-react-router-dom-npm-5.1.5-b0a728cc6d-3.zip/node_modules/@types/react-router-dom"' has no exported member 'Routes'. Did you mean 'Route'?  TS2724

    1 | import React, { Suspense, lazy } from "react";
    2 | 
  > 3 | import { BrowserRouter as Router, Routes, Route } from "react-router-dom";
      |                                   ^
    4 | 
```

**Comment by sumanthratna** [comment]
Oh, this is a simple fix. Just `yarn remove @types/react-router-dom`. @timdorr should I add create a PR to add this to the upgrade guide doc?
