### ISSUE TITLE
Unable to bind state types to useLocation

### ISSUE THREAD

**Issue by tconroy** [ReactTraining/react-router#7498]
Currently, it is not possible to safely type custom `state` values for the `Location` object returned by the `useLocation` hook. This is because the State generic is never properly bound from the hook direction.

## Version

`6.0.0-beta.0`

## Steps to reproduce
In a typescript project,

```tsx
import { Location } from 'history';
import { useLocation } from 'react-router-dom';

interface MyState {
  someValue: boolean;
}

function App() {
  const { state }: Location<MyState> = useLocation();
}

```

## Expected Behavior

TypeScript compiles the above successfully without warnings.

## Actual Behavior

Typescript throws the following error:
```
TS2322: Type 'Location<State>' is not assignable to type 'Location<MyState>'.
  Type 'State' is not assignable to type 'MyState'.
    Type 'null' is not assignable to type 'MyState'.
```

**Comment by timdorr** [comment]
https://github.com/ReactTraining/react-router/pull/7326#issuecomment-626418225
