### ISSUE TITLE
BrowserRouter adds staticContext prop

### ISSUE THREAD

**Issue by zmeyc** [ReactTraining/react-router#7501]
BrowserRouter adds staticContext to props which causes warnings if props are passed to other components. As I understand from docs, this prop should only be added for StaticRouter when using SSR?

## Version

5.2.0

## Test Case

https://codesandbox.io/s/react-router-xty8c?file=/index.js

## Steps to reproduce

Pass props to underlying component:

```
function Home(props) {
  return (
    <div {...props}>
      <h2>Home</h2>
    </div>
  )
}

...

<Route exact path="/" component={Home} />
```

## Expected Behavior

No warnings.

## Actual Behavior

```
Warning: React does not recognize the `staticContext` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `staticcontext` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in div (at index.js:34)
    in Home (created by Context.Consumer)
    in Route (at index.js:24)
    in div (at index.js:9)
    in Router (created by BrowserRouter)
    in BrowserRouter (at index.js:8)
    in App (at index.js:78)
```

**Comment by timdorr** [comment]
You shouldn't blindly apply all the props passed to a component to a plain DOM element. We also include `history`, `location`, and `match`, all of which are invalid for the DOM.
