### ISSUE TITLE
[v6] Following migration guide results in `Module not found: Error: Can't resolve 'history' in ....`

### ISSUE THREAD

**Issue by fdjones** [ReactTraining/react-router#7502]
Node version: v12.18.2
npm version: 6.14.5

I've followed the migration steps outlined here: https://github.com/ReactTraining/react-router/blob/dev/docs/advanced-guides/migrating-5-to-6.md#upgrade-to-react-router-v6

Installation seems to go fine, but when I try to actually run my app locally (using webpack-dev-server) I get:

```
ERROR in ./node_modules/react-router/index.js
Module not found: Error: Can't resolve 'history' in '/.........../node_modules/react-router'
 @ ./node_modules/react-router/index.js 1:0-58 3:110-129 8:79-85 16:61-70 21:62-71
 @ ./node_modules/react-router-dom/index.js
 @ ./client/index.js

ERROR in ./node_modules/react-router-dom/index.js
Module not found: Error: Can't resolve 'history' in '/.........../node_modules/react-router-dom'
 @ ./node_modules/react-router-dom/index.js 1:92-163 4:85-105 5:85-102 6:427-437 6:443-453
 @ ./client/index.js
```

I don't think it's related to webpack-dev-server as running `webpack --mode production` also results in the same error. The relevant packages I have listed in my package.json:

```
    "react": "^16.13.0",
    "react-router": "^6.0.0-beta.0",
    "react-router-dom": "^6.0.0-beta.0",
```

Really like the new v6 API so any help here would be greatly appreciated.

Thanks!

**Comment by timdorr** [comment]
You need to also install the `history` library. I added a note about this to the docs.

**Comment by fdjones** [comment]
Great, thank you.
