### ISSUE TITLE
[v6] useParams returns an empty object during testing 

### ISSUE THREAD

**Issue by kurylenkoigor** [ReactTraining/react-router#7504]
## Version

6.0.0-beta.0

## Steps to reproduce

I'm trying to test a component 
```js
<Route path="profile-activation/:profileToken" element={<ProfileActivation />}/>
```

which in turn is rendered under parent 
```js
<Route path="auth/*" element={<Auth />} />
```

When I'm trying to access **useParams()** in the tests, it returns an empty object. However, **useLocation()** works fine at the same time and returns an object with the relative data

Here you can see two consoles, first one has failed to log **useParams()**, second one succeeded with **useLocation()**;

```
    console.log
      {}

      at ProfileActivationForm (src/features/Auth/components/ProfileActivation/ProfileActivationForm/ProfileActivationForm.tsx:52:11)

    console.log
      {
        pathname: '/auth/profile-activation/token123',
        search: '',
        hash: '',
        state: null,
        key: 'iwq4xdri'
      }

      at ProfileActivationForm (src/features/Auth/components/ProfileActivation/ProfileActivationForm/ProfileActivationForm.tsx:53:11)
```

This is my component in the tests:

```js
<MemoryRouter initialEntries={['/auth/profile-activation/token123']}>
      <Route
          path="/auth/profile-activation/:profileToken"
          element={<ProfileActivation />}
       />
</MemoryRouter>
```

 
## Expected Behavior

**useParams()** returns an object with relative data, for ex. ```{ profileToken: 'token123' }```

## Actual Behavior

**useParams()** returns an empty object

**Comment by timdorr** [comment]
You aren't wrapping in a `Routes`. You need that around all `Route` components.

**Comment by kurylenkoigor** [comment]
My bad :( thank you

**Comment by tranhaminh91** [comment]
i got the same issue. What do you mean "You aren't wrapping in a Routes"?

**Comment by ericmatte** [comment]
> You aren't wrapping in a Routes. You need that around all Route components.

@tranhaminh91 I think he means wrapping in a `Route` (no `s`).
For me, that was what fixed the issue.

Your `useParams()` must be inside a children component of at least one `Route` component.

**Comment by artem-galas** [comment]
I have the same issue, didn't manage to make it work with V6

**Component:**

```
const Profile = () => {
  const { id } = useParams();

  return <div data-testid="for-testing">{id}</div>
}
```

**Tests** 
```
const { debug } = render(
	<MemoryRouter initialEntries={['/profile/1']}>
		<Route path="/profile/:id">
			<Profile/>
		</Route>
	</MemoryRouter>,
);
```

Result

```
<body>
  <div />
</body>
```

Where in Version 5 result is **expected**:

```
<body>
      <div>
        <div
          data-testid="for-testing"
        >
          1
        </div>
      </div>
</body>
```


Am I doing something wrong?

**Comment by artem-galas** [comment]
Read the migration guide one more time and realised that would be the **working** solution:

```
const { debug } = render(
			<MemoryRouter initialEntries={['/profile/1']}>
				<Routes>
					<Route path="/profile/:id">
						<Profile />
					</Route>
				</Routes>
			</MemoryRouter>,
		);
```

**Result:**

```
<body>
      <div>
        <div
          data-testid="for-testing"
        >
          1
        </div>
      </div>
    </body>
```

**Comment by andrerpena** [comment]
For those coming from Google, I had this problem when I accidentally did:

> import { useParams } from "react-router";

instead of 

> import { useParams } from "react-router-dom";

**Comment by Oumar-1** [comment]
> > You aren't wrapping in a Routes. You need that around all Route components.
> 
> @tranhaminh91 I think he means wrapping in a `Route` (no `s`). For me, that was what fixed the issue.
> 
> Your `useParams()` must be inside a children component of at least one `Route` component.

thanks this 'Your `useParams()` must be inside a children component of at least one `Route` component.'  realy help me realise the issue thank you again

**Comment by esteban-uo** [comment]
> For those coming from Google, I had this problem when I accidentally did:
> 
> > import { useParams } from "react-router";
> 
> instead of
> 
> > import { useParams } from "react-router-dom";
Thanks!!!

lessons learnt: don't trust blindly auto import from IDE's...
