### ISSUE TITLE
match.params returns empty even when URL contains params

### ISSUE THREAD

**Issue by divmgl** [ReactTraining/react-router#7507]
This is a duplicate of https://github.com/ReactTraining/react-router/issues/5870. Not sure why a two-year old issue related to this was closed six months ago when the problem still exists.

Here's some example code that I'm using right now which demonstrates this problem:

```jsx
const StatsSwitch = () => (
  <Switch>
    <Route path="/gods/all/:gameMode" component={AllGameModeSwitch} />
    <Route path="/gods/ranked/:gameMode" component={RankedGameModeSwitch} />
  </Switch>
)

const AllGameModeSwitch = () => (
  <Switch>
    <Route path="/gods/all/conquest" component={GameModeStats} />
    <Route path="/gods/all/joust" component={GameModeStats} />
    <Redirect to="/gods/all/conquest" />
  </Switch>
)

const GameModeStats = () => {
  const { gameMode } = useParams() // gameMode is undefined
}
```

## Workaround

```jsx
const GameModeStats = () => {
  const location = useLocation()
  const { params } = matchPath(location.pathname, {
    path: "/gods/:stat/:gameMode/:bracket?"
  })

  const { gameMode } = params // gameMode is properly populated
}
```

---

I'm opening a new thread to restart discussion on this. I lost many hours to this until I stumbled upon that old thread. I'm hoping we can create some action items from this issue. Some potential solutions:

* Add additional documentation which talks about this use case when using nested routes
* Use `React.Context` to keep track of params as long as nested routes continue to match

**Comment by timdorr** [comment]
`useParams()` works on the nearest ancestor `Route`. The one from `StatsSwitch` is getting overridden by `AllGameModeSwitch`, which doesn't have any params in the path. 

If you're hard-coding it, then you can switch from `component` to `children` and pass it as a prop. Then it's just `const gameMode = params.gameMode || props.gameMode`.
