### ISSUE TITLE
[v6] RouteProps type is not exported by react-router-dom package

### ISSUE THREAD

**Issue by ROiPinheiro** [ReactTraining/react-router#7508]
## Version

react-router-dom@^6.0.0-beta.0

## Test Case

codesandbox.io/s/react-router-zkmp8

## Steps to reproduce

Try import "RouteProps" from "react-router-dom" library

## Expected Behavior

Can be imported like other types.

## Actual Behavior

"Module '"../../node_modules/react-router-dom"' has no exported member 'RouteProps'.ts(2305)"

**Comment by timdorr** [comment]
Those are exported by `react-router`.

**Comment by knyzorg** [comment]
@timdorr Shouldn't everything exported by react-router be re-exported by react-router-dom?
