### ISSUE TITLE
How to write PrivateRoute component (extend example in documentation)

### ISSUE THREAD

**Issue by svdHero** [ReactTraining/react-router#7510]
Hi there,

inspired by [this example](https://reactrouter.com/web/example/auth-workflow) from the documentation, I was wondering how to write a simple component `PrivateRoute` with "Switch-Fall-Through" to the next route case.

I came up with something like:
```typescript
type PrivateRouteProps = RouteProps & {
  isLoggedIn: boolean;
};

function PrivateRoute({ isLoggedIn, children, ...rest }: PrivateRouteProps) {
  return (
    <Fragment>{isLoggedIn && <Route {...rest}>{children}</Route>}</Fragment>
  );
}
```

However, the behaviour is not how I expected it. The full code snippet is this:

```typescript
import React, { Fragment, useState } from "react";
import {
  BrowserRouter,
  Switch,
  Route,
  RouteProps,
  Link
} from "react-router-dom";

import "./styles.css";

type PrivateRouteProps = RouteProps & {
  isLoggedIn: boolean;
};

function PrivateRoute({ isLoggedIn, children, ...rest }: PrivateRouteProps) {
  return (
    <Fragment>{isLoggedIn && <Route {...rest}>{children}</Route>}</Fragment>
  );
}

export default function App() {
  const [isLoggedIn, setIsLoggedIn] = useState(true);
  const statusText = isLoggedIn ? "logged in" : "logged out";
  const buttonText = isLoggedIn ? "log off" : "log in";
  return (
    <BrowserRouter>
      <div className="App">
        <header>
          <p>You are {statusText}.</p>
          <button
            onClick={() => {
              setIsLoggedIn(!isLoggedIn);
            }}
          >
            {buttonText}
          </button>
        </header>
        <nav>
          <ul>
            <li>
              <Link to="/public">Public Page</Link>
            </li>
            <li>
              <Link to="/private-one">Private Page One</Link>
            </li>
            <li>
              <Link to="/private-two">Private Page Two</Link>
            </li>
          </ul>
        </nav>
        <main>
          <Switch>
            <Route path="/public">
              <h1>My Public Content</h1>
            </Route>
            {isLoggedIn && (
              <Route path="/private-one">
                <h1>My Private Content One</h1>
              </Route>
            )}
            <PrivateRoute isLoggedIn={isLoggedIn} path="/private-two">
              <h1>My Private Content Two</h1>
            </PrivateRoute>
            <Route path="*">
              <h1>404 Nothing here!</h1>
            </Route>
          </Switch>
        </main>
      </div>
    </BrowserRouter>
  )
}
```
[![Edit elegant-field-52940](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/elegant-field-52940?fontsize=14&hidenavigation=1&theme=dark)

Note that I used a somewhat manual approach with the route `/private-one` and the `PrivateRoute` component with route `/private-two`. However, when `isLoggedIn` is `false`, in the first case, I get a fall-through to the wildcard route, but in the second case, just an empty component is rendered.

Why is that? Is it because the `Route` components are on different nesting levels? How can I write a `PrivateRoute` that also has a fall-through behaviour like with the manual approach?
Maybe this would be worthwhile to add to the documentation, in case people don't want an auth-workflow with redirect (most would, though, I guess)?

**Comment by timdorr** [comment]
Switch reads its children's props directly, so whatever renders inside those children isn't used for choosing a route. You can use any component under a Switch technically, as long as it has a `path` prop. But that component's rendering won't be used for route selection.
