### ISSUE TITLE
Request: System.register module format

### ISSUE THREAD

**Issue by TheMcMurder** [ReactTraining/react-router#7514]
I currently need a `system.register` module of `react-router`. Is there any desire to add a new build target/module format to react router? If I worked on adding something like that is it something you'd be interested in merging? I have an alternative way to get what I need but in case others also needed it I wanted to start a discussion.

Some context: We're using SystemJS in our application, and while it supports UMD bundles in the import map it works better IMHO to use system module format. The good news is that rollup supports the format out of the box so it should in theory be as easy as adding a new build target to generate the module.

I understand if it's not something y'all want to maintain. Thanks for this and other projects.

**Comment by timdorr** [comment]
Unfortunately, we're not going to add this. The point of the UMD bundle is to work with many different types of loaders, including SystemJS. Since it already works for that and the general trend is towards ES modules long-term, it doesn't make sense to add this specific entry point. Sorry!

**Comment by TheMcMurder** [comment]
Thanks for the quick response. I'll pursue an alternative approach. 😀
