### ISSUE TITLE
[v6]`matchPath` ignores ending slash

### ISSUE THREAD

**Issue by govizlora** [ReactTraining/react-router#7517]
## Version

**6.0.0-beta.0**

## Test Case

https://codesandbox.io/s/matchpath-example-9299d

## Steps to reproduce

Call `matchPath("foo/*", "/foo-bar/one")`

## Expected Behavior

I think `/foo-bar/one` shouldn't be a match for `foo/*`, thus the return should be `null`.

## Actual Behavior

The return is
```
path: "foo/*"
pathname: "/foo"
params: Object
  *: "-bar/one"
```

**Comment by anushaNemilidinne** [comment]
Hello! I would like to work on this.

**Comment by huttonr** [comment]
This looks like why:

https://github.com/ReactTraining/react-router/issues/7529#issuecomment-698674552
