### ISSUE TITLE
[v6] Nested routes with children do not work

### ISSUE THREAD

**Issue by phistuck** [ReactTraining/react-router#7518]
## Version

v6-beta.0

## Test Case
https://codesandbox.io/s/react-router-deep-nesting-k8ist?file=/example.js

## Steps to reproduce
Click on one of the "Pages" links and then on, say, "Page 1".

## Expected Behavior
The content of "Page 1" renders (basically "Page 1").

## Actual Behavior
No route is rendered, not even the container of Pages.

Note that I see this warning -
```
You rendered descendant <Routes> (or called `useRoutes`) at "/pages/" (under <Route path="/">) but the parent route path has no trailing "*". This means if you navigate deeper, the parent won't match anymore and therefore the child routes will never render.

Please change the parent <Route path="/"> to <Route path="//*">. 
```

But that makes no sense, because there is no `<Route>` above that `<Route>` and even if I add it, it the expected behavior is still not occurring.

I hope this is not a support question (regardless, no one replies in the Discord chat, so I am not sure what to do).

**Comment by timdorr** [comment]
You need to use the `element` prop on `<Route>`, not children.

**Comment by phistuck** [comment]
Thank you, @timdorr. Bearing that in mind, when is `<Outlet>` needed? Where does it fit in if this.props.children gets you the same thing?
