### ISSUE TITLE
Direct dependency on @types/react

### ISSUE THREAD

**Issue by KutnerUri** [ReactTraining/react-router#7522]
## Version 
react-router-dom: "^5.2.0",
@types/react-router-dom: "^5.1.5",

## Description
I'm getting this TS error:
```
Type '{ to: string; replace?: boolean | undefined; download?: any; hrefLang?: string | undefined; media?: string | undefined; ping?: string | undefined; rel?: string | undefined; target?: string | undefined; ... 261 more ...; location?: Location<...> | undefined; }' is not assignable to type 'NavLinkProps<PoorMansUnknown>'.
  Types of property 'style' are incompatible.
    Type 'React.CSSProperties | undefined' is not assignable to type 'import("/Users/kutner/Documents/Projects/bit-cli/node_modules/.pnpm/@types/react@16.9.38/node_modules/@types/react/index").CSSProperties | undefined'.
```

It seems that @types/react-router-dom has a dev dependency on `@types/react@16.9.38`, and not a peer dependency.
This makes it incompatible with my project's `@types/react 16.9.43` :/

## suggested solution
Change `@types/react` to be a peer dependency, with semver range

**Comment by timdorr** [comment]
Those types aren't maintained here. They are in the DefinitelyTyped repo.

**Comment by KutnerUri** [comment]
thanks
