### ISSUE TITLE
history@5.0.0 is not supported when use TypeScript

### ISSUE THREAD

**Issue by kingller** [ReactTraining/react-router#7525]
Hi,
  When I upgrade to `history` 5.0.0, some types check failed, such as 
```
xx/@types/react-router/index.d.ts(81, 97)
xx/history/index has no exported member 'LocationState'
...
```

Is `history@5.5.0` supported?

**Comment by timdorr** [comment]
It's not supported for v4/v5. It's only supported for v6, which is in prerelease.
