### ISSUE TITLE
Link [component] property is never working and was never working (ref: #7524)

### ISSUE THREAD

**Issue by activenode** [ReactTraining/react-router#7530]
**I needed to open this second issue unfortunately because the first one was prematurely closed before checked for the solution to be working.**

Reference: https://github.com/ReactTraining/react-router/issues/7524

The proposed solution on which premise the ticket was closed is not working: https://github.com/ReactTraining/react-router/issues/7524#issuecomment-665366615

The workaround given by @jan-paulus is properly working but it is not satisfying enough since it does not solve the bug in itself (see: https://github.com/ReactTraining/react-router/issues/7524#issuecomment-665639618)

## Version

**`react-router-dom@5.2.0`**

Please note that since this `component` property was introduced it never worked so it fails also for 

- `5.1.0`
- `5.1.1`
- `5.1.2`

## Test Case

https://codesandbox.io/s/react-router-v5-component-bug-5jyv3?file=/src/Routes.js

## Steps to reproduce

1. Try to render a Link with a custom component by using `forwardRef` such as described in the official documentation e.g. via:

```jsx
const FancyLink = React.forwardRef((props, ref) => (
  <a ref={ref}>💅 {props.children}</a>
))

<Link to="/" component={FancyLink} />
```

## Expected Behavior

The Link uses the given `ref` and sets its `href` and triggers proper routing.

## Actual Behavior

Routing does not work, the component is logically function-less.

**Comment by ppvolto** [comment]
Its a Simple Documentation Error?
`
const FancyLink = React.forwardRef(({children, ...props}, ref) => (
  <a ref={ref} {...props}>💅 {children}</a>
))

<Link to="/" component={FancyLink} />
`
I use emotion for styling
```
const LinkComponent = styled.a`
  color: blue;
`;
const FancyLink = React.forwardRef(({children, ...props}, ref) => (
  <LinkComponent ref={ref} {...props} />
))

<Link to="/" component={FancyLink} />
```
Works for me.

**Comment by timdorr** [comment]
Please stop opening duplicate issues.

**Comment by activenode** [comment]
I really feel that both of you are not taking this issue "seriously" as actually proving a point on what you are saying considering the given codesandbox.

I know what you (both) are proposing and as you can see in the referenced ticket i DID do this and it does NOT solve the problem. Yes it does set the `href` but the functionality is still broken (no history push!).

I do not want to preach but I am literally astonished by the way this is simply closed prematurely (again) even though I am literally proving that the proposed solution does not work.

I feel desperate in seeing how this is treated.

So again:

I am not having problems applying your proposed solution but it does not work - as you would see when you would test it in the given codesandbox. YES it does link to the referenced but it does link only because the `href` on the `a` tag naturally does this (via HARD browser reload). There is no functionality with `<Link />` with this.

**PLEASE REOPEN**

**Comment by activenode** [comment]
@timdorr please reopen and read carefully and analyse the actual issue. Else I feel forced to open another duplicate issue which I do not want.


All analysis and code samples are stated also proving that the given "fix" is not a fix - which is totally fine but it doesn't help the fact that prematurely closing the issue does not help anybody :)

**Comment by activenode** [comment]
@timdorr  I feel urged to open another issue if one of these does not get reopened. The bug is still there and the bug does not get fixed by simply adding `...props` .
