### ISSUE TITLE
useHistory hooks doesn't work in the same as way as used to work in version 5.1.2

### ISSUE THREAD

**Issue by adybionka** [ReactTraining/react-router#7531]
After upgrading react-router to version 5.2.0 some parts of my application stop working because `useHistory` used in my hook, doesn't trigger anymore rerender of component, where this hook is used, even when history has changed. [This change](https://github.com/ReactTraining/react-router/compare/v5.1.2...v5.2.0#diff-ec5920a4c0d285caf4185dc57f785affR18) cause this. So fix seems to be pretty straightforward.

...but from the release note, we can read that it was changed due to a performance boost, but as we can see this is breaking change so we should consider this change as a bug or change the "major" part of the version and mention this in the documentation. 

## Version

**5.2.0**

## Test Case

https://codesandbox.io/s/new-wildflower-jist7

## Steps to reproduce

Put component which use `useHistory` hook inside `Router` component but outside `Switch` component. 

## Expected Behavior

A component which use `useHistory` hooks should rerender every time when browser history has changed. It used to work in this way in version 5.1.2 and older.

## Actual Behavior

A component which use `useHistory` hooks isn't rerender when browser history has changed.

**Comment by timdorr** [comment]
Yes, that was intentional because we don't want the component to render just because you're using the history instance. For people doing `const { push } = useHistory()`, this was causing unnecessary renders.

If you want to re-render when the location changes, use `useLocation`.

**Comment by adybionka** [comment]
Thank you for your clarification. I wanted to make sure that this was intended. But still is worth mentioning it in a changelog.
