### ISSUE TITLE
Changing route does not reset 'Select text' (i.e using CMD +A)

### ISSUE THREAD

**Issue by saviomuc** [ReactTraining/react-router#7532]
Hello,

I am not sure if this is the right place to ask because I'm not even sure if that's a bug or a feature.

## Version
This seems to be reproducible in all versions 

## Test Case
Take for instance this page  (https://reactrouter.com/core/guides/quick-start) and select text (using CMD/CTRL+A)
![image](https://user-images.githubusercontent.com/1830601/88944263-ccb6ae00-d28c-11ea-9fc8-2816d6bb6272.png)
and navigate to another route
![image](https://user-images.githubusercontent.com/1830601/88944304-db04ca00-d28c-11ea-8dd4-7a7e7cba1169.png)

## Expected Behavior
Text should not be selected anymore

## Actual Behavior
Text stays selected across all routes

**Comment by timdorr** [comment]
It's not really a bug. We're rendering the same components at the high level, so React is re-using the existing DOM elements, which retains the selection even as their contents change. This is the same for any SPA, not just one using React Router. If you do this on facebook.com and click around (they have their own router), you'll see the selection is retained across pages. It's just how React and the DOM works.

**Comment by saviomuc** [comment]
Thanks @timdorr yeah that makes a lot of sense. Thanks a lot =)
