### ISSUE TITLE
PageNotFound appearing to other router

### ISSUE THREAD

**Issue by Vince-vegas** [ReactTraining/react-router#7533]
Why the NotFoundPage is appearing to **blog & contact** router

         <BrowserRouter>

        <Switch>
          <Route exact path="/" component={Home} />
          <Route exact path="/about" component={About} />
          <Route component={NotFoundPage} />
        </Switch>

        <Switch>
          <Route exact path="/blog" component={Blog} />
          <Route exact path="/contact" component={Contact} />
        </Switch>

        </BrowserRouter>

**Comment by timdorr** [comment]
Because each switch operates independently. There is nothing in the first switch that matches those routes other than the last. You should combine them.

**Comment by Vince-vegas** [comment]
> Because each switch operates independently. There is nothing in the first switch that matches those routes other than the last. You should combine them.

Is it possible that I can separate the 404 Page
