### ISSUE TITLE
Why the Blog & Contact route doesn't appear, is there any way to have multiple providers in Routes

### ISSUE THREAD

**Issue by Vince-vegas** [ReactTraining/react-router#7536]
` <Switch>
    <AProvider>
        <Route exact path="/" component={Home} />
        <Route exact path="/about" component={About} />
    </AProvider>

     <BProvider>
        <Route exact path="/blog" component={Blog} />
        <Route exact path="/contact" component={Contact} />
        <Route component={NotPage} />
     </BProvider>
     </Switch>
      `

**Comment by timdorr** [comment]
Switch only works on the first level of children below it. You would need to wrap your providers elsewhere.

**Comment by Vince-vegas** [comment]
Can you give me a simple example of how to do it with code
