### ISSUE TITLE
Navigating to same route results in re-render

### ISSUE THREAD

**Issue by cristian-eriomenco** [ReactTraining/react-router#7539]
This is an empty create-react-app example with react-router-dom

## Version

"react": "^16.13.1",
"react-dom": "^16.13.1",
"react-router-dom": "^5.2.0",
"react-scripts": "3.4.1"

## Test Case

https://codesandbox.io/s/inspiring-sinoussi-y0l4f?file=/src/App.js:0-889

## Steps to reproduce
There are two routes under the Switch component:
1. / - for Home component
2. /contacts - for Contacts component

Click Home link and observe the console logs.

## Expected Behavior
My assuption is that if we're already on same route and try to navigate it would not attempt to re-render the component.
## Actual Behavior
Clicking on Home link multiple times results in a Home rendered message.

**Comment by timdorr** [comment]
Your component is getting new props from the new location you are at (Route is providing them). You can implement shouldComponentUpdate to avoid this, but it's intentional behavior.

**Comment by cristian-eriomenco** [comment]
@timdorr Thank you for your reply. 
Let me get this right:
Navigating from '/' to '/' using <Link to="/" ...  is designed to Re-Render the underlying page despite the route not being changed?

**Comment by timdorr** [comment]
It's a new location, even if it's the same pathname. You can use shouldComponentUpdate to determine if the component cares about the new location or not.
