### ISSUE TITLE
[v6] Can't use useRoutes hook with Router component

### ISSUE THREAD

**Issue by kcsujeet** [ReactTraining/react-router#7541]
## Version
6.0.0-beta.0

## Steps to reproduce

-  import Router from 'react-router-dom' instead of BrowserRouter

- use useRoutes hook to build routes object as shown [here](https://reacttraining.com/blog/react-router-v6-pre/)

## Expected Behavior
Everything should work fine 

## Actual Behavior
Getting this error instead `Error: useRoutes() may be used only in the context of a < Router > component`

**Comment by timdorr** [comment]
You have to provide the `location` prop to Router in v6. It no longer accepts a history.

**Comment by knuxbbs** [comment]
> 
> 
> You have to provide the `location` prop to Router in v6. It no longer accepts a history.

@timdorr where's the guidance about this? [Here](https://github.com/ReactTraining/react-router/issues/7162#issuecomment-589648110) you pointed to the same workaround of the previous versions, that is "create a history instance and pass that as a prop to a Router".

**Comment by MrBirb** [comment]
@knuxbbs Have you found a solution to this lol?

**Comment by knuxbbs** [comment]
> @knuxbbs Have you found a solution to this lol?

Unfortunately no. I think it depends on https://github.com/ReactTraining/react-router/pull/7586.
