### ISSUE TITLE
https://reactrouter.com/web/example/auth-workflow example display wrong 

### ISSUE THREAD

**Issue by mimiliaogo** [ReactTraining/react-router#7542]
## Version

**Please replace this sentence with the React Router version that you are using.**

## Test Case

https://reactrouter.com/web/example/auth-workflow

## Steps to reproduce
After clicking the login button, it still display the not login message
![image](https://user-images.githubusercontent.com/44743062/89265753-8afc7d80-d667-11ea-80c5-b5c17e171e89.png)

**Comment by mimiliaogo** [comment]
This is because the fakeAuth.isAuthenticated is not a state.
so  AuthButton will not re-render.

**Comment by timdorr** [comment]
If you add a call to useLocation(), it will work because the location change triggers a re-render there. 

If you want to make a PR to fix that, go right ahead.

**Comment by morgan-sam** [comment]
This issue was fixed in #7474
