### ISSUE TITLE
type definition for useNavigate hook doesn't allow numbers  

### ISSUE THREAD

**Issue by brettatoms** [ReactTraining/react-router#7546]
## Version

v.6.0.0-beta.0

## Test Case

```
const navigate = useNavigate()
navigate(-1) // typescript error 
```

## Actual Behavior

The [docs](https://github.com/ReactTraining/react-router/blob/dev/docs/api-reference.md#usenavigate) for `useNavigate` say you can pass a delta as the `to` parameter but the type definition uses `To` from the `history` package which doesn't allow numbers.

**Comment by timdorr** [comment]
Can you give an example of the error you're getting? That is the type definition:

https://github.com/ReactTraining/react-router/blob/fae90a497f08f6ac0dca9d7de84958fea7cfc3c2/packages/react-router/index.tsx#L483

https://github.com/ReactTraining/react-router/blob/fae90a497f08f6ac0dca9d7de84958fea7cfc3c2/packages/react-router/index.tsx#L472-L475

**Comment by brettatoms** [comment]
Sorry, I missed the `(delta: number): void` overload.  The error I was seeing must have been on our end.
