### ISSUE TITLE
useLocation doesn't work with BrowserRouter

### ISSUE THREAD

**Issue by thisismydesign** [ReactTraining/react-router#7549]
It works fine with HashRouter but when switching to BrowserRouter it stops triggering upon navigating to a different page (still triggers on first page load). My project is a standard CRA. Can reproduce locally and live. Using AWS Amplify. Standard setup with the following rewrite:
- `</^[^.]+$/> | /index.html | 200 (Rewrite)`

## Version

`"@types/react-router-dom": "^5.1.5"`

## Test Case

```
const usePageTracking = (): void => {
  const location = useLocation();
  const [initialized, setInitialized] = useState(false);

  useEffect(() => {
    if (!window.location.href.includes("localhost")) {
      ReactGA.initialize("UA-xx");
    }
    setInitialized(true);
  }, []);

  useEffect(() => {
    if (initialized) {
      ReactGA.pageview(location.pathname + location.search);
    }
  }, [initialized, location]);
};
```

```
const App: FunctionComponent = () => {
  usePageTracking();
  ....
}
```

**Comment by thisismydesign** [comment]
@timdorr If it's super obvious why the example taken directly from the docs doesn't work, could you explain or point me to the right place?

**Comment by timdorr** [comment]
It should work just fine. Make sure you have the very latest version (the types aren't the right package for us to know the version you're using). But outside of that, it's hard to know what might be wrong because we can't see any of your setup code.

**Comment by thisismydesign** [comment]
@timdorr Copied the wrong line, sorry about that. Updated to `5.2.0`.

It doesn't work for me and specifically only for BrowserRouter hence the bug report. Here's my `App.tsx`, nothing special afaict.

```
import React, { FunctionComponent, Suspense, lazy } from "react";
import { HashRouter as Router, Switch, Route } from "react-router-dom";

import Layout from "components/App/Layout/Layout";
import Loading from "components/App/Loading/Loading";
import Head from "components/App/Head/Head";
import usePageTracking from "utils/usePageTracking";

const Home = lazy(() => import("components/App/Home/Home"));
// ...

const App: FunctionComponent = () => {
  usePageTracking();

  return (
    <>
      <Head />
      <Router>
        <Layout>
          <Suspense fallback={<Loading />}>
            <Switch>
              <Route exact path="/" component={Home} />
              // ...
              <Route path="/" />
            </Switch>
          </Suspense>
        </Layout>
      </Router>
    </>
  );
};

export default App;
```

**Comment by timdorr** [comment]
You're using the hook from outside the BrowserRouter. It has to be in a component that is wrapped by the BrowserRouter.

I would move the `<Router>` out to wherever you render the App component. It's generally a good idea to move the Router as close to the top of the tree as possible.

**Comment by thisismydesign** [comment]
Yep, thanks a lot!
