### ISSUE TITLE
Feature request (please close if not relevant): 404 component which displays closest match

### ISSUE THREAD

**Issue by sktguha** [ReactTraining/react-router#7551]
It would be really good if react-router ships with a 404 component, which also shows a closest match . As all Route components receives the path and other parameters so those can be added to a lookup table and the 404 component can iterate through the table to find the closest match and display it like "Did you mean to go to" + closestMatchUrl . I realise for dynamic paths as /some/path/:ids etc it would be difficult so for first version just simple hamming distance checking can be done for only simple string path params

I apologize in advance if its not something relevant. In that case please feel free to close it.

**Comment by timdorr** [comment]
We already have the concept of a pathless route that catches everything missed in a Switch or Routes. Coming up with some sort of "did you mean?" heuristic seems like a lot of work and doesn't really have that much value to the library. We're not going to add this.

**Comment by sktguha** [comment]
Hmm ok .understood. Thanks for replying.
