### ISSUE TITLE
Error After Upgrade React-router and react-router-dom to 6.0.0-beta.0 

### ISSUE THREAD

**Issue by Ako92** [ReactTraining/react-router#7560]
## Version

6.0.0-beta.0

## Test Case

after upgrade react-router-dom to version 6.0.0-beta.0 it raise this error: 
```
./node_modules/react-router/index.js
Module not found: Can't resolve 'history' in '.\node_modules\react-router'
```
## Steps to reproduce
Just Upgrade to latest beta version

## Expected Behavior
Use navigate instead of history

**Comment by timdorr** [comment]
You have to install the `history` package as well. Check the install instructions on the release notes: https://github.com/ReactTraining/react-router/releases/tag/v6.0.0-beta.0
