### ISSUE TITLE
How to ignore query string (search) in routing?

### ISSUE THREAD

**Issue by mortoray** [ReactTraining/react-router#7562]
I would like the routing to ignore the query string in it's routing. In particular, I don't want any props update /re-rendering to occur if only the query string (search) of the location changes. How can I do this?

I'm upgrading an up from v3 where this was apparently standard: I could update the browser history, changing the query string, and react-router would not change the route. Now I have a hierarchy of components that should not rerender if the location changes.

The rerendering, and moreso, unmounting/remounting, occurs when I call `history.replace(...)` with a new search value.

**Comment by timdorr** [comment]
You cannot. A new query string is a new location, so it must be passed down. You need to decide if the change is important or not in your components with shouldComponentUpdate or React.memo().

**Comment by mortoray** [comment]
The problem is that the re-rendering is happening before it evaluates my components.  I'm using a `Route` with a `render` property, and if the query string changes, it calls `render` again. This rerendering appears outside of my control.
