### ISSUE TITLE
API suggestion for Router to add a 'callback' prop to support for adding callbacks when route changes

### ISSUE THREAD

**Issue by Nekosandesu** [ReactTraining/react-router#7564]
I find it necessary to do something when the location changes. For example, some common things could happen when URL changes, such as event tracking for page views etc. 

Here's my code example (Actually, this is what I'm doing to resolve my problem in my project):

```jsx
import React from 'react';
import { BrowserRouter } from 'react-router-dom';
import { isFunction, isArray } from 'utils/common';

export default class Router extends BrowserRouter {
  constructor(props) {
    super(props);
    this.unlistenCallback = [];
    if (isFunction(props.callback)) {
      this.unlistenCallback.push(this.history.listen(props.callback));
    } else if (isArray(props.callback)) {
      props.callback.forEach((cb) => {
        if (isFunction(cb)) this.unlistenCallback.push(this.history.listen(cb));
      });
    }
  }

  componentWillUnmount() {
    if (this.unlistenCallback) {
      this.unlistenCallback.forEach((cb) => cb());
    }
  }
}
```

When use:

```jsx
// cb here can be a function or an array of functions whitch will be called when the location changes 
<Router callback={cb}>
  // ...
</Router>
```

Can I have a pull request? Or what do you think about this idea? Thanks for your reply.

**Comment by timdorr** [comment]
Just use the useLocation hook. That will trigger a re-render when the location changes and you can handle that appropriately.

**Comment by asumaran** [comment]
@timdorr could you elaborate please? I'm trying to do the same as the OP. I want to track location changes to record visited pages and I can't find a way to it with React Router v6.

**Comment by timdorr** [comment]
I mean something like this. Just pop this in your tree somewhere it will always be rendered.

```js
function Tracker() {
  const location = useLocation()

  useEffect(() => {
    doTrackingStuff(location)
  }, [location])

  return null
}
```

**Comment by asumaran** [comment]
@timdorr Thank you! I was able to implement what I wanted without issues.
