### ISSUE TITLE
Add type=module for client side navigation requests

### ISSUE THREAD

**Issue by AjayPoshak** [ReactTraining/react-router#7567]
I am trying to do a differential build where the modern browsers are shipped modern syntax using `type=module`, and for legacy browsers, `nomodule` attribute is used.

Challenge here is that how do I add `type="module"` and `nomodule` attribute on script tags which are generated as a result of client side navigation?

I want to generate two script tags, one for `type=module` and another for `nomodule` for every navigation request.

**Comment by timdorr** [comment]
This has nothing to do with React Router.
