### ISSUE TITLE
Replace import  'BrowserRouter as Route,' to 'BrowserRouter' in examples

### ISSUE THREAD

**Issue by it-efrem** [ReactTraining/react-router#7568]
Hi, guys!

I did't can understand why my React App doesn't work, it turned out that in examples importing use like
`import {BrowserRouter as Router}`
and in App used `<Router>`.

**It's confusing.**

I have proposal - change import to
`import {BrowserRouter}`
and use in App `<BrowserRouter>`

**Comment by timdorr** [comment]
Thanks, but this is pretty common in many areas of the docs and code examples. I think we're going to stick with it for now.
