### ISSUE TITLE
Usage with Create React App (v16.13.1) throws warning findDOMNode although im not using it anywhere

### ISSUE THREAD

**Issue by TheArvindNarayan** [ReactTraining/react-router#7569]
## Version

"react-router-dom": "^5.2.0",

## Test Case

https://codesandbox.io/s/react-router-gh6n7

## Steps to reproduce

use with react version ^16.13.1 and `connected-react-router`

## Expected Behavior

warnings to be thrown from <React.StrictMode>

```Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of Router which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here:```

## Actual Behavior

No warnings to be thrown from <React.StrictMode>

**Comment by timdorr** [comment]
This isn't a React Router issue.
