### ISSUE TITLE
How use useParams in class component in react

### ISSUE THREAD

**Issue by khanhnam99** [ReactTraining/react-router#7570]
![image](https://user-images.githubusercontent.com/575720/90711065-f8481980-e2c9-11ea-8a78-2f311fa04fbe.png) 

bug

![image](https://user-images.githubusercontent.com/575720/90711168-2f1e2f80-e2ca-11ea-9246-9d52da3b6b21.png)

How use useParams in class component in react?

**Comment by timdorr** [comment]
You can't use hooks in class components. You have to use a function component.

**Comment by khanhnam99** [comment]
thanks
