### ISSUE TITLE
[v6] Missing history dependency

### ISSUE THREAD

**Issue by gsimone** [ReactTraining/react-router#7572]
I don't think this is a bug since based on this commit https://github.com/ReactTraining/react-router/commit/fa6f257230d500a142ba92b4643a71fb868b24a1#diff-ac523f195aefed7149e563c5eb772a17

Might be worth adding the need to install history to these docs

https://reacttraining.com/blog/react-router-v6-pre/

https://github.com/ReactTraining/react-router/blob/f59ee5488bc343cf3c957b7e0cc395ef5eb572d2/docs/advanced-guides/migrating-5-to-6.md

**Comment by timdorr** [comment]
The latest version of that file includes installing the history package: https://www.github.com/ReactTraining/react-router/tree/dev/docs%2Fadvanced-guides%2Fmigrating-5-to-6.md

Make sure you're looking at the latest docs.

**Comment by gsimone** [comment]
Might we worth fixing the blog post

**Comment by gsimone** [comment]
Looks like this is the sentence with wrong link

```
Pulling an example straight from the v5 to v6 migration guide, a v6 app might look something like this
```
