### ISSUE TITLE
[v6] Allow typing of navigate call

### ISSUE THREAD

**Issue by geoff-harper** [ReactTraining/react-router#7574]
Currently in the docs `navigate` has the following type dec

```
interface NavigateFunction {
  (to: To, options?: { replace?: boolean; state?: State }): void;
  (delta: number): void;
}
```

In my opinion this should take an argument so that we can type our state objects. I think this is relatively straightforward since the `Location` interface already supports it

```
interface Location<S extends State = State> {
  pathname: string;
  search: string;
  hash: string;
  state: S;
  key: string;
}
```

This would be great since having a state mystery box isn't ideal

**Comment by timdorr** [comment]
Unfortunately, that navigate type won't be carried to anywhere you read that state. The type of the current location is a runtime concern. It is not known statically. 

We know that `useLocation` returns a `Location`, but we don't know what type of `state` is on that Location. You either have to override the type to force it or add lots of type guards everywhere you use those things.

**Comment by geoff-harper** [comment]
That's fine but I'd still like to be able to idiotproof it against myself. Of course I could write a wrapper hook but it seemed like a nice opt-in feature
