### ISSUE TITLE
useLocation search is empty with every change

### ISSUE THREAD

**Issue by Geddard** [ReactTraining/react-router#7582]
Hi there, I've been using hooks for a while and i recently discovered these router hooks that at the beginning seemed like the right way to go.

But i've noticed that in one of my use cases the search value provided by useLocation is out of sync with window.location.search.

My setup consists of a table, where each column has a filter input, when i type into these inputs, the query params should be updated with key=value.

So i've created a custom hook that handles queryupdates like this:

```
import { extend, isEmpty, isEqual, omit } from 'lodash-es';
import { useEffect, useRef, useState } from 'react';
import { useHistory, useLocation } from 'react-router-dom';

const deserialize = (search: string) => Object.fromEntries(new URLSearchParams(search));

type UpdateQueryParams = (key: string, value: string) => void;

export const useQueryParams: () => [Record<string, string>, UpdateQueryParams] = () => {
  const { push } = useHistory();
  const { search, pathname } = useLocation();
  const [queryParams, setQueryParams] = useState(deserialize(search));

  const prevQuery = useRef<Record<string, string>>();

  const updateQueryParams = (key: string, value: string) => {
    const currentParams = deserialize(search);
    const newParams = isEmpty(value) ? omit(currentParams, [key]) : extend(currentParams, { [key]: value });

    setQueryParams(newParams);
  };

  useEffect(() => {
    if (!isEqual(prevQuery.current, queryParams)) {
      push({ pathname, search: new URLSearchParams(queryParams).toString() });
      prevQuery.current = queryParams;
    }
  }, [search, queryParams, push, pathname]);

  return [queryParams, updateQueryParams];
};
```

The problem i have is that for some reason, with each new query param I try to push. the `{ search } ` is empty like there was nothin there before, so he query params list gets replaced completely instead of getting new params added, this is fixed by simply changing it for window.location.search everywhere... so my guess is that there's something off with the hook... But i can't tell if it's my fault or if it's a bug.

Ideas?

Thanks!

**Comment by Geddard** [comment]
Well apparently this is related to me using BrowserRouter as the main Router component in my app, I changed this to the regular Router and add the `createBrowserHistory` function for the history prop and now it works as expected, a little counterintuitive though.

**Comment by JNotelddim** [comment]
@Geddard  I'm having a similar problem, but I don't quite understand your solution.

What do you mean by "the regular Router" sorry?

**Comment by Geddard** [comment]
> @Geddard I'm having a similar problem, but I don't quite understand your solution.
> 
> What do you mean by "the regular Router" sorry?

By "regular router" I meant changing it to the `import { Router } ...`, but that also didn't help my situation. I'm not sure yet what is making it that sometimes the routing doesn't react as I want it to.

**Comment by JNotelddim** [comment]
Fair enough -

I'm finding with BrowserRouter, if you try navigating by using `history.push('/example/path/with?queryString=values')`, then the `search` value in `location` will be empty.

Based on this [StackOverflow thread](https://stackoverflow.com/questions/44121069/how-to-pass-params-with-history-push-link-redirect-in-react-router-v4), it seems to me that if you instead pass the queryString like this:

```
      history.push({
        pathname: '/emaple/path/with',
        search: `?queryString=values`,
      });
```

then the browser router will be able to track the queryString, and `search` will no longer come back empty.

Not sure if this is helpful for you, but it's gotten me unstuck :)
