### ISSUE TITLE
[v6] <Link> crashes if "to" prop is undefined

### ISSUE THREAD

**Issue by thedanwoods** [ReactTraining/react-router#7583]
## Version

**6.0.0-beta.0**

## Test Case

https://codesandbox.io/s/loving-hugle-4321b?file=/src/App.js

## Steps to reproduce

Run the sandbox above, or try `<Link to={undefined}>Text</Link>`

## Expected Behavior

Ideally, provide a warning and render anyway; or just ignore the problem and render, as per the v5 behaviour.

## Actual Behavior

It crashes with the unhelpful error `c is undefined`.

**Comment by dvfleet413** [comment]
I'm curious what the maintainers think about this issue.  I haven't experienced it myself, and it may be intentional so we don't accidentally create anchor tags with no href attribute.  If the maintainers want to change this behavior to render even without the `to` prop (maybe make it default to "#") I'd be happy to work up a PR

**Comment by renatobenks** [comment]
this is not a bug, because actually, the `Link` needs to know where should it go. Therefore, as long as the `to` prop is required, it can't be undefined

**Comment by MeiKatz** [comment]
@renatobenks then it would be better with a more descriptive message instead of just crashing.

**Comment by thedanwoods** [comment]
@timdorr Please reopen, as it is a bug. Although it does need a `to` prop work, the `to` prop may be dynamically assigned at runtime. If something goes wrong, I wouldn't expect it to just crash completely with an indecipherable error message.

**Comment by rcidaleassumpo** [comment]
> If something goes wrong, I wouldn't expect it to just crash completely with an indecipherable error message.
What about then dealing with the possible undefined value on your side ? You are pushing the problem that starts in your application, to be dealt by the library. As stated by @renatobenks , if it says that it doesn't take in undefined, you shouldn't provide undefined. Now if the library maintainers have time to deal with that. good luck.

**Comment by thedanwoods** [comment]
I think my point is that if `to` _is_ `undefined` due to a developer's silliness, then crashing completely with `c is undefined` can be hard to debug in any non-trivial application, and it's not a great developer experience.

If it's the **intention** of the library authors that it **should** crash with an indecipherable error message, then that's fine. But I don't think it is - it smells like a bug - and I think the issue should be reopened.

**Comment by renatobenks** [comment]
I suggested to close it because once you have static types covering it, you actually don't need a double-check, but maybe, I guessed wrong, what do you think @timdorr?
