### ISSUE TITLE
Protected routes support out of the box.

### ISSUE THREAD

**Issue by adamszeptycki** [ReactTraining/react-router#7584]
I have a question / feature request.

Would you guys be open to add protected routes (accessible only for authenticated users) to `react-router`

I would imagine the interface to look more or less like this:
```
<Router
  isAuthenticated={true}
  redirectUnauthenticatedTo="/login"
>
   <Login path="/login" />
   <Dashboard path="/Dashboard" protected/>
<Router>
```

If there is a chance of merging that in I would love to work on that.

**Comment by timdorr** [comment]
We would rather stay agnostic to this sort of thing. There are many different ways to do authentication, and they often times would not work with this kind of API. Instead, we would like to leave it to other libraries or the user to implement something customized to their needs.

**Comment by adamszeptycki** [comment]
Ok thanks for the response.
