### ISSUE TITLE
[v6] Support history prop on <BrowserRouter />

### ISSUE THREAD

**Issue by salvoravida** [ReactTraining/react-router#7585]
Hi guys, great work with v6 release!

Just a little note:

It would be nice to add support for a already created history object on <BrowserRouter 
and skip creation if it is passed as prop.

We need it to support redux-first-history integration.

Can i open a PR about it?

Regards,

**Comment by timdorr** [comment]
You would need to implement your own Router component in the new system. `<Router>` no longer takes a history prop, so it's not as simple as just passing it through:

https://github.com/ReactTraining/react-router/blob/761f104ed144601b3bcd7a8a35aa635afc5e05db/packages/react-router-dom/index.tsx#L92-L117

**Comment by salvoravida** [comment]
Yes i have already seen beta0 code

I suppose to add history suport on <BrowserRouter not <Router, just small change:

```javascript
 export function BrowserRouter({ children, history, window }: BrowserRouterProps) { 
   let historyRef = React.useRef<BrowserHistory>(); 
   if (historyRef.current == null) { 
     historyRef.current = history || createBrowserHistory({ window }); 
   } 
```

Isn't it possible?

**Comment by timdorr** [comment]
Yeah, that should be fine. You can always open up a PR, no need to ask.
