### ISSUE TITLE
Typescript 4.0.2 requiring type declaration on `useParams()`

### ISSUE THREAD

**Issue by bmueller-sykes** [ReactTraining/react-router#7588]
Typescript 4.0.2
react-router-dom 5.2.0
@types/react-router-dom 5.1.5

It could be that this is now the "correct" behavior, but...

Up to this point, in a Typescript file, I could just do this:

```const { id } = useParams()```

...but as of Typescript 4.0.2 (and probably TS 4), I now get the following error on the above line:

```Property 'id' does not exist on type '{}'```

So I can go through and add interfaces to my `useParams` declarations, like this:

```
interface IParams { id: string; }

const { id } = useParams<IParams>()
```

...but I'm wondering if that's the "right" solution here. I wasn't sure if this represented a bug with the React Router library, or if this is just Typescript finally doing the right thing.

**Comment by timdorr** [comment]
Yes, the right thing with the current types is to use the generic.
