### ISSUE TITLE
Need to navigate outside of nested Memory Router

### ISSUE THREAD

**Issue by shalinibajpai0310** [ReactTraining/react-router#7589]
Can you provide an example of the implementation described below.
I am facing a similar kind of issue.

Thanks for the reply. I've just managed to figure it out also after rethinking how I can achieve this and came up with a very similar solution whereby I simply pass the top-level history instance as a prop to my MemoryRouter component, allowing all nested routes access to this instance of 'appHistory' to be able to navigate out of the MemoryRouter, which works exactly the way I want it to. Thanks for the fast reply either way though as it turns out I was on track after looking into this more : )

_Originally posted by @richardansell in https://github.com/ReactTraining/react-router/issues/7060#issuecomment-563457303_

**Comment by timdorr** [comment]
The same recommendation I made in that issue still applies
