### ISSUE TITLE
hooks not work with vite

### ISSUE THREAD

**Issue by Lsw931102** [ReactTraining/react-router#7592]
when i use useHistory in react-router i got then error:
![image](https://user-images.githubusercontent.com/13031383/91658380-4cd56b00-eafa-11ea-86d3-7feb80b0e210.png)
here is my code:
![image](https://user-images.githubusercontent.com/13031383/91658522-61663300-eafb-11ea-840d-8878c3863e64.png)
the version of react-router is 5.2

**Comment by timdorr** [comment]
This isn't caused by React Router.
