### ISSUE TITLE
React router not providing full functionality that path-to-regexp is capable of.

### ISSUE THREAD

**Issue by nmkname** [ReactTraining/react-router#7593]
I wouldn't say its a bug, however I was really confused by current behaviour. Path-to-regexp library which is used by react-router to match urls and templates allows to match full urll instead of location pathname. Will it be possible in future(or current) versions to fully check url matching by presented path?

**Comment by timdorr** [comment]
We've dropped the path-to-regexp dependency in the next version, so we'll build whatever makes sense for our feature set.
