### ISSUE TITLE
[v6]  params are not working

### ISSUE THREAD

**Issue by misshu1** [ReactTraining/react-router#7594]
## Version

6.0.0-beta.0

## Steps to reproduce
const slug = useParams();
console.log(slug)

will return
{*: "store/test"}

const { slug } = useParams();
here slug is udefined

## Expected Behavior

It should return the actual slug

**Comment by timdorr** [comment]
Does your route include that param? Please see the docs: https://github.com/ReactTraining/react-router/blob/dev/docs/installation/getting-started.md#reading-url-parameters

**Comment by misshu1** [comment]
I have the following code 
`{folderState.apps.map((app) => (
                <Route
                    key={app.id}
                    path={isMobile ? app.link : '/*'}
                    element={
                        <>
                            {app.isOpen && checkUserPermisions(app) && (
                                <Suspense
                                    fallback={<SpinnerApp global delay={200} />}
                                >
                                    {app.component} 
                                </Suspense>
                            )}
                        </>
                    }
                >
                    {app.id === 4 && (
                        <Route
                            path=':slug'
                            element={<div>something here</div>}
                        />
                    )}
                </Route>
            ))}`

The app with id 4 have a route '/store' and a child route ':slug'

**Comment by timdorr** [comment]
You can't use `useParams` unless you are under the Route with the param(s) in the path. There is no Route context in your App component.

**Comment by misshu1** [comment]
Ok, I found the problem seems like I need to wrap my entire loop in a <Routes>, but there is a problem since my path is exact only on mobile, only on mobile will render the routes, on the desktop the path '/*' will not render anything.
