### ISSUE TITLE
VSCode debug browser crashes when component returns a <Redirect />

### ISSUE THREAD

**Issue by diego92sigma6** [ReactTraining/react-router#7595]
## Description
Hello, I think I found an unexpected behavior that only occurs when done on a VSCode debug browser (chrome, msedge, etc). It happens when a component returns a `<Redirect />` - it closes the whole window even if there are more tabs opened.
I'd really like to see if this has happened to someone else before. Thanks in advance!

## Version

react-router-dom 5.2.0
```
		"@testing-library/jest-dom": "^4.2.4",
		"@testing-library/react": "^9.5.0",
		"@testing-library/user-event": "^7.2.1",
		"@types/axios": "^0.14.0",
		"@types/jest": "^24.9.1",
		"@types/js-cookie": "^2.2.6",
		"@types/node": "^12.12.54",
		"@types/react": "^16.9.47",
		"@types/react-dom": "^16.9.8",
		"@types/react-helmet-async": "^1.0.3",
		"@types/react-router-dom": "^5.1.5",
		"@types/store": "^2.0.2",
		"axios": "^0.20.0",
		"bootstrap": "^4.5.2",
		"js-cookie": "^2.2.1",
		"react": "^16.13.1",
		"react-bootstrap": "^1.3.0",
		"react-dom": "^16.13.1",
		"react-helmet-async": "^1.0.6",
		"react-image-autofit-frame": "^0.1.0",
		"react-router-dom": "^5.2.0",
		"react-scripts": "3.4.3",
		"react-simple-file-input": "^2.1.0",
		"store": "^2.0.12",
		"typescript": "^4.0.2"
```

## Steps to reproduce

* Create a react app with a component that returns a `<Redirect to="/existing-route" />`
* Create a launch.json in vscode that launches the webpage
* Press f5 to launch the debug browser
* trigger a component that returns a `<Redirect/>`

## Expected Behavior

* Target component is rendered

## Actual Behavior

* The browser window is closed when on a vscode-launched browser (chrome, edge, etc), but works perfectly when manually navigating from my browser (Chrome)

## Additional notes
The crash occurs exactly at globalHistory.replaceState(), in line 392 of the file node_modules/history/esm/history.js.

```js
        globalHistory.replaceState({
          key: key, //  = generated hash string
          state: state  // = null
        }, null, href); //  = the value of prop "to" in my <Redirect/>
```
I can't navigate into its implementation since vscode takes me to its declaration.

IMO this sounds more like a browser issue rather than a react-router implementation problem. I'd appreciate a confirmation on this

**Comment by timdorr** [comment]
Yes, this isn't caused by this library. I would check the appropriate VS Code support channels.

**Comment by FoxyWolfy** [comment]
diego92sigma6,

Any fix for "debug browser crashes when component returns a <Redirect />"??
I ran into it also,  Thanks....

**Comment by diego92sigma6** [comment]
Hi. Yes I found a fix for this but is more about vscode than react-router. Try to add the `"debug.javascript.usePreview": false ` option in your settings to disable the experimental version of debugger for chrome

**Comment by FoxyWolfy** [comment]
Thanks Diego!  I've been chasing this bug for two days thinking it was in react-router.   I owe you man!
