### ISSUE TITLE
Relative url with double slash 

### ISSUE THREAD

**Issue by cattofiq** [ReactTraining/react-router#7596]
I think this is issue because I open this Bug Report. 

## Version

5.2.0

## Test Case

https://codesandbox.io/s/react-router-forked-cnogl

## Steps to reproduce
If you can see I added two slash About link `  <Link to="//about">About</Link>` and when I try to go this link I get error _Failed to execute 'replaceState' on 'History': A history state object with URL 'https://about/' cannot be created in a document with origin 'https://cnogl.csb.app' and URL 'https://cnogl.csb.app/'._ 

## Expected Behavior
I think React Router must remove extra slashes before push state. Is there any reason preventing this?

**Comment by timdorr** [comment]
That is trying to visit the protocol-less URL of `//about/`, which is converted to `https://about/`. It's not valid to push to a URL of a different origin. That's not a bug, that's an error with your code.

**Comment by cattofiq** [comment]
I know push different origin to history is not valid but I ask can React Router detect this and redirect to /about?

**Comment by timdorr** [comment]
If you make a typo, that's your responsibility to fix.

**Comment by cattofiq** [comment]
Haha This is just example. If some little typo broke your library this is also your problem :d

**Comment by cattofiq** [comment]
For example you can check Vue-Router v2 There are don't have any problem like this.
