### ISSUE TITLE
Component without path prop rendered in Switch makes all following routes render nothing

### ISSUE THREAD

**Issue by sarneeh** [ReactTraining/react-router#7597]
## Version

5.2.0

## Test Case

https://codesandbox.io/s/switch-case-1u65v

## Steps to reproduce

1. Put any component in a `Switch` component that does not have a `path` prop, and then put an actual `Route` after it.
2. Everything after a component without the `path` prop will be ignored by `Switch`, resulting in rendering nothing.

## Expected Behavior

I think React Router should either:
- Throw an error/warning that you're trying to render something you shouldn't in the `Switch` component
- Ignore components that aren't instances of `Route` in the `Switch` component

## Actual Behavior

The `Switch` component ignores everything after a non-Route (or specifically a component that does not have a `path` prop) which results in that everything that's being rendered **before** that component (and the component itselt) works, and everything **after** doesn't.

## Notes

Here's the problematic logic: https://github.com/ReactTraining/react-router/blob/b6826980ee0d89267ebac4f066ab8ed517536f2c/packages/react-router/modules/Switch.js#L12-L46

It assumes that every component in `Switch` has a `path` prop, and when it doesn't it just assigns the `match` to `context.match`, which apparently is already defined, which makes all of the following components being ignored.

**Comment by timdorr** [comment]
Switch doesn't nest. It only works on direct children. This has always been the case of how it works.

**Comment by sarneeh** [comment]
@timdorr I think you didn't understand the case. Whenever you will render anything other than `Route` in the `Switch` component, every `Route` after that non-Route component will stop to work.

```
    <Router>
      <Switch>
        <SomeComponent />
        <Route path="/blog">Blog Posts</Route>
        <Route path="/users">User Directory</Route>
      </Switch>
    </Router>
```

https://codesandbox.io/s/switch-case-forked-eq6qq
