### ISSUE TITLE
[v6] Support for merging search params in createSearchParams

### ISSUE THREAD

**Issue by Jessidhia** [ReactTraining/react-router#7604]
It's currently not possible to easily alter one query parameter while leaving other query parameters unmodified without having to resort to the `URLSearchParams` imperative API.

Current code:

```tsx
const [searchParams, setSearchParams] = useSearchParams()

// inside an event handler / effect
const newParams = createSearchParams(searchParams) // race condition / bug: does not clone the search params!
newParams.set('foo', 'bar') // imperative API!
setSearchParams(newParams) // imperative API too but this one can't be helped
```

Merely using `setSearchParams({ foo: 'bar' })` would clobber any other search params that the caller may want to preserve.

When using the `qs` module, one can get away with combining `qs.parse`/`qs.stringify` and object spreads, but `URLSearchParams` is not spreadable as it's a class instance and not a plain object.

A possible API could be `createSearchParams(searchParams, { foo: 'bar' })`, or `createSearchParams([searchParams, { foo: 'bar' }])` the latter would be easier to adapt to `useSearchParams()[1]` (named `setSearchParams` in my example code).

EDIT: I guess one can use `Object.fromEntries(searchParams)` to make it spreadable; but it'd still be nice if `createSearchParams` could be made variadic for this purpose. A further convenience of deleting `undefined` values would also be needed to actually use this as a helper.

**Comment by timdorr** [comment]
I'm not sure I understand why using `searchParams.set()` is a bad thing here. If you're doing this inside of a handler or effect, you're running imperative code. `setSearchParams` has to be imperative code as well, so you're already in that mode. It's not possible with React's APIs to make absolutely everything declarative. That's just not Javascript's programming model. 

Just make the `.set` and `setSearchParams` calls on two lines and you've got what you're asking for.
