### ISSUE TITLE
History objects do not match

### ISSUE THREAD

**Issue by nolawnchairs** [ReactTraining/react-router#7606]
Hi,

I'm using react-router and the `useHistory` hook in my project (typescript based), and the signatures don't match:

The first image is a screen shot of the intellisense from the hook:
![h01](https://user-images.githubusercontent.com/224439/92679732-72ad0c00-f353-11ea-87d0-9221acd7a3a6.png)

This image is a console.log dump of the history object returned from the `useHistory` hook:
![h02](https://user-images.githubusercontent.com/224439/92679735-76409300-f353-11ea-8fb1-0ff639202f4d.png)

I see that the intellisense has a `back` method, but it is not included on the object provided. Of course, when trying to use `history.back()`, I get an error `history.back () is not a function`

My router is instantiated like so:

Main entry (lines redacted)
```
import { BrowserRouter } from 'react-router-dom'
...
  return (
    <BrowserRouter>
       <RouteContent />
    </BrowserRouter>

```

`RouteContent.tsx`:
```
import React from 'react'
import { Switch, Route } from 'react-router-dom'
import { Navigation } from '@util/Navigation'

export const RouteContent: React.FC<{}> = (): React.ReactElement => {

  return (
    <div id="route">
      <Switch>
        {Navigation.routes.map(r => {
          const { component: Component, exact } = r
          return (
            <Route key={r.route} path={r.route} exact={exact}>
              <Component />
            </Route>
          )
        })}
      </Switch>
    </div>
  )
}
```

Relevant dependencies:
```
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-router-dom": "^5.2.0",
    ...
    "@types/react-router-dom": "^5.1.5",
```
Is there something I'm missing? Nothing in your documentation gives me any clues as to why the discrepancy. Or are the TS types wrong?

Sorry that I'm not asking on SO, but no one there answers questions anymore

**Comment by MeiKatz** [comment]
First: the `@types` lib is non of us, therefore we don't have our hands on it.

Second: yes, there should be a `back` method, but I am also not sure about this bug.

**Comment by timdorr** [comment]
You probably have the wrong version of history installed. Make sure it's a 4.x version with `npm ls history`.
