### ISSUE TITLE
useHistory not exported in 6.0.0beta0?

### ISSUE THREAD

**Issue by znakeeye** [ReactTraining/react-router#7607]
With `6.0.0beta0` I'm experiencing the exact problem as described in #6987.

**My package.json:**
```json
"react-router": "^6.0.0-beta.0",
"react-router-dom": "^6.0.0-beta.0",
```

![image](https://user-images.githubusercontent.com/958469/92921458-5cc34800-f434-11ea-98da-3689b95ef870.png)

Reverting to `5.2.0` fixes the problem. However, I really need some new v6 stuff, so I can't downgrade. For the record, I cleaned the `nmp` cache and reinstalled everything. Still the same error.

More specifically, I have a dependency on `withRouter` which was removed. So I'm trying to re-implement it using hooks, and for that I need `useHistory`. Please refer [withRouter.tsx](https://gist.github.com/sibelius/7d760fa16a121ec0f4cd8b143a59bee6#file-withrouter-tsx).

What `useHistory` removed or is what could be the culprit?

**Comment by timdorr** [comment]
See #7476. I has been removed for now.
