### ISSUE TITLE
React-router v6 - HashRouter not working

### ISSUE THREAD

**Issue by sinhpn92** [ReactTraining/react-router#7609]
Hi,
I have used 
```
"react-router": "^6.0.0-beta.0",
"react-router-dom": "^6.0.0-beta.0",
```
And I got issue with HashRouter, It's doesn't working.
My implementation like this:
```
<BrowserRouter>
        <Routes>
          <Route path={'/app/dashboard'} element={<Dashboard/>}/>
           <HashRouter>
                <Route path={'/detail'} element={<ItemDetail/>}/>
           </HashRouter>
        </Routes>
      </BrowserRouter>
```
I tried to use navigate like this: `navigate('#detail')` or `navigate('#/detail')` But it's still not working.

What's wrong here? Have any suggest to solve this?

Thank so much~!

**Comment by timdorr** [comment]
You have two Routers in your app there. You should only be using one.

**Comment by sinhpn92** [comment]
> You have two Routers in your app there. You should only be using one.

Because I want to use HashRouter. If Do not use Routes there, I need to implement like this:
      ```
<BrowserRouter>
          <Route path={'/app/dashboard'} element={< Dashboard/>}/>
          <Route>
            <HashRouter>
              <Route path={'/detail'} element={<ItemDetail/>}/>
            </HashRouter>
          </Route>
      </BrowserRouter>
```
But, It's still not working :((

**Comment by sinhpn92** [comment]
Why do you close this ticket? @timdorr 
I didn't solve :( Please help.

**Comment by timdorr** [comment]
This isn't a support system. It's a bug tracker. You need to fix your implementation because this isn't a bug. You shouldn't have two Routers in your tree.
