### ISSUE TITLE
percent-encoding parameters inside the URL path

### ISSUE THREAD

**Issue by Pavinati** [ReactTraining/react-router#7612]
## Version
react-router: ^5.2.0

Params in urls always crash the app, no matter if not encoded, percent-encoded or double encoded

https://codesandbox.io/s/react-router-forked-wr782?file=/index.js
(uncomment the appropriate function to test the different configuration)

## Expected result
I expect there is a way of using any parameters inside a path (as long as it's a well-formed URL)

## Actual result
the app crashes in different steps, depending on the encoding strategy

**Comment by timdorr** [comment]
This is an underlying history issue. See ReactTraining/history#745

**Comment by spacejamjim** [comment]
The underlying history issue has been fixed. Is it possible to get the dependency for history updated in React Router before the release of 6
