### ISSUE TITLE
Redirect(Auth) Sandbox not working

### ISSUE THREAD

**Issue by vivek-itmtb** [ReactTraining/react-router#7614]
I Checked out the Code Sandbox for the section Redirect(Auth) in the examples tab in the Official documentation.
It doesn't show a logout button after login and the "you are not allowed" text is always there no matter if you login.
Please check it out and share the error.
[Page link](https://reactrouter.com/web/example/auth-workflow)

**Comment by timdorr** [comment]
It's updated in the code, it just hasn't been pushed out to the website yet: https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/examples/Auth.js
