### ISSUE TITLE
props.history.goBack() not work in ios WeChat browser after first history.push('xxx')

### ISSUE THREAD

**Issue by wowtrxqn** [ReactTraining/react-router#7620]
i test many times for this behavior and find the bug only in ios WeChat after first history.push()

for example :   in the Main page i click a link (use history.push) and jump into A page, but the back button ( use props.history.goBack()) is not work , but when i go on click a link(history.push) in A page jump into B page, the back button in B page can go back to A page and now the back button in the A page is working fine(can go back to Main page) !!!

No such strange behavior in Android WeChat！

In ios WeChat, you must jump 2 times to be normal, all the first jump operation cannot go back

both HashBrowser and Browser router are all find this bug！

below is my relation package
"react": "^16.11.0",
"react-dom": "^16.11.0",
"react-router-dom": "^5.2.0",

**Comment by Mr-Lucky** [comment]
@wowtrxqn 
I have the same problem，have you solved it?

**Comment by dream-approaching** [comment]
@wowtrxqn  I have the same problem，have you solved it?

**Comment by kaimzhou** [comment]
@wowtrxqn I have the same problem，have you solved it?

**Comment by XuChunxiao** [comment]
@wowtrxqn I have the same problem，have you solved it?
