### ISSUE TITLE
v6 : Where is the Redirect component ?

### ISSUE THREAD

**Issue by ostrebler** [ReactTraining/react-router#7621]
## Version

6.0.0-beta.0

## Steps to reproduce

Try to import "Redirect", or search for "redirect" in the code or in the doc.

## Expected Behavior

Having a `Redirect` component like mentioned here : https://github.com/ReactTraining/react-router/issues/7185

## Actual Behavior

`Redirect` seems to have never existed, like some sort of a Mandela effect.

**Comment by timdorr** [comment]
Use the Navigate component.
