### ISSUE TITLE
Nested Routes with path="*" yields incorrect warning

### ISSUE THREAD

**Issue by chriserickson** [ReactTraining/react-router#7624]
With the following route table:
```typescript tsx
export default function App() {
  return (
    <div className="App">
      <BrowserRouter>
        <Routes>
          <Route path="/something" element={<div>This is not important</div>} />
          <Route path="*">
            <div>
              <h1>Global Nav</h1>
              <Routes>
                <Route path="*" element={<div>Hi2</div>} />
              </Routes>
            </div>
          </Route>
        </Routes>
      </BrowserRouter>
    </div>
  );
}
```

The console is giving the following warning:
```
You rendered descendant <Routes> (or called `useRoutes`) at "/" (under <Route path="/">) but the parent route path has no trailing "*". This means if you navigate deeper, the parent won't match anymore and therefore the child routes will never render.

Please change the parent <Route path="/"> to <Route path="//*">. 
    in Routes (at App.tsx:14)
    in App (at src/​index.tsx:7) 
```

I've not been able to figure out what it means, or how to fix it. Being that there is no path matching `/`, I suspect it is a false warning.

## Version

6.0.0.beta

## Test Case

https://codesandbox.io/s/react-router-v6-nested-route-bug-zg760

**Comment by huttonr** [comment]
`<Route path="*">` is missing the element prop, but also does changing the path to `path="/*"` fix it?  (Just the top-level Route, not the nested one.)

**Comment by chriserickson** [comment]
Thanks for the help -- it wasn't clear to me when to use children vs. element.

Question: is there a better error message that could be given? I didn't find the error message very helpful for finding what I'd done wrong -- it actually seems incorrect to me and like it would send me down the wrong path in trying to find what the warning is about.

**Comment by Raman-3r** [comment]
You rendered descendant <Routes> (or called `useRoutes()`) at "/account" (under <Route path="/account">) but the parent route path has no trailing "*". This means if you navigate deeper, the parent won't match anymore and therefore the child routes will never render.

Please change the parent <Route path="/account"> to <Route path="/account/*">

app.js
<Route path="/account" element={ <ProtectedRoute component= {Profile}/>}></Route>

protectedroute.js
import { Divider } from "@material-ui/core";
import React, { Fragment } from "react";
import { useSelector } from "react-redux";
import { Navigate, Route, Routes } from "react-router-dom";

const ProtectedRoute = ({ component: Component, ...rest }) => {
  const { loading, isAuthenticated, user } = useSelector((state) => state.user);
  return (
    <Fragment>
      {loading === false && (
        <Routes>
          <Route
            {...rest}
            render={(props) => {
              if (isAuthenticated === false) {
                return <Navigate to="/login" />;
              }

              // if (isAdmin === true && user.role !== "admin") {
              //   return <Navigate to="/login" />;
              // }

              return <Component {...props} />;
            }}
          ></Route>
        </Routes>
      )}
    </Fragment>
  );
};

export default ProtectedRoute;


i use this concept to project route when user is login but i get error as a given above please suggecst me any solutin regarding this

**Comment by Raman-3r** [comment]
<Route path="/account" element={ <ProtectedRoute component= {Profile}/>}></Route>
