### ISSUE TITLE
Installing react-router taking too long

### ISSUE THREAD

**Issue by kavin25** [ReactTraining/react-router#7625]
- I am trying to install react-router-dom with `npm install react-router`. I started it about 20-30 minutes ago and it is still installing. 
- This has never happened with me before. First time, that it is taking so long to install it. 

Please resolve the issue or please tell what the issue might be

**Comment by timdorr** [comment]
This doesn't have anything to do with the library. Check your tooling or internet connection.

**Comment by GDBxNS** [comment]
Probably your App is still running while you are installing library. Just shut down the app it will take a couple of seconds to finish.
