### ISSUE TITLE
@wjin0352 Can't redirect through action.js file

### ISSUE THREAD

**Issue by s-v-d** [ReactTraining/react-router#7626]
@wjin0352 

The simplest working example:

`history.js`:

```
import createHistory from 'history/createHashHistory'
OR
import createHistory from 'history/createBrowserHistory'

export default createHistory()
```

`actions.js`:

```
import history from './history'

history.push('/500')
```

_Originally posted by @thekarel in https://github.com/ReactTraining/react-router/issues/3498#issuecomment-295151161_

I am trying to do exactly same thing. It only changes the url in address bar but not redirect the actual page.

**Comment by timdorr** [comment]
This was already answered: https://github.com/ReactTraining/react-router/issues/3498#issuecomment-301057248
