### ISSUE TITLE
v6 beta 0, wildcard after parameter not routing

### ISSUE THREAD

**Issue by btrauma8** [ReactTraining/react-router#7627]
just trying out this new wildcard thing. according to the migration docs, this should work.
i cannot get this to work.
```
<BrowserRouter>
<Routes>
<Route path="user/:id/*"><div>hello</div></Route>
</Routes>
</BrowserRouter>
```

localhost:3000/user/jeff/data
_nothing_
localhost:3000/user/jeff
**hello** _(as expected)_

am i doing something wrong, or, are the migration docs wrong, or, is there a bug? i don't know.

**Comment by bleathem** [comment]
I have this same problem.  Did you come across a solution @btrauma8 ?
