### ISSUE TITLE
State not being passed with Link

### ISSUE THREAD

**Issue by zimmicz** [ReactTraining/react-router#7628]
## Version

5.2.0

## Test Case

https://codesandbox.io/s/react-router-passing-state-ytk96?file=/src/App.js

## Steps to reproduce

Go back and forth between using the link.

## Expected Behavior

I'd expect `/world` route would receive `{hello: 'world'}` state. It works using `<Redirect />`.

## Actual Behavior

`location.state` is undefined.

**Comment by timdorr** [comment]
HashRouter doesn't support location.state: https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/docs/api/HashRouter.md
