### ISSUE TITLE
BrowserRouter forceRefresh prop does not behave as expected

### ISSUE THREAD

**Issue by paul-millar** [ReactTraining/react-router#7637]
## Version

5.2.0

## Test Case

Our use case is that we have an app that listens on a websocket for app updates. If the version on the server does not equal that on the client, then our hope is that on next link click or history.push that the page reloads. 

However, we've noticed that this doesn't update dynamically. We can see that this essentially just gets passed down to the `history` package as a prop, but the result of the API on the `BrowserRouter` is somewhat un-react in that we'd expect changes to props to actually change the behaviour. 

I've created a examples with the defaults changed below and a button to toggle:
Enabled: https://codesandbox.io/s/react-router-forcerefresh-l7xiv?file=/src/App.js
Disabled: https://codesandbox.io/s/react-router-forcerefresh-forked-xx9iu?file=/src/App.js

## Steps to reproduce
1. Navigate between the two pages with forceRefresh disabled
2. Turn on forceRefresh by clicking the button.
3. Click on a link and see that the navigation behaviour doesn't change.

## Expected Behavior
Changing the prop actually changes the navigational behaviour

## Actual Behavior
Changing the prop does not change the navigational behaviour

**Comment by timdorr** [comment]
You can trick it by using the `key` prop:
```js
<Router key={forceRefresh ? 1 : 2} forceRefresh={forceRefresh}>
```
That forces a full re-initialization every time the value changes.

**Comment by spikebrehm** [comment]
The problem with using the `key` trick is that it will cause the `<Router>` to re-mount, which has side effects like destroying open dialogs, etc. It would be really awesome if changing the `forceRefresh` prop worked out of the box.

**Comment by spikebrehm** [comment]
Here's our workaround: https://github.com/remix-run/history/pull/614#issuecomment-908367092

**Comment by mjackson** [comment]
Thanks for posting your workaround, @spikebrehm. In order for us to make this work in v5 we would need to rethink the architecture a bit since the `forceRefresh` value is actually passed into the history object's constructor, so it can't be dynamic. We could definitely do it though.

I'll keep this in mind while working on v6 so we don't have the same limitation there.
