### ISSUE TITLE
feature request: protocol and host info in useLocation

### ISSUE THREAD

**Issue by rifler** [ReactTraining/react-router#7638]
sometimes I need full url of current page to pass somewhere, for example:
```js
const Component = () => {
  const fullUrl = getFullUrlSomeHow();
  return <>
    ..some layout...
    <a href={`https://another-service.com?retpath=${encodeURIComponent(fullUrl)}`}>
      Link to another site, that do some job and redirects back
    </a>
  </>;
}
```

there are some solutions:
1) window.location. Cons - checks `typeof window !== 'undefined'` for ssr (rehydration warning), Component doesn't rerender when url changes
2) window.location.protocol + window.location.host + useLocation. Cons - checks `typeof window !== 'undefined'` for ssr (rehydration warning)
3) Store protocol&host in state (redux/context/etc) from the server, write custom hook that fetches info from useLocation and from store and combines it
4) add protocol and host to react-router :)

**Comment by timdorr** [comment]
Router is only for on-page routing. Any other elements of the URL, such as the protocol or host, are unrelated to on-page routing. If they change, that will trigger a page reload and new instances of everything in Router.

So, if you need to reference them, just use `window.location` instead of useLocation, as you're not longer using the Router location.

**Comment by rifler** [comment]
> just use window.location instead of useLocation

I describe cons of that solution

> Router is only for on-page routing. Any other elements of the URL, such as the protocol or host, are unrelated to on-page routing. If they change, that will trigger a page reload and new instances of everything in Router.

I understand, but `location` word in `useLocation` signals that this is single source of truth about location information, that have to contain protocol and host
