### ISSUE TITLE
parameter includes colon when matched in the middle of a url part

### ISSUE THREAD

**Issue by jpodpro** [ReactTraining/react-router#7641]
## Version
5.1.2

## Test Case
https://codesandbox.io/s/react-router-forked-gb036

## Steps to reproduce
if attempting to match a path like `/path/foo:id` the parameter returned when using `/path/foo:bar` is prefixed by a colon

## Expected Behavior
there should be no colon prefixing the parameter value

## Actual Behavior
there is a colon prefixing the parameter value

**Comment by timdorr** [comment]
This is expected behavior. The colon is part of the parameter definition. So you have essentially `/path/foo{id}`, therefore the colon is a part of that parameter value in the URL `/path/foo:bar`
