### ISSUE TITLE
[Website] Examples are not working (Access-Control-Allow-Origin error)

### ISSUE THREAD

**Issue by codeclown** [ReactTraining/react-router#7642]
## Version

Current website at https://reactrouter.com

## Test Case

None

## Steps to reproduce

1. Open https://reactrouter.com/web/example/basic

## Expected Behavior

Should see example on the right side of the screen

## Actual Behavior

Right side of the screen is blank:

![image](https://user-images.githubusercontent.com/211543/94915960-72b5ad00-04b6-11eb-97e5-c69ce34e371f.png)

Console shows CORS errors:

![image](https://user-images.githubusercontent.com/211543/94916028-937e0280-04b6-11eb-8187-25c48affb40d.png)

Similar issue has been reported and fixed before (#7213), but seems like it has resurfaced.

**Comment by codeclown** [comment]
Hi @CompuIves! Maybe you would be able to assist at fixing? Hope you don't mind me pinging here, but the other issue is locked.

**Comment by CompuIves** [comment]
Yes! I can help! This is a weird one, on my phone I can't seem to repro the issue. This happens when you open the example?

**Comment by codeclown** [comment]
@CompuIves Yep, tested on:

- Chrome Incognito (Mac) -> FAIL
- Safari Incognito (Mac) -> FAIL
- Firefox Incognito (Mac) -> FAIL

Curiously:

- Safari (iOS) -> PASS

**Comment by CompuIves** [comment]
Ah okay, I know enough then. I'll have a fix live in 30 min!

**Comment by CompuIves** [comment]
Oh this is interesting, I can't repro the issue in Chrome, Safari and Firefox. It might have to do with a VPN or Firewall, could you share what headers are returned for the `define` call?

**Comment by codeclown** [comment]
@CompuIves Yeah, confirmed that it only fails when I have (commercial) VPN on. Works fine when I turn it off.

Anyway, here's the headers (commercial VPN enabled):

```
alt-svc: h3-27=":443"; ma=86400, h3-28=":443"; ma=86400, h3-29=":443"; ma=86400
cache-control: private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0
cf-ray: 5dbe5fce0ebcf14a-ARN
cf-request-id: 058ada34c20000f14a8f0ce200000001
content-encoding: br
content-type: text/html; charset=UTF-8
date: Fri, 02 Oct 2020 12:19:52 GMT
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
expires: Thu, 01 Jan 1970 00:00:01 GMT
server: cloudflare
set-cookie: __cfduid=d5f5ac19f60e8dc0cf3fed644efa7272d1601641192; expires=Sun, 01-Nov-20 12:19:52 GMT; path=/; domain=.codesandbox.io; HttpOnly; SameSite=Lax; Secure
status: 403
vary: Accept-Encoding
x-frame-options: SAMEORIGIN
```

**Comment by timdorr** [comment]
Yeah, your VPN is adding that `x-frame-options: SAMEORIGIN` header, it appears. That is not on my end. Either that or Cloudflare is caching differently at wherever that VPN exit node is. Regardless, not an issue with either Router or Codesandbox.
