### ISSUE TITLE
faille to run test script  

### ISSUE THREAD

**Issue by Morteza-Jenabzadeh** [ReactTraining/react-router#7644]
I'm not sure if here is a good place to ask or not. (already tried on [SO](https://stackoverflow.com/questions/64166891/fail-to-run-react-router-test-script))
 I'd love to contribute on the awesome package but failed to run the test:
 
## what I  have doe :
yarn test 

## what happened
```
Error: Can't find a root directory while resolving a config file path.
Provided path to resolve: packages/*
```

## what expected 
run test script 

os: win 10

**Comment by timdorr** [comment]
Not sure if it works on Windows 10. I would try running within WSL or via GitHub Codespaces.
