### ISSUE TITLE
After redirect with cleanup-hook component render a previous value

### ISSUE THREAD

**Issue by qetr1ck-op** [ReactTraining/react-router#7645]
## Version

5.2.0

## Test Case

With state as context - https://codesandbox.io/s/suspicious-easley-svkt2?file=/src/App.js
With state as mobx's observable - https://codesandbox.io/s/adoring-fog-dsvew?file=/src/App.js:353-381

### Preconditions:

- component **A** as a page for react-router
- component **B** as a page for react-router
- **state** which is used in **A** and **B** 

## Expected Behavior

0. Initial state **{ value: 0 }**
1. Initial URI - **/a** 
2. React-router renders the component **A**. It renders **{ value: 0 }**.
3. Redirect to **/b**
4. Component **A** has a cleanup hook where the state was updated to  **{ value: 1 }**
5. React-router renders the component B. It renders **{ value:1 }**

## Actual Behavior

In **.5** component B renders an old state **{ value: 0 }**  (before cleanup in component A). 
After it reacts for changes for second rerender it has a new state **{ value:1 }**.

I bet either I'm doing smth wrong or I don't understand how it's possible to clean/reset global stores/states.
I'd appreciate any feedback.

**Comment by timdorr** [comment]
This doesn't have anything to do with React Router. You're using Context incorrectly. By changing a property on the context value, you're not triggering an update of that context value. This is much like using useRef instead of useState. You need some sort of mechanism to broadcast context updates through your tree.

**Comment by qetr1ck-op** [comment]
Right, it was a silly attempt. Fixed the demo with context - https://codesandbox.io/s/suspicious-easley-svkt2?file=/src/App.js.
Less verbose demo with mobx - https://codesandbox.io/s/adoring-fog-dsvew?file=/src/App.js:353-381.

**Comment by qetr1ck-op** [comment]
Should I open a new one or there's a chance you have a look at this one? @timdorr
