### ISSUE TITLE
[v6] Attach arbitrary data to route (not on navigation)

### ISSUE THREAD

**Issue by benneq** [ReactTraining/react-router#7648]
I'd like to attach some data per Route, for example a Page Title, which can then be picked up and used within a component.

Something like this:
```
// route definitions:
const MyRoutes = () => {
  return (
    <Routes>
      <Route path="/foo" element={<FooPage />} data={{ title: "Foo" }} />
      <Route path="/bar" element={<BarPage />} data={{ title: "Bar" }} />
    </Routes>
  );
};
```

```
// page header component
const PageHeader = () => {
  const { data } = useActiveRoute(); // non-existing hook which returns the "data" field

  return (
    <header>{data.title}</header>
  );
};
```

Even better would be a way traverse the whole "active routes path", i.e. `currentRoute> currentRoute.parent > currentRoute.parent.parent > etc.`. This way it would be super easy to create and display breadcrumbs.

**Comment by timdorr** [comment]
You would just pass that in as props to your component inside of the `element` prop:
```js
// route definitions:
const MyRoutes = () => {
  return (
    <Routes>
      <Route path="/foo" element={<FooPage title="Foo" />} />
      <Route path="/bar" element={<BarPage title="Bar" />} />
    </Routes>
  );
};
```

**Comment by benneq** [comment]
That's not what I'm looking for. I need that data in a completely different component.

Take for example this component tree:
```
<App>
  <Router>
    <Header>
      <!-- Here I need the data -->
      {currentRoute.data.title}
    </Header>
    <Main>
      <Routes>
        <Route path="/foo" element={<FooPage />} data={{ title: "Foo" }} />
        <Route path="/bar" element={<BarPage />} data={{ title: "Bar" }} />
      </Routes>
    </Main>
  <Router>
</App>
```

**Comment by timdorr** [comment]
You wouldn't be able to do that. The data wouldn't be in `currentRoute` before that Route has been rendered.

**Comment by benneq** [comment]
That's why I was requesting something like a `useCurrentRoute()` hook, that will trigger a rerender of `Header` component every time `currentRoute` changes. This way I could access `currentRoute.data` for every route change.

**Comment by timdorr** [comment]
You can already do that with a Context: https://reactjs.org/docs/context.html

We're not going to implement this because it's already a built-in React feature.
