### ISSUE TITLE
Empty string hash fragment `#` is stripped from `to` prop

### ISSUE THREAD

**Issue by rafgraph** [ReactTraining/react-router#7649]
## Version

5.2.0

## Test Case

https://codesandbox.io/s/react-router-forked-z49on

## Steps to reproduce
Create this link
`<Link to="/about#">About</Link>`

## Expected Behavior
For the href rendered in the browser to be `.../about#`

## Actual Behavior
The herf rendered in the browser is `.../about` with the `#` stripped.

## Why
The empty string hash fragment `#` means scroll to top.
https://html.spec.whatwg.org/multipage/browsing-the-web.html#target-element
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#attr-href

**Comment by timdorr** [comment]
You should use an `a`, not Link, to do this.

**Comment by rafgraph** [comment]
In https://github.com/rafgraph/react-router-hash-link, which wraps `<Link>` and provides hash link scroll functionality, I use `#` for scroll to top functionality as per the spec. `react-router-hash-link` receives the `to` prop first so it's able to know if `#` is present, but when it's render in the DOM the `#` is stripped which is confusing to the user, as well analytics tracking, etc.

Using an `a` tag only works if on the same the same path, or don't provide a path, otherwise it causes a full page load. If you use an `a` tag with `href` `/about#` on the `/topics` page it causes a full page load. Also using it with `react-router-hash-link` means you a get a lot of nice scroll functionality for free.

What's the reason for stripping it?
Seems kind of harmless to be spec compliant in this instance, and allow other libraries to add functionality that `react-router` has chosen not to implement.

**Comment by rafgraph** [comment]
So this is causing a bug in `react-router-hash-link` https://github.com/rafgraph/react-router-hash-link/pull/69 for `<NavHashLink>` because when the `#` is stripped the location doesn't doesn't match the `to` prop so the link isn't active.

@timdorr would you consider reopening this? Thanks.
