### ISSUE TITLE
[Bug: v5] Wrapped <Route/> breaks the next <Route/>

### ISSUE THREAD

**Issue by pobch** [ReactTraining/react-router#7651]
## Version

**5.2.0**

## Test Case

https://codesandbox.io/s/agitated-grass-mcm3y?file=/src/App.js

## Steps to reproduce

1. Go to this [codesandbox](https://codesandbox.io/s/agitated-grass-mcm3y?file=/src/App.js)
2. Click "Page B" link

## Expected Behavior

The link should bring us to path `/b` and render "BBBB" text on the screen

## Actual Behavior

The empty page was rendered instead.

To make it work as expected, we need to uncomment line 27 and 28. The problem is these props are irrelevant to the `WrappedRoute` component (which doesn't accept any props), but somehow make a different result.

**Comment by timdorr** [comment]
Switch reads the props of its children directly, so you can't do this.
