### ISSUE TITLE
react router appears to be incompatible with react 16.13

### ISSUE THREAD

**Issue by jwlogemann** [ReactTraining/react-router#7652]
When you install react-router in a basic react quickstart project it gives the following error:

Failed to compile
./node_modules/react-router-dom/esm/react-router-dom.js
Module not found: Can't resolve '/home/react/node_modules/babel-loader/lib/index.js' in '/home/react'

**Comment by timdorr** [comment]
It works just fine with any version of React. Something is wrong with your installation, not this library.

**Comment by Alexej-Vakulich** [comment]
@timdorr @jwlogemann I have the same error
