### ISSUE TITLE
Migration guide from v3 to v6?

### ISSUE THREAD

**Issue by Svish** [ReactTraining/react-router#7655]
We have an older website which got stuck on `react-router` v3 because of the drastic changes that came in v4. Main issue was that all the routing in this website was based around single routes files with nested routes, and a rewrite of that was just too much and impossible to get prioritized. Maybe others are in the same situation?

Either way, I see that in v6, this feature is coming back?

> Another important reason for using the element prop in v6 is that <Route children> is reserved for nesting routes. This is one of people's favorite features from v3 and @reach/router, and we're bringing it back in v6.

For the v6 release, would it be possible for someone knowledgeable to write a migration guide for upgrading from v3 to v6? Not necessarily super detailed, but just _some_ sort of guidance with coming from v3 in mind, particularly surrounding how to migrate v3 nested routes to v6 nested routes?

🙏 #hopeful-we-can-finally-upgrade-and-get-those-tasty-hooks-in-this-project-as-well

**Comment by timdorr** [comment]
If someone wants to write that guide and submit it as a PR, we can definitely include it. But it's not something we're going to write ourselves, given the large number of changes between the two and the age since we've worked on anything v3-related.

**Comment by Svish** [comment]
Fair enough. 👍
