### ISSUE TITLE
Using <Switch /> makes location.state accessed from withRouter HOC to not be defined.

### ISSUE THREAD

**Issue by npetridis** [ReactTraining/react-router#7656]
## Version

In my environment: 4.3.1
In sandbox provided: 5.2.0

## Test Case

https://codesandbox.io/s/react-router-forked-vd9kr?file=/index.js

## Steps to reproduce
1. press the Home link to go to `/test` page
2. In the comment at the sandbox when using Switch inside a nested route access to location.state from withRouter is overwritten. When not (use Fragment at the sandbox) then it works as expected.

## Expected Behavior
When using Switch and I access location.state props from withRouter HOC I can see the state I have passed to the specific route.
<img width="554" alt="Screenshot 2020-10-14 at 3 39 34 PM" src="https://user-images.githubusercontent.com/6136507/95989886-83114480-0e33-11eb-9dfb-0cb929800473.png">

## Actual Behavior
When using Switch and I access location.state props from withRouter HOC the state not defined.
<img width="554" alt="Screenshot 2020-10-14 at 3 39 47 PM" src="https://user-images.githubusercontent.com/6136507/95989911-8a385280-0e33-11eb-9b24-a24c7ca0d6a3.png">

**Comment by timdorr** [comment]
[Switch sets the `location` prop](https://github.com/ReactTraining/react-router/blob/master/packages/react-router/modules/Switch.js#L40) on the child it selects to render. This isn't the correct way to set that state anyways. You should be setting it on the Link so it's saved in the history stack.
