### ISSUE TITLE
Upgrade path-to-regexp to latest

### ISSUE THREAD

**Issue by rahul-sharma-uipath** [ReactTraining/react-router#7658]
## Version

react-router 5.1.2
npm version 6.14.8
node >12.19.0
path-to-regexp 6.1.0

## Steps to reproduce

run create-react-app with the above in package.json and the app will fail to compile

## Expected Behavior

it should compile 

## Actual Behavior

Using the above config results in the following error 

![image](https://user-images.githubusercontent.com/50849907/96047043-522c1200-0e29-11eb-9415-0535f3027bed.png)

We believe this is because the `path-to-regexp` package currently imported in `react-router` is `1.7.0` and the latest version that we are using in our app does not include the default export that `react-router` is looking for

**Comment by timdorr** [comment]
We can't upgrade path-to-regexp because they removed `/foo*` matching. You need to get a separate version of path-to-regexp for React Router to use. npm should handle that automatically, so I would look into why that sub-dependency was upgraded. It's not something we did ourselves, as we request the 1.x version specifically.

**Comment by deenamo** [comment]
I started getting the same error in my custom app (non-CRA) after doing some unrelated dependency updates (like upgrade to Webpack 5):
```
ERROR in ./node_modules/react-router/esm/react-router.js 9:0-42
Module not found: Error: Can't resolve 'path-to-regexp' in '/Users/[...]/node_modules/react-router/esm'
 @ ./node_modules/react-router-dom/esm/react-router-dom.js
```

I was able to work around the error by removing `node_modules` and `package-lock.json`, followed by a complete reinstall with `npm install --force`

**Comment by rahul-sharma-uipath** [comment]
@deenamo thanks for this suggestion, our workaround was forking path-to-regexp with a different name internally so it didn't conflict with the import from `react-router`

**Comment by anandrikka** [comment]
> ## Version
> react-router 5.1.2 npm version 6.14.8 node >12.19.0 path-to-regexp 6.1.0
> 
> ## Steps to reproduce
> run create-react-app with the above in package.json and the app will fail to compile
> 
> ## Expected Behavior
> it should compile
> 
> ## Actual Behavior
> Using the above config results in the following error
> 
> ![image](https://user-images.githubusercontent.com/50849907/96047043-522c1200-0e29-11eb-9415-0535f3027bed.png)
> 
> We believe this is because the `path-to-regexp` package currently imported in `react-router` is `1.7.0` and the latest version that we are using in our app does not include the default export that `react-router` is looking for

@rahul-sharma-uipath did you figure out this issue?
