### ISSUE TITLE
Attempted import error: '__RouterContext' is not exported from 'react-router'.

### ISSUE THREAD

**Issue by naresh-FD** [ReactTraining/react-router#7659]
In  "react-router-dom": "^5.2.0",

![image](https://user-images.githubusercontent.com/50324374/96331303-e987a400-1079-11eb-97d4-a1a92d013cc4.png)

**Comment by timdorr** [comment]
You should not be using that context directly. Regardless, it's included, so something is wrong with your installation.

**Comment by jedwards1211** [comment]
@timdorr we need the context **really badly** to be able to get at it in modern components that use hooks.

**Comment by jedwards1211** [comment]
Yes the hooks didn't exist at the time I wrote that comment

**Comment by Edison4mobile** [comment]
so what is the solution of this error?
![image](https://user-images.githubusercontent.com/31374816/177079225-e249b5c9-9793-404e-b6ef-139c6adc3f2d.png)
