### ISSUE TITLE
nav bar disappears when changing route

### ISSUE THREAD

**Issue by mosodev** [ReactTraining/react-router#7664]
Got the basename solution from https://github.com/ReactTraining/react-router/issues/7128.  With the basename in the Routes element, the <nav> element will disappear after clicking on the nav link.  We need a way to have the nav receives a basename and stays on the page after changing route.   In router 5.0, we can do that by setting basename in the BrowserRouter level.   Is there a way to make the nav bar stays after changing route and applying the basename on the link in 6.0?

```jsx
// url where new router is created: https://my-site/who/users
const RootModule = () => {
  return (
    <main>
      <BrowserRouter>
        <Routes basename="who/users">
          <nav>
            <Link to="">Home</Link>
            <Link to="who/users/about">About</Link>
            <Link to="who/users/users">Users</Link>
          </nav>
          <Routes>
            <Route path="/" element={<Home />} />
            <Route path="who/users/about" element={<About />} />
            <Route path="who/users/users" element={<Users />} />
          </Routes>
        </Routes>
      </BrowserRouter>
    </main>
  );
};
```

Thanks.

**Comment by zlksnk** [comment]
No as of now, this is a dupe of #7216.
