### ISSUE TITLE
Redirects when reloading using lazy loading

### ISSUE THREAD

**Issue by halvardssm** [ReactTraining/react-router#7666]
## Version

5.2.0

## Test Case

https://codesandbox.io/s/hungry-robinson-5w30d

## Steps to reproduce

1. go to codesandbox ^
2. press link (goto about)
3. reload the embeded browser
4. notice how the page redirects you to home

## Expected Behavior

Expected that the page does not redirect me back to the home page when reloading using lazy loading.

## Actual Behavior

The page redirects me to the home page when reloading using lazy loading.

**Comment by timdorr** [comment]
`Suspense` needs to be outside of the `Switch`. `Switch` only works on the first level of children, so it's getting in the way.
