### ISSUE TITLE
Jfc, do you have to change the API *every* version?

### ISSUE THREAD

**Issue by rw3iss** [ReactTraining/react-router#7668]
It's a freaking router... how do you decide to change how to talk to it every damn iteration? Just settle on something, ffs.

**Comment by pshrmn** [comment]
v4 was released in April 2017 and [v5 is v4](https://reacttraining.com/blog/react-router-v5/#why-the-major-version-bump). v6 is a change, but if you're satisfied with v4/v5, then nothing is forcing you to switch.

**Comment by rw3iss** [comment]
I know. Just settle on a damn API already, please.

**Comment by timdorr** [comment]
Please don't be an asshole to folks giving you software for free.
