### ISSUE TITLE
[v6] useLocation() generic parameter missing

### ISSUE THREAD

**Issue by ppbl** [ReactTraining/react-router#7670]
## Version

**v6.0.0-beta.0**

## Expected Behavior

```typescript
const { state } = useLocation<any>()
```

## Actual Behavior
error: `There should be 0 type parameters, but 1`

Use the d.ts file that comes with v6, v5 supports generics

**Comment by timdorr** [comment]
https://github.com/ReactTraining/react-router/pull/7326#issuecomment-626418225
