### ISSUE TITLE
`exact` prop should not be passed to DOM element

### ISSUE THREAD

**Issue by cgolinski** [ReactTraining/react-router#7672]
## Version
react-router-dom 5.1.0
styled-components 4.3.2

## Steps to reproduce
```
import { Link } from 'react-router-dom';
import styled from 'styled-components';

const MyComponent = () => (
  <StyledLink
    to="about"
    exact={false}
  >
    Go to About page
  </StyledLink>
);

const StyledLink = styled(Link)`
  color: white;
  display: flex;
  align-items: center;

  &:hover {
    opacity: 88%;
  }
`;
```

## Expected Behavior
<Link> renders and works with no console errors. 

## Actual Behavior
<Link> renders and works but shows a console error: 

>received `false` for non-boolean attribute `exact`

<img width="780" alt="received_false_for_non_boolean_attribute_exact" src="https://user-images.githubusercontent.com/22013506/97216233-e6886400-179b-11eb-86c3-7b99871c82de.png">

## Suspected cause

`styled-components` correctly passes all props to `react-router-dom`'s custom React component `<Link>`. I think `react-router-dom` is passing `<Link>`'s `exact` prop to its `<a>`. It should not be passing it, as `exact` is not an attribute on `<a>` tags.

> If the styled target is a simple element (e.g. styled.div), styled-components passes through any known HTML attribute to the DOM. If it is a custom React component (e.g. styled(MyComponent)), styled-components passes through all props.
-- https://styled-components.com/docs/basics#passed-props

> The warning message below indicates that non-standard attributes are being attached to HTML DOM elements such as `<div>` or `<a>`. If you are seeing this warning message, it is likely that you or a library you are using is attaching props as attributes to HTML DOM elements. 
`Warning: Received "true" for a non-boolean attribute`
-- https://styled-components.com/docs/faqs#why-am-i-getting-html-attribute-warnings

**Comment by timdorr** [comment]
`Link` doesn't have an `exact` prop, only `NavLink` does. You shouldn't be passing that prop to `Link` or an `<a>`.
