### ISSUE TITLE
[Feature request] Expose a context for relative Link's basepath.

### ISSUE THREAD

**Issue by tranvansang** [ReactTraining/react-router#7674]
# Motivation

In several projects I have joined, we had the pattern in which we have to prepend a prefix to mostly every Link component.

For example, in a multilingual app, I have to create a `LocaleLink` component that gets the current locale and prepend the appropriate prefix to the target, for e.g. `/ja`, `/en`.

In another similar case, in a multi-tenant application, we have to prefix the tenant id to the Link components, too.

# Background information why I propose this feature request

Minutes ago, I read in the [v6 pre-announcement post](https://reacttraining.com/blog/react-router-v6-pre/) which announces that react-router v6 will support relative path in the Link component. The post is old already. I just got it too later. After that, I also read several recent v6-related docs.

When reading the summary, I thought that with the relative path feature of the Link component, I can remove my `LocaleLink` component (that gets the current locale and prepend the locale prefix). Unfortunately, in the current stage (at least based on what I read from the current docs), the Link will be relative to the nearest Route's basepath, no way to customize the basepath.

**It is possible if the team could create and expose a context to overwrite the basepath for Link components that have a relative target (i.e., non-absolute pathname)? I do not think it will break any existing feature.**

Finally, thank you very much for your awesome work.

**Comment by timdorr** [comment]
Just make the language a param and use the `useParams()` hook to read it from the URL.

**Comment by coreyward** [comment]
@timdorr This is an old issue, but for what it's worth, this recommendation [goes against best practices](https://developers.google.com/search/docs/specialty/international/managing-multi-regional-sites#locale-specific-urls).
