### ISSUE TITLE
After installing react router dom getting npm ERR! code ELIFECYCLE 0 error

### ISSUE THREAD

**Issue by krisrajzlive** [ReactTraining/react-router#7676]
After installing react-router-dom and its types everything seems broken and I am getting error npm ERR! code ELIFECYCLE. Googled it and tried everything still no respite. I would appreciate lending any help to fix it. Have spent more than two days on this still can't figure out. Tried deleting the entire solution and started from session 7 and I found react-router-dom is the causing the issue.

PS C:\Users\krisrajz\source\repos\Reactivities\client-app> npm start

> client-app@0.1.0 start C:\Users\krisrajz\source\repos\Reactivities\client-app

> react-scripts start

C:\Users\krisrajz\source\repos\Reactivities\client-app\node_modules\react-scripts\scripts\utils\verifyTypeScriptSetup.js:231

        appTsConfig.compilerOptions[option] = suggested;

                                            ^

TypeError: Cannot add property noFallthroughCasesInSwitch, object is not extensible

    at verifyTypeScriptSetup (C:\Users\krisrajz\source\repos\Reactivities\client-app\node_modules\react-scripts\scripts\utils\verifyTypeScriptSetup.js:231:45)

    at Object.<anonymous> (C:\Users\krisrajz\source\repos\Reactivities\client-app\node_modules\react-scripts\scripts\start.js:31:1)

    at Module._compile (internal/modules/cjs/loader.js:1133:30)

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)

    at Module.load (internal/modules/cjs/loader.js:977:32)

    at Function.Module._load (internal/modules/cjs/loader.js:877:14)

    at internal/main/run_main_module.js:18:47

npm ERR! code ELIFECYCLE

npm ERR! errno 1

npm ERR! client-app@0.1.0 start: `react-scripts start`

npm ERR! Exit status 1

npm ERR!

npm ERR! Failed at the client-app@0.1.0 start script.

npm ERR! A complete log of this run can be found in:

npm ERR!     C:\Users\krisrajz\AppData\Roaming\npm-cache\_logs\2020-11-01T10_18_22_738Z-debug.log

PS C:\Users\krisrajz\source\repos\Reactivities\client-app> npm remove react-router-dom

removed 12 packages and audited 2185 packages in 18.938s

121 packages are looking for funding

  run `npm fund` for details

found 0 vulnerabilities

PS C:\Users\krisrajz\source\repos\Reactivities\client-app> npm cache clean

npm ERR! As of npm@5, the npm cache self-heals from corruption issues and data extracted from the cache is guaranteed to be valid. If you want to make sure everything is consistent, use 'npm cache verify' instead. On the other hand, if you're debugging an issue with the installer, you can use `npm install --cache /tmp/empty-cache` to use a temporary cache instead of nuking the actual one.

npm ERR!

npm ERR! If you're sure you want to delete the entire cache, rerun this command with --force.

npm ERR! A complete log of this run can be found in:

npm ERR!     C:\Users\krisrajz\AppData\Roaming\npm-cache\_logs\2020-11-01T10_19_32_465Z-debug.log

PS C:\Users\krisrajz\source\repos\Reactivities\client-app> npm clean

Usage: npm <command>

where <command> is one of:

    access, adduser, audit, bin, bugs, c, cache, ci, cit,

    clean-install, clean-install-test, completion, config,

    create, ddp, dedupe, deprecate, dist-tag, docs, doctor,

    edit, explore, fund, get, help, help-search, hook, i, init,

    install, install-ci-test, install-test, it, link, list, ln,

    login, logout, ls, org, outdated, owner, pack, ping, prefix,

    profile, prune, publish, rb, rebuild, repo, restart, root,

    run, run-script, s, se, search, set, shrinkwrap, star,

    stars, start, stop, t, team, test, token, tst, un,

    uninstall, unpublish, unstar, up, update, v, version, view,

    whoami

npm ERR! code E404

npm ERR! 404 Not Found - GET https://registry.npmjs.org/react-routerdom - Not found

npm ERR! 404

npm ERR! 404  'react-routerdom@5.0.1' is not in the npm registry.

npm ERR! 404 You should bug the author to publish it (or use the name yourself!)

npm ERR! 404

npm ERR! 404 Note that you can also install from a

npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:

npm ERR!     C:\Users\krisrajz\AppData\Roaming\npm-cache\_logs\2020-11-01T10_21_08_777Z-debug.log

PS C:\Users\krisrajz\source\repos\Reactivities\client-app> npm install react-router-dom@5.0.1

+ react-router-dom@5.0.1

added 12 packages from 6 contributors and audited 2197 packages in 46.731s

121 packages are looking for funding

  run `npm fund` for details

found 0 vulnerabilities

PS C:\Users\krisrajz\source\repos\Reactivities\client-app> install @types/react-router-dom@4.3.4

install : The term 'install' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was 

included, verify that the path is correct and try again.

At line:1 char:1

+ install @types/react-router-dom@4.3.4

+ ~~~~~~~

PS C:\Users\krisrajz\source\repos\Reactivities\client-app> npm start

> client-app@0.1.0 start C:\Users\krisrajz\source\repos\Reactivities\client-app

> react-scripts start

C:\Users\krisrajz\source\repos\Reactivities\client-app\node_modules\react-scripts\scripts\utils\verifyTypeScriptSetup.js:231

        appTsConfig.compilerOptions[option] = suggested;

                                            ^

TypeError: Cannot add property noFallthroughCasesInSwitch, object is not extensible

    at verifyTypeScriptSetup (C:\Users\krisrajz\source\repos\Reactivities\client-app\node_modules\react-scripts\scripts\utils\verifyTypeScriptSetup.js:231:45)

    at Object.<anonymous> (C:\Users\krisrajz\source\repos\Reactivities\client-app\node_modules\react-scripts\scripts\start.js:31:1)

    at Module._compile (internal/modules/cjs/loader.js:1133:30)

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)

    at Module.load (internal/modules/cjs/loader.js:977:32)

    at Function.Module._load (internal/modules/cjs/loader.js:877:14)

    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)

    at internal/main/run_main_module.js:18:47

npm ERR! code ELIFECYCLE

npm ERR! errno 1

npm ERR! client-app@0.1.0 start: `react-scripts start`

npm ERR! Exit status 1

npm ERR!

npm ERR! Failed at the client-app@0.1.0 start script.

npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

npm ERR!     C:\Users\krisrajz\AppData\Roaming\npm-cache\_logs\2020-11-01T10_24_22_282Z-debug.log

PS C:\Users\krisrajz\source\repos\Reactivities\client-app>

log:
0 info it worked if it ends with ok 1 verbose cli [ 1 verbose cli   'C:\\Program Files\\nodejs\\node.exe', 1 verbose cli   'C:\\Users\\krisrajz\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js', 1 verbose cli   'start' 1 verbose cli ] 2 info using npm@6.14.8 3 info using node@v12.16.3 4 verbose run-script [ 'prestart', 'start', 'poststart' ] 5 info lifecycle client-app@0.1.0~prestart: client-app@0.1.0 6 info lifecycle client-app@0.1.0~start: client-app@0.1.0 7 verbose lifecycle client-app@0.1.0~start: unsafe-perm in lifecycle true 8 verbose lifecycle client-app@0.1.0~start: PATH: C:\Users\krisrajz\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\krisrajz\source\repos\Reactivities\client-app\node_modules\.bin;C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\iCLS\;C:\Program Files\Intel\Intel(R) Management Engine Components\iCLS\;C:\Program Files\Microsoft MPI\Bin\;C:\Windows\System32;C:\Windows;C:\Windows\System32\wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\;C:\Program Files\Microsoft SQL Server\140\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\150\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\ManagementStudio\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\PROGRA~1\Java\JDK18~1.0_2\bin;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\Users\krisrajz\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Java\jdk1.8.0_201\bin;C:\Users\krisrajz\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\krisrajz\.dotnet\tools;C:\Users\krisrajz\AppData\Local\Programs\Fiddler;C:\Users\krisrajz\AppData\Roaming\npm;C:\Users\krisrajz\AppData\Local\Microsoft\WindowsApps;C:\Users\krisrajz\.dotnet\tools 9 verbose lifecycle client-app@0.1.0~start: CWD: C:\Users\krisrajz\source\repos\Reactivities\client-app 10 silly lifecycle client-app@0.1.0~start: Args: [ '/d /s /c', 'react-scripts start' ] 11 silly lifecycle client-app@0.1.0~start: Returned: code: 1  signal: null 12 info lifecycle client-app@0.1.0~start: Failed to exec start script 13 verbose stack Error: client-app@0.1.0 start: `react-scripts start` 13 verbose stack Exit status 1 13 verbose stack     at EventEmitter.<anonymous> (C:\Users\krisrajz\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16) 13 verbose stack     at EventEmitter.emit (events.js:310:20) 13 verbose stack     at ChildProcess.<anonymous> (C:\Users\krisrajz\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14) 13 verbose stack     at ChildProcess.emit (events.js:310:20) 13 verbose stack     at maybeClose (internal/child_process.js:1021:16) 13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5) 14 verbose pkgid client-app@0.1.0 15 verbose cwd C:\Users\krisrajz\source\repos\Reactivities\client-app 16 verbose Windows_NT 10.0.19041 17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\krisrajz\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start" 18 verbose node v12.16.3 19 verbose npm  v6.14.8 20 error code ELIFECYCLE 21 error errno 1 22 error client-app@0.1.0 start: `react-scripts start` 22 error Exit status 1 23 error Failed at the client-app@0.1.0 start script. 23 error This is probably not a problem with npm. There is likely additional logging output above. 24 verbose exit [ 1, true ]

Googled it and tried everything such as removing node_modules, recreating dependeices etc.,, still having issue.

Source code: https://github.com/krisrajzlive/Reactivities

Thank you

Regards

Raj

**Comment by timdorr** [comment]
This has nothing to do with React Router.
