### ISSUE TITLE
require babel/runtime@7.12.1 will report ERR_REQUIRE_ESM

### ISSUE THREAD

**Issue by linxiaowu66** [ReactTraining/react-router#7677]
version: react-router-dom@5.2.0

After installing the new babel/runtime version will report ERR_REQUIRE_ESM. And this issue babel team has the workaround: https://github.com/babel/babel/issues/12299, so react-router-dom has any plan to solve this issue?

**Comment by timdorr** [comment]
That isn't something we maintain, so we have no ability to fix it. If your environment requires a certain version of it to work, just add that as a dependency to your project to ensure it resolves to the right version.
