### ISSUE TITLE
Link component prop example produces broken output

### ISSUE THREAD

**Issue by peterjosling** [ReactTraining/react-router#7678]
The example in the documentation for `Link`'s `component` prop generates a broken link with no `href`, that performs no navigation when clicked.

```
const FancyLink = React.forwardRef((props, ref) => (
  <a ref={ref}>💅 {props.children}</a>
))

<Link to="/" component={FancyLink} />
```

My expectation from reading the documentation was that the above snippet would generate a clickable link that performs all the same logic as a regular `<Link>` such as preventing default browser navigation, supporting middle/ctrl/cmd click etc. From looking at the code, it seems that all of this logic is actually on the default `component`, meaning you have to reimplement this portion of the `Link` behaviour to use a custom `<a>` tag.

What's the intended behaviour for this prop? Either the documentation should be updated (so that the example has an href and an onclick handler to prevent navigation), or the component should be updated so that the href/onclick behaviour gets applied to custom components.

## Version
5.2.0

## Test Case
https://jsfiddle.net/m1e3ogxz/3/

## Expected Behavior
A clickable link is generated that navigates when clicked.

## Actual Behavior
An `<a>` tag with no href is generated. Nothing happens when clicked.

**Comment by timdorr** [comment]
This is already fixed on master, it just hasn't been propagated back to the website yet: https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/docs/api/Link.md

**Comment by peterjosling** [comment]
That updated example renders as a link correctly now, but clicking it still performs browser navigation. Is the intention that the user needs to add their own onclick handler and new tab handling?

Updated jsfiddle: https://jsfiddle.net/m1e3ogxz/5/

**Comment by timdorr** [comment]
For that, you need to consume and use the `navigate` prop, like so: 

```js
const FancyLink = ({ children, navigate, ...props }) => (
  <a
    {...props}
    onClick={(e) => {
      e.preventDefault();
      navigate();
    }}
  >
    💅 {children}
  </a>
);
```

**Comment by peterjosling** [comment]
But then to get correct new tab handling I need to add the rest of the code from the default onClick handler:

```
const FancyLink = ({ children, navigate, ...props }) => (
    <a
      {...props}
      onClick={(e) => {
        try {
          if (onClick) onClick(event);
        } catch (ex) {
          event.preventDefault();
          throw ex;
        }

        if (
          !event.defaultPrevented && // onClick prevented default
          event.button === 0 && // ignore everything but left clicks
          (!target || target === "_self") && // let browser handle "target=_blank" etc.
          !isModifiedEvent(event) // ignore clicks with modifier keys
        ) {
          event.preventDefault();
          navigate();
        }
      }}
    >
      💅 {children}
    </a>
);
```

at which point I feel like I've re-implemented most of `Link`... Should the default `LinkAnchor` behaviour not be exposed somehow? I'm struggling to see what the value of the `component` prop is in its current state.

**Comment by timdorr** [comment]
It was a community addition, so it solves someone's use case. I agree, it has low value as-is, but we're relying on the community if it needs to be refactored or improved.

**Comment by hugmanrique** [comment]
I've commented a possible solution for removing this boilerplate in the linked issue right above. While it focuses on v6, I think it's also applicable to v5.
