### ISSUE TITLE
"Redirect" doesn't work because of history@5.0.0

### ISSUE THREAD

**Issue by smitroshin** [ReactTraining/react-router#7680]
## Version
```
"history": "^5.0.0",  
"react": "^17.0.1",  
"react-dom": "^17.0.1",  
"react-router-dom": "^5.2.0",  
"react-scripts": "4.0.0",  
```

## Test Case

https://codesandbox.io/s/react-router-redirect-issue-ugs02

## Steps to reproduce
Simulate navigation to protected route. Just navigate to `/` route. 

## Expected Behavior
Because you are not logged in, app should redirect you to `/login` page.

## Actual Behavior
URL is changing but component did not mounting.

## Comments
`history` package recently released a major version - `v5.0.0`.
Redirect doesn't work because of it. I also describe [issue on history repository](https://github.com/ReactTraining/history/issues/840).

[There](https://github.com/ReactTraining/history/issues/811) can also be some changes what breaks `react-router` .

I use `Router` with `history` instead of `BrowserRouter` with `useHistory` hook, because I need often access to history from outside of react components.
It would be great if in the future `react-router` will get me this feature without using history package :)

**Comment by timdorr** [comment]
React Router 5.x isn't compatible with history 5.0.0. [This is listed in our dependencies.](https://github.com/ReactTraining/react-router/blob/master/packages/react-router/package.json#L40) Simply install a version within the `^4.9.0` range.

**Comment by chasecaleb** [comment]
@timdorr Since you ("you" as in ReactTraining) maintain both of these dependencies, are there plans to address this? Staying on an outdated dependency long-term is not a good solution for many developers/companies.

See also the related discussion here: https://github.com/ReactTraining/history/issues/810

**Comment by timdorr** [comment]
React Router v6 uses History v5. We already request the correct version in our dependencies for either version of Router.
