### ISSUE TITLE
useParams type problem in Typescript with strictNullChecks

### ISSUE THREAD

**Issue by paveldvorak5** [ReactTraining/react-router#7681]
## Version

6.0.0-beta.0

## Test Case

https://codesandbox.io/s/react-router-forked-qwcx0?file=/index.tsx

## Steps to reproduce
There error is not shown because CodeSandbox doesn't support strict mode, but it shows if you download it and run locally

## Expected Behavior
The useParams return type is defined as  Record<string, string>
But in strictNullChecks mode ist's parsed like Record<string, string|undefined>
Quick and dirty fix is Record<string, any>
Is there some way to fix this?

## Actual Behavior
![obrazek](https://user-images.githubusercontent.com/14863835/98450356-733c0600-213c-11eb-9dd2-0c067a095e4e.png)

Thanks

**Comment by timdorr** [comment]
That isn't how that type should behave. Something else must be going on in your environment. Here's it working find in the playground: https://www.typescriptlang.org/play?useDefineForClassFields=true&noUnusedLocals=true&noUnusedParameters=true&preserveConstEnums=true&target=99#code/C4TwDgpgBACghgJzgWwM5QLxQEoQMYD2CAJgDyrAICWAdgOYA0UF19AfANwCwAULxAA8wRYFABmAVxp5gVAjSgTUEeEjQAKAJQAuWIhToA3ryhQEEYBIQLDAXyhx0qg9x63evQjQpQw+tJiKys4amp7yPn5UCACSxIEAchLIAEYQCAB0fgjKMTTA6tkGWXDRcWF8PF6oBAA2EBm1BHSFpbHEmkA

**Comment by paveldvorak5** [comment]
No, it's not, the error is shown when also this is ticked
![obrazek](https://user-images.githubusercontent.com/14863835/98584707-91ce0880-22c6-11eb-8ba9-d4956e4cb2d8.png)
![obrazek](https://user-images.githubusercontent.com/14863835/98584752-9eeaf780-22c6-11eb-8c28-93b35f1b6106.png)

**Comment by timdorr** [comment]
This is a beta feature and not a default of `strict` mode, so I wouldn't expect us to add support for it. If you have this enabled you can get around it with a null coalescing operator: `parseInt(params.pairId ?? '')`

**Comment by paveldvorak5** [comment]
OK,
I have solved it like this:
`const pairId = Number.parseInt( params.pairId as string )`

**Comment by artola** [comment]
> That isn't how that type should behave. Something else must be going on in your environment. Here's it working find in the playground: https://www.typescriptlang.org/play?useDefineForClassFields=true&noUnusedLocals=true&noUnusedParameters=true&preserveConstEnums=true&target=99#code/C4TwDgpgBACghgJzgWwM5QLxQEoQMYD2CAJgDyrAICWAdgOYA0UF19AfANwCwAULxAA8wRYFABmAVxp5gVAjSgTUEeEjQAKAJQAuWIhToA3ryhQEEYBIQLDAXyhx0qg9x63evQjQpQw+tJiKys4amp7yPn5UCACSxIEAchLIAEYQCAB0fgjKMTTA6tkGWXDRcWF8PF6oBAA2EBm1BHSFpbHEmkA

@timdorr  I find that the typing for return of `useParams` that is `Record<string, string>` might be wrong, because should be `Record<string, string | undefined>`.

```ts
const {userId} = useParams();   // <== if there is a `userId` it is of type `string` but might be also not existing/optional
```
In v5 we were using something like:

```ts
const {id, lang} = useParams<{
      id?: string;
      lang?: string;
    }>();
```
