### ISSUE TITLE
"Link" component calls 'to' function without clicks

### ISSUE THREAD

**Issue by NeurosurgeonXX** [ReactTraining/react-router#7682]
## Version

5.2.0

## Test Case

https://codesandbox.io/s/react-router-forked-l8ul3

## Steps to reproduce

run the above test case code modified from the example code. 

I just modified the 

`to="/about”` 

to 

`to={(location) => {
                console.log(1)
                return { ...location, pathname: '/about' }
 }}`

## Expected Behavior

print 1 once only after each click of "about".

## Actual Behavior

print 1 once after each click of any other Links
and print 1 twice after each click of Link "about"

**Comment by timdorr** [comment]
This is expected. `Link` renders an `<a>` and needs to determine the `href` attribute. The `to` function is called on every render.
