### ISSUE TITLE
Installation with Yarn

### ISSUE THREAD

**Issue by mansodelvalle** [ReactTraining/react-router#7683]
I was having a problem installing with Yarn. And I also found people going through the same problem as me. When I installed with this command bugged my entire application web.
`yarn add history react-router-dom @ next`
The solution was to add babel-types as well, i hope i can help some people.
`yarn add history babel-types react-router-dom@next`

**Comment by timdorr** [comment]
You have extra spaces around the @ symbol for the dist tag: `yarn add history react-router-dom@next`

**Comment by mansodelvalle** [comment]
That was a typo. But the problem remains. Please do not close this issue.
