### ISSUE TITLE
Suggestion: URL Converters

### ISSUE THREAD

**Issue by AlexFrazer** [ReactTraining/react-router#7685]
I haven't seen this on the road map but I have seen it in other routing solutions so would like to propose it

Here's the idea: I have a route that will have a url parameter that will match a certain _type_. I want to check that the url matches that type and convert it when it is received in the view layer. Imagine these cases:

```tsx
<Route path="/map/:latitude/:longitude">
  <Map />
</Route>
```

In this case, `latitude` and `longitude` should likely be interpreted as a `float` type, because when you receive it in your component, you will have to inevitably do some overhead to make it useable. Maybe even adding an "intermediate" component to handle it

```tsx
function Map() {
  const { latitude, longitude } = useParams();
  const fixedLatitude = parseFloat(latitude, 10);
  const fixedLongitude = parseFloat(longitude, 10);
  if (Number.isNaN(fixedLongitude) || Number.isNaN(fixedLatitude)) {
    // render something else
  }
  return <MapWithActualData latitude={fixedLatitude} longitude={fixedLongitude} />
}
```

Same could be done with higher order components or something like that. It is kind of a pain to do this kind of work.

In the framework flask,  they have a concept of a [url converter](https://flask.palletsprojects.com/en/1.1.x/api/#url-route-registrations), making it easier to handle

```python
@app.route('/map/<float:latitude>/<float:longitude>')
def map(latitude, longitude):
  pass
```

I think something like this could be useful in react router with a slightly different API. Say in the example above:

```tsx
<Route
  path="/map/:latitude/:longitude"
  converters={{
    latitude: FloatConverter,
    longitude: FloatConverter,
  }}
>
```

This would do two things:
1. not match the route unless longitude and latitude are valid `float` types (i.e., passes the float converter appropriately)
2. send the values in as the specified type, in this case, it would convert it from the native `String` to a `Number`

Thoughts?

**Comment by timdorr** [comment]
This kind of thing has been suggested before. It's not not something we're going to add, mainly because it makes the TypeScript types essentially lie and it's fairly complex to implement. 

You can get the same thing from your code in userland with `parseInt` or whatever you need at the callsite for useParams (or the route props).
