### ISSUE TITLE
[v6] Add support for Route Groups

### ISSUE THREAD

**Issue by Robert-Fish** [ReactTraining/react-router#7686]
I believe having groups for route which are related e.g 
/products
/product/:productID
/product:productID/delete

This would help with organising your list of routes and is already a common pattern in backend frameworks such as [laravel]("https://laravel.com/docs/8.x/routing#route-groups"). The usage would someone akin to this:

     import { Route, Switch, RouteGroup} from 'react-router-dom';
	 <RouteGroup routePrefix="/products">
	  <Route route="/">
		<ProductList />
	  <Route>
	  <Route route="product/:productID">
		<ProductDetail />
	  <Route>
	  <Route route="/:productID/delete">
		<ProductDelete />
	  <Route>
	 </RouteGroup>

Based on the routePrefix, the route children would have that prefix added to the url so the /product/:productID would become /products/product/:productID

**Comment by timdorr** [comment]
You can already do this with nested routes in v6: https://github.com/ReactTraining/react-router/blob/v6.0.0-beta.0/docs/installation/getting-started.md#nested-routes
