### ISSUE TITLE
useParams typings

### ISSUE THREAD

**Issue by artola** [ReactTraining/react-router#7687]
## Version

6.0.0-beta.0

## Steps to reproduce

I find that the typing for return of `useParams` that is `Record<string, string>` are wrong. The `useParams` can not warranty other than if a param exists it is `string` otherwise it must be `undefined`.

```ts
const {id, lang} = useParams();   // <== if there is a `id` it is of type `string` but might be also not existing/optional
```

In v5 we were using something like:

```ts
const {id, lang} = useParams<{
      id?: string;
      lang?: string;
    }>();
```

## Expected Behavior

```ts
export type Params = Record<string, string | undefined>;
```

https://github.com/ReactTraining/react-router/blob/262b45dd8d6cbdc3a984259c5591ffc3de80d600/packages/react-router/index.tsx#L722

## Actual Behavior

The actual typings does not consider the possibility of optional params.

**Comment by timdorr** [comment]
v6 doesn't have optional params, so that wouldn't make sense.

**Comment by artola** [comment]
> v6 doesn't have optional params, so that wouldn't make sense.

@timdorr See what happen when we have "optional" params (like it was possible on v5). We can render the same component but we can receive a different number of params.

```js
import React from "react";
import { HashRouter, Routes, Route, Link, useParams } from "react-router-dom";

const Home = () => <div>Home</div>;

const User = () => {
  const { id, lang } = useParams();

  return (
    <div>
      User: {id} - {lang}
    </div>
  );
};

export default function App() {
  return (
    <>
      <HashRouter>
        <div>
          <Link to="/">Home</Link>
          {"  -  "}
          <Link to="user/123">User: 123</Link>
          {"  -  "}
          <Link to="user/123/en">User: 123 - en</Link>
        </div>
        <Routes>
          <Route path="/" element={<Home />} />
          <Route path="user">
            <Route path=":id" element={<User />} />
            <Route path=":id/:lang" element={<User />} />
          </Route>
        </Routes>
      </HashRouter>
    </>
  );
}
```

**Comment by timdorr** [comment]
Yes, but in that case the _value_ of the Record isn't `undefined`, the _index_ is. So, the types are still incorrect in that case. 

Regardless, we don't know enough about your routes in the type system to make any determination like that.

**Comment by artola** [comment]
If the typings are more "friendly" as it was before, we could change it as needed as still be 100% compat with the actual code, this change allows to pass our typings else defaults to the actual `Params`.

```ts
export function useParams<T = Params>(): T {
  return React.useContext(RouteContext).params;
}
```

See: https://github.com/ReactTraining/react-router/blob/262b45dd8d6cbdc3a984259c5591ffc3de80d600/packages/react-router/index.tsx#L542

**Comment by timdorr** [comment]
You would also need to assert the return from that function `as` the type generic. So, there's little difference between this:
```ts
const { id, lang } = useParams() as MyParams
```
and this:
```ts
const { id, lang } = useParams<MyParams>()
```
You can already do this now, no changes needed.

**Comment by artola** [comment]
I would really prefer the version that we were use to have until v5:

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/900dc05ac8fa0fbe850f1cac7656585c1e454800/types/react-router/index.d.ts#L164

I appreciate v6 effort, pretty nice code, but it also includes some breaking changes (e.g., no more optional params, any hack like duplicated routes is not the same) or these typings.

**Comment by tannera** [comment]
You can manually override the types of a 3rd party library if they don't fit your need:

```ts
// in some custom-types.ts file in your project
import 'react-router';

declare module 'react-router' {
    export function useParams<
        Params extends { [K in keyof Params]?: string } = Record<string, string>
    >(): Params;
}
```

**Comment by artola** [comment]
@tannera Your hint is right, anyway you will end up doing it in many projects, this is the reason why I find that v5 typings where a bit better than v6 on this point, allowing to use the generic type without a workaround.
