### ISSUE TITLE
[V6]  remounting the same component on nested routes change

### ISSUE THREAD

**Issue by bshimrit** [ReactTraining/react-router#7688]
## Version

**^6.0.0-beta.0**

## Test Case

https://codesandbox.io/s/re-mounting-on-same-component-m30yo

## Steps to reproduce
go to sandbox change url to "https://m30yo.csb.app/app"
AppContainer has nested routes that should render the same component
when you land on /app  the ChildView component is navigating to a different route "app/child" with same component

## Expected Behavior
ChildView component will not remount
the same nested routes config didn't remount in react-router 3

## Actual Behavior
ChildView component remounts

**Comment by timdorr** [comment]
This is just how React works. If you render the same tree of components, it will reuse the instances of the components for each render. There is no way around this. You should build a component that responds to hook or prop value changes.

**Comment by bshimrit** [comment]
@timdorr thanks for the quick reply. to anyone facing same issue the solution for me was to avoid the tree and put all routes on same level, thus avoiding remounting on same components.For the example above:

```
   <BrowserRouter>
      <Routes>
        <Route path="/app" element={<AppContainer />}>
          <Route element={<ChildView shouldNavigate={true} />} />
          {/* other routes... */}
          <Route path="/child" element={<ChildView />} />
           {/* other '/child' routes (not nested) */}
        </Route>
      </Routes>
    </BrowserRouter>
```

**Comment by Tonysmark** [comment]
This is so annoying, just simply don't use `react-router-config` instead using original `react-router-dom` will solve this problem
