### ISSUE TITLE
Inconsistent use of `func` and `function` in docs

### ISSUE THREAD

**Issue by srianbury** [ReactTraining/react-router#7689]
(First time contributor)
`function` is used as the type in the [Link docs](https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/docs/api/Link.md), but elsewhere `func` is used.
## Version

N/A

## Test Case

N/A

## Steps to reproduce
N/A
## Expected Behavior
`## to: func`
`## innerRef: func`
## Actual Behavior
`## to: function`
`## innerRef: function`

**Comment by timdorr** [comment]
Can you submit a PR to fix this instead?
