### ISSUE TITLE
React 17 support

### ISSUE THREAD

**Issue by Thibaut-Fatus** [ReactTraining/react-router#7695]
## Version
- react-router-dom@5.2.0
- react-router@5.2.0
- react@17.0.1
- react-scripts@4.0.0

## Test Case

https://codesandbox.io/s/react-router-forked-zeizl?file=/index.js
which does actually work, but the exact same example does not locally

## Steps to reproduce

- `yarn install` these packages
- try to use any hooks from react-router-dom (for instance `useParams`)

you'll get an error `Invalid hook call`

because `react@16.14` is resolved and installed in `node_modules/react-router-dom/node_modules` instead of using the root `react@17.0.1`

- deleting the directory `node_modules/react-router-dom/node_modules/react`

or

- adding an `alias` key in react-script `webpack.config` like so `react: path.resolve('node_modules/react'),`

solves the issue

## Expected Behavior

react-router-dom has 
```
  "peerDependencies": {
    "react": ">=15"
  },
```
which should allow `react@17.0.1` resolution ?

## Actual Behavior

We should be able to use `react-router-dom` hook `useParams` without having invalid hook call with react 17

**Comment by Thibaut-Fatus** [comment]
requesting `react@16.xx` in the host `package.json` fixes the issue since react-router does not install a duplicate version then, but would be nice to be able to use react 17

**Comment by timdorr** [comment]
Yeah, there's nothing preventing you from installing React 17 and using that. I've got it in place in our production app right now and it works A-OK. 

Something is wrong with your installation tooling if it's resolving a different version of React. Router shouldn't have it's own React module under any version of React, as many of the internal instances React uses are going to mismatch and cause issues.

**Comment by mateja176** [comment]
> Yeah, there's nothing preventing you from installing React 17 and using that. I've got it in place in our production app right now and it works A-OK.
> 
> Something is wrong with your installation tooling if it's resolving a different version of React. Router shouldn't have it's own React module under any version of React, as many of the internal instances React uses are going to mismatch and cause issues.

I've encountered the same problem while using `yarn` and it may very well be an issue with yarn since react-router specifies
```json
  "peerDependencies": {
    "react": ">=15"
  },
```
Which does not exclude v17.

**Comment by alippai** [comment]
It works, but duplicate "react-is" module versions are loaded and bundled, both v16 and v17 (correctly as this is what the react-router specifies in it's package.json). I don't see how the current package.json would allow react v17 (this is true for both v5 and v6)

**Comment by bezsinnyidmytro** [comment]
does it have any solution to leave host app with react v17 and not have 2 versions of react in the bundle?
I still see that both 16 and 17 is added to package-lock
