### ISSUE TITLE
Url-params. Code don't behave as Documentation says

### ISSUE THREAD

**Issue by sselvaggi** [ReactTraining/react-router#7696]
## Version

5.2.0

## Test Case
https://reactrouter.com/web/example/url-params

## Steps to reproduce
Go to https://reactrouter.com/web/example/url-params
Copy the code
Paste it in your App.tsx

## Expected Behavior
It should use /:id param to be shown in the screen
According with documentation
useParams() returns an object with id attribute

Documentation says it must be used in this way:
 let { id } = useParams();

## Actual Behavior
useParams() returns the id itself

It can be used in this way:
 let id = useParams();

Property 'id' does not exist on type '{}'.  TS2339

    47 |   // We can use the `useParams` hook here to access
    48 |   // the dynamic pieces of the URL.
  > 49 |   let { id } = useParams();

**Comment by timdorr** [comment]
We don't maintain the types for 5.x. However, for this and upcoming versions, you can assert a type to get around this:

```ts
let { id } = useParams() as MyParams;
```
