### ISSUE TITLE
[v6] Non-immediate nested Routes

### ISSUE THREAD

**Issue by Mangatt** [ReactTraining/react-router#7697]
Since v6 is working out of the box with nested routes, it would be definitely helpful to support event non-immediate nested routes like this:

```js
<Routes>
	<div>
		<Route path="dashboard" element={<div>Dashboard</div>} />
		<Route path="contact" element={<div>Contact</div>} />
	</div>
</Routes>
```

This is important mainly when sub-routes are generated dynamically and it's not possible to ensure that `Route` will be at to of the structure, not wrapped by any other element.

**Comment by Mangatt** [comment]
It might be event useful to have separate `RoutesContext` component for that.

**Comment by MeiKatz** [comment]
In your case: why don't you put the `<Routes />` component inside the divs?

**Comment by Mangatt** [comment]
@MeiKatz That's just an example, because sometimes it is not possible.

**Comment by MeiKatz** [comment]
@Mangatt can you give an example?

**Comment by Mangatt** [comment]
In our case, it is `NestedSortable` component, which by it's nature does not allow that. But there are others, especially anything that is using `React.Children` to provide functionality (much like React Router does).

**Comment by MeiKatz** [comment]
Okay, can you give some example code? I don't get what you try to say (sorry for that).

**Comment by Mangatt** [comment]
Assume pseudo-structure like this:

```jsx
<Routes>
	<ul>
		<li>
			<Route path="dashboard" element={<div>Dashboard</div>} />
		</li>
		<li>
			<Route
				path="contact"
				element={
					<ul>
						Contact
						<li>
							<Route path="dashboard" element={<div>Sub-contact</div>} />
						</li>
					</ul>
				}
			/>
		</li>
	</ul>
</Routes>
```

**Comment by MeiKatz** [comment]
I get what you want. Not sure how hard it would be to traverse the virtual tree and find the route components.

**Comment by timdorr** [comment]
You should isolate your layout in a separate component, as shown in the second example here: https://github.com/ReactTraining/react-router/blob/v6.0.0-beta.0/docs/installation/getting-started.md#nested-routes

As for mixing other element types in the children of Routes, that's not something we're going to do. Routes is meant to behave like Switch, returning whatever valid tree path of children match for the current location. Adding other elements makes this much more complex.

You should instead use multiple Routes throughout your tree where you need matching.

**Comment by Styn** [comment]
Just as a reference for anybody else running into this.
I thought this meant it was also not possible to get nested routes from a separate component.
For example this doesn't work:
```
export function External (props: Props) {
  return (
    <>
      External component
      <Outlet />
    </>
  );

export const ExternalRoutes = () => {
  return (
    <>
        <Route path={`one`} element={<p>one</p>} />
        <Route path={`two`} element={<p>two</p>} />
    </>
  );
};

 <Routes>
  <Route path='external' element={<External />} >
    <ExternalRoutes />
  </Route>
</Routes>
```

Since this will render both the `one` and `two` elements, because in the virtual dom there is an `<ExternalRoutes>` element in the tree.
This can be fixed by doing this:
```
 <Routes>
  <Route path='external' element={<External />} >
    {ExternalRoutes()}
  </Route>
</Routes>
```
So there is no intermediary react element  in the virtual dom.
