### ISSUE TITLE
Module not found: Can't resolve 'react-router-native' in 'C:\Users\anonymous\Desktop\app'

### ISSUE THREAD

**Issue by adamelmohamad** [ReactTraining/react-router#7700]
I have been trying to resolve this the whole day. I am using latest version of react-router-native. For some reason it is not working. I tried npm install react-router-native, removed, then re-installed. nothing works.

**Comment by timdorr** [comment]
This doesn't have anything to do with React Router. Check with the support resources for your build tooling.
