### ISSUE TITLE
[v6] HashRouter 'hashType' prop is no longer supported

### ISSUE THREAD

**Issue by tannera** [ReactTraining/react-router#7703]
## Version

6.0.0-beta.0

## Test Case

Example working with Version 5.2: https://codesandbox.io/s/brave-bouman-xye62?file=/src/App.js
Example with 6.0 beta.0: https://codesandbox.io/s/friendly-wood-5tj4f?file=/src/App.js

## Steps to reproduce

Using `<HashRouter/>` with the `hashType="noslash"` prop does not work in v6, only the default slash behaviour is supported in v6.

```
  <HashRouter hashType="noslash">
    <Routes basename="test">
      <Route path="/">
        <Home />
      </Route>
    </Routes>
  </HashRouter>
```

## Expected Behavior

hashType prop would be supported just like in version 5.1 as described in https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/docs/api/HashRouter.md#hashtype-string

There are no notices about hashType being deprecated anywhere. 

## Actual Behavior

<HashRouter/> always behaves as with `<HashRouter hashType="slash"/>` which was the default behaviour.

**Comment by timdorr** [comment]
Router v6 is based on History v5, which removes `hashType`. If you want it back, you would need to ask over there first: https://github.com/ReactTraining/history/ However, be warned that it was specifically removed in v5, so it's not likely to return.

**Comment by thejohnhoffer** [comment]
This is a request to reconsider this issue. The old [v5 API of `HashRouter`](https://v5.reactrouter.com/web/api/HashRouter) allows hashes to begin as `#` rather than `#/`. A UI I'm migrating to React has a requirement that the hash be of the form `#a=x#b=y#c=z`, so I restored the v5 API behavior for a component constructed with: 

```
<HashRouter hashType="noslash"/>
```

I've opened a PR (#8450) that allows `hashType="noslash"`, and I'm happy to improve or clean up the solution to meet the contributors' standards for inclusion in a minor version release.

**Comment by fnick851** [comment]
@thejohnhoffer I'm using ` "react-router-dom": "^6.2.1"` and this features is not available. I guess it hasn't made its way into react-router yet?

**Comment by thejohnhoffer** [comment]
> @thejohnhoffer I'm using ` "react-router-dom": "^6.2.1"` and this feature is not available. I guess it hasn't made its way into react-router yet?
> 
> UPDATE: I see it is available via your package - life saver, thanks!

I'm happy you're using it @fnick851. Please [let me know](https://github.com/thejohnhoffer/use-hash-history/issues/new) of any issues you're facing.

For anyone else, [here is the template you should use for now.](https://github.com/thejohnhoffer/test-history-router#history-router-test-template).

You should use `use-hash-history` and `react-router-dom@6.1.1`. I haven't yet tested with `react-router-dom@6.2.1`.

**Comment by chazlm** [comment]
is this workaround still required for react-router-dom@6.5.0?

**Comment by chazlm** [comment]
@thejohnhoffer I'm looking to use use-hash-history but implementation isn't clear, are you able to assist?
