### ISSUE TITLE
Route with "render" attribute doesn't reload route component on create-react-app Fast Refresh feature

### ISSUE THREAD

**Issue by aurimasniekis** [ReactTraining/react-router#7705]
I am not sure if this is related to `react-router` or `create-react-app` itself as it provides the Fast Refresh feature but when using a specific attribute `render` on route component it breaks its functionality. I am not sure about the internal difference of using render attribute instead of the inner content of the route tag.

## Version

```"react-router-dom": "^5.2.0"```

## Test Case

None

## Steps to reproduce

```
npx create-react-app my-app --template router
```

Replace the route in App.js

```jsx
<Route path="/about" render={About}>
    <About />
</Route>
```

with 

```jsx
<Route path="/about" render={About}/>
```

## Expected Behavior

Changing content in `About.js` the website would reload with new changes

## Actual Behavior

The content doesn't change, but the fast reload does its job and fetches updated Javascript as it should.

**Comment by timdorr** [comment]
Is that in the base template? That is invalid, as you should only have children _or_ render props, not both.

**Comment by aurimasniekis** [comment]
I am not sure what you mean about the base template, but I have just reproduced the same issue with a common starter template that I have in my application.

P.S. I am not using both children & render props. I always used only render prop, but it doesn't work with refresh anymore.

**Comment by timdorr** [comment]
Well, we're not doing anything abnormal with React that would break Fast Refresh explicitly. I would consult the Fast Refresh support resources to see if there's a workaround or similar bug being tracked.
