### ISSUE TITLE
Error message should be clear when useRouter is used without the context of <BrowserRouter>

### ISSUE THREAD

**Issue by DevTGhosh** [ReactTraining/react-router#7706]
## Version

 `"react-router-dom": "^6.0.0-beta.0"`

## Test Case

https://codesandbox.io/s/react-router-forked-34uui?file=/index.js

## Steps to reproduce

Use `useRoutes()` without using it in context of `<BrowserRouter />

## Expected Behavior

Should return: `useRoutes()` may be used only in the context of a `<BrowserRouter>` component. 
Maybe also suggest to wrap the component or it's parent components where `useRoutes()` is used with `<BrowserRouter>` to be more clear. 

## Actual Behavior
`useRoutes()` may be used only in the context of a `<Router>` component.

**Comment by MeiKatz** [comment]
That's not a bug. `<BrowserRouter>` is just a wrapper around `<Router>` – but in the most cases you will not see it.

**Comment by DevTGhosh** [comment]
Is just passing `<Router><App></Router>` to the parent component from `import { Router } from 'react-router-dom'` supposed to work? 
https://codesandbox.io/s/react-router-forked-34uui?file=/index.js

If not maybe a link to the relevant doc explaining how `<Router>` works then, because if someone is not familiar with how `<Router>` the error doesn't give them the right direction to solve the error on their own.

**Comment by MeiKatz** [comment]
You have to pass `history` as a prop.

**Comment by DevTGhosh** [comment]
Ah got it, still the error should reflect that right?

**Comment by MeiKatz** [comment]
Might be, but I think it's just some kind of neatness to do so. Also it would need some kind of overhead, because we need to pass via the context which kind of wrapper we used. Maybe with an additional context. It is possible but I don't think that we could justify the afford.

**Comment by timdorr** [comment]
If you're not wrapping in a Router of any type, we have no way of knowing which one you intended to use. Code can't read minds (yet). 

Regardless, this wording is specific as to not imply it only works with a specific Router type. It should be left as-is.

**Comment by DevTGhosh** [comment]
Fair enough I will update the issue so other people can find it more easily. 

Solution:

You will need to wrap the component or the parent component where `useRoutes()` is being used with a  low level `<Router>` component with a `history` prop or more likely you will want to use the built-in routers mentioned [here ](https://github.com/ReactTraining/react-router/blob/dev/docs/api-reference.md#setup) according to your setup. 

Ex: https://codesandbox.io/s/react-router-forked-nqirf

**Comment by knuxbbs** [comment]
> 
> Solution:
> 
> You will need to wrap the component or the parent component where `useRoutes()` is being used with a low level `<Router>` component with a `history` prop or more likely you will want to use the built-in routers mentioned [here ](https://github.com/ReactTraining/react-router/blob/dev/docs/api-reference.md#setup) according to your setup.

@DevTGhosh where is the sample with generic router? As pointed [here](https://github.com/ReactTraining/react-router/issues/7541), this looks like a unsolved bug.
