### ISSUE TITLE
[v6] `matchPath` does not match partial pathnames

### ISSUE THREAD

**Issue by JeffBaumgardt** [ReactTraining/react-router#7710]
## Version

**6.0.0-beta.0**

## Test Case

With a pathname of `/foo/bar/123/baz` I want to match `/baz` portion of the path. 

## Steps to reproduce

```js
const pathname = '/foo/bar/123/baz'
const match = matchPath('/baz', pathname) // -> null
const match2 = matchPath('*/baz', pathname) // -> null
```

##
The problem is with the `compilePath` function regular expression. 

Two options:
1) Remove the starting `^`. Probably not the best idea as it can break many others
2) Add a `if (path.startsWith('*') {}` - Add a `(.*)` before the match after the `^`

```js
let source = '^(';

if (path.startsWith('*') {
  source += '(.*)'
}

source +=  path
  .replace(/^\/*/, '/') // Make sure it has a leading /
  .replace(/\/?\*?$/, '') // Ignore trailing / and /*, we'll handle it below
  .replace(/[\\.*+^$?{}|()[\]]/g, '\\$&') // Escape special regex chars
  .replace(/:(\w+)/g, (_: string, key: string) => {
    keys.push(key);
    return '([^\\/]+)';
  }) +
')';

if (path.endsWith('*')) {
  if (path.endsWith('/*')) {
    source += '\\/?'; // Don't include the / in params['*']
  }
  keys.push('*');
  source += '(.*)';
} else if (end) {
  source += '\\/?';
}

  if (end) source += '$';
```

Then you can use a pattern that starts with `*/baz` and will match `/foo/bar/123/baz`

I'm happy to submit a PR to add this but I wanted your feedback first.

**Comment by timdorr** [comment]
That's not the function of `matchPath` in the context of routing. We only want to match either the exact path ("Are we _at_ this path?") or the prefix ("Are we _within_ this path?"). 

Matching a postfix isn't a feature we want for routing. You always have to have some base to your path, as we can't do anything with a sub-path in isolation. It would just become another base path without any context (which is what happens at the root of the tree).
