### ISSUE TITLE
issues with the router not being found on context when npm install -g is used

### ISSUE THREAD

**Issue by dgoldstein0** [ReactTraining/react-router#7715]
## Version

5.2.0

## Test Case

```
import React from 'react';
import {configure, mount} from 'enzyme';
import React16Adapter from 'enzyme-adapter-react-16';
import {MemoryRouter} from 'react-router';
import {Link} from 'react-router-dom';

configure({adapter: new React16Adapter()});

describe('Legal hold individual view members list', () => {
  it('does nothing', () => {
    const anything = mount(
      <MemoryRouter>
        <Link to="/foo" />
      </MemoryRouter>
    );
    expect(1).toEqual(1);
  });
});
```

## Steps to reproduce

npm install -g react-router@5.2.0
npm install -g react-router-dom@5.2.0
npm install enzyme enzyme-adapter-react-16

run the test case, e.g. with jest

## Expected Behavior

the test does nearly nothing so it should pass

## Actual Behavior

mounting the component will fail with an error inside Link saying there's no Router on context.

The reason for this is because using `npm install -g` results in react-router-dom getting it's own private copy of react-router.  Thus `Link` tries to read the react context from react-router-dom's react-router, whereas `MemoryRouter` puts the router in context using it's copy of react-router.  Since the React context api depends on object identity being preserved, having the duplication of react-router means we read and write different entries in the context.

One way to fix the test is to import MemoryRouter from react-router-dom, as it is reexported; then both it and Link would use react-router-dom's private copy of react-router and everything would be fine.  But that doesn't solve the footgun here: the primary problem is that mixing direct deps on react-router and react-router-dom is fundamentally unsafe, but a lot of code does it today since (1) using npm install with -g is uncommon, and (2) lots of example code do this so people don't think twice about it.

If instead, react-router-dom to take a peer dep on react-router, then npm installation can help us enforce that there is only one version of react-router to be found and we don't end up with issues with React's context api.  Such a peer dep could still pin the exact version of react-router, even if this isn't common practice for peer deps.  (The alternative seems to be that all sample code using react-router and react-router-dom, should be fixed to only directly use react-router-dom; I'm not sure if that's preferable)

**Comment by timdorr** [comment]
react-router and react-router-dom aren't globally installable packages. They have no executables, so that doesn't make sense for them. Install them locally for the packages/projects you intend to use them on.

**Comment by dgoldstein0** [comment]
well my actual problem is I've built bazel integration with node that ends up with a layout of node_modules much like `npm install -g` results in - in that we end up with multiple copies of react-router in the exact same fashion, and so have the same problem.

That said I've never heard of a package not being "globally installable".  I agree it might not make sense most of the time - in that you really want to pin the right version for each project.  But if this was supposed to be a property of packages, wouldn't there be some way to label a package so that npm install -g on it would fail?
