### ISSUE TITLE
Redirect feature no longer supported...

### ISSUE THREAD

**Issue by ThomasBurleson** [ReactTraining/react-router#7716]
With RRv6 the `<Redirect .../>` component is no longer available. 
The Beta docs indirectly discuss this in the *Not Found Routes* section:

```jsx
function App() {
  return (
    <Routes>
      <Route path="/" element={<Home />} />
      <Route path="dashboard" element={<Dashboard />} />
      <Route path="*" element={<NotFound />} />
    </Routes>
  );
}
``` 

Issues:  
* The associated text should clearly provide textual content regarding "deprecated Redirect component"... so searches are easy. 
* This solution will use the fallback element but **does NOT** update the url... so invalid urls could be bookmarked. 

Consider the above following routes:

```jsx
function App() {
  return (
    <Routes>
      <Route path="/" element={<Home />} />
      <Route path="dashboard" element={<Dashboard />} />
      <Route path="*" element={<Dashboard />} />
    </Routes>
  );
}
``` 

* Url `/dashboard` will show the dashboard. Cool!
* Url `/portal` will show the dashboard. Ok, but the Url is still invalid.

With Redirect support, a `/portal` url would both redirect to `/dashboard` url and use the Dashboard component.
How do we update the Url value to reflect the correct path ?

**Comment by timdorr** [comment]
There is a `<Navigate />` component to replace it. It does much the same thing, but doesn't work the same with `<Routes>` as `<Redirect>` did with `<Switch>`.

**Comment by ThomasBurleson** [comment]
@timdorr - Your feedback about `<Navigate />` is exactly my point and BUG report. From the `<Routes>`, I can fallback to default view... but I cannot update the URL. Does that not seem like a bug ?

**Comment by mjackson** [comment]
@ThomasBurleson You could always just put a `<Navigate>` in your `<Route element>` if you really want to put it in your route config:

```js
import { Routes, Route, Navigate } from 'react-router-dom';

function App() {
  return (
    <Routes>
      <Route path="/" element={<Home />} />
      <Route path="dashboard" element={<Dashboard />} />
      <Route path="*" element={<Navigate to="/dashboard" />} />
    </Routes>
  );
}
```

**Comment by emilio-martinez** [comment]
> if you really want to put it in your route config

@mjackson do you mean to say there's an alternative recommend approach/pattern to do this outside of the route config?
