### ISSUE TITLE
useLocation returning incorrect object

### ISSUE THREAD

**Issue by timothyarmes** [ReactTraining/react-router#7717]
## Version

    "react-router-dom": "^5.2.0",
    "history": "^5.0.0",

## The problem

I've struggling with a really strange problem.  My top level render tree looks like this:

```
import { Switch, Route, Router, Redirect, useHistory, useLocation } from 'react-router-dom';
import { createBrowserHistory } from 'history';

...

const history = createBrowserHistory();

...

And eventually I hydrate with...

  const ClientApp = () => (
      <Router history={history}>
        <ApolloProvider client={apolloClient}>
          <ThemeProvider theme={theme}>
            <ThemeProvider theme={{ props: { MuiUseMediaQuery: { ssrMatchMedia } } }}>
              <UserProvider render={
                ({ me: curUser, loading: loadingCurUser, refetch: refetchSelf }) => {
                  const history = useHistory();
                  const location = useLocation();
                  console.log(history, location);
                  return (
                      <Switch>
                        <! -- Snipped Routes ->
                        ...

                        <Route render={({ location }) => <Redirect to={`/${defaultLocale}${location.pathname}`} />} />
                      </Switch>
                  );
                }
              }
              />
            </ThemeProvider>
          </ThemeProvider>
        </ApolloProvider>
      </Router>
  );
```

Before I continue, I'd like to state that if I use `<BrowserRouter>` instead of `<Router history={history}>` then everything works perfectly.  The problem I'm about to describe **only** happens when using `Router` with my history object, which appears to me to be exactly what `<BrowserRouter>` is doing under the hood anyway...

The problem that I initially observed when when moving from  `<BrowserRouter>` to `<Router history={history}>` was that none of my Routes matched (except for `/`), and I fell to the last route (seen code above) which tried to redirect to `/enundefined`, which implied that `location.pathname` is undefined.  Very strange.

Hence I ended up adding the `useLocation` hook above to examine the context's `location` object.

Now, if I render the home page my debug prints the expected result:

```
Object {pathname: "/", search: "", hash: "", state: null, key: "default"}
```

However, if I click on any link at all then  the location object returned by `useLocation` looks like this:

```
{action: "PUSH", location: {…}}
```

Which explains why `location.pathname` is undefined, and why my code breaks.

This object looks like a subset of the `history` object, rather than the `location` object itself.  Here are a series of screenshots of the console as I click on a link (in each case, history on left, location on right):

1) I start with `/`, everything looks good:

![image](https://user-images.githubusercontent.com/1092550/101611337-ac9cb580-3a09-11eb-89ec-37095f293cf1.png)

2) I click a link, and I see this:

![image](https://user-images.githubusercontent.com/1092550/101611460-d524af80-3a09-11eb-9bed-1f1fe3035c24.png)

3) And then immediately after:

![image](https://user-images.githubusercontent.com/1092550/101611541-ed94ca00-3a09-11eb-989f-40f0a3fc6100.png)

I'm at a complete loss.  Examining the source code to BrowserRouter suggest that I'm doing the same thing that it does.

Just of the sake of completeness, if I use `BrowserRouter` and I click on a link:

![image](https://user-images.githubusercontent.com/1092550/101611872-554b1500-3a0a-11eb-84ce-895ee1843a6f.png)

**Comment by timothyarmes** [comment]
OK, so after digging into the React Router code I see that the `history`'s listen function indeed returning { action, location}, which Router isn't expecting.

This made me realise that Router requires version 4.9.0 of history, not version 5.0.0.

**Comment by Lagicrus** [comment]
Thank you so much @timothyarmes !
I was having this exact same issue and this closed issue saved me 🙏 
Finally can fix my issue
