### ISSUE TITLE
useNavigate() in React HOC give this error but should work according to docs

### ISSUE THREAD

**Issue by erikswed** [ReactTraining/react-router#7721]
## Version

    "react-router-dom": "^6.0.0-beta.0",

## Steps to reproduce
Create a react style HOC and try to use the useNavigate()

Here's the code that fails:
[CodeSandbox](https://codesandbox.io/s/apple-basket-with-router-v6-and-withauthorization-forked-wwoby?file=/src/session/WithAuthorization.jsx)
```
/* eslint-disable react/prefer-stateless-function */
import React from 'react';
import { useNavigate } from 'react-router-dom';
import AuthUserContext from './context';

const WithAuthorization = condition => Component => {
	const withAuthorization = props => {
		const navigate = useNavigate();
		const doStuff = event => navigate('/', { replace: true });
		return (
			<AuthUserContext.Consumer>
				{authUser => (condition(authUser) ? <Component {...props} /> : doStuff())}
			</AuthUserContext.Consumer>
		);
	};
	return withAuthorization;
};

export default WithAuthorization;
```
If I move the useNavigate() declaration to outside function like this:

```
const WithAuthorization = condition => Component => {
	const navigate = useNavigate();
	const withAuthorization = props => {
		const doStuff = event => navigate('/', { replace: true });
		return (
			<AuthUserContext.Consumer>
				{authUser => (condition(authUser) ? <Component {...props} /> : doStuff())}
			</AuthUserContext.Consumer>
		);
	};
	return withAuthorization;
};
```
I get another like;

Line 7:19:  React Hook "useNavigate" cannot be called inside a callback. React Hooks must be called in a React function component or a custom React Hook function  react-hooks/rules-of-hooks

## Expected Behavior
Should work as expected 

## Actual Behavior
Getting the error:
Line 8:20:  React Hook "useNavigate" is called in function "withAuthorization" which is neither a React function component or a custom React Hook function  react-hooks/rules-of-hooks

**Comment by timdorr** [comment]
This isn't a React Router issue, you need to read up on how to use hooks. We can't help you with this, unfortunately.

**Comment by erikswed** [comment]
Should mention in the doc's that this limitation exist

**Comment by MeiKatz** [comment]
@erikswed Yeh, but it's not a limitation of RR but of React itself.
