### ISSUE TITLE
Custom hash history with low-level Router doesn't render the routes after clicking the router link.

### ISSUE THREAD

**Issue by evankazadaiev** [ReactTraining/react-router#7729]
For business purposes, I need to use hash history in my project. Previously I used react HashRouter for that purpose (everything worked fine), but now I need a way to work with history object in stores (handle user redirects and so on). Custom hash history + low-level react Router doesn't help. I have searched this question on StackOverflow and other resources and found nothing helpful. 

## Version

"react-router-dom": "5.2.0"

## Test Case

https://codesandbox.io/s/react-router-forked-0ukeq?file=/index.js

Video: https://drive.google.com/file/d/1975EnOWr2qsfw5MsQfX29vyMZiGoje-W/view

## Steps to reproduce
Create a custom hash history file in history.js (createHashHistory), after pass this history object as a prop to the low-level router. Then click on any router link.

## Expected Behavior
Click on the router link should redirect the user to the link's route and render it.

## Actual Behavior
Seems the router doesn't understand what to render in the switch, white screen is displayed instead of rendered route. If I use Redirect component at the end of the Switch block, the Router gets into an infinite loop.

**Comment by pshrmn** [comment]
You are using history v5 with react router v5. Switch to history v4 and it should work as expected.

**Comment by evankazadaiev** [comment]
@pshrmn Thanks a million! That worked.
