### ISSUE TITLE
How to use navigator outside a react component in v6，like axios interceptor ?

### ISSUE THREAD

**Issue by wangming-0215** [ReactTraining/react-router#7730]
![image](https://user-images.githubusercontent.com/21071580/103291781-7a3e1100-4a27-11eb-9f2f-bc7286426b6b.png)

**Comment by pshrmn** [comment]
You would need to create a custom history instance that is used both by your router and this interceptor. I also would recommend not redirecting on 404s and have rendering logic to show the 404 logic on bad pages instead.

**Comment by wangming-0215** [comment]
> You would need to create a custom history instance that is used both by your router and this interceptor. I also would recommend not redirecting on 404s and have rendering logic to show the 404 logic on bad pages instead.

Thx.

**Comment by knuxbbs** [comment]
> 
> 
> You would need to create a custom history instance that is used both by your router and this interceptor. I also would recommend not redirecting on 404s and have rendering logic to show the 404 logic on bad pages instead.

This doesn't looks to work. See #7541 and #7706.
