### ISSUE TITLE
Are there any plans to support history location state clearing?

### ISSUE THREAD

**Issue by zhangdingding** [ReactTraining/react-router#7733]
### Are there any plans to support history location state clearing?

Sometimes we use `history.location.state` to pass "temporary state". When finished using, it should be cleaned up immediately. As far as I know, there is NO API to clear the location state, and the only workaround is:

```javascript
history.replace(currentPath, undefined);
```

I don't want to argue about where the "temporary state" should be kept, that's a different issue. Adding a `history` API to clear `history.location.state` sounds reasonable.

Thanks 🙂

**Comment by timdorr** [comment]
This would be a question for the history library: https://github.com/ReactTraining/history
