### ISSUE TITLE
Can't pass moment.js object to history state

### ISSUE THREAD

**Issue by OfirD1** [ReactTraining/react-router#7747]
## Version

5.2.0

## Test Case

https://codesandbox.io/s/react-router-forked-p4956

## Steps to reproduce
Push a history state whose value is a `moment.js` object (or an object with a `moment.js` property, it doesn't matter).

## Expected Behavior
I expect it to work without issues.

## Actual Behavior
I get an error:

```
Failed to execute 'replaceState' on 'History': function (number) {
    var b = number % 10,
          output = toInt((number...<omitted>... 
} could not be cloned.
```

On other cases (see for example [this SO question](https://stackoverflow.com/questions/63540675/unable-to-use-history-push-with-react-router-to-pass-props-to-state-to-use-withi)), the error is slightly different:

```
Failed to execute 'pushState' on 'History': function (number) {
    var b = number % 10,
          output = toInt((number...<omitted>... 
} could not be cloned.
```

**Comment by pshrmn** [comment]
> The state object can be anything that can be serialized.

https://developer.mozilla.org/en-US/docs/Web/API/History/pushState#parameters

A moment object has function as properties, so it cannot be serialized.
