### ISSUE TITLE
[V5] When using Router with custom History, components stop loading after code edit

### ISSUE THREAD

**Issue by mgpepe** [ReactTraining/react-router#7751]
## Version

```
  "dependencies": {
    "@testing-library/jest-dom": "^5.11.9",
    "@testing-library/react": "^11.2.3",
    "@testing-library/user-event": "^12.6.2",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "react-router": "^5.2.0",
    "react-router-dom": "^5.0.0",
    "react-scripts": "4.0.1",
    "web-vitals": "^0.2.4"
  },
```

## Test Case

`App.js`

```
import {
Router,
  Switch,
  Route,
  Link
} from "react-router-dom";

import { createBrowserHistory } from "history";

const history = createBrowserHistory();

export default function App() {
  // test change file 2 s
  return ( 
    <Router history={history}>
      <div>
        <nav>
          <ul>
            <li>
              <Link to="/">Home</Link>
            </li>
            <li>
              <Link to="/about">About</Link>
            </li>
            <li>
              <Link to="/users">Users</Link>
            </li>
          </ul>
        </nav>

        {/* A <Switch> looks through its children <Route>s and
            renders the first one that matches the current URL. */}
        <Switch>
          <Route path="/about">
            <About />
          </Route>
          <Route path="/users">
            <Users />
          </Route>
          <Route path="/">
            <Home />
          </Route>
        </Switch>
      </div>
    </Router>
  );
}

function Home() {
  return <h2>Home</h2>;
}

function About() {
  return <h2>About</h2>;
}

function Users() {
  return <h2>Users</h2>;
}

```

## Steps to reproduce
1. make new installation of react.js
2. install react-router-dom
3. setup the minimal version for router with custom history
4. npm start
5. click to test linking [works]
6. go back to code and add a comment somewhere and save file
7. go back to test linking [doesn't work]
8. if you go and refresh the browser, it starts working again

## Expected Behavior
after editing the file, you can click between pages and browse different components

## Actual Behavior
after editing the file, when clicking, the url in the browser changes, but the components don't load and the page is empty.

**Comment by timdorr** [comment]
You aren't specifying, but make sure you're using a 4.x version of history. The latest 5.x versions aren't not compatible.

**Comment by mgpepe** [comment]
History is `"version": "4.10.1",`, whatever was installed as a depenedency of the React Router

**Comment by mgpepe** [comment]
I am sorry, maybe I am new around here but why was the issue closed without further discussion?

**Comment by timdorr** [comment]
This isn't a support system, it's a bug tracker.  If your code isn't hot reloading, that doesn't have anything to do with React Router. That is a tooling issue. You should consult the appropriate support resources for whatever tools you are using that do hot reloading.
