### ISSUE TITLE
[v6] Navigate on first/initial render not working

### ISSUE THREAD

**Issue by Blackglade** [ReactTraining/react-router#7753]
The short version is, I am adding authentication to my SPA and am trying to redirect the user on first/initial render if they are not logged in. 

The following doesn't work:

```jsx
export default function Dashboard(){

	const navigate = useNavigate();
	
	if(true){
		navigate('/login')
	}

	return (
		// ...some html
	)
}
```

But this does:

```jsx
export default function Dashboard(){

	return (
		// ...some html
		{true && <Navigate to="/login"/>
	)
}
```

Not sure if this is a bug or intended behavior (if it is intended, I couldn't find anything in the docs/error message about this). Is using the Navigate tag my only option or can I use useNavigate here?

## Version

6.0.0-beta.0

**Comment by timdorr** [comment]
Navigate calls need to be inside a useEffect, as they are an effect. More importantly, this will help avoid routing loops caused by re-rendering the same component.
