### ISSUE TITLE
Issue when trying to extend the Link class in react-router-native

### ISSUE THREAD

**Issue by Ak10990** [ReactTraining/react-router#7755]
Here is the detailed log: 

Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check your code at App.js:26.
    in Route (at App.js:20)
    in RCTView (at View.js:34)
    in View (at App.js:18)
    in Router (created by MemoryRouter)
    in MemoryRouter (at NativeRouter.js:11)
    in NativeRouter (at App.js:17)
    in App (at renderApplication.js:45)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:106)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:132)
    in AppContainer (at renderApplication.js:39)

Here is the Link class which is extended:
import React from 'react';
import {Link} from 'react-router-native';

 export default class Link1 extends Link {
 }

Can someone please suggest what went wrong here

**Comment by MeiKatz** [comment]
Just don't do it. Use composition instead.

**Comment by Ak10990** [comment]
> Just don't do it. Use composition instead.

I don't think composition will resolve my problem because I have to use this Link at multiple places.
Any ideas on the above error.

**Comment by MeiKatz** [comment]
Yeah, I don't think you got the concept of composition right: create a new wrapping component that uses Link internally and then use the wrapping component everywhere you need it.
