### ISSUE TITLE
Testing custom hooks which rely on useSearchParams on v6

### ISSUE THREAD

**Issue by benskz** [ReactTraining/react-router#7759]
I'm trying to test a custom hook which changes the search params and relies on `useSearchParams` to do this. However, when in the testing environment I'm unsure what to wrap the hook in, in order for it to function as expected.
I'm using react-router v6.

customHook:
```
export const useCustomSearchParams = () => {
  const [searchParams, setSearchParams] = useSearchParams();

  const updateSearchParams = (newSearchParams = {}, clearSearchParams = []) => {
    const searchParamsObject = {};
    for (const [key, value] of params.entries()) {
      searchParamsObject[key] = value;
    }

    clearSearchParams.forEach((key) => delete searchParamsObject[key]);

    setSearchParams({
      ...searchParamsObject,
      ...newSearchParams,
    });
  };

  return [searchParams, updateSearchParams];
};
```

test:
```
import { renderHook, act } from '@testing-library/react-hooks';
import { BrowserRouter } from 'react-router-dom';
import { useCustomSearchParams } from './useCustomSearchParams';

it('should add new params', () => {
  const wrapper = ({ children }) = <BrowserRouter>{children}<BrowserRouter />
  const { result } = renderHook(() => useCustomSearchParams(), { wrapper });

  act(() => {
    result.current[1]({ foo: 'bar' });
  });

  expect(mockSetSearchParams).toHaveBeenCalledWith({
    foo: 'bar',
  });
});
```

This works as far as I can tell but I don't know how to reset the url before each test. So tests after this one will contain `foo=bar`.

**Comment by tomasfrancisco** [comment]
@benskz Have you got around this issue? I'm facing similar issue.
I need to be able to see what's in the URL history, but since routes only get created in the wrapper, it's hard to have access to the history outside renderHook.

**Comment by benskz** [comment]
@tomasfrancisco  I'm afraid I eventually gave up on this one as I could not solve the described issue.

**Comment by InnaVS** [comment]
@benskz, @tomasfrancisco  for me changing "BrowserRouter" -> "MemoryRouter" solved the issue.

**Comment by mostopalove** [comment]
@benskz , @tomasfrancisco Did you manage to solve this issue?
Solution of @InnaVS doesn't work for me
