### ISSUE TITLE
https://reactrouter.com/ unavailable

### ISSUE THREAD

**Issue by OperKH** [ReactTraining/react-router#7760]
https://reactrouter.com/ can be reached only via IPv6 and unavailable via IPv4

My ISP doesn't provide IPv6 and the site is unavailable for me ~1 month.
I set up IPv6 tunnel and see that it became available.

**Comment by timdorr** [comment]
I just tried over IPv4 and IPv6 and both work for me. Might be something with your connection to Cloudflare? Not really an issue for the library, though.

**Comment by lytvynenkosv** [comment]
@OperKH Looks like there is some problem with accessing it from Ukraine. Works fine when VPN is used.

**Comment by iliatcymbal** [comment]
For some reason `reactrouter` uses the same IP as casino `championslots.online` which is blocked in Ukraine.

**Comment by timdorr** [comment]
The site uses CloudFlare, so they have the same IPs as many other sites. Those are AnyCast IPs, so they will route to whatever is the closest POP for your area. They are not unique, but they do have different pairs for different sites that they host.
