### ISSUE TITLE
[v5] Link Component Prop breaks navigations

### ISSUE THREAD

**Issue by aburkowsky9** [ReactTraining/react-router#7761]
## Version
v5.2.0

## Test Case

https://codesandbox.io/s/react-router-forked-3vbpe?file=/index.js

## Steps to reproduce
In the test case:
Click on the `Link` with the text: "Lets wrap about some children"
<img width="293" alt="Screen Shot 2021-02-03 at 9 48 58 AM" src="https://user-images.githubusercontent.com/38677277/106787921-1f3ea180-6605-11eb-8d10-d0a048884ec0.png">

Only the `/about` Link has been passed a custom component.

## Expected Behavior
Passing in a custom component to the component prop of the Link component provides the same navigation experience as the the Link component without the component prop (changes the url path to the route and doesnt refresh the entire page).
## Actual Behavior
Passing a custom component to the component prop of the Link component breaks navigation when the Link component is clicked. The DOM will still render the `Route` pointed to by the `to` prop, but it **causes a page refresh and the address bar does not update the path.**

I expect this has to do with a `navigate` method being passed to the custom component, but not being called within the custom component as it is in the default `LinkAnchor` component: 

https://github.com/ReactTraining/react-router/blob/ebd1528bafebd81ca9b813f722c8f1368bb57e7e/packages/react-router-dom/modules/Link.js#L43

https://github.com/ReactTraining/react-router/blob/ebd1528bafebd81ca9b813f722c8f1368bb57e7e/packages/react-router-dom/modules/Link.js#L101

It is not clear from the react-router doc site that this is a necessary step. I would prefer that the onus of calling `navigate` does not fall on the custom component as a concern for component libraries that should not be aware of React Router

**Comment by MeiKatz** [comment]
That is not a bug. We do some special event checking in the Link component. Just copy the event handling from there and use it in your custom link component.

**Comment by aburkowsky9** [comment]
@MeiKatz @timdorr  I understand that is an option. Should this be a bit more clear in the documentation?

**Comment by webbower** [comment]
@MeiKatz I would argue "look at the source" is not developer friendly documentation, especially when you don't even have a link in the docs to the relevant code to mimic. Plus, [the docs for the RR Link](https://reactrouter.com/web/api/Link/component-reactcomponent) actually misrepresent how to integrate a custom component, since the RR `Link` component feeds a non-standard `navigate` prop which doesn't actually enable the SPA navigation functionality given the example code in the docs by spreading `props` onto the custom component. The `Link` component would need to pass a crafted `onClick` prop that calls `navigate()` internally for the doc example to work.

So even if this is by design, the support/docs for how to use a custom component with RR `Link` is flat out inaccurate and unhelpful. At the very least, an update to the docs would be good. Even better would be to provide an HOC that would do this baseline SPA navigation connection that could also be used to potentially replace the `AnchorLink` component with `hoc('a')` that would take the `navigate()` prop and craft the custom `onClick` prop to call `navigate()` internally so that you could more easily do:

```jsx
import { Link, withReactRouterNavigation } from 'react-router-dom';
import MyLink from './path/to/my-link.jsx';

const CustomLink = withReactRouterNavigation(MyLink);

return <Link href="..." component={CustomLink}>Click Me</Link>;
```

**Comment by MeiKatz** [comment]
@webbower I didn't say I support the current solution. I just told the current situation.

**Comment by webbower** [comment]
@MeiKatz So the call is to leave this closed (cc @timdorr) and treat this as a wontfix even though it could just be a doc change to fix? The current documentation led my team to abandon using the RR `Link` component and to instead manually recreate this functionality using `<a href="#!" onClick={(ev) => { props.history.push(...); ev.preventDefault(); }}>` all over our project (before I joined).

**Comment by juanfabrega** [comment]
Hi -- I'd like to mention our team has run into this exact issue, and we based a component around the existing docs, which produced this same "hard refresh" issue when navigation is triggered with a custom component.

In an ideal world our component library would be 100% unaware of react-router and the `component` prop would work transparently (with RR Link component passing what it needs via prop spread). Given that this is not the case, is there no other solution than to copy and paste RR onclick handling code into our component?
 
This seems highly brittle and creates a dependency on RR implementation when RR isn't even a dependency in our library at all.

If there are any other solutions, we'd love to continue this discussion. Thanks for all the hard work!

**Comment by MeiKatz** [comment]
@juanfabrega I think a good solution would be to put the RR behaviour in a separate function and export it. Then everybody could use the same behaviour if needed. But this will only be the case for RRv6 or if we ship a minor version of RRv5 supporting it. I don't know, what do you think, @timdorr?

**Comment by aburkowsky9** [comment]
An alternative solution were debating is using a polymorphic component where the RR Link is passed into an `as` prop:
https://www.benmvp.com/blog/polymorphic-react-components-typescript/

Codesandbox with example: https://codesandbox.io/s/react-router-forked-b35cq?file=/index.js

**Comment by MeiKatz** [comment]
Something like this:
```jsx
function buildOnClickHandler({
  target,
  navigate,
  onClick
}) {
  return function onClick( event ) {
    try {
      if ( onClick ) onClick( event );
    } catch ( ex ) {
      event.preventDefault();
      throw ex;
    }

    if (
      !event.defaultPrevented && // onClick prevented default
      event.button === 0 && // ignore everything but left clicks
      ( !target || target === "_self" ) && // let browser handle "target=_blank" etc.
      !isModifiedEvent( event ) // ignore clicks with modifier keys
    ) {
      event.preventDefault();
      navigate();
    }
  };
}
```
And used like this:
```jsx
const FancyLink = React.forwardRef(( props, ref ) => {
  const onClick = buildOnClickHandler( props );

  return (
    <a ref={ ref } { onClick } { ...props }>💅 { props.children }</a>
  );
});

<Link to="/" component={ FancyLink } />
```

**Comment by MeiKatz** [comment]
@aburkowsky9 I don't think that it matters if the prop is called `component` or `as` – it does the same. Also not sure if we should swap the inner and the outer component.

**Comment by aburkowsky9** [comment]
@MeiKatz in the isomorphic example (`CustomLink`) you are correct. We can call the prop whatever we want. The `as` prop defaults to an anchor tag, but the option to pass in the RRLink is available. In this case we can use the RRLink without its `component` prop to accomplish the same goal.

`
const CustomLink = React.forwardRef(({ children, as: Component = 'a', ...anchorAttributes }, forwardedRef) => {
  return (
    <Component ref={forwardedRef} {...anchorAttributes}>
      <p>Lets wrap</p>
      {children}
      <p>some children</p>
    </Component>
  )
})

function App() {
  return (
    <Router>
      <div>
        <ul>
          <li>
            <Link to="/">Home</Link>
          </li>
          <li>
            <CustomLink as={Link} to="/about">
              About
            </CustomLink>
            {/* <Link to="/about" component={CustomLink}>
              About
            </Link> */}
          </li>
          <li>
            <CustomLink href="/about">About default anchor reload page</CustomLink>
          </li>
          <li>
            <Link to="/topics">Topics</Link>
          </li>
        </ul>

        <hr />

        <Route exact path="/" component={Home} />
        <Route path="/about" component={About} />
        <Route path="/topics" component={Topics} />
      </div>
    </Router>
  )
}

`

**Comment by MeiKatz** [comment]
@aburkowsky9 Yeah, I got what you mean in the first place, but I don't think that `as` should be a property of `CustomLink` but of `Link` itself. Anyway, your solution should work for now.

**Comment by juanfabrega** [comment]
Hi @MeiKatz and @aburkowsky9. First off, thanks so much for the quick response!

For the time being, I have used the solution proposed initially and also expanded upon here: 
https://github.com/ReactTraining/react-router/issues/7761#issuecomment-789086353

In terms of future API development for this, personally the polymorphic component looks pretty great, although it seems to break with the existing API, no? 

Is there a reason why Link can't use the `onClick` exposed by the custom component to fire off the navigate method? I expect I'm missing something basic here.

My component is working now, so thanks again! would love to see this piece of info make it into the docs. If you would like I can submit a PR for this change. Let me know.

**Comment by httpete** [comment]
> @aburkowsky9 Yeah, I got what you mean in the first place, but I don't think that `as` should be a property of `CustomLink` but of `Link` itself. Anyway, your solution should work for now.
This worked for me, StyledLink is my Styled-component.

```const RouterLink: React.FC<LinkProps & ICustomLinkProps> = (props) => {
  return (
    <StyledLink as={Link} {...props}>
      {props.children}
    </StyledLink>
  );
};```
