### ISSUE TITLE
New route is mounting before previous route unmounts

### ISSUE THREAD

**Issue by nelsonchen90** [ReactTraining/react-router#7762]
## Version

**5.2.0**
**4.3.1**

## Test Case

https://codesandbox.io/s/react-router-basic-forked-ioc7u?file=/example.js:2209-2229

## Steps to reproduce

Home component is being used in both the Home (as the root component to route) and About component (as a child)

- turn on console
- click Home link to go to home
- click on 'about' link to go to about
- see the console.

## Expected Behavior

the first Home component should be unmounted first before the second Home component (from About) is mounted (render)

## Actual Behavior

The component (Home 2) for the next route is mounted before the component (Home 1) from the previous route is unmounted

**Comment by timdorr** [comment]
That's not what I'm seeing:

```
home will unmount, id: 1
home did mount, id: 2
about did mount 
```

Even then, this is out of scope for React Router. This is just the semantics of how React renders. We don't have any control over that.

**Comment by nelsonchen90** [comment]
@timdorr Thanks for the quick review!

I want to clarify the actual behavior:

The first line: the 'home 2' renders first. Then the 'home 1' unmounts, following with 'home 2' did mount is called.
```
Home render, id 2
home will unmount, id: 1
home did mount, id: 2
about did mount 
```

So you are saying react-router doesn't control when the next route will mount and the previous route got destroyed/unmounted?

**Comment by timdorr** [comment]
Yeah, we don't control that. That's just the normal React lifecycle. It does renders first and then changes mounts.
