### ISSUE TITLE
[v6-beta.0] Plus sign (+) in URL path gets decoded into space

### ISSUE THREAD

**Issue by darrentorpey** [ReactTraining/react-router#7765]
## Version

`v6.0.0-beta.0`

## Test Case

https://codesandbox.io/s/react-router-600-beta0-2n4ut

## Steps to reproduce

https://user-images.githubusercontent.com/50610/107079246-90c15000-67bd-11eb-96bd-3596a9ca135d.mov

## Expected Behavior

`+` is a valid character (not an encoding) for pathname of URL, as referenced here: https://stackoverflow.com/a/1006074 and by Michael Jackson for past versions of this library here: https://github.com/ReactTraining/react-router/issues/716#issuecomment-71346876

## Actual Behavior

`+` character in pathname is turned into ` ` (space character)

This is breaking our existing valid URLs that have a + in the pathname of the URL such as `/brand/abraham+ivy/` (the brand's actual name is "abraham+ivy").

## Reference

Some context that might be illuminating:

The code seems to be doing this intentionally but looks like it have have been inspired by code from an old version of this library that itself later had this behavior removed due to it being a bug:
- https://github.com/ReactTraining/react-router/commit/fbc109c0218508a301caae36469c8fc5d70de5fa
- https://github.com/ReactTraining/react-router/commit/20c2c9b6fd5797504b0ff9ba37261173a9164571

**Comment by tconroy** [comment]
Thanks for flagging this. Also an issue my team is running into with v6. It's forcing us to change our pathing structure, unfortunately.

**Comment by brookslybrand** [comment]
Looking back through the commit history, I couldn't find a good reason why the `.replace(/\+/g, ' ')` was basically added back. If this was the mistake, the fix is super easy and I have a PR up for it (unless of course I'm missing something!)
