### ISSUE TITLE
[v5] <Switch> component does not give any warning about invalid children

### ISSUE THREAD

**Issue by BogdanDenis** [ReactTraining/react-router#7766]
## Version
5.2.0

## Test Case
https://codesandbox.io/s/a-simple-react-router-v4tutorial-forked-4mo5o?file=/index.js

## Steps to reproduce
1. Use `<Switch>` component
2. Define more than one route the following way:
```
<SomeWrappingComponent>
  <Route path="/some-path" component={SomeComponent} />
</SomeWrappingComponent>
```
3. Visit the first defined route and observe that it's rendered correctly
4. Visit the second defined route and observe an empty page

## Expected Behavior
Since the docs specify that only valid children of `<Switch>` are `<Route>` or `<Redirect>` I'd expect to see either an error message on screen or at least a warning in console.

## Actual Behavior
No error message or warning is given.

**Comment by timdorr** [comment]
We actually don't care if they are those types specifically. We only care about the `path` props existing on the direct children. Unfortunately, prop types have no way to represent this requirement, so we don't have a way of working around it. It's a documented thing, but isn't something we can type check.
