### ISSUE TITLE
 How to use useParams with typescript passing parameters dynamically?

### ISSUE THREAD

**Issue by Yuri-Tiofilo** [ReactTraining/react-router#7767]
In a project I used my useParams from react-router-dom. But in this case I have to create an interface to pass as parameters, is this the only way to pass this parameter?

Ex: 

````
interface PropsRoute {
  bookId?: string | undefined;
}

const { bookId } = useParams<PropsRoute>();

````

**Comment by liorbd** [comment]
The default type of ```useParams()``` return value is ```{}```, So you need to define your own type
