### ISSUE TITLE
Mocking useNavigate with jest does not work

### ISSUE THREAD

**Issue by andradaaag** [ReactTraining/react-router#7768]
## Version

"react-router-dom": "6.0.0-beta.0",
## Test Case

https://codesandbox.io/s/react-router-forked-t90r7
The sandbox doesn't properly work because `jest.mock` is still not a function (aka sandbox doesn't support it yet boo).

## Steps to reproduce
1. Create a component that uses `useNavigate` hook and make a `navigate` call inside of it.
2. Create a react-testing-library test for it and mock the hook like
```
jest.mock('react-router-dom', () => ({
    ...jest.requireActual('react-router-dom'),
    useNavigate: () => ({
        navigate: jest.fn(),
    }),
}))
```

## Expected Behavior
1. Test works and the `navigate` mock function is called.

## Actual Behavior
1. Test fails with 
```
Error: Uncaught [TypeError: navigate is not a function]
```

**Comment by timdorr** [comment]
That's an issue with Jest, not this library.

**Comment by andradaaag** [comment]
@timdorr This used to work with the `useHistory` hook and mocking the `push` method. We already had such tests which are currently working. This is why I assumed something in the router is not properly set.

**Comment by zacharytyhacz** [comment]
It is such a pain in butt to mock `useNavigate()` hook.

@andradaaag 
I asked a question on stack: https://stackoverflow.com/questions/66284286/react-jest-mock-usenavigate

**Comment by andradaaag** [comment]
Update: I was wrongly mocking the hook since it's returning a function that returns a function and not an object with the navigate property on it like I did in my example above. Here is the working code:
```
jest.mock('react-router-dom', () => ({
    ...(jest.requireActual('react-router-dom') as {}),
    useNavigate: () => jest.fn(),
}))
```
