### ISSUE TITLE
Error on react-router webpage while loading sandox

### ISSUE THREAD

**Issue by ipsum13** [ReactTraining/react-router#7776]
The following error is showing on react-router webpage while loading any [sandbox.](https://reactrouter.com/web/example/basic)

TypeError
_interopRequireDefault is not a function

evaluate
/index.js:9

// If you experience any struggles with this sandbox, please raise an issue
on github. :)

import React from 'react';
import ReactDOM from 'react-dom';
import App from './example';

View compiled

**Comment by timdorr** [comment]
Appears to be working now.
