### ISSUE TITLE
Include react-router-hash-link in react-router

### ISSUE THREAD

**Issue by kokushkin** [ReactTraining/react-router#7780]
Hi. I think it would be super useful to include https://github.com/rafgraph/react-router-hash-link functionality into this repository (copy and paste). So Link and NavLink components would be able to support # refs
`<Link to="/some/path#with-hash-fragment">Link to Hash Fragment</Link >`
I was super confused to know that React-Router can't handle this yet.

I'd like to describe my situation better. We have our internal library that extends functionality of React-Router by adding localization feature to the references. So, instead of `Link` we use `LocalizedLink` to have refs like /en/sdasdas.
Well, now,  I need to add some # refs, but because React-Router doesn't support it, our library doesn't support it as well.

Other people may have similar use cases and after all, as I understand it, React-Router was meant to cover all what regular <a> refs can do. If so, then it should be included to avoid other confusions.
I'd like to implement it if it's supported.

**Comment by timdorr** [comment]
This is really functionality that should live elsewhere. It's not so much that React Router doesn't support hash links, but more that the content for the hash is generally not available in the browser when it would scroll to it, as React hasn't rendered it yet. That's not really React Router's domain, as we just care about mapping URLs to component trees and not the states of those components.

The core of React Router should definitely _allow_ this kind of behavior, but shouldn't support every bit of functionality or use case as a built-in. We let others add it in so differing use cases can be handled in more specific ways. Trying to apply a one-size-fits-all approach in the core of the library isn't likely to make some people happy.

**Comment by kokushkin** [comment]
Hi! Yes, I see your point, one-size-fits-all is definitely a bad thing. At the same time one-size-undercover-some-basics also seems like an opposite extreme. The right answer somewhere in the middle as usual I think. Imagine you would have two types of <a> tags to cover "regular" and hash refs, would it be better?

> ... we just care about mapping URLs to component trees ...

well, hash is a part of the URL standard. 

>  generally not available in the browser when it would scroll to it,

hm..if it's not available, then why the hash ref should be available at the moment?
What's an example of what you've described? A long list of elements with the hash refs between them? So, lets say, we have a hash ref in one of the first elements which points out at one of the last elements (that hasn't been uploaded yet)? Is this the case? 
Ok,,then.. maybe it's possible to pass a callback to upload the element  when the ref is clicked.

Well, ok, I'll do my workaround anyway, maybe I'll figure out something and bring it back) I can't use HashLink straight away though, as I described, so I have to something else.
