### ISSUE TITLE
Could issue #4407 receive a status update for documentation purposes?

### ISSUE THREAD

**Issue by bluenote10** [ReactTraining/react-router#7783]
Issue #4407 has been closed ~4 years ago with the [statement](https://github.com/ReactTraining/react-router/issues/4407#issuecomment-284949808):

> closing, we know people want suggestions on how to do this, and we've got plans to make a big fatty demo of the different approaches. I'll make sure to come back here and post it when its done.

Perhaps I'm blind, but I've been searching around a lot and I couldn't find out how #4407 has been resolved eventually. Since such issues serve as documentation themselves (it's the best resource Google has returned for me), it would nice to post a short status update / link to a solution.

Apologies in advance if this isn't actually a "documentation bug" but blindness on my part...

**Comment by timdorr** [comment]
Because of how v4 and beyond has been architected, this isn't really possible by the library anymore. Nor is it how much of the React ecosystem has moved (see SWR). So, plans changed and there is no plan to make that demo anymore.

**Comment by bluenote10** [comment]
:+1: thanks for the clarification! I'll have to think about the implications...

Would it be possible to post that short info on the issue? I spend 2 hours re-reading the issue comments, reading the docs, git grepping the repo, reading source code, cross checking with dozen of (outdated) SO questions, because the way the issue reads it clearly sounded like there must be a solution by now and I'm missing it. Handling async route switching seems to be an obvious problem, so I'm most likely not the last person confused by the lack of documentation / status update. Unfortunately due to the way the locking works, it doesn't even link your clarifying post there :disappointed: .
