### ISSUE TITLE
npm i react-router-dom --save found 0 vulnerabilities

### ISSUE THREAD

**Issue by nickbenz007** [ReactTraining/react-router#7784]
Hello Everyone,
So finally I am really really annoyed by this issue which occurred on Dated: 5th-March-2020 and I have been following all those pages which contains piece of info regarding ( npm i react-router-dom --save ) and I couldn't resolve this. Heads up to me especially regarding resolving I have done the following:- Removing of Node js from control panel and then installing again, removing of Node Modules and re-installing them again, even though, I tried npm audit, npm audit fix. You name it and so on but nothing helped..!
Now kindly and I am humbly requesting if there is anyone in this world can solve this issue I am so much frustrated and I don't know what to say anymore..
NOTE: it has been 8 months that I am using REACT and I am kind a newbie so apologies in advance if I mis-understood..!

**Comment by timdorr** [comment]
This has nothing to do with React Router.
