### ISSUE TITLE
[v6] PartialRouteObject is not exported from 'react-router-dom'

### ISSUE THREAD

**Issue by minvedacat** [ReactTraining/react-router#7786]
## Version

6.0.0-beta.0

## Test Case

https://codesandbox.io/s/react-router-forked-iz735

## Steps to reproduce

1. import { PartialRouteObject } from 'react-router-dom'
2. PartialRouteObject is not exported

## Expected Behavior

``` tsx
import { Navigate, useRoutes, PartialRouteObject } from 'react-router-dom';

const someRoutes: PartialRouteObject[] = ...
const otherRoutes: PartialRouteObject[] = ...
```

## Actual Behavior
```sh
Module '"../../../node_modules/react-router-dom"' 
has no exported member 'PartialRouteObject'
```

**Comment by timdorr** [comment]
That is exported from `react-router`.
