### ISSUE TITLE
Redirect component crushes on using search query params

### ISSUE THREAD

**Issue by ikondrat** [ReactTraining/react-router#7790]
## Version

5.2.0

## Test Case

https://codesandbox.io/s/react-router-dom-issue-klph9

## Steps to reproduce

Click on **Redirect me with param from gtagjs**

## Expected Behavior
Redirect to /test with params from the link

## Actual Behavior
TypeError
Expected "1" to be defined

**Comment by timdorr** [comment]
The `to` prop, when a string, is a pathname. To do that with the search, you need to redirect to a location object: `to={{pathname: testRoute, search: window.location.search}}`

**Comment by ikondrat** [comment]
@timdorr Does it mean the documentation is wrong?
https://reactrouter.com/web/api/Redirect/to-string
`The URL to redirect to. Any valid URL path that path-to-regexp@^1.7.0 understands. All URL parameters that are used in to must be covered by from.<Redirect to="/somewhere/else" />
`

**Comment by ikondrat** [comment]
@timdorr shall I create PR to update the wrong documentation?

**Comment by ikondrat** [comment]
Ahh  I see 
Thanks for the explanation
