### ISSUE TITLE
Unbound methods from history prop used in react-router Link and Redirect components

### ISSUE THREAD

**Issue by aldexis** [ReactTraining/react-router#7795]
## Version

5.2.0

## Test Case

https://codesandbox.io/s/react-router-forked-x8xt9?file=/index.js

## Steps to reproduce

- Define a custom `History` implementation that calls `this` in its `push` or `replace` method
- Pass in an instance of that History implementation to `Router`
- Go through either a `Link` or a `Redirect`

## Expected Behavior

We should get to the targeted page.

## Actual Behavior

The router fails when trying to call its unbound `replace` or `push` method due to `this` being `undefined` (or `window` in the above code example).

I believe we should add `method = method.bind(history)` to https://github.com/ReactTraining/react-router/blob/22bd7fb4fbeccc0cb573088b5bfaf1bec0dc7bf9/packages/react-router/modules/Redirect.js#L20-L22 and https://github.com/ReactTraining/react-router/blob/22bd7fb4fbeccc0cb573088b5bfaf1bec0dc7bf9/packages/react-router-dom/modules/Link.js#L102-L105 ?

**Comment by timdorr** [comment]
That seems to be relying on a particular implementation. That's now how `history` works internally, so it's not something we're going to add.
