### ISSUE TITLE
Catch All Route doesn't show when using children prop and navigating to a non-index route

### ISSUE THREAD

**Issue by AquaDuck1** [ReactTraining/react-router#7797]
## Version

**6.0.0-beta.0**

## Test Case

https://codesandbox.io/s/jolly-shadow-c3v95?file=/src/App.js

## Steps to reproduce

Create a catch route all using `children` to render a component when the route is matched:

```jsx
(
  <Route path="*">
    <div>Catch All</div>
  </Route>
)
```

Navigate to any non-index route, like `/non-existent-route`.

## Expected Behavior

"Catch All" is shown.

## Actual Behavior

Nothing is shown.

## Other

If you provide the `element` prop instead of `children`, it works as expected:

```jsx
(
  <Route
    path="*"
    element={<div>Catch All</div>}
  />
)
```

"Catch All" is shown.

**Comment by timdorr** [comment]
I'm not sure what you're reporting. This is just the API in v6. Route doesn't render children.

**Comment by AquaDuck1** [comment]
> Route doesn't render children

But I've demonstrated in my code example that it does render children:

```jsx
(
  <Route path="/login">
    <div>Login</div>
  </Route>
)
```

It just doesn't do so when using a catch all path.

I see in the API docs that you can nest a `<Route>` inside of another `<Route>` so that's where my confusion stemmed from. This must be used for another purpose that I'm not up to speed on yet.

My bad! Appreciate the quick response, I'll make sure to use `element` instead for this purpose.
