### ISSUE TITLE
Percent-encoding parameters inside the URL path - newer version of history should be used

### ISSUE THREAD

**Issue by phuhl** [ReactTraining/react-router#7799]
## Version

react-router-dom@^5.1.2
react-router@5.2.0

## Test Case

https://codesandbox.io/s/react-router-forked-wr782?file=/index.js
(uncomment the appropriate function to test the different configuration)

## Steps to reproduce

Push a url like this: `history.push(decodeURIComponent("abc%"))` or like this `history.push("abc%")`

## Expected Behavior

In at least one case the % sign should be url encoded.

## Actual Behavior

In neither case the % is encoded, which leads to a crash further down the line, when react-router tries to decode the URI.

Previously, it has been stated, that this is an underlying problem of the history package. In history version 5 there is a fix available now. It should be fixable in this package, too, I guess.

Previous issues: https://github.com/ReactTraining/react-router/issues/7612, https://github.com/ReactTraining/react-router/issues/7225, https://github.com/ReactTraining/react-router/issues/5824

**Comment by timdorr** [comment]
History v5 is used in v6, which is still in beta. This I was already fixed for the next major release. 

We can't port back v5 because the changes are too substantial and would require a major revision.

**Comment by phuhl** [comment]
Ok, thanks, didn't know that.
