### ISSUE TITLE
Is React Router maintained ?

### ISSUE THREAD

**Issue by Aarbel** [ReactTraining/react-router#7802]
Looks like Pull request and many issues are not treated since 7/8 months.

Do React Router administrators need help ? 

![image](https://user-images.githubusercontent.com/25119847/112665979-f34cd900-8e5b-11eb-9d08-dacc839918fc.png)

**Comment by timdorr** [comment]
See #7613

**Comment by Aarbel** [comment]
@mjackson i'm sure many developers would be thrilled to maintain this lib. 

Can you open it to other maintainers ?
