### ISSUE TITLE
When using history.replace() to a different URL parameter on the same page, the function component's outer method is not re-executed.

### ISSUE THREAD

**Issue by ericlee33** [ReactTraining/react-router#7804]
## Version

**Please replace this sentence with the React Router version that you are using.**

## Test Case

https://codesandbox.io/s/react-router-gh6n7

## Steps to reproduce
https://codesandbox.io/s/crazy-wildflower-ci1re?file=/src/Foo.js

Click the button, and looking at console.log, the method bar was not retriggered. Why?
## Expected Behavior
The Bar function should be executed again.
## Actual Behavior
When I clicked the button to navigate to the same page but with different URL parameters using history.replace(), the function bar on the outer layer of the function component wasn't re-executed. I don't want to trigger the Bar function in the function component. How can I avoid this problem?

**Comment by timdorr** [comment]
This is just how ES Modules work. Modules are only ever imported and executed once. This has nothing to do with React Router or even React itself.
