### ISSUE TITLE
Sending Function to another Router using Link

### ISSUE THREAD

**Issue by umerjaved178** [ReactTraining/react-router#7813]
## Version

latest version

## Test Case

https://codesandbox.io/s/blazing-resonance-qgi2m?fontsize=14&hidenavigation=1&theme=dark&file=/src/Header.js

As mentioned in the Documentation that we can send data as props using 'state' to another route. But we can't send functions as props if we will send function using 'state' it will give an error

## Expected Behavior
We should pass function using 'state' 
## Actual Behavior
It is giving error as shown in Test case

**Comment by timdorr** [comment]
The `state` field on a Location should be serializable. E.g., it should be the same content when you do `JSON.parse(JSON.stringify(state))`. You cannot send complex objects or functions via `state`.

**Comment by umerjaved178** [comment]
Then how can we achieve this functionality? How can we send function to other route
