### ISSUE TITLE
Component does not render only after reloading it for the second time.

### ISSUE THREAD

**Issue by slim-hmidi** [ReactTraining/react-router#7814]
## Version

**react-router-dom:** 5.2.0
**history:** 5.0.0

## Steps to reproduce
```ts
import React from 'react';
import {Route, Router} from 'react-router-dom';
import CircularProgress from '@material-ui/core/CircularProgress';
import App from './App';
import SignIn from 'features/authentication/signIn/SignInContainer';
import SignUp from 'features/authentication/signUp/SignUpContainer';
import history from 'browserHistory/index';
const Root = (): JSX.Element => (
    <Router history={history}>
      <Route exact path="/" component={App} />
      <Route exact path="/signin" component={SignIn} />
      <Route path="/signup" component={SignUp} />
    </Router>
);

export default Root;
```
## Expected Behavior
The homepage should display the content of the App page if user signed in otherwise redirects to signin page.
## Actual Behavior
The url of signin page displayed but I got a blank page, when I reload I got the component displayed.

## More
if I change Router ot BrowserRouter, the app works well however I'm not able to use `history.push()` when I call it from redux files.

**Comment by slim-hmidi** [comment]
there is an issue with history v5.0.0
Downgrading to v4 fixed the problem.

**Comment by chrisbag** [comment]
I have been struggling with redirect for a couple of hours trying to understand why the url was indeed changed but the component not rendered.

Downgrading to history v4 did the trick.
Thanks for the solution

**Comment by VladRDV** [comment]
version 5.3.0, this still happens
