### ISSUE TITLE
React | TypeError: Cannot read property 'location' of undefined

### ISSUE THREAD

**Issue by josefernandoperezgarcia1998** [ReactTraining/react-router#7815]
HEEEELP
I wanna do a simple navbar with React

I install "npm install --save react-router-dom"

![image](https://user-images.githubusercontent.com/66925963/113489102-5d2e3980-947f-11eb-82fb-790fd3cd2228.png)
![image](https://user-images.githubusercontent.com/66925963/113489113-6c14ec00-947f-11eb-9e4d-709824f6a736.png)
![image](https://user-images.githubusercontent.com/66925963/113489121-7800ae00-947f-11eb-906e-19279ef208e2.png)
![image](https://user-images.githubusercontent.com/66925963/113489126-8353d980-947f-11eb-9761-c277bce12a08.png)

**Comment by MeiKatz** [comment]
You use <Router /> instead of <Route />
