### ISSUE TITLE
useParams returns an empty object in unit tests

### ISSUE THREAD

**Issue by Mikilll94** [ReactTraining/react-router#7817]
I have noticed that in unit tests, `useParams` hook always returns an empty object. Here is my unit test:
```js
test('renders learn react link', () => {
  render(
    <MemoryRouter initialEntries={['/person/2']}>
      <Person />
    </MemoryRouter>
  );
  const labelElement = screen.getByText(/Person id: 2/i);
  expect(labelElement).toBeInTheDocument();
});
```

As you can see, in my test I have set the initial route to '/person/2'.

If you run the repro project below:
```
yarn
yarn dev
```
and go to this address: http://localhost:3000/person/2, you should see the label: "Person id: 2". Thus, when the app is running `useParams` works fine. But in unit tests it always returns an empty object.

## Version

5.2.0

## Test Case

Here is the repro project:
[react-router-repro.zip](https://github.com/ReactTraining/react-router/files/6271485/react-router-repro.zip)

## Steps to reproduce

1. Run tests
```
yarn
yarn test
```
2. Test is failing because `useParams` returned an empty object:
![Screenshot 2021-04-07 at 14 14 35](https://user-images.githubusercontent.com/17653648/113864765-95998480-97ab-11eb-95f2-253c0f02fe62.png)

## Expected Behavior
`useParams()` hook in unit tests should return url params.

## Actual Behavior
`useParams()` hook in unit tests returns an empty object.

**Comment by timdorr** [comment]
You have no `<Route>` defined anywhere. You've defined no params for `useParams` to extract.

**Comment by dezoito** [comment]
@Mikilll94 , were you able to get your tests running?

I am having similar issues, even though my tests have a `<Route>` defined
