### ISSUE TITLE
path-to-regexp dependency

### ISSUE THREAD

**Issue by meijintao233** [ReactTraining/react-router#7819]
## Version

master branch

## Steps to reproduce
packages/react-router/modules/matchPath.js
packages/react-router/modules/generatePath.js

## Expected Behavior
import { pathToRegexp } from 'path-to-regexp'

## Actual Behavior
import pathToRegexp from 'path-to-regexp'

**lib path-to-regexp  export several functions without export default**

**Comment by timdorr** [comment]
We are locked to a 1.x version of path-to-regexp. Make sure you're not installing a newer version.
