### ISSUE TITLE
Can't resolve 'history' in 'C:\Users\.\.\.\node_modules\react-router'

### ISSUE THREAD

**Issue by rohan9896** [ReactTraining/react-router#7820]
## Version
React router v6.0.0beta
**Please replace this sentence with the React Router version that you are using.**

## Test Case

https://codesandbox.io/s/react-router-gh6n7

## Actual Behavior
My react app is not building

**Comment by timdorr** [comment]
This has nothing to do with React Router.

**Comment by DavidOnGitHub** [comment]
You need to install history separately. https://github.com/ReactTraining/react-router/releases/tag/v6.0.0-beta.0
