### ISSUE TITLE
BrowserRouter basename value not updated on all links

### ISSUE THREAD

**Issue by andriichern** [ReactTraining/react-router#7823]
## Version

5.2.0

## Steps to reproduce
Could be found following the link: https://codesandbox.io/s/react-router-forked-tckzd
Example is simple but clearly demonstrate the problem.

## Expected Behavior
All links href value are respected to match actual `basename`.

## Actual Behavior
BrowserRouter do not change nested links' urls in case of dynamic `basename`.
In the test case link there is a case when `basename` is dynamic to represent different languages of an app. Current language is stored as a state. If you change click on another language app itself displaysa correct one, but all links are contain the same old `basename` value.

Currently as a workaround it is possible to manually refresh the page with `window.location.reload()` but I do not think it is an actual an expectd behaviour.

**Comment by timdorr** [comment]
`basename` is not intended to propagate. It emulates the HTML `<base name>` tag, which also does not update throughout the document when changed.

**Comment by andriichern** [comment]
Ok, it is clear, but why we can not use it in dynamic nature? If we update state of our app it re-renders - why this emulation could not accept cnahge in `basename` value? if it only emulates `<base>` tag and not impacts it...
