### ISSUE TITLE
No matching version found for chalk@4.1.1

### ISSUE THREAD

**Issue by JotSinghChawla** [ReactTraining/react-router#7826]
I was installing a react-router-dom package in my new React Project and it shows an error stating :
`No matching version found for chalk@4.1.1 in react router dom`

**Comment by JotSinghChawla** [comment]
I was just installing react router dom package in my New React Project and it was the first thing I installed. So idk why I am getting this error. Also I check the chalk version with npm view chalk. And it show latest version is 4.1.0

**Comment by timdorr** [comment]
We don't use chalk anywhere except our website, which isn't a public package. Something else is going on with your build setup.

**Comment by JotSinghChawla** [comment]
Yes, I got the issue now. It's with the NPM, As Chalk just published its new package hour ago.
