### ISSUE TITLE
history.listen fired after componentDidMont of it's children component

### ISSUE THREAD

**Issue by YagamiNewLight** [ReactTraining/react-router#7829]
The router's subscription to the history comes before yours, so React is getting priority. This is expected. If you don't want this behavior, make your own instance of history, subscribe to it first, and then pass it to a plain Router instance.

_Originally posted by @timdorr in https://github.com/ReactTraining/react-router/issues/6525#issuecomment-449979641_

**Comment by timdorr** [comment]
I'm not sure what you're asking here, but this isn't a bug report or feature request.

**Comment by YagamiNewLight** [comment]
Apologize if I was not doing it incorrectly. 

But basically, I ran into the same problem where you provided a solution(your comment in the issue des),  

After following your solution, the history.listen fired indeed BEFORE the componentDidMont of its children component, BUT the hisotry.listen NOT fire anymore when navigating between the children component.(see the reproduce link I provided)

Thanks in advance.

**Comment by YagamiNewLight** [comment]
I open a[ StackOverflow question](https://stackoverflow.com/questions/67249479/history-listen-doesnt-fire-as-i-expected), could you please help me? @timdorr
