### ISSUE TITLE
[v6] Link does not have `as` prop

### ISSUE THREAD

**Issue by nuanyang233** [ReactTraining/react-router#7832]
^6.0.0-beta.0

## Expected Behavior
https://github.com/ReactTraining/react-router/blob/dev/docs/advanced-guides/migrating-5-to-6.md#rename-link-component-to-link-as-and-navlink-exact-to-navlink-end

As stated in the documentation, `Link` components should have `as` prop that allow us to change the corresponding component type
## Actual Behavior

https://github.com/ReactTraining/react-router/blob/dev/packages/react-router-dom/index.tsx#L166

`Link` does not have `as` prop

**Comment by chaance** [comment]
This is by design, but we plan on providing a different low-level API that will allow you to render links as you see fit.

**Comment by mjackson** [comment]
We already do provide `useNavigate` and `useHref`, so I think this just needs to be documented to show people how to use them to create their own links.

```tsx
function CustomLink({ to }) {
  let href = useHref(to);
  let navigate = useNavigate();

  function handleClick() {
    navigate(href);
  }

  return (
    <MyLink onClick={handleClick}>
      click me
    </MyLink>
  )
}
```

**Comment by graup** [comment]
But Link and NavLink to some additional stuff that would be annoying to replicate by hand. How about providing a use{Nav}Link hook that returns all the props that Link/NavLink generates?

**Comment by KingSora** [comment]
In case you're still interested in assing this functionality, I've created a small react component which does exactly this: https://github.com/KingSora/react-as you can also try it in the playground here: https://stackblitz.com/edit/react-as-playground?file=Link.tsx
