### ISSUE TITLE
[v6] calling `navigate()` in componentDidMount via HOC wrapper over useNavigate is not working

### ISSUE THREAD

**Issue by piecyk** [ReactTraining/react-router#7833]
## Version

6.0.0-beta.0

## Test Case

In this example we are wrapping `useNavigate` hook with HOC for class components. 

```jsx
const withNavigate = (Component) => (props) => <Component navigate={useNavigate()} {...props} />
```

https://codesandbox.io/s/react-router-v9yq1

## Steps to reproduce

Click on `About` link 

## Expected Behavior

Should navigate `/home`

## Actual Behavior

When `navigate` is called in componentDidMount, warning is thrown
```
You should call navigate() in a useEffect, not when your component is first rendered. 
```
 and navigation is skipped.

This is happening because of `activeRef` check in `navigate`. Overall componentDidMount will be called before the `useEffect` making the activeRef.current still false https://github.com/ReactTraining/react-router/blob/dev/packages/react-router/index.tsx#L422

**Comment by timdorr** [comment]
This isn't a bug, it's expected behavior. We have that check specifically to prevent this kind of usage, as it causes issues with CM/Suspense and infinite loops in your code. You should not be navigating from cDM and I would recommend against mixing hooks with class components.

**Comment by piecyk** [comment]
Thanks @timdorr for explaining, also did check the https://github.com/ReactTraining/react-router/commit/cbcd398276efaad31e5e994fdb2f80ca454eb859 👍 

As fully agree that calling navigate in render phase is wrong, bit wondering why calling it from cDM should be also 🤔  Imho would throw the warning and still call navigate 😉

**Comment by rommeras** [comment]
This is weird to prevent navigating in cDM and allowing in useEffect, this is basically the same
