### ISSUE TITLE
Add meta field in Route

### ISSUE THREAD

**Issue by toinbis** [ReactTraining/react-router#7834]
https://router.vuejs.org/guide/advanced/meta.html is very useful for setting meta information for route, for instance, Sidebar title or event page title.

Could this be added in react router v6?

Thanks!

**Comment by timdorr** [comment]
We don't have a centralized route configuration like Vue Router, so that kind of thing wouldn't apply. You can pass in that info as a prop on your components within the `element` prop.

**Comment by liho98** [comment]
> We don't have a centralized route configuration like Vue Router, so that kind of thing wouldn't apply. You can pass in that info as a prop on your components within the `element` prop.

when i useEffect watch the location.pathname in root app, how do i get the element props that i pass into the component??????

please reopen this issue, thanks.
