### ISSUE TITLE
[v6] - No way to disable outlet

### ISSUE THREAD

**Issue by cnkt** [ReactTraining/react-router#7835]
I believe there should be a way to disable outlet usage for some routes even if they are nested.

Is it possible? I read all the docs but couldn't find a way.

Thanks.

**Comment by shulcsm** [comment]
What do you mean by "disable" outlet. You have to render it for it to be "enabled".

Default element for Route is <Outlet /> you can just pass in something to override. Similar with things that call `createRoutesFromArray`.

**Comment by cnkt** [comment]
There is a tabbed interface in my app. Let's assume the links as follows:

/car/:car_id
/car/:car_id/details
/car/:car_id/damages
/car/:car_id/photos

There is a CarLayout component and all sub pages open in an Outlet component in CarLayout. But i want the Photos page to open in full page, not in the Outlet of CarLayout.

**Comment by webholics** [comment]
I am facing the exact same problem and don't know how to solve it currently.
