### ISSUE TITLE
Switch & 404 Not Working w/ config map

### ISSUE THREAD

**Issue by grumpyTofu** [ReactTraining/react-router#7839]
## Version

"react-router-dom": "^5.2.0"

## Test Case

https://codesandbox.io/s/react-router-gh6n7

## Steps to reproduce

This works:

```
<Router>
  <Layout>
    <Switch>
      <Route exact path="/">
        <Counter />
      </Route>
      <Route path="*">
        <NotFound />
      </Route>
    </Switch>
  </Layout>
</Router>
```

This does not work:

```
export interface RouteConfig {
  path: string;
  exact: boolean;
  component: React.FC;
}

const routeConfig: RouteConfig[] = [
  {
    path: '/',
    exact: true,
    component: Counter,
  },
];

const App: React.FC = () => {
  return (
    <Router>
      <Layout>
        <Switch>
          {routeConfig.map(route => (
            <Route
              exact={route.exact}
              component={route.component}
              key={`Route_${route.path}`}
            />
          ))}
          <Route path="*">
            <NotFound />
          </Route>
        </Switch>
      </Layout>
    </Router>
   );
}
```

## Expected Behavior

Navigating to anywhere besides "/", should show a NotFound page

## Actual Behavior

Counter component is shown at every route

**Comment by ultralabsgev** [comment]
I don't know why (I have the same problem, it's just not render other components besides '/' component), but I fix it just rename "/" path and it starts working

it was

`const routeMap = [
  {
    path: '/',
    render: () => <Dashboard />,
  },
  {
    path: '/e',
    render: () => <E />,
    children: [
      {
        path: '/e/:id',
        renderComponent: () => <ED />,
      },
    ],
  },
 ] `
 it become
 `const routeMap = [
  {
    path: '/xz',
    render: () => <Dashboard />,
  },
  {
    path: '/e',
    render: () => <E />,
    children: [
      {
        path: '/e/:id',
        renderComponent: () => <ED />,
      },
    ],
  },
 ] `
