### ISSUE TITLE
I want to see all my history paths or at least the last path

### ISSUE THREAD

**Issue by KevinSabetay3345** [ReactTraining/react-router#7842]
This would be a feature more than an issue.
I need to see what my last path was to know what to do next.
I know there is a function with history.goBack() but I just need the string, not a function.
Thanks!

**Comment by timdorr** [comment]
This is a limitation of the DOM History API. You cannot read previous URLs from the history, only navigate to them. 

You may be able to store the history changes using `history.listen()`, but that would be up to you to implement.
