### ISSUE TITLE
expose LinkAnchor

### ISSUE THREAD

**Issue by KutnerUri** [ReactTraining/react-router#7844]
I'm trying to use a custom underlying `<a/>` tag, like `<Link component={CustomAnchor}/>`.
I can make my own component, but I see a lot of logic in the [original LinkAnchor](https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/modules/Link.js).

So, I think LinkAnchor should be made public, and exported from `react-router-dom`.
Is this possible? I could make PR if needed.

### Types 
```ts
type ReactRouterLinkProps = {
  /** @deprecated */
  innerRef?: any;
  navigate: () => void;
};
type LinkAnchorProps = ReactRouterLinkProps & React.AnchorHTMLAttributes<HTMLAnchorElement>;

declare const LinkAnchor: FC<LinkAnchorProps>;
```

**Comment by timdorr** [comment]
Duplicate of #7727
