### ISSUE TITLE
Support for redirect in react-router-config

### ISSUE THREAD

**Issue by SimonChaumet** [ReactTraining/react-router#7845]
Using react-router-config does not allow to redirect without creating a component.

It could be really great to implement it without creating a component.

I wanted to have a static config to render my app in server side in the future but I didn't saw a react-router-config@v6 neither a static config in reach router, is the static config going to be deprecated in the future ?

**Comment by timdorr** [comment]
Yes, we don't have any plans to include it in v6. I would recommend finding an alternative library.

**Comment by SimonChaumet** [comment]
@timdorr It could be great to add a warning at the beginning of the readme in react-router-config or in "the future of react router"
