### ISSUE TITLE
v5/v6 feature req: strongly typed mocks for RouteComponentProps

### ISSUE THREAD

**Issue by diracs-delta** [ReactTraining/react-router#7850]
Hi there. Like many users of `react-router`, I'd like to use this in a production-scale app that requires best practices like TypeScript and unit testing. The problem is that injected `RouteComponentProps` are difficult to mock and require a lot of boilerplate to do so. This makes testing any component that uses injected `RouteComponentProps`, say a `BlogPage` that reads the `id` from the URL, more difficult than it should be. See below:

https://stackoverflow.com/questions/46927392/how-to-test-a-react-component-with-routecomponentprops

Do strongly typed testing utility functions like the solution above have a place here in the `react-router-dom` codebase? I think it would be a nice addition that does not impact current users, and covers a commonly-needed use case with modern development practices.

BTW, I haven't really been keeping up with v6 development, so forgive me if this is already solved in v6 and I just need to be more patient. However, if it isn't implemented in v6 yet either, I'd be happy to contribute with a maintainer's approval and guidance. 👍

**Comment by timdorr** [comment]
We don't want to be prescriptive about test utilities, because there are many systems for testing. It's best to leave that to third-party libraries, which can focus on a particular combination of tools, frameworks, and code patterns.
