### ISSUE TITLE
[V5] Cannot scroll to top.

### ISSUE THREAD

**Issue by nyngwang** [ReactTraining/react-router#7854]
The following doesn't work, I've read all answers on stackoverflow: https://stackoverflow.com/questions/36904185/react-router-scroll-to-top-on-every-transition, this is a bug, please fix.

```
import {useEffect} from "react";
import {useRouteMatch} from "react-router-dom";

export const ScrollToTop = () => {
    const {path} = useRouteMatch()

    useEffect(() => {
        console.log("path =", path)
        window.scrollTo(0, 0)
    }, [path])

    return null
}
```

**Comment by Shivani-kumari** [comment]
> The following doesn't work, I've read all answers on stackoverflow: https://stackoverflow.com/questions/36904185/react-router-scroll-to-top-on-every-transition, this is a bug, please fix.
> 
> ```
> import {useEffect} from "react";
> import {useRouteMatch} from "react-router-dom";
> 
> export const ScrollToTop = () => {
>     const {path} = useRouteMatch()
> 
>     useEffect(() => {
>         console.log("path =", path)
>         window.scrollTo(0, 0)
>     }, [path])
> 
>     return null
> }
> 
this solution is not working in web app
