### ISSUE TITLE
useParams does not fully work when Route has an array of path's

### ISSUE THREAD

**Issue by Ed-Ed** [ReactTraining/react-router#7856]
## Version

^5.2.0

## Test Case

https://codesandbox.io/s/lucid-keldysh-yewiz

## Steps to reproduce

Have an array of paths in `Route` in a `Switch`:

```
<Route path={["/", "/:id"]}>
    <Component />
</Route>
```
if you try to navigate to `/123` for example, when using the params hook: `useParams`, id will be undefined.

If you swap `"/"` and `"/:id"` in the array, it will work.

## My Expected Behavior

No matter the order of the array, it should pickup all the params.

Is this expected?

**Comment by timdorr** [comment]
Using an array for your paths is really just a hack to support path-to-regexp's array support. It's not recommended for reasons such as this. This is an expected bug.

**Comment by Ed-Ed** [comment]
@timdorr what is the recommended approach? Would it be this?

```
<Route path="/">
    <Component />
</Route>

<Route path="/:id">
    <Component />
</Route>
```

**Comment by timdorr** [comment]
Yep. You can `.map` over an array of paths to put out multiple `Route`s as well, if you prefer the old style.
