### ISSUE TITLE
URI encoding

### ISSUE THREAD

**Issue by Bacto** [ReactTraining/react-router#7867]
Hi,

It seems that the Link component from react-router-dom doesn't encode the URI.

When using `<Link to={'test-"quotes"'}>`, the HTML result is `test-&quot;quotes&quot;`.
AFAIK, the result should be `test-%22quotes%22`.
This is the result we get with `<a href={encodeURI('test-"quotes"')}>`.

I tried to manually encode the URI with `<Link to={encodeURI('test-"quotes"')}>` but still, the result is `test-&quot;quotes&quot;`.

Did I missed something or there is, as I think, something wrong here?

Tested with the latest version (5.2.0).

**Comment by timdorr** [comment]
ReactTraining/history#745
