### ISSUE TITLE
Fortify Security Scan Critical Finding: Hardcoded Encryption Key

### ISSUE THREAD

**Issue by jstrong62** [ReactTraining/react-router#7871]
## Version

6.14.11

## Test Case

A complete security scan in Fortify (by MicroFocus).

## Steps to reproduce

N/A

## Expected Behavior

Zero critical or high security findings.

## Actual Behavior

One critical finding found of type **Hardcoded Encryption Key**

react-router/cjs/react-router.js

`790: var key = "__react_router_build__";`

Details from Fortify:

Hardcoded encryption keys can compromise security in a way that is not easy to remedy.

Encryption keys should never be hardcoded and should be obfuscated and managed in an external source. Storing encryption keys in plain text anywhere on the system allows anyone with sufficient permissions to read and potentially misuse the encryption key.

**Comment by timdorr** [comment]
This is a false positive. This isn't an encryption key.
