### ISSUE TITLE
about useHistory from react-router-dom some problem

### ISSUE THREAD

**Issue by FlyFishCode** [ReactTraining/react-router#7872]
is me use error？
why history is undefined,i want to user history.push()

https://codesandbox.io/embed/react-router-v5-starter-forked-zn0dm?fontsize=14&hidenavigation=1&theme=dark

**Comment by myNameIsDu** [comment]
The Router component must be wrapped in an outer layer

**Comment by myNameIsDu** [comment]
You have to wrap the Router component in the outer layer. Now that it's in the App component, you can try it by moving the UseHistory component to the About component

**Comment by FlyFishCode** [comment]
ok，i'll try

**Comment by FlyFishCode** [comment]
Thank you, it has been resolved. Can help me find documentation about useHistory api. I can't find it in'react-router-dom'
