### ISSUE TITLE
react-router v6 There is a problem with useNavigate

### ISSUE THREAD

**Issue by CGSimplePeople** [ReactTraining/react-router#7882]
baseName is invalid  
Routes basename='/Web/Work'
use useNavigate for routing redirection, without secondary routing
current route  http://localhost/Web/Work/Home
use useNavigate jump to “Login”，route becomes http://localhost/Login

**Comment by myNameIsDu** [comment]
use navigate('../Login')

**Comment by CGSimplePeople** [comment]
I tried this once，but the route jump became  http://localhost/Web/login
I think ‘..’ just let the routing jump to the upper level

**Comment by adamfriedland** [comment]
Is there any update regarding this issue? I've currently encountered the same issue.
