### ISSUE TITLE
When creating multiple Routes with a map function the same component always re-renders

### ISSUE THREAD

**Issue by ilyador** [ReactTraining/react-router#7883]
v 5.2.0

When creating multiple Routes with a `map` function, the same component always re-renders, although the docs say that using the same component on multiple routes should not trigger an unmount.

Switching between pages 1 and 2 (generated by map) always unmounts them, whereas switching between 3 and 4 does not.
What is even weirder is that it is the `key` prop that is somehow related, when it is removed, the unmounting does not happen anymore.

```js
const privatePages = [
  {
    path: '/page1',
    component: <Page num='1' />
  },
  {
    path: '/page2',
    component: <Page num='2' />
  }
]

function Page({ num }) {
  useEffect(() => {
    console.log(`page ${num} mount`)
    return () => { console.log(`page ${num} unmount`) }
  }, [])

  return <div>page {num}</div>
}

export default function App() {
  return (
    <Router>
      <Switch>
        {privatePages.map((page, index) => (
          <Route key={index} path={page.path}>
            {page.component}  // <===================== Unmounts each time switching between 1 and 2
          </Route>
        ))}

        <Route path='/page3'>
          <Page num='3' />   // <====================== No unmounts between 3 and 4
        </Route>
        <Route path='/page4'>
          <Page num='4' />
        </Route>
      </Switch>
    </Router>
  )
}
```
Working example: [https://codesandbox.io/s/jolly-wave-g1g82?file=/src/App.js:0-1399](https://codesandbox.io/s/jolly-wave-g1g82?file=/src/App.js:0-1399)

**Comment by ilyador** [comment]
I think it is a bug since what make the difference is the 'key' prop, and I don't see a way it can be a React or simply a usage issue.

**Comment by carvallegro** [comment]
Hey @ilyador Have you tried using the `page.path` as key? It is a much more unique key than the element's place in the index.
