### ISSUE TITLE
Question: How can I view files inside cjs folder? Thank you

### ISSUE THREAD

**Issue by learnuidev** [ReactTraining/react-router#7888]
https://github.com/ReactTraining/react-router/blob/fc91700e08df8147bd2bb1be19a299cbb14dbcaa/packages/react-router-dom/index.js#L6

**Comment by pshrmn** [comment]
This folder is created when bundling the package for release. You can see it in your `node_modules` or browse it on [unpkg](https://unpkg.com/browse/react-router-dom@5.2.0/cjs/).
