### ISSUE TITLE
Activating/Deactivating BrowserRouters

### ISSUE THREAD

**Issue by LoganDark** [ReactTraining/react-router#7891]
My last issue #7889 was immediately closed as a support issue, so now I'm opening a dedicated feature request for this functionality. Don't worry, this is not a request for support.

I would like the ability to enable/disable `BrowserRouters` so that they _remember their current path_, but don't update the browser URL or listen for changes on the browser URL. When enabling a `BrowserRouter`, the browser's URL will immediately update and it will begin listening for changes again.

This could possibly be done with a `disabled` prop, but I don't know if that's the best name for it. The router would still work, it just would only be navigable by links/programmatically and wouldn't be linked to the browser's address bar.

My use case for this is having multiple sections where each one has its own router and remembers the last path you visited if you momentarily visit another section.

This could also be implemented a lot of other ways; since you closed my issue without looking at it, I was not able to have any discussion about how this could be best done (my issue was not just a support request). Perhaps a different solution would be to let some `Route`s remember their path when they no longer match.

**Comment by timdorr** [comment]
You can do this with a plain `<Router>` component and a custom [history](https://github.com/ReactTraining/history/tree/v4). Just switch between a memory history and a browser history as needed. Or chain them together with a `listen` on the memory history that selectively updates the browser history. This isn't something we would build into the core of the library.

**Comment by LoganDark** [comment]
> You can do this with a plain `<Router>` component and a custom [history](https://github.com/ReactTraining/history/tree/v4). Just switch between a memory history and a browser history as needed. Or chain them together with a `listen` on the memory history that selectively updates the browser history. This isn't something we would build into the core of the library.

Alrighty, thanks for the info. I'll see what I can do.

**Comment by LoganDark** [comment]
Thank you, it worked! It was a lot of manual work, but here's what I did:

- Manually made a BrowserHistory in `index.ts` and passed it to `App`
- Made MemoryHistories for each section's Router and added a listener to each one that updates the BrowserHistory if it's the current section
- Added a listener on the BrowserHistory that changes section / updates the respective section's MemoryHistory on page load & if it's changed by something other than the MemoryHistory listener (to prevent infinite loops)

Now, each section's complete route is preserved when switching between them and everything, exactly what I needed. I'm still just as bad as ever at explaining things, but your comment was just what I needed @timdorr :)
