### ISSUE TITLE
[v5] Different behavior between redirection and user operation when browser back 

### ISSUE THREAD

**Issue by utakatano** [ReactTraining/react-router#7892]
## Version

**5.2.0**

## Test Case

Created an example using the below code.
About Home.tsx, it has 2 approaches for user to transition to `/about`
 - auto redirection ( `<Redirect />` )
 - user intentional transition ( `<Link>` )

**App.tsx**

```tsx
import React from 'react'
import { BrowserRouter, Switch, Route } from 'react-router-dom'
import { About } from './pages/About'
import { Home } from './pages/Home'

const App: React.FC = () => {
  return (
    <BrowserRouter>
      <Switch>
        <Route path='/about'>
          <About />
        </Route>

        <Route path='/'>
          <Home />
        </Route>
      </Switch>        
    </BrowserRouter>
  )
}

export default App
```

**Home.tsx**

```tsx
import React, { useEffect, useState } from 'react'
import { Link, Redirect } from 'react-router-dom'

export const Home: React.FC = () => {
  const [isRedirect, setIsRedirect] = useState(false)

  useEffect(() => {
    const timer = setTimeout(() => {
      setIsRedirect(true)
    }, 5000)

    return () => {
      clearTimeout(timer)
    }
  }, [])

  if (isRedirect) {
    return <Redirect push to='/about' />
  }

  return (
    <div>
      <h2>Home</h2>
      <Link to='/about'>Go To About</Link>
    </div>
  )
}
```

## Steps to reproduce

**Redirect**

1. Please open a new tab and navigate to `http://localhost:3000/` (Home)
2. Wait for about 5 seconds (it goes to About page)
3. Use browser back (press back button)

**Link**

1. Please open a new tab and navigate to `http://localhost:3000/` (Home)
2. Click "Go To About" ( `<Link />` )
3. Use browser back (press back button)

## Expected Behavior

In the step 3, the above 2 results should be same (it should be Home page)

## Actual Behavior

**Redirect**

new tab page (before navigate to Home in the step 1)

**Link**

Home page

For your information, it can reproduce when your use `history.push` instead of Redirect

```tsx
  useEffect(() => {
    const timer = setTimeout(() => {
      history.push('/about')
    }, 5000)

    return () => {
      clearTimeout(timer)
    }
  }, [])
```

How could I resolve this ?

**Comment by timdorr** [comment]
I wasn't able to reproduce this: https://codesandbox.io/s/react-router-forked-mou81

Sounds like something outside of the library is going on. Either with your app or your browser setup.

**Comment by utakatano** [comment]
@timdorr 

Thank you for your confirmation ~
But I can reproduce it in your example (it works well in code sandbox).

Open chrome browser and navigate to https://mou81.csb.app/

**Comment by timdorr** [comment]
I'm not seeing it there at all. It's got to be something with your browser (an extension possibly?).
