### ISSUE TITLE
Property 'goBack' does not exist on type 'History<any>'. Did you mean 'back'? 

### ISSUE THREAD

**Issue by chilupa** [ReactTraining/react-router#7893]
I was trying to use `goBack()` function of useHistory hook provided by `react-router-dom`. It shows the below error.

```
Property 'goBack' does not exist on type 'History<any>'. Did you mean 'back'?
```

I'm using React with TypeScript.

**Versions**
```
"react-router": "^5.2.0",
"react-router-dom": "^5.2.0",
```

**Sample Code**

```
  import { useHistory } from 'react-router-dom'

  const history = useHistory()

  const handleRoute = () => {
    history.goBack()
  }
```

**Comment by timdorr** [comment]
Make sure you have a 4.x version of History installed. React Router 5.x is only compatible with History 4.x.
