### ISSUE TITLE
[v6] Element from useRoutes does not work as child of <Route />

### ISSUE THREAD

**Issue by rediska1114** [ReactTraining/react-router#7898]
## Version
```
"react-router": "^6.0.0-beta.0",
"react-router-dom": "^6.0.0-beta.0",
```
## Test Case

https://codesandbox.io/s/react-router-forked-ou7yr?file=/index.js

## Steps to reproduce

1. Click on "Dashboard" link or click on "Dashboard Test" link

## Expected Behavior

Pages "Dashboard" and "Dashboard test" are rendered.

## Actual Behavior

Pages mentioned above aren't rendered.

P.S. If we uncomment lines with nested `<Route />`, rendering works as expected.

This bug blocks the migration of our large-scale project to v6

**Comment by timdorr** [comment]
In v6, you need to use the `element` prop, not children. This will work:
```js
<Route path="*" element={<DashboardRoutes />} />
```

**Comment by rediska1114** [comment]
In `element` I want to use layout component with `<Outlet />` inside, and declare all routes in `children`. It does work with `<Route />` elements in `children`. Why can't I do the same thing with `useRoutes`?

**Comment by timdorr** [comment]
`useRoutes` is just returning a single element, not a `<Route>`. So it has none of the capabilities or context of a `<Route>`. It's meant to mirror the functionality of react-router-config.
