### ISSUE TITLE
Search parameters are not kept in the URL

### ISSUE THREAD

**Issue by hornta** [ReactTraining/react-router#7900]
## Version

5.2.0

## Test Case
https://codesandbox.io/s/vigilant-shockley-2pbl4?file=/src/App.js

## Expected Behavior
I expect my URL to contain both `foo` and `bar` with a value of test.

## Actual Behavior
The URL contains only `bar`

## Comments
What's interesting here is that when I switch from using the `useLocation` hook to window.location then it works as expected. I created a working example here: https://codesandbox.io/s/recursing-mahavira-63ttp?file=/src/App.js

**Comment by timdorr** [comment]
This isn't an issue with React Router, it's an issue with React itself. You have two competing useEffects that are both attempting to mutate a common state (from useLocation) independently of each other. There's no way for us to know you're using a stale bit of state elsewhere in your render function.

**Comment by jeremyckahn** [comment]
I'm running into a similar issue on my project. Would it be reasonable to access `window.location` directly instead of the object returned from `useLocation()` to avoid these sorts of issues?
