### ISSUE TITLE
[v6] Incorrect Link Route

### ISSUE THREAD

**Issue by charlesomer** [ReactTraining/react-router#7901]
## Version

6.0.0-beta.0

## Description

I have an array of markdown files which are being fetched and then rendered by react. As part of this process, these pages have relative links to each other which react router should be creating and linking accordingly however links within those pages seem to act one level deeper than they should.

For example:
`example.com/file1` has a link to `file2` but instead of linking to `example.com/file2` it navigates to `example.com/file1/file2`.

I have tried to reproduce this manually using a basic setup but this doesn't seem to have the same issue.

Are there any restrictions/known issues when autogenerating Routes that I've perhaps missed which could be causing this? I'm going to keep trying to work out why this is happening but I'm running out of ideas... :)

**Comment by charlesomer** [comment]
Extra note: I'm _not_ using nesting of `<Route />`, rather I'm just setting the `path` prop to whatever the absolute path is.

**Comment by charlesomer** [comment]
Here's a snippet from my setup which produces the issue for me.

```
  useEffect(() => {
    setRRPages([
      <Route path='test1' element={<RRLink to='test2'>LINK1</RRLink>} />,
      <Route path='test2' element={<RRLink to='test1'>LINK2</RRLink>} />,
    ])
  }, [])

  return (
    <ThemeProvider theme={theme}>
      <CssBaseline />
      <Grid container spacing={2} justifyContent='center' paddingX={2}>
        <Grid item xs={12} sm={10} md={8}>
          <Routes>
            {RRPages}
          </Routes>
        </Grid>
      </Grid>
    </ThemeProvider>

```

**Comment by timdorr** [comment]
```js
      <Route path='test1' element={<RRLink to='test2'>LINK1</RRLink>} />,
      <Route path='test2' element={<RRLink to='test1'>LINK2</RRLink>} />,
```
The `Link` elements in this case are being rendered under the context of the `Route` they are contained within, so they are treated as relative to their parent paths. You need to set `to="/test1"` to make them non-relative.

**Comment by charlesomer** [comment]
Great okay thank you. How does this work for links like the following: `/../../page`? I'm generating pages based on markdown documents and the pages links are all relative to each other. Adding `/` during the page generation _seems_ to work but it also causes weird rendering resulting in react router thinking the page hasn't been found temporarily.

As a side note, perhaps it would be good if React Router had the option to link to pages in the same way the `<a>` tags work which would avoid this

**Comment by charlesomer** [comment]
Never mind, I think the weird 'not found' stuff is because of something else I'm doing. The `/../../page` still seems like the wrong way to go about this though?
