### ISSUE TITLE
[Bug]: useLocation's pathname and useRouteMatch's url are working differently

### ISSUE THREAD

**Issue by eakl** [ReactTraining/react-router#7905]
### What version of React Router are you using?

6.0.0-beta.0

### Steps to Reproduce

With React-Router v5: https://codesandbox.io/s/async-microservice-9fc6h?file=/src/App.js
With React-Router v6: https://codesandbox.io/s/xenodochial-cori-g9gxc?file=/src/App.js

useRouteMatch's url and useLocation's pathname are working differently. If this is expected, I apologies. But I can't find match.url is React Router v6 or an equivalent.

### Expected Behavior

Let's say `<Component />` loads at `/home`.

In React Router v5, **url** will be `/home`.
On click,  a new URL will be pushed: `/home/modal` and the modal will open.
On cancel, `/home` will be pushed and the modal will close.
It works as expected

```javascript
export const Component = () => {
  const { url } = useRouteMatch()
  const history = useHistory()

  const onClick = () => {
    history.push(`${url}/modal`)
  }
  
  const onCancel = () => {
    history.push(`${url}`)
  }

  return (
      <button onClick={onClick}>Open Modal</button>
      <Route path={`${url}/modal`}>
        <Model
          onCancel={onCancel}
          ...
        />
      </Route>
  )
}
```

### Actual Behavior

In React Router v6, **pathname** url will be `/home`.
On click,  we navigate to `/home/modal` and the modal will open.
On cancel, the pathname will now be `/home/modal` and the modal will never close.

I am not sure whether it is an issue of `pathname` and `url` not working the same way or `history.push` vs `navigate`. 

```javascript
export const Component = () => {
  const { pathname } = useLocation()
  const navigate = useNavigate()

  const onClick = () => {
    navigate(`modal`)
  }
  
  const onCancel = () => {
    navigate(`${pathname}`)
  }

  return (
      <button onClick={onClick}>Open Modal</button>
      <Route path={`modal`} element={
        <Model
          onCancel={onCancel}
          ...
        />
      } />
  )
}
```

**Comment by timdorr** [comment]
v6 routing is relative. So, you want this:

```js
  const onCancel = () => {
    navigate(`..`) // navigate up one level
  }
```

**Comment by eakl** [comment]
@timdorr but how about having nested routes in the modal?

You still need access to the current absolute matched url because whether you are at

ˋ/home/modal/ˋ
ˋ/home/modal/tab2ˋ
or
ˋ/home/modal/tab2/subtab3ˋ

when you close the tab you should come back to ˋ/homè and not necessarily 1 step behind (i.e ˋnavigate('..')ˋ)

How to you handle such situation with relative path?
