### ISSUE TITLE
[v6] Server side rendering support

### ISSUE THREAD

**Issue by aneurycasado** [ReactTraining/react-router#7911]
### What version of React Router are you using?

6

### Steps to Reproduce

Is there any documentation on server-side rendering with react-router v6? I am currently going through this guide:
https://morioh.com/p/995f1244f33b

and have encountered this error:

`TypeError: a.replace is not a function`

when removing context from the StaticRouter. 

I also can't seem to find any updated docs for server side rendering with react router v6. These are the current docs:
https://reactrouter.com/web/guides/server-rendering

which still use context.

### Expected Behavior

To not experience any bug after removing context from StaticRouter

### Actual Behavior

ReactDOMServer.renderToString throws an error.

**Comment by myNameIsDu** [comment]
@aneurycasado   I can try to find the problem for you, but I need an example from you :smiley:

**Comment by chaance** [comment]
Hey @aneurycasado, if you can provide a minimal reproduction, perhaps in a test repo, I'll be happy to re-open this. All docs for v6 are a work-in-progress, but you can find them here on GitHub for now on the `dev` branch: https://github.com/ReactTraining/react-router/blob/dev/docs/

The specific doc I think you're looking for is on migrating from 5 to 6: https://github.com/ReactTraining/react-router/blob/dev/docs/advanced-guides/migrating-5-to-6.md

Let me know if you still have any issues. Others may be able to help as well, but without some reproduction for us to spot the error it's very difficult to diagnose and point to any specific solutions.
