### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by stesvis** [ReactTraining/react-router#7912]
### What version of React Router are you using?

5.0.2 ("latest")

### Steps to Reproduce

Create a brand new app:
`npx create-react-app react-demo`

Add a simple navigation and routes:
```
import "./App.css";

import { Link, Route, BrowserRouter as Router, Switch } from "react-router-dom";

import AboutPage from "./AboutPage";
import HomePage from "./HomePage";
import logo from "./logo.svg";

function App() {
  return (
    <div className="App">
      <header className="App-header">
        <img src={logo} className="App-logo" alt="logo" />
        <Router>
          <nav>
            <ul>
              <li>
                <Link to="/">Home</Link>
              </li>
              <li>
                <Link to="/about">About</Link>
              </li>
            </ul>
          </nav>

          <Switch>
            <Route path="/about">
              <AboutPage />
            </Route>
            <Route path="/">
              <HomePage />
            </Route>
          </Switch>
        </Router>
      </header>
    </div>
  );
}

export default App;
```

1. On local server, everything works (`npm start`)
2. Deploy the app (I did on Ubuntu and IIS to compare)
2. Browse the app
3. Switch between **Home** and **About** (works)
4. When you are on the **About** page (`/about`) click the reload button in the browser
5. It throws a 404 error (by IIS or apache/nginx)

### Expected Behavior

React should just reload the sub-routes when you click on the menu AND when you type the url directly.

### Actual Behavior

Reloading a page in a sub-route like `/whatever` throws a 404.

Example: https://portal.levitica.ca/

**Comment by pshrmn** [comment]
You need to configure your server to serve the app's `index.html` for all possible URLs. I go into it a bit in the `Serving Single-Page Applications from Configurable Static Servers` section in [this blog post](https://blog.pshrmn.com/single-page-applications-and-the-server/).
