### ISSUE TITLE
[Bug]: v6 wildcard doesn't appear to work

### ISSUE THREAD

**Issue by Zashy** [ReactTraining/react-router#7916]
### What version of React Router are you using?

v6 beta

### Steps to Reproduce

Create a simple project that does like:
```
<BrowserRouter>
  <Routes>
    <Route path='a'><div>Hello</div></Route>
    <Route path='*'><div>World</div></Route>
  </Routes>
<BrowserRouter>
```

Then go to https://localhost:8080/b

Here, I tried making a code sandbox... not that it appears to be working right now... https://codesandbox.io/s/react-router-forked-drsl3?file=/package.json

I'm trying to migrate an app that was using a wildcard to match when no other pages matched in v5. And it doesn't appear to work anymore, and I can't find anything documented about how to migrate successfully.

### Expected Behavior

It renders a page that says 'World'

### Actual Behavior

It renders a blank page

**Comment by renatobenks** [comment]
I didn't get that @Zashy, because I checked your codesandbox and it seems to be working 🤔 

It was missing rendering a `<Routes />` there. Once you do that, probably will gonna wok

**Comment by timdorr** [comment]
You need to move from the Route's `children` to the `element` prop, as per the migration guide.

**Comment by Zashy** [comment]
Um so use children. But `<Route><Element /></Route>` is children. You mean move them back up to a prop called `element` I guess. Okay that seems to work, though confusing migration guide since it says using React's children is fine, but now it's not.

Thanks I guess, must use element. Solution below:

```
<BrowserRouter>
  <Routes>
    <Route path='a' element={<div>Hello</div>} />
    <Route path='*' element={<div>World</div>} />
  </Routes>
<BrowserRouter>
```

**Comment by renatobenks** [comment]
yeahh, I just forgot, `children` was removed a few time ago 🤔 

someone's need to update that in v6 documentation
