### ISSUE TITLE
[Bug]: v6: useMatch in a nested routes context is not relative

### ISSUE THREAD

**Issue by tommie-lie** [ReactTraining/react-router#7920]
### What version of React Router are you using?

6.0.0-beta.0

### Use case
One of the great new benefits of v6 is the [new nested routing mechanism](https://reacttraining.com/blog/react-router-v6-pre/#relative-route-path-and-link-to) which allows thinking of individual components as small apps being wired together.
However, when using `useMatch` in such a nested context, I have to pass the complete location path to `useMatch`, not just the path inside my "little world".

My use case is a component that renders a sub-menu with a bunch of links to different nested routes inside that component. I can tell the menu (which is a third party component) which item is to be highlighted, hence I want to get access to the currently rendered nested route without having to know the complete pathname to my component.

### Steps to Reproduce

* Create a component that is rendered in a route (e.g. the Topics component in this expression `<Route path="/topics/*" element={<Topics />} />`.
* Let the component render another `<Routes>` component with a bunch of routes that match the above parent route.
* Use a `useMatch` hook relative to the parent route (e.g. `useMatch(":topicId")`).

There is a CodeSandbox which is based on the v5 version of the nested routes example here: https://codesandbox.io/s/react-router-nesting-forked-qxzh4?file=/example.js:911-1103

### Expected Behavior

The `useMatch(":topicId")` in [example.js:56](https://codesandbox.io/s/react-router-nesting-forked-qxzh4?file=/example.js:989-1041) should match and return the current topic in the params.

[The tentative API docs](https://github.com/ReactTraining/react-router/blob/7b326f5e5d0262eef0f98097384241eb070a9c39/docs/api-reference.md#usematch) also indicate that matching should be done relative to the current location (although being imprecise on the wording).

### Actual Behavior

Using the `useMatch` hook in a component that is rendered as part of a `Route` requires the full path and returns null if used relative to the currently active route.

**Comment by timdorr** [comment]
useMatch isn't intended to be used relatively. It's just a wrapper around [`matchPath()`](https://github.com/ReactTraining/react-router/blob/dev/docs/api-reference.md#matchpath) that uses the current location's `pathname` as a basis. You should either prepend the current path or use `matchPath` directly with the pathname of your choosing.

**Comment by dralletje** [comment]
If you don't mind, could you elaborate a bit on why that is?

v6 has this distinction between paths starting with a `/` and those without, baked in everywhere, but `useMatch` seems a rare exception.
Reach Router currently has it with support for relative paths, and it works perfectly.
The comment above `useMatch` refers to it being "useful for components that need to know "active" state, e.g. <NavLink>.", but as it is now, it definitely can't be used for NavLink.

Not trying to be an overly demanding open-source profiteer, but this seems like such an easy win, so I'm curious to the reasons why :)

@tommie-lie if you want to use it anyway (like I will):
```javascript
import { useMatch, useResolvedPath } from "react-router-dom";
let useRelativeMatch = (path) => {
  let fullpath = useResolvedPath(path).pathname
  return useMatch(fullpath)
}
```

**Comment by tommie-lie** [comment]
Thanks @dralletje for your code snippet :-)

I was also under the impression that `useMatch` deviates from how react-router usually handles paths, hence I opened the issue. Indeed I was trying to figure out how NavLink works and why it wouldn't use useMatch. I'd be happy to work on a PR if the behaviour should actually be changed.
If this is intentional behaviour, as it seems, I would suggest changing the documentation accordingly. But from a consistency point of view I am also interested in the reasoning and the big-picture view of the API.
