### ISSUE TITLE
[Bug]: Can't provide history.goBack as a reference to a callback

### ISSUE THREAD

**Issue by gabrielsanttana** [ReactTraining/react-router#7921]
### What version of React Router are you using?

v5.2.0

### Steps to Reproduce

1. Install react-router-dom@5.2.0
2. Try to provide history.goBack method as a callback to a component
3. Run a unit test on the component
4. Check that it fails, returning the following warning: 

![image](https://user-images.githubusercontent.com/47339825/127185483-257a1ced-8496-48ef-beb7-ee86ee1a07c9.png)

### Expected Behavior

The `history.goBack` method should be called correctly, without having to wrap it inside an arrow function, for instance.

`
<button type="button" onClick={history.goBack} />
`

### Actual Behavior

`
<button type="button" onClick={() => history.goBack()} />
`

**Comment by timdorr** [comment]
You're not defining `history` anywhere. You have to have access to it in the current scope. This isn't a React Router bug.

**Comment by gabrielsanttana** [comment]
> You're not defining `history` anywhere. You have to have access to it in the current scope. This isn't a React Router bug.

I'm actually defining it, I just didn't included that in the details.

`const history = useHistory();`
