### ISSUE TITLE
[Bug]: generatePath() not working with webpack 5

### ISSUE THREAD

**Issue by donnikitos** [ReactTraining/react-router#7922]
### What version of React Router are you using?

5.2.0

### Steps to Reproduce

Set up a React project with `webpack` 5.46.0 and `webpack-dev-server` 3.11.2

use `generatePath()`

### Expected Behavior

expected to generate string

### Actual Behavior

Throws uncaught TypeError:
`path_to_regexp__WEBPACK_IMPORTED_MODULE_5___default().compile is not a function`

![image](https://user-images.githubusercontent.com/5833538/127220693-088132f4-cc6c-452a-9f50-d58c591b56d9.png)

**Comment by jonkoops** [comment]
@donnikitos I think there might be something wrong with your setup, I am running React Router on Webpack and I am not getting this issue.

**Comment by timdorr** [comment]
This isn't a bug with React Router.

**Comment by donnikitos** [comment]
@timdorr  @jonkoops 
I am slightly skeptical, since I am not the only one reporting that issue.
There is a [stackoverflow thread](https://stackoverflow.com/questions/59601757/react-router-dom-redirect-not-working-shows-error) 
also there was already an issue opened quite some time ago, see [Issue #6203](https://github.com/ReactTraining/react-router/issues/6203)

The bug might be solved by upgrading `path-to-regexp` to 2.4.0. A higher version breaks it again as it seems.

**Comment by joao-paulo-parity** [comment]
FWIW this could be happening due to another dependency which also requires path-to-regexp on another version. For me it was [koa-router](https://github.com/koajs/router/blob/90dd73c44d0e76db0890b552023711de896c12d3/package.json#L15).
