### ISSUE TITLE
[Bug]:  Prompt is not working in case of iframes with cross origin with latest google chrome version.

### ISSUE THREAD

**Issue by KaranPalan7507** [ReactTraining/react-router#7927]
### What version of React Router are you using?

5.2.0

### Steps to Reproduce

Google chrome in its latest version has removed alert, confirm and prompt from cross origin iframes.

To prevent transition to new route, react-router-dom uses Prompt component which internally is using window. confirm.
And because of which the functionality is broken.

### Expected Behavior

Any alternate way to handle prompt with custom user alert box.

### Actual Behavior

Currently nothing is happening on using prompt with cross origin iframes.
An warning is thrown in console regarding chrome's latest behavior and further details.
Refer below link for the details
https://www.chromestatus.com/feature/5148698084376576.

**Comment by timdorr** [comment]
If they've removed it for that context, there's nothing we can do. There is no alternative API for us to use.
