### ISSUE TITLE
[Bug]: Example for animated transition contains error-prone code.

### ISSUE THREAD

**Issue by tommy-josepovic** [ReactTraining/react-router#7928]
### What version of React Router are you using?

5.1.0

### Steps to Reproduce

1. Visit the [animated transition example](https://reactrouter.com/web/example/animated-transitions).
2. Repeatedly click on any of the links from the example very quickly.

### Expected Behavior

The transition between the previous page and the new page should only happen once.

The previous page should only unload once.

The new page should only load once.

### Actual Behavior

The previous page begins to unload and the new page begins to load, but the transition is interrupted, the animation from the previous page restarts and the new page reloads.

This can cause a race conditions when using the ``componentDidMount()`` and ``componentWillUnmount()`` lifecycle methods, as the components from the new page will load, unload, and reload very quickly.

It also looks wierd.

### Possible Fix

This desired behavior can be obtained by replacing the ``key`` prop of ``<CSSTransition />`` from ``key={location.key}`` to ``key={location.pathname}``. [Here is a code example](https://codesandbox.io/s/react-router-animated-transitions-forked-o58oe?file=/example.js:1237-1287) where repeatedly clickling on a link does not cause the animation to restart.

**Comment by renatobenks** [comment]
I tried to reproduce it, but I didn't catch it. I mean, I couldn't see both pages being loaded repeatedly, actually just a once each. I've seen the next page been mounted first, and right after that, the previous one been unmounted, sequencelly. Is that not right?

**Comment by tommy-josepovic** [comment]
Here's a video of what I get.

You can see that when I double click on a link, instead of there being a smooth transition from one color to the next, the transition starts, then abruptly restarts. This results in the color flashing.

https://user-images.githubusercontent.com/44372776/127690005-0b1170a8-5164-408e-9bd5-27648ea91489.mp4

**Comment by timdorr** [comment]
If you want to submit a PR to fix the example, I can get that updated. The code lives here: https://github.com/ReactTraining/react-router/tree/master/packages/react-router-dom/examples/Animation
