### ISSUE TITLE
[Feature]: 

### ISSUE THREAD

**Issue by schutzie** [ReactTraining/react-router#7930]
### What is the new or updated feature that you are suggesting?

It would be great to have a label or name property in the objects used in useRoutes().  My specific use case is for the Material UI Breadcrumbs component.  If you combine it with React Router you can make it really dynamic, but the best you can do for a breadcrumbs label would be the path.  Adding a name would be extremely helpful.

`{
    path: 'theUglyPathName',
    element: <SomeComponent />,
    label: "Home"
}`

Here's an example where Anthony Sistilli is just concatenating the "path" values.  This is where I would use a "label" value instead.

https://www.youtube.com/watch?v=n9kn8yQPC4E&t=1336s

### Why should this feature be included?

Makes the useRoutes functionality more useful for UI as well as the general route functionality.

**Comment by timdorr** [comment]
Just put it as a prop on the element: `{ path: 'theUglyPathName', element: <SomeComponent label="Home" /> }`

You can use that from within your matched component or externally by using `element.props`.

**Comment by schutzie** [comment]
Then every component has to implement and handle the props.  <ComponentA label="something" /> and <ComponentB label="something else" /> etc.  That's harder to manage long term, isn't it?  Especially if you have dozens or hundreds of routes and components.  I'm not a React expert by any means, still learning, but seems like a single attribute makes more sense.

**Comment by timdorr** [comment]
```js
const element = useRoutes(routes)
console.log(element.props.children.props.label)
```

You have to go down a level, but it's in there.

**Comment by schutzie** [comment]
There it is.  Thanks Tim.
