### ISSUE TITLE
[Bug]: Search Params are persisting on subsequent links

### ISSUE THREAD

**Issue by jefmsmit** [ReactTraining/react-router#7931]
### What version of React Router are you using?

4.3.1

### Steps to Reproduce

I have a component that creates links using `Link` from `react-routerdom` by passing a hash to the `to` property and specifying a `pathname` and a `search`. That works fine.

However other links using `Link` while they look correct when inspecting the dom end up keeping the search query string instead of clearing it. 

### Expected Behavior

I would expect the search the query string to be empty. 

### Actual Behavior

The query string specified by the search param is persistent for all subsequent links.

**Comment by jefmsmit** [comment]
It is affecting navigation behavior. In my case, I have a pagination component that puts the page number of the current view on the URL as a query parameter for bookmarking reasons. `/mylistview?page=5` for example. If you navigate to somewhere else that also supports pagination the `page=5` param follows you. So I think I'm clicking `/myotherlistview` but I'm actually going to `/myotherlistview?page-5`

**Comment by renatobenks** [comment]
I just checked your version of react-rooter, and from what I've seen, it shouldn't be happening at all. Can you show me how are you using `Link`? Maybe, I'll become clear about what's happening.

Either way, I'd recommend you to upgrade such a version of react-router, because it's too long behind, and eventually, it'll fix it, if that is even a bug.

**Comment by jefmsmit** [comment]
@renatobenks its a combination of react-router, react-router-dom and react-bootstrap. I'm using it like:
`<Pagination.Item as={Link} to="/mylistview?page=5" href="/mylistview?page=5">5</Pagination.Item>`

**Comment by renatobenks** [comment]
what about the other `Link` to `/myotherlistview` @jefmsmit? which is causing the conflict

**Comment by jefmsmit** [comment]
Those are build with react-router-bootstrap components like `LinkContainer`

**Comment by renatobenks** [comment]
Hmm, so I've seen here https://github.com/react-bootstrap/react-router-bootstrap/blob/master/src/LinkContainer.js, and here https://github.com/ReactTraining/react-router/blob/v4.3.1/packages/react-router-dom/modules/Link.js, it seems to be related in some way with `href`, did you try remove it?

**Comment by jefmsmit** [comment]
Interesting @renatobenks 
I put the href on there to fix this issue: https://github.com/react-bootstrap/react-bootstrap/issues/5948
If I remove the href, the pagination links stop working and clicking other links still propagates the query params.

**Comment by renatobenks** [comment]
I see it! Well, anyways, this issue seems to be related to `react-router-bootstrap` and not actually with this package, once this package is overriding the link behaviour through a new `href` definition
