### ISSUE TITLE
[v6]: Export RouteContext so we can forward it when using a Slot/Fill approach

### ISSUE THREAD

**Issue by jgoux** [ReactTraining/react-router#7933]
### What is the new or updated feature that you are suggesting?

Hello!

I want [`RouteContext`](https://github.com/ReactTraining/react-router/blob/8ac6777a96accd0813aae43743d9f76c95630968/packages/react-router/index.tsx#L84-L89) to be exposed so I can use it to forward the routing context when using a[ Slot/Fill](https://www.npmjs.com/package/nano-slots) approach.

### Why should this feature be included?

Right now when sending a component containing routing (like a Link) into a distant parent component, it totally loses its routing context, as it's rendered in a different branch of the react component tree. So we lose all the benefits of relative routing.

In order to "fix" that, I need to send a replica of the current routing context as well. I was able to do it with a "trick", relying on `basename` as explained [here](https://github.com/ReactTraining/react-router/pull/7462#issuecomment-893291284) and [here](https://github.com/exah/nano-slots/issues/5#issuecomment-894488463).

It's not perfect because once the `basename` bug is resolved, I won't be able to use absolute paths in these components as they will be prepended with the `basename`. Also the basename is more a workaround than a proper fix.

In order to do it correctly, I need to access the `RouteContext` directly, consuming its current value (like [this](https://github.com/ReactTraining/react-router/blob/8ac6777a96accd0813aae43743d9f76c95630968/packages/react-router/index.tsx#L507-L511)) and passing it to a new `RouteContext.Provider` (like [this](https://github.com/ReactTraining/react-router/blob/8ac6777a96accd0813aae43743d9f76c95630968/packages/react-router/index.tsx#L547-L555)).

So please, could you expose the `RouteContext`? 🙏

**Comment by timdorr** [comment]
This was already addressed in the last issue: https://github.com/ReactTraining/react-router/issues/7164#issuecomment-617562970

**Comment by jgoux** [comment]
Yes, sorry I realized a bit late that the issue was already tracked. At least, I don't think my use case was previously mentioned so this isn't totally lost. 😄 

Have a great week-end Tim!

**Comment by jgoux** [comment]
@timdorr Sorry for spamming, but I just noticed you pointed me to the `createPortal` comment.

Actually this isn't a custom portal issue here, `createPortal` won't fix anything because the `RouteContext`s are declared as children of the component where the subcomponents will be sent  (the Layout), so they aren't both children of the `RouteContext`s from a component tree structure.

Here is an example illustrating what I'm saying : https://codesandbox.io/s/vigorous-easley-q661i?file=/src/App.tsx

In this example I used the `@wordpress/component` flavour of the Slot/Fill pattern, which is using `createPortal` in its implementation.

**Comment by timdorr** [comment]
Getting access to `RouteContext` won't fix that. The instance of `<Routes>` you have under your `Screen` component will [redefine the context value](https://github.com/ReactTraining/react-router/blob/dev/packages/react-router/index.tsx#L547), so you would still get the ancestor value (which is the default coming from `BrowserRouter`). That's just how React context works, so this isn't something we can fix. You have to get your rendered components at least under the `element` prop of your Routes.

**Comment by jgoux** [comment]
I'm not sure I follow. By exposing RouteContext I will be able to create a copy of the current context as you said, then it's just of matter of wrapping the inserted components like this :

```tsx
<CopyOfRoutes>
  <Route path="*" element={props.tabs} />
</CopyOfRoutes>
```

This is exactly what I'm currently doing and it works. My only issue is that I can't make a true `CopyOfRoutes` right now and have to rely on `basename`.
