### ISSUE TITLE
[Bug]:  Migrating to useNavigate v6 from useHistory v5

### ISSUE THREAD

**Issue by JalalMitali** [ReactTraining/react-router#7940]
### What version of React Router are you using?

V6.0 0-alpha.2

### Steps to Reproduce

I am trying to make an auth system with routing and I already made one kn V5 router with useHistory hook now I want to migrate to v6 but it says  : ( cannot read property 'history' of undefined )

### Expected Behavior

I kindly want to redirect users to the previous page if they already logged in otherwise I want to keep them...

### Actual Behavior

I cant make a login system redirecting users depending on wether they are logged in or not

**Comment by timdorr** [comment]
First, you're using an outdated version of the v6 preview releases. Make sure you're on beta.0.

Without seeing how you have your code set up, it's not really possible to diagnose. But this looks like a support issue to me, not a bug in the library. Please re-read the migration guide, as those hooks have very different APIs.
